Add Motion controls
Ryujinx/Ryujinx pull request #1363
Opened 2020-07-05 12:47 UTC by emmauss

Adds support for motion controls for controllers, using the Cemu Hook Motion Provider (DSU) protocol. 

Motion source can be configured globally (the DSU options in the main input page), or specifically for each controller in their controller configuration pages. The `Enable Motion Client` checkbox globally toggles motion controls for all controllers, irrespective of what is set in each control, though when enabled, each controller can be disabled separately.
Most  controllers would only need one slot from a motion source, except Paired Joycons, which needs two motion sources. This can be 'mirrored' to allow input from only one source, or use a separate slot from the motion server.

The following places were used as reference;
https://v1993.github.io/cemuhook-protocol/
https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/issues/18
https://github.com/dekuNukem/Nintendo_Switch_Reverse_Engineering/blob/c2f5e95800288b19faff315cedfd66d9699c4b66/imu_sensor_notes.md

2020-07-07 01:22 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +
Remove extra empty line

2020-07-07 01:22 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +
Remove extra empty line

2020-07-07 01:22 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +
Remove extra empty line

2020-07-07 01:24 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/InputConfig.cs
> +        /// nable Motion Controls
```suggestion
        /// Enable Motion Controls
```

2020-07-07 01:24 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/MotionDevice.cs
> +        public MotionDevice(Client motionSource){
```suggestion
        public MotionDevice(Client motionSource)
        {
```

2020-07-07 01:24 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/MotionDevice.cs
> +            if(config != null && config.EnableMotion)
```suggestion
            if (config != null && config.EnableMotion)
```

2020-07-07 01:25 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/MotionDevice.cs
> +                if(config.ControllerType == ControllerType.JoyconPair && !config.MirrorInput)
```suggestion
                if (config.ControllerType == ControllerType.JoyconPair && !config.MirrorInput)
```

2020-07-07 01:25 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/MotionDevice.cs
> +            return value;
Add an empty line before a return

2020-07-07 01:28 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +
Remove extra empy line

2020-07-07 01:28 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +
Remove extra empy line

2020-07-07 01:29 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +
Maybe you should do something in case there is a socket error ? If not, disable the warning could be nice!

2020-07-07 01:33 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +            catch(SocketException ex)
```suggestion
            catch (SocketException ex)
```

2020-07-07 01:34 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +                if(data.Length == 0)
```suggestion
                if (data.Length == 0)
```

2020-07-07 01:35 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +                HandleResponse(data, clientId);
Disable the warning if it's not revelant to a real issue

2020-07-07 01:35 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +        public unsafe async Task HandleResponse(byte[] data, int clientId)
Disable the warning if it's not revelant to a real issue

2020-07-07 01:38 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +                                int cid = clientId;
Why you don't use `clientId` directly ?

2020-07-07 01:39 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +                    header.CRC32 = crc;
```suggestion
                    header.CRC32 = Crc32Algorithm.Compute(mem.ToArray());
```

2020-07-07 01:40 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +                    header.CRC32 = crc;
```suggestion
                    header.CRC32 = Crc32Algorithm.Compute(mem.ToArray());
```

2020-07-07 01:41 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +                if(SetSixAxisState(states[i].PlayerId, accel, gyro, states[i].Orientation))
```suggestion
                if (SetSixAxisState(states[i].PlayerId, accel, gyro, states[i].Orientation))
```

2020-07-07 01:41 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +            for(int i = 0; i < 9; i++)
```suggestion
            for (int i = 0; i < 9; i++)
```

2020-07-07 01:42 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/Types/SharedMem/Npad/SixAxisState.cs
> +        public  ulong _unknown2;
```suggestion
        public ulong _unknown2;
```

2020-07-07 20:21 UTC, emmauss commented on Ryujinx.Common/DSU/Client.cs
> +
at this point, the clients are being closed, so any existing connections are forcibly closed. A socket exception would only mean that the client is connected, or connecting. we are closing it either way.

2020-07-07 20:31 UTC, emmauss commented
addressed comments

2020-07-13 21:53 UTC, emmauss commented
rebased, and updated orientation

2020-07-21 04:30 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/MotionInput.cs
> +        public ulong   TimeStamp     { get; set; }
Align is wrong

2020-07-21 04:31 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +            if(_clients.ContainsKey(player))
```suggestion
            if (_clients.ContainsKey(player))
```

2020-07-21 04:33 UTC, AcK77 commented on Ryujinx.Common/DSU/Client.cs
> +        public unsafe async Task HandleResponse(byte[] data, int clientId)
I don’t think unsafe is necessary here, same for following methods

2020-07-21 04:35 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +        private unsafe bool SetSixAxisState(PlayerIndex player, HidVector accel,
I don’t think unsafe is necessary here

2020-07-21 04:35 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +                                            currentLayout.Header.MaxEntryIndex : currentLayout.Header.LatestEntry - 1);
Align is a bit weird here

2020-07-24 10:56 UTC, emmauss commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +        private unsafe bool SetSixAxisState(PlayerIndex player, HidVector accel,
Can't remove the unsafe with causing compiler error

2020-07-24 10:57 UTC, emmauss commented
Updated with a filter for orientation, and rebased

2020-07-24 11:15 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +        private unsafe bool SetSixAxisState(PlayerIndex player, HidVector accel,
might be worth moving the unsafe block to the part that is actually unsafe

2020-07-24 11:30 UTC, emmauss commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +        private unsafe bool SetSixAxisState(PlayerIndex player, HidVector accel,
done

2020-08-02 14:01 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                EnableKeyboard  = new ReactiveObject<bool>();
Nits: extra space (same for next lines)

2020-08-02 14:02 UTC, AcK77 commented on Ryujinx.Common/Motion/Client.cs
> +                    catch (SocketException ex)
Why silent exceptions?

2020-08-02 14:06 UTC, AcK77 commented on Ryujinx.Common/Motion/MotionInput.cs
> +            if(gyro.Length() <=1 && accel.Length() >= 0.9 && accel.Z <= -0.9)
```suggestion
            if (gyro.Length() <=1 && accel.Length() >= 0.9 && accel.Z <= -0.9)
```

2020-08-02 14:06 UTC, AcK77 commented on Ryujinx.Common/Motion/MotionInput.cs
> +                if(_calibrationFrame >= 90)
```suggestion
                if (_calibrationFrame >= 90)
```

2020-08-02 14:08 UTC, AcK77 commented on Ryujinx.Common/Utilities/MotionSensorFilter.cs
> +            norm = 1 / norm;        // use reciprocal for division
```suggestion
            norm = 1 / norm; // use reciprocal for division
```

2020-08-02 14:08 UTC, AcK77 commented on Ryujinx.Common/Utilities/MotionSensorFilter.cs
> +                _intergralError += error;      // accumulate integral error
```suggestion
                _intergralError += error; // accumulate integral error
```

2020-08-02 14:08 UTC, AcK77 commented on Ryujinx.Common/Utilities/MotionSensorFilter.cs
> +                _intergralError = new Vector3();     // prevent integral wind up
```suggestion
                _intergralError = new Vector3(); // prevent integral wind up
```

2020-08-02 16:12 UTC, emmauss commented on Ryujinx.Common/Motion/Client.cs
> +                    catch (SocketException ex)
Actually, I only put the try catch as a failsafe so the game doesn't close if there is an issue with the socket when it is disposed. there is no documentation on exceptions that may be thrown if the socket is disposed in some situations. that's why it's empty.

2020-08-02 16:15 UTC, AcK77 commented on Ryujinx.Common/Motion/Client.cs
> +                    catch (SocketException ex)
Maybe you can use some logging then, as you did in other functions!

2020-08-03 08:01 UTC, emmauss commented
Rebased and added more error logs

2020-08-24 09:11 UTC, emmauss commented
Rebased

2020-08-24 14:21 UTC, Thog requested changes
lgtm apart from one nit.

Also the configuration version will need to be updated (**version 13 is reserved** so use 14)

Another note, after this PR gets merged, it would be nice to add support for Cemu hook as a standard input method to unify this a bit (an issue will need to be made)

2020-08-24 14:21 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +
Remove this

2020-08-25 09:50 UTC, emmauss commented
@Thog resolved the issues. The config format is not changed, only the json schema, so no need to bump the file version. Also, it client uses Cemu Hook. It's just known as DSU internally.

2020-08-27 23:18 UTC, AcK77 approved these changes
Just one nit! Lgmt!

2020-08-27 23:18 UTC, AcK77 commented on Ryujinx.Common/Motion/Protocol/Header.cs
> +        public uint CRC32;
```suggestion
        public uint Crc32;
```

2020-09-05 19:36 UTC, gdkchan commented on Ryujinx.Common/Motion/MotionInput.cs
> +            // TODO :  RE the correct filter
```suggestion
            // TODO: RE the correct filter
```

2020-09-05 19:36 UTC, gdkchan commented on Ryujinx.Common/Utilities/MotionSensorFilter.cs
> +    /// https://github.com/xioTechnologies/Open-Source-AHRS-With-x-IMU/blob/master/x-IMU%20IMU%20and%20AHRS%20Algorithms/x-IMU%20IMU%20and%20AHRS%20Algorithms/AHRS/MahonyAHRS.cs
Put the links as a regular comment, we don't need it on the XML doc.

2020-09-05 19:36 UTC, gdkchan commented on Ryujinx.Common/Motion/Client.cs
> +        public const uint   Magic   = 0x43555344; //DSUC
```suggestion
        public const uint   Magic   = 0x43555344; // DSUC
```

2020-09-05 19:46 UTC, gdkchan commented on Ryujinx.Common/Motion/Client.cs
> +namespace Ryujinx.Common.Motion
Why is this on `Ryujinx.Common`? I think it should be part of the GUI. Common is for things that are or might be used by multiple projects, I don't think this is the case for motion controls. Ideally HLE should just expose a basic API that allows sending motion information, and the GUI would handle the actual communication with the controller, android device etc.

2020-09-05 20:48 UTC, emmauss commented
Addressed comments

2020-09-05 21:12 UTC, gdkchan approved these changes
lgtm, thanks. Great job 👍

2020-09-09 18:40 UTC, riperiperi requested changes
Looks good. I did have a chance to use it and I had to make a few tweaks to get things working right for my Pro Controller via BetterJoy, but the code otherwise is fine.

2020-09-09 18:40 UTC, riperiperi commented on Ryujinx/Motion/MotionInput.cs
> +                        if (deltaGyro.Length() > 0.1f)
This deadzone is too high, 0.01f is a better default.

2020-09-09 18:40 UTC, riperiperi commented on Ryujinx/Motion/MotionInput.cs
> +                _filter.Update(-gyro.X, gyro.Y, -gyro.Z, -accel.X, accel.Y, -accel.Z);
`_filter.SamplePeriod` is currently `1/60f`, but the betterjoy motion server seems to be doing 1/200f (with spikes to 1/100f). Should just set it before each update with `_filter.SamplePeriod = deltaTime;`. As discussed, `1/60f` breaks vertical aiming and motion minigames in zelda.

To get accurate results with my pro controller at 100% sensitivity, I had to use `_filter.SamplePeriod = deltaTime * 0.9f;`. Not sure if this is indicitive of an issue with 100% sensitivity, or the filter needing a slightly scaled gyro result.

2020-09-09 18:40 UTC, riperiperi commented on Ryujinx/Ui/ControllerWindow.cs
> +                    _altSlotNumber.Value       = keyboardConfig.AltSlot;;
Double semicolon.

2020-09-10 18:48 UTC, emmauss commented
Addressed comments.

2020-09-11 01:21 UTC, LDj3SNuD reviewed
This is my review: https://github.com/LDj3SNuD/Ryujinx/commits/base_motion

2020-09-11 21:35 UTC, riperiperi requested changes
Just a small thing, generally looks good otherwise.

2020-09-12 16:41 UTC, emmauss commented
Rebased. Added setting a reference orientation, and deriving relative orientation from it.

2020-09-17 18:29 UTC, LDj3SNuD approved these changes
lgtm, ty

2020-09-26 18:35 UTC, riperiperi approved these changes
LGTM, works rather well here with wired switch pro controller.

2020-09-29 15:59 UTC, cooperate commented
Does this have support for the Ring Con accesory?

2020-09-29 21:32 UTC, merged