Implements Appveyor Ryujinx Auto-Updater
Ryujinx/Ryujinx pull request #1403
Opened 2020-07-19 20:14 UTC by MelonSpeedruns

2020-07-27 19:01 UTC, MelonSpeedruns commented
LGTM! Nice work Xpl0iter!

2020-07-28 15:36 UTC, Doctorwho1909 commented
checked the newest PR and all is working LGTM! and badly needed

2020-07-28 20:10 UTC, PersonaVinny commented
Tested it, works great! Great new feature. :watermelon:

2020-08-06 21:22 UTC, AcK77 commented on Ryujinx/Updater/UpdateDialog.cs
> +            NoButton.Pressed  += (obj, args) =>
Why don't use a function instead inline the code here ?

2020-08-06 21:23 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +            if (Running) return;
Add a new empty line after

2020-08-06 21:24 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +                    string fetchedJson = await jsonClient.DownloadStringTaskAsync(MasterUrl);
```suggestion
                    string  fetchedJson = await jsonClient.DownloadStringTaskAsync(MasterUrl);
```
and align other lines

2020-08-06 21:27 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +            if (newVersion < currentVersion)
Since `newVersion` and `currentVersion` are initialize to `0.0` what you catch an error during the parse? It will open an empty `UpdateDialog` instead of throw an error ? There is something weird here!

2020-08-06 21:27 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +                return;
Add new empty line before

2020-08-06 21:28 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +            if (Directory.Exists(UpdateDir))
Add brackets

2020-08-06 21:28 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +            Directory.CreateDirectory(UpdateDir);
Add new empty line after

2020-08-06 21:31 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +            if (isLinux)
Instead of using `isLinux` argument, why don't use `if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux))` directly ?

2020-08-06 21:32 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +                            TarEntry entry = tarEntry;
Add new empty line after

2020-08-09 12:27 UTC, AcK77 commented on Ryujinx/Updater/UpdateDialog.cs
> +        private void YesButton_Pressed(object sender, EventArgs args)
Adds new  empty line before

2020-08-27 17:42 UTC, Thog requested changes
Require some changes.

Also worth noting that the updater shouldn't run if:
- The platform CPU isn't x64.
- In a development environment (maybe a check of the version string)

2020-08-27 17:42 UTC, Thog commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 13;
```suggestion
        public const int CurrentVersion = 14;
```
Version 13 is reserved for LDN

2020-08-27 17:42 UTC, Thog commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +        /// Checks for updates when ryujinx starts when enabled
```suggestion
        /// Checks for updates when Ryujinx starts when enabled
```

2020-08-27 17:42 UTC, Thog commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        /// Checks for updates when ryujinx starts when enabled
```suggestion
        /// Checks for updates when Ryujinx starts when enabled
```

2020-08-27 17:42 UTC, Thog commented on Ryujinx/Config.json
> +  "version": 13,
```suggestion
  "version": 14,
```

2020-08-27 17:42 UTC, Thog commented on appveyor.yml
> +- path: ryujinx%config_name%%APPVEYOR_BUILD_VERSION%-osx_x64.zip
read the line return to reduce diff.

2020-08-27 17:42 UTC, Thog commented on Ryujinx/Updater/Updater.cs
> +                    _buildUrl = "https://ci.appveyor.com/api/buildjobs/" + _jobId + "/artifacts/ryujinx-" + _buildVer + "-" + _platformExt;
Make a constant here

2020-08-27 17:42 UTC, Thog commented on Ryujinx/Program.cs
> +}
line return

2020-08-27 17:42 UTC, Thog commented on Ryujinx/Updater/Updater.cs
> +}
line return.

2020-09-12 11:09 UTC, Thog requested changes
Mostly preconditions are missing right now for the updater, otherwise should be ready.

2020-09-12 11:09 UTC, Thog commented on Ryujinx/Updater/Updater.cs
> +            Version newVersion     = Version.Parse(_buildVer);
AppVeyor send us arbitrary values here, this need to be in a try catch.

2020-09-12 11:09 UTC, Thog commented on Ryujinx/Program.cs
> +            if (ConfigurationState.Instance.CheckUpdatesOnStart.Value)
It might also be better to do some util function that check those preconditions for the other codepath calling ``Updater.BeginParse``

2020-09-13 10:50 UTC, emmauss requested changes

2020-09-13 10:50 UTC, emmauss commented on Ryujinx/Updater/Updater.cs
> +        public static async void BeginParse(MainWindow mainWindow, bool showVersionUpToDate)
Return a `Task` instead of a `void`

2020-09-13 10:50 UTC, emmauss commented on Ryujinx/Updater/Updater.cs
> +        public async static void UpdateRyujinx(UpdateDialog updateDialog, string downloadUrl)
Same as above comment

2020-09-13 15:28 UTC, Thog approved these changes
lgtm

2020-09-14 19:48 UTC, emmauss approved these changes

2020-09-16 17:41 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +            if (configurationFileFormat.Version < 13)
`public const int CurrentVersion = 14;` so you should check 14!

2020-09-16 17:41 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
>          [GUI] MenuBar        _menuBar;
```suggestion
        [GUI] MenuBar         _menuBar;
```
and same for following lines

2020-09-16 17:41 UTC, AcK77 commented on Ryujinx/Updater/Updater.cs
> +            //Extract Update
```suggestion
            // Extract Update
```

2020-09-18 22:46 UTC, AcK77 approved these changes

2020-09-19 20:08 UTC, riperiperi approved these changes
Looking good, will be nice to see this finally merged.

2020-09-29 20:05 UTC, merged