Texture/Buffer Memory Management Improvements
Ryujinx/Ryujinx pull request #1408
Opened 2020-07-20 21:11 UTC by riperiperi

![image](https://user-images.githubusercontent.com/6294155/87986387-f88ba400-cad4-11ea-85c9-032753ae448e.png)

This PR aims to make texture and buffer memory management better in a few areas, so that we can do things like flush textures without worrying about data corruption, and thus fix a few issues with our AutoDeleteCache having a limited size. The course pictured above generally has the ground incredibly dark, as the course shadow map and lighting cube for the floor are both dropped out of the AutoDeleteCache during loading. No such problem in the screenshot. 😌 

All of these changes are related, which is why they're all part of one PR. There is one change that needs to be here to make this more stable, but more on that later.

1. Overlapping textures that are not  are now removed from the AutoDeleteCache. This gives us a guarantee that no unrelated overlapping textures can flush out of order, when we get around to flushing them, and it also cleans out the texture cache so that it's not a huge mess of tangled overlaps. It can also remove some dead textures, which can help with memory usage.
2. When textures fall out of the AutoDeleteCache, they are now flushed rather than lost. The alternative would be an infinite size texture cache, but then we would need you to have a 32GB page file or something. So reworking things to better facilitate flushing wins.
3. Modification flag is unset when a texture's memory is unmapped. This will stop textures from flushing when their memory is definitely used for something else.
4. Buffer and Texture flushing now writes to memory _without_ triggering write tracking. This avoids textures from setting each other as dirty when flushing to memory - which allows us to flush textures in the auto delete cache in order of use without any repercussions. It has been extended to buffers as it seems to improve performance and remove vertex explosions.
5. An OpenGL resource cache now exists so that textures that are deleted and immediately reused can just use the old texture resource. **This mostly exists as a mitigation to some games aggressively reusing memory used for screen render targets.**
6. With the new overlap rules, we can detect whether or not a texture needs its initial data set or not, based on the presence of existing textures and if their memory has been modified. This can improve performance for res scaling, or games that continually create render targets and set the data of other, unrelated ones. (mostly improves res scaling) **It is needed as part of (5)'s performance mitigation.**
7. View compatibility has been refactored a bit so that it returns an enum that indicates if it's only copy compatible. This avoids calling it multiple times.

## Benefits
![image](https://user-images.githubusercontent.com/6294155/87986956-c0d12c00-cad5-11ea-88f4-83b7024d27d3.png)

Here are the benefits, with helpful numbers pointing to which change was responsible:

- All random chance course issues (broken shadows, black actor lighting, black screen) in MK8 are fixed. (1, 2)
- In Super Mario Odyssey, you **no longer need to pause the game or fast travel to fix broken graphics in most kingdoms.** (1, 2)
- Generally, games with textures are black or garbage after loading will be improved, but that of course does not include all situations (UE4 and catherine don't count) (1, 2)
- **Vertex explosions have been reduced in Unity games**, and their performance has slightly improved. I am not sure if this has affected any other games. (4)
- Write tracking performance will improve with range-tracking, due to less dead overlapping textures within the same spot. In MK8, thousands of 32x32 textures are rendered to in a sequence to generate static lighting for actors. These take up the same space in memory as the _nvdec video_, causing a major performance hit when we return to the menu. With this change, these overlaps are removed before we start tracking the nvdec video, so it can continue being a nice single memory region rather than thousands of tiny ones. (1)

## Rules

(writeup in progress)

## Random corruptions due to flushing?

Yes, I'm PRing something that has a chance to do this. Play 32 courses in Mario Kart and you will notice something that's off in at least one course, or it may even crash. Here's the reason why that is:

The rules for flushing indicate that we should only flush a texture if its memory has not been modified since the last time it was used (and if the memory was unmapped, which is working fine). What happens if two textures share the same page?

Under the _current method_ of tracking texture modification, two or more textures that share a page can face a dilemma. If one texture on the page consumes the dirty flag, it is consumed for _all other textures on the page_. How do we solve this one?

That's right - it's range tracking time again. Literally cannot get away from this. Essentially, it will work better when the memory write tracking is able to signal to each affected texture individually - so that if one's dirty bit is consumed, the other's is still present. The range tracking PR will be rebased on top of this one.

## Call for Testing
Even with the above issue, it would really benefit us to test this PR to check if there have been any regressions. Since every game uses textures, the surface area for potential regressions is huge. If the game is generally improved, good! If textures are corrupt, missing or the game crashes very quickly, then there's probably an issue.

This may change performance on some games, for better or worse. It will be good to know cases where it kills it.

This will be a part of the range tracking PR in future, which may be a better test target when it's up and running due to flushing being more predicatble. I will comment when that is ready.

2020-07-21 22:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +    class ResourcePool
I think this should be disposable, to allow all textures in to pool to be deleted.

2020-07-21 22:02 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        public TextureView TryGetTexture(TextureCreateInfo info, float scaleFactor)
`Try*` methods usually returns a bool indicating if the operation was successful, and the actual value as a out parameter. I'd just call this `GetTexture`. Or maybe `GetTextureOrNull` if you really want to be explicit about the fact that it can return null.

2020-07-21 22:03 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        private object _lock = new object();
nit: `readonly` (on both fields).

2020-07-21 22:06 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        private uint GetTextureKey(TextureCreateInfo info)
Why not just override `GetHashCode` and `Equals` on `TextureCreateInfo`, and use it as key.

2020-07-21 22:07 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Renderer.cs
> +            ResourcePool = new ResourcePool();
I think this should be disposed when the renderer is disposed.

2020-07-21 22:08 UTC, gdkchan commented on Ryujinx.Graphics.GAL/ITexture.cs
> +        void Release();
Is this supposed to be the new way to dispose of textures? If so, I think this interface should stop implementing IDisposable.

2020-07-21 22:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Renderer.cs
> +        public void PreFrame()
Would be nice to not need this function, maybe it's possible to "tick" the pool on window present? I still need to take a look at the code to figure out what this is used for.

2020-07-23 05:11 UTC, Doctorwho1909 commented
![image](https://user-images.githubusercontent.com/64975148/88253876-c40d1900-cc89-11ea-9e95-b0333a0066d9.png)
turns out my broken fog was a Driver issue updating fixed the problem I have found no regressions or new issues with this PR great work as always it even caused a big speed boost in some titles

2020-07-23 22:34 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/Renderer.cs
> +        public void PreFrame()
I deliberately added this PreFrame function to avoid blocking on anything that would have to wait on GPU commands in the future. It's future sight more than anything (for instance, glSync objects from the previous frame could be disposed here, if we were to generate them throughout the previous frame)

2020-07-23 22:37 UTC, riperiperi commented
Will need some investigation into performance implications for the flushes. While it's definitely more accurate to not trash these textures, and the point of overlap is definitely the best way to dispose them, doing so mid-frame could cause a stutter. Some games also aggressively reuse a memory region for a target many times in a frame, such as animal crossing.

2020-07-24 01:14 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Renderer.cs
> +        public void PreFrame()
Wouldn't calling that from the window Present function have the same effect, without needing to introduce a new function that needs to be explicitly called before each frame?

2020-07-30 22:49 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +                if (texture.IsViewCompatible(view.Info, view.Size, out int _, out int _) != TextureViewCompatibility.Incompatible)
There will be no CopyOnly views in `_views`, but if there were then I'd probably want to count them. (for the case this function is currently used for, at least)

2020-07-30 22:49 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Memory/Buffer.cs
> +            _context.PhysicalMemory.WriteUntracked(address, data);
Noted. I'll add a note in a comment.

2020-07-30 22:59 UTC, riperiperi commented on Ryujinx.Graphics.GAL/ITexture.cs
> +        void Release();
Yeah, I guess dispose should only be used internally now. Release indicates that the backing resource isn't being finalized yet.

2020-08-31 22:58 UTC, EmulationFanatic commented
This noticeably raised the average FPS of and improved (but did not eliminate) vertex explosions in the game "Good Job!"

2020-08-31 23:33 UTC, ReaperOfSouls1909 commented
Is this still wip ? Or is more testing needed ?

2020-09-02 22:27 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +        private TextureViewCompatibility PropagateViewCompatability(TextureViewCompatibility first, TextureViewCompatibility second)
This function has been moved to that class with the rebase.

2020-09-02 22:51 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        private uint GetTextureKey(TextureCreateInfo info)
Do I need to override equals here? I think the struct equality would do the job - though it would change from the current behaviour of grouping lists by width and height, to creating dictionary buckets but grouping lists by exact TextureCreateInfo.

2020-09-02 22:58 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        private uint GetTextureKey(TextureCreateInfo info)
Though it would mean I could remove the .Equals check in `GetTextureOrNull`.

2020-09-03 03:56 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        private uint GetTextureKey(TextureCreateInfo info)
AFAIK the default struct equality is not very fast, that's why overriding it is recommended. If the current approach has some advantage, then it's fine for me, but I think doing what I suggested would simplify the code without much of a performance penalty.

2020-09-03 03:59 UTC, jduncanator commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        private uint GetTextureKey(TextureCreateInfo info)
For better performance, you need to implement IEquatable<T> (and so override Equals), otherwise the object will be boxed/unboxed to do an object comparison. It's not strictly needed for using it as a key, but it will be better overall.

2020-09-03 23:26 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +        private uint GetTextureKey(TextureCreateInfo info)
OK, I did that. The equals override is a bit long but I guess there's no way around that 😅

2020-09-04 01:23 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/Renderer.cs
> +        public void PreFrame()
(opengl) Present is techincally always during a frame rather than before. Buffers are only swapped _after_ it completes the present, and the present happens after all fifo calls are processed. If we're doing things here that need to wait for gpu sync, then it will delay swapbuffers and the frame time could be slightly higher. If we do it at the start of the next frame, there's less chance sync is required.

Haven't tested any of this, just a theory. I'm not sure if swap buffers will end up forcing a sync anyways.

2020-09-05 10:16 UTC, jduncanator commented on Ryujinx.Graphics.GAL/TextureCreateInfo.cs
> +            return Width | (Height << 16);
This can use `HashCode.Combine`

2020-09-08 16:35 UTC, riperiperi commented
I've committed an additional fix when using SizeChange on compressed+non-compressed view combinations.

Before, this could set either the compressed or non compressed texture with a size with the wrong size, depending on which texture had its size changed. This caused exceptions when flushing the texture. 

Now it correctly takes the block size into account, assuming that these textures are only related because a pixel in the non-compressed texture represents a block in the compressed one.

2020-09-08 22:53 UTC, riperiperi commented
Disregard previous comment about performance issues, there doesn't seem to be much performance impact despite the tendancy for flushing textures midgame. (tested smo, mario kart, acnh). In AC:NH specifically, I was hovering around 25-26 fps in a rather busy area, and with or without this PR it was really margin of error as it fluctuated within that 1 frame difference. VRAM usage may be slightly higher but nothing appears to be leaking.

2020-09-08 23:46 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
> +        public static TextureViewCompatibility PropagateViewCompatability(TextureViewCompatibility first, TextureViewCompatibility second)
typo: `Compatability`.

2020-09-08 23:46 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Image/TextureManager.cs
> +            public TextureViewCompatibility Compatibility;
I would make those a get-only auto-property if theres no need to modify those fields.

2020-09-09 00:29 UTC, gdkchan approved these changes
lgtm, nice to see the weird texture bugs and vertex explosions finally fixed (to some extent).

2020-09-09 00:49 UTC, jduncanator requested changes
Nicely done! Appreciate the well documented nature of the code, and everything looks really tidy :) Only a few nits and questions from me here, excuse my ignorance if some of them seem silly.

2020-09-09 00:49 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            int blockHeight = Info.FormatInfo.BlockHeight;
Nit: These two local declarations could probably be hoisted to the top of the function.

2020-09-09 00:49 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
You may want to consider `newRefCount <= 1`. I know technically this is an illegal state, however it would help prevent bugs in functions that depend on the return value of this function being true when all the ref's have been released. The debug assert will make the issue obvious to developers.

2020-09-09 00:49 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
> +            else if (first == TextureViewCompatibility.CopyOnly || second == TextureViewCompatibility.CopyOnly)
Assuming this function should "Obtain the minimum compatibility level", should this not check that both textures are CopyOnly compatible, rather than either of them?

```suggestion
            else if (first == TextureViewCompatibility.CopyOnly && second == TextureViewCompatibility.CopyOnly)
```

2020-09-09 00:49 UTC, jduncanator commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +                        list.Remove(texture);
Are you sure this is valid? Removing values from a collection whilst they're being iterated over via an IEnumerable is usually illegal.

2020-09-09 00:51 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +                        list.Remove(texture);
We return immediately afterwards. If the loop continued, it would throw.

2020-09-09 00:51 UTC, jduncanator commented on Ryujinx.Graphics.OpenGL/ResourcePool.cs
> +                        list.Remove(texture);
Ah yep, missed that. :+1:

2020-09-09 00:52 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
That would be `<= 0` not `<= 1`.

2020-09-09 00:52 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
Yes, that's what I meant, my bad. (I was thinking of -1 in my head)

2020-09-09 00:54 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
> +            else if (first == TextureViewCompatibility.CopyOnly || second == TextureViewCompatibility.CopyOnly)
If one texture is CopyOnly and the other is Full, then when considering them both the minimum level of compatibility is copy. It's the same logic as the incompatible check above - it chooses the most restrictive compatibility of the two.

2020-09-09 00:55 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Image/TextureCompatibility.cs
> +            else if (first == TextureViewCompatibility.CopyOnly || second == TextureViewCompatibility.CopyOnly)
:+1:

2020-09-09 00:56 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
It hasn't been triggered yet, but I can do this for safety.

2020-09-09 00:58 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
I don't see how `<= 0` is better to be honest. If it's using that for disposal, then it would result in double disposal if there's a bug allowing it to be decremented below 0.

2020-09-09 01:00 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
I'm happy with it either way, just a suggestion.

2020-09-09 01:00 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
Actually, this returned result isn't used anywhere right now. It is returned from AutoDeleteCache.Remove, but that return value is not used by anything right now (it was at one point)

2020-09-09 01:01 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Image/Texture.cs
> +            return newRefCount == 0;
It was essentially used to check if an AutoDeleteCache remove resulted in the texture being deleted. I guess in that case, <= 0 would make more sense.

2020-09-09 01:05 UTC, jduncanator approved these changes

2020-09-10 18:53 UTC, Thog approved these changes

2020-09-10 19:44 UTC, merged