Implement vfnms
Ryujinx/Ryujinx pull request #1489
Opened 2020-08-21 01:07 UTC by saldabain

Closes #1477 

Implements slow path of vfnms (FMA instructions not implemented).

2020-09-09 21:46 UTC, riperiperi requested changes

2020-09-09 21:46 UTC, riperiperi commented on ARMeilleure/Decoders/OpCodeTable.cs
> +            SetA32("<<<<11101x01xxxxxxxx10>>x0x0xxxx", InstName.Vfnms,    InstEmit32.Vfnms,    typeof(OpCode32SimdReg));
Vfnms is a scalar instruction, so should use the `OpCode32SimdRegS` decoder.

https://static.docs.arm.com/ddi0487/ea/DDI0487E_a_armv8_arm.pdf#G41.5054688

2020-09-09 21:46 UTC, riperiperi commented on ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs
> +            EmitVectorTernaryOpF32(context, (op1, op2, op3) =>
This is a scalar instruction. You need to use `EmitScalarTernaryOpF32`. Would also be good to have a FastFP/SSE2 path for this.

2020-09-09 21:46 UTC, riperiperi commented on Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +        public void Vnmfs([Values(0u)] uint rd,
`Vfnms`, same above. The input is also S rather than V.

2020-09-09 21:46 UTC, riperiperi commented on Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +            uint opcode = 0xe900A00; // VNMFS.F32 D0, D0, D0
This is not a valid opcode. The comment is not right either, there is no vector version of this opcode.

The real base instruction would be `ee900a00`, which is `vfnms.f32 s0, s0, s0`. As described above, the fp16 variant is not supported and should be filtered by the decoder.

2020-09-09 21:46 UTC, riperiperi commented on Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +            opcode |= ((rm & 0xf) << 0) | ((rm & 0x10) << 1);
Please keep in mind that the encoding for registers flips when the size is f64 (Vm:M for fp32, M:Vm for fp64). You can see an example of how this is handled in Movi_S.

2020-09-09 21:46 UTC, riperiperi commented on Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +            opcode |= ((rm & 0xf) << 0) | ((rm & 0x10) << 1);
(same for d and n)

2020-09-09 21:46 UTC, riperiperi commented on ARMeilleure/Decoders/OpCodeTable.cs
> +            SetA32("<<<<11101x01xxxxxxxx10>>x0x0xxxx", InstName.Vfnms,    InstEmit32.Vfnms,    typeof(OpCode32SimdReg));
Additionally, the size should be `1x` rather than `>>`, as we do not allow fp16. (`>>` would allow `01`)

`"<<<<11101x01xxxxxxxx101xx0x0xxxx"`

2020-09-11 00:05 UTC, saldabain commented on Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +            opcode |= ((rm & 0xf) << 0) | ((rm & 0x10) << 1);
Thank you for the awesome and clear comments -- I'll get on fixing these right away :)

2020-11-27 18:01 UTC, Thog commented
Need rebase.

2020-11-28 08:02 UTC, closed without merging