Appveyor
Ryujinx/Ryujinx pull request #1529
Opened 2020-09-03 04:52 UTC by qurious-pixel

Create an AppImage of Ryujinx

2020-09-11 00:48 UTC, qurious-pixel commented
Ready for Review

2020-09-11 00:59 UTC, gdkchan commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +            DirectoryInfo logDir = new DirectoryInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Ryujinx/Logs"));
I think it should be `"Ryujinx", "Logs"` to allow the combine method to use the proper directory separator depending on the OS were the emulator is running.

2020-09-11 01:01 UTC, jduncanator requested changes

2020-09-11 01:01 UTC, jduncanator commented on appimage.sh
> +mv Ryujinx-x86_64.AppImage ryujinx$config_name$APPVEYOR_BUILD_VERSION-linux_x64.AppImage
I'd prefer if this script was embedded in the appveyor.yml file, under a separate build_script target, rather than as a separate file in the repository. See my comment and link about build matrix scripts!

2020-09-11 01:02 UTC, jduncanator commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> -            DirectoryInfo logDir = new DirectoryInfo(Path.Combine(path, "Logs"));
For clarity, there is already another PR open discussing the merits of this change, it's better to keep the discussion for this there, and merge the change that we decide on over in that PR. PR linked [here](https://github.com/Ryujinx/Ryujinx/pull/1530).

2020-09-11 01:14 UTC, qurious-pixel commented on appveyor.yml
> +
Initially I used this method, but the VS 2019 clears all file after success. 
I will revert to this method. Still need a good way to handle the logs. 
Custom Config.json is easiest while leaving the other log code unchanged.

2020-09-12 09:31 UTC, jduncanator commented on appveyor.yml
> +      dotnet publish -c $config -r linux-x64 /p:Version=$APPVEYOR_BUILD_VERSION
You don't need this line, as the previous build_script, that runs on all matrix entries, has already built the Linux x64 target (as well as all the Windows and macOS targets, which aren't really needed).

2020-09-13 00:24 UTC, qurious-pixel commented on appveyor.yml
> +      dotnet publish -c $config -r linux-x64 /p:Version=$APPVEYOR_BUILD_VERSION
with the matrix, VS 2019 clears upon completion, so Ubuntu needs to recreate the files.

2020-09-13 00:27 UTC, jduncanator commented on appveyor.yml
> +      dotnet publish -c $config -r linux-x64 /p:Version=$APPVEYOR_BUILD_VERSION
The normal `build_script`, the one that isn't targetting a specific matrix entry, should run on both targets, so the files should be there.

2020-09-13 03:07 UTC, qurious-pixel commented on appveyor.yml
> +      dotnet publish -c $config -r linux-x64 /p:Version=$APPVEYOR_BUILD_VERSION
This can all be built with Ubuntu. VS 2019 isn't necessary, but I could not get VS 2019 to build some of the linux stuff using WSL1. Needs WSL2.
[AppVeyor Ubuntu Image](https://ci.appveyor.com/project/qurious-pixel/ryujinx/builds/35173947)

2020-09-22 22:09 UTC, jduncanator commented on appveyor.yml
> +      dotnet publish -c $config -r linux-x64 /p:Version=$APPVEYOR_BUILD_VERSION
Were you able to resolve this? I think this is the last thing preventing it from getting merged.

2020-11-27 18:03 UTC, Thog commented
Need rebase.

2021-04-23 23:33 UTC, closed without merging