Move Logs into Config directory
Ryujinx/Ryujinx pull request #1530
Opened 2020-09-03 15:40 UTC by qurious-pixel

Allow logs to be written in config folder, leaving Publish folder unchanged.

2020-09-05 09:46 UTC, Thog requested changes
Added some comments that need to be addressed.

I'm also against moving logs to this kind of location due to the idea of it not being tied to the build you are using.

2020-09-05 09:46 UTC, Thog commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +            DirectoryInfo logDir = new DirectoryInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Ryujinx/Logs"));
Starting with b9398f1f3a13612a0bc3e64205cdb7eca3f48d4d, Ryujinx support custom data directory.
As such you need to modify [AppDataManager](https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Common/Configuration/AppDataManager.cs) to add an util here that use the BasePath.

2020-09-05 09:46 UTC, Thog commented on Ryujinx/Ui/SettingsWindow.cs
> +            string logPath = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Logs");
Starting with b9398f1f3a13612a0bc3e64205cdb7eca3f48d4d, Ryujinx support custom data directory.
As such you need to modify [AppDataManager](https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Common/Configuration/AppDataManager.cs) to add an util here that use the BasePath.

2020-09-05 21:30 UTC, qurious-pixel commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +            DirectoryInfo logDir = new DirectoryInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "Ryujinx/Logs"));
I did try `./Ryujinx -r <my-data-dir>` but it fails if the directory does not exist and falls back to the original base dir. This would crash the emulator if the fallback tries again to write to write-protected area. 
maybe a non-destructive way to create the directory if doesn't exist.

Also, the first line of the logs indicate the version. 
Maybe you are saying if the user is running multiple versions of Ryujinx?

2020-09-06 22:26 UTC, jduncanator commented
I’m fairly against this change. The config file is usually located in AppData, and we already have issues getting users to locate the logs when they’re in the same folder as Ryujinx itself, let alone some hidden folder that’s difficult to find on Windows. The config folder is also shared across multiple different Ryujinx versions.

My preference here would be to leave the default location, but to add a config option that allows you to change the log folder location. If you want to move logs out of the publish folder, you can change your config and put them somewhere else.

2020-09-07 14:20 UTC, qurious-pixel commented
I understand the hesitancy to change the location to AppData.
I like how Ryujinx has the open Logs Folder button.
I would like to have a way to set the change location BEFORE launching the App.

If changing the DataDir folder, should the logsDir also change, or should the user also select this?

2020-09-07 14:52 UTC, gdkchan commented
Sounds like just adding another command line parameter to allow setting a custom log output folder would solve the issue.

2020-09-09 05:06 UTC, jduncanator commented
> I would like to have a way to set the change location BEFORE launching the App.

You can always tweak the Config.json to point to the correct location, before launching Ryujinx.

2020-09-09 22:58 UTC, qurious-pixel commented
I can see log on/off switches, but i wasn't able to find where to set the path for logs. I had turned off the logs, originally, but decided it was more important to keep them on, in a writeable directory.

2020-09-10 00:34 UTC, jduncanator commented
> I can see log on/off switches, but i wasn't able to find where to set the path for logs. I had turned off the logs, originally, but decided it was more important to keep them on, in a writeable directory.

The feature doesn't exist yet. I meant, if we were to add the option to configure the logs directory via settings, you could always tweak the directory in the config file before launching Ryujinx for the first time.

2021-02-15 21:57 UTC, Shahil-Ayato commented
@qurious-pixel are you still interested in this Pull Request?

2021-02-16 19:21 UTC, qurious-pixel commented
> @qurious-pixel are you still interested in this Pull Request?

It is necessary for any read-only system like AppImage or Flatpak, but as of now, I am making the change during build. This PR can be dropped.

2021-02-17 20:05 UTC, AcK77 commented
Superseeded by #2027

2021-02-17 20:05 UTC, closed without merging