Bugs in DLC Json loading
Ryujinx/Ryujinx pull request #1548
Opened 2020-09-15 03:09 UTC by CharlesToniolo

Bugs in DLC Json loading #1366

2020-11-27 18:04 UTC, Thog commented
Need rebase.

2020-12-02 02:17 UTC, CharlesToniolo commented
@Thog Hi, I fixed the conflicts and I also changed the method RemoveAllButton_Clicked that was recently created to use the TreeStore.Clear() method.

2020-12-03 17:54 UTC, AcK77 requested changes

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.Common/Configuration/DlcContainerLoader.cs
> +            if (!_localStorageManagement.Exists(_dlcJsonPath))
Add `{}`

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.Common/IO/LocalStorageManagement.cs
> +        public bool Exists(string filePath)
You can put the action on the same line.

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.Common/IO/LocalStorageManagement.cs
> +        public Stream OpenRead(string filePath)
You can put the action on the same line.

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.HLE/Loaders/Dlc/DlcNcaLoader.cs
> +                if (!TryCreateNca(ncaFile.AsStorage(), _containerPath, out var nca))
Add `{}`

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.HLE/Loaders/Dlc/DlcNcaLoader.cs
> +                    if ((nca.Header.TitleId & 0xFFFFFFFFFFFFE000).ToString("x16") != _titleId)
Add `{}`

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.HLE/Loaders/Dlc/DlcNcaLoader.cs
> +            catch (MissingKeyException exception)
This exception is reached ? Since we load games before DLC the check is already done before ?

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.HLE/Loaders/Dlc/DlcNcaLoader.cs
> +                return true;
Add new empty line before.

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx.HLE/Loaders/Dlc/DlcNcaLoader.cs
> +            return false;
Add new empty line before

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx/Ryujinx.csproj
> +    <EmbeddedResource Include="Ui\Windows\DlcWindow.glade" />
Good idea 👍

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +                    if (!savedDlcNca.Enabled)
Add `{}`

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +                if (_treeModel.IterHasChild(treeIter))
Add `{}`

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +                            if ((bool)_treeModel.GetValue(c, (int)TreeStoreColumn.Enabled))
Add `{}`

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +                            totalChildren++;
Add a new empty line after.

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +            if (fileChooser.Run() != (int)ResponseType.Accept)
Add `{}`

2020-12-03 17:54 UTC, AcK77 commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +        private void RemoveAllButton_Clicked(object sender, EventArgs args)
You can put the action on the same line

2020-12-03 23:08 UTC, CharlesToniolo commented on Ryujinx.HLE/Loaders/Dlc/DlcNcaLoader.cs
> +            catch (MissingKeyException exception)
You are right...

2021-01-13 16:26 UTC, EmulationFanatic commented
@CharlesToniolo can you rebase?

2021-02-17 20:11 UTC, Shahil-Ayato commented
@CharlesToniolo are you still interested in this pull request?

2021-03-18 02:37 UTC, CharlesToniolo commented
Rebased.. Sorry for taking too long to do that.

2021-03-18 23:19 UTC, AcK77 commented
Hi @CharlesToniolo, there is still conflict with `Ryujinx/Ui/Windows/DlcWindow.cs`

2021-03-19 01:02 UTC, CharlesToniolo commented
@AcK77 Fixed the conflict! 

It was caused by a commit made 2 hours ago.

2022-02-06 07:26 UTC, Moonlacer commented
This PR should be checked again since it has been about a year. Maybe it will get merged this year... XD

2022-08-17 07:06 UTC, Thog commented
... Should be redone at this point 😞

2022-08-17 07:06 UTC, closed without merging