acc/hid: Implement ListQualifiedUsers and SetTouchScreenConfiguration
Ryujinx/Ryujinx pull request #1555
Opened 2020-09-17 00:51 UTC by AcK77

This implement/stub:
- IAccountServiceForApplication ListOpenContextStoredUsers
- IAccountServiceForApplication ListQualifiedUsers
- IHidServer SetTouchScreenConfiguration

All checked by RE.

Closes #1306, Closes #1267 

Make some games goes ingame: 

![Capture1](https://user-images.githubusercontent.com/4905390/93406708-a080dc00-f890-11ea-8461-da5794da7025.PNG)
![image](https://user-images.githubusercontent.com/4905390/93406677-8ba44880-f890-11ea-8c24-e3144ef7130f.png)
![image](https://user-images.githubusercontent.com/4905390/93406683-919a2980-f890-11ea-829f-d1151154d19f.png)
![image](https://user-images.githubusercontent.com/4905390/93406694-97900a80-f890-11ea-8a39-a2e10772891b.png)

2020-09-17 08:02 UTC, Thog requested changes

2020-09-17 08:02 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +        [Command(1002)]
```suggestion
        [Command(1002)] // 9.0.0+
```

2020-09-18 09:47 UTC, Thog approved these changes

2020-09-19 20:23 UTC, riperiperi commented on Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs
> +            MemoryHelper.FillWithZeros(context.Memory, outputPosition, (int)outputSize);
Are games really fine with this returning an empty list? I know that 3d allstars calls it, but it also crashes later on so we'll never know for sure.

2020-09-20 03:35 UTC, jduncanator approved these changes
Other than clarification on the point @riperiperi raised, this lgtm

2020-09-20 03:43 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Account/Acc/IAccountServiceForApplication.cs
> +            MemoryHelper.FillWithZeros(context.Memory, outputPosition, (int)outputSize);
If you add a UserId in the buffer, the game will call `IAccountServiceForApplication::LoadOpenContext()` whIch will require more works, since all games who needs `ListOpenContextStoredUsers` run fine with an empty buffer, I thinks it’s fine now until we determine (if needed) what the « OpenContext » is!

2020-09-20 04:32 UTC, merged