Return "NotAvailable" when no UserChannel data is present.
Ryujinx/Ryujinx pull request #1569
Opened 2020-09-22 21:15 UTC by riperiperi

Now when no data is available, it returns NotAvailable like the other `Pop` functions. Fixes crashing regressions caused by https://github.com/Ryujinx/Ryujinx/pull/1560 .

Examples of games that call this when no data is present: Splatoon, Super Kirby Clash

2020-09-22 22:08 UTC, jduncanator approved these changes

2020-09-23 03:45 UTC, Cronos-0 commented
Confirm UserChannel empty should be resolved.

![bandicam 2020-09-23 10-41-47-546](https://user-images.githubusercontent.com/35269098/93964467-d3900780-fd89-11ea-8168-e935b6e36c7f.jpg)

2020-09-23 19:22 UTC, AcK77 requested changes
The returned ResultCode is right according to RE, but there is an extra check as I commented.

2020-09-23 19:22 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
After a quick RE, we should throw this exception.
This check is made at the beginning of the function instead and we should add it.
```csharp
if ((kind - 1) > 2 )
{
    return ResultCode.ObjectInvalid;
}
```

2020-09-23 19:25 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
```cs
if (kind != LaunchParameterKind.UserChannel && kind != LaunchParameterKind.PreselectedUser)
{
    return ResultCode.ObjectInvalid;
}
```
is much more readable.

2020-09-23 19:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
Yeah "we shouldn't" sorry for the mistake! I've just given the RE pseudocode :D

2020-09-23 19:40 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
Are you sure its doing a `>` comparison? If that's the case then that means there's one kind missing from the enum (with value 3).

2020-09-23 19:45 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
The value 3 is something but for now it seems reserved/unused.

https://github.com/Ryujinx/Ryujinx/blob/6c9565693fd87ae1af81ed63b5fbdde2a5dbecb8/Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/Types/LaunchParameterKind.cs#L3-L8

2020-09-23 21:01 UTC, riperiperi commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
Can't I just return `ResultCode.ObjectInvalid` from `default:` in the switch statement? ...and add a case for unknown that throws.

2020-09-23 21:27 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
Yeah it's fine too ;)

2020-09-23 21:40 UTC, riperiperi commented on Ryujinx.HLE/HOS/Services/Am/AppletOE/ApplicationProxyService/ApplicationProxy/IApplicationFunctions.cs
>                      throw new NotImplementedException($"Unknown LaunchParameterKind {kind}");
Added handling for this.

2020-09-23 21:48 UTC, AcK77 approved these changes

2020-09-23 21:56 UTC, gdkchan approved these changes
lgtm, thanks.

2020-09-23 21:57 UTC, merged