Add trace log level
Ryujinx/Ryujinx pull request #1690
Opened 2020-11-11 06:59 UTC by rodyt

This PR accomplishes the following:

- Adds a "trace" log level for miscellaneous logs, as requested in #1547 
- Adds some documentation for the Ryujinx.Common.Logging module
- Refactors some logging code, most notably, removing the `PrintStub` method 

I didn't document everything in the module either because the field/class/method was self-explanatory or I didn't understand what it did well enough to feel confident in documenting it. Any help is appreciated.

2020-11-13 18:27 UTC, riperiperi requested changes
https://github.com/Ryujinx/Ryujinx/pull/1672 seems to have been reverted somehow, and there is an alignment issue with 2 statements.

Worth noting that there are a ton of PRs in the horizon project that this will conflict with, but that'll be the case at all times so it's unavoidable.

Not sure if you want to make any other changes with regards to the discussions 2 days ago. I appreciate the addition of XML comments. 😌

2020-11-13 18:27 UTC, riperiperi commented on Ryujinx.Common/Logging/LogEventArgs.cs
> +            Class = logClass;
Alignment.

2020-11-13 18:27 UTC, riperiperi commented on Ryujinx.Memory/Tracking/MemoryTracking.cs
> -                    region.UpdateProtection();
All changes in https://github.com/Ryujinx/Ryujinx/pull/1672 seems to be reverted (or just not rebased, IDK)

2021-02-05 00:03 UTC, gdkchan commented
Closing because the author doesn't intend to work on it anymore.

2021-02-05 00:03 UTC, closed without merging