gui: Toggle between docked/handheld mode by clicking status bar
Ryujinx/Ryujinx pull request #1726
Opened 2020-11-18 05:35 UTC by AcK77

This PR just add a way to toggle between the docked and the handheld mode by clicking the label in the status bar.
Nothing more.

![docked](https://user-images.githubusercontent.com/4905390/99487890-8bdfc380-2967-11eb-8af2-fff0af5ae153.gif)

2020-11-18 18:05 UTC, Xpl0itR approved these changes
lgtm

2020-11-18 21:19 UTC, Thog requested changes

2020-11-18 21:19 UTC, Thog commented on Ryujinx/Ui/MainWindow.cs
> +            ConfigurationState.Instance.ToFileFormat().SaveConfig(Program.ConfigurationPath);
This should be volatile

```suggestion
```

2020-11-18 23:14 UTC, Thog approved these changes

2020-11-19 00:33 UTC, jduncanator commented on Ryujinx/Ui/MainWindow.cs
> +            ConfigurationState.Instance.ToFileFormat().SaveConfig(Program.ConfigurationPath);
I agree 👍

2020-11-19 00:33 UTC, jduncanator approved these changes

2020-11-19 00:34 UTC, merged