This should fix issue #1374 in Linux
Ryujinx/Ryujinx pull request #1751
Opened 2020-11-24 21:35 UTC by d3ce1t

This is my first contribution to this amazing project. Take it easy :)

Changes:
- Bind buttons by detecting the transition from down to up.
- Bind axis by detecting movement from value higher than 50% to a value lower than 50%.

Caveats:
- I have tested only with DS3 in Linux (Fedora 32).
- ZL and ZR detection works by accident. This code doesn't take negative axis into account.
  The reason it works is because axis are managed in absolute value. So when pressing ZL/ZR
  axis value goes from -1 to 1 (or 1 to 0 and back to 1) and this hits the axis detector.
- Likely I have broken all the other controllers in other platforms (testing needed).

2020-11-24 21:58 UTC, d3ce1t commented
BTW looks like the previous code didn't work in Linux because Joystick.GetState was retrieving a wrong state.

After the first button was pressed and bounded to a key, subsequent Joystick.GetState calls were returning a state with that button in "down" state (despite being "up" actually). I don't know OpenTK.Input, but it seems like input is buffered and needs to be consumed completely.

2020-11-25 03:09 UTC, qurious-pixel commented
Latest build 1.0.5819 works well on linux with DS4.
i was able to input the controls and save the profile.
Then refreshed and recalled the profile correctly.

2020-11-25 17:57 UTC, d3ce1t commented
> Latest build 1.0.5819 works well on linux with DS4.
> i was able to input the controls and save the profile.
> Then refreshed and recalled the profile correctly.

I guess you mean build 1.0.5816, right?

2020-11-26 14:06 UTC, qurious-pixel commented
This one.
[build 1.0.5819](https://ci.appveyor.com/project/gdkchan/ryujinx/builds/36493460)

2020-11-27 00:16 UTC, d3ce1t commented
Thank you! I didn't know the build of this PR was available there. So I'm glad it worked for you too.

What I'm curious about is whether it works in Windows (I can't test that)

2021-01-13 14:41 UTC, EmulationFanatic commented
@d3ce1t Can you rebase this?

2021-01-18 17:34 UTC, d3ce1t commented
@EmulationFanatic Done :)

2021-01-19 18:16 UTC, EmulationFanatic commented
Tested input mapping with three controllers in Windows across multiple boots of the application to see if there had been any changes compared to master.
-Xbox 360 for Windows controller: no change in operation. Worked as intended.
-Pro Controller with BetterJoy: no change in operation. Worked as intended.
-Logitech Dual Action (Dinput controller): this PR resolved the issue with Button12 being spammed while trying to map inputs. I was able to map all buttons/axes without any trouble this time.

Big thumbs up from me!

2021-01-20 17:42 UTC, Doctorwho1909 commented
this fixes #1941 also

2021-01-20 19:04 UTC, AcK77 requested changes
It could be nice to move the files in the `UI` folder to another folder, maybe in the `Helper` folder or another one which contains all classes/files related to input.

2021-01-20 19:04 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            if (_inputDevice.ActiveId.StartsWith("keyboard")) {
Add the bracket on a new line

2021-01-20 19:04 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            else if (_inputDevice.ActiveId.StartsWith("controller")) {
Add the bracket on a new line

2021-01-20 19:04 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            else {
Add the bracket on a new line

2021-01-20 19:04 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    if (assigner.HasAnyButtonPressed() || assigner.ShouldCancel()) {
Add an empty line before and add the bracket on a new line

2021-01-20 19:04 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    if (pressedButton != "") {
Add the bracket on a new line

2021-02-01 17:59 UTC, Xpl0itR approved these changes

2021-02-01 18:03 UTC, Xpl0itR commented
nit: Use explicit types instead of var, other than that lgtm

2021-02-01 18:14 UTC, d3ce1t commented
Thanks for your feedback @Xpl0itR. Changed :)

2021-02-09 08:47 UTC, Thog approved these changes
lgtm, just a few nits

2021-02-09 08:47 UTC, Thog commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            //Buttons
```suggestion
            // Buttons
```

2021-02-09 08:47 UTC, Thog commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            //Axis
```suggestion
            // Axis
```

2021-02-09 08:47 UTC, Thog commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            //Hats
```suggestion
            // Hats
```

2021-02-09 08:48 UTC, AcK77 requested changes

2021-02-09 08:48 UTC, AcK77 commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            //Hats
```suggestion
            // Hats
```

2021-02-09 08:48 UTC, AcK77 commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            //Axis
```suggestion
            // Axis
```

2021-02-09 08:48 UTC, AcK77 commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            //Buttons
```suggestion
            // Buttons
```

2021-02-09 08:48 UTC, AcK77 commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            // Reverse list so axis button take precedence when more than one button is recognized
```suggestion
            // Reverse list so axis button take precedence when more than one button is recognized.
```

2021-02-09 08:48 UTC, AcK77 commented on Ryujinx/Ui/Input/JoystickButtonAssigner.cs
> +            CollectButtonStats();
Add a new empty line before

2021-02-17 20:02 UTC, AcK77 commented
Hi @d3ce1t any news about the reviews?
Thanks!

2021-02-17 20:25 UTC, d3ce1t commented
Ey Sorry @AcK77! I cound't apply your changes yet. Very busy these days. Likely this weekend I will have time to do it :)

2021-02-20 22:48 UTC, d3ce1t commented
Thanks for your feedback. All changes included :)

2021-02-20 23:22 UTC, AcK77 approved these changes
Lgtm! Thanks!

2021-02-20 23:22 UTC, merged