Add the ability to layeredfs individual exefs with mod loader
Ryujinx/Ryujinx pull request #1766
Opened 2020-12-01 07:42 UTC by shadowninja108

2020-12-01 18:35 UTC, AcK77 requested changes

2020-12-01 18:35 UTC, AcK77 commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +                if (!codeFs.FileExists(name))
Add `{}`

2020-12-01 18:35 UTC, AcK77 commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
Remove extra empty line

2020-12-01 18:35 UTC, AcK77 commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +            if(modres.Npdm != null)
Add `{}`

2020-12-01 22:29 UTC, jduncanator commented
Please add a description describing the changes you've made, and how they work.

2020-12-03 17:45 UTC, AcK77 commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +
Remove extra empty line

2020-12-03 17:45 UTC, AcK77 commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +            ModLoadResult modres = _fileSystem.ModLoader.ApplyExefsMods(TitleId, nsos);
What about :
```suggestion
            ModLoadResult modLoadResult = _fileSystem.ModLoader.ApplyExefsMods(TitleId, nsos);
```

2020-12-03 17:45 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +            ModLoadResult res = new ModLoadResult();
You can set the fields like that. And probably rename the var to something a bit more explicit.
```suggestion
            ModLoadResult modLoadResult = new ModLoadResult
            {
                Stubs    = new BitVector32(),
                Replaces = new BitVector32()
            };
```

2020-12-03 17:45 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                        Logger.Warning?.Print(LogClass.ModLoader, "Multiple replacements to 'main.npdm'");
Add a new empty line after

2020-12-03 17:45 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                    Logger.Info?.Print(LogClass.ModLoader, $"main.npdm replaced");
If the NPDM is "replaced", you should put this after the next line.

2020-12-28 10:38 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                    modLoadResult.Npdm = new Npdm(npdmFile.OpenRead());
```suggestion
                    modLoadResult.Npdm = new Npdm(npdmFile.OpenRead());
                    
```

2020-12-28 10:44 UTC, AcK77 approved these changes
Lgtm! Thanks!

2020-12-29 19:52 UTC, Thog approved these changes

2020-12-29 19:54 UTC, merged

2021-01-01 20:11 UTC, gdkchan commented
Those changes broke loading unpacked ROMs. They now always fail with `Process initialization returned error "InvalidMemRange".`.

2021-01-01 20:12 UTC, gdkchan commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                if(npdmFile.Exists)
`if (npdmFile.Exists)`.

2021-01-01 20:12 UTC, gdkchan commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                    if(modLoadResult.Npdm != null)
`if (modLoadResult.Npdm != null)`.

2021-01-01 22:07 UTC, gdkchan commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +            for(int i = 0; i < nsos.Length; i++)
`for (int i = 0; i < nsos.Length; i++)`.