gui/gpu: Implement setting and toggle for Aspect Ratio
Ryujinx/Ryujinx pull request #1777
Opened 2020-12-03 05:16 UTC by AcK77

This implement a setting for the aspect ratio to values: 4:3, 16:9 (default value), 21:9, 32:9 and stretched.
You can sets it at runtime using the settings window or using the toggle in the status bar.
It fixes #1597.

ACNH using an ExeFs patch for 21:9 (1080p screen):
![ACNH_219](https://user-images.githubusercontent.com/4905390/100967082-a781c700-352e-11eb-8f3d-b1765f50fec0.PNG)

Some SMO example (without patch):
4:3
![SMO_43](https://user-images.githubusercontent.com/4905390/100967142-caac7680-352e-11eb-9887-83058a957c98.PNG)

16:9
![SMO_169](https://user-images.githubusercontent.com/4905390/100967143-cb450d00-352e-11eb-9c42-941c1bc54e2a.PNG)

21:9
![SMO_219](https://user-images.githubusercontent.com/4905390/100967144-cbdda380-352e-11eb-8b0d-faa7002236ce.PNG)

32:9
![SMO_329](https://user-images.githubusercontent.com/4905390/100967145-cc763a00-352e-11eb-8191-8534101eb4cc.PNG)

Stretched
![SMO_Stretched](https://user-images.githubusercontent.com/4905390/100967140-c97b4980-352e-11eb-8c2c-ac168320ec45.PNG)

2020-12-08 06:14 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +            float ratioX = isStretched ? 1.0f : MathF.Min(1f, _height * (float)NativeHeight * aspectRatio / ((float)NativeHeight         * _width));
```cs
float ratioX = isStretched ? 1.0f : MathF.Min(1f, ((float)_height * aspectRatioX) / ((float)_width * aspectRatioY));
```
(and a similar change on the line below).
The AspectRatio enum would have two extension methods to return floats `AspectRatioX` and `AspectRatioY`. X would return 16, 21 etc and Y would return 9.
`NativeWidth` and `NativeHeight` can be then removed with this change (as the actual dimensions are irrelevant, only the ratio matters).

2020-12-10 01:26 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +            AspectRatio aspectRatio = ConfigurationState.Instance.Graphics.AspectRatio.Value;
I don't the OpenGL backend should be reading the configuration directly. The enum would be better on `Ryujinx.Graphics.GAL`, and the aspect ratio could be passed as argument to the present function.

2020-12-12 12:18 UTC, Thog commented
Need rebase.

2020-12-12 12:20 UTC, Thog approved these changes

2020-12-16 01:07 UTC, gdkchan approved these changes
lgtm, thanks.

2020-12-16 01:18 UTC, riperiperi requested changes
Looks good, just a small complaint about the enum names starting with "To". I think `Fixed` is a good way to preface the fixed aspects, since they can't start with a number.

2020-12-16 01:18 UTC, riperiperi commented on Ryujinx.Common/Configuration/AspectRatioExtensions.cs
> +        To4x3,
I understand you can't start these with numbers, but how about `Fixed4x3` and friends?

2020-12-16 01:18 UTC, riperiperi commented on Ryujinx/Config.json
> +  "aspect_ratio": "To169",
If the enum name is changed, this will have to be too.

2020-12-16 01:18 UTC, riperiperi commented on Ryujinx/Ui/GLRenderer.cs
> +                if (AllocatedWidth > AllocatedHeight * (SwitchPanelHeight * aspectRatio.ToFloat()) / SwitchPanelHeight)
Instead of duplicating this, calculate it once and reuse: `float aspectWidth = SwitchPanelHeight * aspectRatio.ToFloat();` or something.

2020-12-16 01:18 UTC, riperiperi commented on Ryujinx/_schema.json
> +        "To4x3",
Also may need to be changed

2020-12-16 02:13 UTC, riperiperi approved these changes

2020-12-16 02:19 UTC, merged