Extend info printed when guest crashes/breaks execution
Ryujinx/Ryujinx pull request #1845
Opened 2020-12-29 21:42 UTC by shadowninja108

HleProcessDebugger was changed quite a bit to facilitate code reuse between the stack trace and register print code.

2020-12-30 21:56 UTC, AcK77 requested changes

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                Size = size;
```suggestion
                Size        = size;
```

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                } else
```suggestion
                }
                else
```

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                        return $"{v:x16} ({info.ImageDisplay})\t=> {info.SubDisplay}";
```suggestion
                    {
                        return $"{v:x16} ({info.ImageDisplay})\t=> {info.SubDisplay}";
                    }
```

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                    return $"{v:x16}";
```suggestion
                {
                    return $"{v:x16}";
                }
```

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                        return $"{v:x16} ({info.SpDisplay})";
```suggestion
                    {
                        return $"{v:x16} ({info.SpDisplay})";
                    }
```

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                return true;
```suggestion
            {
                return true;
            }

```

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                return true;
```suggestion
            {
                return true;
            }

```

2020-12-30 21:56 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            type &= 0xff; // take lower 8 bits
```suggestion

            type &= 0xff; // take lower 8 bits
```

2020-12-31 20:23 UTC, gdkchan reviewed
General comments:
Comments should start with a upper case character. So "// Try" rather than "// try" (for example).
There are several values formatted as hex missing the 0x prefix. I think they should have the prefix to indicate it is a hex value, rather than decimal or some other base. Example of one such case: `trace.AppendLine($"   {address:x16}");`.

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +
nit: Remove spacing on empty line.

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +                    if(address >= symbol.Value && address < next.Value)
```suggestion
                    if (address >= symbol.Value && address < next.Value)
```

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            symbol = default(ElfSymbol);
I think that can be just `symbol = default;`.

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +
Empty line.

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            public string SpDisplay => SubOffset == 0 ? "SP" : $"SP:-0x{SubOffset:x4}";
Why the minus?

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            info = default(PointerInfo);
Same comment about default.

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            ulong sp = thread.Context.GetX(31);
Same.

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            if(type != 0x0B) // is this pointer within the stack?
```suggestion
            if (type != 0x0B) // is this pointer within the stack?
```

2020-12-31 20:23 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            uint type = (uint)meminfo.State;
I think it would be better to keep it as `MemoryState` instead of casting to uint, would make the core more clear with proper names rather than "magic" constants.

2021-03-13 14:41 UTC, Thog commented on Ryujinx.HLE/HOS/Kernel/Process/HleProcessDebugger.cs
> +            public string SpDisplay => SubOffset == 0 ? "SP" : $"SP:-0x{SubOffset:x4}";
This is to represent the offset of a variable on the stack

2021-03-13 14:47 UTC, Thog commented
Ready for review again

2021-03-15 07:09 UTC, AcK77 approved these changes

2021-05-20 23:25 UTC, riperiperi approved these changes
Some neat improvements here. Good job!

2021-05-20 23:27 UTC, merged