Prevent Windows Display Sleep
Ryujinx/Ryujinx pull request #1850
Opened 2020-12-31 19:47 UTC by EliEron

This PR prevents Windows from turning off the display while a game is running. And also adds an option to enable or disable this behavior. I have decided to enable it by default, since I can't imagine many users want the display to turn off during gameplay. Honestly I even considered not adding a config option at all, especially given that doing so took far more code than the actual feature.

I also looked into implementing this for Linux but determined it too be a too complex, as it requires D-Bus communication, and it would have been hard for me to test since I don't currently have any Linux test environment setup.

The placement and use of the class is based on the WindowsMultimediaTimerResolution class, as that is also a Windows exclusive feature that calls native code. Windows itself keeps tracks of threads that are preventing the display from sleeping and resumes normal behavior when they exit, so it was not necessary to create a method to manually enable the display sleep.

Most of the GUI changes comes from the formatting changes required to keep the ='s lined up with each other. I also noticed some minor errors in the GTK Glade file while I was editing it (One wrong and one missing tooltip) which I decided I might as well fix while I was working in the file.

I am pretty new to Git and code contributions in general so I apologize if I have made any mistakes, and I welcome any feedback both of the code and the GUI changes. I'm not great at naming things so I am very much open to suggestions for a better label for the GUI setting.

This PR partially fixes issue #1829.

2021-01-01 13:59 UTC, Thog requested changes
Mostly lgtm but state need to be restored when going back from emulation context.

Also, I'm not a fan of OS dependent settings like that, it could be nice investigating how to implement the same behaviour on other OSes if possible (otherwise, the setting need to be hidden for non Windows systems on the UI)

2021-01-01 13:59 UTC, Thog commented on Ryujinx/Ui/MainWindow.cs
> +                    WindowsDisplaySleep.Prevent();
The previous execution state should be restored after exiting a emulation.

2021-01-01 18:41 UTC, EliEron commented
I did consider manually restoring the execution state while writing the PR, but in my testing it didn't seem to be necessary. Windows appeared to do so on it's own, after exiting sleep was reenabled without having to change anything. But just to be safe I have now added code to manually restore the execution state.

As for making the GUI option appear on Windows only I am entirely open to that, but have no idea how to code that, figuring out how to add the config option to the GUI was complex enough as it was, with the half a dozen places that had to be modified. 

Maybe it would be better to make it a config file only option? As I doubt a lot of people would want to turn it off in the first place.

2021-01-02 09:42 UTC, AcK77 requested changes
If it was me I’d just disabled sleeping as default when a game is loaded in the emulation context and restore the previous sleeping when the emulation context is closed. I don’t think it needs any configuration field/settings.
Additionally to that, the WindowsDisplaySleeping should be renamed with a more generic name (DisplaySleeping ?). And the OS check needs to be done in this class directly in case someone want to implement other OS specific implementations of this.

2021-01-02 09:42 UTC, AcK77 commented on Ryujinx.Common/System/WindowsDisplaySleep.cs
> +
Remove extra empty line

2021-01-02 09:42 UTC, AcK77 commented on Ryujinx.Common/System/WindowsDisplaySleep.cs
> +                                    EXECUTION_STATE.ES_DISPLAY_REQUIRED);
Remove extra empty line

2021-01-02 10:31 UTC, EliEron commented
Alright I have gone ahead and renamed the file and moved the OS check inside the methods. 

As for the config option I would like to get a consensus from you guys. Personally I wouldn't mind removing the config either, but the issue report this PR was created to resolve specifically asked for an option, and I do know that some really people dislike applications making these kinds of changes without offering any option to turn it off.

2021-01-02 10:37 UTC, AcK77 commented
Well, if you run a game on your PC, there is no sleeping until you close the game.
It’s same here, so there is no good point to let the system sleeping while you running a game under the emulator... I don’t see a situation where this could be useful!

2021-01-02 12:39 UTC, EliEron commented
Good point, and like I said I'm certainly not against it personally.  Alright I've gone ahead and removed the GUI changes. 

Hopefully that should resolve both your and Thog's main concerns with the code.

2021-01-02 22:21 UTC, AcK77 requested changes

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +
Remove extra spaces

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +
Remove extra spaces

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                Language                   = new ReactiveObject<Language>();
Remove extra spaces, aligment is done between `{ }` and not on the whole file

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +
Remove extra spaces

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/System/DisplaySleep.cs
> +            if (Environment.OSVersion.Platform == PlatformID.Win32NT)
You should use `if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))`

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/System/DisplaySleep.cs
> +            if (Environment.OSVersion.Platform == PlatformID.Win32NT)
You should use `if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))`

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                Version                    = ConfigurationFileFormat.CurrentVersion,
Remove extra spaces, aligment is done between `{ }` and not on the whole file

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +            Graphics.ResScale.Value                 = 1;
Remove extra spaces, aligment is done between `{ }` and not on the whole file

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +            Graphics.ResScale.Value                 = configurationFileFormat.ResScale;
Remove extra spaces, aligment is done between `{ }` and not on the whole file

2021-01-02 22:21 UTC, AcK77 commented on Ryujinx/Ui/SettingsWindow.cs
> +            ConfigurationState.Instance.Logger.EnableError.Value                = _errorLogToggle.Active;
Remove extra spaces, aligment is done between `{ }` and not on the whole file

2021-01-03 08:45 UTC, EliEron commented
Addressed all of the comments, hopefully it should be ready for merge now.

2021-01-08 08:48 UTC, AcK77 commented
Needs a rebase

2021-01-08 13:13 UTC, EliEron commented
Rebase has been completed, I also squashed all of the commits since the history was getting quite messy.

2021-01-11 15:31 UTC, AcK77 approved these changes
Lgtm!

2021-01-13 17:52 UTC, Xpl0itR approved these changes

2021-01-23 13:04 UTC, Thog approved these changes

2021-01-24 23:02 UTC, merged