services: add "apm:p"
Ryujinx/Ryujinx pull request #1854
Opened 2021-01-01 22:10 UTC by macabeus

Closes https://github.com/Ryujinx/Ryujinx/issues/1846

With this PR, there is no more error about missing `apm:p`, but the games that did this error (such as [2048](https://github.com/FlagBrew/2048)) now there is this following error:
```
Exception has occurred: CLR/System.ArgumentOutOfRangeException
An exception of type 'System.ArgumentOutOfRangeException' occurred in Ryujinx.Graphics.Gpu.dll but was not handled in user code: 'Specified argument was out of the range of valid values.'
   at Ryujinx.Graphics.Gpu.Synchronization.SynchronizationManager.RegisterCallbackOnSyncpoint(UInt32 id, UInt32 threshold, Action callback) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.Graphics.Gpu\Synchronization\SynchronizationManager.cs:line 80
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.AndroidFence.RegisterCallback(GpuContext gpuContext, Action callback) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\Types\AndroidFence.cs:line 73
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.PostFrameBuffer(Layer layer, BufferItem item) in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 351
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.Compose() in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 290
   at Ryujinx.HLE.HOS.Services.SurfaceFlinger.SurfaceFlinger.HandleComposition() in C:\Users\macabeus\ApenasMeu\Ryujinx\Ryujinx.HLE\HOS\Services\SurfaceFlinger\SurfaceFlinger.cs:line 227
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

I don't know if it's another error, or it's because of the implementation of `apm:p`.

2021-01-01 22:11 UTC, macabeus commented on Ryujinx.HLE/HOS/Services/Apm/IManagerPrivileged.cs
> +        }
I didn't know what should I do with `GetPerformanceMode` and `IsCpuOverclockEnabled`. I kept it because I'm using as base `IManager` and these methods are mandatory - but I think that it doesn't exist on `apm:p`.
Maybe we could change `IManager` to not require these methods?

2021-01-02 09:35 UTC, AcK77 requested changes

2021-01-02 09:35 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Apm/IManagerPrivileged.cs
> +    [Service("apm:p")] // 8.0.0-
```suggestion
    [Service("apm:p")] // 1.0.0-7.0.1
```

2021-01-02 09:35 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Apm/IManagerPrivileged.cs
> +    class IManagerPrivileged : IManager
For a proper implementation you should do the same (copy/paste) as IManager/ManagerServer because your current implementation is totally wrong! You just needs to remove uneeded calls from the copy/pasted code.

2021-01-02 14:31 UTC, macabeus commented on Ryujinx.HLE/HOS/Services/Apm/IManagerPrivileged.cs
> +    class IManagerPrivileged : IManager
@AcK77 Okay. I removed the unneeded calls on my pasted code, in the methods `GetPerformanceMode` and `IsCpuOverclockEnabled`. Now they return a dummy/default value.
Should I do something more?

2021-01-02 15:08 UTC, AcK77 approved these changes
Lgtm! Thanks!

2021-01-02 15:10 UTC, Thog approved these changes
lgtm, thanks 👍

2021-01-02 15:11 UTC, merged