settings: add Show Confirm Exist toggle
Ryujinx/Ryujinx pull request #1856
Opened 2021-01-02 02:28 UTC by macabeus

Solves https://github.com/Ryujinx/Ryujinx/issues/1853

![image](https://user-images.githubusercontent.com/9501115/103449586-130aa180-4c5f-11eb-86a7-64dfe58dec60.png)

2021-01-02 02:31 UTC, macabeus commented on Ryujinx/Ui/MainWindow.cs
> +            if (!_gameLoaded || !ConfigurationState.Instance.ShowConfirmExit || GtkDialog.CreateExitDialog())
I know that I'm calling `!ConfigurationState.Instance.ShowConfirmExit` always times that is called `GtkDialog.CreateExitDialog`.... and it looks a little ugly for me.
Maybe we could do it better?

2021-01-02 06:05 UTC, EmulationFanatic commented
The "Check for" text doesn't make sense here. The option should just be 'Show "Confirm Exit" Dialog'

2021-01-02 09:46 UTC, AcK77 requested changes

2021-01-02 09:46 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 19;
Version 19 is currently the ldn-2 build one. Please use 20 to avoid any issues with the ldn-2 build.

2021-01-02 10:29 UTC, SeraUQ commented
Would also be good to add the appropriate stuff to `/Ryujinx/Config.json`  and  `/Ryujinx/_schema.json `

2021-01-02 13:48 UTC, macabeus commented
@EmulationFanatic @SeraUQ @AcK77 Done.

2021-01-07 21:36 UTC, Thog approved these changes
lgtm

2021-01-08 08:41 UTC, AcK77 commented
Needs a rebase0

2021-01-09 03:57 UTC, macabeus commented
@AcK77 Done

2021-01-11 15:04 UTC, AcK77 approved these changes
Lgtm!

2021-01-13 17:48 UTC, Xpl0itR approved these changes
lgtm, thanks

2021-01-14 22:30 UTC, merged