config: add option to show/hide console
Ryujinx/Ryujinx pull request #1866
Opened 2021-01-04 21:20 UTC by macabeus

Closes https://github.com/Ryujinx/Ryujinx/issues/1669

![image](https://user-images.githubusercontent.com/9501115/103580770-ab5c8c80-4ed2-11eb-99f9-e730a5de8b8f.png)

2021-01-04 21:21 UTC, macabeus commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 21;
19 ->  ldn-2
20 -> https://github.com/Ryujinx/Ryujinx/pull/1856

2021-01-04 21:22 UTC, macabeus commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +            ShowConsole.Value                      = false;
Since it's a feature for developers, I'm setting it as disabled by default

2021-01-04 21:22 UTC, macabeus commented on Ryujinx.Common/Logging/Logger.cs
> +        }
I don't know if it's the best place to put these functions...

2021-01-04 23:24 UTC, EmulationFanatic commented
Just a suggestion here: instead of "Show Console" as the option, "Show Console Window" might be more descriptive?

2021-01-04 23:31 UTC, SeraUQ commented
this PR breaks the linux build
```
00:00:00.132 |E| Application : Unhandled exception caught: System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Ryujinx.Common.Logging.Logger.GetConsoleWindow()
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 124
```

2021-01-05 02:04 UTC, macabeus commented
@SeraUQ Could you test again, please?

2021-01-05 02:13 UTC, SeraUQ commented
@macabeus its the same error as before
```
00:00:00.152 |E| Application : Unhandled exception caught: System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32.dll: cannot open shared object file: No such file or directory
   at Ryujinx.Common.Logging.Logger.GetConsoleWindow()
   at Ryujinx.Program.Main(String[] args) in C:\projects\ryujinx\Ryujinx\Program.cs:line 124
```

2021-01-05 02:14 UTC, jduncanator commented
This code shouldn't live in the logging code base, it should live under a separate area, perhaps platform specific extensions. The logger really has nothing to do with the console, except for being one of many targets for the log output.

2021-01-08 08:38 UTC, AcK77 commented
Needs a rebase

2021-01-09 03:53 UTC, macabeus commented
@AcK77 Done

2021-01-11 15:29 UTC, AcK77 requested changes

2021-01-11 15:29 UTC, AcK77 commented on Ryujinx.Common/Platform/Windows.cs
> +    internal class WindowsPlatform: Platform
This should be in `Ryujinx.Common.System` and you should do something like `ForceDedicatedGpu.cs`.
And you should rename the class to something like `ConsoleHelper` or `ConsoleManager`, etc...

2021-01-11 15:29 UTC, AcK77 commented on Ryujinx.Common/Platform/Windows.cs
> +
remove extra empty line

2021-01-11 15:29 UTC, AcK77 commented on Ryujinx.Common/Platform/Platform.cs
> +    public class Platform
This is not really usefull

2021-01-11 15:29 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
It could be nice to handle the OS check somewhere else? In the "Console" class maybe?
With something like `ConsoleManager.IsHideSupported()`?

2021-01-11 15:29 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            if (ConfigurationState.Instance.ShowConsole)
Same for this logic, maybe `ConsoleManager.RefreshConsoleState()` or something like that?

2021-01-14 02:49 UTC, macabeus commented on Ryujinx.Common/Platform/Platform.cs
> +    public class Platform
What is not exactly useful? The class `Platform`?
How should I do?

2021-01-14 02:49 UTC, macabeus commented on Ryujinx.Common/Platform/Platform.cs
> +    public class Platform
@AcK77 What is not exactly useful? The class `Platform`?
How should I do?

2021-01-14 02:54 UTC, macabeus commented on Ryujinx.Common/Platform/Platform.cs
> +    public class Platform
I made this class in order to inherit it on `Windows` (and in the future, someone can create a Linux, etc).
And I'm using `Platform` here:
```c#
public static Platform Instance { get; }
```

2021-01-14 03:03 UTC, macabeus commented on Ryujinx.Common/Platform/Windows.cs
> +    internal class WindowsPlatform: Platform
@AcK77 Well... It's a different approach that @jduncanator suggested: https://discord.com/channels/410208534861447168/410432399500115968/795843020959252490

Which should we follow?

2021-01-27 23:56 UTC, AcK77 commented on Ryujinx.Common/Platform/Windows.cs
> +    internal class WindowsPlatform: Platform
Just follow what's already done here: https://github.com/Ryujinx/Ryujinx/tree/master/Ryujinx.Common/System
We used different classes which contains OS specific things.

2021-02-20 00:45 UTC, AcK77 commented
@macabeus are you still interested to working on this?

2021-02-20 23:47 UTC, macabeus commented
@AcK77 I'm focusing only on the website now, so I'm not working on this PR anymore

2021-04-08 00:48 UTC, AcK77 commented
Superseded by #2082

2021-04-08 00:48 UTC, closed without merging