Add support for inline software keyboard
Ryujinx/Ryujinx pull request #1868
Opened 2021-01-05 17:50 UTC by Caian

This PR implements the inline protocol used by the `SoftwareKeyboardApplet` to talk to games like Gnosia (Ryujinx/Ryujinx-Games-List#2563) and Monster Hunter Gen U (#1640). The lack of this protocol results in bad initialization of the software keyboard applet and, very likely, a hard lock inside the game.

This implementation of the Inline keyboard has support for Ok and Cancel operations and relies on the input GUI to acquire user input while the game runs in the background:

![s1](https://user-images.githubusercontent.com/2220062/103680194-90d2f380-4f64-11eb-826e-d7085855a1fd.PNG)

Therefore it does draw a keyboard on top of the game, which (for now) can lead to minor graphical glitches:

![s2](https://user-images.githubusercontent.com/2220062/103680511-09d24b00-4f65-11eb-9a7d-a9128e35f2c4.PNG)

These glitches do not break the game and may only appear when the input is requested. They may be fixed by implementing the `IApplicationDisplayService.GetIndirectLayerImageMap` method that I stubbed.

2021-01-06 11:18 UTC, Caian commented
PR updated to fix the graphical glitches. Now the `GetIndirectLayerImageMap` method fills the response buffer with zeros.

2021-01-06 19:50 UTC, Doctorwho1909 commented
![image](https://user-images.githubusercontent.com/64975148/103813722-f099cf00-5036-11eb-8c09-7119245835ba.png)
works very well on monster hunter and dark souls

2021-01-06 21:01 UTC, Caian commented
Great to hear @Doctorwho1909 

So, if approved, this may change the status of Ryujinx/Ryujinx-Games-List#72 and Ryujinx/Ryujinx-Games-List#511

2021-01-06 21:43 UTC, gdkchan reviewed
Very nice to see this fixed, just a couple of comments.

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineKeyboardRequest.cs
> +
nit: Remove empty line.

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                writer.Write((uint)0x0); // Reply code
it might be a good idea to create a enum with those reply codes, and use the enum instead (to make more clear what the values actually mean).

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +            // Obtain the validation status response,
Should be `.` rather than `,` at the end (I know its a existing typo, but could fix it aswell since you touched that line).

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +            // WARNING Do not invoke applet state changes because the inline keyboard
```suggestion
            // WARNING: Do not invoke applet state changes because the inline keyboard
```

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +            // is expected to be always running once it is initialized
```suggestion
            // is expected to be always running once it is initialized.
```

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                        case (InlineKeyboardRequest)0: // Unknown request sent by some games after calc
I would add `Unknown0 = 0` to the enum just to make this line nicer.

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                Logger.Error?.PrintStub(LogClass.ServiceAm, $"Invalid Software Keyboard request {request} during state {_state}!");
```suggestion
                Logger.Error?.Print(LogClass.ServiceAm, $"Invalid Software Keyboard request {request} during state {_state}!");
```

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardDictSet.cs
> +    [StructLayout(LayoutKind.Sequential, Pack=4)]
```suggestion
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
```

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceDisplay, $"GetIndirectLayerImageMap");
```suggestion
            Logger.Stub?.PrintStub(LogClass.ServiceDisplay, "GetIndirectLayerImageMap");
```

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceDisplay, $"GetIndirectLayerImageMap");
I think the log already includes the method name, passing it here might be redundant.

2021-01-06 21:43 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +        [Command(2450)]
This seems unrelated to the swkbd changes, why was it implemented now?

2021-01-06 22:22 UTC, Caian commented
Thanks for the feedback @gdkchan I'll work on those.

2021-01-06 22:36 UTC, Caian commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +        [Command(2450)]
When using the inline keyboard, the game is responsible for creating and rendering a layer with the keyboard image. The pixels of the image are filled by the Display Service using the handle given by `ILibraryAppletAccessor.GetIndirectLayerConsumerHandle`.

2021-01-07 02:33 UTC, Caian commented
PR updated with @gdkchan review.

2021-01-07 06:01 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +        private static readonly uint maxStrLenUTF8 = 0x7D4;
```suggestion
        private const uint MaxStrLenUTF8 = 0x7D4;
```

2021-01-07 06:01 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +        private static readonly uint maxStrLenUTF16 = 0x3EC;
```suggestion
        private const uint MaxStrLenUTF16 = 0x3EC;
```

2021-01-07 06:01 UTC, gdkchan commented on Ryujinx.Common/Logging/LogClass.cs
> +        ServiceDisplay,
Why not use `ServiceVi`?

2021-01-07 09:34 UTC, Caian commented on Ryujinx.Common/Logging/LogClass.cs
> +        ServiceDisplay,
Agree

2021-01-07 18:29 UTC, gdkchan commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +        private static readonly uint maxStrLenUTF8 = 0x7D4;
This was not fully addressed, constants should start in upper case.

2021-01-07 20:02 UTC, gdkchan commented
Tested Gnosia and I get this after trying to start the game:
```
ServiceAm OnBackgroundInteractiveData: Invalid Software Keyboard request Finalize during state Ready!
```
It seems to softlock after that.

2021-01-07 20:13 UTC, Caian commented
> Tested Gnosia and I get this after trying to start the game:
> 
> ```
> ServiceAm OnBackgroundInteractiveData: Invalid Software Keyboard request Finalize during state Ready!
> ```
> 
> It seems to softlock after that.
> Fortunately the save file is created, and its possible to start the game if you restart the emulator and load the created save file. However it always softlocks the first time you start a new game from the "New Game" menu.

That's odd, which artifact did you use?

2021-01-07 20:17 UTC, gdkchan commented
> 
> 
> > Tested Gnosia and I get this after trying to start the game:
> > ```
> > ServiceAm OnBackgroundInteractiveData: Invalid Software Keyboard request Finalize during state Ready!
> > ```
> > 
> > 
> > It seems to softlock after that.
> > Fortunately the save file is created, and its possible to start the game if you restart the emulator and load the created save file. However it always softlocks the first time you start a new game from the "New Game" menu.
> 
> That's odd, which artifact did you use?

I built it myself locally.

2021-01-07 20:28 UTC, Caian commented
> > > Tested Gnosia and I get this after trying to start the game:
> > > ```
> > > ServiceAm OnBackgroundInteractiveData: Invalid Software Keyboard request Finalize during state Ready!
> > > ```
> > > 
> > > 
> > > It seems to softlock after that.
> > > Fortunately the save file is created, and its possible to start the game if you restart the emulator and load the created save file. However it always softlocks the first time you start a new game from the "New Game" menu.
> > 
> > 
> > That's odd, which artifact did you use?
> 
> I built it myself locally.

From the branch itself or merging with master (if so, which hash)?

Could you tell me version of the game are you testing, as well as the system version?

ty

2021-01-07 20:30 UTC, gdkchan commented
Game version if 1.0.0, system version is 9.0.1, I merged with master as your branch alone doesn't build here (`Fill` method can't be found on `MemoryManager` or something like that). Have you managed to actually start a game past the profile creation screen?

2021-01-07 20:48 UTC, Caian commented
> Game version if 1.0.0, system version is 9.0.1, I merged with master as your branch alone doesn't build here (`Fill` method can't be found on `MemoryManager` or something like that). Have you managed to actually start a game past the profile creation screen?
> 
> > You receive this message when the game is starting or when you enter the new game menu?
> 
> When the game is starting from the New game menu. It works if you go from the Continue menu with a save already created.

No, I stopped after successfully inputting the name, but I managed to reproduce the issue and I'll see what I can do.

ty

2021-01-07 21:16 UTC, Caian commented
Solved and re-tested for Gnosia (passing the char creation this time) and Monster Hunter Gen U (char creation and in-game chat)

As for the building issue, I didn't want to merge master to this branch and trash the commit log, but I needed that `Fill` method to fix the graphical glitches mentioned earlier.

2021-01-07 21:17 UTC, gdkchan commented
You can just rebase it on top of master, this is not going to "trash the commit log".

2021-01-07 21:18 UTC, gdkchan commented
I will approve after the names for the consts are fixed, as I commented before.

2021-01-07 21:28 UTC, Caian commented
> I will approve after the names for the consts are fixed, as I commented before.

Sorry, done.

2021-01-07 21:29 UTC, gdkchan approved these changes
lgtm, thanks. Awesome work 👍

2021-01-07 21:34 UTC, Thog reviewed
lgtm, thanks 👍

2021-01-07 21:35 UTC, Thog approved these changes

2021-01-07 22:08 UTC, gdkchan commented
Fate EXTELLA/LINK is still broken if you are interested. It calls the software keyboard, but it never actually shows. It also calls `GetIndirectLayerImageMap` non-stop (I believe that is normal?)

2021-01-07 22:16 UTC, Caian commented
> Fate EXTELLA/LINK is still broken if you are interested. It calls the software keyboard, but it never actually shows. It also calls `GetIndirectLayerImageMap` non-stop (I believe that is normal?)

I'll take a look as well, thanks.

The thing with `GetIndirectLayerImageMap` is normal because, as far as I can tell, the call is in the render loop so the keyboard doesn't appear laggy.

2021-01-08 08:37 UTC, AcK77 requested changes
Nice job for a first contribution, but there are still some things to fix for consistency with the project!

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +            uint cursor = WriteString(text, writer, maxSize, encoding);
Add a new empty line after

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                return stream.ToArray();
add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.MovedCursorUtf8V2, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.ChangedStringUtf8V2, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.MovedCursorV2, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.ChangedStringV2, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.UnsetCustomizedDictionaries, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.ReleasedUserWordInfo, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.UnsetCustomizeDic, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.DecidedEnterUtf8, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.MovedCursorUtf8, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.ChangedStringUtf8, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.DecidedCancel, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.DecidedEnter, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.ChangedString, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.Default, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.MovedCursor, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.MovedTab, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                              InlineKeyboardResponse.FinishedInitialize, writer);
new line isn't really needed.

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +            // TODO: a better way would be handling the background creation properly
```suggestion
            // TODO: A better way would be handling the background creation properly
```

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                    return;
Add new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceVi);
The stub logging should be placed before the last `return`

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            var numBuffs = context.Request.ReceiveBuff.Count;
Why don't use an explicit cast here and var name like "buffersCount" ?

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +        // GetIndirectLayerImageMap(u64 width, u64 height, u64 handle, u64 ??, u64 ??, u64 ??) -> nothing??
You should use this : `GetIndirectLayerImageCropMap(f32, f32, f32, f32, u64, u64, u64, nn::applet::AppletResourceUserId, pid) -> (u64, u64, buffer<bytes, 0x46>)`

And then determine values with this following switchbrew description:

```
Takes a PID-descriptor, an type-0x46 buffer, two s64s width/height, then two u64s: <output from AM GetIndirectLayerConsumerHandle>, and AppletResourceUserId. Returns two output s64s, which are copied to output u64s by official sw.

Official sw sets the width/height using input s32s.

Calls the same func as #GetIndirectLayerImageCropMap internally, with the input floats set to 0.0f, then 1.0f for the rest.
```

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            if (numBuffs != 1)
Why this check? Is it based on RE or it's just an hack to avoid an issue ?

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +                return ResultCode.Success;
Add a new empty line before

2021-01-08 08:37 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            var layerBuffSz = layerBuff.Size;
please use explicit casting here and better var names, we usually names "Position" instead of "Ptr" and "Size" instead of "Sz"

2021-01-08 09:38 UTC, Caian commented
> Nice job for a first contribution, but there are still some things to fix for consistency with the project!

Thank you! I'll work on those comments as well.

2021-01-08 12:07 UTC, Caian commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceVi);
There is an early return for the function in the line 251, should it be adapted for the sake of always showing the stub message?

2021-01-08 12:09 UTC, jduncanator commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceVi);
I think this is fine.

2021-01-08 12:17 UTC, Caian commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            if (numBuffs != 1)
It is a safeguard because I don't know if the method can be called with a different buffer configuration, specially when I'm accessing indices.

I also know that it is harmless to do nothing when working with the keyboard layer, but I can't say the same about other possible uses, so I preferred to do nothing if anything is unexpected.

2021-01-08 12:46 UTC, Caian commented
I fixed the problem with Fate EXTELLA/LINK with some caveats and resolved most comments from @AcK77, I'm still waiting for a two of them.

Some games, like Gnosia and Monster Hunter will send a Calc request without the intention of getting a text back, which makes the input dialog to pop ahead of time. This is not an issue, just an annoyance, which I circumvented by just sending the default text of the Applet (`Ryujinx`).

Because of this, some games (like Gnosia in the char creation screen) will come with `Ryujinx` pre-filled, which can be changed normally. I decided to go this way to avoid any potential locks.

2021-01-08 13:25 UTC, EmulationFanatic commented
Confirmed fixed in Fate/EXTELLA LINK. Nice work!
![image](https://user-images.githubusercontent.com/62343878/104020323-3dd28980-517a-11eb-9acb-d3477a4fe206.png)

2021-01-09 00:28 UTC, Caian commented
Retested Dark Souls Remastered with the new version.

2021-01-11 15:18 UTC, AcK77 requested changes
One more pass on the code style, and some details to the buffer count thing.

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +
remove extra empty line

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +                    break;
```suggestion
                {
                    break;
                }
```

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                                _encoding = Encoding.UTF8;
Add brackets

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                                showKeyboard = true;
Add brackets

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                            string inputText = (!string.IsNullOrWhiteSpace(
This could be in one line

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                                    SubmitText = (!string.IsNullOrWhiteSpace(
This could be in one line

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                                    _interactiveSession.Push(InlineResponses.DecidedEnterUtf8(inputText));
Add brackets

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +                                    _interactiveSession.Push(InlineResponses.DecidedEnter(inputText));
Add brackets

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +
remove extra empty line

2021-01-11 15:18 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            if (buffersCount != 1)
Since the call should always returns a buffer... The case where the buffer count is different than 1 is near to impossible.
I think it's fine to remove all this logic, we don't do that in any other calls which use buffers.

2021-01-11 18:27 UTC, AcK77 approved these changes

2021-01-11 18:27 UTC, merged