Implement Sfdnsres.GetAddrInfo
Ryujinx/Ryujinx pull request #1909
Opened 2021-01-13 17:34 UTC by WilliamWsyHK

This PR is to implement `nn::socket::resolver::IResolver(6)`, which would close #637.

2021-01-17 21:46 UTC, jduncanator requested changes
Left a few comments, didn't do an indepth review, just some code improvements from a brief glance over it :)

Thanks for your first contribution!

2021-01-17 21:46 UTC, jduncanator commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +        private AddrInfo ParseAddrInfoFromBytes(byte[] addrInfoBytes)
This can be a `ReadOnlySpan<byte>`, no need to pass in a full `byte[]`.

2021-01-17 21:46 UTC, jduncanator commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +            }
Once you make the argument a ROS, you can use the `BinaryPrimitives` class here to simplify all this logic. For example:

```
int flags = BinaryPrimitives.ReadUInt32BigEndian(addrInfo); // Where addrInfo is a ReadOnlySpan passed into the function
```

2021-01-17 21:46 UTC, jduncanator commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo.cs
> +    class AddrInfo
This should be a struct, and `sockaddr` should also be implemented, and then changed to `public SockAddr Addr;`.

With it being a struct, it may also mean it's directly blittable from a Span, rather than having to use the `ParseAddrInfoFromBytes` function.

2021-01-23 01:27 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +        private AddrInfo ParseAddrInfoFromBytes(byte[] addrInfoBytes)
Agreed. This would be changed

2021-01-23 01:27 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +            }
Oh I didn't notice in C# we already have such function!

2021-01-23 01:31 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo.cs
> +    class AddrInfo
I really would like it could be directly blittable, but given that the fact `struct sockaddr *ai_addr` is a pointer to either IPv4 / IPv6, and knowing that NS only has IPv4 currently, should we just pretend it to be always 4 bytes of IPv4, or leave it as dynamic `byte[]` with either IPv4/IPv6?

2021-01-28 00:09 UTC, AcK77 reviewed
Do this implementation based on reverse engineering?
Thanks for your first contribution.

2021-01-28 00:09 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +                context.Memory.Write((ulong)bufferPosition, IPAddress.HostToNetworkOrder((int)0xBEEFCAFE));
Why don't use `BinaryPrimitives.ReverseEndianness()` instead of `IPAddress.HostToNetworkOrder()` ?
(same for following lines)

2021-01-28 00:09 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +        private long SerializeAddrInfo(ServiceCtx context, long offset, AddrInfo hints, IPAddress address)
```suggestion
        private long SerializeAddrInfo(ServiceCtx context, long offset, AddrInfo addrInfo, IPAddress address)
```

2021-01-28 00:09 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo.cs
> +        public System.Net.Sockets.AddressFamily Family;
use a `using` for `System.Net.Sockets`

2021-01-28 00:09 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo.cs
> +        // public int AddrLen;
Why is it commented ?

2021-01-28 00:30 UTC, jduncanator commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +                context.Memory.Write((ulong)bufferPosition, IPAddress.HostToNetworkOrder((int)0xBEEFCAFE));
You can also just get a `Span` from the `context.Memory` and use `BinaryPrimitives.WriteUInt32BigEndian`.

2021-01-29 13:25 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo.cs
> +        // public int AddrLen;
`Addrs` itself already contains enough length while being parsed, and if serializing, the correct length is also written base on `Array.Length`

2021-01-29 13:27 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +                context.Memory.Write((ulong)bufferPosition, IPAddress.HostToNetworkOrder((int)0xBEEFCAFE));
Hmm must be thinking in C way when writing this line. I will take the `Span` way then.

2021-01-29 13:29 UTC, WilliamWsyHK commented
Yes the implementation is base on reverse engineering, and the whole code is working as in the normal C code, except N was doing some wrapping on the BSD socket library.

2021-01-29 13:42 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +        private long SerializeAddrInfo(ServiceCtx context, long offset, AddrInfo hints, IPAddress address)
I think I will call it as `hintsAddrInfo` instead, to let the caller knowing the intent that it is acting like the C `getaddrinfo`, which requires `hints` to work.

2021-02-07 17:50 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/Types/AddrInfo.cs
> +    class AddrInfo
I don't think Nintendo will bring support for IPv6 later so I think it could be nice to assume ipv4 all the time

2021-02-07 17:56 UTC, Thog requested changes
I think some stuffs could be turned into structure (example AddrInfo). Some logics are missing part because of no reverse. Otherwise lgtm

2021-02-07 17:56 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +            bufferPosition += canonName.Length;
This is highly ineffective. I think that you could do a structure for the non variable parts of this and just write the structure (casting the WritableRegion memory span to that structure and just writing it)

2021-02-07 17:56 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +            bool enableNsdResolve = context.RequestData.ReadInt32() == 1;
NSD resolution need to be supported here

2021-02-20 00:48 UTC, AcK77 commented
@WilliamWsyHK are you still interested to working on this?

2021-02-20 00:51 UTC, WilliamWsyHK commented
Yes, will try to get some code updated these 2 days

2021-03-01 19:49 UTC, EmulationFanatic commented
> Yes, will try to get some code updated these 2 days

Hi @WilliamWsyHK we haven't forgotten your PR here :) we hope you haven't forgotten it either!

2021-03-24 17:54 UTC, AcK77 commented
Superseded by #2130

2021-03-24 17:54 UTC, closed without merging