Add the TamperMachine module for runtime mods and cheats
Ryujinx/Ryujinx pull request #1928
Opened 2021-01-18 12:31 UTC by Caian

This is a draft implementation of a small programmable thread that enables runtime memory modifications and cheats. It is named Tamper instead of Cheat because some modifications are not necessarily cheats, they alter the game to provide differents experience, some possible only with emulators, like unlocked FPS mods.

It is integrated with the `ModLoader` class and shared the mod folder already available in Ryujinx.

It's initial implementation aims to support Atmosphere style cheats: 
https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/features/cheats.md

Only a subset of the Atmosphere OpCodes are implemented, but still enable support for the 60fps mod in MHGU:
![60fps](https://user-images.githubusercontent.com/2220062/104914669-41ca8c80-596e-11eb-8367-04796a1179b9.PNG)

2021-01-20 08:37 UTC, mageven commented
Related issue #1513

2021-02-17 19:55 UTC, AcK77 requested changes
I’ve just reviewed the code style and haven’t tested the build. But amazing works there!
Maybe you should put everything in a `TamperMachine` folder instead of `Tamper\Atmosphere` since there is no other cheats format available!

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +        }
```suggestion
            }
```

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                    for (int i = 0; i < QueryCheatsDir(mods, modDir); i++)
Could be nice to add brackets

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                        for (int i = 0; i < QueryCheatsDir(mods, cheat); i++)
Could be nice to add brackets

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                    if (cheat.Exists)
Could you add a new empty line before each if In the previous lines?

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +            if (!cheatsDir.Exists) return 0;
Put the return on a new line and add brackets

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                if (!StrEquals(CheatExtension, file.Extension))
Add brackets

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                if (!UInt64.TryParse(cheatId, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ulong buildId))
```suggestion
                if (!ulong.TryParse(cheatId, NumberStyles.HexNumber, CultureInfo.InvariantCulture, out ulong buildId))
```
Can do the job?

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +
Remove extra empty line

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +
Remove extra empty line

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +
Remove extra empty line

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ProgramLoader.cs
> +                tamperInfo = null;
Add new empty line after

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ProgramLoader.cs
> +                tamperInfo = null;
Add new empty line after

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ProgramLoader.cs
> +                tamperInfo = null;
Add new empty line after

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ProgramLoader.cs
> +                    tamperInfo = null;
Add new empty line after

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/ProgramLoader.cs
> +                tamperInfo = null;
Add new empty line after

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/CodeEmitters/KeyPressConditional.cs
> +            return new InputMask((long)inputMask, context.PressedKeys);
Add empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/CodeEmitters/MemoryConditional.cs
> +        private const int ValueImmediate4 = 8;
Those 2 following vars are Size right? If yes maybe you should rename it!

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/CodeType.cs
> +        DebugLog = 0xFFF,
```suggestion
        DebugLog = 0xFFF
```

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/MemoryHelper.cs
> +            return new Pointer(addressImmediateValue, context.Process);
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/MemoryHelper.cs
> +            return new Pointer(finalAddressValue, context.Process);
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/MemoryHelper.cs
> +            return new Pointer(finalAddressValue, context.Process);
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/MemoryHelper.cs
> +            return new Pointer(finalAddressValue, context.Process);
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/MemoryHelper.cs
> +            return EmitPointer(offsetImmediate, context);
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/MemoryHelper.cs
> +            return EmitPointer(offsetRegister, offsetImmediate, context);
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/Atmosphere/MemoryHelper.cs
> +            return EmitPointer(offsetRegister, offsetImmediate, context);
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/TamperMachine.cs
> +        public TamperMachine()
```suggestion
        public TamperMachine() { }
```

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/TamperMachine.cs
> +                    return;
New empty line before

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/TamperMachine.cs
> +                if (input.PlayerId == PlayerIndex.Player1)
What about Handled ?

2021-02-17 19:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/TamperMachine.cs
> +            // TODO: Fallback to another?
I’m pretty sure games will crashes (or asks for) if there is nothing as Player1 or Handled

2021-02-20 15:57 UTC, Caian commented
Thank you for the feedback @AcK77 I indeed organized the namespaces expecting something other than Atmosphere could be implemented. But I can undo this until something is actually implemented.

2021-03-04 16:14 UTC, Mou-Ikkai commented
I approve of it, I attempted the 9,999,999 Gold/SP cheat for SSBU and it works.
(With a bit of buying.)
![image](https://user-images.githubusercontent.com/45863583/109993807-a9e4f000-7cda-11eb-9550-a96b03a0ae4b.png)

2021-03-22 18:47 UTC, AcK77 approved these changes
Lgtm after those little nits will be fixed!

2021-03-22 18:47 UTC, AcK77 commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +            // TODO: Disable PPTC?
Unless you are sure it will not cause any crashes, you should disable PPTC. (same comment for the `TODO` above)

2021-03-22 18:47 UTC, AcK77 commented on Ryujinx.HLE/HOS/ProgramLoader.cs
>                  return false;
New empty line before is still missing.

2021-03-22 18:47 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/CodeEmitters/Arithmetic.cs
> +                case Not: Emit(typeof(OpNot<>)            ); break;
```suggestion
                case Not: Emit(typeof(OpNot<>)                      ); break;
```

2021-03-22 18:47 UTC, AcK77 commented on Ryujinx.HLE/HOS/Tamper/CodeEmitters/Arithmetic.cs
> +                case Mov: Emit(typeof(OpMov<>)            ); break;
```suggestion
                case Mov: Emit(typeof(OpMov<>)                      ); break;
```

2021-03-23 13:43 UTC, Caian commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +            // TODO: Disable PPTC?
This is a comment from early development that I should have removed. The Tamper Machine will refuse to modify game code, so it can be an alternative to ExeFS mods that do disable PPTC. Most cheats don't modify code and it would be a shame to preemptively disable PPTC.

2021-03-26 22:53 UTC, Thog approved these changes
lgtm, thanks 👍

2021-03-27 14:12 UTC, merged