Implemented ISystemSettingsServer.IsUserSystemClockAutomaticCorrectionEnabled
Ryujinx/Ryujinx pull request #1932
Opened 2021-01-19 13:43 UTC by Joshi234

This is used when a game wants to check if the system clock is synced with a server. Right now there is as far as I know no game that uses it, but some homebrew uses it

2021-01-19 18:02 UTC, AcK77 requested changes

2021-01-19 18:02 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
> +        [Command(205)]
Why there is this call since it's already implemented in https://github.com/Ryujinx/Ryujinx/pull/1933 ?

2021-01-19 18:02 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +        public ResultCode IsUserSystemClockAutomaticCorrectionEnabled(ServiceCtx context)
This call miss the symbol as comment

2021-01-19 18:02 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +            context.ResponseData.Write(true);
It could be nice to explain why you sets it to `true`, add a logging to say it's stubbed

2021-01-19 18:02 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +            return ResultCode.Success;
Add an empty line before

2021-01-20 18:55 UTC, AcK77 requested changes
It's still not based on any RE, but since it's not an important call, I guess it's fine as-is...
There are some things to fix.

2021-01-20 18:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +        // // IsUserSystemClockAutomaticCorrectionEnabled() -> bool
```suggestion
        // IsUserSystemClockAutomaticCorrectionEnabled() -> bool
```

2021-01-20 18:55 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +            context.ResponseData.Write(true);//True means that the clock is synced with the internet, when on false it's not synced
```suggestion
            // NOTE: Set it to true means the clock is synced with internet. It's false instead.
            context.ResponseData.Write(true);
```

2021-01-20 22:25 UTC, Joshi234 commented
> It's still not based on any RE, but since it's not an important call, I guess it's fine as-is...
> There are some things to fix.

I used this https://github.com/3096/switch-time/releases homebrew to verify it's right.

2021-01-23 12:32 UTC, Thog requested changes
mostly okay, just few nits

2021-01-23 12:32 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +        public ResultCode IsUserSystemClockAutomaticCorrectionEnabled(ServiceCtx context)
Need a stub print.

2021-01-23 12:32 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
> +}
Can you remove this diff?

2021-01-23 12:32 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +}
Can you remove this diff?

2021-02-04 13:15 UTC, riperiperi approved these changes
The stub itself is fine, your comment is a bit weird though. Is there any functional difference when this is returned true in any games? You can replicate it on the real switch just by disabling internet sync in the settings applet.

2021-02-04 13:15 UTC, riperiperi commented on Ryujinx.HLE/HOS/Services/Settings/ISystemSettingsServer.cs
> +            // NOTE: Set it to true means the clock is synced with internet. It's false instead.
The english here is a bit broken. Also, I'm not sure why the comment says "it's false" when the response is clearly true.

> When set to true, is automatically synced with the internet.

Should probably be enough.

2021-02-04 14:44 UTC, Joshi234 commented
> The stub itself is fine, your comment is a bit weird though. Is there any functional difference when this is returned true in any games? You can replicate it on the real switch just by disabling internet sync in the settings applet.

I saw people saying that this would unlock locked bcat events  in animal crossing at any time when the event update is installed, I gonna try to see if it's true on the next acnh event

2021-02-07 20:59 UTC, Thog approved these changes

2021-02-09 08:41 UTC, AcK77 approved these changes

2021-02-09 08:41 UTC, merged