Implemented IFileSystemProxy.OpenDataStorageWithProgramIndex
Ryujinx/Ryujinx pull request #1933
Opened 2021-01-19 15:20 UTC by Joshi234

This service is used by Immortals Fenyx Rising which unfortunatly still doesnt boot because of Ryujinx.HLE.HOS.Services.Sockets.Sfdnsres.IResolver: 12 and it would close #1596

2021-01-19 15:46 UTC, EmulationFanatic commented
Confirmed this PR makes Rollercoaster Tycoon 3 bootable. 
![2021-01-19 08_43_25-Ryujinx 1 0 6362 - RollerCoaster Tycoon® 3_ Complete Edition v1 0 0 (01004900113](https://user-images.githubusercontent.com/62343878/105057791-ced71980-5a32-11eb-8d11-2eb8fc0ee005.png)

2021-01-19 17:11 UTC, Banjo-Kazooie-fan commented
Immortals Fenyx Rising isn't crashing with that service anymore (another missing service makes trouble now) - will update the game's entry as soon as this pr gets merged to master

2021-01-19 18:05 UTC, AcK77 requested changes

2021-01-19 18:05 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
> +            byte unknown = context.RequestData.ReadByte();
`unknown` should be `programIndex`

2021-01-19 18:05 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
> +            return ResultCode.Success;
Add a new empty line before

2021-01-19 18:05 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
> +            MakeObject(context, new FileSystemProxy.IStorage(context.Device.FileSystem.RomFs.AsStorage()));
This is wrong. You should use LibHac to parse the NCA contained in the game dump. Then found the right one related to the needed program index and return the corresponding RomFS.

2021-01-20 11:53 UTC, Joshi234 commented on Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
> +            MakeObject(context, new FileSystemProxy.IStorage(context.Device.FileSystem.RomFs.AsStorage()));
I tried doing this, but I just have no idea how I would do that, so I just threw when the programIndex isn't 0

2021-01-20 18:59 UTC, AcK77 commented
Well, if you don't know what you do, it's probably better to close the PR.
We can't merge guessed code for important things like this. What you have to do is to open the game archive and then return the right NCA RomFS related to the ProgramIndex. If you returns the wrong RomFS the guest could throw an error later which that will be harder to debug because of this wrong implementation.

2021-01-20 19:13 UTC, closed without merging