Add items to standard logs
Ryujinx/Ryujinx pull request #1942
Opened 2021-01-20 18:40 UTC by Joshi234

This is useful if to troubleshoot issues when someone sends a log for troubleshooting.

2021-01-20 19:07 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +                Logger.Notice.Print(LogClass.Application, $"AudioBackend: {ConfigurationState.Instance.System.AudioBackend.Value}");
Those logs should be done when the users change settings too (with Toggles or in the Settings window).

2021-01-23 12:37 UTC, Thog requested changes
Just small nits, otherwise lgtm

2021-01-23 12:37 UTC, Thog commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +                if((AudioBackend)_audioBackendStore.GetValue(activeIter, 1)!= ConfigurationState.Instance.System.AudioBackend.Value) {
```suggestion
                if((AudioBackend)_audioBackendStore.GetValue(activeIter, 1) != ConfigurationState.Instance.System.AudioBackend.Value)
                {
```

2021-01-23 12:37 UTC, Thog commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +                if((AudioBackend)_audioBackendStore.GetValue(activeIter, 1)!= ConfigurationState.Instance.System.AudioBackend.Value) {
Also could be interesting to use a temporary variable for `` (AudioBackend)_audioBackendStore.GetValue(activeIter, 1);``

2021-01-23 12:39 UTC, mageven commented
Related issue: #1728. Toggle events are missing I suppose. Could be worth adding.

2021-01-23 12:41 UTC, Joshi234 commented
> Related issue: #1728. Toggle events are missing I suppose. Could be worth adding.

Toggle Events doesn't make any sense when they dont get saved, that's why it's only logged when saving

2021-01-23 12:42 UTC, mageven commented
What happens if a crash occurs when they toggled Vsync or Docked mode?

2021-01-23 12:45 UTC, Joshi234 commented
> What happens if a crash occurs when they toggled Vsync or Docked mode?

Missed that you can click on the text, gonna add that

2021-01-27 23:50 UTC, AcK77 requested changes

2021-01-27 23:50 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            Logger.Notice.Print(LogClass.Application, $"VSync changed to: {_emulationContext.EnableDeviceVsync}");
```suggestion
            Logger.Notice.Print(LogClass.Application, $"VSync toggled to: {_emulationContext.EnableDeviceVsync}");
```
and add a new empty line before

2021-01-27 23:50 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            Logger.Notice.Print(LogClass.Application, $"IsDocked changed to: {ConfigurationState.Instance.System.EnableDockedMode.Value}");
```suggestion
            Logger.Notice.Print(LogClass.Application, $"IsDocked toggled to: {ConfigurationState.Instance.System.EnableDockedMode.Value}");
```
and add a new empty line before

2021-01-27 23:50 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            if(ConfigurationState.Instance.Graphics.EnableVsync.Value != _vSyncToggle.Active)
Add a new empty line before

2021-01-27 23:50 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            if(ConfigurationState.Instance.System.EnableDockedMode.Value != _dockedModeToggle.Active)
Add a new empty line before

2021-01-27 23:50 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +                if (audioBackend != ConfigurationState.Instance.System.AudioBackend.Value) {
```suggestion
                if (audioBackend != ConfigurationState.Instance.System.AudioBackend.Value)
                { 
```

2021-01-27 23:50 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +                    Logger.Notice.Print(LogClass.Application, $"AudioBackend changed to: {audioBackend}");
Add a new empty line before

2021-02-04 13:02 UTC, riperiperi approved these changes
Nice, this is helpful.

2021-02-20 01:16 UTC, AcK77 requested changes

2021-02-20 01:16 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            Logger.Notice.Print(LogClass.Application, $"VSync toggled to: {_emulationContext.EnableDeviceVsync}");
Add a new empty line before.

2021-02-20 01:16 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            Logger.Notice.Print(LogClass.Application, $"IsDocked toggled to: {ConfigurationState.Instance.System.EnableDockedMode.Value}");
Add a new empty line before.

2021-02-20 01:16 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            if(ConfigurationState.Instance.Graphics.EnableVsync.Value != _vSyncToggle.Active)
```suggestion
            if (ConfigurationState.Instance.Graphics.EnableVsync.Value != _vSyncToggle.Active)
```

2021-02-20 01:16 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            if(ConfigurationState.Instance.System.EnableDockedMode.Value != _dockedModeToggle.Active)
```suggestion
            if (ConfigurationState.Instance.System.EnableDockedMode.Value != _dockedModeToggle.Active)
```

2021-02-20 03:41 UTC, mageven reviewed
The current logs for toggles are a bit inconsistent. Vsync can also be toggled via hotkeys but it's not logged; and changes to Vsync inside Settings Window don't affect the current run. 
Also, I prefer logs at places where config is actually set rather than `LoadApplication()` and Settings Window.

So my suggestions- since they only affect emulation, a pair of "set" and "changed" logs.

"set" for both- `Initialize()` in `Switch.cs` is a good location for now.
Docked "changed" - `OnDockedModeChange()` in `Horizon.cs`
Vsync "changed" - It'd be nice if a common method was introduced like the one for docked. Otherwise, one at every toggle location.

2021-02-25 00:08 UTC, Joshi234 commented
Messed up everything gonna do a new pr

2021-02-25 00:43 UTC, Joshi234 commented
I changed the locations of the stuff as @mageven suggested.

2021-02-25 05:21 UTC, mageven reviewed
Looks much better now. I forgot to mention this previously but `Logger.Info` is better suited here than `Logger.Notice` for all of these.

2021-02-25 05:21 UTC, mageven commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +                Logger.Notice.Print(LogClass.Application, $"Vsync toggled to: {_vSyncToggle.Active}");
I think this isn't needed. This option comes into effect the next time emulation is started and there's already a log for that.

2021-02-25 12:53 UTC, Joshi234 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +                Logger.Notice.Print(LogClass.Application, $"Vsync toggled to: {_vSyncToggle.Active}");
You could change the setting while a game is running tho

2021-02-25 13:47 UTC, Joshi234 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +                Logger.Notice.Print(LogClass.Application, $"Vsync toggled to: {_vSyncToggle.Active}");
nevermind it doesnt effect the running game

2021-03-09 23:36 UTC, Joshi234 commented
This is ready for review btw

2021-03-18 22:58 UTC, AcK77 approved these changes

2021-03-18 23:04 UTC, Thog approved these changes
lgtm

2021-03-18 23:09 UTC, merged