Newbranch
Ryujinx/Ryujinx pull request #1946
Opened 2021-01-22 18:50 UTC by Joshi234

This shows a bar which shows the progress of pptc and of the shader cache loading. Unfortunatly there are 2 bugs right now. The first one is that the progress bar starts at about 15% and the other one is that it often crashes while updating the text. I hope you can help me fix it.
![image](https://user-images.githubusercontent.com/46032261/105532144-ba24ab00-5cea-11eb-977e-9376785c474b.png)
![image](https://user-images.githubusercontent.com/46032261/105532262-e5a79580-5cea-11eb-9831-6b79e8e4ff2d.png)

2021-01-22 19:52 UTC, Dime333 commented
This is a very Nice feature. I hope something similar can be added that shows the progress when starting in full screen.

2021-01-22 23:53 UTC, Joshi234 commented
LeverBars needed to get changed to ProgressBars because LeverBars are broken, they can't go lower then 10% and fixed the crashing

2021-01-23 03:33 UTC, Ghostotakoi commented
I have mentioned something similar here https://github.com/Ryujinx/Ryujinx/issues/1312 and here https://github.com/Ryujinx/Ryujinx/issues/1705

2021-01-24 22:49 UTC, jduncanator commented
Just took a brief look over the code. These changes should not live in the `Logger` class.

There is already a global `UiHandler` on `Device` for displaying the software keyboard user interface, so the status update related code should live there. This can then also be re-used by other components. The shader cache itself should also have an event added to it called `Status` that emits the event whenever the rebuild status changes. 

In a central position, where both the `UiHandler` instance and the shader cache are both accessible, you'd then add a handler to the shader cache's status update event, and call the `UiHandler` instance's `UpdateStatus` method, with the new status.

This way, the Shader Cache and the status message are completely decoupled, and other code in the future can listen for shader cache status changes in a similar way.

2021-01-31 14:54 UTC, Joshi234 commented
> Just took a brief look over the code. These changes should not live in the `Logger` class.
> 
> There is already a global `UiHandler` on the `Switch` instance for displaying the software keyboard user interface, so the status bar related code should live there. This can then also be re-used by other components. The shader cache itself should also have an event added to it called `Status` that emits the event whenever the rebuild status changes.
> 
> In a central position, where both the `UiHandler` instance and the shader cache are both accessible, you'd then add a handler to the shader cache's status update event, and call the `UiHandler` instance's `UpdateStatus` method, with the new status. The shader cache shouldn't have any status bar specific code in it.
> 
> This way, the shader cache and the status bar are completely decoupled, and other code in the future can listen for shader cache status changes in a similar way.

Alright changed it

2021-02-02 01:27 UTC, saldabain commented
It only appears to work in increments of 50 for me, is that intended?

2021-02-02 07:38 UTC, Joshi234 commented
@saldabain it's intended because updating it for every would be to much, but I gonna decrease it to 10

2021-02-22 00:11 UTC, riperiperi requested changes
This is a really useful feature, and I like the look of the new bar, but I have quite a few comments.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx.Common/Status/StatusChangedEventArgs.cs
> +        public readonly string ClassName;
Rather than having this be a string, consider using an `enum` of different status types.

```csharp
namespace Ryujinx.Common.Status
{
    public enum StatusType {
        Ptc,
        ShaderCache
    }
}
```

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx.Common/Status/StatusChanged.cs
> +    public static class StatusChanged
Weird name for a static class (sounds more like an event field), though I'm not sure what's better. Maybe `StatusHandler`?

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
> +                Common.Status.StatusChanged.DisableStatus();
Import `Ryujinx.Common.Status` to avoid qualifying this.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx.HLE/IHostUiHandler.cs
> +        /// </summary>
Closing tag without an opening tag. I guess the above example is also broken, but you can add the `<summary>` for that one too.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx.HLE/IHostUiHandler.cs
> +        void ShowStatus(object o, Common.Status.StatusChangedEventArgs args);
Import `Ryujinx.Common.Status` to avoid qualifying this.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx.HLE/IHostUiHandler.cs
> +        /// Disable the Status
Add `<summary>` above this to fix the xml doc.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx/Ui/Applet/GtkHostUiHandler.cs
> +                window._status.Text =  args.ClassName+": "+ args.Current.ToString()+ " / "+args.Total.ToString();
Whitespace is really inconsistent here. VS will do it for you if you cut and paste the line into the same location.

```csharp
window._status.Text = args.ClassName + ": " + args.Current.ToString() + " / " + args.Total.ToString();
```

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx/Ui/Applet/GtkHostUiHandler.cs
> +        public void DisableStatus(object o,EventArgs args)
Space after comma.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx/Ui/Applet/GtkHostUiHandler.cs
> +            MainWindow window = ((MainWindow)_parent);
Outer brackets not needed.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx/Ui/Applet/GtkHostUiHandler.cs
> +            MainWindow window = ((MainWindow)_parent);
Outer brackets not needed.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.cs
> +
Remove these spaces.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.cs
> +        [GUI] public readonly ProgressBar _statusProgressBar;
This breaks the alignment of all of these variables. Since they have a different visibility, maybe you should put them before or after in their own group, with their own alignment.

2021-02-22 00:11 UTC, riperiperi commented on Ryujinx.Common/Status/StatusChangedEventArgs.cs
> +        public readonly string ClassName;
A benefit of using enum values like this is that you leave it up to the UI to convert that to readable text or influence the display (maybe treat these status types differently) without doing an arbitrary string comparison. Makes things a lot easier to translate, as it's not printing a string directly.

2021-02-22 02:56 UTC, jduncanator commented on Ryujinx.Common/Status/StatusChanged.cs
> +            StatusDisableEvent.Invoke(null,EventArgs.Empty);
This should also be:
```suggestion
            StatusDisableEvent?.Invoke(null,EventArgs.Empty);
```
to avoid invoking an empty (null) event handler.

2021-02-22 02:57 UTC, jduncanator commented on Ryujinx/Ui/Applet/GtkHostUiHandler.cs
> +                window._status.Text =  args.ClassName+": "+ args.Current.ToString()+ " / "+args.Total.ToString();
```suggestion
                window._status.Text =  $"{args.ClassName}: {args.Current}/{args.Total}";
```

2021-02-22 02:58 UTC, jduncanator commented on Ryujinx/Ui/MainWindow.cs
> +        [GUI] public readonly ProgressBar _statusProgressBar;
This shouldn't be a public readonly field anyway. Expose it via a getter-only property on MainWindow.

2021-02-23 12:58 UTC, Niwu34 commented
![Joshi pptc](https://user-images.githubusercontent.com/67392333/108846659-1bd47f80-75df-11eb-8aef-8fee99d8ddb9.PNG)
![Joshi Shader cache bar](https://user-images.githubusercontent.com/67392333/108846666-1d9e4300-75df-11eb-8961-64b1497c04b5.PNG)
works awesome

2021-02-23 12:59 UTC, MelonSpeedruns commented
Does this mean the CMD console cna be disabled by default? :O

2021-02-24 23:04 UTC, Joshi234 commented
> Does this mean the CMD console cna be disabled by default? :O

Theoretically yes, since there is no real need for normal users anymore since everything is in the logs

2021-02-27 20:17 UTC, Shahil-Ayato commented
Shouldn’t this get closed if it’s superseded?

2021-02-27 22:14 UTC, closed without merging