Implement pcv service
Ryujinx/Ryujinx pull request #1952
Opened 2021-01-24 03:41 UTC by WilliamWsyHK

This PR is to implement `nn::pcv::detail::IPcvService`, for completeness.

2021-01-28 00:33 UTC, AcK77 requested changes
You should sets defaults values in `Initialize` call instead of returns a default value in each calls.
It's obviously not based on RE so I wonder what needs this service ?
I'm pretty sure some calls should returns some ResultCode is a guest call them without initiliaze the service before.
I'm not against a stub for this service since we will never be able to support that anyway.

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        // [Command(5)]
remove those 2 commented lines

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        // [Command(10)]
remove those 2 commented lines

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        // [Command(13)]
remove those 2 commented calls

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        public ResultCode Initialize(ServiceCtx context)
You should set a private field `_isInitialized` to true and then return it in `IsInitialized()`

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            return ResultCode.Success;
Add a new empty line before

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            return ResultCode.Success;
Add a new empty line before

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            context.ResponseData.Write(true);
write `_isInitialized` instead

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServicePcv);
Add a new empty line after

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServicePcv);
Sets `_isInitialized` to false

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            return ResultCode.Success;
Add a new empty line before

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServicePcv, new { powerControlTarget, microVolt });
Add a new empty lines before and after

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServicePcv, new { powerControlTarget });
Add a new empty lines before and after

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServicePcv, new { powerControlTarget, microVolt });
Add a new empty lines before and after

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        // [Command(21)]
Remove those 3 commented calls

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServicePcv, new { maxCount });
Add a new empty line before

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            (long position, long size) = context.Response.GetBufferType0x22(0);
```suggestion
            (long bufferPosition, long bufferSize) = context.Response.GetBufferType0x22(0);
```

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        // [Command(26)]
Remove those 2 commented calls

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        // Takes an input PowerControlTarget. Returns an output bool.
You should add the symbol here

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        // [Command(29)]
Remove this commented call

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServicePcv, new { powerControlTarget });
Add a new empty line before

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +                fixed (byte* ptr = outputBufferSpan.Slice(outCount * structSize, structSize))
There is an helper to write a struct directly at a memory offset, looks at other services for examples.
Then you can remove the usage of `unsafe`.

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +                fixed (byte* ptr = outputBufferSpan.Slice(outCount * structSize, structSize))
There is an helper to write a struct directly at a memory offset, looks at other services for examples.
Then you can remove the usage of `unsafe`.

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            }
Add a new empty line after

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            }
Add a new empty line after (same for some other calls)

2021-01-28 00:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +            }
Add a new empty line after (same for some other calls)

2021-01-29 14:28 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +                fixed (byte* ptr = outputBufferSpan.Slice(outCount * structSize, structSize))
For this I tried to avoid writing real data before knowing the actual count.

2021-01-29 14:28 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +                fixed (byte* ptr = outputBufferSpan.Slice(outCount * structSize, structSize))
For this I tried to avoid writing real data before knowing the actual count.

2021-04-13 01:24 UTC, kennyvv commented on Ryujinx.HLE/HOS/Services/Pcv/IPcvService.cs
> +        public ResultCode Initialize(ServiceCtx context)
Java dev huh? There's properties here m8 😜
A property like:
```public bool IsInitialized { get; private set; } ```

2021-05-02 21:13 UTC, AcK77 commented
What needs this service ?

2021-05-20 23:45 UTC, AcK77 commented
The usage of pcv service is still unknown, the code is pretty inaccurate based on my own RE and the PR seems to be inactive so I close it because of those cases.

2021-05-20 23:45 UTC, closed without merging