Improve inline keyboard compatibility
Ryujinx/Ryujinx pull request #1959
Opened 2021-01-25 03:14 UTC by Caian

This PR, together with #1945, fixes keyboard soft-locking issues that some players are having in MHGU. It also fixes a bug when creating a character in Dark Souls Remastered, where a second attempt to input the name, if it is smaller than the first one, will crash the game. Finally it implements a new keyboard request used by MHR that otherwise appears as an error in the log.

The particular reason some users have problems in MHGU seems to be related with a save game migrated from Switch or a different version of Monster Hunter, changing the messages exchanged with the applet with some weird ones. A save file kindly provided by a user on Discord happens to manifest the issue, if it ever need to be reproduced again.

A special thanks for Discord user plaisi for the testing and feedback.

Games re-tested:

- Dark Souls Remastered - Character creation screen
- Gnosia - Character creation screen
- Fate / Extella Link - Character creation screen
- Monster Hunter Rise Demo - In-game messaging
- Monster Hunter Generations Ultimate - In-game messaging (standard save)
- Monster Hunter Generations Ultimate - Set / Item renaming (standard save)
- Monster Hunter Generations Ultimate - Guild card renaming (standard save)
- Monster Hunter Generations Ultimate - In-game messaging (imported save)
- Monster Hunter Generations Ultimate - Set / Item renaming (imported save)
- Monster Hunter Generations Ultimate - Guild card renaming (imported save)

2021-01-28 00:16 UTC, AcK77 requested changes
Nice works! Just some nits.

2021-01-28 00:16 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +        private SoftwareKeyboardState _stateFg = SoftwareKeyboardState.Uninitialized;
`Fg` means `Foreground`? If yes, it could be better to use the word `Foreground` directly.
Same for the next line with `Bg` > `Background`.

2021-01-28 00:16 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +            Thread.Sleep(ResetDelayMillis);
What if you remove the delay ?

2021-01-28 00:23 UTC, jduncanator commented
As a general comment on this entire PR, it'd be great to see proper code documentation added to _at least_ all of the structs that are implemented here. I was diligent in making sure all of the original SoftwareKeyboard implementation was well documented, but it seems with some of the later changes that it's becoming less and less so. I really think this needs documentation added to bring it up to scratch with the standard SoftwareKeyboard implementation.

2021-01-28 00:34 UTC, Caian commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +            Thread.Sleep(ResetDelayMillis);
Then it doesn't work. The game will not understand the state reset and will soft-lock itself. The fact that the games spam `PopInteractiveData` suggests a different relation between the keyboard and the game, as commented, perhaps a continuous stream of responses.

This is the solution I considered more stable, as a thread continuously pushing messages to the interactive queue, could be bad.

2021-01-28 00:35 UTC, Caian commented
> As a general comment on this entire PR, it'd be great to see proper code documentation added to _at least_ all of the structs that are implemented here. I was diligent in making sure all of the original SoftwareKeyboard implementation was well documented, but it seems with some of the later changes that it's becoming less and less so. I really think this needs documentation added to bring it up to scratch with the standard SoftwareKeyboard implementation.

Thank you @jduncanator it will be provided.

2021-01-28 00:36 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardApplet.cs
> +            Thread.Sleep(ResetDelayMillis);
Maybe you should explain that in a comment and remove the `TODO` so ?

2021-01-30 16:05 UTC, Caian commented
@jduncanator I added comments to the enums, structs and their fields, also some explanations throughout the main applet file. Some fields I left uncommented because I could not find any source of information on what they are. Please let me know if there's anything else you find important to add.

2021-02-10 21:20 UTC, Thog approved these changes
lgtm, thanks 👍

2021-02-11 00:28 UTC, AcK77 approved these changes

2021-02-11 00:28 UTC, merged