Hide Cursor On Idle
Ryujinx/Ryujinx pull request #1993
Opened 2021-02-03 19:36 UTC by pineappleEA

Closes #1508 

This adds an option on General Settings,  on by default, that when enabled the mouse cursor will automatically hide if it's idle on the game space (windowed or full screen) for more than 8 seconds and recover it once it's moved again.

Before:
![image](https://user-images.githubusercontent.com/67879877/106794788-f8fb1f00-6661-11eb-8b7d-d503a4e06c02.png)

After:
![image](https://user-images.githubusercontent.com/67879877/106794857-0b755880-6662-11eb-823d-85b2c86a862b.png)

Note: Show "Confirm Exit" Dialog is moved on the second screenshot because it should have had position 2 on the SettingsWindow.glade file but it had 1 instead (which belongs to Check for Updates on Launch)

The way this works is pretty simple:

- A timer runs for 8 seconds (8000 msec)
- When it ticks an event fires and the cursor is changed to Gdk's BlankCursor
- Every time the mouse is moved the event that checks that fires, the timer is reset and the cursor gets unset

P.S. The first iteration of the code set the cursor used 
`Window.Cursor = new Gdk.Cursor(Gdk.Display.Default, Gdk.CursorType.BlankCursor);`
to hide the cursor and while this worked on Linux it didn't on Windows. The correct way was to set
`Gtk.Application.Invoke(delegate { Window.Cursor = new Gdk.Cursor(Gdk.Display.Default, Gdk.CursorType.BlankCursor); });`

2021-02-03 22:11 UTC, mhvuze commented
Excellent, thank you very much for this! I have tested the PR with several games in windowed and full screen mode and it works as expected on my Windows 10 PC.

2021-02-07 06:04 UTC, nadimmoran commented
It works as it should, I have a doubt if I want to hide the cursor at all times if it is active or not, as it would be, I would like to try in another build apart since some games when the touch is used said game has its own pointer and it is little annoying that it mixes with the mouse

2021-02-07 20:48 UTC, Thog approved these changes

2021-02-09 08:20 UTC, AcK77 requested changes
Some nits have to be fixed! Nice works!

2021-02-09 08:20 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 21;
21 is the version of LDN 2.1, please change it to 22.

2021-02-09 08:20 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +            if (configurationFileFormat.Version < 21)
21 -> 22

2021-02-09 08:20 UTC, AcK77 commented on Ryujinx/Config.json
> +  "version": 21,
```suggestion
  "version": 22,
```

2021-02-09 08:20 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +        private static System.Timers.Timer _idleTimer = new System.Timers.Timer();
Why is it static? `System.Timers` can be added as a using?
Maybe the var should be named `_idleCursorTimer`?

2021-02-09 08:20 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +            _idleTimer = new System.Timers.Timer();
You could use {} for field and then add the event handler

2021-02-09 08:20 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +        private void ResetPtr()
ResetPointer or ResetCursor maybe?

2021-02-09 08:20 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +
Remove extra empty line

2021-02-14 20:53 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +            if (ConfigurationState.Instance.HideCursorOnIdle)
Since you put this check in `ResetCursorIdle()` it could be better to add it in `HideCursorIdle()` too instead of in the method which call `HideCursorIdle()`.

2021-02-14 21:53 UTC, AcK77 approved these changes

2021-02-14 22:14 UTC, Thog reviewed
lgtm except for the small nit

2021-02-14 22:14 UTC, Thog commented on Ryujinx/_schema.json
> +        "hide_cursor_on_idle": {
misaligned

2021-02-15 21:48 UTC, merged

2022-11-23 08:20 UTC, GamerzHell9137 commented
> it doesn't work.

Works fine here