Add custom log dir
Ryujinx/Ryujinx pull request #2027
Opened 2021-02-16 23:50 UTC by Joshi234

This adds an option to set your own log path.

2021-02-17 00:29 UTC, EmulationFanatic commented
Requires a restart of the application after setting the Logs path. I suppose this makes sense, but it would be nice if it somehow took effect immediately, or automatically restarted Ryujinx after setting.

2021-02-17 00:37 UTC, jduncanator requested changes

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public string CustomLogDir { get; set; }
Probably best to use the full word "Directory", there isn't any reason to shorten it here.

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +            public ReactiveObject<string> CustomLogDir { get; private set; }
Ditto.

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                if (ConfigurationState.Instance.Logger.CustomLogDir.Value == "" || ConfigurationState.Instance.Logger.CustomLogDir.Value==null) {
This can just be `String.IsNullOrEmpty(ConfigurationState.Instance.Logger.CustomLogDir.Value)`

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                    Logger.AddTarget(new AsyncLogTargetWrapper(
You should check that the directory exists before using it, otherwise the application will just crash. If the folder doesn't exist, it should fallback to using the default logs directory.

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                    new FileLogTarget(Path.Combine(AppDomain.CurrentDomain.BaseDirectory+"Logs"), "file"),
Why was "Logs" appended here? This is incorrect anyway, it needs a path separator after the BaseDirectory, it should be `Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Logs")`

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx/Program.cs
> +
Why is the File log target added twice? Once here and once in the LoggerModule?

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx/Ui/MainWindow.cs
> +            if (!(ConfigurationState.Instance.Logger.CustomLogDir.Value == "" | ConfigurationState.Instance.Logger.CustomLogDir.Value == null))
Ditto.

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx/Program.cs
> +            if (!(ConfigurationState.Instance.Logger.CustomLogDir.Value == "" | ConfigurationState.Instance.Logger.CustomLogDir.Value == null)) {
Ditto.

2021-02-17 00:37 UTC, jduncanator commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +            Logger.CustomLogDir.Value              = "";//When set to nothing it saves into the Ryujinx application folder
I don't think we need this comment here. If it's needed, it should be a XML doc on the CustomLogDirectory field itself.

2021-02-17 00:38 UTC, EmulationFanatic commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                    Logger.AddTarget(new AsyncLogTargetWrapper(
It created the folder automatically when I tested it.

2021-02-17 00:40 UTC, jduncanator commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                    Logger.AddTarget(new AsyncLogTargetWrapper(
Best not to assume this behaviour, that seems like a side affect of how the file is opened.

2021-02-17 00:41 UTC, Joshi234 commented on Ryujinx/Program.cs
> +
Because here it gets added when logging to file gets enabled

2021-02-17 00:42 UTC, jduncanator commented on Ryujinx/Program.cs
> +
This was never required before, and the logging worked fine. Why is it required now? I don't see any other changes that would require this to be the case.

2021-02-17 00:43 UTC, jduncanator commented on Ryujinx/Ui/Windows/SettingsWindow.glade
> +                            <object class="GtkEntry" id="_customLogDir">
This should be a folder/file browser entry, not a free text entry.

2021-02-17 00:46 UTC, Joshi234 commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                    Logger.AddTarget(new AsyncLogTargetWrapper(
It already does this in FileLogTarget

2021-02-17 00:48 UTC, jduncanator commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                    Logger.AddTarget(new AsyncLogTargetWrapper(
I'm more thinking along the lines of: The user enters `ImBeingAGiantIdiot` into the custom log directory field. This isn't even a valid path, and passing this down to the underlying log target will most likely result in a crash.

It should validate the path exists, is valid, and if it isn't, should either fallback to the default directory, or create it.

2021-02-17 01:11 UTC, Joshi234 commented on Ryujinx/Program.cs
> +
Yeah I was pretty dumb

2021-02-17 04:44 UTC, mageven commented
Tying logging to yet another component that can fail (one that does so frequently too looking at support questions on discord) doesn't sound like a good idea to me.

This makes support harder too as there's not one common path to recommend to users for getting logs. It's already difficult as it is now (even considering "Open Log Folder" which isn't always possible)

Also, I'm trying to understand why a regular user needs this (or why a GUI config I guess). Logs are pretty lightweight so the reason isn't lack of space.

If you want custom log locations, I suggest passing it via command line. It'll work without side-effects at least (like requiring a reboot on location change). But that's kind of redundant, when redirection works just as well.

This also doesn't close #1526 imo. They wanted logs in the data directory (for a different purpose).

2021-02-17 05:15 UTC, jduncanator commented
> Tying logging to yet another component that can fail (one that does so frequently too looking at support questions on discord) doesn't sound like a good idea to me.
> 
> This makes support harder too as there's not one common path to recommend to users for getting logs. It's already difficult as it is now (even considering "Open Log Folder" which isn't always possible)
> 
> Also, I'm trying to understand why a regular user needs this (or why a GUI config I guess). Logs are pretty lightweight so the reason isn't lack of space.
> 
> If you want custom log locations, I suggest passing it via command line. It'll work without side-effects at least (like requiring a reboot on location change). But that's kind of redundant, when redirection works just as well.
> 
> This also doesn't close #1526 imo. They wanted logs in the data directory (for a different purpose).

I'm sort-of of the same thinking, although I think we can go a step further than the command line option.

What was suggested in that issue was a configuration option in the config file. I think that's fine, and I think we should implement that, but I too question the requirement for an actual GUI option to configure that. The user in that issue would then be able to set their logging directory in the config file before booting Ryujinx, and have everything they wanted (I think this was for AppImage support, which needs everything in specific locations).

I'm sort of averse to adding too many command line options, unless we want to go all in and have everything configurable by a command line option too.

2021-02-17 19:11 UTC, CeruleanSky commented
>If you want custom log locations, I suggest passing it via command line.

If you use the command line switch for a custom user directory could the log folder just go in there?  It seems that solution works fine for other emulators, and it would probably work for the flatpack/appimage users as well.  Then there would be only two places it would be found, either the default, or an intentionally picked, and thus hopefully unconfusing place along side every other user file for portable/custom/flatpack/etc users.

2021-02-17 19:16 UTC, AcK77 requested changes
A bunch of things need to be fixed. Maybe you should change the logic here and there to get something which work easier without some not needed code!
Nice try, I hope you will find a nice way to fix everything 😊!

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            string logPath;
Add new empty line after

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +
Remove extra empty line

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +
Remove extra empty line

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            if (!String.IsNullOrEmpty(ConfigurationState.Instance.Logger.CustomLogDirectory.Value))
You should group the both if condition, then if the directory exists and it’s not empty (since here the string can’t be null) it use the custom path, else, it use the default one. Btw the { should be on a new line.

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +            try {
The { should be on a new line

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +                return;
Why do you silent all exception, it’s usually a bad practice, you should fix the issue instead of silent it, if it’s possible!

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +
Remove the extra 2 empty lines

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> -        private readonly StreamWriter  _logWriter;
Why it’s not readonly anymore?

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +        private StreamWriter  _logWriter;
Alignment is wrong (but you shouldn’t change that line)

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Logging/Targets/FileLogTarget.cs
> +            if (Directory.Exists(path))
Why do you change that if the path is passed as argument? You should change the path where this method is called instead.

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +                if (Logger.HasTarget("file"))
You should just check the path, if the custom isn’t sets, use the default one, check if the folder exists (as jD suggested) and then start the FileLogger. You duplicate code for nothing here and it could be done much easier.

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Logging/Logger.cs
> +            return false;
Add a new empty line before

2021-02-17 19:16 UTC, AcK77 commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +        public static void ReloadFileLogger(object sender, ReactiveEventArgs<bool> e)
Why it’s public now?

2021-02-20 03:50 UTC, mageven commented
> I'm sort of averse to adding too many command line options, unless we want to go all in and have everything configurable by a command line option too.

I'd like it if there's a cli-only Ryujinx in the long term.

> If you use the command line switch for a custom user directory could the log folder just go in there? It seems that solution works fine for other emulators, and it would probably work for the flatpack/appimage users as well. Then there would be only two places it would be found, either the default, or an intentionally picked, and thus hopefully unconfusing place along side every other user file for portable/custom/flatpack/etc users.

@CeruleanSky's solution seems like a good compromise to me. The log files have version info in and on them so that's not an issue.
But I'm fine with a config option as long as it is robust and doesn't miss any logs.

2021-02-20 10:27 UTC, Joshi234 commented
And what about an advanced tab in the settings for settings that most people won't use but might be useful to some people?

2021-02-20 11:15 UTC, EmulationFanatic commented
> And what about an advanced tab in the settings for settings that most people won't use but might be useful to some people? I don't see why adding a the option in the config file but not in the settings when it's already implemented, it just makes it less user friendly

I think the GUI field is the most user friendly option here and should be kept. Having config file options and a command line parameter on top of it would be great too. This way it be doesn't matter how a user enjoys using Ryujinx most; they can have the feature in any context.

2021-02-23 00:27 UTC, Joshi234 commented
So what should we do now?

2021-02-23 03:31 UTC, EmulationFanatic commented
> So what should we do now?

I think adding a command line switch would satisfy any outstanding requirements (and it would overrule any GUI setting).

2021-02-23 16:20 UTC, Joshi234 commented on Ryujinx.Common/Configuration/LoggerModule.cs
> +            ConfigurationState.Instance.Logger.CustomLogDirectory.Event      += ReloadFileLoggerNewDirectory;
Is it possible to have an unknown type for `ReactiveEventArgs<bool> e?`

2021-03-11 01:45 UTC, qurious-pixel commented
Could it be done via command-line switch like `-r` and `-f`
[Custom Data Dir](https://github.com/Ryujinx/Ryujinx/blob/5ab5b0e709c3667ca85a6727620ff26f074e4ce5/Ryujinx/Program.cs#L38-L57)
<details><summary>Code Block</summary>

            {
                string arg = args[i];

                if (arg == "-r" || arg == "--root-data-dir")
                {
                    if (i + 1 >= args.Length)
                    {
                        Logger.Error?.Print(LogClass.Application, $"Invalid option '{arg}'");

                        continue;
                    }

                    baseDirPathArg = args[++i];
                }
                else if (arg == "-f" || arg == "--fullscreen")
                {
                    startFullscreenArg = true;
                }
                else if (launchPathArg == null)
                {
                    launchPathArg = arg;
                }
            }
</details>

Add something like `-l` and `--user-log-dir`

2021-04-09 15:05 UTC, Joshi234 commented
Closing this since it's kind a stupid, maybe in the future when it's needed I gonna implement it

2021-04-09 15:05 UTC, closed without merging