Add MotionButton to simulate shaking of controller
Ryujinx/Ryujinx pull request #2039
Opened 2021-02-20 02:00 UTC by CeruleanSky

Adds a hotkey(inspired by yuzu feature) that simulates shaking of a motion devices.  It is currently defaults to Grave " ` " .  The ranges are from shaking my phone while running the sixaxis homebrew from https://github.com/switchbrew/switch-examples/tree/master/hid/sixaxis .  A hotkey was chosen because a person might not have a joystick button to assign or may not be using keyboard input as a controller.

It works for my purposes as hitting a key is easier than using my feet to shake my phone, perhaps this will work for others as well.

2021-02-20 02:04 UTC, AcK77 commented
Is that needed/useful for anything else than testing a sixaxis homebrew ?

2021-02-20 02:08 UTC, CeruleanSky commented
Any software that has a shake controller motion gesture and you don't want to setup a motion server or actually have to shake your device physically. Super Mario Odyssey for example has shaking your controller as a modifier for many action.

2021-03-06 15:09 UTC, riperiperi requested changes
This is particularly useful, nice work. One thing though:

Are we OK with making this a hotkey rather than a controller button? Perhaps each player would want to have their own shake button, and bind it to their controller rather than the keyboard.

I'm also not sure about the aggressive gyro rotation. I'm not sure how many games depend on gyro change to detect motion controls that could be triggered by violent shaking rather than precision, but it will definitely cause the screen to shake horribly in games with gyroscope aiming. Maybe accelerometer only could work?

2021-03-06 15:09 UTC, riperiperi commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                    ToggleVsync = Key.Tab,
I don't think we usually put a comma on the last item of a list.

2021-03-06 15:09 UTC, riperiperi commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                    MotionButton = Key.Grave,
This is a redefinition - it replaces the `KeyboardHotkeys` object above which defines `ToggleVsync`, so after this is done it will be entirely undefined. You should set `ToggleVsync` here too.

2021-03-06 15:09 UTC, riperiperi commented on Ryujinx/Modules/Motion/MotionDevice.cs
> +            Gyroscope = new Vector3(random.Next(-2000, 2000) * 0.001f);
What format is gyro data in? If it's a normalized vector, this could produce some undesirable results.

2021-03-06 15:09 UTC, riperiperi commented on Ryujinx/Modules/Motion/MotionDevice.cs
> +
Unnecessary space.

2021-03-06 15:09 UTC, riperiperi commented on Ryujinx/Ui/GLRenderer.cs
> +                if (currentHotkeyButtons.HasFlag(HotkeyButtons.MotionButton))
Nit: add a newline above

2021-03-06 15:09 UTC, riperiperi commented on Ryujinx/Ui/GLRenderer.cs
> +                else {
This bracket should be on the next line.

2021-03-06 20:55 UTC, CeruleanSky commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                    ToggleVsync = Key.Tab,
Slipped in when experimenting to figure out how config worked. Fixed.

2021-03-06 20:55 UTC, CeruleanSky commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                    MotionButton = Key.Grave,
Done and removed trailing comma as well.

2021-03-06 20:55 UTC, CeruleanSky commented on Ryujinx/Modules/Motion/MotionDevice.cs
> +            Gyroscope = new Vector3(random.Next(-2000, 2000) * 0.001f);
I tested Yuzu, whose feature inspired this, on the sixaxis homebrew, their motion button feature did not produce a normalized vector, but they did clamp the components in the range of -1 to 1.  I chose -2 to 2 from shaking my phone and watching the values produced by the net.sshnuke.dsu.MotionSource Android software in the sixaxis homebrew. 

I'll hold off for now, but if your testing with software and hardware indicates that it should be normalized, that can be done easily.

2021-03-06 21:28 UTC, CeruleanSky commented
>Are we OK with making this a hotkey rather than a controller button? Perhaps each player would want to have their own shake button, and bind it to their controller rather than the keyboard.

I generally use [antimicro](https://github.com/AntiMicro/antimicro/) for binding a key to a controller.  Perhaps it would be preferred to override or dual purpose a controller button instead. I picked hotkey so it works for keyboard and controller users and doesn't interfere with their usual controls.  As far as multiple people, I did not really have multiple people with their controllers in mind for this. I'm sure they would enjoy such a thing, but at least from me, it will have to be a future feature, as I'm not really setup to test it. 

>I'm also not sure about the aggressive gyro rotation. I'm not sure how many games depend on gyro change to detect motion controls that could be triggered by violent shaking rather than precision, but it will definitely cause the screen to shake horribly in games with gyroscope aiming. Maybe accelerometer only could work?

I'll be glad to adjust things, I could even offer config presets, accel only, gyro only, harmonic oscillation, etc , but I don't really have much to test with, and was just using Yuzu's values in the sixaxis homebrew as guidance, which does activate both the gyro and the acceleration.   As far as the aggressiveness, while the ranges worked for my purposes, if it is causing issues, perhaps my phone was shaken a bit harder than needed when I was sliding it on the table....

2021-04-11 04:24 UTC, CeruleanSky commented
Due to the dropping of OpenTK3 which includes a newer motion system, a new input system, and due to the lack of my ability to test and develop it for multiple controllers, I am closing this.  Maybe the new system will allow an easier to add motion button in case anybody else wants to remake this.

2021-04-11 04:25 UTC, CeruleanSky commented
Due to the dropping of OpenTK3 which includes a newer motion system, a new input system, and due to the lack of my ability to test and develop it for multiple controllers, I am closing this. Maybe the new system will allow an easier to add motion button in case anybody else wants to remake this.

2021-04-11 04:25 UTC, closed without merging