Auto-delete dlc.json when a dlc has been moved or deleted.
Ryujinx/Ryujinx pull request #2054
Opened 2021-02-23 17:41 UTC by jms-c

This will allow DLC's to be moved without issues (other than having to re-add dlcs).
This should solve part of #1366.

2021-02-23 17:42 UTC, jms-c commented
Feel free to change DLC's to DLCS (if you prefer, I don't know which is more grammatically correct)

2021-02-23 18:01 UTC, EmulationFanatic commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +                    GtkDialog.CreateErrorDialog("Your DLC's have been moved or deleted, please re-add them.");
"DLC files have been moved or deleted; please re-add your DLC."
Again sidesteps the apostrophe issue. Your call, but this is more correct in terms of English rules. In terms of punctuation, I'm not sure how it is normally used in dialog boxes and whether a period is correct or whether this should all be in title case.

2021-02-23 18:03 UTC, jms-c commented
I will commit some changes to fix those issues.

2021-02-23 18:21 UTC, jms-c commented
A new commit to change the wording has been added.
(based on EmulationFanatic's feedback with modifications)

2021-02-23 18:59 UTC, jms-c commented
Skips remaining dlc if game is running with invalid dlc and logs in console.

2021-02-23 19:14 UTC, jms-c commented
It now logs properly instead of Console.Writeline!

2021-02-23 19:26 UTC, jms-c commented
This just closes the dlc manager now after the error, reopen to see empty list (prevents partial list).

2021-02-23 19:35 UTC, jms-c commented
This new change makes sure the list stay empty after clear allowing re-adding of dlc easily.
It just now needs some testing, in my opinion. (and gui warning on game launch (but I can't implement that atm because it crashes))

2021-02-23 19:59 UTC, EmulationFanatic commented
Works well on Windows. Tested the following:

- Scenario 1: Managing DLC for a game whose DLC has been moved or deleted.
As expected, there was a dialog box warning me and then the DLC manager popped up for me to re-add the DLC file.
- Scenario 2: Launching a game whose DLC has been moved or deleted.
As expected, the DLC was discarded, the event noted in the console & log, and the game launched successfully.

Hopefully adding a pop-up on launch in Scenario 2 instances is possible somehow. That way the user is sure to know that their DLC is not working. If not now, then when the new UI hits :)

2021-02-23 20:10 UTC, jms-c commented
> 
> 
> Works well on Windows. Tested the following:
> 
>     * Scenario 1: Managing DLC for a game whose DLC has been moved or deleted.
>       As expected, there was a dialog box warning me and then the DLC manager popped up for me to re-add the DLC file.
> 
>     * Scenario 2: Launching a game whose DLC has been moved or deleted.
>       As expected, the DLC was discarded, the event noted in the console & log, and the game launched successfully.
> 
> 
> Hopefully adding a pop-up on launch in Scenario 2 instances is possible somehow. That way the user is sure to know that their DLC is not working. If not now, then when the new UI hits :)

The gui would be great but any attempt crashes the emulator for some reason (atleast for me).

2021-02-23 20:13 UTC, jms-c commented
New minor change, doesn't load any dlc if a invalid dlc is detected. This should be more noticeable

2021-02-24 08:19 UTC, jms-c commented
Major Update!
Now it no longer destroys dlc.json but simply removes the invalid entries.

2021-02-24 08:26 UTC, jms-c commented
Testing requested. (especially on linux)
https://w.ryujinx.org/dl/2054

2021-02-24 16:00 UTC, vickyorlo commented
Tested on Linux:

- Game is Project Diva Mega Mix, with several of the song packs already added in the DLC manager.
- Song Pack 1, containing a song called Double Lariat, moved away to a different folder.
- DLC manager when opened warns about missing DLCs. DLC missing from the list. Pressed the cancel button.
- Opened the DLC manager again, warns about missing DLCs again. Pressed the save button.
- Opened the DLC manager again, the DLC is still missing as expected.
- Added the Song Pack 1 DLC again, and then moved it somewhere else.
- Opened the game, the message about a missing DLC is visible in the console log.
- Double Lariat is gone from the song list, but songs from the other DLC packs are still visible.
- Closed the game and opened the DLC manager, warns about missing DLC.
- Added the Song Pack 1 DLC again.
- Double Lariat is visible again.

To summarize, everything works as expected.

2021-02-24 16:06 UTC, jms-c commented
If anyone could submit working gui code, it would be helpful as using "_device.UiHandler.DisplayMessageDialog" causes the emulator to freeze.
Therefore, It isn't in the pr.

2021-02-24 16:52 UTC, jms-c commented
I added a gui warning. There is however an issue as it doesn't dispose _emulationContext (it hangs if i try).

2021-02-24 17:12 UTC, jms-c commented
It will now restart ryujinx if user responds no on ui.

2021-02-24 17:42 UTC, jms-c commented
Please test the new gui!
https://w.ryujinx.org/dl/2054
Try to launch the game after moving a dlc file.
Comment your results.

2021-02-24 19:33 UTC, EmulationFanatic reviewed
Works as intended on Windows here. I tested all scenarios I could think of and everything worked as it should.
Added some verbiage suggestions but they are your call to adopt or discard :)

2021-02-24 19:33 UTC, EmulationFanatic commented on Ryujinx/Ui/MainWindow.cs
> +                        bool continueGame = GtkDialog.CreateChoiceDialog("An error occurred while trying to load the game!",
For the title bar on this window, something more generic in title case like "Game Load Error" would be preferred imho.

2021-02-24 19:33 UTC, EmulationFanatic commented on Ryujinx/Ui/MainWindow.cs
> +                           e.Message, "Would you like to continue playing? (pressing no will restart ryujinx)");
"Continue loading anyway? Pressing "No" will restart the emulator."

2021-02-24 19:33 UTC, EmulationFanatic commented on Ryujinx/Ui/MainWindow.cs
> +                            Logger.Warning?.PrintMsg(LogClass.Application, "Stopped loading game due to an exception!");
"Game launch was aborted due to an exception"

2021-02-24 19:42 UTC, jms-c commented
Thanks for the improvements. I have updated the wording (imo, it's clearer)!

2021-02-24 19:42 UTC, jms-c commented on Ryujinx/Ui/MainWindow.cs
> +                           e.Message, "Would you like to continue playing? (pressing no will restart ryujinx)");
I like that.
The "Continue loading anyway" makes it sound more like "Their is a problem, stop running" instead of "You can continue - I don't mind"

2021-02-25 12:10 UTC, vickyorlo commented
Tested again on Linux:

- First five steps the same
- Running the game shows the DLC missing warning. Pressed "No".
- Ryujinx restarts.
- Launched the game again, pressing "yes"
- Double Lariat not present, songs from other song packs present.

Once again, looks good.

2021-02-25 15:23 UTC, jms-c commented
I think this PR is ready, but if any last minute testers want to test feel-free,
To test, install dlc using the manager then move the file using a file manager.
It shouldn't crash when editing dlc and launching the game.

Here is a shiny download button:
[![Download Ryujinx](https://img.shields.io/badge/Download-2054-red?style=for-the-badge&labelColor=blue)](https://w.ryujinx.org/dl/2054)

Please comment recomendations and results on this pr.

2021-02-25 15:34 UTC, EmulationFanatic commented
As fluid as this functionality is, I have reservations about the entire emulator restarting. I think finding a way to properly stop the loading (or check for DLC prior to launching the game) would be preferred if at all possible.

2021-02-25 15:35 UTC, jms-c commented
I would love to stop the emulator but the only way I see is _emulationContext.dispose(); return; but the disposal hanged the emulator on testing.

2021-02-25 15:45 UTC, EmulationFanatic commented
> I would love to stop the emulator but the only way I see is _emulationContext.dispose(); return; but the disposal hanged the emulator on personal testing.

What about a pre-load DLC check to prevent launch in the first place?

2021-02-25 15:52 UTC, jms-c commented
If I can get the titleId it should be possible.

2021-02-25 16:19 UTC, EmulationFanatic commented
> If I can get the titleId it should be possible. (early enough)
> However, it looks like the titleId is only initialized after loading.

Is there a sensible way of changing that? To identify the titleID prior to loading, that is.

2021-02-25 16:23 UTC, jms-c commented
It requires parsing nsp/xci headers it seems. which = lots of copied code.

2021-02-26 05:08 UTC, mageven commented
The suggested `UiHandler` code didn't work because, for some reason, `LoadApplication()` executes on the GUI thread. This is also part of the reason the GUI completely freezes when you start loading a game. But making it run on a different thread is a disruptive change and better off as its own PR.

Restarting the whole emulator application is a bad idea and should be avoided at all costs (especially after detecting the problem).

Fwiw, I thought your earlier solution to just log a warning and proceed wasn't bad. It remains the simplest solution for now.

2021-02-26 08:18 UTC, jms-c commented
I added a gui as running the game causes undefined behavour with some games completely deleting parts of saves due to missing dlc. That is why I offer the option of stopping the game before it gets to a point where that happens. (otherwise people might not be very happy)

2021-02-26 08:35 UTC, vickyorlo commented
See my previous report: 

> However, I noticed the score I had on Double Lariat got erased. Perhaps some more visible warning could be useful to prevent "undefined behavior" when a game overwrites a save with missing DLCs.

Various games might handle missing DLCs in different ways, in my opinion a pop-up warning is fairly useful in terms of user experience. The warning in the console instantly gets flooded by other messages.

2021-02-26 16:02 UTC, jms-c commented
I think this is ready. Feel free to review whenever.

2021-02-26 17:59 UTC, MetrosexualGarbodor commented
Tested on Windows 10: ran the game (Xenoblade 2) to check the DLC and update were installed, closed the emulator, moved the DLC *and* the update to another folder, opened Ryujinx, clicked on "Manage DLC" and it gave me the following error:
![unknown (1)](https://user-images.githubusercontent.com/79612681/109336414-416dbd00-785b-11eb-9612-f6d0f00439b9.png)
So it would seem it is working as intended. 
My only feedback past that would be considering if there should be (or if it's even worth implementing) a similar functionality for when updates are moved, as stuff can break when the save file and DLC are on, but the updates are off. 
I also tested if it would say anything different if I only added 5 out of 6 DLCs, and it didn't. I realize this falls on the user if they somehow forget about one file, but I believe it's also worth considering if it's worth implementing for the future. 
Thank you for your work.

2021-02-26 18:47 UTC, jms-c commented
If you want to test here: 

Here is a shiny download button:
[![Download Ryujinx](https://img.shields.io/badge/Download-2054-red?style=for-the-badge&labelColor=blue)](https://w.ryujinx.org/dl/2054)

Please comment recomendations and results on this pr.

2021-02-28 17:38 UTC, jms-c commented
If anyone wants to review, please do.

2021-02-28 18:14 UTC, jms-c commented
Do I need to do anything more for this pull request?

2021-03-01 15:24 UTC, jms-c commented
Please review.

2021-03-02 23:01 UTC, AcK77 requested changes
Why you don’t remove the missing DLC file in the list and then run the game without the missing DLC instead of throw an exception (It’s a bad practice in this situation), restart Ryujinx (I don’t see why you want to restart the emulator), and more, which is not a good solution to fixes the issue.

Nice try for a first contribution! Keep it up!

2021-03-03 08:12 UTC, jms-c commented
I found an issue that happend when I previously did start the game with missing DLC and a console warning.
The issue is due to how games handle missing DLC. Starting some games (especially bad with autosaving) may do varying things from ignoring dlc (and using save) or deleting data (from dlc) and more

2021-03-03 08:15 UTC, jms-c commented
The exception based GUI was a little unusual. It was used as I couldn't create a GUI in HOS.ApplicationLoader. 
Also, the emu restart was used as the method of disposing the emulation context and returning hanged the emu. (in testing)

2021-03-11 20:37 UTC, jms-c commented
If anyone can share GUI code that doesn't use the weird exception approach, feel free to comment.

2021-03-15 20:27 UTC, jms-c commented
If anyone wants to have a look at this code and change the ui. I will happily change it.
Have a nice day.

2021-04-01 20:45 UTC, jms-c commented
Ping! If anyone wants to have a look, feel free!

2021-04-02 15:29 UTC, jms-c commented
I have added the ability to stop the game without restarting the emulator!
Along with that, it now also doesn't use an exception to detect a dlc error.

Testers Needed!

2021-04-02 15:50 UTC, jms-c commented
**Testing Information**
To test the latest commit, start a game with a moved dlc. 

When it prompts to continue, try to do one of the following:
Click "NO" and try to play another game
Click "YES"
Click "NO" and reopen the same game but click YES next
Or anything else regarding dlc.

Report any unusual errors (that don't happen normally)

2021-04-02 16:22 UTC, EmulationFanatic commented
This is a great improvement! I tested the following scenarios:

With DLC intact:
Booted normally of course.

With DLC file moved:
- Launched and clicked NO - took me back to main window game selection screen as intended.
- Relaunched and clicked YES - launched the game without the missing DLC without issues.
- Relaunched and clicked NO - took me back to the main window where I then right-click Manage DLC. This warned me about missing DLC and advised to re-add it. Re-added it and launched successfully.

Awesome improvement!

2021-04-02 17:54 UTC, malfestio commented
`00:00:38.857 |E| Application : DLC files have been moved or deleted; skipping 28 DLC files`
`00:00:38.857 |E| Application CreateErrorDialog: 28 DLC files have been moved or deleted; please re-add your DLC.`

works great, changed the folder name to mess with it an it gave me that error in a dialog window, changed folder back and it all appeared again

2021-04-02 17:59 UTC, jms-c commented
On the discord, people have been having success with this pr.

2021-04-03 12:26 UTC, jms-c commented
Waiting for reviews!
@AcK77 requested changes have been done!

2021-04-03 18:17 UTC, jms-c commented
This PR now supports notifying when an update is moved/deleted!

2021-04-06 18:56 UTC, jms-c commented
Please review!

2021-04-07 20:45 UTC, AcK77 requested changes
There is a lot of syntax issue, please fixes everything before asking for review...
You misses some spaces here and there like `if(blablabla>0)` should be `if (blablabla > 0)`, you added some empty lines where it's not needed and forget to add some where it's needed.

```
        public static int ignoreLoadErrorState = 0;
        public static int ignoreSelectedState = 0;
        public static string loadFailureString = null;
```
Those lines in ApplicationLoader is a bit strange. I don't think it's how things should be handled. But nice try, keep it up!

2021-04-07 20:49 UTC, jms-c commented
It's unusual but needed to keep track of state.

2021-04-07 20:55 UTC, jms-c commented
If not used, the pr is unable to differentiate whether to show DLC prompt, Update Prompt or none.

2021-04-07 21:32 UTC, riperiperi requested changes
I feel like the way the ApplicationLoader is returning errors isn't entirely desirable. I'm not a fan of returning strings destined for the UI from core emulator libraries like HLE, Armeilleure etc, as they will be harder to localize.

I think the way this should be done, is that the `LoadXci`, `LoadNca` etc functions could return a status code to indicate success, or a reason that they failed. You could also define a custom exception type and throw that, which will allow you to pass back additional information like the missing update/dlc count. Either solution would be a lot cleaner than using public fields as a means of returning method results.

I've commented on code style regardless so that you're aware of those.

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx/Ui/Windows/TitleUpdateWindow.cs
> +                if(!File.Exists(path))
Missing space.
`if (!File.Exists(path))`

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx/Ui/Windows/TitleUpdateWindow.cs
> +                }
Maybe a newline after this.

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx/Ui/Windows/TitleUpdateWindow.cs
>                  AddUpdate(path);
Is it alright that this update is still added, even when it is missing?

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +        public static int ignoreLoadErrorState = 0;
Public variables should start with a capital letter.
`IgnoreLoadErrorState`

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +        // Used as a value for the button.
What button?

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +            if(loadFailureString != null)
Needs a space in `if (`

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +                if(invalidDlcCount > 0)
Needs a space in `if (`

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx.HLE/HOS/ApplicationLoader.cs
> +                    }
Newline after this.

2021-04-07 21:32 UTC, riperiperi commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +            if(invalidDlcCount > 0)
Needs a space in `if (`

2021-04-07 21:33 UTC, jms-c commented on Ryujinx/Ui/Windows/TitleUpdateWindow.cs
> +                if(!File.Exists(path))
Lol, genuinely didn't catch that because ryujinx is more lenient with title updates.

2021-04-07 21:35 UTC, jms-c commented
Thanks for the helpful feedback, I will develop some fixes tomorrow.

2021-04-10 19:14 UTC, jms-c commented
Syntax has improved and Rip In Peri Peri's suggestion has been implemented!

2021-04-11 09:19 UTC, jms-c commented
Review requested.

2021-04-23 15:09 UTC, jms-c commented
Please review.

2021-05-17 19:08 UTC, jms-c commented
Conflicts resolved (hopefully)!

2021-05-17 19:10 UTC, jms-c commented
Nope, not resolved lol. Time to code a fix.

2021-05-17 19:18 UTC, jms-c commented
Fixed! It was literally a one line fix lol

2021-05-17 20:21 UTC, jms-c commented
Converted to draft because it was hanging (and it's unmergeable therefore)

2021-05-29 15:48 UTC, jms-c commented
I have attempted to fix hanging on this PR. However, I believe there is a better way (that I don't know atm)

2021-11-30 05:41 UTC, Shahil-Ayato commented
Superseded by #2867.

2021-12-04 19:40 UTC, closed without merging