Fix "Hide Cursor on Idle" inefficiency
Ryujinx/Ryujinx pull request #2058
Opened 2021-02-25 07:19 UTC by mageven

Both `DateTime.Now` and `ReactiveObject.get` (due to RW lock) are pretty heavy calls and are called from a sensitive location `UpdateFrame()` (runs every ~1ms and is responsible for handling input) which is already in a bad enough state.

There's loads of ways to combat that. With this PR, I have simplified the logic and moved the checks to `HandleScreenState()` which runs in the GUI thread.

2021-02-25 08:10 UTC, Thog approved these changes
lgtm

2021-02-28 10:36 UTC, AcK77 requested changes

2021-02-28 10:36 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +        const int CursorHideIdleTime = 8; //seconds
```suggestion
        const int CursorHideIdleTime = 8; // seconds
```

2021-02-28 10:36 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +            ConfigurationState.Instance.HideCursorOnIdle.Event += HideCursorStateChanged;
Add a new empty line before

2021-02-28 12:51 UTC, riperiperi approved these changes
LGTM, with agreement with Ac_K's comments.

I didn't review the original, but I did see this code after it merged and had similar concerns. Good to see it fixed up.

2021-03-02 22:45 UTC, AcK77 approved these changes

2021-03-02 22:45 UTC, merged