Minor wording fixes... Except I'm doing it for all of Ryujinx.
Ryujinx/Ryujinx pull request #2078
Opened 2021-03-04 16:23 UTC by Mou-Ikkai

Let's make the wording a bit better, sure this is trivial, but I still want to do it.

2021-03-04 18:57 UTC, Mou-Ikkai commented
Done!

2021-03-04 19:03 UTC, EmulationFanatic reviewed
Left a couple of comments but overall these are good 👍

2021-03-04 19:05 UTC, Mou-Ikkai commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                            Logger.Error?.Print(LogClass.Application, "Extraction failed. The main NCA is not present in the selected file.");
Then I'll put "Extraction Failure", it's just that since it's happening at that moment.

2021-03-04 19:10 UTC, Shahil-Ayato commented on Ryujinx/Ui/MainWindow.cs
> +                    Logger.Error?.Print(LogClass.Application, $"Error updating: {task.Exception}");
This should be kept as `updater`

2021-03-04 19:11 UTC, Mou-Ikkai commented on Ryujinx/Ui/MainWindow.cs
> +                    Logger.Error?.Print(LogClass.Application, $"Error updating: {task.Exception}");
Doesn't go as smooth off the mind, but sure.

2021-03-04 19:14 UTC, EmulationFanatic commented on Ryujinx/Ui/MainWindow.cs
> +                            Logger.Info?.Print(LogClass.Application, "Loading as HomeBrew.");
Sorry, missed this one. I can't find any references to "HomeBrew" with a capital B. "Homebrew" seems to be the consensus format, but I'm not sure I would change any capitalization at all here.

2021-03-04 19:16 UTC, Mou-Ikkai commented on Ryujinx/Ui/MainWindow.cs
> +                            Logger.Info?.Print(LogClass.Application, "Loading as HomeBrew.");
It's just that with all the other formats being all capital, I decided Homebrew should at least have its proper starting capital letter. *And the capital B was a mistake.*

2021-03-05 13:01 UTC, Shahil-Ayato requested changes
LGTM just fix that thing I mentioned earlier ^^

2021-03-05 13:01 UTC, Shahil-Ayato commented on Ryujinx/Ui/MainWindow.cs
> +                GtkDialog.CreateInfoDialog("A game has already been loaded", "Please close the game and try again.");
Wouldn’t it be better to make it `Please close the game first and then try again` ?

2021-03-05 13:06 UTC, EmulationFanatic reviewed
Added a few more suggestions. It's your call if you want to change them or not.

2021-03-05 13:06 UTC, EmulationFanatic commented on Ryujinx/Ui/MainWindow.cs
> +                                Logger.Error?.Print(LogClass.Application, "The file which you have specified is not supported by Ryujinx.");
"The specified file is not supported by Ryujinx." would be more concise.

2021-03-05 13:06 UTC, EmulationFanatic commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                GtkDialog.CreateErrorDialog("Some fields entered were invalid and therefore your config was not saved.");
"Invalid data detected in one or more fields; the configuration was not saved." would be proper English.

2021-03-05 13:06 UTC, EmulationFanatic commented on Ryujinx/Ui/MainWindow.cs
> +                GtkDialog.CreateInfoDialog("A game has already been loaded", "Please close the game and try again.");
"A game has already been loaded", "Please stop emulation or close the emulator before launching another game."

2021-03-05 13:07 UTC, Mou-Ikkai commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                GtkDialog.CreateErrorDialog("Some fields entered were invalid and therefore your config was not saved.");
I'll definitely do this one.  Since the default dialogue has a typo in there, not fun.

2021-03-05 13:10 UTC, Shahil-Ayato commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                                GtkDialog.CreateErrorDialog("Extraction failure. The main NCA is not present in the selected file.");
I think leaving it as `Failed` would be better here.

2021-03-05 13:12 UTC, EmulationFanatic commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                                GtkDialog.CreateErrorDialog("Extraction failure. The main NCA is not present in the selected file.");
Alternatively, you can cover all your bases with:
"when were you when extraction was kill? 
I was sit at home loding switch gaem NCA. 
"extraction is kill" 
"no"

2021-03-05 13:15 UTC, Mou-Ikkai commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                                GtkDialog.CreateErrorDialog("Extraction failure. The main NCA is not present in the selected file.");
Perfect, Fanatic

2021-03-17 12:18 UTC, EmulationFanatic approved these changes
LGTM

2021-03-18 22:44 UTC, AcK77 approved these changes

2021-03-18 22:44 UTC, merged

2021-03-20 22:31 UTC, Pixxel123 commented
I would also suggest changing the `OpenAl` in the config json to `OpenAL`, if you still wanting to do more word changes!

https://github.com/Ryujinx/Ryujinx/blob/bcbf240d2eab2a2794224487d87519ac31016c96/Ryujinx/_schema.json#L1280