Prevent Display Sleep on Linux
Ryujinx/Ryujinx pull request #2080
Opened 2021-03-05 02:30 UTC by pineappleEA

#1850 addressed the issue for Windows users, this one aims to do so for Linux ones.

While the Windows code runs only once, in the MainWindow, this isn't possible with X11 (I know, I hate Xorg too). Instead, we have to reset the counter constantly so I do it on the UpdateFrame loop.

It's important to note that IntPtr.Zero makes libX11 look at the DISPLAY environmental variable for the display (if you only have one screen it's :0).

2021-03-05 03:34 UTC, CeruleanSky commented
Any reason for not using a timer of a few hundred milliseconds (System.Threading.Timer , System.Timers.Timer, or maybe there is a better one) and not calling this from MainWindow.cs around where the windows one is called or another place?

I saw [log message on a recent pull request](https://github.com/Ryujinx/Ryujinx/pull/2058#issue-579870534) that the update frame code is pretty abused as is, and it might be better to keep more things out of there when it can be done.

2021-03-10 19:06 UTC, pineappleEA commented
The PR is open for review again!

Radically changed the way it works, Instead of Opening a Display , sending the Reset signal every frame on UpdateFrame() of GLRenderer, a function that starts the timer on MainWindow starts and stops at the same time with the Windows functions.  The timer Opens a Display, sends the Reset signal and Closes the Display every 25s. Since some laptops may dim the screen after 30s of idle, 25s feels about right.

2021-03-10 19:56 UTC, gdkchan commented
Is that really how applications usually disable the screen saver on linux? It looks very hacky with the call every 25 seconds.

2021-03-10 19:59 UTC, jms-c commented
What about XScreenSaverSuspend?
That would stop the screensaver too. (however, this solution is also quite popular it seems)

2021-03-10 20:04 UTC, pineappleEA commented
I've attempted every possible solution. The best solution is to send a DBus message according to freedesktop, sadly GNOME doesn't respect that and GNOME has the biggest share when it comes to desktop environments. Indeed it is hacky and I despise the solution, Xorg indeed is at a terrible state. Regarding what other software does, MPV sends the reset signal every 10s and bsnes a fake keypress every 20 (which is the same as sending a reset signal I guess).

2021-03-14 18:31 UTC, AcK77 approved these changes

2021-03-15 23:31 UTC, Xpl0itR requested changes
As previously discussed on discord, using a timer to invoke a dll every 25 seconds isn't a good idea. You should instead use dbus, `org.gnome.SessionManager.Inhibit` on gnome and `org.freedesktop.ScreenSaver.Inhibit` elsewhere.

2021-03-17 17:13 UTC, pineappleEA commented
I believe treating each compositor differently is a worse solution. For example, during my test I found out dbus is broken on kwin too, it expects qdbus.

2021-04-04 20:49 UTC, Alkaid-Benetnash commented
I currently use `https://github.com/FeralInteractive/gamemode` to deal with screensaver on Gnome 3.38.
According to [their source code](https://github.com/FeralInteractive/gamemode/blob/b11d2912e280acb87d9ad114d6c7cd8846c4ef02/daemon/gamemode-dbus.c#L711), gamemode seems to only use the freedesktop dbus interface.
Not sure why @pineappleEA found gnome not respecting that API.

2021-04-06 12:27 UTC, pineappleEA commented
@Alkaid-Benetnash I tested gamemoderun on KDE and indeed prevents sleep. It's nice to hear GNOME works with `org.freedesktop.ScreenSaver.Inhibit` and doesn't require `org.gnome.SessionManager.Inhibit`. I'll take a closer look at what gamemode does and if that's the case someone should tell BSNES and MPV devs too since they do similar calls every some seconds

2022-07-11 22:58 UTC, AcK77 commented
Closed due to inactivity and a hacky way to handle things. Feel free to fix things and reopen it later! Thanks.

2022-07-11 22:58 UTC, closed without merging