Add analog stick range modifier
Ryujinx/Ryujinx pull request #2095
Opened 2021-03-10 21:19 UTC by SutandoTsukai181

Adds a range modifier for analog sticks. Partially addresses #2059.

The range slider's bounds are [0.0, 1.0] for keyboard, and [0.0, 2.0] for controllers.
Keyboard has an extra button (LStick Modifier) to apply the modifier while it's held down (default is Left Shift). Controllers do not have a button, as the range modifier is applied directly (as per #2059).

Preview and default values:

[Keyboard](https://cdn.discordapp.com/attachments/412730623405457408/819305847226105947/unknown.png)

[Controller](https://cdn.discordapp.com/attachments/412730623405457408/819305888958775326/unknown.png)

2021-03-13 08:27 UTC, SutandoTsukai181 commented
In case the diff count is preventing someone from reviewing, the actual diff count is 235 (195 additions, 40 deletions). I used a newer glade version which is why that file has a lot of changes 😅.

2021-03-22 21:12 UTC, AcK77 requested changes

2021-03-22 21:12 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 24;
This should be `23` but will probably need to be changed back if anything is merged before this PR.

2021-03-22 21:12 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/KeyboardConfig.cs
> +        public Key LeftStickRangeButton { get; set; }
Should be in `NpadKeyboardLeft` maybe ?

2021-03-22 21:12 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/KeyboardConfig.cs
> +        public Key RightStickRangeButton { get; set; }
Should be in `NpadKeyboardRight` maybe ?

2021-03-22 21:12 UTC, AcK77 commented on Ryujinx/Config.json
> +  "version": 24,
same comment as the first one : `23`

2021-03-22 21:12 UTC, AcK77 commented on Ryujinx/_schema.json
> +        "range_modifier_left": {
Why there is those 2 items `range_modifier_left` and `range_modifier_right` twice ?

2021-03-22 21:12 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.glade
> +<!-- Generated with glade 3.38.2 -->
https://github.com/Ryujinx/Ryujinx/issues/1699

There are a lot of unneeded changes here, some items have been renamed which could cause issues.
There are a bunch of empty code too:
```
                                        <child>
                                          <placeholder/>
                                        </child>
```

2021-03-23 04:01 UTC, SutandoTsukai181 commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 24;
I followed [this](https://github.com/Ryujinx/Ryujinx/pull/1866/files#r551575809) PR, but I forgot to leave a comment. In this context, 23 is #2082

2021-03-23 04:07 UTC, SutandoTsukai181 commented on Ryujinx.Common/Configuration/Hid/KeyboardConfig.cs
> +        public Key LeftStickRangeButton { get; set; }
I tried to avoid adding these 2 keys to `NpadKeyboard` because all of the keys there are directly mapped to native switch input. I thought adding something that is not native input in there would be confusing.

2021-03-23 04:09 UTC, SutandoTsukai181 commented on Ryujinx/Ui/Windows/ControllerWindow.glade
> +<!-- Generated with glade 3.38.2 -->
Alright, will revert to `3.22.1` and update the file again.

2021-03-23 04:17 UTC, SutandoTsukai181 commented on Ryujinx/_schema.json
> +        "range_modifier_left": {
These 2 are for `controller_config` (check "$id" element), and the previous 2 are for `keyboard_config`. Also, the range for controllers is between 0 and 2, while the range for keyboard is between 0 and 1, so that's another reason why they should be separate.

2021-03-23 04:21 UTC, SutandoTsukai181 commented on Ryujinx/_schema.json
> +          "description": "Controller Left Analog Stick Range",
I kinda missed what this description is referring to. Is it referring to the actual input device (keyboard) or the switch input (controller/joycon)? Should this be `Keyboard Left Analog Stick Range` instead?

2021-03-23 04:54 UTC, SutandoTsukai181 commented on Ryujinx/Ui/Windows/ControllerWindow.glade
> +<!-- Generated with glade 3.38.2 -->
Changes addressed.

2021-03-29 21:49 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 24;
I don't know which one will be merged first, so it's better to follow what there is on master instead of opened PR.

2021-03-29 21:54 UTC, AcK77 commented on Ryujinx/_schema.json
> +          "description": "Controller Left Analog Stick Range",
The description referring to the what the field is... So yeah it should be `Keyboard Left Analog Stick Range`

2021-03-29 22:31 UTC, SutandoTsukai181 commented
@AcK77 All changes addressed: reverted back to the older glade version, changed the config version, and updated the schema descriptions.

2021-04-03 10:48 UTC, SutandoTsukai181 commented
Waiting for reviews.

2021-04-11 13:33 UTC, SutandoTsukai181 commented
Will wait for #2194 to be merged before rebasing and continuing work on this.

2021-06-12 08:31 UTC, Thog commented
This needs a rewrite because of #2194.

2021-06-12 08:31 UTC, closed without merging