Improves logging to console.
Ryujinx/Ryujinx pull request #2146
Opened 2021-03-26 16:00 UTC by Pixxel123

This PR aims to expose more user changeable information in the logs, mainly so that the upcoming Discord bot (https://github.com/Ryujinx/ryuko-ng/pull/3) can use this information for analysis.

This also simplifies the hotkey states logging from #1942 (which I have removed due to cluttering up tests), as it uses the already recorded configuration states and leverages the already existing `ReactiveObject.cs` change state.

Both UI menu item changes and hotkey changes are logged in real time.

I've grouped the values into categories as well, for easier parsing for analysis. If objects do not have a name, they won't be printed, so I've left some commented placeholders for those who want more information exposed for their purposes.

2021-03-26 16:20 UTC, AcK77 commented
`Ryujinx.HLE/HOS/Horizon.cs` Needs a rebase

2021-03-27 13:57 UTC, AcK77 requested changes
Good idea, it's way better than the current way. I've just some changes requested ;)!

2021-03-27 13:57 UTC, AcK77 commented on Ryujinx.Common/ReactiveObject.cs
> +                    if (!string.IsNullOrEmpty(Name))
Add brackets hover the next 3 lines

2021-03-27 13:57 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> -            if (_audioBackendSelect.GetActiveIter(out TreeIter activeIter))
You should add this next code back, because if you don't, the audio backend isn't configurable anymore using the GUI.
```
            if (_audioBackendSelect.GetActiveIter(out TreeIter activeIter))
            {
                ConfigurationState.Instance.System.AudioBackend.Value = (AudioBackend)_audioBackendStore.GetValue(activeIter, 1);
            }
```

(https://github.com/Ryujinx/Ryujinx/pull/1942/files#diff-52233a1b2858093f071f6439da4b0c888e8fdc4859d60ecdf73b6089c43d739bL434)

2021-03-27 13:57 UTC, AcK77 commented on Ryujinx.Common/ReactiveObject.cs
> +        public string _name { get; private set; }
Add a new empty line before

2021-03-27 13:57 UTC, AcK77 commented on Ryujinx.Common/ReactiveObject.cs
> -                _value         = value;
Could be nice to keep the alignment here

2021-03-27 13:57 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                GameDirs          = new ReactiveObject<List<string>>(); //{ Name = "Game dir", Category = "UI" };
I don't think those commented args are really useful. They could be added easily if needed so it's probably better to remove those.
(Same suggestion for all other fields)

2021-03-27 23:31 UTC, Pixxel123 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                GameDirs          = new ReactiveObject<List<string>>(); //{ Name = "Game dir", Category = "UI" };
Would it be worth having a comment at the start that states something like "Add a name and category to items that should appear in the log"?

2021-03-28 00:14 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                GameDirs          = new ReactiveObject<List<string>>(); //{ Name = "Game dir", Category = "UI" };
You can remove the commented lines and keep only one you have done, since they are useful one! The rest of fields doesn’t really needs logging, and if they needs to be logged one day, we could easily understand how do it by looking to other declared one. (Even more when you considering this will be only done by developers)

2021-03-29 21:58 UTC, AcK77 requested changes

2021-03-29 21:58 UTC, AcK77 commented on Ryujinx.Common/Logging/LogClass.cs
> +        Configuration
Sort this alphabetically

2021-03-29 21:58 UTC, AcK77 commented on Ryujinx.Common/ReactiveObject.cs
> +        private string _name { get; set; }
`_name` and `Name` aren't used and can be removed

2021-03-29 21:58 UTC, AcK77 commented on Ryujinx.Common/ReactiveObject.cs
> +        public string LoggedName { get; }
This is not used and can be removed too

2021-03-29 21:58 UTC, AcK77 commented on Ryujinx.Common/ReactiveObject.cs
> +                        //When values are changed, logged to console. If value does not have a Name, no log is printed
I don't think those 2 lines of comment are really revelent. They could be removed.

2021-03-29 22:45 UTC, AcK77 approved these changes
Lgtm! Thanks!

2021-03-29 22:56 UTC, Thog approved these changes

2021-04-03 00:14 UTC, jduncanator commented on Ryujinx.Common/ReactiveObject.cs
> +        public ReactiveObject(string loggedName = "")
I don't really like the idea of this information being stored in the ReactiveObject itself, the ReactiveObject is designed to be reusable as a generic component, so having it intrinsically linked to "logging" in some way breaks the concept of separation of concerns. Worst case, I'd rather this just be called `name`, rather than `loggedName`.

2021-04-03 00:15 UTC, jduncanator commented on Ryujinx.Common/ReactiveObject.cs
> +                        Logger.Info?.Print(LogClass.Configuration, $"{_loggedName} set to: {_value}");
I think this should be handled in the Configuration code. You can add an additional event handler to the `Event` event of each configuration object, and then log the changes there. The way this currently is, any other reuse of ReactiveObject for anything not related to configuration will potentially spam these log messages.

2021-04-03 00:17 UTC, jduncanator commented on Ryujinx.Common/ReactiveObject.cs
> +        public ReactiveObject(string loggedName = "")
Perhaps you could use a `DisplayNameAttribute` on each configuration field in `ConfigurationState` and use that to determine a "friendly name" for the configuration object?

2021-04-04 20:12 UTC, gdkchan reviewed
Needs a rebase now that a new setting has been added.

2021-04-04 20:12 UTC, gdkchan commented on Ryujinx.Common/ReactiveObject.cs
> +                      Event?.Invoke(this, new ReactiveEventArgs<T>(oldValue, value));
Why the extra space here?

2021-04-07 12:03 UTC, jms-c approved these changes
Looks good to me! 
Have a nice day!

2021-04-12 19:32 UTC, riperiperi approved these changes
Looks good, will be useful seeing this info on logs.

2021-04-13 19:58 UTC, merged