Add inlined on translation call counting
Ryujinx/Ryujinx pull request #2190
Opened 2021-04-09 17:45 UTC by FICTURE7

Contributes to #2158.

* Add re-usable structures to do on translation counting (might want to make `Counter` a generic though).
* Add on translation call counting.
* Change call counting behavior to be associated with nodes (i.e head of translations) instead of edges (i.e out of translation branches). Before if all incoming branches to a translation was not hinted for rejit, it would never tier up even though it could be hot.
  * **Pros**: Improves hot code discovery.
  * **Cons**: Increase in code size. -- Because we may discover more code to rejit, and the decoder may produce a far larger output for HCQ than for LCQ.

PPTC integration is done this way for the sake of simplicity and because it allows `EntryTable` to be dynamic/expandable, although it currently is not.

Call counting is not implemented as an atomic operation currently, so `EnqueueForRejit` needs to ensure the rejit queue contains unique requests so as to not waste time compiling the same stuff. I held back from implementing an IR instruction for this because I figure it would require some discussion to model it in IR, and I am not entirely if its worth. If you think so let me know :>

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Common/Counter.cs
> +        /// Tries to create a <see cref="Counter"/> instance from the specified <see cref="EntryTable{byte}"/> instance.
```suggestion
        /// Tries to create a <see cref="Counter"/> instance from the specified <see cref="EntryTable{T}"/> instance.
```

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Common/Counter.cs
> +        /// <param name="countTable"><see cref="EntryTable{TEntry}"/> from which to create the <see cref="Counter"/></param>
```suggestion
        /// <param name="countTable"><see cref="EntryTable{T}"/> from which to create the <see cref="Counter"/></param>
```

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Common/EntryTable.cs
> +        /// Initializes a new instance of the <see cref="EntryTable{TValue}"/> class with the specified capacity.
```suggestion
        /// Initializes a new instance of the <see cref="EntryTable{TEntry}"/> class with the specified capacity.
```

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Common/EntryTable.cs
> +        /// Tries to allocate an entry in the <see cref="EntryTable{TValue}"/>. Returns <see langword="true"/> if
```suggestion
        /// Tries to allocate an entry in the <see cref="EntryTable{TEntry}"/>. Returns <see langword="true"/> if
```

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Translation/PTC/Ptc.cs
> +        private static TranslatedFunction FastTranslate(ReadOnlySpan<byte> code, Counter<uint> callCounter, ulong guestSize,
We usually put each argument on a separate line when it becomes too long, rather than spliting it like that.

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Translation/PTC/Ptc.cs
> +        internal static void MakeAndSaveTranslations(ConcurrentDictionary<ulong, TranslatedFunction> funcs, IMemoryManager memory,
Same comment as above.

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Translation/Translator.cs
> +            CountTable = new EntryTable<uint>(capacity: 4 * 1024 * 1024);
I'd prefer if a constant was defined for `4 * 1024 * 1024` on the top of the class.

2021-04-12 21:13 UTC, gdkchan commented on ARMeilleure/Translation/Translator.cs
> +                            Ryujinx.Common.Logging.Logger.Info?.Print(
Not sure if logging rejit requests is desirable, especially as "Info". It can certainly be useful, but I don't think its something we'd want to log by default.

2021-04-13 06:35 UTC, FICTURE7 commented on ARMeilleure/Translation/PTC/Ptc.cs
> +            UnwindInfo unwindInfo, bool highCq)
```suggestion
        private static TranslatedFunction FastTranslate(
            ReadOnlySpan<byte> code,
            Counter<uint> callCounter,
            ulong guestSize,
            UnwindInfo unwindInfo,
            bool highCq)
```

2021-04-13 06:36 UTC, FICTURE7 commented on ARMeilleure/Translation/PTC/Ptc.cs
> +            JumpTable jumpTable, EntryTable<uint> countTable)
```suggestion
        internal static void MakeAndSaveTranslations(
            ConcurrentDictionary<ulong, TranslatedFunction> funcs,
            IMemoryManager memory,
            JumpTable jumpTable,
            EntryTable<uint> countTable)
```

2021-04-13 06:37 UTC, FICTURE7 commented on ARMeilleure/Translation/PTC/Ptc.cs
> +            JumpTable jumpTable, EntryTable<uint> countTable)
```suggestion
        internal static void LoadTranslations(ConcurrentDictionary<ulong, TranslatedFunction> funcs, IMemoryManager memory,
            JumpTable jumpTable, EntryTable<uint> countTable)
```
```suggestion
        internal static void LoadTranslations(
            ConcurrentDictionary<ulong, TranslatedFunction> funcs, 
            IMemoryManager memory,
            JumpTable jumpTable,
            EntryTable<uint> countTable)
```

2021-04-13 06:40 UTC, FICTURE7 commented on ARMeilleure/Translation/Translator.cs
> +        private long _nextUpdate;
```suggestion
        private const int CountTableCapacity = 4 * 1024 * 1024;

        private long _nextUpdate;
```

2021-04-13 06:41 UTC, FICTURE7 commented on ARMeilleure/Translation/Translator.cs
> +            CountTable = new EntryTable<uint>(capacity: 4 * 1024 * 1024);
```suggestion
            CountTable = new EntryTable<uint>(CountTableCapacity);
```

2021-04-13 07:43 UTC, FICTURE7 commented on ARMeilleure/Translation/Translator.cs
> +                            Ryujinx.Common.Logging.Logger.Info?.Print(
I decided to remove it, there are probably better ways to instrument this with event counters.

2021-04-13 15:07 UTC, gdkchan approved these changes
lgtm, thanks!

2021-04-13 23:54 UTC, gdkchan commented
Tests are failing, apparently the changes are causing a hard crash when they are executed. I recommend trying to run them locally.

2021-04-14 08:28 UTC, FICTURE7 commented
It was not disposing the `Counter<T>` instances and since they had finalizers, they would survive a gen0 collection and so would the `EntryTable<T>`. This meant that memory would fluctuate a lot more during the tests because `Translator` instances (and thus `EntryTable<T>`) are constantly allocated, and the `EntryTable<T>` instances would live up to at least gen1. I guess the windows CI did not like this fluctuation, since I could not reproduce this once even with server GC toggled on.

2021-04-15 15:34 UTC, LDj3SNuD requested changes

2021-04-15 15:34 UTC, LDj3SNuD commented on ARMeilleure/Translation/Translator.cs
> +            }
I think we should raise an exception here, in the hypothetical case of not being able to allocate a further entry in the count table, also to avoid not being able to have rejits. In this way we can realise the limit and increase the capacity of the table.

2021-04-15 15:34 UTC, LDj3SNuD commented on ARMeilleure/Common/Counter.cs
> +        public ref T Value
Nit:
```suggestion
        public ref T Value
```

2021-04-15 15:34 UTC, LDj3SNuD commented on ARMeilleure/Common/Counter.cs
> +                return ref _countTable.GetValue(_index);
Nit:
```suggestion
                return ref _countTable.GetValue(_index);
```

2021-04-15 15:34 UTC, LDj3SNuD commented on ARMeilleure/Common/EntryTable.cs
> +            _table = GC.AllocateArray<TEntry>(capacity, pinned: true);
The approach is certainly interesting (https://tooslowexception.com/pinned-object-heap-in-net-5/) but tests (see below) show a significant reduction in performance linearly dependent on the capacity of the table (currently 16 MiB).
It would be advisable instead to use `_table = Marshal.AllocHGlobal(capacity);` and add a Dispose() method `Marshal.FreeHGlobal(_table);`.
To avoid wasting 16 MiB per run without restarting the emulator, the constructor of this class could be called in the `if (Interlocked.Increment(ref _threadCount) == 1)` block (@ Translator.Execute()) and the Dispose() method in the `if (Interlocked.Decrement(ref _threadCount) == 0)` block.

```
GitHub CI Artifact | GitHub CI Tests Time

#2190:
ubuntu-latest (Debug)    | 12m 42s
ubuntu-latest (Release)  | 6m 30s
macOS-latest (Debug)     | 13m 25s
macOS-latest (Release)   | 9m 57s
windows-latest (Debug)   | 9m 20s
windows-latest (Release) | 13m 6s

#master:
ubuntu-latest (Debug)    | 2m 2s
ubuntu-latest (Release)  | 2m 40s
macOS-latest (Debug)     | 1m 57s
macOS-latest (Release)   | 1m 53s
windows-latest (Debug)   | 2m 37s
windows-latest (Release) | 2m 17s
```
```
CountTableCapacity | Local Tests Time

4 * 1024 * 1024 | ~10:00
...
1000000 | 3:36
500000  | 2:42
250000  | 2:02
125000  | 1:40
62500   | 1:33
31250   | 1:28
```

2021-04-15 15:53 UTC, FICTURE7 commented on ARMeilleure/Common/EntryTable.cs
> +            _table = GC.AllocateArray<TEntry>(capacity, pinned: true);
Sounds good to me.

2021-04-16 14:29 UTC, FICTURE7 commented on ARMeilleure/Instructions/InstEmitFlowHelper.cs
> +                        typeof(NativeInterface).GetMethod(nameof(NativeInterface.GetFunctionAddress)), address);
```suggestion
                    Operand fallbackAddr = context.Call(typeof(NativeInterface).GetMethod(nameof(NativeInterface.GetFunctionAddress)), address);
```

2021-04-16 14:44 UTC, FICTURE7 commented on ARMeilleure/Common/EntryTable.cs
> +            _table = GC.AllocateArray<TEntry>(capacity, pinned: true);
FWIW this could also be fixed by implementing a memory pool, but busting out a memory pool to get a completely managed table seemed more like wishful thinking than anything else. Much like getting the tests to re-use the same `Translator` instance.

Kinda bummbed out I was not suspicious of the tests runtime. Thanks a lot for noticing and looking into this. 👍

2021-04-17 14:02 UTC, FICTURE7 commented
Here's a chart of the working set of bcab67f (red) vs 5f5abaa (blue). Let me know if this is a concern, I'll revert 5f5abaa if so.

![bcab67f vs 5f5abaa](https://user-images.githubusercontent.com/8182340/115115728-052b2300-9fa7-11eb-80de-06418484e1fb.png)

2021-04-17 17:49 UTC, LDj3SNuD commented
I think the previous solution (on bcab67f) is preferable.
The current expandability of the table is welcome.
I also raise the question of the usefulness of using a template for the EntryTable class; because if we had a table with fixed-size entries (4 or 8 bytes per entry, for example) we could simplify a few things, not only in the class itself but also externally; we could send around `Value` as `IntPtr` type and for example we'd have `Operand address = Const(counter.Value.ToInt64(), true, Ptc.CountTableIndex);` (@ Translator.EmitRejitCheck()) while also avoiding
```csharp
        public static unsafe Operand Const<T>(ref T reference, int? index = null)
        {
            return Operand().With((long)Unsafe.AsPointer(ref reference), index != null, index);
        }
```
(@ OperandHelper.cs)
and in Ptc.PatchCode() we'd have `imm = (ulong)callCounter.Value.ToInt64();`.
This is not a prerequisite for PR approval.

2021-04-17 18:15 UTC, FICTURE7 commented
The idea behind making `EntryTable` a generic was to make it a re-usable structure. For example it could re-used to replace the jump tables we currently use, and could be useful for various overnight experiments. Like implementing profiling/instrumentation of compiled code or implementing a constant pool.

As for using `IntPtr` as return value, it seems to me quite unideal to pass raw pointers around when we could be passing proper references. Plus it allows us to read and write to these references directly from C# without using things like `Marshal`. E.g here:
https://github.com/Ryujinx/Ryujinx/blob/dc8c781d7a8a6778e493cca798cf2a7d298983de/ARMeilleure/Instructions/NativeInterface.cs#L256-L262

2021-04-18 12:36 UTC, LDj3SNuD approved these changes

2021-04-18 12:37 UTC, LDj3SNuD commented
lgtm, ty

2021-04-18 21:42 UTC, gdkchan approved these changes

2021-04-18 21:43 UTC, merged