Show Game Compatibility in UI
Ryujinx/Ryujinx pull request #2193
Opened 2021-04-10 14:56 UTC by Joshi234

This allow you to see the game compatibility in the ui as a column and open the website for more informations directly from the ui
![image](https://user-images.githubusercontent.com/46032261/114274209-a81af480-9a1d-11eb-906f-d2263e17de1d.png)
![image](https://user-images.githubusercontent.com/46032261/114274222-afda9900-9a1d-11eb-8bba-c686a5842025.png)

2021-04-10 15:57 UTC, saldabain requested changes

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            if (ConfigurationState.Instance.Ui.GuiColumns.FavColumn) _favToggle.Active = true;
Alignments needs adjusting

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            _favToggle.Toggled += Fav_Toggled;
Same as above

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/Helper/CompatibilityHelper.cs
> +                     comp = JsonSerializer.Deserialize<CompatibilityItem[]>(await client.GetStringAsync(_githubEndpointUrl + @"repos/Ryujinx/Ryujinx-Games-List/issues?per_page=100&page=" + page.ToStr
Consider using C#s implicit string formatter instead of manual concatenation:
                     `comp = JsonSerializer.Deserialize<CompatibilityItem[]>(await client.GetStringAsync($"{_githubEndpointUrl}repos/Ryujinx/Ryujinx-Games-List/issues?per_page=100&page={page.ToString()}"));`

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            DefaultWidth = monitorWidth < 1280 ? monitorWidth : 1280;
Alignment

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> -            int monitorWidth  = Display.PrimaryMonitor.Geometry.Width  * Display.PrimaryMonitor.ScaleFactor;
Alignment

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            Icon = new Gdk.Pixbuf(Assembly.GetExecutingAssembly(), "Ryujinx.Ui.Resources.Logo_Ryujinx.png");
Same as above :)

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            _virtualFileSystem = VirtualFileSystem.CreateInstance();
Same as above

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            _uiHandler = new GtkHostUiHandler(this);
Same as above

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            DeleteEvent += Window_Close;
Same as above

2021-04-10 15:57 UTC, saldabain commented on Ryujinx/Ui/MainWindow.cs
> +            _fullScreen.Activated += FullScreen_Toggled;
Same as above

2021-04-10 15:58 UTC, saldabain commented
Overall lgtm other than the nits, bear in mind this PR might not get merged until the new UI rolls out (if even then) but nice job :)

2021-04-10 16:33 UTC, Joshi234 commented
I hope it gets merged before the new UI so I don't have to care about all the conflicts

2021-04-10 23:36 UTC, Shahil-Ayato commented
> I hope it gets merged before the new UI so I don't have to care about all the conflicts

Afaik the new UI is coming this month so you may need to port this over to Avalonia.

2021-04-11 01:38 UTC, Powerlated commented
Parsing the compatibility strings and making them pertain more to human readers would also be nice.

2021-04-11 16:04 UTC, Joshi234 commented
This is ready for review btw

2021-04-12 19:21 UTC, riperiperi commented
This cannot work as is, for a few reasons:

- Github has a 100 issue max page size, which you are honoring... However, it means that every time this is updated, Ryujinx makes **34 requests** to the GitHub API. I don't think we should be doing that.
- Each one of these issue pages contains a LOT more information than is needed, including a _full issue body_. Each page is over 500kb, meaning that Ryujinx ends up downloading... **17MB** of GitHub issues, right now. That's a very large download to surprise people with, they could be on a metered connection.
- An additional web service to depend on makes the emulator flimsier if it goes down. Amiibo and LDN are necessary to be online, but this is not.
  - A way of avoiding this could be building the compatibility list at build time (on GitHub Actions) and distributing just that as a JSON file with each build, with only the required information. However, making 34 requests to the GitHub API for each GitHub Actions build is also a lot of a problem.
  - The cost for accessing the GitHub API could be moved elsewhere. A web service that processes the issue list daily and builds this JSON file could be created, which will mean only making these requests a manageable number of times.
- There's already a replacement compatibility site on the way, maybe you should contact trickster about integrating with the stuff he's building.
  - Perhaps he already has a service for creating a smaller cached compat list that you could use.

Note that these are just my opinions. You'll need to ask other members of the team about theirs.

2021-04-12 22:37 UTC, Joshi234 commented
> This cannot work as is, for a few reasons:
> 
> * Github has a 100 issue max page size, which you are honoring... However, it means that every time this is updated, Ryujinx makes **34 requests** to the GitHub API. I don't think we should be doing that.
> * Each one of these issue pages contains a LOT more information than is needed, including a _full issue body_. Each page is over 500kb, meaning that Ryujinx ends up downloading... **17MB** of GitHub issues, right now. That's a very large download to surprise people with, they could be on a metered connection.
> * An additional web service to depend on makes the emulator flimsier if it goes down. Amiibo and LDN are necessary to be online, but this is not.
>   
>   * A way of avoiding this could be building the compatibility list at build time (on GitHub Actions) and distributing just that as a JSON file with each build, with only the required information. However, making 34 requests to the GitHub API for each GitHub Actions build is also a lot of a problem.
>   * The cost for accessing the GitHub API could be moved elsewhere. A web service that processes the issue list daily and builds this JSON file could be created, which will mean only making these requests a manageable number of times.
> * There's already a replacement compatibility site on the way, maybe you should contact trickster about integrating with the stuff he's building.
>   
>   * Perhaps he already has a service for creating a smaller cached compat list that you could use.
> 
> Note that these are just my opinions. You'll need to ask other members of the team about theirs.

I decided to create an API which gets all the issues using an access token once a day and then only returns the needed values.
The API is hosted for free on heroku and can be found here: https://ryujinx-compatibility-api.herokuapp.com/

2021-04-12 23:40 UTC, gdkchan commented
I'm not a fan of this, and the way it is show on the UI is confusing imo. Would be more clear to just show the state of the game, like "Playable", "In-Game", "Nothing", maybe with different colours for each state. Anyway, my other concerns were already listed above by riperiperi so no point in repeating them.

2021-04-15 14:44 UTC, Joshi234 commented
Closing this for now, I gonna port it over to the new ui when it arrives

2021-04-15 14:44 UTC, closed without merging