Miria: The Death of OpenTK 3
Ryujinx/Ryujinx pull request #2194
Opened 2021-04-10 22:07 UTC by Thog

As a preparation for the new UI system and for Vulkan, this PR removes OpenTK 3 dependency entirely.

To do so, a new input system was implemented for keyboard and controller handling. On the controller side, SDL2 was chosen and handling of controllers was completely revisited.

With this new input system the following new features are now available:
- Controllers can now be hot-plugged without any constraints. No need to click any "refresh" buttons.
- Motion is supported without the need of external tools on supported controllers. (Legacy Cemuhook integration is still present if desired)
- Rumble API is exposed **while still not in use for now** (outside the scope of this PR)
- DS4, DS5, Pro Controller and Single Joycons are natively supported. (Joycon pairs are not yet natively supported and outside the scope of this PR; Cemuhook integration can be used for this in the meantime.)
- GTK3 keyboard introduces support for different regional layouts.
- When a gamepad isn't supported by SDL2, a user can extend compatibility and mappings via the addition of a ``SDL_GameControllerDB.txt`` file in the same directory as ``Ryujinx.exe``. See [SDL_GameControllerDB](https://github.com/gabomdq/SDL_GameControllerDB) for community efforts.

As the nature of these changes are highly incompatible with (and impossible to migrate from) the old system, this will reset input configurations.

Changelog:
- Switch to OpenTK 4 for OpenAL implementation and mark as obsolete.
- Switch to OpenTK 4 for the Ryujinx.Graphics.OpenGL project.
- Use [SPB](https://github.com/Thog/SPB) for context creation and manipulations instead of OpenTK 3.
   - Currently only WGL and GLX backend are supported. (no regressions compared to old implementation)
- Switch to SDL2 for controller input.
- Switch to GTK3 for keyboard input.
- Individual keyboard support was deprecated.

2021-04-11 02:25 UTC, Ghostotakoi commented
Plans for native mouse support

2021-04-11 13:26 UTC, SutandoTsukai181 commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +namespace Ryujinx.Input.GTK3
`Ryujinx.Input.GTK3` is in a folder in `Ryujinx` project instead of in its own project or inside `Ryujinx.Input`. Is this intentional?

2021-04-11 13:33 UTC, Thog commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +namespace Ryujinx.Input.GTK3
This is tied to GTK3 and the UI itself, there is no need of moving it as it's not code that can be shared across UIs.

2021-04-11 19:41 UTC, AcK77 requested changes

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/Controller/Motion/StandardMotionConfigController.cs
> +    public class StandardMotionConfigController : MotionConfigController
```suggestion
    public class StandardMotionConfigController : MotionConfigController { }
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/Controller/StandardControllerInputConfig.cs
> +    public class StandardControllerInputConfig : GenericControllerInputConfig<GamepadInputId, StickInputId>
```suggestion
    public class StandardControllerInputConfig : GenericControllerInputConfig<GamepadInputId, StickInputId> { }
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/Keyboard/StandardKeyboardInputConfig.cs
> +    public class StandardKeyboardInputConfig : GenericKeyboardInputConfig<Key>
```suggestion
    public class StandardKeyboardInputConfig : GenericKeyboardInputConfig<Key> { }
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Input/GTK3/GTK3KeyboardDriver.cs
> +        public event Action<string> OnGamepadConnected;
Could be nice to fix those warnings

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Input/GTK3/GTK3KeyboardDriver.cs
> +
remove extra empty line

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +            // IsRenderHandler = true;
Why don't remove it?

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +
remove extra empty line

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
> +            ToggleVSync,
```suggestion
            ToggleVSync
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/GLWidget.cs
> +            } catch (Exception) {}
```suggestion
            }
            catch (Exception) { }
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/SPBOpenGLContext.cs
> +            // window.Hide();
leftover?

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            _lStick.Label                    = "Unbound";
```suggestion
            _lStick.Label                     = "Unbound";
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            _rStick.Label                    = "Unbound";
```suggestion
            _rStick.Label                     = "Unbound";
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            _enableCemuHook.Active           = false;
```suggestion
            _enableCemuHook.Active            = false;
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    _enableCemuHook.Active           = controllerConfig.Motion.MotionBackend == MotionInputBackendType.CemuHook;
```suggestion
                    _enableCemuHook.Active            = controllerConfig.Motion.MotionBackend == MotionInputBackendType.CemuHook;
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +
Remove extra empty line

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
>                  catch (JsonException)
```suggestion
                catch (JsonException) { }
```

2021-04-11 19:41 UTC, AcK77 commented on Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs
> +    [Obsolete]
I'm not sure about the usage of this flag, as you can see in your PR, github print some warning about it, which is a bit annoying for review. (Even if I'm agree with what's planned)

2021-04-11 20:49 UTC, Shahil-Ayato commented on Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs
> +                // NOTE: We scan all properties ignoring the depth entirely in purpose.
Shouldn’t this be `on purpose`?

2021-04-12 11:20 UTC, emmauss commented on Ryujinx.Input/Assigner/ButtonAssigner.cs
> +    public interface ButtonAssigner
Shouldn't this use standard naming conventions for Interfaces? With an initial `I`

2021-04-12 11:35 UTC, emmauss requested changes
Did a quick review. Looks good,other than a couple small issues.

2021-04-12 11:35 UTC, emmauss commented on Ryujinx.Input/Assigner/GamepadButtonAssigner.cs
> +            // return Mouse.GetState().IsAnyButtonDown || Keyboard.GetState().IsAnyKeyDown;
This should probably be remove if not being used.

2021-04-12 11:35 UTC, emmauss commented on Ryujinx.Input/Assigner/GamepadButtonAssigner.cs
> +
Rogue white space

2021-04-12 16:10 UTC, albfan commented
Just tested this about  input (one pair of combined joycons, one joycon left and one joycon right) and comparing with gamepad tool there're some controllers missing (joycon left): Both GUI based on sdl2 has several false positives (I suppose two are for joycons involved on combined joycon)

![bad-detection](https://user-images.githubusercontent.com/220968/114425711-a4bc7000-9bb9-11eb-9084-54cc4aabe4ce.jpg)

I just build a CLI about sdl2 and game controllers, check that controllers are mapped on GameControllers db 

https://github.com/gabomdq/SDL_GameControllerDB

and this is the output from sdl2-jstest:

https://gitlab.com/sdl-jstest/sdl-jstest

```
$ ./sdl2-jstest -l
Found 7 joystick(s)

Joystick Name:     'Nintendo Switch Right Joy-Con'
Joystick GUID:     050000007e0500000720000001800000
Joystick Number:    0
Number of Axes:     2
Number of Buttons: 11
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Right Joy-Con'
  Mapping: '050000007e0500000720000001800000,Nintendo Switch Right Joy-Con,a:b1,b:b2,x:b0,y:b3,back:b9,start:b8,leftstick:b10,leftshoulder:b4,rightshoulder:b6,leftx:a1~,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Right Joy-Con IMU'
Joystick GUID:     050000007e0500000720000001800000
Joystick Number:    1
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Right Joy-Con'
  Mapping: '050000007e0500000720000001800000,Nintendo Switch Right Joy-Con,a:b1,b:b2,x:b0,y:b3,back:b9,start:b8,leftstick:b10,leftshoulder:b4,rightshoulder:b6,leftx:a1~,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Right Joy-Con IMU'
Joystick GUID:     050000007e0500000720000001800000
Joystick Number:    2
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Right Joy-Con'
  Mapping: '050000007e0500000720000001800000,Nintendo Switch Right Joy-Con,a:b1,b:b2,x:b0,y:b3,back:b9,start:b8,leftstick:b10,leftshoulder:b4,rightshoulder:b6,leftx:a1~,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Left Joy-Con IMU'
Joystick GUID:     050000007e0500000620000001800000
Joystick Number:    3
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Left Joy-Con'
  Mapping: '050000007e0500000620000001800000,Nintendo Switch Left Joy-Con,a:b9,b:b8,x:b7,y:b10,back:b5,start:b0,leftstick:b6,leftshoulder:b2,rightshoulder:b4,leftx:a1,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Left Joy-Con'
Joystick GUID:     050000007e0500000620000001800000
Joystick Number:    4
Number of Axes:     2
Number of Buttons: 11
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Left Joy-Con'
  Mapping: '050000007e0500000620000001800000,Nintendo Switch Left Joy-Con,a:b9,b:b8,x:b7,y:b10,back:b5,start:b0,leftstick:b6,leftshoulder:b2,rightshoulder:b4,leftx:a1,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Left Joy-Con IMU'
Joystick GUID:     050000007e0500000620000001800000
Joystick Number:    5
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Switch Left Joy-Con'
  Mapping: '050000007e0500000620000001800000,Nintendo Switch Left Joy-Con,a:b9,b:b8,x:b7,y:b10,back:b5,start:b0,leftstick:b6,leftshoulder:b2,rightshoulder:b4,leftx:a1,lefty:a0~,platform:Linux,'

Joystick Name:     'Nintendo Switch Combined Joy-Cons'
Joystick GUID:     060000007e0500000820000000000000
Joystick Number:    6
Number of Axes:     4
Number of Buttons: 22
Number of Hats:     0
Number of Balls:    0
GameControllerConfig:
  Name:    'Nintendo Combined Joy-Cons (joycond)'
  Mapping: '060000007e0500000820000000000000,Nintendo Combined Joy-Cons (joycond),a:b0,b:b1,back:b9,dpdown:b15,dpleft:b16,dpright:b17,dpup:b14,guide:b11,leftshoulder:b5,leftstick:b12,lefttrigger:b7,leftx:a0,lefty:a1,rightshoulder:b6,rightstick:b13,righttrigger:b8,rightx:a2,righty:a3,start:b10,x:b3,y:b2,platform:Linux,'
```

So filtering IMU (as we know that is not a needed controller and has only axis but no buttons) (not sure if there's other way to filter IMU joysticks) and updating game db controller I think this should be solved.

Didn't check exactly what's the sdl version we are using in this PR, will dig about sdl2 and gamecontroller db

2021-04-12 16:42 UTC, albfan commented
All joycons are recognized after put a recent game controller db on same path as Ryujinx executable:

![IMG_20210412_182301 (1)](https://user-images.githubusercontent.com/220968/114428532-9b80d280-9bbc-11eb-94dc-f4862a5764af.jpg)

[SDL_GameControllerDB.txt](https://github.com/Ryujinx/Ryujinx/files/6298284/SDL_GameControllerDB.txt)

But mapping is not done automatically, are we planning to map controller using game controller db?

So as controllers are recognized by GUID and this is the same for IMU and controller, filter of IMU needs to be done on Ryujinx, what do you think? I can discuss on sdl2 itself too, but probably that will involve changes on API and wrapper ppy.SDL2-CS

NOTE: is it possible to rework paths for this kind of config files to `Environment.SpecialFolder.ApplicationData` that will ease progress on #https://github.com/Ryujinx/Ryujinx/issues/1077 too

NOTE2: I will work on showing pressed buttons on Input dialog to help to see if map is correct, is that ok?

2021-04-12 23:21 UTC, gdkchan reviewed
Very nice, just need to get rid of GTK now.
I will do some testing shortly.

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +            if (value <= -short.MaxValue)
Shouldn't this be checking if `value >= short.MaxValue` aswell?

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadManager.cs
> +        // TODO: move that in the input manager maybe?
```suggestion
        // TODO: Move that in the input manager maybe?
```

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadManager.cs
> +        // TODO: move that in the input manager maybe?
```suggestion
        // TODO: Move that in the input manager maybe?
```

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadManager.cs
> +                // TODO: move that in the input manager maybe?
```suggestion
                // TODO: Move that in the input manager maybe?
```

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/IGamepad.cs
> +        /// <remarks><see cref="MotionInputId.Accelerometer"/> values are in m/s^2</remarks>
I think this information should be on `MotionInputId`. Its a bit odd to put it on the function instead.

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/IGamepad.cs
> +        /// <param name="configuration"></param>
Missing.

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/IGamepad.cs
> +
Double empty line.

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/IGamepad.cs
> +        public static GamepadStateSnapshot GetStateSnapshot(IGamepad gamepad)
Same comment about `public static`.

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/IGamepadDriver.cs
> +        public string DriverName { get; }
`public` is redundant on interfaces (more below).

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx.Input/IKeyboard.cs
> +        public static KeyboardStateSnapshot GetStateSnapshot(IKeyboard keyboard)
`public static`.

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +            OpenTK.Mathematics.Vector2 stick = new OpenTK.Mathematics.Vector2(stickX, stickY);
Any reason for not using `System.Numerics.Vector2` here?

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +            throw new NotImplementedException();
If this is not supposed to be implemented, ever, then it should throw `NotSupportedException`.

2021-04-12 23:21 UTC, gdkchan commented on Ryujinx/Ui/GLRenderer.cs
> +
Double empty line.

2021-04-13 06:57 UTC, albfan commented
will remove al lthis as it is out of scope for this

2021-04-13 17:39 UTC, Thog commented on Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceDriver.cs
> +    [Obsolete]
ok

2021-04-13 17:41 UTC, Thog commented on Ryujinx.Input/Assigner/GamepadButtonAssigner.cs
> +            // return Mouse.GetState().IsAnyButtonDown || Keyboard.GetState().IsAnyKeyDown;
Missed to clean up

2021-04-13 17:44 UTC, Thog commented on Ryujinx.Common/Configuration/ConfigurationFileFormat.cs
> +        /// TODO: Remove this when those older versions aren't in use anymore.
The configuration parsing isn't actually the issue but more the way we interact with it (aka using Includes expecting it to not be null currently on master)

2021-04-13 17:50 UTC, Thog commented on Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs
> +    public class JoyconConfigControllerStick<Button, Stick> where Button: unmanaged where Stick: unmanaged
The reason I made it that way is to allow different drivers configuration if we want to change it (aka something that doesn't map with the current system)

Tho maybe I can just simplify the whole thing for now I guess?

2021-04-13 17:51 UTC, gdkchan commented on Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs
> +    public class JoyconConfigControllerStick<Button, Stick> where Button: unmanaged where Stick: unmanaged
I actually planned to delete this comment but forgot. I think I found a valid reason for it after reading the rest of the code.

2021-04-13 17:51 UTC, Thog commented on Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs
> +                    throw new JsonException($"Unknown backend type {motionBackendType}");
Not quite sure what error we should throw here tbh

2021-04-13 17:53 UTC, Thog commented on Ryujinx.Common/Configuration/Hid/LeftJoyconCommonConfig.cs
> +    public class LeftJoyconCommonConfig<Button, Stick>
leftover I missed oops

2021-04-13 17:54 UTC, gdkchan commented on Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs
> +    public class JoyconConfigControllerStick<Button, Stick> where Button: unmanaged where Stick: unmanaged
On another note, by convention generic type parameters are usually prefixed with `T`.

2021-04-13 17:59 UTC, Thog commented on Ryujinx.Graphics.OpenGL/IOpenGLContext.cs
> +        public static bool HasContext()
Yeah the public isn't actually useful here but the static is still needed.
For Mac support we will need to readd something here yeah

2021-04-13 18:00 UTC, Thog commented on Ryujinx.Input.SDL2/SDL2Driver.cs
> +            // Change this... maybe
Mostly needed to choose the polling rate but missed to remove this comment (yet again..)

2021-04-13 18:18 UTC, Thog commented on Ryujinx.Input.SDL2/SDL2GamepadDriver.cs
> +                SDL2Driver.Instance.Dispose();
I actually refcount in SDL2Driver

2021-04-13 18:24 UTC, Thog commented on Ryujinx.Input/Assigner/GamepadButtonAssigner.cs
> +                List<GamepadButtonInputId> pressedButtons = new List<GamepadButtonInputId>();
nice one, will change 👍

2021-04-13 18:25 UTC, Thog commented on Ryujinx.Input/Assigner/GamepadButtonAssigner.cs
> +                TextWriter writer = new StringWriter();
Code from before that I just moved and used

2021-04-13 19:00 UTC, Thog commented on Ryujinx.Input/HLE/NpadController.cs
> +            if (value <= -short.MaxValue)
Code I moved again will fix

2021-04-13 19:17 UTC, Thog commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +            OpenTK.Mathematics.Vector2 stick = new OpenTK.Mathematics.Vector2(stickX, stickY);
only to keep the normalize logic that is below

2021-04-13 19:26 UTC, Thog commented on Ryujinx.Common/Configuration/Hid/Controller/JoyconConfigControllerStick.cs
> +    public class JoyconConfigControllerStick<Button, Stick> where Button: unmanaged where Stick: unmanaged
Yeah I know but wanted to make it way more explicit because I have multiple argument (so you directly see what it refer to)

2021-04-13 19:47 UTC, Thog commented on Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                ushort lowFrequencyRaw = (ushort)(lowFrequency * ushort.MaxValue);
Code I moved again will fix in another PR

2021-04-13 20:16 UTC, Thog commented
Rebased and ready for reviews again

2021-04-13 23:14 UTC, AcK77 approved these changes

2021-04-13 23:57 UTC, gdkchan commented
Tested with an Ipega bluetooth controller, which is the most unusual controller that I have here. Here's the issues I found:
- Button B and Right should are not recognized (they are recorgnized on master and by windows controller test utility).
- The button names on the UI do not match the ones on the controller (it shows Start as RightShoulder for example), not a big issue.
- Button presses are only registered after I release the button on the mapper which is a bit weird, however they work fine ingame.

2021-04-14 01:19 UTC, gdkchan approved these changes
lgtm, the problems with the controller are due to the SDL2 mappings, and its not like anyone will use this funky controller anyway.

2021-04-14 08:49 UTC, emmauss approved these changes

2021-04-14 10:28 UTC, merged