Added missing VCVT instruction variant between floating point and fixed point values
Ryujinx/Ryujinx pull request #2242
Opened 2021-04-24 11:07 UTC by piyachetk

This fixes #1344 although the game still crashes later due to missing another 32-bit instruction but now it can go a little farther.

2021-04-30 07:41 UTC, Thog requested changes
Would be nice to have some unit tests for this

2021-05-02 09:59 UTC, piyachetk commented
I've added some unit tests for both instructions. VQMOVN/VQMOVUN seems to be doing fine. VCVT seems to have some problems with rounding (not sure why).

2021-05-28 12:13 UTC, piyachetk commented
I've added the VPADDL and VPADAL instructions along with their test units.

2021-05-29 19:07 UTC, CeruleanSky commented
No More Heroes [(Ryujinx-Games-List #2809)](https://github.com/Ryujinx/Ryujinx-Games-List/issues/2809) requires UHADD8 and now boots to the point where it says Marvelous before crashing due to what looks like memory access errors.

2021-05-31 00:33 UTC, CeruleanSky commented on ARMeilleure/Instructions/InstEmitAlu32.cs
> +            Operand m4 = context.BitwiseAnd(context.ShiftRightUI(m, Const(24)), Const(0xff));
Operand m4 = context.ShiftRightUI(m, Const(24));

BitWiseAnd on an i32 shifted 24 bits right seems redundant and produces additional IR. 

As a side note, an alternative implementation that might be worth looking at:
https://github.com/MerryMage/dynarmic/blob/5f96ca00b109d99c2ea1d4d141b3e3948edefbea/src/dynarmic/backend/x64/emit_x64_packed.cpp#L266

2021-05-31 00:33 UTC, CeruleanSky commented on ARMeilleure/Instructions/InstEmitAlu32.cs
> +            Operand n4 = context.BitwiseAnd(context.ShiftRightUI(n, Const(24)), Const(0xff));
Operand n4 = context.ShiftRightUI(n, Const(24));
Same as above

2021-05-31 05:51 UTC, piyachetk commented on ARMeilleure/Instructions/InstEmitAlu32.cs
> +            Operand m4 = context.BitwiseAnd(context.ShiftRightUI(m, Const(24)), Const(0xff));
I've simplified my implementation of UHADD8. Reduced a lot of IRs.

2021-06-03 00:26 UTC, EmulationFanatic commented
The incorrect audio in LIMBO leads me to believe there is a problem with the implementation. In past CPU instruction PRs, it was an indicator that there was something wrong; in the case of [this PR submitted by @saldabain](https://github.com/Ryujinx/Ryujinx/pull/1776), the author had to make adjustments in order to correct bad audio in a handful of games that had their missing opcodes fulfilled. If you are on the Ryujinx Discord server you can take a look at the change below.

https://discord.com/channels/410208534861447168/410432399500115968/784151448728240129

2021-06-03 07:16 UTC, piyachetk commented
AFAIK, Limbo only uses VCVT and VQMOVN instructions. Both of my implementations pass the unit tests just fine. I also thought about FPSCR rounding mode and cumulative saturation bit but this VCVT variant does not use the default rounding mode from FPSCR and my VQMOVN implementation uses existing fallback methods which are also used in USAT instructions which do set the cumulative saturation bit (and they all pass the tests). My unit tests can be wrong though but I don't think it is.

2021-06-26 17:53 UTC, gdkchan reviewed
Sorry for the delay, those instruction implementations are more complicated to review as we need to compare the implementation against the reference on the manual to ensure they are correct. Anyway I did a first pass pointing mostly code style issues, will check  the actual implementation later, but if tests passes, they should be fine.

2021-06-26 17:53 UTC, gdkchan commented on ARMeilleure/Decoders/OpCode32SimdRegAddLong.cs
> +
nit: Remove blank line.

2021-06-26 17:53 UTC, gdkchan commented on ARMeilleure/Decoders/OpCode32SimdRegMultLong.cs
> +
nit: Remove blank line.

2021-06-26 17:53 UTC, gdkchan commented on ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs
> +            EmitVectorBinaryOpI32(context, (op1, op2) => {
`{` should be on new line for consistency.

2021-06-26 17:53 UTC, gdkchan commented on ARMeilleure/Instructions/InstEmitSimdArithmetic32.cs
> +            EmitVectorBinaryOpI32(context, (op1, op2) => {
`{` should be on new line for consistency.

2021-06-26 17:53 UTC, gdkchan commented on ARMeilleure/Instructions/InstEmitSimdCvt32.cs
> +        //VCVT: convert vector elements (32-bit) between floating-point and fixed point
Comments should have a space after `//`, like `// VCVT` etc. More cases below.

2021-06-26 17:53 UTC, gdkchan commented on ARMeilleure/Instructions/SoftFloat.cs
> +        public static int FPToSFixed(float value, int fbits)
Those methods should also be in `SoftFallback` imo. Right now `SoftFloat`  has implementations that match very closely what is on the manual, and are pretty accurate. I don't think this is the case for those helper functions. Btw, from what I recall the Arm64 fixed-point conversion instructions does this inline, why not do the same for Arm32?

2021-06-28 12:30 UTC, riperiperi reviewed
I've had these comments sitting for a while. I haven't had the time to fully go through everything, but I might as well post them.

2021-06-28 17:47 UTC, piyachetk commented on Ryujinx.Tests/Cpu/CpuTestSimdCvt32.cs
> +            uint opcode = 0xF3800F50u; // VCVT.U32.F32 D0, D0, #0
I've changed the opcode for both tests with U and Q flags set to 0.

2021-06-28 18:00 UTC, piyachetk commented on ARMeilleure/Instructions/SoftFloat.cs
> +        public static int FPToSFixed(float value, int fbits)
I've made the conversion inline and removed those methods in SoftFallback since they aren't used anymore. I tried to imitate UCVTF's implementation (I've just realized we already have fixed point conversion implementation in Arm64). Anyways, it passes the tests now.

2021-06-28 18:01 UTC, piyachetk commented on Ryujinx.Tests/Cpu/CpuTestSimdCvt32.cs
> +        public void Vcvt_V2_F32_I32([Values(0u, 2u, 4u, 8u)] uint vd,
OK.

2021-06-29 22:45 UTC, riperiperi commented
Did the issues fixed in your recent commits appear in the tests, or in any of the affected games? I don't have any of them personally.

2021-06-30 01:46 UTC, piyachetk commented
I've only personally tested two games. Limbo still has audio issues and Planescape crashes due to missing another instruction. The Star Wars game was tested by a friend of mine so I don't know how the latest commit is doing in that game.

2021-08-31 16:21 UTC, CeruleanSky commented
I'm hoping this pull request wasn't forgotten and is still being considered for review as at least on the issue tracker it hasn't really had activity for a couple months.  If the issue is instruction review takes a while, perhaps it could be split and some of the instructions(UHADD8 maybe as No More Heroes 1&2 use it) be put into new pull requests as the instructions are needed for several games, and it would be nice to use master so others can easily check if some games go further or are still crashing in regards to their other aspects.

2021-08-31 16:32 UTC, piyachetk commented
I'm okay with that idea. Which instruction should be split into its own PR? Is it only UHADD8?

2024-01-14 12:22 UTC, ScottNash042 commented
needs a rebase

2024-01-27 01:30 UTC, AcK77 commented
Latest missing instructions are ported in #6185, this can be closed.

2024-01-27 01:30 UTC, closed without merging