nsd: Cleanup the service and implement some calls
Ryujinx/Ryujinx pull request #2250
Opened 2021-04-28 02:34 UTC by AcK77

This PR cleanup the `nsd` service a bit and implement / stub some calls (checked with RE):

- Added placeholders for lastest firmware calls,
- `GetSettingName` is removed because of a bad previous implementation (doesn't seems to be used by any games so there is no regression).
- `SetChangeEnvironmentIdentifierDisabled`, `WriteSaveDataToFsForTest`,`DeleteSaveDataOfFsForTest`, and `IsChangeEnvironmentIdentifierDisabled` are stubbed.
- `GetApplicationServerEnvironmentType` is implemented (closes #2247).

Now PGA TOUR 2K21 goes in-game (then deadlock):
![Capture](https://user-images.githubusercontent.com/4905390/116337696-ced97900-a7da-11eb-9f19-aa2fefd48cba.PNG)

2021-04-30 07:40 UTC, Thog requested changes

2021-04-30 07:40 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs
> +            throw new ServiceNotImplementedException(this, context, false);
Any reasons of removing the implementation here?

2021-04-30 07:40 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs
> +            byte environmentType = identifier.Substring(0, 2) switch
an enum ``ApplicationServerEnvironmentType`` would be better here.

2021-05-02 00:02 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Sockets/Nsd/IManager.cs
> +            throw new ServiceNotImplementedException(this, context, false);
The current implementation is totally wrong and any games seems to currently uses it, so it's better to remove it.

2021-05-02 00:15 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Sockets/Nsd/Manager/FqdnResolver.cs
> +            if (address != "api.sect.srv.nintendo.net"     ||
This check seems incorrect. `x != y || x != z` will always be true, regardless of the value in "x" because the value in "x" will always be either different from "y" or different from "z", since it can't be equal to both.

2021-05-02 10:20 UTC, Thog approved these changes

2021-05-05 02:32 UTC, gdkchan approved these changes
lgtm, thanks.

2021-05-05 21:16 UTC, merged