gtk3: Add base for future Vulkan integration
Ryujinx/Ryujinx pull request #2260
Opened 2021-05-01 17:50 UTC by Thog

This PR puts in place the foundation for the future Vulkan integration on the GTK3 UI.
It should be noted that I changed how the GTK3 widget is initialized to allow the Vulkan side to grab the window handle associated to the widget.

This also updated SPB to 0.0.3-build14 that fixed a use after free on XErrorHandler on Linux.

2021-05-01 17:56 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.cs
> +        private IRendererWidget CreatRenderereWidget()
`Renderer`

2021-05-01 17:56 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.cs
> +            Widget rendererWidget = ((Widget)RendererWidget);
Remove outer brackets.

2021-05-01 17:56 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.cs
> +            rendererWidget.Dispose();
Doing this twice?

2021-05-01 17:56 UTC, riperiperi commented on Ryujinx/Ui/VKRenderer.cs
> +
Double newline?

2021-05-01 17:56 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.cs
> +        private IRendererWidget CreatRenderereWidget()
Ok, the whole thing:
`CreateRendererWidget`

2021-05-01 17:57 UTC, Thog commented on Ryujinx/Ui/MainWindow.cs
> +            rendererWidget.Dispose();
Nice catch, it is supposed to dispose window and then the widget

2021-05-01 18:00 UTC, Shahil-Ayato commented on Ryujinx/Ui/GLWidget.cs
> +        public SwapableNativeWindowBase NativeWindow { get; private set; }
Just a typo here `Swapable` should be `Swappable`

2021-05-01 18:01 UTC, Thog commented on Ryujinx/Ui/GLWidget.cs
> +        public SwapableNativeWindowBase NativeWindow { get; private set; }
typo in the dep urgh, will fix in another release

2021-05-01 18:40 UTC, Shahil-Ayato commented on Ryujinx/Ui/MainWindow.cs
> +                RendererWidget = CreatRendererWidget();
Typo here, Should be `Create` instead of `Creat`

2021-05-01 19:36 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.cs
> +        private RendererWidgetBase CreatRendererWidget()
`CreateRendererWidget`

2021-05-02 20:36 UTC, riperiperi approved these changes
Very nice!

2021-05-02 20:53 UTC, AcK77 approved these changes
Just some nits, instead of that it lgtm!

2021-05-02 20:53 UTC, AcK77 commented on Ryujinx/Ui/GLRenderer.cs
Extra empty line

2021-05-02 20:53 UTC, AcK77 commented on Ryujinx/Ui/VKRenderer.cs
> +        public VKRenderer(InputManager inputManager, GraphicsDebugLevel glLogLevel) : base(inputManager, glLogLevel) {}
```suggestion
        public VKRenderer(InputManager inputManager, GraphicsDebugLevel glLogLevel) : base(inputManager, glLogLevel) { }
```

2021-05-02 20:53 UTC, AcK77 commented on Ryujinx/Ui/VKRenderer.cs
> +        public override void InitializeRenderer() {}
```suggestion
        public override void InitializeRenderer() { }
```

2021-05-02 20:53 UTC, AcK77 commented on Ryujinx/Ui/VKRenderer.cs
> +        public override void SwapBuffers() {}
```suggestion
        public override void SwapBuffers() { }
```

2021-05-02 21:59 UTC, gdkchan approved these changes
lgtm other than the few comments.

2021-05-02 21:59 UTC, gdkchan commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        $"GPU:  {_gpuVendorName}"));
Why is that aligned? It will have double space.

2021-05-02 21:59 UTC, gdkchan commented on Ryujinx/Ui/RendererWidgetBase.cs
> +
Double empty line.

2021-05-02 21:59 UTC, gdkchan commented on Ryujinx/Ui/RendererWidgetBase.cs
> +            //Touchscreen
```suggestion
            // Touchscreen
```

2021-05-02 22:27 UTC, Shahil-Ayato approved these changes
LGTM

2021-05-03 17:27 UTC, emmauss requested changes
I don't think having the vulkan switch/check is necessary now, as it will always be false.

2021-05-03 17:27 UTC, emmauss commented on Ryujinx/Ui/MainWindow.cs
> +        private static bool UseVulkan = false;
I don't think this is necessary now. When vulkan come in, it will be replaces by a config value. As it is now, it's not being modified in any way.

2021-05-03 17:27 UTC, emmauss commented on Ryujinx/Ui/MainWindow.cs
> +            if (UseVulkan)
same as above review

2021-05-03 17:27 UTC, emmauss commented on Ryujinx/Ui/MainWindow.cs
> +            if (UseVulkan)
same. this scope is unreachable currently

2021-05-04 09:14 UTC, emmauss approved these changes

2021-05-04 16:19 UTC, merged