Hide Console (Rebase of #2082)
Ryujinx/Ryujinx pull request #2265
Opened 2021-05-03 01:59 UTC by Shahil-Ayato

This is a rebase of both #2082 and #1866.
The original author of all the code is https://github.com/macabeus
This fixes all the issues the previous PR's had and it fully works on Windows and no longer breaks Linux

![Screenshot 2021-05-03 015535](https://user-images.githubusercontent.com/67567036/116835594-06984600-ab78-11eb-8a7a-e3ca1ebe9a6c.png)

Special thanks to @Pixelylon and @pineappleEA for helping me fix all of the issues with the previous PR's

2021-05-03 02:10 UTC, AcK77 requested changes

2021-05-03 02:10 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +
Remove extra empty line

2021-05-03 02:10 UTC, AcK77 commented on Ryujinx.Common/Configuration/ConfigurationState.cs
> +                configurationFileFormat.ShowConsole = false;
Maybe the console should be shown as default as you set it to true in LoadDefault()

2021-05-03 02:10 UTC, AcK77 commented on Ryujinx.Common/System/ConsoleHelper.cs
> +            else
You can concat the else and the if below

2021-05-03 02:10 UTC, AcK77 commented on Ryujinx/Program.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
This check should be done in the ConsoleHelper class

2021-05-03 02:10 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
This check should be done in the ConsoleHelper class

2021-05-03 10:02 UTC, Shahil-Ayato commented
Will do the rest tomorrow

2021-05-03 17:19 UTC, Leischii commented
I'm not sure if this should be merged anytime soon. There are still situations where the emulator freezes and the only way to close it is my closing the console window (or via task manager, but that isn't a good solution imo). Trying to close the emulator window doesn't work in these situations, so until this is fixed, I don't think removing the console is that good. Feel free to disagree.

2021-05-30 22:13 UTC, Mou-Ikkai commented
> I'm not sure if this should be merged anytime soon. There are still situations where the emulator freezes and the only way to close it is my closing the console window (or via task manager, but that isn't a good solution imo). Trying to close the emulator window doesn't work in these situations, so until this is fixed, I don't think removing the console is that good. Feel free to disagree.

That's why it's a toggleable option.

2021-07-05 01:28 UTC, Zeswen commented
> I'm not sure if this should be merged anytime soon. There are still situations where the emulator freezes and the only way to close it is my closing the console window (or via task manager, but that isn't a good solution imo). Trying to close the emulator window doesn't work in these situations, so until this is fixed, I don't think removing the console is that good. Feel free to disagree.

First of all thank you very much for your efforts and the amazing project @Shahil-Ayato :)

I don't think the window freezing is a real issue here, since Windows handles it via the not responding alert, which access Task Manager internally.

Besides, there is a lot of issues with [Remote Play support](https://www.reddit.com/r/Cuphead/comments/dqobm3) due to the console window instantiation, this feature could really help address it (didn't check the PR yet, will do tomorrow). 

Also, as @Mou-Ikkai mentioned, this is a togglable option enabled by default, so there is not really a huge problem here.    

Please reconsider merging this PR, thanks! :)

2021-07-16 23:34 UTC, defunky commented
Any plans on fixing conflicts?

2021-07-16 23:37 UTC, Shahil-Ayato commented
> Any plans on fixing conflicts?

I can fix the simple conflicts like config.json and program.cs but j need to talk with the devs on The other two as every time I try to rebase I get errors while building this. I hope to manage to fix this soon.

2021-10-16 09:51 UTC, Shahil-Ayato commented
Rebased and ready for review! Apologies for how long this took. 
Thank you to @Sazpaimon for helping me out with the rebase!
P.S Sorry @emmauss I hope this isn't difficult to port to Avalonia.

2021-10-19 19:51 UTC, MutantAura commented
Working great on my end. 
I'm unsure what should be default honestly. Perhaps at a later date it may be beneficial to change it to auto-hide. I don't know of any other emulator that has their console out by default but this may be a change once the emulator is more mature.

2022-03-03 20:22 UTC, Shahil-Ayato commented
Superseded by #3170.

2022-03-03 20:22 UTC, closed without merging