Reduce technical debt
Ryujinx/Ryujinx pull request #2289
Opened 2021-05-16 11:40 UTC by marodev

Hello, 

Everyone likes a nice and clean codebase. This pull request is _very simple_ and aims to reduce the technical debt. It specifically targets the following rules:

ReSharper:
- "Merge sequential checks in && or || expressions﻿" [rule](https://www.jetbrains.com/help/resharper/MergeSequentialChecks.html)
- "Convert 'as' expression type check and the following null check into pattern matching﻿" [rule](https://www.jetbrains.com/help/resharper/UsePatternMatching.html)
- "Replace if statement with null-propagating code" [rule](https://www.jetbrains.com/help/resharper/UseNullPropagation.html)

SonarQube:
- "Null checks should not be used with 'is'" [rule](https://rules.sonarsource.com/csharp/RSPEC-4201)
- "'IEnumerable' LINQs should be simplified" [rule](https://rules.sonarsource.com/csharp/RSPEC-2971)
- "Duplicate casts should not be made" [rule](https://rules.sonarsource.com/csharp/RSPEC-3247)

2021-05-16 12:01 UTC, Cristallix reviewed
I like your modifications. I also mentioned my personal preferences about the null check with boolean. Ley me know what you think about this.

2021-05-16 12:48 UTC, marodev commented
> I like your modifications. I also mentioned my personal preferences about the null check with boolean. Ley me know what you think about this.

Hi @Cristallix, 

Thanks a lot, I appreciate your feedback!

Your suggestion to go even further and make it shorter, i.e. from

`if (_client?.Client != null && _client.Client.Connected)`

to

` if (_client?.Client?.Connected ?? false)`

is interesting!

I personally use the null-coalescing operator (??) only with a 'backup' value, for example

`return iEnumerable?.Sum() ?? double.NaN`

For a boolean expression, where we have only two options (true / false) and put `false` as the backup value, it reminds me a little of the pattern `if(expression == false)` that is a common smell, particularly for beginners.

Things having said, this is only my view and I'm willing to change it if another reviewer prefers your style.

2021-05-16 14:17 UTC, Benedani commented
> For a boolean expression, where we have only two options (true / false) and put `false` as the backup value, it reminds me a little of the pattern `if(expression == false)` that is a common smell, particularly for beginners.

I think in this case, you can read it as "if `client?.Client` exists, use its `.Connected` property, otherwise fall back to `false`". It makes sense to have the fallback value, and so doesn't trigger me nearly as much as `== true` and `== false` do.

2021-05-16 14:32 UTC, marodev commented
> > For a boolean expression, where we have only two options (true / false) and put `false` as the backup value, it reminds me a little of the pattern `if(expression == false)` that is a common smell, particularly for beginners.
> 
> I think in this case, you can read it as "if `client?.Client` exists, use its `.Connected` property, otherwise fall back to `false`". It makes sense to have the fallback value, and so doesn't trigger me nearly as much as `== true` and `== false` do.

Thanks for the explanation! I updated it accordingly.

2021-05-16 23:11 UTC, jduncanator commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client != null && _client.Client.Connected)
I disagree with this change, it just serves to obfuscate the actual purpose of the check. I'm all for shorter code, but the purpose of shorter code is to make it more readable, not less.

2021-05-16 23:13 UTC, gdkchan commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client != null && _client.Client.Connected)
Yea, it just makes the code more confusing imo.

2021-05-16 23:15 UTC, gdkchan commented on Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/ArrayType.cs
> +            else _dimensionExpression?.Print(writer);
Missing `{` `}`.

2021-05-16 23:17 UTC, jduncanator requested changes
Some initial thoughts. The tough thing with changes like these is that they're largely driven by personal preference and internal bias. I'd prefer to lean closer towards what we had before, as that's what we all seem to be comfortable with, rather than towards something radically different.

2021-05-16 23:17 UTC, jduncanator commented on ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs
> +            while (node is not PhiNode)
This has poorer code-gen on .NET 5.0. I'm not sure about .NET 6.0, but there is a legitimate reason to do the null check separately.

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIO.cs
> +            return other is SoundIO d && this.handle == d.handle;
All of the code in the `Native` folder from SoundIo is auto-generated. There is no point in modifying this, as if we update the SoundIO library, this code will be re-generated, and the changes lost.

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIODevice.cs
> +            return other is SoundIODevice d && (this.handle == d.handle || Natives.soundio_device_equal (this.handle, d.handle));
ditto

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIOInStream.cs
> +            return other is SoundIOInStream d && (this.handle == d.handle);
ditto

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIOOutStream.cs
> +            return other is SoundIOOutStream d && (this.handle == d.handle);
ditto

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Graphics.OpenGL/Pipeline.cs
> +            _unit0Texture?.Bind(0);
I'm a little skeptical on these two changes in this file. They're _probably_ fine, but they do make the code harder to understand from a quick glance.

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/EncodedFunction.cs
> +            _attrs?.Print(writer);
If we keep these changes as is, they can have the blank lines between them removed.

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client?.Connected ?? false)
This line is much harder to parse and understand than what we had before. The goal of "simplifying" and keeping lines short is to improve readability, in this case, we degrade it in my opinion.

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client?.Connected ?? false)
Ditto.

2021-05-16 23:17 UTC, jduncanator commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client?.Connected ?? false)
Ditto.

2021-05-16 23:25 UTC, Cristallix commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client != null && _client.Client.Connected)
What do you mean by "obfuscate the actual purpose of the check" ?

2021-05-16 23:26 UTC, jduncanator commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client != null && _client.Client.Connected)
It makes it hard to understand what it's doing. The previous check I can glance at and understand what it's doing without thinking, with the change, I have to sit there and think about what the code is doing to understand whether it enters the code flow statement or not

2021-05-17 06:23 UTC, marodev commented on ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs
> +            while (node is not PhiNode)
Interesting! Did you look at the generated IL code?

2021-05-17 06:24 UTC, marodev commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIO.cs
> +            return other is SoundIO d && this.handle == d.handle;
Done. Reverted to the previous state.

2021-05-17 06:25 UTC, marodev commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIODevice.cs
> +            return other is SoundIODevice d && (this.handle == d.handle || Natives.soundio_device_equal (this.handle, d.handle));
Done. Reverted to the previous state.

2021-05-17 06:25 UTC, marodev commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIOInStream.cs
> +            return other is SoundIOInStream d && (this.handle == d.handle);
Done. Reverted to the previous state.

2021-05-17 06:25 UTC, marodev commented on Ryujinx.Audio.Backends.SoundIo/Native/libsoundio/SoundIOOutStream.cs
> +            return other is SoundIOOutStream d && (this.handle == d.handle);
Done. Reverted to the previous state.

2021-05-17 06:35 UTC, marodev commented on Ryujinx.Graphics.OpenGL/Pipeline.cs
> +            _unit0Texture?.Bind(0);
Do you in general not like the null-conditional operator (?.)

2021-05-17 06:35 UTC, marodev commented on Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/ArrayType.cs
> +            else _dimensionExpression?.Print(writer);
Done.

2021-05-17 06:37 UTC, marodev commented on Ryujinx.HLE/HOS/Diagnostics/Demangler/Ast/EncodedFunction.cs
> +            _attrs?.Print(writer);
Done. Blank lines have been removed.

2021-05-17 06:39 UTC, marodev commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client?.Connected ?? false)
How about

`if (_client?.Client != null && _client.Client.Connected)`

2021-05-23 21:16 UTC, AcK77 commented on ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs
> +            while (node is not PhiNode)
This seems to throw `System.NullReferenceException : Object reference not set to an instance of an object.` in the CI.

2021-05-24 06:16 UTC, marodev commented on ARMeilleure/CodeGen/RegisterAllocators/LinearScanAllocator.cs
> +            while (node is not PhiNode)
Absolutely, the refactoring is not the same. I reverted to the previous state. Thanks for pointing it out.

2021-05-29 20:37 UTC, RKennedy9064 commented on Ryujinx.Input/Motion/CemuHook/Client.cs
> +                if (_client?.Client?.Connected ?? false)
Not sure how relevant this is, but saw this PR and figured I'd offer my 2 cents. Any thoughts to using the new C# 9 syntax instead? It's a little more verbose, but I like how it can be read like a sentence and I've never been a fan of seeing `!=` everywhere. It can be applied to most of the other changes here as well, but feel free to disregard my comment if you're not a fan of the new syntax.

```csharp
if (_client is not null and _client.Client is not null and _client.Client.Connected)
```

https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9#pattern-matching-enhancements

2021-08-04 19:58 UTC, AcK77 commented
Are you still interested to works on it ?

2021-08-11 19:41 UTC, AcK77 commented
Closed due to inactivity

2021-08-11 19:41 UTC, closed without merging