frontend: Add a SDL2 headless window
Ryujinx/Ryujinx pull request #2310
Opened 2021-05-24 20:14 UTC by Thog

This is an all integrated experience that only depends on SDL2.
Every settings are configurable via commandline.

User can control input mapping via presaved profile from GTK3 or use the default preset.

It still need to be decided if we want to put sidebar information in the title bar.

![image](https://user-images.githubusercontent.com/1760003/119402355-1cafa700-bcdd-11eb-8148-d36f0a65c1f8.png)

2021-06-08 21:24 UTC, AcK77 requested changes

2021-06-08 21:24 UTC, AcK77 commented on Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs
> +
Remove extra empty line

2021-06-08 21:24 UTC, AcK77 commented on Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs
> +            public void Dispose()
Dispose are usually at the end of the class

2021-06-08 21:24 UTC, AcK77 commented on Ryujinx.Headless.SDL2/Program.cs
> +                    return null;
Add a new empty line before

2021-06-08 21:24 UTC, AcK77 commented on Ryujinx.Headless.SDL2/Program.cs
> +                return;
Add a new empty line before

2021-06-08 21:24 UTC, AcK77 commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +        public void Dispose()
Dispose are usually at the end of the class (same for the next method)

2021-07-06 17:45 UTC, AcK77 approved these changes

2021-07-06 20:08 UTC, merged

2021-10-11 18:58 UTC, albfan commented
As I'm trying to use to integrate with Kodi https://github.com/xbmc/repo-plugins/pull/3510

A signal would be great to trigger "stop emulation"

2021-10-12 10:13 UTC, albfan commented
Nvm this is merged, continues on #2131