Add TouchScreen Manager
Ryujinx/Ryujinx pull request #2333
Opened 2021-05-31 18:43 UTC by emmauss

This pr moves touchscreen updates to the Input project.

2021-06-01 07:26 UTC, Thog requested changes
One less thing to have duplicate between UIs 👍 
Just have some comments but otherwise the code lgtm, will need to test it

2021-06-01 07:26 UTC, Thog commented on Ryujinx.Input/IMouseDriver.cs
> +        public bool[] Buttons { get; }
Remove all public here, those are uneeded in an interface

2021-06-01 07:26 UTC, Thog commented on Ryujinx.Input/IMouseDriver.cs
> +        public bool[] Buttons { get; }
I kind would prefer that you do something like what was done in the ``IGamepad`` and ``IKeyboard`` interface that create a snapshot instance instead of having access directly given like that imo.

That would allow to avoid possible weird thing happening if any values change during ``TouchScreenManager`` update.

2021-06-01 07:26 UTC, Thog commented on Ryujinx/Ui/MainWindow.cs
> +            var mouseDriver = new Gtk3MouseDriver(this);
```suggestion
            Gtk3MouseDriver mouseDriver = new Gtk3MouseDriver(this);
```

2021-06-01 07:26 UTC, Thog commented on Ryujinx/Ui/MainWindow.cs
> +            var mouseDriver = new Gtk3MouseDriver(this);
Does this actually work on the render widget?
I remember having to register on it instead of the main one for keyboard...
~~Also did you checked if the touch area is the same size as the widget one in the end? I think it could be possible to have mapping issue on the main window.~~ Just saw that you grab the allocation size after 👍

2021-06-01 07:26 UTC, Thog commented on Ryujinx/Ui/RendererWidgetBase.cs
> +            TouchScreenManager?.Dispose();
Invert with ``NpadManager`` dispose (as you initalize ``TouchScreenManager`` after ``NpadManager`` in ``Initialize``.

2021-06-01 11:22 UTC, emmauss commented on Ryujinx/Ui/MainWindow.cs
> +            var mouseDriver = new Gtk3MouseDriver(this);
I does work on the render widget, but I'll switch it to the widget for consistency.

2021-06-01 15:37 UTC, emmauss commented on Ryujinx.Input/IMouseDriver.cs
> +        public bool[] Buttons { get; }
I've split it into driver and device classes

2021-06-08 21:18 UTC, AcK77 requested changes

2021-06-12 09:26 UTC, emmauss commented
reviews addressed.

2021-06-12 14:00 UTC, AcK77 approved these changes

2021-06-12 14:00 UTC, AcK77 commented on Ryujinx/Input/GTK3/GTK3Mouse.cs
> +            throw new System.NotImplementedException();
What about `using System;`?

2021-06-12 18:40 UTC, emmauss commented on Ryujinx/Input/GTK3/GTK3Mouse.cs
> +            throw new System.NotImplementedException();
done

2021-06-13 12:19 UTC, Thog approved these changes

2021-06-14 06:42 UTC, merged