Add Screenshot Feature
Ryujinx/Ryujinx pull request #2354
Opened 2021-06-09 08:29 UTC by emmauss

Adds taking screen captures of games at their internal resolution. So you can now take your 8K screenshots even if you don't have a display that high. 
It can be used from the Actions menu or with the hotkey, F9.

Fixes #2143 .

2021-06-09 23:20 UTC, AcK77 requested changes

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationState.cs
> +                ScreenShot = Key.F8
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationState.cs
> +                    ScreenShot = Key.F8
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
> +        public Key ScreenShot { get; set; }
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx.Graphics.GAL/IRenderer.cs
> +        void ScreenShot();
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx.Graphics.GAL/ScreenCaptureImageInfo.cs
> +        public int Width { get; }
If you align assignment above then align var names and `{ get; }` (some spaces are missing)

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Renderer.cs
> +        public void ScreenShot()
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Window.cs
> +        internal bool ScreenCaptureRequested{ get; set; }
```suggestion
        internal bool ScreenCaptureRequested { get; set; }
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Window.cs
> +            if(ScreenCaptureRequested)
```suggestion
            if (ScreenCaptureRequested)
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Window.cs
> +            GL.ReadPixels(x, y, width, height, isBgra ? PixelFormat.Bgra : PixelFormat.Rgba, PixelType.UnsignedByte, bitmap);
Add a new empty line before and after

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            if(_emulationContext!=null && RendererWidget != null)
```suggestion
            if (_emulationContext != null && RendererWidget != null)
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.glade
> +<!-- Generated with glade 3.38.2 -->
Why all those changes? Does this cause no issues?

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +        public bool ScreenshotRequested{ get; set; }
```suggestion
        public bool ScreenshotRequested { get; set; }
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +            if(Renderer != null)
```suggestion
            if (Renderer != null)
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        var currentTime  = DateTime.Now;
If you align assignments you should align var names too

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                                    : Image.LoadPixelData<Rgba32>(e.Data, e.Width, e.Height);
Maybe align the : with the ?

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        if (e.FlipY)
Add a new empty line before

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        Logger.Notice.Print(LogClass.Application, $"ScreenShot saved to {path}", "Screenshot");
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +            ScreenShot
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +            if (_keyboardInterface.IsPressed((Key)ConfigurationState.Instance.Hid.Hotkeys.Value.ScreenShot))
`ScreenShot` -> `Screenshot`

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/_schema.json
> +        "screen_shot"
```suggestion
        "screenshot"
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/_schema.json
> +        "screen_shot": {
```suggestion
        "screenshot": {
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/_schema.json
> +          "$id": "#/properties/hotkeys/properties/screen_shot",
```suggestion
          "$id": "#/properties/hotkeys/properties/screenshot",
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/_schema.json
> +          "title": "ScreenShot",
```suggestion
          "title": "Screenshot",
```

2021-06-09 23:20 UTC, AcK77 commented on Ryujinx/Config.json
> +    "screen_shot": "F8"
```suggestion
    "screenshot": "F8"
```

2021-06-10 16:25 UTC, emmauss commented on Ryujinx/Ui/MainWindow.glade
> +<!-- Generated with glade 3.38.2 -->
nope. it's metadata glade adds. it doesn't affect the ui builder.

2021-06-10 16:27 UTC, emmauss commented
Fixed the names

2021-06-10 16:59 UTC, GamerzHell9137 commented
Any more information about it? Like where the SS are being saved?

2021-06-11 10:21 UTC, GamerzHell9137 commented
For people who want to test the PR, the folder where the screenshots are being saved is Windows Picture folder.

2021-06-11 14:17 UTC, Benedani commented
While I don't have concerns about the Pictures folder on Linux (where it exists), I think the path should be made configurable in the settings.

2021-06-13 12:15 UTC, Thog requested changes
Some small issues otherwise lgtm

2021-06-13 12:15 UTC, Thog commented on Ryujinx/Config.json
> +    "screenshot": "F8"
Also need a configuration version change

2021-06-13 12:15 UTC, Thog commented on Ryujinx/_schema.json
> +
Remove empty line

2021-06-13 12:15 UTC, Thog commented on Ryujinx/_schema.json
> +          "default": "F9"
```suggestion
          "default": "F8"
```

2021-06-14 07:59 UTC, emmauss commented on Ryujinx/Config.json
> +    "screenshot": "F8"
I've already bumped the version from 26 to 27

2021-06-17 21:44 UTC, Thog approved these changes
code lgtm, haven't got much time to test if this cause any regressions in term of performances (cc @gdkchan & @EmulationFanatic)

2021-06-20 23:50 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        var    currentTime  = DateTime.Now;
```suggestion
                        var    currentTime = DateTime.Now;
```
and same for other vars

2021-06-20 23:50 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.glade
> +<!-- Generated with glade 3.38.2 -->
I mean, it's not specifically this line, it's about the whole file. (Like `can_focus` to `can-focus` as example)

2021-06-23 21:40 UTC, AcK77 approved these changes

2021-06-23 22:20 UTC, riperiperi reviewed
Nice feature! Just got one question with the changes to the glade file.

2021-06-23 22:20 UTC, riperiperi commented on Ryujinx/Ui/MainWindow.glade
> +                        <property name="tooltip_text" translatable="yes">Simulate a Wake_up Message</property>
Is this intentional? It looks like you meant to just change `-` to `_` in variable names.

2021-06-26 18:17 UTC, emmauss commented on Ryujinx/Ui/MainWindow.glade
> +                        <property name="tooltip_text" translatable="yes">Simulate a Wake_up Message</property>
No. I've reverted it.

2021-06-26 18:17 UTC, emmauss commented
rebased and ready to merge

2021-06-26 21:30 UTC, MelonSpeedruns commented
Looks good to me, WHERE'S THE MERGE???? >:(

2021-06-26 21:39 UTC, riperiperi commented on Ryujinx/Configuration/ConfigurationState.cs
> +                Common.Logging.Logger.Warning?.Print(LogClass.Application, $"Outdated configuration version {configurationFileFormat.Version}, migrating to version 27.");
Should be migrating to version 28

2021-06-26 22:09 UTC, GamerzHell9137 commented
Other than the rebasing thing everything works great. Gj!

2021-06-27 09:23 UTC, emmauss commented on Ryujinx/Configuration/ConfigurationState.cs
> +                Common.Logging.Logger.Warning?.Print(LogClass.Application, $"Outdated configuration version {configurationFileFormat.Version}, migrating to version 27.");
fixed

2021-06-28 12:28 UTC, riperiperi approved these changes

2021-06-28 20:09 UTC, merged