Unbind input on middle click
Ryujinx/Ryujinx pull request #2358
Opened 2021-06-10 17:51 UTC by ooa113y

This PR allows to "unbind" inputs in the `ControllerWindow` by middle-clicking while an input is selected.

This is my first code contribution to Ryujinx, so I apologize if the code is not compliant with some internal standard, or even if it's just outright bad for some reason that I don't understand.

2021-06-10 21:11 UTC, emmauss requested changes

2021-06-10 21:11 UTC, emmauss commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    else if (_middleMousePressed)
this can be simplified with a ternary conditional operator.

2021-06-10 21:11 UTC, emmauss commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            _middleMousePressed = false;
This is not necessary.

2021-06-10 23:29 UTC, jduncanator commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            _middleMousePressed = false;
Technically neither is `_mousePressed = false` above it. Either both should be removed, or this change left.

2021-06-11 06:29 UTC, ooa113y commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    else if (_middleMousePressed)
Sorry but this confuses me slightly.

There are two conditions here, one that checks for `pressedButton` and one that checks for `_middleMousePressed`, with different results. Should I merge them together into something like `button.Label = buttonPressed != "" ? pressedButton : _middleMousePressed ? "Unbound": button.Label`? To me personally that seems much more confusing to read, but I'll do it of course.

Or do you mean just this specific addition? In that case we end up with `button.Label = _middleMousePressed ? "Unbound" : button.Label` which is still somewhat awkward in my eyes since it repeats `button.Label` twice.

I'm not against changing this, I'm just not entirely sure *what* the change should be here 😅

2021-06-11 06:34 UTC, ooa113y commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            _middleMousePressed = false;
Removed both of these, confirmed the window functions fine without them.

2021-06-18 22:34 UTC, AcK77 requested changes

2021-06-18 22:34 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    _middleMousePressed = false;
Add a new empty line before

2021-06-18 22:34 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            if (args.Event.Button == 2)
`_middleMousePressed = args.Event.Button == 2`

2021-06-19 06:10 UTC, ooa113y commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +            if (args.Event.Button == 2)
Done.

2021-06-19 06:10 UTC, ooa113y commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    _middleMousePressed = false;
Done.

2021-06-21 00:34 UTC, AcK77 approved these changes

2021-06-23 20:43 UTC, riperiperi approved these changes
Nice one!

2021-06-23 20:51 UTC, merged