hid/irs: Stub IsFirmwareUpdateAvailableForSixAxisSensor and CheckFirmwareVersion
Ryujinx/Ryujinx pull request #2371
Opened 2021-06-16 22:51 UTC by LukeFZ

This pull request stubs nn::hid::IHidServer::IsFirmwareUpdateAvailableForSixAxisSensor and nn::irsensor::IIrSensorServer::CheckFirmwareVersion, to make games which use these commands run without the "Ignore Missing Services" setting enabled.

This is my first pull request/contribution to Ryujinx, so feedback on what I did right/wrong would be much appreciated.

2021-06-17 01:41 UTC, AcK77 requested changes

2021-06-17 01:41 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            bool updateAvailable = false;
Maybe you could use a global private var named `_isFirmwareUpdateAvailableForSixAxisSensor` here

2021-06-17 01:41 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +            PlayerIndex irCameraHandle        = (PlayerIndex)context.RequestData.ReadInt32();
This should be casted as an int

2021-06-17 01:41 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +        public ResultCode CheckFirmwareVersion(ServiceCtx context)
https://switchbrew.org/wiki/HID_services#CheckFirmwareVersion

This call take a PID as param, you should add it in the symbol and check if the order your read them is good, because usually there is a ulong placeholder to store it in the IPC call (try to look in other services to see how we did that)

2021-06-17 01:41 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +        public ResultCode IsFirmwareUpdateAvailableForSixAxisSensor(ServiceCtx context)
https://switchbrew.org/wiki/HID_services#IsFirmwareUpdateAvailableForSixAxisSensor

This call take a PID as param, you should add it in the symbol and check if the order your read them is good, because usually there is a ulong placeholder to store it in the IPC call (try to look in other services to see how we did that)

(Some other calls of this service are wrong too)

2021-06-17 13:13 UTC, LukeFZ commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +            PlayerIndex irCameraHandle        = (PlayerIndex)context.RequestData.ReadInt32();
Not quite sure what you mean here. Should I just remove the cast to PlayerIndex and just use the int itself?

2021-06-17 18:41 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +            PlayerIndex irCameraHandle        = (PlayerIndex)context.RequestData.ReadInt32();
Yes, the value cast is an `int` not a `PlayerIndex`

2021-06-17 18:55 UTC, LukeFZ commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +            PlayerIndex irCameraHandle        = (PlayerIndex)context.RequestData.ReadInt32();
Okay, thanks!

2021-06-17 21:41 UTC, Thog requested changes
Mostly lgtm, only need some tiny fixes 👍

2021-06-17 21:41 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            _isFirmwareUpdateAvailableForSixAxisSensor = false;
Degroup from previous assignation or align with them

```suggestion

            _isFirmwareUpdateAvailableForSixAxisSensor = false;
```

2021-06-17 21:41 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +        public ResultCode IsFirmwareUpdateAvailableForSixAxisSensor(ServiceCtx context)
It is not necessarily present and looking at the layout I didn't found anything for it but yeah always something to be aware of ^^

2021-06-17 21:41 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +        // IsFirmwareUpdateAvailableForSixAxisSensor(nn::hid::SixAxisSensorHandle, nn::hid::AppletResourceUserId, pid) -> bool UpdateAvailable
Inverted parameters in definition
```suggestion
        // IsFirmwareUpdateAvailableForSixAxisSensor(nn::hid::AppletResourceUserId, nn::hid::SixAxisSensorHandle, pid) -> bool UpdateAvailable
```

2021-06-17 21:41 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            int  sixAxisSensorHandle  = context.RequestData.ReadInt32();
you need to skip 4 bytes because of padding
```suggestion
            int  sixAxisSensorHandle  = context.RequestData.ReadInt32();
            context.RequestData.BaseStream.Position += 4;
```

2021-06-17 21:41 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +        public ResultCode CheckFirmwareVersion(ServiceCtx context)
It is not necessarily present and looking at the layout I didn't found anything for it but yeah always something to be aware of ^^

2021-06-17 21:46 UTC, LukeFZ commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            int  sixAxisSensorHandle  = context.RequestData.ReadInt32();
Thanks for confirming my suspicion! I noticed in testing that padding was probably necessary to get accurate numbers, but since all other calls dont have this padding I decided against adding it. Should I apply this padding to the other commands which don't currently have it?

2021-06-17 21:54 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            int  sixAxisSensorHandle  = context.RequestData.ReadInt32();
It really depends of the offset at which a field is placed and the next field size.

Basically this follow standard C alignment *most* of the time.

example 1 (padding):
```c
struct A {
    int  field_0x0;
                    // padding of 4 bytes right after field_0x0 to meet the alignment requirements for field_0x8. (sizeof(long) - sizeof(int) = 4)
    long field_0x8;
}
```

example 2 (no padding):
```c
struct A {
    int  field_0x0;
    int  field_0x4;
                    // no padding after field_0x4 because it meet the alignment requirements for field_0x8. (sizeof(long) - (sizeof(int) + sizeof(int)) = 0)
    long field_0x8;
}
```

2021-06-17 22:12 UTC, LukeFZ commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            int  sixAxisSensorHandle  = context.RequestData.ReadInt32();
Alright, so just add the sizes of all previous fields together and check how many padding bytes to add to get to a multiple of 8 bytes, correct? 

Adding the same padding to IsSixAxisSensorAtRest and ResetSixAxisSensorFusionParameters (among others) fixes their applet ids as well, so I can confirm that this would fix other commands as well. Should I open up another PR for those fixes, or just add them to this one? (Personally I'd open up another PR, to not clutter up this one with unrelevant changes)

2021-06-17 22:14 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            int  sixAxisSensorHandle  = context.RequestData.ReadInt32();
Another PR would be better 👍

2021-06-17 22:15 UTC, LukeFZ commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +            int  sixAxisSensorHandle  = context.RequestData.ReadInt32();
Great! I'll do that then.

2021-06-17 23:48 UTC, AcK77 approved these changes
Thanks for your contribution, lgtm!

2021-06-19 11:52 UTC, Thog approved these changes

2021-06-19 11:53 UTC, merged