Initial support for GPU channels
Ryujinx/Ryujinx pull request #2372
Opened 2021-06-17 20:22 UTC by gdkchan

This adds some basic support for GPU channels. Each channel has *separate state*. Due to the fact that everything was using a single channel before, games that made use of multiple Queues (each Queue is a channel) would end with corrupt state. The most common situation that causes this is Queue A setting up its state, then a new queue (Queue B) being created, and then setting up its own state, and corrupting Queues A state in the process.

This fixes the problem by adding a new `GpuChannel` class, and moving almost all of the state that shouldn't be shared there. A few things such as draw state were not moved yet, but those shouldn't cause issues as this state is reset often. GPU address spaces are also still shared, but this is a separate issue, and queues can share an address space (address spaces are created per Device rather than per Queue).

Things that still need to be done:
- Separate host state. OpenGL doesn't allow this, at least not easily. The backend could expose a `CreatePipeline` method, and allow the creation of separate pipelines. Supporting this on OpenGL would require keeping track of each pipeline state and setting it on switch as needed, or using multiple contexts. Vulkan allows the creation of multiple queues, were each queue has separate state, but queues have a limit that varies per vendor.
- Separate remaining state on frontend (mostly draw related state).
- Separate GPU address spaces (this is likely the most complicated part). Likely requires the memory tracking to work over physical memory instead, otherwise the the caches are dependant on the guest process address space, which means that those resources can't be shared between processes.

This fixes a number of games that previously had `InvalidMemoryRegionException`s caused by addresses from already closed channels being used, due to all queues sharing the same channel.

Fixes https://github.com/Ryujinx/Ryujinx-Games-List/issues/2901
Now goes ingame.
![image](https://user-images.githubusercontent.com/5624669/122465599-abd37600-cf8e-11eb-9642-258b20f13d1c.png)
![image](https://user-images.githubusercontent.com/5624669/122465615-afff9380-cf8e-11eb-8c26-bc1bf7374b03.png)
![image](https://user-images.githubusercontent.com/5624669/122465628-b4c44780-cf8e-11eb-83c7-5e872c22e1a2.png)
(Note: Still has an issue when a save is loaded where the scene is mostly black. Needs further investigation.)

Fixes https://github.com/Ryujinx/Ryujinx-Games-List/issues/1965
Now goes ingame.
![image](https://user-images.githubusercontent.com/5624669/122465764-dde4d800-cf8e-11eb-8c22-63e50e493565.png)
![image](https://user-images.githubusercontent.com/5624669/122465780-e0dfc880-cf8e-11eb-8388-2e3fa99153ff.png)
![image](https://user-images.githubusercontent.com/5624669/122465815-e6d5a980-cf8e-11eb-9fc3-9fcc29588540.png)
![image](https://user-images.githubusercontent.com/5624669/122465830-ea693080-cf8e-11eb-97c9-00bed3778ba2.png)

Likely also fixes (needs re-testing, I don't have those games):
https://github.com/Ryujinx/Ryujinx-Games-List/issues/82
https://github.com/Ryujinx/Ryujinx-Games-List/issues/143
https://github.com/Ryujinx/Ryujinx-Games-List/issues/745
https://github.com/Ryujinx/Ryujinx-Games-List/issues/876
https://github.com/Ryujinx/Ryujinx-Games-List/issues/924
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3077
Might also fix Nekopara vol. 1/2/3 save issue?

2021-06-17 20:56 UTC, Thog requested changes
Some tiny issues I found on my first review pass 👍 

So far I didn't found any regressions on the games I tested.

2021-06-17 20:56 UTC, Thog commented on Ryujinx.Graphics.Gpu/Memory/BufferCache.cs
> +    class BufferCache
Missing ``IDisposable``

2021-06-17 20:56 UTC, Thog commented on Ryujinx.Graphics.Gpu/Image/TextureManager.cs
> -    class TextureManager : IDisposable
TextureManager still implement Dispose, this shouldn't be removed.

2021-06-17 21:41 UTC, Thog approved these changes

2021-06-18 14:02 UTC, zombie167 commented
It should be certain that Dragon Ball Xenoverse 2 can enter the game.
![test](https://user-images.githubusercontent.com/22722505/122572289-3051f180-d080-11eb-8675-5490d7d2131c.jpg)

Final Fantasy X/X-2 HD Remaster not being able to enter the game should be a regression, because the earlier version 1.0.5796 is ok, this PR has not been fixed yet, I believe it is caused by some reason
https://youtu.be/j0lHliNHRhc

2021-06-18 14:13 UTC, EmulationFanatic commented
> It should be certain that Dragon Ball Xenoverse 2 can enter the game.
> ![test](https://user-images.githubusercontent.com/22722505/122572289-3051f180-d080-11eb-8675-5490d7d2131c.jpg)
> 
> Final Fantasy X/X-2 HD Remaster not being able to enter the game should be a regression, because the earlier version 1.0.5796 is ok, this PR has not been fixed yet, I believe it is caused by some reason
> https://youtu.be/j0lHliNHRhc

Final Fantasy X/X-2 HD Remaster is not a regression on this PR. It does not go in-game on master and has not for some time, as noted in the issue:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/876

2021-06-18 16:13 UTC, zombie167 commented
> > It should be certain that Dragon Ball Xenoverse 2 can enter the game.
> > ![test](https://user-images.githubusercontent.com/22722505/122572289-3051f180-d080-11eb-8675-5490d7d2131c.jpg)
> > Final Fantasy X/X-2 HD Remaster not being able to enter the game should be a regression, because the earlier version 1.0.5796 is ok, this PR has not been fixed yet, I believe it is caused by some reason
> > https://youtu.be/j0lHliNHRhc
> 
> Final Fantasy X/X-2 HD Remaster is not a regression on this PR. It does not go in-game on master and has not for some time, as noted in the issue:
> [Ryujinx/Ryujinx-Games-List#876](https://github.com/Ryujinx/Ryujinx-Games-List/issues/876)

Sorry for misunderstanding,I am not referring to the emulation regression caused by PR

2021-06-19 02:35 UTC, gdkchan commented
It has come to my attention that `COTTOn Reboot!` was able to progress further with those changes, but didn't render anything, so I decided to take a look. It turns out that the game was broken because the host state was not updated, and one channel was using stale state from another one. I fixed it by marking all state as modified on channel switch, and also forcing rebind of all buffers, textures and render targets. This also solves one of the bullets of the "Things that still need to be done". The PR description has been updated and now includes test results of this game.

Anyone that already reviewed may wish to take a look at the latest commit, and maybe do a retest.

2021-06-23 08:33 UTC, Thog approved these changes

2021-06-23 21:55 UTC, riperiperi approved these changes
Looking great, very nice work. Just one small nit.

2021-06-23 21:55 UTC, riperiperi commented on Ryujinx.Graphics.Gpu/Engine/GPFifo/GPFifoProcessor.cs
> +        /// Forces a full host state update by marking all state as modfied,
`modified`

2021-06-23 22:08 UTC, riperiperi approved these changes

2021-06-23 23:51 UTC, merged