changing the session cleaning to fix a crash while running Game Builder Garage
Ryujinx/Ryujinx pull request #2438
Opened 2021-07-02 16:15 UTC by Gummygamer

2021-07-02 16:34 UTC, emmauss commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    //_sessions.Remove(serverSessionHandle);
removed commented out code

2021-07-02 16:34 UTC, Benedani requested changes

2021-07-02 16:34 UTC, Benedani commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +            }
There is something called `_sessions.ContainsKey`. No need for the slower try-catch.

2021-07-02 16:34 UTC, Benedani commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    //_sessions.Remove(serverSessionHandle);
Are you sure this won't cause any regressions?

2021-07-02 16:42 UTC, Gummygamer commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    //_sessions.Remove(serverSessionHandle);
It would easily cause a crash if it weren't by the approach of removing sessions if they collide in key. As it is I'm more concerned with possible performance issues like in memory usage or speed. I'm really thinking it might be there a better way to manage that memory.

2021-07-02 20:58 UTC, Gummygamer commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +            }
Changed.

2021-07-02 21:02 UTC, Gummygamer commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    //_sessions.Remove(serverSessionHandle);
changed.

2021-07-06 16:17 UTC, AcK77 requested changes

2021-07-06 16:17 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> -                    _sessions.Remove(serverSessionHandle);
if the `IpcMessageType` is `HipcCloseSession` of `TipcCloseSession` I'm pretty sure the session have to be removed here and not in the `AddSessionObj` method.

2021-07-06 16:17 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +            if(!_sessions.ContainsKey(serverSessionHandle))
```suggestion
            if (!_sessions.ContainsKey(serverSessionHandle))
```

Imo this looks like more as a hack than a real fix :/

2021-07-06 18:52 UTC, Gummygamer commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +            if(!_sessions.ContainsKey(serverSessionHandle))
I understand and would love some help in reaching a better solution if possible. This PR avoided crashes and, because I remove sessions when they collide in key, it remains viable to run. That's why it's submitted at all, but I know it deserves polish.

2021-07-06 19:03 UTC, Gummygamer commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> -                    _sessions.Remove(serverSessionHandle);
Interesting distinction in terms of message type. Should I add a branch (if) to detect that?

2021-07-06 19:15 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> -                    _sessions.Remove(serverSessionHandle);
It's just a way to handle both type, there is no distinction in terms of functionality here.

2021-07-07 20:38 UTC, Gummygamer commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> -                    _sessions.Remove(serverSessionHandle);
Now I've checked the context of the code in question and I suppose not removing the sessions in those conditions is core to my solution to the crashes. The crashes happened when a session key was not found in the dictionary. So...maybe Ryujinx was trying to close sessions too soon without my PR? Again, I would love help with a "smoother" solution if the current one is too rough.

2022-03-15 10:55 UTC, AcK77 commented
Closing as stale and because this isn't a proper fix.

2022-03-15 10:55 UTC, closed without merging