Implementations of SVC calls related to self modifying code
Ryujinx/Ryujinx pull request #2451
Opened 2021-07-08 10:19 UTC by shadowninja108

(Don't merge until tested thoroughly)

2021-07-08 12:20 UTC, Leischii commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                KernelResult r = proc.MemoryManager.MapPages(address, _host_pagelist, KMemoryPermission.ReadAndWrite);
Don't think r as variable name will go through review

2021-07-10 17:33 UTC, AcK77 requested changes
On top of all those comments related to codestyle, it could be nice to get a little PR description even if this is a draft. What needs those SVC?

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        private IEnumerable<HostMemoryRange> _host_pagelist;
```suggestion
        private IEnumerable<HostMemoryRange> _hostPagelist;
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        private ulong _pagecount;
```suggestion
        private ulong _pageCount;
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        private ulong _src_addr;
```suggestion
        private ulong _srcAddress;
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        private bool _initialized;
If the value of this field is never used, it's probably better to remove it.

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        private bool _is_owner_mapped;
```suggestion
        private bool _isOwnerMapped;
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        private bool _is_mapped;
```suggestion
        private bool _isMapped;
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +            if (_pagecount != BitUtils.DivRoundUp(size, KPageTableBase.PageSize))
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                if (_is_mapped)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +
remove extra empty line

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +            return KernelResult.Success;
Add a new empty line before

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                // MemoryState.CodeWritable
Leftover ?

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                KernelResult r = proc.MemoryManager.MapPages(address, _host_pagelist, KMemoryPermission.ReadAndWrite);
Yeah `r` is a bit strange as a var name. `resultCode` it's maybe better?

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +            if (_pagecount != BitUtils.DivRoundUp(size, KPageTableBase.PageSize))
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                if (_is_owner_mapped)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        public KernelResult MapToOwner(ulong address, ulong size, KMemoryPermission perm)
```suggestion
        public KernelResult MapToOwner(ulong address, ulong size, KMemoryPermission permission)
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                    perm == KMemoryPermission.Read ?
You can put this on one line

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                // MemoryState.CodeReadOnly
leftover ?

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +
remove extra empty line

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +            if (_pagecount != BitUtils.DivRoundUp(size, KPageTableBase.PageSize))
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +            if (_pagecount != BitUtils.DivRoundUp(size, KPageTableBase.PageSize))
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +        public KernelResult UnmapToOwner(ulong address, ulong size)
Add a new empty line before

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                _is_owner_mapped = false;
Add a new empty line before

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +
remove extra empty line

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +
remove extra empty line

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            /* TODO: Hack, speaks for itself. */
```suggestion
            // TODO: Hack, speaks for itself.
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            if (srcProcess == null)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            /* TODO: Hack, speaks for itself. */
```suggestion
            // TODO: Hack, speaks for itself.
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            if (srcProcess == null)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +
Remove extra empty line

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            KCodeMemory cmem = new KCodeMemory(_context);
```suggestion
            KCodeMemory codeMemory = new KCodeMemory(_context);
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            cmem.Initialize(address, size);
Add new empty line before

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            KCodeMemory cmem = process.HandleTable.GetObject<KCodeMemory>(handle);
```suggestion
            KCodeMemory codeMemory = process.HandleTable.GetObject<KCodeMemory>(handle);
```

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +                        if (HasJitPatch || permission != KMemoryPermission.ReadAndWrite)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +                        if (HasJitPatch || (permission | KMemoryPermission.Execute) == KMemoryPermission.ReadAndExecute)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +                        if (HasJitPatch || permission == KMemoryPermission.None)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +                        if (HasJitPatch || permission == KMemoryPermission.None)
You should add brackets

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            return KernelResult.InvalidHandle;
Add a new empty line before

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +
remove extra empty line

2021-07-10 17:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall64.cs
> +        public KernelResult MapProcessMemory64([R(0)] ulong dst, [R(1)] int handle, [R(2)] ulong src, [R(3)] ulong size)
Add empty line before

2021-07-10 19:06 UTC, shadowninja108 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                // MemoryState.CodeWritable
A proper implementation would specify the memory state for the pages, but that doesn't seem possible atm. I left this as a note until it could be sorted out, I'll probably clarify in the comment.

2021-07-10 19:07 UTC, shadowninja108 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                // MemoryState.CodeReadOnly
Same as the other memory state comment.

2021-07-10 19:09 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/Process/KCodeMemory.cs
> +                // MemoryState.CodeWritable
It could be nice to clarify that in a comment yes ;)

2022-05-03 11:53 UTC, MutantAura commented
Superceded by #2958

2022-05-03 11:53 UTC, closed without merging