Amadeus: DSP code generation improvements
Ryujinx/Ryujinx pull request #2460
Opened 2021-07-10 19:49 UTC by Thog

This improve RyuJIT codegen drastically on the DSP side.
This may reduce CPU usage of the DSP thread quite a lot.

There is still room to improvements on that side and this might be addressed by follow up PRs.

As always, regression testing needed.

2021-07-10 20:40 UTC, GamerzHell9137 commented
Are there any places where we should look into where we could see differences?
Which audio backend etc?

2021-07-11 04:26 UTC, Thealexbarney requested changes
Looks mostly good. And I have to say you're quite aggressive with `AggressiveInlining`

2021-07-11 04:26 UTC, Thealexbarney commented on Ryujinx.Audio/Renderer/Dsp/Command/CommandList.cs
> +            if (index > 0 && index < _buffersEntryCount)
index >= 0

2021-07-11 09:53 UTC, Thog commented on Ryujinx.Audio/Renderer/Dsp/Command/DepopForMixBuffersCommand.cs
> +            Debug.Assert(depopValue == 0);
Technically can be removed as this should never be called with 0

2021-07-11 10:02 UTC, Thog commented on Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs
> +        [MethodImpl(MethodImplOptions.AggressiveInlining)]
I guess as I have all of those with known channel count I could make those constants here, thanks 👍

2021-07-13 01:35 UTC, Thealexbarney approved these changes
Looks okay to me

2021-07-16 16:54 UTC, AcK77 approved these changes

2021-07-18 11:05 UTC, merged