Implement vibrations
Ryujinx/Ryujinx pull request #2468
Opened 2021-07-12 00:21 UTC by mpnico

### Implements vibrations in Ryujinx.
Based on previous PRs #1665 and #1436 and adapted for Miria (#2194)

Amplification values are ignored for now, only frequency values are used. Frequency values seems to oscillate around a neutral value which stop the rumble effect. This neutral value change between games and was assumed to be the first vibration values sent to the npad. Still some values seems weird, for example when hitting a wall in SMO.

#### Tested games
- Mario Kart 8 Deluxe
- Super Mario Odyssey
- Super Mario 3D World
- Diablo III

#### TODO
- [ ] Add UI option to enable / disable rumble
- [ ] Dig out better frequency calculation
- [ ] Figure out how to use amplification

2021-07-12 01:10 UTC, Shahil-Ayato commented
Is this also for HD rumble or just regular rumble for now?

2021-07-12 01:25 UTC, RyzenDew commented
It works well and feels nice but in smo when rumble should help you find the moon in the ground it wont stop vibrating seas kingdom green pipe
Also tested just dance 2021 and it works great there.

2021-07-12 01:32 UTC, Mou-Ikkai commented
Game: Super Smash Bros. Ultimate
Controller: Xbox One Wireless (MODEL 1708) w/ Xbox Wireless Adapter.

When going from the intro into the main menu, the rumble doesn't stop naturally. (It took about 1 minute to stop, I used a stopwatch.)
TEST 2: None of SSBU's rumbles stop at the correct time. The logs seem to point that: aLow and aHigh reset to 0, but fLow and fHIgh stay at 160-320 respectively at any time. I believe the stop of the rumbling may be caused by the Xbox adapter/Controller in a timeout of sorts.

[SSBU-RUMBLE.log](https://github.com/Ryujinx/Ryujinx/files/6798082/Ryujinx_1.0.0%2B926bb10_2021-07-11_21-21-43.log)

2021-07-12 01:46 UTC, MutantAura commented
### Initial tests

**Super Smash Bros. Ultimate** - Controller first vibrates on pressing START at title and never stops. Continuous vibration throughout game and only stops when closing game. Reconnecting controller will stop the effect but it will start as soon as any vibration effect is used again. Worth noting that other vibrations still happened at the correct time e.g. on move hits etc but a background vibration was persistent.

**Mario Kart 8 Deluxe** - Perfect as far as I can tell. Will test more between Ryu and switch later but for now I can't detect any major issues.

**The Legend of Zelda: Breath of the Wild** - Could not notice any vibrations/rumble at all. Unsure of what the issue is here.

**Pokémon Shield** - Vibration works on main menu when not in-game. Need to check this against real hardware as it's been so long since I've played.

2021-07-12 10:00 UTC, Thog commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        if (!_device.Hid.Npads.RumbleQueues.TryGetValue(playerIndex, out ConcurrentQueue<HidVibrationValue> rumbleQueue))
imo this if block should be done in the HLE project.

2021-07-12 10:00 UTC, Thog commented on Ryujinx.Input/HLE/NpadController.cs
> +                Logger.Info?.Print(LogClass.Hid, "New rumble effect aLow=" + vibrationValue.AmplitudeLow + ", fLow=" + vibrationValue.FrequencyLow + ", aHigh=" + vibrationValue.AmplitudeHigh + ", fHi
Reminder to remove this before undrafting ^^

2021-07-12 10:00 UTC, Thog commented on Ryujinx.Input/HLE/NpadController.cs
> +                // FrequencyHigh oscillate around stopValues.FrequencyHigh
```suggestion

                // FrequencyHigh oscillate around stopValues.FrequencyHigh
```

2021-07-12 10:00 UTC, Thog commented on Ryujinx.Input/HLE/NpadController.cs
> +                float lowFreq = Math.Abs(vibrationValue.FrequencyLow - stopValues.FrequencyLow) / stopValues.FrequencyLow;
I think this is a nice middle ground in term of algorithm, need testing but still.

2021-07-12 10:00 UTC, Thog commented on Ryujinx.Input/HLE/NpadController.cs
> +                _gamepad.RumbleInfinity(lowFreq, highFreq);
I do think the system module auto reset to the stop state after a quite short amount of time, will check again later during the week.

2021-07-12 10:00 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> -                    controller.StyleSet           = NpadStyleTag.FullKey;
All of this is aligned for clarity, rollback all those changes.

2021-07-12 10:00 UTC, Thog commented on Ryujinx.Input/IGamepad.cs
> +        void RumbleInfinity(float lowFrequency, float highFrequency);
I don't think ``RumbleInfinity`` is needed.
Would be better to just send uint.MaxValue and remap on the SDL2 gamepad side if ``durationMs == uint.MaxValue`` and throw an exception if ``durationMs > SDL_HAPTIC_INFINITY`` otherwise.

2021-07-12 10:00 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +                    // first value received seems to be the "stop" values
imo we could easily find the "stop" values and use them as constant.
There is also no guaranties that we will receive a "stop" value first.

2021-07-12 13:27 UTC, Niwu34 commented
The 8bit do mode of the sn30 plus doesn't seem to work with this Pr
switch/xinput mode work tho
I have a feeling that the Feedback is always a little too long (Need to compare it with my switch later)
Monster Hunter Stories 2 starts with one minute rumble and my controller starts vibrating for a whole min evertime there is Rumble in the game

2021-07-12 20:46 UTC, Benedani commented
I feel like the long rumbles are being caused by the amplification values being ignored.
Would multiplying the frequency with the amplification work?

2021-07-12 21:38 UTC, mpnico commented
This is more complex. Currently, SDL2 lib only implements "regular" rumble for now : two motors, "fixed" frequency, variable intensity. So we have to find a "magic formula" to translate HD rumble to regular rumble. Using only amplification seems not enough, using only frequency seems worse

2021-07-12 21:40 UTC, RyzenDew commented
One of the yuzu prs has an sdl2 git that has hd rumble wip

2021-07-12 22:03 UTC, Mou-Ikkai commented
> One of the yuzu prs has an sdl2 git that has hd rumble wip

That's... Irrelevant.

2021-07-13 00:19 UTC, CeruleanSky commented
> One of the yuzu prs has an sdl2 git that has hd rumble wip

https://github.com/german77/SDL/tree/hd_rumble  
The first commit to the tree has some frequency tables if they aren't already present in Ryujinx and the PR mentions that SDL will have HD rumble support in the future so perhaps it will be eventually up-streamed.

2021-07-13 23:58 UTC, mpnico commented
Updated the PR, much better implementation.

2021-07-14 23:26 UTC, Mou-Ikkai commented
Game: Super Smash Bros. Ultimate
Controller: Xbox One Wireless (MODEL 1708) w/ Xbox Wireless Adapter.

Rumble seems normal after latest patch. Rumbles seem to match that of the game being run on a native switch. Plus the rumbles don't overextend when there are FPS drops. It also didn't break when I set myself to be hit by multiple enemies at once.

2021-07-14 23:34 UTC, Mou-Ikkai commented
Game: Project DIVA Mega Mix
Controller: Xbox One Wireless (MODEL 1708) w/ Xbox Wireless Adapter.
Song: Meteor

As a test of simple rumbles, I decided to try the long-Sliders on MegaMix. It was mostly fine, one issue I saw is that sometimes, the rumble would weaken at a random part of the slider, then suddenly come back near the middle or end of the slide.

2021-07-15 00:58 UTC, mpnico commented
Updated PR with the UI work.

2021-07-15 13:48 UTC, Benedani commented
Seems to work in my tested games: SMO, SSBU, MK8 Deluxe, 3D World, Super Mario Maker 2, BotW, Terraria and Pokemon Sword (literally the only time you get rumble is in Dynamax battles btw, great game). Minecraft's absence of rumble also works.

2021-07-16 11:43 UTC, emmauss requested changes

2021-07-16 11:43 UTC, emmauss commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +        private Boolean IsSameVibrationValues(HidVibrationValue val1, HidVibrationValue val2)
use `bool` alias.
Consider replacing with an override of `Equals` of  `HidVibrationValue`

2021-07-16 11:43 UTC, emmauss commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +        private HidVibrationValue _neutralVibrationValue = new HidVibrationValue
Use a static  field to represent the neutral value. It can be used below

2021-07-16 11:43 UTC, emmauss commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +                return new HidVibrationValue
can be replaced with static field for neutral value

2021-07-16 11:43 UTC, emmauss commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +            if (position == 0)
This can be simplified with a ternary conditional operator

2021-07-16 17:14 UTC, AcK77 requested changes

2021-07-16 17:14 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationState.cs
> +                foreach(InputConfig config in configurationFileFormat.InputConfig)
```suggestion
                foreach (InputConfig config in configurationFileFormat.InputConfig)
```

2021-07-16 17:14 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +
remove extra empty line

2021-07-16 17:14 UTC, AcK77 commented on Ryujinx.Headless.SDL2/Program.cs
> +
remove extra empty line

2021-07-16 17:14 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +                }
Add a new empty line after

2021-07-16 17:14 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +                }
Add a new empty line after

2021-07-22 22:29 UTC, mpnico commented on Ryujinx.Input/HLE/NpadController.cs
> +                float lowFreq = Math.Abs(vibrationValue.FrequencyLow - stopValues.FrequencyLow) / stopValues.FrequencyLow;
That was actually wrong, I use amplitude now

2021-07-22 22:32 UTC, mpnico commented on Ryujinx.Input/HLE/NpadController.cs
> +                _gamepad.RumbleInfinity(lowFreq, highFreq);
During my tests on last commit, I was never able to reproduce an infinite rumble situation. But more tests is needed to be sure.

2021-07-22 22:33 UTC, mpnico commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +                    // first value received seems to be the "stop" values
Absolutely true :) That approach was wrong.

2021-07-22 23:09 UTC, mpnico commented
Added requested changes and implemented missing GetVibrationDeviceInfo Service, thx to @AcK77

This fix the lack of rumble in Monster Hunter Rise (and probably other games too)

2021-07-25 22:48 UTC, Thog commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        if (!_device.Hid.Npads.RumbleQueues.TryGetValue(playerIndex, out ConcurrentQueue<HidVibrationValue> rumbleQueue))
yes

2021-07-25 23:07 UTC, AcK77 requested changes
Just some code style issues for a first batch, I’ll take a closer look when this will be addressed! Thanks for working on the rumble feature ;)

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +                    }
Add a new extra empty line after

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/ResultCode.cs
> +        InvalidNpadDeviceType = (122 << ErrorCodeShift) | ModuleId,
It could be nice to keep the alignment as we did in other `ResultCode.cs` file for considtency

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/ResultCode.cs
> +        InvalidDeviceIndex = (124 << ErrorCodeShift) | ModuleId,
124 is duplicated

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                    throw new NotSupportedException($"Unsupported rumble duration {durationMs}");
I’m not sure we should throw an exception here, maybe a logging error is enough, since it will not stop the execution for a vibration error.

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +            if (queue.TryDequeue(out (HidVibrationValue, HidVibrationValue) dualVvibrationValue))
```suggestion
            if (queue.TryDequeue(out (HidVibrationValue, HidVibrationValue) dualVibrationValue))
```

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +                    Logger.Debug?.Print(LogClass.Hid, $"New rumble effect for {controllerConfig.PlayerIndex} " +
The logger should print the method name `UpdateRumble` so the message text could be shorter.

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        if (!_device.Hid.Npads.RumbleQueues.TryGetValue(playerIndex, out ConcurrentQueue<(HidVibrationValue, HidVibrationValue)> rumbleQueue))
Add a new extra empty line before

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        controller.UpdateRumble(rumbleQueue);
Add a new extra empty line before

2021-07-25 23:07 UTC, AcK77 commented on Ryujinx.Input/IGamepad.cs
> +        /// Starts a rumble effect on the gamepad.
Nice catch!

2021-07-25 23:49 UTC, mpnico commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        if (!_device.Hid.Npads.RumbleQueues.TryGetValue(playerIndex, out ConcurrentQueue<(HidVibrationValue, HidVibrationValue)> rumbleQueue))
Block has been moved to NpadDevices

2021-07-25 23:49 UTC, mpnico commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        controller.UpdateRumble(rumbleQueue);
Block has been moved to NpadDevices

2021-07-25 23:52 UTC, mpnico commented
Rebased and added requested changes (but one, on ResultCode)

2021-07-27 21:29 UTC, MelonSpeedruns commented
I've played Skyward Sword for about 2 hours with this PR with an official Pro Controller. There was no bugs or weird issues I've encountered! GG!

2021-07-30 23:11 UTC, AcK77 requested changes
Some nits left, after that everything should be good!

2021-07-30 23:11 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +{
Wrong alignment

2021-07-30 23:11 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/HidDevices/NpadDevices.cs
> +            return rumbleQueue;
Add a new empty line before.

2021-07-30 23:11 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/IHidServer.cs
> +                context.Device.Hid.Npads.UpdateRumbleQueue(currentIndex, dualVibrationValues);
Add a new empty line before.

2021-07-30 23:11 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/ResultCode.cs
> +        InvalidBufferSize     = (124 << ErrorCodeShift) | ModuleId
```suggestion
        InvalidBufferSize     = (131 << ErrorCodeShift) | ModuleId
```
And it should be returned in `SendVibrationValues` call if `vibrationValues.Length != deviceHandles.Length`

2021-08-02 20:23 UTC, mpnico commented on Ryujinx.HLE/HOS/Services/Hid/ResultCode.cs
> +        InvalidBufferSize     = (124 << ErrorCodeShift) | ModuleId
Thx for the right value !

2021-08-02 20:24 UTC, mpnico commented
Adressed last requested changes.

2021-08-02 20:29 UTC, AcK77 approved these changes

2021-08-02 20:40 UTC, Thog approved these changes

2021-08-03 21:08 UTC, RyzenDew commented
rumble does not work on the joy cons at all not sure if you can add it or not

2021-08-04 20:03 UTC, mpnico commented
> rumble does not work on the joy cons at all not sure if you can add it or not

I will try to investigate the problem.

2021-08-04 22:39 UTC, merged

2021-08-04 22:48 UTC, RyzenDew commented
> > rumble does not work on the joy cons at all not sure if you can add it or not
> 
> 
> 
> I will try to investigate the problem.

Guess it will be in another pr ... lol also thank you