Add Application Content Explorer
Ryujinx/Ryujinx pull request #2479
Opened 2021-07-15 09:04 UTC by emmauss

Adds a content explorer to game files in the game list, specifically nsp and xci files. This allows viewing the content of the game's filesystems, including xci partitions, filesystems, archives like nca, etc. It also supports extracting filesystems and saving binary or blocks to the local filesystem. Extraction is found in the context menu after selecting an applicable item.
The feature can be found in the Extract Data submenu in the game list context menu, or using the Explore button in the dlc window if you want to view the contents of a dlc archive.
![Screenshot from 2021-07-15 08-55-44](https://user-images.githubusercontent.com/5307160/125760809-20253c85-fcd2-41fc-8645-6b4ac94e2b5b.png)

2021-07-18 10:53 UTC, Thog requested changes
lgtm only a small warn to fix

2021-07-18 10:53 UTC, Thog commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                catch (Exception ex)
Fix warning here

2021-07-20 17:31 UTC, Miepee commented on Ryujinx/Ui/Widgets/GameTableContextMenu.Designer.cs
> +            _exploreMenuItem = new MenuItem("Expore Contents")
```suggestion
            _exploreMenuItem = new MenuItem("Explore Contents")
```
Just a small typo.

2021-07-23 22:58 UTC, AcK77 requested changes
A bunch of codestyle issues have to be fixed, I still haven't check the logic and the code by itself for now. I'm not a huge fan of using a different GTK version for the `.glade` file too.

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/DlcWindow.cs
> +                if(path.ToLower().EndsWith(".nsp"))
```suggestion
                if (path.ToLower().EndsWith(".nsp"))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +        public VirtualFileSystem VirtualFileSystem { get; }
You can't put those `private` ?

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(string.IsNullOrWhiteSpace(query))
```suggestion
            if (string.IsNullOrWhiteSpace(query))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(name == "[expand]" || type == "Section" || type == "Partition")
```suggestion
            if (name == "[expand]" || type == "Section" || type == "Partition")
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(name.Contains(query) || titleId.Contains(query))
```suggestion
            if (name.Contains(query) || titleId.Contains(query))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                model.IterChildren(out childIter, parentIter);
```suggestion
                model.IterChildren(out TreeIter childIter, parentIter);
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                TreeIter childIter;
This can be removed.

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                    if (name.Contains(query) || titleId.Contains(query))
Add brackets

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                    if (model.IterHasChild(childIter))
Add brackets

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(type == "Section" || type == "Partition" || type == "DIR")
```suggestion
            if (type == "Section" || type == "Partition" || type == "DIR")
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                MenuItem extractToMenuItem = new MenuItem("Extract To ...");
```suggestion
                MenuItem extractToMenuItem = new MenuItem("Extract to ...");
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                MenuItem saveToMenuItem = new MenuItem("Save To ...");
```suggestion
                MenuItem saveToMenuItem = new MenuItem("Save to ...");
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                SelectMultiple = false,
```suggestion
                SelectMultiple = false
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
Remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(_operationRunning)
```suggestion
            if (_operationRunning)
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            string savePath = GetSaveToPath("Save To...");
```suggestion
            string savePath = GetSaveToPath("Save to ...");
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            FileStream destination;
it's a bit strange to have the same var name 10 lines above.

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
Remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +        public void LogMessage(string message)
It's a bit strange to name LogMessage since we already have a Logger class. `UpdateStatusBarMessage` should be better.

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(fileSystem.OpenDirectory(out var directory, entry.FullPath.ToU8Span(), OpenDirectoryMode.All) == Result.Success)
```suggestion
            if (fileSystem.OpenDirectory(out var directory, entry.FullPath.ToU8Span(), OpenDirectoryMode.All) == Result.Success)
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                switch(entry.Type)
```suggestion
                switch (entry.Type)
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            foreach(var entry in fileSystem.EnumerateEntries("*", SearchOptions.Default))
```suggestion
            foreach (var entry in fileSystem.EnumerateEntries("*", SearchOptions.Default))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                if(nca.CanOpenSection(sectionType))
```suggestion
                if (nca.CanOpenSection(sectionType))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            foreach(var sectionType in Enum.GetValues<NcaSectionType>())
```suggestion
            foreach (var sectionType in Enum.GetValues<NcaSectionType>())
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(parentIter.Equals(TreeIter.Zero))
```suggestion
            if (parentIter.Equals(TreeIter.Zero))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                catch (Exception ex)
Maybe you should log the exception too?

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                        if(section.DirectoryExists("/" + relativePath))
```suggestion
                        if (section.DirectoryExists("/" + relativePath))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                if(nca.CanOpenSection(sectionType))
```suggestion
                if (nca.CanOpenSection(sectionType))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(treeStore.IterNChildren(args.Iter) == 1 && treeStore.IterChildren(out var child, args.Iter))
```suggestion
            if (treeStore.IterNChildren(args.Iter) == 1 && treeStore.IterChildren(out var child, args.Iter))
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                                                }
Add a new empty line after

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                    ulong size = 0;
Add a new empty line after.

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                                                return;
Add a new empty line before

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                                            string relativePath = string.Join('/', levels.AsSpan().Slice(3).ToArray());
Add a new empty line before

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            string savePath = GetSaveToPath("Extract To...");
```suggestion
            string savePath = GetSaveToPath("Extract to ...");
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            if(_operationRunning)
```suggestion
            if (_operationRunning)
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +            _explorerSelection.GetSelected(out TreeIter treeIter);
Add extra empty line before

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                            if(section.OpenFile(out var file, relativePath.ToU8Span(), OpenMode.Read) == Result.Success)
```suggestion
                            if (section.OpenFile(out var file, relativePath.ToU8Span(), OpenMode.Read) == Result.Success)
```

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +                                            string relativePath = string.Join('/', levels.AsSpan().Slice(3).ToArray());
Add extra empty line before

2021-07-23 22:58 UTC, AcK77 commented on Ryujinx/Ui/Windows/AppExplorerWindow.cs
> +
remove extra empty line

2022-09-11 07:04 UTC, closed without merging