Ensure right joycon motion data is set
Ryujinx/Ryujinx pull request #2488
Opened 2021-07-17 22:49 UTC by emmauss

There's a bug where the right joycon is not retrieved from cemuhook, and that the right joycon motion shared mem is cleared after update. This aims to fix that issue. 
This should allow right joycon to work in Skyward Sword.

2021-07-17 23:12 UTC, Shahil-Ayato commented on Ryujinx.Input/HLE/NpadController.cs
> +                        // Then request and retrive the data
`retrive` should be `retrieve`

2021-07-18 00:30 UTC, gdkchan commented
Closes #2127 I guess?

2021-07-18 10:57 UTC, Thog approved these changes
lgtm only one thing to change

2021-07-18 10:57 UTC, Thog commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        motionState = (controller.GetHLEMotionState(), isJoyconPair ? controller.GetHLEMotionState(true) : default);
Note really a huge fan of ternary inside tuples

2021-07-18 13:47 UTC, emmauss commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        motionState = (controller.GetHLEMotionState(), isJoyconPair ? controller.GetHLEMotionState(true) : default);
fixed

2021-07-18 17:04 UTC, AcK77 requested changes

2021-07-18 17:04 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +            var motionInput = _mainMotionInput;
```suggestion
            MotionInput motionInput = _mainMotionInput;
```

2021-07-18 17:04 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +            if(isSecondaryController)
```suggestion
            if (isSecondaryController)
```

2021-07-18 17:04 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +        public SixAxisInput GetHLEMotionState(bool isSecondaryController = false)
```suggestion
        public SixAxisInput GetHLEMotionState(bool isJoyconPair = false)
```

2021-07-18 17:04 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +                if(_secondaryMotionInput == null)
```suggestion
                if (_secondaryMotionInput == null)
```

2021-07-18 17:04 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadManager.cs
> +                    if(isJoyconPair && !motionState.Item2.Equals(default))
```suggestion
                    if (isJoyconPair && !motionState.Item2.Equals(default))
```

2021-07-18 17:22 UTC, emmauss commented
Addressed comments

2021-07-18 17:22 UTC, emmauss commented
Addressed comments

2021-07-18 20:45 UTC, AcK77 approved these changes

2021-07-18 23:32 UTC, gdkchan approved these changes
Looks alright, please add `Fixes #2127` if the issue is fixed by this change on the PR description, to have it auto-close on merge.

2021-07-20 16:47 UTC, emmauss commented
> 
> 
> Looks alright, please add `Fixes #2127` if the issue is fixed by this change on the PR description, to have it auto-close on merge.

It fixes only the last comments on #2127 . It doesn't fix the issue in the first comment.

2021-07-23 23:01 UTC, merged