Avalonia UI
Ryujinx/Ryujinx pull request #2507
Opened 2021-07-26 16:52 UTC by emmauss

Spanking new ui using avalonia. 

For the most part, this is a port of the gtk ui, with some avalonia specific changes here and there. The controller settings window has been merged with the settings window, and now has a new design which some of you may be familiar with. A new game load screen for showing pptc and cache progress has been added. There are other stuff that I may have forgotten, but it should be there somewhere.

![Screenshot from 2021-07-26 16-19-05](https://user-images.githubusercontent.com/5307160/127024984-10abdc38-1725-4066-a1c9-ccd726473fa1.png)
![Screenshot from 2021-07-26 16-19-09](https://user-images.githubusercontent.com/5307160/127025001-25fa4e1c-b434-48c8-a345-7b002357d51a.png)
![Screenshot from 2021-07-26 16-19-36](https://user-images.githubusercontent.com/5307160/127025014-85725058-bd7f-4798-aa4f-2b0311480a42.png)
![Screenshot from 2021-07-26 16-27-54](https://user-images.githubusercontent.com/5307160/127025026-bef61200-7935-4f8e-8453-f1253df26e25.png)
![Screenshot from 2021-07-26 16-28-07](https://user-images.githubusercontent.com/5307160/127025036-aa49fe8f-9591-4619-bc59-89db9d4c0880.png)
![Screenshot from 2021-07-26 16-28-46](https://user-images.githubusercontent.com/5307160/127025068-8c7d8ec6-9088-4c1d-b5dd-eef1a13e6f10.png)
![Screenshot from 2021-07-26 16-32-00](https://user-images.githubusercontent.com/5307160/127025381-9586b0b7-fabe-4fb5-acc6-7a06d1cc5f14.png)

There are a few issues with avalonia, and some have been reported and others we had to work around with.

- Although Avalonia has an opengl widget, they do not have a native opengl widget, and instead, draws what you have rendered unto a texture and draws that instead in a control during their render pass. Because we need full control over the opengl context, and also because we would need something that supports vulkan, we are using an embedded window to provide the opengl context and vulkan surface. This is what most other ui toolkits provide out of the box, but is not available on Avalonia.
- Due to the above, focus on the window can be finicky at times, due to how different os handles child windows.
- Comboboxes may crash if the contents are updated in real time and then accessed. This can occur on the controller profiles combobox, but it's rare. This is reported here, https://github.com/AvaloniaUI/Avalonia/issues/5571 .
- A scroll button may appear on devices with desktop scaling greater than 100% in menus. This is just a ui glitch and will be fixed in a newer dependency update.

This is currently beta and is open for testing and design review.

2021-07-26 16:58 UTC, emmauss commented
Currently, the build script needs to be updated to build the new project. Will do so soon.

2021-07-26 17:34 UTC, GamerzHell9137 commented
Changing controller settings crashes the emulator atm.

2021-07-26 17:52 UTC, pineappleEA commented
The GUI is looking great so far.
However, I have encountered two minor issues, both likely linux exclusive. The first is an error message that gets spammed in the terminal when executing the avalonia GUI 

> Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files
   at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
   at Tmds.DBus.Connection.CallMethodAsync(Message message)
   at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
   at Avalonia.FreeDesktop.DBusMenuExporter.DBusMenuExporterImpl.Init()

This occurs when opening any of the drop-down menus in the top bar (File, Options, Actions etc)
and is on Arch linux both on wayland and xwayland.

The second issue is that most text appears to be a few pixels above where it is supposed to be, causing the top row of pixels to be cut off, and often times not being centered vertically. Again on Arch linux and on both wayland and xwayland. Specifically KDE Plasma, as it might have something to do with being a qt desktop.
In this screenshot it is especially visible in the top and bottom bars.
![Screenshot_20210726_193908](https://user-images.githubusercontent.com/67879877/127034216-83ada6d5-015b-412b-a874-7565c474702d.png)
And in the settings it's also visible in most text.
![Screenshot_20210726_193926](https://user-images.githubusercontent.com/67879877/127034286-f7aff703-e732-4a21-9958-5f9b3e185612.png)

2021-07-26 18:34 UTC, emmauss commented
> 
> 
> The GUI is looking great so far.
> However, I have encountered two minor issues, both likely linux exclusive. The first is an error message that gets spammed in the terminal when executing the avalonia GUI
> 
> > Tmds.DBus.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files
> > at Tmds.DBus.DBusConnection.CallMethodAsync(Message msg, Boolean checkConnected, Boolean checkReplyType)
> > at Tmds.DBus.Connection.CallMethodAsync(Message message)
> > at Tmds.DBus.CodeGen.DBusObjectProxy.SendMethodReturnReaderAsync(String iface, String member, Nullable`1 inSignature, MessageWriter writer)
> > at Avalonia.FreeDesktop.DBusMenuExporter.DBusMenuExporterImpl.Init()
> 
> This occurs when opening any of the drop-down menus in the top bar (File, Options, Actions etc)
> and is on Arch linux both on wayland and xwayland.
> 
> The second issue is that most text appears to be a few pixels above where it is supposed to be, causing the top row of pixels to be cut off, and often times not being centered vertically. Again on Arch linux and on both wayland and xwayland. Specifically KDE Plasma, as it might have something to do with being a qt desktop.
> In this screenshot it is especially visible in the top and bottom bars.
> ![Screenshot_20210726_193908](https://user-images.githubusercontent.com/67879877/127034216-83ada6d5-015b-412b-a874-7565c474702d.png)
> And in the settings it's also visible in most text.
> ![Screenshot_20210726_193926](https://user-images.githubusercontent.com/67879877/127034286-f7aff703-e732-4a21-9958-5f9b3e185612.png)

is the text issue improved in the newest commit

2021-07-26 18:41 UTC, pineappleEA commented
No, I'm still experiencing the same issues on the latest commit.

2021-07-26 18:51 UTC, ooa113y commented
Pressing Tab (used to toggle vsync before) crashes the emulator with
```
00:01:13.001 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.Input.KeyboardNavigation.GetIsTabStop(InputElement element)
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext()
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext()
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext()
   at Avalonia.Input.Navigation.TabNavigation.GetFocusableDescendants(IInputElement element, NavigationDirection direction)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at Avalonia.Input.Navigation.TabNavigation.GetNextInTabOrder(IInputElement element, NavigationDirection direction, Boolean outsideElement)
   at Avalonia.Input.KeyboardNavigationHandler.GetNext(IInputElement element, NavigationDirection direction)
   at Avalonia.Input.KeyboardNavigationHandler.Move(IInputElement element, NavigationDirection direction, KeyModifiers keyModifiers)
   at Avalonia.Input.KeyboardNavigationHandler.OnKeyDown(Object sender, KeyEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Ryujinx.Ava.Program.Main(String[] args)
```

Additionally, the recently-implemented Screenshot and Hide UI functions seem to be missing. Would it be on whoever originally created them to reimplement this once Avalonia is merged? If so, I have some work to do soon 😅

2021-07-26 20:19 UTC, GamerzHell9137 commented
-Opening Settings lags a bit
-UI looks way too big
-System version on taskbar text is being cut down a bit 
![image](https://user-images.githubusercontent.com/2002038/127048051-39f769e1-03c5-4578-b010-d5e2cbf48999.png)
-Line under Memory Manager Mode is way too thick/big
-Controllers can't be configured and saved
-Old controller profiles can't be applied nor new can be made
-When resizing the window from the native window size the taskbar and the menus on top are shown half and can be hidden once resizing it to the lowest possible size
-Exiting Fullscreen mode is impossible until you click the screen after going into fullscreen mode
-Pressing ESC while in windowed mode opens the stopping emulation window, if you choose no/or yes the emulator window will be inaccessible and the emulator will crash (a new windows opens in Windows taskbar)
-Clicking the game window makes the window "flash" (Can be seen on title text)
-Changing the aspect ratio from the taskbar is not working

![image](https://user-images.githubusercontent.com/2002038/127052162-095aacf5-0f26-44cc-920a-da35cc2dcc3c.png)

![image](https://user-images.githubusercontent.com/2002038/127047951-651ef67a-5f49-4321-ab09-1fa55b6460d6.png)

2021-07-26 20:59 UTC, GamerzHell9137 commented
Gonna edit the old post when stuff gets fixed, gonna reply new stuff when i find them

-Windows screen can be resized more than the minimum that's possible
-Controller once configured can't be used (DS4 controller)

![image](https://user-images.githubusercontent.com/2002038/127057350-ca30fc4f-74fe-412d-8fad-e436b65d48a2.png)

2021-07-26 21:12 UTC, RyzenDew commented
[Ryujinx_1.0.0+c68f2bd_2021-07-26_18-10-00.log](https://github.com/Ryujinx/Ryujinx/files/6881255/Ryujinx_1.0.0%2Bc68f2bd_2021-07-26_18-10-00.log)
2 players Crashes the new GUI

2021-07-26 22:10 UTC, knuxbbs commented
Why get rid of GtkSharp?

2021-07-26 23:42 UTC, RyzenDew commented
[Ryujinx_1.0.0+c68f2bd_2021-07-26_20-37-29.log](https://github.com/Ryujinx/Ryujinx/files/6881716/Ryujinx_1.0.0%2Bc68f2bd_2021-07-26_20-37-29.log)
Crashes on windows 11 but works fine on 10 and this is from just running the program

2021-07-26 23:50 UTC, MutantAura commented
**Gonna be a long one so strap in**
Brief overview of my findings and also **opinions** of this so far. I'll keep this updated with new/old stuff etc.

### BUGS

- Loading a previous GTK controller profile will crash the program. Default is fine.
- Editing input settings **in-game** will cause the emulator to not register any inputs even after saving until the game has been restarted.
- Unsure if it's a bug or a design choice but the window can be resized into shapes that seriously make no sense. See a couple of my favourites here: 
![image](https://user-images.githubusercontent.com/44103205/127069821-f20c1962-c1d3-4fa8-94cb-f3630125a2ff.png)
![image](https://user-images.githubusercontent.com/44103205/127069831-e7d21083-eed3-4d52-a557-671c9438a65f.png)
![image](https://user-images.githubusercontent.com/44103205/127069872-8c45a86d-d221-4d49-bac3-a3ff11a5a549.png)

After a couple of these resizes the game art for a few games became permenantly bugged until a restart: 
![image](https://user-images.githubusercontent.com/44103205/127070156-bf717da8-ca9c-451c-9005-76545b992ed1.png)

- When trying to edit the GUI/tabs in settings you have to click the tickbox and not the text as this does nothing. Very unintuitive and if you click the text the whole tab closes which is frustrating. 
![image](https://user-images.githubusercontent.com/44103205/127070669-a8049156-34f5-403f-8d4b-f575b3eb6fd8.png)



Now we get onto the good stuff... My personal opinion and some aesthetic choices.
### AESTHETICS 

- I personally feel everything is just _too big_ like a setting for people with poorer vision has been enabled. The font sizes overall are unbalanced with game titles being frankly enormous. In windowed mode especially it's quite overwhelming compared to the subtle sleeker view of the old UI.
- Game art feels off too. Large gaps between the games and most not filling the column they are bound too looks odd in comparison to old UI and compared to the massive text the icon looks small.
- On that same vein I'm wondering if the "icon" header is even needed in all honesty. Combining the Icon and application tabs would make a much more streamlined panel in my view as it's needlessly separating things and adding general clutter to the screen. Disabling the Icon column looks much better in my eyes but I'd still like the icon to be there. "Application" should always be the first column. 
![image](https://user-images.githubusercontent.com/44103205/127070550-f74bf415-36df-4638-bf75-308fbf7bdac2.png)

- As has already been noted the line separating settings is very thick and off-putting. 
![image](https://user-images.githubusercontent.com/44103205/127070776-8721641f-657c-41d9-9232-8efb787220f5.png)

- The tickboxes in general have a very strange colour scheme which makes them hardly visible. Just a filled blue box would work better in my opinion or make the tick more pronounced somehow.
![image](https://user-images.githubusercontent.com/44103205/127070951-d66192eb-c264-49a3-80fa-3f371e93f916.png)

- **Sections of settings** aren't very well separated. It's very hard to tell exactly what is a new section. Compare Avalonia here to a small section from both Dolphin and Yuzu.

AV: 
![image](https://user-images.githubusercontent.com/44103205/127071185-169538ca-0994-48aa-aed0-fcc3bec60848.png)

Dolphin: 
![image](https://user-images.githubusercontent.com/44103205/127071203-7b56a07f-9f7f-4e5c-8dc5-cd1100a9d13d.png)

Yuzu: 
![image](https://user-images.githubusercontent.com/44103205/127071227-f045f6b1-7341-4e76-9da3-bce3cd281df4.png)

Ignoring the other two's use of subtabs as there honestly aren't enough settings here to bother the universal "this is a section" seems to be a small box around settings of value which I feel like Ryu is missing. It's difficult to tell where "Core" ends and "Hacks" start because it doesn't follow this standard. 

- Input is gonna get it's own section :)


### THE INPUT MENU

- The window is not resizable which is odd given the levels of customisation available for the main window.
- Text is frequently too large for boxes and misalligned. (See images)
![image](https://user-images.githubusercontent.com/44103205/127071476-60a2145c-fc19-4939-aca0-0347ae23f308.png)
![image](https://user-images.githubusercontent.com/44103205/127071487-14019adc-ec8c-4efa-969d-f4631721b6a1.png)
![image](https://user-images.githubusercontent.com/44103205/127071502-e9cff5fc-3e99-4152-9e85-c759873a1ce1.png)
![image](https://user-images.githubusercontent.com/44103205/127071512-c2807fe6-3239-4c27-8a69-b744b5c2b039.png)

- The controller profile section in my opinion is now very unintuitive with the new "icon" style options. I was unsure of what they were before I hovered over them and even now I don't see the connection on some of them. 
![image](https://user-images.githubusercontent.com/44103205/127071640-fddb994b-a32c-4a80-b2a6-1dc768a6d8bd.png)
The "load" profile is a particular offender for me personally and the order seems wrong. "Load" and "Save" should intuitively be next to each other and I assumed the "+" was save but that means "add". I'm still unsure of why both Save and Add are needed when surely they could functionaly do the same thing if a profile with X name didn't already exist?

- The image for each controller works _OK_ for the joycons but is far too small and squashed for the pro controller. The colours again also blend together which makes viewing it very difficult. This combined with the non resizable window is kinda a pain.
![image](https://user-images.githubusercontent.com/44103205/127071821-1903ed84-57af-4a37-9170-c1ee7b690268.png)

- Ok so this one is entirely subjective and it's very much a snowball from some of the other choices that have been made. The Input UI to me looks messy, convoluted and overall quite confusing. I'll use Dolphin and Yuzu once more as an example of what I consider great input UI to look like.

Ava: 
![image](https://user-images.githubusercontent.com/44103205/127072139-b442e685-8430-42a9-94de-e99de9bc5ea5.png)

Dolphin: 
![image](https://user-images.githubusercontent.com/44103205/127072153-e96d0331-b729-4dea-986e-d854e85d5384.png)

Yuzu: 
![image](https://user-images.githubusercontent.com/44103205/127072161-d01097c6-838e-4b36-897e-fa7f4ab5a07b.png)

Once again there are a few key thing's I feel to take away from outright head2head comparison here.

1. The controller image should be the centre of the show and not a small side image that _just about_ lines up with the mapping areas.
2. The text again as a symptom of the rest of the UI is much too large and takes up far too much space on the screen.
3. Combining a reduced text size, use of boxed settings areas and making the image centre stage and larger gives us a good final product. Allow the UI to be more free flowing around the controller itself. Right now it's very much "left column of settings" and "right column of settings" that are meant to just about match with the image. 

Instead of just saying this I've done a pretty rushed photoshop of the kind of thing I'm talking about. (VERY SCUFFED SORRY)
![image](https://user-images.githubusercontent.com/44103205/127073404-879a97fa-bb44-4f3a-96b3-9e0d901e66b8.png)

Of course I'm not a UI designer and I have no idea how this would work in the actual code but to me it's certainly not weak or a failure to take some inspiration from other emulators that no doubt the target audience have used in the past etc. The photoshop was quick and simple and didnt even change any text sizes etc but to my eye already looks far more intuative.

That was way longer than I intended it to be PHEW!

2021-07-26 23:59 UTC, RyzenDew commented
So another issue is i can't setup a new ryujinx install so no popup about key it just crashes

2021-07-27 08:22 UTC, emmauss commented
> **Gonna be a long one so strap in**
> Brief overview of my findings and also **opinions** of this so far. I'll keep this updated with new/old stuff etc.
> ### BUGS
> 
>     * Loading a previous GTK controller profile will crash the program. Default is fine.
> 
>     * Editing input settings **in-game** will cause the emulator to not register any inputs even after saving until the game has been restarted.
> 
>     * Unsure if it's a bug or a design choice but the window can be resized into shapes that seriously make no sense. See a couple of my favourites here:
>       ![image](https://user-images.githubusercontent.com/44103205/127069821-f20c1962-c1d3-4fa8-94cb-f3630125a2ff.png)
>       ![image](https://user-images.githubusercontent.com/44103205/127069831-e7d21083-eed3-4d52-a557-671c9438a65f.png)
>       ![image](https://user-images.githubusercontent.com/44103205/127069872-8c45a86d-d221-4d49-bac3-a3ff11a5a549.png)
> 
> 
> After a couple of these resizes the game art for a few games became permenantly bugged until a restart:
> ![image](https://user-images.githubusercontent.com/44103205/127070156-bf717da8-ca9c-451c-9005-76545b992ed1.png)
> 
>     * When trying to edit the GUI/tabs in settings you have to click the tickbox and not the text as this does nothing. Very unintuitive and if you click the text the whole tab closes which is frustrating.
>       ![image](https://user-images.githubusercontent.com/44103205/127070669-a8049156-34f5-403f-8d4b-f575b3eb6fd8.png)
> 
> 
> Now we get onto the good stuff... My personal opinion and some aesthetic choices.
> ### AESTHETICS
> 
>     * I personally feel everything is just _too big_ like a setting for people with poorer vision has been enabled. The font sizes overall are unbalanced with game titles being frankly enormous. In windowed mode especially it's quite overwhelming compared to the subtle sleeker view of the old UI.
> 
>     * Game art feels off too. Large gaps between the games and most not filling the column they are bound too looks odd in comparison to old UI and compared to the massive text the icon looks small.
> 
>     * On that same vein I'm wondering if the "icon" header is even needed in all honesty. Combining the Icon and application tabs would make a much more streamlined panel in my view as it's needlessly separating things and adding general clutter to the screen. Disabling the Icon column looks much better in my eyes but I'd still like the icon to be there. "Application" should always be the first column.
>       ![image](https://user-images.githubusercontent.com/44103205/127070550-f74bf415-36df-4638-bf75-308fbf7bdac2.png)
> 
>     * As has already been noted the line separating settings is very thick and off-putting.
>       ![image](https://user-images.githubusercontent.com/44103205/127070776-8721641f-657c-41d9-9232-8efb787220f5.png)
> 
>     * The tickboxes in general have a very strange colour scheme which makes them hardly visible. Just a filled blue box would work better in my opinion or make the tick more pronounced somehow.
>       ![image](https://user-images.githubusercontent.com/44103205/127070951-d66192eb-c264-49a3-80fa-3f371e93f916.png)
> 
>     * **Sections of settings** aren't very well separated. It's very hard to tell exactly what is a new section. Compare Avalonia here to a small section from both Dolphin and Yuzu.
> 
> 
> AV:
> ![image](https://user-images.githubusercontent.com/44103205/127071185-169538ca-0994-48aa-aed0-fcc3bec60848.png)
> 
> Dolphin:
> ![image](https://user-images.githubusercontent.com/44103205/127071203-7b56a07f-9f7f-4e5c-8dc5-cd1100a9d13d.png)
> 
> Yuzu:
> ![image](https://user-images.githubusercontent.com/44103205/127071227-f045f6b1-7341-4e76-9da3-bce3cd281df4.png)
> 
> Ignoring the other two's use of subtabs as there honestly aren't enough settings here to bother the universal "this is a section" seems to be a small box around settings of value which I feel like Ryu is missing. It's difficult to tell where "Core" ends and "Hacks" start because it doesn't follow this standard.
> 
>     * Input is gonna get it's own section :)
> 
> 
> ### THE INPUT MENU
> 
>     * The window is not resizable which is odd given the levels of customisation available for the main window.
> 
>     * Text is frequently too large for boxes and misalligned. (See images)
>       ![image](https://user-images.githubusercontent.com/44103205/127071476-60a2145c-fc19-4939-aca0-0347ae23f308.png)
>       ![image](https://user-images.githubusercontent.com/44103205/127071487-14019adc-ec8c-4efa-969d-f4631721b6a1.png)
>       ![image](https://user-images.githubusercontent.com/44103205/127071502-e9cff5fc-3e99-4152-9e85-c759873a1ce1.png)
>       ![image](https://user-images.githubusercontent.com/44103205/127071512-c2807fe6-3239-4c27-8a69-b744b5c2b039.png)
> 
>     * The controller profile section in my opinion is now very unintuitive with the new "icon" style options. I was unsure of what they were before I hovered over them and even now I don't see the connection on some of them.
>       ![image](https://user-images.githubusercontent.com/44103205/127071640-fddb994b-a32c-4a80-b2a6-1dc768a6d8bd.png)
>       The "load" profile is a particular offender for me personally and the order seems wrong. "Load" and "Save" should intuitively be next to each other and I assumed the "+" was save but that means "add". I'm still unsure of why both Save and Add are needed when surely they could functionaly do the same thing if a profile with X name didn't already exist?
> 
>     * The image for each controller works _OK_ for the joycons but is far too small and squashed for the pro controller. The colours again also blend together which makes viewing it very difficult. This combined with the non resizable window is kinda a pain.
>       ![image](https://user-images.githubusercontent.com/44103205/127071821-1903ed84-57af-4a37-9170-c1ee7b690268.png)
> 
>     * Ok so this one is entirely subjective and it's very much a snowball from some of the other choices that have been made. The Input UI to me looks messy, convoluted and overall quite confusing. I'll use Dolphin and Yuzu once more as an example of what I consider great input UI to look like.
> 
> 
> Ava:
> ![image](https://user-images.githubusercontent.com/44103205/127072139-b442e685-8430-42a9-94de-e99de9bc5ea5.png)
> 
> Dolphin:
> ![image](https://user-images.githubusercontent.com/44103205/127072153-e96d0331-b729-4dea-986e-d854e85d5384.png)
> 
> Yuzu:
> ![image](https://user-images.githubusercontent.com/44103205/127072161-d01097c6-838e-4b36-897e-fa7f4ab5a07b.png)
> 
> Once again there are a few key thing's I feel to take away from outright head2head comparison here.
> 
>     1. The controller image should be the centre of the show and not a small side image that _just about_ lines up with the mapping areas.
> 
>     2. The text again as a symptom of the rest of the UI is much too large and takes up far too much space on the screen.
> 
>     3. Combining a reduced text size, use of boxed settings areas and making the image centre stage and larger gives us a good final product. Allow the UI to be more free flowing around the controller itself. Right now it's very much "left column of settings" and "right column of settings" that are meant to just about match with the image.
> 
> 
> Instead of just saying this I've done a pretty rushed photoshop of the kind of thing I'm talking about. (VERY SCUFFED SORRY)
> ![image](https://user-images.githubusercontent.com/44103205/127073404-879a97fa-bb44-4f3a-96b3-9e0d901e66b8.png)
> 
> Of course I'm not a UI designer and I have no idea how this would work in the actual code but to me it's certainly not weak or a failure to take some inspiration from other emulators that no doubt the target audience have used in the past etc. The photoshop was quick and simple and didnt even change any text sizes etc but to my eye already looks far more intuative.
> 
> That was way longer than I intended it to be PHEW!

 Nothing I can do [...]

2021-07-27 10:15 UTC, Niwu34 commented
I agree to the the notes that Mutant did  to the Controller input Layout!
The way it is now is causing claustrophobia for me!

I personally like mapping my inputs clockwise a-b-x-y, right stick, etc.. Doing this with the New UI is really hard for the Eyes to keep the overview...

Having the different sections like Mutant showed (or Yuzu uses) is just way more pleasing and user friendly!
Having something like that in combination with this Issue would be great:
https://github.com/Ryujinx/Ryujinx/issues/1568#issue-706496618

2021-07-27 10:42 UTC, MutantAura commented
> I don't know what you mean by the input ui is convoluted or messy. Dolphins got way less input configurations to support, and Yuzu just has more options. I don't mind increasing the controller image, or letting it grow with the window, but I don't think your mockup is more optimal.

Maybe I used wording that was too strong last night. I don't think I'd call it "messy" so much as unintuitive. It requires you to look around first to see what things do rather than, as most programs have achieved, it being completely obvious and I could likely map without labels. My main issue is that everything in the new input UI is "connected" in columns and nothing has any space to breathe. Moving these UI elements away from each other into almost a second visualisation of the controller to me just *looks* better and I can't explain that without subjectivity. Given how the main UI is now also a much darker colour the Pro Controller image would also need an update and I feel like it would be a great time have a real talk about Input UI in general seeing as it's likely the setting that users look at most.

What Niwu said is also true. Clockwise mapping is such a staple in emulators, input display programs etc that people almost expect emulators to have this cyclic UI scheme where you travel around the controller. Whether it be automatic is likely out of the scope of the initial PR but taking steps to make sure it isn't a complete overhaul now could be useful.

I'll wait for more people to weigh in on this particular topic and perhaps try and see what people think in #interface-development. As I say most of my arguments are coming purely from subjectivity so this is just my opinions :)

2021-07-27 10:49 UTC, GamerzHell9137 commented
The minimum size thing was not fixed or its not acting like GTK is.
![image](https://user-images.githubusercontent.com/2002038/127141303-dfde205d-b17a-4c93-bfd0-aa510e1d5449.png)
At certain resizes the taskbar and the menu's are half showing (disappear the more you resize it down) which shouldn't be the case
![image](https://user-images.githubusercontent.com/2002038/127141378-9ce9a54c-8298-4e0c-8438-60993e9f96cd.png)

If we're following more rules of GTK build the system version should be visible once in game. The taskbar preferebly should be hidden in Avalonia build while the shaders and pptc are building and show after they are built (like GDK does).

So, min game size 1280x720, min emulator size 1280x795 with taskbar and menubar not disappearing/shrinking (If GDK rules we're following)
![image](https://user-images.githubusercontent.com/2002038/127141920-ef1414ae-cfb0-43c1-8507-487320c5fe53.png)

2021-07-27 11:52 UTC, Leischii commented
> 
> 
> > I don't know what you mean by the input ui is convoluted or messy. Dolphins got way less input configurations to support, and Yuzu just has more options. I don't mind increasing the controller image, or letting it grow with the window, but I don't think your mockup is more optimal.
> 
> Maybe I used wording that was too strong last night. I don't think I'd call it "messy" so much as unintuitive. It requires you to look around first to see what things do rather than, as most programs have achieved, it being completely obvious and I could likely map without labels. My main issue is that everything in the new input UI is "connected" in columns and nothing has any space to breathe. Moving these UI elements away from each other into almost a second visualisation of the controller to me just _looks_ better and I can't explain that without subjectivity. Given how the main UI is now also a much darker colour the Pro Controller image would also need an update and I feel like it would be a great time have a real talk about Input UI in general seeing as it's likely the setting that users look at most.
> 
> What Niwu said is also true. Clockwise mapping is such a staple in emulators, input display programs etc that people almost expect emulators to have this cyclic UI scheme where you travel around the controller. Whether it be automatic is likely out of the scope of the initial PR but taking steps to make sure it isn't a complete overhaul now could be useful.
> 
> I'll wait for more people to weigh in on this particular topic and perhaps try and see what people think in #interface-development. As I say most of my arguments are coming purely from subjectivity so this is just my opinions :)

I also agree that this input layout change in the mockup looks more clear and less stuffed. Really had a hard time finding specific buttons when I first looked at the current ava layout. I think that's due to all input boxes being right underneat the next. A little gap between the different input boxes might already be able do the trick too.

2021-07-27 12:43 UTC, Niwu34 commented
The Controller will not be usable as soon as you strart the game and open the Menu.
Buttons are still mappable but no input is not recognised by the game.

2021-07-27 13:45 UTC, Niwu34 commented
Using the settings ingame doesn't block the controls - thx for the quick fix
I have a rather subjective request:
![Screenshot 2021-07-27 154328](https://user-images.githubusercontent.com/67392333/127164739-2bbfab5b-1252-4482-8989-9b404f8f5d3e.png)
I think that it makes more sense to put the input settings here - but as i said... rather subjective

2021-07-27 14:24 UTC, GamerzHell9137 commented
-Pressing Save in input options before pressing Apply crashes the emulator
-Controller setup doesn't show for controller until a game is loaded up (Acts like Disabled)
-Anistropic filtering can be saved up to x8 and not x16. Choosing x8 saves as x4, x4 as x2 etc.
![image](https://user-images.githubusercontent.com/2002038/127170699-7814f90f-4538-45c4-ab19-9565966eb389.png)

2021-07-27 14:29 UTC, GamerzHell9137 commented
-Opening Settings lags a bit (Compared to GTK)
-UI looks way too big
-Exiting Fullscreen mode is impossible until you click the screen after going into fullscreen mode
-Game window is still not acting like an active window (Clicking on the emulator UI makes the emulator active)
-Escaping with ESC doesn't work at all now

2021-07-27 14:39 UTC, emmauss commented
> Merged the old issues with new one's that i've found
> 
> -Pressing Save in input options before pressing Apply crashes the emulator
> -Controller setup doesn't show for controller until a game is loaded up (Acts like Disabled)
> -Anistropic filtering can be saved up to x8 and not x16. Choosing x8 saves as x4, x4 as x2 etc.
> -Opening Settings lags a bit (Compared to GTK)
> -UI looks way too big
> -Exiting Fullscreen mode is impossible until you click the screen after going into fullscreen mode
> -Game window is still not acting like an active window (Clicking on the emulator UI makes the emulator active)
> -Escaping with ESC doesn't work at all now

Whats the error for the save and apply crash? Pressing Save should immediately close the window, before you can press Apply

2021-07-27 14:42 UTC, GamerzHell9137 commented
> 
> 
> > Merged the old issues with new one's that i've found
> > -Pressing Save in input options before pressing Apply crashes the emulator
> > -Controller setup doesn't show for controller until a game is loaded up (Acts like Disabled)
> > -Anistropic filtering can be saved up to x8 and not x16. Choosing x8 saves as x4, x4 as x2 etc.
> > -Opening Settings lags a bit (Compared to GTK)
> > -UI looks way too big
> > -Exiting Fullscreen mode is impossible until you click the screen after going into fullscreen mode
> > -Game window is still not acting like an active window (Clicking on the emulator UI makes the emulator active)
> > -Escaping with ESC doesn't work at all now
> 
> Whats the error for the save and apply crash? Pressing Save should immediately close the window, before you can press Apply
Swapped from controller to disabled and pressed Save instead of Apply

```00:00:36.533 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ava.Ui.ViewModels.ControllerSettingsViewModel.Save()
   at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveSettings()
   at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveButton_Clicked(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Ryujinx.Ava.Program.Main(String[] args)
```

2021-07-27 15:38 UTC, emmauss commented
> > > Merged the old issues with new one's that i've found
> > > -Pressing Save in input options before pressing Apply crashes the emulator
> > > -Controller setup doesn't show for controller until a game is loaded up (Acts like Disabled)
> > > -Anistropic filtering can be saved up to x8 and not x16. Choosing x8 saves as x4, x4 as x2 etc.
> > > -Opening Settings lags a bit (Compared to GTK)
> > > -UI looks way too big
> > > -Exiting Fullscreen mode is impossible until you click the screen after going into fullscreen mode
> > > -Game window is still not acting like an active window (Clicking on the emulator UI makes the emulator active)
> > > -Escaping with ESC doesn't work at all now
> > 
> > 
> > Whats the error for the save and apply crash? Pressing Save should immediately close the window, before you can press Apply
> 
> Swapped from controller to disabled and pressed Save instead of Apply
> 
> ```
> 
> 00:00:36.533 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
>    at Ryujinx.Ava.Ui.ViewModels.ControllerSettingsViewModel.Save()
>    at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveSettings()
>    at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveButton_Clicked(Object sender, RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
>    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
>    at Avalonia.Controls.Button.OnClick()
>    at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
>    at System.Reactive.Subjects.Subject`1.OnNext(T value)
>    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
>    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
>    at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
>    at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
>    at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
>    at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
>    at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
>    at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
>    at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
>    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
>    at Ryujinx.Ava.Program.Main(String[] args)
> ```

Could you test now?

2021-07-27 16:09 UTC, GamerzHell9137 commented
> 
> 
> > > > Merged the old issues with new one's that i've found
> > > > -Pressing Save in input options before pressing Apply crashes the emulator
> > > > -Controller setup doesn't show for controller until a game is loaded up (Acts like Disabled)
> > > > -Anistropic filtering can be saved up to x8 and not x16. Choosing x8 saves as x4, x4 as x2 etc.
> > > > -Opening Settings lags a bit (Compared to GTK)
> > > > -UI looks way too big
> > > > -Exiting Fullscreen mode is impossible until you click the screen after going into fullscreen mode
> > > > -Game window is still not acting like an active window (Clicking on the emulator UI makes the emulator active)
> > > > -Escaping with ESC doesn't work at all now
> > > 
> > > 
> > > Whats the error for the save and apply crash? Pressing Save should immediately close the window, before you can press Apply
> > 
> > 
> > Swapped from controller to disabled and pressed Save instead of Apply
> > ```
> > 
> > 00:00:36.533 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
> >    at Ryujinx.Ava.Ui.ViewModels.ControllerSettingsViewModel.Save()
> >    at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveSettings()
> >    at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveButton_Clicked(Object sender, RoutedEventArgs e)
> >    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
> >    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
> >    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
> >    at Avalonia.Controls.Button.OnClick()
> >    at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
> >    at System.Reactive.Subjects.Subject`1.OnNext(T value)
> >    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
> >    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
> >    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
> >    at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
> >    at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
> >    at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
> >    at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
> >    at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
> >    at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
> >    at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
> >    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
> >    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
> >    at Ryujinx.Ava.Program.Main(String[] args)
> > ```
> 
> Could you test now?

Works fine now. Another issue that i found is when you connect a controller after opening Ryujinx and choose the controller the Input Device changes to empty (Can be seen in the input device list tho) 
![image](https://user-images.githubusercontent.com/2002038/127188851-7dfa6a46-f03b-4454-a24a-b0f8bb8630bc.png)
![image](https://user-images.githubusercontent.com/2002038/127188818-834a99d5-e1ed-4a7f-8d38-f3d43760ee54.png)

2021-07-27 16:14 UTC, GamerzHell9137 commented
Seems like even after closing and opening again the emulator, the emulator is crashing when you go into input settings and trying to Apply or Save the controller. Think the error is save as from the last post but just to be sure gonna post it again.

```

00:00:10.041 |E| Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Ava.Ui.ViewModels.ControllerSettingsViewModel.Save()
   at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveSettings()
   at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveButton_Clicked(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
   at System.Reactive.Subjects.Subject`1.OnNext(T value)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Ryujinx.Ava.Program.Main(String[] args)

```

2021-07-27 16:16 UTC, GamerzHell9137 commented
Where are the Avalonia settings saved by the way? Can't use the emulator at all and the config file is not the same as in the Ryujinx folder.

2021-07-27 16:21 UTC, RyzenDew commented
![done](https://user-images.githubusercontent.com/84041391/127190612-4ac95c03-1afe-44e5-8bbe-71bedba61e38.png)
just a simple redesign clean and aligned 

* input device needs be longer 
* player box could be as well to fill in the top bits
* when motion is enabled it has room to expand

2021-07-27 16:26 UTC, MutantAura commented
> ![Untitled-2](https://user-images.githubusercontent.com/84041391/127191360-ddd9fd1e-b117-48df-94be-62b295917410.png)
> 
> just a simple redesign clean and aligned
> 
> * input device needs be longer
> * player box could be as well to fill in the top bits
> * when motion is enabled it has room to expand

We've been brainstorming some designs on discord if you wanted to have some input. The most liked one so far is here: 
![image](https://user-images.githubusercontent.com/44103205/127191441-afd22097-65b1-4176-8137-83c83bff896f.png)

However feel free to join a more general discourse there.

2021-07-27 16:27 UTC, RyzenDew commented
> > ![Untitled-2](https://user-images.githubusercontent.com/84041391/127191360-ddd9fd1e-b117-48df-94be-62b295917410.png)
> > just a simple redesign clean and aligned
> > 
> > * input device needs be longer
> > * player box could be as well to fill in the top bits
> > * when motion is enabled it has room to expand
> 
> We've been brainstorming some designs on discord if you wanted to have some input. The most liked one so far is here:
> ![image](https://user-images.githubusercontent.com/44103205/127191441-afd22097-65b1-4176-8137-83c83bff896f.png)
> 
> However feel free to join a more general discourse there.

it's not as clean looking but it looks good

2021-07-27 16:33 UTC, GamerzHell9137 commented
-When closing Ryujinx trough X on upper right side is says the wrong message.
Its supposed to be
![image](https://user-images.githubusercontent.com/2002038/127192585-cf54a182-159e-4a59-add1-61b43a0da51a.png)

2021-07-27 16:43 UTC, emmauss commented
> Where are the Avalonia settings saved by the way? Can't use the emulator and the config file is not the same as the GTK config file.

The config files should be in the same directory as the application, or the Ryujinx appdata folder. The config files can be used for both apps

2021-07-27 16:45 UTC, emmauss commented
> > > > > Merged the old issues with new one's that i've found
> > > > > -Pressing Save in input options before pressing Apply crashes the emulator
> > > > > -Controller setup doesn't show for controller until a game is loaded up (Acts like Disabled)
> > > > > -Anistropic filtering can be saved up to x8 and not x16. Choosing x8 saves as x4, x4 as x2 etc.
> > > > > -Opening Settings lags a bit (Compared to GTK)
> > > > > -UI looks way too big
> > > > > -Exiting Fullscreen mode is impossible until you click the screen after going into fullscreen mode
> > > > > -Game window is still not acting like an active window (Clicking on the emulator UI makes the emulator active)
> > > > > -Escaping with ESC doesn't work at all now
> > > > 
> > > > 
> > > > Whats the error for the save and apply crash? Pressing Save should immediately close the window, before you can press Apply
> > > 
> > > 
> > > Swapped from controller to disabled and pressed Save instead of Apply
> > > ```
> > > 
> > > 00:00:36.533 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
> > >    at Ryujinx.Ava.Ui.ViewModels.ControllerSettingsViewModel.Save()
> > >    at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveSettings()
> > >    at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveButton_Clicked(Object sender, RoutedEventArgs e)
> > >    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
> > >    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
> > >    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
> > >    at Avalonia.Controls.Button.OnClick()
> > >    at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
> > >    at System.Reactive.Subjects.Subject`1.OnNext(T value)
> > >    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
> > >    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
> > >    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
> > >    at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
> > >    at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
> > >    at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
> > >    at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
> > >    at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
> > >    at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
> > >    at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
> > >    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
> > >    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
> > >    at Ryujinx.Ava.Program.Main(String[] args)
> > > ```
> > 
> > 
> > Could you test now?
> 
> Works fine now. Another issue that i found is when you connect a controller after opening Ryujinx and choose the controller the Input Device changes to empty (Can be seen in the input device list tho)
> 
> If you go into game and go into input settings you can see the controller setup inputs fine but once you hit Apply it crashes the emu. (The controller is not working in game even tho its chosen and the inputs are setup correctly)
> 
> ```
> 00:00:28.343 |E| Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
>    at Ryujinx.Ava.Ui.ViewModels.ControllerSettingsViewModel.Save()
>    at Ryujinx.Ava.Ui.Windows.SettingsWindow.SaveSettings()
>    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
>    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
>    at Avalonia.Controls.Button.OnClick()
>    at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs e)
>    at System.Reactive.Subjects.Subject`1.OnNext(T value)
>    at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e)
>    at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e)
>    at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e)
>    at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties props, KeyModifiers inputModifiers)
>    at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e)
>    at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e)
>    at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
>    at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
>    at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
>    at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
>    at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
>    at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
>    at Ryujinx.Ava.Program.Main(String[] args)
> ```
> 
> ![image](https://user-images.githubusercontent.com/2002038/127188851-7dfa6a46-f03b-4454-a24a-b0f8bb8630bc.png)
> ![image](https://user-images.githubusercontent.com/2002038/127188818-834a99d5-e1ed-4a7f-8d38-f3d43760ee54.png)

This is an issue with avalonia. details can be found here, https://github.com/AvaloniaUI/Avalonia/issues/5571 . No workaround as of now.

2021-07-27 17:18 UTC, emmauss commented
@GamerzHell9137 could you check the latest builds

2021-07-27 17:57 UTC, GamerzHell9137 commented
@emmauss 
Controller is fine. The message when closing the emulator is fixed too.
Game window is still not considered the active window which means ESC (stopping emulation/exiting fullscreen) won't work until you click the emulator window.


https://user-images.githubusercontent.com/2002038/127204042-5311a4a9-2ead-47bb-9ae9-6eef736d6991.mp4


Pressing ESC while in windowed mode shouldn't say that its gonna close the emulator but just that its gonna stop the emulation.
For some reason if you press ESC way too many times to stop the emulation, if you boot a new game again, the window for stopping emulation will pop out and the PPTC/Shader compilation will not scale with the window size.

![image](https://user-images.githubusercontent.com/2002038/127202759-d8cc3db2-bdd8-4609-9e60-2b45acc128dc.png)

Changes to anistropic filtering are not applied during gameplay, it can be changed on master.
Going fullscreen looks like this now, has something to do with Hide UI i think. And with ALT you should be able to disable Hide UI which doesn't work right now.

![image](https://user-images.githubusercontent.com/2002038/127203401-a846b8d6-cd43-4bf3-818f-4451f913ffcb.png)

2021-07-27 18:08 UTC, gdkchan commented
Imo `Alt` is a odd choice to hide the UI, because Alt is usually used to toggle key combos for actions on the menu bar (for example, Alt + F would open the file menu, which allows it to be navigated without a mouse). You'll notice that pressing `Alt` shows a underscore below one of the characters on the menu text, which indicates which key you can press next to open it. Or well, would before this change...

2021-07-27 18:35 UTC, emmauss commented
Alt is used to show the UI or focus on the application's menu, which is a common function of Alt in most windows. it's rare for programs to use Alt nowadays due to this function. Control is used more often for combinations. Even the Alt+Enter hotkey for fullscreen is no longer used on windows.

2021-07-27 18:51 UTC, gdkchan commented
> 
> 
> Alt is used to show the UI or focus on the application's menu, which is a common function of Alt in most windows. it's rare for programs to use Alt nowadays due to this function. Control is used more often for combinations. Even the Alt+Enter hotkey for fullscreen is no longer used on windows.

I tried a few windows programs here (notepad, wordpad, paint etc) and they all have this functionality. Press `Alt` on any of them and you'll see. The only application I currently use where `Alt` is used to show/hide the menu bar is Firefox. But most of it can be used without accessing the menu bar anyway, as it has a separate, more "modern" menu. And even then, `Alt` is still dual purposed on it (pressing `Alt` shows the menu *and* allows the user to open them by pressing another key, on the emulator what happens is the opposite, pressing `Alt` *hides* the UI, at least AFAIK).

2021-07-27 19:30 UTC, GamerzHell9137 commented
The ALT thing for Hide UI is a thing on master right now, dunno what's the best nor i have any suggestions about the hotkeys. I had no issues using ALT to make it appear tho.

2021-07-28 09:41 UTC, MutantAura commented
New UI will take appearance of windows theme (Dark if Dark Light if Light etc.) which is resulting in some less than great user experiences reported on discord. Here is a screenshot of windows in "Light" mode and the avalonia UI: 
![image](https://user-images.githubusercontent.com/44103205/127300844-72a351c8-c8ce-4db3-8567-71a8e52bff64.png)

Should this likely be separated entirely away from an OS theme?

2021-07-28 11:56 UTC, emmauss commented
> New UI will take appearance of windows theme (Dark if Dark Light if Light etc.) which is resulting in some less than great user experiences reported on discord. Here is a screenshot of windows in "Light" mode and the avalonia UI:
> ![image](https://user-images.githubusercontent.com/44103205/127300844-72a351c8-c8ce-4db3-8567-71a8e52bff64.png)
> 
> Should this likely be separated entirely away from an OS theme?

Strange, I'm explicitly requesting the dark theme, and it shows as dark on gnome light theme.

2021-07-28 18:25 UTC, emmauss commented
Dark theme is now enforced

2021-07-28 21:23 UTC, RyzenDew commented
The search box could you add a 1 or 2 px space on the top and bottom that way it does touch the title bar

2021-07-29 09:59 UTC, bylaws commented
It would be nice if a light theme were supported at some point, some people find it easier to read text on them

2021-07-29 13:02 UTC, MutantAura commented
Looking great! Feels much more intuative to look at and map buttons now. Just a few smaller clean-ups.

Default window sizes does this to the trigger bar (Window not large enough, button clips out and overlaps in areas): 
![image](https://user-images.githubusercontent.com/44103205/127495626-3a329155-90af-4443-aa1f-ad56d1a72257.png)

SR and SL persist into the joycon pair and pro controller mappings. Should be replaced with ZR and ZL:
![image](https://user-images.githubusercontent.com/44103205/127495684-3f7b66d3-c548-4f71-b918-2e0a91ba8fa9.png)
![image](https://user-images.githubusercontent.com/44103205/127495720-be67a3b9-be02-4612-b118-def21cdf15a4.png)

Enabling motion requires scrolling for the settings, this isn't awful but I feel when rumble is merged this is also going to be a problem. A slightly increased default vertical size would help greatly here and scrolling would then only be needed for cemuhook motion.

Regular size: 
![image](https://user-images.githubusercontent.com/44103205/127496119-97ed5923-d819-432d-8f8b-8d490723b8c9.png)

Small increase in vertical to the button the motion box: 
![image](https://user-images.githubusercontent.com/44103205/127496194-32e997b8-5bf8-49de-a78e-930d10d13109.png)

Perhaps this is within the rumble PR's scope of interest however and not the initial UI PR, completely up to you.

Motion box isn't properly alligned: 
![image](https://user-images.githubusercontent.com/44103205/127496325-724fb8d8-a095-4ce4-8948-932d612c2a4e.png)

Controller image still feels a tad on the small side? Also doesn't increase with window scaling but that's neither here nor there. 
![image](https://user-images.githubusercontent.com/44103205/127496711-492fe6f8-0807-41c5-a117-71aee3ff89b1.png)

2021-07-29 13:09 UTC, MutantAura commented
As a side note alongside my default window size increase idea I prefer the gap sizes in the original mock ups here: 
![image](https://user-images.githubusercontent.com/44103205/127497612-7e0598c8-eec4-434a-8211-749c72f52251.png)

Wondering if there was a reason for pushing things closer together again or if it was a space concern.

2021-07-29 14:41 UTC, emmauss commented
I'm trying to limit the width of settings window. so I can't add any more margins between columns

2021-07-29 15:44 UTC, RyzenDew commented
![image](https://user-images.githubusercontent.com/84041391/127522977-4b478850-c8f2-4c00-a88c-7a8d50fb6484.png)
Looking much better

2021-07-29 21:56 UTC, AcK77 requested changes
I've made a first review on the design only, this is what I've noticed here and there, I've haven't check Amiibo window and Settings window for now, I'll do it later.

### General UI
- Everything have rounded corners, dropdown menus, combobox, buttons, textboxes (but not all), checkboxes which IMO doesn't looks really nice, the got something which look more modern, we should use squared corners, or at least, reduce the round value. I've already did that but your removed it.
- Buttons doesn't have a min-width size which made "OK" button really small, and "Cancel" button too big. I already added one but you removed it.
- The dark theme is too dark, in a previous commit, I use the same grey as the Switch menu (QLaunch) but you changed it.
- The game list header is too dark too if we compare it to the window background.
- The game list item background should be alternate between two color (with a bit darker/lighter color).
- If the game list is empty, the header should be hidden and show a "Please add a game folder in settings" message centered verticaly and horizontaly.
- The font size seems to be a bit too large. Which made the text with too much AA and a bit unreadable. I already changed that but you removed it.
- The menus have a right margin too low as the top and bottom margin.
- If a menu have a submenu, the submenu is over the parent menu which is wrong.
- Submenus are misaligned to parent content.
  ![GUI1](https://user-images.githubusercontent.com/4905390/127570465-f72ec25c-c071-4e79-9e70-acbd26a0d9ca.png)
- The search textbox have a white border at the bottom, which looks like "3D" border, when other border are flat.
- "System Version" should be "Firmware Version".
- The tick in checkbox should be darked, it near to invisible right now.
- The Favorite column should be hidden as default if there isn't favorite games (maybe).
- The "Options" menu have to be reorganized, maybe Settings should be the first item, idk for the other one but it looks strange for me.
- MessageBox title should start with "Ryujinx" but without the version to make it not too long.
- Some MessageBox looks strange, the text is bold or too big.
- When you double click a game to run it, there is a little white border on the game icon which looks strange.
- It could be nice to add the "Loading" bar until the game draw the first frame.
- When a game is running the status bar text looks is wrong aligned verticaly. (or the status bar height is too large idk).
- When a game is running you can focus the window by clicking in the rendering widget, you have to click on the status bar or the menu.
- When a game is running, the status bar doesn't have any separator. I already added them, but you removed it.
- When you start/stop game, the menubar seems to move up to one pixel, which is strange.
- Checking for an update is available while a game is running, I think we should disable it (it's probaly same in GTK).
- The exit messagebox looks different from some other ones (and looks better with a bit of restyling).
 ![GUI3](https://user-images.githubusercontent.com/4905390/127570550-e7f62ea1-4cce-44b5-abbe-35fdccbc1ce4.png)
- OpenFile dialog doesn't have title, it could be nice to get one (if it's possible with Avalonia).

### User Profiles Window
- The window width is way too large for nothing.
- The "... Profile ..." buttons aren't aligned to the profile list.
  ![GUI2](https://user-images.githubusercontent.com/4905390/127570603-c8d85e9b-1fc2-4788-a4cb-a49b2d664410.png)
- The "Close" button should be at the right of the window (and it's too small as I said above).
- The green color of the selected profile is wrong. Maybe you should use the red color of the Ryujinx logo. I think I already did that but you removed it. See GTK for example:
  ![UserProfile](https://user-images.githubusercontent.com/4905390/127570619-e109795c-df15-43a4-a740-3a478c00401f.png)
- You can click one time on a profile in the list, but it doesn't nothing and shouldn't be enable.
- There is no "Yes/No" messagebox if you delete a user profile.
- If you create a new profile, a textbox to enter the name appear, but the textbox isn't focused.
- The firmware avatar list have too wasted space and there is no selected border, but a selected background.
- The colorpicker for the background doesn't have the Ryujinx icon and a wrong title too.

### About Window
- The social buttons should include the text.
- The patreon names list bottom isn't aligned with the social buttons.
- The patreon names list text start with an empty line.
- The "www.ryujinx.org" and "REE-YOU-JI-NX" should be centered with Ryujinx.
  ![GUI4](https://user-images.githubusercontent.com/4905390/127570645-db9bd577-b1ee-4ab6-8675-c215922d5672.png)
- Some texts spacing aren't consistent.
  ![GUI5](https://user-images.githubusercontent.com/4905390/127570671-0d51ec44-2f80-4733-9529-7490be185956.png)

2021-07-29 22:31 UTC, gdkchan commented
> If a menu have a submenu, the submenu is over the parent menu which is wrong.

This is normal behavior and how it looks on any other UI, unless I'm misunderstanding what you mean here.

2021-07-29 22:57 UTC, AcK77 commented
> > If a menu have a submenu, the submenu is over the parent menu which is wrong.
> 
> This is normal behavior and how it looks on any other UI, unless I'm misunderstanding what you mean here.

True and same for "Submenus are misaligned to parent content.", I made the mistake due to a too large top margin, the rounded corners and no drop shadow.

2021-07-30 23:31 UTC, emmauss commented
a few thoughts on @AcK77 comment

I don't see any issues with rounded corners. The theme is based on fluent design and winui, and most controls come with rounded corners. Rounded corners look better to me.
The dark theme looks fine to me
there is no need for an empty list view telling the user to add a game directory
The font size is reasonably small. it's already 13 units, down from the default 16
Menu margins are ok. it's in line with the fluet theme
submenus are supposed to be over the parent menu.
Submenu being slightly lower than the parent menu item that spawned it is part of the fluent theme.
All textboxes have the white bottom border. it's part of the base theme.
The system version uses the same label as the current ui. I do not want to change it unless it's necessary.
I've been trying to change the check color in the checkbox, no success. will continue.
Without the favorite column, you can set new favorites.
Options menu is the same as current. also, there isn't any need to reorganise. many apps have their settings menuiten at the bottom of the options or edit menu
Which message box has the version in the title?
Which message box in particular have strange fonts?
Will look into the white border when selecting a cell in the game list, but it seems it's something avalonia does by default
As the theme is based on fluent ui, separators are rarely used, and not for items that do not need separators
The menu moving 1px up when starting a game and down when stopping a game is simply due to dockpanel recalculating the dimensions of other docked contols when there is nothing in the center. there is a moment between when the game list is removed and when the renderer is added.
The exit message box is a content dialog, there are limitation with it so it can't be used for some of our custom dialogs now. I'll change the others ina follow up pr
File dialogs can have titles. I'll add it soon.

2021-07-30 23:47 UTC, AcK77 commented
> I don't see any issues with rounded corners. The theme is based on fluent design and winui, and most controls come with rounded corners. Rounded corners look better to me.

This doesn't look better to me. The rounded corner is too big and doesn't looks good at all.

> The dark theme looks fine to me

The dark theme is too dark, as you can see with the ProController icon in the setting menu.

> there is no need for an empty list view telling the user to add a game directory

This is a new GUI, so why don't add new little feature like that?

> The font size is reasonably small. it's already 13 units, down from the default 16

The font size is still larger as the GTK UI, there is too much AA on it and do things less readable.

> Menu margins are ok. it's in line with the fluet theme

Menu margins are wrong, just look at other GUI menus and you will see things are really bad aligned in Avalonia.

> submenus are supposed to be over the parent menu.

True as stated in my previous comment.

> Submenu being slightly lower than the parent menu item that spawned it is part of the fluent theme.

They are too lower as the parent, look at other GUI menus and you will see.

> All textboxes have the white bottom border. it's part of the base theme.

And the base theme can't be edited? Since that make the textboxes design strange.

> The system version uses the same label as the current ui. I do not want to change it unless it's necessary.

I think it's necessary, but it could be nice to get more feedback on that. "System" vs "Firmware".

> Without the favorite column, you can set new favorites.

I said "disabled as default" if you want to use favorites, you can enable the column and it will be saved in the config file.

> Options menu is the same as current. also, there isn't any need to reorganise. many apps have their settings menuiten at the bottom of the options or edit menu

The point of a new GUI is to improve things. The Options menu is a bit bad organized it could be nice to do something on that.

> Which message box has the version in the title?

No ones, but it could be nice to add "Ryujinx" in the title (without the version to avoid long title).

> Which message box in particular have strange fonts?

Some error message, try User Profile and you will see some.

> As the theme is based on fluent ui, separators are rarely used, and not for items that do not need separators

Even if it's part of the theme, the status bar should get some separators to get things more readable, how a new user is supposed to understand you can click on item? With separators it could improve the UX.

> The menu moving 1px up when starting a game and down when stopping a game is simply due to dockpanel recalculating the dimensions of other docked contols when there is nothing in the center. there is a moment between when the game list is removed and when the renderer is added.

I'm pretty sure it doesn't do that while I working a bit a the GUI. So the issue could be fixed somewhere because it looks strange as-is.

> The exit message box is a content dialog, there are limitation with it so it can't be used for some of our custom dialogs now. I'll change the others ina follow up pr

Why another PR if you already change the whole GUI here ?

2021-07-31 03:08 UTC, gdkchan commented
> This doesn't look better to me. The rounded corner is too big and doesn't looks good at all.

It looks fine to me, I prefer rounded corners over square controls in general.

> The dark theme is too dark, as you can see with the ProController icon in the setting menu.

The color is fine to me, but I agree that the pro-controller blending with the background is an issue. I guess one of them needs to have their color adjusted.

> This is a new GUI, so why don't add new little feature like that?

Interesting idea, I would develop it further and add a first time setup dialog that asks for keys, firmware, game folder etc (skippable, of course).

> The font size is still larger as the GTK UI, there is too much AA on it and do things less readable.

Font size is fine to me, even though the UI does look bigger in general compared to the old one. Doesn't bother me though (although I do agree that some elements were way too big before, but they seem to have all been adjusted now).

> They are too lower as the parent, look at other GUI menus and you will see.

I don't see anything wrong with it being slightly lower tbh. It seems to be a style choice rather than a bug.

> And the base theme can't be edited? Since that make the textboxes design strange.

Looks fine to me with the bottom border. It's a bit like Android UI.

> I think it's necessary, but it could be nice to get more feedback on that. "System" vs "Firmware".

Personally I prefer firmware since that's how its called across the code too, but I don't mind "System".

> I said "disabled as default" if you want to use favorites, you can enable the column and it will be saved in the config file.

Imo it's better to have it enabled by default, it's a useful feature and I use it to keep games I test often at the top of the list.

> No ones, but it could be nice to add "Ryujinx" in the title (without the version to avoid long title).

Applications usually don't put their names in all the window titles. It is not very useful either, the user can already identify the application it belongs to from the icon (not to mention that it should be obvious what it belong to if it was opened as a result of previous user action).

> Even if it's part of the theme, the status bar should get some separators to get things more readable, how a new user is supposed to understand you can click on item? With separators it could improve the UX.

I agree that something to indicate that some status bar items can be clicked is nice, but I don't think separators would help there?

> I'm pretty sure it doesn't do that while I working a bit a the GUI. So the issue could be fixed somewhere because it looks strange as-is.

Agree that would be nice to fix it.

> Why another PR if you already change the whole GUI here ?

Agree.

2021-08-01 03:52 UTC, jmacato commented
Amazing stuff folks :D

2021-08-02 09:54 UTC, GamerzHell9137 commented
Font is too small now.

![image](https://user-images.githubusercontent.com/2002038/127842525-3421167b-04b7-4bdc-af8a-f057f7b61192.png)

The GTK one is perfect 
![image](https://user-images.githubusercontent.com/2002038/127842741-a7635ed6-a774-41ed-b84f-910636625bf9.png)

2021-08-02 21:21 UTC, emmauss commented
> 
> 
> Amazing stuff folks :D

It would be nice if the combo box issue is fixed.

2021-08-03 11:28 UTC, Z3USI0TA commented
Hi, Perfect, very good!
Do the command line work to you? 
Here its no load the o game and its not work -f and ... only open the GUI.

2021-08-03 18:32 UTC, jmacato commented
> > 
> 
> > 
> 
> > Amazing stuff folks :D
> 
> 
> 
> It would be nice if the combo box issue is fixed.


Can you link to me the issue tracker for it? So i can check with my colleagues

2021-08-03 19:12 UTC, GamerzHell9137 commented
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > Amazing stuff folks :D
> > 
> > 
> > It would be nice if the combo box issue is fixed.
> 
> Can you link to me the issue tracker for it? So i can check with my colleagues

https://github.com/AvaloniaUI/Avalonia/issues/5571

2021-08-05 03:20 UTC, Shahil-Ayato commented
Makes #1699 redundant as Glade would no longer be needed since we’re switching from GTK to Avalonia with this PR

2021-08-09 20:44 UTC, pineappleEA commented
The Misaligned text appears to be fixed on the settings window, but the main window remains as it was in the previous report. I have also noticed that the gap between the "Enhancements" heading and the first option on the graphics tab is smaller than on any other tab, as well as inconsistent gaps with the System Time and Hacks on the System tab.
![Screenshot_20210809_223156](https://user-images.githubusercontent.com/67879877/128771843-38753986-1f54-4dde-8db4-637e909680bc.png)

2021-08-13 09:49 UTC, emmauss commented
Ready for Review

2021-08-13 15:52 UTC, MutantAura commented
Looking overall very good.
Just my final thoughts.

![image](https://user-images.githubusercontent.com/44103205/129385134-25e83d4a-9e6d-4916-a132-03e2b359f8d3.png)
Timezone here if you select it you cannot unselect it by clicking away, you have to click on another option first.
The month feels like it should be centre aligned? Looks very squished considering the size of the box.

Top bar is not a match with GTK and input feels very strange being the final option
![image](https://user-images.githubusercontent.com/44103205/129385342-7cddaa1b-143a-4455-acd0-bd38e1b0291b.png)

Rumble and Motion don't quite fit on the default window panel which I think should be manageable with a few tweaks.
![image](https://user-images.githubusercontent.com/44103205/129385433-3f91f41a-daf0-4eb2-a3c7-2ab654d4db23.png)
See discord mock-up below: 
![image](https://user-images.githubusercontent.com/44103205/129385530-42b397b5-c341-4dca-b743-2dc6481bdb8e.png)

Another issue here is the motion box is still misaligned but I think most liked motion all being in one box anyway so this is probably something that doesn't need to be fixed if the above is implemented.
![image](https://user-images.githubusercontent.com/44103205/129385698-d71dcdb6-aa06-43c6-ba58-e3e4dbc0fbd5.png)

Configure cemuhook is also very squished against its container. Once again probably a combined fix with the first input nag
![image](https://user-images.githubusercontent.com/44103205/129385842-882f2197-ccae-41fb-ba66-3c7090c0c505.png)

Otherwise looking good to me :)

2021-08-13 16:55 UTC, emmauss commented
> Looking overall very good.
> Just my final thoughts.
> 
> ![image](https://user-images.githubusercontent.com/44103205/129385134-25e83d4a-9e6d-4916-a132-03e2b359f8d3.png)
> Timezone here if you select it you cannot unselect it by clicking away, you have to click on another option first. This box also seems **massive** for the info its showing
> The month feels like it should be centre aligned? Looks very squished considering the size of the box.
> 
> Top bar is not a match with GTK and input feels very strange being the final option
> ![image](https://user-images.githubusercontent.com/44103205/129385342-7cddaa1b-143a-4455-acd0-bd38e1b0291b.png)
> ![image](https://user-images.githubusercontent.com/44103205/129386042-eb0f8ae6-0403-4842-8f8c-cd9311fb089f.png)
> 
> Rumble and Motion don't quite fit on the default window panel which I think should be manageable with a few tweaks.
> ![image](https://user-images.githubusercontent.com/44103205/129385433-3f91f41a-daf0-4eb2-a3c7-2ab654d4db23.png)
> See discord mock-up below:
> ![image](https://user-images.githubusercontent.com/44103205/129385530-42b397b5-c341-4dca-b743-2dc6481bdb8e.png)
> 
> Another issue here is the motion box is still misaligned but I think most liked motion all being in one box anyway so this is probably something that doesn't need to be fixed if the above is implemented.
> ![image](https://user-images.githubusercontent.com/44103205/129385698-d71dcdb6-aa06-43c6-ba58-e3e4dbc0fbd5.png)
> 
> Configure cemuhook is also very squished against its container. Once again probably a combined fix with the first input nag
> ![image](https://user-images.githubusercontent.com/44103205/129385842-882f2197-ccae-41fb-ba66-3c7090c0c505.png)
> 
> Otherwise looking good to me :)
The input being sticky until you click another input control is just how avalonia handles input focus. Nothing I can do about that.

The timezone box is large in order to accommodate the longest timezone name in the list. Textbox do not grow with content.

The Misc box with the motion toggle is separate from the motion box because the motion box is hidden when motion is disabled, so the toggle need to be always visible and outside. 

I'll work on the rest a bit later today

2021-08-13 18:33 UTC, GamerzHell9137 commented
I'm still for a bigger font in settings like its on gtk. Its for us 4 eyed people.

2021-08-14 23:29 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                    <Slider
```suggestion
                                    <Slider
                                        Margin="0,-10,0,-5"                  
```

2021-08-14 23:47 UTC, MutantAura reviewed
Assumed this was the best way to show my personal tweaks?

This is the final product of such edits: 
![image](https://user-images.githubusercontent.com/44103205/129462776-51361273-06f9-4362-8ae4-8c5ed3737e77.png)

Probably quite messy. Lots of margin work was manual so I assume clean up would be required in any case.

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                    <Slider
```suggestion
                                    <Slider
                                        Margin="0,-10,0,-5"
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                        <Slider
```suggestion
                        <Slider
                            Margin="0,-5,0,-5"
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                        <Slider
```suggestion
                        <Slider
                            Margin="0,-5,0,-5"
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                    <Slider
```suggestion
                                    <Slider
                                        Margin="0,-10,0,-5"
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                              <TextBlock Text="{locale:Locale ControllerSettingsMotion}" />
```suggestion
                              <TextBlock
                                  Text="{locale:Locale ControllerSettingsMotion}"
                                  Margin="0" />
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                  Margin="0,1"
```suggestion
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                    <TextBlock
```suggestion
                                    <TextBlock
                                        Margin="0,0,20,0"
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                    <Slider
```suggestion
                                    <Slider
                                        Margin="0,-5,0,-5"
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                    <Slider
```suggestion
                                    <Slider
                                        Margin="0,-5,0,-5"
```

2021-08-14 23:47 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                <Button Margin="5,5" HorizontalAlignment="Center"
```suggestion
                                <Separator Margin="-16,0" />
                                <Button Margin="0,8,0,0" HorizontalAlignment="Center"
```

2021-08-19 11:18 UTC, codbugpatrol commented
Congrats @emmauss , amazing job!
Love the light theme. 
Only one issue found:

![image](https://user-images.githubusercontent.com/85196112/130059137-5070d4ff-6348-476c-a5e1-22485ef729cd.png)

One question is regarding the path. A have a reference folder created with mklink in windows ( Y:\Games\Switch )
which points out to a folder in M:\Nintendo Switch\Games. In Avalania UI it is showing the end path, not the reference path. 
![image](https://user-images.githubusercontent.com/85196112/130059269-13ae2252-c298-4838-a3ef-982b6003105c.png)

Mainline shows the reference path:
![image](https://user-images.githubusercontent.com/85196112/130059729-b251663e-3128-4751-8099-f861600dcdd3.png)

I think this is a bug, because it is not holding the reference path.
Other then this, I find everything great.

2021-08-20 07:54 UTC, emmauss commented
> Congrats @emmauss , amazing job!
> Love the light theme.
> Only one issue found:
> 
> One question is regarding the path. I have a reference folder created with mklink in windows ( Y:\Games\Switch )
> which points out to a folder in M:\Nintendo Switch\Games. In Avalania UI it is showing the end path, not the reference path.
> ![image](https://user-images.githubusercontent.com/85196112/130059269-13ae2252-c298-4838-a3ef-982b6003105c.png)
> 
> Mainline shows the reference path:
> ![image](https://user-images.githubusercontent.com/85196112/130059729-b251663e-3128-4751-8099-f861600dcdd3.png)
> 
> I think this is a bug, because it is not holding the reference path.
> Other then this, I find everything great.

I do not understand what you mean by reference path. The folder dialog provides the absolute path to the directory. This is provided directly from the OS, using the OS native folder dialog. So the path should be  accessible. 
Are you not able to access your games with that path?

2021-08-20 12:23 UTC, codbugpatrol commented
> > Congrats @emmauss , amazing job!
> > Love the light theme.
> > Only one issue found:
> > One question is regarding the path. I have a reference folder created with mklink in windows ( Y:\Games\Switch )
> > which points out to a folder in M:\Nintendo Switch\Games. In Avalania UI it is showing the end path, not the reference path.
> > ![image](https://user-images.githubusercontent.com/85196112/130059269-13ae2252-c298-4838-a3ef-982b6003105c.png)
> > Mainline shows the reference path:
> > ![image](https://user-images.githubusercontent.com/85196112/130059729-b251663e-3128-4751-8099-f861600dcdd3.png)
> > I think this is a bug, because it is not holding the reference path.
> > Other then this, I find everything great.
> 
> I do not understand what you mean by reference path. The folder dialog provides the absolute path to the directory. This is provided directly from the OS, using the OS native folder dialog. So the path should be accessible.
> Are you not able to access your games with that path?

@emmauss , I've selected the path 'Y:\Games\Switch', which is a mklink to a folder 'M:\Nintendo Switch\Games'. But instead showing the path I've selected, is showing the path of the mklink origin folder. In mainline this does not happen, there, if I select the 'Y:\Games\Switch' it will show this path, not the origin path of the mklink. Why this is not good ? Because the mklink is supposed to be agnostic of the origin folder, If by any means I change the origin, the path will still be Y:\....

2021-08-20 13:36 UTC, emmauss commented
> > > Congrats @emmauss , amazing job!
> > > Love the light theme.
> > > Only one issue found:
> > > One question is regarding the path. I have a reference folder created with mklink in windows ( Y:\Games\Switch )
> > > which points out to a folder in M:\Nintendo Switch\Games. In Avalania UI it is showing the end path, not the reference path.
> > > ![image](https://user-images.githubusercontent.com/85196112/130059269-13ae2252-c298-4838-a3ef-982b6003105c.png)
> > > Mainline shows the reference path:
> > > ![image](https://user-images.githubusercontent.com/85196112/130059729-b251663e-3128-4751-8099-f861600dcdd3.png)
> > > I think this is a bug, because it is not holding the reference path.
> > > Other then this, I find everything great.
> > 
> > 
> > I do not understand what you mean by reference path. The folder dialog provides the absolute path to the directory. This is provided directly from the OS, using the OS native folder dialog. So the path should be accessible.
> > Are you not able to access your games with that path?
> 
> @emmauss , I've selected the path 'Y:\Games\Switch', which is a mklink to a folder 'M:\Nintendo Switch\Games'. But instead showing the path I've selected, is showing the path of the mklink origin folder. In mainline this does not happen, there, if I select the 'Y:\Games\Switch' it will show this path, not the origin path of the mklink. Why this is not good ? Because the mklink is supposed to be agnostic of the origin folder, If by any means I change the origin, the path will still be Y:....

Unfortunately, it's not a bug, but intentional on avalonia's side.

2021-08-29 02:44 UTC, AcK77 reviewed
I've started to looks a bit at the code, so I post the beginning of my code review. Be sure you are up-to-date to master since there are some little changes done to GTK UI and the Configuration recently.

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/App.axaml.cs
> +
Remove extra empty line

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/App.axaml.cs
> +            catch (Exception)
It could be nice to do something with the exception (maybe log it or something)?

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/App.axaml.cs
> +            Dispatcher.UIThread.InvokeAsync(async () =>
Fix the warning

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/App.axaml.cs
> +                        LocaleManager.Instance["DialogThemeRestartSubMessage"], "Yes", "No", LocaleManager.Instance["DialogRestartRequiredMessage"]);
"Yes" / "No" aren't exist in the locale file?

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/App.axaml.cs
> +            catch (Exception)
It could be nice to do something with the exception (maybe log it or something)?

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/App.axaml.cs
> +            }
Why all this logic is needed? To use the default theme first? Maybe you could do something easier instead of hardcode the array indexes. Plus, you silent an exception if the custom theme parsing failed, maybe you should log the error?

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/AppHost.cs
> +        private void Parent_PointerLeft(object? sender, PointerEventArgs e)
```suggestion
        private void Parent_PointerLeft(object sender, PointerEventArgs e)
```

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/AppHost.cs
> +        private void Parent_PointerEntered(object? sender, PointerEventArgs e)
```suggestion
        private void Parent_PointerEntered(object sender, PointerEventArgs e)
```

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/AppHost.cs
> +        public void Exit()
Why don't call it `Dispose` directly and then use the Dispose method instead of the Exit one ?

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Common/ApplicationData.cs
> +        }
Add a new empty line after

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Input/Avalonia/AvaloniaKeyboard.cs
> +        public void Dispose()
```suggestion
        public void Dispose() { }
```

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Input/Avalonia/AvaloniaKeyboard.cs
> +        public void SetTriggerThreshold(float triggerThreshold)
```suggestion
        public void SetTriggerThreshold(float triggerThreshold) { }
```

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Input/Avalonia/AvaloniaKeyboard.cs
> +        public void Rumble(float lowFrequency, float highFrequency, uint durationMs)
```suggestion
        public void Rumble(float lowFrequency, float highFrequency, uint durationMs) { }
```

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Input/Avalonia/AvaloniaKeyboard.cs
> +        public Vector3 GetMotionData(MotionInputId inputId)
```suggestion
        public Vector3 GetMotionData(MotionInputId inputId) => Vector3.Zero;
```

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Input/Avalonia/AvaloniaKeyboard.cs
> +            JoyconConfigKeyboardStick<ConfigKey> stickConfig)
new line isn't really needed here

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Input/Avalonia/AvaloniaMappingHelper.cs
> +
remove extra empty line

2021-08-29 02:44 UTC, AcK77 commented on Ryujinx.Ava/Program.cs
> +
Remove extra empty line and align the next line with previous ones

2021-08-29 14:26 UTC, emmauss commented on Ryujinx.Ava/App.axaml.cs
> +            }
The styles loaded on a window is determined by the order of the styles set in the App.xaml. It's much easier accessing  default styles by index since the order never changes.
Also, because of the way Avalonia use styles, you must always have a base style as the first style, then any other style being applied according to the order. The styles determine every thing that's visible.
In this case, the default avalonia fluent theme is loaded at 0, then the datagrid fluent theme at 1, and then the fluent v2 styles at 2.  the base dark/light style at 3. and then the custom style if set at 4. 
Lastly, there is an issue with the v2 theme that prevents it from being unloaded once loaded. so I can't change the order of all the styles loaded at runtime

2021-08-29 14:38 UTC, emmauss commented
Rebased. Addressed comments

2021-08-31 12:12 UTC, GamerzHell9137 commented
Here's some feedback for the latest build:

1.  I'd add a line above things on the main menu because it feels like the taskbar and the game list part is getting blended in together
2. The game list item boxes are wider and look worse than GTK's (for 2 pixels)
![image](https://user-images.githubusercontent.com/2002038/131493254-737a901d-4b16-4a10-9cac-2b3ca76657df.png)
3. I'd text align the item boxes of the game list to the left just like its on GTK, looks better.
4. There's no scroll bar for left and right on the game list like GTK has. (Its hidden in GTK until you hover near the end of the gamelist after which you can scroll left and right)
![image](https://user-images.githubusercontent.com/2002038/131493650-e79af3b4-f770-487f-91fe-373d350b9185.png)
7. I'd align the text to left instead of having it in middle, looks better (GTK)
8. The search on gamelist is not activated when you start typing on the keyboard but its forcing you to click on it first
9. The default sizes of the items on gamelist can be resized a bit, they look too big (tho probably just aligning it to the left would fix that)
10. Upper taskbar could be resized too, 38 pixels is too wide for it.
![image](https://user-images.githubusercontent.com/2002038/131497404-7deed1c5-21a1-4b01-8f20-95215a345a98.png)


A simple mockup:
![image](https://user-images.githubusercontent.com/2002038/131497019-e62165ca-ad3a-47af-8766-b15d3278ee61.png)

Why does everything look bigger on Avalonia but the text is too small? Like there's no uniformity in it (In settings)
Someone complained about the rounded corners but i'm fine about it, its just the things being too big compared to GTK and it doesn't make it look better.
![image](https://user-images.githubusercontent.com/2002038/131497729-2b8726d4-fb83-477c-9f8c-f0a04e284f7f.png)

When changing themes the window for restarting the emulator is transparent 
![image](https://user-images.githubusercontent.com/2002038/131498196-aa880b33-5290-412e-8182-80b4e8611f4d.png)
Clicking Save instead of Apply when changing themes looks like this
![image](https://user-images.githubusercontent.com/2002038/131498815-e03db9ef-2441-4cd7-b388-3bb23e3da323.png)
Settings window should be smaller like GDK's, the fullscreen'd one doesn't look good. There's too much blank space for no reason. (Or lower the size of the game directories box, theme etc, think more work would be necessary to make it look "right". Or maybe make General, System, Graphics and Logging a different resolution while Input staying the same if its possible, not sure how that would work. The Save,Apply buttons are way too the right on the Logging as example so the resolution thing might be a good thing to make it look more uniform)
![image](https://user-images.githubusercontent.com/2002038/131499041-dc528e16-81c5-4ecc-b1e0-b4370e82b44b.png)

2021-08-31 12:15 UTC, GamerzHell9137 commented
And game window is still not the active window of the emulator.
Fullscreen is still broken.
Pressing ESC doesn't open the closing emulator window.

2021-08-31 21:13 UTC, emmauss commented
> 
> 
> Here's some feedback for the latest build:
> 
>     1. I'd add a line above things on the main menu because it feels like the taskbar and the game list part is getting blended in together
> 
>     2. The game list item boxes are wider and look worse than GTK's (for 2 pixels)
>        ![image](https://user-images.githubusercontent.com/2002038/131493254-737a901d-4b16-4a10-9cac-2b3ca76657df.png)
> 
>     3. I'd text align the item boxes of the game list to the left just like its on GTK, looks better.
> 
>     4. There's no scroll bar for left and right on the game list like GTK has. (Its hidden in GTK until you hover near the end of the gamelist after which you can scroll left and right)
>        ![image](https://user-images.githubusercontent.com/2002038/131493650-e79af3b4-f770-487f-91fe-373d350b9185.png)
> 
>     5. I'd align the text to left instead of having it in middle, looks better (GTK)
> 
>     6. The search on gamelist is not activated when you start typing on the keyboard but its forcing you to click on it first
> 
>     7. The default sizes of the items on gamelist can be resized a bit, they look too big (tho probably just aligning it to the left would fix that)
> 
>     8. Upper taskbar could be resized too, 38 pixels is too wide for it.
>        ![image](https://user-images.githubusercontent.com/2002038/131497404-7deed1c5-21a1-4b01-8f20-95215a345a98.png)
> 
> 
> A simple mockup:
> ![image](https://user-images.githubusercontent.com/2002038/131497019-e62165ca-ad3a-47af-8766-b15d3278ee61.png)
> 
> Why does everything look bigger on Avalonia but the text is too small? Like there's no uniformity in it (In settings)
> Someone complained about the rounded corners but i'm fine about it, its just the things being too big compared to GTK and it doesn't make it look better.
> ![image](https://user-images.githubusercontent.com/2002038/131497729-2b8726d4-fb83-477c-9f8c-f0a04e284f7f.png)
> 
> When changing themes the window for restarting the emulator is transparent
> ![image](https://user-images.githubusercontent.com/2002038/131498196-aa880b33-5290-412e-8182-80b4e8611f4d.png)
> Clicking Save instead of Apply when changing themes looks like this
> ![image](https://user-images.githubusercontent.com/2002038/131498815-e03db9ef-2441-4cd7-b388-3bb23e3da323.png)
> Settings window should be smaller like GDK's, the fullscreen'd one doesn't look good. There's too much blank space for no reason. (Or lower the size of the game directories box, theme etc, think more work would be necessary to make it look "right". Or maybe make General, System, Graphics and Logging a different resolution while Input staying the same if its possible, not sure how that would work. The Save,Apply buttons are way too the right on the Logging as example so the resolution thing might be a good thing to make it look more uniform)
> ![image](https://user-images.githubusercontent.com/2002038/131499041-dc528e16-81c5-4ecc-b1e0-b4370e82b44b.png)

1. I don't see any issue with the current style
2. I don't see any issue with this
3. I also don't see an issue with alignment
4. There is no horizontal scrollbar because the game list grows to fit the available space, and does not overflow
5. I don't see any issue with the current alignment
6. That's because the game list does not have it's own embedded search box. gtk's is the only one I know that has it. Nothing I can do about that.
7. The sizes looks ok
8. I don't see any issue with this. they are vertically large because of the search box. I also can't reduce the size of the textbox with reducing the font size.

Everything looks bigger because there are natural margins around every control. reducing those would make them look too compressed

The style applyer has a bug which triggers if you have a populated game list. That's why there is a prompt to restart if that issue occurs. It can't be fixed on our end.
it's an issue with how avalonia applies themes.

Also I would like people to not make too many comparisons with gtk. this is not gtk2.0. This is avalonia, and I will stick to avalonia's core design as much as possible.
Please look for issues in functionality, not style. If you want style changes, you can create your own style an apply it. Making any style change at this point would override previous submissions, and I'm tired of going back and forth on this.

2021-08-31 21:55 UTC, GamerzHell9137 commented
As much as i like that you want to stick to Avalonia's core design it just looks half assed and unfinished to me. An UI change should look better or at least comparable to the previous one but right now it looks like everything's overblown. The Fullscreen issues should be fixed for the merge tho. If i find anything else broken I'll report back.

2021-08-31 23:52 UTC, Shahil-Ayato commented
> As much as i like that you want to stick to Avalonia's core design, Ryujinx's implementation right now just looks half baked and unfinished to me. An UI change should look better or at least comparable to the previous one but right now it looks like everything's overblown. The Fullscreen issues should be fixed for the merge tho. If i find anything else broken I'll report back.

As @emmauss said the point isn’t looks right now that can be added in later. Right now the point is to get a functional UI. I think a big issue right now with testing is people are literally only looking at how it’s designed and not if it functions. The only thing we want is to get the UI to a functional state.

2021-09-04 20:57 UTC, knuxbbs commented
> > As much as i like that you want to stick to Avalonia's core design, Ryujinx's implementation right now just looks half baked and unfinished to me. An UI change should look better or at least comparable to the previous one but right now it looks like everything's overblown. The Fullscreen issues should be fixed for the merge tho. If i find anything else broken I'll report back.
> 
> As @emmauss said the point isn’t looks right now that can be added in later. Right now the point is to get a functional UI. I think a big issue right now with testing is people are literally only looking at how it’s designed and not if it functions. The only thing we want is to get the UI to a functional state.

I may have missed something, but I would really like to know why you guys want to replace GtkSharp.

2021-09-04 21:32 UTC, GamerzHell9137 commented
> 
> 
> > > As much as i like that you want to stick to Avalonia's core design, Ryujinx's implementation right now just looks half baked and unfinished to me. An UI change should look better or at least comparable to the previous one but right now it looks like everything's overblown. The Fullscreen issues should be fixed for the merge tho. If i find anything else broken I'll report back.
> > 
> > 
> > As @emmauss said the point isn’t looks right now that can be added in later. Right now the point is to get a functional UI. I think a big issue right now with testing is people are literally only looking at how it’s designed and not if it functions. The only thing we want is to get the UI to a functional state.
> 
> I may have missed something, but I would really like to know why you guys want to replace GtkSharp.

GTK doesn't support Vulkan.

2021-09-05 08:48 UTC, emmauss commented
> 
> 
> > > > As much as i like that you want to stick to Avalonia's core design, Ryujinx's implementation right now just looks half baked and unfinished to me. An UI change should look better or at least comparable to the previous one but right now it looks like everything's overblown. The Fullscreen issues should be fixed for the merge tho. If i find anything else broken I'll report back.
> > > 
> > > 
> > > As @emmauss said the point isn’t looks right now that can be added in later. Right now the point is to get a functional UI. I think a big issue right now with testing is people are literally only looking at how it’s designed and not if it functions. The only thing we want is to get the UI to a functional state.
> > 
> > 
> > I may have missed something, but I would really like to know why you guys want to replace GtkSharp.
> 
> GTK doesn't support Vulkan.

There are ways to run vulkan on gtk3, the wip vulkan branch is using one. This is similar to what I'm using here to support proper opengl and vulkan in avalonia.
The main reason we are moving from gtk is how unstable it is, esp. when your system isn't configured well for it.

2021-09-12 12:43 UTC, MutantAura commented
Ok so I've just done my final sweep of all _functionality_ so I'll list **everything** in the program and give it a YES/NO/MAYBE tag.

### CONSOLE
Same as GTK, nothing to report here: **YES**

### TOP BAR

## FILE
Load game from file -> **YES**

Load unpacked game -> **YES**

Open Mii Applet -> **YES**

Open Ryujinx folder -> **YES**

Open Logs folder -> **YES**

Exit -> **YES** _but hangs for a second on first time use_

## OPTIONS
Toggle Fullscreen -> **MAYBE** _goes fullscreen but still has the top and bottom bars? Unsure if this is intentional. F11 and Alt+Enter trigger true fullscreen_
![image](https://user-images.githubusercontent.com/44103205/132985472-8cda5cee-5204-4a7c-904e-3159f03f8359.png)

Start games in fullscreen -> **YES** _Interestingly doesn't show the same issue as above. True fullscreen is achieved_

Change language -> **MAYBE** _Most items of interest have translations but some do not. Screenshots of affected areas below._
**French + Portuguese**
![image](https://user-images.githubusercontent.com/44103205/132985570-2b6bcba6-c9ed-4e10-a6cb-1130fbe29958.png)
![image](https://user-images.githubusercontent.com/44103205/132985586-82011c8d-6541-44ed-b167-f5e2dfc960e4.png)
![image](https://user-images.githubusercontent.com/44103205/132985614-32dd47d4-d709-495e-8e70-ee9949febe06.png) (unsure if this is tied to PC system language but I'll put it here anyway)
![image](https://user-images.githubusercontent.com/44103205/132985637-d9af3c97-095d-4347-9a0c-d0d435d1aa66.png)

Enable GUI Columns -> **YES**

Settings -> **YES**

Manage user profiles -> **YES**

## ACTIONS
Stop emulation -> **YES**

Simulate wakeup message -> **Unsure of where to test this :)**

Scan an amiibo -> **Never used this feature so I'll leave for others to test**

Take screenshot -> **YES**

Hide UI -> **YES**

## TOOLS
Install firmware (from XCI) -> **YES**
Install firmware (from ZIP) -> **YES**
Install firmware (from directory) -> **YES**

## HELP
Check for updates -> :)

About -> **YES**

### MAIN WINDOW
Resize -> **YES**

Adjust column sizes -> **YES**

Toggle favourite -> **YES**

Open user save directory -> **YES**

Manage title updates -> **YES**

Manage DLC -> **YES**

Open mods directory -> **YES**

Cache management -> **ALL YES**

Extract Data (Logo) -> **NO** _crashes on master too_
Log file: [Ryujinx_1.0.0-dirty_2021-09-12_12-56-06.log](https://github.com/Ryujinx/Ryujinx/files/7149525/Ryujinx_1.0.0-dirty_2021-09-12_12-56-06.log)

Extract Data (romfs) -> **YES**

Extract Data (exefs) -> **NO** _does not crash in master seems to randomly work_
Log: [Ryujinx_1.0.0-dirty_2021-09-12_12-58-40.log](https://github.com/Ryujinx/Ryujinx/files/7149528/Ryujinx_1.0.0-dirty_2021-09-12_12-58-40.log)

Launching games (Shader compile) -> **YES**
Launching games (PTC) -> **YES**
_Some slight hangs at the end of both of these? Could maybe be replaced with the generic "scrolling no ETA" loading bar when finished?_

## Manage user profiles
Add new profile -> **YES**

Select firmware avatar -> **YES**

Import image file -> **YES**

Save profile name -> **YES**

Delete selected profile -> **YES**

### SETTINGS

## GENERAL
Enable Discord Rich Presence -> **YES**

Check for updates on launch -> :)

Show Confirm Exit Dialog -> **YES**

Hide Cursor on idle -> _unsure how to test this. Enabled and in-game cursor did not hide after around 1 min?_

Game directories -> **YES**
Add -> **YES**
Remove -> **YES**

Enable custom theme -> **YES**
Browse -> **YES**

Base theme change -> **YES**

## INPUT
Enable docked mode -> **YES**

Direct keyboard access -> **YES**

Direct mouse access -> **YES**

Player -> **YES**

Input device -> **YES**

Refresh -> **MAYBE** _issues with avalonia already highlighted if controllers connected while in the window_

Controller type -> **YES**

Profile select -> **YES**
Add -> **YES**
Save -> **YES**
Load -> **NO** _whenever a profile is loaded the selected profile just goes back to default_
Delete -> **YES**

Mappings -> **ALL YES**

Configure cemuhook motion -> **YES**

Enable Motion -> **YES**

Enable Rumble -> **YES**

## SYSTEM
System Region -> **YES**

System Language -> **YES**

System Timezone -> **YES**

System time -> **YES**

Enable Vsync -> **YES**

Enable PPTC -> **YES**

Enable FS integrity checks -> **YES**

Audio Backend -> **YES**

Memory Manager -> **YES**

Expand DRAM -> **YES**

Ignore missing services -> **YES**

## GRAPHICS
Enable shader cache -> **YES**

Anisotropic filtering -> **YES**

Resolution Scale -> **YES**

Aspect Ratio -> **YES**

Graphics backend multithreading -> **YES**

Graphics shader dump path -> **YES**

## LOGGING
All options -> **YES**
_Dev_ options I don't know how to test :)_

### TLDR

**BROKEN STUFF**

**Toggle fullscreen?**
**Translations missing**
**Extract Logo** - master issue
**Extract exefs randomly crashes**
**Hide cursor on idle?**
**Loading profiles**

Maybe some of these are expected but I just thought a top to bottom analysis would be worthwhile

2021-09-12 20:15 UTC, emmauss commented
rebased

2021-09-19 08:13 UTC, emmauss commented
rebased

2021-10-02 21:47 UTC, emmauss commented
added grid view. Sort is not persistent yet

2021-12-05 02:19 UTC, custodiodan commented
A while ago I reported the window not being entirely rendered, now it`s gone and everything works well. Some bugs regarding window sizing are gone as well. Now one important point: It would be nice if Avalonia UI accepted command-line game launch. One of the most nicer feature is the loading shaders/game screen when used with an external launcher, so the user could view the progress of game loading, instead of a black screen. Mainline and Headless works with command-line, but lacks the loading screen, while Avalonia shows it and lacks command-line. The perfect combination would have both.

2021-12-24 12:35 UTC, MutantAura commented
Another comment for you :)

Overall extremely polished compared to my last testing. Some bugs are present but mainly in the newer features.

- Loading the mii editor applet first thing will crash the emulator with the following error:
`00:00:00.089 |E| Application : Unhandled exception caught: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Ava.Ui.Windows.MainWindow.LoadApplication(String path, Boolean startFullscreen) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.ava\Ui\Windows\MainWindow.axaml.cs:line 253
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 258
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 205
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 111
   at Ryujinx.Ava.Program.Main(String[] args) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.ava\Program.cs:line 44
`
Loading the applet **after** another game will allow it to boot but the previous games title and ID will show up on the "loading screen". Likely why this is crashing?
![image](https://user-images.githubusercontent.com/44103205/147351928-06880820-ec16-4281-ac25-d1924757b7d2.png)

- Bug where browsing the native directory has been fixed in .NET 6 so that isn't an issue anymore.

- Audio controls are very broken (probably just not looked at yet):
- F2 mute hotkey does not update the UI to show the muted symbol or 0 volume etc but it **does** work.
- Volume levels shown in the logs seem wrong when the program is loaded. Potentially an issue when config files are mixed.
- Changing the volume slider to say 50% sets the real volume to 5000% if applied. Probably just a number error somewhere.
![image](https://user-images.githubusercontent.com/44103205/147352296-cde01a8c-6076-43df-8c63-f6d3989bede6.png)
- Volume emoji still visible during the loading screens when all other HUD elements are not: 
![image](https://user-images.githubusercontent.com/44103205/147352254-fc09b52f-b2a7-4564-bfcb-f21f96a689ea.png)

- Controller profiles are still fairly janky. (video from older build but issues remain)
https://user-images.githubusercontent.com/44103205/147352530-e1525715-09d9-4b7d-ade8-7e3fdd755a7f.mp4
Profiles seem to not want to be swapped out for each other past the first load. Default will also return each time you open the input settings even if you saved a different config. Custom configs will persist outside of the settings window if a custom profile is saved but upon returning to the input page the default profile will be shown to the user, not the controls they were actually using.

- As a more subtle UI change would it be possible to have some kind of minor separator for the bottom render widgets?
![image](https://user-images.githubusercontent.com/44103205/147352694-fa4cfefd-edd0-47be-8a91-90524b61711f.png)
Currently they are all in a continuous line and master has small separators to distinguish them.

- Exiting fullscreen will cause black bars to appear on top and bottom of the render window:
Before:
![image](https://user-images.githubusercontent.com/44103205/147352783-07268af3-eb05-4ee2-9659-462bacb0bf92.png)
After: 
![image](https://user-images.githubusercontent.com/44103205/147352844-736f175a-c878-43e7-a347-47632caf7a36.png)
This persists even after ending emulation and starting the same, or even a different game, again:
![image](https://user-images.githubusercontent.com/44103205/147352892-92e86cad-a9b0-49f1-b15c-e7dc36b43b29.png)

Other than those everything else functions as expected.

2021-12-31 09:00 UTC, emmauss commented
Dropped glfw and insteads uses avalonia's opengl control. A workaround needs to be done for vulkan. Also, due to an issue that will be fixed in the next avalonia release, I've disabled transparency on popups. So, popups will look boicky for now

2022-01-03 16:50 UTC, Narugakuruga commented
Is this related?
Avalonia dev is considering add vulkan renderer
https://github.com/AvaloniaUI/Avalonia/discussions/7137

2022-01-03 17:05 UTC, emmauss commented
> Is this related? Avalonia dev is considering add vulkan renderer [AvaloniaUI/Avalonia#7137](https://github.com/AvaloniaUI/Avalonia/discussions/7137)

This is another approach to what I was thinking of using to support vulkan, but it would require restarting Ryujinx to switch renderers. I also don't know how they will implement it or what they will expose for users.

2022-01-13 16:54 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                        Maximum="1"
Max should be 2.

2022-01-13 16:54 UTC, MutantAura commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml
> +                                        Maximum="1"
Same as above.

2022-01-23 20:02 UTC, saldabain commented
Toggling F11 causes the window to resize itself to bigger dimensions than it originally was. Repeating this exacerbates the issue.

2022-01-23 20:05 UTC, saldabain commented
It feels like there should be margin to the right of the search field to be symmetric with the margin of the list button, just a nit, but with rounded corners it feels odd to have the field flush against the border of the window.

2022-02-06 22:35 UTC, MutantAura commented
Starting to feel quite polished now.

## Final few "Major" **bugs** left that I can see.

- Line down the middle of the load bars for PTC and Shader compiles but not for launching?
![image](https://user-images.githubusercontent.com/44103205/152703484-75926c31-3dde-4ec1-8e9a-94e7c9b1531e.png)
![image](https://user-images.githubusercontent.com/44103205/152703503-b7414e57-6fd7-48d6-b2c7-8f865fa4c86c.png)

- "Actions" header does not update when a game is launched (I believe you're already aware of this?). Can also check volume vid below.
![image](https://user-images.githubusercontent.com/44103205/152703544-89f1fab8-db1a-49c7-a972-53a71dc51d9b.png)

- Entering and exiting fullscreen increases the Y dimensions of the window. Mash F11 and you soon see quite a drastic resize!
![image](https://user-images.githubusercontent.com/44103205/152703636-c04ae405-ff9a-45fa-9b12-12956302e7e7.png)

- The volume slider does not update back to "global" value when ending and restarting emulation.

https://user-images.githubusercontent.com/44103205/152703797-b4c16f8e-7ee6-4f31-9a7d-a0ed9d7eaae9.mp4

---

## The next bit aren't what I'd consider "major" but they're just a bit weird/my personal opinion.

- Resizing the window or moving it around causes the renderer to get a bit muddled. The freeze is when I'm moving the window and afterwards its a resize in Y and then X

https://user-images.githubusercontent.com/44103205/152704041-96476d11-6394-4745-aa69-47ce2ab90e86.mp4

- My view on the Host refresh rate being visible on the render widget is that it really doesn't need to be there. I don't think it adds any value to the bottom bar which imo is meant to be for things the user wants to toggle mid-session or dynamic information such as performance statistics. I think it should just be removed from the bar and left in settings. I also believe this should default to 0 (unlimited) in the default configuration format to more closely match GTK. Being able to target a select refresh rate is the exception, not the rule. Most simply wish to see how high their systems can reach and most games do not support dynamic framerates anyway.

- Is there any way to just make this left section a different colour or is it just the way the borders have to work? To me it just looks somewhat odd. 
![image](https://user-images.githubusercontent.com/44103205/152704300-d4f00a4a-d109-4208-962f-870f6a5924f3.png)

- Also perhaps a _slight_ increase in the size of the icons? They seem quite small for having such a large button padding around them.
![image](https://user-images.githubusercontent.com/44103205/152704359-1c3035f1-4d0c-4122-a10f-6a6be97074a9.png)

Overall looking **really** good though. Very much shaping into it's own UI rather than just GTK2.0 :)

2022-02-07 11:51 UTC, Eli0t77 commented
why actively block people on windows less than 10?
 if it works without this check they should be allowed to use the software
`System.NotSupportedException: Windows versions earlier than 10 are not supported`

2022-02-07 12:00 UTC, emmauss commented
> why actively block people on windows less than 10? if it works without this check they should be allowed to use the software `System.NotSupportedException: Windows versions earlier than 10 are not supported`

The theming library we are using has a hard requirement for window 10+

2022-03-08 12:19 UTC, emmauss commented
Rebased. Locale files needs update

2022-03-13 13:08 UTC, emmauss commented
Rebased. Locales need to be updated

2022-04-15 03:02 UTC, Moonlacer commented
I am using a 4K display with a 250% Windows scale, and upon opening the settings window, it does not allow me to see the window bar at the top to be able to drag, minimize, or close the window as can be seen in this picture:
![image](https://user-images.githubusercontent.com/79172044/163511213-e7257316-9432-4809-9cbd-b96c8f8ef0e0.png)
Moving my mouse as far to the top as possible doesn't allow me to interact with it, either

I don't know what Avalonia has for this type of scaling issue, but it would be nice to have it go Fullscreen or at least fit on the screen

2022-05-15 12:18 UTC, closed without merging