Vulkan backend
Ryujinx/Ryujinx pull request #2518
Opened 2021-07-30 23:24 UTC by gdkchan

**NOTE to AMD users:** The last version of their driver that is known to function properly is [21.3.2](https://drivers.amd.com/drivers/Non-WHQL-Radeon-Software-Adrenalin-2020-21.3.2-Win10-64Bit-Mar29.exe). You might want to downgrade it if you want to try this without the vertex corruption for now.

### Overview

This is a WIP implementation of a Vulkan graphics backend. The main goal here is improving the performance for AMD users, however there are other advantages of using Vulkan for all vendors.

Main advantages of Vulkan (for all vendors):
- Support for compressed 3D textures: Fixes graphical glitches on Tales of Vesperia, Ghost & Goblins returns, Monster Hunter Rise and more.
- Support for textures views between compressed and uncompressed formats. Avoids copies, we do not yet take advantage of this, but will in the future.
- Supports for 2D array views from 3D textures. Avoids copies, we do not yet take advantage of this, but will in the future.
- Allows transform feedback buffers to have other uses while the transform feedback is active. Avoids copies.

### Pending work

Those items should be completed before the Vulkan implementation is merged.
- [ ] Multisampling support.
- [ ] Alpha test support.
- [ ] Custom image formats at bind. Or maybe change how it works to play nicely with Vulkan? (Required to render ground etc correctly on Xenoblade Chronicles Definitive Edition, fire/ice etc effects on Kirby Star Allies).
- [ ] Make sure it plays nicely with the AMD driver (there are currently some known bugs with AMD drivers, more on that later).
- [ ] Integrate SPIR-V backend and make sure it is functionally equivalent to the GLSL one.
- [ ] Write basic tests for shaders and the backend, to ensure they behave as expected.
Other nice-to-haves, not essential for merge:
- [ ] Index buffer conversion for quads. Should improve the speed of games using quads.
- [ ] Better Uint8 index buffer conversion. Should have some very minor performance improvement for AMD.
- [ ] Experiment with other descriptor set update methods. May improve performance. I already made quite a lot of tests in this area however, and it doesn't seems like there's much we can do to improve it further.
- [ ] Consider using a separate thread for command submission. Might benefit Intel due to the workaround that makes it submit commands a lot.
- [ ] Pipeline cache. Effectively a on-disk shader cache on Vulkan.

### Known issues

- Some game models are stretching to the origin on AMD. **The last version of their driver that is known to function properly is 21.3.2**. You might want to downgrade it if you want to try this without the vertex corruption for now.
- AMD also suffers from a issue where the window is partially transparent and the desktop is visible. Not all systems are affected, it is currently unknown exactly what triggers it, it might be a GTK issue.
- Missing transparency on a few games due to the lack of alpha test.
- Some games (Luigi's Mansion 3, Mario Tennis Aces, etc) softlocks on Intel because sampler arrays are not properly defined on pipeline layouts on Vulkan. It will be addressed separately, as the plan is using a different method to handle those textures.

### Performance roadmap

The changes below should improve performance significantly on the Vulkan backend in the near future.
- Threaded GAL: Large performance improvements for all vendors, since Vulkan drivers do not provide any form of threaded optimizations, unlike OpenGL.
- SPIR-V backend: This will not improve overall performance, but will reduce shader compilation times and consequently, stutters, resulting in a smoother experience. It is not currently included to make the testing process easier. Right now, it converts GLSL to SPIR-V at runtime. If there is a bug, we know it's not due to shaders, since it is using the same shader source used on OpenGL (for the most part). The SPIR-V backend will be included soon, and enabled by default after Vulkan and SPIR-V has received enough internal testing.

**Async shader compilation:** This is something that is asked a lot. The truth is that async shader compilation is not really worth it, since it introduces graphical glitches, and in fact, pretty much all emulators that implemented this feature in the past **are moving away from it because there are better alternatives**. The better alternative in this case is parallel shader compilation, which also reduces the compilation times significantly without introducing graphical glitches. **This is already implemented as part of Threaded GAL, and will also come to Vulkan after Threaded GAL is merged**.

### Improvements

AMD:

TBD

Intel:
Some graphical issues that exists on OpenGL are not present on Vulkan.

OpenGL:
![image](https://user-images.githubusercontent.com/5624669/127716506-403ea8ba-77f5-4dad-bca8-548cf3be93f0.png)
![image](https://user-images.githubusercontent.com/5624669/127716582-f1c498b6-a570-4774-9fb2-45b866d0e1ab.png)
Vulkan:
![image](https://user-images.githubusercontent.com/5624669/127716635-7cf8429a-775e-42dc-98c7-5a46d5c7a6e4.png)
![image](https://user-images.githubusercontent.com/5624669/127716652-53dbed14-6409-4de0-b1ca-79905862e491.png)

OpenGL:
![image](https://user-images.githubusercontent.com/5624669/127717322-b8fca13e-75f1-425e-8fc4-2e22494042e3.png)
Vulkan:
![image](https://user-images.githubusercontent.com/5624669/127718211-89e4d2bc-d6e5-4794-8018-95c3f76eef89.png)

OpenGL:
![image](https://user-images.githubusercontent.com/5624669/127718135-e6fe22a5-6359-4005-beb3-9ce5691fd946.png)
Vulkan:
![image](https://user-images.githubusercontent.com/5624669/127718299-330a4fe2-8288-4534-9fb8-97b5401f4367.png)
![image](https://user-images.githubusercontent.com/5624669/127718332-5eadc2f6-c73d-4170-b2fd-dd32e055cb91.png)
![image](https://user-images.githubusercontent.com/5624669/127718682-d1be1ab2-284b-495a-8fbe-ff24172023fd.png)

### What to test

All games really, but if you find a issue, before reporting, make sure it was not already reported, or is included on the "known issues" section.

2021-07-31 02:26 UTC, Sakura0134 commented
I noticed serious bugs in RADV compared to amdvlk. Feature Request: Please add a toggle switch to switch between amdvlk and RADV. 
RADV
![Screenshot_20210731_111408](https://user-images.githubusercontent.com/85794603/127725948-376a7752-8593-48a8-ad17-a0e3f75bb30a.png)
RadeonSI
![Screenshot_20210731_111534](https://user-images.githubusercontent.com/85794603/127725950-94585480-cf68-4627-b6a7-a3ecb1270cea.png)
amdvlk
![Screenshot_20210731_111149](https://user-images.githubusercontent.com/85794603/127725944-1e21bf79-6330-4cbc-b375-415175e2487c.png)
Test System: CPU: Ryzen 3500u GPU: Vega 8

2021-07-31 02:50 UTC, Sakura0134 commented
Glitched Input System(Triggered by Arrow Keys)
![Screenshot_20210731_112748](https://user-images.githubusercontent.com/85794603/127726470-02419648-97c0-415b-beb7-8b9d2ff5cca3.png)

2021-07-31 02:51 UTC, Sakura0134 commented
amdvlk crashing an for some reason, Vulkan API is not producing any logs and what I get is this terminal snippet
![Screenshot_20210731_114556](https://user-images.githubusercontent.com/85794603/127726502-e6bb71db-55be-4488-9c32-ac2198df0c97.png)

2021-07-31 02:51 UTC, Sakura0134 commented
More info(I suppose) on pr-testing

2021-07-31 03:09 UTC, Sakura0134 commented
This PR doesn't work with RADV, at all and crashes after character selection in amdvlk(Test System: Ryzen 5 3500u GPU: Vega 8)

2021-07-31 04:27 UTC, TiggyDee commented
Link's Awakening crashes on boot with an AMD RX 580. (Same behavior happens with a RX 5500XT)
[Ryujinx_1.0.005fd259_2021-07-30_20-44-17.log](https://github.com/Ryujinx/Ryujinx/files/6910677/Ryujinx_1.0.005fd259_2021-07-30_20-44-17.log)

2021-07-31 08:45 UTC, tyx233 commented
original：osx 闪退 是没给mac适配吗， 为什么会出现这个问题？
Translation：osx quit unexpectedly. Didn't it adapt to osx? Why does this problem happen?

[Ryujinx_1.0.0+05fd259_2021-07-31_14-09-02.log](https://github.com/Ryujinx/Ryujinx/files/6910914/Ryujinx_1.0.0%2B05fd259_2021-07-31_14-09-02.log)

2021-07-31 09:02 UTC, emmauss commented
> 
> 
> original：osx 闪退 是没给mac适配吗， 为什么会出现这个问题？
> Translation：osx quit unexpectedly. Didn't it adapt to osx? Why does this problem happen?
> 
> [Ryujinx_1.0.0+05fd259_2021-07-31_14-09-02.log](https://github.com/Ryujinx/Ryujinx/files/6910914/Ryujinx_1.0.0%2B05fd259_2021-07-31_14-09-02.log)

OSX does not support vulkan.

2021-07-31 10:11 UTC, GamerzHell9137 commented
@gdkchan the download link to the AMD driver is broken

2021-07-31 10:14 UTC, GamerzHell9137 commented
Ohh and here's some positives out of Vulkan (tested on GTX 960)

Pokken Tournament is full speed VS OpenGL and the color issue is fixed on it 
![image](https://user-images.githubusercontent.com/2002038/127736659-078fc5b7-58ce-495e-ba84-2a3b27e0946b.png)

Project Diva doesn't have weird lines in the sky anymore VS OpenGL
![image](https://user-images.githubusercontent.com/2002038/127736681-7bfa0850-5487-4393-aa66-6f772ec53846.png)
![image](https://user-images.githubusercontent.com/2002038/127736690-03083414-946d-4ef0-9293-2aff95b450e9.png)

Bravely Default II is loading faster VS OpenGL
Bayonetta is running faster too VS OpenGL

2021-07-31 12:47 UTC, GamerzHell9137 commented
Windows 10, Ryzen 3600, GTX 960 2 GB VRAM, 16 GB RAM

1.  Mario Golf: Super Rush crashes when trying to load the character selection screen. Nothing shown in the logs, console shows a Fatal Error. In Adventure mode there's a blue tint over the screen.

![image](https://user-images.githubusercontent.com/2002038/127739813-bacaf901-c016-477f-a3cb-0c4ce31e6b08.png)

2. Chocobo's Mystery Dungeon EVER BUDDY! the log textboxs which shows what's going on in the game is empty and doesn't show anything, other textboxes are fine
![image](https://user-images.githubusercontent.com/2002038/127739889-40bef8f0-3927-40bc-9d02-20eb2e826b12.png)

3. Rune Factory 5: Texture's are appearing and disappearing, same with objects in the world. There's a msg in red in the console.

VIDEO OF ISSUE : https://streamable.com/hjw8i0
```
00:02:43.047 |E| GUI.RenderLoop Gpu .ctor: Shader compilation error: CompilationError Ryu:7: warning: '#extension' : extension not supported: GL_EXT_texture_shadow_lod
Ryu:96: error: 'textureSize' : no matching overloaded function found
Ryu:96: error: 'Helper_TextureSizeUnscale' : no matching overloaded function found
Ryu:96: error: 'assign' :  cannot convert from ' const float' to ' temp highp int'
Ryu:97: error: 'textureSize' : no matching overloaded function found
Ryu:97: error: 'g' : vector swizzle selection out of range
Ryu:97: error: 'Helper_TextureSizeUnscale' : no matching overloaded function found
Ryu:97: error: 'assign' :  cannot convert from ' const float' to ' temp highp int'
```

4. Story of Seasons: Pioneers of Olive Town: Water puddles at certain angles and distances  are black 
![image](https://user-images.githubusercontent.com/2002038/127740111-ea805a97-4212-441e-bb21-2cd07c0b4b73.png)

5. BRAVELY DEFAULT II: Sometimes after fleeing a battle the screen is stuck at the battle screen. Red text in logs after getting into a battle. Game soft locks randomly while walking in overworld with the error ``Gpu AwaitResult: Error: Query result timed out. Took more than 5000 tries.``

```00:01:55.721 |E| GUI.RenderLoop Gpu .ctor: Shader compilation error: CompilationError Ryu:7: warning: '#extension' : extension not supported: GL_EXT_texture_shadow_lod
Ryu:36: error: 's_render_scale' : undeclared identifier
Ryu:36: error: 's_render_scale' :  left of '[' is not of type array, matrix, or vector
Ryu:46: error: 's_render_scale' : undeclared identifier
Ryu:46: error: 's_render_scale' :  left of '[' is not of type array, matrix, or vector
```

![image](https://user-images.githubusercontent.com/2002038/127740237-6b76fd73-20d6-44f5-bbdb-173418913d32.png)

2021-07-31 17:35 UTC, gdkchan commented
> Mario Golf: Super Rush crashes when trying to load the character selection screen. Nothing shown in the logs, console shows a Fatal Error.

This was fixed in 637ffad260e87259ff5345b44ebdb089443bfe22.

2021-07-31 20:15 UTC, d3ce1t commented
In Fedora 34 with Intel Graphics using Mesa I got next error when trying to run a game.

```console
$ GDK_BACKEND=x11 ./Ryujinx
00:00:00.003 |W| Application GetWindowScaleFactor: Couldn't determine monitor DPI: The type initializer for 'Gdip' threw an exception.
00:00:00.369 |I| Configuration LogValueChange: EnableFileLog set to: False
00:00:00.371 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.372 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.372 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.373 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.374 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.402 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+0165c9d
00:00:00.409 |N| Application Print: Operating System: Linux 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 (X64)
00:00:00.409 |N| Application Print: CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz ; 8 logical
00:00:00.409 |N| Application Print: RAM: Total 15689 MB ; Available 11119 MB
00:00:00.412 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.412 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.463 |N| Application LoadApplication: Using Firmware Version: 9.0.1
00:00:01.453 |E| GUI.RenderLoop Application : Unhandled exception caught: System.DllNotFoundException: Unable to load shared library 'shaderc_shared' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libshaderc_shared: cannot open shared object file: No such file or directory
   at shaderc.NativeMethods.shaderc_compile_options_initialize()
   at shaderc.Options..ctor(Boolean enableIncludes)
   at Ryujinx.Graphics.Vulkan.Shader..ctor(Vk api, Device device, ShaderStage stage, ShaderBindings bindings, String glsl)
   at Ryujinx.Graphics.Vulkan.TextureBlit..ctor(VulkanGraphicsDevice gd, Device device)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel, String[] requiredExtensions)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'shaderc_shared' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libshaderc_shared: cannot open shared object file: No such file or directory
   at shaderc.NativeMethods.shaderc_compile_options_initialize()
   at shaderc.Options..ctor(Boolean enableIncludes)
   at Ryujinx.Graphics.Vulkan.Shader..ctor(Vk api, Device device, ShaderStage stage, ShaderBindings bindings, String glsl)
   at Ryujinx.Graphics.Vulkan.TextureBlit..ctor(VulkanGraphicsDevice gd, Device device)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel, String[] requiredExtensions)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Aborted (core dumped)
```

2021-07-31 21:14 UTC, GamerzHell9137 commented
Characters are underneath track parts in Mario Kart
![image](https://user-images.githubusercontent.com/2002038/127752545-c6af1e93-60ed-4278-aecd-678b6104f566.png)

2021-07-31 23:20 UTC, edisionnano commented
> In Fedora 34 with Intel Graphics using Mesa I got next error when trying to run a game. Looks like shaderc_shared.dll is included in the build but shaderc_shared.so is not.
> 
> Note I'm in a Wayland Session, so X11 is forced to make use of XWayland.
> 
> ```
> $ GDK_BACKEND=x11 ./Ryujinx
> 00:00:00.003 |W| Application GetWindowScaleFactor: Couldn't determine monitor DPI: The type initializer for 'Gdip' threw an exception.
> 00:00:00.369 |I| Configuration LogValueChange: EnableFileLog set to: False
> 00:00:00.371 |I| Configuration LogValueChange: ResScale set to: 1
> 00:00:00.372 |I| Configuration LogValueChange: ResScaleCustom set to: 1
> 00:00:00.372 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
> 00:00:00.373 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
> 00:00:00.374 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
> 00:00:00.402 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+0165c9d
> 00:00:00.409 |N| Application Print: Operating System: Linux 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 (X64)
> 00:00:00.409 |N| Application Print: CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz ; 8 logical
> 00:00:00.409 |N| Application Print: RAM: Total 15689 MB ; Available 11119 MB
> 00:00:00.412 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
> 00:00:00.412 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> 00:00:00.463 |N| Application LoadApplication: Using Firmware Version: 9.0.1
> 00:00:01.453 |E| GUI.RenderLoop Application : Unhandled exception caught: System.DllNotFoundException: Unable to load shared library 'shaderc_shared' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libshaderc_shared: cannot open shared object file: No such file or directory
>    at shaderc.NativeMethods.shaderc_compile_options_initialize()
>    at shaderc.Options..ctor(Boolean enableIncludes)
>    at Ryujinx.Graphics.Vulkan.Shader..ctor(Vk api, Device device, ShaderStage stage, ShaderBindings bindings, String glsl)
>    at Ryujinx.Graphics.Vulkan.TextureBlit..ctor(VulkanGraphicsDevice gd, Device device)
>    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel, String[] requiredExtensions)
>    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
>    at Ryujinx.Ui.RendererWidgetBase.Render()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'shaderc_shared' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libshaderc_shared: cannot open shared object file: No such file or directory
>    at shaderc.NativeMethods.shaderc_compile_options_initialize()
>    at shaderc.Options..ctor(Boolean enableIncludes)
>    at Ryujinx.Graphics.Vulkan.Shader..ctor(Vk api, Device device, ShaderStage stage, ShaderBindings bindings, String glsl)
>    at Ryujinx.Graphics.Vulkan.TextureBlit..ctor(VulkanGraphicsDevice gd, Device device)
>    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel, String[] requiredExtensions)
>    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
>    at Ryujinx.Ui.RendererWidgetBase.Render()
>    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
> Aborted (core dumped)
> ```

Perhaps you need to install this dependency, for example for arch this package https://archlinux.org/packages/extra/x86_64/shaderc/ provides this shared library, for fedora find a way to get libshaderc

2021-08-01 00:35 UTC, yuwenhua653 commented
AMD graphics card Pokémon sword shield white screen
![image](https://user-images.githubusercontent.com/30205483/127755472-c3f2d129-9617-4408-aaa0-d3c808232351.png)

2021-08-01 00:38 UTC, jduncanator commented
For anyone reporting issues on specific Vendors and Configurations, please post the GPU model you have, the operating system you're on, and the driver you're using. Even better, upload a full log.

2021-08-01 08:17 UTC, jduncanator commented
I'm going to start collating issues I've observed here. All tests were performed on the following hardware, with the same Ryujinx settings, unless noted otherwise:

**OS**: Windows 10 21H1 19043.1151
**CPU**: Ryzen 5 3600
**GPU**: AMD RX580 8GB - AMD Radeon Adrenaline 21.3.2 driver
**RAM**: 16GB 3600MHz DDR4 (CL16)

**Ryujinx Ver**: Ryujinx built from fb186f8
Vulkan backend, Native Resolution, GLSL shader backend

----

## Burnout Paradise Remastered 1.0.0 
[Ryujinx_1.0.0-dirty_2021-08-01_17-49-18.log](https://github.com/Ryujinx/Ryujinx/files/6912339/Ryujinx_1.0.0-dirty_2021-08-01_17-49-18.log)

The game boots fine, however once past the opening cutscene, corruption is throughout the game.

![image](https://user-images.githubusercontent.com/1518948/127764008-de8e3385-d9ef-4bd2-b9f2-6dd49fe7f02d.png)

An odd behaviour with Vsync is observed. Disabling Vsync results in a loss of ~20% performance.

### Vsync On
![image](https://user-images.githubusercontent.com/1518948/127764039-07cf23e5-62c5-4836-8905-df5dce96efc9.png)

### Vsync Off
![image](https://user-images.githubusercontent.com/1518948/127764049-c6fe6548-2392-41ae-bb71-cf8ce4076ee4.png)

## Mario Kart 8 Deluxe 1.7.2

[Ryujinx_1.0.0-dirty_2021-08-01_18-12-02.log](https://github.com/Ryujinx/Ryujinx/files/6912342/Ryujinx_1.0.0-dirty_2021-08-01_18-12-02.log)

The game boots fine, however nine times out of ten fails to go in game, instead resulting in a freeze waiting on a GPU query result.

```
[...]
00:01:06.394 |I| HLE.OsThread.9 ServiceNv Create: Created map 1649 with size 0x00003000!
00:01:06.395 |I| HLE.OsThread.9 ServiceNv Create: Created map 1650 with size 0x0003c000!
00:01:06.666 |W| HLE.OsThread.9 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:15.510 |E| Gpu AwaitResult: Error: Query result timed out. Took more than 5000 tries.
```

Character models are missing, even on 21.2.3 drivers.

![image](https://user-images.githubusercontent.com/1518948/127764214-53f65655-bc7e-42a2-913b-3290af0a23b0.png)


(More coming)

2021-08-01 13:07 UTC, d3ce1t commented
> > In Fedora 34 with Intel Graphics using Mesa I got next error when trying to run a game. Looks like shaderc_shared.dll is included in the build but shaderc_shared.so is not.
> > Note I'm in a Wayland Session, so X11 is forced to make use of XWayland.
> > ```
> > $ GDK_BACKEND=x11 ./Ryujinx
> > 00:00:00.003 |W| Application GetWindowScaleFactor: Couldn't determine monitor DPI: The type initializer for 'Gdip' threw an exception.
> > 00:00:00.369 |I| Configuration LogValueChange: EnableFileLog set to: False
> > 00:00:00.371 |I| Configuration LogValueChange: ResScale set to: 1
> > 00:00:00.372 |I| Configuration LogValueChange: ResScaleCustom set to: 1
> > 00:00:00.372 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
> > 00:00:00.373 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
> > 00:00:00.374 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
> > 00:00:00.402 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+0165c9d
> > 00:00:00.409 |N| Application Print: Operating System: Linux 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 (X64)
> > 00:00:00.409 |N| Application Print: CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz ; 8 logical
> > 00:00:00.409 |N| Application Print: RAM: Total 15689 MB ; Available 11119 MB
> > 00:00:00.412 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
> > 00:00:00.412 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> > 00:00:00.463 |N| Application LoadApplication: Using Firmware Version: 9.0.1
> > 00:00:01.453 |E| GUI.RenderLoop Application : Unhandled exception caught: System.DllNotFoundException: Unable to load shared library 'shaderc_shared' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libshaderc_shared: cannot open shared object file: No such file or directory
> >    at shaderc.NativeMethods.shaderc_compile_options_initialize()
> >    at shaderc.Options..ctor(Boolean enableIncludes)
> >    at Ryujinx.Graphics.Vulkan.Shader..ctor(Vk api, Device device, ShaderStage stage, ShaderBindings bindings, String glsl)
> >    at Ryujinx.Graphics.Vulkan.TextureBlit..ctor(VulkanGraphicsDevice gd, Device device)
> >    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel, String[] requiredExtensions)
> >    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
> >    at Ryujinx.Ui.RendererWidgetBase.Render()
> >    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> >    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> > --- End of stack trace from previous location ---
> >    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> >    at System.Threading.ThreadHelper.ThreadStart()
> > Unhandled exception. System.DllNotFoundException: Unable to load shared library 'shaderc_shared' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libshaderc_shared: cannot open shared object file: No such file or directory
> >    at shaderc.NativeMethods.shaderc_compile_options_initialize()
> >    at shaderc.Options..ctor(Boolean enableIncludes)
> >    at Ryujinx.Graphics.Vulkan.Shader..ctor(Vk api, Device device, ShaderStage stage, ShaderBindings bindings, String glsl)
> >    at Ryujinx.Graphics.Vulkan.TextureBlit..ctor(VulkanGraphicsDevice gd, Device device)
> >    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel, String[] requiredExtensions)
> >    at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
> >    at Ryujinx.Ui.RendererWidgetBase.Render()
> >    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
> >    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> > --- End of stack trace from previous location ---
> >    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> >    at System.Threading.ThreadHelper.ThreadStart()
> > Aborted (core dumped)
> > ```
> 
> Perhaps you need to install this dependency, for example for arch this package https://archlinux.org/packages/extra/x86_64/shaderc/ provides this shared library, for fedora find a way to get libshaderc

Thanks! It worked. I had to symblink libshaderc_shared.so.1 > libshaderc_shared.so because it didn't exist. 

```console
$ sudo dnf install libshaderc
$ sudo ln -s /usr/lib64/libshaderc_shared.so.1 /usr/lib64/libshaderc_shared.so
```

2021-08-01 13:27 UTC, d3ce1t commented
### System info
```
00:00:00.382 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+0165c9d
00:00:00.389 |N| Application Print: Operating System: Linux 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 (X64)
00:00:00.389 |N| Application Print: CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz ; 8 logical
00:00:00.389 |N| Application Print: RAM: Total 15689 MB ; Available 11588 MB
00:00:00.391 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.391 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.402 |N| Application LoadApplication: Using Firmware Version: 9.0.1
00:00:01.712 |N| GUI.RenderLoop Gpu PrintGpuInformation: Intel Intel(R) UHD Graphics 620 (KBL GT2) (Vulkan v1.2.168, Driver v21.1.5)
```

### New Super Mario Bros U Deluxe
Note: Performance is better in OpenGL and there no graphic issues

![image](https://user-images.githubusercontent.com/3706385/127772148-e7750449-f53b-465e-9604-ab63ddc1fa40.png)

![image](https://user-images.githubusercontent.com/3706385/127772220-5053482f-38d2-4f20-b320-507bfe378c3b.png)

2021-08-01 22:11 UTC, jduncanator commented
> ### System info
> 
> ```
> 
> 00:00:00.382 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+0165c9d
> 
> 00:00:00.389 |N| Application Print: Operating System: Linux 5.13.4-200.fc34.x86_64 #1 SMP Tue Jul 20 20:27:29 UTC 2021 (X64)
> 
> 00:00:00.389 |N| Application Print: CPU: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz ; 8 logical
> 
> 00:00:00.389 |N| Application Print: RAM: Total 15689 MB ; Available 11588 MB
> 
> 00:00:00.391 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
> 
> 00:00:00.391 |N| Application PrintSystemInfo: Launch Mode: UserProfile
> 
> 00:00:00.402 |N| Application LoadApplication: Using Firmware Version: 9.0.1
> 
> 00:00:01.712 |N| GUI.RenderLoop Gpu PrintGpuInformation: Intel Intel(R) UHD Graphics 620 (KBL GT2) (Vulkan v1.2.168, Driver v21.1.5)
> 
> ```
> 
> 
> 
> ### New Super Mario Bros U Deluxe
> 
> Note: Performance is better in OpenGL and there no graphic issues
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3706385/127772148-e7750449-f53b-465e-9604-ab63ddc1fa40.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/3706385/127772220-5053482f-38d2-4f20-b320-507bfe378c3b.png)
> 
> 
> 
> 

Mesa OpenGL is likely going to be the preferred choice for many users for a while, until Vulkan can be refined and optimised. It's really only Intel and AMD on Windows that suffer the most from OpenGL and Vulkan provides a big boost there.

Eventually, the hope is, that Vulkan becomes the first class backend, however the first iteration was never going to beat OpenGL on Mesa or the NV OGL drivers on Windows.

2021-08-02 00:00 UTC, GamerzHell9137 commented
### Windows 10, Ryzen 3600, GTX 960 2 GB VRAM, 16 GB RAM

Taiko graphics broken 
![image](https://user-images.githubusercontent.com/2002038/127789232-d66291bb-0283-485c-ad20-5d64081e1c45.png)

2021-08-02 00:55 UTC, jduncanator commented
> ### Windows 10, Ryzen 3600, GTX 960 2 GB VRAM, 16 GB RAM
> Taiko graphics broken
> ![image](https://user-images.githubusercontent.com/2002038/127789232-d66291bb-0283-485c-ad20-5d64081e1c45.png)
> 
> Monster Hunter Gen (iirc this is Alpha channel related?)
> ![image](https://user-images.githubusercontent.com/2002038/127789263-8a0e7852-3fd8-41ad-94f9-ab0e96262a2f.png)

Taiko graphics look related to Alpha test/blend support as well.

2021-08-02 06:42 UTC, gdkchan commented
> Most (all?) games fail to boot with a resolution scale greater than 1 set, with the following exception:

> Changing resolution scale whilst in-game results in a crash:

> Crashes shortly after the stadium intro cutscene starts playing, with the following exception:

Fixed on 266be800acdf9fdc5be6bc15841741a01837a7be.

> Character models are missing, even on 21.2.3 drivers.

> Character models are exploded at character select screen.

> Character models are exploded.

> Character models are exploded here too.

> Character models are exploded here as well:

Fixed on 66dd53716fd71f1758bef7696e4238e47af245e0.

2021-08-02 06:49 UTC, gdkchan commented
Note for AMD GPU users on Windows: The issue causing model vertices being stretched out was fixed. The crash when changing the resolution scale was fixed. The crash on Pokémon Sword on scenes with DoF or fog effects was also fixed. If you find any more games with vertex explosions etc exclusive to AMD, please let me know. **Downgrading the driver should be no longer needed**, just use the latest version. The window transparency issue was not fixed yet, I was not able to find a way to reproduce it so far, only some systems are affected.

2021-08-02 07:00 UTC, molitar commented
> 
> 
> Note for AMD GPU users on Windows: The issue causing model vertices being stretched out was fixed. The crash when changing the resolution scale was fixed. The crash on Pokémon Sword on scenes with DoF or fog effects was also fixed. If you find any more games with vertex explosions etc exclusive to AMD, please let me know. **Downgrading the driver should be no longer needed**, just use the latest version. The window transparency issue was not fixed yet, I was not able to find a way to reproduce it so far, only some systems are affected.

Ok will try latest drivers I had downgraded to 12.3.2 and than I started having the transparent window problem.

2021-08-02 09:38 UTC, rolmerin commented
> Note for AMD GPU users on Windows: The issue causing model vertices being stretched out was fixed. The crash when changing the resolution scale was fixed. The crash on Pokémon Sword on scenes with DoF or fog effects was also fixed. If you find any more games with vertex explosions etc exclusive to AMD, please let me know. **Downgrading the driver should be no longer needed**, just use the latest version. The window transparency issue was not fixed yet, I was not able to find a way to reproduce it so far, only some systems are affected.

Hi,I found that window transparency issue can be 100% reproduced through ReShade.When installing ReShade,make sure to click "enable/disable ReShade in Vulkan globally".Then select Ryujinx installation folder,and vulkan api.
Tested in windows 10 ,ReShade 4.9.1.

2021-08-02 10:26 UTC, jduncanator commented
> > Note for AMD GPU users on Windows: The issue causing model vertices being stretched out was fixed. The crash when changing the resolution scale was fixed. The crash on Pokémon Sword on scenes with DoF or fog effects was also fixed. If you find any more games with vertex explosions etc exclusive to AMD, please let me know. **Downgrading the driver should be no longer needed**, just use the latest version. The window transparency issue was not fixed yet, I was not able to find a way to reproduce it so far, only some systems are affected.
> 
> Hi,I found that window transparency issue can be 100% reproduced through ReShade.When installing ReShade,make sure to click "enable/disable ReShade in Vulkan globally".Then select Ryujinx installation folder,and vulkan api.
> Tested in windows 10 ,ReShade 4.9.1.
> Besides,I also found another way to repoduce the issue wihout using ReShade.
> When loading a savadata in BRAVELY DEFAULT II,the game will just stuck in the loading screen.Then click minimize or maximize , the window will become transparent.
> Tested in AMD RX590 video card
> [Ryujinx_1.0.0+b32f116_2021-08-02_18-21-11.log](https://github.com/Ryujinx/Ryujinx/files/6916200/Ryujinx_1.0.0%2Bb32f116_2021-08-02_18-21-11.log)

Can you provide a screenshot to demonstrate each of the issues? The issue with BRAVELY DEFAULT II sounds like a standard issue that exists in master on all vendors at the moment.

2021-08-02 13:39 UTC, jduncanator commented
I've tested both of the above transparency issues, and neither reproduced the issue where some users see the entire window going semi-transparent. A video reproducing this issue can be found here: https://youtu.be/qRnNafuG9fo?t=310

2021-08-02 13:43 UTC, Leischii commented
> 
> 
> I've tested both of the above transparency issues, and neither reproduced the issue where some users see the entire window going semi-transparent. A video reproducing this issue can be found here: https://youtu.be/qRnNafuG9fo?t=310

The transparency issue can be fixed by turning off image sharpening in the radeon software. Should also work the other way around to trigger it.

2021-08-02 13:48 UTC, jduncanator commented
> > I've tested both of the above transparency issues, and neither reproduced the issue where some users see the entire window going semi-transparent. A video reproducing this issue can be found here: https://youtu.be/qRnNafuG9fo?t=310
> 
> The transparency issue can be fixed by turning off image sharpening in the radeon software. Should also work the other way around to trigger it.

Thanks legend~! Can confirm that this causes the issue on latest AMD drivers on Windows... attempting to figure out what causes it now!

![image](https://user-images.githubusercontent.com/1518948/127872041-5a4d1f80-160f-444a-bee1-d29002fbe39a.png)

2021-08-02 16:18 UTC, molitar commented
Disabling sharpening worked for me also for the transparency issue but not my crashing issue on loading Dragon Quest XI. 

[Ryujinx_1.0.0+b32f116_2021-08-02_12-07-43.log](https://github.com/Ryujinx/Ryujinx/files/6918239/Ryujinx_1.0.0%2Bb32f116_2021-08-02_12-07-43.log)

2021-08-02 16:33 UTC, GamerzHell9137 commented
> 
> 
> Disabling sharpening worked for me also for the transparency issue but not my crashing issue on loading Dragon Quest XI.
> 
> [Ryujinx_1.0.0+b32f116_2021-08-02_12-07-43.log](https://github.com/Ryujinx/Ryujinx/files/6918239/Ryujinx_1.0.0%2Bb32f116_2021-08-02_12-07-43.log)

Try deleting PPTC and Shader cache, sometimes games crash when they have older files that are being loaded in or something.

2021-08-02 16:45 UTC, KookiesGH commented
```
00:00:00.032 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+b32f116
00:00:00.036 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.036 |N| Application Print: CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz ; 8 logical
00:00:00.037 |N| Application Print: RAM: Total 16318 MB ; Available 12047 MB
00:00:00.038 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.038 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.246 |N| Application LoadApplication: Using Firmware Version: 11.0.1
00:00:01.973 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 2070 (Vulkan v1.2.175, Driver v471.41.0.0)
```
### Skyward Sword HD
Title screen renders darker than on OpenGL / console. Skyloft in the backround of the File Select screen has some kind of artifacting around the edges of objects. Main game seems to render fine, at least outside Skyview Temple.
![image](https://user-images.githubusercontent.com/66989235/127894138-6fa6d7e5-2c18-46be-a297-1002c32d3d25.png)
![image](https://user-images.githubusercontent.com/66989235/127894180-81f79b17-b636-4e67-aef0-7d9ae9232459.png)
Also, I can get a consistent hang when a Deku Baba opens its mouth. The video/rendering stops, but the game continues in the background.
![image](https://user-images.githubusercontent.com/66989235/127895486-7c56f56b-3b67-40ae-a46f-90e9214a61cc.png)
Stopping emulation and then attempting to restart the game results in a full crash.
```
00:00:00.013 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.014 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.014 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.015 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.016 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.031 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+b32f116
00:00:00.036 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.036 |N| Application Print: CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz ; 8 logical
00:00:00.036 |N| Application Print: RAM: Total 16318 MB ; Available 12019 MB
00:00:00.038 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.038 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:00.249 |N| Application LoadApplication: Using Firmware Version: 11.0.1
00:00:02.009 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA NVIDIA GeForce RTX 2070 (Vulkan v1.2.175, Driver v471.41.0.0)
00:00:02.681 |W| HLE.GuestThread.14 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:02.683 |W| HLE.GuestThread.14 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:02.684 |W| HLE.GuestThread.14 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.479 |W| HLE.GuestThread.18 KernelSvc PrintResult: MapSharedMemory64 returned error InvalidMemRange.
00:00:03.505 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.507 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.508 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.509 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.510 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.510 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.538 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.539 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.540 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.541 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.542 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.543 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.548 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:03.581 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:02:17.903 |W| HLE.GuestThread.16 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:02:17.903 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.903 |W| HLE.GuestThread.14 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.18 KernelSvc PrintResult: SendSyncRequest64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.17 KernelSvc PrintResult: WaitSynchronization64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.904 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:02:17.919 |E| HLE.OsThread.12 SurfaceFlinger DequeueBuffer: No available buffer slots
00:02:17.919 |E| HLE.OsThread.12 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
00:00:00.073 |N| Application LoadApplication: Using Firmware Version: 11.0.1
00:00:01.273 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorInitializationFailed".
   at Ryujinx.Graphics.Vulkan.VulkanInitialization.CreateDevice(Vk api, PhysicalDevice physicalDevice, UInt32 queueFamilyIndex, String[] supportedExtensions, UInt32 queueCount)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.SetupContext(GraphicsDebugLevel logLevel, String[] requiredExtensions)
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.Initialize(GraphicsDebugLevel logLevel)
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

2021-08-02 16:51 UTC, scese250 commented
```
 00:00:00.043 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+b32f116
00:00:00.049 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.049 |N| Application Print: CPU: AMD Ryzen 5 2600 Six-Core Processor ; 12 logical
00:00:00.049 |N| Application Print: RAM: Total 16310 MB ; Available 11003 MB
00:00:00.051 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.051 |N| Application PrintSystemInfo: Launch Mode: UserProfile
```

AMD Driver: 21.3.1
Windows 10 20H2

I don't know if someone reported it on Discord but Xenoblade 1 crash at boot and 2 crash at loading save.

Xenoblade 1
[Ryujinx_1.0.0+b32f116_2021-08-02_12-40-34.log](https://github.com/Ryujinx/Ryujinx/files/6918419/Ryujinx_1.0.0%2Bb32f116_2021-08-02_12-40-34.log)

Xenoblade 2
[Ryujinx_1.0.0+b32f116_2021-08-02_12-43-27.log](https://github.com/Ryujinx/Ryujinx/files/6918422/Ryujinx_1.0.0%2Bb32f116_2021-08-02_12-43-27.log)

I've disabled the mods and purge the PTC cache for testing and the result is the same.

2021-08-02 18:11 UTC, molitar commented
> ry deleting PPTC and Shader cache, sometimes games crash when they have older files that are being loaded in o

Already did that in fact it had to redownload the entire cache last time I ran it after driver update.  Took a while at it's size.

2021-08-02 19:00 UTC, jroberts2010 commented
![2021-08-02 (1)](https://user-images.githubusercontent.com/9343716/127910209-819547ef-53d7-4424-936c-4c1b9d1a3a49.png)
![2021-08-02 (2)](https://user-images.githubusercontent.com/9343716/127910218-76cc628e-9b76-46cb-b4f1-2f89fd9ac43f.png)
![2021-08-02](https://user-images.githubusercontent.com/9343716/127910224-47f766ff-1f18-46e2-81b5-e2c59d42b882.png)

The shadows in FE3H are corrupted. It sort of follows the camera around when you're standing still. Those three areas are the easiest places to see it. Tested on latest AMD drivers and ryu vulkan build, WIN 10.

2021-08-02 19:22 UTC, Fogg12 commented
![image](https://user-images.githubusercontent.com/87782299/127912245-20cb9700-3f35-467c-8aaf-67abc18b291d.png)
In Super Mario Odyssey the water is broken. I am using the latest AMD Drivers (21.7.2) and I have an RX 570. In the screenshot I am using the Vulkan and Threaded GAL Build but this also happens on just Vulkan.

2021-08-03 09:35 UTC, rainy-lam commented
![Ryujinx_56rK7DXHRs](https://user-images.githubusercontent.com/12071755/127991186-f6364e41-b344-4c95-9a9a-38a9c72f8c9e.png)
![Ryujinx_TxRDktz8uL](https://user-images.githubusercontent.com/12071755/127991227-788cdf96-fddb-452e-99ee-dffeac106265.jpg)

There are some graphic issues on Monster Hunter Rise.
OS: Windows 10 21H1
GPU: AMD Radeon RX570
Driver: AMD 21.3.1

[Ryujinx_1.0.0+8c45f85_2021-08-03_16-37-33.log](https://github.com/Ryujinx/Ryujinx/files/6923002/Ryujinx_1.0.0%2B8c45f85_2021-08-03_16-37-33.log)

2021-08-03 11:29 UTC, sneik15 commented
Crash on start Xenonable Chronicles Definitive Edition v1.0
[Ryujinx_1.0.0+8c45f85_2021-08-03_13-13-26.log](https://github.com/Ryujinx/Ryujinx/files/6923694/Ryujinx_1.0.0%2B8c45f85_2021-08-03_13-13-26.log)

OS: Windows 10 21H1
GPU: AMD Radeon RX 6900 XT
Driver: AMD 21.7.2

2021-08-04 21:21 UTC, MutantAura commented
Just a couple of games tested here.

R5 5600X
RTX 3070 FE
32GB 3600MHz DDR4
Windows Version 10.0.19042 Build 19042

**Pokemon Mystery Dungeon: Rescue Team DX**

Some very obvious problems with pop-in and flicker on some in-game assets. Not as bad in the overworld but get's very buggy while in dungeons. Note these tests were on an older version of the PR but as I have trouble even getting this game to boot I have no reason to believe they're fixed.
[Video](https://youtu.be/4HDYbj7MRcQ)
Couple of screenshots: 
![image](https://user-images.githubusercontent.com/44103205/128255793-9544ae74-d26a-4e46-a935-9e1943b08267.png)
![image](https://user-images.githubusercontent.com/44103205/128255840-719b7d00-2ba9-4953-be30-c587321977b1.png)
![image](https://user-images.githubusercontent.com/44103205/128255870-59675e83-13e7-4599-95f1-9514eff0f46a.png)
For those who havent played the game the house is not meant to be here...
![image](https://user-images.githubusercontent.com/44103205/128256005-42243b8f-bbdf-47ec-8509-f1ccca538e24.png)
Dungeons basically unrecognisable 
![image](https://user-images.githubusercontent.com/44103205/128256059-2715c197-03bc-498d-9f40-b2047f701de6.png)


**Super Smash Bros. Ultimate**

Overall good here, no visual artifacts that I can see and even some graphical OGL glitches such as colour issues on Pokemon stadium are fixed. Only thing I saw is the menu. 
OGL: 
![image](https://user-images.githubusercontent.com/44103205/128256339-65536828-04bf-4cdf-ad35-377c5eaa6c15.png)
Vulkan:
![image](https://user-images.githubusercontent.com/44103205/128256429-f47b7ac8-dd22-44e4-90fd-c319c7604559.png)

Even WoL is working fine which I had a bet would have some kind of issue ;)
![image](https://user-images.githubusercontent.com/44103205/128256571-7164b4f2-b0ba-49fc-8252-318de1134471.png)

2021-08-05 00:39 UTC, gdkchan commented
> 
> 
> ![image](https://user-images.githubusercontent.com/87782299/127912245-20cb9700-3f35-467c-8aaf-67abc18b291d.png)
> In Super Mario Odyssey the water is broken. I am using the latest AMD Drivers (21.7.2) and I have an RX 570. In the screenshot I am using the Vulkan and Threaded GAL Build but this also happens on just Vulkan.

Should be fixed on 9153a1a68b402ae51a4db49116d93146ab9921f4.

2021-08-05 01:19 UTC, KookiesGH commented
Skyward Sword HD still crashing on Deku Baba mouth opening as of c54b4c6
Windows 10 20H2, NVIDIA RTX 2070 471.41

[Ryujinx_1.0.0+c54b4c6_2021-08-04_19-09-26.log](https://github.com/Ryujinx/Ryujinx/files/6935259/Ryujinx_1.0.0%2Bc54b4c6_2021-08-04_19-09-26.log)
[Video demonstration](https://streamable.com/3o5tiu)

2021-08-05 02:12 UTC, RinMaru commented
![ryujinx_capture_2021-08-04_22-07-27](https://user-images.githubusercontent.com/15071652/128279716-230a8f8c-a3bd-4008-8630-0afb078441a6.jpg)

Ryujinx_1.0.0+c54b4c6
Windows 11 Beta
Ryzen 5 5600X
RX 480 4GB
20GB DDR4

2021-08-05 02:57 UTC, rolmerin commented
Xenoblade 2 V2.1.0
All character models are invisible.
![1](https://user-images.githubusercontent.com/88316690/128283451-fa85c0cd-7a90-4689-808b-07778aea050c.jpg)

However,when pulling up the camera(right stick),the character will visible again.
![2](https://user-images.githubusercontent.com/88316690/128283740-c72d1f53-caf6-48bb-a867-e232229017fb.jpg)

Tested in Windows 10,AMD RX590.
[Ryujinx_1.0.0+c54b4c6_2021-08-05_10-26-38.log](https://github.com/Ryujinx/Ryujinx/files/6935618/Ryujinx_1.0.0%2Bc54b4c6_2021-08-05_10-26-38.log)

2021-08-05 03:19 UTC, gdkchan commented
> 
> 
> Just a couple of games tested here.
> 
> R5 5600X
> RTX 3070 FE
> 32GB 3600MHz DDR4
> Windows Version 10.0.19042 Build 19042
> 
> **Pokemon Mystery Dungeon: Rescue Team DX**
> 
> Some very obvious problems with pop-in and flicker on some in-game assets. Not as bad in the overworld but get's very buggy while in dungeons. Note these tests were on an older version of the PR but as I have trouble even getting this game to boot I have no reason to believe they're fixed.
> [Video](https://youtu.be/4HDYbj7MRcQ)
> Couple of screenshots:
> ![image](https://user-images.githubusercontent.com/44103205/128255793-9544ae74-d26a-4e46-a935-9e1943b08267.png)
> ![image](https://user-images.githubusercontent.com/44103205/128255840-719b7d00-2ba9-4953-be30-c587321977b1.png)
> ![image](https://user-images.githubusercontent.com/44103205/128255870-59675e83-13e7-4599-95f1-9514eff0f46a.png)
> For those who havent played the game the house is not meant to be here...
> ![image](https://user-images.githubusercontent.com/44103205/128256005-42243b8f-bbdf-47ec-8509-f1ccca538e24.png)
> Dungeons basically unrecognisable
> ![image](https://user-images.githubusercontent.com/44103205/128256059-2715c197-03bc-498d-9f40-b2047f701de6.png)

Fixed on 30cf88a4f66d77fe1ea09610e58e6cfd9098bbfe.

2021-08-05 06:24 UTC, scese250 commented
```
00:00:00.046 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+da65ba0
00:00:00.053 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.053 |N| Application Print: CPU: AMD Ryzen 5 2600 Six-Core Processor ; 12 logical
00:00:00.053 |N| Application Print: RAM: Total 16310 MB ; Available 9493 MB
00:00:01.446 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD Radeon R9 200 Series (Vulkan v1.2.170, Driver v2.0.179)
```

Xenoblade 2 still crash after loading save with a R9 280x 3GB. Driver version is 21.5.2 (sadly recently AMD dropped support for that series).

[Ryujinx_1.0.0+da65ba0_2021-08-05_02-15-56.log](https://github.com/Ryujinx/Ryujinx/files/6936365/Ryujinx_1.0.0%2Bda65ba0_2021-08-05_02-15-56.log)

2021-08-05 12:33 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/PipelineFull.cs
> +                QueryResultFlags.QueryResult64Bit);
```suggestion
                QueryResultFlags.QueryResult64Bit | QueryResultFlags.QueryResultWaitBit);
```
The counter queue expects this command to always copy the query result. It seems that this copy can be skipped if the result is not available yet.

This should fix the counter queue getting stuck on AMD. Leischii has reported it fixing counter queue crashes on MK8D, but I'd recommend testing Splatoon 2 to see if the ink works.

2021-08-05 15:23 UTC, GamerzHell9137 commented
> 
> 
> > **Pokemon Mystery Dungeon: Rescue Team DX**
> > Some very obvious problems with pop-in and flicker on some in-game assets. Not as bad in the overworld but get's very buggy while in dungeons. Note these tests were on an older version of the PR but as I have trouble even getting this game to boot I have no reason to believe they're fixed.
> 
> Fixed on [30cf88a](https://github.com/Ryujinx/Ryujinx/commit/30cf88a4f66d77fe1ea09610e58e6cfd9098bbfe).

Awesome, this affected a lot of Unity games. RF5 doesn't have the issue either now!

2021-08-05 18:49 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineFull.cs
> +                QueryResultFlags.QueryResult64Bit);
fwiw I tried this on NVIDIA before, and it didn't fix the splatoon 2 crash.

2021-08-05 21:37 UTC, GamerzHell9137 commented
Is 9b63b60 supposed to fix Query Result timed out?

2021-08-05 21:38 UTC, gdkchan commented
> 
> 
> Is [9b63b60](https://github.com/Ryujinx/Ryujinx/commit/9b63b60fe593ca56519b9e31e509666ae1623a01) supposed to fix Query Result timed out?

Only on AMD.

2021-08-06 00:59 UTC, RyzenDew commented
![image](https://user-images.githubusercontent.com/84041391/128439723-b318d253-8705-4956-8fa8-15c8d1275579.png)
Issue in UE3 games like outlast 2 
```
Lighting is broken 
screen space reflections also broken
textures are corrupt
handheld makes the lighting brighter but not normal lighting.
```

```
00:01:04.315 |W| Gpu Log: Shader translator: Invalid instruction at 0x000030 (0x50F41BA06FF70107).
00:01:04.315 |W| Gpu Log: Shader translator: Invalid instruction at 0x000078 (0x50F41BA060670107).
00:01:04.315 |W| Gpu Log: Shader translator: Invalid instruction at 0x0001A8 (0x50F41BA060470107).
```

[Ryujinx_1.0.0-dirty_2021-08-05_21-53-01.log](https://github.com/Ryujinx/Ryujinx/files/6942364/Ryujinx_1.0.0-dirty_2021-08-05_21-53-01.log)

2021-08-06 04:40 UTC, molitar commented
Unable to load saved game crashes 99% of the time.  The 1% it loads it will run fine than crash later during the game.

First Log game loaded fine than crashed during game play.

[Ryujinx_1.0.0+0a03a55_2021-08-05_18-01-17.log](https://github.com/Ryujinx/Ryujinx/files/6943017/Ryujinx_1.0.0%2B0a03a55_2021-08-05_18-01-17.log)

Second Log game fails to load.. just when it's near finishing the load it crashes.

[Ryujinx_1.0.0+841f685_2021-08-05_23-29-21.log](https://github.com/Ryujinx/Ryujinx/files/6943022/Ryujinx_1.0.0%2B841f685_2021-08-05_23-29-21.log)

2021-08-06 15:43 UTC, Katafiora commented
In Fire Emblem: Three Houses, I think there's lightning "missing"? The first picture is from original gameplay, while the second one is from Ryujinx:
![1](https://user-images.githubusercontent.com/88550054/128535832-b1624156-d13d-4405-8e1e-eadc0c925210.png)
![2](https://user-images.githubusercontent.com/88550054/128535866-ba0c3673-de85-4824-ad16-f18aa9050bff.png)
Windows 21H1 - Ryzen 3600 - 5700XT - 21.7.2

2021-08-06 23:57 UTC, Thog commented
Added support for Vulkan on ``ryujinx-headless-sdl2` releases.

This can be selected via the commandline argument ``--graphics-backend Vulkan``.

2021-08-07 11:25 UTC, allucbr commented
![image](https://user-images.githubusercontent.com/27929170/128598599-738f8d1b-7e5c-4fa2-87af-bf41fb47a3e8.png)
Error on CRT

2021-08-07 11:27 UTC, allucbr commented
![image](https://user-images.githubusercontent.com/27929170/128598615-1f609a92-4f10-4724-899f-c214df6284c8.png)
Version 2fdc60e X 580 21.7.2 DRIVER Vulkan

2021-08-07 11:29 UTC, allucbr commented
![image](https://user-images.githubusercontent.com/27929170/128598681-664838ba-031c-4562-9b3a-81a615a3f41f.png)
Version 2fdc60e X 580 21.7.2 DRIVER Vulkan

2021-08-07 11:57 UTC, allucbr commented
![image](https://user-images.githubusercontent.com/27929170/128599348-8df9e95e-ac6b-432a-a98a-949d5b2c428d.png)
issue on smoke

2021-08-07 11:58 UTC, allucbr commented
Issue on smoke
![image](https://user-images.githubusercontent.com/27929170/128599395-82eb151c-56aa-4ea8-b7c1-66f41ba203f7.png)

2021-08-07 12:02 UTC, allucbr commented
the smoke from the chimneys is overlaying the images
![image](https://user-images.githubusercontent.com/27929170/128599487-cc4fed49-9e85-4086-bf12-2b7263bccab7.png)

2021-08-07 12:07 UTC, allucbr commented
high reflection
![image](https://user-images.githubusercontent.com/27929170/128599619-695a6b41-7753-4e87-8523-3502ded93feb.png)

2021-08-07 12:09 UTC, allucbr commented
![image](https://user-images.githubusercontent.com/27929170/128599664-1eab90c3-e87e-4f38-b69f-b3d887eed93e.png)

2021-08-08 04:03 UTC, yuwenhua653 commented
Broken the color of some games on OpenGL
This PR
![ryujinx_capture_2021-08-08_12-00-35](https://user-images.githubusercontent.com/30205483/128620268-b2499886-fdc5-442d-b5f1-647c4306dbd8.png)
Mainline
![ryujinx_capture_2021-08-08_12-01-29](https://user-images.githubusercontent.com/30205483/128620284-087e5367-2c79-45cb-b4f7-ccb75e61948d.png)

2021-08-08 04:18 UTC, gdkchan commented
I'm aware, the BGRA swap code is currently commented out on the shader (as Vulkan does not need it since it supports BGRA natively). I will re-enable it later.

2021-08-08 09:40 UTC, seb-pau commented
Mario Golf keeps crashing for me at the 5th or 6th hole of the second course. (First course work fine).

[Full log](https://pastebin.com/fLTQmYn8)

System Info
```
00:00:00.042 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+2fdc60e
00:00:00.047 |N| Application Print: Operating System: Microsoft Windows 10.0.22000 (X64)
00:00:00.047 |N| Application Print: CPU: AMD Ryzen 5 5600X 6-Core Processor ; 12 logical
00:00:00.047 |N| Application Print: RAM: Total 32691 MB ; Available 20738 MB
00:00:00.048 |N| Application PrintSystemInfo: Logs Enabled: Warning, Error
00:00:00.048 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.334 |N| Application LoadApplication: Using Firmware Version: 11.0.1
00:00:01.127 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD Radeon RX 6800 (Vulkan v1.2.178, Driver v2.0.188)
```

Error 
```
00:13:00.834 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorUnknown".
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.DescriptorPoolHolder..ctor(Vk api, Device device)
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.GetPool(Vk api, Int32 requiredCount)
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.AllocateDescriptorSets(Vk api, ReadOnlySpan`1 layouts)
   at Ryujinx.Graphics.Vulkan.DescriptorSetManager.AllocateDescriptorSet(Vk api, DescriptorSetLayout layout)
   at Ryujinx.Graphics.Vulkan.PipelineLayoutCacheEntry.GetNewDescriptorSetCollection(VulkanGraphicsDevice gd, Int32 commandBufferIndex, Int32 setIndex, Boolean& isNew)
   at Ryujinx.Graphics.Vulkan.DescriptorSetUpdater.UpdateAndBindDescriptorSets(CommandBufferScoped cbs, PipelineBindPoint pbp)
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp)
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance)
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.PerformDeferredDraws()
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.Render()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

There are also multiple errors about `extension not supported: GL_EXT_texture_shadow_lod` during gameplay.

2021-08-09 11:05 UTC, rolmerin commented
Xenoblade 2
There is a strange shadow persistently in the screen.Whenever moving the character or camera,the shadow follows.
In some relatively dark places,this issue is not too noticeable.
There is no such issue in opengl.
![3](https://user-images.githubusercontent.com/88316690/128696254-8e575322-6faf-4f45-97e0-04b5a44e0739.jpg)

No issue in Opengl
![4](https://user-images.githubusercontent.com/88316690/128696327-242dcebb-f00c-45a3-9622-f17f04a49ad4.jpg)

[Ryujinx_1.0.0+2fdc60e_2021-08-09_18-34-50.log]
(https://github.com/Ryujinx/Ryujinx/files/6953904/Ryujinx_1.0.0%2B2fdc60e_2021-08-09_18-34-50.log)

2021-08-09 15:10 UTC, Dragonballlover commented
astral chain 
astral chain has some unusal bug i face in vulkan build 
when you start the game then i charcter is missing in title screen you can see below for comparison !! 


Latest Master Build
![Screenshot (118)](https://user-images.githubusercontent.com/66829293/128726939-5b0d0440-837d-4bdc-a67a-e7df4ea6a237.png)

Vulkan Build
![Screenshot (26)](https://user-images.githubusercontent.com/66829293/128726988-1d890acd-7603-43d6-a516-11c81e0e15e7.png)


also having a graphic glicthes in first mission when you shoot your enimes on bike and then when they died a strange black graphic gliches apper !! 

vulkan build
![Screenshot (28)](https://user-images.githubusercontent.com/66829293/128727587-5f9c95da-a161-4fb4-b329-d5a68a9f054e.png)
![Screenshot (29)](https://user-images.githubusercontent.com/66829293/128727593-60ea6344-2bad-46d7-8091-428700936605.png)
![Screenshot (39)](https://user-images.githubusercontent.com/66829293/128727597-6ff59856-97ff-426c-83b9-ef9e5da672f0.png)

Also Having Strange Bright Light issues at some random cases!!
![Screenshot (42)](https://user-images.githubusercontent.com/66829293/128727824-068c4035-3778-4ceb-97f9-38919382b08b.png)

And One more Thing Astral Chain in vulkan Build Uses More Ram !! on vukhan it uses About 10 Gb of ram but on master it only uses 7Gb of ram !!

Master Build
![Screenshot (119)](https://user-images.githubusercontent.com/66829293/128728607-93607d1d-a6bd-47c2-8d28-9508bbe46259.png)

Vulkan Build
![Screenshot (48)](https://user-images.githubusercontent.com/66829293/128728664-bb5858df-5803-4683-b5b8-972661a07185.png)


Some More Graphics Glitches when you beat enemies and whe they die they have different colour gliches!!

Vulkan Build
![Screenshot (49)](https://user-images.githubusercontent.com/66829293/128729273-3dad3241-b1a1-4cb0-b8eb-3f0270efd8df.png)
![Screenshot (53)](https://user-images.githubusercontent.com/66829293/128729279-54c0b82c-8bfd-469e-9e5b-449f9079c506.png)


Sorry For Bad English!!

2021-08-09 15:19 UTC, Dragonballlover commented
Hollow Knight
In Hollow knight There Are many gliches where your charcter color get white to black  !! Also at cutsense you also get also cutsense gliches where bulb and light get green color at the place of yellow!!

Vulkan Build
![Screenshot (54)](https://user-images.githubusercontent.com/66829293/128730202-775bb10d-049b-4d73-b24a-41b1ab57f974.png)


Starting Cutsense Gliches !!

![Screenshot (63)](https://user-images.githubusercontent.com/66829293/128730319-cb6fdf00-a090-4ec4-aab9-e6dc25d14c8b.png)
![Screenshot (64)](https://user-images.githubusercontent.com/66829293/128730324-7a90c951-ff4f-4536-8316-cb7ed9e77a64.png)
![Screenshot (60)](https://user-images.githubusercontent.com/66829293/128730537-8569873b-9c3e-4c94-bee7-5451022cbf46.png)
![Screenshot (62)](https://user-images.githubusercontent.com/66829293/128730546-ee455697-7e5e-489f-8e9a-4e2d406d4f11.png)


Ingame Gliches Vulkan Build!!
![Screenshot (73)](https://user-images.githubusercontent.com/66829293/128730774-8745d7d6-c35f-4386-a863-8297bddf4678.png)
![Screenshot (75)](https://user-images.githubusercontent.com/66829293/128730786-cf1a21ec-b126-450d-9997-8d9ac87f7810.png)
![Screenshot (81)](https://user-images.githubusercontent.com/66829293/128730788-0b797eef-66c7-44cf-b0d6-eb680fbf9804.png)
![Screenshot (84)](https://user-images.githubusercontent.com/66829293/128730789-6dbb3f29-869e-4eec-8686-067965595adb.png)
![Screenshot (87)](https://user-images.githubusercontent.com/66829293/128730794-bd350cf4-5a81-426c-8f00-8beeebc39e91.png)

2021-08-09 15:28 UTC, Dragonballlover commented
Ben 10 : Power Trip

This game is having so many graphic glitches compared to master !! but master also have many gliches like charcter voice is not coming,tunder lighting issue when you enter in portal,some river corruption !!

Master build
![Screenshot (115)](https://user-images.githubusercontent.com/66829293/128731411-cea71ff0-c6b0-4eeb-a6ab-28e43ac5aaad.png)

Vulkan Build
![Screenshot (97)](https://user-images.githubusercontent.com/66829293/128731531-cb372c42-7d53-45ee-a216-c3af4cc63ca9.png)
![Screenshot (92)](https://user-images.githubusercontent.com/66829293/128731623-eba86f1d-9048-4231-ab21-5c96ac50e4ed.png)


Some Unsual Gliches
![Screenshot (89)](https://user-images.githubusercontent.com/66829293/128731759-ab6a75cb-aed4-4c2f-b185-5838c23b2511.png)
![Screenshot (90)](https://user-images.githubusercontent.com/66829293/128731766-1ea2ff50-1a36-419d-87b8-425b70ab93d9.png)

Not Render Tunder Proper Compare to Switch tunder lighting freeze Some times at one Place !!
![Screenshot (107)](https://user-images.githubusercontent.com/66829293/128731976-6e43f652-c3ca-49c3-a936-3b3315814acd.png)
![Screenshot (109)](https://user-images.githubusercontent.com/66829293/128731987-dc4dcd30-072c-42b7-94db-e9d9f6512f2e.png)



Log-
[Ryujinx_1.0.0+2fdc60e_2021-08-09_18-57-19.log](https://github.com/Ryujinx/Ryujinx/files/6955582/Ryujinx_1.0.0%2B2fdc60e_2021-08-09_18-57-19.log)

2021-08-10 08:48 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs
>              public unsafe DescriptorSetCollection AllocateDescriptorSets(ReadOnlySpan<DescriptorSetLayout> layouts)
Unsafe can be dropped here now.

2021-08-10 13:59 UTC, Dragonballlover commented
Crash Bandicoot 4 has broken graphics !!

Starting Cutsense graphic has black screen!! 
![Screenshot (121)](https://user-images.githubusercontent.com/66829293/128880129-4ef5aca7-8024-4ae0-842d-a6bb48678a3c.png)

Ingame Graphic Broken!!
![Screenshot (123)](https://user-images.githubusercontent.com/66829293/128880138-f42a5f31-48e5-4de8-99d2-f22384db9969.png)

2021-08-10 14:13 UTC, Dragonballlover commented
Donkey Kong Tropical Freeze

Donkey Kong Waterfall water Is freeze and some water not rendering!!
 ![Screenshot (126)](https://user-images.githubusercontent.com/66829293/128880718-1b3912c8-634c-42b7-9725-dcf5755cb7e8.png)
![Screenshot (128)](https://user-images.githubusercontent.com/66829293/128881072-a25cbd00-4c4e-431b-9de4-906e9ed4d8af.png)

Water jump animation has delay time!!
![Screenshot (133)](https://user-images.githubusercontent.com/66829293/128881431-74f92cd3-6a0d-4ad7-9337-d859d3758259.png)

And there are strenge lighting issue in ingame!!

2021-08-10 14:24 UTC, Dragonballlover commented
New Super Lucky's Tale -

Shadow of Coins Has Broken -
![Screenshot (149)](https://user-images.githubusercontent.com/66829293/128883639-9e370dba-79c3-4697-83df-629ff33eae03.png)


Strange Gliche-
![Screenshot (151)](https://user-images.githubusercontent.com/66829293/128883736-4c9766e6-bff3-437b-aa8f-ff53ed8a2d9f.png)

Strange Character Shadow Broken-
![Screenshot (155)](https://user-images.githubusercontent.com/66829293/128884467-af3f4898-eb20-41c9-9cde-1d8a7038bd23.png)

2021-08-10 14:49 UTC, RinMaru commented
> Donkey Kong Tropical Freeze
> 
> Donkey Kong Waterfall water Is freeze and some water not rendering!!
> ![Screenshot (126)](https://user-images.githubusercontent.com/66829293/128880718-1b3912c8-634c-42b7-9725-dcf5755cb7e8.png)
> ![Screenshot (128)](https://user-images.githubusercontent.com/66829293/128881072-a25cbd00-4c4e-431b-9de4-906e9ed4d8af.png)
> 
> Water jump animation has delay time!!
> ![Screenshot (133)](https://user-images.githubusercontent.com/66829293/128881431-74f92cd3-6a0d-4ad7-9337-d859d3758259.png)
> 
> And there are strenge lighting issue in ingame!!
> 
> Log-
> [Ryujinx_1.0.0+88f1365_2021-08-10_18-19-35.log](https://github.com/Ryujinx/Ryujinx/files/6962428/Ryujinx_1.0.0%2B88f1365_2021-08-10_18-19-35.log)

cant even get ingame on AMD with this build
[Ryujinx_1.0.0+88f1365_2021-08-10_10-45-07.log](https://github.com/Ryujinx/Ryujinx/files/6962604/Ryujinx_1.0.0%2B88f1365_2021-08-10_10-45-07.log)

2021-08-15 03:30 UTC, george-ravelly commented
When I start any game with vulkan the ryujinx closes alone tested with openGL and opened normally, I'm using Linux and my processor is an i5 3570 and my GPU is the RX 550 log
[Ryujinx_1.0.0+88f1365_2021-08-15_00-29-04.log](https://github.com/Ryujinx/Ryujinx/files/6987459/Ryujinx_1.0.0%2B88f1365_2021-08-15_00-29-04.log)

2021-08-28 07:09 UTC, felixthecat1970 commented
Tested some games here some observed bugs:
Win10 20H2
Ryzen 3400g
A300 asrock
8gb ram / ssd nvme 256
driver 21.8.1 (minimal install)

Xenoblade Chronicles Definitive Edition (0100FF500E34A000) with no update / update 1.1.2 
*crash and close emulator
[xenoblade de.log](https://github.com/Ryujinx/Ryujinx/files/7070296/xenoblade.de.log)

One Piece: Pirate Warriors 3 Deluxe Edition (0100774009CF6000) *Global scenary shadow split in middle
![image](https://user-images.githubusercontent.com/12580269/131209799-301fe212-7ace-428d-96af-418bf5b30adb.png)

[one piece 3.log](https://github.com/Ryujinx/Ryujinx/files/7070310/one.piece.3.log)

2021-08-30 20:16 UTC, Lukas1860 commented
So I have a amd graphic card so opengl wont work out with me. I wanna play with my friends but i need to use this beta vulkan stuff. So am I able to have both: Multiplayer and vulkan? I already tried some copy pasting but it didnt work pls help :)

2021-08-31 01:03 UTC, SeibaEX commented
No backgrounds for SMT III Remaster.

![ryujinx_capture_2021-08-30_17-57-06](https://user-images.githubusercontent.com/45580586/131424729-9a672d7b-2433-48cf-9f6e-2604f0605bda.png)

![ryujinx_capture_2021-08-30_18-00-37](https://user-images.githubusercontent.com/45580586/131424895-b18cfd38-6b6b-4cbd-b8c2-bee3ab61d98f.png)

[Ryujinx_1.0.0+46ac808_2021-08-30_17-51-22.log](https://github.com/Ryujinx/Ryujinx/files/7080359/Ryujinx_1.0.0%2B46ac808_2021-08-30_17-51-22.log)

2021-08-31 13:25 UTC, jochuan commented
On Rune factory 4 Special edition i think that i found a regression that is happening after the PR was rebased. Those black dots are appearing in the title screen intro and on characters dialogue box as white dots that sometimes appear over some letters
![image](https://user-images.githubusercontent.com/11268912/131508652-42085003-58cc-4528-acdf-64e9fcdb207f.png)
![image](https://user-images.githubusercontent.com/11268912/131508712-2d2cd2ab-4cee-4e3f-99b7-ca2518d8a4e0.png)

The dragon still isn't being rendered correctly and some characters still have vertex explosions
![image](https://user-images.githubusercontent.com/11268912/131509159-619bd738-52f4-4083-8731-c263aa3e5278.png)
![image](https://user-images.githubusercontent.com/11268912/131509244-adb569dc-cefe-4ff8-8735-3bab69a667fc.png)
![image](https://user-images.githubusercontent.com/11268912/131509312-904a9c29-6fd9-4d1c-b7a3-44abc813cfc0.png)
![image](https://user-images.githubusercontent.com/11268912/131509359-e5fbea24-dfba-4c92-8452-db398fea8692.png)
![image](https://user-images.githubusercontent.com/11268912/131509389-6c5d2275-c2b9-42f4-8b19-d377e8f5156e.png)

Also for some reason after progressing a little more in the game tutorial the dragon renders correctly
![image](https://user-images.githubusercontent.com/11268912/131509683-ac6abfd2-b1de-40c7-99ad-5fd13997a9e1.png)

2021-08-31 16:31 UTC, dante3732 commented
## Bug Report
### What's the issue you encountered?
The game freezes in one place, after the cutscene when Luigi and the others take the elevator to the second floor.
![Снимок экрана (1898)](https://user-images.githubusercontent.com/66036249/131353917-d6f2c228-14c1-4e7e-8a84-6f7766bda4d1.png)
If you use the Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods, then the game does not freeze at this place, but hangs in front of the door to the garage in which you need to take vacuum cleaner.
![4](https://user-images.githubusercontent.com/66036249/131353908-d663ab08-e191-4374-81be-ed742ac4ec49.png)

### How can the issue be reproduced?
This happens without any special action.

### Log file
Log crash after elevator without Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods.
[Ryujinx_1.0.03a175b9_2021-08-28_14-55-58.log](https://github.com/Ryujinx/Ryujinx/files/7077363/Ryujinx_1.0.03a175b9_2021-08-28_14-55-58.log)
Log crash next to the door to the garage with Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods.
[Ryujinx_1.0.088f1365_2021-08-28_15-37-03.log](https://github.com/Ryujinx/Ryujinx/files/7077375/Ryujinx_1.0.088f1365_2021-08-28_15-37-03.log)

### Environment?

- Ryujinx version: 1.0.088f1365
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen R5 3600
  - GPU: AMD RX Vega 64
  - RAM: 16GB
- Applied Mods : Yes/No

### Additional context?
Without the mod, the game freezes after the elevator, and with the mod, the game freezes next to the door to the garage.

Also, the emulator can freeze randomly in different places.

2021-08-31 17:45 UTC, RyzenDew commented
> ## Bug Report
> 
> ### What's the issue you encountered?
> 
> The game freezes in one place, after the cutscene when Luigi and the others take the elevator to the second floor.
> 
> ![Снимок экрана (1898)](https://user-images.githubusercontent.com/66036249/131353917-d6f2c228-14c1-4e7e-8a84-6f7766bda4d1.png)
> 
> If you use the Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods, then the game does not freeze at this place, but hangs in front of the door to the garage in which you need to take vacuum cleaner.
> 
> ![4](https://user-images.githubusercontent.com/66036249/131353908-d663ab08-e191-4374-81be-ed742ac4ec49.png)
> 
> 
> 
> ### How can the issue be reproduced?
> 
> This happens without any special action.
> 
> 
> 
> ### Log file
> 
> Log crash after elevator without Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods.
> 
> [Ryujinx_1.0.03a175b9_2021-08-28_14-55-58.log](https://github.com/Ryujinx/Ryujinx/files/7077363/Ryujinx_1.0.03a175b9_2021-08-28_14-55-58.log)
> 
> Log crash next to the door to the garage with Disable-Lens-Flare, Disable-Dynamic-Resoluiton, Save fix mods.
> 
> [Ryujinx_1.0.088f1365_2021-08-28_15-37-03.log](https://github.com/Ryujinx/Ryujinx/files/7077375/Ryujinx_1.0.088f1365_2021-08-28_15-37-03.log)
> 
> 
> 
> ### Environment?
> 
> 
> 
> - Ryujinx version: 1.0.088f1365
> 
> - Game version: 1.0.0
> 
> - System Specs:
> 
>   - OS: Windows 10
> 
>   - CPU: Ryzen R5 3600
> 
>   - GPU: AMD RX Vega 64
> 
>   - RAM: 16GB
> 
> - Applied Mods : Yes/No
> 
> 
> 
> ### Additional context?
> 
> Without the mod, the game freezes after the elevator, and with the mod, the game freezes next to the door to the garage.
> 
> 
> 
> Also, the emulator can freeze randomly in different places.
> 
> 

Ryujinx does not need the save fix or to disable any effects all it needs is the disable dynamic res mod for performance. 

Best to not use the save fix anymore.

2021-08-31 21:47 UTC, RyzenDew commented
> > Ryujinx does not need the save fix or to disable any effects all it needs is the disable dynamic res mod for performance.
> 
> > 
> 
> > Best to not use the save fix anymore.
> 
> 
> 
> Without this patch, the emulator will freeze anyway.
> 
> [Ryujinx_1.0.0+8d9035a_2021-08-31_22-42-08.zip](https://github.com/Ryujinx/Ryujinx/files/7086534/Ryujinx_1.0.0%2B8d9035a_2021-08-31_22-42-08.zip)
> 
> 00:14:30.074 |E| Gpu AwaitResult: Error: Query result timed out. Took more than 5000 tries.
> 
> 00:14:35.088 |E| Gpu AwaitResult: Error: Query result timed out. Took more than 5000 tries.
> 
> 00:14:51.195 |I| Ptc Save: Saved Profiling Info (size: 88417 bytes, profiled functions: 26288).
> 
> 
Its about removing the mods not needed to property find the issue at hand thats all and the save fix was a hack needed only for yuzu at the time and should be removed from any mod site or github.

2021-09-01 00:14 UTC, felixthecat1970 commented
another batch tested games with bugs:
Win10 20H2
Ryzen 3400g
A300 asrock
8gb ram / ssd nvme 256
driver 21.8.1 (minimal install)

Lastest PR Vulkan build ryujinx-Release-1.0.0+8d9035a-win_x64 and ryujinx-headless-sdl2-Release-1.0.0+8d9035a-win_x64

Crimzon Clover World Explosion *infinite stuck in loading screen
[Crimzon Clover World Explosion v1.0.0 [01006b800de26000].log](https://github.com/Ryujinx/Ryujinx/files/7087328/Crimzon.Clover.World.Explosion.v1.0.0.01006b800de26000.log)

Psikyo Shooting Stars Alpha and Psikyo Shooting Stars Bravo *Black screen but background sound play
[Psikyo Shooting Stars Alpha v1.0.0 [01007a200f2e2000].log](https://github.com/Ryujinx/Ryujinx/files/7087330/Psikyo.Shooting.Stars.Alpha.v1.0.0.01007a200f2e2000.log)
[Psikyo Shooting Stars Bravo v1.0.0 [0100d7400f2e4000].log](https://github.com/Ryujinx/Ryujinx/files/7087331/Psikyo.Shooting.Stars.Bravo.v1.0.0.0100d7400f2e4000.log)

Ikaruga *Missing 3d baground / Random on-off 3d background in levels or flickers
![image](https://user-images.githubusercontent.com/12580269/131591176-602f4633-3e94-4c16-9da7-c3f42aee96f2.png)
[Ikaruga v1.0.2 [01009f20086a0000].log](https://github.com/Ryujinx/Ryujinx/files/7087341/Ikaruga.v1.0.2.01009f20086a0000.log)

GRANDIA HD Collection *Main menu starts  and play ok but loading grandia 1 or 2 game will stuck
[GRANDIA HD Collection v1.01.19 [0100e0600bbc8000] grandia 1 boot.log](https://github.com/Ryujinx/Ryujinx/files/7087360/GRANDIA.HD.Collection.v1.01.19.0100e0600bbc8000.grandia.1.boot.log)
[GRANDIA HD Collection v1.01.19 [0100e0600bbc8000] grandia 2 boot.log](https://github.com/Ryujinx/Ryujinx/files/7087361/GRANDIA.HD.Collection.v1.01.19.0100e0600bbc8000.grandia.2.boot.log)

apart, ryujinx-headless-sdl2-Release looks like have better (framepacing) instead ryujinx-Release QT sttuter (after shader build) in 60fps games (like 2d) but headless build has not "fullscreen" tag for test (already check --help but no command available) can i request --fullscreen enable command for headless build? thanks

2021-09-10 02:26 UTC, FaeTalan commented
On RE Zero, Rebecca's eyes are creepy red/pink (using vulkan). On main build they are fine (using opengl).

2021-09-12 09:35 UTC, notjokr commented
### What's the issue you encountered?

Various rendering errors throughout the game

Also, the resolution seems to dip back down to native frequently. (currently have it set to 3x)

### How can the issue be reproduced?

Pause menu explosion ([example](https://gfycat.com/teemingshadybrontosaurus), make sure you click the HD toggle on gfycat, it can't be seen otherwise)

Just enter the pause menu

Black elemental trails ([example 1](https://gfycat.com/distantmintycassowary), [example 2](https://gfycat.com/giganticdistinctamurstarfish))

Use any attack that leaves behind any sort of elemental trail (I know this one is mentioned already)

Green particles ([example 1](https://gfycat.com/essentialimperfectaxolotl), [example 2](https://gfycat.com/gaseousvioletconey))

The two easiest places to reproduce this are during the Void Termina fight, or using Marx's down special

Off pitch healing sound ([example](https://gfycat.com/uncomfortableperfectblobfish), you will need to unmute the clip to hear it)

I'm not really sure how to reliably reproduce this. It just happens sometimes, but not all the time

Greens Greens flickering ([example](https://gfycat.com/animatedsillyfruitfly))

Just get to the second half of the post-story level

2021-09-14 23:33 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.9.1 
Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
Graphics Backend: on
final Fantasy VII, Starlink Battle for Attlas and Haven close emulator

2021-09-14 23:35 UTC, Mou-Ikkai commented
> Win10 64 bits
> Sapphire Radeon RX 580 series X 4GB
> Ryzen 7 2700x
> 16GB ram
> driver 21.9.1
> Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
> Graphics Backend: on
> final Fantasy VII, Starlink Battle for Attlas and Haven close emulator

Yeah, AMD's latest driver broke Vulkan for quite a few applications.

2021-09-15 01:46 UTC, yuwenhua653 commented
With the latest AMD driver, the game will not start in VK

2021-09-21 01:37 UTC, AlfredoDore commented
unfortunately the emulator continues to close with the new AMD drive

2021-09-29 20:41 UTC, AlfredoDore commented
![imagem](https://user-images.githubusercontent.com/90729203/135343025-770a8cb9-abbf-473b-8211-5a29cd4d890d.png) 
![imagem](https://user-images.githubusercontent.com/90729203/135344179-101a5b5f-9774-473e-b7ae-897ce5b8c8d4.png)

Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.8.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
Graphics Backend: on
Haven has correct grass rendering, but it's black, Final Fantasy VII the screen is black and only the sound is left, Bulletstorm: Duke of Switch Edition there are several graphical flaws and you can only go to the building's façade, Mario Kart 8 Deluxe is starting, but when you go to play it closes on loading, the Crash Bandcount trilogy has very slow video loading and the game has graphical glitches, in Rockman 11 the characters' eyes turn black (somewhat bizarre), Mario Odyssey closes on startup the game, Baldo the guardians Owls has a slow problem, Sonic Colors takes time to load, the video is slow and when starting it closes the emulator, Starlink: Battle for Atlas doesn't even start, and I have graphical and slow problems in Zelda Link's Awakerning and Pokémon Shield, also graphical issues with Resident Evil series

2021-09-29 21:23 UTC, GamerzHell9137 commented
> 
> 
> ![imagem](https://user-images.githubusercontent.com/90729203/135343025-770a8cb9-abbf-473b-8211-5a29cd4d890d.png) ![imagem](https://user-images.githubusercontent.com/90729203/135344179-101a5b5f-9774-473e-b7ae-897ce5b8c8d4.png)
> 
> Win10 64 bits Sapphire Radeon RX 580 series X 4GB Ryzen 7 2700x 16GB ram driver 21.8.2 Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25 Graphics Backend: on Haven has correct grass rendering, but it's black, Final Fantasy VII the screen is black and only the sound is left, Bulletstorm: Duke of Switch Edition there are several graphical flaws and you can only go to the building's façade, Mario Kart 8 Deluxe is starting, but when you go to play it closes on loading, the Crash Bandcount trilogy has very slow video loading and the game has graphical glitches, in Rockman 11 the characters' eyes turn black (somewhat bizarre), Mario Odyssey closes on startup the game, Baldo the guardians Owls has a slow problem, Sonic Colors takes time to load, the video is slow and when starting it closes the emulator, Starlink: Battle for Atlas doesn't even start, and I have graphical and slow problems in Zelda Link's Awakerning and Pokémon Shield, also graphical issues with Resident Evil series

Disable AMD Image Sharpening to make the screen look normal.

2021-09-29 23:51 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.8.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
Graphics Backend: on
Crayon Shin-chan: Ora to Hakase no Natsuyasumi – Owaranai Nanokakan no Tabi apparently with almost no serious problem, sometimes there is a drop in yield and once in a while there is a problem in the shadows 
![imagem](https://user-images.githubusercontent.com/90729203/135363697-1e50aa67-11fd-4491-be9a-37604c0e1a4b.png)

2021-09-30 13:39 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.8.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
Graphics Backend: on
Disable AMD Image Sharpening 
graphically the Sakura Succubus game series is normal, but the animations are slow
Mindcell game looks fine, there are a few graphical defects like dark textures when objects are too far away and villain gets all white texture  
![imagem](https://user-images.githubusercontent.com/90729203/135464758-3b255ef9-3264-4ce8-a462-ebd140953aee.png) 
![imagem](https://user-images.githubusercontent.com/90729203/135465496-388f6598-9980-427c-952e-8f30becfa780.png)

2021-10-01 18:52 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.8.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
Graphics Backend: on
Disable AMD Image Sharpening
Super Mario 3D All Stars starts but only the audio is left, in Sonic Collors it is slow 
![imagem](https://user-images.githubusercontent.com/90729203/135671644-e3377f15-40ce-45df-9e56-8d62f087c794.png)
![imagem](https://user-images.githubusercontent.com/90729203/135671913-8453d9df-4688-41b7-a9d0-095de86694c9.png)

2021-10-02 12:07 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.8.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
Graphics Backend: on
Disable AMD Image Sharpening
the AM2R fan-made game which is a Metroid 2 makeover doesn't start (including in the regular version) and Zelda Link's Awakerning has a problem in the video where there is a black stripe in the left corner, during the game it looks like it goes very well, but it stays too slow and Mario Kart 8 closes when starting the game 
![imagem](https://user-images.githubusercontent.com/90729203/135715240-7f8e0070-676f-4cb2-8a95-22a16e73b339.png)
![imagem](https://user-images.githubusercontent.com/90729203/135715199-8b0e464a-940b-4317-a2de-2dfb92797250.png)
![imagem](https://user-images.githubusercontent.com/90729203/135715166-5454d94c-8ea5-4ab1-8574-1636a2c03aef.png)

2021-10-05 00:11 UTC, AlfredoDore commented
Metroid Dread keeps crashing despite not having nater at 60 fps, besides it has black textures (including the menu) in the non-platform part, the performance drops a lot 
![imagem](https://user-images.githubusercontent.com/90729203/135939606-b67ebb2d-4350-4ac1-9cb9-07048dedf931.png)

2021-10-07 18:49 UTC, AlfredoDore commented
@felixthecat1970 sorry, I'm new to this, the log would be that black block right? so I'll send it after some like Mario Kart 8, Starlink and Mario Odissey that are closing, I want to help find bugs in more games.

2021-10-08 01:51 UTC, felixthecat1970 commented
> 
> 
> @felixthecat1970 sorry, I'm new to this, the log would be that black block right? so I'll send it after some like Mario Kart 8, Starlink and Mario Odissey that are closing, I want to help find bugs in more games.

dont worry, only put .log files after each test you do (drop in in the post windows); also if you want involve more with testing, support etc you can access to discord server where many people, developers, user lurks, search main page https://ryujinx.org/ for invitation or use this direct link https://discord.gg/VkQYXAZ (uou need a free discord account)

2021-10-08 19:26 UTC, dante3732 commented
> > With the latest AMD driver, the game will not start in VK
> 
> This issue has been fixed now. I do believe it is a bug on the driver side, but I added a workaround on the emulator.
Metroid Dread work good, but densha de go crash in menu, before densha work better.

2021-10-08 23:19 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.8.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25
Graphics Backend: on
Disable AMD Image Sharpenin
I bring here a report of some games (I don't want to pollute the page) these are some of the previous games mentioned above, sorry if I didn't send Log before, but now here they are, some games are almost perfect just a few jaustes and that's it, but others like Mario Odyssey, Donkey Kong Country and Mario Kart 8 simply close, some are left with black screen (FFVII) and others just need more performance (RE0)
I highlight the Zelda Skyward Sword which looks like a sandstorm and the textures are weird 
![imagem](https://user-images.githubusercontent.com/90729203/136633341-a1551128-0800-4bad-b3a5-e3c9e1827caa.png)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-00-19.log](https://github.com/Ryujinx/Ryujinx/files/7314442/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-00-19.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-08-43.log](https://github.com/Ryujinx/Ryujinx/files/7314477/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-08-43.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-20-13.log](https://github.com/Ryujinx/Ryujinx/files/7314492/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-20-13.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-26-27.log](https://github.com/Ryujinx/Ryujinx/files/7314495/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-26-27.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-28-14.log](https://github.com/Ryujinx/Ryujinx/files/7314522/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-28-14.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-47-42.log](https://github.com/Ryujinx/Ryujinx/files/7314528/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-47-42.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-49-13.log](https://github.com/Ryujinx/Ryujinx/files/7314536/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-49-13.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-51-22.log](https://github.com/Ryujinx/Ryujinx/files/7314551/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-51-22.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_19-56-33.log](https://github.com/Ryujinx/Ryujinx/files/7314561/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_19-56-33.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_20-04-08.log](https://github.com/Ryujinx/Ryujinx/files/7314581/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_20-04-08.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_20-08-53.log](https://github.com/Ryujinx/Ryujinx/files/7314586/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_20-08-53.log)
[Ryujinx_1.0.0+a5c9e25_2021-10-08_20-12-35.log](https://github.com/Ryujinx/Ryujinx/files/7314591/Ryujinx_1.0.0%2Ba5c9e25_2021-10-08_20-12-35.log)

2021-10-08 23:27 UTC, MetrosexualGarbodor commented
> 
> 
> Win10 64 bits Sapphire Radeon RX 580 series X 4GB Ryzen 7 2700x 16GB ram driver 21.8.2 Lastest PR Vulkan build ryujinx-Release-1.0.0+a5c9e25

FYI, the PR has been updated. You should redownload it.

2021-10-08 23:30 UTC, AlfredoDore commented
@MetrosexualGarbodor so I'm going to take advantage and update the drivers

2021-10-09 14:07 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.10.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+1143880-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
although the photo shows Castlevania at 47fps, it's slow (like it's weighing on processing), AM2R the game is fine, except its loads are very slow (it's a fan-made game that's a renewal of Metroid II: Return from Samus) RE0 needs yield and has some flaws in the textures, in Shin Chan I can't capture the exact moment of the flaw, but the shadows on the left side are blinking, problem similar to Doraemon's, Cadnece of Hyrule needs yield 
![imagem](https://user-images.githubusercontent.com/90729203/136659259-003d4421-ec81-4b35-a06a-454513858078.png)
![imagem](https://user-images.githubusercontent.com/90729203/136659566-4683baf0-5df0-4fbb-80af-bf3a66678d66.png)
![imagem](https://user-images.githubusercontent.com/90729203/136659817-1d33b982-3fbe-4669-8e57-5d2113ab013b.png)
![imagem](https://user-images.githubusercontent.com/90729203/136659960-4d43a7e8-725d-4470-bac2-b1601d2599c8.png)
![imagem](https://user-images.githubusercontent.com/90729203/136660273-7adbfcea-da64-445a-ad29-cd4bbf7b2a2f.png)
![imagem](https://user-images.githubusercontent.com/90729203/136660792-ff471e88-5079-49ab-bedf-89a7d6d9c13e.png)

[Ryujinx_1.0.0+1143880_2021-10-09_10-51-12.log](https://github.com/Ryujinx/Ryujinx/files/7315729/Ryujinx_1.0.0%2B1143880_2021-10-09_10-51-12.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-37-48.log](https://github.com/Ryujinx/Ryujinx/files/7315711/Ryujinx_1.0.0%2B1143880_2021-10-09_10-37-48.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-47-03.log](https://github.com/Ryujinx/Ryujinx/files/7315717/Ryujinx_1.0.0%2B1143880_2021-10-09_10-47-03.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-32-05.log](https://github.com/Ryujinx/Ryujinx/files/7315696/Ryujinx_1.0.0%2B1143880_2021-10-09_10-32-05.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-26-02.log](https://github.com/Ryujinx/Ryujinx/files/7315679/Ryujinx_1.0.0%2B1143880_2021-10-09_10-26-02.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-01-11.log](https://github.com/Ryujinx/Ryujinx/files/7315653/Ryujinx_1.0.0%2B1143880_2021-10-09_10-01-11.log)
[Ryujinx_1.0.0+1143880_2021-10-09_09-47-32.log](https://github.com/Ryujinx/Ryujinx/files/7315602/Ryujinx_1.0.0%2B1143880_2021-10-09_09-47-32.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-17-29.log](https://github.com/Ryujinx/Ryujinx/files/7315656/Ryujinx_1.0.0%2B1143880_2021-10-09_10-17-29.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-19-33.log](https://github.com/Ryujinx/Ryujinx/files/7315659/Ryujinx_1.0.0%2B1143880_2021-10-09_10-19-33.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-23-19.log](https://github.com/Ryujinx/Ryujinx/files/7315666/Ryujinx_1.0.0%2B1143880_2021-10-09_10-23-19.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-50-00.log](https://github.com/Ryujinx/Ryujinx/files/7315718/Ryujinx_1.0.0%2B1143880_2021-10-09_10-50-00.log)
[Ryujinx_1.0.0+1143880_2021-10-09_10-57-40.log](https://github.com/Ryujinx/Ryujinx/files/7315751/Ryujinx_1.0.0%2B1143880_2021-10-09_10-57-40.log)

2021-10-10 07:01 UTC, benderscruffy commented
Donkey Kong Country: Tropical Freeze crashes out after you press L and R to start the game
[Ryujinx_1.0.0+1143880_2021-10-10_14-55-48.log](https://github.com/Ryujinx/Ryujinx/files/7317021/Ryujinx_1.0.0%2B1143880_2021-10-10_14-55-48.log)

2021-10-10 08:21 UTC, benderscruffy commented
Quest of Dungeons
missing the grid and cursor on the inventory screen
![Capture](https://user-images.githubusercontent.com/2696404/136688248-98843f5a-c8ea-40f5-9660-8a11fc7c0bfe.PNG)

2021-10-10 10:27 UTC, benderscruffy commented
Survival Z
map is blank with Vulkan backend
![Capture](https://user-images.githubusercontent.com/2696404/136691842-ceabda83-f5bb-44f5-973f-62b603cb9aca.PNG)

2021-10-10 20:55 UTC, EimaMei commented
Metroid Dread background is fully invisible in the menu a nd loading screens, but is somewhat transaprent in gameplay.
![image](https://user-images.githubusercontent.com/69605234/136712711-4cc7cce9-26a9-4968-8cba-fd3d9178b10c.png)
![image](https://user-images.githubusercontent.com/69605234/136712714-44c44545-6249-4bb2-b0b1-df5bc0bf9508.pn
[Ryujinx_1.0.0+88f1365_2021-10-10_23-48-40.log](https://github.com/Ryujinx/Ryujinx/files/7318233/Ryujinx_1.0.0%2B88f1365_2021-10-10_23-48-40.log)
g

2021-10-12 19:33 UTC, KawaiiDinosaur commented
Windows 10 x64
Ryzen 3700X 
AMD Radeon 5700 XT, driver version 21.10.2

Visual artifacts that are present in some screens in Metroid Dread on OpenGL are fixed on Vulkan.

![ryujinx_capture_2021-10-12_16-05-12](https://user-images.githubusercontent.com/36821201/137017553-b504d6bb-a1bd-4c79-9bf7-61549d6e3b42.png)
![ryujinx_capture_2021-10-12_16-09-07](https://user-images.githubusercontent.com/36821201/137017560-baece52b-dbae-4067-a0e1-1aa609f78131.png)
![ryujinx_capture_2021-10-12_16-13-34](https://user-images.githubusercontent.com/36821201/137017561-1cdb729d-396b-4fd3-beac-e55807c45aed.png)

2021-10-13 00:48 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.10.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+1143880-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
 Mario Kart 8 Deluxe v1.7.2 when you update the emulator it can play, but if you close the emulator and open it again, it doesn't work anymore, I took advantage of the time to play and tested the steps, but there comes a time when it just closes, so the two log files are by Mario Kart, one when you can play and the other when you close 
[Ryujinx_1.0.0+1143880_2021-10-12_21-43-34.log](https://github.com/Ryujinx/Ryujinx/files/7333875/Ryujinx_1.0.0%2B1143880_2021-10-12_21-43-34.log)
[Ryujinx_1.0.0+1143880_2021-10-12_21-44-04.log](https://github.com/Ryujinx/Ryujinx/files/7333877/Ryujinx_1.0.0%2B1143880_2021-10-12_21-44-04.log)

2021-10-13 01:31 UTC, Iifriet commented
Windows 11
i7-10700k + RX 6800 XT (21.10.1
ryujinx-Release-1.0.0+1143880-win_x64

**Game: Hyrule Warriors: Definitive Edition**
**Issue:** Shadows appear incorrectly stretched when using the Vulkan renderer. Shadows are emulated properly using the OpenGL renderer.

**Vulkan**
![ryujinx_capture_2021-10-12_21-25-32](https://user-images.githubusercontent.com/92411953/137051075-a480bd42-2fc4-4278-98ad-fd8eacfb49e0.png)

**OpenGL**
![ryujinx_capture_2021-10-12_21-26-41](https://user-images.githubusercontent.com/92411953/137051079-7ae67b13-02ce-45c3-9da0-d7120c351b75.png)

2021-10-14 02:19 UTC, RomanKode commented
OS: Manjaro KDE
CPU: Ryzen 3700x
GPU: 5700XT

Game Tested: Monster Hunter Rise
Build: 1143880
Crashes while loading on startup.
[Ryujinx_1.0.0+1143880_2021-10-13_20-42-21.log](https://github.com/Ryujinx/Ryujinx/files/7342430/Ryujinx_1.0.0%2B1143880_2021-10-13_20-42-21.log)

2021-10-16 00:09 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.10.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+1143880-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Bulletstorm: Duke of Switch Edition has texture errors, loses a lot of performance, and closes on tower mission 
![imagem](https://user-images.githubusercontent.com/90729203/137565759-a3ce2031-636e-48bd-8234-32162b63f894.png)
![imagem](https://user-images.githubusercontent.com/90729203/137565721-d3044fa9-61ca-40a4-adaa-a0dcbc792231.png)
[Ryujinx_1.0.0+1143880_2021-10-15_21-01-12.log](https://github.com/Ryujinx/Ryujinx/files/7356431/Ryujinx_1.0.0%2B1143880_2021-10-15_21-01-12.log)

2021-10-16 05:26 UTC, ct9900 commented
Win10 64 bits
Sapphire Radeon RX 480 
Ryzen 7 1700x
32GB ram
ryujinx-Release-1.0.0+8c45f85-win_x64
ryujinx-Release-1.0.0+1143880-win_x64

**Both  have same question：when the character discharge a fireball，it will be crashed。**

[Ryujinx_1.0.0+8c45f85_2021-10-16_12-24-08.log](https://github.com/Ryujinx/Ryujinx/files/7357003/Ryujinx_1.0.0%2B8c45f85_2021-10-16_12-24-08.log)
[Ryujinx_1.0.0+1143880_2021-10-16_12-51-15.log](https://github.com/Ryujinx/Ryujinx/files/7356997/Ryujinx_1.0.0%2B1143880_2021-10-16_12-51-15.log)

2021-10-16 10:52 UTC, TerrXMaster commented
Win10 64 bits
Radeon RX 6700XT
Adrenalin 21.10.1
I7-4790K
16GB ram
ryujinx-Release-1.0.0+1143880-win_x64
New Pokemon Snap has a lot of graphical issues in the game's environment
It is playable with these glitches but it doesn't look so nice.
[Ryujinx_1.0.0+1143880_2021-10-16_12-36-27.log](https://github.com/Ryujinx/Ryujinx/files/7357408/Ryujinx_1.0.0%2B1143880_2021-10-16_12-36-27.log)
![New Pokemon Snap Graphical issue](https://user-images.githubusercontent.com/58532792/137584376-abfa1bbb-419c-4613-92a5-41044bc0530a.PNG)
![New Pokemon Snap Graphical issue 2](https://user-images.githubusercontent.com/58532792/137584377-4cf82b16-ad9d-4d5c-a3ae-20d3cc183bca.PNG)

2021-10-16 11:52 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.10.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+1143880-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Mortal Kombat 11 starts and you can even choose the character, but when it's time to fight it closes 
[Ryujinx_1.0.0+1143880_2021-10-16_08-45-13.log](https://github.com/Ryujinx/Ryujinx/files/7357481/Ryujinx_1.0.0%2B1143880_2021-10-16_08-45-13.log)

2021-10-20 12:46 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.10.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+1143880-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Highschool Romance has black screen 
Jack Axe has sprite problems and just like Arm2 (project made by fans of Metroid II renewal: Return of Samus) it takes a long time to start and transitions take too long. 
Ultra Age takes time to start, textures are blinking and has loss of performance (it is Unreal Engine) 
Wings of Darkness it takes a long time to start, there is loss of performance, the initial video is very slow and the textures are also blinking (it's also Unreal Engine) 
![imagem](https://user-images.githubusercontent.com/90729203/138094622-d1a24248-90f5-4424-9561-a00e2323f0bb.png)
![imagem](https://user-images.githubusercontent.com/90729203/138089717-0c7d27cf-9de6-4347-b45e-d63d315150e9.png)
![imagem](https://user-images.githubusercontent.com/90729203/138089112-acdccd9d-abcc-41b3-8718-73be17314f15.png)
![imagem](https://user-images.githubusercontent.com/90729203/138090790-0c011d44-e3b5-49e3-a54e-752926bd4135.png)
[Ryujinx_1.0.0+1143880_2021-10-20_09-01-18.log](https://github.com/Ryujinx/Ryujinx/files/7381012/Ryujinx_1.0.0%2B1143880_2021-10-20_09-01-18.log)
[Ryujinx_1.0.0+1143880_2021-10-20_08-51-55.log](https://github.com/Ryujinx/Ryujinx/files/7380984/Ryujinx_1.0.0%2B1143880_2021-10-20_08-51-55.log)
[Ryujinx_1.0.0+1143880_2021-10-20_09-05-12.log](https://github.com/Ryujinx/Ryujinx/files/7381043/Ryujinx_1.0.0%2B1143880_2021-10-20_09-05-12.log)
[Ryujinx_1.0.0+1143880_2021-10-20_09-11-57.log](https://github.com/Ryujinx/Ryujinx/files/7381075/Ryujinx_1.0.0%2B1143880_2021-10-20_09-11-57.log)
[Ryujinx_1.0.0+1143880_2021-10-20_09-32-53.log](https://github.com/Ryujinx/Ryujinx/files/7381288/Ryujinx_1.0.0%2B1143880_2021-10-20_09-32-53.log)

2021-10-24 00:42 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.10.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+c395fca-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Mario Kart has delayed audio and loss of performance, moreover when I close it and start it again the emulator closes, so both Mario Kart 8 logs (one working and the other not, I don't actually understand this problem ) 
Fuga has this serious problem of texture and loss of yield.
Donkey Kong Country: Tropical Freeze closes when starting the game 
AM2R (fan game Metroid II) starts the game fast, but the transitions are endless 
Demon's Tier has problems with fonts and sprites 
Sonic Collor's has income problem 
Zelda Skyway Sword has yield and texture issues 
Zelda Link's Awakerning As you move away from the beach you gain fps, however the fps rate is very unstable, one moment accelerates a lot and others have huge drops 
![imagem](https://user-images.githubusercontent.com/90729203/138575545-a6177352-e2f0-4947-b90a-c9bfa8fb3238.png)
![imagem](https://user-images.githubusercontent.com/90729203/138575563-922bf00d-84c3-4a25-a5b5-6b025e741dc9.png)
![imagem](https://user-images.githubusercontent.com/90729203/138575491-b56cc039-5d87-4657-80a0-99ae2fd69344.png)
![imagem](https://user-images.githubusercontent.com/90729203/138575513-665f16a2-8234-4967-928b-1b967564646a.png)
![imagem](https://user-images.githubusercontent.com/90729203/138575362-8589b387-44d7-43bb-b923-f04711ef062f.png)
![imagem](https://user-images.githubusercontent.com/90729203/138575328-24c12113-b139-4df7-ac15-08bb7bcb1e27.png) 
![imagem](https://user-images.githubusercontent.com/90729203/138575233-bc75a1e6-fa44-41ee-9336-b2261e5b5d08.png)
![imagem](https://user-images.githubusercontent.com/90729203/138575245-ae472e9a-32cf-4f49-8c5d-cb9875c037d2.png)
![imagem](https://user-images.githubusercontent.com/90729203/138575444-7c4a1562-6836-4c5e-9b34-1b2be5878cb7.png)

[Ryujinx_1.0.0+c395fca_2021-10-23_21-36-40.log](https://github.com/Ryujinx/Ryujinx/files/7403871/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-36-40.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-06-29.log](https://github.com/Ryujinx/Ryujinx/files/7403851/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-06-29.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-18-11.log](https://github.com/Ryujinx/Ryujinx/files/7403853/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-18-11.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-21-06.log](https://github.com/Ryujinx/Ryujinx/files/7403855/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-21-06.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-24-21.log](https://github.com/Ryujinx/Ryujinx/files/7403857/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-24-21.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-29-58.log](https://github.com/Ryujinx/Ryujinx/files/7403862/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-29-58.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-27-39.log](https://github.com/Ryujinx/Ryujinx/files/7403863/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-27-39.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-32-32.log](https://github.com/Ryujinx/Ryujinx/files/7403868/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-32-32.log)
[Ryujinx_1.0.0+c395fca_2021-10-23_21-39-13.log](https://github.com/Ryujinx/Ryujinx/files/7403878/Ryujinx_1.0.0%2Bc395fca_2021-10-23_21-39-13.log)

2021-11-06 11:30 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+c395fca-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
when activating the option ignore missing services Starlink It worked in it the videos are very slow and there are strange textures, also try to improve the audio  
![imagem](https://user-images.githubusercontent.com/90729203/140607594-9c170ee3-58b1-47d7-bb2d-bcf1b2301dbe.png)
[Ryujinx_1.0.0+c395fca_2021-11-06_08-09-59.log](https://github.com/Ryujinx/Ryujinx/files/7490350/Ryujinx_1.0.0%2Bc395fca_2021-11-06_08-09-59.log)

2021-11-07 12:02 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+c395fca-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Nickelodeon All Star's only the transitions and loads that are slow, I didn't see graphical errors 
![imagem](https://user-images.githubusercontent.com/90729203/140644015-3c8edfbb-856d-4acf-83ab-b41c560a48c7.png)
[Ryujinx_1.0.0+c395fca_2021-11-07_08-54-43.log](https://github.com/Ryujinx/Ryujinx/files/7492195/Ryujinx_1.0.0%2Bc395fca_2021-11-07_08-54-43.log)

2021-11-09 14:03 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+c395fca-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
even with the option ignore missing services activated, Mario Kart 8 on Vulkan does not start after the second time it is started, this option caused several games (including Starlink) to start, I recommend trying to fix this error and the error in the emulator clock 
![imagem](https://user-images.githubusercontent.com/90729203/140937318-3614d4f6-db93-4ba6-b28a-eb18ca5e274c.png)
[Ryujinx_1.0.0+c395fca_2021-11-09_10-47-14.log](https://github.com/Ryujinx/Ryujinx/files/7505216/Ryujinx_1.0.0%2Bc395fca_2021-11-09_10-47-14.log)
[Ryujinx_1.0.0+c395fca_2021-11-09_10-58-01.log](https://github.com/Ryujinx/Ryujinx/files/7505218/Ryujinx_1.0.0%2Bc395fca_2021-11-09_10-58-01.log)

2021-11-10 13:53 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Nintendo Switch Online N64 games do not start 
Nintendo Switch Online games Super Nintendo games work, but when making mods adding roms it simply closes 
Nintendo Switch Online games Nintendo 8-bit is working perfectly 
Crash Trilogy continues with broken textures and proportions, plus weird transitions and loads 
AM2R now it starts faster, but loading is very slow and I noticed some graphical errors on the intro screen, in addition to the screen transition 
Donkey Kong Country Tropical Freezing closes when starting the game 
Fuga improved a lot, but it has some flickering textures and a small drop in performance, in the 3D part it's to stay at 30 fps and in the 2D part it's 60 fps 
Haven has a slight drop in performance in the intro video, also a small drop in game performance and the most visible error is the grass rendering black 
Sonic Colours had a big improvement, but there's still loss of performance, I think it's a memory leak
Zelda A Link Awakerning indoors it's at the normal rate, but outdoors there's a big drop in yield, very noticeable when you go to the beach 
Zelda Skaway Sword there is this problem with textures 
Mario Kart has improved a lot, but needs more performance 
![imagem](https://user-images.githubusercontent.com/90729203/141121953-69023396-29c2-4e31-916f-95c20371c678.png)
![imagem](https://user-images.githubusercontent.com/90729203/141121865-a06b8e11-d049-4e4a-883c-699d6a027d3b.png)
![imagem](https://user-images.githubusercontent.com/90729203/141121366-daab3f47-d359-4795-93af-466a0028848a.png)
![imagem](https://user-images.githubusercontent.com/90729203/141121266-e489b5e1-70a4-4700-824c-52d0fc6d7e1e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141120760-eca4b91a-ebf0-42c2-804e-b075cc661cb1.png)
![imagem](https://user-images.githubusercontent.com/90729203/141120401-44afbbc3-5b43-47cd-9992-40c3a93042c9.png)
![imagem](https://user-images.githubusercontent.com/90729203/141119462-559af5d9-d280-4112-b317-63bf40eaac62.png)
![imagem](https://user-images.githubusercontent.com/90729203/141118633-3da76bac-d8ef-4f23-a2ba-93ae8fa30230.png)
![AM2R](https://user-images.githubusercontent.com/90729203/141117332-d11851f6-68ad-4e46-8b8c-fdb20244235f.jpg)
![imagem](https://user-images.githubusercontent.com/90729203/141117507-fe0f1246-41c3-443e-9c37-eb222e0abb68.png)
![imagem](https://user-images.githubusercontent.com/90729203/141116321-1f43cd56-d410-419b-8b93-e33e4a73dc3e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141116068-15a0760f-9984-4359-870d-74d371dc231d.png)
![imagem](https://user-images.githubusercontent.com/90729203/141115600-c66ad230-ec98-4cfc-95df-e68e39be0053.png)
![imagem](https://user-images.githubusercontent.com/90729203/141115070-c1bb7a77-8ab7-4d61-989b-559b62330a0e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141114278-fd6bd088-5d66-4705-9fff-0a25972945f1.png)
[Ryujinx_1.0.0+07e1466_2021-11-10_09-37-19.log](https://github.com/Ryujinx/Ryujinx/files/7512717/Ryujinx_1.0.0%2B07e1466_2021-11-10_09-37-19.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_09-36-05.log](https://github.com/Ryujinx/Ryujinx/files/7512719/Ryujinx_1.0.0%2B07e1466_2021-11-10_09-36-05.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_09-37-19.log](https://github.com/Ryujinx/Ryujinx/files/7512762/Ryujinx_1.0.0%2B07e1466_2021-11-10_09-37-19.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_09-44-54.log](https://github.com/Ryujinx/Ryujinx/files/7512786/Ryujinx_1.0.0%2B07e1466_2021-11-10_09-44-54.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_09-48-34.log](https://github.com/Ryujinx/Ryujinx/files/7512817/Ryujinx_1.0.0%2B07e1466_2021-11-10_09-48-34.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_09-54-08.log](https://github.com/Ryujinx/Ryujinx/files/7512886/Ryujinx_1.0.0%2B07e1466_2021-11-10_09-54-08.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_10-03-09.log](https://github.com/Ryujinx/Ryujinx/files/7512892/Ryujinx_1.0.0%2B07e1466_2021-11-10_10-03-09.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_10-05-01.log](https://github.com/Ryujinx/Ryujinx/files/7512911/Ryujinx_1.0.0%2B07e1466_2021-11-10_10-05-01.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_10-09-31.log](https://github.com/Ryujinx/Ryujinx/files/7512954/Ryujinx_1.0.0%2B07e1466_2021-11-10_10-09-31.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_10-15-01.log](https://github.com/Ryujinx/Ryujinx/files/7512984/Ryujinx_1.0.0%2B07e1466_2021-11-10_10-15-01.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_10-21-23.log](https://github.com/Ryujinx/Ryujinx/files/7513029/Ryujinx_1.0.0%2B07e1466_2021-11-10_10-21-23.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_10-27-50.log](https://github.com/Ryujinx/Ryujinx/files/7513055/Ryujinx_1.0.0%2B07e1466_2021-11-10_10-27-50.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_10-31-10.log](https://github.com/Ryujinx/Ryujinx/files/7513194/Ryujinx_1.0.0%2B07e1466_2021-11-10_10-31-10.log)

2021-11-10 19:39 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Amane amane has slow audio and the commands don't work right 
Demons does not start 
Japanese 8-bit Nintendo also working very well 
Blaster Master Zero 1 update 1.6.1 make the emulator close 
Blaster Master Zero 2 perfect
Blaster Master Zero 3 it has a small drop in yield, but not compromising like Zelda Link Wakerning 
Cadence of Hyrule has a small drop in Hyrule Castle, but nothing compromising 
Demon's Tier have font errors and broken sprites 
Jack Axe has sprite errors 
Alex Kid there is a small drop in video performance 

![imagem](https://user-images.githubusercontent.com/90729203/141180620-e020bf5a-c1c9-4eb2-bb81-cb1001daa651.png)
![imagem](https://user-images.githubusercontent.com/90729203/141180109-346c994f-2174-478f-9c71-fcff4a228a81.png)
![imagem](https://user-images.githubusercontent.com/90729203/141179906-3d981215-0323-44a8-8f87-61945876633b.png)
![imagem](https://user-images.githubusercontent.com/90729203/141179546-9154718d-377c-4ca1-a5a2-55a25b7f5ec3.png)
![imagem](https://user-images.githubusercontent.com/90729203/141179474-a3bf1152-5a2c-4a29-8c14-8ce892e72166.png)
![imagem](https://user-images.githubusercontent.com/90729203/141179167-607ab189-8d73-4959-a8f6-47766d066539.png)
![imagem](https://user-images.githubusercontent.com/90729203/141178800-ee39f990-4e25-404f-813d-bb3899d97a4d.png)
![imagem](https://user-images.githubusercontent.com/90729203/141178518-0e7e4b09-7606-411a-bde8-670c6e812cfd.png)
![imagem](https://user-images.githubusercontent.com/90729203/141177740-1e19b912-bd1a-4e3d-aeb0-52e531ed49e0.png)
![imagem](https://user-images.githubusercontent.com/90729203/141177104-f7ddfdfa-4a2f-4161-a1af-3c90e5afa363.png)
![imagem](https://user-images.githubusercontent.com/90729203/141176758-657ccbfe-c7cd-47f0-afd7-c017bd33ac96.png)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-01-10.log](https://github.com/Ryujinx/Ryujinx/files/7515287/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-01-10.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-04-44.log](https://github.com/Ryujinx/Ryujinx/files/7515294/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-04-44.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-06-49.log](https://github.com/Ryujinx/Ryujinx/files/7515332/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-06-49.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-12-20.log](https://github.com/Ryujinx/Ryujinx/files/7515355/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-12-20.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-15-03.log](https://github.com/Ryujinx/Ryujinx/files/7515373/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-15-03.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-17-42.log](https://github.com/Ryujinx/Ryujinx/files/7515379/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-17-42.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-20-13.log](https://github.com/Ryujinx/Ryujinx/files/7515389/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-20-13.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-23-12.log](https://github.com/Ryujinx/Ryujinx/files/7515398/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-23-12.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-25-11.log](https://github.com/Ryujinx/Ryujinx/files/7515409/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-25-11.log)
[Ryujinx_1.0.0+07e1466_2021-11-10_16-28-14.log](https://github.com/Ryujinx/Ryujinx/files/7515422/Ryujinx_1.0.0%2B07e1466_2021-11-10_16-28-14.log)

2021-11-11 00:15 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Super Mario Odissey when you arrive in the top hat city, the emulator closes, however the performance has improved a lot, but you need to fix some things like the mist that doesn't subside when you pass through it and the water that keeps flashing 
![imagem](https://user-images.githubusercontent.com/90729203/141213757-d42419e1-6e49-4c0c-ae93-e9a5892c92cb.png)
[Ryujinx_1.0.0+07e1466_2021-11-10_21-09-49.log](https://github.com/Ryujinx/Ryujinx/files/7516714/Ryujinx_1.0.0%2B07e1466_2021-11-10_21-09-49.log)

2021-11-11 13:21 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Resident Evil 0 Rebecca's and others' eye textures are flashing, plus there's yield losses 
Resident Evil it has a serious problem, as it is not possible to walk forward, only sideways, and there is also loss of income 
Resident Evil Revelations 1 graphically it's fine, but there's a lot of loss of income 
Resident Evil Revelations 2 have drastic drops in income 
![imagem](https://user-images.githubusercontent.com/90729203/141305092-3122d439-0237-47bb-8e34-bcc9d5e7f7b3.png)
![imagem](https://user-images.githubusercontent.com/90729203/141303366-9c9e3108-a9e9-42c0-b22e-adbf53c62b0b.png)
![imagem](https://user-images.githubusercontent.com/90729203/141301733-9530cf90-1862-43e8-9078-d084204c0595.png)
![imagem](https://user-images.githubusercontent.com/90729203/141299923-b590790b-aa0c-4bc2-8410-5db7e9cc3586.png)
[Ryujinx_1.0.0+07e1466_2021-11-11_09-30-52.log](https://github.com/Ryujinx/Ryujinx/files/7520477/Ryujinx_1.0.0%2B07e1466_2021-11-11_09-30-52.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_09-52-04.log](https://github.com/Ryujinx/Ryujinx/files/7520546/Ryujinx_1.0.0%2B07e1466_2021-11-11_09-52-04.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_10-03-04.log](https://github.com/Ryujinx/Ryujinx/files/7520600/Ryujinx_1.0.0%2B07e1466_2021-11-11_10-03-04.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_10-16-17.log](https://github.com/Ryujinx/Ryujinx/files/7520649/Ryujinx_1.0.0%2B07e1466_2021-11-11_10-16-17.log)

2021-11-11 15:11 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Yoshi suffers from severe texture failures and yield losses 
Baldo has graphical glitches and loss of income 
Pokémon Shield isn't even starting 
Final Fantasy VII Black Screen
New Super Mario Bros stays with black textures 
Super Mario 3D World has lost income 
![imagem](https://user-images.githubusercontent.com/90729203/141321520-679a0ad1-aa9c-45fa-b18a-36af4375a795.png)
![imagem](https://user-images.githubusercontent.com/90729203/141320924-59d8db5a-a2b3-4d69-87e2-8407a783760c.png)
![imagem](https://user-images.githubusercontent.com/90729203/141320801-ea36b10f-6957-4103-ba88-7fc756a1baf7.png)
![imagem](https://user-images.githubusercontent.com/90729203/141320605-374470d8-ee3f-4473-bbdc-44d60d5235bf.png)
![imagem](https://user-images.githubusercontent.com/90729203/141319986-476ada37-2291-46d2-bd28-036fb84bec98.png)
![imagem](https://user-images.githubusercontent.com/90729203/141319652-67e1cabd-7354-4b05-a226-6c70af96b706.png)
![imagem](https://user-images.githubusercontent.com/90729203/141319496-6490e806-9483-4649-b9c4-632367f0a3c8.png)
![imagem](https://user-images.githubusercontent.com/90729203/141318719-79ad7f61-6543-4141-b05e-ba97374c57e9.png)
![imagem](https://user-images.githubusercontent.com/90729203/141317979-5dfd6927-91e8-481f-9090-43f679624c1b.png)
![imagem](https://user-images.githubusercontent.com/90729203/141317871-8505d6f9-dbbc-45db-bc3b-c332fa85944d.png)
[Ryujinx_1.0.0+07e1466_2021-11-11_11-45-21.log](https://github.com/Ryujinx/Ryujinx/files/7521185/Ryujinx_1.0.0%2B07e1466_2021-11-11_11-45-21.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_11-49-48.log](https://github.com/Ryujinx/Ryujinx/files/7521222/Ryujinx_1.0.0%2B07e1466_2021-11-11_11-49-48.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_11-56-16.log](https://github.com/Ryujinx/Ryujinx/files/7521257/Ryujinx_1.0.0%2B07e1466_2021-11-11_11-56-16.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_11-57-52.log](https://github.com/Ryujinx/Ryujinx/files/7521263/Ryujinx_1.0.0%2B07e1466_2021-11-11_11-57-52.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_11-59-12.log](https://github.com/Ryujinx/Ryujinx/files/7521277/Ryujinx_1.0.0%2B07e1466_2021-11-11_11-59-12.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_12-01-04.log](https://github.com/Ryujinx/Ryujinx/files/7521307/Ryujinx_1.0.0%2B07e1466_2021-11-11_12-01-04.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_12-05-03.log](https://github.com/Ryujinx/Ryujinx/files/7521320/Ryujinx_1.0.0%2B07e1466_2021-11-11_12-05-03.log)
[Ryujinx_1.0.0+07e1466_2021-11-11_12-07-17.log](https://github.com/Ryujinx/Ryujinx/files/7521351/Ryujinx_1.0.0%2B07e1466_2021-11-11_12-07-17.log)

2021-11-11 21:16 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
GTA III there is a lot of vertex explosion and memory loss, in addition to severe texture errors 
![imagem](https://user-images.githubusercontent.com/90729203/141370009-395dbafd-5769-4488-8688-8ba25ed3b75c.png)
[Ryujinx_1.0.0+07e1466_2021-11-11_18-05-08.log](https://github.com/Ryujinx/Ryujinx/files/7523309/Ryujinx_1.0.0%2B07e1466_2021-11-11_18-05-08.log)

2021-11-12 08:47 UTC, beyondmeat commented
Please provide updated binaries

2021-11-12 11:41 UTC, AlfredoDore commented
> Please provide updated binaries

what do you mean binaries?

2021-11-12 12:05 UTC, Itamai commented
> Please provide updated binaries

Check the github bot comment the binaries got updated 3 days ago
https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424

2021-11-12 13:22 UTC, AlfredoDore commented
> 
> 
> > Please provide updated binaries
> 
> Check the actions bot comment the binaries got updated 3 days ago [#2518 (comment)](https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424)

that's fast hahahaha, downloading the new version here

2021-11-12 13:35 UTC, AlfredoDore commented
> 
> 
> > > Please provide updated binaries
> > 
> > 
> > Check the actions bot comment the binaries got updated 3 days ago [#2518 (comment)](https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424)
> 
> that's fast hahahaha, downloading the new version here

strange, it's the same version I have here 
![imagem](https://user-images.githubusercontent.com/90729203/141475559-711e412c-0f24-4f05-a71b-3674f8bb6861.png)

2021-11-12 20:04 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.1
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Starlink has a lot of graphical errors and a lot of vertex explosions, in addition to loss of performance (and no, this trial version of Ryujinx Vulkan I'm using is updated and not old) 
Kitaria Fables it's almost perfect, it only takes a while to start and it has some flickering textures, but the performance is very good, even fluctuating between 29 and 30fps, which is normal for this game 
MindCell has some low fps and some weird textures, like dotted water 
![imagem](https://user-images.githubusercontent.com/90729203/141527848-6702f986-268e-480b-9bc4-3c63e6208aae.png)
![imagem](https://user-images.githubusercontent.com/90729203/141526842-2e33b07f-20fc-45d2-89c5-bc16ef0b9f6d.png)
![imagem](https://user-images.githubusercontent.com/90729203/141525305-dfff7cbc-4623-4f54-9a37-04de0450d7f4.png)
![imagem](https://user-images.githubusercontent.com/90729203/141524950-9cbace33-d49b-4b61-b6d5-2509a32cf06a.png)
![imagem](https://user-images.githubusercontent.com/90729203/141524985-5d609c3c-4ef8-40e9-b831-8cf7d0c30f32.png)
[Ryujinx_1.0.0+07e1466_2021-11-12_16-28-50.log](https://github.com/Ryujinx/Ryujinx/files/7530018/Ryujinx_1.0.0%2B07e1466_2021-11-12_16-28-50.log)
[Ryujinx_1.0.0+07e1466_2021-11-12_16-48-40.log](https://github.com/Ryujinx/Ryujinx/files/7530075/Ryujinx_1.0.0%2B07e1466_2021-11-12_16-48-40.log)
[Ryujinx_1.0.0+07e1466_2021-11-12_16-56-19.log](https://github.com/Ryujinx/Ryujinx/files/7530096/Ryujinx_1.0.0%2B07e1466_2021-11-12_16-56-19.log)
[Ryujinx_1.0.0+07e1466_2021-11-12_16-59-09.log](https://github.com/Ryujinx/Ryujinx/files/7530129/Ryujinx_1.0.0%2B07e1466_2021-11-12_16-59-09.log)

2021-11-12 20:38 UTC, TerrXMaster commented
Win10 64 bits
Radeon RX 6700 XT 
I7-4790K
16GB ram
driver 21.11.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Ignore Missing Services: on
Graphics Backend: on
Disable AMD Image Sharpening
Tested Games: ACNH & New Pokemon Snap

Animal Crossing is more stable and reaches around 19 to 23 fps. Some reactions, such as "Distress", have graphical errors.
Pokemon Snap is benefiting from the new build and has received a great performance boost. The game runs almost completely at 60 fps. Unfortunately I noticed an audio error in video sequences. Image and sound are offset (sound is faster than the image).
In addition, the graphics errors are still present in the environment
![Unbenannt](https://user-images.githubusercontent.com/36804380/141531152-12211fa1-8797-4a02-814d-70aafafd6c8f.PNG)
.
![Unbenannt5](https://user-images.githubusercontent.com/36804380/141531176-5fee4a6c-8aa4-4769-9630-38b63b600f39.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/36804380/141531179-7fc93928-e64d-4e52-928c-0eaee20c359e.PNG)
[Pokemon Snap Log Ryujinx_1.0.0+07e1466_2021-11-12_19-48-25.log](https://github.com/Ryujinx/Ryujinx/files/7530275/Pokemon.Snap.Log.Ryujinx_1.0.0%2B07e1466_2021-11-12_19-48-25.log)
[Animal Crossing Log Ryujinx_1.0.0+07e1466_2021-11-12_19-39-29.log](https://github.com/Ryujinx/Ryujinx/files/7530276/Animal.Crossing.Log.Ryujinx_1.0.0%2B07e1466_2021-11-12_19-39-29.log)

2021-11-13 06:11 UTC, KawaiiDinosaur commented
Game version: 1.0.1

System Specs:

    OS: Windows 11 build 22000.318
    CPU: Ryzen 3700X
    GPU: RX 5700 XT (Driver 21.11.1)
    RAM: 16GB
    Applied Mods : No

Flashing white squares in Shin Megami Tensei V.

![ryujinx_capture_2021-11-13_03-05-22](https://user-images.githubusercontent.com/36821201/141608132-f5b59898-9790-4824-a87a-ed483431d4b6.png)

2021-11-13 12:31 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Highschool Romance it's almost perfect, there are some slow audio and animations on some occasions. 
Sakura Succubus the performance has improved, but there is still a slowdown, Sakura Nova in the middle of the game gives an error and the emulator closes and Sakura Swin Club has some income losses in the middle of the game 
![imagem](https://user-images.githubusercontent.com/90729203/141643824-eb201d9c-875a-4487-a7e5-57b2feec3320.png)
![imagem](https://user-images.githubusercontent.com/90729203/141643744-8617f48f-7820-4d26-b9d5-03e978aba669.png)
![imagem](https://user-images.githubusercontent.com/90729203/141643625-e5b613d4-9458-411f-9de8-4995afa3864e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141643490-dfee2ce8-1a37-43a6-b1e1-b314ed84ce1e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141643064-77c75764-e418-4c94-a572-2c9b0cd688ac.png)
![imagem](https://user-images.githubusercontent.com/90729203/141642801-7df2f0e5-03a2-49b8-a3a6-5b06c1a039fd.png)
![imagem](https://user-images.githubusercontent.com/90729203/141643277-5e9d1b54-a6b3-44f6-ac7f-09934e6f912e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141643397-e7a467f8-b1e6-4d68-9c71-ff30319888d1.png)
[Ryujinx_1.0.0+07e1466_2021-11-13_08-49-59.log](https://github.com/Ryujinx/Ryujinx/files/7531949/Ryujinx_1.0.0%2B07e1466_2021-11-13_08-49-59.log)
[Ryujinx_1.0.0+07e1466_2021-11-13_08-57-19.log](https://github.com/Ryujinx/Ryujinx/files/7531958/Ryujinx_1.0.0%2B07e1466_2021-11-13_08-57-19.log)
[Ryujinx_1.0.0+07e1466_2021-11-13_09-03-30.log](https://github.com/Ryujinx/Ryujinx/files/7531970/Ryujinx_1.0.0%2B07e1466_2021-11-13_09-03-30.log)
[Ryujinx_1.0.0+07e1466_2021-11-13_09-12-24.log](https://github.com/Ryujinx/Ryujinx/files/7531979/Ryujinx_1.0.0%2B07e1466_2021-11-13_09-12-24.log)
[Ryujinx_1.0.0+07e1466_2021-11-13_09-17-05.log](https://github.com/Ryujinx/Ryujinx/files/7531984/Ryujinx_1.0.0%2B07e1466_2021-11-13_09-17-05.log)
[Ryujinx_1.0.0+07e1466_2021-11-13_09-20-28.log](https://github.com/Ryujinx/Ryujinx/files/7531986/Ryujinx_1.0.0%2B07e1466_2021-11-13_09-20-28.log)
[Ryujinx_1.0.0+07e1466_2021-11-13_09-22-35.log](https://github.com/Ryujinx/Ryujinx/files/7531992/Ryujinx_1.0.0%2B07e1466_2021-11-13_09-22-35.log)
[Ryujinx_1.0.0+07e1466_2021-11-13_09-26-33.log](https://github.com/Ryujinx/Ryujinx/files/7532002/Ryujinx_1.0.0%2B07e1466_2021-11-13_09-26-33.log)

2021-11-14 13:09 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan build ryujinx-Release-1.0.0+07e1466-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Final Fantasy VIII practically perfect, I just notice that in the videos the audio bursts a little 
Overall NSK arcades are excellent, but Taito's has an invisible graphics issue 
![imagem](https://user-images.githubusercontent.com/90729203/141682339-88cbbbcf-9a10-4af5-a66a-7d6c010b1a42.png)
![imagem](https://user-images.githubusercontent.com/90729203/141682266-53cc0100-d63b-4f9b-86db-3d109ac4c109.png)
![imagem](https://user-images.githubusercontent.com/90729203/141682242-fb57cd3e-0715-4f00-89bd-853b75f710cf.png)
![imagem](https://user-images.githubusercontent.com/90729203/141682154-3250fd9b-bae7-4712-9453-82f9ea604f17.png)
![imagem](https://user-images.githubusercontent.com/90729203/141682042-93e41b85-d6b4-4a18-bf77-69fbec4ae484.png)
[Ryujinx_1.0.0+07e1466_2021-11-14_09-35-58.log](https://github.com/Ryujinx/Ryujinx/files/7533744/Ryujinx_1.0.0%2B07e1466_2021-11-14_09-35-58.log)
[Ryujinx_1.0.0+07e1466_2021-11-14_09-59-27.log](https://github.com/Ryujinx/Ryujinx/files/7533754/Ryujinx_1.0.0%2B07e1466_2021-11-14_09-59-27.log)
[Ryujinx_1.0.0+07e1466_2021-11-14_10-06-01.log](https://github.com/Ryujinx/Ryujinx/files/7533769/Ryujinx_1.0.0%2B07e1466_2021-11-14_10-06-01.log)

2021-11-14 16:02 UTC, riperiperi commented
Pushed a fix for texture flush from GPU thread. Should fix some lighting issues with UE4 games (very bright everything). Will not fix issues with flickering lighting on AMD.

2021-11-15 00:45 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+96d6c83-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Starlink has texture flaws, moreover the videos lose a lot of performance and in the tutorial on how to use Starlink there are audio losses, this game on Switch is 30 fps and it's really worth playing (even because of the Star Fox), improving it would also improve Mario + Rabbits and other possible Ubsoft games this is one of the reasons I ask for improvements to this game
apparently Final Fantasy VIII is fine, no loss of income and such, I just don't remember this blue mist, I don't know if it's from the game or it's a mistake, but the rest is really fine 
![imagem](https://user-images.githubusercontent.com/90729203/141705936-797b8cfe-e4cb-4dcf-8486-c3525a69f4a4.png)
![imagem](https://user-images.githubusercontent.com/90729203/141705909-63260c56-a208-47a0-814c-cbdc51ac4b7f.png)
![imagem](https://user-images.githubusercontent.com/90729203/141703241-935abcb7-d4d9-4528-baff-b76e1e12cfef.png)
![imagem](https://user-images.githubusercontent.com/90729203/141702892-6af4e0d4-0f0b-4baf-a5f3-67741e976474.png)
![imagem](https://user-images.githubusercontent.com/90729203/141702785-dac515fd-6d86-4e60-9750-b85b4290d6e1.png)
![imagem](https://user-images.githubusercontent.com/90729203/141702750-00c54275-422e-4001-bc72-d821f167f350.png)
![imagem](https://user-images.githubusercontent.com/90729203/141702738-fcb8485e-677f-4ffb-b07e-f6ef51a178e9.png)
[Ryujinx_1.0.0+96d6c83_2021-11-14_19-52-49.log](https://github.com/Ryujinx/Ryujinx/files/7534934/Ryujinx_1.0.0%2B96d6c83_2021-11-14_19-52-49.log)
[Ryujinx_1.0.0+96d6c83_2021-11-14_20-43-36.log](https://github.com/Ryujinx/Ryujinx/files/7535069/Ryujinx_1.0.0%2B96d6c83_2021-11-14_20-43-36.log)

2021-11-15 21:52 UTC, KawaiiDinosaur commented
Asides from the occasional flickering texture, SMTV rendering is pretty much perfect on AMD.

![ryujinx_capture_2021-11-15_18-20-37](https://user-images.githubusercontent.com/36821201/141858812-ca1dc28d-3910-4dde-827e-f0daaf8a3a00.png)
![ryujinx_capture_2021-11-15_18-22-14](https://user-images.githubusercontent.com/36821201/141858819-a94637bc-f9e8-4cd3-bea5-52ac7c1d2b2b.png)
![ryujinx_capture_2021-11-15_18-22-38](https://user-images.githubusercontent.com/36821201/141858821-95d942b7-2ce7-4dc5-a423-84c7539af973.png)
![ryujinx_capture_2021-11-15_18-23-37](https://user-images.githubusercontent.com/36821201/141858826-36902797-55c1-49d0-968c-370827afa462.png)
![ryujinx_capture_2021-11-15_18-25-13](https://user-images.githubusercontent.com/36821201/141858829-b6c4c126-17f8-428d-9f97-e0eb50888a8c.png)
![ryujinx_capture_2021-11-15_18-28-57](https://user-images.githubusercontent.com/36821201/141858836-2c588daf-355e-4fab-8741-72876817627d.png)
![ryujinx_capture_2021-11-15_18-30-56](https://user-images.githubusercontent.com/36821201/141858840-8a19ff62-ca80-42e1-b293-cbfe2ee8c10f.png)

2021-11-16 00:36 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin

![imagem](https://user-images.githubusercontent.com/90729203/141874114-9a3bb6cf-4dda-4ea5-82d0-9e60d94fba37.png)
![imagem](https://user-images.githubusercontent.com/90729203/141874080-df6347a5-2934-426a-bf40-fea28099e5b5.png)
![imagem](https://user-images.githubusercontent.com/90729203/141873840-e7ebda23-2f1b-4936-8305-a497abe688e5.png)
![imagem](https://user-images.githubusercontent.com/90729203/141873507-078bce24-f14e-4e03-9b8c-a11cc1593577.png)
![imagem](https://user-images.githubusercontent.com/90729203/141873364-538aa2aa-e812-4eb6-8a76-6685d7591d70.png)
![imagem](https://user-images.githubusercontent.com/90729203/141873067-6b04634d-a9da-4f3e-a03b-44c85b7a58f5.png)
![imagem](https://user-images.githubusercontent.com/90729203/141873031-87fd96dd-0cb2-41bb-9991-04d46a3e62ea.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872650-49932d41-e5c3-4a15-8374-160e2f87a063.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872495-478ecd60-f4e8-45d2-98d5-b722cf0f0e19.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872470-0284871f-281a-46d1-974a-39786e110163.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872446-35cc4e07-c624-4d50-9157-1bfd415d961e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872368-abd36b53-b18e-4e5d-ac52-19cf947e7e76.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872211-59857d70-0d5b-49b0-85f2-dccb8415f194.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872149-f267b314-db31-4ee4-933c-34c26799757e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141872126-f4bf2edf-588a-403d-8ce2-2ab098514031.png)
![imagem](https://user-images.githubusercontent.com/90729203/141871651-25968588-211d-4821-8191-480e7e5ed20e.png)
![imagem](https://user-images.githubusercontent.com/90729203/141871636-d8563de2-ca1d-4144-9313-e9c79d288fee.png)
[Ryujinx_1.0.0+2522726_2021-11-15_20-58-59.log](https://github.com/Ryujinx/Ryujinx/files/7542339/Ryujinx_1.0.0%2B2522726_2021-11-15_20-58-59.log)
[Ryujinx_1.0.0+2522726_2021-11-15_21-07-35.log](https://github.com/Ryujinx/Ryujinx/files/7542356/Ryujinx_1.0.0%2B2522726_2021-11-15_21-07-35.log)
[Ryujinx_1.0.0+2522726_2021-11-15_21-12-14.log](https://github.com/Ryujinx/Ryujinx/files/7542401/Ryujinx_1.0.0%2B2522726_2021-11-15_21-12-14.log)
[Ryujinx_1.0.0+2522726_2021-11-15_21-23-35.log](https://github.com/Ryujinx/Ryujinx/files/7542403/Ryujinx_1.0.0%2B2522726_2021-11-15_21-23-35.log)
[Ryujinx_1.0.0+2522726_2021-11-15_21-31-40.log](https://github.com/Ryujinx/Ryujinx/files/7542425/Ryujinx_1.0.0%2B2522726_2021-11-15_21-31-40.log)
[Ryujinx_1.0.0+2522726_2021-11-15_21-24-55.log](https://github.com/Ryujinx/Ryujinx/files/7542429/Ryujinx_1.0.0%2B2522726_2021-11-15_21-24-55.log)

2021-11-16 01:59 UTC, RaidenX5 commented
Win10 64 bits
Sapphire Radeon R7 260X 2GB
Intel i7 3770
12 GB ram
driver 21.5.2 (legacy driver)
PR Vulkan ryujinx-Release-1.0.0+96d6c83-win_x64
Graphics Backend: Vulkan
Disable AMD Image Sharpening

Crash when playing Xenoblade Chronicle DE when start up after the sword loading on the bottom right for some time. Log captured from command windows.
00:00:25.731 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorUnknown".
   at Ryujinx.Graphics.Vulkan.PipelineState.CreateGraphicsPipeline(Vk api, Device device, ShaderCollection program, PipelineCache cache, RenderPass renderPass)
   at Ryujinx.Graphics.Vulkan.PipelineBase.CreatePipeline(PipelineBindPoint pbp)
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp)
   at Ryujinx.Graphics.Vulkan.PipelineBase.Draw(Int32 vertexCount, Int32 instanceCount, Int32 firstVertex, Int32 firstInstance)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_40(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorUnknown".
   at Ryujinx.Graphics.Vulkan.PipelineState.CreateGraphicsPipeline(Vk api, Device device, ShaderCollection program, PipelineCache cache, RenderPass renderPass)
   at Ryujinx.Graphics.Vulkan.PipelineBase.CreatePipeline(PipelineBindPoint pbp)
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp)
   at Ryujinx.Graphics.Vulkan.PipelineBase.Draw(Int32 vertexCount, Int32 instanceCount, Int32 firstVertex, Int32 firstInstance)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_40(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

2021-11-16 09:41 UTC, AntoSkate commented
Operating System: Windows 11 22000.318 (X64)
CPU: Intel Core i5-9400F
GPU: NVIDIA GeForce RTX 2060 (Driver v496.49.0.0)
RAM: 16GB

Splatoon 2 5.5.0

The game crashes when trying to enter the tutorial map

> 00:00:38.618 |E| Cpu InvalidAccessHandler: Invalid memory access at virtual address 0xFFFFFFFFFFFFFFFF.
00:00:38.623 |E| Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: va=0xFFFFFFFFFFFFFFFF, size=0x0000000000000010
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertValidAddressAndSize(UInt64 va, UInt64 size)
   at Ryujinx.Cpu.MemoryManagerHostMapped.SignalMemoryTracking(UInt64 va, UInt64 size, Boolean write, Boolean precise)
   at Ryujinx.Cpu.MemoryManagerHostMapped.Write(UInt64 va, ReadOnlySpan`1 data)
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.WriteImpl(UInt64 va, ReadOnlySpan`1 data, WriteCallback writeCallback)
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.Write[T](UInt64 va, T value)
   at Ryujinx.Graphics.Gpu.Engine.Threed.SemaphoreUpdater.<>c__DisplayClass13_0.<ReportCounter>g__resultHandler|0(Object evt, UInt64 result)
   at Ryujinx.Graphics.Vulkan.Queries.CounterQueueEvent.TryConsume(UInt64& result, Boolean block, AutoResetEvent wakeSignal)
   at Ryujinx.Graphics.Vulkan.Queries.CounterQueue.EventConsumer()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

[Ryujinx_1.0.0+2522726_2021-11-16_10-30-55.log](https://github.com/Ryujinx/Ryujinx/files/7545159/Ryujinx_1.0.0%2B2522726_2021-11-16_10-30-55.log)

2021-11-16 19:03 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Starlink still only starts with the option ignore missing services activated, besides that there are audio problems and the videos are very slow, apart from the texture errors 
![imagem](https://user-images.githubusercontent.com/90729203/142048926-1f106347-137a-43c7-a8f5-6fe6f80ee210.png)
![imagem](https://user-images.githubusercontent.com/90729203/142046480-84c99932-edb7-4945-818c-c51d84c6868f.png)
![imagem](https://user-images.githubusercontent.com/90729203/142046259-e872ed9c-461c-493a-9c94-47a4ec13fe31.png)
![imagem](https://user-images.githubusercontent.com/90729203/142046145-278f561d-7570-4417-bfba-1a0bde0c6961.png)
![imagem](https://user-images.githubusercontent.com/90729203/142046088-c4b1e281-5517-402f-8519-41fc152ad768.png)
![imagem](https://user-images.githubusercontent.com/90729203/142045675-30400969-0ae1-4350-b1fe-7ecd1f01e6ab.png)
![imagem](https://user-images.githubusercontent.com/90729203/142045710-e74d1665-ad89-4dc4-a7c3-f2b848b64e02.png)
![imagem](https://user-images.githubusercontent.com/90729203/142044840-e6261c49-4773-4c0a-a53c-2c6f8238ad12.png)
[Ryujinx_1.0.0+2522726_2021-11-16_14-28-20.log](https://github.com/Ryujinx/Ryujinx/files/7548944/Ryujinx_1.0.0%2B2522726_2021-11-16_14-28-20.log)
[Ryujinx_1.0.0+2522726_2021-11-16_15-36-19.log](https://github.com/Ryujinx/Ryujinx/files/7548958/Ryujinx_1.0.0%2B2522726_2021-11-16_15-36-19.log)
[Ryujinx_1.0.0+2522726_2021-11-16_15-37-31.log](https://github.com/Ryujinx/Ryujinx/files/7549029/Ryujinx_1.0.0%2B2522726_2021-11-16_15-37-31.log)
[Ryujinx_1.0.0+2522726_2021-11-16_15-54-36.log](https://github.com/Ryujinx/Ryujinx/files/7549051/Ryujinx_1.0.0%2B2522726_2021-11-16_15-54-36.log)
[Ryujinx_1.0.0+2522726_2021-11-16_15-55-49.log](https://github.com/Ryujinx/Ryujinx/files/7549096/Ryujinx_1.0.0%2B2522726_2021-11-16_15-55-49.log)

2021-11-16 21:12 UTC, Ghaleon7771 commented
Win7 64 bits
AMD Radeon R7 360 2GB
I3 3240 3.4Ghz
8GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Hi friends, first of all, THANK YOU, for releasing this Vulkan build, i got a pretty good FPS boost on my poor PC. 
I was trying SD Gundam G Generation Genesis, and while it works almost perfect on all stages and no graphics issues, there is a problem i encountered which you can see in the screenshot... the same happens with the character menu.
![New Bitmap Image](https://user-images.githubusercontent.com/87739309/142066508-fab7b81e-00a6-47cb-9e76-99c83cffaebe.png)

2021-11-16 22:23 UTC, AlfredoDore commented
> 
> 
> Win7 64 bits AMD Radeon R7 360 2GB I3 3240 3.4Ghz 8GB ram driver 21.11.2 Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64 Graphics Backend: on Hi friends, first of all, THANK YOU, for releasing this Vulkan build, i got a pretty good FPS boost on my poor PC. I was trying SD Gundam G Generation Genesis, and while it works almost perfect on all stages and no graphics issues, there is a problem i encountered which you can see in the screenshot... the same happens with the character menu. There is no character/mecha image on the right side. ![New Bitmap Image](https://user-images.githubusercontent.com/87739309/142066688-2ca8e47f-13ca-4ed9-b27c-a5dd97fe0dad.png)
it is very important that you send the log file, it shows how the game behaves (play the game and after closing the emulator the log will be recorded with the game information from the bottom up, so attach the log to the chat) 
![imagem](https://user-images.githubusercontent.com/90729203/142075545-65bc4505-dc58-491d-b5c5-23f95e4ac1d7.png)

2021-11-16 22:40 UTC, Ghaleon7771 commented
Ah ok, totally forgot about logs, here they are:
[Ryujinx_1.0.0+2522726_2021-11-16_18-12-21.log](https://github.com/Ryujinx/Ryujinx/files/7550354/Ryujinx_1.0.0%2B2522726_2021-11-16_18-12-21.log)
[Ryujinx_1.0.0+2522726_2021-11-16_18-16-16.log](https://github.com/Ryujinx/Ryujinx/files/7550355/Ryujinx_1.0.0%2B2522726_2021-11-16_18-16-16.log)
[Ryujinx_1.0.0+2522726_2021-11-16_19-37-28.log](https://github.com/Ryujinx/Ryujinx/files/7550356/Ryujinx_1.0.0%2B2522726_2021-11-16_19-37-28.log)

2021-11-16 23:28 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Metroid Dread has black textures and yield drop (although they are few but they are noticeable) and Super Mario Odyssey is no longer crashing, but textures are flickering and the fog for example is not dissipating as it should 
Monster Sanctuary perfect
Shin Chan is almost there, he has problem with some textures and transitions, remember that it is exclusive to Switch 
Zelda Link Awakening has a lot of loss of performance and Zelda Skyaway Sword has these texture errors 
Super Mario 3D World has a lot of loss of income 
![imagem](https://user-images.githubusercontent.com/90729203/142082369-9b0250a1-1534-4c2c-89fa-85a8e8683fbe.png)
![imagem](https://user-images.githubusercontent.com/90729203/142081787-e6af5b49-9ea0-45f2-aebd-dd95914b5162.png)
![imagem](https://user-images.githubusercontent.com/90729203/142081655-df7ea511-2a01-42b5-913f-2e69ccf355e3.png)
![imagem](https://user-images.githubusercontent.com/90729203/142081507-fd314852-e2dd-4b18-8c0b-e42b98c54fa1.png)
![imagem](https://user-images.githubusercontent.com/90729203/142081354-09b8f1e9-fa4f-4fb2-951b-8d17a64b2415.png)
![imagem](https://user-images.githubusercontent.com/90729203/142081250-1026324f-ced6-40db-9dac-e646647b2b72.png)
![imagem](https://user-images.githubusercontent.com/90729203/142081159-a2bb3536-62a5-40af-83c6-0029d37c928f.png)
![imagem](https://user-images.githubusercontent.com/90729203/142081109-a36ca870-eb8c-4783-a6f5-3c0a59227fb6.png)
![imagem](https://user-images.githubusercontent.com/90729203/142080957-0a8718f8-4589-4f72-9911-ca85fb1a6568.png)
![imagem](https://user-images.githubusercontent.com/90729203/142080746-2077deaa-6737-477e-92d9-73db77203ebe.png)
![imagem](https://user-images.githubusercontent.com/90729203/142080703-324864f9-a7bc-407a-bea0-5ea79c6af98d.png)
![imagem](https://user-images.githubusercontent.com/90729203/142080562-797aabfc-3ddb-4d34-830e-af102c01037b.png)
![imagem](https://user-images.githubusercontent.com/90729203/142080426-49e21994-596f-49d7-b132-dc54488604b2.png)
![imagem](https://user-images.githubusercontent.com/90729203/142080191-3803954e-652f-4934-9e20-4254c4fb3a26.png)
![imagem](https://user-images.githubusercontent.com/90729203/142080163-08392f5e-649b-444e-8228-9b2e679dedf1.png)
![imagem](https://user-images.githubusercontent.com/90729203/142079675-5d230d31-8d65-4959-85e1-2af32eb5ef65.png)
![imagem](https://user-images.githubusercontent.com/90729203/142078871-e9206438-d3c0-4d48-9d7e-ca27836f835a.png)
![imagem](https://user-images.githubusercontent.com/90729203/142078832-7dd80b90-3df3-45dd-b21c-4e610908dee0.png)
![imagem](https://user-images.githubusercontent.com/90729203/142078573-74f91208-fc3d-4f88-b7e4-7756da022944.png)
[Ryujinx_1.0.0+2522726_2021-11-16_19-37-13.log](https://github.com/Ryujinx/Ryujinx/files/7550385/Ryujinx_1.0.0%2B2522726_2021-11-16_19-37-13.log)
[Ryujinx_1.0.0+2522726_2021-11-16_19-49-00.log](https://github.com/Ryujinx/Ryujinx/files/7550445/Ryujinx_1.0.0%2B2522726_2021-11-16_19-49-00.log)
[Ryujinx_1.0.0+2522726_2021-11-16_20-01-05.log](https://github.com/Ryujinx/Ryujinx/files/7550457/Ryujinx_1.0.0%2B2522726_2021-11-16_20-01-05.log)
[Ryujinx_1.0.0+2522726_2021-11-16_20-13-14.log](https://github.com/Ryujinx/Ryujinx/files/7550510/Ryujinx_1.0.0%2B2522726_2021-11-16_20-13-14.log)
[Ryujinx_1.0.0+2522726_2021-11-16_20-18-50.log](https://github.com/Ryujinx/Ryujinx/files/7550525/Ryujinx_1.0.0%2B2522726_2021-11-16_20-18-50.log)
[Ryujinx_1.0.0+2522726_2021-11-16_20-24-41.log](https://github.com/Ryujinx/Ryujinx/files/7550542/Ryujinx_1.0.0%2B2522726_2021-11-16_20-24-41.log)

2021-11-17 01:35 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Mario Kart 8 same problem as usual, when playing once everything is ok, but when closing and starting again never again, this problem was solved in OpenGL but not in Vulkan, so two Mario Kart log files one working and one not, in the middle of the game I noticed yield losses and vertex explosions 
![imagem](https://user-images.githubusercontent.com/90729203/142092750-a27df84d-9104-407b-8ba3-21e4fad6c1ba.png)
[Ryujinx_1.0.0+2522726_2021-11-16_22-31-54.log](https://github.com/Ryujinx/Ryujinx/files/7550987/Ryujinx_1.0.0%2B2522726_2021-11-16_22-31-54.log)
[Ryujinx_1.0.0+2522726_2021-11-16_22-31-54.log](https://github.com/Ryujinx/Ryujinx/files/7550990/Ryujinx_1.0.0%2B2522726_2021-11-16_22-31-54.log)

2021-11-17 13:19 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Overall Resident Evil 0, 1 and Revelations 1 and 2 have loss of performance, plus 1 is not moving forward, just sideways and back, Zero has Rebecca's eye texture problem ( I think it's the same problem as Rockman 11), the videos are running very well 
in the Revelations 2 menu has a texture error in the eye 
![imagem](https://user-images.githubusercontent.com/90729203/142208030-445fe4ee-8b6e-412b-87f1-0c03db96dd0c.png)
![imagem](https://user-images.githubusercontent.com/90729203/142207415-c461bcf1-8e13-4b2a-939f-43e417c31c1f.png)
![imagem](https://user-images.githubusercontent.com/90729203/142207178-3642536b-b042-45fa-a418-3a0ecd28f8ad.png)
![imagem](https://user-images.githubusercontent.com/90729203/142205508-931173aa-371e-4e79-b704-903406a616ce.png)
![imagem](https://user-images.githubusercontent.com/90729203/142204947-003f6b8b-7531-49cc-bd55-38182b8e4285.png)
![imagem](https://user-images.githubusercontent.com/90729203/142203190-312f25a9-cb19-4a31-912a-3950d8d34d15.png)
![imagem](https://user-images.githubusercontent.com/90729203/142203031-93a1dc58-4b96-4f6f-b26e-babfe3e927ed.png)
![imagem](https://user-images.githubusercontent.com/90729203/142202986-d46e62f6-12ad-49e8-93f0-902533a5e505.png)
![imagem](https://user-images.githubusercontent.com/90729203/142201708-c09feaaf-1d5c-4f09-932c-38d413d190cb.png)
![imagem](https://user-images.githubusercontent.com/90729203/142201216-507431bb-1f25-437e-b98f-65cee1832407.png)
![imagem](https://user-images.githubusercontent.com/90729203/142201319-4d510afe-ab40-4cf2-a394-64d0c7b89574.png)
![imagem](https://user-images.githubusercontent.com/90729203/142201662-b1bbbe57-c9ac-4465-a5d8-5677ce21d41c.png)
[Ryujinx_1.0.0+2522726_2021-11-17_09-23-27.log](https://github.com/Ryujinx/Ryujinx/files/7554638/Ryujinx_1.0.0%2B2522726_2021-11-17_09-23-27.log)
[Ryujinx_1.0.0+2522726_2021-11-17_09-42-25.log](https://github.com/Ryujinx/Ryujinx/files/7554710/Ryujinx_1.0.0%2B2522726_2021-11-17_09-42-25.log)
[Ryujinx_1.0.0+2522726_2021-11-17_10-11-37.log](https://github.com/Ryujinx/Ryujinx/files/7554859/Ryujinx_1.0.0%2B2522726_2021-11-17_10-11-37.log)
[Ryujinx_1.0.0+2522726_2021-11-17_10-11-37.log](https://github.com/Ryujinx/Ryujinx/files/7554870/Ryujinx_1.0.0%2B2522726_2021-11-17_10-11-37.log)

2021-11-18 12:26 UTC, AlfredoDore commented
when I reshade it becomes transparent 
![imagem](https://user-images.githubusercontent.com/90729203/142415109-0741e602-3e6a-4fc2-ba36-a3cd5f9c3627.png)

2021-11-18 21:26 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
income has improved a lot 
AM2R it has slow starting game, going to menu, area transitions and more, the game runs at 60 fps and I didn't see any graphical defects, but this slow loading kills the game experience 
now Demon's Tier is perfect, no slowdowns and no broken sprites 
![imagem](https://user-images.githubusercontent.com/90729203/142499138-d0570ced-85fc-435f-afc6-5cb5988c5a2d.png)
![imagem](https://user-images.githubusercontent.com/90729203/142498415-b98ff013-1e90-4474-b82b-e16a678f35bc.png)
![imagem](https://user-images.githubusercontent.com/90729203/142498437-e2259db6-4699-4706-b6e7-b825a79db1c4.png)
![imagem](https://user-images.githubusercontent.com/90729203/142497990-c2c7474d-ceff-4b69-b533-89e42a6e93d2.png)
![imagem](https://user-images.githubusercontent.com/90729203/142497902-990c33fe-2fb9-44cf-ae6a-637586fc59ef.png)
![imagem](https://user-images.githubusercontent.com/90729203/142497844-a72a3a87-687a-4512-95b7-ac89bd17b3b1.png)
![imagem](https://user-images.githubusercontent.com/90729203/142497491-cdec2765-efe6-489d-9866-3c8273d541cf.png)
![imagem](https://user-images.githubusercontent.com/90729203/142497333-d40e06ec-61b3-436b-86a0-5eadcf7337c2.png)
![imagem](https://user-images.githubusercontent.com/90729203/142496414-d6e3d10f-e9d7-4427-8ebe-db69ef2450f6.png)
[Ryujinx_1.0.0+2522726_2021-11-18_17-59-25.log](https://github.com/Ryujinx/Ryujinx/files/7565970/Ryujinx_1.0.0%2B2522726_2021-11-18_17-59-25.log)
[Ryujinx_1.0.0+2522726_2021-11-18_18-06-46.log](https://github.com/Ryujinx/Ryujinx/files/7566030/Ryujinx_1.0.0%2B2522726_2021-11-18_18-06-46.log)
[Ryujinx_1.0.0+2522726_2021-11-18_18-18-27.log](https://github.com/Ryujinx/Ryujinx/files/7566100/Ryujinx_1.0.0%2B2522726_2021-11-18_18-18-27.log)

2021-11-19 03:44 UTC, yuwenhua653 commented
win 11 64bit
AMD R7 5700u
21.11.3
Pokémon Brilliant Diamond,Pokémon Shining Pearl
Run game error
`00:00:22.442` |E| Gpu .ctor: Shader compilation error: CompilationError Ryu:7: warning: '#extension' : extension not supported: GL_EXT_texture_shadow_lod
Ryu:192: error: 'gl_Layer' : required extension not requested: Possible extensions include:
Ryu: GL_ARB_shader_viewport_layer_array
Ryu: `GL_NV_viewport_array2`
Then the game crashes
[Ryujinx_1.0.0+2522726_2021-11-19_11-39-24.log](https://github.com/Ryujinx/Ryujinx/files/7567612/Ryujinx_1.0.0%2B2522726_2021-11-19_11-39-24.log)

2021-11-19 10:37 UTC, dante3732 commented
https://user-images.githubusercontent.com/66036249/142609025-a374fea9-ff4a-4221-b16c-59a8379d1d5a.mp4

Flickering on SMT5 on AMD Vulkan.

2021-11-19 12:52 UTC, LOuroboros commented
> 
> 
> win 11 64bit AMD R7 5700u 21.11.3 Pokémon Brilliant Diamond,Pokémon Shining Pearl Run game error `00:00:22.442` |E| Gpu .ctor: Shader compilation error: CompilationError Ryu:7: warning: '#extension' : extension not supported: GL_EXT_texture_shadow_lod Ryu:192: error: 'gl_Layer' : required extension not requested: Possible extensions include: Ryu: GL_ARB_shader_viewport_layer_array Ryu: `GL_NV_viewport_array2` Then the game crashes [Ryujinx_1.0.0+2522726_2021-11-19_11-39-24.log](https://github.com/Ryujinx/Ryujinx/files/7567612/Ryujinx_1.0.0%2B2522726_2021-11-19_11-39-24.log)

Same error here. I'm not sure if it matters, but I also noticed that the automated build generated out of this PR consumes a lot more of RAM than **[the regular automated builds hosted on AppVeyor](https://ci.appveyor.com/project/gdkchan/ryujinx/history)**, somewhere around 1.5 GB, but it increases constantly, and it's not just when using the Vulkan renderer, but even when using the OGL one.
CPU usage also remains high. 98-99% of CPU used.

Meanwhile, **[said AppVeyor builds don't even manage to consume 1GB of RAM and their CPU usage remains at 35-45% while a game is loading, and it stays at 65-75% at most while inside the game's overworld](https://user-images.githubusercontent.com/4485172/142621415-94309a02-e938-40e4-9998-d6019202c639.png)**.

Now, I know I have a potato of a PC, but bear with me.
I feel like this behavior makes no sense and shouldn't be happening regardless of how underpowered my hardware combo is. Despite how prone to crashes Yuzu is for example, it doesn't consume as much resources, but I'm not sure if it's a good target for comparison. Maybe the difference in how both emulators use a PC's hardware resources stems from different approaches to emulate the Switch or something, I don't know.

I'm assuming there's a good chance this problem gets solved *(assuming there actually is an error to solve here)* as the Vulkan renderer keeps being developed and the goals to merge it are reached. I'm just leaving my experience here in case it could be helpful.

**CPU**: i3 2120 *(2c/4t, running at 3-3.2 GHz)*
**RAM**: 4GBs *(running on single channel because of reasons)*
**GPU**: Gigabyte's NVIDIA GeForce GT 1030, 2GB GDDR5, Driver Version 472.12
**OS**: Windows 10 v21H1 x64, Build 19043.1165

Log with this PR's automated build:
[Ryujinx_1.0.0+2522726_2021-11-19_09-24-42.log](https://github.com/Ryujinx/Ryujinx/files/7570207/Ryujinx_1.0.0%2B2522726_2021-11-19_09-24-42.log)
***Note**: When the "ErrorOutOfDeviceMemory" warning was printed on the Windows Command Prompt, I shut down Ryujinx right away.
As I said above, this just never happens in the AppVeyor builds because RAM consumption is much more sane with them.*

I'm not sure if it helps, but here's also a log with the latest AppVeyor build for comparison, from the moment Ryujinx starts to the moment my savefile is loaded and I enter the game's overworld *(takes about 4 minutes and 10 seconds after I double click the game on Ryujinx's list)*.
[Ryujinx_1.0.7106_2021-11-19_09-35-07.log](https://github.com/Ryujinx/Ryujinx/files/7570248/Ryujinx_1.0.7106_2021-11-19_09-35-07.log)

2021-11-19 23:43 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I thought final fantasy was perfect, but here in the prison part and in the video in the credits option the videos are too slow, if they fix it, it's a 100% game on Vulkan  
![imagem](https://user-images.githubusercontent.com/90729203/142701403-581c8f84-81c1-4ac3-96f8-9b9d911c8860.png)
[Ryujinx_1.0.0+2522726_2021-11-19_18-53-01.log](https://github.com/Ryujinx/Ryujinx/files/7573429/Ryujinx_1.0.0%2B2522726_2021-11-19_18-53-01.log)

2021-11-22 01:02 UTC, AlfredoDore commented
just a curiosity: the OpenGL update straightened out the wrong colors of the FFVIII, but even in the main video playback is slow, and now the game itself is almost perfect, all that's left is to straighten out the video playback, as there are games that the video is slow and the game is normal, I'll send the main log, maybe it will help, the one from Vulkan I sent a few days ago 
![imagem](https://user-images.githubusercontent.com/90729203/142786514-12fed3e9-0764-4853-a0d5-20825b05d862.png)
[Ryujinx_1.0.7107_2021-11-21_21-45-29.log](https://github.com/Ryujinx/Ryujinx/files/7577559/Ryujinx_1.0.7107_2021-11-21_21-45-29.log)

2021-11-22 12:14 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.2
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
one more example, in Haven on OpenGL the grass would render the correct color, but it blinks while on Vulkan it renders fine and behaves as it does in the actual game, but the color is black (previously it was grey) 
Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/142859704-a4e1328d-07a8-4e23-8cd6-155569629e16.png)
[Ryujinx_1.0.0+2522726_2021-11-22_09-09-47.log](https://github.com/Ryujinx/Ryujinx/files/7580812/Ryujinx_1.0.0%2B2522726_2021-11-22_09-09-47.log)

OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/142859310-ac4c1dd0-2d7d-41eb-bfbc-46d36ed75865.png)
[Ryujinx_1.0.7107_2021-11-22_09-01-06.log](https://github.com/Ryujinx/Ryujinx/files/7580816/Ryujinx_1.0.7107_2021-11-22_09-01-06.log)

2021-11-22 12:59 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
several visual novel games have improved the animation, but there is still loss of performance, Sakura Nova and The Marauder Chronicles are closing, Amane has very big loss of performance and even changing the language he continues in Japanese, since there are several languages, Jack Ax is with the sprites all broken and with invisible objects, in general I think it has to improve the shader and the performance in general, as there are games (including Zelda Link Awakerning) that have this black texture on the screen at the time of the video and in certain games involving 2D 
![imagem](https://user-images.githubusercontent.com/90729203/142865282-08a33be6-449f-477e-9c49-cf58e87e7db4.png)
![imagem](https://user-images.githubusercontent.com/90729203/142865213-908cf972-086e-4e0f-87c0-e50090f2f4d2.png)
![imagem](https://user-images.githubusercontent.com/90729203/142865078-107ca3fc-8700-4aae-a298-b3d90f705bbe.png)
![imagem](https://user-images.githubusercontent.com/90729203/142864102-5af7982f-f91f-45ad-83af-26d089c59387.png)
![imagem](https://user-images.githubusercontent.com/90729203/142863917-c88a2d88-86fc-4915-a1e7-63b6420e83cb.png)
![imagem](https://user-images.githubusercontent.com/90729203/142863779-68429b1b-87f4-4089-8025-6edc9d827aa6.png)
![imagem](https://user-images.githubusercontent.com/90729203/142863350-4220834a-e3b8-45ac-aa29-9a5a22b8d09b.png)
![imagem](https://user-images.githubusercontent.com/90729203/142862898-1a1373d1-c113-4634-8a00-0d7e1091a250.png)
![imagem](https://user-images.githubusercontent.com/90729203/142862481-afc53d1e-e77c-46d0-91db-c63db100ccc7.png)
![imagem](https://user-images.githubusercontent.com/90729203/142862030-40cd8988-a7c7-4e41-8899-90c680cc7b2c.png)
![imagem](https://user-images.githubusercontent.com/90729203/142861485-f2451757-6b2a-40d4-9106-966c00cfafd0.png)
![imagem](https://user-images.githubusercontent.com/90729203/142861508-34adfd73-9cf6-4354-b4c5-f33ff570da5b.png)
![imagem](https://user-images.githubusercontent.com/90729203/142861593-e9f540a4-6db8-4bd5-913a-70e9832250a9.png)
![imagem](https://user-images.githubusercontent.com/90729203/142861708-cc1a2b23-5c1b-48d4-a910-4a5360e39cef.png)
[Ryujinx_1.0.0+2522726_2021-11-22_09-23-53.log](https://github.com/Ryujinx/Ryujinx/files/7580946/Ryujinx_1.0.0%2B2522726_2021-11-22_09-23-53.log)
[Ryujinx_1.0.0+2522726_2021-11-22_09-28-26.log](https://github.com/Ryujinx/Ryujinx/files/7580977/Ryujinx_1.0.0%2B2522726_2021-11-22_09-28-26.log)
[Ryujinx_1.0.0+2522726_2021-11-22_09-31-52.log](https://github.com/Ryujinx/Ryujinx/files/7580988/Ryujinx_1.0.0%2B2522726_2021-11-22_09-31-52.log)
[Ryujinx_1.0.0+2522726_2021-11-22_09-36-49.log](https://github.com/Ryujinx/Ryujinx/files/7581031/Ryujinx_1.0.0%2B2522726_2021-11-22_09-36-49.log)
[Ryujinx_1.0.0+2522726_2021-11-22_09-33-58.log](https://github.com/Ryujinx/Ryujinx/files/7581035/Ryujinx_1.0.0%2B2522726_2021-11-22_09-33-58.log)
[Ryujinx_1.0.0+2522726_2021-11-22_09-41-16.log](https://github.com/Ryujinx/Ryujinx/files/7581070/Ryujinx_1.0.0%2B2522726_2021-11-22_09-41-16.log)
[Ryujinx_1.0.0+2522726_2021-11-22_09-48-51.log](https://github.com/Ryujinx/Ryujinx/files/7581088/Ryujinx_1.0.0%2B2522726_2021-11-22_09-48-51.log)
[Ryujinx_1.0.0+2522726_2021-11-22_09-50-53.log](https://github.com/Ryujinx/Ryujinx/files/7581101/Ryujinx_1.0.0%2B2522726_2021-11-22_09-50-53.log)

2021-11-22 19:21 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
on the Super Nintendo I'm having problems adding mods 
and I can't play the N64 games 
![imagem](https://user-images.githubusercontent.com/90729203/142922255-70159609-a021-417a-9c53-44b1dc7e1d8b.png)
[Ryujinx_1.0.0+2522726_2021-11-22_16-08-38.log](https://github.com/Ryujinx/Ryujinx/files/7583775/Ryujinx_1.0.0%2B2522726_2021-11-22_16-08-38.log)
[Ryujinx_1.0.0+2522726_2021-11-22_16-06-57.log](https://github.com/Ryujinx/Ryujinx/files/7583753/Ryujinx_1.0.0%2B2522726_2021-11-22_16-06-57.log)
[Ryujinx_1.0.0+2522726_2021-11-22_16-13-51.log](https://github.com/Ryujinx/Ryujinx/files/7583796/Ryujinx_1.0.0%2B2522726_2021-11-22_16-13-51.log)
[Ryujinx_1.0.0+2522726_2021-11-22_16-20-07.log](https://github.com/Ryujinx/Ryujinx/files/7583806/Ryujinx_1.0.0%2B2522726_2021-11-22_16-20-07.log)

2021-11-23 22:32 UTC, DarkriGaming commented
Getting bad visual glitches on the build, will attach a screenshot and logs
Have a Radeon rx 480, and a Ryzen 5 2600
[Ryujinx_1.0.0+2522726_2021-11-23_17-13-02.log](https://github.com/Ryujinx/Ryujinx/files/7591375/Ryujinx_1.0.0%2B2522726_2021-11-23_17-13-02.log)
![Ryujinx_Jxy18fklK7](https://user-images.githubusercontent.com/34459201/143139553-4744a429-1140-47bc-b305-0160befdf5be.png)

2021-11-25 12:41 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+2522726-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Sonic needs more performance, overall better than OpenGL 

[Ryujinx_1.0.0+2522726_2021-11-25_09-01-37.log](https://github.com/Ryujinx/Ryujinx/files/7602983/Ryujinx_1.0.0%2B2522726_2021-11-25_09-01-37.log)

2021-11-28 16:28 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+555fa00-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
it's transparent because of reshade, but when it's full screen it's not transparent 
AM2R is loading much faster, but needs to improve more, Mario Kart is almost like Cemu, but there are some parts that have fps drop 
Crash trilogy continues with those errors, but for example the monkey there now has a body, but the proportions and texture errors (apart from the slow video) remain 
now in Haven the grass is loading as it should and the fps rate is more consistent, plus Jacke Ax still has the sprites broken 
Fuga it's almost, there are still some texture errors 
Sonic Colours doesn't work anymore 
New Super Mario Bros continue with the black textures 
Zelda Link Awakening has fps ranges from 27 to 60 fps, in addition to that black bar that appears on fmvs of many games 
Final Fantasy VIII still has slow video, even most of the game is perfectly playable, but then the videos get very slow 
Zelda Skyway Sword continues with texture issues (same as Fuga) including this hideous brown screen 
Rockman 11 there are several texture errors 
Super Mario Odyssey is having texture problems and yield losses 
![imagem](https://user-images.githubusercontent.com/90729203/143776705-7d6331aa-2ce1-414d-929f-2c2efa56943a.png)
![imagem](https://user-images.githubusercontent.com/90729203/143776429-84c5c496-e44d-4bb5-ae62-f0565cd0fae5.png)
![imagem](https://user-images.githubusercontent.com/90729203/143776200-d126fd07-9dbb-4dd9-bf14-31365e72e4c7.png)
![imagem](https://user-images.githubusercontent.com/90729203/143776027-75dc2eff-0507-412e-897e-90a656ec9bab.png)
![imagem](https://user-images.githubusercontent.com/90729203/143775640-3f09b2dc-8647-4311-bc8d-031334c8fd48.png)
![imagem](https://user-images.githubusercontent.com/90729203/143775490-30b51194-c37e-4f6b-a516-e54ec303c75d.png)
![imagem](https://user-images.githubusercontent.com/90729203/143775369-2a5b1731-3c8d-458d-9d84-d745d42b331b.png)
![imagem](https://user-images.githubusercontent.com/90729203/143775100-4d8b8421-b41e-4001-ac40-6bbfdc6dd49a.png)
![imagem](https://user-images.githubusercontent.com/90729203/143774789-b3e6363a-57fc-48c7-becd-11860320965f.png)
![AM2R](https://user-images.githubusercontent.com/90729203/143774469-93384c39-bd6b-4366-bdac-dadd3da3ba05.jpg)
![imagem](https://user-images.githubusercontent.com/90729203/143774034-ed314f47-20d3-49dc-8add-602b71d80011.png)
![imagem](https://user-images.githubusercontent.com/90729203/143773829-108dc00e-e2ad-4c61-b72d-4bcfa7ca3d85.png)
[Ryujinx_1.0.0+2522726_2021-11-25_09-01-37.log](https://github.com/Ryujinx/Ryujinx/files/7613780/Ryujinx_1.0.0%2B2522726_2021-11-25_09-01-37.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-12-11.log](https://github.com/Ryujinx/Ryujinx/files/7613782/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-12-11.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-13-17.log](https://github.com/Ryujinx/Ryujinx/files/7613783/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-13-17.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-16-22.log](https://github.com/Ryujinx/Ryujinx/files/7613796/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-16-22.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-30-04.log](https://github.com/Ryujinx/Ryujinx/files/7613809/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-30-04.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-35-55.log](https://github.com/Ryujinx/Ryujinx/files/7613819/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-35-55.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-42-21.log](https://github.com/Ryujinx/Ryujinx/files/7613827/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-42-21.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-43-28.log](https://github.com/Ryujinx/Ryujinx/files/7613850/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-43-28.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-49-23.log](https://github.com/Ryujinx/Ryujinx/files/7613855/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-49-23.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-52-18.log](https://github.com/Ryujinx/Ryujinx/files/7613856/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-52-18.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_12-54-49.log](https://github.com/Ryujinx/Ryujinx/files/7613862/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-54-49.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_13-00-24.log](https://github.com/Ryujinx/Ryujinx/files/7613869/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-00-24.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_13-06-56.log](https://github.com/Ryujinx/Ryujinx/files/7613875/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-06-56.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_13-11-42.log](https://github.com/Ryujinx/Ryujinx/files/7613885/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-11-42.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_13-15-39.log](https://github.com/Ryujinx/Ryujinx/files/7613897/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-15-39.log)
[Ryujinx_1.0.0+555fa00_2021-11-28_13-22-24.log](https://github.com/Ryujinx/Ryujinx/files/7613908/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-22-24.log)

2021-11-29 02:42 UTC, jduncanator commented
> Win10 64 bits Sapphire Radeon RX 580 series X 4GB Ryzen 7 2700x 16GB ram driver 21.11.3 Lastest PR Vulkan ryujinx-Release-1.0.0+555fa00-win_x64 Graphics Backend: on Disable AMD Image Sharpenin it's transparent because of reshade, but when it's full screen it's not transparent AM2R is loading much faster, but needs to improve more, Mario Kart is almost like Cemu, but there are some parts that have fps drop Crash trilogy continues with those errors, but for example the monkey there now has a body, but the proportions and texture errors (apart from the slow video) remain now in Haven the grass is loading as it should and the fps rate is more consistent, plus Jacke Ax still has the sprites broken Fuga it's almost, there are still some texture errors Sonic Colours doesn't work anymore New Super Mario Bros continue with the black textures Zelda Link Awakening has fps ranges from 27 to 60 fps, in addition to that black bar that appears on fmvs of many games Final Fantasy VIII still has slow video, even most of the game is perfectly playable, but then the videos get very slow Zelda Skyway Sword continues with texture issues (same as Fuga) including this hideous brown screen Rockman 11 there are several texture errors Super Mario Odyssey is having texture problems and yield losses ![imagem](https://user-images.githubusercontent.com/90729203/143776705-7d6331aa-2ce1-414d-929f-2c2efa56943a.png) ![imagem](https://user-images.githubusercontent.com/90729203/143776429-84c5c496-e44d-4bb5-ae62-f0565cd0fae5.png) ![imagem](https://user-images.githubusercontent.com/90729203/143776200-d126fd07-9dbb-4dd9-bf14-31365e72e4c7.png) ![imagem](https://user-images.githubusercontent.com/90729203/143776027-75dc2eff-0507-412e-897e-90a656ec9bab.png) ![imagem](https://user-images.githubusercontent.com/90729203/143775640-3f09b2dc-8647-4311-bc8d-031334c8fd48.png) ![imagem](https://user-images.githubusercontent.com/90729203/143775490-30b51194-c37e-4f6b-a516-e54ec303c75d.png) ![imagem](https://user-images.githubusercontent.com/90729203/143775369-2a5b1731-3c8d-458d-9d84-d745d42b331b.png) ![imagem](https://user-images.githubusercontent.com/90729203/143775100-4d8b8421-b41e-4001-ac40-6bbfdc6dd49a.png) ![imagem](https://user-images.githubusercontent.com/90729203/143774789-b3e6363a-57fc-48c7-becd-11860320965f.png) ![AM2R](https://user-images.githubusercontent.com/90729203/143774469-93384c39-bd6b-4366-bdac-dadd3da3ba05.jpg) ![imagem](https://user-images.githubusercontent.com/90729203/143774034-ed314f47-20d3-49dc-8add-602b71d80011.png) ![imagem](https://user-images.githubusercontent.com/90729203/143773829-108dc00e-e2ad-4c61-b72d-4bcfa7ca3d85.png) [Ryujinx_1.0.0+2522726_2021-11-25_09-01-37.log](https://github.com/Ryujinx/Ryujinx/files/7613780/Ryujinx_1.0.0%2B2522726_2021-11-25_09-01-37.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-12-11.log](https://github.com/Ryujinx/Ryujinx/files/7613782/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-12-11.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-13-17.log](https://github.com/Ryujinx/Ryujinx/files/7613783/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-13-17.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-16-22.log](https://github.com/Ryujinx/Ryujinx/files/7613796/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-16-22.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-30-04.log](https://github.com/Ryujinx/Ryujinx/files/7613809/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-30-04.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-35-55.log](https://github.com/Ryujinx/Ryujinx/files/7613819/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-35-55.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-42-21.log](https://github.com/Ryujinx/Ryujinx/files/7613827/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-42-21.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-43-28.log](https://github.com/Ryujinx/Ryujinx/files/7613850/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-43-28.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-49-23.log](https://github.com/Ryujinx/Ryujinx/files/7613855/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-49-23.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-52-18.log](https://github.com/Ryujinx/Ryujinx/files/7613856/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-52-18.log) [Ryujinx_1.0.0+555fa00_2021-11-28_12-54-49.log](https://github.com/Ryujinx/Ryujinx/files/7613862/Ryujinx_1.0.0%2B555fa00_2021-11-28_12-54-49.log) [Ryujinx_1.0.0+555fa00_2021-11-28_13-00-24.log](https://github.com/Ryujinx/Ryujinx/files/7613869/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-00-24.log) [Ryujinx_1.0.0+555fa00_2021-11-28_13-06-56.log](https://github.com/Ryujinx/Ryujinx/files/7613875/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-06-56.log) [Ryujinx_1.0.0+555fa00_2021-11-28_13-11-42.log](https://github.com/Ryujinx/Ryujinx/files/7613885/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-11-42.log) [Ryujinx_1.0.0+555fa00_2021-11-28_13-15-39.log](https://github.com/Ryujinx/Ryujinx/files/7613897/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-15-39.log) [Ryujinx_1.0.0+555fa00_2021-11-28_13-22-24.log](https://github.com/Ryujinx/Ryujinx/files/7613908/Ryujinx_1.0.0%2B555fa00_2021-11-28_13-22-24.log)

Make sure you're testing with ReShade and any other external graphics tools disabled. Otherwise, there is no way for us to determine if a bug/issue is caused by ReShare or by the Vulkan backend itself.

2021-11-29 13:05 UTC, AlfredoDore commented
> 

sim estou testando, os problemas gráficos são os mesmos desabilitados e habilitados e como disse, não fica transparente em tela cheia

2021-11-29 19:59 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+555fa00-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Starlink has improved a lot, in the videos and in the tutorial there is audio loss, I would say it had a 40% improvement, there are still these squares on the screen and the video playback is very slow, this improvement has also caused Haven to improve by 80%, both just need more throughput, Starlink still has explosions of vertices, with these improvements it made me more excited about making bug reports 
Resident Evil 1 HD still has the problem of not walking forward (classic controller and which I prefer) the new controller is normal 



![imagem](https://user-images.githubusercontent.com/90729203/143928046-351193f6-b56d-42ad-aba1-cc5d7dd25df5.png)
![imagem](https://user-images.githubusercontent.com/90729203/143928420-0a244bba-2706-4e79-8143-aeeec4dee9fd.png)
![imagem](https://user-images.githubusercontent.com/90729203/143928627-062fd050-a3d0-4631-9b96-6b1e4a4f697d.png)
![imagem](https://user-images.githubusercontent.com/90729203/143930497-cbd89eb9-6c52-4b1c-928e-c83b65a03fb1.png)
[Ryujinx_1.0.0+555fa00_2021-11-29_15-54-05.log](https://github.com/Ryujinx/Ryujinx/files/7620651/Ryujinx_1.0.0%2B555fa00_2021-11-29_15-54-05.log)
[Ryujinx_1.0.0+555fa00_2021-11-29_16-42-34.log](https://github.com/Ryujinx/Ryujinx/files/7620743/Ryujinx_1.0.0%2B555fa00_2021-11-29_16-42-34.log)

2021-11-29 20:35 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+555fa00-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I can accurately say that Haven is working much better than in the OpenGL version, the fps are very constant, you just need to polish the yield more 
as for Rockman 11 and Resident Evil 0, they both have the same texture problem in the eyes and some things (RE 0 very visible in the eyes) so I am sending the Rockman 11 Vulkan and OpenGL Log as this problem does not occur in OpenGL 
OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/143938444-f53675a0-0505-46b2-8d14-ce8794bf83df.png)
![imagem](https://user-images.githubusercontent.com/90729203/143938540-526f23ea-a2a6-4bcc-ab93-66219524af70.png)
Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/143937580-0f617bad-9d01-4fa1-aafc-52a9eec5c4c5.png)
![imagem](https://user-images.githubusercontent.com/90729203/143938139-5312098b-faff-4aea-927c-547c02516b80.png)
![imagem](https://user-images.githubusercontent.com/90729203/143936355-5a09dfd9-f088-4ed7-a1ed-895a49b8d9bb.png)
[Ryujinx_1.0.0+555fa00_2021-11-29_17-05-13.log](https://github.com/Ryujinx/Ryujinx/files/7620871/Ryujinx_1.0.0%2B555fa00_2021-11-29_17-05-13.log)
[Ryujinx_1.0.0+555fa00_2021-11-29_17-21-41.log](https://github.com/Ryujinx/Ryujinx/files/7620936/Ryujinx_1.0.0%2B555fa00_2021-11-29_17-21-41.log)
log OpenGL
[Ryujinx_1.0.7112_2021-11-29_17-28-33.log](https://github.com/Ryujinx/Ryujinx/files/7620943/Ryujinx_1.0.7112_2021-11-29_17-28-33.log)

2021-12-03 21:05 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+4a0beac-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Final Fantasy VIII and VII videos are still too slow, it's a really annoying thing to play like that 
in addition Final Fantasy VII has many image errors and several graphical glitches 
AM2R there are some problems, but the main one is the loading, which is very slow 
Nintendo 64 online still doesn't work and the problem with the Super Nintendo online is that you can't add mods to add roms, while the NES one is doing very well 
Crash trilogy improved the video speed (is as it should be) the problem of textures and proportions continue, I will send the OpenGL and Vulkan Log for comparison  
Rockman 11 continues with the texture errors, but the performance has improved a lot, as well as Crash, I'm sending from OpenGL because there are no errors in these textures 
OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/144672359-c77b2fef-447e-4513-ae52-429c142bac65.png)
![imagem](https://user-images.githubusercontent.com/90729203/144672032-17f3aa23-ad7e-4feb-a6b7-a62fcbc4f6a8.png)
![imagem](https://user-images.githubusercontent.com/90729203/144670047-56e2c650-79e6-47c8-971f-9bcf0d7cb5e2.png)
![imagem](https://user-images.githubusercontent.com/90729203/144670241-72feabbd-509b-46ee-aed0-774ec91bd7e9.png)
![imagem](https://user-images.githubusercontent.com/90729203/144670334-77797c8b-c623-41e8-af44-989411e1efd6.png)

Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/144671716-b84c6499-77a6-4ded-b930-adb86dc3e811.png)
![imagem](https://user-images.githubusercontent.com/90729203/144671254-4f72a692-eaad-487a-9893-dc7c855a6170.png)
![imagem](https://user-images.githubusercontent.com/90729203/144669068-8aed2f9d-f379-4167-bf4f-2ce846f50d8b.png)
![imagem](https://user-images.githubusercontent.com/90729203/144669266-7dd43db8-0a64-4dbd-b2dc-1e9e064945f1.png)
![imagem](https://user-images.githubusercontent.com/90729203/144669433-deb953fd-5cc6-4260-9a12-b9c41855998c.png)
![imagem](https://user-images.githubusercontent.com/90729203/144668605-cf42e8ee-8c6b-4ba7-8d8f-c4336822dcdd.png)
![imagem](https://user-images.githubusercontent.com/90729203/144668328-4e7d69c9-a713-40ee-85d5-771e60ac247e.png)
![imagem](https://user-images.githubusercontent.com/90729203/144667397-6c53581e-2683-4297-a4e7-edcff1ac66dc.png)
![imagem](https://user-images.githubusercontent.com/90729203/144666401-89cff351-8b04-452a-976c-0319fa92ecb7.png)
![imagem](https://user-images.githubusercontent.com/90729203/144665223-8e0970a1-0a2b-4d91-8cf3-9db591b29e6f.png)
![imagem](https://user-images.githubusercontent.com/90729203/144664683-b40f5709-50a6-4982-80cd-3dbe3a6ce348.png)
Vulkan
[Ryujinx_1.0.0+4a0beac_2021-12-03_17-49-45.log](https://github.com/Ryujinx/Ryujinx/files/7652304/Ryujinx_1.0.0%2B4a0beac_2021-12-03_17-49-45.log)
[Ryujinx_1.0.0+4a0beac_2021-12-03_16-39-10.log](https://github.com/Ryujinx/Ryujinx/files/7652026/Ryujinx_1.0.0%2B4a0beac_2021-12-03_16-39-10.log)
[Ryujinx_1.0.0+4a0beac_2021-12-03_16-56-58.log](https://github.com/Ryujinx/Ryujinx/files/7652100/Ryujinx_1.0.0%2B4a0beac_2021-12-03_16-56-58.log)
[Ryujinx_1.0.0+4a0beac_2021-12-03_17-10-36.log](https://github.com/Ryujinx/Ryujinx/files/7652131/Ryujinx_1.0.0%2B4a0beac_2021-12-03_17-10-36.log)
[Ryujinx_1.0.0+4a0beac_2021-12-03_17-19-08.log](https://github.com/Ryujinx/Ryujinx/files/7652144/Ryujinx_1.0.0%2B4a0beac_2021-12-03_17-19-08.log)
[Ryujinx_1.0.0+4a0beac_2021-12-03_17-20-43.log](https://github.com/Ryujinx/Ryujinx/files/7652157/Ryujinx_1.0.0%2B4a0beac_2021-12-03_17-20-43.log)
[Ryujinx_1.0.0+4a0beac_2021-12-03_17-24-16.log](https://github.com/Ryujinx/Ryujinx/files/7652185/Ryujinx_1.0.0%2B4a0beac_2021-12-03_17-24-16.log)
[Ryujinx_1.0.0+4a0beac_2021-12-03_17-29-47.log](https://github.com/Ryujinx/Ryujinx/files/7652214/Ryujinx_1.0.0%2B4a0beac_2021-12-03_17-29-47.log)

OpenGL
[Ryujinx_1.0.7113_2021-12-03_17-38-34.log](https://github.com/Ryujinx/Ryujinx/files/7652264/Ryujinx_1.0.7113_2021-12-03_17-38-34.log)
[Ryujinx_1.0.7113_2021-12-03_17-57-02.log](https://github.com/Ryujinx/Ryujinx/files/7652318/Ryujinx_1.0.7113_2021-12-03_17-57-02.log)

2021-12-03 21:09 UTC, gdkchan commented
> Final Fantasy VIII and VII videos are still too slow, it's a really annoying thing to play like that

That is due to you using the SDL2 audio backend, you need to change to OpenAL for this game.

2021-12-03 21:12 UTC, AlfredoDore commented
> That is due to you using the SDL2 audio backend, you need to change to OpenAL for this game.

I understand, I was already thinking it was a video player problem or something, thank you

2021-12-04 14:03 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+4a0beac-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Mario Kart 8 keeps closing on Vulkan, in OpenGL this issue has been resolved 
even in OpenAL Starlink videos are slow and with audio cut, game performance and textures have improved a lot, but need more improvement ,it gives this kernel error constantly in addition, the screen still has grainy 
Metroid it has improved considerably, but it still needs improvement in yield loss and it still has the plants there with black textures, and they are not black textures. 
Donkey Kong Tropical Returns is back up and running, it needs performance improvement 
Resident Evil 1 still has the classic control problem of not moving forward, while Resident Evil Zero doesn't suffer from the same problem, but the textures of the characters' eyes keep flickering and probably have other texture errors 
in general I found the updates positive, but there are still textures and yield issues like for example Resident Evil Zero when it fires there is a small yield drop and the eye issue in RE Zero and Rockman 11 that don't occur in the OpenGL version 
![imagem](https://user-images.githubusercontent.com/90729203/144712313-9abc7553-b77e-45da-b9c4-bb1694cba196.png)
![imagem](https://user-images.githubusercontent.com/90729203/144712276-bb97e18e-2746-4ee3-a459-9f6b112a6fd5.png)
![imagem](https://user-images.githubusercontent.com/90729203/144711656-30b6b849-373f-49ba-bff7-df28b580db06.png)
![imagem](https://user-images.githubusercontent.com/90729203/144712066-cb57b204-d203-48ab-aa44-5591a43e7cea.png)
![imagem](https://user-images.githubusercontent.com/90729203/144711821-b15417ad-8061-443f-8195-fff2baa6806d.png)
![imagem](https://user-images.githubusercontent.com/90729203/144711624-40516f8f-fdb9-42a8-98c3-ee9795a774ec.png)
![imagem](https://user-images.githubusercontent.com/90729203/144711488-b24e2fdd-ec93-4c10-be91-133886430b24.png)
![imagem](https://user-images.githubusercontent.com/90729203/144711192-20471ff2-37ef-4f0c-a62c-f7d2a35e35bf.png)
![imagem](https://user-images.githubusercontent.com/90729203/144710573-cc908cab-fa16-4546-ab69-c7e15686a058.png)
![imagem](https://user-images.githubusercontent.com/90729203/144710491-a209ec1b-23c0-47f7-b19d-4da43ff54196.png)
![imagem](https://user-images.githubusercontent.com/90729203/144709949-79909be5-b5c1-4e3a-91e0-067bcc8471bd.png)
![imagem](https://user-images.githubusercontent.com/90729203/144710280-5f48ebe6-8932-482f-88a3-7d216f5bda59.png)
[Ryujinx_1.0.0+4a0beac_2021-12-04_09-31-53.log](https://github.com/Ryujinx/Ryujinx/files/7653913/Ryujinx_1.0.0%2B4a0beac_2021-12-04_09-31-53.log)
[Ryujinx_1.0.0+4a0beac_2021-12-04_09-34-24.log](https://github.com/Ryujinx/Ryujinx/files/7653988/Ryujinx_1.0.0%2B4a0beac_2021-12-04_09-34-24.log)
[Ryujinx_1.0.0+4a0beac_2021-12-04_10-17-28.log](https://github.com/Ryujinx/Ryujinx/files/7654006/Ryujinx_1.0.0%2B4a0beac_2021-12-04_10-17-28.log)
[Ryujinx_1.0.0+4a0beac_2021-12-04_10-31-59.log](https://github.com/Ryujinx/Ryujinx/files/7654008/Ryujinx_1.0.0%2B4a0beac_2021-12-04_10-31-59.log)
[Ryujinx_1.0.0+4a0beac_2021-12-04_10-45-17.log](https://github.com/Ryujinx/Ryujinx/files/7654034/Ryujinx_1.0.0%2B4a0beac_2021-12-04_10-45-17.log)
[Ryujinx_1.0.0+4a0beac_2021-12-04_10-37-16.log](https://github.com/Ryujinx/Ryujinx/files/7654016/Ryujinx_1.0.0%2B4a0beac_2021-12-04_10-37-16.log)
[Ryujinx_1.0.0+4a0beac_2021-12-04_11-00-00.log](https://github.com/Ryujinx/Ryujinx/files/7654045/Ryujinx_1.0.0%2B4a0beac_2021-12-04_11-00-00.log)

2021-12-05 00:32 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+23dfa33-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I don't know if you can see it, but it's the same graphic problem as Starlink, that is, if Starlink solves it, it solves this one too  I just got coins (hence this transparent number) 
![imagem](https://user-images.githubusercontent.com/90729203/144728884-1050ab3e-e31b-4eaf-b2b9-7a6f4fc33c89.png)
![imagem](https://user-images.githubusercontent.com/90729203/144728840-512fbb5b-df1c-45a1-a719-609e962996ee.png)
[Ryujinx_1.0.0+23dfa33_2021-12-04_21-23-52.log](https://github.com/Ryujinx/Ryujinx/files/7654995/Ryujinx_1.0.0%2B23dfa33_2021-12-04_21-23-52.log)

2021-12-05 10:20 UTC, curtive commented
Windows 10, x64
Radeon RX 5700 - 21.10.2
16GB RAM
ryujinx-Release-1.0.0+23dfa33-win_x64

Xenoblade Chronicles crashes at the menu. With OpenGL you are able to go ingame.
[Ryujinx_1.0.0+23dfa33_2021-12-05_11-18-45.log](https://github.com/Ryujinx/Ryujinx/files/7655659/Ryujinx_1.0.0%2B23dfa33_2021-12-05_11-18-45.log)

2021-12-07 00:59 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.11.3
Lastest PR Vulkan ryujinx-Release-1.0.0+23dfa33-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
RE 0 and 1 still have the same problem, 1 with the original do not walk forward control and 0 with eye textures (plus some yield losses when shooting) 
[Ryujinx_1.0.0+23dfa33_2021-12-06_21-50-46.log](https://github.com/Ryujinx/Ryujinx/files/7664587/Ryujinx_1.0.0%2B23dfa33_2021-12-06_21-50-46.log)
[Ryujinx_1.0.0+23dfa33_2021-12-06_21-54-28.log](https://github.com/Ryujinx/Ryujinx/files/7664604/Ryujinx_1.0.0%2B23dfa33_2021-12-06_21-54-28.log)

2021-12-07 15:41 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+23dfa33-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Resident Evil Revelations 1 and 2 need more optimization, there is a lot of drop in FPS, compared to 2 there are texture errors, not only in the blurring of the menu's eye, Fuga is now closing, you also need to improve the textures for 2D stuff, and the shaders for 2D stuff, because they get buggy, which doesn't happen in OpenGL
Zelda Skyway Sword has this grotestco texture error and yield issues 
![imagem](https://user-images.githubusercontent.com/90729203/145059947-d04c0ceb-7d05-4911-95c3-280978d69840.png)
![imagem](https://user-images.githubusercontent.com/90729203/145059508-865e77cd-ad9e-4efa-99bd-0454a378818b.png)
![imagem](https://user-images.githubusercontent.com/90729203/145059358-56cc71fb-84ee-4755-9667-e24c5ba6cdf3.png)
![imagem](https://user-images.githubusercontent.com/90729203/145058725-b6b07914-73b8-416e-b8bf-6628c28f2e91.png)
![imagem](https://user-images.githubusercontent.com/90729203/145057866-0b49bea2-d048-4807-89a8-a9a159a287d5.png)
![imagem](https://user-images.githubusercontent.com/90729203/145057468-528dfc87-165c-4980-84e0-3fa09ec6ad32.png)
![imagem](https://user-images.githubusercontent.com/90729203/145055031-07da35f7-99ee-43dd-90b1-3b877bec0ee5.png)
![imagem](https://user-images.githubusercontent.com/90729203/145053875-46db2780-2dae-4248-8dc6-0652bc6b0495.png)
![imagem](https://user-images.githubusercontent.com/90729203/145053482-f75b7df4-5d61-4a36-a20d-bf0b3c4a8ea7.png)
[Ryujinx_1.0.0+23dfa33_2021-12-07_11-54-03.log](https://github.com/Ryujinx/Ryujinx/files/7669277/Ryujinx_1.0.0%2B23dfa33_2021-12-07_11-54-03.log)
[Ryujinx_1.0.0+23dfa33_2021-12-07_12-03-49.log](https://github.com/Ryujinx/Ryujinx/files/7669415/Ryujinx_1.0.0%2B23dfa33_2021-12-07_12-03-49.log)
[Ryujinx_1.0.0+23dfa33_2021-12-07_12-21-04.log](https://github.com/Ryujinx/Ryujinx/files/7669455/Ryujinx_1.0.0%2B23dfa33_2021-12-07_12-21-04.log)
[Ryujinx_1.0.0+23dfa33_2021-12-07_12-26-46.log](https://github.com/Ryujinx/Ryujinx/files/7669478/Ryujinx_1.0.0%2B23dfa33_2021-12-07_12-26-46.log)
[Ryujinx_1.0.0+23dfa33_2021-12-07_12-31-40.log](https://github.com/Ryujinx/Ryujinx/files/7669549/Ryujinx_1.0.0%2B23dfa33_2021-12-07_12-31-40.log)

2021-12-07 22:14 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+23dfa33-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Megaton Musashi it's a launch game, it's fine but it needs more performance, Starlink still needs a lot of improvement, including its video playback (such a good game and still in this state, but I have faith in you guys) 
![imagem](https://user-images.githubusercontent.com/90729203/145113866-2fbcb63f-a1fe-4da3-bee6-841fa00fae19.png)
![imagem](https://user-images.githubusercontent.com/90729203/145113583-3425de13-ce4c-4e20-ac62-ab45934fb94f.png)
![imagem](https://user-images.githubusercontent.com/90729203/145113035-f3bd8be6-1515-4693-9ea3-c645fe44dbfb.png)
![imagem](https://user-images.githubusercontent.com/90729203/145111868-0e34dfab-8669-44c3-9cc3-48a785e620c8.png)
![imagem](https://user-images.githubusercontent.com/90729203/145111709-5115fec6-5ac2-48c0-89a1-2de3eb513e14.png)
[Ryujinx_1.0.0+23dfa33_2021-12-07_18-38-50.log](https://github.com/Ryujinx/Ryujinx/files/7671863/Ryujinx_1.0.0%2B23dfa33_2021-12-07_18-38-50.log)
[Ryujinx_1.0.0+23dfa33_2021-12-07_18-57-01.log](https://github.com/Ryujinx/Ryujinx/files/7671924/Ryujinx_1.0.0%2B23dfa33_2021-12-07_18-57-01.log)

2021-12-08 13:08 UTC, okt04175 commented
Can't run Pokemon BD/SP on Vulkan Mode.

SystemInfo
```
00:00:00.066 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.086 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+23dfa33
00:00:00.097 |N| Application Print: Operating System: Microsoft Windows 6.1.7601 Service Pack 1 (X64)
00:00:00.097 |N| Application Print: CPU: AMD Ryzen 7 5800X 8-Core Processor ; 16 logical
00:00:00.099 |N| Application Print: RAM: Total 65461 MB ; Available 52960 MB
00:00:00.101 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error
00:00:00.101 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.080 |I| Gpu : Backend Threading (On): True
00:00:00.256 |N| Application LoadApplication: Using Firmware Version: 13.0.0
00:00:00.256 |I| Application LoadApplication: Loading as NSP.
00:00:02.263 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD Radeon RX 6900 XT (Vulkan v1.2.178, Driver v2.0.188)
```

[Ryujinx_1.0.0+23dfa33_2021-12-08_20-51-28.log](https://github.com/Ryujinx/Ryujinx/files/7676144/Ryujinx_1.0.0%2B23dfa33_2021-12-08_20-51-28.log)

```
00:00:13.746 |E| .NET ThreadPool Worker Gpu .ctor: Shader compilation error: CompilationError Ryu:7: warning: '#extension' : extension not supported: GL_EXT_texture_shadow_lod
Ryu:192: error: 'gl_Layer' : required extension not requested: Possible extensions include:
Ryu: GL_ARB_shader_viewport_layer_array
Ryu: GL_NV_viewport_array2
00:00:29.658 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.PipelineState.CreateGraphicsPipeline(Vk api, Device device, ShaderCollection program, PipelineCache cache, RenderPass renderPass) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineState.cs:line 338
   at Ryujinx.Graphics.Vulkan.PipelineBase.CreatePipeline(PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1101
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1061
   at Ryujinx.Graphics.Vulkan.PipelineBase.Draw(Int32 vertexCount, Int32 instanceCount, Int32 firstVertex, Int32 firstInstance) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 247
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_40(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 143
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131

```

2021-12-08 16:12 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+26a8b74-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
in OpenGL Starlink doesn't suffer from screen grain and also has better textures, however both suffer from sluggishness and vertex bursts, videos run slow, plus I noticed kernel error: HLE.GuestThread.39 KernelSvc PrintResult: SendyncRequest64 returned error PortRemoteClosed.
HLE. Thread. 15 KernelIpc CallHipcMethod: Missing service Ryujinx.HLE.HOS. Services.Hid.IHidbusServer: 1 ignored 
then I sent Vulkan and OpenGL log for help 
OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/145241217-ecb8af6b-d040-43ac-8a4d-8578aca23635.png)
![imagem](https://user-images.githubusercontent.com/90729203/145240933-def54fdf-adb1-4d0a-b510-cee881ea2e04.png)
![imagem](https://user-images.githubusercontent.com/90729203/145240534-d3317887-0f2b-4450-a933-3bdbf09af42f.png)
Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/145237778-9306cad6-194f-458c-9b4e-3c7ab5b2f2b3.png)
![imagem](https://user-images.githubusercontent.com/90729203/145238056-6dd09b80-048c-423c-b602-edab79b54cb4.png)
![imagem](https://user-images.githubusercontent.com/90729203/145235539-7626bf38-aefa-46b0-8d1a-d3ce20d50c48.png)
![imagem](https://user-images.githubusercontent.com/90729203/145234903-afd21d69-8960-477c-9ac3-4580279f5e77.png)
![imagem](https://user-images.githubusercontent.com/90729203/145229797-5eb71d4b-b831-4b10-8565-417a36f54f3d.png)
![imagem](https://user-images.githubusercontent.com/90729203/145230760-01aa5585-5a22-4eee-b5f9-557a04695786.png)
![imagem](https://user-images.githubusercontent.com/90729203/145231641-56fd0d12-aec8-4167-8fdc-33d03f124d4a.png)
log OpenGL
[Ryujinx_1.0.7116_2021-12-08_12-48-29.log](https://github.com/Ryujinx/Ryujinx/files/7677325/Ryujinx_1.0.7116_2021-12-08_12-48-29.log)
log Vulkan
[Ryujinx_1.0.0+26a8b74_2021-12-08_11-49-54.log](https://github.com/Ryujinx/Ryujinx/files/7677177/Ryujinx_1.0.0%2B26a8b74_2021-12-08_11-49-54.log)

2021-12-08 16:27 UTC, AlfredoDore commented
I don't know if it helps, but the Starlink Firmware is the 9.0.1

2021-12-09 15:47 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+26a8b74-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Mario Kart has weird lighting and vertex explosions in addition to yield drops, Super Mario Odyssey has several issues to solve, among them constant yield drops and flickering textures, Nintendo 64 still doesn't work and still doesn't work adding Super Nintendo mods 
![imagem](https://user-images.githubusercontent.com/90729203/145428032-2a757db0-d90d-433f-bee1-94f171d23ce1.png)
![imagem](https://user-images.githubusercontent.com/90729203/145427629-32f21fe4-50cc-4687-9ece-53934363acc6.png)
![imagem](https://user-images.githubusercontent.com/90729203/145427385-d34d4be1-4f99-4f6f-a49f-416b9f3decf8.png)
![imagem](https://user-images.githubusercontent.com/90729203/145422993-bf7b8007-9143-44e6-bfd9-5362b6c432b9.png)
![imagem](https://user-images.githubusercontent.com/90729203/145420295-e9ac5910-5233-444c-a9fb-7a68b95082c9.png)
![imagem](https://user-images.githubusercontent.com/90729203/145420653-29cecb58-44a2-4a09-be51-aa114f9b08a3.png)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-03-43.log](https://github.com/Ryujinx/Ryujinx/files/7686131/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-03-43.log)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-03-43.log](https://github.com/Ryujinx/Ryujinx/files/7686390/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-03-43.log)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-33-27.log](https://github.com/Ryujinx/Ryujinx/files/7686395/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-33-27.log)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-34-38.log](https://github.com/Ryujinx/Ryujinx/files/7686401/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-34-38.log)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-35-56.log](https://github.com/Ryujinx/Ryujinx/files/7686412/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-35-56.log)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-38-00.log](https://github.com/Ryujinx/Ryujinx/files/7686474/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-38-00.log)

2021-12-09 15:50 UTC, riperiperi commented
Issues with N64 emulation are more related to not supporting the JIT services, rather than any graphics backend.

2021-12-09 16:44 UTC, AlfredoDore commented
> Issues with N64 emulation are more related to not supporting the JIT services, rather than any graphics backend.

I understand, I'm crazy to play Starlink, before the textures were black, now you can see it right, but there's still a lot to improve, especially video playback, in several games (regardless of the audio option) it's slow

2021-12-10 02:02 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+5fa0a75-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I noticed an improvement in performance in Starlink, but still the same problems in textures, Super Mario Odyssey still needs a lot of improvement until it reaches the OpenGL version, Zelda Link Awakerning has a lot of fps variation, besides that there's this triangle thing 
![imagem](https://user-images.githubusercontent.com/90729203/145504466-953a6531-c4c2-462e-ae3c-bd357566e244.png)
![imagem](https://user-images.githubusercontent.com/90729203/145504036-07b09161-8f21-4fd0-8b68-ed384bbe187a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145503974-2aba125b-f5f3-41d1-96e9-f491cc6b7994.png)
![imagem](https://user-images.githubusercontent.com/90729203/145503917-b23e77a2-868c-4863-b410-c894c6ce577b.png)
![imagem](https://user-images.githubusercontent.com/90729203/145503715-e9200ed6-e82c-463b-8be8-2efab9bc9b04.png)
![imagem](https://user-images.githubusercontent.com/90729203/145503447-1e7bcb6d-cefb-487b-98d6-657c4fe14e8c.png)
![imagem](https://user-images.githubusercontent.com/90729203/145503155-4ec5c3f8-80df-456c-b20f-f8a9007b00b1.png)
![imagem](https://user-images.githubusercontent.com/90729203/145502750-f6f83819-be43-4d85-939b-235e73a0d99a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145502661-69ed0ed7-c799-43f0-832d-d88a20cd6195.png)
![imagem](https://user-images.githubusercontent.com/90729203/145502582-c1a3b6ad-13e3-4f66-b984-dce761d2e351.png)
![imagem](https://user-images.githubusercontent.com/90729203/145502453-938e2101-497d-45a2-b8a5-dfa3ca3743f8.png)
![imagem](https://user-images.githubusercontent.com/90729203/145502276-95ab4335-cf2a-4775-9d53-64f04b3949be.png)
![imagem](https://user-images.githubusercontent.com/90729203/145500278-ce147f17-9580-4465-998a-354e288a2b43.png)
![imagem](https://user-images.githubusercontent.com/90729203/145500348-ff0a1a8d-a756-47fb-8a20-707c6ba3acb6.png)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-38-00.log](https://github.com/Ryujinx/Ryujinx/files/7689461/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-38-00.log)
[Ryujinx_1.0.0+26a8b74_2021-12-09_12-38-00.log](https://github.com/Ryujinx/Ryujinx/files/7689466/Ryujinx_1.0.0%2B26a8b74_2021-12-09_12-38-00.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-09_22-32-41.log](https://github.com/Ryujinx/Ryujinx/files/7689493/Ryujinx_1.0.0%2B5fa0a75_2021-12-09_22-32-41.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-09_22-40-09.log](https://github.com/Ryujinx/Ryujinx/files/7689535/Ryujinx_1.0.0%2B5fa0a75_2021-12-09_22-40-09.log)

2021-12-10 17:55 UTC, AlfredoDore commented
Final Fantasy VII is practically unplayable 
Jack Axe has the most broken sprites ever 
AM2R it's really slow in loading and there is an error in the sprites 
Pokémon Shield need income 
the new Pokemon closes 
![imagem](https://user-images.githubusercontent.com/90729203/145618874-74368989-5468-4b9d-8117-93dbf27bb913.png)
![imagem](https://user-images.githubusercontent.com/90729203/145618739-77d0c073-1192-44f8-80f0-0e212af34306.png)
![imagem](https://user-images.githubusercontent.com/90729203/145618027-f73c0c3f-9fb8-47fc-ac85-e9a2bfe80af7.png)
![imagem](https://user-images.githubusercontent.com/90729203/145617823-f115ce11-82e3-43de-8b9c-1adc7ace535f.png)
![imagem](https://user-images.githubusercontent.com/90729203/145617240-215770e1-80a5-40e9-8471-b44bd3a8a3ad.png)
![imagem](https://user-images.githubusercontent.com/90729203/145617072-baf26035-31b2-4be6-baab-52bbd9325c2a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145616804-39867a1a-db32-4276-85db-95902c03e0ff.png)
![imagem](https://user-images.githubusercontent.com/90729203/145616687-473f93ce-5b20-4b7f-88cb-603ab0300784.png)
![imagem](https://user-images.githubusercontent.com/90729203/145616604-6924c79e-be66-4e03-a423-bc8418dba2b2.png)
![imagem](https://user-images.githubusercontent.com/90729203/145616523-b1687a6b-518f-45ce-9f92-de9ea96a66db.png)
![imagem](https://user-images.githubusercontent.com/90729203/145616214-21322abc-1db4-458d-8df7-d9bd42754188.png)
![imagem](https://user-images.githubusercontent.com/90729203/145615882-23df5e52-fbe7-4f39-9d46-5fdd770bd69d.png)
![imagem](https://user-images.githubusercontent.com/90729203/145615029-147656ce-ac15-439f-b379-f2c772cc9af9.png)
![imagem](https://user-images.githubusercontent.com/90729203/145614250-dcee0c78-d038-4478-b22e-7296628b3ea2.png)
![imagem](https://user-images.githubusercontent.com/90729203/145614367-c6e2d838-231d-48e9-81c8-094a5483753e.png)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_14-10-49.log](https://github.com/Ryujinx/Ryujinx/files/7694423/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_14-10-49.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_14-19-33.log](https://github.com/Ryujinx/Ryujinx/files/7694424/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_14-19-33.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_14-26-49.log](https://github.com/Ryujinx/Ryujinx/files/7694455/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_14-26-49.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_14-33-20.log](https://github.com/Ryujinx/Ryujinx/files/7694472/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_14-33-20.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_14-37-01.log](https://github.com/Ryujinx/Ryujinx/files/7694495/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_14-37-01.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_14-44-00.log](https://github.com/Ryujinx/Ryujinx/files/7694536/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_14-44-00.log)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_14-53-31.log](https://github.com/Ryujinx/Ryujinx/files/7694565/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_14-53-31.log)

2021-12-10 18:35 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+5fa0a75-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Resident Evil HD still doesn't walk in front of the original control 
Resident Evil Revelations 2 had a very big performance improvement, but still needs more stability 
![imagem](https://user-images.githubusercontent.com/90729203/145623276-269b72f4-b394-4ae6-ab37-3e666e57530a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145622482-2f5e817d-f490-4be0-9cac-073529a8dae8.png)
![imagem](https://user-images.githubusercontent.com/90729203/145622410-2009fb68-98a8-4fda-98d5-7bc9ed0ea9ed.png)
[Ryujinx_1.0.0+5fa0a75_2021-12-10_15-15-09.log](https://github.com/Ryujinx/Ryujinx/files/7694717/Ryujinx_1.0.0%2B5fa0a75_2021-12-10_15-15-09.log)

2021-12-11 13:20 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+9f98684-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Final Fantasy VIII is practically perfect, Crash geometry is very strange and needs more performance (crashes a lot), Haven graphically looks wonderful, just needs more performance, Baldo needs performance and there's this rectangle on the screen (many 2D games suffer with that) I put Crash's OpenGL because its textures and geometry are perfect, New SUPER Mario Bros. now just needs more performance  
Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/145677552-df169ce3-019f-475d-8ec3-89ef7123db46.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677519-f0290fdf-ef9e-4ec0-b6c9-0b183333bd62.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677439-c2e8dcac-1c04-40c3-9408-d4a1f37f96c6.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677402-4f9196cf-5d7f-4e8e-977e-1846fd7f3e3b.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677335-1e209c52-077a-442b-99b0-629d4d1c135b.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677305-3664ddcb-8500-422a-be2e-92ea09195e9c.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677101-6a8aaab2-f035-4cf8-8a1a-1e82260cad66.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677018-b867db66-008a-4c8c-b745-ae82614a417d.png)
![imagem](https://user-images.githubusercontent.com/90729203/145676833-2d469848-82ca-41fb-96fb-102658dd3f59.png)
![imagem](https://user-images.githubusercontent.com/90729203/145676675-5994eb10-6083-474f-a65c-a777fa7e6aa7.png)
![imagem](https://user-images.githubusercontent.com/90729203/145676661-dfa87330-7db5-4bba-ac36-6a40ccb01807.png)
![imagem](https://user-images.githubusercontent.com/90729203/145676634-8b7fbc9f-ae9e-48f7-ba42-b198005c9150.png)
![imagem](https://user-images.githubusercontent.com/90729203/145676552-dfb0339b-568d-4530-9a12-c4808025d439.png)
[Ryujinx_1.0.0+9f98684_2021-12-11_09-25-56.log](https://github.com/Ryujinx/Ryujinx/files/7696975/Ryujinx_1.0.0%2B9f98684_2021-12-11_09-25-56.log)
[Ryujinx_1.0.0+9f98684_2021-12-11_09-30-48.log](https://github.com/Ryujinx/Ryujinx/files/7696987/Ryujinx_1.0.0%2B9f98684_2021-12-11_09-30-48.log)
[Ryujinx_1.0.0+9f98684_2021-12-11_09-38-46.log](https://github.com/Ryujinx/Ryujinx/files/7697006/Ryujinx_1.0.0%2B9f98684_2021-12-11_09-38-46.log)
[Ryujinx_1.0.0+9f98684_2021-12-11_09-48-08.log](https://github.com/Ryujinx/Ryujinx/files/7697029/Ryujinx_1.0.0%2B9f98684_2021-12-11_09-48-08.log)
[Ryujinx_1.0.0+9f98684_2021-12-11_09-53-58.log](https://github.com/Ryujinx/Ryujinx/files/7697049/Ryujinx_1.0.0%2B9f98684_2021-12-11_09-53-58.log)
OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/145677653-87e6b5c7-6c22-4b73-8c0d-ea6e015436c0.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677714-41a8e870-9386-490b-b52b-4c7f68132b34.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677769-29c63afa-753a-46be-8bab-f7a13d5e2352.png)
![imagem](https://user-images.githubusercontent.com/90729203/145677838-5ccd0384-cd9a-4f58-a4b5-3a555ab86c4c.png)
[Ryujinx_1.0.7122_2021-12-11_10-06-42.log](https://github.com/Ryujinx/Ryujinx/files/7697076/Ryujinx_1.0.7122_2021-12-11_10-06-42.log)

2021-12-12 14:05 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+2e9336a-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Zelda a Link Awakerning it has these triangles, it also needs more income 
Jack Axe it has totally broken sprites 
Mario Kart 8 has these lights 
Crash still with texture errors and bad proportions 
Pokémon Sword needs a lot of performance, especially in animations 
Pokémon Shiny Diamond does not start 
Haven needs a little more performance, there's also an error where when we camp, the image is black, in OpenGL it's normal 
![imagem](https://user-images.githubusercontent.com/90729203/145715437-c67c5e27-cc6f-4eba-b1cd-a6bea0a36c4d.png)
![imagem](https://user-images.githubusercontent.com/90729203/145715184-b31b034c-a39c-4cf3-9aad-e4720ae8af60.png)
![imagem](https://user-images.githubusercontent.com/90729203/145715083-eb3cfedc-05e7-4c77-a374-0eada3568961.png)
![imagem](https://user-images.githubusercontent.com/90729203/145715039-1be75963-abd1-4550-9a35-179bd00a9481.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714949-6653a749-5494-4d22-af1b-3cfdb1272b5a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714808-3ab57222-39ca-4fef-bab9-430ad2b77103.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714779-a7f1d374-b1a2-4870-b7ea-a37b65c54215.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714739-27e08ef6-1e31-4742-ad27-e7d7d91a3095.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714698-1b2d3053-f969-453d-9798-daaef40e5d2a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714646-df80fb30-cc61-4aba-ba55-491f2256f6ca.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714614-99e19762-3356-4676-aaf3-c5f9fe9c0061.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714593-c2d336ca-ec7e-4502-b739-33363f08136f.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714477-dd8e2cd9-aec1-40b0-8d73-2d954e9a9879.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714252-832757a3-ff93-43d6-b9b4-a3e85d45239f.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714268-6ad79f3c-3221-45aa-a46a-84ac29a5d79e.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714288-80327646-079e-4eae-9bc0-ca13dd741b7a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714352-6fb9458b-b6f6-4dcd-a8a0-709b4c781313.png)
![imagem](https://user-images.githubusercontent.com/90729203/145714380-adc5997a-7a02-41df-97e3-1e4e8a43663d.png)
[Ryujinx_1.0.0+2e9336a_2021-12-12_10-34-04.log](https://github.com/Ryujinx/Ryujinx/files/7698814/Ryujinx_1.0.0%2B2e9336a_2021-12-12_10-34-04.log)
[Ryujinx_1.0.0+2e9336a_2021-12-12_10-27-25.log](https://github.com/Ryujinx/Ryujinx/files/7698818/Ryujinx_1.0.0%2B2e9336a_2021-12-12_10-27-25.log)
[Ryujinx_1.0.0+2e9336a_2021-12-12_10-38-10.log](https://github.com/Ryujinx/Ryujinx/files/7698836/Ryujinx_1.0.0%2B2e9336a_2021-12-12_10-38-10.log)
[Ryujinx_1.0.0+2e9336a_2021-12-12_10-45-03.log](https://github.com/Ryujinx/Ryujinx/files/7698845/Ryujinx_1.0.0%2B2e9336a_2021-12-12_10-45-03.log)
[Ryujinx_1.0.0+2e9336a_2021-12-12_10-52-39.log](https://github.com/Ryujinx/Ryujinx/files/7698857/Ryujinx_1.0.0%2B2e9336a_2021-12-12_10-52-39.log)
[Ryujinx_1.0.0+2e9336a_2021-12-12_10-55-43.log](https://github.com/Ryujinx/Ryujinx/files/7698860/Ryujinx_1.0.0%2B2e9336a_2021-12-12_10-55-43.log)

OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/145715542-964e4984-abd1-4354-a940-cfdcc8bb5e5b.png)
[Ryujinx_1.0.7122_2021-12-12_11-01-03.log](https://github.com/Ryujinx/Ryujinx/files/7698870/Ryujinx_1.0.7122_2021-12-12_11-01-03.log)

2021-12-12 15:50 UTC, GamerzHell9137 commented
Seems like with the latest build Taiko has been fixed! 
![image](https://user-images.githubusercontent.com/2002038/145719242-85181511-e2c8-4719-a94c-9878a2bbfe96.png)

Monster Hunter still looks the same but it might be something else 
![image](https://user-images.githubusercontent.com/2002038/145719274-aa05e69a-b6c9-40fb-99ff-a1d55508191d.png)

2021-12-12 16:12 UTC, AlfredoDore commented
> Seems like with the latest build Taiko has been fixed! ![image](https://user-images.githubusercontent.com/2002038/145719242-85181511-e2c8-4719-a94c-9878a2bbfe96.png)
> 
> Monster Hunter still looks the same but it might be something else ![image](https://user-images.githubusercontent.com/2002038/145719274-aa05e69a-b6c9-40fb-99ff-a1d55508191d.png)

put the log files 
![imagem](https://user-images.githubusercontent.com/90729203/145720011-4ed98ab3-f511-4cfe-8766-3cd0c51cb52c.png)

2021-12-13 20:18 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+2e9336a-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
finally Rebecca and Rockman's eye problems are gone, they are now normal, however RE Revelations 1 and RE 0 need performance improvement, AM2R needs sprite improvements and loading improvement (takes too long) 
it would be good for you to straighten out the RE 1 controller, the original controller is not working, only the alternative one works 
I changed the prodkey to 13.2, but apparently that's not what improved the graphics on Rockman 11 and RE 0
Niclelodeon All Star Brawl there are phases that are in trouble 
Sakura Nova is closing 
Cuphead is doing very well 
it looks like the blurring error in the eye center of Resident Evil Revelations 2 has been fixed (it was a barely visible error, had to pay close attention) 
still about Resident Evil Revelations 2, in the print it doesn't appear, but the dark side flashes green in the picture collection 
another error of RE Revelations 2 is this lighting 
![imagem](https://user-images.githubusercontent.com/90729203/145882233-bca6734b-fc32-4d39-a146-7ecd0464ddbf.png)
![imagem](https://user-images.githubusercontent.com/90729203/145882133-154d3fc6-0d5d-4ccc-88ae-d0bd03dbdfb4.png)
![imagem](https://user-images.githubusercontent.com/90729203/145882047-36fcec0b-0c36-4532-9ad4-67a58b27f0d8.png)
![imagem](https://user-images.githubusercontent.com/90729203/145881647-a61d41c1-df30-41a1-8159-1d345d8827bf.png)
![imagem](https://user-images.githubusercontent.com/90729203/145881404-cbb42adf-b9d8-4fa4-8ac0-9cb33b4f3abd.png)
![imagem](https://user-images.githubusercontent.com/90729203/145880879-bb3b8854-aa3c-4991-bac8-265702710e0c.png)
![imagem](https://user-images.githubusercontent.com/90729203/145880168-27914df6-cb03-4450-90ac-59a51710f061.png)
![imagem](https://user-images.githubusercontent.com/90729203/145879758-02d58369-bb76-403e-8328-0da65dbf9ffe.png)
![imagem](https://user-images.githubusercontent.com/90729203/145879058-9077295c-ac50-40be-ac6f-9f940922c349.png)
![imagem](https://user-images.githubusercontent.com/90729203/145878848-f028a856-8a57-4d34-8ab5-3dc426d717be.png)
![imagem](https://user-images.githubusercontent.com/90729203/145878646-662b3ff2-7dcc-43a6-a376-14d9a3f0fa17.png)
![imagem](https://user-images.githubusercontent.com/90729203/145878445-2dc8dd62-4db5-4778-a667-9952fb7bcf2e.png)
![imagem](https://user-images.githubusercontent.com/90729203/145878348-3227e4b9-27a4-43e4-987a-e90e67708705.png)
![imagem](https://user-images.githubusercontent.com/90729203/145876650-69084249-65fc-4d28-b36c-610eb8f3aab9.png)
![imagem](https://user-images.githubusercontent.com/90729203/145875315-7c020117-9e2b-41f4-9ea9-29d8db5db50f.png)
![imagem](https://user-images.githubusercontent.com/90729203/145875212-7bae6c20-1b86-45e3-8bc4-4c24c67af7e4.png)
![imagem](https://user-images.githubusercontent.com/90729203/145874385-00f8c24f-b630-465e-ad1c-4d4d3a6ce7dc.png)
![imagem](https://user-images.githubusercontent.com/90729203/145873558-603807a4-87ed-4491-9ded-bea9b6692a3a.png)
![imagem](https://user-images.githubusercontent.com/90729203/145872068-dc248094-5da8-4f91-aefc-17d837aa8337.png)
![imagem](https://user-images.githubusercontent.com/90729203/145872162-c2264eb0-e9e2-4968-9e56-16371509c12e.png)
![imagem](https://user-images.githubusercontent.com/90729203/145872050-6d23033f-abd6-43b2-88af-6731c268be74.png)
![imagem](https://user-images.githubusercontent.com/90729203/145871815-69f2563d-37b1-45c8-857b-d4e8497c3925.png)
![imagem](https://user-images.githubusercontent.com/90729203/145870809-539f233c-9608-44bc-b2f3-1f75697dbce3.png)
[Ryujinx_1.0.0+2e9336a_2021-12-13_15-42-40.log](https://github.com/Ryujinx/Ryujinx/files/7706161/Ryujinx_1.0.0%2B2e9336a_2021-12-13_15-42-40.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_15-51-52.log](https://github.com/Ryujinx/Ryujinx/files/7706208/Ryujinx_1.0.0%2B2e9336a_2021-12-13_15-51-52.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_15-59-45.log](https://github.com/Ryujinx/Ryujinx/files/7706240/Ryujinx_1.0.0%2B2e9336a_2021-12-13_15-59-45.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_16-20-11.log](https://github.com/Ryujinx/Ryujinx/files/7706384/Ryujinx_1.0.0%2B2e9336a_2021-12-13_16-20-11.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_16-27-36.log](https://github.com/Ryujinx/Ryujinx/files/7706404/Ryujinx_1.0.0%2B2e9336a_2021-12-13_16-27-36.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_16-30-32.log](https://github.com/Ryujinx/Ryujinx/files/7706443/Ryujinx_1.0.0%2B2e9336a_2021-12-13_16-30-32.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_16-43-39.log](https://github.com/Ryujinx/Ryujinx/files/7706576/Ryujinx_1.0.0%2B2e9336a_2021-12-13_16-43-39.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_16-57-27.log](https://github.com/Ryujinx/Ryujinx/files/7706683/Ryujinx_1.0.0%2B2e9336a_2021-12-13_16-57-27.log)
[Ryujinx_1.0.0+2e9336a_2021-12-13_17-15-07.log](https://github.com/Ryujinx/Ryujinx/files/7706724/Ryujinx_1.0.0%2B2e9336a_2021-12-13_17-15-07.log)

2021-12-15 13:37 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+2e9336a-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
strange, yesterday there was an error in the sprites but today not, however the loading problem continues (loads are very slow, only OpenGL loads are a little faster, but not satisfactory) 
AM2r Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/146195939-7a2a5323-0132-4e2e-b458-62b1cf12b366.png)
AM2R OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/146194105-82f55fb7-ad36-4a72-a960-ae6a30478a5d.png)
log OpenGL
[Ryujinx_1.0.7124_2021-12-15_10-17-27.log](https://github.com/Ryujinx/Ryujinx/files/7719648/Ryujinx_1.0.7124_2021-12-15_10-17-27.log)
log Vulkan 
[Ryujinx_1.0.0+2e9336a_2021-12-15_10-26-36.log](https://github.com/Ryujinx/Ryujinx/files/7719720/Ryujinx_1.0.0%2B2e9336a_2021-12-15_10-26-36.log)

2021-12-18 23:52 UTC, AlfredoDore commented
Blaster Master Zero 1 crashes on update 1.6.1 
so far Super Mario 3D All Star's on Vulkan or Sunshine and Galaxy only has sound and no video 
Yoshi 
![imagem](https://user-images.githubusercontent.com/90729203/146658586-f8a8490c-013c-4726-9c48-5b1eead43c36.png)
![imagem](https://user-images.githubusercontent.com/90729203/146658542-0eefcfc1-64dc-4b90-9a18-bf40f2ca0680.png)
![imagem](https://user-images.githubusercontent.com/90729203/146658566-276637d1-d60b-427a-a0af-cdef747ef22c.png)
[Ryujinx_1.0.0+2e9336a_2021-12-18_20-44-12.log](https://github.com/Ryujinx/Ryujinx/files/7740116/Ryujinx_1.0.0%2B2e9336a_2021-12-18_20-44-12.log)
[Ryujinx_1.0.0+2e9336a_2021-12-18_20-42-06.log](https://github.com/Ryujinx/Ryujinx/files/7740117/Ryujinx_1.0.0%2B2e9336a_2021-12-18_20-42-06.log)
[Ryujinx_1.0.0+2e9336a_2021-12-18_20-46-24.log](https://github.com/Ryujinx/Ryujinx/files/7740124/Ryujinx_1.0.0%2B2e9336a_2021-12-18_20-46-24.log)

2021-12-19 00:22 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+2e9336a-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
OpenGL is normal, as for Vulkan this filter is brown, in addition it has a black texture in the intro 
Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/146659021-dc644488-90a8-4c4a-9212-4a5c54da9e00.png)
![imagem](https://user-images.githubusercontent.com/90729203/146659047-d974969d-287d-405d-bbd3-57551f83bde3.png)
![imagem](https://user-images.githubusercontent.com/90729203/146659056-d05ce890-855c-47d5-9e27-ae1120fd2728.png)
![imagem](https://user-images.githubusercontent.com/90729203/146659064-3d15af66-f73a-4090-b0bc-4f5f4384c86c.png)
[Ryujinx_1.0.0+2e9336a_2021-12-18_21-14-52.log](https://github.com/Ryujinx/Ryujinx/files/7740147/Ryujinx_1.0.0%2B2e9336a_2021-12-18_21-14-52.log)
OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/146658948-fcaa70be-0e18-40e1-a5ac-b61d67bca264.png)
![imagem](https://user-images.githubusercontent.com/90729203/146658970-93474ce0-3347-4805-9af9-a70d9ba36cd8.png)
![imagem](https://user-images.githubusercontent.com/90729203/146658995-108e857c-ed10-4d2b-b5c0-ad650d430f02.png)
[Ryujinx_1.0.7125_2021-12-18_21-10-20.log](https://github.com/Ryujinx/Ryujinx/files/7740149/Ryujinx_1.0.7125_2021-12-18_21-10-20.log)

2021-12-19 15:35 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+94b4312-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Bullets Strom it's full of vertex and texture explosions, plus it only works on Vulkan (it's Unreal Engine) 
Zelda Link Awakerning there are these problems with this triangle and a lot of loss of performance (there are several oscillations between 17 and 60 fps) 
In Super Mario Odyssey  as you approach the dinosaur, the frame rate drops and when you pick it up, the rate drops to 12/9, in addition the textures are blinking 
![imagem](https://user-images.githubusercontent.com/90729203/146680933-eaa7f174-3ef1-47bc-b437-f0bebae46c1f.png)
![imagem](https://user-images.githubusercontent.com/90729203/146680615-e7ef22b7-0609-4865-87ef-74470d38441b.png)
![imagem](https://user-images.githubusercontent.com/90729203/146680570-e4a270ed-4eb9-40d6-94e5-45412508996f.png)
![imagem](https://user-images.githubusercontent.com/90729203/146680540-6df97d6c-e4d4-4dff-b672-8a33780af74f.png)
![imagem](https://user-images.githubusercontent.com/90729203/146680479-55640d4a-6a0f-433c-9414-707bdcd11388.png)
![imagem](https://user-images.githubusercontent.com/90729203/146680372-a4cc1bc1-c20a-4f0f-84cc-ffe34d643767.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679928-cf2f6ad2-f8aa-444d-a2b3-a3c15ea5134b.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679899-448172be-cf18-4b15-b31c-30937b63e323.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679870-e5e5bd26-63c4-4520-b4ee-b59631e18854.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679820-8b2cb372-9c98-4ef2-94c3-30aced3a4311.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679743-e9c55458-710f-4374-8977-6ac8b8f10589.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679480-479af487-fecc-4092-ab0e-540d0da9a629.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679448-40a71d4a-a3a8-4840-9472-bc10db8c2031.png)
![imagem](https://user-images.githubusercontent.com/90729203/146679090-7fffdc68-d287-42fa-8104-3d0d97d1b126.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678983-1fcc5748-1a02-45ab-82aa-05238d4a013f.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678932-9112d214-0bf0-4258-9f7a-153058a0dc0b.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678897-806831b1-4b5a-4274-802c-7152a2b9f66b.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678368-c2c3c5a4-6f9c-49f6-9f4b-f64ac7aa241b.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678289-aab4248e-bc85-4ec0-9c38-aa7e23083ee4.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678175-273a2bdf-5f98-4847-86b3-4e7eeeb5f9b1.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678109-78d2161b-7860-441f-a6b1-c40c3767cb99.png)
![imagem](https://user-images.githubusercontent.com/90729203/146677898-5686bf89-165a-43c7-8036-3ced78349184.png)
![imagem](https://user-images.githubusercontent.com/90729203/146677944-993db192-ef5e-4ab8-88df-5d4087fdc884.png)
![imagem](https://user-images.githubusercontent.com/90729203/146677970-0577e813-c06f-4381-954f-8c5bb679f096.png)
![imagem](https://user-images.githubusercontent.com/90729203/146677990-342b535f-68d0-45db-a664-ef4575b1e03f.png)
![imagem](https://user-images.githubusercontent.com/90729203/146678005-781469d8-2d1a-4fe2-8c12-289d7be316cb.png)
[Ryujinx_1.0.0+94b4312_2021-12-19_11-10-17.log](https://github.com/Ryujinx/Ryujinx/files/7740933/Ryujinx_1.0.0%2B94b4312_2021-12-19_11-10-17.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_11-17-39.log](https://github.com/Ryujinx/Ryujinx/files/7740958/Ryujinx_1.0.0%2B94b4312_2021-12-19_11-17-39.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_11-37-03.log](https://github.com/Ryujinx/Ryujinx/files/7740980/Ryujinx_1.0.0%2B94b4312_2021-12-19_11-37-03.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_11-38-50.log](https://github.com/Ryujinx/Ryujinx/files/7741003/Ryujinx_1.0.0%2B94b4312_2021-12-19_11-38-50.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_11-48-21.log](https://github.com/Ryujinx/Ryujinx/files/7741023/Ryujinx_1.0.0%2B94b4312_2021-12-19_11-48-21.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_12-02-25.log](https://github.com/Ryujinx/Ryujinx/files/7741030/Ryujinx_1.0.0%2B94b4312_2021-12-19_12-02-25.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_12-08-01.log](https://github.com/Ryujinx/Ryujinx/files/7741058/Ryujinx_1.0.0%2B94b4312_2021-12-19_12-08-01.log)

2021-12-20 00:46 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+94b4312-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Haven is almost perfect, a little more frame-per-second stability and that's it. 
Super Mario World 3D only gives small bottlenecks 
Pokémon Brilliant Diamond  simply closes 
Pokémon Shield has large yield losses in open areas 
Yoshi has had dramatic improvements, but there are still too many textures flashing 
![imagem](https://user-images.githubusercontent.com/90729203/146697160-dd6f799f-5fcc-431e-be3d-847518d4cc76.png)
![imagem](https://user-images.githubusercontent.com/90729203/146696711-f1520830-5e4c-4825-9043-35b8d477ae1e.png)
![imagem](https://user-images.githubusercontent.com/90729203/146696070-657e7818-b189-47c6-b38c-f84ae374216e.png)
![imagem](https://user-images.githubusercontent.com/90729203/146695782-f7278ffc-badc-4fd9-a69f-a199367d184e.png)
[Ryujinx_1.0.0+94b4312_2021-12-19_20-59-32.log](https://github.com/Ryujinx/Ryujinx/files/7741854/Ryujinx_1.0.0%2B94b4312_2021-12-19_20-59-32.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_21-11-16.log](https://github.com/Ryujinx/Ryujinx/files/7741877/Ryujinx_1.0.0%2B94b4312_2021-12-19_21-11-16.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_21-27-42.log](https://github.com/Ryujinx/Ryujinx/files/7741903/Ryujinx_1.0.0%2B94b4312_2021-12-19_21-27-42.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_21-30-46.log](https://github.com/Ryujinx/Ryujinx/files/7741922/Ryujinx_1.0.0%2B94b4312_2021-12-19_21-30-46.log)
[Ryujinx_1.0.0+94b4312_2021-12-19_21-40-51.log](https://github.com/Ryujinx/Ryujinx/files/7741926/Ryujinx_1.0.0%2B94b4312_2021-12-19_21-40-51.log)

2021-12-20 14:13 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+94b4312-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
it needs performance in both, there is a lot of FPS variation, besides I can't take a print of the texture error, but the background there of the figures, which is black, turns green 
![imagem](https://user-images.githubusercontent.com/90729203/146780064-7eb4c8b3-4d30-4e0c-95dc-95456801120b.png)
![imagem](https://user-images.githubusercontent.com/90729203/146779979-b9f6745a-7574-4769-86a1-b8e0f033caf1.png)
![imagem](https://user-images.githubusercontent.com/90729203/146779101-88d79bf0-8c18-4529-9192-88d02229a571.png)
![imagem](https://user-images.githubusercontent.com/90729203/146778412-e1fac67a-7de8-40fc-a33e-df60e117d522.png)
![imagem](https://user-images.githubusercontent.com/90729203/146778571-07d6cdb6-fc3a-4af8-8bfb-2a02e6bacb70.png)
[Ryujinx_1.0.0+94b4312_2021-12-20_10-50-53.log](https://github.com/Ryujinx/Ryujinx/files/7745782/Ryujinx_1.0.0%2B94b4312_2021-12-20_10-50-53.log)
[Ryujinx_1.0.0+94b4312_2021-12-20_11-00-15.log](https://github.com/Ryujinx/Ryujinx/files/7745834/Ryujinx_1.0.0%2B94b4312_2021-12-20_11-00-15.log)

2021-12-20 17:36 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+94b4312-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Resident Evil the original controller still doesn't move forward, only backwards and sideways (Resident Evil 0 doesn't have the same problem) 
Resident Evil and 0 both have a drop in frame rate, just need more stability and of course, the 1 straighten the control 
Crash still has the proportions of bizarre textures (this does not happen in OpenGL or in the main )
Waifu Uncovered has problems with spraites, however now you can play, before they were all broken 
Jacke Axe is with the sprites totally broken, or is unplayable, which makes me think that you guys should improve the 2D platform of the emulator (drawn and animated games) 
 Metroid Dread need performance 
![imagem](https://user-images.githubusercontent.com/90729203/146808186-8abed5df-341a-4d64-bcf3-26da2cfdf6f3.png)
![imagem](https://user-images.githubusercontent.com/90729203/146806887-1a09867a-62eb-4516-b4b3-ef4bad4adbb9.png)
![imagem](https://user-images.githubusercontent.com/90729203/146805587-9b454210-cafb-4af6-8a11-21112e0ba358.png)
![imagem](https://user-images.githubusercontent.com/90729203/146805356-cb6386fd-7643-4428-a16e-6b4b69de0bc4.png)
![imagem](https://user-images.githubusercontent.com/90729203/146805239-df020ede-d673-4679-baea-1246fcb66bba.png)
![imagem](https://user-images.githubusercontent.com/90729203/146804782-54975b85-ea63-43f4-95d7-ed3e8a7e1f97.png)
![imagem](https://user-images.githubusercontent.com/90729203/146804232-4b77efad-ed63-407d-b114-a61373161be1.png)
![imagem](https://user-images.githubusercontent.com/90729203/146803761-e2bb4149-b601-422e-8c53-60b8ed9fce9d.png)
![imagem](https://user-images.githubusercontent.com/90729203/146803505-02097549-8617-49ee-b0e9-c577a916ece1.png)
[Ryujinx_1.0.0+94b4312_2021-12-20_13-52-29.log](https://github.com/Ryujinx/Ryujinx/files/7746829/Ryujinx_1.0.0%2B94b4312_2021-12-20_13-52-29.log)
[Ryujinx_1.0.0+94b4312_2021-12-20_13-57-51.log](https://github.com/Ryujinx/Ryujinx/files/7746866/Ryujinx_1.0.0%2B94b4312_2021-12-20_13-57-51.log)
[Ryujinx_1.0.0+94b4312_2021-12-20_14-05-41.log](https://github.com/Ryujinx/Ryujinx/files/7746900/Ryujinx_1.0.0%2B94b4312_2021-12-20_14-05-41.log)
[Ryujinx_1.0.0+94b4312_2021-12-20_14-13-49.log](https://github.com/Ryujinx/Ryujinx/files/7746935/Ryujinx_1.0.0%2B94b4312_2021-12-20_14-13-49.log)
[Ryujinx_1.0.0+94b4312_2021-12-20_14-18-52.log](https://github.com/Ryujinx/Ryujinx/files/7746954/Ryujinx_1.0.0%2B94b4312_2021-12-20_14-18-52.log)

2021-12-21 13:53 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+94b4312-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Amane Switch has improved a lot, but it still has functionality problems, among them not changing languages (this game even has the Galician language) 
Kurikinton still has some menu issues 
When Alex Kidd dies, he has the strange sprites, even when he presses ZR, which goes to classic mode, turns green 
Endless Fables has yield and texture issues 
Mario Kart 8 the problem of the lights was solved, but on the track at the Doce Kingdom there are still some flashes of light, in the print I couldn't take it out at the time and there's still that problem of a long time, where the game runs once and doesn't open anymore, but when updates the main it works again, however this issue has been resolved in OpenGL (major version) resolve this 
Kaze and the Wild Masks apparently without visual problems, however the yield rate is unstable 
Cadence of Hyrule it is without visual problems and the performance is very good, even if once in a while there is some small loss 
Sakura SUccubus game series has normal audio in SDL2, however OPENAL is slow, in addition they have slow animation 
![imagem](https://user-images.githubusercontent.com/90729203/146940822-51f1b685-0416-4498-bb93-b9f48a30b7d7.png)
![imagem](https://user-images.githubusercontent.com/90729203/146939795-0a939428-1b29-4cec-894e-aa4ede9b915d.png)
![imagem](https://user-images.githubusercontent.com/90729203/146938547-094b54b1-a2b4-4856-9bd2-044a691a9cde.png)
![imagem](https://user-images.githubusercontent.com/90729203/146937291-4ad271ca-b8fa-444b-b16c-3e12c321b8d6.png)
![imagem](https://user-images.githubusercontent.com/90729203/146936579-96e65338-f26b-461e-8882-d545e7f2e750.png)
![imagem](https://user-images.githubusercontent.com/90729203/146936513-7857591d-dbba-4ede-a460-63a3f77de278.png)
![imagem](https://user-images.githubusercontent.com/90729203/146935958-5ac6dfe3-fc31-4136-b7ba-ebfa57490ab0.png)
![imagem](https://user-images.githubusercontent.com/90729203/146935525-b0f0c3fe-8a33-49e9-a848-22ece4c3872e.png)
![imagem](https://user-images.githubusercontent.com/90729203/146935198-a2a8c29d-1b26-4a18-a6cc-288263283533.png)
[Ryujinx_1.0.0+94b4312_2021-12-21_09-55-39.log](https://github.com/Ryujinx/Ryujinx/files/7755428/Ryujinx_1.0.0%2B94b4312_2021-12-21_09-55-39.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_09-59-46.log](https://github.com/Ryujinx/Ryujinx/files/7755469/Ryujinx_1.0.0%2B94b4312_2021-12-21_09-59-46.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_10-05-13.log](https://github.com/Ryujinx/Ryujinx/files/7755496/Ryujinx_1.0.0%2B94b4312_2021-12-21_10-05-13.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_10-09-18.log](https://github.com/Ryujinx/Ryujinx/files/7755547/Ryujinx_1.0.0%2B94b4312_2021-12-21_10-09-18.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_10-15-45.log](https://github.com/Ryujinx/Ryujinx/files/7755588/Ryujinx_1.0.0%2B94b4312_2021-12-21_10-15-45.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_10-21-48.log](https://github.com/Ryujinx/Ryujinx/files/7755607/Ryujinx_1.0.0%2B94b4312_2021-12-21_10-21-48.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_10-24-58.log](https://github.com/Ryujinx/Ryujinx/files/7755665/Ryujinx_1.0.0%2B94b4312_2021-12-21_10-24-58.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_10-50-57.log](https://github.com/Ryujinx/Ryujinx/files/7755761/Ryujinx_1.0.0%2B94b4312_2021-12-21_10-50-57.log)
[Ryujinx_1.0.0+94b4312_2021-12-21_10-50-57.log](https://github.com/Ryujinx/Ryujinx/files/7755771/Ryujinx_1.0.0%2B94b4312_2021-12-21_10-50-57.log)

2021-12-23 01:30 UTC, riperiperi commented
I've pushed something that might fix your issues with "Jack Axe". This should also help any other opengl/game maker games with weird issues.

I've also pushed some preliminary support for device local buffers, and some new stuff that loads textures/buffer data on a preload command buffer if possible. The total command buffers in the pool has been increased to account for potentially doubling the number we go through, but 16 might be a bit too much.

The preload command buffer stuff still needs a bit more thinking. I don't currently like the way that everything selects between cbs/main/preload command buffers, feels like there could be a helper method to avoid duplicating selection behaviour (also something a bit less weird for when we need to push and wait for the command buffer on staging buffer upload)

2021-12-23 15:11 UTC, AlfredoDore commented
> I've pushed something that might fix your issues with "Jack Axe". This should also help any other opengl/game maker games with weird issues. Before, texture data was always uploaded _before_ a draw command buffer, even if the data was used then reuploaded in the same buffe. Now it can be uploaded during, and the preload behaviour is explicit (and works for buffer uploads).
> 
> I've also pushed some preliminary support for device local buffers, and some new stuff that loads textures/buffer data on a preload command buffer if possible. The total command buffers in the pool has been increased to account for potentially doubling the number we go through, but 16 might be a bit too much.
> 
> The preload command buffer stuff still needs a bit more thinking. I don't currently like the way that everything selects between cbs/main/preload command buffers, feels like there could be a helper method to avoid duplicating selection behaviour (also something a bit less weird for when we need to push and wait for the command buffer on staging buffer upload)

thanks man, hope this solves those brown filters in the Zelda Skyaward Sword videos

2021-12-23 15:12 UTC, riperiperi commented
> thanks man, hope this solves those brown filters in the Zelda Skyaward Sword videos

It won't unfortunately, I think this is a depth mode issue.

2021-12-24 00:28 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+fe00c53-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
the problem with the control of Resident Evil 1 HD still persists, in addition there are some slow moments (classic control doesn't go forward, only sideways and backwards)
Record of Lodoss War is broken in several possible ways 
Jack Ax now has scenery, but equally all broken 
Shield Pokémon needs more performance, fps drop a lot 
Starlink still has a lot to do, I recommend improving the videos, as it doesn't matter whether it's OpenAL or SDL2, the videos are very slow, and visually speaking, OpenGL is better, but no less worse 
one thing that still needs to improve is 2D, the change made certain things appear, but there are still errors  
still no Shining Diamond Pokémon works on Vulkan 
Resident Evil Zero doesn't have a problem with the classic controller that the 1 has, plus it looks like the textures have been straightened out, what's left is to straighten out those locks. 
![imagem](https://user-images.githubusercontent.com/90729203/147301727-a22d3eb3-c61c-45dc-abbf-e63ae0a36059.png)
![imagem](https://user-images.githubusercontent.com/90729203/147301663-e4a7188f-365b-4f6b-a41c-6c2605404f9c.png)
![imagem](https://user-images.githubusercontent.com/90729203/147301486-f40ad91e-4931-4425-9a94-9c2fa6b51ccc.png)
![imagem](https://user-images.githubusercontent.com/90729203/147301459-98ceeb08-5650-4acb-aeb9-affbc8849a55.png)
![imagem](https://user-images.githubusercontent.com/90729203/147300911-9b3e0ee9-3dcf-4e42-9eb5-606641895eb0.png)
![imagem](https://user-images.githubusercontent.com/90729203/147300834-6389934f-da2f-4681-8943-8197c5cb47ed.png)
![imagem](https://user-images.githubusercontent.com/90729203/147300667-9989fadd-6bb9-4b80-99d1-b8d666e5461b.png)
![imagem](https://user-images.githubusercontent.com/90729203/147300380-47627a1a-3f32-4a7a-b5a0-0fcfeb46fd0f.png)
![imagem](https://user-images.githubusercontent.com/90729203/147300197-598e9d9e-31ce-4b07-a4cc-b7ac4020d67a.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299904-9476e533-3161-4ac7-a598-b5fd2d5a61d4.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299769-aa35ee60-7199-4efe-aaa1-b63e8a34d439.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299740-83ba5c69-40d0-4e34-96ee-ba80941e9a57.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299711-2ceeb542-15cf-41ab-a4b7-e062670bc376.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299689-5701f019-0786-476a-9d20-5ef65c707db4.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299641-a0fadc67-3a03-4c35-bcb4-af91cb953c27.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299622-80819b63-2b71-4847-b8ee-769e7018d1de.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299601-12296951-248e-4fdc-9627-9b96299c6531.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299490-6d4743f7-846e-43d3-9de9-6a4b3638f5ad.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299451-23f88e8b-f9a2-4791-a300-215db7ddd90b.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299356-25dfdef5-d30d-4d8f-ac7d-d7cee3ab8f37.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299319-7685455c-571a-4e86-a8cc-db1cd90dd001.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299290-df70a265-d2e9-4906-9475-66acf2d50658.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299260-25f98aef-a296-4d29-b5f7-fce87b98670c.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299219-900124d6-a8c4-46cc-ac3a-fa6c81f8459e.png)
![imagem](https://user-images.githubusercontent.com/90729203/147298945-7991bbcc-9875-42ae-a33b-050ed4e43f86.png)
![imagem](https://user-images.githubusercontent.com/90729203/147299053-d14b6d61-e301-447f-b9ea-21b1c72b5956.png)
[Ryujinx_1.0.0+fe00c53_2021-12-23_20-16-59.log](https://github.com/Ryujinx/Ryujinx/files/7771776/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_20-16-59.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_20-24-02.log](https://github.com/Ryujinx/Ryujinx/files/7771783/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_20-24-02.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_20-30-59.log](https://github.com/Ryujinx/Ryujinx/files/7771788/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_20-30-59.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_20-34-52.log](https://github.com/Ryujinx/Ryujinx/files/7771808/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_20-34-52.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_20-40-40.log](https://github.com/Ryujinx/Ryujinx/files/7771818/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_20-40-40.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_20-43-48.log](https://github.com/Ryujinx/Ryujinx/files/7771866/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_20-43-48.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_21-14-38.log](https://github.com/Ryujinx/Ryujinx/files/7771889/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_21-14-38.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_21-16-43.log](https://github.com/Ryujinx/Ryujinx/files/7771909/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_21-16-43.log)
[Ryujinx_1.0.0+fe00c53_2021-12-23_21-23-27.log](https://github.com/Ryujinx/Ryujinx/files/7771920/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_21-23-27.log)

2021-12-24 02:21 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+fe00c53-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
finally AM2R load times have been fixed, but sprites are broken, this does not happen in OpenGL  
![imagem](https://user-images.githubusercontent.com/90729203/147307782-00ad1d2f-2ded-4993-8350-b74d861126e6.png)
[Ryujinx_1.0.0+fe00c53_2021-12-23_23-14-30.log](https://github.com/Ryujinx/Ryujinx/files/7772234/Ryujinx_1.0.0%2Bfe00c53_2021-12-23_23-14-30.log)

2021-12-24 02:28 UTC, AlfredoDore commented
in fact the visuals of the 2D games have been fixed in OpenGL, whereas in Vulkan it's still a mess 
![imagem](https://user-images.githubusercontent.com/90729203/147308251-685d452e-6a08-4143-8131-1089b096b2d6.png)

2021-12-24 16:14 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+fe00c53-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
RE Revelations 1 is basically without graphical errors, just lacking performance, RE Revelations 2 no longer has the black menu background flashing green and the previously buggy luminous texture has been fixed, but it also lacks performance 
Zelda still has this triangle on the screen, besides its frame rate is very unstable  
![imagem](https://user-images.githubusercontent.com/90729203/147363990-98ece602-8550-4b14-adde-fa3543d7524b.png)
![imagem](https://user-images.githubusercontent.com/90729203/147363957-46423a54-43ec-4c89-b33b-562b699ada2d.png)
![imagem](https://user-images.githubusercontent.com/90729203/147363932-1e3d27ec-46de-4ff9-baa4-6944f06dbe49.png)
![imagem](https://user-images.githubusercontent.com/90729203/147363827-80a834ac-f733-435f-8cec-0a336c165828.png)
![imagem](https://user-images.githubusercontent.com/90729203/147363794-7afca52a-25d3-42b9-9081-00d705cf365d.png)
![imagem](https://user-images.githubusercontent.com/90729203/147363773-aafcb63c-4640-4add-b839-423214b2ac69.png)
![imagem](https://user-images.githubusercontent.com/90729203/147363076-c0f83b8d-7b0b-402c-b8db-9d236e98208d.png)
![imagem](https://user-images.githubusercontent.com/90729203/147363014-7dc284b6-e532-4e37-bafd-930321f1bf9f.png)
![imagem](https://user-images.githubusercontent.com/90729203/147362799-e7953390-109f-4037-bb76-60d17a155d20.png)
[Ryujinx_1.0.0+fe00c53_2021-12-24_11-54-46.log](https://github.com/Ryujinx/Ryujinx/files/7774734/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_11-54-46.log)
[Ryujinx_1.0.0+fe00c53_2021-12-24_12-44-06.log](https://github.com/Ryujinx/Ryujinx/files/7774769/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_12-44-06.log)
[Ryujinx_1.0.0+fe00c53_2021-12-24_13-05-53.log](https://github.com/Ryujinx/Ryujinx/files/7774787/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_13-05-53.log)
[Ryujinx_1.0.0+fe00c53_2021-12-24_13-09-43.log](https://github.com/Ryujinx/Ryujinx/files/7774800/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_13-09-43.log)

2021-12-24 16:52 UTC, MutantAura commented
For Links Awakening the unstable framerate is caused by the dynamic framerate swaps. This happens on OGL too. 
Use version 1.0.0 (no update) of the game with this mod: https://cdn.discordapp.com/attachments/356187763139280896/724250990928461834/Stable-60fps-v2.zip

2021-12-24 17:17 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+fe00c53-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Haven and Super Mario 3D World are almost 100%, all that remains is to improve performance, Crash Trilogy still has these weird proportions (in addition to the videos being slow in any audio option) and Yoshi still has a lot to fix. 
![imagem](https://user-images.githubusercontent.com/90729203/147366387-2bc0505f-01ca-4d16-a5be-8681a62cf004.png)
![imagem](https://user-images.githubusercontent.com/90729203/147366321-3d22e22f-ca19-4121-8e42-8d77e91809b9.png)
![imagem](https://user-images.githubusercontent.com/90729203/147366281-3c3172a3-1f28-4a62-9238-91fbf26a5d6b.png)
![imagem](https://user-images.githubusercontent.com/90729203/147366152-500750ec-d67e-4587-821c-164f4c1471df.png)
![imagem](https://user-images.githubusercontent.com/90729203/147365881-6b5da2e9-5b32-4a23-a361-208c5a248b17.png)
![imagem](https://user-images.githubusercontent.com/90729203/147365673-1f1cef08-23a0-4076-a6b1-37df52cf8dec.png)
[Ryujinx_1.0.0+fe00c53_2021-12-24_13-34-45.log](https://github.com/Ryujinx/Ryujinx/files/7774871/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_13-34-45.log)
[Ryujinx_1.0.0+fe00c53_2021-12-24_14-02-23.log](https://github.com/Ryujinx/Ryujinx/files/7774884/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_14-02-23.log)
[Ryujinx_1.0.0+fe00c53_2021-12-24_13-55-08.log](https://github.com/Ryujinx/Ryujinx/files/7774886/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_13-55-08.log)
[Ryujinx_1.0.0+fe00c53_2021-12-24_14-08-19.log](https://github.com/Ryujinx/Ryujinx/files/7774893/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_14-08-19.log)

2021-12-24 17:18 UTC, AlfredoDore commented
> For Links Awakening the unstable framerate is caused by the dynamic framerate swaps. This happens on OGL too. Use version 1.0.0 (no update) of the game with this mod: https://cdn.discordapp.com/attachments/356187763139280896/724250990928461834/Stable-60fps-v2.zip
> 
> The framerate should be much improved.

ideally without mods, so I report this

2021-12-24 18:32 UTC, SheKenFFS commented
There is a way to make it work with the LDN multiplayer version of Ryujinx?

2021-12-25 14:02 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+b538d5d-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
The Marauder Chronicles and Sakura Nova continue to close, Crash still has broken textures and totally wrong proportions, overall the 2D texture increase solved it in OpenGL, but in Vulkan only a few things straightened out, there's an enemy in Crash (human) that I went bald, now it's correct, but other things are wrong and in 2D games for example now the Switch's Handhelm appears in Final Fantasy VII, but the screen rendering is horrible and the fonts are all broken 
![imagem](https://user-images.githubusercontent.com/90729203/147386597-9a598089-2d08-4035-8c52-1493549f5f01.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386470-d4e72fdc-555a-47c0-b091-2e3381131d58.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386336-d46b3653-2dc9-4406-83e8-ca29cf7e306e.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386247-08ffe0d0-143e-4fc4-8291-d89fd5ebc425.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386199-4846ae79-dbd9-4abf-b4ce-dbba8755201a.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386128-b6cac579-cb0c-4ab2-a125-f075093ab682.png)
![imagem](https://user-images.githubusercontent.com/90729203/147385989-c4cd7e20-5b58-4031-95eb-30f558033cac.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386036-b0b78b9d-2ff4-4ceb-8b42-aeb9037b7c0e.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386065-8fc0fd36-ed8e-4df8-a249-a0c092361abd.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386091-00fa14fc-ac1a-42ab-b534-a54f65d4f933.png)
![imagem](https://user-images.githubusercontent.com/90729203/147386363-fa03cbd8-4c6c-4427-aa3a-36edabee21e1.png)

[Ryujinx_1.0.0+fe00c53_2021-12-24_14-08-19.log](https://github.com/Ryujinx/Ryujinx/files/7775864/Ryujinx_1.0.0%2Bfe00c53_2021-12-24_14-08-19.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_10-30-36.log](https://github.com/Ryujinx/Ryujinx/files/7775870/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_10-30-36.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_10-34-55.log](https://github.com/Ryujinx/Ryujinx/files/7775875/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_10-34-55.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_10-37-54.log](https://github.com/Ryujinx/Ryujinx/files/7775887/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_10-37-54.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_10-45-53.log](https://github.com/Ryujinx/Ryujinx/files/7775895/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_10-45-53.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_10-48-16.log](https://github.com/Ryujinx/Ryujinx/files/7775897/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_10-48-16.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_10-54-46.log](https://github.com/Ryujinx/Ryujinx/files/7775911/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_10-54-46.log)

2021-12-25 22:35 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+b538d5d-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Doraemon Story of Seasons just need to keep the frame rate constant, because graphically speaking it has already been fixed, Super Mario Oddsey still has to do, textures flashing and when it gets close to Tyrannosaurus Rex the frame rate drops a lot, Haven just needs to improve the yield, Yoshi still on the textures flickering and falling frames per second 

![imagem](https://user-images.githubusercontent.com/90729203/147394711-b5b0c11f-67dd-4ec4-8ec0-f3f5a978aabf.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394656-0bf97585-c9d4-40cf-85dd-4923bd9ed35c.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394609-f8781cd1-3724-431f-a9e7-5af0264536c5.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394587-4e9c9878-7444-4d5f-9914-3308b3724fe8.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394575-15271899-1fd3-4af0-b1e6-59737ffd40da.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394556-e3e70b16-24ff-4e28-a0f9-7bf1c7b9674c.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394525-4cdf2eec-911e-4da8-83f7-df1b89906c3b.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394370-38a991ee-dcc3-4a0d-9c0e-8ec46b9b2067.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394252-19abb65c-6d28-461e-aa47-7ba3f18f11ba.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394153-3d8ca25b-731b-4143-bd92-ebdd58317812.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394186-5895dd28-faa2-45fe-9774-9ef72b67962c.png)
![imagem](https://user-images.githubusercontent.com/90729203/147394211-4d4c3a6a-4edc-486b-b1bf-198b66389292.png)
[Ryujinx_1.0.0+b538d5d_2021-12-25_18-50-37.log](https://github.com/Ryujinx/Ryujinx/files/7776313/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_18-50-37.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_19-06-57.log](https://github.com/Ryujinx/Ryujinx/files/7776318/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_19-06-57.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_19-28-15.log](https://github.com/Ryujinx/Ryujinx/files/7776322/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_19-28-15.log)
[Ryujinx_1.0.0+b538d5d_2021-12-25_19-18-13.log](https://github.com/Ryujinx/Ryujinx/files/7776326/Ryujinx_1.0.0%2Bb538d5d_2021-12-25_19-18-13.log)

2021-12-26 16:51 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+b538d5d-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Resident Evil Revelations 2 Needs Income 
Waifu Uncovered still has a lot of texture issues 
Pokémon Brillant Diamond does not start 
Pokémon Shield need more income 
Zelda Link's Awakerning does not appear, but has a checkered water texture error, in addition to the low fps rate besides, there's still the triangle  
Rockman 11 just need income 
![imagem](https://user-images.githubusercontent.com/90729203/147414863-80b50f5b-b6e0-44c2-8b3f-d0836f2a12ac.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414799-c27b8c4e-fc67-420a-82a0-99abb98dca49.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414736-58719094-45e3-4b53-88a9-ee41abd259c5.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414706-aaf6057d-abda-496e-872a-3019184bd9df.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414656-f00869fe-139e-4355-b362-84e0bc25d477.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414641-1ffa6e23-2372-474a-9b90-3defe84ed336.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414620-615a6f61-de6d-44de-afea-dc6c4b9b14a6.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414593-552ebf13-d0fc-4c21-9ee1-555bdfd4bec9.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414401-2787b412-0350-454c-824a-1052c4af0ab1.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414274-4d010bb8-739c-43a0-a4cf-332b993563f4.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414187-5af9ac4a-1f23-4825-b1bc-54ca4d4b235b.png)
![imagem](https://user-images.githubusercontent.com/90729203/147414009-07ef0c67-f9b6-428b-becd-061449dd16ae.png)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-07-18.log](https://github.com/Ryujinx/Ryujinx/files/7777234/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-07-18.log)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-22-34.log](https://github.com/Ryujinx/Ryujinx/files/7777244/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-22-34.log)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-27-03.log](https://github.com/Ryujinx/Ryujinx/files/7777246/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-27-03.log)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-28-36.log](https://github.com/Ryujinx/Ryujinx/files/7777252/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-28-36.log)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-32-17.log](https://github.com/Ryujinx/Ryujinx/files/7777260/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-32-17.log)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-44-22.log](https://github.com/Ryujinx/Ryujinx/files/7777264/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-44-22.log)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-46-06.log](https://github.com/Ryujinx/Ryujinx/files/7777277/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-46-06.log)

2021-12-27 00:50 UTC, AlfredoDore commented
I put it from OpenGL because of the graphical comparison, in OpenGL you see much better, but the videos are also very slow 
OpenGL
![imagem](https://user-images.githubusercontent.com/90729203/147423954-df15568b-8cd9-4a90-a8f3-5372d7dc3da3.png)
[Ryujinx_1.0.7140_2021-12-26_21-29-49.log](https://github.com/Ryujinx/Ryujinx/files/7777783/Ryujinx_1.0.7140_2021-12-26_21-29-49.log)
Vulkan
![Starlink Vulkan](https://user-images.githubusercontent.com/90729203/147424002-9786d320-b865-4c63-9dfe-ade2340c19e8.png)
[Ryujinx_1.0.0+b538d5d_2021-12-26_13-32-17.log](https://github.com/Ryujinx/Ryujinx/files/7777788/Ryujinx_1.0.0%2Bb538d5d_2021-12-26_13-32-17.log)

2021-12-27 14:36 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+b538d5d-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Resident Evil 1 and 0 there are no graphics problems and the 1 no longer has the control problem, however both need improvement in performance, the 1 at the time of lightning causes some crashes and in the main hall there are fps drops, the 0 still has a lot of crashes 
Baldo is without graphics problems, but need income  
![imagem](https://user-images.githubusercontent.com/90729203/147481138-2f5a1ad7-113a-4a64-8875-40aeac3eab3f.png)
![imagem](https://user-images.githubusercontent.com/90729203/147480797-0503ea27-c958-4334-bbbe-4d2d3ce776ca.png)
![imagem](https://user-images.githubusercontent.com/90729203/147480584-3eb1976d-e0ac-4bd0-8088-4ceb67c01989.png)
[Ryujinx_1.0.0+b538d5d_2021-12-27_11-16-28.log](https://github.com/Ryujinx/Ryujinx/files/7780560/Ryujinx_1.0.0%2Bb538d5d_2021-12-27_11-16-28.log)
[Ryujinx_1.0.0+b538d5d_2021-12-27_11-25-15.log](https://github.com/Ryujinx/Ryujinx/files/7780597/Ryujinx_1.0.0%2Bb538d5d_2021-12-27_11-25-15.log)
[Ryujinx_1.0.0+b538d5d_2021-12-27_11-33-24.log](https://github.com/Ryujinx/Ryujinx/files/7780614/Ryujinx_1.0.0%2Bb538d5d_2021-12-27_11-33-24.log)

2021-12-29 00:02 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+b538d5d-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Zelda there are a lot of texture errors and vertex explosions 
![imagem](https://user-images.githubusercontent.com/90729203/147615553-974b8e5b-a60f-4a78-89b8-f429d969179d.png)
![imagem](https://user-images.githubusercontent.com/90729203/147615609-ff406085-8c15-4140-9157-227789d941f2.png)
![imagem](https://user-images.githubusercontent.com/90729203/147615638-54c38092-1418-4cab-a7ea-fe0f86b9a48e.png)
![imagem](https://user-images.githubusercontent.com/90729203/147615693-8f94912b-5206-4f52-a008-6da67f9095bb.png)
![imagem](https://user-images.githubusercontent.com/90729203/147615724-ad74b348-f6f0-4b19-8b59-50470315a270.png)
![imagem](https://user-images.githubusercontent.com/90729203/147615775-b67f0b97-61cc-413e-b0bd-05c08e2b738f.png)
[Ryujinx_1.0.0+b538d5d_2021-12-28_20-46-00.log](https://github.com/Ryujinx/Ryujinx/files/7786771/Ryujinx_1.0.0%2Bb538d5d_2021-12-28_20-46-00.log)

2021-12-29 14:05 UTC, AlfredoDore commented
even in OpenGL there is still this white water error, but the stones render correctly 
![imagem](https://user-images.githubusercontent.com/90729203/147670230-947c7806-5177-471e-ae5f-347387d24f6b.png)

2022-01-03 17:51 UTC, drednoot commented
00:00:00.287 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+b538d5d
00:00:00.325 |N| Application Print: Operating System: Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 (X64)
00:00:00.326 |N| Application Print: CPU: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz ; 4 logical
00:00:00.329 |N| Application Print: RAM: Total 7925 MB ; Available 7002 MB
00:00:00.334 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.335 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.639 |N| Application LoadApplication: Using Firmware Version: 13.1.
00:00:08.456 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD RADV POLARIS10 (ACO) (Vulkan v1.2.145, Driver v21.0.3)
GPU - AMD Radeon RX570
Game - Shin Megami Tensei V 1.0.1

[Ryujinx_1.0.0+b538d5d_2022-01-03_21-04-18.log](https://github.com/Ryujinx/Ryujinx/files/7803150/Ryujinx_1.0.0%2Bb538d5d_2022-01-03_21-04-18.log)
and terminal outputs this before ryujinx crashes
```
*** stack smashing detected ***: terminated
Aborted (core dumped)
```
for some reason this only happens after a reboot;
when I try to open a game for the second time, ryujinx outputs this instead
[Ryujinx_1.0.0+b538d5d_2022-01-03_21-35-24.log](https://github.com/Ryujinx/Ryujinx/files/7803246/Ryujinx_1.0.0%2Bb538d5d_2022-01-03_21-35-24.log)
and then ryujinx crashes

dmesg output:
`[  225.071553] [drm:amdgpu_cs_ioctl [amdgpu]] *ERROR* Failed to initialize parser -2!`

2022-01-04 06:52 UTC, drednoot commented
00:00:00.230 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0+08b0dd0
00:00:00.268 |N| Application Print: Operating System: Linux 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 (X64)
00:00:00.269 |N| Application Print: CPU: Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz ; 4 logical
00:00:00.272 |N| Application Print: RAM: Total 7925 MB ; Available 6374 MB
00:00:00.278 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.279 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.144 |I| Gpu : Backend Threading (Off): False
00:00:00.625 |N| Application LoadApplication: Using Firmware Version: 13.1.0
00:00:07.427 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD RADV POLARIS10 (ACO) (Vulkan v1.2.145, Driver v21.0.3)
GPU: AMD Radeon rx570
Game: Shin Megami Tensei V

The same issue, even on the new build
[Ryujinx_1.0.0+08b0dd0_2022-01-04_10-41-20.log](https://github.com/Ryujinx/Ryujinx/files/7805818/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_10-41-20.log)

2022-01-04 12:44 UTC, Narugakuruga commented
![ryujinx_capture_2022-01-04_20-35-41](https://user-images.githubusercontent.com/31060534/148060440-4d646fa4-289e-48b7-8ad1-8178583627ab.png)
Is the Alpha test working?
I'm on a relatively old AMD driver 21.8.2(because the newer has vsync bug)
could be it lacks of some vulkan extensions?

2022-01-04 13:32 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+08b0dd0-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
the Resident Evil saga (0 to Revelations 1 and 2) need performance, I no longer see serious graphics problems, Haven now the problem is loading and game performance, Super Mario Oddyssey the textures blink and there is a lot of drop in performance, Starlink still have a lot to do 
Jack Axe and other 2D games still suffer from serious graphics issues, the texture increase has resolved some issues (including those for high-end games) but apparently you still have to do something about it. 
we can say that now Shin Chan is 100% (no graphics issues, no functionality issues and no performance issues) 
![imagem](https://user-images.githubusercontent.com/90729203/148066431-e555719d-8133-43ff-85f1-6e0c2e6585cc.png)
![imagem](https://user-images.githubusercontent.com/90729203/148066300-d4633a58-ac4e-4f59-b097-008030acec7a.png)
![imagem](https://user-images.githubusercontent.com/90729203/148066029-0c9df7c9-f417-493b-9bc4-db4bbbf5b77c.png)
![imagem](https://user-images.githubusercontent.com/90729203/148065491-28a7ad98-bc14-4956-892d-12de3b37377a.png)
![imagem](https://user-images.githubusercontent.com/90729203/148065392-1f8c2900-e6fd-4da1-ac07-c18c9d384254.png)
![imagem](https://user-images.githubusercontent.com/90729203/148064716-e57d988b-c6fd-470b-9bad-a3811710a8ee.png)
![imagem](https://user-images.githubusercontent.com/90729203/148063929-f9610b90-f8ae-47de-a67e-d29f251a0df3.png)
![imagem](https://user-images.githubusercontent.com/90729203/148062985-6998390e-484c-4fde-bea1-4e9742783edd.png)
![imagem](https://user-images.githubusercontent.com/90729203/148062916-f16231c0-13a0-4d1a-a0e4-a1450bdadf49.png)
![imagem](https://user-images.githubusercontent.com/90729203/148062810-82bb7854-aefd-4d9e-9e5b-9c5f21cf2795.png)
![imagem](https://user-images.githubusercontent.com/90729203/148062720-8b147d00-c005-4463-a033-5fb41f5c3474.png)
![imagem](https://user-images.githubusercontent.com/90729203/148062445-54f62eb3-dd22-4562-98f4-47f37f591668.png)
![imagem](https://user-images.githubusercontent.com/90729203/148061774-9e47118a-b700-4d35-904a-9a6fdf9eb2f1.png)
![imagem](https://user-images.githubusercontent.com/90729203/148061371-786c5de6-ab6e-4764-aabe-43d7bd1a2ae1.png)
![imagem](https://user-images.githubusercontent.com/90729203/148061161-18a99e04-137d-4e0c-9426-af514cd16807.png)
![imagem](https://user-images.githubusercontent.com/90729203/148060676-59a02f90-f312-449b-8759-d59ec6acbd6f.png)
![imagem](https://user-images.githubusercontent.com/90729203/148060512-479c6b73-92e5-41ea-97aa-4ff0fe220e27.png)
![imagem](https://user-images.githubusercontent.com/90729203/148060315-41811716-ff35-41dc-9f7d-f4bfa02983f7.png)
![imagem](https://user-images.githubusercontent.com/90729203/148059871-4509232a-5514-4ee9-84ee-c78bfc0b3c99.png)
![imagem](https://user-images.githubusercontent.com/90729203/148059663-6765dbe7-c42e-418f-948a-c60c7da914c5.png)
![imagem](https://user-images.githubusercontent.com/90729203/148059771-70dbcfe8-3ffd-47b8-9456-60bc80174727.png)
![imagem](https://user-images.githubusercontent.com/90729203/148058687-9a036cd3-145d-48c0-9139-80509a324203.png)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_09-12-17.log](https://github.com/Ryujinx/Ryujinx/files/7807604/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_09-12-17.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_09-31-28.log](https://github.com/Ryujinx/Ryujinx/files/7807605/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_09-31-28.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_09-40-38.log](https://github.com/Ryujinx/Ryujinx/files/7807637/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_09-40-38.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_09-42-52.log](https://github.com/Ryujinx/Ryujinx/files/7807652/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_09-42-52.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_09-46-16.log](https://github.com/Ryujinx/Ryujinx/files/7807674/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_09-46-16.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_09-51-38.log](https://github.com/Ryujinx/Ryujinx/files/7807703/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_09-51-38.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_09-58-07.log](https://github.com/Ryujinx/Ryujinx/files/7807734/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_09-58-07.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_10-03-26.log](https://github.com/Ryujinx/Ryujinx/files/7807770/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_10-03-26.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_10-10-44.log](https://github.com/Ryujinx/Ryujinx/files/7807808/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_10-10-44.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_10-20-33.log](https://github.com/Ryujinx/Ryujinx/files/7807846/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_10-20-33.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_10-25-49.log](https://github.com/Ryujinx/Ryujinx/files/7807865/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_10-25-49.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-04_10-28-39.log](https://github.com/Ryujinx/Ryujinx/files/7807888/Ryujinx_1.0.0%2B08b0dd0_2022-01-04_10-28-39.log)

2022-01-05 19:36 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+08b0dd0-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Zelda is still on the triangle thing, I noticed an improvement in performance (mainly menu) but the game is still very variable 
in Mario Kart 8 I saw some flashes of lights 
like other RE games, this one suffers from serious performance losses (I think it's memory leak) graphically it's already fine 
![imagem](https://user-images.githubusercontent.com/90729203/148277869-04dfcace-8c9b-424d-ad30-ae8f0178361d.png)
![imagem](https://user-images.githubusercontent.com/90729203/148277697-697c6db6-ff36-40ff-864d-9c795c29b392.png)
![imagem](https://user-images.githubusercontent.com/90729203/148277135-87783ca3-bb94-4e73-a41d-61ba044cda17.png)
![imagem](https://user-images.githubusercontent.com/90729203/148275765-b650d1d0-0b96-4197-a05f-74db13c8a09b.png)
[Ryujinx_1.0.0+08b0dd0_2022-01-05_16-08-23.log](https://github.com/Ryujinx/Ryujinx/files/7817273/Ryujinx_1.0.0%2B08b0dd0_2022-01-05_16-08-23.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-05_16-21-06.log](https://github.com/Ryujinx/Ryujinx/files/7817336/Ryujinx_1.0.0%2B08b0dd0_2022-01-05_16-21-06.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-05_16-32-28.log](https://github.com/Ryujinx/Ryujinx/files/7817357/Ryujinx_1.0.0%2B08b0dd0_2022-01-05_16-32-28.log)

2022-01-06 14:57 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+08b0dd0-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
AM2R has normal loads, however it has broken sprites 
Yoshi the textures blink and needs more consistency in performance, although he is now faster, he has dips
Final Fantasy VII still has broken rendering (1/4 of the screen) in addition to various texture errors 
Super Mario 3D World is in need of more throughput and consistency, there is a lot of variation in frame rates 
![imagem](https://user-images.githubusercontent.com/90729203/148402262-7ed3eb02-4273-48fa-9fcc-abc5e58fb460.png)
![imagem](https://user-images.githubusercontent.com/90729203/148401636-a41575fe-2ebb-4c43-bfdc-ebbe83bb821f.png)
![imagem](https://user-images.githubusercontent.com/90729203/148401548-983f1029-d1ed-4b95-b0c9-ac8e30525c48.png)
![imagem](https://user-images.githubusercontent.com/90729203/148401391-33e317d4-a78e-4f68-9322-5d24a43f54dd.png)
![imagem](https://user-images.githubusercontent.com/90729203/148401303-358515ed-84a9-4fbd-b4fb-33d393c26a86.png)
![imagem](https://user-images.githubusercontent.com/90729203/148401131-00d8e6c4-2c3a-4663-8788-e88346581b48.png)
![imagem](https://user-images.githubusercontent.com/90729203/148400926-b386eb6f-359e-4e13-95a8-1a18ab4ce038.png)
![imagem](https://user-images.githubusercontent.com/90729203/148400501-65ade58c-4b5d-4f46-ac1b-6c635fe12b3a.png)
![imagem](https://user-images.githubusercontent.com/90729203/148399975-39d97a9c-53e1-4b29-aac2-a731da76164e.png)
![imagem](https://user-images.githubusercontent.com/90729203/148399302-b367ec25-993f-4c63-9531-b3922c8cdb6b.png)
![imagem](https://user-images.githubusercontent.com/90729203/148398773-ff86391e-181c-4558-9bf0-97f651e53ca2.png)
![imagem](https://user-images.githubusercontent.com/90729203/148398284-f1538906-9929-40a6-8dab-dba864d498ea.png)
![imagem](https://user-images.githubusercontent.com/90729203/148398461-9a7209fb-1010-402a-8424-12a4f77f3bf5.png)
[Ryujinx_1.0.0+08b0dd0_2022-01-06_11-27-18.log](https://github.com/Ryujinx/Ryujinx/files/7822468/Ryujinx_1.0.0%2B08b0dd0_2022-01-06_11-27-18.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-06_11-34-13.log](https://github.com/Ryujinx/Ryujinx/files/7822501/Ryujinx_1.0.0%2B08b0dd0_2022-01-06_11-34-13.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-06_11-38-58.log](https://github.com/Ryujinx/Ryujinx/files/7822541/Ryujinx_1.0.0%2B08b0dd0_2022-01-06_11-38-58.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-06_11-45-59.log](https://github.com/Ryujinx/Ryujinx/files/7822581/Ryujinx_1.0.0%2B08b0dd0_2022-01-06_11-45-59.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-06_11-52-02.log](https://github.com/Ryujinx/Ryujinx/files/7822609/Ryujinx_1.0.0%2B08b0dd0_2022-01-06_11-52-02.log)

2022-01-07 18:53 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+08b0dd0-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
![imagem](https://user-images.githubusercontent.com/90729203/148592584-1acf9268-6840-47cc-a063-e04fb9727728.png)
![imagem](https://user-images.githubusercontent.com/90729203/148592086-da587662-6d8a-49c3-9502-b9ebc1d24ca2.png)
![imagem](https://user-images.githubusercontent.com/90729203/148591455-78be86bc-1db7-4d6d-b403-9d4b32d1188d.png)
[Ryujinx_1.0.0+08b0dd0_2022-01-07_15-36-43.log](https://github.com/Ryujinx/Ryujinx/files/7830701/Ryujinx_1.0.0%2B08b0dd0_2022-01-07_15-36-43.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-07_15-43-17.log](https://github.com/Ryujinx/Ryujinx/files/7830742/Ryujinx_1.0.0%2B08b0dd0_2022-01-07_15-43-17.log)

2022-01-08 02:04 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+08b0dd0-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Metroid Dread is around 96%, has some small yield losses 
![imagem](https://user-images.githubusercontent.com/90729203/148627368-9e4ca65b-bf4f-4fa2-a811-cc76f09322b1.png)
[Ryujinx_1.0.0+08b0dd0_2022-01-07_22-53-29.log](https://github.com/Ryujinx/Ryujinx/files/7832396/Ryujinx_1.0.0%2B08b0dd0_2022-01-07_22-53-29.log)

2022-01-08 23:09 UTC, AlfredoDore commented
I'm putting AM2R OpenGL because in OpenGL it behaves as it should be, on Vulkan sprites and background are broken 
![imagem](https://user-images.githubusercontent.com/90729203/148662777-12b3e9b8-bee6-440c-9f47-b9255940bc97.png)
[Ryujinx_1.0.7160_2022-01-08_19-53-26.log](https://github.com/Ryujinx/Ryujinx/files/7834155/Ryujinx_1.0.7160_2022-01-08_19-53-26.log)

2022-01-08 23:40 UTC, AlfredoDore commented
here are two more games that behave properly in OpenGL, but in Vulkan it has many problems, Crash suffers from severe proportions and crashes on Vulkan, but on OpenGL it is more stable and there is no texture error, Jack Ax has the sprites very well, but on Vulkan they are all broken 
OpenGL 
![imagem](https://user-images.githubusercontent.com/90729203/148663298-c9f326d8-b4dd-4e44-b501-a316a8389f07.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663258-a0c558b4-5d3f-4bb3-997b-b1b8da919dee.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663231-51891f27-7dd5-4a39-b773-4d7199adb4f3.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663100-4ba3b130-f6d4-48e6-97ab-eb71f966320b.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663109-007c2959-6390-4b78-b11b-65047536b5c3.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663129-4a5c94ca-8477-4b07-995b-c80a94a79cc4.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663158-f16871f5-e249-4b36-b1a2-b967269bd453.png)
[Ryujinx_1.0.7160_2022-01-08_20-14-04.log](https://github.com/Ryujinx/Ryujinx/files/7834175/Ryujinx_1.0.7160_2022-01-08_20-14-04.log)
[Ryujinx_1.0.7160_2022-01-08_20-18-55.log](https://github.com/Ryujinx/Ryujinx/files/7834184/Ryujinx_1.0.7160_2022-01-08_20-18-55.log)
Vulkan
![imagem](https://user-images.githubusercontent.com/90729203/148663452-f0735b0e-3aaf-46e7-ab90-ccb05f018999.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663466-961a6417-4d86-48aa-aa1f-30c3449760d3.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663477-5586f66a-2b94-4f08-a129-eaf21c0bb35d.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663488-b550e9cc-5432-4169-a591-e64262aadf95.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663539-e53ef1d5-9a9d-4b45-a13f-649113dfdd5b.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663554-d972038a-8e9a-456c-ba44-312a17bd1b15.png)
![imagem](https://user-images.githubusercontent.com/90729203/148663608-4e45e808-90bf-4a7e-a98d-983424b473e6.png)

[Ryujinx_1.0.0+08b0dd0_2022-01-08_20-29-45.log](https://github.com/Ryujinx/Ryujinx/files/7834201/Ryujinx_1.0.0%2B08b0dd0_2022-01-08_20-29-45.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-08_20-34-50.log](https://github.com/Ryujinx/Ryujinx/files/7834214/Ryujinx_1.0.0%2B08b0dd0_2022-01-08_20-34-50.log)

2022-01-09 14:03 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+08b0dd0-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Bai Qu: Hundreds of Melodies it needs more performance in the animations, it has a drop in performance, however it has no graphical errors 
Fuga: Melodies of Steel no longer crashes, but textures flicker and needs yield 
Sakura Nova is closing 
The Marauder Chronicles is closing
Animal Crossing: New Horizons closes after starting it 
![imagem](https://user-images.githubusercontent.com/90729203/148685220-708c52bf-97ad-4392-80da-4b85f4c251d9.png)
![imagem](https://user-images.githubusercontent.com/90729203/148685093-9fafcea0-70d1-437c-9b0e-c5b23c5fac18.png)
![imagem](https://user-images.githubusercontent.com/90729203/148684991-61f46d68-b33e-4bb2-937a-789554a93e1f.png)
![imagem](https://user-images.githubusercontent.com/90729203/148684691-519c48c6-2a9b-47cd-9941-6e0cb19e5e42.png)
![imagem](https://user-images.githubusercontent.com/90729203/148684627-35f40ad2-70e0-4375-a33c-8278c85c2290.png)
![imagem](https://user-images.githubusercontent.com/90729203/148684192-c233d7fb-bf56-4ad6-b91e-4904e1ad4023.png)
![imagem](https://user-images.githubusercontent.com/90729203/148684495-5f4b29ed-e431-4e41-ae4c-7cee0c17b489.png)
[Ryujinx_1.0.0+08b0dd0_2022-01-09_10-24-44.log](https://github.com/Ryujinx/Ryujinx/files/7835143/Ryujinx_1.0.0%2B08b0dd0_2022-01-09_10-24-44.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-09_10-37-54.log](https://github.com/Ryujinx/Ryujinx/files/7835178/Ryujinx_1.0.0%2B08b0dd0_2022-01-09_10-37-54.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-09_10-50-13.log](https://github.com/Ryujinx/Ryujinx/files/7835187/Ryujinx_1.0.0%2B08b0dd0_2022-01-09_10-50-13.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-09_10-52-49.log](https://github.com/Ryujinx/Ryujinx/files/7835190/Ryujinx_1.0.0%2B08b0dd0_2022-01-09_10-52-49.log)
[Ryujinx_1.0.0+08b0dd0_2022-01-09_11-00-24.log](https://github.com/Ryujinx/Ryujinx/files/7835204/Ryujinx_1.0.0%2B08b0dd0_2022-01-09_11-00-24.log)

2022-01-09 23:49 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+08b0dd0-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
no matter the audio option, Starlink videos will always be slow and with audio cut, it would be very good to solve this problem that even other games like Mario + Rabbits have (both from Ubsofit) 
![Starlink](https://user-images.githubusercontent.com/90729203/148706090-538d8376-7e70-4841-ac4d-663e5ec9ea18.jpg)
![imagem](https://user-images.githubusercontent.com/90729203/148706086-84b060fe-d0ce-4c7f-97de-951232957252.png)
[Ryujinx_1.0.0+08b0dd0_2022-01-09_20-41-26.log](https://github.com/Ryujinx/Ryujinx/files/7836215/Ryujinx_1.0.0%2B08b0dd0_2022-01-09_20-41-26.log)

2022-01-10 11:14 UTC, Squall-Leonhart commented
Skyward Sword demonstrates graphical issues with Vulkan, exactly like the ones experienced by https://github.com/yuzu-emu/yuzu/issues/6666

same issue is in the screenshots posted by AlfredoDore above

2022-01-11 01:19 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+a327ca4-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I felt an improvement in performance in Starlink, but still the graphics problems and video speed are still a big problem (besides the fact that to run the game it has to be in Ignore Services) Mario Kart 8 closed 
Final Fantasy VII continues with the bizarre errors 
Crash Trylogy still has the ratio issues and yield losses 
Blaster Master Zero 1 1.6.1 update closes 
Haven just needs yield, graphically he is already 100% or close to it 
Super Mario Odyssey there's still a lot to do, there's still memory leaks, textures flickering and vertex explosions 
This triangle persists in Zelda Link's Awakening 
Lodoss still has broken sprites 
now yes Jack Ax had the sprites improved 
AM2R now has the normal sprites, except for the game over title
 
In general in high-end games I saw better performance, in 2D games Sprites improvement, but it needs better in games like Lodoss and Final Fantasy VII it still needs a lot, as well as Starlink 
![imagem](https://user-images.githubusercontent.com/90729203/148864243-31ffede0-8e2a-4656-8d4a-8cb684b3940f.png)
![imagem](https://user-images.githubusercontent.com/90729203/148863947-e08ba879-3426-4de1-a0ef-2187233697f3.png)
![imagem](https://user-images.githubusercontent.com/90729203/148863605-adf270a0-144e-4d64-85c4-288e85c2a658.png)
![imagem](https://user-images.githubusercontent.com/90729203/148863549-6df4d5d5-8c10-4dd7-a17b-3981b4feb85d.png)
![imagem](https://user-images.githubusercontent.com/90729203/148863320-196630f9-89fc-4e40-89a5-2627c9618036.png)
![imagem](https://user-images.githubusercontent.com/90729203/148863268-5743f3ae-9e1b-4414-a86e-4b7cc8d8b9ed.png)
![imagem](https://user-images.githubusercontent.com/90729203/148862992-de8e7f5a-79eb-47d7-9c3d-dcf73d6a9e4b.png)
![imagem](https://user-images.githubusercontent.com/90729203/148862342-ae308da5-c322-456f-9c8e-1f3d2f25b600.png)
![imagem](https://user-images.githubusercontent.com/90729203/148862233-0ed2c038-e195-4a9c-ae80-51a077241494.png)
![imagem](https://user-images.githubusercontent.com/90729203/148862131-180b140f-1253-4296-8b25-5d5640fcc56f.png)
![imagem](https://user-images.githubusercontent.com/90729203/148861958-023139bc-a6df-475f-a346-a022175e292d.png)
![imagem](https://user-images.githubusercontent.com/90729203/148861573-cc6d478c-e4b3-4c7f-b30a-bb840f8d7778.png)
![imagem](https://user-images.githubusercontent.com/90729203/148861414-3cc9a508-11b7-45fb-a44e-6181621a838e.png)
![imagem](https://user-images.githubusercontent.com/90729203/148860933-903c55aa-5b6f-481e-949c-1c28d000f148.png)
![imagem](https://user-images.githubusercontent.com/90729203/148860508-9d3415bd-d9ba-4b53-9c45-a2ecc7eb5721.png)
![imagem](https://user-images.githubusercontent.com/90729203/148860335-4d3991ff-f54a-4015-ae28-87ce1cf5ab4c.png)
![imagem](https://user-images.githubusercontent.com/90729203/148860240-25542dbc-bb53-4783-b109-9495211e116b.png)
![imagem](https://user-images.githubusercontent.com/90729203/148860097-448877bc-e339-4e48-84d9-4e4fb2cc9a4d.png)
![imagem](https://user-images.githubusercontent.com/90729203/148860056-58b3df20-ff9d-402a-8e1e-78f57daa904a.png)
![imagem](https://user-images.githubusercontent.com/90729203/148859953-97fc147a-51e4-43e4-8a6c-f2f0dbab7386.png)
![imagem](https://user-images.githubusercontent.com/90729203/148859829-ecffd5aa-9d95-4270-976d-c738ce4c2dbb.png)
![imagem](https://user-images.githubusercontent.com/90729203/148858451-3c305df4-23bf-4276-b295-eb6004372e97.png)
![imagem](https://user-images.githubusercontent.com/90729203/148858651-468a3347-d2e3-4b67-a3d9-b318f8f04409.png)
![imagem](https://user-images.githubusercontent.com/90729203/148858789-362b37b8-5c3e-404f-970f-c2ed6ebbcede.png)
[Ryujinx_1.0.0+a327ca4_2022-01-10_20-57-56.log](https://github.com/Ryujinx/Ryujinx/files/7842689/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_20-57-56.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_21-17-27.log](https://github.com/Ryujinx/Ryujinx/files/7842699/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_21-17-27.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_21-20-15.log](https://github.com/Ryujinx/Ryujinx/files/7842713/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_21-20-15.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_21-31-01.log](https://github.com/Ryujinx/Ryujinx/files/7842733/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_21-31-01.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_21-32-27.log](https://github.com/Ryujinx/Ryujinx/files/7842745/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_21-32-27.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_21-38-00.log](https://github.com/Ryujinx/Ryujinx/files/7842769/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_21-38-00.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_21-43-17.log](https://github.com/Ryujinx/Ryujinx/files/7842799/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_21-43-17.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_21-53-03.log](https://github.com/Ryujinx/Ryujinx/files/7842839/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_21-53-03.log)
[Ryujinx_1.0.0+a327ca4_2022-01-10_22-11-20.log](https://github.com/Ryujinx/Ryujinx/files/7842901/Ryujinx_1.0.0%2Ba327ca4_2022-01-10_22-11-20.log)

2022-01-12 01:00 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+7c1e4a9-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Lodoss practically unplayable 
Resident Evil Zero is very stable and so far without any graphical errors 
Resident Evil is also more stable and without graphical errors 
Resident Evil Revelations also had more stability 
Resident Evil Revelations 2 is unstable, in presentations the fps rate drops a lot
Sakura nova keeps closing 
Bullets has improved a lot, but there are still things to do, textures still have errors and flicker, and there are vertex explosions 
Final Fantasy VII still in bad rendering 
in short: some games have improved a lot, Bullets is only working on Vulkan, there's still more to improve on it (it's Unreal Engine, I just don't know which one) the Resident Evil saga had performance improvements, but it needs more stability 
![imagem](https://user-images.githubusercontent.com/90729203/149044944-c4482ad4-3759-4371-9291-9c4e46ce3eb6.png)
![imagem](https://user-images.githubusercontent.com/90729203/149044871-24191b70-c608-46f4-abaa-9568b8ffd34d.png)
![imagem](https://user-images.githubusercontent.com/90729203/149044516-fd7ba9e3-ce3b-4731-9b9a-e28de0b0ce5c.png)
![imagem](https://user-images.githubusercontent.com/90729203/149044170-3102a5ab-eb40-46ec-9bf5-4144deb3f30d.png)
![imagem](https://user-images.githubusercontent.com/90729203/149044124-d77bd20c-55f8-4d75-9e7a-4fca4e85c45a.png)
![imagem](https://user-images.githubusercontent.com/90729203/149044020-7bfbc3d9-d54e-48ae-aa8f-cca9219741fd.png)
![imagem](https://user-images.githubusercontent.com/90729203/149043837-a77332c1-6cfe-43ed-b458-77b7c013aeca.png)
![imagem](https://user-images.githubusercontent.com/90729203/149043650-c5bab06b-4df1-4747-88bc-546da906d0e0.png)
![imagem](https://user-images.githubusercontent.com/90729203/149043530-e9aa9766-f059-4e54-bad7-4098b942e5da.png)
![imagem](https://user-images.githubusercontent.com/90729203/149043309-ddf3f91c-9024-4b78-a623-9816ea87785c.png)
![imagem](https://user-images.githubusercontent.com/90729203/149043194-06cb0205-06f6-4471-af40-38cc397a88e8.png)
![imagem](https://user-images.githubusercontent.com/90729203/149042641-8683a554-7866-4b85-8ede-4416cc53e448.png)
![imagem](https://user-images.githubusercontent.com/90729203/149040497-ad38a335-e8a5-4403-878f-db90cfec9fca.png)
![imagem](https://user-images.githubusercontent.com/90729203/149039578-5b9cd43d-3296-44a7-ba74-0e4e2f0755a5.png)
![imagem](https://user-images.githubusercontent.com/90729203/149038877-a8312f2f-1bb6-4767-9f9a-70d3b5970298.png)
![imagem](https://user-images.githubusercontent.com/90729203/149038026-703b6064-007e-48b8-9f4b-914fe2c7972b.png)
![imagem](https://user-images.githubusercontent.com/90729203/149038102-3e56cdd1-339c-4d5e-a49d-c4311329027c.png)
![imagem](https://user-images.githubusercontent.com/90729203/149038172-20e40fec-6674-41e9-82f1-9ead31d125c1.png)
![imagem](https://user-images.githubusercontent.com/90729203/149038277-c903725f-3268-498c-a7f4-007025816b99.png)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_20-33-55.log](https://github.com/Ryujinx/Ryujinx/files/7850492/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_20-33-55.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_20-40-13.log](https://github.com/Ryujinx/Ryujinx/files/7850537/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_20-40-13.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_20-49-24.log](https://github.com/Ryujinx/Ryujinx/files/7850560/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_20-49-24.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_20-56-14.log](https://github.com/Ryujinx/Ryujinx/files/7850599/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_20-56-14.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_21-25-25.log](https://github.com/Ryujinx/Ryujinx/files/7850690/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_21-25-25.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_21-33-51.log](https://github.com/Ryujinx/Ryujinx/files/7850713/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_21-33-51.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_21-40-01.log](https://github.com/Ryujinx/Ryujinx/files/7850724/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_21-40-01.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_21-45-28.log](https://github.com/Ryujinx/Ryujinx/files/7850772/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_21-45-28.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_21-55-59.log](https://github.com/Ryujinx/Ryujinx/files/7850786/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_21-55-59.log)

2022-01-12 01:37 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+7c1e4a9-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Shiny Diamond Pokemon does not perform 
besides the lack of income, in Pokémon Shield I saw this graphic error 
in Super Mario Odyssey in the falls the fps drops sharply and the textures are blinking 
![imagem](https://user-images.githubusercontent.com/90729203/149048404-bdec740b-f856-42a5-ae0d-3aed1f072d0c.png)
![imagem](https://user-images.githubusercontent.com/90729203/149047965-e5bcfe91-3ec4-4096-b3d8-40ee60b7118c.png)
![imagem](https://user-images.githubusercontent.com/90729203/149047433-dafee94c-749b-4518-99f9-b91d1c6c7133.png)
![imagem](https://user-images.githubusercontent.com/90729203/149046987-f1bed9a2-d6fd-4c9c-80af-94b67eb5249e.png)
![imagem](https://user-images.githubusercontent.com/90729203/149046751-409dc0fb-d7bd-4d1c-aece-de5e3de62f33.png)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_22-12-57.log](https://github.com/Ryujinx/Ryujinx/files/7850869/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_22-12-57.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_22-15-18.log](https://github.com/Ryujinx/Ryujinx/files/7850923/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_22-15-18.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_22-28-14.log](https://github.com/Ryujinx/Ryujinx/files/7850971/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_22-28-14.log)

2022-01-12 01:49 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+7c1e4a9-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I noticed a significant improvement in Crash, but it still needs to improve the performance a little more, besides the texture proportion errors are still wrong 
![imagem](https://user-images.githubusercontent.com/90729203/149048816-eca7acf2-247c-4ce0-b150-399cb5a7d823.png)
![imagem](https://user-images.githubusercontent.com/90729203/149049087-0eeb9802-63c3-49d5-87ab-a4f3b74df4b5.png)
[Ryujinx_1.0.0+7c1e4a9_2022-01-11_22-40-32.log](https://github.com/Ryujinx/Ryujinx/files/7851016/Ryujinx_1.0.0%2B7c1e4a9_2022-01-11_22-40-32.log)

2022-01-15 18:18 UTC, AlfredoDore commented
I'm putting the main version because the sprites and textures are perfect, in Vulkan they are all broken 
![imagem](https://user-images.githubusercontent.com/90729203/149632930-cf9debf1-e22f-4c90-b40a-7b459f2be9db.png)
![imagem](https://user-images.githubusercontent.com/90729203/149632947-5788ec08-3ed5-4018-886d-a6fad04c724a.png)
![imagem](https://user-images.githubusercontent.com/90729203/149632972-0cf3967e-8bc9-4a96-9f8a-ba234dfb6386.png)
![imagem](https://user-images.githubusercontent.com/90729203/149633007-6b4feb61-4bc9-4cd8-9a77-835a0a0d6f5c.png)
![imagem](https://user-images.githubusercontent.com/90729203/149633019-691e482e-0d08-47d4-a515-08640a4216de.png)
![imagem](https://user-images.githubusercontent.com/90729203/149633131-eb5c5efb-a6e6-4e05-bfb4-3de920a0f77a.png)
[Ryujinx_1.0.7172_2022-01-15_15-07-52.log](https://github.com/Ryujinx/Ryujinx/files/7875560/Ryujinx_1.0.7172_2022-01-15_15-07-52.log)

2022-01-16 09:24 UTC, SomeoneIsWorking commented
Looks like Xenoblade Chronicles Definitive Edition works fine now (because it wasn't initially fixed by `Custom image formats at bind` update)

2022-01-18 16:41 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 21.12.1
Lastest PR Vulkan ryujinx-Release-1.0.0+7c1e4a9-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I was able to identify the lighting error, it turns out that you straightened the global lighting, but missed the drift load lighting error for when it picks up momentum. at drift time the whole screen flashes and this is too fast for me to show in print, as for the problem of playing for the second time, this problem persists in Vulkan, in OpenGL there is no problem, even in the other Switch emulator it has the same boot problem on my PC (the other one on my PC also has lighting problems and severe losses income)
In short: in Vulkan you need to straighten the lighting error of the drift load, make the performance even more constant and the main thing: solve the initialization problem in Vulkan, because this problem also existed in OpenGL but you already solved it there 
![imagem](https://user-images.githubusercontent.com/90729203/149978144-b233e27a-23db-441a-83c4-c6cb9c1de111.png)
[Ryujinx_1.0.0+7c1e4a9_2022-01-18_13-09-46.log](https://github.com/Ryujinx/Ryujinx/files/7890744/Ryujinx_1.0.0%2B7c1e4a9_2022-01-18_13-09-46.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-18_13-33-06.log](https://github.com/Ryujinx/Ryujinx/files/7890773/Ryujinx_1.0.0%2B7c1e4a9_2022-01-18_13-33-06.log)

2022-01-19 00:45 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.1
Lastest PR Vulkan ryujinx-Release-1.0.0+7c1e4a9-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Super Mario 3D World graphically speaking is excellent and the process, the problem is also the latency (the RE 0, 1 and Revelations 1 and 2 just aren't 100% because of the latency, you have to keep the performance stable) 
graphically Haven is very good and the speed is good, but the problem is that there is still latency (even the uploads are slow) 
Metroid Dread is also just latency, no graphical problem 
these games that I made a report are almost 100, it's to improve the stability of the performance  
![imagem](https://user-images.githubusercontent.com/90729203/150042013-5b6dd00c-a188-4930-b86e-fc4dd3d96111.png)
![imagem](https://user-images.githubusercontent.com/90729203/150040718-683b4cb0-1b2c-47b8-85d9-cd1cd4d5ac36.png)
![imagem](https://user-images.githubusercontent.com/90729203/150040048-994cd08c-11ca-429e-995b-bb8d9296c100.png)
[Ryujinx_1.0.0+7c1e4a9_2022-01-18_21-14-32.log](https://github.com/Ryujinx/Ryujinx/files/7893186/Ryujinx_1.0.0%2B7c1e4a9_2022-01-18_21-14-32.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-18_21-25-05.log](https://github.com/Ryujinx/Ryujinx/files/7893222/Ryujinx_1.0.0%2B7c1e4a9_2022-01-18_21-25-05.log)
[Ryujinx_1.0.0+7c1e4a9_2022-01-18_21-32-38.log](https://github.com/Ryujinx/Ryujinx/files/7893247/Ryujinx_1.0.0%2B7c1e4a9_2022-01-18_21-32-38.log)

2022-01-20 20:14 UTC, AlfredoDore commented
Pokémon Brilliant Diamond gives this error, not even in the main version it starts 
![imagem](https://user-images.githubusercontent.com/90729203/150414537-15bb60ff-4f61-462c-8430-8315b9e1d2cc.png)

2022-01-20 23:49 UTC, temperal approved these changes

2022-01-23 23:28 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR Vulkan ryujinx-Release-1.0.0+6fe0ac2-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
I noticed an improvement in the performance of the games, Lodoss still has broken sprites and Mario Kart the drift loading problem seems to have been resolved, but now the characters blink, textures still have blinking and Zelda Link Awakerning is almost there, Fuga needs improvement the performance stability, and improving the textures of the water that has these squares and removing the triangle, Haven the problem remains the loadings and a small loss of performance in the opening video 
Crash still has the wrong proportions and a lot of latency (normal is 16, but it's in the range of 30) 
Guardians of the Galaxy starts correctly 
Pokémon Diamant Brillant does not start and gives an error that closes the emulator 
Zelda Skyward Sword continues to have texture issues 
Super Mario Odyssey has improved performance a lot, but the whole scenario is blinking 
![imagem](https://user-images.githubusercontent.com/90729203/150702366-4e839ed6-97da-4444-a7f6-9358e4db3194.png)
![imagem](https://user-images.githubusercontent.com/90729203/150702228-d03aaf9a-94ef-48a7-9056-1cfd28e63754.png)
![imagem](https://user-images.githubusercontent.com/90729203/150702121-5c2610a9-4787-4011-a2c3-4452335ae141.png)
![imagem](https://user-images.githubusercontent.com/90729203/150702057-d5facd44-b983-404f-8ea5-b7c77d305f30.png)
![imagem](https://user-images.githubusercontent.com/90729203/150701853-df81ab5c-6b00-437c-888c-52089563bb09.png)
![imagem](https://user-images.githubusercontent.com/90729203/150701599-774d48d5-73e7-4d0b-849b-a5823ee5684b.png)
![imagem](https://user-images.githubusercontent.com/90729203/150701436-f7c4fe3e-c26a-40b5-8e84-12f2615cbdd3.png)
![imagem](https://user-images.githubusercontent.com/90729203/150701390-78a0c418-6baf-4a00-ae2b-77fa5de0857e.png)
![imagem](https://user-images.githubusercontent.com/90729203/150701119-dc1b2a64-3eed-4467-8268-d9e7f2ff7fb7.png)
![imagem](https://user-images.githubusercontent.com/90729203/150701068-9d9bccb0-6d15-4da0-b641-bb4130a2c292.png)
![imagem](https://user-images.githubusercontent.com/90729203/150701047-abf77d76-fe50-49ad-9778-27bf8c8f19ec.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700986-118c7942-dc51-4406-a464-cc04a558bd80.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700954-a4bf5c68-94fe-4cec-9c96-3f54780a86de.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700921-07ee18a9-6d7f-4d91-83fc-6aee6b71542e.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700855-d0f22b6f-2a73-4693-88fc-8944cc592950.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700718-a2dcd8f0-7dc5-4047-b5b4-1275713cd4f9.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700619-c1dac660-73a6-4c6c-a256-20a562c992de.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700383-e12d87d3-8a92-477c-ad69-bc5003cea4f4.png)
![imagem](https://user-images.githubusercontent.com/90729203/150700352-97ad269d-ccd3-409a-acff-a9dbce82e3ee.png)
[Ryujinx_1.0.0-dirty_2022-01-23_19-21-03.log](https://github.com/Ryujinx/Ryujinx/files/7921569/Ryujinx_1.0.0-dirty_2022-01-23_19-21-03.log)
[Ryujinx_1.0.0-dirty_2022-01-23_19-28-47.log](https://github.com/Ryujinx/Ryujinx/files/7921577/Ryujinx_1.0.0-dirty_2022-01-23_19-28-47.log)
[Ryujinx_1.0.0-dirty_2022-01-23_19-33-01.log](https://github.com/Ryujinx/Ryujinx/files/7921593/Ryujinx_1.0.0-dirty_2022-01-23_19-33-01.log)
[Ryujinx_1.0.0-dirty_2022-01-23_19-41-05.log](https://github.com/Ryujinx/Ryujinx/files/7921600/Ryujinx_1.0.0-dirty_2022-01-23_19-41-05.log)
[Ryujinx_1.0.0-dirty_2022-01-23_19-44-17.log](https://github.com/Ryujinx/Ryujinx/files/7921615/Ryujinx_1.0.0-dirty_2022-01-23_19-44-17.log)
[Ryujinx_1.0.0-dirty_2022-01-23_19-52-32.log](https://github.com/Ryujinx/Ryujinx/files/7921630/Ryujinx_1.0.0-dirty_2022-01-23_19-52-32.log)
[Ryujinx_1.0.0-dirty_2022-01-23_19-59-09.log](https://github.com/Ryujinx/Ryujinx/files/7921635/Ryujinx_1.0.0-dirty_2022-01-23_19-59-09.log)
[Ryujinx_1.0.0-dirty_2022-01-23_20-03-00.log](https://github.com/Ryujinx/Ryujinx/files/7921646/Ryujinx_1.0.0-dirty_2022-01-23_20-03-00.log)
[Ryujinx_1.0.0-dirty_2022-01-23_20-14-09.log](https://github.com/Ryujinx/Ryujinx/files/7921658/Ryujinx_1.0.0-dirty_2022-01-23_20-14-09.log)
[Ryujinx_1.0.0-dirty_2022-01-23_20-19-10.log](https://github.com/Ryujinx/Ryujinx/files/7921661/Ryujinx_1.0.0-dirty_2022-01-23_20-19-10.log)
[Ryujinx_1.0.0-dirty_2022-01-23_20-21-37.log](https://github.com/Ryujinx/Ryujinx/files/7921671/Ryujinx_1.0.0-dirty_2022-01-23_20-21-37.log)

2022-01-24 16:39 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR Vulkan ryujinx-Release-1.0.0+90c000b-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Lodoss the menu has improved, but there is still work to be done, besides the Deedlit is still invisible 
Resident Evil Revelations 1 needs to improve latency 
Resident Evil 0 and 1 suffer from latency, the normal is 16, but the RE are in the range of 30 to 40 (depending can to 90) 
Bullets It doesn't work anymore, now the screen is frozen 
Starlink has very high latency, it no longer has the green texture error for distant things, but it still has a lot to improve 
![imagem](https://user-images.githubusercontent.com/90729203/150825163-5569553c-8861-4100-9a40-8818ec8b208e.png)
![imagem](https://user-images.githubusercontent.com/90729203/150823492-209534e0-c662-4d81-be74-93061f57f1ea.png)
![imagem](https://user-images.githubusercontent.com/90729203/150822821-ca97729d-55df-4ac4-b577-dcedb7f2a6f3.png)
![imagem](https://user-images.githubusercontent.com/90729203/150820972-4d08e07d-f4df-4d67-93af-e504889240e3.png)
![imagem](https://user-images.githubusercontent.com/90729203/150820418-81b95032-efbf-4765-83de-2d31f4f2156a.png)
![imagem](https://user-images.githubusercontent.com/90729203/150819700-8b797070-97b7-43b5-bd7d-f8f3b57eea2b.png)
![imagem](https://user-images.githubusercontent.com/90729203/150817871-c9cc5a6c-4a80-44b7-9cb4-c0bb3527ae06.png)
![imagem](https://user-images.githubusercontent.com/90729203/150817223-18788163-3256-4c96-ade0-70a80e1bdc5f.png)
![imagem](https://user-images.githubusercontent.com/90729203/150814231-812bb2ce-42a4-4780-80e6-9121c42ad2c6.png)
![imagem](https://user-images.githubusercontent.com/90729203/150813206-c95e1d2b-0c49-4e01-8dfd-77a44aadf348.png)
![imagem](https://user-images.githubusercontent.com/90729203/150812915-7f1ca1b4-e69c-4adf-b703-389fd864b463.png)
![imagem](https://user-images.githubusercontent.com/90729203/150812208-741ffd07-3f9d-4b7f-95c8-a001cf144307.png)
![imagem](https://user-images.githubusercontent.com/90729203/150809804-7374b447-d820-427f-947d-51361e0c6f78.png)
![imagem](https://user-images.githubusercontent.com/90729203/150810356-8426171a-7519-4cc9-96e7-ba1e8bc2fc07.png)
[Ryujinx_1.0.0-dirty_2022-01-24_12-10-54.log](https://github.com/Ryujinx/Ryujinx/files/7926582/Ryujinx_1.0.0-dirty_2022-01-24_12-10-54.log)
[Ryujinx_1.0.0-dirty_2022-01-24_12-24-17.log](https://github.com/Ryujinx/Ryujinx/files/7926644/Ryujinx_1.0.0-dirty_2022-01-24_12-24-17.log)
[Ryujinx_1.0.0-dirty_2022-01-24_12-29-39.log](https://github.com/Ryujinx/Ryujinx/files/7926680/Ryujinx_1.0.0-dirty_2022-01-24_12-29-39.log)
[Ryujinx_1.0.0-dirty_2022-01-24_12-34-31.log](https://github.com/Ryujinx/Ryujinx/files/7926751/Ryujinx_1.0.0-dirty_2022-01-24_12-34-31.log)
[Ryujinx_1.0.0-dirty_2022-01-24_12-50-52.log](https://github.com/Ryujinx/Ryujinx/files/7926888/Ryujinx_1.0.0-dirty_2022-01-24_12-50-52.log)
[Ryujinx_1.0.0-dirty_2022-01-24_13-05-59.log](https://github.com/Ryujinx/Ryujinx/files/7926964/Ryujinx_1.0.0-dirty_2022-01-24_13-05-59.log)
[Ryujinx_1.0.0-dirty_2022-01-24_13-09-50.log](https://github.com/Ryujinx/Ryujinx/files/7927151/Ryujinx_1.0.0-dirty_2022-01-24_13-09-50.log)
[Ryujinx_1.0.0-dirty_2022-01-24_13-35-22.log](https://github.com/Ryujinx/Ryujinx/files/7927222/Ryujinx_1.0.0-dirty_2022-01-24_13-35-22.log)

2022-01-24 17:15 UTC, riperiperi commented
@AlfredoDore Can you retest Link's Awakening with the latest version to see if the block flickering on the intro video + water is fixed?

2022-01-24 17:39 UTC, AlfredoDore commented
> @AlfredoDore Can you retest Link's Awakening with the latest version to see if the block flickering on the intro video + water is fixed?

I will test now

2022-01-24 17:54 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR Vulkan ryujinx-Release-1.0.0+90c000b-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Link's Awakening the screen triangle is gone, but it still has this texture error in the water (only now it blinks very fast), there is also the latency problem
Baldo graphically it's ok, but his performance needs to improve 
![imagem](https://user-images.githubusercontent.com/90729203/150837383-9011ec14-0c27-4fd8-88e0-741e9e5df203.png)
![imagem](https://user-images.githubusercontent.com/90729203/150836921-d9afe6f0-5695-493b-8d9c-aa60e37e0b2c.png)
![imagem](https://user-images.githubusercontent.com/90729203/150836675-ec618a38-c006-4b34-8d56-1e4131fa6279.png)
![imagem](https://user-images.githubusercontent.com/90729203/150836599-5e5f8d32-b818-4f70-9a3f-f2f701603056.png)
![imagem](https://user-images.githubusercontent.com/90729203/150836099-117c57e4-55e1-4df8-8534-f98ba696555d.png)
![imagem](https://user-images.githubusercontent.com/90729203/150835585-015da687-2b13-4e7f-8e15-27f9b6da1c24.png)
![imagem](https://user-images.githubusercontent.com/90729203/150835703-0284bccc-42f5-4c61-8aa7-e01cf7f8e57a.png)
[Ryujinx_1.0.0-dirty_2022-01-24_14-39-59.log](https://github.com/Ryujinx/Ryujinx/files/7927686/Ryujinx_1.0.0-dirty_2022-01-24_14-39-59.log)
[Ryujinx_1.0.0-dirty_2022-01-24_14-46-55.log](https://github.com/Ryujinx/Ryujinx/files/7927710/Ryujinx_1.0.0-dirty_2022-01-24_14-46-55.log)
[Ryujinx_1.0.0-dirty_2022-01-24_14-50-36.log](https://github.com/Ryujinx/Ryujinx/files/7927741/Ryujinx_1.0.0-dirty_2022-01-24_14-50-36.log)

2022-01-24 21:04 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR Vulkan ryujinx-Release-1.0.0+90c000b-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Mario Kart 8 has the lights flashes, but very fast and the textures are blinking and Mario Odyssey has high latency and the textures are always blinking (including the characters) 
Sakura Succubus his problem is the animations that have high latency, and I would like them to solve several problems with visual novel games 
Final Fantasy VII still has the serious rendering problem, in addition to the font and text errors 
Zelda Skyward Sword has textures error, and also in the villain, the black aura is with some rectangles 
![imagem](https://user-images.githubusercontent.com/90729203/150864339-6301d3b8-d446-4d1a-97ee-01d5b37d87e5.png)
![imagem](https://user-images.githubusercontent.com/90729203/150864147-0be1ce1c-38b4-42ac-a32d-9ba3843ea22d.png)
![imagem](https://user-images.githubusercontent.com/90729203/150863795-087035d4-9bbb-4f4d-9729-6dcb3fa4ad5d.png)
![imagem](https://user-images.githubusercontent.com/90729203/150863701-3f7d0c30-1941-4186-a23a-0f13f83f4e98.png)
![imagem](https://user-images.githubusercontent.com/90729203/150863581-1e4861ad-6627-4644-9608-23c28bee25d9.png)
![imagem](https://user-images.githubusercontent.com/90729203/150863535-1b213647-79f6-4414-8d77-aeb855d70869.png)
![imagem](https://user-images.githubusercontent.com/90729203/150863324-8f84ba02-f052-4d5e-8204-1d93ca1f917f.png)
![imagem](https://user-images.githubusercontent.com/90729203/150863258-89aea663-c1e0-42e6-adad-5a968d65e643.png)
![imagem](https://user-images.githubusercontent.com/90729203/150862670-c353aa32-ec54-4b02-84d3-9d57eea294ea.png)
![imagem](https://user-images.githubusercontent.com/90729203/150861784-9a03f6e0-e33d-47d7-81b8-31355aa14730.png)
![imagem](https://user-images.githubusercontent.com/90729203/150859542-3cd621c7-6d75-43ae-8372-4f7a989f1a8c.png)
![imagem](https://user-images.githubusercontent.com/90729203/150860620-f6e19689-8e22-45af-8e09-5efc939690c3.png)
[Ryujinx_1.0.0-dirty_2022-01-24_17-19-12.log](https://github.com/Ryujinx/Ryujinx/files/7928721/Ryujinx_1.0.0-dirty_2022-01-24_17-19-12.log)
[Ryujinx_1.0.0-dirty_2022-01-24_17-38-32.log](https://github.com/Ryujinx/Ryujinx/files/7928753/Ryujinx_1.0.0-dirty_2022-01-24_17-38-32.log)
[Ryujinx_1.0.0-dirty_2022-01-24_17-47-16.log](https://github.com/Ryujinx/Ryujinx/files/7928790/Ryujinx_1.0.0-dirty_2022-01-24_17-47-16.log)
[Ryujinx_1.0.0-dirty_2022-01-24_17-53-55.log](https://github.com/Ryujinx/Ryujinx/files/7928830/Ryujinx_1.0.0-dirty_2022-01-24_17-53-55.log)
[Ryujinx_1.0.0-dirty_2022-01-24_18-00-33.log](https://github.com/Ryujinx/Ryujinx/files/7928854/Ryujinx_1.0.0-dirty_2022-01-24_18-00-33.log)

2022-01-26 15:44 UTC, AlfredoDore commented
Ryujinx-Release-1.0.0+9b6dcd4-win_x64
Final Fantasy VII still has this bizarre rendering, which most likely affects other games 
Lodoss still have these graphics problems 
Starlink has several problems, among them the problem of playing FMV's 
in Zelda the water texture problem persists 
Bullets is working again, but in addition to the vertex explosions, and errors, the game crashes on the first mission 
my only complaint in Haven is in terms of latency, there are certain times when it goes up, this game is almost perfect 
![imagem](https://user-images.githubusercontent.com/90729203/151196022-3ea70634-19f5-4225-99ef-9394329462d6.png)
![imagem](https://user-images.githubusercontent.com/90729203/151194692-734a964f-2bd1-4bbe-81c0-1335ecc6f004.png)
![imagem](https://user-images.githubusercontent.com/90729203/151194348-6001e145-d54f-4d1e-ab0e-f4e02a42e2cd.png)
![imagem](https://user-images.githubusercontent.com/90729203/151194173-e0516749-fb1f-427f-b7f8-b95939f027fe.png)
![imagem](https://user-images.githubusercontent.com/90729203/151182585-5df9ba28-d398-40a6-b0e5-29ff54ad199d.png)
![imagem](https://user-images.githubusercontent.com/90729203/151182250-ac89d9ea-6359-431d-9019-6f9160c1774e.png)
![imagem](https://user-images.githubusercontent.com/90729203/151181914-4f5940ab-f305-4d31-945f-4acb4f0403dd.png)
![imagem](https://user-images.githubusercontent.com/90729203/151181409-f224aed6-5294-4d6a-90f2-e9effbd8d713.png)
![imagem](https://user-images.githubusercontent.com/90729203/151180904-2adcbea7-f038-4df9-a078-d9d9fa12c131.png)
![imagem](https://user-images.githubusercontent.com/90729203/151180041-b757c464-6b6e-49d5-a175-8480731fc318.png)
![imagem](https://user-images.githubusercontent.com/90729203/151179691-0ae5298e-3000-49cd-be60-c2068db3a259.png)
![imagem](https://user-images.githubusercontent.com/90729203/151179113-ea2a1737-a57e-4e77-8b17-a8a0d7dc3559.png)
![imagem](https://user-images.githubusercontent.com/90729203/151178159-2555df70-6999-481d-9cf8-fd691573c371.png)
![imagem](https://user-images.githubusercontent.com/90729203/151178263-39de03be-6dd9-46a4-9618-4176d0babf66.png)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_11-09-13.log](https://github.com/Ryujinx/Ryujinx/files/7942360/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_11-09-13.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_11-13-29.log](https://github.com/Ryujinx/Ryujinx/files/7942414/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_11-13-29.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_11-16-36.log](https://github.com/Ryujinx/Ryujinx/files/7942489/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_11-16-36.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_11-26-57.log](https://github.com/Ryujinx/Ryujinx/files/7942512/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_11-26-57.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_11-29-20.log](https://github.com/Ryujinx/Ryujinx/files/7942551/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_11-29-20.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_11-33-29.log](https://github.com/Ryujinx/Ryujinx/files/7942996/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_11-33-29.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_12-38-14.log](https://github.com/Ryujinx/Ryujinx/files/7943055/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_12-38-14.log)

2022-01-26 21:03 UTC, AlfredoDore commented
Super Mario Odyssey has improved performance, but still latencies and textures flicker, Resident Evil 0 and 1 need to decrease latency, Pokémon Shield also needs performance and improve a texture error that leaves half of the arena invisible 

![imagem](https://user-images.githubusercontent.com/90729203/151246233-a1e1dcca-7e2c-4463-a5f3-8536f8912e57.png)
![imagem](https://user-images.githubusercontent.com/90729203/151245892-62e9a9d4-8340-48f1-b9cb-e9ac9704d229.png)
![imagem](https://user-images.githubusercontent.com/90729203/151245154-eb96f72a-138e-46d9-841a-dc1ce2426abe.png)
![imagem](https://user-images.githubusercontent.com/90729203/151244733-50172a4d-f1c7-49ce-9a80-49ffee62cb2a.png)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_17-44-51.log](https://github.com/Ryujinx/Ryujinx/files/7945477/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_17-44-51.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_17-50-35.log](https://github.com/Ryujinx/Ryujinx/files/7945498/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_17-50-35.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_17-53-19.log](https://github.com/Ryujinx/Ryujinx/files/7945516/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_17-53-19.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-26_17-58-33.log](https://github.com/Ryujinx/Ryujinx/files/7945530/Ryujinx_1.1.0%2B9b6dcd4_2022-01-26_17-58-33.log)

2022-01-27 12:12 UTC, AlfredoDore commented
Waifu Uncovered is almost perfect, but still has graphical issues 
Sakura Nova is still crashing in the first part of the game 
The Marauder Chronicles it's also crashing in the first part of the game 
Sakura Swim has high latency 
![imagem](https://user-images.githubusercontent.com/90729203/151356521-418f7fde-e189-4a32-bc49-cdaab9fdc4d6.png)
![imagem](https://user-images.githubusercontent.com/90729203/151355271-d6b806a6-5e58-4444-bc67-384021a3c09e.png)
![imagem](https://user-images.githubusercontent.com/90729203/151354714-db1e7ab3-0eec-46c1-bbb0-b033690ebac2.png)
![imagem](https://user-images.githubusercontent.com/90729203/151354179-c4c0ba6b-c63b-47cd-ad11-bad43cd7c8ac.png)
![imagem](https://user-images.githubusercontent.com/90729203/151353481-5ccf1ce1-ca91-47e3-9b02-08009fc30a02.png)
![imagem](https://user-images.githubusercontent.com/90729203/151353290-1c862753-c52f-43b9-97c0-103c61c95653.png)
![imagem](https://user-images.githubusercontent.com/90729203/151352765-05621694-a1e6-409f-b114-f9933dfd8bf8.png)
![imagem](https://user-images.githubusercontent.com/90729203/151351112-e54a1faa-470c-4dbe-a4f1-f804812a131b.png)
![imagem](https://user-images.githubusercontent.com/90729203/151352264-db3d6d21-c91b-4658-a1d9-5709d2cc9b4d.png)
[Ryujinx_1.1.0+9b6dcd4_2022-01-27_08-33-16.log](https://github.com/Ryujinx/Ryujinx/files/7950089/Ryujinx_1.1.0%2B9b6dcd4_2022-01-27_08-33-16.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-27_08-44-01.log](https://github.com/Ryujinx/Ryujinx/files/7950107/Ryujinx_1.1.0%2B9b6dcd4_2022-01-27_08-44-01.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-27_08-47-44.log](https://github.com/Ryujinx/Ryujinx/files/7950136/Ryujinx_1.1.0%2B9b6dcd4_2022-01-27_08-47-44.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-27_08-53-01.log](https://github.com/Ryujinx/Ryujinx/files/7950183/Ryujinx_1.1.0%2B9b6dcd4_2022-01-27_08-53-01.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-27_09-00-32.log](https://github.com/Ryujinx/Ryujinx/files/7950210/Ryujinx_1.1.0%2B9b6dcd4_2022-01-27_09-00-32.log)
[Ryujinx_1.1.0+9b6dcd4_2022-01-27_09-03-32.log](https://github.com/Ryujinx/Ryujinx/files/7950258/Ryujinx_1.1.0%2B9b6dcd4_2022-01-27_09-03-32.log)

2022-01-28 00:43 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR Vulkan ryujinx-Release-1.0.0+bc9344e-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Mario Kart 8 is almost done, now the textures flicker less and the lighting problem is almost solved, every now and then the screen flashes white, especially on very lit tracks like the sweet track 
Super Mario Odyssey has improved the performance a lot, but it needs to be more stable, also the textures flicker a lot 
Zelda lInk Awakening has improved the yield a lot, but the water remains the same 
Bullets it started working again, the performance is more stable, but the texture problems persist 
in general some games have improved and the general performance of the emulator has improved a lot 
![imagem](https://user-images.githubusercontent.com/90729203/151466943-a6335a4c-7652-457a-8dfa-9df98029d52f.png)
![imagem](https://user-images.githubusercontent.com/90729203/151466747-6e8bd0b9-16d5-41ee-9267-5f3b6c59ea36.png)
![imagem](https://user-images.githubusercontent.com/90729203/151466507-e3979f2b-b724-4f7f-ab54-854f63ec8f7e.png)
![imagem](https://user-images.githubusercontent.com/90729203/151466159-2fd0a4c5-6516-431a-9445-39f13f47f8a5.png)
![imagem](https://user-images.githubusercontent.com/90729203/151466014-d7fa7615-2734-45dc-bab4-60c780af7ce0.png)
![imagem](https://user-images.githubusercontent.com/90729203/151465874-df8b4d8a-5ce1-4840-893a-696c41923b01.png)
![imagem](https://user-images.githubusercontent.com/90729203/151465646-6425bca7-eaea-4e25-8c1e-122727fc2920.png)
![imagem](https://user-images.githubusercontent.com/90729203/151464838-752f48ee-2172-45d1-9ad6-5959c70b95c1.png)
![imagem](https://user-images.githubusercontent.com/90729203/151463949-258e7a1f-8836-4613-9ff7-00d244e4751a.png)
![imagem](https://user-images.githubusercontent.com/90729203/151463831-67cdbbd8-2db2-47e4-b45a-87a91b3fe73b.png)
![imagem](https://user-images.githubusercontent.com/90729203/151463572-8610f278-c94e-4940-9484-b4253186771f.png)
![imagem](https://user-images.githubusercontent.com/90729203/151463477-174680e2-58af-43b6-aea1-29a686034531.png)
[Ryujinx_1.1.0+bc9344e_2022-01-27_20-56-54.log](https://github.com/Ryujinx/Ryujinx/files/7954654/Ryujinx_1.1.0%2Bbc9344e_2022-01-27_20-56-54.log)
[Ryujinx_1.1.0+bc9344e_2022-01-27_21-05-12.log](https://github.com/Ryujinx/Ryujinx/files/7954665/Ryujinx_1.1.0%2Bbc9344e_2022-01-27_21-05-12.log)
[Ryujinx_1.1.0+bc9344e_2022-01-27_21-08-20.log](https://github.com/Ryujinx/Ryujinx/files/7954699/Ryujinx_1.1.0%2Bbc9344e_2022-01-27_21-08-20.log)
[Ryujinx_1.1.0+bc9344e_2022-01-27_21-20-13.log](https://github.com/Ryujinx/Ryujinx/files/7954725/Ryujinx_1.1.0%2Bbc9344e_2022-01-27_21-20-13.log)
[Ryujinx_1.1.0+bc9344e_2022-01-27_21-27-31.log](https://github.com/Ryujinx/Ryujinx/files/7954758/Ryujinx_1.1.0%2Bbc9344e_2022-01-27_21-27-31.log)
[Ryujinx_1.1.0+bc9344e_2022-01-27_21-33-18.log](https://github.com/Ryujinx/Ryujinx/files/7954785/Ryujinx_1.1.0%2Bbc9344e_2022-01-27_21-33-18.log)

2022-01-28 06:03 UTC, benderscruffy commented
Quest of Dungeons still not fixed
![ryujinx_capture_2022-01-28_14-00-27](https://user-images.githubusercontent.com/2696404/151495473-8e07543c-104d-4471-acc0-c0b3d23b94eb.png)
0:00:36.691 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ VUID-VkImageMemoryBarrier-subresourceRange-01486 ] Object 0: handle = 0xaacfe8000000105f, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x86799d17 | vkCmdPipelineBarrier: subresourceRange.baseMipLevel (= 1) is greater or equal to the mip level count of the image (i.e. greater or equal to 1). The Vulkan spec states: subresourceRange.baseMipLevel must be less than the mipLevels specified in VkImageCreateInfo when image was created (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-subresourceRange-01486)
00:00:36.691 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ VUID-VkImageMemoryBarrier-subresourceRange-01724 ] Object 0: handle = 0xaacfe8000000105f, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x29bbee05 | vkCmdPipelineBarrier: subresourceRange.baseMipLevel + .levelCount (= 1 + 1 = 2) is greater than the mip level count of the image (i.e. greater than 1). The Vulkan spec states: If subresourceRange.levelCount is not VK_REMAINING_MIP_LEVELS, subresourceRange.baseMipLevel + subresourceRange.levelCount must be less than or equal to the mipLevels specified in VkImageCreateInfo when image was created (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-subresourceRange-01724)
[Ryujinx_1.1.0+bc9344e_2022-01-28_13-57-05.log](https://github.com/Ryujinx/Ryujinx/files/7956119/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_13-57-05.log)

2022-01-28 06:23 UTC, benderscruffy commented
Book of Demons
graphics are all messed up
[Ryujinx_1.1.0+bc9344e_2022-01-28_14-17-05.log](https://github.com/Ryujinx/Ryujinx/files/7956251/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_14-17-05.log)
![ryujinx_capture_2022-01-28_14-20-44](https://user-images.githubusercontent.com/2696404/151497812-8cc2bda8-9bbb-4e72-aefd-3635f026e3f7.png)
![ryujinx_capture_2022-01-28_14-21-03](https://user-images.githubusercontent.com/2696404/151497847-3c94040d-7729-420c-a192-219e29c0e7b2.png)
![ryujinx_capture_2022-01-28_14-21-26](https://user-images.githubusercontent.com/2696404/151497882-2816aee4-c3d5-46ad-91ad-4e671a4fe98a.png)

2022-01-28 07:03 UTC, benderscruffy commented
Ghosts n Goblins Resurrection [0100D6200F2BA000]
keeps on spamming heaps of Vulkan errors making the game stutter 
[Ryujinx_1.1.0+bc9344e_2022-01-28_14-56-21.log](https://github.com/Ryujinx/Ryujinx/files/7956486/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_14-56-21.log)

2022-01-28 11:59 UTC, AlfredoDore commented
> Quest of Dungeons still has graphic glitches ![ryujinx_capture_2022-01-28_14-00-27](https://user-images.githubusercontent.com/2696404/151495473-8e07543c-104d-4471-acc0-c0b3d23b94eb.png) 0:00:36.691 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ VUID-VkImageMemoryBarrier-subresourceRange-01486 ] Object 0: handle = 0xaacfe8000000105f, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x86799d17 | vkCmdPipelineBarrier: subresourceRange.baseMipLevel (= 1) is greater or equal to the mip level count of the image (i.e. greater or equal to 1). The Vulkan spec states: subresourceRange.baseMipLevel must be less than the mipLevels specified in VkImageCreateInfo when image was created (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-subresourceRange-01486) 00:00:36.691 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ VUID-VkImageMemoryBarrier-subresourceRange-01724 ] Object 0: handle = 0xaacfe8000000105f, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x29bbee05 | vkCmdPipelineBarrier: subresourceRange.baseMipLevel + .levelCount (= 1 + 1 = 2) is greater than the mip level count of the image (i.e. greater than 1). The Vulkan spec states: If subresourceRange.levelCount is not VK_REMAINING_MIP_LEVELS, subresourceRange.baseMipLevel + subresourceRange.levelCount must be less than or equal to the mipLevels specified in VkImageCreateInfo when image was created (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-VkImageMemoryBarrier-subresourceRange-01724) [Ryujinx_1.1.0+bc9344e_2022-01-28_13-57-05.log](https://github.com/Ryujinx/Ryujinx/files/7956119/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_13-57-05.log)

looks to me like the same rendering error as in Final Fantasy VII and the graphical issues as in Lodoss

2022-01-28 16:05 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR Vulkan ryujinx-Release-1.0.0+bc9344e-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
AM2R it can be said that it is perfect, it is even quite stable 
Resident Evil 0, 1, Revelations 1 and 2 need stability, graphically they are like on the Switch itself 
Crash still has bizarre proportions and Lodoss still has graphical issues 
![imagem](https://user-images.githubusercontent.com/90729203/151579922-160ef814-d505-49a4-8c06-b05b1adeee59.png)
![imagem](https://user-images.githubusercontent.com/90729203/151578693-c0015c2a-0f2a-4be5-b010-3aaf9221f7f8.png)
![imagem](https://user-images.githubusercontent.com/90729203/151578278-d63ddfe2-f4b1-4bdb-95a4-ad5c21444c91.png)
![imagem](https://user-images.githubusercontent.com/90729203/151577346-481919ff-3ed6-4184-89b5-6fcb4cbd62bd.png)
![imagem](https://user-images.githubusercontent.com/90729203/151576988-a7bf2fc5-24a4-48f8-8aa4-9eb7e151243e.png)
![imagem](https://user-images.githubusercontent.com/90729203/151575884-603ab467-d66a-4b80-a032-321ab4f70722.png)
![imagem](https://user-images.githubusercontent.com/90729203/151575461-9f74c3cf-76ea-468c-8f39-c2d66b5064ac.png)
![imagem](https://user-images.githubusercontent.com/90729203/151574607-5a7c215a-7c9b-4173-abd4-a4aa7291c909.png)
![imagem](https://user-images.githubusercontent.com/90729203/151574228-f6f1eb62-f913-4764-b0e6-51706a59fd8b.png)
![imagem](https://user-images.githubusercontent.com/90729203/151573253-045fbfd4-113a-4349-9011-0fb7c0009734.png)
![imagem](https://user-images.githubusercontent.com/90729203/151572757-326a5f59-4e3b-4442-901b-b568219bf657.png)
[Ryujinx_1.1.0+bc9344e_2022-01-28_12-16-26.log](https://github.com/Ryujinx/Ryujinx/files/7959752/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_12-16-26.log)
[Ryujinx_1.1.0+bc9344e_2022-01-28_12-20-08.log](https://github.com/Ryujinx/Ryujinx/files/7959775/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_12-20-08.log)
[Ryujinx_1.1.0+bc9344e_2022-01-28_12-23-15.log](https://github.com/Ryujinx/Ryujinx/files/7959805/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_12-23-15.log)
[Ryujinx_1.1.0+bc9344e_2022-01-28_12-27-51.log](https://github.com/Ryujinx/Ryujinx/files/7959889/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_12-27-51.log)
[Ryujinx_1.1.0+bc9344e_2022-01-28_12-39-43.log](https://github.com/Ryujinx/Ryujinx/files/7959942/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_12-39-43.log)
[Ryujinx_1.1.0+bc9344e_2022-01-28_12-48-45.log](https://github.com/Ryujinx/Ryujinx/files/7959998/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_12-48-45.log)
[Ryujinx_1.1.0+bc9344e_2022-01-28_12-54-51.log](https://github.com/Ryujinx/Ryujinx/files/7960041/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_12-54-51.log)

2022-01-28 16:37 UTC, AlfredoDore commented
Lodoss in OpenGL 
![imagem](https://user-images.githubusercontent.com/90729203/151585902-a7791901-94c6-4aea-b5e8-29f08b6f7fe1.png)

2022-01-28 23:35 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR Vulkan ryujinx-Release-1.0.0+bc9344e-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
in Starlink 1.0.5 update the game crashes when it starts, it's the game that needs more attention, the other games improved performance, only Zelda that had a small drop 
![imagem](https://user-images.githubusercontent.com/90729203/151635457-da57a74a-ad2e-45b0-b977-e401ff366b0d.png)
![imagem](https://user-images.githubusercontent.com/90729203/151635098-7bebcc9b-abb2-4636-894d-a81e4106a6e7.png)
![imagem](https://user-images.githubusercontent.com/90729203/151634358-c2be0666-d29f-4066-8177-bb0c213dbd4f.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633889-4977ac7f-7b82-4eb2-9110-e5ed4a4564c0.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633604-b8d13c23-8ede-46b2-8395-1a45df07eca4.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633565-b411dd09-97de-48c0-aeb3-5e4addc3fcf3.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633485-45f5267b-26e9-4e39-9b23-09e6346f1a99.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633334-ade8f7f8-7c34-4e7a-80ad-15fea040396f.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633281-e60e0b39-f5d4-408a-b3d9-6886da4dc93b.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633185-21950406-06c8-4f7c-9347-184166058e96.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633135-bcddc9d8-59dc-42a7-80b5-57fbef9b48eb.png)
![imagem](https://user-images.githubusercontent.com/90729203/151633066-c9f34540-59a6-479f-960e-8093f3050d19.png)
![imagem](https://user-images.githubusercontent.com/90729203/151632686-61f82833-bf1c-4a2a-acbf-131a30b692f3.png)
![imagem](https://user-images.githubusercontent.com/90729203/151632322-0fb5bad9-792d-4dc8-b481-da3fa62c63f1.png)
![imagem](https://user-images.githubusercontent.com/90729203/151631812-1aa96448-48c8-4ffb-be1f-72e86dca1c86.png)
![imagem](https://user-images.githubusercontent.com/90729203/151631344-888bf88c-fbc0-407c-9ab1-7a60aa54ee93.png)
![imagem](https://user-images.githubusercontent.com/90729203/151631279-2b36de98-8d62-46b3-a4ea-303aba87b2df.png)
![imagem](https://user-images.githubusercontent.com/90729203/151630797-b2246f18-263b-4043-b701-72c8f8b5b485.png)
[Ryujinx_1.1.0+66d3500_2022-01-28_19-32-45.log](https://github.com/Ryujinx/Ryujinx/files/7962233/Ryujinx_1.1.0%2B66d3500_2022-01-28_19-32-45.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_19-38-53.log](https://github.com/Ryujinx/Ryujinx/files/7962270/Ryujinx_1.1.0%2B66d3500_2022-01-28_19-38-53.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_19-44-48.log](https://github.com/Ryujinx/Ryujinx/files/7962308/Ryujinx_1.1.0%2B66d3500_2022-01-28_19-44-48.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_19-51-46.log](https://github.com/Ryujinx/Ryujinx/files/7962333/Ryujinx_1.1.0%2B66d3500_2022-01-28_19-51-46.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_19-57-22.log](https://github.com/Ryujinx/Ryujinx/files/7962347/Ryujinx_1.1.0%2B66d3500_2022-01-28_19-57-22.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_19-59-58.log](https://github.com/Ryujinx/Ryujinx/files/7962360/Ryujinx_1.1.0%2B66d3500_2022-01-28_19-59-58.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_20-05-07.log](https://github.com/Ryujinx/Ryujinx/files/7962430/Ryujinx_1.1.0%2B66d3500_2022-01-28_20-05-07.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_20-10-46.log](https://github.com/Ryujinx/Ryujinx/files/7962431/Ryujinx_1.1.0%2B66d3500_2022-01-28_20-10-46.log)
[Ryujinx_1.1.0+66d3500_2022-01-28_20-22-31.log](https://github.com/Ryujinx/Ryujinx/files/7962480/Ryujinx_1.1.0%2B66d3500_2022-01-28_20-22-31.log)

2022-01-29 02:30 UTC, benderscruffy commented
Torchlight 3
keeps spamimg Vulkan errors which makes the game go REALLY slow and stutter 

00:04:12.944 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ UNASSIGNED-CoreValidation-DrawState-InvalidCommandBuffer-VkImageView ] Object 0: handle = 0xf04a4b0000024699, type = VK_OBJECT_TYPE_IMAGE_VIEW; Object 1: handle = 0xa8a8130000001be8, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; Object 2: handle = 0x2c7977c78c0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x7bb837f8 | You are adding vkCmdBindPipeline() to VkCommandBuffer 0x2c7977c78c0[] that is invalid because bound VkImageView 0xf04a4b0000024699[] was destroyed.

00:04:01.709 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ VUID-vkCmdDrawIndexed-None-02699 ] Object 0: handle = 0x40a799000002206f, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xa44449d4 | Descriptor set VkDescriptorSet 0x40a799000002206f[] encountered the following validation error at vkCmdDrawIndexed() time: Descriptor in binding #1 index 0 requires FLOAT component type, but bound descriptor format is VK_FORMAT_R8G8B8A8_SINT. The Vulkan spec states: Descriptors in each bound descriptor set, specified via vkCmdBindDescriptorSets, must be valid if they are statically used by the VkPipeline bound to the pipeline bind point used by this command (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdDrawIndexed-None-02699)

00:04:01.707 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ VUID-vkCmdCopyBufferToImage-bufferImageHeight-00204 ] Object 0: handle = 0x477bb8000002373a, type = VK_OBJECT_TYPE_IMAGE; | MessageID = 0x374d00c3 | vkCmdCopyBufferToImage(): pRegion[0] bufferImageHeight (1) must be a multiple of the compressed image's texel height (4). The Vulkan spec states: If {imageparam} is a blocked image, for each element of pRegions, bufferImageHeight must be a multiple of the compressed texel block height (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdCopyBufferToImage-bufferImageHeight-00204)
[Ryujinx_1.1.0+66d3500_2022-01-29_10-19-12.zip](https://github.com/Ryujinx/Ryujinx/files/7962817/Ryujinx_1.1.0%2B66d3500_2022-01-29_10-19-12.zip)

2022-01-29 02:34 UTC, gdkchan commented
I'm not sure if you enabled the Vulkan debug logs intentionally or not, but it can be disabled in the settings graphics tab, setting the graphics backend log level to None.

2022-01-29 03:10 UTC, benderscruffy commented
ok have turned it off

2022-01-29 03:11 UTC, benderscruffy commented
Perky Little Things [0100C5B010BA4000][v0]
music starts then crashes out
[Ryujinx_1.1.0+66d3500_2022-01-29_11-08-18.log](https://github.com/Ryujinx/Ryujinx/files/7962863/Ryujinx_1.1.0%2B66d3500_2022-01-29_11-08-18.log)

00:00:39.943 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorMemoryMapFailed".
   at Ryujinx.Graphics.Vulkan.MemoryAllocatorBlockList.Allocate(UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocatorBlockList.cs:line 180
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.Allocate(Int32 memoryTypeIndex, UInt64 size, UInt64 alignment, Boolean map) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 49
   at Ryujinx.Graphics.Vulkan.MemoryAllocator.AllocateDeviceMemory(PhysicalDevice physicalDevice, MemoryRequirements requirements, MemoryPropertyFlags flags) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\MemoryAllocator.cs:line 37
   at Ryujinx.Graphics.Vulkan.BufferManager.Create(VulkanGraphicsDevice gd, Int32 size, Boolean forConditionalRendering, Boolean deviceLocal) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\BufferManager.cs:line 93
   at Ryujinx.Graphics.Vulkan.VulkanGraphicsDevice.CreateBuffer(Int32 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\VulkanGraphicsDevice.cs:line 202
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_2(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 59
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131

2022-01-29 03:48 UTC, benderscruffy commented
STRIKERS1945 for Nintendo Switch 
graphics are all messed up
![ryujinx_capture_2022-01-29_11-46-22](https://user-images.githubusercontent.com/2696404/151646206-dc82f948-8d64-41d9-8629-841c8c907a82.png)
![ryujinx_capture_2022-01-29_11-46-25](https://user-images.githubusercontent.com/2696404/151646209-59a11c6b-8bad-47a3-9779-c64a490a6670.png)
![ryujinx_capture_2022-01-29_11-46-31](https://user-images.githubusercontent.com/2696404/151646212-f39db91d-6bf2-4565-a7a9-01e57b6fee29.png)
![ryujinx_capture_2022-01-29_11-46-43](https://user-images.githubusercontent.com/2696404/151646214-2b8ca772-99cd-4c80-8d91-085ea979934d.png)

2022-01-29 05:40 UTC, benderscruffy commented
Laytons Mystery Journey Katrielle to Daifugo no Inbo DX Plus [0100FDB00AA80000][v0][JP]
screen is all stretched out
cannot go in game 
![ryujinx_capture_2022-01-29_13-37-55](https://user-images.githubusercontent.com/2696404/151649057-d13a01da-3684-4372-897e-583795219a3d.png)
![ryujinx_capture_2022-01-29_13-38-08](https://user-images.githubusercontent.com/2696404/151649064-c1720711-71a4-4ddf-ab83-254f2f1e28a7.png)

2022-01-29 09:34 UTC, killerqueen69420 commented
![image](https://user-images.githubusercontent.com/98641136/151655874-f1273c92-10ff-4fc2-b966-eb7924bb96d4.png)
Weird gray box appear when using strong or agile style

2022-01-29 10:28 UTC, benderscruffy commented
STRIKERS1945 for Nintendo Switch
graphics are still messed up on the left hand side of the screen

2022-01-29 10:28 UTC, AnakinMM commented
### BUG Pokemon Legends Arceus (GPU AMD and VULKAN)
The water surface of rivers and lakes is not transparent in Vulkan. (temp puddles during rain are transparent)
In OpenGL water is transparent, but the 3D models too...

P.S. In Vulkan appear a box during the fade-in of the titles. 

### Log file
Action: Open Ryujinx -> Load the game -> Press A -> Wait the game to load -> Take a screenshot -> Close Ryujinx from Task Manager
[VULKAN Ryujinx_1.1.0+8c7ad0f_2022-01-29_10-39-42.log](https://github.com/Ryujinx/Ryujinx/files/7963436/VULKAN.Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_10-39-42.log)
[OPENGL Ryujinx_1.1.0+8c7ad0f_2022-01-29_10-54-18.log](https://github.com/Ryujinx/Ryujinx/files/7963438/OPENGL.Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_10-54-18.log)

### Spec
Ryujinx version: Ryujinx-Release-1.0.0+8c7ad0f-win_x64
Game version: 1.0.1
Shader: 6014 form Emusak

OS: Windows 11
STORAGE: SSD
CPU: AMD Ryzen 5 3600
GPU: AMD RX 570 8gb
RAM: 16gb

### Screenshot
VULKAN
![ryujinx_capture_2022-01-29_10-40-34](https://user-images.githubusercontent.com/98625359/151656881-d7d99b06-2bc3-44bd-95cd-f4c05e2a7fca.png)

OPENGL
![ryujinx_capture_2022-01-29_10-55-22](https://user-images.githubusercontent.com/98625359/151656895-9cddc8a7-a799-4388-ab23-90cd5ac5d14b.png)

VULKAN - BOX BEFORE TITLES
![ryujinx_capture_2022-01-29_10-41-53](https://user-images.githubusercontent.com/98625359/151656906-b388bdd3-7052-423c-83b8-9882d83140a0.png)

SETTINGS
![Immagine 2022-01-29 112049](https://user-images.githubusercontent.com/98625359/151657305-c922f28a-1a6b-4db4-be37-6a36bec005b3.png)
![Immagine 2022-01-29 112108](https://user-images.githubusercontent.com/98625359/151657315-23093d2f-1d49-4e92-9f27-b1e4432f4474.png)

2022-01-29 13:56 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR ryujinx-Release-1.0.0+8c7ad0f-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Starlink is closing when you put an update, this update is necessary to continue with the game, in addition to improving various aspects of the game 
Bullets had the vertex explosions reduced, but it still has, besides now you can continue in the game, there are also graphical flaws, such as black textures and textures blinking 
Final Fantasy VII had a big improvement, however it still has this green pixel on the left corner screen, with this improvement several games now have better rendering 
the performance in Zelda Link Awakerning has improved, but it still has drops, in addition the wrong texture of the water persists
Super Mario Odyssey is almost there, he is more stable, he just needs to improve the performance and make his textures stop blinking, the game Bullets has the same texture problem 
Zelda Skyward Sword still has texture errors and these video errors 
Lodoss still continue the graphical errors 
Mario Kart 8 has improved the performance a lot, the vertex explosions are practically gone (but you still feel on the sweet kingdom track) 
this update was very welcome, it improved the rendering of different games, although certain problems still persist (like the textures blinking) I know that at the moment Pokémon is important, but don't forget about Starlink, I have a lot of fun with the game during the tests of it, even more having the Star Fox team 
![imagem](https://user-images.githubusercontent.com/90729203/151663351-c3700a22-82ea-444f-bb81-6ebaea029776.png)
![imagem](https://user-images.githubusercontent.com/90729203/151663135-169784ec-8583-436a-9f13-7e3090b029ca.png)
![imagem](https://user-images.githubusercontent.com/90729203/151663042-d3d20da9-3b0f-4a94-8c6a-2c5ac8b4d48e.png)
![imagem](https://user-images.githubusercontent.com/90729203/151663014-9689a1ba-fac2-4779-b53e-5f26d4eec9e1.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662975-e65be868-27c3-439e-b6e8-6aa43d05973e.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662828-5072fd6e-55d9-4f29-9cd6-034bcb9f7101.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662587-c5090467-f9d9-45b1-a16d-dcfab4e17774.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662400-7607a36f-c22d-4ddc-a7fa-24f3432a3609.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662355-f5e96884-95c3-451b-a0c3-c541826cd298.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662129-c1231600-1a62-49fd-be9a-80eebd2eee6c.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662013-6d1a906f-99f0-4faa-9eb6-38ba4fafe8a7.png)
![imagem](https://user-images.githubusercontent.com/90729203/151662001-b6c0bf6a-bbe1-4a45-918f-8b044728da86.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661900-abfd9adb-b48f-4f31-9d40-14cf6390775a.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661881-023d179c-c2dc-4727-8dc8-52ed4c6a57a1.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661565-d01b23a5-2c33-4c7f-84c2-b33dd4a5d048.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661518-1d8c3ab0-c7a3-453f-bf17-a5517fd8adbc.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661437-75fcb053-9c7f-4e1c-afe4-8b42f68e4d41.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661358-2f10f375-1395-4b5f-a434-f1e2dae82a00.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661305-bc7e8306-654d-4dcd-be8f-92013097b7b5.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661282-6b27367f-c846-48de-a2b1-6db4700bcf45.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661077-056a2114-c36a-44be-ae31-02c2dbc929a4.png)
![imagem](https://user-images.githubusercontent.com/90729203/151661165-1f49797d-aec5-46df-a087-fe763a221bf7.png)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_09-28-26.log](https://github.com/Ryujinx/Ryujinx/files/7963665/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_09-28-26.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_09-35-12.log](https://github.com/Ryujinx/Ryujinx/files/7963695/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_09-35-12.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_09-56-25.log](https://github.com/Ryujinx/Ryujinx/files/7963720/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_09-56-25.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_10-10-49.log](https://github.com/Ryujinx/Ryujinx/files/7963739/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_10-10-49.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_10-18-12.log](https://github.com/Ryujinx/Ryujinx/files/7963762/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_10-18-12.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_10-28-59.log](https://github.com/Ryujinx/Ryujinx/files/7963774/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_10-28-59.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_10-34-04.log](https://github.com/Ryujinx/Ryujinx/files/7963780/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_10-34-04.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_10-36-59.log](https://github.com/Ryujinx/Ryujinx/files/7963803/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_10-36-59.log)

2022-01-29 20:06 UTC, DragonsFear commented
is there a way to stretch the image like in the mainline build (21/9 - 32/9) or will that be added on a later date 
beqause sofar i havent seen a way to run it in ultrawide

2022-01-29 20:42 UTC, AlfredoDore commented
> s there a way to stretch the image like in the mainline build (21/9 - 32/9) or will that be added on a later date
beqause sofar i havent seen a way to run it in ultrawide

I believe it will, but it's not the time for that, first you have to improve the operation of the emulator (accuracy and performance) and then implement these things

2022-01-30 00:37 UTC, AlfredoDore commented
Win10 64 bits
Sapphire Radeon RX 580 series X 4GB
Ryzen 7 2700x
16GB ram
driver 22.1.2
Lastest PR ryujinx-Release-1.0.0+8c7ad0f-win_x64
Graphics Backend: on
Disable AMD Image Sharpenin
Super Mario 3D World has improved the performance, but the blur is grainy, in addition there is still a loss of performance 
Yoshi has the textures blinking and needs more performance 
Waifu Uncovered is almost resolved, it is constant and does not crash 
Metroid Dread no longer has graphical problems, it just lacks optimization 
Crash still has the bizarre proportions 
Fuga has the best rendered textures, but they still flicker and have latency 
![imagem](https://user-images.githubusercontent.com/90729203/151682306-fd9345db-fc1e-4ac2-8c7a-fcdcc41f83cf.png)
![imagem](https://user-images.githubusercontent.com/90729203/151682213-f3394b32-d2d1-48f3-a419-5294cedfb674.png)
![imagem](https://user-images.githubusercontent.com/90729203/151682186-25445463-8919-4265-b825-ac4412410be7.png)
![imagem](https://user-images.githubusercontent.com/90729203/151682139-534eaa43-de6e-4090-9a8a-862b621d14ca.png)
![imagem](https://user-images.githubusercontent.com/90729203/151682033-08e3b7ce-580b-4ba0-a9e7-f9b95b615de7.png)
![imagem](https://user-images.githubusercontent.com/90729203/151681902-ff5719bc-58f2-45a8-9385-7fdd3e1cc173.png)
![imagem](https://user-images.githubusercontent.com/90729203/151681848-423aeacc-8224-480a-8493-c5778a22a67d.png)
![imagem](https://user-images.githubusercontent.com/90729203/151681718-bc00dfee-b67e-40d4-8989-80172b8175d8.png)
![imagem](https://user-images.githubusercontent.com/90729203/151681658-6307408f-51f6-4272-9f25-01987f771367.png)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_20-59-41.log](https://github.com/Ryujinx/Ryujinx/files/7965020/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_20-59-41.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_21-07-19.log](https://github.com/Ryujinx/Ryujinx/files/7965036/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_21-07-19.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_21-15-05.log](https://github.com/Ryujinx/Ryujinx/files/7965043/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_21-15-05.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_21-23-13.log](https://github.com/Ryujinx/Ryujinx/files/7965047/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_21-23-13.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_21-27-51.log](https://github.com/Ryujinx/Ryujinx/files/7965059/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_21-27-51.log)
[Ryujinx_1.1.0+8c7ad0f_2022-01-29_21-32-07.log](https://github.com/Ryujinx/Ryujinx/files/7965063/Ryujinx_1.1.0%2B8c7ad0f_2022-01-29_21-32-07.log)

2022-01-30 01:44 UTC, jduncanator commented
@AlfredoDore Can I ask you to start placing your images/screenshots into spoilers? It's getting a little hard to parse the information in this thread. Ideally, this thread should only have a single instance of each issue and a single screenshot showing that issue.

2022-01-30 08:21 UTC, benderscruffy commented
Taxi Chaos [0100B76011DAA000][v0]
lots of flashing graphics during gameplay
![ryujinx_capture_2022-01-30_16-18-38](https://user-images.githubusercontent.com/2696404/151692240-b4570560-2620-4830-b562-8c3419dd2d5e.png)
![ryujinx_capture_2022-01-30_16-17-11](https://user-images.githubusercontent.com/2696404/151692248-089082e6-81fe-4909-a784-d25daef24d85.png)

2022-01-30 09:28 UTC, benderscruffy commented
Assault Android Cactus 0100DF200B24C000
missing the characters from the title screen and character select screen (just shadow with the weapons)
![ryujinx_capture_2022-01-30_17-23-44](https://user-images.githubusercontent.com/2696404/151694187-3b967c2d-3722-454a-8d96-b17e8f616e36.png)
![ryujinx_capture_2022-01-30_17-23-27](https://user-images.githubusercontent.com/2696404/151694185-958b3610-397e-414b-adc5-956744450c45.png)
![ryujinx_capture_2022-01-30_17-24-06](https://user-images.githubusercontent.com/2696404/151694191-406a4921-0db4-4539-874c-20f189e5540e.png)

2022-01-30 11:37 UTC, AlfredoDore commented
> @AlfredoDore Can I ask you to start placing your images/screenshots into spoilers? It's getting a little hard to parse the information in this thread. Ideally, this thread should only have a single instance of each issue and a single screenshot showing that issue.
> 
> If you go to the top of this thread, you'll see the template I started using to report issues, it would be great if you could consolidate all your findings into a single post following that format ([here](https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890474275))

right, so it's one game at a time with this information? It happens that there are games that are the same error, because for example: Bullets, Yoshi and Fuga are Unreal Engine

2022-01-30 17:14 UTC, OpalaSS commented
### Crash Team Racing Nitro-Fueled (OPENGL and VULKAN)

Sound is choppy, very unstable.

### Log file

[OPENGL Ryujinx_1.1.14_2022-01-30_13-22-21.log](https://github.com/Ryujinx/Ryujinx/files/7966388/Ryujinx_1.1.14_2022-01-30_13-22-21.log)

[VULKAN Ryujinx_1.1.0+8c7ad0f_2022-01-30_13-31-33.log](https://github.com/Ryujinx/Ryujinx/files/7966391/Ryujinx_1.1.0%2B8c7ad0f_2022-01-30_13-31-33.log)

### Spec

Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
Ryujinx Opengl: 1.1.14

OS: Windows 11
STORAGE: SSD
CPU: Intel 3570K (4.5Ghz)
RAM: 12gb (1600mhz)
GPU: GTX 1070
DRIVER: 511.23

![image](https://user-images.githubusercontent.com/50283428/151709742-076ef56c-6012-41c7-a3d6-2cf8cc5ca37e.png)

![image](https://user-images.githubusercontent.com/50283428/151709768-6a70fbb9-a5be-408f-be62-0473c925fd24.png)

2022-01-30 17:39 UTC, KawaiiDinosaur commented
commit 8c7ad0f-win_x64
Windows 11 21H2
CPU: Ryzen 7 3700X
GPU: Radeon RX 5700 XT
Drivers: Adrenalin 22.1.2

Pokémon Legends Arceus: certain textures displaying text don't load correctly. Other than that, the game runs pretty much perfect.

![ryujinx_capture_2022-01-30_14-27-28](https://user-images.githubusercontent.com/36821201/151710623-c338ab46-3022-4bab-bf2a-4169b74dbc39.png)
![ryujinx_capture_2022-01-30_14-28-19](https://user-images.githubusercontent.com/36821201/151710624-47ed26b9-f12e-48f7-83f3-47b193259ca0.png)

2022-01-30 20:25 UTC, AlfredoDore commented
Starlink
with the update, which is essential to continue in the game, it doesn't go beyond the menu and without the update there are performance and video playback problems (in addition to graphical problems) 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-01-30_17-12-56.log](https://github.com/Ryujinx/Ryujinx/files/7966852/Ryujinx_1.1.0%2B8c7ad0f_2022-01-30_17-12-56.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor  4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151716205-d9b09bf5-293d-4288-bbc2-5d3d695db0b6.png)
![imagem](https://user-images.githubusercontent.com/90729203/151716305-24114c24-4794-483d-98a1-bbe48c3a0ff2.png)

2022-01-30 21:24 UTC, andresgonz13 commented
It crashes when i use the vulkan api in Pokemon Arceus (it opens with opengl but it is slow and the characters are invisible)
AMD R9 270X 4GB
I5 3570
16GB RAM
[Ryujinx_1.0.0-dirty_2022-01-30_17-14-39.log](https://github.com/Ryujinx/Ryujinx/files/7966945/Ryujinx_1.0.0-dirty_2022-01-30_17-14-39.log)

2022-01-30 23:04 UTC, jduncanator commented
> It crashes when i use the vulkan api in Pokemon Arceus (it opens with opengl but it is slow and the characters are invisible) (I get the start menu, the game crashes after i press start and loading for a while) AMD R9 270X 4GB (ADRENALIN 21.5.2, last update for my graphic) I5 3570 16GB RAM [Ryujinx_1.0.0-dirty_2022-01-30_17-14-39.log](https://github.com/Ryujinx/Ryujinx/files/7966945/Ryujinx_1.0.0-dirty_2022-01-30_17-14-39.log)

Pokémon: LA requires the latest optional drivers from AMD. Unfortunately, that means if these drivers aren't available for your graphics card, you won't be able to launch Pokémon: LA. There's not much we can do on our end, as there are bugs in the older drivers.

If you have a save, you can bypass the opening sequence and should be able to get in game on an older driver version.

2022-01-31 00:00 UTC, AlfredoDore commented
Crash Trilogy
has latency issues and these weird proportions of textures, including latency affects the sync of audios in videos 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-01-30_20-53-40.log](https://github.com/Ryujinx/Ryujinx/files/7967241/Ryujinx_1.1.0%2B8c7ad0f_2022-01-30_20-53-40.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151723230-b0924664-7747-47ee-a07b-3573609a035c.png)
![imagem](https://user-images.githubusercontent.com/90729203/151723301-20e57d9f-91fb-4c9b-b8f6-ec389d5d73fb.png)

2022-01-31 10:30 UTC, benderscruffy commented
Dead Cells 0100646009FBE000
rainbow bits on the title screen
![ryujinx_capture_2022-01-31_17-47-00](https://user-images.githubusercontent.com/2696404/151777874-587933f5-4364-4012-9128-83af32b1426a.png)
mini map during gameplay is messed up
![ryujinx_capture_2022-01-31_17-47-53](https://user-images.githubusercontent.com/2696404/151777895-3fadc123-1e48-46b5-a521-07a09c6b733c.png)

2022-01-31 10:36 UTC, benderscruffy commented
Laytons Mystery Journey Katrielle to Daifugo no Inbo DX Plus [0100FDB00AA80000][v0][JP]
has been fixed
no problems so far
![ryujinx_capture_2022-01-31_18-33-39](https://user-images.githubusercontent.com/2696404/151778767-18dee1ad-07a1-4571-8364-32c5d05f572b.png)

2022-01-31 12:30 UTC, AlfredoDore commented
Super Mario 3D World
there is grain in the blur (I checked) and the game has a loss of performance, but no other apparent graphical errors 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-01-31_09-20-37.log](https://github.com/Ryujinx/Ryujinx/files/7970624/Ryujinx_1.1.0%2B8c7ad0f_2022-01-31_09-20-37.log)

Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151793576-6d735ab8-5f0a-48bb-aa8d-8db86fbbbb49.png)

2022-01-31 12:38 UTC, AlfredoDore commented
Resident Evil Revelations 2
there are no apparent graphical problems, just loss of performance 

Log file
[Ryujinx_1.1.0+8c7ad0f_2022-01-31_09-31-38.log](https://github.com/Ryujinx/Ryujinx/files/7970687/Ryujinx_1.1.0%2B8c7ad0f_2022-01-31_09-31-38.log)


Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151794716-a897563f-274c-4775-8919-1430e7e4d148.png)
![imagem](https://user-images.githubusercontent.com/90729203/151794937-1cb631dd-2b28-4557-9bdc-930cd86b9b0b.png)

2022-01-31 12:49 UTC, AlfredoDore commented
The World Ends with You -Final Remix-
it's fine 

Log file
[Ryujinx_1.1.0+8c7ad0f_2022-01-31_09-39-36.log](https://github.com/Ryujinx/Ryujinx/files/7970759/Ryujinx_1.1.0%2B8c7ad0f_2022-01-31_09-39-36.log)

Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151796214-5d1b6eda-2b22-4823-bfe4-f304f40bbe28.png)

2022-01-31 13:27 UTC, AlfredoDore commented
Reisdent Evil Revelations 1
no graphics problems, but it has performance losses (basically every gun shot slows down the game, the other RE 0 and 1 also have the same problem) 

Log file
[Ryujinx_1.1.0+8c7ad0f_2022-01-31_10-16-20.log](https://github.com/Ryujinx/Ryujinx/files/7970994/Ryujinx_1.1.0%2B8c7ad0f_2022-01-31_10-16-20.log)


Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151800810-25cd2a2a-56ce-4e06-a754-16c8db315721.png)
![imagem](https://user-images.githubusercontent.com/90729203/151801266-7179aebe-74ac-478e-a8e8-75eb38ab2ad2.png)

2022-01-31 17:23 UTC, AlfredoDore commented
Super Mario Odyssey
the textures are flashing very fast (so much so that I can't capture it at first) and there's a lot of performance loss 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-01-31_14-13-12.log](https://github.com/Ryujinx/Ryujinx/files/7972795/Ryujinx_1.1.0%2B8c7ad0f_2022-01-31_14-13-12.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151842090-b30e6f26-78a0-4045-874d-a018b9c1162d.png)

2022-02-01 12:41 UTC, AlfredoDore commented
Lodoss
has a lot of sprite problems 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-01_09-35-56.log](https://github.com/Ryujinx/Ryujinx/files/7978471/Ryujinx_1.1.0%2B8c7ad0f_2022-02-01_09-35-56.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151969646-44e1a177-5b71-4679-b78f-976454211d73.png)

2022-02-01 12:56 UTC, AlfredoDore commented
Resident Evil 0
it has no graphics problems, what remains is to improve the performance (when it fires it slows down the game, the others are also the same way) 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-01_09-48-58.log](https://github.com/Ryujinx/Ryujinx/files/7978566/Ryujinx_1.1.0%2B8c7ad0f_2022-02-01_09-48-58.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151971917-9774b8f3-7583-4747-8eaf-b5dabe0fe635.png)

2022-02-01 13:20 UTC, AlfredoDore commented
Donkey Kong Tropical Freeze
on the map it has graphics problems and suffers from slowness, on the stage I noticed a lighting error, especially in the letters of the barrels 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-01_10-10-25.log](https://github.com/Ryujinx/Ryujinx/files/7978709/Ryujinx_1.1.0%2B8c7ad0f_2022-02-01_10-10-25.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/151974917-0aa3fecc-6065-4ecb-b5ca-2bfd61f80f4d.png)

2022-02-01 13:24 UTC, AlfredoDore commented
Animal Crossing New Horizons 
does not start 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-01_10-21-02.log](https://github.com/Ryujinx/Ryujinx/files/7978732/Ryujinx_1.1.0%2B8c7ad0f_2022-02-01_10-21-02.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2

2022-02-01 14:53 UTC, AlfredoDore commented
Pokémon Brilliant diamond
does not start
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-01_11-49-56.log](https://github.com/Ryujinx/Ryujinx/files/7979345/Ryujinx_1.1.0%2B8c7ad0f_2022-02-01_11-49-56.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2

2022-02-01 20:23 UTC, RaphaelIPBeja commented
When playing pokemon full screen, the fps drops a lot.. but i noticed something REALLY weird. If i play full screen, i get like 19 FPS using rx6900xt and gpu gets silent, like its not under work, but if i open AMD overlay pressing alt+r, looks like the gpu wakes up and it gets into 30 fps (vsync enabled) and gpu consumption goes from 50w into 84w, game gets smooth and as soon as i close the overlay (alt+r) or click the game itself, fps drops into 19 again and gpu just goes silent again. Any ideias?

2022-02-01 22:46 UTC, AlfredoDore commented
> When playing pokemon full screen, the fps drops a lot.. but i noticed something REALLY weird. If i play full screen, i get like 19 FPS using rx6900xt and gpu gets silent, like its not under work, but if i open AMD overlay pressing alt+r, looks like the gpu wakes up and it gets into 30 fps (vsync enabled) and gpu consumption goes from 50w into 84w, game gets smooth and as soon as i close the overlay (alt+r) or click the game itself, fps drops into 19 again and gpu just goes silent again. Any ideias?

this happens to me too, it's as if the card is not used (in neither of the two Switch emulators)

2022-02-02 03:57 UTC, DragonsFear commented
> When playing pokemon full screen, the fps drops a lot.. but i noticed something REALLY weird. If i play full screen, i get like 19 FPS using rx6900xt and gpu gets silent, like its not under work, but if i open AMD overlay pressing alt+r, looks like the gpu wakes up and it gets into 30 fps (vsync enabled) and gpu consumption goes from 50w into 84w, game gets smooth and as soon as i close the overlay (alt+r) or click the game itself, fps drops into 19 again and gpu just goes silent again. Any ideias?

here running with a RX570 8GB OC Edition , and can't say i noticed this , sure some drops in fps in the city (from 30 to 25/26), but overall 30fps stable

2022-02-02 06:07 UTC, AutumnWolfMike commented
![ryujinx_capture_2021-11-19_15-09-11](https://user-images.githubusercontent.com/98867177/152098862-c18db571-6b7b-4dca-a9fe-054ea0e41933.png)

Yo-Yo and Whip both do this... Whip is only glitchy if you use the whip but Yo Yo is always like that

![ryujinx_capture_2022-02-01_23-34-30](https://user-images.githubusercontent.com/98867177/152099131-7ac8dd17-a4b6-43c9-9f89-718837f924c9.png)

In Bowser's Fury you can see the water's wireframe sometimes

![ryujinx_capture_2022-02-01_23-29-13](https://user-images.githubusercontent.com/98867177/152099392-8d76b48e-4868-4fa0-aa02-7354d6ca5bae.png)

Urbosa's Dress has vertex explosions and the floor looks like this

![ryujinx_capture_2022-01-26_14-58-54](https://user-images.githubusercontent.com/98867177/152099474-cc60a4f4-845b-47e3-a3dc-daecfb8b1c49.png)

While mostly perfect I encountered some random vertex explosions in Pokemon Legends Arceus, reloading the area/game fixes the issue

These are very rare and only saw em a few times
![ryujinx_capture_2022-02-01_23-48-19](https://user-images.githubusercontent.com/98867177/152100331-d125b02d-0657-417c-aeed-6df38055f57c.png)
![ryujinx_capture_2022-02-01_23-48-52](https://user-images.githubusercontent.com/98867177/152100342-ef10d749-9e42-41ed-9ef3-6ed64c3a877e.png)
![ryujinx_capture_2022-02-01_23-49-23](https://user-images.githubusercontent.com/98867177/152100498-1943840d-6bf8-4b47-abd5-3511cde3b4da.png)

Mon Hun Rise has lots of issues with character faces and rendering clothes. The game also seems to skip frames (it is not caching, because I already cached the places where it does this)

![ryujinx_capture_2022-02-01_23-49-05](https://user-images.githubusercontent.com/98867177/152100578-b5b06dfe-783a-4e1f-b5e8-57d1434458c0.png)

This thing is glitchy too

![ryujinx_capture_2022-02-01_23-57-49](https://user-images.githubusercontent.com/98867177/152101084-ac9a197e-2b24-40e9-9612-c667d7a2fd32.png)
![ryujinx_capture_2022-02-01_23-58-01](https://user-images.githubusercontent.com/98867177/152101090-6365d6fa-b763-4561-b055-e1d9912316a9.png)

And some of the terrain is invisible

![ryujinx_capture_2022-02-01_23-56-18](https://user-images.githubusercontent.com/98867177/152101585-6ea550bd-5c21-4da3-892c-50c455af531c.png)
![ryujinx_capture_2022-02-01_23-56-19](https://user-images.githubusercontent.com/98867177/152101513-9b951c6f-766f-4bae-b746-5f696cf32d41.png)

Lighting changes abruptly, sometimes it only affects some objects and others not

![Capture](https://user-images.githubusercontent.com/98867177/152101381-12aa10f7-fede-4275-a101-b9e1d2f490e1.PNG)

I am running this version of the vulkan drivers on a RX 570 card

2022-02-03 17:31 UTC, jochuan commented
On cytus alpha the main menu is fullspeed but when you start the tutorial the fps drop to around 30 and the music begins to stutter a lot and if you start a normal music stage the music is normal but the fps is low ( 18-35fps).
[Ryujinx_1.1.0+8c7ad0f_2022-02-03_14-06-30.log](https://github.com/Ryujinx/Ryujinx/files/7996843/Ryujinx_1.1.0%2B8c7ad0f_2022-02-03_14-06-30.log)
.

2022-02-04 11:45 UTC, Squall-Leonhart commented
Any reason why you are using vkstatic? its outdated and has multiple drawbacks.

2022-02-04 12:04 UTC, riperiperi commented
Not really sure what you mean here. Vulkan loading is controlled by Silk.NET, and it seems to load the regular `libvulkan.so` and `vulkan-1.dll` libraries.

https://github.com/dotnet/Silk.NET/blob/main/src/Vulkan/Silk.NET.Vulkan/VulkanLibraryNameContainer.cs

2022-02-04 12:13 UTC, riperiperi commented
> On cytus alpha the main menu is fullspeed but when you start the tutorial the fps drop to around 30 and the music begins to stutter a lot and if you start a normal music stage the music is normal but the fps is low ( 18-35fps).

> 00:00:00.148 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl

Make sure your graphics backend is set to Vulkan.

2022-02-04 12:37 UTC, Squall-Leonhart commented
Yes, it seems something is up with my machine causing RTSS to fail to hook, the developer has just confirmed it working on his end.

2022-02-04 14:00 UTC, jochuan commented
> > On cytus alpha the main menu is fullspeed but when you start the tutorial the fps drop to around 30 and the music begins to stutter a lot and if you start a normal music stage the music is normal but the fps is low ( 18-35fps).
> 
> > 00:00:00.148 |I| Configuration LogValueChange: GraphicsBackend set to: OpenGl
> 
> Make sure your graphics backend is set to Vulkan.

Strange, i though that i was using vulkan before, i didn't even had to change my backend when i booted the emulator today but anyway i made sure that i was using vulkan now and i still get a lot of stutters in the tutorial but looks like the other musics are normal.
[Ryujinx_1.1.0+8c7ad0f_2022-02-04_10-45-31.log](https://github.com/Ryujinx/Ryujinx/files/8003550/Ryujinx_1.1.0%2B8c7ad0f_2022-02-04_10-45-31.log)

2022-02-04 16:28 UTC, AlfredoDore commented
![imagem](https://user-images.githubusercontent.com/90729203/152565299-2e2c610f-4a20-495b-8194-aa87bf98f5e1.png)
![imagem](https://user-images.githubusercontent.com/90729203/152565803-579236a9-7a2f-480e-a4cc-51633b627fbb.png)

2022-02-04 23:14 UTC, benderscruffy commented
Kirby Star Allies v1.0.0
intro video (Starfall A Rude Awakening)
nothing but a black screen with the sound
Lets be Friends video
keeps on flickering so much
keeps on spamming
00:01:23.502 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x7FFFF (sRGB: False)
[Ryujinx_1.1.0+8c7ad0f_2022-02-05_07-07-15.log](https://github.com/Ryujinx/Ryujinx/files/8006767/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_07-07-15.log)

2022-02-05 02:24 UTC, benderscruffy commented
Gato Roboto
missing part of the border on the bottom right  hand side
![ryujinx_capture_2022-02-05_10-22-56](https://user-images.githubusercontent.com/2696404/152625353-acfdf97e-c0a5-4099-8973-f7cd3220c496.png)

2022-02-05 03:10 UTC, benderscruffy commented
Pinball FX3
black screen with the scoreboard and music playing
![ryujinx_capture_2022-02-05_11-03-19](https://user-images.githubusercontent.com/2696404/152626748-e6e9feb0-cb4c-4469-b0de-5ebdc800a464.png)
![ryujinx_capture_2022-02-05_11-03-27](https://user-images.githubusercontent.com/2696404/152626752-8f8ce782-fbb2-463f-96c5-801007622255.png)
![ryujinx_capture_2022-02-05_11-03-35](https://user-images.githubusercontent.com/2696404/152626753-40062479-ae69-4903-95cc-07c9f6c20647.png)

2022-02-05 03:43 UTC, benderscruffy commented
WRC 9 The Official Game 
black squares around the car on the title screen
during game black squares from the wheels (supposed to be dust or smoke)
![ryujinx_capture_2022-02-05_11-35-35](https://user-images.githubusercontent.com/2696404/152627551-b7972df4-c81b-4e34-9f95-ca2d98222d95.png)
![ryujinx_capture_2022-02-05_11-39-29](https://user-images.githubusercontent.com/2696404/152627554-2569b04b-2400-4adc-9728-fdf76b097b3f.png)

2022-02-05 03:54 UTC, benderscruffy commented
Quest of Dungeons 
has been fixed
![ryujinx_capture_2022-02-05_11-52-41](https://user-images.githubusercontent.com/2696404/152627809-8cbb589b-71eb-481d-8471-c7fc66e70cc3.png)

2022-02-05 04:02 UTC, benderscruffy commented
Rush Rally Origins 
missing lots of graphics
![ryujinx_capture_2022-02-05_11-59-35](https://user-images.githubusercontent.com/2696404/152627970-4f59af38-1a0c-439c-945d-04f0726bb0eb.png)
keeps spamming
00:04:06.514 |E| GUI.RenderLoop Gpu ConvertToVkFormat: Format Etc2RgbUnorm is not supported by the host.
[Ryujinx_1.1.0+8c7ad0f_2022-02-05_11-55-26.log](https://github.com/Ryujinx/Ryujinx/files/8007337/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_11-55-26.log)

2022-02-05 04:14 UTC, benderscruffy commented
Monster Blast 
after you choose your level it crashes out the emulator
![ryujinx_capture_2022-02-05_12-12-17](https://user-images.githubusercontent.com/2696404/152628228-e4130512-8212-4188-bf41-a9167180681d.png)
[Ryujinx_1.1.0+8c7ad0f_2022-02-05_12-09-42.log](https://github.com/Ryujinx/Ryujinx/files/8007355/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_12-09-42.log)

00:02:17.676 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x4913A (sRGB: False).
00:02:17.846 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x113C6F000..0x114C6F000 is not fully mapped.
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 376
   at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureCache.cs:line 485
   at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 64
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 416
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 345
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.CommitBindings() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 239
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 130
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 224
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 128
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__65_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 396
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100

2022-02-05 04:44 UTC, Aayan22112 commented
> Download the artifacts for this pull request:
> 
>     * [ryujinx-headless-sdl2-Release-1.0.0+8c7ad0f-linux_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/152854828.zip)
> 
>     * [ryujinx-headless-sdl2-Release-1.0.0+8c7ad0f-osx_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/152854829.zip)
> 
>     * [ryujinx-headless-sdl2-Release-1.0.0+8c7ad0f-win_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/152854830.zip)
> 
>     * [ryujinx-Release-1.0.0+8c7ad0f-linux_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/152854831.zip)
> 
>     * [ryujinx-Release-1.0.0+8c7ad0f-osx_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/152854832.zip)
> 
>     * [ryujinx-Release-1.0.0+8c7ad0f-win_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/152854833.zip)
> 
> 
> Only for Developers

Not able to download this for Win version. Download gets interrupted after 20+ mb, and file corrupts.

2022-02-05 04:45 UTC, Aayan22112 commented
Unable to download the Win version, Download gets interrupted after 20+ mb and get a corrupt file
 Please check

2022-02-05 05:05 UTC, GamerzHell9137 commented
> Unable to download the Win version, Download gets interrupted after 20+ mb and get a corrupt file Please check

Dont use any kind of downloader apps and download it trough default browser download managers eg Chrome, Firefox.

2022-02-05 12:42 UTC, AlfredoDore commented
Shadow Man Remastered
the graphics are totally broken, however the audio is perfect 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-05_09-29-41.log](https://github.com/Ryujinx/Ryujinx/files/8008025/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_09-29-41.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.1
![imagem](https://user-images.githubusercontent.com/90729203/152642318-7a4730f4-222b-4b47-bfd7-4f903fcbac8f.png)
![imagem](https://user-images.githubusercontent.com/90729203/152642401-cf2fcdb2-74bb-47e7-88f0-c46364d89a67.png)
![imagem](https://user-images.githubusercontent.com/90729203/152642434-a0a84a2b-2467-4792-b2b6-137845df06a1.png)

2022-02-05 13:05 UTC, AlfredoDore commented
Megaton Musashi
need to improve performance 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-05_09-51-10.log](https://github.com/Ryujinx/Ryujinx/files/8008057/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_09-51-10.log)

Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.1
![imagem](https://user-images.githubusercontent.com/90729203/152643258-b38ad5fa-ada8-4a99-ae93-489e6a0bf21c.png)

2022-02-06 02:43 UTC, benderscruffy commented
Lost Lands 2 The Four Horsemen
the smoke and fog are square artefact's
black lines through title screen
![ryujinx_capture_2022-02-06_10-35-58](https://user-images.githubusercontent.com/2696404/152665842-daa708c2-a03b-4a65-8757-51fa669e2c7a.png)
![ryujinx_capture_2022-02-06_10-39-34](https://user-images.githubusercontent.com/2696404/152665845-73595852-2062-4b08-99f9-b42266354f7e.png)
![ryujinx_capture_2022-02-06_10-39-47](https://user-images.githubusercontent.com/2696404/152665848-5a5dd7db-778e-4591-8fbd-010519c711a3.png)

2022-02-06 02:56 UTC, benderscruffy commented
Monster Jam Steel Titans 2
corrupt text
![ryujinx_capture_2022-02-06_10-52-53](https://user-images.githubusercontent.com/2696404/152666082-3bbe2d0c-158a-49a6-892e-5b8092d5a368.png)

2022-02-06 07:56 UTC, benderscruffy commented
Shadow Gangs 
graphic artefacts on the right hand side of the screen when you walk
![ryujinx_capture_2022-02-06_15-48-12](https://user-images.githubusercontent.com/2696404/152672279-730a43f9-73fa-47d6-9dc0-d2ca10ee39dd.png)
![ryujinx_capture_2022-02-06_15-52-31](https://user-images.githubusercontent.com/2696404/152672282-36de6908-448d-4bad-bb73-173eeef6c97f.png)
![ryujinx_capture_2022-02-06_15-52-39](https://user-images.githubusercontent.com/2696404/152672283-97803a14-6645-44b1-8fb9-d12bd08b05f4.png)

2022-02-06 12:14 UTC, AlfredoDore commented
Blaster Master Zero 1
there is a problem with the 1.6 update, the previous update is normal 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-05_10-19-20.log](https://github.com/Ryujinx/Ryujinx/files/8010130/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_10-19-20.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.1
![imagem](https://user-images.githubusercontent.com/90729203/152680151-f3ffaefe-85e7-42ae-b341-b179c921e873.png)

2022-02-06 18:32 UTC, AlfredoDore commented
Jack Axe 
it's going very well, just the loading bar that blinks, but the rest is excellent 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-06_15-23-33.log](https://github.com/Ryujinx/Ryujinx/files/8010873/Ryujinx_1.1.0%2B8c7ad0f_2022-02-06_15-23-33.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.1
![imagem](https://user-images.githubusercontent.com/90729203/152695840-ba8302b2-5e99-4c50-a50c-d13934b65274.png)

2022-02-06 18:55 UTC, AlfredoDore commented
Zelda Breath of the Wide
there are still many problems 
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-06_15-50-40.log](https://github.com/Ryujinx/Ryujinx/files/8010954/Ryujinx_1.1.0%2B8c7ad0f_2022-02-06_15-50-40.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.1
![imagem](https://user-images.githubusercontent.com/90729203/152696766-73e0a352-3e4d-4e40-a0d6-3a3431fb95dd.png)

2022-02-06 19:21 UTC, AlfredoDore commented
Zelda Skaward Sword
brown textures, and texture errors  
Log file
[Ryujinx_1.1.0+8c7ad0f_2022-02-06_16-16-59.log](https://github.com/Ryujinx/Ryujinx/files/8011051/Ryujinx_1.1.0%2B8c7ad0f_2022-02-06_16-16-59.log)
Spec
Ryujinx Vulkan: 1.0.0+8c7ad0f-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.1
![imagem](https://user-images.githubusercontent.com/90729203/152697630-9771fe82-db02-4a50-9167-3108e05f7c11.png)
![imagem](https://user-images.githubusercontent.com/90729203/152697658-4d0e4e22-49bd-422b-9350-cfc4a269061b.png)
![imagem](https://user-images.githubusercontent.com/90729203/152697728-e0b1b636-95b7-4fd2-914c-54a8d5b8455e.png)
![imagem](https://user-images.githubusercontent.com/90729203/152697772-2ebefed7-0d0c-46e5-9023-e74415716704.png)

2022-02-08 03:52 UTC, Cougar164 commented
> ### Overview
> This is a WIP implementation of a Vulkan graphics backend. The main goal here is improving the performance for AMD users, however there are other advantages of using Vulkan for all vendors.
> 
> Main advantages of Vulkan (for all vendors):
> 
> * Support for compressed 3D textures: Fixes graphical glitches on Tales of Vesperia, Ghost & Goblins returns, Monster Hunter Rise and more.
> * Support for textures views between compressed and uncompressed formats. Avoids copies, we do not yet take advantage of this, but will in the future.
> * Supports for 2D array views from 3D textures. Avoids copies, we do not yet take advantage of this, but will in the future.
> * Allows transform feedback buffers to have other uses while the transform feedback is active. Avoids copies.
> 
> ### Pending work
> Those items should be completed before the Vulkan implementation is merged.
> 
> * [ ]  Multisampling support.
> * [x]  Alpha test support.
> * [x]  Custom image formats at bind. Or maybe change how it works to play nicely with Vulkan? (Required to render ground etc correctly on Xenoblade Chronicles Definitive Edition, fire/ice etc effects on Kirby Star Allies).
> * [ ]  Make sure it plays nicely with the AMD driver (there are currently some known bugs with AMD drivers, more on that later).
> * [ ]  Integrate SPIR-V backend and make sure it is functionally equivalent to the GLSL one.
> * [ ]  Write basic tests for shaders and the backend, to ensure they behave as expected.
> 
> Other nice-to-haves, not essential for merge:
> 
> * [ ]  Index buffer conversion for quads. Should improve the speed of games using quads.
> * [ ]  Better Uint8 index buffer conversion. ~Should have some very minor performance improvement for AMD.~ AMD now supports Uint8 index buffers.
> * [ ]  Experiment with other descriptor set update methods. May improve performance. I already made quite a lot of tests in this area however, and it doesn't seems like there's much we can do to improve it further.
> * [x]  ~Consider using a separate thread for command submission. Might benefit Intel due to the workaround that makes it submit commands a lot.~ No longer an issue, the workaround was removed as the bug was fixed on their driver.
> * [ ]  Pipeline cache. Effectively a on-disk shader cache on Vulkan.
> 
> ### Known issues
> * ~Some game models are stretching to the origin on AMD. **The last version of their driver that is known to function properly is 21.3.2**. You might want to downgrade it if you want to try this without the vertex corruption for now.~ Fixed on [66dd537](https://github.com/Ryujinx/Ryujinx/commit/66dd53716fd71f1758bef7696e4238e47af245e0), **downgrading the driver should be no longer needed**, just use the latest version.
> * AMD also suffers from a issue where the window is partially transparent and the desktop is visible. Not all systems are affected, it is currently unknown exactly what triggers it, it might be a GTK issue.
> * Missing transparency on a few games due to the lack of alpha test.
> * Some games (Luigi's Mansion 3, Mario Tennis Aces, etc) softlocks on Intel because sampler arrays are not properly defined on pipeline layouts on Vulkan. It will be addressed separately, as the plan is using a different method to handle those textures.
> 
> ### Performance roadmap
> The changes below should improve performance significantly on the Vulkan backend in the near future.
> 
> * Threaded GAL: Large performance improvements for all vendors, since Vulkan drivers do not provide any form of threaded optimizations, unlike OpenGL.
> * SPIR-V backend: This will not improve overall performance, but will reduce shader compilation times and consequently, stutters, resulting in a smoother experience. It is not currently included to make the testing process easier. Right now, it converts GLSL to SPIR-V at runtime. If there is a bug, we know it's not due to shaders, since it is using the same shader source used on OpenGL (for the most part). The SPIR-V backend will be included soon, and enabled by default after Vulkan and SPIR-V has received enough internal testing.
> 
> **Async shader compilation:** This is something that is asked a lot. The truth is that async shader compilation is not really worth it, since it introduces graphical glitches, and in fact, pretty much all emulators that implemented this feature in the past **are moving away from it because there are better alternatives**. The better alternative in this case is parallel shader compilation, which also reduces the compilation times significantly without introducing graphical glitches. **This is already implemented as part of Threaded GAL, and will also come to Vulkan after Threaded GAL is merged**.
> 
> ### Improvements
> AMD:
> 
> TBD
> 
> Intel: Some graphical issues that exists on OpenGL are not present on Vulkan.
> 
> OpenGL: ![image](https://user-images.githubusercontent.com/5624669/127716506-403ea8ba-77f5-4dad-bca8-548cf3be93f0.png) ![image](https://user-images.githubusercontent.com/5624669/127716582-f1c498b6-a570-4774-9fb2-45b866d0e1ab.png) Vulkan: ![image](https://user-images.githubusercontent.com/5624669/127716635-7cf8429a-775e-42dc-98c7-5a46d5c7a6e4.png) ![image](https://user-images.githubusercontent.com/5624669/127716652-53dbed14-6409-4de0-b1ca-79905862e491.png)
> 
> OpenGL: ![image](https://user-images.githubusercontent.com/5624669/127717322-b8fca13e-75f1-425e-8fc4-2e22494042e3.png) Vulkan: ![image](https://user-images.githubusercontent.com/5624669/127781422-8a26aeb5-d72e-4f16-86dc-a13a4117fb7a.png)
> 
> OpenGL: ![image](https://user-images.githubusercontent.com/5624669/127718135-e6fe22a5-6359-4005-beb3-9ce5691fd946.png) Vulkan: ![image](https://user-images.githubusercontent.com/5624669/127718299-330a4fe2-8288-4534-9fb8-97b5401f4367.png) ![image](https://user-images.githubusercontent.com/5624669/127718332-5eadc2f6-c73d-4170-b2fd-dd32e055cb91.png) ![image](https://user-images.githubusercontent.com/5624669/127718682-d1be1ab2-284b-495a-8fbe-ff24172023fd.png)
> 
> ### What to test
> All games really, but if you find a issue, before reporting, make sure it was not already reported, or is included on the "known issues" section.



> ### Overview
> This is a WIP implementation of a Vulkan graphics backend. The main goal here is improving the performance for AMD users, however there are other advantages of using Vulkan for all vendors.
> 
> Main advantages of Vulkan (for all vendors):
> 
> * Support for compressed 3D textures: Fixes graphical glitches on Tales of Vesperia, Ghost & Goblins returns, Monster Hunter Rise and more.
> * Support for textures views between compressed and uncompressed formats. Avoids copies, we do not yet take advantage of this, but will in the future.
> * Supports for 2D array views from 3D textures. Avoids copies, we do not yet take advantage of this, but will in the future.
> * Allows transform feedback buffers to have other uses while the transform feedback is active. Avoids copies.
> 
> ### Pending work
> Those items should be completed before the Vulkan implementation is merged.
> 
> * [ ]  Multisampling support.
> * [x]  Alpha test support.
> * [x]  Custom image formats at bind. Or maybe change how it works to play nicely with Vulkan? (Required to render ground etc correctly on Xenoblade Chronicles Definitive Edition, fire/ice etc effects on Kirby Star Allies).
> * [ ]  Make sure it plays nicely with the AMD driver (there are currently some known bugs with AMD drivers, more on that later).
> * [ ]  Integrate SPIR-V backend and make sure it is functionally equivalent to the GLSL one.
> * [ ]  Write basic tests for shaders and the backend, to ensure they behave as expected.
> 
> Other nice-to-haves, not essential for merge:
> 
> * [ ]  Index buffer conversion for quads. Should improve the speed of games using quads.
> * [ ]  Better Uint8 index buffer conversion. ~Should have some very minor performance improvement for AMD.~ AMD now supports Uint8 index buffers.
> * [ ]   [...]

2022-02-08 03:54 UTC, Cougar164 commented
Please can someone me when im using Open GL the game will launch but when im using Vulkan the game is not launching my gpu is Nvidia GTX 1650

2022-02-09 09:29 UTC, benderscruffy commented
Hard West - 0100ECE00D13E000
background is white
![ryujinx_capture_2022-02-09_17-14-35](https://user-images.githubusercontent.com/2696404/153165937-b32be8b9-818a-426c-94f3-01653501e7dd.png)
opengl is fine
![153144692-a58355c8-4dc7-41a5-8339-9fea12f61296](https://user-images.githubusercontent.com/2696404/153166002-f79e3fdf-3ba6-4353-8e96-852585c5eaa1.png)

2022-02-12 08:35 UTC, ibrokemypie commented
Pokemon Legends Arceus crashes before displaying the game at all but after loading (I think)
Using mesa 21.3.5, linux 5.17 rc 2, ryujinx build 1.0.0+8c7ad0f-linux_x64
RX6600xt, i7 4770k, 16gb ddr3 ram
[Ryujinx_1.1.0+8c7ad0f_2022-02-12_19-29-18.log](https://github.com/Ryujinx/Ryujinx/files/8053064/Ryujinx_1.1.0%2B8c7ad0f_2022-02-12_19-29-18.log)

2022-02-13 09:11 UTC, benderscruffy commented
Hollow Knight
graphic glitches with character and other things
![ryujinx_capture_2022-02-13_17-08-21](https://user-images.githubusercontent.com/2696404/153746432-469d169c-9398-4df2-b0c9-0e97fe084c87.png)
![ryujinx_capture_2022-02-13_17-08-56](https://user-images.githubusercontent.com/2696404/153746437-b5b849e3-0221-4d26-bf36-49135cbb1134.png)

2022-02-13 16:56 UTC, AlfredoDore commented
Lodoss
is still having serious texture problems 
Log file
[Ryujinx_1.1.0+cb27bc4_2022-02-13_13-45-08.log](https://github.com/Ryujinx/Ryujinx/files/8056121/Ryujinx_1.1.0%2Bcb27bc4_2022-02-13_13-45-08.log)
Spec
ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153765439-14872ae5-8cde-49b4-8c53-4a4d31378741.png)

2022-02-13 17:01 UTC, AlfredoDore commented
Shadow Man
is still having serious texture problems
Log file
[Ryujinx_1.1.0+cb27bc4_2022-02-13_13-56-53.log](https://github.com/Ryujinx/Ryujinx/files/8056142/Ryujinx_1.1.0%2Bcb27bc4_2022-02-13_13-56-53.log)
Spec
ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153765875-0947128b-3be2-4681-8335-d657b5cc1924.png)
![imagem](https://user-images.githubusercontent.com/90729203/153765937-6025bcc6-cc5d-4614-89fb-c9b347ac8256.png)

2022-02-13 17:06 UTC, AlfredoDore commented
Zelda Breath of the Wild
is still having serious texture problems and income 
Log file
[Ryujinx_1.1.0+cb27bc4_2022-02-13_14-02-00.log](https://github.com/Ryujinx/Ryujinx/files/8056150/Ryujinx_1.1.0%2Bcb27bc4_2022-02-13_14-02-00.log)

Spec
ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153766072-0fadbbe0-1853-4fd3-89cf-50380287050a.png)

2022-02-13 17:17 UTC, AlfredoDore commented
Yoshi
is still having serious texture problems and income
Log file
[Ryujinx_1.1.0+cb27bc4_2022-02-13_14-09-16.log](https://github.com/Ryujinx/Ryujinx/files/8056183/Ryujinx_1.1.0%2Bcb27bc4_2022-02-13_14-09-16.log)
Spec
ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153766364-01164306-3a71-4270-b273-3c1f4b73274d.png)
![imagem](https://user-images.githubusercontent.com/90729203/153766512-623510cf-1df6-4f5b-8740-1e0e94536828.png)

2022-02-13 17:22 UTC, AlfredoDore commented
Crash Trilogy
is still having serious texture problems and income
Log file
[Ryujinx_1.1.0+cb27bc4_2022-02-13_14-18-14.log](https://github.com/Ryujinx/Ryujinx/files/8056194/Ryujinx_1.1.0%2Bcb27bc4_2022-02-13_14-18-14.log)
Spec
ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153766679-b1ddeb0a-cd72-47a9-be47-6902f1e72652.png)
![imagem](https://user-images.githubusercontent.com/90729203/153766713-8ea8b349-a1b3-48d9-ac9b-8a8eba6bb9e8.png)

2022-02-13 17:32 UTC, AlfredoDore commented
Final Fantasy VII
in the FMVs and in the game artifacts appear 
Log file
[Ryujinx_1.1.0+cb27bc4_2022-02-13_14-24-06.log](https://github.com/Ryujinx/Ryujinx/files/8056208/Ryujinx_1.1.0%2Bcb27bc4_2022-02-13_14-24-06.log)
Spec
ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153766972-41b9ab8f-e1a3-4d88-ad78-a45e29470b80.png)
![imagem](https://user-images.githubusercontent.com/90729203/153767063-4fde545a-8624-4307-b79d-c3e8e886f17f.png)

2022-02-14 09:03 UTC, benderscruffy commented
hollow knight still a problem
![ryujinx_capture_2022-02-14_17-00-53](https://user-images.githubusercontent.com/2696404/153832763-616f5862-45e2-4625-ba6e-d0e2d0c96dd8.png)
00:01:55.802 |E| GUI.RenderLoop Gpu DebugReport: Validation Error: [ VUID-vkCmdClearAttachments-aspectMask-02503 ] Object 0: handle = 0x2053db507e0, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0x873171ec | vkCmdClearAttachments() pAttachments[0] aspectMask has VK_IMAGE_ASPECT_STENCIL_BIT but there is no stencil attachment in subpass The Vulkan spec states: If the aspectMask member of any element of pAttachments contains VK_IMAGE_ASPECT_STENCIL_BIT, then the current subpass' depth/stencil attachment must either be VK_ATTACHMENT_UNUSED, or must have a stencil component (https://vulkan.lunarg.com/doc/view/1.2.189.0/windows/1.2-extensions/vkspec.html#VUID-vkCmdClearAttachments-aspectMask-02503)
[Ryujinx_1.1.0+422b73e_2022-02-14_16-59-09.log](https://github.com/Ryujinx/Ryujinx/files/8059315/Ryujinx_1.1.0%2B422b73e_2022-02-14_16-59-09.log)

2022-02-14 12:42 UTC, AlfredoDore commented
Yoshi
is still having serious texture problems and income
Log file
[Ryujinx_1.1.0+422b73e_2022-02-14_09-26-55.log](https://github.com/Ryujinx/Ryujinx/files/8060764/Ryujinx_1.1.0%2B422b73e_2022-02-14_09-26-55.log)
Spec
ryujinx-Release-1.0.0+422b73e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153865862-1186c419-9e88-47a1-a05e-479ccb68432e.png)

2022-02-14 13:00 UTC, AlfredoDore commented
Zelda Link's Awakerning
still have performance issues and these artifacts 
Log file
[Ryujinx_1.1.0+422b73e_2022-02-14_09-53-24.log](https://github.com/Ryujinx/Ryujinx/files/8060885/Ryujinx_1.1.0%2B422b73e_2022-02-14_09-53-24.log)

Spec
ryujinx-Release-1.0.0+422b73e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/153868247-5da092e1-f6dc-47b4-9b45-e0db27f022bf.png)

2022-02-15 02:22 UTC, isaiahboone commented
[Ryujinx_1.1.0+810a7d3_2022-02-14_22-46-33.log](https://github.com/Ryujinx/Ryujinx/files/8065236/Ryujinx_1.1.0%2B810a7d3_2022-02-14_22-46-33.log)
I'm experiencing what appears to be a memory leak when trying to open Pokemon Brilliant Diamond. I can't even make it to the title screen.

Specs
Ryujinx-Release-1.1.0+810a7d3-win_x64
OS: Windows 11
STORAGE: 1TB SSD
CPU: Intel i9-7940x 
RAM: 64gb
GPU: Radeon RX 6800 XT
DRIVER: 22.2.1

2022-02-16 15:21 UTC, AlfredoDore commented
Starlink Battle for Atlas
the game does not start with the update which is essential to continue the game, also without the update the game starts but there are many rendering and video playback problems 
Log file
[Ryujinx_1.1.0+4e062ff_2022-02-16_12-10-47.log](https://github.com/Ryujinx/Ryujinx/files/8081055/Ryujinx_1.1.0%2B4e062ff_2022-02-16_12-10-47.log)
Spec
ryujinx-Release-1.0.0+4e062ff-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/154295654-eadce48c-865e-4190-a800-1b21b553c250.png)

2022-02-16 15:48 UTC, AlfredoDore commented
Yoshi
although the performance has improved, the textures continue to flicker 
Log file
[Ryujinx_1.1.0+4e062ff_2022-02-16_12-34-24.log](https://github.com/Ryujinx/Ryujinx/files/8081272/Ryujinx_1.1.0%2B4e062ff_2022-02-16_12-34-24.log)
Spec
ryujinx-Release-1.0.0+4e062ff-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/154301681-ca67cacd-493d-47bf-885a-f58d78cc1bbf.png)

2022-02-16 16:14 UTC, AlfredoDore commented
Shadow Man
although the performance has improved, the textures continue to flicker
black textures error 
Log file
[Ryujinx_1.1.0+4e062ff_2022-02-16_13-08-43.log](https://github.com/Ryujinx/Ryujinx/files/8081472/Ryujinx_1.1.0%2B4e062ff_2022-02-16_13-08-43.log)
Spec
ryujinx-Release-1.0.0+4e062ff-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/154307358-d2d2ba77-dc2b-4ab8-998e-1e3f29580122.png)
![imagem](https://user-images.githubusercontent.com/90729203/154307610-16900ee6-59dc-461a-9cb4-e0309fe5f9c9.png)

2022-02-16 20:28 UTC, RetroPCYT commented
Game: Mario Kart 8 Deluxe
Description: In certain circuits some textures that go through the character

![mk8d issue 3 jpg](https://user-images.githubusercontent.com/99839803/154351203-51780e44-4549-4325-a7b8-072a2fc7d6ca.jpg)
![mk8d issue 1 jpg](https://user-images.githubusercontent.com/99839803/154351207-64f27fd5-9912-4315-8244-17fa6f9047a1.jpg)
![mk8d issue 2 jpg](https://user-images.githubusercontent.com/99839803/154351210-bf9c8c8c-18bc-4d1c-8404-93cd540adb29.jpg)

Log file
[Ryujinx_1.1.0+cb27bc4_2022-02-14_18-18-37.log](https://github.com/Ryujinx/Ryujinx/files/8083322/Ryujinx_1.1.0%2Bcb27bc4_2022-02-14_18-18-37.log)

Build: ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
GPU: Geforce GTX970
Drivers: 497.00

Saludos!

2022-02-16 20:55 UTC, MutantAura commented
> Game: Mario Kart 8 Deluxe Description: I noticed some glitches on specific tracks where certain textures go through the character, this is most noticeable on the "Toad's Turnpike" and "DK Jungle" tracks. These issues do NOT occur using the OpenGL API.
> 
> ![mk8d issue 3 jpg](https://user-images.githubusercontent.com/99839803/154351203-51780e44-4549-4325-a7b8-072a2fc7d6ca.jpg) ![mk8d issue 1 jpg](https://user-images.githubusercontent.com/99839803/154351207-64f27fd5-9912-4315-8244-17fa6f9047a1.jpg) ![mk8d issue 2 jpg](https://user-images.githubusercontent.com/99839803/154351210-bf9c8c8c-18bc-4d1c-8404-93cd540adb29.jpg)
> 
> Log file [Ryujinx_1.1.0+cb27bc4_2022-02-14_18-18-37.log](https://github.com/Ryujinx/Ryujinx/files/8083322/Ryujinx_1.1.0%2Bcb27bc4_2022-02-14_18-18-37.log)
> 
> Build: ryujinx-Release-1.0.0+cb27bc4-win_x64 OS: Windows 10 GPU: Geforce GTX970 Drivers: 497.00
> 
> Saludos!

I can reproduce this but in future please test on the latest version and using the latest gpu drivers. You're currently outdated in both cases.

2022-02-17 02:38 UTC, Raz-Yagami commented
Game: Shin Megami Tensei V
Issue: On map of Demon king's Castle Drop badly fps Both OS Windows 11 and Linux Garuda

Log Windows: 
[Ryujinx_1.1.0+4e062ff_2022-02-16_17-42-07.log](https://github.com/Ryujinx/Ryujinx/files/8085065/Ryujinx_1.1.0%2B4e062ff_2022-02-16_17-42-07.log)
![SMTV - Demon Kings Castle - Bad render drop fps badly Windows 11 nvidia 51197](https://user-images.githubusercontent.com/98293425/154393005-0e7e57dd-01a7-4dc3-8fa4-f3136b2b895a.jpg)

 Log Linux: 
[Ryujinx_1.1.0+4e062ff_2022-02-16_10-16-30.log](https://github.com/Ryujinx/Ryujinx/files/8085072/Ryujinx_1.1.0%2B4e062ff_2022-02-16_10-16-30.log)
![Captura de pantalla de 2022-02-16 10-18-13](https://user-images.githubusercontent.com/98293425/154393064-fee3e65c-dc52-4bfc-8ef7-47c819e686be.png)

Specs: 
used build:  ryujinx-Release-1.0.0+4e062ff-win_x64 and ryujinx-Release-1.0.0+4e062ff-linux_x64

OS: Windows 11 update today & Garuda Linux Zen 5.16.9
RAM: 16 RAM 3200 mhz
Video: Nvidia GTX 1070 
Driver: win driver 511.79 and Linux driver 510.54
Storage: SSD 5480 GB and 2 HDD back data

2022-02-17 02:43 UTC, Raz-Yagami commented
Game: Xenoblade Chronicle DE on Linux
Issues: Crash when trying to boot the game on Linux; windows edition run fine

Log Linux:
[Ryujinx_1.1.0+4e062ff_2022-02-16_10-12-27.log](https://github.com/Ryujinx/Ryujinx/files/8085124/Ryujinx_1.1.0%2B4e062ff_2022-02-16_10-12-27.log)

Specs:
used build: ryujinx-Release-1.0.0+4e062ff-win_x64 and ryujinx-Release-1.0.0+4e062ff-linux_x64

OS: Windows 11 update today & Garuda Linux Zen 5.16.9
CPU: Ryzen 5 5600x
RAM: 16 RAM 3200 mhz
Video: Nvidia GTX 1070
Driver: win driver 511.79 and Linux driver 510.54
Storage: SSD 5480 GB and 2 HDD back data

2022-02-17 14:53 UTC, AlfredoDore commented
Haven
needs to improve the execution of the video that gives small crashes, also the loading and the performance of the game that despite being fast is unstable, graphically it is like on Switch 
Log file
[Ryujinx_1.1.0+4e062ff_2022-02-17_11-46-21.log](https://github.com/Ryujinx/Ryujinx/files/8089597/Ryujinx_1.1.0%2B4e062ff_2022-02-17_11-46-21.log)
Spec
ryujinx-Release-1.0.0+4e062ff-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/154506751-3384df23-3b07-462c-bcc4-f15fded58321.png)

2022-02-17 16:44 UTC, Raz-Yagami commented
Game: Monster Hunter Stories 2

Issues Window: Crash on loading save game or entering option
[Ryujinx_1.1.0+4e062ff_2022-02-17_07-58-46.log](https://github.com/Ryujinx/Ryujinx/files/8090492/Ryujinx_1.1.0%2B4e062ff_2022-02-17_07-58-46.log)

Issue Linux: Crash loading just the game
[Ryujinx_1.1.0+4e062ff_2022-02-17_00-36-07.log](https://github.com/Ryujinx/Ryujinx/files/8090507/Ryujinx_1.1.0%2B4e062ff_2022-02-17_00-36-07.log)

Specs:
used build: ryujinx-Release-1.0.0+4e062ff-win_x64 and ryujinx-Release-1.0.0+4e062ff-linux_x64

OS: Windows 11 update today & Garuda Linux Zen 5.16.9
CPU: AMD Ryzen 5 5600x
RAM: 16 GB 3200 mhz
Video: Nvidia GTX 1070 8 Gb
Driver: win driver 511.79 and Linux driver 510.54
Storage: SSD 480 GB and 2 HDD backup data

2022-02-19 21:59 UTC, AlfredoDore commented
Crash Trilogy
is still having serious texture problems and income
Log file
[Ryujinx_1.1.0+f569817_2022-02-19_18-48-55.log](https://github.com/Ryujinx/Ryujinx/files/8103064/Ryujinx_1.1.0%2Bf569817_2022-02-19_18-48-55.log)
Spec
ryujinx-Release-1.0.0+cb27bc4-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/154820344-895e0e03-e74a-460f-b94b-085e7a7acfe6.png)
![imagem](https://user-images.githubusercontent.com/90729203/154820471-d9e83a32-8626-4831-abf4-2e28bf055f87.png)

2022-02-19 23:06 UTC, AlfredoDore commented
Starlink
it has several graphical problems and slowness, besides with the update it doesn't start, it just stays in the menu 
Log file
[Ryujinx_1.1.0+f569817_2022-02-19_19-57-21.log](https://github.com/Ryujinx/Ryujinx/files/8103126/Ryujinx_1.1.0%2Bf569817_2022-02-19_19-57-21.log)
Spec
ryujinx-Release-1.0.0+f569817-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.1.2
![imagem](https://user-images.githubusercontent.com/90729203/154822046-192e5486-9b72-496f-8b72-fd52b44ebd0e.png)
![imagem](https://user-images.githubusercontent.com/90729203/154821966-b2240995-a991-47d5-9cf4-017b6489dbd8.png)

2022-02-19 23:12 UTC, AlfredoDore commented
Shadow Man
has black texture errors 
Log file
[Ryujinx_1.1.0+f569817_2022-02-19_20-07-59.log](https://github.com/Ryujinx/Ryujinx/files/8103142/Ryujinx_1.1.0%2Bf569817_2022-02-19_20-07-59.log)
Spec
ryujinx-Release-1.0.0+f569817-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154822154-337cacd9-2b17-44c2-a0c2-0121d2797834.png)
![imagem](https://user-images.githubusercontent.com/90729203/154822173-a657335b-2699-4c76-a5d9-d402133fb800.png)

2022-02-19 23:53 UTC, AlfredoDore commented
Shadow Man
has black texture errors
Log file
[Ryujinx_1.1.0+943c5a6_2022-02-19_20-49-49.log](https://github.com/Ryujinx/Ryujinx/files/8103186/Ryujinx_1.1.0%2B943c5a6_2022-02-19_20-49-49.log)
Spec
ryujinx-Release-1.0.0+943c5a6-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154822998-ca464a71-09cb-4986-9e2c-a7f9c63f4eea.png)
![imagem](https://user-images.githubusercontent.com/90729203/154823023-d9e2591e-e5ae-4eb9-9619-178dc78ac450.png)

2022-02-20 00:00 UTC, AlfredoDore commented
Crash Trilogy
textures are still having aspect ratio issues 
Log file
[Ryujinx_1.1.0+943c5a6_2022-02-19_20-53-44.log](https://github.com/Ryujinx/Ryujinx/files/8103199/Ryujinx_1.1.0%2B943c5a6_2022-02-19_20-53-44.log)
Spec
ryujinx-Release-1.0.0+943c5a6-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154823111-f627d8bb-184d-4224-a79b-647b4f97e550.png)
![imagem](https://user-images.githubusercontent.com/90729203/154823147-1f40cfcd-5c64-46b0-a128-64b346d7ae49.png)

2022-02-20 00:13 UTC, Raz-Yagami commented
Sorry its just one version back but it take me time to test all in build on both OS: 
Used build: ryujinx-Release-1.0.0+f569817-linux_x64 and ryujinx-Release-1.0.0+f569817-win_x64

Game: Shin Megami Tensei V
Issue win and linux: fog of maps "Demon King's Castle· its the main drop rest improved
Log win:
[Ryujinx_1.1.0+f569817_2022-02-19_14-40-23.log](https://github.com/Ryujinx/Ryujinx/files/8103184/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-40-23.log)

![SMTV fog issue but improved render](https://user-images.githubusercontent.com/98293425/154823014-ab9ec64b-206d-4389-aee9-a36b96d913d2.jpg)
log linux:
[Ryujinx_1.1.0+f569817_2022-02-19_07-12-35.log](https://github.com/Ryujinx/Ryujinx/files/8103187/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-12-35.log)

![Captura de pantalla de 2022-02-19 07-14-24](https://user-images.githubusercontent.com/98293425/154823068-722518fb-0128-43f2-b5a1-d118ec80bc36.png)
 
Game: The Legend of Zelda Breath of the Wild
Issue Linux: Physic random error ambient where should not to be
log linux;
[Ryujinx_1.1.0+f569817_2022-02-19_07-36-59.log](https://github.com/Ryujinx/Ryujinx/files/8103195/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-36-59.log)


![Captura de pantalla de 2022-02-19 07-42-40](https://user-images.githubusercontent.com/98293425/154823134-4b42545a-176d-4177-8572-f68f4ed005aa.png)

Game: Xenoblade Chronicle DE
Issue Linux: Still crash loading game on linux
log linux:
[Ryujinx_1.1.0+f569817_2022-02-19_07-46-20.log](https://github.com/Ryujinx/Ryujinx/files/8103198/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-46-20.log)

Game: Monster Hunter Stories 2
Issue windows: get in game but freeze image but game still run internally normal
log windows:
[Ryujinx_1.1.0+f569817_2022-02-19_14-48-13.log](https://github.com/Ryujinx/Ryujinx/files/8103204/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-48-13.log)

log linux:
[Ryujinx_1.1.0+f569817_2022-02-19_07-18-35.log](https://github.com/Ryujinx/Ryujinx/files/8103206/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-18-35.log)

Game: Crash Team Racing Nitro Fuel
Issue both OS:
log win:
[Ryujinx_1.1.0+f569817_2022-02-19_14-52-55.log](https://github.com/Ryujinx/Ryujinx/files/8103211/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-52-55.log)


log linux:
[Ryujinx_1.1.0+f569817_2022-02-19_07-22-38.log](https://github.com/Ryujinx/Ryujinx/files/8103209/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-22-38.log)

wrong:
![Crash TRNF effect not correctly displayed eviroment](https://user-images.githubusercontent.com/98293425/154823319-01736f5e-959a-4009-b8a0-7dc9efe7abf1.jpg)

Correct from original console:
![envyroment reflection ambient effect](https://user-images.githubusercontent.com/98293425/154823333-37830318-642b-443b-a1b9-03edc3dac1ce.png)

Game: Blue Reflection Second Light
Issue 20 fps cap both OS
Log Win:
[Ryujinx_1.1.0+f569817_2022-02-19_14-58-15.log](https://github.com/Ryujinx/Ryujinx/files/8103213/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-58-15.log)
![BR SL 20 fps cap](https://user-images.githubusercontent.com/98293425/154823373-93d78654-683a-486d-8172-854ff1ccce5c.jpg)

Log Linux:
[Ryujinx_1.1.0+f569817_2022-02-19_07-20-20.log](https://github.com/Ryujinx/Ryujinx/files/8103215/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-20-20.log)
![Captura de pantalla de 2022-02-19 07-21-47](https://user-images.githubusercontent.com/98293425/154823391-59851c05-3394-4a1d-a382-1323df37d81c.png)

Specs: Build used 
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200mhz
GPU: Nvidia GTX 1070
Drivers: 511.79 windows and 510.54 linux
Storage: SSD 480GB and 2 HDD

2022-02-20 00:20 UTC, AlfredoDore commented
Haven
graphically without problems and it's faster, but it has a lot of oscillation 
Log file
[Ryujinx_1.1.0+943c5a6_2022-02-19_21-06-57.log](https://github.com/Ryujinx/Ryujinx/files/8103229/Ryujinx_1.1.0%2B943c5a6_2022-02-19_21-06-57.log)
Spec
ryujinx-Release-1.0.0+943c5a6-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154823554-8c5ed8d9-0990-4a98-bec5-070755e59c5e.png)

2022-02-20 00:22 UTC, AlfredoDore commented
> Sorry its just one version back but it take me time to test all in build on both OS: Used build: ryujinx-Release-1.0.0+f569817-linux_x64 and ryujinx-Release-1.0.0+f569817-win_x64
> 
> Game: Shin Megami Tensei V Issue win and linux: fog of maps "Demon King's Castle" its the main drop the rest improved Log win: [Ryujinx_1.1.0+f569817_2022-02-19_14-40-23.log](https://github.com/Ryujinx/Ryujinx/files/8103184/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-40-23.log)
> 
> ![SMTV fog issue but improved render](https://user-images.githubusercontent.com/98293425/154823014-ab9ec64b-206d-4389-aee9-a36b96d913d2.jpg) log linux: [Ryujinx_1.1.0+f569817_2022-02-19_07-12-35.log](https://github.com/Ryujinx/Ryujinx/files/8103187/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-12-35.log)
> 
> ![Captura de pantalla de 2022-02-19 07-14-24](https://user-images.githubusercontent.com/98293425/154823068-722518fb-0128-43f2-b5a1-d118ec80bc36.png)
> 
> Game: The Legend of Zelda Breath of the Wild Issue Linux: Physic random error ambient where should not to be log linux; [Ryujinx_1.1.0+f569817_2022-02-19_07-36-59.log](https://github.com/Ryujinx/Ryujinx/files/8103195/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-36-59.log)
> 
> ![Captura de pantalla de 2022-02-19 07-42-40](https://user-images.githubusercontent.com/98293425/154823134-4b42545a-176d-4177-8572-f68f4ed005aa.png)
> 
> Game: Xenoblade Chronicle DE Issue Linux: Still crash loading game on linux log linux: [Ryujinx_1.1.0+f569817_2022-02-19_07-46-20.log](https://github.com/Ryujinx/Ryujinx/files/8103198/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-46-20.log)
> 
> Game: Monster Hunter Stories 2 Issue windows: get in game but freeze image but game still run internally normal log windows: [Ryujinx_1.1.0+f569817_2022-02-19_14-48-13.log](https://github.com/Ryujinx/Ryujinx/files/8103204/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-48-13.log)
> 
> log linux: it freeze ingame [Ryujinx_1.1.0+f569817_2022-02-19_07-18-35.log](https://github.com/Ryujinx/Ryujinx/files/8103206/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-18-35.log)
> 
> Game: Crash Team Racing Nitro Fuel Issue both OS: log win: [Ryujinx_1.1.0+f569817_2022-02-19_14-52-55.log](https://github.com/Ryujinx/Ryujinx/files/8103211/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-52-55.log)
> 
> log linux: [Ryujinx_1.1.0+f569817_2022-02-19_07-22-38.log](https://github.com/Ryujinx/Ryujinx/files/8103209/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-22-38.log)
> 
> wrong: ![Crash TRNF effect not correctly displayed eviroment](https://user-images.githubusercontent.com/98293425/154823319-01736f5e-959a-4009-b8a0-7dc9efe7abf1.jpg)
> 
> Correct from original console: ![envyroment reflection ambient effect](https://user-images.githubusercontent.com/98293425/154823333-37830318-642b-443b-a1b9-03edc3dac1ce.png)
> 
> Game: Blue Reflection Second Light Issue 20 fps cap both OS Log Win: [Ryujinx_1.1.0+f569817_2022-02-19_14-58-15.log](https://github.com/Ryujinx/Ryujinx/files/8103213/Ryujinx_1.1.0%2Bf569817_2022-02-19_14-58-15.log) ![BR SL 20 fps cap](https://user-images.githubusercontent.com/98293425/154823373-93d78654-683a-486d-8172-854ff1ccce5c.jpg)
> 
> Log Linux: [Ryujinx_1.1.0+f569817_2022-02-19_07-20-20.log](https://github.com/Ryujinx/Ryujinx/files/8103215/Ryujinx_1.1.0%2Bf569817_2022-02-19_07-20-20.log) ![Captura de pantalla de 2022-02-19 07-21-47](https://user-images.githubusercontent.com/98293425/154823391-59851c05-3394-4a1d-a382-1323df37d81c.png)
> 
> Specs: Build used OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10 CPU: AMD Ryzen 5 5600x RAM: 16 Gb 3200mhz GPU: Nvidia GTX 1070 Drivers: 511.79 windows and 510.54 linux Storage: SSD 480GB and 2 HDD

use the newest version, the 943c5a6

2022-02-20 00:40 UTC, Raz-Yagami commented
Used Build: ryujinx-Release-1.0.0+943c5a6-win_x64
Game : Shin Megami Tensei V
Issue: Map Demon King's Castle Fog effect main problem of drops the rest improvement
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_16-21-07.log](https://github.com/Ryujinx/Ryujinx/files/8103243/Ryujinx_1.1.0%2B943c5a6_2022-02-19_16-21-07.log)
![SMTV fog issue but improved render](https://user-images.githubusercontent.com/98293425/154823931-ac238bfb-ed6c-41c1-9c33-cd25287e37f7.jpg)

PC specs:
OS: Windows 11 21H2 updated
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhx
GPU: Nvidia GTX 1070
Driver: Win 511.79
Storage: 480 GB and 2 HDD

2022-02-20 00:46 UTC, Raz-Yagami commented
Game: Monster Hunter Stories 2
Issue: Freeze in game walking there
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_16-41-56.log](https://github.com/Ryujinx/Ryujinx/files/8103249/Ryujinx_1.1.0%2B943c5a6_2022-02-19_16-41-56.log)
![MHS 2 freeze image in-game but still running move and music](https://user-images.githubusercontent.com/98293425/154824046-bae730d3-bffc-4c68-9bb9-dc9dcee96fd2.jpg)

PC specs:
OS: Windows 11 21H2 updated
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhx
GPU: Nvidia GTX 1070
Driver: Win 511.79
Storage: SSD 480 GB and 2 HDD

2022-02-20 00:47 UTC, AlfredoDore commented
Starlink
with the update the game does not go beyond the menu and without it the game works, only it has several graphics problems and video slowness, however without the update it is impossible to continue in the game 
Log file
[Ryujinx_1.1.0+943c5a6_2022-02-19_21-41-40.log](https://github.com/Ryujinx/Ryujinx/files/8103250/Ryujinx_1.1.0%2B943c5a6_2022-02-19_21-41-40.log)
Spec
ryujinx-Release-1.0.0+943c5a6-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154824021-160f1689-7bcb-4b57-a648-895ed759647f.png)
![imagem](https://user-images.githubusercontent.com/90729203/154824037-3b80c82f-44d9-4f81-a41f-523cbd98f70d.png)

2022-02-20 00:52 UTC, Raz-Yagami commented
Game: Blue Reflection Second light
Issue: 20 fps cap
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_16-48-38.log](https://github.com/Ryujinx/Ryujinx/files/8103256/Ryujinx_1.1.0%2B943c5a6_2022-02-19_16-48-38.log)
![BR SL 20 fps cap](https://user-images.githubusercontent.com/98293425/154824170-8a1a970a-ad73-43a0-9da3-e606aa6eaa5f.jpg)

PC specs:
OS: Windows 11 21H2 updated
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhx
GPU: Nvidia GTX 1070
Driver: Win 511.79
Storage: SSD 480 GB and 2 HDD

2022-02-20 01:02 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: Xenoblade Chronicles DE
Issue: Crash loading the game
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_09-00-52.log](https://github.com/Ryujinx/Ryujinx/files/8103272/Ryujinx_1.1.0%2B943c5a6_2022-02-19_09-00-52.log)
![Captura de pantalla de 2022-02-19 09-00-59](https://user-images.githubusercontent.com/98293425/154824368-5e7ef8f2-b23b-45a5-9b02-00345ec53e38.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda linux Zen 5.16.10
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 01:07 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: Shin Megami Tensei V
Issue linux: On Map Demon King's Castle fog its main issue of drops fps the rest improvement
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_09-02-53.log](https://github.com/Ryujinx/Ryujinx/files/8103280/Ryujinx_1.1.0%2B943c5a6_2022-02-19_09-02-53.log)
![Captura de pantalla de 2022-02-19 09-05-06](https://user-images.githubusercontent.com/98293425/154824469-2bf1c34d-c05f-4269-99f6-e7d38311c39d.png)


PC specs:
OS: Windows 11 21H2 updated and Garuda linux Zen 5.16.10
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 01:12 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: Blue Reflection Second Light
Issue: 20 fps cap
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_09-08-05.log](https://github.com/Ryujinx/Ryujinx/files/8103281/Ryujinx_1.1.0%2B943c5a
![Captura de pantalla de 2022-02-19 09-09-54](https://user-images.githubusercontent.com/98293425/154824525-3cebbf9e-ef15-4519-8b3e-ea4c4f702501.png)
6_2022-02-19_09-08-05.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda linux Zen 5.16.10
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 01:16 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: The Legend of Zelda Breath of the Wild
Issue: Crash in-game
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_09-12-44.log](https://github.com/Ryujinx/Ryujinx/files/8103286/Ryujinx_1.1.0%2B943c5a6_2022-02-19_09-12-44.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda linux Zen 5.16.10
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 01:24 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: Xenoblade Chronicle 2

Issue: freeze in-game after 4-5 minutes or changing maps
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_09-17-05.log](https://github.com/Ryujinx/Ryujinx/files/8103290/Ryujinx_1.1.0%2B943c5a6_2022-02-19_09-17-05.log)
![Captura de pantalla de 2022-02-19 09-21-36](https://user-images.githubusercontent.com/98293425/154824732-cff65c13-2b7b-4d50-a4f2-f28ed7dca005.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda linux Zen 5.16.10
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 01:40 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: Crash Team Racing Nitro Fuel
Issue: Effect of environment not correctly displayed
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_09-31-15.log](https://github.com/Ryujinx/Ryujinx/files/8103308/Ryujinx_1.1.0%2B943c5a6_2022-02-19_09-31-15.log)
wrong:
![Captura de pantalla de 2022-02-19 09-34-24](https://user-images.githubusercontent.com/98293425/154825023-08a0c12f-8ae4-48fc-ae66-4791f218e8e2.png)

Correctly of console effect:
![envyroment reflection ambient effect](https://user-images.githubusercontent.com/98293425/154825030-a0309d1b-d08f-491a-be74-c542fe1ec107.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda linux Zen 5.16.10
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 01:50 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: The Legend of Zelda Link's Awakening
Issue: render drops fps
log:
[Ryujinx_1.1.0+943c5a6_2022-02-19_09-40-58.log](https://github.com/Ryujinx/Ryujinx/files/8103321/Ryujinx_1.1.0%2B943c5a6_2022-02-19_09-40-58.log)
![Captura de pantalla de 2022-02-19 09-43-17](https://user-images.githubusercontent.com/98293425/154825262-1276b713-5443-4948-b7be-f92ee46dfdca.png)
![Captura de pantalla de 2022-02-19 09-45-44](https://user-images.githubusercontent.com/98293425/154825268-95dc4419-f12d-4c22-9816-65dae907a503.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5660x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 06:30 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: Monster Hunter Stories 2
Issues: Crash Loading the game
log linux:
[Ryujinx_1.1.0+943c5a6_2022-02-19_14-28-46.log](https://github.com/Ryujinx/Ryujinx/files/8103513/Ryujinx_1.1.0%2B943c5a6_2022-02-19_14-28-46.log)

![Captura de pantalla de 2022-02-19 14-29-11](https://user-images.githubusercontent.com/98293425/154831481-1cea49e0-154b-4b60-a440-a27a2577fe75.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 06:45 UTC, Raz-Yagami commented
Build used : ryujinx-Release-1.0.0+943c5a6-linux_x64.zip
Game: Bayonetta 2
Issue: Freeze in-game after certain time mostly 3-5 minutes
[Ryujinx_1.1.0+943c5a6_2022-02-19_14-36-50.log](https://github.com/Ryujinx/Ryujinx/files/8103528/Ryujinx_1.1.0%2B943c5a6_2022-02-19_14-36-50.log)
![Captura de pantalla de 2022-02-19 14-42-54](https://user-images.githubusercontent.com/98293425/154831815-b497cea2-bd7d-4a58-b14f-68288d080275.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 12:48 UTC, AlfredoDore commented
Zelda Link's Awakerning
has yield losses and has artifacts in the water 
Log file
[Ryujinx_1.1.0+943c5a6_2022-02-20_09-36-43.log](https://github.com/Ryujinx/Ryujinx/files/8103984/Ryujinx_1.1.0%2B943c5a6_2022-02-20_09-36-43.log)
Spec
ryujinx-Release-1.0.0+943c5a6-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154842839-f81bb2a8-f9d0-4f5f-8d73-30286202388d.png)
![imagem](https://user-images.githubusercontent.com/90729203/154842981-67d0d5e4-600b-4a42-888d-a3c5a8bc96cf.png)
![imagem](https://user-images.githubusercontent.com/90729203/154843185-86133619-bd83-4d2c-99b8-a56ed53d8a00.png)

2022-02-20 17:41 UTC, AlfredoDore commented
Shadow Man
black textures error
Log file
[Ryujinx_1.1.0+e0cc822_2022-02-20_14-36-38.log](https://github.com/Ryujinx/Ryujinx/files/8104549/Ryujinx_1.1.0%2Be0cc822_2022-02-20_14-36-38.log)
ryujinx-Release-1.0.0+e0cc822-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154856098-6f0cfc51-b390-4691-8c4c-25cffcca77b1.png)
![imagem](https://user-images.githubusercontent.com/90729203/154856146-a93b7490-0cff-481a-a17a-b7f1d5bf6697.png)
![imagem](https://user-images.githubusercontent.com/90729203/154856180-8c9b799a-84ce-4a6e-9820-b6d8d22ecf9a.png)

2022-02-20 17:41 UTC, Raz-Yagami commented
Game: Monster hunter Stories 2
Build used: ryujinx-Release-1.0.0+e0cc822-win_x64
Issues: Freeze on same point and spawn of error audio log

log win:
[Ryujinx_1.1.0+e0cc822_2022-02-20_09-32-52.log](https://github.com/Ryujinx/Ryujinx/files/8104536/Ryujinx_1.1.0%2Be0cc822_2022-02-20_09-32-52.log)
![MHS 2 freeze image in-game but still running move and music](https://user-images.githubusercontent.com/98293425/154856110-7dd651cf-ee64-4ab1-9561-623148fc2ecf.jpg)
![MHS 2 freeze image but music still going normaly](https://user-images.githubusercontent.com/98293425/154856128-bc415553-06da-4621-acb9-ec97543e9a1e.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 17:47 UTC, AlfredoDore commented
Zelda Link's Awakerning
has yield losses and has artifacts in the water
Log file
[Ryujinx_1.1.0+e0cc822_2022-02-20_14-41-49.log](https://github.com/Ryujinx/Ryujinx/files/8104570/Ryujinx_1.1.0%2Be0cc822_2022-02-20_14-41-49.log)
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154856338-e64624da-0822-4378-b0f5-c8adc19e4071.png)

2022-02-20 17:53 UTC, AlfredoDore commented
Crash
textures are still having aspect ratio issues
Log file
[Ryujinx_1.1.0+e0cc822_2022-02-20_14-48-53.log](https://github.com/Ryujinx/Ryujinx/files/8104592/Ryujinx_1.1.0%2Be0cc822_2022-02-20_14-48-53.log)
ryujinx-Release-1.0.0+e0cc822-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154856542-2fb86301-7977-44c3-a599-fd96488a72e9.png)
![imagem](https://user-images.githubusercontent.com/90729203/154856608-f5a7e524-1a34-40e8-8822-7a7d8a6a51f0.png)

2022-02-20 22:36 UTC, Raz-Yagami commented
Game: Monster hunter Stories 2
build used: ryujinx-Release-1.0.0+c9eaf19-win_x64
Issues: Freeze in-game walking that direction and audio spam failed log
log:
[Ryujinx_1.1.0+c9eaf19_2022-02-20_14-28-36.log](https://github.com/Ryujinx/Ryujinx/files/8105064/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_14-28-36.log)
![MHS 2 freeze image but music still going normaly](https://user-images.githubusercontent.com/98293425/154867395-334e1114-4233-4e3e-b05b-c05b22c57f63.jpg)
![MHS 2 freeze image in-game but still running move and music](https://user-images.githubusercontent.com/98293425/154867398-de318c36-5fa3-44a7-b5d8-6fda51fa6e96.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 22:57 UTC, Raz-Yagami commented
Game: Blue Reflection Second Light
build used: ryujinx-Release-1.0.0+c9eaf19-win_x64
Issues: 20 fps cap and log GPU processing is to slow
log:
[Ryujinx_1.1.0+c9eaf19_2022-02-20_14-50-45.log](https://github.com/Ryujinx/Ryujinx/files/8105108/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_14-50-45.log)
![BR SL 20 fps cap GPU process is to slow log](https://user-images.githubusercontent.com/98293425/154868090-aefde697-51f9-481d-a161-f9cac50b5834.jpg)
![BR SL 20 fps cap](https://user-images.githubusercontent.com/98293425/154868095-1749f5e8-7d84-44c9-8b16-03bddf339780.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 23:00 UTC, AlfredoDore commented
Starlink
in addition to the various graphical problems and the FMVs that run very slow, the update that is essential doesn't work, it stays in the menu 
Log file
[Ryujinx_1.1.0+c9eaf19_2022-02-20_19-52-11.log](https://github.com/Ryujinx/Ryujinx/files/8105120/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_19-52-11.log)
ryujinx-Release-1.0.0+c9eaf19-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154868002-aa67a261-076a-4bb4-8798-6ba9bca3d954.png)

2022-02-20 23:06 UTC, Raz-Yagami commented
Game: The Legend of Zelda Link's Awakening
Build used : ryujinx-Release-1.0.0+c9eaf19-win_x64
Issues: Render drop fps and log cause GPU process is to slow
log:
[Ryujinx_1.1.0+c9eaf19_2022-02-20_14-57-52.log](https://github.com/Ryujinx/Ryujinx/files/8105128/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_14-57-52.log)
![zelda awakening GPU process is to slow](https://user-images.githubusercontent.com/98293425/154868309-21f4af8a-bdc1-4bc1-8dd1-76f234be6a4d.jpg)
![zelda awakening slowdown fps some time drop to 20](https://user-images.githubusercontent.com/98293425/154868317-cd32138e-fde3-4ff6-b9af-4d642c5b4d57.jpg)

Warning: MSI Afterburn don't detect vulkan process to pop-up on screen

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-20 23:29 UTC, AlfredoDore commented
Shadow Man
black textures error
Log file
[Ryujinx_1.1.0+c9eaf19_2022-02-20_20-10-07.log](https://github.com/Ryujinx/Ryujinx/files/8105156/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_20-10-07.log)
ryujinx-Release-1.0.0+c9eaf19-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
Switch
![imagem](https://user-images.githubusercontent.com/90729203/154868926-a0685ff6-40ac-4884-8dad-3cb5e259acd1.png)
![imagem](https://user-images.githubusercontent.com/90729203/154868959-cf4ea76d-f357-4466-af26-a9faa3272296.png)
N64
![imagem](https://user-images.githubusercontent.com/90729203/154869112-8b1990cc-80a4-4597-a9c1-975250b9baf5.png)
![imagem](https://user-images.githubusercontent.com/90729203/154869145-152ed3e0-40ba-4939-99a3-ddc97e34ba47.png)

2022-02-20 23:36 UTC, CrusadingNinja commented
> Shadow Man black textures error Log file [Ryujinx_1.1.0+c9eaf19_2022-02-20_20-10-07.log](https://github.com/Ryujinx/Ryujinx/files/8105156/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_20-10-07.log) ryujinx-Release-1.0.0+c9eaf19-win_x64 OS: Windows 10 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.2.2 Switch ![imagem](https://user-images.githubusercontent.com/90729203/154868926-a0685ff6-40ac-4884-8dad-3cb5e259acd1.png) ![imagem](https://user-images.githubusercontent.com/90729203/154868959-cf4ea76d-f357-4466-af26-a9faa3272296.png) N64 ![imagem](https://user-images.githubusercontent.com/90729203/154869112-8b1990cc-80a4-4597-a9c1-975250b9baf5.png) ![imagem](https://user-images.githubusercontent.com/90729203/154869145-152ed3e0-40ba-4939-99a3-ddc97e34ba47.png)

What is the point of the Project64 screenshots here?

2022-02-20 23:46 UTC, AlfredoDore commented
> What is the point of the Project64 screenshots here?

to get an idea of what the game is like when it runs well

2022-02-20 23:48 UTC, riperiperi commented
I have a feeling that Shadow Man Remastered on Nintendo Switch isn't running using an N64 RDP graphics backend.

2022-02-20 23:49 UTC, Squall-Leonhart commented
> Warning: MSI Afterburn don't detect vulkan process to pop-up on screen and Bayonetta 2 work flaweless on Linux to.

RTSS hooking the vulkan renderer requires you leaving the render window totally alone until emulated video appears.

2022-02-20 23:49 UTC, AlfredoDore commented
> 

I said have an idea, not equal  hahahahaha

2022-02-20 23:51 UTC, CrusadingNinja commented
> > What is the point of the Project64 screenshots here?
> 
> to get an idea of what the game is like when it runs well

Then if you want to convey that idea, screenshots from a switch should be used as comparison, not screenshots from an emulator of a completely different system.

2022-02-21 00:21 UTC, Raz-Yagami commented
Game: Xenoblade Chronicle DE
Build used : ryujinx-Release-1.0.0+c9eaf19-linux_x64
Issue: Crash loading game, windows edition work fine
Log:
[Ryujinx_1.1.0+c9eaf19_2022-02-20_08-16-52.log](https://github.com/Ryujinx/Ryujinx/files/8105262/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_08-16-52.log)


PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-21 00:31 UTC, Raz-Yagami commented
Game: Xenoblade Chronicle 2
Build used : ryujinx-Release-1.0.0+c9eaf19-linux_x64
Issue: To many re-run but can't load game stuck, Windows edition work fine
Log:
[Ryujinx_1.1.0+c9eaf19_2022-02-20_08-25-57.log](https://github.com/Ryujinx/Ryujinx/files/8105286/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_08-25-57.log)
![Captura de pantalla de 2022-02-20 08-27-09](https://user-images.githubusercontent.com/98293425/154871548-6048b494-ccab-42a9-b2df-1b13c0161ac5.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-21 00:32 UTC, AlfredoDore commented
> Game: Xenoblade Chronicle 2 Build used : ryujinx-Release-1.0.0+c9eaf19-linux_x64 Issue: To many re-run but can't load game stuck, Windows edition work fine Log: [Ryujinx_1.1.0+c9eaf19_2022-02-20_08-25-57.log](https://github.com/Ryujinx/Ryujinx/files/8105286/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_08-25-57.log) ![Captura de pantalla de 2022-02-20 08-27-09](https://user-images.githubusercontent.com/98293425/154871548-6048b494-ccab-42a9-b2df-1b13c0161ac5.png)
> 
> PC specs: OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10 CPU: AMD Ryzen 5 5600x RAM: 16 Gb 3200 mhz GPU: Nvidia GTX 1070 Driver: Win 511.79 | Linux 510.54 Storage: SSD 480 GB and 2 HDD

is windows 11 good for emulation? I saw that who is an AMD user loses income

2022-02-21 00:37 UTC, Raz-Yagami commented
Game: Monster Hunter Stories 2
Build used : ryujinx-Release-1.0.0+c9eaf19-linux_x64
Issues: Have the same problem of windows edition freeze going that side
Log:
[Ryujinx_1.1.0+c9eaf19_2022-02-20_08-32-32.log](https://github.com/Ryujinx/Ryujinx/files/8105299/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_08-32-32.log)
![Captura de pantalla de 2022-02-20 08-34-16](https://user-images.githubusercontent.com/98293425/154871892-3c00b86b-7878-4a05-b41e-b99b96de7e93.png)

*** That its all test for today ***

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-21 00:38 UTC, AlfredoDore commented
Crash
texture errors and now there was an improvement in its performance, but it still needs to improve stability  
Log file
[Ryujinx_1.1.0+c9eaf19_2022-02-20_21-30-59.log](https://github.com/Ryujinx/Ryujinx/files/8105303/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_21-30-59.log)
ryujinx-Release-1.0.0+c9eaf19-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154871752-7a5801c8-811d-43cc-9d5d-9343dd9239d4.png)
![imagem](https://user-images.githubusercontent.com/90729203/154871857-67fa72c5-42a1-4ac1-ad81-37b620730255.png)

2022-02-21 00:46 UTC, Raz-Yagami commented
> Just use most updated driver for windows 11 and your are cover I speak spanish find me on yt testing Garuda linux vs windows 11; I love both OS and Fantasy Tavern work better on linux Ryujinx less latency.

2022-02-21 00:47 UTC, Raz-Yagami commented
> > Game: Xenoblade Chronicle 2 Build used : ryujinx-Release-1.0.0+c9eaf19-linux_x64 Issue: To many re-run but can't load game stuck, Windows edition work fine Log: [Ryujinx_1.1.0+c9eaf19_2022-02-20_08-25-57.log](https://github.com/Ryujinx/Ryujinx/files/8105286/Ryujinx_1.1.0%2Bc9eaf19_2022-02-20_08-25-57.log) ![Captura de pantalla de 2022-02-20 08-27-09](https://user-images.githubusercontent.com/98293425/154871548-6048b494-ccab-42a9-b2df-1b13c0161ac5.png)
> > PC specs: OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.10 CPU: AMD Ryzen 5 5600x RAM: 16 Gb 3200 mhz GPU: Nvidia GTX 1070 Driver: Win 511.79 | Linux 510.54 Storage: SSD 480 GB and 2 HDD
> 
> is windows 11 good for emulation? I saw that who is an AMD user loses income

> Just use most updated driver for windows 11 and your are cover I speak spanish find me on yt testing Garuda linux vs windows 11; I love both OS and Fantasy Tavern work better on linux Ryujinx less latency.

2022-02-21 13:37 UTC, AlfredoDore commented
Final Fantasy VII
screen artifacts during FMVs and certain parts of the game 
Log file
[Ryujinx_1.1.0+c9eaf19_2022-02-21_10-30-25.log](https://github.com/Ryujinx/Ryujinx/files/8109571/Ryujinx_1.1.0%2Bc9eaf19_2022-02-21_10-30-25.log)
ryujinx-Release-1.0.0+c9eaf19-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154965495-546a7bb0-2dc6-4cb8-b727-c5dba94c74e3.png)

2022-02-21 15:20 UTC, AlfredoDore commented
Yoshi
in addition to the textures blinking, when reaching this stage it simply gets stuck on loading 
Log file
[Ryujinx_1.1.0+c9eaf19_2022-02-21_12-14-51.log](https://github.com/Ryujinx/Ryujinx/files/8110338/Ryujinx_1.1.0%2Bc9eaf19_2022-02-21_12-14-51.log)
ryujinx-Release-1.0.0+c9eaf19-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/154983192-64c2bf2e-744a-4fee-a5f9-d5a485894515.png)

2022-02-22 09:13 UTC, lurkingaround commented
Mononoke Slashdown - 0100F3A00FB78000
Crashes with error when selecting new game to play, otherwise running perfectly as far as I can tell.
[Ryujinx_1.1.0+c9eaf19_2022-02-22_19-50-30.log](https://github.com/Ryujinx/Ryujinx/files/8115220/Ryujinx_1.1.0%2Bc9eaf19_2022-02-22_19-50-30.log)

Windows 10
AMD Ryzen 5 4500U 6C/6T 2.3GHz
16GB 4266MHz LPDDR4

2022-02-22 09:34 UTC, benderscruffy commented
Axiom Verge - 0100052004384000
flashing and glitchy graphics during the intro and gameplay
![ryujinx_capture_2022-02-22_17-13-07](https://user-images.githubusercontent.com/2696404/155103999-da7d35f9-0c1f-4c83-92c3-8568771c9cab.png)
![ryujinx_capture_2022-02-22_17-13-45](https://user-images.githubusercontent.com/2696404/155104009-ad3b38b3-29b8-44e9-9c2e-a66f0718efff.png)

2022-02-23 08:27 UTC, benderscruffy commented
> Monster Blast after you choose your level it crashes out the emulator ![ryujinx_capture_2022-02-05_12-12-17](https://user-images.githubusercontent.com/2696404/152628228-e4130512-8212-4188-bf41-a9167180681d.png) [Ryujinx_1.1.0+8c7ad0f_2022-02-05_12-09-42.log](https://github.com/Ryujinx/Ryujinx/files/8007355/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_12-09-42.log)
> 
> 00:02:17.676 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x4913A (sRGB: False). 00:02:17.846 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: The specified GPU virtual memory range 0x113C6F000..0x114C6F000 is not fully mapped. at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetPhysicalRegions(UInt64 va, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Memory\MemoryManager.cs:line 376 at Ryujinx.Graphics.Gpu.Image.TextureCache.FindOrCreateTexture(MemoryManager memoryManager, TextureSearchFlags flags, TextureInfo info, Int32 layerSize, Nullable`1 sizeHint, Nullable`1 range) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureCache.cs:line 485 at Ryujinx.Graphics.Gpu.Image.TexturePool.Get(Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 64 at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitTextureBindings(TexturePool pool, ShaderStage stage, Int32 stageIndex) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 416 at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 345 at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.CommitBindings() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\StateUpdater.cs:line 239 at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 130 at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 224 at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 128 at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 188 at Ryujinx.Ui.RendererWidgetBase.b__65_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 396 at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 100

still crashes out with the same error

2022-02-23 08:37 UTC, benderscruffy commented
> Book of Demons graphics are all messed up [Ryujinx_1.1.0+bc9344e_2022-01-28_14-17-05.log](https://github.com/Ryujinx/Ryujinx/files/7956251/Ryujinx_1.1.0%2Bbc9344e_2022-01-28_14-17-05.log) ![ryujinx_capture_2022-01-28_14-20-44](https://user-images.githubusercontent.com/2696404/151497812-8cc2bda8-9bbb-4e72-aefd-3635f026e3f7.png) ![ryujinx_capture_2022-01-28_14-21-03](https://user-images.githubusercontent.com/2696404/151497847-3c94040d-7729-420c-a192-219e29c0e7b2.png) ![ryujinx_capture_2022-01-28_14-21-26](https://user-images.githubusercontent.com/2696404/151497882-2816aee4-c3d5-46ad-91ad-4e671a4fe98a.png)

still a problem with the graphics but they are getting better
![ryujinx_capture_2022-02-23_16-36-13](https://user-images.githubusercontent.com/2696404/155285142-047df86f-0b81-4f5b-8ce5-ebfe35bee4e1.png)

2022-02-23 08:56 UTC, benderscruffy commented
> Rush Rally Origins missing lots of graphics ![ryujinx_capture_2022-02-05_11-59-35](https://user-images.githubusercontent.com/2696404/152627970-4f59af38-1a0c-439c-945d-04f0726bb0eb.png) keeps spamming 00:04:06.514 |E| GUI.RenderLoop Gpu ConvertToVkFormat: Format Etc2RgbUnorm is not supported by the host. [Ryujinx_1.1.0+8c7ad0f_2022-02-05_11-55-26.log](https://github.com/Ryujinx/Ryujinx/files/8007337/Ryujinx_1.1.0%2B8c7ad0f_2022-02-05_11-55-26.log)

still has the graphic glitches 
and keeps spamming the error
![ryujinx_capture_2022-02-23_16-55-31](https://user-images.githubusercontent.com/2696404/155287697-84e8f65a-56e8-47f5-b6b8-57eda6ddcd1a.png)

2022-02-23 13:31 UTC, Duartangel commented
> 

I have an RX 6800 XT video card and Pokemon Legends Arceus is running very poorly and if I put a resolution higher than the default it gets worse. What can I do? It runs very well with Yuzu, but I like Ryujinx better =/

2022-02-25 09:19 UTC, benderscruffy commented
To the Top Mammoth [0100421013760000]
graphics are all glitchy
![ryujinx_capture_2022-02-25_17-16-27](https://user-images.githubusercontent.com/2696404/155689068-f991ab89-c622-4ee9-b8a8-caa15fde49e0.png)
![ryujinx_capture_2022-02-25_17-17-29](https://user-images.githubusercontent.com/2696404/155689091-7aec81a5-25fa-4dd5-abfc-f2c952124667.png)

2022-02-25 14:21 UTC, AlfredoDore commented
> 

in Starlink there is a similar problem, in which case the shadows are dark and something very far away becomes black

2022-02-26 05:31 UTC, benderscruffy commented
Power Pro Kun Pocket R [01000C4015030000]
few graphic glitches
![ryujinx_capture_2022-02-26_13-28-52](https://user-images.githubusercontent.com/2696404/155830551-1ed6e9cc-337f-497b-a125-c017e87a74f3.png)

00:02:47.830 |E| .NET ThreadPool Worker Gpu .ctor: Shader compilation error: CompilationError Ryu:7: warning: '#extension' : extension not supported: GL_EXT_texture_shadow_lod
Ryu:91: error: 'gl_Layer' : required extension not requested: Possible extensions include:
Ryu: GL_ARB_shader_viewport_layer_array
Ryu: GL_NV_viewport_array2

2022-02-26 17:49 UTC, AlfredoDore commented
Mario Kart 8
textures are flickering and need performance improvement 
Log file
[Ryujinx_1.1.0+c9eaf19_2022-02-26_14-39-32.log](https://github.com/Ryujinx/Ryujinx/files/8147146/Ryujinx_1.1.0%2Bc9eaf19_2022-02-26_14-39-32.log)
ryujinx-Release-1.0.0+c9eaf19-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/155853686-bfbfdd46-e28f-487c-a2ee-8831ba557696.png)

2022-02-26 18:21 UTC, MarkLanders777 commented
> Mario Kart 8 textures are flickering and need performance improvement Log file [Ryujinx_1.1.0+c9eaf19_2022-02-26_14-39-32.log](https://github.com/Ryujinx/Ryujinx/files/8147146/Ryujinx_1.1.0%2Bc9eaf19_2022-02-26_14-39-32.log) ryujinx-Release-1.0.0+c9eaf19-win_x64 OS: Windows 10 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.2.2 ![imagem](https://user-images.githubusercontent.com/90729203/155853686-bfbfdd46-e28f-487c-a2ee-8831ba557696.png)

You should make a short video showing the issue, because the picture proves you wrong 60fps and no flickering

2022-02-26 23:08 UTC, AlfredoDore commented
> You should make a short video showing the issue, because the picture proves you wrong 60fps and no flickering

this occurs mid-run, the log shows this happening 
00:00:25.764 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:27.494 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:27.778 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:28.079 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:28.481 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:31.517 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:06.837 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:08.167 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:10.739 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:11.392 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:14.985 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:39.970 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:50.176 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 143996 bytes, profiled functions: 42546).

2022-02-27 13:38 UTC, AlfredoDore commented
Digimon Story Cyber Sleuth: Complete Edition Switch
it has totally broken graphics and the game does not go beyond the menu 
Log file
[Ryujinx_1.1.0+c9eaf19_2022-02-27_10-33-46.log](https://github.com/Ryujinx/Ryujinx/files/8148731/Ryujinx_1.1.0%2Bc9eaf19_2022-02-27_10-33-46.log)
ryujinx-Release-1.0.0+c9eaf19-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/155884596-1a6c8735-1cdf-4ca4-bafe-78395899436f.png)

2022-02-27 23:42 UTC, AlfredoDore commented
Shadow Man
strangely the lanterns are rendering better, it looked like bright blurs, but it still has black texture errors 
Log file
[Ryujinx_1.1.0+59e889e_2022-02-27_20-37-21.log](https://github.com/Ryujinx/Ryujinx/files/8149626/Ryujinx_1.1.0%2B59e889e_2022-02-27_20-37-21.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/155904881-7d9f8528-9ed7-41cb-8015-702a5089b838.png)
![imagem](https://user-images.githubusercontent.com/90729203/155904902-c56228e5-8507-4b75-8559-74a07c032ac6.png)
![imagem](https://user-images.githubusercontent.com/90729203/155904938-5263056f-1099-4a49-98ec-584e8354bef0.png)

2022-02-27 23:53 UTC, AlfredoDore commented
Starlink
in addition to slow video playback, there are several graphical errors and with the update that is essential for the game's progress, the game only goes to the menu, then closes 
Log file
[Ryujinx_1.1.0+59e889e_2022-02-27_20-43-05.log](https://github.com/Ryujinx/Ryujinx/files/8149651/Ryujinx_1.1.0%2B59e889e_2022-02-27_20-43-05.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/155905102-3f8a61a6-974b-4b76-97a0-6b5788ed0163.png)
![imagem](https://user-images.githubusercontent.com/90729203/155905342-5e13d206-5c6d-4f45-91f7-067900913eba.png)

2022-02-28 00:22 UTC, AlfredoDore commented
Zelda Link's Awakerning
has yield losses and this water texture error 
Log file
[Ryujinx_1.1.0+59e889e_2022-02-27_21-14-12.log](https://github.com/Ryujinx/Ryujinx/files/8149722/Ryujinx_1.1.0%2B59e889e_2022-02-27_21-14-12.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/155906300-2f589784-3b88-46e1-abce-98868c588501.png)
![imagem](https://user-images.githubusercontent.com/90729203/155906460-89ae662e-4bae-48f6-b14a-e509fdc89f0f.png)

2022-02-28 01:20 UTC, Raz-Yagami commented
Game: Shin Megami Iensei V
Build used : ryujinx-Release-1.0.0+59e889e-win_x64
Issue: Drop FPS in Demon Kings Castle Multi effect, still better Opengl version
Log:
[Ryujinx_1.1.0+59e889e_2022-02-27_17-02-07.log](https://github.com/Ryujinx/Ryujinx/files/8149883/Ryujinx_1.1.0%2B59e889e_2022-02-27_17-02-07.log)
![Multi effect drop FPS](https://user-images.githubusercontent.com/98293425/155909372-305bb7b5-b825-4d2a-88d8-df2c1a756565.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 01:27 UTC, Raz-Yagami commented
Game: Monster Hunter Stories 2
Build used : ryujinx-Release-1.0.0+59e889e-win_x64
Issue: Spam Audio Error next freeze in game, to finally crash
log:
[Ryujinx_1.1.0+59e889e_2022-02-27_17-20-44.log](https://github.com/Ryujinx/Ryujinx/files/8149903/Ryujinx_1.1.0%2B59e889e_2022-02-27_17-20-44.log)
![MHS 2 freeze image but music still next crash](https://user-images.githubusercontent.com/98293425/155909791-98711801-896f-4d79-b4c5-ee192f8b315a.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 01:49 UTC, Raz-Yagami commented
Game: The Legend of Zelda Links Awakening
Build used : ryujinx-Release-1.0.0+59e889e-win_x64
Issues: cut the weeds and swamp have drops, Opengl still working better
log:
[Ryujinx_1.1.0+59e889e_2022-02-27_17-35-49.log](https://github.com/Ryujinx/Ryujinx/files/8149964/Ryujinx_1.1.0%2B59e889e_2022-02-27_17-35-49.log)
![zelda awakening slowdown fps some time drop to 20](https://user-images.githubusercontent.com/98293425/155911216-95549641-c9e0-4681-a7f1-6c8450cfdc8c.jpg)
![zelda awakening slowdown fps cutting grass](https://user-images.githubusercontent.com/98293425/155911225-e008992e-f734-469c-b7fa-df52db24dd7c.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 02:12 UTC, Raz-Yagami commented
Game: Blue Reflection Second Light
Build used : ryujinx-Release-1.0.0+59e889e-win_x64
Issue: 20 FPS cap on vulkan, Opengl run fine 30 FPS
log:
[Ryujinx_1.1.0+59e889e_2022-02-27_18-02-43.log](https://github.com/Ryujinx/Ryujinx/files/8150064/Ryujinx_1.1.0%2B59e889e_2022-02-27_18-02-43.log)
![BR SL 20 fps cap](https://user-images.githubusercontent.com/98293425/155912857-21b855d5-a9d5-4c71-a71a-32f0c50e6759.jpg)
![BR SL 30 fps cap Opengl](https://user-images.githubusercontent.com/98293425/155912860-e4412c0a-a4dd-4293-b7c4-3a179eb701aa.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 02:30 UTC, Raz-Yagami commented
Game: Crash Team Racing Nitro Fueled

Status: Perfect on Both OS, all effect enviroment in gold medal

***** Congratulation  Team Ryujinx*****
Build used : ryujinx-Release-1.0.0+59e889e-linux_x64 and ryujinx-Release-1.0.0+59e889e-win_x64

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 02:38 UTC, Raz-Yagami commented
Game: Monster Hunter Stories 2
Build used : ryujinx-Release-1.0.0+59e889e-linux_x64
Issue: Crash loading game; the same problem of windows edition
log:
[Ryujinx_1.1.0+59e889e_2022-02-27_10-33-11.log](https://github.com/Ryujinx/Ryujinx/files/8150176/Ryujinx_1.1.0%2B59e889e_2022-02-27_10-33-11.log)
[Ryujinx_1.1.0+59e889e_2022-02-27_10-34-38.log](https://github.com/Ryujinx/Ryujinx/files/8150178/Ryujinx_1.1.0%2B59e889e_2022-02-27_10-34-38.log)
[Ryujinx_1.1.0+59e889e_2022-02-27_10-32-18.log](https://github.com/Ryujinx/Ryujinx/files/8150179/Ryujinx_1.1.0%2B59e889e_2022-02-27_10-32-18.log)
![Captura de pantalla de 2022-02-27 10-34-23](https://user-images.githubusercontent.com/98293425/155914792-155e6ffe-68d3-4f58-9dbc-cef45e8a2cb2.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 02:41 UTC, Raz-Yagami commented
Game: Xenoblade Chronicle DE
Build used : ryujinx-Release-1.0.0+59e889e-linux_x64
issue: Crash Loading the game; Windows edition working fine
log:
[Ryujinx_1.1.0+59e889e_2022-02-27_10-39-55.log](https://github.com/Ryujinx/Ryujinx/files/8150195/Ryujinx_1.1.0%2B59e889e_2022-02-27_10-39-55.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 02:53 UTC, Raz-Yagami commented
Game: Xenoblade Chronicle 2

Status: Stable on both OS, the Linux version its don't crash anymore

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 03:03 UTC, Raz-Yagami commented
Game: Blue Reflection Second Light
Build used : ryujinx-Release-1.0.0+59e889e-linux_x64
Issue: 20 FPS cap; Opengl run 30 FPS
log:
[Ryujinx_1.1.0+59e889e_2022-02-27_10-57-29.log](https://github.com/Ryujinx/Ryujinx/files/8150272/Ryujinx_1.1.0%2B59e889e_2022-02-27_10-57-29.log)
![Captura de pantalla de 2022-02-27 10-59-22](https://user-images.githubusercontent.com/98293425/155917158-c742bc8b-7772-4ff6-be73-6f71a878e350.png)
![Captura de pantalla de 2022-02-27 11-01-16](https://user-images.githubusercontent.com/98293425/155917174-c4c16bf0-35b2-480b-bf6f-6df139903a95.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 03:17 UTC, Raz-Yagami commented
Game: Shin Megami tensei V
Build used : ryujinx-Release-1.0.0+59e889e-linux_x64
Issue: Maps Demon Kings Castle drop FPS, still better the Opengl
log:
[Ryujinx_1.1.0+59e889e_2022-02-27_11-04-35.log](https://github.com/Ryujinx/Ryujinx/files/8150332/Ryujinx_1.1.0%2B59e889e_2022-02-27_11-04-35.log)
![Captura de pantalla de 2022-02-27 11-10-03](https://user-images.githubusercontent.com/98293425/155918139-5157a37c-8a55-45ed-aa4d-d8859808a2c9.png)
![Captura de pantalla de 2022-02-27 11-10-09](https://user-images.githubusercontent.com/98293425/155918175-66c8a4c3-a377-43c0-b13d-2138d45b5c0b.png)
![Captura de pantalla de 2022-02-27 11-12-45](https://user-images.githubusercontent.com/98293425/155918207-8791d744-c77e-4d77-ab35-2b587a8aaff6.png)
![Captura de pantalla de 2022-02-27 11-13-08](https://user-images.githubusercontent.com/98293425/155918240-f2c935b0-c3fb-433d-a5b6-4008f9dee903.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 03:24 UTC, Raz-Yagami commented
Game: The Legend of Zelda Breath of the Wild
Build used : ryujinx-Release-1.0.0+59e889e-linux_x64
Issue: Still crash after 4-5 minutes in-game, Windows Edition work fine
Log:
[Ryujinx_1.1.0+59e889e_2022-02-27_11-18-01.log](https://github.com/Ryujinx/Ryujinx/files/8150377/Ryujinx_1.1.0%2B59e889e_2022-02-27_11-18-01.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-02-28 14:17 UTC, AlfredoDore commented
Haven
the game has constant fps drops, on Switch it runs at 60 fps, on the emulator there are areas that drop to 20 fps, it has no more graphical errors  
Log file
[Ryujinx_1.1.0+59e889e_2022-02-28_11-04-26.log](https://github.com/Ryujinx/Ryujinx/files/8153938/Ryujinx_1.1.0%2B59e889e_2022-02-28_11-04-26.log)

ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/155997890-b9924c61-aee4-44ba-9c0b-df5a39ab5004.png)

2022-02-28 14:53 UTC, AlfredoDore commented
Crash Trilogy
the game has improved the speed, but it needs to improve even more, because the game normally runs at 30 fps and goes to 20, also the textures have aspect ratio error 
Log file
[Ryujinx_1.1.0+59e889e_2022-02-28_11-46-39.log](https://github.com/Ryujinx/Ryujinx/files/8154216/Ryujinx_1.1.0%2B59e889e_2022-02-28_11-46-39.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/156003350-ffc8769e-d34d-4733-a79a-94386e22ee4c.png)
![imagem](https://user-images.githubusercontent.com/90729203/156003530-be58840c-e627-4a9f-a419-4235b6c8f846.png)
![imagem](https://user-images.githubusercontent.com/90729203/156003839-1f5eb82b-b643-4f67-bc39-253745973070.png)

2022-02-28 16:39 UTC, AlfredoDore commented
Pokémon Shining Pearl 
doesn't work, the game just closes 
Log file
[Ryujinx_1.1.0+59e889e_2022-02-28_13-36-23.log](https://github.com/Ryujinx/Ryujinx/files/8155017/Ryujinx_1.1.0%2B59e889e_2022-02-28_13-36-23.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2

2022-02-28 16:43 UTC, AlfredoDore commented
Pokémon Shining Pearl
also with update 1.2.0 closes 
Log file
[Ryujinx_1.1.0+59e889e_2022-02-28_13-40-26.log](https://github.com/Ryujinx/Ryujinx/files/8155041/Ryujinx_1.1.0%2B59e889e_2022-02-28_13-40-26.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2

2022-02-28 18:27 UTC, adambennett08330 commented
> Pokémon Shining Pearl also with update 1.2.0 closes Log file [Ryujinx_1.1.0+59e889e_2022-02-28_13-40-26.log](https://github.com/Ryujinx/Ryujinx/files/8155041/Ryujinx_1.1.0%2B59e889e_2022-02-28_13-40-26.log) ryujinx-Release-1.0.0+59e889e-win_x64 OS: Windows 10 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.2.2

you sure the game isnt working? cause its working fine for me. the only issue i have is the title screen not showing like it did when game first launched before update 
![image](https://user-images.githubusercontent.com/100615043/156035726-bd76470d-a811-4f1f-9df9-c43ab34f351d.png)
![image](https://user-images.githubusercontent.com/100615043/156035903-7549f264-dd30-41fd-b612-326fea617e70.png)
![image](https://user-images.githubusercontent.com/100615043/156036004-8f32c931-44fe-45f0-ba6e-a53c46d3eff1.png)
ryujinx-1.1.54-win_x64
OS: Windows 10
Storage NVME SSD
CPU: AMD Ryzen 5 4600H 3GHz
RAM: 8gb (3200MHz)
GPU: Geforce RTX 1650 TI 4GB GDDR6 1585MHz

2022-02-28 18:32 UTC, GamerzHell9137 commented
> > Pokémon Shining Pearl also with update 1.2.0 closes Log file [Ryujinx_1.1.0+59e889e_2022-02-28_13-40-26.log](https://github.com/Ryujinx/Ryujinx/files/8155041/Ryujinx_1.1.0%2B59e889e_2022-02-28_13-40-26.log) ryujinx-Release-1.0.0+59e889e-win_x64 OS: Windows 10 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.2.2
> 
> you sure the game isnt working? cause its working fine for me on my asus laptop. the only issue i have is the title screen not showing like it did when game first launched before update ![image](https://user-images.githubusercontent.com/100615043/156035726-bd76470d-a811-4f1f-9df9-c43ab34f351d.png) ![image](https://user-images.githubusercontent.com/100615043/156035903-7549f264-dd30-41fd-b612-326fea617e70.png) ![image](https://user-images.githubusercontent.com/100615043/156036004-8f32c931-44fe-45f0-ba6e-a53c46d3eff1.png) ryujinx-1.1.54-win_x64 OS: Windows 10 Storage NVME SSD CPU: AMD Ryzen 5 4600H 3GHz RAM: 8gb (3200MHz) GPU: Geforce RTX 1650 TI 4GB GDDR6 1585MHz

You know we're on the Vulkan PR here?

2022-02-28 18:35 UTC, Raz-Yagami commented
> > Pokémon Shining Pearl also with update 1.2.0 closes Log file [Ryujinx_1.1.0+59e889e_2022-02-28_13-40-26.log](https://github.com/Ryujinx/Ryujinx/files/8155041/Ryujinx_1.1.0%2B59e889e_2022-02-28_13-40-26.log) ryujinx-Release-1.0.0+59e889e-win_x64 OS: Windows 10 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.2.2
> 
> you sure the game isnt working? cause its working fine for me. the only issue i have is the title screen not showing like it did when game first launched before update ![image](https://user-images.githubusercontent.com/100615043/156035726-bd76470d-a811-4f1f-9df9-c43ab34f351d.png) ![image](https://user-images.githubusercontent.com/100615043/156035903-7549f264-dd30-41fd-b612-326fea617e70.png) ![image](https://user-images.githubusercontent.com/100615043/156036004-8f32c931-44fe-45f0-ba6e-a53c46d3eff1.png) ryujinx-1.1.54-win_x64 OS: Windows 10 Storage NVME SSD CPU: AMD Ryzen 5 4600H 3GHz RAM: 8gb (3200MHz) GPU: Geforce RTX 1650 TI 4GB GDDR6 1585MHz

He has AMD Graphics Card so the issue about fix bug, crash on the red side drivers, our Nvidia have better driver this project need more AMD user testing for dev make workaround for now this it more promising Ryujinx. He have 8 core CPU for better test.

2022-02-28 18:37 UTC, adambennett08330 commented
> > > Pokémon Shining Pearl also with update 1.2.0 closes Log file [Ryujinx_1.1.0+59e889e_2022-02-28_13-40-26.log](https://github.com/Ryujinx/Ryujinx/files/8155041/Ryujinx_1.1.0%2B59e889e_2022-02-28_13-40-26.log) ryujinx-Release-1.0.0+59e889e-win_x64 OS: Windows 10 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.2.2
> > 
> > 
> > you sure the game isnt working? cause its working fine for me on my asus laptop. the only issue i have is the title screen not showing like it did when game first launched before update ![image](https://user-images.githubusercontent.com/100615043/156035726-bd76470d-a811-4f1f-9df9-c43ab34f351d.png) ![image](https://user-images.githubusercontent.com/100615043/156035903-7549f264-dd30-41fd-b612-326fea617e70.png) ![image](https://user-images.githubusercontent.com/100615043/156036004-8f32c931-44fe-45f0-ba6e-a53c46d3eff1.png) ryujinx-1.1.54-win_x64 OS: Windows 10 Storage NVME SSD CPU: AMD Ryzen 5 4600H 3GHz RAM: 8gb (3200MHz) GPU: Geforce RTX 1650 TI 4GB GDDR6 1585MHz
> 
> You know we're on the Vulkan PR here?
in console its saying its using amd

2022-02-28 23:17 UTC, AlfredoDore commented
> you sure the game isnt working? cause its working fine for me on my asus laptop. the only issue i have is the title screen not showing like it did when game first launched before update.

it doesn't even get to the menu screen or anything, it just closes

2022-03-01 00:08 UTC, isaiahboone commented
> > you sure the game isnt working? cause its working fine for me on my asus laptop. the only issue i have is the title screen not showing like it did when game first launched before update.
> 
> it doesn't even get to the menu screen or anything, it just closes

can confirm the same happens with me when trying to launch Brilliant Diamond.
[Ryujinx_1.1.0+59e889e_2022-02-28_20-31-40.log](https://github.com/Ryujinx/Ryujinx/files/8157768/Ryujinx_1.1.0%2B59e889e_2022-02-28_20-31-40.log)

Specs:
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: 1TB SSD
CPU: Intel Core i9-7940X 14-Core Processor 4.6 GHz
RAM: 48GB 3600MHz
GPU: Radeon RX 6800 XT 16GB GDDR6 2150MHz
DRIVER: 22.2.3

2022-03-01 05:05 UTC, Raz-Yagami commented
Game: Pokemon Shinning Pearl
Build used: ryujinx-Release-1.0.0+59e889e-win_x64
Issue: Crash loading Game
Log:
[Ryujinx_1.1.0+59e889e_2022-02-28_21-01-36.log](https://github.com/Ryujinx/Ryujinx/files/8158863/Ryujinx_1.1.0%2B59e889e_2022-02-28_21-01-36.log)
[Ryujinx_1.1.0+59e889e_2022-02-28_21-02-51.log](https://github.com/Ryujinx/Ryujinx/files/8158864/Ryujinx_1.1.0%2B59e889e_2022-02-28_21-02-51.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-01 08:27 UTC, yuwenhua653 commented
Pokemon Shining Pearl doesn't work in VK branch no matter what graphics card

2022-03-02 14:47 UTC, AlfredoDore commented
Yoshi
besides slowdowns and flickering textures, the game doesn't get past that part 
Log file
[Ryujinx_1.1.0+59e889e_2022-03-02_11-42-24.log](https://github.com/Ryujinx/Ryujinx/files/8170339/Ryujinx_1.1.0%2B59e889e_2022-03-02_11-42-24.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/156384291-ba516956-f793-4093-894c-f5c6678c0980.png)

2022-03-02 22:50 UTC, AlfredoDore commented
Mario Kart 8
the performance has improved, but when it gives the thunder effects or when it goes into the water, the fps drops, the characters stopped blinking but in the flower cup the scenarios still blink 
Log file
[Ryujinx_1.1.0+59e889e_2022-03-02_19-26-04.log](https://github.com/Ryujinx/Ryujinx/files/8173459/Ryujinx_1.1.0%2B59e889e_2022-03-02_19-26-04.log)
ryujinx-Release-1.0.0+59e889e-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.2
![imagem](https://user-images.githubusercontent.com/90729203/156461124-7486c8c4-9bcb-4641-9e16-78c9a3b9ec40.png)
![imagem](https://user-images.githubusercontent.com/90729203/156461993-f9ac357b-13ac-47ee-a09c-8536b7266e12.png)

2022-03-03 01:31 UTC, AlfredoDore commented
It's funny that I can only test Mario Kart when there is an update of the main one, because once played it just closes and this was never solved (in Vulkan, this doesn't happen in the main one)

2022-03-03 01:54 UTC, RetroPCYT commented
> It's funny that I can only test Mario Kart when there is an update of the main one, because once played it just closes and this was never solved (in Vulkan, this doesn't happen in the main one)

Mario Kart 8 Deluxe runs great in OpenGL (@ 2x Native Resolution) using a "legacy" GTX970, better than vulkan at least for now... saludos!

2022-03-04 00:15 UTC, Raz-Yagami commented
Game: TS
Build used : ryujinx-Release-1.0.0+d047323-win_x64
Issue: Black scene rendering in-game; Opengl work fine
Log:
[Ryujinx_1.1.0+d047323_2022-03-03_15-46-43.log](https://github.com/Ryujinx/Ryujinx/files/8181982/Ryujinx_1.1.0%2Bd047323_2022-03-03_15-46-43.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 00:32 UTC, Raz-Yagami commented
Game: Monster hunter Stories 2
Build used : ryujinx-Release-1.0.0+d047323-win_x64
Issue: first 2 run crash game the 3rd go in-game fine walking around without issue but could be bad experience for new player if see fatal crashing; Opengl run fine
Logs crash first 2 run:
[Ryujinx_1.1.0+d047323_2022-03-03_16-17-45.log](https://github.com/Ryujinx/Ryujinx/files/8182029/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-17-45.log)
[Ryujinx_1.1.0+d047323_2022-03-03_16-15-34.log](https://github.com/Ryujinx/Ryujinx/files/8182030/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-15-34.log)
Logs 3rd run in-game okay:
[Ryujinx_1.1.0+d047323_2022-03-03_16-19-06.log](https://github.com/Ryujinx/Ryujinx/files/8182032/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-19-06.log)
![MHS 2 Ingame walking around okay](https://user-images.githubusercontent.com/98293425/156676197-c0df955f-2221-4a6c-b78a-135e9278e9eb.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 00:38 UTC, Raz-Yagami commented
Game: Pokemon Shining Pearl
Build used : ryujinx-Release-1.0.0+d047323-win_x64
Issue: Still crashing loading game
Logs 3 runs:
[Ryujinx_1.1.0+d047323_2022-03-03_16-36-51.log](https://github.com/Ryujinx/Ryujinx/files/8182082/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-36-51.log)
[Ryujinx_1.1.0+d047323_2022-03-03_16-33-26.log](https://github.com/Ryujinx/Ryujinx/files/8182083/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-33-26.log)
[Ryujinx_1.1.0+d047323_2022-03-03_16-36-17.log](https://github.com/Ryujinx/Ryujinx/files/8182084/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-36-17.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 00:45 UTC, Raz-Yagami commented
Game: Blue Reflection Second Light
Build used : ryujinx-Release-1.0.0+d047323-win_x64
Issue: 20 fps cap, Opengl run 30 fps
logs:
[Ryujinx_1.1.0+d047323_2022-03-03_16-39-00.log](https://github.com/Ryujinx/Ryujinx/files/8182116/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-39-00.log)
![BR SL 20 fps cap GPU process is to slow log](https://user-images.githubusercontent.com/98293425/156677614-da0b0ec4-5b7d-4c2f-9b5c-2ea0c31d4e3d.jpg)
![BR SL 20 fps cap](https://user-images.githubusercontent.com/98293425/156677637-1a2a8208-5941-400f-b37a-405cfc5e5918.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 01:02 UTC, Raz-Yagami commented
Game: Shin Megami Tensei V
Build used : ryujinx-Release-1.0.0+d047323-win_x64
Status: Run better on map Demon Kings Castle like the Opengl version 30 fps most time little drop to 20 fps but fine

Logs don't change just improved if its posible:
[Ryujinx_1.1.0+d047323_2022-03-03_16-46-46.log](https://github.com/Ryujinx/Ryujinx/files/8182174/Ryujinx_1.1.0%2Bd047323_2022-03-03_16-46-46.log)
![More stable Demon King Castle 30 fps](https://user-images.githubusercontent.com/98293425/156678824-e015f79e-7339-4c06-98b1-5d215ad42529.jpg)
 
PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 01:30 UTC, Raz-Yagami commented
Game: The Legend of Zelda Breath of the Wild
Build used : ryujinx-Release-1.0.0+d047323-win_x64
Status: Run fine on second try, at least 20 minute without crash on windows and environment effect its impressive

log 1st run 
[Ryujinx_1.1.0+d047323_2022-03-03_17-03-30.log](https://github.com/Ryujinx/Ryujinx/files/8182289/Ryujinx_1.1.0%2Bd047323_2022-03-03_17-03-30.log)
crash:
log 2nd run fine:
[Ryujinx_1.1.0+d047323_2022-03-03_17-07-32.log](https://github.com/Ryujinx/Ryujinx/files/8182290/Ryujinx_1.1.0%2Bd047323_2022-03-03_17-07-32.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 01:48 UTC, Raz-Yagami commented
Game: The legend of Zelda Link's Awakening
Build used : ryujinx-Release-1.0.0+d047323-win_x64
Status: Getting Better perfomance with Vsync off running on get laggy
logs:
[Ryujinx_1.1.0+d047323_2022-03-03_17-31-29.log](https://github.com/Ryujinx/Ryujinx/files/8182382/Ryujinx_1.1.0%2Bd047323_2022-03-03_17-31-29.log)
![better experience on this vk with mods and vsync off](https://user-images.githubusercontent.com/98293425/156683376-ae8e8f7c-97e9-4f90-aed2-43dc512c799e.jpg)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 02:07 UTC, Raz-Yagami commented
Game: Monster Hunter Stories 2
Build used : ryujinx-Release-1.0.0+d047323-linux_x64
Issue: Still crashing loading game; Opengl linux run fine and windows vk at least run 3rd try
Logs 3 but run 7 time:
[Ryujinx_1.1.0+d047323_2022-03-03_09-58-06.log](https://github.com/Ryujinx/Ryujinx/files/8182473/Ryujinx_1.1.0%2Bd047323_2022-03-03_09-58-06.log)
[Ryujinx_1.1.0+d047323_2022-03-03_09-58-55.log](https://github.com/Ryujinx/Ryujinx/files/8182474/Ryujinx_1.1.0%2Bd047323_2022-03-03_09-58-55.log)
[Ryujinx_1.1.0+d047323_2022-03-03_09-59-33.log](https://github.com/Ryujinx/Ryujinx/files/8182475/Ryujinx_1.1.0%2Bd047323_2022-03-03_09-59-33.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 02:51 UTC, Raz-Yagami commented
Game: Shin Megami Tensei V
Build used : ryujinx-Release-1.0.0+d047323-linux_x64
Status: Run better its just the fog that could drop frames; Opengl Still handle better
Logs:
[Ryujinx_1.1.0+d047323_2022-03-03_10-21-48.log](https://github.com/Ryujinx/Ryujinx/files/8182670/Ryujinx_1.1.0%2Bd047323_2022-03-03_10-21-48.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 02:57 UTC, Raz-Yagami commented
Game: Xenoblade Chronicle DE
Build used : ryujinx-Release-1.0.0+d047323-linux_x64
Issue: Still crashing just loading the game; Windows edition run fine its seem Opengl Linux have the same issue
Logs 3 runs:
[Ryujinx_1.1.0+d047323_2022-03-03_10-51-12.log](https://github.com/Ryujinx/Ryujinx/files/8182687/Ryujinx_1.1.0%2Bd047323_2022-03-03_10-51-12.log)
[Ryujinx_1.1.0+d047323_2022-03-03_10-52-08.log](https://github.com/Ryujinx/Ryujinx/files/8182688/Ryujinx_1.1.0%2Bd047323_2022-03-03_10-52-08.log)
[Ryujinx_1.1.0+d047323_2022-03-03_10-52-30.log](https://github.com/Ryujinx/Ryujinx/files/8182689/Ryujinx_1.1.0%2Bd047323_2022-03-03_10-52-30.log)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 03:47 UTC, Raz-Yagami commented
Game: The Legend of Zelda Breath of The Wild
Build used : ryujinx-Release-1.0.0+d047323-linux_x64
Issue: Run at 3rd try but more buggy physic on areas should not be a lake
Logs:
[Ryujinx_1.1.0+d047323_2022-03-03_11-34-49.log](https://github.com/Ryujinx/Ryujinx/files/8182902/Ryujinx_1.1.0%2Bd047323_2022-03-03_11-34-49.log)
[Ryujinx_1.1.0+d047323_2022-03-03_11-36-44.log](https://github.com/Ryujinx/Ryujinx/files/8182903/Ryujinx_1.1.0%2Bd047323_2022-03-03_11-36-44.log)
[Ryujinx_1.1.0+d047323_2022-03-03_11-38-16.log](https://github.com/Ryujinx/Ryujinx/files/8182904/Ryujinx_1.1.0%2Bd047323_2022-03-03_11-38-16.log)
![Captura de pantalla de 2022-03-03 11-42-34](https://user-images.githubusercontent.com/98293425/156695585-462c4b6c-1676-4c48-9682-aab569195bfb.png)
![Captura de pantalla de 2022-03-03 11-42-51](https://user-images.githubusercontent.com/98293425/156695598-6d8e07b6-b782-4d36-a109-2c2b9da17672.png)
![Captura de pantalla de 2022-03-03 11-42-24](https://user-images.githubusercontent.com/98293425/156695619-5f5097d4-dcc6-4a04-97cd-c16b0b300c99.png)

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 04:19 UTC, Raz-Yagami commented
Game: The legend of Zelda Link's Awakening
Build used : ryujinx-Release-1.0.0+d047323-linux_x64
Status: Getting Better perfomance with Vsync off running on get laggy, cutting weed run better
logs:
[Ryujinx_1.1.0+d047323_2022-03-03_12-08-50.log](https://github.com/Ryujinx/Ryujinx/files/8182998/Ryujinx_1.1.0%2Bd047323_2022-03-03_12-08-50.log)
![Captura de pantalla de 2022-03-03 12-10-45](https://user-images.githubusercontent.com/98293425/156698096-38f9ce7c-2292-4997-a76d-0eca89a4edba.png)
![Captura de pantalla de 2022-03-03 12-10-53](https://user-images.githubusercontent.com/98293425/156698112-df973805-2cf0-4819-94a3-348d97bc0cb6.png)

if add disable depth field get 70-120 fps vsync off; but run without it to see improvement it got better imagen added

PC specs:
OS: Windows 11 21H2 updated and Garuda Linux Zen 5.16.11
CPU: AMD Ryzen 5 5600x
RAM: 16 Gb 3200 mhz
GPU: Nvidia GTX 1070
Driver: Win 511.79 | Linux 510.54
Storage: SSD 480 GB and 2 HDD

2022-03-04 16:53 UTC, AlfredoDore commented
Pokemon Shining Pearl
doesn't work, the game just closes
Log file
[Ryujinx_1.1.0+d047323_2022-03-04_13-47-18.log](https://github.com/Ryujinx/Ryujinx/files/8187452/Ryujinx_1.1.0%2Bd047323_2022-03-04_13-47-18.log)
ryujinx-Release-1.0.0+d047323-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3

2022-03-04 16:59 UTC, AlfredoDore commented
Crash Trilogy
has yield losses and texture errors 
Log file
[Ryujinx_1.1.0+d047323_2022-03-04_13-53-33.log](https://github.com/Ryujinx/Ryujinx/files/8187509/Ryujinx_1.1.0%2Bd047323_2022-03-04_13-53-33.log)
ryujinx-Release-1.0.0+d047323-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/156805924-54335483-d0a3-4c47-a82c-3f18a9e8b7ea.png)
![imagem](https://user-images.githubusercontent.com/90729203/156806422-9c4badc8-fd5a-4536-b684-c13739fbd556.png)

2022-03-04 17:23 UTC, AlfredoDore commented
Mario Kart 8
textures are more stable, but still continue to flicker and have a performance issue, but only in light and water effects 
Log file
[Ryujinx_1.1.0+d047323_2022-03-04_14-00-15.log](https://github.com/Ryujinx/Ryujinx/files/8187708/Ryujinx_1.1.0%2Bd047323_2022-03-04_14-00-15.log)
ryujinx-Release-1.0.0+d047323-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/156808160-e46919c6-c187-4bb7-ad2c-69c71cfc740e.png)
![imagem](https://user-images.githubusercontent.com/90729203/156810170-c1482435-c31d-4695-9505-08cdc5af5701.png)

2022-03-04 17:32 UTC, AlfredoDore commented
Starlink
Starlink has several problems and video playback is very slow, and the game is not playable with the update, which is essential to continue the game 
Log file
[Ryujinx_1.1.0+d047323_2022-03-04_14-24-34.log](https://github.com/Ryujinx/Ryujinx/files/8187774/Ryujinx_1.1.0%2Bd047323_2022-03-04_14-24-34.log)
ryujinx-Release-1.0.0+d047323-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/156812103-e8d4143f-2822-409b-bee6-67615acaa7ea.png)
![imagem](https://user-images.githubusercontent.com/90729203/156812502-c6478062-7821-470d-b5d6-e89269123e88.png)

2022-03-04 17:36 UTC, AlfredoDore commented
Shadow Man
black textures bugs 
Log file
[Ryujinx_1.1.0+d047323_2022-03-04_14-33-19.log](https://github.com/Ryujinx/Ryujinx/files/8187797/Ryujinx_1.1.0%2Bd047323_2022-03-04_14-33-19.log)
ryujinx-Release-1.0.0+d047323-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/156813373-c782138d-c450-4557-816b-d824935987d6.png)
![imagem](https://user-images.githubusercontent.com/90729203/156813482-230729aa-893d-48d0-8aeb-ef1c15d2071b.png)

2022-03-04 17:44 UTC, AlfredoDore commented
Zelda  
loses performance and has this problem with the texture of the water (it's not exactly texture but an artifact) 
Log file
[Ryujinx_1.1.0+d047323_2022-03-04_14-37-58.log](https://github.com/Ryujinx/Ryujinx/files/8187829/Ryujinx_1.1.0%2Bd047323_2022-03-04_14-37-58.log)
ryujinx-Release-1.0.0+d047323-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/156814273-f23cb8e5-5014-4e77-bfb7-380edec87229.png)

2022-03-04 19:11 UTC, MutantAura commented
Hey!
While we appreciate any and all testers who go to the effort of reporting their findings we do have a couple of guidelines that we expect any reports to follow to avoid spamming the development team (anyone following this thread gets an email every time someone comments!)

1. If a game has not **significantly** changed status since a previous report or a developer has not specifically asked for a game to be retested then please do not report the same issues again. This will not get them looked at or fixed any faster.

2. If the issue also occurs in master (the main download) then please do not report it on the pull request but instead check to see if there is already an open issue/open an issue if there is not. Alternatively join the discord to check if it is solvable or already known about.

Lots of recent reports are either unrelated to the Vulkan backend itself or are simply reposts of previous issues. If you wish to report something make sure you follow the above guidance before doing so.
Thank you!

2022-03-05 00:22 UTC, benderscruffy commented
Max The Curse Of The Brotherhood
graphic artefacts on the left hand side of the screen 
doesn't happen any where else on the screen
![ryujinx_capture_2022-03-05_07-49-25](https://user-images.githubusercontent.com/2696404/156858681-feee9a58-3d85-4c66-bbf4-a87ff21f5df0.png)
![ryujinx_capture_2022-03-05_07-58-27](https://user-images.githubusercontent.com/2696404/156858688-02395763-397c-41a1-8e86-b360fd98bb32.png)
![ryujinx_capture_2022-03-05_07-59-22](https://user-images.githubusercontent.com/2696404/156858691-4aaa37ef-90a0-4f0e-8ea2-161bd657ba45.png)
![ryujinx_capture_2022-03-05_08-02-38](https://user-images.githubusercontent.com/2696404/156858694-83ce36fc-8e15-4019-9390-a4e0be809637.png)

2022-03-05 08:41 UTC, benderscruffy commented
can anyone get ingame with New Super Mario Bros U Deluxe [0100EA80032EA000][v0]
mine just sits there with the message
00:00:19.660 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:00:24.168 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

2022-03-05 08:42 UTC, GamerzHell9137 commented
> can anyone get ingame with New Super Mario Bros U Deluxe [0100EA80032EA000][v0] mine just sits there with the message 00:00:19.660 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU... 00:00:24.168 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

https://discord.gg/VkQYXAZ

2022-03-05 09:32 UTC, benderscruffy commented
Yo-Kai Watch 4
on the character select screen the characters keep flashing
in game the lighting keeps on flashing

2022-03-05 10:13 UTC, GamerzHell9137 commented
> Yo-Kai Watch 4 on the character select screen the characters keep flashing in game the lighting keeps on flashing

When posting issues post imgaes/videos of them and more info about your OS and hardware you're using. Just saying its not working isn't helping anyone and its just spamming everyone's inboxes for no reason.

2022-03-05 23:17 UTC, AlfredoDore commented
> 

there's a game already working on Vulkan and not on OpenGL (it's one of those I've already reported) a topic I'd like you to open is Starlink, it's one of the Switch games I want to play the most (despite having it for other platforms, the Switch has its exclusives)

2022-03-06 03:21 UTC, benderscruffy commented
Heroine Anthem Zero Episode 1 
colour of the title screen wording and of your companions are incorrect
![ryujinx_capture_2022-03-06_11-14-18](https://user-images.githubusercontent.com/2696404/156907763-955b9401-124f-4487-b967-04e236f41826.png)
![ryujinx_capture_2022-03-06_11-16-52](https://user-images.githubusercontent.com/2696404/156907770-49ffe0bf-dcaa-4929-b209-cad9b495aa9c.png)
this is how it is supposed to look
![Capture](https://user-images.githubusercontent.com/2696404/156907807-ba18ffaa-4f7c-441d-b8a9-1173367b6659.PNG)
![Capture1](https://user-images.githubusercontent.com/2696404/156907815-40ee1045-1129-4b46-b952-838ce23e1d19.PNG)

2022-03-07 16:33 UTC, sauradipdebnath commented
Kirby and legends Arceus works better on vulkan

2022-03-08 13:06 UTC, AlfredoDore commented
Haven
no graphics problems, just loss of performance 
Log file
[Ryujinx_1.1.0+5d6cf74_2022-03-08_09-49-55.log](https://github.com/Ryujinx/Ryujinx/files/8206383/Ryujinx_1.1.0%2B5d6cf74_2022-03-08_09-49-55.log)
ryujinx-Release-1.1.0+5d6cf74-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/157242727-5c634ebc-f08f-4007-846e-bdc43605a9c6.png)
![imagem](https://user-images.githubusercontent.com/90729203/157243332-591c27fe-da4d-4df9-ba41-4138fd25a293.png)

2022-03-08 18:34 UTC, Visualwit commented
Loading "Super Mario 3D All Stars" Works Just Fine. But Loading A Game Like Mario Galaxy Makes The Emulator Stop Responding And Then Crash! Can You Help?

ERROR: 00:00:07.423 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x4912B (sRGB: False).

2022-03-08 21:33 UTC, Niwu34 commented
> > Loading "Super Mario 3D All Stars" Works Just Fine. But Loading A Game Like Mario Galaxy Makes The Emulator Stop Responding And Then Crash! Can You Help?
> > ERROR: 00:00:07.423 |E| GPU.MainThread Gpu GetInfo: Invalid texture format 0x4912B (sRGB: False).
> 
> it's one of the games I really want to play but neither of the two emulators work

I'd highly recomend Dolphin for that -it has texture packs support and controller profiles which should give the best experince as of now

2022-03-08 21:42 UTC, AlfredoDore commented
> I'd highly recomend Dolphin for that -it has texture packs support and controller profiles which should give the best experince as of now

I have a Wii, I would like to play with the videos with better definition  https://www.youtube.com/watch?v=S-Q9v2K9A_w

2022-03-09 15:50 UTC, AlfredoDore commented
Triangle Strategy
Yield drops, slow loading and flickering textures, in short: it has the same problems as Fuga, Yoshi and Bullets (Unreal Engine) 
Log file
[Ryujinx_1.1.0+5d6cf74_2022-03-09_12-07-58.log](https://github.com/Ryujinx/Ryujinx/files/8216078/Ryujinx_1.1.0%2B5d6cf74_2022-03-09_12-07-58.log)
ryujinx-Release-1.1.0+5d6cf74-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/157470474-e540296a-090d-46f4-9004-9f776fcef97a.png)
![imagem](https://user-images.githubusercontent.com/90729203/157470782-c2984a8e-d688-4b65-bc7a-734e65695f77.png)
![imagem](https://user-images.githubusercontent.com/90729203/157471654-8125602e-c33e-4546-b51d-e515d8d8729a.png)
![imagem](https://user-images.githubusercontent.com/90729203/157472406-96313057-985c-40cf-b099-21a617232b1f.png)

2022-03-09 16:28 UTC, Essasetic commented
Hey GDKChan, Ryujinx Vulkan doesn't appear to work on Wayland. I get this when I try to force the Wayland driver:

`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Ryujinx.Headless.SDL2.WindowBase.HandleWindowEvent(SDL_Event evnt) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Headless.SDL2/WindowBase.cs:line 143
   at Ryujinx.SDL2.Common.SDL2Driver.HandleSDLEvent(SDL_Event& evnt) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.SDL2.Common/SDL2Driver.cs:line 137
   at Ryujinx.SDL2.Common.SDL2Driver.EventWorker() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.SDL2.Common/SDL2Driver.cs:line 152
Aborted (core dumped)`

switching to OpenGL or letting it use XWayland instead works.

2022-03-09 16:45 UTC, sauradipdebnath commented
Please add vulkan features to opengl

2022-03-09 16:54 UTC, MelonSpeedruns commented
> Please add vulkan features to opengl

Which features are we talking about here?

2022-03-09 18:22 UTC, AlfredoDore commented
> > Please add vulkan features to opengl
> 
> Which features are we talking about here?

I think some shaders

2022-03-09 19:37 UTC, Essasetic commented
> > > Please add vulkan features to opengl
> > 
> > 
> > Which features are we talking about here?
> 
> I think some shaders

You mean how it processes shaders? SPIR-V?

2022-03-09 20:15 UTC, Niwu34 commented
> > > > Please add vulkan features to opengl
> > > 
> > > 
> > > Which features are we talking about here?
> > 
> > 
> > I think some shaders
> 
> You mean how it processes shaders? SPIR-V?

shader cache?

2022-03-09 22:16 UTC, AlfredoDore commented
> > > > > Please add vulkan features to opengl
> > > > 
> > > > 
> > > > Which features are we talking about here?
> > > 
> > > 
> > > I think some shaders
> > 
> > 
> > You mean how it processes shaders? SPIR-V?
> 
> shader cache?

is a way to reduce processing

2022-03-09 23:15 UTC, AlfredoDore commented
> > > > Please add vulkan features to opengl
> > > 
> > > 
> > > Which features are we talking about here?
> > 
> > 
> > I think some shaders
> 
> You mean how it processes shaders? SPIR-V?

the 2D renderer would be a good one as it is much better than the Vulkan one

2022-03-09 23:20 UTC, riperiperi commented
I think this PR comments section has somehow managed to be the least productive in the entire repository.

2022-03-10 03:25 UTC, Mou-Ikkai commented
> I think this PR comments section has somehow managed to be the least productive in the entire repository.

We're almost at Reddit levels of useless comments... Almost.

2022-03-10 13:11 UTC, AlfredoDore commented
Zelda Link Awakerning
the artifact in the water continues and also loss of yield (the artifact in the water appears as we approach it) 
Log file
[Ryujinx_1.1.0+501b1dc_2022-03-10_10-03-34.log](https://github.com/Ryujinx/Ryujinx/files/8223622/Ryujinx_1.1.0%2B501b1dc_2022-03-10_10-03-34.log)
ryujinx-Release-1.0.0+501b1dc-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/157668233-30a86527-3893-4edb-9b0c-8f27abb8e3eb.png)
![imagem](https://user-images.githubusercontent.com/90729203/157668510-e0d15ff7-b84e-41ea-8d52-77d91de79173.png)

2022-03-10 13:15 UTC, MutantAura commented
> Hey! While we appreciate any and all testers who go to the effort of reporting their findings we do have a couple of guidelines that we expect any reports to follow to avoid spamming the development team (anyone following this thread gets an email every time someone comments!)
> 
> 1. If a game has not **significantly** changed status since a previous report or a developer has not specifically asked for a game to be retested then please do not report the same issues again. This will not get them looked at or fixed any faster.
> 2. If the issue also occurs in master (the main download) then please do not report it on the pull request but instead check to see if there is already an open issue/open an issue if there is not. Alternatively join the discord to check if it is solvable or already known about.
> 
> Lots of recent reports are either unrelated to the Vulkan backend itself or are simply reposts of previous issues. If you wish to report something make sure you follow the above guidance before doing so. Thank you!

Hey @AlfredoDore please refer to the above message that I posted a few days ago. If nothing has **significantly changed** in the game state then please don't feel the need to report it :)
I will start to hide/delete any message that I deem are duplicates/spam.

2022-03-14 16:24 UTC, AlfredoDore commented
Donkey Kong Tropical Freeze
texture failures and I saw an error also in the water texture (looking like cardboard) some things shine a lot, but the performance is excellent 
Log file
[Ryujinx_1.1.0+d3ce548_2022-03-14_13-07-24.log](https://github.com/Ryujinx/Ryujinx/files/8246735/Ryujinx_1.1.0%2Bd3ce548_2022-03-14_13-07-24.log)
ryujinx-Release-1.0.0+d3ce548-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/158214226-a5ddade3-d031-45db-8174-42c904d63c6d.png)
![imagem](https://user-images.githubusercontent.com/90729203/158215920-46419044-392a-493a-bd7c-ead5710bd4b1.png)

2022-03-14 16:32 UTC, Leischii commented
> 

There is a new PR since yesterday that fixes a regression on WarioWare. Gdk said it could also affect Tropical Freeze, so I would test master to see if this is really a vulkan only problem.
PR mentioned is: #3198

2022-03-14 16:34 UTC, gdkchan commented
> There is a new PR since yesterday that fixes a regression on WarioWare. Gdk said it could also affect Tropical Freeze, so I would test master to see if this is really a vulkan only problem. PR mentioned is: #3198

It does not affect this level.

2022-03-14 16:35 UTC, Leischii commented
> It does not affect this level.

Forget I said anything then :D

2022-03-14 17:39 UTC, AlfredoDore commented
Starlink
has several problems, but the most serious is that even with the update 1.5 the game does not leave the menu, the most relevant update of the game is the 1.6 (10GB) in which they fixed a lot and the updates are necessary to continue the game until the final, without update you can't finish the game, in addition the FMV's are very slow, running at 2fps and with a lot of audio cut, including the explanation of how to use a Starlink, without the update the game starts 
Log file
[Ryujinx_1.1.0+d3ce548_2022-03-14_14-26-47.log](https://github.com/Ryujinx/Ryujinx/files/8247257/Ryujinx_1.1.0%2Bd3ce548_2022-03-14_14-26-47.log)
ryujinx-Release-1.0.0+d3ce548-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![Starlink](https://user-images.githubusercontent.com/90729203/158229313-cad1ab03-962d-4681-a610-1740196743d3.jpg)

2022-03-15 16:50 UTC, AlfredoDore commented
Mario Kart 8
the game is now much more stable, despite the little loss of performance and the textures flicker, but very little, now it has this dark shadow problem 
Log file
[Ryujinx_1.1.0+c1c9a15_2022-03-15_13-24-13.log](https://github.com/Ryujinx/Ryujinx/files/8255507/Ryujinx_1.1.0%2Bc1c9a15_2022-03-15_13-24-13.log)
ryujinx-Release-1.0.0+c1c9a15-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.2.3
![imagem](https://user-images.githubusercontent.com/90729203/158425128-893fcc7e-c57f-447c-94ef-a4116c37145f.png)

2022-03-27 16:01 UTC, AlfredoDore commented
both Vulkan and OpenGL Starlink with updates 1.05 and 1.06 give this error when starting the game (it only goes to the start menu), without the updates it starts and the videos are very slow 
ryujinx-Release-1.0.0+e9819d0-win_x64
![imagem](https://user-images.githubusercontent.com/90729203/160289983-6b8554c6-1b3a-49fa-a9bc-810827856728.png)
[Ryujinx_1.1.0+e9819d0_2022-03-27_12-44-19.log](https://github.com/Ryujinx/Ryujinx/files/8357985/Ryujinx_1.1.0%2Be9819d0_2022-03-27_12-44-19.log)

2022-03-28 14:11 UTC, yell0wsuit commented
> both Vulkan and OpenGL Starlink with updates 1.05 and 1.06 give this error when starting the game (it only goes to the start menu), without the updates it starts and the videos are very slow

Not related to vulkan: https://github.com/Ryujinx/Ryujinx-Games-List/issues/88#issuecomment-855225568

2022-03-30 13:51 UTC, AlfredoDore commented
Ultra Age
before it was blinking a lot, but now it is more stable, once in a while the textures blink, it has a drop in performance 
Log file
[Ryujinx_1.1.0+e9819d0_2022-03-30_10-38-37.log](https://github.com/Ryujinx/Ryujinx/files/8381044/Ryujinx_1.1.0%2Be9819d0_2022-03-30_10-38-37.log)
Spec
ryujinx-Release-1.0.0+e9819d0-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.3.2
![imagem](https://user-images.githubusercontent.com/90729203/160850236-4d003887-9c4e-46e9-b6db-10cc4ed74557.png)

2022-04-09 01:57 UTC, gdkchan commented
I have enabled the SPIR-V backend by default for testing purposes now (faster shader compilation). If you tested the PR before and experience new issues not present on previous tests, please let me know.
If everything goes well, we can remove the shaderc dependency soon.

2022-04-09 13:16 UTC, AlfredoDore commented
Chrono Cross
it has slowness and font errors (has the same problem of slowness in Starlink FMVs)
Log file
[Ryujinx_1.1.0+cef6bcb_2022-04-09_09-58-45.log](https://github.com/Ryujinx/Ryujinx/files/8456981/Ryujinx_1.1.0%2Bcef6bcb_2022-04-09_09-58-45.log)
Spec
ryujinx-Release-1.0.0+cef6bcb-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162575215-85d76766-3ab4-428e-a312-90867a1dbbd9.png)
![imagem](https://user-images.githubusercontent.com/90729203/162575295-0a493efd-da9f-41d7-85f8-351d767bafba.png)
![imagem](https://user-images.githubusercontent.com/90729203/162575559-f5160db3-68ea-4662-8742-e3e6a7e0e3c8.png)

2022-04-09 13:26 UTC, AlfredoDore commented
Starlink
it now starts, but only goes to the ship selection
Log file
[Ryujinx_1.1.0+cef6bcb_2022-04-09_10-18-00.log](https://github.com/Ryujinx/Ryujinx/files/8457005/Ryujinx_1.1.0%2Bcef6bcb_2022-04-09_10-18-00.log)
Spec
ryujinx-Release-1.0.0+cef6bcb-win_x64
OS: Windows 10
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162575942-d5952228-a90f-4b29-a105-16d07444b145.png)

2022-04-09 13:34 UTC, Haronee commented
> Chrono Cross it has slowness and font errors (has the same problem of slowness in Starlink FMVs) Log file [Ryujinx_1.1.0+cef6bcb_2022-04-09_09-58-45.log](https://github.com/Ryujinx/Ryujinx/files/8456981/Ryujinx_1.1.0%2Bcef6bcb_2022-04-09_09-58-45.log) Spec ryujinx-Release-1.0.0+cef6bcb-win_x64 OS: Windows 10 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.4.1 ![imagem](https://user-images.githubusercontent.com/90729203/162575215-85d76766-3ab4-428e-a312-90867a1dbbd9.png) ![imagem](https://user-images.githubusercontent.com/90729203/162575295-0a493efd-da9f-41d7-85f8-351d767bafba.png) ![imagem](https://user-images.githubusercontent.com/90729203/162575559-f5160db3-68ea-4662-8742-e3e6a7e0e3c8.png)

Hi @AlfredoDore , thank you for your numerous reports, can you please verify if the issues you report **don't** occur on Ryujinx master before reporting them here?

Thanks.

2022-04-09 13:47 UTC, AlfredoDore commented
> Hi @AlfredoDore , thank you for your numerous reports, can you please verify if the issues you report **don't** occur on Ryujinx master before reporting them here?
> 
> Thanks.

In the beginning, Chrono Cross only goes to the menu, in Vulkan you can play (with big losses in income, but it works)

2022-04-09 13:53 UTC, Niwu34 commented
Hello @AlfredoDore,
we highly appreciate you testing this Vulkan PR as not many Ryujinx user are currently in the possession of an AMD gpu or don't have the time to test.
I think that you joining the official Ryujinx discord Server would make the testing/bug reporting process a lot easier: Many of the issues you report are also occurring on the Master branch and the developers are looking for specific Vulkan related issues!
We would be able to directly tell you which bugs are currently relevant and which games need further testing etc

2022-04-09 14:06 UTC, AlfredoDore commented
> Hello @AlfredoDore, we highly appreciate you testing this Vulkan PR as not many Ryujinx user are currently in the possession of an AMD gpu or don't have the time to test. I think that you joining the official Ryujinx discord Server would make the testing/bug reporting process a lot easier: Many of the issues you report are also occurring on the Master branch and the developers are looking for specific Vulkan related issues! We would be able to directly tell you which bugs are currently relevant and which games need further testing etc

I would like to help, my PC is all AMD

2022-04-09 14:08 UTC, Niwu34 commented
> I would like to help, my PC is all AMD

feel free to join, read the rules and verify that you read them - #Vulkan Testing Report should be ideal for your reports!
https://discord.gg/ryujinx

2022-04-09 14:08 UTC, MarkLanders777 commented
@AlfredoDore you can join to Ryujinx discord here https://discord.gg/ryujinx and report in the Vulkan report channel

2022-04-09 15:12 UTC, AlfredoDore commented
> @AlfredoDore you can join to Ryujinx discord here https://discord.gg/ryujinx and report in the Vulkan report channel
is this the same server?
![imagem](https://user-images.githubusercontent.com/90729203/162580024-e34ce8e4-a2cf-4a25-9eb3-e33b0767195d.png)

2022-04-09 15:14 UTC, MarkLanders777 commented
> > @AlfredoDore you can join to Ryujinx discord here https://discord.gg/ryujinx and report in the Vulkan report channel
> 
> is this the same server? ![imagem](https://user-images.githubusercontent.com/90729203/162580024-e34ce8e4-a2cf-4a25-9eb3-e33b0767195d.png)

Yes

2022-04-09 18:51 UTC, SomeoneIsWorking commented
Is it normal that ecfa0860c3108fe59f580505631d21db088e84b0 made no difference for me (visual glitches-wise)?
Not more or not less

2022-04-09 19:38 UTC, MutantAura commented
> Is it normal that [ecfa086](https://github.com/Ryujinx/Ryujinx/commit/ecfa0860c3108fe59f580505631d21db088e84b0) made no difference for me (visual glitches-wise)? Not more or not less

That's good news. It means that the new shader backend isn't providing any of it's own new issues :)

2022-04-09 19:54 UTC, SomeoneIsWorking commented
I'm building manually from this branch via `dotnet build -c Release -o build` and I just thought it's either not using SPIR-V or it was already using SPIR-V so one of those is the reason I'm not feeling any changes

2022-04-09 23:19 UTC, Nextking1986 commented
Good night. I would like to communicate that the Pokemon Sword and Shield game needs more performance, it is still not at the ideal speed which is 30 fps. The game still has some shadow bugs as shown in the image attached below.

My hardware:
- Radeon RX 560 OC 4GB
-  16 GB DE RAM
- Ryzen 5 1600 

Driver: 22.4.1

![Sem título](https://user-images.githubusercontent.com/102981461/162594680-db529238-3fae-4e23-a658-072a20600936.png)

[Ryujinx_1.1.0+b290ce1_2022-04-09_20-10-01.log](https://github.com/Ryujinx/Ryujinx/files/8457903/Ryujinx_1.1.0%2Bb290ce1_2022-04-09_20-10-01.log)

2022-04-09 23:27 UTC, MarkLanders777 commented
> Good night. I would like to communicate that the Pokemon Sword and Shield game needs more performance, it is still not at the ideal speed which is 30 fps. The game still has some shadow bugs as shown in the image attached below.
> 
> My hardware:
> 
> * Radeon RX 560 OC 4GB
> * 16 GB DE RAM
> * Ryzen 5 1600
> 
> Driver: 22.4.1
> 
> ![Sem título](https://user-images.githubusercontent.com/102981461/162594680-db529238-3fae-4e23-a658-072a20600936.png)
> 
> [Ryujinx_1.1.0+b290ce1_2022-04-09_20-10-01.log](https://github.com/Ryujinx/Ryujinx/files/8457903/Ryujinx_1.1.0%2Bb290ce1_2022-04-09_20-10-01.log)

Your CPU is too weak for emulating Switch games

2022-04-10 00:42 UTC, AlfredoDore commented
Crash Trylogi
Crash improved performance, but still has the problem of texture proportions and scenes are losing audio sync due to loss of performance
Log file
[Ryujinx_1.1.0+972356b_2022-04-09_21-28-51.log](https://github.com/Ryujinx/Ryujinx/files/8457997/Ryujinx_1.1.0%2B972356b_2022-04-09_21-28-51.log)
Spec
ryujinx-Release-1.0.0+972356b-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162596175-cfc844e8-1086-45db-8d2c-f617ca5d9dc3.png)
![imagem](https://user-images.githubusercontent.com/90729203/162596224-c7760067-8288-4fc1-8cf4-399bb2836649.png)
![imagem](https://user-images.githubusercontent.com/90729203/162596325-f13dd466-3552-4612-add9-00aa5df04646.png)

2022-04-10 02:50 UTC, benderscruffy commented
Pinball FX3 v1.0.11.0
messed up graphics
![ryujinx_capture_2022-04-10_10-45-09](https://user-images.githubusercontent.com/2696404/162599097-82f75f8f-bfb0-4f7f-8f18-c61b91cb9ce6.png)

2022-04-10 10:54 UTC, jojorne commented
The shadows being clamped based on camera angle has being fixed.

2022-04-10 18:47 UTC, Theslees commented
## Possible regresion due to recent commits
After recent commits to the build, Ryujinx began to crash on Vulkan backend when loading what seems to be a big mass amount of shaders at the same time; with the same error.

>  (Note;The error is not logged within Ryujinx's log files.)
> Examples in where the crash occurs; SMO loading a save, BoTW after save is loaded, PK Sword looking away from a > wall in the Wild Area and loading in many things at once, etc...

**System summary**
*linux5.17.1-arch1-1
AMD Ryzen 5 5600G (using Vega 8 iGPU)
Mesa 22.0.1
Ryujinx 1.1.0+2B972356b*

**log:**
[Ryujinx_1.1.0+972356b_2022-04-10_14-35-59.log](https://github.com/Ryujinx/Ryujinx/files/8459680/Ryujinx_1.1.0%2B972356b_2022-04-10_14-35-59.log)

**Error Snippet not shown in logs, after producing crash:**
```ACO ERROR:
    In file ../mesa-22.0.1/src/amd/compiler/aco_assembler.cpp:104
    Unsupported opcode:  s1: %8310:s[1],  s1: %8309:scc,  s1: %0:exec = s_and_saveexec_b32 %29:vcc, %0:exec
Aborted (core dumped)```

2022-04-10 19:10 UTC, DadSchoorse commented
a6e6213221c4e010c9c3dc352c4fc67f37cc3cf1 is pretty broken, you have to check VkPhysicalDeviceSubgroupSizeControlProperties. So only use a subgroup size of 32 if minSubgroupSize and maxSubgroupSize allow it and if the stage is included in requiredSubgroupSizeStages.

2022-04-10 19:49 UTC, gdkchan commented
> [a6e6213](https://github.com/Ryujinx/Ryujinx/commit/a6e6213221c4e010c9c3dc352c4fc67f37cc3cf1) is pretty broken, you have to check VkPhysicalDeviceSubgroupSizeControlProperties. So only use a subgroup size of 32 if minSubgroupSize and maxSubgroupSize allow it and if the stage is included in requiredSubgroupSizeStages.

Yes, technically the right thing to do here is checking if the subgroup size of 32 is supported. However, we don't have a fallback right now, so if that subgroup is not supported, then it is not going to render correctly anyway. I can add the check just in case there is some driver out there that would crash if an unsupported size is specified.

2022-04-10 19:52 UTC, DadSchoorse commented
> I can add the check just in case there is some driver out there that would crash if an unsupported size is specified.

The assert @TiggyDee reported is caused by this issue.

2022-04-10 21:06 UTC, gdkchan commented
> > I can add the check just in case there is some driver out there that would crash if an unsupported size is specified.
> 
> The assert @Theslees reported is caused by this issue.

Thanks for leting me know, it has been fixed now.

2022-04-10 21:19 UTC, gdkchan commented
> Crash Trylogi Crash improved performance, but still has the problem of texture proportions

Should be fixed.

2022-04-11 00:42 UTC, AlfredoDore commented
Super Mario Odyssey
there was a great improvement in performance, but there is still a drop in performance, when starting the game at it goes black and comes the audio and only then comes the video, in addition the textures flashperformance
Log file
[Ryujinx_1.1.0+d352773_2022-04-10_21-29-03.log](https://github.com/Ryujinx/Ryujinx/files/8460282/Ryujinx_1.1.0%2Bd352773_2022-04-10_21-29-03.log)
Spec
ryujinx-Release-1.0.0+d352773-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162647600-80257beb-a8d6-420a-854a-67031fd043bb.png)

2022-04-11 00:48 UTC, AlfredoDore commented
forgot to mention an error that is happening with the control, it is vibrating a lot and constant

2022-04-11 01:44 UTC, AlfredoDore commented
the performance gain is undeniable, in this part of the game before here on my PC it reached 30 fps and 14 fps when I had the T-Rex, but now there are only drops when there are certain explosions, also the textures flicker a lot and the control has improved more but needs more tweaking (it's vibrating a lot, getting to the point of being annoying)
![imagem](https://user-images.githubusercontent.com/90729203/162651222-1b6e3d14-472e-43b6-8133-82e6058f3d58.png)

2022-04-11 02:07 UTC, AlfredoDore commented
Mario Kart 8
there was a brutal improvement in performance, it's almost like the Cemu emulator (Wii U), I don't see any more flashing textures in this title, here the control is normal, you just need to fix the problem of it starting only once for each emulator update, this doesn't happen in Open GL
Log file
[Ryujinx_1.1.0+768202c_2022-04-10_22-48-55.log](https://github.com/Ryujinx/Ryujinx/files/8460529/Ryujinx_1.1.0%2B768202c_2022-04-10_22-48-55.log)
Spec
ryujinx-Release-1.0.0+768202c-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162652916-8756412c-0934-433c-bfca-bb44fd0abab0.png)

2022-04-11 13:46 UTC, GamerzHell9137 commented
Outstanding job on Vulkan so far!
I've tested most of my games and couldn't find anything wrong with it.
Mostly the game's either run better or same as OpenGL. There were some games that had a really big performance hit compared to OpenGL but I'm sure it will be fixed at some point in the future.

As for the issue that I've encountered:

1. Bravely Default II
```
-Softlocks really fast after getting into game with the console spamming

00:01:45.938 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:01:51.616 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:01:57.258 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:02:02.868 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:02:08.467 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
00:02:14.073 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.

```
2. Life is Strange True Colors

```
-Crashes after starting the game from the main menu, the console log shows a white message which is not saved in the logs

Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Ryujinx.Graphics.Vulkan.DescriptorSetCollection.UpdateImages(Int32, Int32, System.ReadOnlySpan`1<Silk.NET.Vulkan.DescriptorImageInfo>, Silk.NET.Vulkan.DescriptorType)
   at Ryujinx.Graphics.Vulkan.DescriptorSetUpdater.UpdateAndBindDescriptorSets(Ryujinx.Graphics.Vulkan.CommandBufferScoped, Silk.NET.Vulkan.PipelineBindPoint)
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(Silk.NET.Vulkan.PipelineBindPoint)
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32, Int32, Int32, Int32, Int32)
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper+<>c.<InitLookup>b__5_40(System.Span`1<Byte>, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
   at System.Threading.Thread.StartCallback()
```

3. When using the upscaler when SPIR V is enabled (default right now), some effects in games show broken (Either related to MSAA games or to #3240 )
```
Bubble Bobble 4 Friends - Transparent effect when a bubble breaks on the side of the screen
Rune Factory 5 - All transparent effects like Link attacks, monster spawn orbs, boss attack effects, special moves etc.
```

4. Rainbow texture corruption. I've talked about this one a lot on discord. It effect specific games due to low amount of VRAM possibly or the graphics cards drivers not being good for Vulkan (GTX 960 with 2 GB VRAM). Texture corruption happens once the 2 GB is exceeded, doubt it happens on 4GB or over since nobody reported it. Reverting d24c1a897610d50b26d1dff3bfd58e1741b5a215 doesn't cause the issue with the games noted below.

Affected games:
```
Asterix and Obelix
Rune Factory 5
Chocobo GP
No More Heroes 3
```

2022-04-11 14:47 UTC, AlfredoDore commented
> Outstanding job on Vulkan so far! I've tested most of my games and couldn't find anything wrong with it. Mostly the game's either run better or same as OpenGL. There were some games that had a really big performance hit compared to OpenGL but I'm sure it will be fixed at some point in the future.
> 
> As for the issue that I've encountered:
> 
>     1. Bravely Default II
> 
> 
> ```
> -Softlocks really fast after getting into game with the console spamming
> 
> 00:01:45.938 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:01:51.616 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:01:57.258 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:02:02.868 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:02:08.467 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:02:14.073 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> ```
> 
>     2. Life is Strange True Colors
> 
> 
> ```
> -Crashes after starting the game from the main menu, the console log shows a white message which is not saved in the logs
> 
> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Ryujinx.Graphics.Vulkan.DescriptorSetCollection.UpdateImages(Int32, Int32, System.ReadOnlySpan`1<Silk.NET.Vulkan.DescriptorImageInfo>, Silk.NET.Vulkan.DescriptorType)
>    at Ryujinx.Graphics.Vulkan.DescriptorSetUpdater.UpdateAndBindDescriptorSets(Ryujinx.Graphics.Vulkan.CommandBufferScoped, Silk.NET.Vulkan.PipelineBindPoint)
>    at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(Silk.NET.Vulkan.PipelineBindPoint)
>    at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32, Int32, Int32, Int32, Int32)
>    at Ryujinx.Graphics.GAL.Multithreading.CommandHelper+<>c.<InitLookup>b__5_40(System.Span`1<Byte>, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
>    at System.Threading.Thread.StartCallback()
> ```
> 
>     3. When using the upscaler when SPIR V is enabled (default right now), some effects in games show broken (Either related to MSAA games or to games using [Fix shader textureSize with multisample and buffer textures #3240](https://github.com/Ryujinx/Ryujinx/pull/3240) )
> 
> 
> ```
> Bubble Bobble 4 Friends - Transparent effect when a bubble breaks on the side of the screen
> Rune Factory 5 - All transparent effects like Link attacks, monster spawn orbs, boss attack effects, special moves etc.
> ```
> 
>     4. Rainbow texture corruption. I've talked about this one a lot on discord. It effect specific games due to low amount of VRAM possibly or the graphics cards drivers not being good for Vulkan (GTX 960 with 2 GB VRAM). Texture corruption happens once the 2 GB is exceeded, doubt it happens on 4GB or over since nobody reported it. Reverting [d24c1a8](https://github.com/Ryujinx/Ryujinx/commit/d24c1a897610d50b26d1dff3bfd58e1741b5a215) doesn't cause the issue with the games noted below.
> 
> 
> Affected games:
> 
> ```
> Asterix and Obelix
> Rune Factory 5
> Chocobo GP
> No More Heroes 3
> Mario Golf
> ```

there is a game that is only working on Vulkan, the work is really good, but it still needs to improve, like the textures proportions of Crash Trilogy

2022-04-11 14:49 UTC, gdkchan commented
> there is a game that is only working on Vulkan, the work is really good, but it still needs to improve, like the textures proportions of Crash Trilogy

Have you tried it on the latest version? Because the Crash issues should be fixed already.

2022-04-11 14:54 UTC, AlfredoDore commented
> 

I'm going to test it now, I'm just waiting for Bullet's Storm to finish (it's one of the ones I reported a long time ago and I want to check how it turned out now)

2022-04-11 15:15 UTC, AlfredoDore commented
Crash
the proportions are now correct, it is now necessary to improve the performance that has drops
Log file
[Ryujinx_1.1.0+768202c_2022-04-11_12-02-42.log](https://github.com/Ryujinx/Ryujinx/files/8465358/Ryujinx_1.1.0%2B768202c_2022-04-11_12-02-42.log)


Spec
ryujinx-Release-1.0.0+768202c-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162770125-1626b05b-dcd5-4418-9f54-cd039394b969.png)

2022-04-11 15:24 UTC, gdkchan commented
I have now enabled the shader cache on Vulkan for testing purposes. Please let me know if there's anything wrong with it. Some things to note:
- Version was changed, so it will cause invalidation of existing caches (old shader cache is *not* affected).
- Migration from the old shader cache was disabled because Vulkan adds a lot of new state to the cache, so most of the migrated shaders would be unused (or could introduce minor stuttering due to pipeline state not matching). So I have disabled it to force a fresh start.
- Cache files are shared between Vulkan and OpenGL backends. So for example you can Switch from OpenGL to Vulkan and vice-versa, and it will be able to use the same shader cache. The host shader binary, of course, will be different, so it will recompile from guest as needed.
- On Vulkan, it stores raw SPIR-V binaries rather than pipeline caches. This means that changing the GPU or driver does *not* require a full recompile.
- Shader compilation when loading from the cache is already multithreaded, just like OpenGL. And in-game compilation is already also multithreaded, of course.

2022-04-11 15:41 UTC, MutantAura commented
Seeing a fair few:
> TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
In multiple titles. Log below is an SSBU match (same stage and 4 characters as a previous run) which starts at 1 minute in the log.
[Ryujinx_1.0.0-dirty_2022-04-11_16-33-21.log](https://github.com/Ryujinx/Ryujinx/files/8465618/Ryujinx_1.0.0-dirty_2022-04-11_16-33-21.log)

Seems to need to recompile if this misses?

2022-04-11 15:42 UTC, AlfredoDore commented
Animal Crossing
the proportions are now correct, it is now necessary to improve the performance that has drops
Log file
[Ryujinx_1.1.0+0e42b21_2022-04-11_12-40-06.log](https://github.com/Ryujinx/Ryujinx/files/8465630/Ryujinx_1.1.0%2B0e42b21_2022-04-11_12-40-06.log)
closes when opening the game
Spec
ryujinx-Release-1.0.0+0e42b21-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1

2022-04-11 15:55 UTC, AlfredoDore commented
Donkey Kong Country Tropical Freeze
he has these lines and the enemies death animation disappears
Log file
[Ryujinx_1.1.0+0e42b21_2022-04-11_12-43-08.log](https://github.com/Ryujinx/Ryujinx/files/8465721/Ryujinx_1.1.0%2B0e42b21_2022-04-11_12-43-08.log)

Spec
ryujinx-Release-1.1.0+0e42b21-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162779362-6ab5849e-17e2-4105-8817-1e7f9f6c8412.png)
![imagem](https://user-images.githubusercontent.com/90729203/162779699-bd17a950-413f-4de1-886a-df2546acdcbf.png)
![imagem](https://user-images.githubusercontent.com/90729203/162780778-31f21ea6-724a-4e4f-97b3-6b5cd2f4a39d.png)

2022-04-11 16:17 UTC, AlfredoDore commented
Super Mario Odyssey
constant fps with a small drop in fps, textures are flickering and during presentations the controller vibrates like crazy, no longer during the game
Log file
[Ryujinx_1.1.0+0e42b21_2022-04-11_12-57-02.log](https://github.com/Ryujinx/Ryujinx/files/8465983/Ryujinx_1.1.0%2B0e42b21_2022-04-11_12-57-02.log)


Spec
ryujinx-Release-1.1.0+0e42b21-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162783952-009263d2-0ac0-481f-94ef-bfafbf066558.png)
![imagem](https://user-images.githubusercontent.com/90729203/162785103-a2f97f36-f15e-4d0c-a585-9ab273dd37e9.png)

2022-04-11 16:26 UTC, AlfredoDore commented
Starlink
video playback is very slow and there are grains on the screen, with the update it is now possible to select the character but not start the game
Log file
[Ryujinx_1.1.0+0e42b21_2022-04-11_13-17-42.log](https://github.com/Ryujinx/Ryujinx/files/8466048/Ryujinx_1.1.0%2B0e42b21_2022-04-11_13-17-42.log)
Spec
ryujinx-Release-1.1.0+0e42b21-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162785642-187ef189-17a0-4cf1-8cad-3891c6231566.png)
![imagem](https://user-images.githubusercontent.com/90729203/162785927-78ec6699-ef44-4b51-a155-573afd134cd5.png)

2022-04-11 16:38 UTC, AlfredoDore commented
Ultra Age
the textures barely flicker (if you don't look at it properly or notice it) there are also performance losses
Log file
[Ryujinx_1.1.0+0e42b21_2022-04-11_13-28-59.log](https://github.com/Ryujinx/Ryujinx/files/8466115/Ryujinx_1.1.0%2B0e42b21_2022-04-11_13-28-59.log)
Spec
ryujinx-Release-1.1.0+0e42b21-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162788398-243fc1dc-d8e6-4772-9f80-df2330d68248.png)

2022-04-12 00:36 UTC, AlfredoDore commented
BULLETSTORM: DUKE OF SWITCH EDITION
performance has improved a lot, but there are texture problems (they flash too, in addition to some black textures), small drops in performance and it arrives after the second part of the game when leaving the ship the game simply closes
Log file
[Ryujinx_1.1.0+088ee71_2022-04-11_21-10-24.log](https://github.com/Ryujinx/Ryujinx/files/8468599/Ryujinx_1.1.0%2B088ee71_2022-04-11_21-10-24.log)
Spec
ryujinx-Release-1.1.0+088ee71-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/162853639-fa609298-8ae6-44b2-90be-65d837a4b0f0.png)
![imagem](https://user-images.githubusercontent.com/90729203/162853832-cbbc6c5e-7c30-4ad3-b5be-f80200073357.png)
![imagem](https://user-images.githubusercontent.com/90729203/162853933-ddac3ee3-f22a-4e22-9536-c5087d7d498b.png)
![imagem](https://user-images.githubusercontent.com/90729203/162854909-769326b8-9a24-4ede-b3cc-4a7035c06f15.png)

2022-04-12 13:25 UTC, AlfredoDore commented
> @AlfredoDore For all future reports, can you please include a video example of specific issues that you're encountering. You've repeatedly mentioned "flickering textures" that no one else seems to have, and you don't provide any examples or information for us to look into this further. No one really has any idea what "flickering textures" means.

I'm going to record a video, it's just that they keep disappearing and appearing, I can barely take a screenshot

2022-04-12 13:27 UTC, AlfredoDore commented
> @AlfredoDore For all future reports, can you please include a video example of specific issues that you're encountering. You've repeatedly mentioned "flickering textures" that no one else seems to have, and you don't provide any examples or information for us to look into this further. No one really has any idea what "flickering textures" means.

this was one that I managed to take a print, but I'm going to record a video of it
![Mario erro](https://user-images.githubusercontent.com/90729203/162972875-4e15f21c-f5ff-4919-9096-a720552abdd2.png)

2022-04-12 17:22 UTC, MutantAura commented
It's been hard to find _anything_ broken on NV which is amazing! Only issues I've run into are in two titles.

Witcher 3:
![image](https://user-images.githubusercontent.com/44103205/163017242-fcaf7b8f-847a-4687-b161-a913e1843322.png)
Ground and various other textures appear to be missing and for some reason if I run away from this spot I can consistently trigger an "ErrorDeviceLost" crash (see log if useful)
[Ryujinx_1.0.0-dirty_2022-04-12_18-13-18.log](https://github.com/Ryujinx/Ryujinx/files/8475077/Ryujinx_1.0.0-dirty_2022-04-12_18-13-18.log)

OGL reference image: 
![image](https://user-images.githubusercontent.com/44103205/163018144-e0e1d923-780b-4450-bcec-ad1ab3f90075.png)

Bastion:
![image](https://user-images.githubusercontent.com/44103205/163018506-435333b3-bc6c-4e78-b485-9f39a82bc8df.png)
![image](https://user-images.githubusercontent.com/44103205/163018788-0df035a1-cc21-4d7e-8bc2-7d3d29d12d20.png)

Menu is black and in-game does not really render at all. Both OGL and VK show this issue but _not_ current master.

Master reference image:
![image](https://user-images.githubusercontent.com/44103205/163018962-fd923ee3-7480-4c51-8803-6a0d96c9f50a.png)

Other than this I'm completely out of issues. :)

2022-04-12 19:11 UTC, AlfredoDore commented
Super Mario Odyssey
textures keep flickering (don't know the technical name of this) the speed is wonderful, just need to improve that beginning that has a black screen and the sound comes before the video
Log file
[Ryujinx_1.1.0+54260f2_2022-04-12_15-58-17.log](https://github.com/Ryujinx/Ryujinx/files/8475812/Ryujinx_1.1.0%2B54260f2_2022-04-12_15-58-17.log)

Spec
Ryujinx_1.1.0+54260f2 windows 64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
https://streamable.com/jrk8he

2022-04-12 19:17 UTC, MetrosexualGarbodor commented
@AlfredoDore No one else seems to have that flickering issue. Perhaps you should try using DDU and doing a clean reinstall of your AMD drivers, because it really looks like something on your end.

2022-04-12 19:24 UTC, AlfredoDore commented
Zelda Link's Awakerning
although the performance has improved, there is still a lot of variation in fps, and the water still has this problem
Log file
[Ryujinx_1.1.0+54260f2_2022-04-12_16-13-14.log](https://github.com/Ryujinx/Ryujinx/files/8475915/Ryujinx_1.1.0%2B54260f2_2022-04-12_16-13-14.log)


Spec
Ryujinx_1.1.0+54260f2 windows 64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/163037084-44481fba-7c25-4e11-94c9-b36fa64d136e.png)
![imagem](https://user-images.githubusercontent.com/90729203/163037762-0ec39e2a-83e2-4a23-b359-e54e0a3ab39f.png)

2022-04-12 19:29 UTC, AlfredoDore commented
> @AlfredoDore No one else seems to have that flickering issue. Perhaps you should try using DDU and doing a clean reinstall of your AMD drivers, because it really looks like something on your end.

I don't think it's my drivers, but I'll install them then

2022-04-12 20:12 UTC, AlfredoDore commented
> @AlfredoDore No one else seems to have that flickering issue. Perhaps you should try using DDU and doing a clean reinstall of your AMD drivers, because it really looks like something on your end.

I cleaned and reinstalled, the same problem appeared.
https://streamable.com/ur2szb

2022-04-12 20:17 UTC, AlfredoDore commented
The only difference I saw was a decrease in the flashing frequency, but it keeps flashing

2022-04-12 20:48 UTC, rgbarros120 commented
Super Mario Odyssey is performing excellently. But the textures in the game keep flickering all the time.

My SPECS:
RADEON RX 560 OC 4GB
16GB DE RAM
RYZEN 5 1600 SIX CORE

DRIVER 22.3.1

https://www.youtube.com/shorts/rYFH8KLXdsU

[Ryujinx_1.1.0+54260f2_2022-04-12_17-46-11.log](https://github.com/Ryujinx/Ryujinx/files/8476440/Ryujinx_1.1.0%2B54260f2_2022-04-12_17-46-11.log)

2022-04-12 21:06 UTC, AlfredoDore commented
Mario Kart 8
is performing very well, but with small drops (mainly in effects like explosions) and has these dark shadows in the celetion of characters, but when selecting the kart it is normal
Log file
[Ryujinx_1.1.0+93ee66a_2022-04-12_17-51-45.log](https://github.com/Ryujinx/Ryujinx/files/8476553/Ryujinx_1.1.0%2B93ee66a_2022-04-12_17-51-45.log)
Spec
ryujinx-Release-1.0.0+93ee66a-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/163052980-166f568b-75b5-4daa-813b-8c8ff927554a.png)
![imagem](https://user-images.githubusercontent.com/90729203/163053456-0d4916c5-acc0-4616-852d-6a9f1af05eaf.png)

2022-04-12 22:15 UTC, rgbarros120 commented
The game Atelier Sophie 2 is not starting correctly, it is on a reading screen as in the picture above and does not arrive at the game's menu screen and the emulator simply closes out of nowhere.

My SPECS:
RADEON RX 560 OC 4GB
16GB DE RAM
RYZEN 5 1600 SIX CORE

DRIVER 22.3.1

![Sem título](https://user-images.githubusercontent.com/73244003/163063655-07b5c6a8-93af-45d6-be2e-a266ef908a84.png)

[Ryujinx_1.1.0+93ee66a_2022-04-12_19-11-26.log](https://github.com/Ryujinx/Ryujinx/files/8476898/Ryujinx_1.1.0%2B93ee66a_2022-04-12_19-11-26.log)

2022-04-12 22:29 UTC, GamerzHell9137 commented
> Outstanding job on Vulkan so far! I've tested most of my games and couldn't find anything wrong with it. Mostly the game's either run better or same as OpenGL. There were some games that had a really big performance hit compared to OpenGL but I'm sure it will be fixed at some point in the future.
> 
> As for the issue that I've encountered:
> 
>     1. Bravely Default II
> 
> 
> ```
> -Softlocks really fast after getting into game with the console spamming
> 
> 00:01:45.938 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:01:51.616 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:01:57.258 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:02:02.868 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:02:08.467 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> 00:02:14.073 |E| Gpu AwaitResult: Error: Query result SamplesPassed timed out. Took more than 5000 tries.
> ```
> 
>     2. Life is Strange True Colors
> 
> 
> ```
> -Crashes after starting the game from the main menu, the console log shows a white message which is not saved in the logs
> 
> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at Ryujinx.Graphics.Vulkan.DescriptorSetCollection.UpdateImages(Int32, Int32, System.ReadOnlySpan`1<Silk.NET.Vulkan.DescriptorImageInfo>, Silk.NET.Vulkan.DescriptorType)
>    at Ryujinx.Graphics.Vulkan.DescriptorSetUpdater.UpdateAndBindDescriptorSets(Ryujinx.Graphics.Vulkan.CommandBufferScoped, Silk.NET.Vulkan.PipelineBindPoint)
>    at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(Silk.NET.Vulkan.PipelineBindPoint)
>    at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32, Int32, Int32, Int32, Int32)
>    at Ryujinx.Graphics.GAL.Multithreading.CommandHelper+<>c.<InitLookup>b__5_40(System.Span`1<Byte>, Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer, Ryujinx.Graphics.GAL.IRenderer)
>    at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop()
>    at System.Threading.Thread.StartCallback()
> ```
> 
>     3. When using the upscaler when SPIR V is enabled (default right now), some effects in games show broken (Either related to MSAA games or to games using [Fix shader textureSize with multisample and buffer textures #3240](https://github.com/Ryujinx/Ryujinx/pull/3240) )
> 
> 
> ```
> Bubble Bobble 4 Friends - Transparent effect when a bubble breaks on the side of the screen
> Rune Factory 5 - All transparent effects like Link attacks, monster spawn orbs, boss attack effects, special moves etc.
> ```
> 
>     4. Rainbow texture corruption. I've talked about this one a lot on discord. It effect specific games due to low amount of VRAM possibly or the graphics cards drivers not being good for Vulkan (GTX 960 with 2 GB VRAM). Texture corruption happens once the 2 GB is exceeded, doubt it happens on 4GB or over since nobody reported it. Reverting [d24c1a8](https://github.com/Ryujinx/Ryujinx/commit/d24c1a897610d50b26d1dff3bfd58e1741b5a215) doesn't cause the issue with the games noted below.
> 
> 
> Affected games:
> 
> ```
> Asterix and Obelix
> Rune Factory 5
> Chocobo GP
> No More Heroes 3
> Mario Golf
> ```

With the latest changes Life is Strange True Colors and Bravely Default II are booting.

2022-04-13 00:14 UTC, Squall-Leonhart commented
> @AlfredoDore No one else seems to have that flickering issue. Perhaps you should try using DDU and doing a clean reinstall of your AMD drivers, because it really looks like something on your end.

Either the RX 500's have a driver issue that isn't affecting newer parts, or Reshade is involved

evidence to the former is that Xplane vulkan has such an issue on RX 500's, 

Being on the latest AMD driver is usually not the best idea with 2 architecture generation old parts.

2022-04-13 00:19 UTC, AlfredoDore commented
> 

I'm solving this, testing one and the other, I already give an answer

2022-04-13 01:05 UTC, AlfredoDore commented
> > @AlfredoDore No one else seems to have that flickering issue. Perhaps you should try using DDU and doing a clean reinstall of your AMD drivers, because it really looks like something on your end.
> 
> Either the RX 500's have a driver issue that isn't affecting newer parts, or Reshade is involved
> 
> evidence to the former is that Xplane vulkan has such an issue on RX 500's,
> 
> Being on the latest AMD driver is usually not the best idea with 2 architecture generation old parts.


I regressed my drives and removed the reshad, still the same thing (this is the current version of Ryujinx test)
https://streamable.com/xn1r4t

2022-04-13 01:32 UTC, AlfredoDore commented
> > @AlfredoDore No one else seems to have that flickering issue. Perhaps you should try using DDU and doing a clean reinstall of your AMD drivers, because it really looks like something on your end.
> 
> Either the RX 500's have a driver issue that isn't affecting newer parts, or Reshade is involved
> 
> evidence to the former is that Xplane vulkan has such an issue on RX 500's,
> 
> Being on the latest AMD driver is usually not the best idea with 2 architecture generation old parts.

Martio Kart 8 https://streamable.com/84vkb5 do not have this problem, this problem presents more in Unreal games, which sometimes I stop to think if Mario Odyssey is not Unreal Engine

2022-04-13 12:19 UTC, rgbarros120 commented
Mario kart 8 deluxe is still showing dark shadows bug when selecting characters. Needs repair immediately.

My specs:
RADEON RX 560 OC 4GB
16 GB DE RAM (2400MHZ)
RYZEN 5 1600 SIX CORE

![Sem título](https://user-images.githubusercontent.com/73244003/163178291-788606f2-96fd-495b-a62f-d18adb968a20.png)

[Ryujinx_1.1.0+93ee66a_2022-04-13_09-13-55.log](https://github.com/Ryujinx/Ryujinx/files/8481321/Ryujinx_1.1.0%2B93ee66a_2022-04-13_09-13-55.log)

2022-04-13 12:56 UTC, Haronee commented
I can confirm @AlfredoDore 's issues on SMO are real, here's footage

https://user-images.githubusercontent.com/53187465/163184446-001e2cd1-09ec-4012-999b-d86920bda6b3.mp4

And I can also confirm @rgbarros120 's issue on MK8DX are also happening on my AMD system
![image](https://user-images.githubusercontent.com/53187465/163184745-fc27d354-7ccb-474f-ae2e-e9817c1ea14f.png)

Tested on an RX570 on drivers 22.4.1 on Windows

2022-04-13 13:37 UTC, Haronee commented
Mario Tennis Aces crashes after the opening cutscene with no error in the log, this issue doesn't happen on OpenGL. I tried with update 3.1.0 and with the base game (since they changed the cutscene with the update) but it crashes in both cases.

This issue doesn't exist on Nvidia, I checked.

Screenshot of OpenGL working after the cutscene
![image](https://user-images.githubusercontent.com/53187465/163192818-f9fd19ff-bd13-4959-b5cf-7eab552e9ec6.png)


Here's the log in case you need it
[Ryujinx_1.1.0+078f26b_2022-04-13_15-24-56.log](https://github.com/Ryujinx/Ryujinx/files/8481876/Ryujinx_1.1.0%2B078f26b_2022-04-13_15-24-56.log)

2022-04-13 18:36 UTC, SomeoneIsWorking commented
> I can confirm @AlfredoDore 's issues on SMO are real, here's footage

I also have both these issues. Extremely surprised that collaborators claim that no one has them.

2022-04-13 18:50 UTC, riperiperi commented
If you've been having this issue all along, posting a video of it any time in the past few months might have helped more than the 25 unhelpful static screenshots which obviously can't show flickering. I think the skepticism was justified.

The same really goes for any issues with performance or block flickering. We can't really identify motion issues from static screenshots, and it's easier to identify even static issues when given a view of the game in motion.

2022-04-13 19:55 UTC, AlfredoDore commented
Haven
with the update the game is closing, in addition it needs performance (it has a drop in video playback and loading) but graphically it is like on the console (as I reported last time it was possible to continue the game until the end) now it starts but closes
Log file
[Ryujinx_1.1.0+078f26b_2022-04-13_16-31-27.log](https://github.com/Ryujinx/Ryujinx/files/8484217/Ryujinx_1.1.0%2B078f26b_2022-04-13_16-31-27.log)
Spec
ryujinx-Release-1.1.0+078f26b-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1

2022-04-13 22:23 UTC, Mario9699 commented
eBaseball Powerful Pro Yakyuu 2020 is showing dark shadows bug
![未命名](https://user-images.githubusercontent.com/103609670/163279628-0bf26cc8-89f7-4f00-939b-9fe128d0dcfa.png)
[Ryujinx_1.1.0+078f26b_2022-04-14_06-01-40.log](https://github.com/Ryujinx/Ryujinx/files/8484996/Ryujinx_1.1.0%2B078f26b_2022-04-14_06-01-40.log)

2022-04-14 01:26 UTC, AlfredoDore commented
Resident Evil 0
graphically it's excellent, just like the console, the only problem is just a small drop in performance when shooting or some big explosion action (RE 1 also has the same problem)
Log file
[Ryujinx_1.1.0+efaa296_2022-04-13_22-15-53.log](https://github.com/Ryujinx/Ryujinx/files/8485613/Ryujinx_1.1.0%2Befaa296_2022-04-13_22-15-53.log)
Spec
ryujinx-Release-1.1.0+efaa296-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
https://streamable.com/o5py7h

2022-04-14 02:00 UTC, Haronee commented
> > I can confirm @AlfredoDore 's issues on SMO are real, here's footage
> 
> I also have both these issues. Extremely surprised that collaborators claim that no one has them.

This issue seems to be limited to Polaris GPUs on Windows, meaning other AMD GPU users on other architectures did not experience it, which could have led some to claim it wasn't an AMD issue, hence the confusion.

2022-04-14 12:39 UTC, Mario9699 commented
eBaseball Powerful Pro Yakyuu 2020 is not fix Broken figure bug
![未命名](https://user-images.githubusercontent.com/103609670/163392042-4e93dc7c-1861-47ee-9c90-9e2ad16a5af1.png)
[Ryujinx_1.1.0+e9d43b4_2022-04-14_20-30-05.log](https://github.com/Ryujinx/Ryujinx/files/8489196/Ryujinx_1.1.0%2Be9d43b4_2022-04-14_20-30-05.log)

2022-04-14 12:46 UTC, MutantAura commented
> eBaseball Powerful Pro Yakyuu 2020 is not fix Broken figure bug ![未命名](https://user-images.githubusercontent.com/103609670/163392042-4e93dc7c-1861-47ee-9c90-9e2ad16a5af1.png) [Ryujinx_1.1.0+e9d43b4_2022-04-14_20-30-05.log](https://github.com/Ryujinx/Ryujinx/files/8489196/Ryujinx_1.1.0%2Be9d43b4_2022-04-14_20-30-05.log)

You reported this less than 24 hours ago. I've marked this as spam so please don't repeatedly post the same issues as they will not get looked at any faster. Unless a developer informs you that a change should affect a particular game then it likely will not fix your particular issue. Also please check that this does not occur on master before posting and add that information to your original report. You have an NVIDIA GPU so this should be your first check.

2022-04-14 15:12 UTC, AlfredoDore commented
> > > I can confirm @AlfredoDore 's issues on SMO are real, here's footage
> > 
> > 
> > I also have both these issues. Extremely surprised that collaborators claim that no one has them.
> 
> This issue seems to be limited to Polaris GPUs on Windows, meaning other AMD GPU users on other architectures did not experience it, which could have led some to claim it wasn't an AMD issue, hence the confusion.

as for textures flickering in Mario Odyssey, it doesn't happen in OpenGL https://vimeo.com/699474850

2022-04-14 23:45 UTC, AlfredoDore commented
Cadence of Hyrule
there is a loss of performance, in the open world the game is supposed to be at 60 fps, but it is stuck at 33 and in closed environments it is at 60 fps
Log file
[Ryujinx_1.1.0+e9d43b4_2022-04-14_20-36-04.log](https://github.com/Ryujinx/Ryujinx/files/8492889/Ryujinx_1.1.0%2Be9d43b4_2022-04-14_20-36-04.log)
Spec
ryujinx-Release-1.0.0+e9d43b4-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
https://streamable.com/rtl5gy

2022-04-14 23:55 UTC, AlfredoDore commented
Sonic Colours Ultimate 
takes time to start and does not go beyond the game menu, the emulator closes when starting, in addition to several performance drops in the menu
Log file
[Ryujinx_1.1.0+e9d43b4_2022-04-14_20-51-02.log](https://github.com/Ryujinx/Ryujinx/files/8492908/Ryujinx_1.1.0%2Be9d43b4_2022-04-14_20-51-02.log)
Spec
ryujinx-Release-1.0.0+e9d43b4-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1

2022-04-15 00:11 UTC, AlfredoDore commented
Zelda Link's Awakerning
the fps rate needs to improve, it's very fickle, plus this water texture issue: https://streamable.com/f3f7vm
Log file
[Ryujinx_1.1.0+e9d43b4_2022-04-14_21-00-21.log](https://github.com/Ryujinx/Ryujinx/files/8492956/Ryujinx_1.1.0%2Be9d43b4_2022-04-14_21-00-21.log)
Spec
ryujinx-Release-1.0.0+e9d43b4-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/163495613-fa0d2a93-fc02-45ed-bd4a-9ec4210d32df.png)

2022-04-15 12:45 UTC, voldemort2826 commented
> the fps rate needs to improve, it's very fickle

This is by design of the game on real Switch. Or it's a possibility your CPU is not powerful enough to keep the framerate stable.

2022-04-15 14:17 UTC, RMED24 commented
Game: Super Mario 3D All Stars
CPU: Ryzen 5 5600x
GPU: AMD RX 6600 XT (mesa 22.1.0-devel and RADV)
OS: EndeavourOS

The info is in the log but I launch 3d all stars, select super mario sunshine and get:
.NET ThreadPool Worker Gpu ConvertToVkFormat: Format S8UintD24Unorm is not supported by the host.

Apparently this is an unknown issue and occurs on multiple of the vulkan builds

[Ryujinx_1.1.0+325f66d_2022-04-15_14-07-05.log](https://github.com/Ryujinx/Ryujinx/files/8496049/Ryujinx_1.1.0%2B325f66d_2022-04-15_14-07-05.log)

2022-04-15 14:21 UTC, Squall-Leonhart commented
VK_FORMAT_D24_UNORM_S8_UINT is not supported by RADV

2022-04-15 14:22 UTC, Mario9699 commented
eBaseball Powerful Pro Yakyuu 2020 have words are missing bug
![未命名](https://user-images.githubusercontent.com/103609670/163582156-60d393e1-f6a1-48a2-a5d8-b4054db9722f.png)
[Ryujinx_1.1.0+325f66d_2022-04-15_21-56-07.log](https://github.com/Ryujinx/Ryujinx/files/8496419/Ryujinx_1.1.0%2B325f66d_2022-04-15_21-56-07.log)

2022-04-15 14:22 UTC, AlfredoDore commented
> This is by design of the game on real Switch. Or it's a possibility your CPU is not powerful enough to keep the framerate stable.

it is 60 fps on Switch and my PC supports Switch, just watch the video I recorded Mario Kart

2022-04-15 14:25 UTC, gdkchan commented
> Game: Super Mario 3D All Stars CPU: Ryzen 5 5600x GPU: AMD RX 6600 XT (mesa 22.1.0-devel and RADV) OS: EndeavourOS
> 
> The info is in the log but I launch 3d all stars, select super mario sunshine and get: .NET ThreadPool Worker Gpu ConvertToVkFormat: Format S8UintD24Unorm is not supported by the host.

AMD does not support D24S8 formats, we need to emulate S8D24 with D32FS8 like we did for D24S8.

2022-04-15 15:25 UTC, AlfredoDore commented
SUPER MARIO ODYSSEY
the frequency at which textures flicker has decreased, also has a small drop in yield: https://streamable.com/crq9al
Log file
[Ryujinx_1.1.0+325f66d_2022-04-15_12-13-23.log](https://github.com/Ryujinx/Ryujinx/files/8496699/Ryujinx_1.1.0%2B325f66d_2022-04-15_12-13-23.log)
Spec
ryujinx-Release-1.1.0+325f66d-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1

2022-04-15 16:50 UTC, AlfredoDore commented
Haven
on Vulkan the game just starts, on the main one (OpenGL) the game progresses normally
Log file
[Ryujinx_1.1.0+325f66d_2022-04-15_12-10-33.log](https://github.com/Ryujinx/Ryujinx/files/8497013/Ryujinx_1.1.0%2B325f66d_2022-04-15_12-10-33.log)
Spec
ryujinx-Release-1.1.0+325f66d-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1

2022-04-16 23:06 UTC, Mario9699 commented
eBaseball Powerful Pro Yakyuu 2020 have bug
![未命名](https://user-images.githubusercontent.com/103609670/163693796-51c97d35-d51b-47a5-9441-786cab95868b.png)
[Ryujinx_1.1.0+8e28f86_2022-04-17_06-24-11.log](https://github.com/Ryujinx/Ryujinx/files/8500748/Ryujinx_1.1.0%2B8e28f86_2022-04-17_06-24-11.log)

2022-04-18 13:34 UTC, rgbarros120 commented
Mario Kart 8 deluxe the dark shadows bug still persists in the choice of characters. Needs repair immediately.

My specs:
RADEON RX 560 OC 4GB
16 GB DE RAM (2400mhz)
RYZEN 5 1600

DRIVER: 22.3.1

![Sem título 2](https://user-images.githubusercontent.com/73244003/163815733-e282925a-109f-4b30-8a99-64991828c7c3.png)
![Sem título](https://user-images.githubusercontent.com/73244003/163815741-3c342b74-060c-432b-bef4-10b817f108d6.png)

[Ryujinx_1.1.0+8e28f86_2022-04-18_10-27-52.log](https://github.com/Ryujinx/Ryujinx/files/8505928/Ryujinx_1.1.0%2B8e28f86_2022-04-18_10-27-52.log)

2022-04-18 13:46 UTC, rgbarros120 commented
Donkey Kong Tropical Freeze. The Donkey Kong character is showing a graphic bug, as shown in the picture below. Needs repair immediately.

My specs:
RADEON RX 560 OC 4GB
16 GB DE RAM (2400mhz)
RYZEN 5 1600

DRIVER: 22.3.1

![Sem título](https://user-images.githubusercontent.com/73244003/163817251-ac602d93-edf3-41b1-86c1-5182fdf78a14.png)

[Ryujinx_1.1.0+8e28f86_2022-04-18_10-42-15.log](https://github.com/Ryujinx/Ryujinx/files/8505996/Ryujinx_1.1.0%2B8e28f86_2022-04-18_10-42-15.log)

2022-04-18 15:18 UTC, rgbarros120 commented
Pokemon Sword needs to improve performance more, such as hammerlock, motoshoke and Wyndon. Some bugs still persist in the game, such as shadows and lights too.

My specs:
RADEON RX 560 OC 4GB
16 GB DE RAM (2400mhz)
RYZEN 5 1600

DRIVER: 22.3.1

![Sem título](https://user-images.githubusercontent.com/73244003/163830230-8f8c3ece-548b-4df2-a45f-197e5c120246.png)
![Sem título 2](https://user-images.githubusercontent.com/73244003/163830253-85ed6830-3e7d-4100-ae2b-91222261df69.png)
![Sem título 3](https://user-images.githubusercontent.com/73244003/163830271-2fbf8921-902c-4764-8ab0-276c3195de3a.png)

[Ryujinx_1.1.0+8e28f86_2022-04-18_12-11-02.log](https://github.com/Ryujinx/Ryujinx/files/8506510/Ryujinx_1.1.0%2B8e28f86_2022-04-18_12-11-02.log)

2022-04-18 21:08 UTC, rgbarros120 commented
Mario Sonic at the Olympic Games Tokyo 2020 has some graphical bugs in the part where the fans are. Needs repair too.

My specs:
RADEON RX 560 OC 4GB
16 GB DE RAM (2400mhz)
RYZEN 5 1600

DRIVER: 22.3.1
![Sem título](https://user-images.githubusercontent.com/73244003/163878289-c864304e-4771-4767-b66d-e052071858d7.png)

[Uploading Ryujinx_1.1.0+8e28f86_2022-04-18_17-53-53.log…]()

2022-04-18 23:58 UTC, mrj1m0thy commented
As suggested in: https://github.com/Ryujinx/Ryujinx/issues/3282
I'll just put this here.
### What's the issue you encountered?

When running the "Mario Golf: Super Rush" game and trying to play an 18 hole match on the "Bonny Greens" course using the vulkan build. Ryujinx crashes with a "ErrorOutOfDeviceMemory" error.

### How can the issue be reproduced?

1. Run "Mario Golf: Super Rush"
2. "Play Golf"
3. "Standard Golf"
4. "Button Controls"
5. "1"
6. "Stroke Play + Take Turns"
7. (everything default here)
8. Choose any characters
9. "Bonny Greens"
10. Holes: 18
(everything else default)
11. Start game
Ryujinx will crash after a while of loading

### Log file

00:01:34.261 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
00:01:50.122 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorOutOfDeviceMemory".
   at Ryujinx.Graphics.Vulkan.PipelineState.CreateGraphicsPipeline(VulkanGraphicsDevice gd, Device device, ShaderCollection program, PipelineCache cache, RenderPass renderPass) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineState.cs:line 366
   at Ryujinx.Graphics.Vulkan.PipelineBase.CreatePipeline(PipelineBindPoint pbp) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1131
   at Ryujinx.Graphics.Vulkan.PipelineBase.RecreatePipelineIfNeeded(PipelineBindPoint pbp) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 1085
   at Ryujinx.Graphics.Vulkan.PipelineBase.DrawIndexed(Int32 indexCount, Int32 instanceCount, Int32 firstIndex, Int32 firstVertex, Int32 firstInstance) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineBase.cs:line 286
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_40(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 141
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in ***ryujinx_latest\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
   at System.Threading.Thread.StartCallback()

### Environment?

- Ryujinx version: 
Fresh build from https://github.com/gdkchan/Ryujinx/commit/4dc1dadbed3fb6a8860694286d39c9644564134a
also present on Vulkan version: 1.1.0+e9819d0
- Game version: v4.0.0
- System Version: 13.2.0
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 3900X
  - GPU: AMD Radeon RX 6800 XT
  - RAM: 64GB
- Applied Mods : No

### Additional context?

I'll assume "ErrorOutOfDeviceMemory" isn't a hardware limitation :)
Running the non Vulkan version of this game just gives me super flickery textures. Enough to give me a headache if I look to long haha.

2022-04-19 04:20 UTC, felixthecat1970 commented
Ryzen 3400g + igpu
Ram 16gb
SSD / NVME
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.6

Games crash in boot always with :  *** stack smashing detected ***: terminated (reported by terminal)
-SLD headless crash same message
-OGL works ok
-tested stable drivers and beta / alpha (kernel-gpu) 
[Ryujinx_1.1.0+8e28f86_2022-04-18_23-04-04.log](https://github.com/Ryujinx/Ryujinx/files/8509790/Ryujinx_1.1.0%2B8e28f86_2022-04-18_23-04-04.log)

2022-04-19 19:48 UTC, SomeoneIsWorking commented
f01a2d8893b6ae0c47859dbc0ce0f3fdef022e35 solves SMO object flickering indeed
I still get flickering in Xenoblade Chronicles: Definitive Edition
I initially wanted to record this (I recorded it after restarting the emulator)
https://www.youtube.com/watch?v=sWfVh_Iq4ec
But then while waiting for OBS to download, it went through some other screens so I waited and when it finally looped back this happened
https://www.youtube.com/watch?v=IqyDNUJ_BZU
Then I tried to go into another screen and come back to get the initial screen so I picked Event Videos and went back but then this happened
https://www.youtube.com/watch?v=PDNiZVx_9mc

RX570 22.4.1 Win10x64

2022-04-19 20:09 UTC, SomeoneIsWorking commented
f01a2d8893b6ae0c47859dbc0ce0f3fdef022e35 fixes SMO object flickering indeed

I then went to check if it also fixes the flickering in Xenoblade Chronicles: Definitive Edition but those still remain
RX570 22.4.1 Win10x64

Upon loading the game, the first screen in main menu, I get this flickering on the bottom right
https://www.youtube.com/watch?v=sWfVh_Iq4ec
After waiting a bit it goes to night time and there are flickering bloomy effects in the sky
https://www.youtube.com/watch?v=9us54lUCbt0
Then after waiting a while, it shows other screens and then loops back to the initial screen and becomes glitchy
https://www.youtube.com/watch?v=IqyDNUJ_BZU
I selected Event Theatre to go to a different screen to then went back to make the initial screen reload and it became even more glitchy
https://www.youtube.com/watch?v=PDNiZVx_9mc

I had written this comment previously and deleted it shortly after because it wasn't worded well, sorry if it caused multiple notifications.

2022-04-19 20:53 UTC, CrusadingNinja commented
> [f01a2d8](https://github.com/Ryujinx/Ryujinx/commit/f01a2d8893b6ae0c47859dbc0ce0f3fdef022e35) fixes SMO object flickering indeed
> 
> I then went to check if it also fixes the flickering in Xenoblade Chronicles: Definitive Edition but those still remain RX570 22.4.1 Win10x64
> 
> Upon loading the game, the first screen in main menu, I get this flickering on the bottom right https://www.youtube.com/watch?v=sWfVh_Iq4ec After waiting a bit it goes to night time and there are flickering bloomy effects in the sky https://www.youtube.com/watch?v=9us54lUCbt0 Then after waiting a while, it shows other screens and then loops back to the initial screen and becomes glitchy https://www.youtube.com/watch?v=IqyDNUJ_BZU I selected Event Theatre to go to a different screen to then went back to make the initial screen reload and it became even more glitchy https://www.youtube.com/watch?v=PDNiZVx_9mc
> 
> I had written this comment previously and deleted it shortly after because it wasn't worded well, sorry if it caused multiple notifications.

Flickering in Xenoblade Chronicles is unrelated to the Vulkan PR; it is also present in master. Please only report issues that are **exclusive** to the Vulkan backend here; it helps the dev team a lot.

2022-04-19 20:57 UTC, riperiperi commented
From the video, it looks like transform feedback on the grass might be broken, rather than the random chance lighting bug that master has. (and regular, well behaved gpus have)

2022-04-19 21:29 UTC, SomeoneIsWorking commented
Sorry, if it is any apology it didn't occur to me that these might also exist in an NVIDIA + OpenGL situation.
I think because some time ago I tried playing it on Linux and it ran perfectly but seems like I'm misremembering.

2022-04-20 21:02 UTC, rgbarros120 commented
Mario Party Superstars in the "Spotlight Swim" minigame has graphical bugs in need of repair.

My specs:
RADEON RX 560 OC 4GB
16 GB DE RAM (2400mhz)
RYZEN 5 1600

DRIVER: 22.3.1

![Sem título](https://user-images.githubusercontent.com/73244003/164322238-ef54c42a-0a8c-4f90-bc8a-46b80f85c5ed.png)

[Ryujinx_1.1.0+47aa773_2022-04-20_17-33-29.log](https://github.com/Ryujinx/Ryujinx/files/8525421/Ryujinx_1.1.0%2B47aa773_2022-04-20_17-33-29.log)

2022-04-20 21:30 UTC, Haronee commented
> Mario Party Superstars in the "Spotlight Swim" minigame has graphical bugs in need of repair.
> 
> My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600
> 
> DRIVER: 22.3.1
> 
> ![Sem título](https://user-images.githubusercontent.com/73244003/164322238-ef54c42a-0a8c-4f90-bc8a-46b80f85c5ed.png)
> 
> [Ryujinx_1.1.0+47aa773_2022-04-20_17-33-29.log](https://github.com/Ryujinx/Ryujinx/files/8525421/Ryujinx_1.1.0%2B47aa773_2022-04-20_17-33-29.log)

IIRC this issue is fixed by #2801 , but unfortunately, it's not merged yet, and it wouldn't really change anything for you since AMD hardware does not support `VK_EXT_fragment_shader_interlock` unlike Nvidia and Intel.

![unknown](https://user-images.githubusercontent.com/53187465/164326121-abe8b625-082f-404d-86f7-b24367f6376c.png)

2022-04-20 21:54 UTC, rgbarros120 commented
> > Mario Party Superstars in the "Spotlight Swim" minigame has graphical bugs in need of repair.
> > My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600
> > DRIVER: 22.3.1
> > ![Sem título](https://user-images.githubusercontent.com/73244003/164322238-ef54c42a-0a8c-4f90-bc8a-46b80f85c5ed.png)
> > [Ryujinx_1.1.0+47aa773_2022-04-20_17-33-29.log](https://github.com/Ryujinx/Ryujinx/files/8525421/Ryujinx_1.1.0%2B47aa773_2022-04-20_17-33-29.log)
> 
> IIRC this issue is fixed by #2801 , but unfortunately, it's not merged yet, and it wouldn't really change anything for you since AMD hardware does not support `VK_EXT_fragment_shader_interlock` unlike Nvidia and Intel.
> 
> ![unknown](https://user-images.githubusercontent.com/53187465/164326121-abe8b625-082f-404d-86f7-b24367f6376c.png)

but on yuzu there is not this bug.

2022-04-20 22:08 UTC, gdkchan commented
> IIRC this issue is fixed by #2801 , but unfortunately, it's not merged yet, and it wouldn't really change anything for you since AMD hardware does not support `VK_EXT_fragment_shader_interlock` unlike Nvidia and Intel.

No, the PR is advanced blend, that issue is caused by lack of fragment shader interlock (which is a completely different feature). Fragment shader interlock is already used on Intel and NVIDIA, but not AMD because they don't support the extension (at least on Windows).

2022-04-20 22:12 UTC, GamerzHell9137 commented
> 

On yuzu it doesn't work at all, its disabled.

2022-04-20 22:12 UTC, GamerzHell9137 commented
> > > Mario Party Superstars in the "Spotlight Swim" minigame has graphical bugs in need of repair.
> > > My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600
> > > DRIVER: 22.3.1
> > > ![Sem título](https://user-images.githubusercontent.com/73244003/164322238-ef54c42a-0a8c-4f90-bc8a-46b80f85c5ed.png)
> > > [Ryujinx_1.1.0+47aa773_2022-04-20_17-33-29.log](https://github.com/Ryujinx/Ryujinx/files/8525421/Ryujinx_1.1.0%2B47aa773_2022-04-20_17-33-29.log)
> > 
> > 
> > IIRC this issue is fixed by #2801 , but unfortunately, it's not merged yet, and it wouldn't really change anything for you since AMD hardware does not support `VK_EXT_fragment_shader_interlock` unlike Nvidia and Intel.
> > ![unknown](https://user-images.githubusercontent.com/53187465/164326121-abe8b625-082f-404d-86f7-b24367f6376c.png)
> 
> but on yuzu there is not this bug.

On yuzu it doesn't work at all, its disabled.

2022-04-20 22:28 UTC, rgbarros120 commented
> 

gdkchan good night. And as for the mario kart 8 deluxe characters dark shadows bug on amd, know if it will be fixed.

2022-04-21 17:07 UTC, rgbarros120 commented
Pokemon Sword still has some bugs of shadows and lights on AMD as shown in the attached figure. Needs repair.

My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600

DRIVER: 22.4.1

![Sem título](https://user-images.githubusercontent.com/73244003/164513815-65bcefc4-437c-4687-8215-bf8849aff02e.png)

[Ryujinx_1.1.0+47aa773_2022-04-21_13-54-10.log](https://github.com/Ryujinx/Ryujinx/files/8532939/Ryujinx_1.1.0%2B47aa773_2022-04-21_13-54-10.log)

2022-04-21 19:48 UTC, ninja85a commented
```
00:00:00.458 |N| Application LoadApplication: Using Firmware Version: 14.1.1
00:00:00.458 |I| Application LoadApplication: Loading as NSP.
00:00:00.543 |I| Application AddAocItem: Found AddOnContent with TitleId 0100E95004039001
00:00:00.605 |I| ModLoader QueryContentsDir: Searching mods for Title 0100E95004038000
00:00:00.605 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039001
00:00:00.608 |I| ModLoader QueryContentsDir: Searching mods for Title 0100E95004038000
00:00:00.608 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100E95004039001
00:00:00.629 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:00.657 |I| Loader LoadExeFs: Loading rtld...
[New Thread 0x7ffdf8ff9640 (LWP 5521)]

Thread 12 "Logger.MessageT" received signal SIG34, Real-time event 34.
[Switching to Thread 0x7fffb77fe640 (LWP 4479)]
__libc_pwrite64 (offset=<optimized out>, count=69, buf=0x7fffc8062e08, fd=76) at ../sysdeps/unix/sysv/linux/pwrite64.c:26
Downloading source file /usr/src/debug/glibc-2.34-29.fc35.x86_64/posix/../sysdeps/unix/sysv/linux/pwrite64.c...
26        return SYSCALL_CANCEL (pwrite64, fd, buf, count, SYSCALL_LL64_PRW (offset));
Missing separate debuginfos, use: dnf debuginfo-install llvm-libs-13.0.0-4.fc35.x86_64
(gdb) handle SIGSEGV nostop
Signal        Stop      Print   Pass to program Description
SIGSEGV       No        Yes     Yes             Segmentation fault
(gdb) handle SIG34 nostop
Signal        Stop      Print   Pass to program Description
SIG34         No        Yes     Yes             Real-time event 34
(gdb) break abort
Downloading source file /usr/src/debug/glibc-2.34-29.fc35.x86_64/stdlib/abort.c...
Breakpoint 2 at 0x7fff366d67a0 (4 locations)
(gdb) c
Continuing.

Thread 58 "SurfaceFlinger." received signal SIG34, Real-time event 34.
00:00:00.814 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.814 |I| Loader LoadExeFs: Loading main...
[New Thread 0x7ffddbfff640 (LWP 5689)]
[New Thread 0x7ffddb7fe640 (LWP 5690)]

Thread 13 "Discord IPC Thr" received signal SIG34, Real-time event 34.
[New Thread 0x7ffddaffd640 (LWP 5691)]
00:01:12.279 |I| Loader PrintRoSectionInfo: main:
    Module: C:\Monolithsoft\BF2\prog\application\BF2\NX64\Rom_Final\BF2.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-3_5_0-Release
00:01:12.280 |I| Loader LoadExeFs: Loading subsdk0...
00:01:12.310 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-3_5_0-Release
00:01:12.310 |I| Loader LoadExeFs: Loading sdk...
00:01:12.363 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 3.5.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-3_5_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-3_5_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-3_5_0-Release
00:01:12.462 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:01:12.887 |I| Ptc Load: Loaded Translation Cache (size: 27809902 bytes, translated functions: 23020).
00:01:12.904 |I| Ptc Load: Loaded Profiling Info (size: 76675 bytes, profiled functions: 22330).
[New Thread 0x7ffdda7fc640 (LWP 5695)]
00:01:13.277 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:01:13.281 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:01:13.291 |I| Loader LoadNsos: Loading image 2 at 0x00000000095f1000...
00:01:13.295 |I| Loader LoadNsos: Loading image 3 at 0x0000000009cac000...
[New Thread 0x7ffdd9ffb640 (LWP 5699)]
00:01:13.316 |I| ModLoader LoadCheats: Build ids found for title 0100E95004038000:
    A75512BE30BB2A8C880177505D7A0B3E24E9D642000000000000000000000000
    F77F1559371C0EC6D50E78774AC59D9500000000000000000000000000000000
    2201BB705408EF610E9AAC23195011D1DD9606F5000000000000000000000000
    867B345248124EF3D70E3202E221E978964C592F000000000000000000000000
00:01:13.316 |I| Loader LoadNca: Application Loaded: Xenoblade Chronicles 2 v2.1.0 [0100e95004038000] [64-bit]
[New Thread 0x7ffdd97fa640 (LWP 5700)]
00:01:13.330 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
[New Thread 0x7ffdd8ff9640 (LWP 5701)]
00:01:13.353 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
Downloading separate debug info for /usr/lib64/libvulkan_intel.so...
Downloading separate debug info for /lib64/libxcb-randr.so.0...
Downloading separate debug info for /usr/lib64/libvulkan_lvp.so...
Downloading separate debug info for /usr/lib64/libvulkan_radeon.so...
Downloading separate debug info for /lib64/libVkLayer_MESA_device_select.so...
[New Thread 0x7efdb9439640 (LWP 5729)]
[New Thread 0x7efdb8c38640 (LWP 5730)]
[New Thread 0x7efd26fff640 (LWP 5731)]
[New Thread 0x7efd267fe640 (LWP 5732)]
[New Thread 0x7efd25ffd640 (LWP 5733)]
Downloading separate debug info for /lib64/libshaderc_shared.so...
Downloading separate debug info for /home/haise/.cache/debuginfod_client/b2cc27b0eaa1895e59fd0355a603e069313b6ddb/debuginfo...
Downloading separate debug info for /lib64/libSPIRV-Tools.so...
Downloading separate debug info for /home/haise/.cache/debuginfod_client/234eadd455b1373d7fed5e1bb0c800c3bfd15059/debuginfo...
Downloading separate debug info for /lib64/libSPIRV-Tools-opt.so...
[Thread 0x7ffdf8ff9640 (LWP 5521) exited]
[New Thread 0x7ffdf8ff9640 (LWP 5772)]
[New Thread 0x7efd257fc640 (LWP 5773)]
[New Thread 0x7efd24ffb640 (LWP 5774)]
[New Thread 0x7efd0bfff640 (LWP 5775)]
00:01:43.582 |N| GUI.RenderLoop Gpu PrintGpuInformation: AMD AMD RADV NAVI10 (Vulkan v1.2.195, Driver v21.3.8)
[New Thread 0x7efd0b7fe640 (LWP 5776)]
00:01:43.613 |I| GPU.MainThread Gpu LoadShaders: Loading 36 shaders from the cache...
[New Thread 0x7efd0affd640 (LWP 5777)]
[New Thread 0x7efd0a7fc640 (LWP 5778)]
[New Thread 0x7efd09ffb640 (LWP 5779)]
[New Thread 0x7efd097fa640 (LWP 5780)]
[New Thread 0x7efd08ff9640 (LWP 5781)]
[New Thread 0x7efceffff640 (LWP 5782)]
[New Thread 0x7efcef7fe640 (LWP 5783)]
[New Thread 0x7efceeffd640 (LWP 5784)]
[New Thread 0x7efcee7fc640 (LWP 5785)]
[New Thread 0x7efcedffb640 (LWP 5786)]
[New Thread 0x7efced7fa640 (LWP 5787)]
[New Thread 0x7efcecff9640 (LWP 5788)]
[Thread 0x7efceeffd640 (LWP 5784) exited]
[Thread 0x7efcef7fe640 (LWP 5783) exited]
[Thread 0x7efceffff640 (LWP 5782) exited]
[Thread 0x7efd08ff9640 (LWP 5781) exited]
[Thread 0x7efd097fa640 (LWP 5780) exited]
[Thread 0x7efd09ffb640 (LWP 5779) exited]
[Thread 0x7efd0a7fc640 (LWP 5778) exited]
[Thread 0x7efd0affd640 (LWP 5777) exited]
00:01:43.760 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
[New Thread 0x7efcef7fe640 (LWP 5789)]
[New Thread 0x7efd0a7fc640 (LWP 5790)]
[Thread 0x7efcef7fe640 (LWP 5789) exited]
[Thread 0x7efd0a7fc640 (LWP 5790) exited]
[New Thread 0x7efd0a7fc640 (LWP 5791)]
[New Thread 0x7efcef7fe640 (LWP 5792)]
[Thread 0x7efd0a7fc640 (LWP 5791) exited]
[Thread 0x7efcef7fe640 (LWP 5792) exited]
[New Thread 0x7efcef7fe640 (LWP 5793)]
[New Thread 0x7efd0a7fc640 (LWP 5794)]
[Thread 0x7efcef7fe640 (LWP 5793) exited]
[Thread 0x7efd0a7fc640 (LWP 5794) exited]
00:01:44.134 |I| HLE.GuestThread.15 Ptc LoadTranslations: 22330 translated functions loaded
[New Thread 0x7efd0a7fc640 (LWP 5797)]
[New Thread 0x7efcef7fe640 (LWP 5798)]
[New Thread 0x7efd097fa640 (LWP 5799)]
00:01:44.397 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:01:44.423 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed. 
00:01:44.424 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:01:44.425 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:01:46.043 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:01:46.067 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100E95004039001
00:01:46.069 |S| HLE.OsThread.16 ServiceNs PrepareAddOnContentImpl: Stubbed. {index [...]

2022-04-30 14:35 UTC, AlfredoDore commented
Star Wars: The Force Unleashed
have the screen dark with this smudge on the screen and there is only a small drop in yield
Log file
[Ryujinx_1.1.0+80959f1_2022-04-30_11-21-48.log](https://github.com/Ryujinx/Ryujinx/files/8597107/Ryujinx_1.1.0%2B80959f1_2022-04-30_11-21-48.log)

Spec
ryujinx-Release-1.1.0+80959f1-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.1
![imagem](https://user-images.githubusercontent.com/90729203/166109670-f13f4beb-66f5-4a84-a2f5-2d6cf9b5ca0b.png)

2022-04-30 19:30 UTC, rgbarros120 commented
The game Atelier Sophie 2: The Alchemist of the Mysterious Dream, does not arrive at the game's home menu screen, the emulator simply crashes and closes out of nowhere.

My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600

DRIVER: 22.4.1

![Sem título](https://user-images.githubusercontent.com/73244003/166120012-e4a76793-1618-423e-b93c-b12dd7a34a57.png)

[Ryujinx_1.1.0+80959f1_2022-04-30_16-24-29.log](https://github.com/Ryujinx/Ryujinx/files/8597686/Ryujinx_1.1.0%2B80959f1_2022-04-30_16-24-29.log)

2022-04-30 23:00 UTC, rgbarros120 commented
Pokemon Sword still has some light and shadow bugs as shown in the photos below. The game also needs more optimization and performance too.

My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600

DRIVER: 22.4.1

![Sem título](https://user-images.githubusercontent.com/73244003/166125362-b3cf4a2d-4411-4c86-a4c1-1b0287b0babf.png)
![Sem título 1](https://user-images.githubusercontent.com/73244003/166125366-e04ece41-c04f-4c3c-a6b2-7edf1abbb7f1.png)

[Ryujinx_1.1.0+80959f1_2022-04-30_19-53-31.log](https://github.com/Ryujinx/Ryujinx/files/8597951/Ryujinx_1.1.0%2B80959f1_2022-04-30_19-53-31.log)

2022-05-01 13:36 UTC, rgbarros120 commented
Mario & Sonic at the Olympic Games: Tokyo 2020, you play this game on the emulator and spend about 10 minutes and the game just crashes.

My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600

DRIVER: 22.4.1

2022-05-01 14:14 UTC, AlfredoDore commented
Super Mario Odyssey
now the textures are almost not blinking anymore, but still one or another thing continues, it also needs improvement in performance
Log file
[Ryujinx_1.1.0+80959f1_2022-05-01_11-03-03.log](https://github.com/Ryujinx/Ryujinx/files/8599083/Ryujinx_1.1.0%2B80959f1_2022-05-01_11-03-03.log)
Spec
ryujinx-Release-1.1.0+80959f1-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2
https://streamable.com/v1tz6w

2022-05-04 09:25 UTC, benderscruffy commented
Pinball FX3 with updates
![ryujinx_capture_2022-05-04_17-20-48](https://user-images.githubusercontent.com/2696404/166655239-8ce0aba7-e6c5-4701-877a-34f5b6164e0c.png)
![ryujinx_capture_2022-05-04_17-21-13](https://user-images.githubusercontent.com/2696404/166655260-8ad94b83-b6fd-4cae-8c72-daecf2e5d5a8.png)
needs #3152

2022-05-04 15:46 UTC, AlfredoDore commented
Mario Kart 8
textures are not flickering and performance is phenomenal
Log file
[Ryujinx_1.1.0+fd3da29_2022-05-04_12-31-30.log](https://github.com/Ryujinx/Ryujinx/files/8621968/Ryujinx_1.1.0%2Bfd3da29_2022-05-04_12-31-30.log)
Spec
Ryujinx_1.1.0+fd3da29-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2

2022-05-04 16:12 UTC, AlfredoDore commented
Super Mario Odyssey 
textures and speed have improved a lot, but it still needs adjustment for effects (a little drop) and something or other still flickers, but it's much better than before
Log file
[Ryujinx_1.1.0+fd3da29_2022-05-04_12-54-47.log](https://github.com/Ryujinx/Ryujinx/files/8622142/Ryujinx_1.1.0%2Bfd3da29_2022-05-04_12-54-47.log)
Spec
Ryujinx_1.1.0+fd3da29-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2
https://streamable.com/86rcf4

2022-05-04 22:37 UTC, rgbarros120 commented
Pokemon Sword needs more performance in some parts of the game, for example, hammerlock, motoshoke, and the game still has some graphical problems with lights, shadows, and bugs in the water parts. The fog issue is also a bit exaggerated.

MY SPECS? RADEON RX 560 OC 4GB; 16GB DE RAM (2400mhz). RYZEN 5 1600

![Sem título 1](https://user-images.githubusercontent.com/73244003/166836558-281136d6-05cf-4d00-a91f-bedc3995320c.png)
![Sem título 2](https://user-images.githubusercontent.com/73244003/166836582-2c4c7e5c-cf39-433b-bc17-16f58fb60c95.png)
![Sem título 3](https://user-images.githubusercontent.com/73244003/166836601-27198498-469e-4e2f-9481-b9b9953597fe.png)
![Sem título](https://user-images.githubusercontent.com/73244003/166836605-b93f5c3b-00eb-4eaf-887a-1287df066e56.png)

[Ryujinx_1.1.0+df843cb_2022-05-04_19-18-22.log](https://github.com/Ryujinx/Ryujinx/files/8627770/Ryujinx_1.1.0%2Bdf843cb_2022-05-04_19-18-22.log)

2022-05-05 15:37 UTC, AlfredoDore commented
Waifu Impact
the performance has improved, but there is still a drop in fps, the textures are now better, but one thing or another they keep blinking
Log file
[Ryujinx_1.1.0+f5e651a_2022-05-05_10-58-41.log](https://github.com/Ryujinx/Ryujinx/files/8632595/Ryujinx_1.1.0%2Bf5e651a_2022-05-05_10-58-41.log)
Spec
ryujinx-Release-1.1.0+f5e651a-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2
https://streamable.com/cnjsob

2022-05-05 23:52 UTC, AlfredoDore commented
Star Wars: The Force Unleashed
there is no more smudge on the screen, but now everything is dark, now the game is no longer seeing the performance losses
Log file
[Ryujinx_1.1.0+bd79647_2022-05-05_20-42-59.log](https://github.com/Ryujinx/Ryujinx/files/8636659/Ryujinx_1.1.0%2Bbd79647_2022-05-05_20-42-59.log)
Spec
ryujinx-Release-1.1.0+bd79647-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2
![imagem](https://user-images.githubusercontent.com/90729203/167044684-81a5b91b-5394-43ea-bc34-03f6e5c3266f.png)

2022-05-06 22:46 UTC, Labans12 commented
Marvel Ultimate Alliance 3

The game's graphics is not showing up properly, and there are also a lot of flickering. The characters have these black shades on them and the floor/walls are see through. Performance works fine though.

Specs
ryujinx-Release-1.1.0+bd79647-win_x64
STORAGE: SSD
CPU: AMD Ryzen 5 3600
RAM: 16gb 
GPU: Radeon RX 5700XR
DRIVER: 22.3.2


![Capture](https://user-images.githubusercontent.com/105085700/167224893-e732b0c9-1b36-4b2f-bd54-e192cec834e7.JPG)


[Ryujinx_1.1.0+bd79647_2022-05-06_18-36-16.log](https://github.com/Ryujinx/Ryujinx/files/8643904/Ryujinx_1.1.0%2Bbd79647_2022-05-06_18-36-16.log)

2022-05-07 01:26 UTC, datsoy commented
Monster Hunter Rise Crash at start up.

Build: Ryujinx_1.1.0+bd79647
OS: Windows 10 LTSC 2021
Ram: 16gb
CPU: Ryzen 5 5600g
GPU/Driver: Ryzen 5 5600g Radeon Vega 7/v22.4.2
[Ryujinx_1.1.0+bd79647_2022-05-07_09-19-33.log](https://github.com/Ryujinx/Ryujinx/files/8644202/Ryujinx_1.1.0%2Bbd79647_2022-05-07_09-19-33.log)

2022-05-07 02:25 UTC, Squall-Leonhart commented
RDNA1 and Polaris users should be on 22.4+ for vulkan fixes, users reporting with 22.3 may be invalid due to issues attributed to the driver.

2022-05-07 04:03 UTC, Labans12 commented
> RDNA1 and Polaris users should be on 22.4+ for vulkan fixes, users reporting with 22.3 may be invalid due to issues attributed to the driver.

I just updated to 22.4.2 and the problem still exists in Marvel Ultimate Alliance 3

2022-05-08 20:22 UTC, rgbarros120 commented
Pokemon Sword still needs more performance and correction of shadows and lights bugs that still persist in the emulator.

My Specs: Radeon RX 560 OC 4GB; 16GB DE RAM(2400mhz); Ryzen 5 1600
Driver: 22.4.1

![Sem título 1](https://user-images.githubusercontent.com/73244003/167314389-23fb57d1-1ede-47d8-bff4-ce63bb5a7ca1.png)
![Sem título](https://user-images.githubusercontent.com/73244003/167314393-5b183ec2-d2fe-43d0-ac22-06477974367f.png)

[Ryujinx_1.1.0+bd79647_2022-05-08_17-14-27.log](https://github.com/Ryujinx/Ryujinx/files/8647737/Ryujinx_1.1.0%2Bbd79647_2022-05-08_17-14-27.log)

2022-05-11 06:57 UTC, cheungyau2022 commented
I can't get any game to run with the Vulkan buid. Is there anything I can do? I tried so many builds in the past months but no luck.
[Ryujinx_1.1.0+bd79647_2022-05-11_14-54-09.log](https://github.com/Ryujinx/Ryujinx/files/8667434/Ryujinx_1.1.0%2Bbd79647_2022-05-11_14-54-09.log)

2022-05-11 10:07 UTC, edisionnano commented
> I can't get any game to run with the Vulkan buid. Is there anything I can do? I tried so many builds in the past months but no luck. [Ryujinx_1.1.0+bd79647_2022-05-11_14-54-09.log](https://github.com/Ryujinx/Ryujinx/files/8667434/Ryujinx_1.1.0%2Bbd79647_2022-05-11_14-54-09.log)

Come at our Discord server, #linux-master-race channel, and we'll help you

2022-05-13 19:10 UTC, AlfredoDore commented
BULLETSTORM: DUKE OF SWITCH EDITION
there was a significant improvement in the textures, one or another texture still flashes and there are still some texture problems, however in the second part where the soldiers appear the audio cuts out and shortly after the emulator closes
Log file
[Ryujinx_1.1.0+bd79647_2022-05-13_15-52-08.log](https://github.com/Ryujinx/Ryujinx/files/8690711/Ryujinx_1.1.0%2Bbd79647_2022-05-13_15-52-08.log)
Spec
ryujinx-Release-1.1.0+bd79647-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2

2022-05-13 23:07 UTC, AlfredoDore commented
Nintendo 64 online
the games now start, but there are problems with transparency, in addition to loss of income, in Starfox 64 at a certain moment the game simply closes
Log file
[Ryujinx_1.1.0+4b54521_2022-05-13_19-58-55.log](https://github.com/Ryujinx/Ryujinx/files/8691685/Ryujinx_1.1.0%2B4b54521_2022-05-13_19-58-55.log)
Spec
ryujinx-Release-1.1.0+4b54521-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2
![imagem](https://user-images.githubusercontent.com/90729203/168399486-8e42021e-940c-4539-b517-2b757a23a0db.png)

2022-05-13 23:41 UTC, AlfredoDore commented
Mario Kart 8
the speed is excellent, there is only a little drop in performance in explosion effects and such, on the character selection screen there is this shadow
Log file
[Ryujinx_1.1.0+4b54521_2022-05-13_20-17-53.log](https://github.com/Ryujinx/Ryujinx/files/8691762/Ryujinx_1.1.0%2B4b54521_2022-05-13_20-17-53.log)
Spec
ryujinx-Release-1.1.0+4b54521-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2
![imagem](https://user-images.githubusercontent.com/90729203/168401662-60d82c63-676a-4f72-8ef1-94c8522769d9.png)

2022-05-13 23:50 UTC, ayurai commented
Xenoblade 2 refuse to even open for me with the last build.
(worked normally in every other)
[Ryujinx_1.1.0+4b54521_2022-05-13_20-47-25.log](https://github.com/Ryujinx/Ryujinx/files/8691786/Ryujinx_1.1.0%2B4b54521_2022-05-13_20-47-25.log)

2022-05-14 00:25 UTC, MarkLanders777 commented
> Xenoblade 2 refuse to even open for me with the last build. (worked normally in every other) [Ryujinx_1.1.0+4b54521_2022-05-13_20-47-25.log](https://github.com/Ryujinx/Ryujinx/files/8691786/Ryujinx_1.1.0%2B4b54521_2022-05-13_20-47-25.log)
> 
> Core i5 12400 16gb ram gtx 1060 6gb (driver version : 512.77) Windows 11

it was fixed already, try again with the new vulkan build

2022-05-14 12:42 UTC, riperiperi commented
> Nintendo 64 online the games now start, but there are problems with transparency, in addition to loss of income, in Starfox 64 at a certain moment the game simply closes Log file [Ryujinx_1.1.0+4b54521_2022-05-13_19-58-55.log](https://github.com/Ryujinx/Ryujinx/files/8691685/Ryujinx_1.1.0%2B4b54521_2022-05-13_19-58-55.log) Spec ryujinx-Release-1.1.0+4b54521-win_x64 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.4.2 ![imagem](https://user-images.githubusercontent.com/90729203/168399486-8e42021e-940c-4539-b517-2b757a23a0db.png)

Might be another AMD moment. Looks fine here on a GTX 1070, though the main menu text is missing:
![image](https://user-images.githubusercontent.com/6294155/168426208-9177c2fa-df44-4fdb-836c-3703444c0200.png)

2022-05-15 17:16 UTC, AlfredoDore commented
> > Nintendo 64 online the games now start, but there are problems with transparency, in addition to loss of income, in Starfox 64 at a certain moment the game simply closes Log file [Ryujinx_1.1.0+4b54521_2022-05-13_19-58-55.log](https://github.com/Ryujinx/Ryujinx/files/8691685/Ryujinx_1.1.0%2B4b54521_2022-05-13_19-58-55.log) Spec ryujinx-Release-1.1.0+4b54521-win_x64 STORAGE: SSD CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz RAM: 16gb (1600mhz) GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz DRIVER: 22.4.2 ![imagem](https://user-images.githubusercontent.com/90729203/168399486-8e42021e-940c-4539-b517-2b757a23a0db.png)
> 
> Might be another AMD moment. Looks fine here on a GTX 1070, though the main menu text is missing: ![image](https://user-images.githubusercontent.com/6294155/168426208-9177c2fa-df44-4fdb-836c-3703444c0200.png)

this only happens in Vulkan, in OpenGL it runs better, funny that my controller (Xbox One) is vibrating directly in Ryujinx

2022-05-16 09:23 UTC, benderscruffy commented
Pinball FX3 v 1.0.11.0
black screen with just the scoreboard and sound
![ryujinx_capture_2022-05-16_17-18-18](https://user-images.githubusercontent.com/2696404/168561220-3fac99b0-f5c5-4633-9ad6-72b62b161c18.png)

2022-05-18 06:00 UTC, XenobladeCN commented
![13](https://user-images.githubusercontent.com/105591901/168967632-c1b771dc-6cf4-4976-a70e-da453d0fb8e2.png)
hi,gdkchan,I'm your fan，Now I'm in some trouble.This branch has conflicts that must be resolved.What should I do？

2022-05-18 06:08 UTC, Shahil-Ayato commented
> ![13](https://user-images.githubusercontent.com/105591901/168967632-c1b771dc-6cf4-4976-a70e-da453d0fb8e2.png)
> hi,gdkchan,I'm your fan，Now I'm in some trouble.This branch has conflicts that must be resolved.What should I do？

You really shouldn’t be making a custom repository if you don’t know how to solve a merge conflict. Just use the regular Vulkan build here https://github.com/Ryujinx/Ryujinx/pull/2518#issuecomment-890255424

2022-05-20 10:53 UTC, d3aths commented
### Pokemon Shield version 1.3.2 - Trees in the wild area are invisible.  
There's blockages where trees should be, i.e they're still there and you can't physically walk through them, they're just invisible. Shadows of trees still show on the ground. I think this happens on routes as well after encountering invisible barriers that I now believe might have been trees. This is a Vulkan specific issue, tested it in the LDN build and trees showed up, however due to AMD gpu it's unplayable :(

![image](https://user-images.githubusercontent.com/16113944/169512234-94fd710f-9714-42ca-bc17-779a450356a2.png)
*Vulkan build*

![image](https://user-images.githubusercontent.com/16113944/169512513-9564f9ed-ba6c-4466-bb79-048bd5e702c8.png)
*OpenGL*

CPU: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz 6 Cores
16GB RAM
GPU: Radeon RX 560 Series VRAM 4096 MB
GDDR5 1750 MHz
Windows 10.0.19044

2022-05-25 12:31 UTC, alex1984sp commented
Hello how are you?
I'd like to play some help, I'm trying Monster Hunter Rise on ryujinx, using vulkan (I tried OpenGL, but it's not more than 13 FPS), but as soon as the game opens, it crashes and closes, do you have any idea of ​​a solution? my pc is a rysen 3600 and video an rx480 8gb gigabyte, the video card drivers are up to date, follow the log according to the guidance given to me abov
[Ryujinx_1.1.0+8ec4879_2022-05-25_09-01-22.log](https://github.com/Ryujinx/Ryujinx/files/8771090/Ryujinx_1.1.0%2B8ec4879_2022-05-25_09-01-22.log)
e

2022-05-26 00:19 UTC, alex1984sp commented
Hello good night, it's me again, see, the characters of MH Rise have some black holes on their faces, follow the prints and the log, I hope it helps and thanks for making it open on Vulkan today.

![image](https://user-images.githubusercontent.com/59449021/170389389-1d0cd2c7-75c1-419c-89be-2a131998f132.png)
![image](https://user-images.githubusercontent.com/59449021/170389494-ea96874c-28d1-4b7e-900e-3b5310d63cc7.png)
![image](https://user-images.githubusercontent.com/59449021/170389560-5129a3b2-6552-4226-9604-4391239deb86.png)

[Ryujinx_1.1.0+a752599_2022-05-25_21-08-52.log](https://github.com/Ryujinx/Ryujinx/files/8775309/Ryujinx_1.1.0%2Ba752599_2022-05-25_21-08-52.log)

2022-05-26 11:56 UTC, alex1984sp commented
Hello, look at me again, I'm having problems with MHRise, every time I try to open a mission that has an intro video, after the video the game crashes and one of the times the PC crashed, I had to restart by holding the off button.
I generated 3 different mission logs to help solve. thanks
[Ryujinx_1.1.0+a752599_2022-05-26_08-31-56.log](https://github.com/Ryujinx/Ryujinx/files/8778723/Ryujinx_1.1.0%2Ba752599_2022-05-26_08-31-56.log)
[Ryujinx_1.1.0+a752599_2022-05-26_08-34-41.log](https://github.com/Ryujinx/Ryujinx/files/8778724/Ryujinx_1.1.0%2Ba752599_2022-05-26_08-34-41.log)
[Ryujinx_1.1.0+a752599_2022-05-26_08-46-46.log](https://github.com/Ryujinx/Ryujinx/files/8778725/Ryujinx_1.1.0%2Ba752599_2022-05-26_08-46-46.log)

2022-05-26 12:08 UTC, Squall-Leonhart commented
This bug isn't for generic system diagnostics, 

FTR, Polaris has issues on Windows 11 with 2022 drivers where stability is concerned, and if you haven't updated your bios and chipset drivers those are both considerations as well.

2022-05-26 14:29 UTC, riperiperi commented
This looks like it might be a driver issue, maybe it doesn't like one of the shaders the game generates. The log unfortunately doesn't have any info.

2022-05-27 22:35 UTC, ayurai commented
Sometimes, for some reason i dont understand xenoblade fails to even load  (i'm not talking about in game loads. the emulator fails to load the game).
[Ryujinx_1.1.0+06c2547_2022-05-27_19-31-14.log](https://github.com/Ryujinx/Ryujinx/files/8789998/Ryujinx_1.1.0%2B06c2547_2022-05-27_19-31-14.log)
Dont know if it is relevant, but here is the log.

2022-05-28 01:28 UTC, moonallie commented
Hiiii, I'm having a problem with Triangle Strategy where the game just flickers, like this https://github.com/Ryujinx/Ryujinx-Games-List/issues/3853 (exactly the same problem in the same places).
[Ryujinx_1.1.0+5d587b6_2022-05-27_22-25-06.log](https://github.com/Ryujinx/Ryujinx/files/8790263/Ryujinx_1.1.0%2B5d587b6_2022-05-27_22-25-06.log)

2022-05-30 02:11 UTC, Wfree86 commented
Not really sure whats going on with my Vulkan build. If I run SSBU on the current OpenGL. version, it runs. But this version shows work in the background but never reaches the opening movie let alone the loading icon.

[Ryujinx_1.1.132_2022-05-29_17-56-27.log](https://github.com/Ryujinx/Ryujinx/files/8794889/Ryujinx_1.1.132_2022-05-29_17-56-27.log)
[Ryujinx_1.1.0+06c2547_2022-05-29_18-12-10.log](https://github.com/Ryujinx/Ryujinx/files/8794891/Ryujinx_1.1.0%2B06c2547_2022-05-29_18-12-10.log)

2022-05-30 18:22 UTC, rgbarros120 commented
The infinite links game has some graphical bugs in the subtitles, as shown in the above image. Needs repair.

My specs: 16GB de ram (2400mhz); ryzen 5 1600 (six core); radeon rx 560 oc 4GB
Driver:  22.5.1
![Sem título](https://user-images.githubusercontent.com/73244003/171044079-f89e623b-6485-4635-92d2-3758d254ee9e.png)

2022-06-02 22:34 UTC, ayurai commented
Torna has some bugs which i didnt see the normal campaing of xenoblade 2 
https://streamable.com/ovn45q

2022-06-02 22:55 UTC, GamerzHell9137 commented
> Torna has some bugs which i didnt see the normal campaing of xenoblade 2
> Xenoblade.2.mp4

Log?

2022-06-03 11:48 UTC, Niwu34 commented
> Torna has some bugs which i didnt see the normal campaing of xenoblade 2
> 
> [Ryujinx_1.1.0+06c2547_2022-06-02_18-57-43.log](https://github.com/Ryujinx/Ryujinx/files/8828316/Ryujinx_1.1.0%2B06c2547_2022-06-02_18-57-43.log)
> 
>  Xenoblade.2.mp4

Can you retry it with gdkchan latest changes?
Just tried it and can't reproduce it.
![image](https://user-images.githubusercontent.com/67392333/171847693-9e0d6b3a-8bf1-49d0-8f24-ed36e3065cab.png)

2022-06-04 03:01 UTC, ayurai commented
> > Torna has some bugs which i didnt see the normal campaing of xenoblade 2
> > [Ryujinx_1.1.0+06c2547_2022-06-02_18-57-43.log](https://github.com/Ryujinx/Ryujinx/files/8828316/Ryujinx_1.1.0%2B06c2547_2022-06-02_18-57-43.log)
> > Xenoblade.2.mp4
> 
> Can you retry it with gdkchan latest changes? Just tried it and can't reproduce it. ![image](https://user-images.githubusercontent.com/67392333/171847693-9e0d6b3a-8bf1-49d0-8f24-ed36e3065cab.png)

it wasnt compiled right ?  bot didnt completed the checks ?

2022-06-05 14:15 UTC, rgbarros120 commented
In the game mario kart 8 deluxe, the dark shadows bug still remains in the choice of characters, it needs to be fixed.

my specs: 16gb de ram (2400mhz); Radeon RX 560 OC 4GB; Ryzen 5 1600 (six core)
driver: 22.5.1

![Sem título](https://user-images.githubusercontent.com/73244003/172054902-b1570ec3-563e-4c46-a79f-682b88e2f215.png)
[Ryujinx_1.1.0+b933d97_2022-06-05_11-09-21.log](https://github.com/Ryujinx/Ryujinx/files/8840132/Ryujinx_1.1.0%2Bb933d97_2022-06-05_11-09-21.log)

2022-06-06 19:35 UTC, MutantAura commented
> The game mario kart 8 deluxe, unfortunately the dark shadows bug still remains in the character selection choice, needs urgent fix.
> 
> My specs: 16gb de ram (2400mhz); radeon rx 560 oc 4gb; ryzen 5 1600 driver: 22.5.1
> 
> ![mario kart](https://user-images.githubusercontent.com/73244003/172233634-266e86fc-8ec2-453c-9c91-ad61c65a2bd3.png) [Ryujinx_1.1.0+8eefa92_2022-06-06_16-25-31.log](https://github.com/Ryujinx/Ryujinx/files/8847096/Ryujinx_1.1.0%2B8eefa92_2022-06-06_16-25-31.log)

You have reported this multiple times. Further reports will be deleted as spam.

2022-06-06 20:09 UTC, rgbarros120 commented
> > The game mario kart 8 deluxe, unfortunately the dark shadows bug still remains in the character selection choice, needs urgent fix.
> > My specs: 16gb de ram (2400mhz); radeon rx 560 oc 4gb; ryzen 5 1600 driver: 22.5.1
> > ![mario kart](https://user-images.githubusercontent.com/73244003/172233634-266e86fc-8ec2-453c-9c91-ad61c65a2bd3.png) [Ryujinx_1.1.0+8eefa92_2022-06-06_16-25-31.log](https://github.com/Ryujinx/Ryujinx/files/8847096/Ryujinx_1.1.0%2B8eefa92_2022-06-06_16-25-31.log)
> 
> You have reported this multiple times. Further reports will be deleted as spam.

2022-06-06 20:10 UTC, rgbarros120 commented
Good afternoon. I reported it because unfortunately it's still bugged.

2022-06-06 20:18 UTC, MutantAura commented
> Good afternoon. I reported it because unfortunately it's still bugged.

Unless a developer or a commit message specifically says that a fix has been pushed then you do not need to post the same reports every time a new build is made. Most of them will be unrelated to your issue. Only report **changes** to previous reports, not just the same report over and over.

2022-06-06 20:25 UTC, rgbarros120 commented
Ok

2022-06-07 05:59 UTC, markbex commented
How to control the rendering resolution(s) for the good of old PCs ?

2022-06-07 06:04 UTC, Ruther92 commented
Why Ryujinx constantly say me this?
-GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?

Can i do something? Im playing ultimate with skyline, after these errors the game freeze

2022-06-07 17:14 UTC, AlfredoDore commented
Doom 3
game is stuck on the start screen
Log file
[Ryujinx_1.1.0+8eefa92_2022-06-07_14-03-55.log](https://github.com/Ryujinx/Ryujinx/files/8855225/Ryujinx_1.1.0%2B8eefa92_2022-06-07_14-03-55.log)
Spec
ryujinx-Release-1.1.0+8eefa92-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.4.2
![imagem](https://user-images.githubusercontent.com/90729203/172441455-33509b07-92e8-42d9-bef0-b89e31b350b4.png)

2022-06-07 23:15 UTC, rgbarros120 commented
> Why Ryujinx constantly say me this? -GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
> 
> Can i do something? Im playing ultimate with skyline, after these errors the game slowdown and freeze

2022-06-07 23:16 UTC, rgbarros120 commented
That's actually what developers have to fix. Solving this would improve many games.

2022-06-07 23:29 UTC, riperiperi commented
This log is not responsible for any issues.

2022-06-08 03:47 UTC, Ruther92 commented
> This log is not responsible for any issues.

Oh ok thanks for the reply.
But that the game Is very slow to boot and freeze frequently is an issue of skyline support or because of the vulkan build?

2022-06-11 02:55 UTC, gdkchan commented
For those that had issues with shaderc on Linux, it should be fixed now as shaderc is no longer needed. The pre-built binary for Windows was removed aswell.
I want to get this merged this month, so please let me know if there's anything that must be done before it is merged (some issue that affects multiple games or something like that), I will try to take a look.

2022-06-11 12:40 UTC, edisionnano commented
> For those that had issues with shaderc on Linux, it should be fixed now as shaderc is no longer needed. The pre-built binary for Windows was removed aswell. I want to get this merged this month, so please let me know if there's anything that must be done before it is merged (some issue that affects multiple games or something like that), I will try to take a look.

As for Linux issues, descriptor indexing has to be sorted cause RADV segfaults without RADV_PERFTEST=bolist

2022-06-11 12:57 UTC, GamerzHell9137 commented
Since the change from GLSL to SPIR V, Bubble Bobble pop effect is not upscaling properly. In Native resolution it works fine.

https://streamable.com/0xrjna

Think i didn't post it here, only talked about it in the server.

2022-06-11 12:59 UTC, A-w-x commented
my env for all my reports: archlinux, mesa git (as of now), 1165g7, intel xe

mario strikers, lots of missing gfx
[mario strikers.log.zip](https://github.com/Ryujinx/Ryujinx/files/8883909/mario.strikers.log.zip)

![Screenshot_2022-06-11_12-52-20](https://user-images.githubusercontent.com/80461138/173188940-b3bb7d5c-aa33-4749-a198-323c6e4ff52e.png)
![Screenshot_2022-06-11_12-52-49](https://user-images.githubusercontent.com/80461138/173188942-7ef7c55a-5330-496e-b285-29b70ceb8ecb.png)

2022-06-11 13:00 UTC, riperiperi commented
> > For those that had issues with shaderc on Linux, it should be fixed now as shaderc is no longer needed. The pre-built binary for Windows was removed aswell. I want to get this merged this month, so please let me know if there's anything that must be done before it is merged (some issue that affects multiple games or something like that), I will try to take a look.
> 
> As for Linux issues, descriptor indexing has to be sorted cause RADV segfaults without RADV_PERFTEST=bolist

That's not really a great explanation. The default descriptor behaviour in RADV does not behave well when disposed buffers remain on the descriptor set, even if they are unused. Enabling the descriptor indexing extension _forces_ RADV to use bolist, due to how their driver works.

2022-06-11 13:03 UTC, A-w-x commented
pokken black screen flickering in battle, the image flickers when there are movements and the screen becames all block for a second

[pokken.log.zip](https://github.com/Ryujinx/Ryujinx/files/8883915/pokken.log.zip)

2022-06-11 13:12 UTC, A-w-x commented
paper mario bad performance, ~20fps or lower vs 30 ogl
[papermario.log.zip](https://github.com/Ryujinx/Ryujinx/files/8883931/papermario.log.zip)

performance seems bad in general vs ogl for me (few other, crash nitro racing, pokemon sw/sh, PLA)

2022-06-11 13:21 UTC, riperiperi commented
> paper mario bad performance, ~20fps or lower vs 30 ogl [papermario.log.zip](https://github.com/Ryujinx/Ryujinx/files/8883931/papermario.log.zip)
> 
> performance seems bad in general vs ogl for me (few other, crash nitro racing, pokemon sw/sh, PLA)

You have Vulkan validation layers on, which can greatly lower performance. Turn them off in the settings by changing "Graphics Backend Logging" to "None".

2022-06-11 13:35 UTC, A-w-x commented
> > paper mario bad performance, ~20fps or lower vs 30 ogl [papermario.log.zip](https://github.com/Ryujinx/Ryujinx/files/8883931/papermario.log.zip)
> > performance seems bad in general vs ogl for me (few other, crash nitro racing, pokemon sw/sh, PLA)
> 
> You have Vulkan validation layers on, which can greatly lower performance. Turn them off in the settings by changing "Graphics Backend Logging" to "None".

i know, it is set for logs, if it helps to see why games are slow

bad performance is without logs, i mean no logs at all

2022-06-12 15:06 UTC, A-w-x commented
so about perf on intel in linux, not sure about windows, there are 2 problems

1 - the gpu keeps a very low clock for unknown reasons resulting in 30 or more fps difference in some cases  vs ogl, this is not ryu fault ofc, but users should be warned that intel hw may be affected by this weird behavior (in my case gpu clock was stuck at 300-400 mhz while it should be 1.3ghz) (this is known issue on intel)

2 - even when forcing higher gpu clock (1ghz) perf is still worse than ogl, 10fps difference or so in some games, bit less on others, so 30fps is 20 on vulkan
link s awakening is a fw fps slower but it stutters like ogl, thought vulkan would improve that
low fifo, don t remember what it means, cpu and gpu usage is low, like 50% - 40%

2022-06-12 21:32 UTC, rgbarros120 commented
Goodnight. I would like to know if there will be corrections to the pipelines in the emulator on the AMD side, because in the emulator kernel the pipelines are working incorrectly.

2022-06-12 21:46 UTC, gdkchan commented
Can you clarify whats the issue you have? Is it freezing permanently or temporarily? And on which game?

2022-06-12 22:07 UTC, rgbarros120 commented
> Can you clarify whats the issue you have? Is it freezing permanently or temporarily? And on which game?

Good night gdkchan. This kernel error appears in every game I play on the emulator, on amd. But the games run fine. I believe it is a kernel bug. And pokemon sword suffers from performance loss, there are places that run at 30fps and others at 20fps.

2022-06-12 22:41 UTC, rgbarros120 commented
> Can you clarify whats the issue you have? Is it freezing permanently or temporarily? And on which game?

Good night gdkchan. This kernel error appears in every game I play on the emulator, on amd. But the games run fine. I believe it is a kernel bug. And pokemon sword suffers from performance loss, there are places that run at 30fps and others at 20fps. Or it could be some feature that hasn't been added in the emulator yet things like. This error is permanent, it is in all games when I run the emulator

2022-06-12 23:11 UTC, riperiperi commented
The background pipeline compile warning does not indicate any problems, this is expected when shader cache is enabled due to how it works (and the warning will be disabled). If your issues do _not_ happen with shader cache disabled, then maybe there is an issue.

2022-06-12 23:13 UTC, riperiperi commented
Note that these warnings don't rely on any vendor specific stuff, they happen on NVIDIA too.

2022-06-12 23:30 UTC, rgbarros120 commented
> Note that these warnings don't rely on any vendor specific stuff, they happen on NVIDIA too.

OK. I thought it was an emulator kernel bug, but good

2022-06-13 00:07 UTC, ayurai commented
https://user-images.githubusercontent.com/20160968/173258920-247e07cc-9453-4e22-b682-53fd0b3baa69.mp4

https://user-images.githubusercontent.com/20160968/173259156-ab4f346d-1020-4309-9e50-d9cf55f969aa.mp4

[Ryujinx_1.1.0+eae47f0_2022-06-12_19-52-24.log](https://github.com/Ryujinx/Ryujinx/files/8887048/Ryujinx_1.1.0%2Beae47f0_2022-06-12_19-52-24.log)

2022-06-13 00:10 UTC, ayurai commented
> > Note that these warnings don't rely on any vendor specific stuff, they happen on NVIDIA too.
> 
> OK. I thought it was an emulator kernel bug, but good. Now pokemon sword needs to improve performance more and fix the shadow and lights bug

also riperiperi  had already answered you question 5 days ago.
![image](https://user-images.githubusercontent.com/20160968/173259298-7b8ac252-bb1e-42da-b70d-1ce62c40f915.png)

2022-06-14 00:53 UTC, AlfredoDore commented
Turok 2
game starts but has several graphical problems and gets stuck on black start screen
Log file
[Ryujinx_1.1.0+f1454a9_2022-06-13_21-40-58.log](https://github.com/Ryujinx/Ryujinx/files/8895419/Ryujinx_1.1.0%2Bf1454a9_2022-06-13_21-40-58.log)
Spec
ryujinx-Release-1.1.0+f1454a9-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.5.2

2022-06-14 01:02 UTC, AlfredoDore commented
Donkey Kong Kountr Tropical Freeze
still has performance loss and texture error
Log file
[Uploading Ryujinx_1.1.0+f1454a9_2022-06-13_21-56-03.log…]()
Spec
ryujinx-Release-1.1.0+f1454a9-win_x64
STORAGE: SSD
CPU: AMD Ryzen 7 2700X Eight-Core Processor 4.19 GHz
RAM: 16gb (1600mhz)
GPU: Radeon RX 580 Series 4GB GDDR5 1750Hz
DRIVER: 22.5.2
![imagem](https://user-images.githubusercontent.com/90729203/173471578-315dcffe-7707-4a6a-8bea-21c69c6e2ea7.png)

2022-06-14 01:12 UTC, AlfredoDore commented
in Doom 3 this error appears in the log, in which it is stuck in the menu, but I think there is something else with problem or missing to make it work correctly
![imagem](https://user-images.githubusercontent.com/90729203/173472447-7e84c60a-1283-4dc3-834c-65ae4395c450.png)

2022-06-14 05:51 UTC, Wfree86 commented
I know that y'all got on that other person's case for reposting the same issues. But I'm posting new logs as I have now deleted my roaming folder (with mods) and let it get remade with the launch of the build. Ran with shader cache on and off. Initial movie sounds plays with a black screen and then eventually crashes when cache is off, or a black screen forever with cache on. V-sync off.
[Ryujinx_1.1.0+1f2257f_2022-06-13_22-28-20.log](https://github.com/Ryujinx/Ryujinx/files/8896776/Ryujinx_1.1.0%2B1f2257f_2022-06-13_22-28-20.log)
[Ryujinx_1.1.0+1f2257f_2022-06-13_22-31-49.log](https://github.com/Ryujinx/Ryujinx/files/8896777/Ryujinx_1.1.0%2B1f2257f_2022-06-13_22-31-49.log)

2022-06-14 21:58 UTC, rgbarros120 commented
Good night Gdkchan all in peace, would it be possible to improve the performance for the game pokemon sword and shield for the AMD staff. There are some parts of the game that run between 20 to 22 fps and other places at 30fps. I would appreciate if you could help us amd users in this game.

2022-06-14 21:59 UTC, markbex commented
[Ryujinx/Ryujinx] Vulkan backend

2022-06-15 17:37 UTC, rgbarros120 commented
> > Pokemon Sword still has some shadow and light bugs in several places on AMD, as shown in the attached figures. Needs repair.
> > My specs: RADEON RX 560 OC 4GB 16 GB DE RAM (2400mhz) RYZEN 5 1600
> > DRIVER: 22.4.1
> > ![Sem título](https://user-images.githubusercontent.com/73244003/164513815-65bcefc4-437c-4687-8215-bf8849aff02e.png)
> > ![Sem título](https://user-images.githubusercontent.com/73244003/164555108-ad39a74e-fd42-4f25-b18f-30d930a61adb.png)
> > ![Sem título](https://user-images.githubusercontent.com/73244003/164556835-70c51cd2-1971-4a6b-a2d5-8e54b9bef931.png)
> > [Ryujinx_1.1.0+47aa773_2022-04-21_13-54-10.log](https://github.com/Ryujinx/Ryujinx/files/8532939/Ryujinx_1.1.0%2B47aa773_2022-04-21_13-54-10.log)
> 
> I think these issues should be fixed now as of my last commit. Give it another try. (will not make the game any faster)
I had already reported about this too. another thing that has to be repaired is also this performance.

2022-06-16 16:34 UTC, gdkchan commented
> Wonder Boy Collection does not start log: [Ryujinx_1.1.0+cb9b5ca_2022-06-16_13-22-08.log](https://github.com/Ryujinx/Ryujinx/files/8920730/Ryujinx_1.1.0%2Bcb9b5ca_2022-06-16_13-22-08.log) AMD driver 22.5.2 RX 580 16ram Ryzen 7 2700x ryujinx-Release-1.1.0+cb9b5ca-win_x64

You should be testing with the Expand DRAM to 6GB option *disabled*.

2022-06-16 17:34 UTC, rgbarros120 commented
Good afternoon gdkchan. some prediction of when the lights and shadows bugs will be fixed and performance will be fixed in pokemon sword and shield on amd.

2022-06-16 18:08 UTC, riperiperi commented
> Good afternoon gdkchan. some prediction of when the lights and shadows bugs will be fixed and performance will be fixed in pokemon sword and shield on amd.

I literally told you to retest last time.

2022-06-16 18:10 UTC, rgbarros120 commented
> > Good afternoon gdkchan. some prediction of when the lights and shadows bugs will be fixed and performance will be fixed in pokemon sword and shield on amd.
> 
> I literally told you to retest last time.

I tested the same thing yet

2022-06-16 19:24 UTC, AlfredoDore commented
> You should be testing with the Expand DRAM to 6GB option _disabled_

![imagem](https://user-images.githubusercontent.com/90729203/174149019-40e5cd4a-0fb8-4c54-9be9-bd2f55ef44f2.png)

2022-06-16 19:58 UTC, AlfredoDore commented
> Please make sure the "Expand DRAM to 6GB" option is disabled. I think having it enabled is causing the crash that you mentioned on Wonder Boy Collection. Thank you.

true, it started, but it gets stuck
![imagem](https://user-images.githubusercontent.com/90729203/174153913-bc1b8f10-6e3b-4fcd-9376-1315bbfaa021.png)

2022-06-19 23:20 UTC, rgbarros120 commented
The pokemon shinning pearl game is giving some delays between wheel 205 and the eternal city, needs to fix this part.

My specs: RADEON RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM (2400MHZ)
DRIVER: 22.5.2

![Sem título](https://user-images.githubusercontent.com/73244003/174504017-07be8bc4-e116-4413-8b41-cbc9c7cfc41e.png)

[Ryujinx_1.1.0+a1bf224_2022-06-19_20-00-44.log](https://github.com/Ryujinx/Ryujinx/files/8936580/Ryujinx_1.1.0%2Ba1bf224_2022-06-19_20-00-44.log)

2022-06-19 23:20 UTC, rgbarros120 commented
The pokemon shinning pearl game is giving some delays between wheel 205 and the eternal city, needs to fix this part.

My specs: RADEON RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM (2400MHZ)
DRIVER: 22.5.2

![Sem título](https://user-images.githubusercontent.com/73244003/174504017-07be8bc4-e116-4413-8b41-cbc9c7cfc41e.png)

[Ryujinx_1.1.0+a1bf224_2022-06-19_20-00-44.log](https://github.com/Ryujinx/Ryujinx/files/8936580/Ryujinx_1.1.0%2Ba1bf224_2022-06-19_20-00-44.log)

2022-06-22 17:29 UTC, ghools commented
download for basic version on windows OS isn't working.

2022-06-22 17:38 UTC, RedPana commented
> download for both basic and dev version on windows OS isn't working.

Works for me, try using different browser

2022-06-22 17:40 UTC, ghools commented
> Works for me, try using different browser

Tried multiple browsers on multiple computers. Will try on a VPN to see if that will fix it. All other files/versions are downloading fine.

2022-06-22 22:37 UTC, XDM-Inc commented
some issues i get with a mix of games running the vulkan backend
compiled together in a log

Vulkan info: (Vulkan v1.3.212, Driver v2.0.226)

OS: Manjaro Linux (KDE)
CPU: ryzen 5950x
GPU: Radeon 6900xt
RAM:64gb ram g skill trident z

[**Collective Logs**](https://pastebin.com/BNTcXsWE)

2022-06-26 17:18 UTC, rgbarros120 commented
Sonic Origins game is crashing all the time, needs repair immediately.

My specs: RADEON RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM (2400MHZ)
DRIVER: 22.5.2

2022-06-28 17:04 UTC, AutumnWolfMike commented
The ground is messed up on Age of Calamity and Fire Emblem Warriors 3 Hopes on RX 500 series AMD GPUs.

It is garbled.

![ryujinx_capture_2022-06-28_10-35-53](https://user-images.githubusercontent.com/98867177/176240784-4173df14-5caa-4ced-b929-9acb177965dc.png)

Ryujinx version: Ryujinx_1.1.0+1c895ed

Here is the log file

[Ryujinx_1.1.0+1c895ed_2022-06-28_10-25-33.log](https://github.com/Ryujinx/Ryujinx/files/9003193/Ryujinx_1.1.0%2B1c895ed_2022-06-28_10-25-33.log)

Game version: 1.0.1

    System Specs:
        OS: Windows 10
        CPU: Ryzen 5 3500X
        GPU: RX 570 4GB VRAM
        RAM: 16B RAM

The game runs well aside from that, the audio stutters a bit.

2022-07-01 12:29 UTC, ghost478 commented
Not sure why it's crashing but it crashes for me when trying Monster Hunter Rise with the latest update.



```
System:
OS: Windows 11
APU: Ryzen 5 4500U
RAM: 16GB RAM
```
[Ryujinx_1.1.0+1c895ed_2022-07-01_22-24-13.log](https://github.com/Ryujinx/Ryujinx/files/9028784/Ryujinx_1.1.0%2B1c895ed_2022-07-01_22-24-13.log)

2022-07-01 12:36 UTC, MetrosexualGarbodor commented
@ghost478 The latest MHR update does not start on Ryujinx. This is unrelated to Vulkan.

2022-07-01 12:42 UTC, ghost478 commented
> @ghost478 The latest MHR update does not start on Ryujinx. This is unrelated to Vulkan.

Ah, my bad. Sorry about that.

2022-07-04 22:33 UTC, riperiperi commented
> The ground is messed up on Age of Calamity and Fire Emblem Warriors 3 Hopes on RX 500 series AMD GPUs.
> 
> It is garbled.
> 
> ![ryujinx_capture_2022-06-28_10-35-53](https://user-images.githubusercontent.com/98867177/176240784-4173df14-5caa-4ced-b929-9acb177965dc.png)
> 
> Ryujinx version: Ryujinx_1.1.0+1c895ed
> 
> Here is the log file
> 
> [Ryujinx_1.1.0+1c895ed_2022-06-28_10-25-33.log](https://github.com/Ryujinx/Ryujinx/files/9003193/Ryujinx_1.1.0%2B1c895ed_2022-06-28_10-25-33.log)
> 
> Game version: 1.0.1
> 
> ```
> System Specs:
>     OS: Windows 10
>     CPU: Ryzen 5 3500X
>     GPU: RX 570 4GB VRAM
>     RAM: 16GB RAM
> ```
> 
> The game runs well aside from that, the audio stutters a bit.

I've implemented a potential fix for this issue on AMD GCN gpus, as well as a few others:

- Corrupted Mipmap Levels on Terrain in Fire Emblem Warriors: Three Hopes
- Corrupted Mipmap Levels on Terrain in The Legend of Zelds: Breath of the Wild
- Broken character lighting in Mario Kart 8, after some time ingame or when cycling characters in the menu for a while.
- Possibly more.

Let me know if these issues are resolved. Also, someone please tell me if the issues were happening on Mesa before, as the workaround is also enabled there. Would also appreciate tests from users with Vega GPUs, as the workaround is only enabled up to Polaris right now.

2022-07-05 01:00 UTC, AutumnWolfMike commented
> > The ground is messed up on Age of Calamity and Fire Emblem Warriors 3 Hopes on RX 500 series AMD GPUs.
> > It is garbled.
> > ![ryujinx_capture_2022-06-28_10-35-53](https://user-images.githubusercontent.com/98867177/176240784-4173df14-5caa-4ced-b929-9acb177965dc.png)
> > Ryujinx version: Ryujinx_1.1.0+1c895ed
> > Here is the log file
> > [Ryujinx_1.1.0+1c895ed_2022-06-28_10-25-33.log](https://github.com/Ryujinx/Ryujinx/files/9003193/Ryujinx_1.1.0%2B1c895ed_2022-06-28_10-25-33.log)
> > Game version: 1.0.1
> > ```
> > System Specs:
> >     OS: Windows 10
> >     CPU: Ryzen 5 3500X
> >     GPU: RX 570 4GB VRAM
> >     RAM: 16GB RAM
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The game runs well aside from that, the audio stutters a bit.
> 
> I've implemented a potential fix for this issue on AMD GCN gpus, as well as a few others:
> 
>     * Corrupted Mipmap Levels on Terrain in Fire Emblem Warriors: Three Hopes (seen above)
> 
>     * Corrupted Mipmap Levels on Terrain in The Legend of Zelda: Breath of the Wild
> 
>     * Broken character lighting in Mario Kart 8, after some time ingame or when cycling characters in the menu for a while.
> 
>     * Possibly more.
> 
> 
> Let me know if these issues are resolved. Also, someone please tell me if the issues were happening on Mesa before, as the workaround is also enabled there. Would also appreciate tests from users with Vega GPUs, as the workaround is only enabled up to Polaris right now.

I can confirm both Warriors (AOC, FEW3H) games are rendering ground textures properly now (at least on my RX 570 4GB), lightsources are still not quite there (flicker) but I saw similar behaviour on the OGL backend so it must be an AMD thing

2022-07-05 02:39 UTC, ayurai commented
Not sure if is a know issue , but looks there is a good amount of crashes in mario and sonic olympic games 2020 
i5-12400
GeForce GTX 1060
Driver v516.59

[Ryujinx_1.1.0+388845f_2022-07-04_23-31-09.log](https://github.com/Ryujinx/Ryujinx/files/9042844/Ryujinx_1.1.0%2B388845f_2022-07-04_23-31-09.log)
[Ryujinx_1.1.0+388845f_2022-07-04_23-26-34.log](https://github.com/Ryujinx/Ryujinx/files/9042845/Ryujinx_1.1.0%2B388845f_2022-07-04_23-26-34.log)

2022-07-05 22:39 UTC, TYTMOC commented
Hello everyone!
Suddenly I can't launch any games on emulator version later than 1.1.0+065a43d (39e5f7f, 388845f, 3bda523). Every time emulator just stops launch process with the same red colored text in console:
```
00:00:01.207 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Ryujinx.Memory.WindowsShared.WindowsApiException: MapViewOfFile3 returned error code 0x3E6.
   at Ryujinx.Memory.WindowsShared.PlaceholderManager.MapViewInternal(IntPtr sharedMemory, UInt64 srcOffset, IntPtr location, IntPtr size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 139
   at Ryujinx.Memory.WindowsShared.PlaceholderManager.MapView(IntPtr sharedMemory, UInt64 srcOffset, IntPtr location, IntPtr size, MemoryBlock owner) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\WindowsShared\PlaceholderManager.cs:line 106
   at Ryujinx.Memory.MemoryManagement.MapView(IntPtr sharedMemory, UInt64 srcOffset, IntPtr address, UInt64 size, MemoryBlock owner) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\MemoryManagement.cs:line 81
   at Ryujinx.Memory.MemoryBlock.MapView(MemoryBlock srcBlock, UInt64 srcOffset, UInt64 dstOffset, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\MemoryBlock.cs:line 150
   at Ryujinx.Cpu.Jit.MemoryManagerHostMapped.Map(UInt64 va, UInt64 pa, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\MemoryManagerHostMapped.cs:line 152
   at Ryujinx.HLE.HOS.Kernel.Memory.KPageTable.MapPages(UInt64 address, KPageList pageList, KMemoryPermission permission, Boolean shouldFillPages, Byte fillValue) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTable.cs:line 127
   at Ryujinx.HLE.HOS.Kernel.Memory.KPageTableBase.AllocateAndMapPages(UInt64 address, UInt64 pagesCount, KMemoryPermission permission) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTableBase.cs:line 567
   at Ryujinx.HLE.HOS.Kernel.Memory.KPageTableBase.MapPages(UInt64 address, UInt64 pagesCount, MemoryState state, KMemoryPermission permission) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Memory\KPageTableBase.cs:line 543
   at Ryujinx.HLE.HOS.Kernel.Process.KProcess.Initialize(ProcessCreationInfo creationInfo, ReadOnlySpan`1 capabilities, KResourceLimit resourceLimit, MemoryRegion memRegion, IProcessContextFactory contextFactory, ThreadStart customThreadStart) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Process\KProcess.cs:line 310
   at Ryujinx.HLE.HOS.ProgramLoader.LoadNsos(KernelContext context, ProcessTamperInfo& tamperInfo, MetaLoader metaData, ProgramInfo programInfo, Byte[] arguments, IExecutable[] executables) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ProgramLoader.cs:line 154
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadExeFs(IFileSystem codeFs, MetaLoader metaData, Boolean isHomebrew) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 661
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 520
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 288
   at Ryujinx.Ui.MainWindow.LoadApplication(String path, Boolean startFullscreen) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 823
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\MainWindow.cs:line 1184
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```
Here's the full log:
[Ryujinx_1.1.0+3bda523_2022-07-06_00-50-43.log](https://github.com/Ryujinx/Ryujinx/files/9050021/Ryujinx_1.1.0%2B3bda523_2022-07-06_00-50-43.log)

2022-07-05 22:43 UTC, MetrosexualGarbodor commented
@TYTMOC This error is usually caused by antivirus software and not at all related to Vulkan. Either make an exception for Ryujinx or get rid of your antivirus. And please don't ask for help on GitHub, we have [Discord](https://discord.gg/ryujinx) for that.

2022-07-06 15:57 UTC, rgbarros120 commented
I wanted to thank the Ryunjxy development team for fixing the mario kart 8 deluxe characters dark shadows bug on AMD. I would also be grateful if you could improve the performance more in the game pokemon sword and shield too, there are some parts of the game that the fps is below 30fps and some parts that run at 30.

2022-07-06 16:34 UTC, rgbarros120 commented
The bug of the dark shadows of the mario kart 8 deluxe character selection was fixed, but in compensation it generated another new bug, as shown in the attached figure.

![Sem título](https://user-images.githubusercontent.com/73244003/177599827-5575f1ea-6d00-4c0d-9c50-7a6c85a121e9.png)
[Ryujinx_1.1.0+3bda523_2022-07-06_13-28-04.log](https://github.com/Ryujinx/Ryujinx/files/9056562/Ryujinx_1.1.0%2B3bda523_2022-07-06_13-28-04.log)


My specs: RADEON RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM (2400mhz)
DRIVER: 22.6.1

2022-07-07 02:00 UTC, jvmke commented
This issue is still present when playing Triangle Strategy. 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3853

2022-07-10 01:49 UTC, XDM-Inc commented
@gdkchan In theory, would i have the ability to combine your vulkan commits AND the LDN versions together to use ldn version to play multiplayer? is their even public source for the ldn version?

2022-07-10 02:05 UTC, MetrosexualGarbodor commented
@XDM-Inc the LDN code is not currently open source. After this PR is merged, there will be an LDN build with Vulkan.

Please next time don't use GitHub for general questions, this discussion is for reporting Vulkan issues or findings. Use [discord](https://discord.gg/ryujinx) instead.

2022-07-10 02:07 UTC, XDM-Inc commented
> @XDM-Inc the LDN code is not currently open source. After this PR is merged, there will be an LDN build with Vulkan.
> 
> Please next time don't use GitHub for general questions, this discussion is for reporting Vulkan issues or findings. Use [discord](https://discord.gg/ryujinx) instead.

thanks and sorry

2022-07-12 03:58 UTC, gdkchan commented
This should be ready for review. I will see if I can fix a few more of the remaining issues during the week, but it should not be considered blocking, we can always fix them later.
A decision still needs to be made about what should be the default backend. Currently it is Vulkan.

2022-07-12 06:06 UTC, EmulationFanatic commented
> This should be ready for review. I will see if I can fix a few more of the remaining issues during the week, but it should not be considered blocking, we can always fix them later. A decision still needs to be made about what should be the default backend. Currently it is Vulkan.

Is it possible to set the default backend per detected GPU vendor? If so, my preference would be to have OpenGL be set as default for Nvidia GPUs only, with Vulkan as the default otherwise.

2022-07-12 16:02 UTC, MutantAura commented
> Is it possible to set the default backend per detected GPU vendor? If so, my preference would be to have OpenGL be set as default for Nvidia GPUs only, with Vulkan as the default otherwise.

Not sure I can agree on this one. For 90% of games (and basically all the AAA ones most people play) Vulkan will be the preferred option for Nvidia just due to shader performance. OpenGL being the exception, not the rule is how it _will_ be going forward and I don't see any point adding an artificial roadblock that everyone will change/we'll recommend they change anyway when they ask for support.

2022-07-12 16:09 UTC, sakuka47 commented
Hello, 

On the other hand vulkan works better on rtx with 516.xx drivers

And for Pascal/Maxwell the 512.xx drivers would be better under Vulkan, to be confirmed?

2022-07-12 16:20 UTC, gdkchan commented
> Is it possible to set the default backend per detected GPU vendor? If so, my preference would be to have OpenGL be set as default for Nvidia GPUs only, with Vulkan as the default otherwise.

It's possible. Presumably if there are multiple GPUs, it would assume the discrete one will be the one used.

> Not sure I can agree on this one. For 90% of games (and basically all the AAA ones most people play) Vulkan will be the preferred option for Nvidia just due to shader performance. OpenGL being the exception, not the rule is how it _will_ be going forward and I don't see any point adding an artificial roadblock that everyone will change/we'll recommend they change anyway when they ask for support.
> 
> If a game works on both then VK is the defacto choice and as such OpenGL should be treated as the fall-back imo.

My personal preference is making OpenGL the default, because that's what is being used on master right now. So when people update they would not see the Vulkan improvements without changing settings, but there's also little to no risk of something breaking that way.

2022-07-12 20:46 UTC, EmulationFanatic commented
> > Is it possible to set the default backend per detected GPU vendor? If so, my preference would be to have OpenGL be set as default for Nvidia GPUs only, with Vulkan as the default otherwise.
> 
> Not sure I can agree on this one. For 90% of games (and basically all the AAA ones most people play) Vulkan will be the preferred option for Nvidia just due to shader performance. OpenGL being the exception, not the rule is how it _will_ be going forward and I don't see any point adding an artificial roadblock that everyone will change/we'll recommend they change anyway when they ask for support.
> 
> If a game works on both then VK is the defacto choice and as such OpenGL should be treated as the fall-back imo.

I've been out of the loop for awhile and thought that there may still have been performance or compatibility issues with Vulkan on Nvidia. If performance and compatibility is otherwise equal, I'm sure the shader compilation speed alone would make Vulkan a preferred choice for most users.

A more intrusive but more plainly apparent route would be to have a GUI pop-up the first time a vulkan-capable build is launched, prompting the user to select their graphics backend (and GPU, if more than one exist).

Something like:
"Vulkan is now supported. Enable Vulkan backend? 
Yes > Select GPU from dropdown if applicable. 
No (will remain using OpenGL)."
And include a note about where to go in Settings to change it in the future.

Once this is set, it wouldn't prompt again.

2022-07-12 22:33 UTC, rgbarros120 commented
Goodnight. Just to let you know that these latest builds that came out recently on Ryujnxy are causing some light bugs on the characters and also on the tracks, in previous builds there wasn't this bug of the characters on the tracks, only on the character selection screen. Well, it's something that needs to be reviewed immediately, because that way the game was totally unplayable due to these light bugs that are occurring.

My Specs: Radeon RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM (2400mhz)
Driver: 22.6.1

![Sem título](https://user-images.githubusercontent.com/73244003/178609229-3a7b09c0-447f-4456-b93b-192f4311362b.png)
![Sem título 2](https://user-images.githubusercontent.com/73244003/178609283-ba16a835-a94e-418a-8ce3-fdb507925707.png)

[Ryujinx_1.1.0+b621cb4_2022-07-12_19-23-04.log](https://github.com/Ryujinx/Ryujinx/files/9097262/Ryujinx_1.1.0%2Bb621cb4_2022-07-12_19-23-04.log)

2022-07-13 11:31 UTC, Mario9699 commented
I can't play eBASEBALLパワフルプロ野球2022
![未命名](https://user-images.githubusercontent.com/103609670/178723911-83d3fd63-f1a3-48f5-b412-1799102754ec.jpg)
[Ryujinx_1.1.0+080a263_2022-07-13_19-18-13.log](https://github.com/Ryujinx/Ryujinx/files/9101631/Ryujinx_1.1.0%2B080a263_2022-07-13_19-18-13.log)

2022-07-13 11:50 UTC, Mario9699 commented
> > 我不能玩eBASEBALLパワフルプロ野球2022 [Ryujinx_1.1.0+080a263_2022-07-13_19-18-13.log](https://github.com/Ryujinx/Ryujinx/files/9101631/Ryujinx_1.1.0%2B080a263_2022-07-13_19-18-13.log)![未命名](https://user-images.githubusercontent.com/103609670/178723911-83d3fd63-f1a3-48f5-b412-1799102754ec.jpg) [](https://github.com/Ryujinx/Ryujinx/files/9101631/Ryujinx_1.1.0%2B080a263_2022-07-13_19-18-13.log)
> 
> 這遊戲在master上能用嗎？

Ryujinx_1.1.0+7abe931 can play eBASEBALLパワフルプロ野球2022
[Ryujinx_1.1.0+7abe931_2022-07-13_07-15-51.log](https://github.com/Ryujinx/Ryujinx/files/9101763/Ryujinx_1.1.0%2B7abe931_2022-07-13_07-15-51.log)

2022-07-13 11:53 UTC, MetrosexualGarbodor commented
@Mario9699 the error you're encountering is due to your antivirus software. Either uninstall it or figure out how to make an exception. And please next time come to Discord for help.

2022-07-13 11:55 UTC, Mario9699 commented
> 

OK I try it

2022-07-13 12:03 UTC, Mario9699 commented
> 

It work,thank you

2022-07-13 16:04 UTC, rgbarros120 commented
Good afternoon gdkchan, I tested this last build on mario kart 8 deluxe, the bug still persists.

2022-07-14 21:06 UTC, MetrosexualGarbodor commented
Splatoon 2 is broken on OpenGL on the latest build (1.1.0+080a263). The screen grinds to a halt, but the game is still running underneath. I tried purging shaders and PPTC to no avail.

https://user-images.githubusercontent.com/79612681/179081025-c33aa23b-4396-4e63-8278-fc9786e25b5a.mp4


If I disable Vsync, the screen starts working again, but the NPCs are all frozen. The frozen image also refreshes once if I pause and unpause emulation.


https://user-images.githubusercontent.com/79612681/179083886-f790378e-eca2-48c7-8a2f-be1d9a37b909.mp4


[Ryujinx_1.1.0+080a263_2022-07-14_21-32-01.log](https://github.com/Ryujinx/Ryujinx/files/9115228/Ryujinx_1.1.0%2B080a263_2022-07-14_21-32-01.log)


It randomly crashed when retesting.
[Ryujinx_1.1.0+080a263_2022-07-14_21-41-15.log](https://github.com/Ryujinx/Ryujinx/files/9115404/Ryujinx_1.1.0%2B080a263_2022-07-14_21-41-15.log)

Crashed on Vulkan as well, which seems to exhibit the same behaviour.


https://user-images.githubusercontent.com/79612681/179086023-2ee8a244-3247-4ccd-82de-39bf13ee4306.mp4





[Ryujinx_1.1.0+080a263_2022-07-14_21-56-50.log](https://github.com/Ryujinx/Ryujinx/files/9115426/Ryujinx_1.1.0%2B080a263_2022-07-14_21-56-50.log)


This does not happen on master.

https://user-images.githubusercontent.com/79612681/179082946-2ff06ba2-b594-4faf-8725-ec3bc3e8a964.mp4

2022-07-15 01:22 UTC, gdkchan commented
This looks like the issue that is caused by misconfigured controller settings. You can see several applet messages on the console which means the game does not like the current controller configuration. You need to make sure that Player 2 is disabled.

2022-07-15 17:34 UTC, austintraver commented
Smash Ultimate was working very successfully for me, running Windows 11 with a NVIDIA 3080Ti 

Thank you for implementing this.

2022-07-15 18:03 UTC, rgbarros120 commented
Good afternoon. Any light bug fix prediction for mario kart 8 deluxe game. These latest builds made the game even worse, needing urgent repair.

2022-07-17 22:34 UTC, rgbarros120 commented
Mario kart 8 deluxe still has the lights bug in recent vulkan builds and needs to be fixed.

My Specs: RADEON RX 560 OC 4GB; RYZEN 5 1600; 16GB DE RAM (2400MHZ)
Driver: 22.6.1
![Sem título](https://user-images.githubusercontent.com/73244003/179427425-a4a613d3-4f96-4a46-b4a2-6122688f0de5.png)
[Ryujinx_1.1.0+38be8f8_2022-07-17_19-21-57.log](https://github.com/Ryujinx/Ryujinx/files/9128687/Ryujinx_1.1.0%2B38be8f8_2022-07-17_19-21-57.log)

2022-07-17 22:51 UTC, rgbarros120 commented
Goodnight. Why they removed my bug report from mario kart 8 deluxe I don't understand.

2022-07-17 23:00 UTC, MutantAura commented
> Goodnight. Why they removed my bug report from mario kart 8 deluxe I don't understand.

I'm removing these posts because we've already told you _multiple times_ that duplicate bug reports will be removed. Unless a developer or commit message specifically mentions that a bug has been fixed then do not continue to post identical bugs. We are aware of bugs people report. We are interested in change, not stuff that's the same as before.

Thanks.

2022-07-17 23:03 UTC, rgbarros120 commented
> > Goodnight. Why they removed my bug report from mario kart 8 deluxe I don't understand.
> 
> I'm removing these posts because we've already told you _multiple times_ that duplicate bug reports will be removed. Unless a developer or commit message specifically mentions that a bug has been fixed then do not continue to post identical bugs. We are aware of bugs people report. We are interested in change, not stuff that's the same as before.
> 
> Thanks.

Sorry

2022-07-20 01:33 UTC, Ackliez commented
Animal crossing new Horizons has a weird shadow in the water when using the Vulkan backend not present in the OpenGL backend

Vulkan video and log
[Ryujinx_1.1.0+155af37_2022-07-19_20-02-52.log](https://github.com/Ryujinx/Ryujinx/files/9145707/Ryujinx_1.1.0%2B155af37_2022-07-19_20-02-52.log)

https://youtu.be/_vaVsbWtIlM

2022-07-21 12:08 UTC, Mario9699 commented
実況パワフルプロ野球(Nintendo Switch) is bug
![未命名](https://user-images.githubusercontent.com/103609670/180209925-342b533b-3549-4835-9ab1-344f0f6587c0.jpg)
[Ryujinx_1.1.0+155af37_2022-07-21_19-38-07.log](https://github.com/Ryujinx/Ryujinx/files/9159155/Ryujinx_1.1.0%2B155af37_2022-07-21_19-38-07.log)

2022-07-21 23:27 UTC, rgbarros120 commented
Good night gdkchan all in peace, would you like to fix the mario kart 8 deluxe in the next Ryujnxy update if possible. For AMD users.

Yours sincerely
Rodrigo

2022-07-21 23:49 UTC, gdkchan commented
It's being worked on, but no ETA on a fix yet.

2022-07-21 23:56 UTC, rgbarros120 commented
> It's being worked on, but no ETA on a fix yet.

Ok thanks.

2022-07-22 19:32 UTC, Nobodygr commented
> It's being worked on, but no ETA on a fix yet.

Hi,

would also love for xenoblade definitive edition to be fixed. Im crashing for no reason at random times mostly at menus. I've posted my log on pr.

2022-07-23 18:09 UTC, Thog approved these changes

2022-07-23 18:18 UTC, Reonu approved these changes
based

2022-07-23 23:09 UTC, Mario9699 commented
JIKKYOU PAWAFURU PURO YAKYU(実況パワフルプロ野球)(Nintendo Switch) is not fix yet
[Ryujinx_1.1.0+c3f37c0_2022-07-24_06-48-19.log](https://github.com/Ryujinx/Ryujinx/files/9174822/Ryujinx_1.1.0%2Bc3f37c0_2022-07-24_06-48-19.log)

2022-07-25 11:36 UTC, riperiperi reviewed
WIP review, still some files to look at.

2022-07-25 11:36 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/BufferHolder.cs
> +            // InsertBarrier(commandBuffer, isWrite);
Remove?

2022-07-25 11:36 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/BufferHolder.cs
> +                // bool needsFlush = _gd.CommandBufferPool.HasWaitableOnRentedCommandBuffer(_waitable, offset, dataSize);
Remove?

2022-07-25 11:36 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/CommandBufferPool.cs
> +                // _api.QueueWaitIdle(_queue);
Remove?

2022-07-25 11:36 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs
> +                    new DescriptorPoolSize(DescriptorType.StorageTexelBuffer, Constants.MaxImageBindings * DescriptorPoolMultiplier)
Aren't we using 4 descriptor sets now?

2022-07-25 11:36 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/SyncManager.cs
> +                        Logger.Error?.PrintMsg(LogClass.Gpu, $"GL Sync Object {result.ID} failed to signal within 1000ms. Continuing...");
Not really a `GL Sync Object`, though makes sense that this was written as it's a straight port of the GL sync manager.

2022-07-25 11:36 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/SamplerHolder.cs
> +                UnnormalizedCoordinates = false // TODO: Use unnormalized coordinates.
Don't we emulate this in the shader?

2022-07-25 14:27 UTC, gdkchan commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "SettingsEnableTextureRecompression": "Enable Texture Recompression",
I only added them to the English one to avoid even more conflicts with master, and because I would need to use an automated translator for most of them which wouldn't give the best translations.

2022-07-25 14:30 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
> +                // most migrated shaders would be unused due to the state not matching.
I planned to remove it after Vulkan is merged to avoid making diffs even larger, but I don't mind removing it now.

2022-07-25 14:34 UTC, gdkchan commented on Ryujinx.Graphics.Shader/CodeGen/Spirv/Declarations.cs
> +                AttributeConsts.VertexId => BuiltIn.VertexId, // FIXME: Invalid
`gl_VertexIndex - gl_BaseVertex` and `gl_InstanceIndex - gl_BaseInstance`.

2022-07-25 14:37 UTC, gdkchan commented on Ryujinx.Graphics.Shader/CodeGen/Spirv/SpirvGenerator.cs
> +                        case InputTopology.Points:
I initially assumed it was not necessary to add anything for the `Triangles` `ExecutionMode`, but then realized that to not be the case and added it later. I can change it now.

2022-07-25 14:38 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/DescriptorSetManager.cs
> +                    new DescriptorPoolSize(DescriptorType.StorageTexelBuffer, Constants.MaxImageBindings * DescriptorPoolMultiplier)
Yes, but it still uses 6 descriptor types in total, so it still requires 6 `DescriptorPoolSize` entries (unless there is a way to specify more than one type per entry?).

2022-07-25 14:40 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/SyncManager.cs
> +                        Logger.Error?.PrintMsg(LogClass.Gpu, $"GL Sync Object {result.ID} failed to signal within 1000ms. Continuing...");
I can change to it `VK Sync Object` but that doesn't really exist in Vulkan. I think it would be better to have the method take a timeout parameter and return a bool or enum, and handle this on the GPU project (and just call it "Sync Object" there), it would be more flexible in case we need to perform waits with different timeout in the future or just check if it has been signalled without waiting.

2022-07-25 15:19 UTC, gdkchan commented on Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
> +                        this.EmitVertex();
The call to `PrepareForVertexReturn` was added to `EmitOut` directly, so `EmitVertex` does not call it. So I suppose it is incorrect for shaders that uses geometry shader passthrough right now, but this is also the case when the Geometry Shader Passthrough is used. I can fix it on the fallback path, but it will remain broken when the extension is supported.

2022-07-25 15:44 UTC, rgbarros120 commented
Any fix forecast for mario kart 8 deluxe game on AMD, related to lights bug.

2022-07-25 15:54 UTC, gdkchan commented
> Any fix forecast for mario kart 8 deluxe game on AMD, related to lights bug.

It might be fixed after Vulkan is merged, it is an issue with copy dependencies which is not directly related to Vulkan (it only affects AMD GCN because those GPUs have an issue with cubemap texture views, which forces us to use copy dependencies for them).

2022-07-25 16:04 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Memory/MemoryManager.cs
> +        public void WriteUntracked<T>(ulong va, T value) where T : unmanaged
Yea it was unused, removed.

2022-07-25 16:04 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs
> +            // We can just have a single file for all vendors.
No, not sure why I didn't remove it before. I removed it now, but it means there will be a now unused `vulkan.toc` and `vulkan.data` file on the shader cache folder now, that should probably be deleted manually.

2022-07-25 16:05 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
> +                // most migrated shaders would be unused due to the state not matching.
Removed.

2022-07-25 16:06 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/BufferRangeList.cs
> +    struct BufferRangeList
Removed.

2022-07-25 16:07 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/SyncManager.cs
> +                        Logger.Error?.PrintMsg(LogClass.Gpu, $"GL Sync Object {result.ID} failed to signal within 1000ms. Continuing...");
Changed to "VK Sync Object". Don't mind doing what I suggested above either if you prefer.

2022-07-25 16:09 UTC, gdkchan commented on Ryujinx.Ava/Program.cs
> +                ForceDpiAware.Windows();
Actually I think I can connect a TV that i have here to test this, might try later.

2022-07-25 17:11 UTC, riperiperi commented
From my investigation, the MK8 issue is not Vulkan related. If the polaris workaround is enabled on OpenGL, similar issues occur. I was able to pin this down as data lost when many copy dependencies are present, and fixing it there is going to take some time.

The workaround still fixes Fire Emblem Warriors: Three Hopes and BOTW, so it will remain enabled. The copy dependency fix will be in a separate PR. I don’t have time to work on it now do it might not be fixed before Vulkan merges.

2022-07-25 19:13 UTC, Wfree86 commented
How do I know if a bug I still have still get  looked at if it's marked as
solved in issues? I've added new logs from the last build and I test it on
every new iterance if I think of doing it.

No one's ever acknowledged my original postings so I don't even know if a
bug report was made or corresponds with a known bug. I just found one that
I thought fits the issue.

2022-07-25 19:50 UTC, gdkchan commented
> How do I know if a bug I still have still get looked at if it's marked as solved in issues? I've added new logs from the last build and I test it on every new iterance if I think of doing it. No one's ever acknowledged my original postings so I don't even know if a bug report was made or corresponds with a known bug. I just found one that I thought fits the issue.

Which bug are you talking about? If you reported it before, its possible it got lost due to the many comments here that now got collapsed (which is one of the reasons for merging it asap).

2022-07-25 20:20 UTC, rgbarros120 commented
Gosh what a pity. So the mario kart 8 deluxe bug is quite complex to solve. But I'll wait for the fix. Thanks for listening.

2022-07-26 09:22 UTC, Sovietfowl commented
As the main dev of Skyline emulator I approve this merge.

2022-07-26 12:13 UTC, riperiperi reviewed
Reviewed all files. A few comments remain.

The biggest thing is that host conditional rendering is currently disabled entirely. I can't remember what the issues with this were, and I don't have time to test right now.

Also, the counter queue isn't the best design for vulkan, as it creates one query pool per query, but that can be refactored later.

2022-07-26 12:13 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +                for (int i = 0; i < count; i++)
Warning

2022-07-26 12:13 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +        // TODO: Remove first parameter.
Something to do later?

2022-07-26 12:13 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +                    // _pipeline?.Dispose();
What's this for?

2022-07-26 13:09 UTC, maximums01 commented
Anyone here having this problem when running Marvel Ultimate Alliance 3? I'm using RX550 with latest driver.
![MUA3](https://user-images.githubusercontent.com/110038634/181013603-dce65d03-a0de-4ed1-8bdf-f87e9bf9a806.png)
.

2022-07-26 13:10 UTC, EmulationFanatic commented
> Anyone here having this problem when running Marvel Ultimate Alliance 3? I'm using RX550 with latest driver. ![MUA3](https://user-images.githubusercontent.com/110038634/181013603-dce65d03-a0de-4ed1-8bdf-f87e9bf9a806.png) .

Yes, I have this same issue with Marvel Ultimate Alliance on my RX 580 with the latest drivers.

2022-07-26 16:36 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/FormatTable.cs
> +            // Add(Format.R32Uscaled,          VkFormat.R32Uscaled);
Because those formats don't exist on Vulkan (maybe there is some extension adding them that I'm not aware of?).

2022-07-26 16:39 UTC, GamerzHell9137 commented
Marvel Ultimate Alliance 3 is a known issue on all vendors.

2022-07-26 16:39 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/HelperShader.cs
> +            static GAL.SamplerCreateInfo GetSamplerCreateInfo(MinFilter minFilter, MagFilter magFilter)
I can move it outside the method. It is a static method because it does not need to capture any state. And I have added it inside this instance method because it is the only one that needs to call it. I can move it outside as well, doesn't make much of a difference to me.

2022-07-26 16:42 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineUid.cs
> +            if (!VulkanConfiguration.UseDynamicState)
I can remove it and assume its always true, don't think keeping this has much value now anyways, unless we find a driver where dynamic state is broken.

2022-07-26 16:44 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Shader.cs
> +            // TODO: We should generate the correct code on the shader translator instead of doing this compensation.
Sort of, it's the same problem, but it can't be ignored when doing GLSL -> SPIR-V. When producing SPIR-V directly, we can ignore validation errors as it happens to work in most (?) drivers, but we should eventually fix it since some driver might not support it at all and just explode.

2022-07-26 16:48 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineFull.cs
> +                        // Gd.ConditionalRenderingApi.CmdBeginConditionalRendering(CommandBuffer, conditionalRenderingBeginInfo);
Maybe it's better to enable it after Vulkan is merged? To avoid introducing even more regressions we will need to track down (if it's done as part of a separate PR, at least we will have two versions to compare and know exactly what broke).

2022-07-26 16:49 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
> +                    // TODO: Exception.
I think that might have been added by @Thog ?

2022-07-26 16:51 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +            // TODO.
Maybe it should throw. But I think in the future we will want to write the reference value into the support buffer to avoid creating one shader version per reference value (which honestly is pretty terrible). I guess I will just update the comment for now.

2022-07-26 16:56 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +        // TODO: Remove first parameter.
Right now that parameter is ignored on Vulkan (except on the viewport transform inverse code, but it is not being used correctly in this case, as `first` is supposed to indicate the first viewport it should update, not the `first` viewport to read from the source viewports span). Not sure if I should remove the parameter or fix the implementation...

2022-07-26 16:59 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +                    // _pipeline?.Dispose();
I think it's a leftover from before it had a pipeline cache. It had to destroy the old pipeline and create a new one for every state change (which was very slow). Probably left the code there for quick testing just in case I had to disable the pipeline cache again.

2022-07-26 20:30 UTC, Wfree86 commented
> > How do I know if a bug I still have still get looked at if it's marked as solved in issues? I've added new logs from the last build and I test it on every new iterance if I think of doing it. No one's ever acknowledged my original postings so I don't even know if a bug report was made or corresponds with a known bug. I just found one that I thought fits the issue.
> 
> Which bug are you talking about? If you reported it before, its possible it got lost due to the many comments here that now got collapsed (which is one of the reasons for merging it asap).

Im not sure if my comment got deleted, but I have the continued black screen while on Vulkan when launching SSBU.

2022-07-26 21:49 UTC, EmulationFanatic commented
> Gosh what a pity. So the mario kart 8 deluxe bug is quite complex to solve. But I'll wait for the fix. Thanks for listening. In the meantime, I'm playing in another emulator project.

Can you try on the latest AMD driver released today?
https://drivers.amd.com/drivers/amd-software-adrenalin-edition-22.7.1-win10-win11-july26.exe

2022-07-27 16:48 UTC, SomeoneIsWorking commented
RX570 22.7.1 turned some Vulkan exclusive bugs to not Vulkan exclusive anymore
Apparently when equalizing the performance with Vulkan, AMD also made it in a way where Vulkan bugs carried over to OpenGL

2022-07-27 16:49 UTC, riperiperi commented
They definitely didn;t equalize performance with Vulkan. This PR discussion isn't really the place for discussing opengl driver changes.

2022-07-27 16:50 UTC, SomeoneIsWorking commented
> This PR discussion isn't really the place for discussing opengl driver changes.

Yes but previously I reported some bugs as "Vulkan exclusive" which isn't the case anymore

2022-07-28 01:35 UTC, weihua-lu commented
Built with https://github.com/Ryujinx/Ryujinx/pull/2518/commits/c4555199d4a349d36d2d10df694aed6089852384, Xenoblade DE crashed right on start with RADV.  Runs ok after adding amdvlk though.

Crashed with RADV:

[Ryujinx_9.9.999_2022-07-28_09-27-01.log](https://github.com/Ryujinx/Ryujinx/files/9204605/Ryujinx_9.9.999_2022-07-28_09-27-01.log)

No issue with amdvlk:

[Ryujinx_9.9.999_2022-07-28_09-30-25.log](https://github.com/Ryujinx/Ryujinx/files/9204610/Ryujinx_9.9.999_2022-07-28_09-30-25.log)

2022-07-29 17:58 UTC, MetrosexualGarbodor commented
Xenoblade 3 crashes sometimes on Nvidia Vulkan with `00:02:31.189 |E| GPU.MainThread Gpu : VK Sync Object 43772 failed to signal within 1000ms. Continuing...
00:02:32.175 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".`

In this log it was when loading a heavy cutscene with no shaders compiled, but others have reported crashing when opening the menu as well.
[Ryujinx_1.1.0+5b910e8_2022-07-29_18-22-57.log](https://github.com/Ryujinx/Ryujinx/files/9222286/Ryujinx_1.1.0%2B5b910e8_2022-07-29_18-22-57.log)

2022-07-29 18:06 UTC, Citrus333 commented
Here's a log from opening the menu crash in Xenoblade Chronicles 3
[Ryujinx_1.1.0+5b910e8_2022-07-29_10-52-05.log](https://github.com/Ryujinx/Ryujinx/files/9222315/Ryujinx_1.1.0%2B5b910e8_2022-07-29_10-52-05.log)
.

2022-07-29 18:24 UTC, riperiperi approved these changes
LGTM

2022-07-29 18:25 UTC, riperiperi commented
> Xenoblade 3 crashes sometimes on Nvidia Vulkan with `00:02:31.189 |E| GPU.MainThread Gpu : VK Sync Object 43772 failed to signal within 1000ms. Continuing... 00:02:32.175 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".`
> 
> In this log it was when loading a heavy cutscene with no shaders compiled, but others have reported crashing when opening the menu as well, although those might be different crashes. [Ryujinx_1.1.0+5b910e8_2022-07-29_18-22-57.log](https://github.com/Ryujinx/Ryujinx/files/9222286/Ryujinx_1.1.0%2B5b910e8_2022-07-29_18-22-57.log)

This looks like a TDR. Does this also happen on OpenGL?

It might be worth forcing the use of GLSL to see if the issue is related to SPIR-V, if it does not happen on OpenGL.

2022-07-29 18:55 UTC, MetrosexualGarbodor commented
I think the same crash happens on OpenGL, but since it doesn't leave an error, it's hard to say. At least it seems to happen in the same circumstances.

2022-07-29 18:57 UTC, gdkchan commented
> I think the same crash happens on OpenGL, but since it doesn't leave an error, it's hard to say. At least it seems to happen in the same circumstances.

You can look at the event viewer, sometimes the NVIDIA driver leaves some information there.

2022-07-29 19:01 UTC, MetrosexualGarbodor commented
Peri's right, I have an OpenGL crash at the same time as the one I recorded on video. Nothing for Vulkan, but it might as well be the same thing.
`A TDR has been detected.
The application must close.


Error code: 7
 (pid=8132 tid=7812 ryujinx.exe 64bit)

Visit http://nvidia.custhelp.com/app/answers/detail/a_id/3633 for more information.
`

2022-07-29 21:12 UTC, riperiperi commented
Can anyone having issues with RADV on Xenoblade games give them a shot now? I’ve pushed a change to the SPIR-V compiler that should fix the issue that was insta-crashing it.

2022-07-29 22:49 UTC, jduncanator reviewed
This is a first pass over the Vulkan changes. I still have about 50 files (largely the most technical changes in the Vulkan change set) left to review, and another 50 or so I've only partially reviewed at a top level. I aim to have those reviews finished sometime today.

I started marking up code style issues in the Ava project, but they were so prevalent that I gave up very quickly. If it matters to anyone, that project probably needs a pass over with dotnet-format.

2022-07-30 00:53 UTC, rabidcopy commented
> Can anyone having issues with RADV on Xenoblade games give them a shot now? I’ve pushed a change to the SPIR-V compiler that should fix the issue that was insta-crashing it.

Compiled your commit since the builds here got held up. RX 570 on latest optional drivers at least goes to the initial loading screen, then crashes before the title screen appears. So at the very least it boots. Will see if it goes further on Linux when those builds drop here.
[Ryujinx_1.0.0-dirty_2022-07-29_19-47-34.log](https://github.com/Ryujinx/Ryujinx/files/9224059/Ryujinx_1.0.0-dirty_2022-07-29_19-47-34.log)
<img width="674" alt="Untitled" src="https://user-images.githubusercontent.com/8052832/181863829-2ee564c1-ca15-45e5-8241-93081fa1d29c.png">

2022-07-30 01:19 UTC, riperiperi commented
RADV is the linux vulkan driver, and the game I tested was Xenoblade 2. I don't know what happens on windows, or if GCN gpus have yet another bug stopping it from booting.

2022-07-30 01:30 UTC, jduncanator requested changes
Here is my actual first pass review now, after Reviewable screwed up the last time around 🙄 I aim to review the rest of the PR today.

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs
> +                return 1 + GetBindingFromIndex(index, _context.Capabilities.MaximumUniformBuffersPerStage, "Uniform buffer");
Perhaps add a comment as to why the + 1 is significant.
```suggestion
                return GetBindingFromIndex(index, _context.Capabilities.MaximumUniformBuffersPerStage, "Uniform buffer") + 1;
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
> +        /// Indicates whenever alpha-to-coverage is enabled.
```suggestion
        /// Indicates whether alpha-to-coverage is enabled.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
> +        /// Indicates whenever alpha-to-coverage dithering is enabled.
```suggestion
        /// Indicates whether alpha-to-coverage dithering is enabled.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
>          /// Indicates whenever the viewport transform is disabled.
```suggestion
        /// Indicates whether the viewport transform is disabled.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
> +        /// Point size if not set from shader.
```suggestion
        /// Point size used if <see cref="ProgramPointSizeEnable" /> is false.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
> +        /// Indicates whenever alpha test is enabled.
```suggestion
        /// Indicates whether alpha test is enabled.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
> +        /// When alpha test is enabled, indicates the comparison that decides if the fragment is discarded.
```suggestion
        /// When alpha test is enabled, indicates the comparison that decides if the fragment should be discarded.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
> +        /// <param name="alphaTestEnable">Indicates whenever alpha test is enabled</param>
```suggestion
        /// <param name="alphaTestEnable">Indicates whether alpha test is enabled</param>
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/GpuChannelGraphicsState.cs
>          /// <param name="alphaToCoverageEnable">Indicates whenever alpha-to-coverage is enabled</param>
```suggestion
        /// <param name="alphaToCoverageEnable">Indicates whether alpha-to-coverage is enabled</param>
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.OpenGL/Pipeline.cs
> +            int* v = stackalloc int[count * 4];
This function can be rewritten "safely", by `stackalloc`ing this array as a `Span<int>` and then passing it into `GL.ScissorArray` using the `ref Int32 v` overload like so:
```cs
GL.ScissorArray(0, count, ref v[0]);
```
This avoids the need for allocating a bare pointer, and the use of unsafe

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Shader/IGpuAccessor.cs
> +        /// If alpha test is disabled, it can will be set to <see cref="AlphaTestOp.Always"/>.
This comment doesn't make sense.

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Shader/IGpuAccessor.cs
> +        /// Queries the type of a vertex shader input attribute at the specified <paramref name="location"/>.
```suggestion
        /// Queries the type of the vertex shader input attribute at the specified <paramref name="location"/>.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Shader/IGpuAccessor.cs
> +        /// Queries the current alpha test reference value used on the comparison.
```suggestion
        /// Queries the current alpha test reference value used by the comparison.
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Shader/IGpuAccessor.cs
> +        /// <param name="location">Location of the input</param>
```suggestion
        /// <param name="location">Location of the input attribute</param>
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/HelperShader.cs
> +        private static GAL.SamplerCreateInfo GetSamplerCreateInfo(MinFilter minFilter, MagFilter magFilter)
This could be moved to a static method on `SamplerCreateInfo`.

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/HelperShader.cs
> +                region[1] = temp;
```suggestion
                (region[0], region[1]) = (region[1], region[0]);
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/HelperShader.cs
> +                region[3] = temp;
```suggestion
                (region[2], region[3]) = (region[3], region[2]);
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/HelperShader.cs
> +            const int ClearColorBufferSize = 16;
I'd hoist this declaration to the top of the function

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/HelperShader.cs
> +                region[1] = temp;
```suggestion
                (region[0], region[1]) = (region[1], region[0]);
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/HelperShader.cs
> +                region[3] = temp;
```suggestion
                (region[2], region[3]) = (region[3], region[2]);
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/ImageWindow.cs
> +            unsafe
Probably cleaner to mark the entire function `unsafe`, given this unsafe block makes up (almost) the entire function.

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/ImageWindow.cs
> +            var subresourceRange = new ImageSubresourceRange(aspectFlags, 0, 1, 0, 1);
```suggestion
            var subresourceRange = new ImageSubresourceRange(ImageAspectFlags.ImageAspectColorBit, 0, 1, 0, 1);
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/CommandBufferPool.cs
> +            Semaphore[] signalSemaphores)
Consider changing the signature of this method to take `ReadOnlySpan<T>` instead of arrays. This would allow minimising allocations at the call sites by allowing them to use `stackalloc`, and wouldn't require any changes to this function.

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/ImageWindow.cs
> +                null);
If the [suggested changes](https://github.com/Ryujinx/Ryujinx/pull/2518/files#diff-ea189ee16b09f3e2af3c0eca89b08e30ef2c740b05f6d0fef2042d177f8811caR250) are made to [CommandBufferPool.cs](https://github.dev/gdkchan/Ryujinx/blob/788f2c172b22cfe2663b898a2aca11bd04b31737/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs#L250) then this can avoid allocations:
```suggestion
            _gd.CommandBufferPool.Return(
                cbs,
                null,
                stackalloc[] { PipelineStageFlags.PipelineStageColorAttachmentOutputBit },
                null);
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/Window.cs
> +                new[] { _renderFinishedSemaphore });
If the [suggested changes](https://github.com/Ryujinx/Ryujinx/pull/2518/files#diff-ea189ee16b09f3e2af3c0eca89b08e30ef2c740b05f6d0fef2042d177f8811caR250) are made to [CommandBufferPool.cs](https://github.dev/gdkchan/Ryujinx/blob/788f2c172b22cfe2663b898a2aca11bd04b31737/Ryujinx.Graphics.Vulkan/CommandBufferPool.cs#L250) then this can avoid allocations:
```suggestion
            _gd.CommandBufferPool.Return(
                cbs,
                stackalloc[] { _imageAvailableSemaphore },
                stackalloc[] { PipelineStageFlags.PipelineStageColorAttachmentOutputBit },
                stackalloc[] { _renderFinishedSemaphore });
```

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Headless.SDL2/Program.cs
> +        private static (WindowBase, IRenderer) CreateRenderer(Options options)
I would split this into two separate functions, `CreateWindow` and `CreateRenderer`.

2022-07-30 01:30 UTC, jduncanator commented on Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs
> +        protected override void InitializeRenderer() { }
`InitializeRenderer` could be redefined as `virtual`, rather than `abstract`, in the base class to avoid the need to declare an empty override.

2022-07-30 01:30 UTC, jduncanator commented on Spv.Generator/LiteralString.cs
> +            int paddingSize = 4 - (Encoding.ASCII.GetByteCount(_value) % 4);
Maybe add a comment here indicating why string literals need padding, and where the significance of the "4" comes from.

2022-07-30 01:46 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Constants.cs
> +        public const int TotalVertexAttribs = 16; // FIXME: Should be 32, but OpenGL only supports 16.
I see the issue here now, this file is global across both backends. This can be closed if you'd like, we would ideally have different capabilities per backend, but that can be a challenge for another day.

2022-07-30 02:05 UTC, choubun2088 commented
hi good job

2022-07-30 02:06 UTC, gdkchan commented
> hi good job

Thanks.

2022-07-30 02:22 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Shader/GpuAccessorBase.cs
> +                return 1 + GetBindingFromIndex(index, _context.Capabilities.MaximumUniformBuffersPerStage, "Uniform buffer");
The binding "0" is reserved to the used by the uniform buffer with the render scales and other emulator data that the shader needs to access.

2022-07-30 02:32 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
> -                }
Yes, it's incompatible because Vulkan requires more state to be stored in the cache, which does not exist in the old cache format. The code for the old shader cache has been removed.

2022-07-30 02:36 UTC, gdkchan commented on Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs
> +            ulong timestamp = (ulong)DateTime.UtcNow.Subtract(DateTime.UnixEpoch).TotalSeconds;
Where would I put it though? Seems weird to have a class with a single one line method.

2022-07-30 02:38 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/FormatTable.cs
> -            Add(Format.Etc2RgbSrgb,         new FormatInfo(3, false, false, All.CompressedSrgb8Etc2));
They were unused. Such a format does not really exist on the GPU, at the API level they are exposed, but its just the RGBA format with alpha forced to 1 on the texture swizzle parameters.

2022-07-30 02:44 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/FormatTable.cs
> -            Add(Format.Etc2RgbSrgb,         new FormatInfo(3, false, false, All.CompressedSrgb8Etc2));
I checked again and I think there might be a difference in how RGB and RGBA ETC2 formats are encoded, so it might be needed in the future. Right now, they are unused though.

2022-07-30 02:47 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs
> +                supportsBc67Compression: true, // Should check BPTC extension, but for some reason NVIDIA is not exposing the extension.
Even if thats the case, it would still be broken on older drivers which some people might be still using.

2022-07-30 02:49 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs
> +                maximumUniformBuffersPerStage: 13, // TODO: Avoid hardcoding those limits here and get from driver?
Right now they are only used on Vulkan, I have only added them to OpenGL because I had to put them there. But those values might be useful for other things in the future. Also this limit is considered to be the limit for all stages, while OpenGL has a per-stage limit, so I would either need to add a limit per stage on the Capabilities struct, or take the min of them all.

2022-07-30 02:51 UTC, gdkchan commented on Ryujinx.Graphics.Shader/IGpuAccessor.cs
> +        /// If alpha test is disabled, it can will be set to <see cref="AlphaTestOp.Always"/>.
Does it make sense if you remove the "can" on "it can will"?

2022-07-30 02:52 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs
> +            ulong timestamp = (ulong)DateTime.UtcNow.Subtract(DateTime.UnixEpoch).TotalSeconds;
I'd add it as an extension method to `DateTime`, in a `DateTimeExtensions.cs` file:
```cs
public static class DateTimeExtensions
{
    /// <summary>Returns the number of seconds that have elapsed since 1970-01-01T00:00:00Z.</summary>
    /// <returns>The number of seconds that have elapsed since 1970-01-01T00:00:00Z.</returns>
    public static ulong ToUnixTimestamp(this DateTime dt)
    {
        return (ulong)dt.Subtract(DateTime.UnixEpoch).TotalSeconds;
    }
}
```

Then you can just use `DateTime.UtcNow.ToUnixTimestamp()`.

2022-07-30 02:54 UTC, gdkchan commented on Ryujinx.Graphics.Shader/IGpuAccessor.cs
> +        /// If alpha test is disabled, it can will be set to <see cref="AlphaTestOp.Always"/>.
Actually, I think its better to change "it can will" to "it should".

2022-07-30 02:55 UTC, jduncanator commented on Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs
> +                supportsBc67Compression: true, // Should check BPTC extension, but for some reason NVIDIA is not exposing the extension.
I would just return false if the extension is not exposed.

2022-07-30 02:56 UTC, jduncanator commented on Ryujinx.Graphics.OpenGL/FormatTable.cs
> -            Add(Format.Etc2RgbSrgb,         new FormatInfo(3, false, false, All.CompressedSrgb8Etc2));
If they're unused, I'm happy for this to be marked resolved.

2022-07-30 02:56 UTC, jduncanator commented on Ryujinx.Graphics.Shader/IGpuAccessor.cs
> +        /// If alpha test is disabled, it can will be set to <see cref="AlphaTestOp.Always"/>.
Yep, "it should" makes sense here!

2022-07-30 02:58 UTC, jduncanator commented on Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs
> -                }
:+1:

2022-07-30 03:14 UTC, gdkchan commented on Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs
> +        protected override void InitializeRenderer() { }
It's better like this IMO. If it was made virtual, then the base class method would need to be the empty one, it doesn't change much, and all the other similar methods are abstract.

2022-07-30 03:18 UTC, gdkchan commented on Spv.Generator/LiteralString.cs
> +            int paddingSize = 4 - (Encoding.ASCII.GetByteCount(_value) % 4);
According to the spec:
> Literal String: A nul-terminated stream of characters consuming an integral number of [words](https://registry.khronos.org/SPIR-V/specs/1.2/SPIRV.html#Word). The character set is Unicode in the UTF-8 encoding scheme. The UTF-8 octets (8-bit bytes) are packed four per [word](https://registry.khronos.org/SPIR-V/specs/1.2/SPIRV.html#Word), following the little-endian convention (i.e., the first octet is in the lowest-order 8 bits of the word). The final word contains the string’s nul-termination character (0), and all contents past the end of the string in the final word are padded with 0.

2022-07-30 03:49 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanDevice.cs
> +                Api.DeviceWaitIdle(InternalHandle);
It doesn't look like any of those methods needs the lock to be honest. Why was that added @emmauss ?

2022-07-30 03:58 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanDisplay.cs
> +            _swapchain = CreateSwapchain(_instance, _device, _physicalDevice, _surface, out var extent, this, _vsyncEnabled);
Are you suggesting passing a `ref SwapchainKHR` parameter here?

2022-07-30 04:03 UTC, yuwenhua653 commented
> 

Still not working on AMD GPU Mesa 22.2.0, the game cannot reach the beginning, the game is XC3

2022-07-30 04:06 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPlatformInterface.cs
> +            catch (Exception)
It doesn't looks like `VulkanDisplay.CreateDisplay` can handle surface being null, so presumably that would already throw anyway in case of failure, so I will just let it propagate.

2022-07-30 04:07 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanDisplay.cs
> +            _swapchain = CreateSwapchain(_instance, _device, _physicalDevice, _surface, out var extent, this, _vsyncEnabled);
No, at the moment `CreateSwapchain` calls `DestroySwapchain` passing in `oldDisplay._swapchain`, where `oldDisplay` is `this`. My suggestion is to pass in the current `_swapchain` explicitly, as another parameter, and use that in the call to `DestroySwapchain`. The only use of  `oldDisplay` is to access the old swapchain.

2022-07-30 04:08 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPlatformInterface.cs
> +            catch (Exception)
> and change this to a finally clause to dispose of the surface.

I don't think that would be correct, the surface should not be disposed if not exception was thrown.

2022-07-30 04:10 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPlatformInterface.cs
> +            catch (Exception)
Ah yea, that's correct. I still don't like generically catching all Exception's though.

2022-07-30 04:10 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPlatformInterface.cs
> +            catch (Exception)
Will let @emmauss handle that as I'm not sure which exceptions are expected here (if any).

2022-07-30 04:15 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanSurfaceRenderingSession.cs
> +        public bool IsYFlipped { get; } = true;
I think it could generate compiler warnings since one code path can never be executed. Probably makes more sense to change all places that use this to just assume the value is true.

2022-07-30 04:16 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanSurfaceRenderingSession.cs
> +        public void Dispose()
Will do, but the problem exists in several other classes too.

2022-07-30 04:19 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanRenderTarget.cs
> +        }
Why was this `GrContext grContext` parameter added? Added theres a `,` at the end.

2022-07-30 04:20 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanRenderTarget.cs
> +        }
Oh I see, it also requires another change.

2022-07-30 04:26 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanSurfaceRenderingSession.cs
> +        public void Dispose()
Yea, a lot of these issues are prevalent throughout the Ava project, I marked the first few instances I saw up, but left the exercise of fixing them all up to the reader.

2022-07-30 04:27 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanRenderTarget.cs
> +        }
Yea, a few files down.

2022-07-30 05:24 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanRenderTarget.cs
> +        public GRContext GrContext { get; set; }
This change requires other changes that were not done. See the other related comment for explanation.

2022-07-30 05:27 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanSkiaGpu.cs
> +                return vulkanRenderTarget;
This change did not work, `TryCreateRenderTarget` is called multiple times (usually from the same thread, but I think it can be called from other threads too). It also is somehow is interrupted before `GrContext` is set on `Initialize` method. The first call on the call stack is `Avalonia.Win32.WindowImpl.WndProc` which makes me think this is called for any window event? Anyway, doing this change causes `GrContext` being passed before it is initialized, so it passes null. Left as-is for now.

2022-07-30 05:32 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanSkiaGpu.cs
> -                return vulkanRenderTarget;
Think this might be a mistake, it now always returns `null` 😅

2022-07-30 05:36 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/OpenGLRenderer.cs
> +                supportsBc67Compression: true, // Should check BPTC extension, but for some reason NVIDIA is not exposing the extension.
It would not work if the extension is not exposed but the driver supports it, which is what the comment calls out. I could check if the format is supported rather than the extension, but would be kinda weird to do it just for this.

2022-07-30 05:39 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanSkiaGpu.cs
> -                return vulkanRenderTarget;
Yea, my bad. I applied your suggestion but it didn't work, so I reverted the change and forgot this return. It's already fixed.

2022-07-30 06:41 UTC, emmauss commented on Ryujinx.Ava/AppHost.cs
> +                renderer = new VulkanRenderer(vulkan.Instance.InternalHandle,
The UI runs on the GPU, whether it's vulkan or opengl. If it fails to initialize vulkan when the app starts, it will fail to start the UI. Currently it crashes with no fallback to opengl. I have a followup branch with fixes for the vulkan backend. It will be handled there.

2022-07-30 06:45 UTC, gdkchan commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanSurfaceRenderingSession.cs
> +        public bool IsYFlipped { get; } = true;
I just removed it to avoid warnings about dead code.

2022-07-30 06:49 UTC, emmauss commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanDevice.cs
> +                Api.DeviceWaitIdle(InternalHandle);
We have absolutely no control of when Avalonia or Skia will use the queues or device. Avalonia runs rendering on 2 occasions, both on different threads. When the window requests paint, like on creation and resize. This is done on the main thread.  And when a control requests a redraw, which is done on a thread we control. SInce a repaint and a redraw request can occur an the same time, we need to lock the devices and queue.

2022-07-30 06:51 UTC, emmauss commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanDevice.cs
> +                Api.QueueWaitIdle(Queue.InternalHandle);
Same comment above. Even a WaitIdle will spam validation errors saying it's being used in multiple threads

2022-07-30 07:15 UTC, emmauss commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPlatformInterface.cs
> +            catch (Exception)
It will crash if vulkan isn't available, so that catches it. It will still crash later down the line as there is no fallback to Opengl. SO this catch is redundant.

2022-07-30 07:18 UTC, emmauss commented on Ryujinx.Ava/Ui/Backend/Vulkan/Skia/VulkanSkiaGpu.cs
> +                return vulkanRenderTarget;
It's called anytime when the window is created or Resized. Avalonia can handle either on the Main thread or the Render thread

2022-07-30 07:34 UTC, jduncanator commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +                    Process.Start(Environment.ProcessPath);
I think there is a property called `EnrironmentVariables` that can be set.

2022-07-30 07:45 UTC, jduncanator commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +                    Process.Start(Environment.ProcessPath);
The intent is to populate the already allocated dictionary.

```cs
var startInfo = new ProcessStartInfo();

startInfo.Environment.Add("ENV_VAR", "value");
```

My main concern with this one is maintaining the portable mode flag across restarts. What I want to avoid is someone launching in portable mode, changing the GPU backend, then having it restart in non-portable mode and overwrite their system wide install, or be missing all their keys/configs/games etc. A further thought is for Linux users who tend to use a lot of "prefix environment variables" for things like GAMEMODE. Without maintaining those, the restarted instance will be missing any tuning the user has done.

2022-07-30 14:47 UTC, jduncanator requested changes
Alright, here comes my pass over the remaining files. I'm about 80% through the actual Vulkan backend now, but I've skipped the Spir-v and BCn changes for the time being as they're huge changes. I aim to have the final 20% complete shortly!

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPhysicalDevice.cs
> +        public static List<KeyValuePair<PhysicalDevice, PhysicalDeviceProperties>> SuitableDevices { get; private set; }
You can make this an `IEnumerable<T>`
```suggestion
        public static IEnumerable<KeyValuePair<PhysicalDevice, PhysicalDeviceProperties>> SuitableDevices { get; private set; }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPhysicalDevice.cs
> +                out _)).ToList();
By making `SuitableDevices` an `IEnumerable<T>`, you can avoid needing to copy and allocate a new list.
```suggestion
            SuitableDevices = PhysicalDevices.Where(x => IsSuitableDevice(
                instance.Api,
                x.Key,
                x.Value,
                surface.ApiHandle,
                out _,
                out _));
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPhysicalDevice.cs
> +        internal static unsafe VulkanPhysicalDevice FindSuitablePhysicalDevice(VulkanInstance instance,
This doesn't need to be `unsafe`.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPhysicalDevice.cs
> +        }
This can be refactored to be "safe":
```suggestion
        private static uint FindSuitableQueueFamily(Vk api, PhysicalDevice physicalDevice, SurfaceKHR surface,
            out uint queueCount)
        {
            const QueueFlags RequiredFlags = QueueFlags.QueueGraphicsBit | QueueFlags.QueueComputeBit;

            var khrSurface = new KhrSurface(api.Context);

            Span<uint> propertiesCount = stackalloc uint[1];
            api.GetPhysicalDeviceQueueFamilyProperties(physicalDevice, propertiesCount, Span<QueueFamilyProperties>.Empty);

            Span<QueueFamilyProperties> properties = stackalloc QueueFamilyProperties[(int)propertiesCount[0]];
            api.GetPhysicalDeviceQueueFamilyProperties(physicalDevice, propertiesCount, properties);

            for (int index = 0; index < properties.Length; index++)
            {
                var queueFlags = properties[index].QueueFlags;

                khrSurface.GetPhysicalDeviceSurfaceSupport(physicalDevice, (uint)index, surface, out var surfaceSupported)
                    .ThrowOnError();

                if (queueFlags.HasFlag(RequiredFlags) && surfaceSupported)
                {
                    queueCount = properties[index].QueueCount;

                    return (uint)index;
                }
            }

            queueCount = 0;

            return uint.MaxValue;
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.GAL/ProgramPipelineState.cs
> +        // TODO: Polygon mode.
Should these TODO have fields reserved for them now, to avoid breaking changes to the struct layout in the future?

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Shader/CodeGen/Spirv/CodeGenContext.cs
> +            GeneratorPool<LiteralInteger> integerPool) : base(0x00010300, instPool, integerPool)
What does this number refer to? Perhaps make it a constant?

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Texture/Encoders/BC7Encoder.cs
> +        private static int[] _mostFrequentPartitions = new int[]
```suggestion
        private static readonly int[] _mostFrequentPartitions = new int[]
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Texture/Encoders/BC7Encoder.cs
> +                    selectedMode = variance > 160 ? 7 : 6;
Would make sense to define an enum for these modes.

Also, where does this "160" magic value come from? Perhaps define a constant for that?

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Texture/Encoders/BC7Encoder.cs
> +                    throw new Exception("invalid index " + index);
Perhaps a better exception and message here? `IndexOutOfRange`?

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Texture/Encoders/BC7Encoder.cs
> +                        throw new Exception("invalid alpha index " + index);
Perhaps a better exception and message here? `IndexOutOfRange`?

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Texture/Utils/BC67Utils.cs
> +﻿using System;
Once piece of feedback I have in common across most of the BCn related changes (and could be applicable to other areas), is it would be nice to split the "non-SIMD" implementation out from the SIMD implementation. Perhaps using a partial class, with the SSE/AVX implementations sitting in a second file so that it's clear?

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Texture/Utils/RgbaColor32.cs
> +            int DivideGuarded(int dividend, int divisor)
I'd call this function something else, it could be confused with the containing function given they have the same name. I'd also move it out with the other `ClampByte` helper at the end of the struct.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Texture/Utils/RgbaColor8.cs
> +                _ => R
This should throw `IndexOutOfRange` rather than just default to returning the red component.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/Auto.cs
> +                throw new Exception("Attempted to inc ref of dead object.");
```suggestion
                throw new Exception("Attempted to increment ref of dead object.");
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/BackgroundResources.cs
> +            foreach (KeyValuePair<Thread, BackgroundResource> tuple in _resources)
Given other accesses to `_resources` are protected by a lock, and locks in C# are re-entrant, it's probably safe to surround this code with a lock as well, just in-case `Cleanup` is called outside a lock in the future.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/BufferHolder.cs
> +            }
No need for a fixed here:
```suggestion
            for (ulong offset = 0; offset < (ulong)data.Length;)
            {
                ulong size = Math.Min(MaxUpdateBufferSize, (ulong)data.Length - offset);
                _gd.Api.CmdUpdateBuffer(cbs.CommandBuffer, dstBuffer, (ulong)dstOffset + offset, size, data.Slice(offset));
                offset += size;
            }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableBuffer.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroyBuffer(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableBufferView.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroyBufferView(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableFramebuffer.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroyFramebuffer(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableImage.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroyImage(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableImageView.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroyImageView(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableMemory.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.FreeMemory(_device, _memory, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposablePipeline.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroyPipeline(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableRenderPass.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroyRenderPass(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/DisposableSampler.cs
> +        }
This can be made "safe":
```suggestion
        public void Dispose()
        {
            _api.DestroySampler(_device, Value, Span<AllocationCallbacks>.Empty);
        }
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/EnumConversion.cs
> +        }
All of these could be turned into switch expressions if you defined a function that was something like:

```cs
private static T LogInvalidAndReturn<T>(T value, string name, T defaultValue = default)
{
    Logger.Debug?.Print(LogClass.Gpu, $"Invalid {name} enum value: {value}.");

    return defaultValue;
}
```

This would then let you do something like:

```cs
        public static CullModeFlags Convert(this Face face)
        {
            return face switch
            {
                Face.Back => CullModeFlags.CullModeBackBit,
                Face.Front => CullModeFlags.CullModeFrontBit,
                Face.FrontAndBack => CullModeFlags.CullModeFrontAndBack,
                _ => LogInvalidAndReturn(face, nameof(Face), CullModeFlags.CullModeBackBit)
            };
        }
```

If you wanted to take it a step further, you could use reflection to get the name of the enum from the generic type parameter, but that may just be overcomplicating it.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/FenceHelper.cs
> +            }
Not sure if I like the while loop or the do..while loop better, up to you :shrug: 
```suggestion
            do
            {
                // Keep waiting while the fence is not signaled.
                result = api.WaitForFences(device, (uint)fences.Length, fences, true, DefaultTimeout);
            }
            while (result == Result.Timeout);
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/FenceHolder.cs
> +                _api.DestroyFence(_device, _fence, null);
Function can be made "safe":
```suggestion
                _api.DestroyFence(_device, _fence, Span<AllocationCallbacks>.Empty);
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/FenceHolder.cs
> +            fences[0] = _fence;
```suggestion
            Span<Fence> fences = stackalloc Fence[1] {
                _fence
            };
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/FenceHolder.cs
> +            fences[0] = _fence;
```suggestion
            Span<Fence> fences = stackalloc Fence[1] {
                _fence
            };
```

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/FormatConverter.cs
> +        public unsafe static void ConvertD24S8ToD32FS8(Span<byte> output, ReadOnlySpan<byte> input)
Can drop the `unsafe` here.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/FormatConverter.cs
> +        public unsafe static void ConvertD32FS8ToD24S8(Span<byte> output, ReadOnlySpan<byte> input)
Can drop the `unsafe` here.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/MemoryAllocator.cs
> +        public unsafe void Dispose()
Can drop the `unsafe` here.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
> +                    throw new VulkanException("Failed to get debug report extension.");
This should probably just set `debugReportCallback` to `default`, and then return rather than throwing an exception.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
> +                    _ => throw new NotSupportedException()
This probably isn't the correct exception to throw for this. `ArgumentException` is probably better.

2022-07-30 14:47 UTC, jduncanator commented on Ryujinx.Headless.SDL2/Vulkan/VulkanWindow.cs
> +        private static unsafe string GetStringFromUtf8Byte(byte* start)
Not sure if this does anything different from `Marshal.PtrToStringUTF8`?

2022-07-30 14:47 UTC, jduncanator commented on Spv.Generator/GeneratorPool.cs
> +    public class GeneratorPool<T> where T : class, new()
What benefit does this have over a standard pool? From the looks of it, it exposes a `Clear` function which returns all the rented objects back to the pool in bulk. Is that the main difference?

2022-07-30 16:51 UTC, emmauss commented on Ryujinx.Ava/Ui/Backend/Vulkan/VulkanPhysicalDevice.cs
> +        }
Removing the keyword was enough to prevent errors.

2022-07-30 18:34 UTC, gdkchan commented on Ryujinx.Graphics.Texture/Encoders/BC7Encoder.cs
> +                    selectedMode = variance > 160 ? 7 : 6;
The enum would just be "Mode1", "Mode2", "Mode3", so its not much different from just passing the integer. I guess I could try to give names to each mode to make the enum more meaningful, but theres no official names for those modes. The value 160 came from testing and fine tuning, ultimately this is just an heuristic that decides whats the best mode based on how much colors change inside the block.

2022-07-30 18:41 UTC, gdkchan commented on Ryujinx.Graphics.Texture/Encoders/BC7Encoder.cs
> +                    throw new Exception("invalid index " + index);
I might replace it with `Debug.Assert`, that was meant to catch errors while testing rather than being final.

2022-07-30 18:45 UTC, gdkchan commented on Ryujinx.Graphics.Texture/Utils/BC67Utils.cs
> +﻿using System;
.NET 7 will have cross platform SIMD APIs, we can just start using those once it lands, so it will have only one fast path, rather than the current SSE path and scalar path. I don't think there's a great way to split them right now, even if I use partial classes, it will need to check for SSE availability somewhere and decide what to call based on that.

2022-07-30 18:47 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Auto.cs
> +                throw new Exception("Attempted to inc ref of dead object.");
That was also not supposed to be final, maybe I should switch to `Debug.Assert`.

2022-07-30 18:51 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/FenceHelper.cs
> +            }
I don't like do-while loops, so I avoid using them as much as possible. One can place the while after the end bracket like `} while` but then it feels inconsistent since we don't do `while {`. One can put it on the next line, but then it looks weird and does not match what other projects do. It's just a silly and personal annoyance, I guess.

2022-07-30 18:54 UTC, gdkchan commented on Spv.Generator/GeneratorPool.cs
> +    public class GeneratorPool<T> where T : class, new()
It was added by @riperiperi , AFAIK that's the main difference. It's supposed to preserve objects across compilations rather than allowing them to be re-used within the same compilation.

2022-07-30 19:39 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/BufferHolder.cs
> +            }
Does not work, the overloads on Silk.NET only takes `Span`, this method receives a `ReadOnlySpan` that can't be converted to regular `Span`.

2022-07-30 21:24 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/FenceHelper.cs
> +            }
Good enough for me, happy to leave it how it is.

2022-07-31 02:53 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/BufferHolder.cs
> +            }
I think that's actually a bug with Silk.NET, it should take a ReadOnlySpan.

2022-07-31 04:58 UTC, jduncanator commented on Ryujinx.Graphics.Vulkan/BufferHolder.cs
> +            }
Raised an issue on the Silk.NET repository: https://github.com/dotnet/Silk.NET/issues/981

2022-07-31 19:10 UTC, edisionnano approved these changes

2022-07-31 19:26 UTC, rgbarros120 commented
I thought it would come out fix for mario kart 8 deluxe, but good. Since it took a while for the next build to come out.

2022-07-31 19:32 UTC, rgbarros120 commented
Now to complete the Super Mario Odyssey bugged too. In the previous build it was not like this. Same problem with mario kart. AMD people are really chipped.

My Specs: RADEON RX 560 OC 4GB; 16GB DE RAM; RYZEN 5 1600
Driver: 22.7.1

![Sem título](https://user-images.githubusercontent.com/73244003/182042239-92f342da-f5ce-4bb7-8c71-eb7740a2ad2b.png)
[Ryujinx_1.1.0+2c08825_2022-07-31_16-24-08.log](https://github.com/Ryujinx/Ryujinx/files/9229586/Ryujinx_1.1.0%2B2c08825_2022-07-31_16-24-08.log)

2022-07-31 20:16 UTC, SomeoneIsWorking commented
Win10 RX 570 22.7.1
Xenoblade Chronicles: Definitive Edition recently started glitch
Can't pinpoint but this problem wasn't there a few days ago with same drivers
Corrupted character portraits
Video contains heavy spoilers: https://imgur.com/a/tu38UUs

2022-07-31 20:29 UTC, gdkchan commented
> Win10 RX 570 22.7.1 Xenoblade Chronicles: Definitive Edition recently started glitch Can't pinpoint but this problem wasn't there a few days ago with same drivers Corrupted character portraits Video contains heavy spoilers: https://imgur.com/a/tu38UUs

Are you using resolution scale? If so, does the issue happen at native resolution (1x)?

2022-07-31 20:40 UTC, rabidcopy commented
I'm not entirely sure how SomeoneIsWorking managed to get the game running with Vulkan on AMD. I have the same card and the latest optional drivers and when trying to use the Vulkan backend, it just crashes before the title screen appears. Have cleared caches. Tried with and without backend multhreading. With and without resolution mods.
[Ryujinx_1.1.0+2c08825_2022-07-31_15-34-11.log](https://github.com/Ryujinx/Ryujinx/files/9229676/Ryujinx_1.1.0%2B2c08825_2022-07-31_15-34-11.log)

2022-07-31 20:46 UTC, gdkchan commented
> I'm not entirely sure how SomeoneIsWorking managed to get the game running with Vulkan on AMD. I have the same card and the latest optional drivers and when trying to use the Vulkan backend, it just crashes before the title screen appears. Have cleared caches. Tried with and without backend multhreading. With and without resolution mods. [Ryujinx_1.1.0+2c08825_2022-07-31_15-34-11.log](https://github.com/Ryujinx/Ryujinx/files/9229676/Ryujinx_1.1.0%2B2c08825_2022-07-31_15-34-11.log)

That was Xenoblade Chronicles Definitive Edition, not Xenoblade Chronicles 3, they are different games.

2022-07-31 21:26 UTC, merged

2022-07-31 21:27 UTC, gdkchan commented
Thanks to everyone that helped testing Vulkan over the past year! Since it is now merged, please open separate issues for the remaining problems with Vulkan, rather than posting them here. Thanks.

2022-07-31 21:41 UTC, SomeoneIsWorking commented
> > Win10 RX 570 22.7.1 Xenoblade Chronicles: Definitive Edition recently started glitch Can't pinpoint but this problem wasn't there a few days ago with same drivers Corrupted character portraits Video contains heavy spoilers: https://imgur.com/a/tu38UUs
> 
> Are you using resolution scale? If so, does the issue happen at native resolution (1x)?

It only happens at 1x, looks fine on 2x
My bug report is probably wrong and this started happening because I lowered the resolution

2022-08-08 05:38 UTC, gamedevsam commented
I just want to say... bravo.

2022-09-09 21:36 UTC, supernarutoash11 commented
oi CDAKACHAN pode deixar eu entrar no discord por favor meu amigo

2022-09-09 21:37 UTC, markbex commented
[Ryujinx/Ryujinx] Vulkan backend