Add manager
Ryujinx/Ryujinx pull request #2651
Opened 2021-09-17 20:09 UTC by Caian

This PR replaces the "Open mod directory" option with a mod manager window that allows inspecting mods and selecting which ones will be activated when the game starts. It also allows quick access to the per-game and global mod directories, as well as the directory of each individual mod.

![ModManager](https://user-images.githubusercontent.com/2220062/133847278-52ebdccb-e320-4939-8f3c-df2a564b3e1e.PNG)

There's also additional log messages to indicate excluded mods when starting a game:

```
00:00:17.189 |I| ModLoader FilterMods: Mod <60 FPS Cheat> is not enabled
00:00:17.189 |I| ModLoader FilterMods: Mod <30 FPS Cheat> is not enabled
00:00:17.189 |I| ModLoader FilterMods: Mod <60 FPS Cheat> is not enabled
```

2021-09-17 21:16 UTC, Mou-Ikkai commented
Seems to work! Tried it with a Megamix mod that added new modules (outfits) to the game.
![image](https://user-images.githubusercontent.com/45863583/133854364-34e9d8e5-6998-4761-8718-2741968199b1.png)
![image](https://user-images.githubusercontent.com/45863583/133854371-5290c9f0-f8ea-4c69-8039-e8ee995e742f.png)
![image](https://user-images.githubusercontent.com/45863583/133854379-f8ecd91e-3adc-451e-9f45-db6bf7bfde2c.png)
![image](https://user-images.githubusercontent.com/45863583/133854384-4a1176b5-a292-496e-b28b-59b77c8676ec.png)
(You can see the Alien module is now gone and it defaulted back to regular Miku after mod was disabled.)

2021-09-18 00:55 UTC, Myoko commented
lgtm!

2021-09-19 10:57 UTC, AcK77 requested changes

2021-09-19 10:57 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                FilterMods(unfilteredModCache.Cheats         , filteredModCache.Cheats         , enabledMods);
```suggestion
                FilterMods(unfilteredModCache.RomfsContainers, filteredModCache.RomfsContainers, enabledMods);
                FilterMods(unfilteredModCache.ExefsContainers, filteredModCache.ExefsContainers, enabledMods);
                FilterMods(unfilteredModCache.RomfsDirs,       filteredModCache.RomfsDirs,       enabledMods);
                FilterMods(unfilteredModCache.ExefsDirs,       filteredModCache.ExefsDirs,       enabledMods);
                FilterMods(unfilteredModCache.Cheats,          filteredModCache.Cheats,          enabledMods);
```

2021-09-19 10:57 UTC, AcK77 commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
>                      catch(Exception e)
```suggestion
                    catch (Exception e)
```

2021-09-19 10:57 UTC, AcK77 commented on Ryujinx/Ui/Windows/ModsWindow.cs
> +        public static string GetModsJsonPath(string titleId)
```suggestion
        private static string GetModsJsonPath(string titleId)
```

2021-09-19 16:05 UTC, MrRobot-o commented
Great job with this mod manager PR.
The mod manager can also find mods which are located in DLC folders.
I tried "Relics of the past" mod and it seems to be working fine as both parts show up.

2021-09-23 16:59 UTC, GamerzHell9137 commented
Closes https://github.com/Ryujinx/Ryujinx/issues/1566

2021-09-25 19:36 UTC, GhostofReachCashGrab commented
Found no issues with this Pr with any Mods or cheats used seems like it's ready to go nice work!

2021-09-30 09:42 UTC, Caian commented
Add warning when a previously enabled mod is removed .

2021-11-08 23:56 UTC, Torphedo commented
Is there anything left to do here? This seems like a cool PR that got left in the dust a bit. Would love to see this merged!

2021-11-09 09:59 UTC, Caian commented
This PR is done, aside from fixing eventual bugs reported by the community and following the recomendations of other maintainers.

It is to be decided though if the PR should be merged before or after #2507, as it introduces more graphical modifications that must be ported.

2022-02-15 12:27 UTC, closed without merging

2022-02-17 01:29 UTC, Zero17N5 commented
Hi, sorry I am new here, How do I download this and how do I instal it?

2022-04-18 00:02 UTC, HeatPhoenix commented
Is there any reason why this was never merged? Looked very useful to me.

2022-04-18 00:06 UTC, MutantAura commented
The author does not intend to work on this further.