Custom widget framerate precision
Ryujinx/Ryujinx pull request #2674
Opened 2021-09-22 00:06 UTC by MutantAura

Follow-up to #2638 
It was mentioned that this feature may be nice to have and it was very basic in nature.

New setting in "General" which is an integer spinwheel for the number of decimal places the bottom render widget will display FPS to. This defaults to the value of 2 for new configuration files. Integer rounding value scales from 0-15 decimal places.
![image](https://user-images.githubusercontent.com/44103205/134261659-45199cd4-8ee6-476a-8d2c-9e54d16ee6c0.png)

See examples: 
2 decimal places
![image](https://user-images.githubusercontent.com/44103205/134261747-e826dec6-6a6c-481f-a51e-963056c1d3e3.png)
1 decimal place
![image](https://user-images.githubusercontent.com/44103205/134261774-f06580b1-5657-4389-a5bb-233df14bb669.png)
0 decimal places
![image](https://user-images.githubusercontent.com/44103205/134261810-82f6c25e-b5dc-4346-809d-a58a77824bf5.png)
15 decimal places (perhaps quite excessive...)
![image](https://user-images.githubusercontent.com/44103205/134261864-42212842-637f-42af-a671-0048dc2fce83.png)

There are some drawbacks. Using a rounding method to allow fully flexible control over this precision means if the final value is 0 then it will be truncated, cases where the user has specified 2DP and the value is 60.00 would be shortened to 60. Could possibly look into a `ToString()` method for each value but I've not thought of a way to do this efficiently yet as 15 if statements sounds messy... Might be more viable to do that if the values were restricted to 0-2 but I'm open to better ideas.
See 2DP defined but 0 has been truncated.
![image](https://user-images.githubusercontent.com/44103205/134262912-3cb71572-031d-49a2-802d-12a9152db0d0.png)

2021-09-22 04:09 UTC, EliEron commented
While I approve of this PR (as I prefer less precision personally) I agree with gdkchan that a dropdown would make far more sense. As you note yourself 15 digits of precision is quite ridiculous, honestly even 3 digits of precision seems overkill. So a short dropdown like the one gdkchan proposes seems far more intuitive to me.

2021-09-22 17:17 UTC, MutantAura commented
Updated implementation:

-Dropdown with common options instead of scroll wheel
-Fixed truncation of ending and leading 0's
-Fixes infinity frametime readings

2021-09-26 01:27 UTC, AcK77 requested changes

2021-09-26 10:23 UTC, MutantAura commented on Ryujinx.HLE/HLEConfiguration.cs
> +        public static int fpsPrecision;
Didn't need any HLE references anyway so fixed by deletion.
Unsure why I added them in the first place.

2021-09-26 10:23 UTC, MutantAura commented on Ryujinx.HLE/HLEConfiguration.cs
> +                                int                    fpsPrecision)
As above, fixed by deletion.

2021-09-26 10:23 UTC, MutantAura commented on Ryujinx.Headless.SDL2/Options.cs
> +        public int fpsPrecision { get; set; }
Naming has been updated globally.

2021-09-26 10:23 UTC, MutantAura commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +
Fixed

2021-09-26 10:24 UTC, MutantAura commented on Ryujinx/Configuration/ConfigurationState.cs
> +                AudioBackend                  = new ReactiveObject<AudioBackend>();
hehe. fixed

2021-09-26 10:24 UTC, MutantAura commented on Ryujinx/Ui/RendererWidgetBase.cs
> +        private string fpsString;
string naming updated

2021-09-26 10:24 UTC, MutantAura commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        float scale       = Graphics.Gpu.GraphicsConfig.ResScale;
alignments should now be variable and value aligned

2021-09-26 21:41 UTC, AcK77 commented on Ryujinx.Headless.SDL2/Options.cs
> +        public static int FpsPrecision { get; set; }
It shouldn't be `static`

2021-09-30 23:49 UTC, MutantAura commented on Ryujinx.Headless.SDL2/Options.cs
> +        public static int FpsPrecision { get; set; }
I _think_ this is fixed...

2021-10-03 15:11 UTC, AcK77 requested changes

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs
> +        public OpenGLWindow(InputManager inputManager, GraphicsDebugLevel glLogLevel, AspectRatio aspectRatio, bool enableMouse, int FpsPrecision) : base(inputManager, glLogLevel, aspectRatio, enable
```suggestion
        public OpenGLWindow(InputManager inputManager, GraphicsDebugLevel glLogLevel, AspectRatio aspectRatio, bool enableMouse, uint fpsPrecision) : base(inputManager, glLogLevel, aspectRatio, enableMouse, fpsPrecision)
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/Options.cs
> +        public int FpsPrecision { get; set; }
```suggestion
        public uint FpsPrecision { get; set; }
```

The value is between 0 and 4 so a uint should be enough

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/Program.cs
> +            _window = new OpenGLWindow(_inputManager, options.LoggingGraphicsDebugLevel, options.AspectRatio, (bool)options.EnableMouse, (int)options.FpsPrecision);
```suggestion
            _window = new OpenGLWindow(_inputManager, options.LoggingGraphicsDebugLevel, options.AspectRatio, (bool)options.EnableMouse, options.FpsPrecision);
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +        private int fpsPrecision;
```suggestion
        private uint _fpsPrecision;
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +        public WindowBase(InputManager inputManager, GraphicsDebugLevel glLogLevel, AspectRatio aspectRatio, bool enableMouse, int FpsPrecision)
```suggestion
        public WindowBase(InputManager inputManager, GraphicsDebugLevel glLogLevel, AspectRatio aspectRatio, bool enableMouse, uint fpsPrecision)
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +            fpsPrecision = FpsPrecision;
```suggestion
            _fpsPrecision = fpsPrecision;
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +                        int    precision  = fpsPrecision;
You can remove this line

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +                        switch (precision)
```suggestion
                        switch (_fpsPrecision)
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationFileFormat.cs
> +        public int FpsPrecision { get; set; }
```suggestion
        public uint FpsPrecision { get; set; }
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationState.cs
> +            public ReactiveObject<int> FpsPrecision { get; private set; }
```suggestion
            public ReactiveObject<uint> FpsPrecision { get; private set; }
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationState.cs
> +                FpsPrecision       = new ReactiveObject<int>();
```suggestion
                FpsPrecision       = new ReactiveObject<uint>();
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +
Remove the extra empty line

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        int    precision  = ConfigurationState.Instance.Ui.FpsPrecision;
You can remove this line

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                        switch (precision)
```suggestion
                        switch (ConfigurationState.Instance.Ui.FpsPrecision)
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            _fpsPrecisionCombo.SetActiveId(ConfigurationState.Instance.Ui.FpsPrecision.Value.ToString());
```suggestion
            _fpsPrecisionCombo.SetActiveId(((int)ConfigurationState.Instance.Ui.FpsPrecision.Value).ToString());
```

2021-10-03 15:11 UTC, AcK77 commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            ConfigurationState.Instance.Ui.FpsPrecision.Value                  = int.Parse(_fpsPrecisionCombo.ActiveId);
```suggestion
            ConfigurationState.Instance.Ui.FpsPrecision.Value                  = uint.Parse(_fpsPrecisionCombo.ActiveId);
```

2021-10-05 00:37 UTC, AcK77 approved these changes
Lgtm! Thanks!

2022-03-15 14:41 UTC, closed without merging