Implement "Delete Save File" Menu Item
Ryujinx/Ryujinx pull request #2679
Opened 2021-09-23 11:07 UTC by Rstar284

![Ryujinx](https://user-images.githubusercontent.com/56640404/134496771-167ad653-0234-4cae-9c66-7cb918716f16.jpg)
 
Add a delete save file menu item when right clicking on a game

2021-09-23 11:37 UTC, GamerzHell9137 commented
Haven't checked the PR but if it doesn't have a confirmation window to delete the save, it should be implemeneted.
"Are you sure you want to delete this save file? Files can't be recovered once deleted! [YES] [NO] "or something like that

2021-09-23 11:40 UTC, Rstar284 commented
![image](https://user-images.githubusercontent.com/56640404/134500602-10c6dc5c-6035-4e92-a8e6-729514a05ae4.png)

mhm! cant have such a dangerous action happen without conformation.

2021-09-23 20:19 UTC, Thealexbarney commented
The way this is done is incorrect. You're not deleting the saves, you're just cleaning out the save directory. And you usually shouldn't interact with the file system using the built-in .NET APIs. You should use the `DeleteSaveData`, `DeleteDeviceSaveData`, etc. APIs instead via `_horizonClient.Fs` in the `GameTableContextMenu` object.

2021-09-24 16:24 UTC, Rstar284 commented
Will fix, thanks for that :)

2021-09-25 19:29 UTC, Thealexbarney commented
You'd probably want deleting an account save and the device save to be separate actions, as well as deleting each account's save individually. You also aren't doing anything when the `Delete*` functions don't return `Success`. `.IsSuccess()` should be used when checking for a successful result.

2021-09-26 14:35 UTC, riperiperi requested changes
Just a few comments on style and wording.

2021-09-26 14:35 UTC, riperiperi commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +            if (!TryFindSaveData(_titleName, _titleId, _controlData, saveDataFilter, out ulong saveDataId)) {return;}
Should add newlines around the curly braces here to match our usual format for if blocks.

2021-09-26 14:35 UTC, riperiperi commented on Ryujinx/Ui/Widgets/GameTableContextMenu.Designer.cs
> +                TooltipText = "Delete all the Application's Save file (if they exists)."
`Delete all save files for the Application (if they exist)`

2021-09-27 17:05 UTC, riperiperi requested changes

2021-09-27 17:05 UTC, riperiperi commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                if (saveDataType.Equals(SaveDataType.Account))
Just use `==` when comparing an enum.

2021-09-28 11:49 UTC, Rstar284 commented on Ryujinx/Ui/Widgets/GameTableContextMenu.Designer.cs
> +            _purgeSaveUserMenuItem.Activated += PurgeDeviceSaveData_Clicked;
Haha, i was thinking why both menus opened together

2021-09-29 04:38 UTC, Thealexbarney commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +            if (!TryFindSaveData(_titleName, _titleId, _controlData, saveDataFilter, out ulong saveDataId))
`TryFindSaveData` appears to ask to create the save data if it doesn't already exist. That's not what you'd want in this situation. Also the filter you're passing in will check for any save with the given program ID, regardless of save type or user ID.

2021-09-30 11:37 UTC, Rstar284 commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +        private void PurgeSaveData(SaveDataFilter saveDataFilter, SaveDataType saveDataType)
Uh well, i just copied how the other delete function were called

2021-10-06 13:51 UTC, Rstar284 commented on Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +            _purgeSaveDeviceMenuItem.Sensitive   = !Utilities.IsZeros(controlData.ByteSpan) && controlData.Value.DeviceSaveDataSize           > 0;
I dont see a way to do so, if you know could help me

2022-10-02 08:27 UTC, marysaka commented
Closing as stale

2022-10-02 08:27 UTC, closed without merging