Map home button
Ryujinx/Ryujinx pull request #2769
Opened 2021-10-22 16:23 UTC by albfan

Implemented on top of #2131 (to be removed)

Fixes #2718 

Allow to listen to home butotn in joycon or keyboard.

final goal is to be able to go back to game selection (so it will ask to stop emulation with emulation dialog) but it can ask to setup new controllers.

Nowadays this are the only functions I use home for in real nintendo switch and I miss that on emulator (stop game, select another, setup new controllers)

2022-07-23 20:18 UTC, Thog requested changes
Finally got the time to review this 😓 

Some notes:
- This PR seems to be way more than just mapping buttons
- The dialogue window being controlled via keyboard/gamepad could be interesting but need to be decoupled from here
- I do believe the combo stuffs need to be less specific than this
- All debug prints need to be removed
- Need a rebase
- Need to be adapted for Avalonia

2022-07-23 20:18 UTC, Thog commented on Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                //System.Console.Write("--- joycon home button configured to: " + (Key)_configuration.RightJoycon.Home + "\n");
Remove this

2022-07-23 20:18 UTC, Thog commented on Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                //System.Console.Write("--- joycon capture button configured to: " + (Key)_configuration.LeftJoycon.Capture + "\n");
Remove this

2022-07-23 20:18 UTC, Thog commented on Ryujinx.Input.SDL2/SDL2GamepadDriver.cs
> +		System.Console.Write("----------------------\n");
Remove this

2022-07-23 20:18 UTC, Thog commented on Ryujinx.Input/GamepadButtonInputId.cs
> +        Capture,
You cannot do that, this break compat with old versions

Prefer making aliases like ``Back`` and ``Start``

2022-07-23 20:18 UTC, Thog commented on Ryujinx.Input/HLE/NpadManager.cs
> +        private bool checkButton(ControllerKeys buttons, ControllerKeys check)
```suggestion
        private static bool CheckButton(ControllerKeys buttons, ControllerKeys check)
```

2022-07-23 20:18 UTC, Thog commented on Ryujinx.Input/IKeyboard.cs
> +                //    System.Console.Write("key " + key +" pressed\n");
Remove this

2022-07-23 20:18 UTC, Thog commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +            return snapshot;
Revert those changes

2022-07-23 20:18 UTC, Thog commented on Ryujinx/Configuration/ConfigurationState.cs
> +            //Common.Logging.Logger.Info?.Print(LogClass.Configuration, $"{valueName} set to: {eventArgs.NewValue}");
Revert this change

2022-07-23 20:18 UTC, Thog commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +                    System.Console.Write("mapped, home key pressed\n");
Remove this

2022-07-23 20:18 UTC, Thog commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +                //System.Console.Write("--- joycon home button configured to: " + (Key)_configuration.RightJoycon.Home + "\n");
Remove this

2022-07-31 15:22 UTC, albfan commented on Ryujinx.Input/GamepadButtonInputId.cs
> +        Capture,
I suppose Home turns into Start, but Capture into Back? What key it matches with?

2022-07-31 15:28 UTC, albfan commented
Let me remove all but mapping home button.

Will open other PR for other features

2022-12-06 03:46 UTC, TSRBerry requested changes
Could you also add this for Avalonia?

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +            return snapshot;
Revert this change.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Ui/MainWindow.cs
> +
```suggestion

            RendererWidget.ComboPressed += OnComboPressed;

```
Properly align and remove the commented code.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Ui/MainWindow.cs
> +            if (Combo == ComboType.SpecialOne)
Add an empty new line before this and combine the if-else statements into a switch-statement.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Ui/MainWindow.cs
> +        private void TakeScreenshot_pressed(object sender, EventArgs args)
```suggestion
        private void TakeScreenshot_Pressed(object sender, EventArgs args)
```

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Ui/RendererWidgetBase.cs
>              TouchScreenManager = _inputManager.CreateTouchScreenManager();
```suggestion
            _inputManager = inputManager;
            
            _inputManager.SetMouseDriver(mouseDriver);

            NpadManager = _inputManager.CreateNpadManager();
            TouchScreenManager = _inputManager.CreateTouchScreenManager();
            
            NpadManager.ComboPressed += OnComboPressed;
           
```
Ideally `_inputManager` would also be above `mouseDriver`.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Ui/RendererWidgetBase.cs
> +            if (Combo == ComboType.Home)
```suggestion

            if (Combo == ComboType.Home)
```
Empty line before.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Ui/RendererWidgetBase.cs
> +                Logger.Info?.Print(LogClass.Application, "Home button pressed");
```suggestion
```
Remove this comment.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx.Common/Combo/ComboPressedEventArgs.cs
> +    }
Could you move this enum into its own file?

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx.Input/HLE/NpadManager.cs
> +        private static bool checkButton(ControllerKeys buttons, ControllerKeys check)
```suggestion
        private static bool CheckButton(ControllerKeys buttons, ControllerKeys check)
```

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx.Input/HLE/NpadManager.cs
> +                        }*/
```suggestion
```
Remove this commented code.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                            Capture      = Key.PrintScreen
This will trigger the screenshot tool for a lot of people. I don't think that's a good default.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                                Capture      = Key.PrintScreen
Same here.

2022-12-06 03:46 UTC, TSRBerry commented on Ryujinx/Ui/MainWindow.glade
> +                        <signal name="activate" handler="TakeScreenshot_pressed" swapped="no"/>
```suggestion
                        <signal name="activate" handler="TakeScreenshot_Pressed" swapped="no"/>
```

2023-05-02 14:20 UTC, AcK77 commented
Closed as stale.

2023-05-02 14:20 UTC, closed without merging