Implement analog stick range modifier
Ryujinx/Ryujinx pull request #2783
Opened 2021-10-25 04:44 UTC by MutantAura

Adds range modification to the analog sticks of a given controller. Partially addresses #2059.

Unlike an older PR (#2095) this PR will not support the addition of a keyboard modifier button directly (potentially a follow-up). This is a simple float multiplication modifier of the stick vector applied before circular clamping in order to maintain a natural min and max of the analog values.

Values above 1.00 = Easier to reach max input at lower analog distance.
Values below 1.00 = Harder/Impossible to reach max input (this will reduce maximum input).
This is in-line with Cemu's convention and so should be familiar to users.

Default values: 
![image](https://user-images.githubusercontent.com/44103205/138635219-05ce5bf9-e65d-4898-b71d-17315b3b6c35.png)

1.00 modification:
![image](https://user-images.githubusercontent.com/44103205/138635685-77c088bc-47c5-484e-be48-fcba555b23e1.png)

1.50 modification:
![image](https://user-images.githubusercontent.com/44103205/138635731-f92d4a2c-f846-4458-81be-1586b66d470d.png)

0.50 modification: 
![image](https://user-images.githubusercontent.com/44103205/138635791-af8d7ce7-f22f-426f-86ae-8054f4ea35ec.png)

2021-12-28 16:36 UTC, AcK77 requested changes
Ryujinx/_schema.json doesn’t exist anymore, it’s needs a rebase too.

2021-12-28 16:36 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +            Vector2 point = new Vector2(position.Dx, position.Dy)*range;
```suggestion
            Vector2 point = new Vector2(position.Dx, position.Dy) * range;
```

2021-12-28 16:36 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 33;
Version needs to be updated

2021-12-28 16:36 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationState.cs
> +            if (configurationFileFormat.Version < 33)
Version needs to be updated

2021-12-28 16:36 UTC, AcK77 commented on Ryujinx/Configuration/ConfigurationState.cs
> +                Common.Logging.Logger.Warning?.Print(LogClass.Application, $"Outdated configuration version {configurationFileFormat.Version}, migrating to version 33.");
Version needs to be updated

2021-12-28 23:27 UTC, MutantAura commented on Ryujinx.Input/HLE/NpadController.cs
> +            Vector2 point = new Vector2(position.Dx, position.Dy)*range;
updated

2021-12-28 23:27 UTC, MutantAura commented on Ryujinx/Configuration/ConfigurationFileFormat.cs
> +        public const int CurrentVersion = 33;
all config versions updated to 35

2021-12-28 23:55 UTC, AcK77 approved these changes
Lgtm! Thanks!

2021-12-29 14:02 UTC, Thog requested changes

2021-12-29 14:02 UTC, Thog commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        RangeRight       = 1.0f,
This needs to be also done on profile json load as the value will end up being 0.0 if the field isn't present

2021-12-29 18:42 UTC, MutantAura commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        RangeRight       = 1.0f,
Workaround added?

2021-12-29 23:11 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    //If both stick ranges are 0 (usually indicative of an outdated profile load) then both sticks will be set to 1.0
```suggestion
                    // If both stick ranges are 0 (usually indicative of an outdated profile load) then both sticks will be set to 1.0.
```

2021-12-29 23:28 UTC, MutantAura commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                    //If both stick ranges are 0 (usually indicative of an outdated profile load) then both sticks will be set to 1.0
updated

2021-12-31 02:05 UTC, gdkchan approved these changes
Looks fine.

2022-01-03 08:07 UTC, Thog approved these changes
lgtm

2022-01-03 11:49 UTC, merged