Support OSD For Performance Stats
Ryujinx/Ryujinx pull request #2897
Opened 2021-12-03 17:25 UTC by emmauss

This pr aims to add a osd for the performance statistics that's shown on the status bar on the render.

- [ ] Support DPI scaling
- [ ] Support Custom Fonts and Styles

![image](https://user-images.githubusercontent.com/5307160/144645947-f4485246-6b54-4a8a-a14f-efe669525988.png)

2021-12-03 21:58 UTC, bylaws commented
A frametime graph would be really cool, I think imgui should be capable of it fairly simply

2021-12-05 18:49 UTC, emmauss commented
Fixed issue with showing OSD over 3d games

2021-12-09 22:51 UTC, Pixxel123 commented
In full screen, when I select the game the parts where the background is visible is all black. It transparent on screenshot or Alt+Tab out. Using an Intel/NVIDIA setup with 100% DPI scaling. This happens with or without OSD enabled.

![image](https://user-images.githubusercontent.com/36304206/145487664-44d91c62-7722-49ba-ad77-f435fabafccb.png)

Windowed OSD works fine:

![image](https://user-images.githubusercontent.com/36304206/145487721-db0184f5-7934-4140-9d6a-fa5ae4344903.png)

There is also A LOT of stuttering in gameplay that is not present in master:

https://user-images.githubusercontent.com/36304206/145487815-5d44bb17-4e82-43af-a49f-7d571ad7d407.mp4

Again, this happens with or without OSD being enabled.

2021-12-12 16:22 UTC, Pixxel123 commented
Stuttering appears to fixed now on Astral Chain!

If I could make a suggestion: `Docked` shows as just Docked on native, but Docked (2x) when upscaled. It may be a good idea to specify Docked/Handheld (Native).

2021-12-14 20:57 UTC, Thog requested changes

2021-12-14 20:57 UTC, Thog commented on Ryujinx/Ui/Resources/copyshader.frag
> +void main()
would be nice to have correct indentation here

2021-12-14 20:57 UTC, Thog commented on Ryujinx/Ui/Resources/copyshader.vert
> +                    layout(location = 0) in vec3 aPosition;
would be nice to have correct indentation here

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Common/Osd/IOsdRenderer.cs
> +using ImGuiNET;
Not a fan to bring the dep to the common project

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Common/Osd/OsdContext.cs
> +﻿using ImGuiNET;
Not a fan to bring the dep to the common project

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Common/Ryujinx.Common.csproj
> +    <PackageReference Include="ImGui.NET" Version="1.78.0" />
same as the comment before.

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Graphics.OpenGL/GlOsdRenderer.cs
> +        public GlOsdRenderer()
Can be removed

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Graphics.OpenGL/Helper/GLHelper.cs
> +        public static (int framebuffer, int texture, int renderbuffer) GenerateRenderTarget(int width, int height)
this look confusing as hell, might be worth making a struct to hold those value instead of unnamed tuple?

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Graphics.OpenGL/Shaders/hudshader.frag
> +void main()
Indent? also should be spaced a bit imo

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Graphics.OpenGL/Shaders/hudshader.vert
> +#version 330 core
should be spaced a bit imo

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Headless.SDL2/Program.cs
> -            if (option.ListInputIds)
Not entirely sure what this whole diff is all about...? I'm okay with Options being a property but all the remapped seems unnecessary considering it's supposed to be tied to the arg

2021-12-14 20:57 UTC, Thog commented on Ryujinx/Ryujinx.csproj
> +    <None Remove="Ui\Resources\hudshader.frag" />
in the Graphics.OpenGL project and not here?

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +            if (this is OpenGLWindow)
Shouldn't this be in InitializeRenderer of OpenGLWindow?

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +                        _performanceStatus = new StatusUpdatedEventArgs(
unnecessary diff imo (or at least not for this PR)

2021-12-14 20:57 UTC, Thog commented on Ryujinx.Graphics.OpenGL/Window.cs
> +            GL.Enable(EnableCap.FramebufferSrgb);
This was before ``swapBuffersCallback``, is that intended?

2021-12-15 14:35 UTC, emmauss commented on Ryujinx/Ryujinx.csproj
> +    <None Remove="Ui\Resources\hudshader.frag" />
forgot to remove those as they are currently not needed.

2021-12-15 14:43 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Window.cs
> +            GL.Enable(EnableCap.FramebufferSrgb);
Yes, if SRGB is enabled, the blits that will happen in the swapbuffer callback will have washed out colors.

2021-12-15 15:04 UTC, emmauss commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +                        _performanceStatus = new StatusUpdatedEventArgs(
I need to store the status so imgui can draw it on the next frame

2021-12-15 15:05 UTC, emmauss commented
address some of the comments

2021-12-18 08:19 UTC, emmauss commented
rebased

2021-12-22 11:26 UTC, Shahil-Ayato commented
Closes #1158

2021-12-24 08:31 UTC, emmauss commented
Rebased

2021-12-24 09:24 UTC, Thog commented on Ryujinx.Common/Osd/IOsdRenderer.cs
> +using ImGuiNET;
I think I will handle that on a follow up as more stuffs could be separated I think.

2021-12-24 09:24 UTC, Thog commented on Ryujinx.Common/Osd/OsdContext.cs
> +﻿using ImGuiNET;
I think I will handle that on a follow up as more stuffs could be separated I think.

2021-12-24 09:24 UTC, Thog commented on Ryujinx.Common/Ryujinx.Common.csproj
> +    <PackageReference Include="ImGui.NET" Version="1.78.0" />
I think I will handle that on a follow up as more stuffs could be separated I think.

2021-12-24 09:25 UTC, Thog approved these changes
lgtm mostly

2021-12-26 20:10 UTC, gdkchan reviewed
How will this be implemented on Vulkan? Does ImGui even support Vulkan?

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj
> +    <EmbeddedResource Include="Shaders\hudshader.frag" />
Why not just use constant strings? Simpler and better than using embedded resources just for this IMO.

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Shaders/hudshader.vert
> +out     vec2 Frag_UV;
Whats up with this weird alignment here?

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Shaders/hudshader.vert
> +    gl_Position = ProjMtx * vec4(Position.xy,0,1);
```suggestion
    gl_Position = ProjMtx * vec4(Position.xy, 0, 1);
```

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Shaders/hudshader.vert
> +uniform mat4 ProjMtx;
The name is likely wrong I think, unless you are doing 3D rendering here, a projection matrix wouldn't make sense.

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
>              _width  = width;
I'd remove the alignment here. If not then you should align `_sizeChanged` too.

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
Stray empty line.

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +            if(_drawRenderTarget.Framebuffer != 0)
```suggestion
            if (_drawRenderTarget.Framebuffer != 0)
```

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs
> +            _hudWindowHandle = SDL_CreateWindow("Ryujinx osd context window", 0, 0, DefaultWidth, DefaultHeight, SDL_WindowFlags.SDL_WINDOW_OPENGL | SDL_WindowFlags.SDL_WINDOW_HIDDEN);
```suggestion
            _hudWindowHandle = SDL_CreateWindow("Ryujinx OSD Context Window", 0, 0, DefaultWidth, DefaultHeight, SDL_WindowFlags.SDL_WINDOW_OPENGL | SDL_WindowFlags.SDL_WINDOW_HIDDEN);
```

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Headless.SDL2/Program.cs
> +        public static Options Options { get; set; }
Why?

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx.Headless.SDL2/WindowBase.cs
> +            bool enableMouse)
Why was this moved to a new line?

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx/Configuration/ConfigurationState.cs
> +            if (configurationFileFormat.Version < 34)
Will need to change, I already used that version.

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx/Ryujinx.csproj
> +    <None Remove="Ui\Resources\blit.comp" />
I think some of those shaders are unused?

2021-12-26 20:10 UTC, gdkchan commented on Ryujinx/Ui/Windows/SettingsWindow.glade
> +<!-- Generated with glade 3.21.0 -->
Why was this file changed? Including changing all `-` to `_`.

2021-12-27 13:33 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Helper/BlitStruct.cs
> +    public struct BlitStruct
it's used outside the graphics project

2021-12-27 13:34 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Helper/GLHelper.cs
> +    public static class GLHelper
same as blitstruct

2021-12-27 13:41 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Helper/RenderTarget.cs
> +    public struct RenderTarget : IDisposable
it's used outside the project

2021-12-27 13:52 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Shaders/hudshader.vert
> +uniform mat4 ProjMtx;
I don't know much about projections to modify this part of the shader, seeing as the data is provided by imgui.

2022-01-05 07:37 UTC, emmauss commented
rebased

2023-02-09 07:28 UTC, closed without merging

2023-02-09 08:42 UTC, emmauss commented
Currently closed because branch is stale and a replacement is already in progress.