Add Cheat Manager
Ryujinx/Ryujinx pull request #2964
Opened 2022-01-01 11:24 UTC by emmauss

Adds a cheat manager which makes it possible to disable and enable installed cheat at runtime. This can be accessed by the context menu on the game list, or Actions -> Manage Cheats during gameplay. By default, all cheats are disabled.
Do note that this does not allow you to edit or add cheats. . Also, because the tampermachine only load cheats at launch, new cheats added to the cheat files and enabled will not be applied.

![Screenshot (88)](https://user-images.githubusercontent.com/5307160/147849362-af9e4178-918d-4d7d-b02d-d62bd484821e.png)
![Screenshot (90)](https://user-images.githubusercontent.com/5307160/147849366-41158bb6-3d02-47a7-9719-1332fe73dea5.png)

Related to #2651 .

2022-01-01 11:45 UTC, Thog approved these changes
code lgtm

2022-01-01 13:12 UTC, AcK77 requested changes

2022-01-01 13:12 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +                tamperMachine.EnableCheats(enabledCheats);
```suggestion
                tamperMachine.EnableCheats(File.ReadAllLines(enabledCheatsPath));
```

2022-01-01 13:12 UTC, AcK77 commented on Ryujinx.HLE/HOS/ModLoader.cs
> +            string enabledCheatsPath = Path.Combine(contentDirectory.FullName, CheatDir, "enabled.txt");
I’d store that in a JSON but I think a txt is enough? Or maybe the same file is used on real hardware?

2022-01-01 13:12 UTC, AcK77 commented on Ryujinx.HLE/HOS/TamperMachine.cs
> +            foreach(var program in _programDictionary.Values)
```suggestion
            foreach (var program in _programDictionary.Values)
```

2022-01-01 13:12 UTC, AcK77 commented on Ryujinx.HLE/HOS/TamperMachine.cs
> +                if(_programDictionary.TryGetValue(cheat, out var program))
```suggestion
                if (_programDictionary.TryGetValue(cheat, out var program))
```

2022-01-01 14:31 UTC, Niwu34 commented
I'm getting this Error Every Time I try to manage Cheats in the game List/Ingame
This Happens when ther is a cheat in the mod directory and when there is none
Cheats in general don't sem to work with this PR (They work on the Master Build)
`00:10:33.771 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Niwu\AppData\Roaming\Ryujinx\mods\contents\01002b00111a2000\cheats'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String , Boolean )
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String , String , EnumerationOptions )
   at System.IO.Directory.InternalEnumeratePaths(String , String , SearchTarget , EnumerationOptions )
   at Ryujinx.Ui.Windows.CheatWindow..ctor(Builder builder, VirtualFileSystem virtualFileSystem, String titleId, String titleName) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\Windows\CheatWindow.cs:line 75
   at Ryujinx.Ui.Widgets.GameTableContextMenu.ManageCheats_Clicked(Object sender, EventArgs args) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\Widgets\GameTableContextMenu.cs:line 474
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object , Span`1& , Signature , Boolean , Boolean )
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
`
The exception says that it can not find any cheats in the directoy even tho there is one (see below)
![Cheats](https://user-images.githubusercontent.com/67392333/147852857-8717fb54-17b4-43fe-b79c-56eeace7eeec.png)

2022-01-01 15:09 UTC, emmauss commented on Ryujinx.HLE/HOS/ModLoader.cs
> +            string enabledCheatsPath = Path.Combine(contentDirectory.FullName, CheatDir, "enabled.txt");
Atmosphere loads every cheat on launch by default. This can disabled, so no cheat is loaded. Atmosphere doesn't have a feature on its own to enable some cheats using a config. It's up to a cheat manager to tell the cfw what cheats to enable if you want to toggle them during runtime.
Since I'm just saving an array, using json would be too much.

2022-01-01 17:02 UTC, Niwu34 commented
The Folder structure of cheats where changed so that there is no Subfolder with the Name of the Cheats required anymore...
(Taking this into account fixes my problem)
The Error in the log above still occurs when there are no Cheats available. (Maybe add a pop up/option of the window without any mods)

Text parts of Mods appear twice in the UI (only the '60fps Mod' enable the Cheat tho)
![unknown](https://user-images.githubusercontent.com/67392333/147855698-ed33d544-29d6-44f9-9940-4dc6d8821217.png)

Enabling the Mods ingame seems to work, disabeling it afterwards (Maybe also add a warning in any kind of form outside of the terminal)
![image](https://user-images.githubusercontent.com/67392333/147855828-ce5487c0-df2a-4e67-92b1-b25c0d604c9b.png)

2022-01-01 17:20 UTC, emmauss commented
> The Folder structure of cheats where changed so that there is no Subfolder with the Name of the Cheats required anymore... (Taking this into account fixes my problem) The Error in the log above still occurs when there are no Cheats available. (Maybe add a pop up/option of the window without any mods)
> 
> Text parts of Mods appear twice in the UI (only the '60fps Mod' enable the Cheat tho) ![unknown](https://user-images.githubusercontent.com/67392333/147855698-ed33d544-29d6-44f9-9940-4dc6d8821217.png)
> 
> Enabling the Mods ingame seems to work, disabling it afterwards does not (Maybe also add a warning in any kind of form outside of the terminal) ![image](https://user-images.githubusercontent.com/67392333/147855828-ce5487c0-df2a-4e67-92b1-b25c0d604c9b.png)

Pushed a fix for your previous crash. That folder format should be supported now

2022-01-01 17:48 UTC, Niwu34 commented
Everything works Now Thank you for the quick fixes
![image](https://user-images.githubusercontent.com/67392333/147856877-7dbb0583-81c6-4aba-a3a0-9b545b7ba2df.png)
![image](https://user-images.githubusercontent.com/67392333/147856859-da59a60d-d24a-4874-9df6-0504f40538d9.png)
![image](https://user-images.githubusercontent.com/67392333/147856869-40c65410-42ef-4945-b1dd-e6ce7b8fe10d.png)

2022-01-02 20:01 UTC, AcK77 approved these changes
Just some nits, instead of that it’s lgtm!

2022-01-02 20:01 UTC, AcK77 commented on Ryujinx/Ui/Windows/CheatWindow.cs
> +                if(cheat.Path.FullName != currentCheatFile)
```suggestion
                if (cheat.Path.FullName != currentCheatFile)
```

2022-01-02 20:01 UTC, AcK77 commented on Ryujinx/Ui/Windows/CheatWindow.cs
> +            if(cheatAdded == 0)
```suggestion
            if (cheatAdded == 0)
```

2022-01-02 20:01 UTC, AcK77 commented on Ryujinx/Ui/Windows/CheatWindow.cs
> +            if(_noCheatsFound)
```suggestion
            if (_noCheatsFound)
```

2022-01-03 08:39 UTC, merged