Readme overhaul
Ryujinx/Ryujinx pull request #2988
Opened 2022-01-10 14:58 UTC by Shahil-Ayato

Our current Readme.md file at the moment looks ok but a bit outdated and has some redundancy in it. This overhauls the readme file to look much better and cleaner.

*Changes*
- a bigger and higher resolution logo now in the center instead of on the side
- pronunciation.
- more clarity on the project opening paragraph.
- made the building instructions more clear.
- grammar fixes.
- removed the help heading and merged it with contact.
- added a donation heading with a link to our Patreon if anyone wishes to support the project financially with notes on how it would be spent.
- added links to the licenses.
- added LibHac in the credits.

2022-01-10 21:35 UTC, Thog approved these changes

2022-01-10 21:41 UTC, AcK77 approved these changes

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +* Hackable Nintendo Switch consoles to reverse-engineer the hardware and its components
`and its components` is redundant.

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +* Hardware to test and fix any bugs certain hardware may have
Hardware was already listed.

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +* Software licenses to help developers use whatever they are comfortable with
`allow` rather than `help`.

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +* Hardware to test and fix any bugs certain hardware may have
I guess you're talking about PC parts rather than Switch hardware here? If so you should clarify.

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +All the funds acquired through our Patreon is considered a donation to support our work, and we will not do patron only releases. We may post exclusive progress reports, or early access to tools that
`are` rather than `is`?

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +All the funds acquired through our Patreon is considered a donation to support our work, and we will not do patron only releases. We may post exclusive progress reports, or early access to tools that
> or early access to tools that can be used with the emulator

Remove this as we are not doing that right now.

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +All the funds acquired through our Patreon is considered a donation to support our work, and we will not do patron only releases. We may post exclusive progress reports, or early access to tools that
I'd also remove
 > , and we will not do patron only releases

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +- [LibHac](https://github.com/Thealexbarney/LibHac) is used for our file-system
```suggestion
- [LibHac](https://github.com/Thealexbarney/LibHac) is used for our file-system implementation.
```

2022-01-11 13:29 UTC, gdkchan commented on README.md
> +  <sub><sup><b>(REE-YOU-JI-NX)</b></sup></sub>
I don't think including the spelling here is necessary. Does anyone even spell it like that?

2022-01-11 14:02 UTC, Shahil-Ayato commented
Ready for review.

2022-01-11 14:27 UTC, LukeWarnut requested changes

2022-01-11 14:27 UTC, LukeWarnut commented on README.md
> +If you want to see what's changed in an update you can visit our [Changelog](https://github.com/Ryujinx/Ryujinx/wiki/Changelog).
```suggestion
If you want to see what's changed in an update, you can visit our [Changelog](https://github.com/Ryujinx/Ryujinx/wiki/Changelog).
```

2022-01-11 14:27 UTC, LukeWarnut commented on README.md
> +For our Local Wireless and LAN builds See our [Multiplayer: Local Play/Local Wireless Guide
```suggestion
For our Local Wireless and LAN builds, see our [Multiplayer: Local Play/Local Wireless Guide
```

2022-01-11 14:27 UTC, LukeWarnut commented on README.md
> +To build Ryujinx open the Command prompt in the project directory. You can quickly access it by holding shift in the file explorer(while inside the Ryujinx directory) then right clicking and selectin
```suggestion
To build Ryujinx, open a command prompt inside the project directory. You can quickly access it on Windows by holding shift in File Explorer, then right clicking and selecting `Open command window here`. Then type the following command:
```

2022-01-12 02:52 UTC, Shahil-Ayato commented
Feedback all addressed, Ready for review

2022-01-13 08:08 UTC, choppymaster commented on README.md
> +Either use `git clone https://github.com/Ryujinx/Ryujinx` to clone the repository or use the `Code>Download zip` button to get the files
```suggestion
Either use `git clone https://github.com/Ryujinx/Ryujinx` to clone the repository or use the `Download zip` button to get the files
```

2022-01-13 08:17 UTC, Shahil-Ayato commented on README.md
> +Either use `git clone https://github.com/Ryujinx/Ryujinx` to clone the repository or use the `Code>Download zip` button to get the files
Imo I don’t like removing `code` as not everyone would know/see where the download button is, so I’m leaving that change there to make it more streamlined for newer users.

2022-01-13 09:54 UTC, choppymaster reviewed
Some nits.

2022-01-13 10:05 UTC, choppymaster commented on README.md
> +* Web hosting and infrastructure
```suggestion
* Web hosting and infrastructure maintaining
```

2022-01-13 10:05 UTC, choppymaster commented on README.md
> +* Additional hardware to test and fix any bugs certain vendors (AMD, Nvidia, and Intel) may have
```suggestion
* Additional hardware to test (eg. GPUS to fix graphical bugs, other accessories to add support for, etc.) 
```

2022-01-13 10:44 UTC, choppymaster commented on README.md
> +All the funds acquired through our Patreon are considered a donation to support our work. Patrons get 1 week of exclusive early access to our progress reports and access to developer interviews.
```suggestion
All the funds acquired through our Patreon are considered a donation to support our work. Patrons will get 1 week of exclusive early access to our progress reports and access to developer interviews.
```

2022-01-13 10:45 UTC, choppymaster commented on README.md
> +The Ryujinx.Audio project is licensed under the terms of the <a href="https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Audio/LICENSE.txt
```suggestion
The Ryujinx.Audio project is licensed under the terms of <a href="https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Audio/LICENSE.txt
```

2022-01-13 10:47 UTC, choppymaster commented on README.md
> +If you are having problems launching homebrew or a particular game marked status-playable or status-ingame in our compatibility list, or if you need help with setting up Ryujinx we recommend you ask
```suggestion
If you are having problems launching homebrew or a particular game marked status-playable or status-ingame in our compatibility list, or if you need help with setting up Ryujinx we recommend you ask questions in the #support channel of our [Discord server](https://discord.gg/Ryujinx) or take a look at our <a href="https://github.com/Ryujinx/Ryujinx/wiki/Frequently-Asked-Questions" target="_blank">FAQ.</a></i><br />  If you have contributions, have suggestions, or just want to get in touch with the team, join our [Discord server](https://discord.gg/Ryujinx).
```

2022-01-13 10:50 UTC, choppymaster commented on README.md
> +Either use `git clone https://github.com/Ryujinx/Ryujinx` to clone the repository or use the `Code>Download zip` button to get the files.
```suggestion
Either use `git clone https://github.com/Ryujinx/Ryujinx` on the command line to clone the repository or use Code --> Download zip button to get the files.
```

2022-01-13 12:23 UTC, Shahil-Ayato commented on README.md
> +The Ryujinx.Audio project is licensed under the terms of the <a href="https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Audio/LICENSE.txt
Imo removing that is unnecessary

2022-01-13 12:24 UTC, Shahil-Ayato commented on README.md
> +This software is licensed under the terms of the <a href="https://github.com/Ryujinx/Ryujinx/blob/master/LICENSE.txt" target="_blank">MIT license.</a></i><br />
Ditto

2022-01-13 13:48 UTC, choppymaster commented on README.md
> +* Software licenses to allow developers use whatever they are comfortable with
Ditto here

2022-01-13 13:54 UTC, choppymaster commented on README.md
> +* Software licenses to allow developers use whatever they are comfortable with
Change to `Software licences (Visual Studio, etc)` etc, up to you.

2022-01-13 14:03 UTC, Shahil-Ayato commented on README.md
> +* Software licenses to allow developers use whatever they are comfortable with
Imo not needed.

2022-01-14 17:17 UTC, EmulationFanatic reviewed
Added my suggestions.

2022-01-14 17:17 UTC, EmulationFanatic commented on README.md
> +* Software licenses to allow developers use whatever they are comfortable with
Development on this emulator takes place during contributors' free time. However, there are some inherent costs:
* Hackable Nintendo Switch consoles to reverse-engineer the hardware
* Additional computer hardware for testing purposes (e.g. GPUs to diagnose graphical bugs, etc.)
* Licenses for various software development tools

2022-01-14 17:17 UTC, EmulationFanatic commented on README.md
> +All the funds acquired through our Patreon are considered a donation to support our work. Patrons will get 1 week of exclusive early access to our progress reports and access to developer interviews.
* Web hosting and infrastructure maintenance

All funds received through Patreon are considered a donation to support the project. Patrons receive early access to progress reports and exclusive access to developer interviews.

2022-01-14 17:17 UTC, EmulationFanatic commented on README.md
> +As of September 2021, Ryujinx has been tested on nearly 3,400 titles: ~3,000 boot past menus and into gameplay, with approximately 2,400 of those being considered playable.
As of January 2022, Ryujinx has been tested on approximately 3,500 titles; over 3,200 boot past menus and into gameplay, with roughly 2,500 of those being considered playable.

2022-01-18 17:37 UTC, Shahil-Ayato commented
@EmulationFanatic great to see you again and I greatly appreciate your input! All feedback has been addressed, ready for review.

2022-01-18 19:39 UTC, EmulationFanatic commented on README.md
> +* Web hosting and infrastructure maintinance
Typo.
"maintenance" is the proper spelling.

2022-01-18 21:40 UTC, Shahil-Ayato commented on README.md
> +* Web hosting and infrastructure maintinance
Agh don’t know how I let that one slip I’ll fix it asap

2022-01-18 21:42 UTC, Shahil-Ayato commented
Feedback all addressed, ready for review/merge

2022-01-18 21:43 UTC, merged