Making deadzones feel nice and smooth
Ryujinx/Ryujinx pull request #3079
Opened 2022-02-03 22:42 UTC by skrekhere

Smoothing out deadzones leads to a much better feel on controller, and adding the .idea directory to the .gitignore cleans up commits using rider
Should fix #3074

2022-02-03 23:28 UTC, MutantAura commented
I'd suggest a more descriptive PR title and description here.
Something like "Adjustments to deadzone calculation and clamping" and a brief explanation of what you're changing and how it is different/better than the old method. Nothing crazy long but it helps the reviewers and also anyone reading :)

2022-02-04 13:49 UTC, MelonSpeedruns commented
Could you push again so the build can be triggered? Looks like something happened to the building system last night and it messed up building.

2022-02-04 22:00 UTC, Vegita2 commented
I made a deadzone visualizer some time ago and added the current implementation and the one from this pr to it.
https://vigilant-beaver-7e2f51.netlify.app/
(there is a select input at the bottom left)

color ranges from black to white depending on stick input value
black = no input
white =  fully pressed
red circle = deadzone

Basically the difference is this:

Current implementation
<img src="https://user-images.githubusercontent.com/9483499/152607625-866cbe47-18f6-4045-a698-5e19f31f60c9.png" width="70%">

Pull request implementation
<img src="https://user-images.githubusercontent.com/9483499/152608055-8962c696-6955-4c4c-bfc4-6eb5f94a9ed4.png" width="70%">

2022-02-06 16:18 UTC, MutantAura commented
Some quick tests performed at deadzone of 0.5 in BoTW

Master:
https://user-images.githubusercontent.com/44103205/152690279-dc835f16-4721-4611-9b6d-59ee457c627c.mp4

PR:
https://user-images.githubusercontent.com/44103205/152690303-45dc9097-67c9-4480-bd0c-f6e1038cc769.mp4

There is much more fine control in the new calculation and removes the almost 8-axis effect a high deadzone would previously apply in the past (See master video). No other abnormalities noticed. Looking good from my perspective.

2022-02-06 17:04 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / (magnitudeClamped)) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
```suggestion
                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
```

2022-02-06 17:04 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dy = ClampAxis((y / (magnitudeClamped)) * ((magnitudeClamped - deadzone) / (1 - deadzone)))
```suggestion
                Dy = ClampAxis((y / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone)))
```

2022-02-06 17:04 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / (magnitudeClamped)) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
Can't magnitude be zero here? Is it fine to divide by zero in this case?

2022-02-06 17:34 UTC, skrekhere commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / (magnitudeClamped)) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
Magnitude should only be zero when x and y are both 0, and in my testing, dividing by zero is fine if it happens. Could add checks for when deadzones are applied to not apply them when both axes are zero, to be safe.

2022-02-08 09:49 UTC, AcK77 requested changes

2022-02-08 09:49 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +            if (magnitudeClamped <= deadzone) return new JoystickPosition()
Add bracket over the `if` content and put the return on a new line.

2022-02-08 09:49 UTC, AcK77 commented on Ryujinx.Input/HLE/NpadController.cs
> +            return new JoystickPosition()
Add a new extra empty line before

2022-02-08 16:52 UTC, skrekhere commented on Ryujinx.Input/HLE/NpadController.cs
> +            if (magnitudeClamped <= deadzone) return new JoystickPosition()
done:)

2022-02-08 16:52 UTC, skrekhere commented on Ryujinx.Input/HLE/NpadController.cs
> +            return new JoystickPosition()
and done

2022-02-09 18:17 UTC, riperiperi commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
I'm not really a fan of the potential divide by zero. ClampAxis seems like it is working by a fluke, as float.NaN casts to 0 as short. If the behaviour of that function changes, this might break things in an unexpected way.

2022-02-09 18:29 UTC, skrekhere commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
There's no more potential of a divide by zero. that changed when I changed the < to a <= in the first check, before the ClampAxis call entirely. The only potential of a divide by zero before the change was when the magnitude is zero, with the set also being zero, but now a divide by zero is only possible with negative deadzone values, which is a whole other problem if that's allowed to happen.

2022-02-10 16:19 UTC, german77 commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
If deadzone is 1 you also have a divide by zero

2022-02-10 16:22 UTC, german77 commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
Ah nevermind we can't never reach this situation since magnitude is already clamped to 1. Another thing to take in mind is that you don't need to clamp negative values. Since (x*x + y*y) is guaranteed to be positive

2022-02-11 02:41 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
Speaking about that, `ClampAxis` appears to be slightly wrong. It would be nice to take a look too, since you're working on this.

2022-02-11 20:52 UTC, riperiperi commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
Ah, I didn't see the condition above that returns early. It should also trigger if deadzone is >= 1, so no concerns.

And yeah, `ClampAxis` is incorrect right now, it doesn't clamp positive and the negative clamp is wrong.

2022-02-12 08:18 UTC, skrekhere commented on Ryujinx.Input/HLE/NpadController.cs
> +                Dx = ClampAxis((x / magnitudeClamped) * ((magnitudeClamped - deadzone) / (1 - deadzone))),
Latest commit should fix everything up :)

2022-02-12 22:18 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +                return (short) Math.Max(value * -short.MinValue, short.MinValue);
```suggestion
                return (short)Math.Max(value * -short.MinValue, short.MinValue);
```

2022-02-12 22:18 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +            return (short) Math.Min(value * short.MaxValue, short.MaxValue);
```suggestion
            return (short)Math.Min(value * short.MaxValue, short.MaxValue);
```

2022-02-12 22:18 UTC, gdkchan commented on Ryujinx.Input/HLE/NpadController.cs
> +                return (short) Math.Max(value * -short.MinValue, short.MinValue);
Kinda wonder if -1.0 is supposed to map to -32768. That would make the range uneven sinnice short.MaxValue is 32767.

2022-02-14 17:42 UTC, skrekhere commented
fixed up that spacing

2022-02-16 10:06 UTC, merged

2022-02-16 10:55 UTC, riperiperi approved these changes
Nice work, good to see this weird behaviour sorted.

2022-02-16 10:55 UTC, riperiperi commented on Ryujinx.Input/HLE/NpadController.cs
> +                return (short)Math.Max(value * -short.MinValue, short.MinValue);
This is a bit weird, but it seems to work as intended?
`-short.MinValue` doesn't fit in a short, it will just equal `-32768` again. But here, it seems to negate as int32, then multiply the float, so it's 32768f.