added trace log level
Ryujinx/Ryujinx pull request #3096
Opened 2022-02-07 21:07 UTC by mlgatto

Added support for trace logs

2022-02-07 21:45 UTC, gdkchan commented
Can you also change:
https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallTable.cs#L482
and:
https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.HLE/HOS/Services/IpcService.cs#L120
To use the new trace log level instead of debug?

2022-02-08 09:45 UTC, AcK77 requested changes
You have to update the config file to add the new field, even if it’s disabled as default!

2022-02-08 09:45 UTC, AcK77 commented on Ryujinx.Common/Logging/Logger.cs
> +                case LogLevel.Trace     : Trace     = enabled ? new Log(LogLevel.Trace) :    new Log?(); break;
Alignment is off here

2022-02-08 13:01 UTC, Pixxel123 commented
If it's not going to be enabled by default, I'd probably move the UI toggle to be at the bottom of the list, after Guest Logs and before Fs Access Logs to make it easier for users to have just the defaults on.

2022-02-08 15:27 UTC, mlgatto commented
> You have to update the config file to add the new field, even if it’s disabled as default!

@AcK77 Where can I find the config file?

2022-02-08 15:30 UTC, gdkchan commented
> > You have to update the config file to add the new field, even if it’s disabled as default!
> 
> @AcK77 Where can I find the config file?

This shouldn't be needed anymore, the default config file was removed some months ago.

2022-02-08 19:39 UTC, mlgatto commented
> I mean you still have to update the code which update the config file is needed, see https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx/Configuration/ConfigurationState.cs#L978 as example.

@AcK77 sorry I'm a bit lost, I think I already have updated that section of the code. Can you elaborate a bit more what is still needed? Thanks :)

2022-02-08 20:56 UTC, jduncanator commented
> > I mean you still have to update the code which update the config file is needed, see https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx/Configuration/ConfigurationState.cs#L978 as example.
> 
> @AcK77 sorry I'm a bit lost, I think I already have updated that section of the code. Can you elaborate a bit more what is still needed? Thanks :)

You need to add a migration from version 35 to your new version. Even though the migration doesn't really need to do anything explicitly (the default value of a bool is false after all), you still need to do a migration to trigger Ryujinx to reserialize the configuration file on first load, bump the version number, and add the new trace log level option to the configuration file.

2022-02-09 18:37 UTC, gdkchan approved these changes
lgtm, thanks.

2022-02-11 18:55 UTC, Thog approved these changes

2022-02-11 20:49 UTC, riperiperi reviewed
Nice, will be good having a trace log level. I don't see anything in here to update the dialog that appears when trying to start a game with Debug logs, though. 

The UI has a dialog that pops up and essentially asks the user to disable them due to potential performance impact - but the majority of these logs have been moved to the trace level. I think the warning should be instead for that level, and also the placement of the checkbox in settings might be worth moving next to debug too.

2022-02-16 10:05 UTC, AcK77 commented
Could you please address the comments of Riperiperi then we can merge it ;)!

2022-02-17 23:27 UTC, riperiperi approved these changes

2022-02-18 00:08 UTC, merged