Lop3Expression: Optimize expressions
Ryujinx/Ryujinx pull request #3184
Opened 2022-03-08 12:12 UTC by merryhime

Implemented for fun. Feel free to close if not required.

NPN-transforms the truth table to one of the basic 14 classes.

Terminology as per:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/8682882/157235838-a30e1159-cc58-4fa7-8347-99da3b22ca34.png">

2022-03-08 12:59 UTC, jduncanator commented
It'd be nice to define all the "magic values" in there as `private const`s at the top of the class, assuming they have some proper name? Judging by the values in the switch expression, seems like they could?

2022-03-08 13:05 UTC, Thog commented on Ryujinx.Graphics.Shader/Instructions/Lop3Expression.cs
> +        private static Operand GetExpr(int imm, EmitterContext context, Operand x, Operand y, Operand z)
Might be worth mapping ``imm`` to an enum and making it have the size of a byte

2022-03-08 13:30 UTC, gdkchan commented
> It'd be nice to define all the "magic values" in there as `private const`s at the top of the class, assuming they have some proper name? Judging by the values in the switch expression, seems like they could? I won't pretend to understand what's happening here, ha!

I think it's worth explaining the problem we're trying to solve here, to put things into context.

The values on the switch expression are the immediate values of the LOP3 instruction. They are effectively the results of the truth table. Since there are 3 inputs, this value is 8-bits, as with 3 1-bit inputs we have effectively 8 possible combinations. For example, for 0x96 (0b10010110) we have:

| A | B | C | Result |
| - | - | - | ------ |
| 0 | 0 | 0 | 0 |
| 0 | 0 | 1 | 1 |
| 0 | 1 | 0 | 1 |
| 0 | 1 | 1 | 0 |
| 1 | 0 | 0 | 1 |
| 1 | 0 | 1 | 0 |
| 1 | 1 | 0 | 0 |
| 1 | 1 | 1 | 1 |

The value on the "Result" column is the immediate value. The problem we're trying to solve here is finding the minimal logical expression that, given the values for inputs A, B and C, can produce the "Result" value. For this specific immediate value, it is `(A ^ B) ^ C`, because if we look at the XOR truth table, we have:

| A | B | Result |
| - | - | ------ |
| 0 | 0 | 0 |
| 0 | 1 | 1 |
| 1 | 0 | 1 |
| 1 | 1 | 0 |

Which is exactly the result of the first 4 rows we had before. But we have an additional input here. We can see that when "A" is 1, we have the inverse results (0b1001 rather than 0b0110). Since XOR has the property inverting the input if the value is 1, and keeping it unchanged if 0, we can simply XOR the result of `(B ^ C)` by `A` to get the results on the first table.

What the instruction does is performing the logical operation for each bit of the 32-bit input values on the register, and producing a 32-bit result.

Given that, I don't think naming them is needed.

2022-03-08 13:34 UTC, gdkchan commented on Ryujinx.Graphics.Shader/Instructions/Lop3Expression.cs
> +                TruthTable.False         => Const(IrConsts.False),
I know that was on the previous code, but I think it's better to just use `Const(0)` and `Const(uint.MaxValue)` or `Const(-1)` here, since `IrConsts.False` and `IrConsts.True` is mostly used for predicate results, that only has two possible values, which is not exactly the case here.

2022-03-13 10:53 UTC, Thog approved these changes

2022-03-19 14:58 UTC, gdkchan requested changes
This is currently causing regressions in at least one game, since it seems to introduce redudant `BitwiseNot` operations.
Previous codegen:
```glsl
    temp_1 = floatBitsToInt(fp_c1_data[0].x) & floatBitsToInt(fp_c0_data[1392].x);
    temp_2 = temp_0 | temp_1;
```
PR:
```glsl
    temp_1 = ~temp_0;
    temp_2 = ~floatBitsToInt(fp_c1_data[0].x);
    temp_3 = ~floatBitsToInt(fp_c0_data[1392].x);
    temp_4 = temp_2 | temp_3;
    temp_5 = temp_1 & temp_4;
    temp_6 = ~temp_5;
```
Disasm:
```
LOP3.LUT R2, R2, c[0x1][0x0], R3, 0xf8 ;
```
This is causing bindless elimination to fail here:
https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Graphics.Shader/Translation/Optimizations/BindlessElimination.cs#L56
Which causes Hades to just show a black screen.

2022-03-19 15:07 UTC, merryhime commented
Thanks. Likely would be easier to not generate the `~(~a & ~b)` pattern to begin with and instead directly generate `a | b`.

2022-03-19 15:52 UTC, gdkchan approved these changes
lgtm, tested a few games and they look file with the change now 👍 
One thing to note is that you need to change the shader codegen version on `Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs` to update the shader cache with the new shaders.
Also it would be nice to have some comparisons of old codegen vs new. I believe it would be mostly improving on XOR expressions that the old one couldn't handle well.

2022-04-05 22:49 UTC, riperiperi approved these changes
Nice one, looks good to me.

2022-04-08 09:17 UTC, merged