UI - Avalonia Part 2
Ryujinx/Ryujinx pull request #3351
Opened 2022-05-19 10:31 UTC by emmauss

This part adds the settings window and its child windows and controls

2022-05-21 21:34 UTC, Thog commented on Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
> +    public class KeyboardHotkeys
Any reasons of this change?

2022-05-21 22:09 UTC, gdkchan commented on Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
> +    public class KeyboardHotkeys
It allows the object to be used on a XAML data binding directly. Using a struct would not allow the UI modifications to be propagated back, I assume because it is passed by value and so it modifies a copy of the struct.

2022-05-22 07:07 UTC, emmauss commented on Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
> +    public class KeyboardHotkeys
The xaml bindings don't work with structs, as updates won't affect the original object.

2022-05-22 09:53 UTC, Thog commented on Ryujinx.Common/Configuration/Hid/KeyboardHotkeys.cs
> +    public class KeyboardHotkeys
I see 👍

2022-05-23 13:19 UTC, AcK77 requested changes

2022-05-23 13:19 UTC, AcK77 commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml.cs
> +                    _currentAssigner.GetInputAndAssign(assigner, keyboard);
Resolve the warning

2022-05-23 13:19 UTC, AcK77 commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml.cs
> +        private async void PlayerIndexBox_OnSelectionChanged(object? sender, SelectionChangedEventArgs e)
Resolve the warning

2022-05-23 13:19 UTC, AcK77 commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml.cs
> +                    _currentAssigner.GetInputAndAssign(assigner);
Resolve the warning

2022-05-25 06:17 UTC, Squall-Leonhart commented
avalonia builds aren't adding their executable name to the Ryujinx Nvidia Profile, leading to threaded optimization not being disabled, the builds are ryujinx.ava.exe, ryujinx.exe is added

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (Config is StandardKeyboardInputConfig)
```suggestion
            if (Config is StandardKeyboardInputConfig keyboardInputConfig)
```

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                Configuration = new InputConfiguration<Key, ConfigStickInputId>(Config as StandardKeyboardInputConfig);
```suggestion
                Configuration = new InputConfiguration<Key, ConfigStickInputId>(keyboardInputConfig);
```

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (Config is StandardControllerInputConfig)
Same as above.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                    ident = "keyboard";
Would be nice to have constants for those too.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (selected == "disabled")
Same comment about the constants.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (selected == "disabled")
On a side note, I'm not sure why strings are being used for this. It seems it would be better to have a struct with device type enum and a integer ID.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +        private static string GetShrinkedGamepadName(string str)
The word `Shrinked` does not exist. The correct is `Shrunken`.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            const string ShrinkChars = "...";
The correct name for this is "Ellipsis".

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +        private static string GetShrinkedGamepadName(string str)
Probably a better name  is `GetShortGamepadName`.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                    IGamepad gamepad = _mainWindow.InputManager.KeyboardDriver.GetGamepad(id);
```suggestion
                    using IGamepad gamepad = _mainWindow.InputManager.KeyboardDriver.GetGamepad(id);
```
Then you can remove the dispose call.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                        new LeftJoyconCommonConfig<Key>
Move this to the line above for consistency with the other. Also needs to fix the indentation.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                        new JoyconConfigKeyboardStick<Key>
Same as above.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                foreach (char invalidChar in Path.GetInvalidFileNameChars())
You can avoid this loop by doing `bool validFileName = ProfileName.IndexOfAny(Path.GetInvalidFileNameChars()) == -1`.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                int i = newConfig.FindIndex(x => x.PlayerIndex == this.PlayerId);
```suggestion
                int i = newConfig.FindIndex(x => x.PlayerIndex == PlayerId);
```

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (_mainWindow.AppHost != null)
`_mainWindow.AppHost?.NpadManager.ReloadConfiguration(newConfig, ConfigurationState.Instance.Hid.EnableKeyboard, ConfigurationState.Instance.Hid.EnableMouse);`

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/MainWindowViewModel.cs
> +            if(AvaloniaMappingHelper.TryGetAvaKey((Ryujinx.Input.Key)ConfigurationState.Instance.Hid.Hotkeys.Value.ShowUi, out var showUiKey))
```suggestion
            if (AvaloniaMappingHelper.TryGetAvaKey((Ryujinx.Input.Key)ConfigurationState.Instance.Hid.Hotkeys.Value.ShowUi, out var showUiKey))
```

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +        public bool IsResolutionScaleActive => _resolutionScale == 0;
Shouldn't this be `!= 0`?

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +                Title = "Select Theme File",
Should be localizable.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +            dialog.Filters.Add(new FileDialogFilter() { Extensions = { "xaml" }, Name = "Xaml Theme File" });
Should be localizable.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +            BaseStyleIndex = config.Ui.BaseStyle == "Light" ? 0 : 1;
Maybe should be localizable, but then this check would need to change too.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/Windows/ControllerSettingsWindow.axaml.cs
> +        private void Button_Unchecked(object sender, RoutedEventArgs e)
Missing empty line above.

2022-06-04 20:26 UTC, gdkchan commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml.cs
> +            if (e.SelectedItem is NavigationViewItem navitem)
Is there no way to make the control do this "automatically"?

2022-06-04 20:34 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +        public bool IsResolutionScaleActive => _resolutionScale == 0;
Nevermind, this is correct, but the name is misleading. It should really be `IsCustomResolutionScaleActive`.

2022-06-06 07:39 UTC, emmauss commented on Ryujinx.Ava/Ui/Controls/ButtonKeyAssigner.cs
> +                        SetButtonText(ToggledButton, "Unbound");
`Unbound` is an enum value, like all other key text. Localizing it will break binding to the Key enum

2022-06-06 08:28 UTC, emmauss commented on Ryujinx.Ava/Ui/Controls/ButtonKeyAssigner.cs
> +                    catch { }
No exception currently. It is removed.

2022-06-06 08:53 UTC, emmauss commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +            BaseStyleIndex = config.Ui.BaseStyle == "Light" ? 0 : 1;
`Light` and `Dark` are used internally for config values, not ui text.

2022-06-06 08:59 UTC, emmauss commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml.cs
> +            if (e.SelectedItem is NavigationViewItem navitem)
No. The base Navigation Panel control doesn't know how to link pages, without the user handling selection changed.

2022-06-06 09:04 UTC, emmauss commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (selected == "disabled")
Strings are simpler. The device list can have as many devices as connected. You would still parse the enums to strings to make comparisons, as we need the name to figure out which type it is.

2022-06-06 12:40 UTC, gdkchan commented on Ryujinx.Ava/Ui/Controls/ButtonKeyAssigner.cs
> +                        SetButtonText(ToggledButton, "Unbound");
IMO the other key names should be localizable too. It's an issue that needs to be solved in general.

2022-06-06 12:42 UTC, gdkchan commented on Ryujinx.Ava/Ui/Models/ControllerModel.cs
> +    public record ControllerModel(ControllerType Type, string Name);
My understanding is that nothing on Ryujinx.Ava needs to be public since no other project will consume it. Is there a reason for making it public?

2022-06-06 12:50 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (selected == "disabled")
On a lot of places, the code is not checking the device ID, but just the "type", that is, if the input is disabled, keyboard or controller. So it seems beneficial to me to use a struct with one enum for the "type" and a string for the ID. For the cases where you don't care about the actual ID, you have a more efficient comparison (you don't need to compare a string, just an ID), the code becomes less fragile because if someone changes one of the strings for some reason, the code no longer breaks at runtime, instead it would be a compile time error. And one could use the rename feature to change all uses properly.

2022-06-07 08:06 UTC, emmauss commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +            if (selected == "disabled")
Added DeviceType enum

2022-06-07 08:13 UTC, emmauss commented on Ryujinx.Ava/Ui/Models/ControllerModel.cs
> +    public record ControllerModel(ControllerType Type, string Name);
Updated all public classes in Ryujinx.Ava to `internal`

2022-06-07 16:18 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +        public ObservableCollection<(DeviceType Type,string Id, string Name)> Devices { get; set; }
```suggestion
        public ObservableCollection<(DeviceType Type, string Id, string Name)> Devices { get; set; }
```

2022-06-24 05:26 UTC, Ackliez commented
The input settings window seems to have an alignment issue with or without optimized scaling

Normalized window
![Short](https://user-images.githubusercontent.com/979183

Full screen window
![Full](https://user-images.githubusercontent.com/97918364/175468243-0c468f91-8e78-44d6-bb73-8939a37e4334.png)
64/175468197-0aebdc1a-2442-493c-89c2-cebdf32d2c0a.png)

2022-07-04 16:27 UTC, gdkchan approved these changes
lgtm, other than the fact that the settings window is way too large by default. Not sure why the width was increased again.

2022-07-05 16:15 UTC, Thog approved these changes
I agree with @gdkchan on the settings window size being a bit too big but apart from that, some part of the code could use some later refactoring

2022-07-05 18:06 UTC, merged