Improve raw NCA handling
Ryujinx/Ryujinx pull request #3434
Opened 2022-07-01 00:50 UTC by liamwhite

This improves the handling of raw NCAs in two ways:
- Allows save data persistence to correctly function when booting the raw NCAs extracted from multiprogram applications. This avoids a crash when attempting to actually boot the game.
- Allows the actual TitleId of the NCA to appear in the main games list.

This allows conveniently booting the individual games from e.g. Super Mario 3D All-Stars, without having to go through the launcher title.

2022-07-03 20:58 UTC, Thog requested changes
That doesn't improve things, that would only result in wrong save being used.

2022-07-04 02:36 UTC, liamwhite commented
So here's how this is playing out:
- the ProgramId for the sub-NCAs in SMD3AS are e.g. 0x010049900F546003 (Mario Galaxy)
- when the game calls OpenSaveDataFileSystem, it requests the save with its own ProgramId, which is 0x010049900F546003
- because of the & ~0xFul, the save was only created in EnsureSaveData for 0x010049900F546000, which then results in a crash

This isn't crashing when the game is booted through the launcher because it registers the sub-programs with LibHac using RegisterProgramIndexMapInfo. The solution I have provided avoids the crash but is indeed incorrect.

One possible way this could be dealt with would be to also mask off the low nibble of ProgramId when [creating the application client](https://github.com/Ryujinx/Ryujinx/blob/d21b403886fdc00dac2493532b3e8ff53d5882c4/Ryujinx.HLE/HOS/LibHacHorizonManager.cs#L78). I don't think this would break anything, but it feels a bit wrong. The other option is that I can just close this, as booting sub-programs isn't something that is normally supported by the console, even though it's useful for debugging games.

Thoughts?

2022-09-14 14:25 UTC, Thealexbarney commented
Registering the program index map the same way as when launching the main program would be the best way

2022-12-26 10:14 UTC, marysaka commented
Closing as stale.

2022-12-26 10:14 UTC, closed without merging