Avalonia - Make tooltips more useful and descriptive, update Spanish localization
Ryujinx/Ryujinx pull request #3453
Opened 2022-07-09 03:11 UTC by MetrosexualGarbodor

Using an emulator for the first time can be confusing, and many people assume certain settings do things they actually don't, which is not helped by the settings' descriptions. Hell, I used Ryujinx for over a year before I understood what "FS integrity checks" did.
My goal here is to keep it as short as possible, while still giving relevant information that the average user can grasp. Below are my proposed changes:

![docked](https://user-images.githubusercontent.com/79612681/178089203-2c4d8352-56c6-4ea3-8a32-06a6fbe49f51.png)

![vsync](https://user-images.githubusercontent.com/79612681/178089241-8789871f-2d11-42b4-bec6-977d658d283b.png)

![fs](https://user-images.githubusercontent.com/79612681/178089253-d7246d58-6937-4701-92cf-cca2e29c9761.png)

![expanDRAM](https://user-images.githubusercontent.com/79612681/178089260-4cff222e-bd5a-42f7-81f3-89066c8f1dd5.png)

![ims](https://user-images.githubusercontent.com/79612681/178089284-034d7dea-8523-4290-91d2-c60ca9e91b7e.png)

![pptc](https://user-images.githubusercontent.com/79612681/178089300-a655812e-19aa-4784-86ad-0bceb523570d.png)

![MMM](https://user-images.githubusercontent.com/79612681/178089303-2beaf8f3-49b9-4228-b644-a189b72bc8e1.png)

![shader cache](https://user-images.githubusercontent.com/79612681/178089308-0676ea71-f44d-436b-b8ee-48107b60aeec.png)

![backend threading](https://user-images.githubusercontent.com/79612681/178089310-69c53b8e-ee1e-41fd-91c8-43325df3d3bd.png)

![audio](https://user-images.githubusercontent.com/79612681/178089339-276fd61a-6383-4acd-9992-d33ae4f6305d.png)

![lan mode](https://user-images.githubusercontent.com/79612681/178089359-8f6a4db7-dfb8-431d-a2cb-16d009194aaf.png)

![discord_rich_presence](https://user-images.githubusercontent.com/79612681/178089380-23838e97-76df-47a8-98f2-e91fe85691cc.png)

I'm a bit iffy on the shader cache and memory manager modes' tooltips, so if anyone has some suggestions for those, I'm all ears. I'm also aware that people will still not read the Vsync tooltip and turn it off, unless the option is renamed to "Frame Limiter" or something similar.
The all-caps suggestions ("OFF if unsure") will be replaced by bold lowercase when it's possible and I figure out how to do it.

Apologies to all of you who did a localization for making you do it again lol.

2022-07-09 03:25 UTC, gdkchan commented
I think the part that says "in handheld mode, handheld controls will be used" is not entirely correct, as most games works fine in handheld mode with player 1 configured only.

And for the VSync tooltip, it shouldn't mention that it can be toggled with Tab key as those shortcuts are configurable now. And Tab to toggle VSync is not even working on Avalonia right now.

2022-07-09 03:29 UTC, german77 commented
Handheld only in handheld mode is a yuzu thing. Since player 1 and handheld are merged together in the config.  A switch should be fine with any controller.

2022-07-09 04:04 UTC, Moonlacer commented
More descriptive, I like it. Somehow, I think adding more text (but not too much) to a tooltip makes it seem higher quality. I am very much looking forward to seeing Avalonia being released to the regular builds... 👍

2022-07-09 08:35 UTC, Niwu34 requested changes
Really nice work: Loving the changes
Gave it a quick read and noticed some tiny things

A few more things that seem a bit odd are the tooltips for the logs:
I'd either remove them or give them a more detailed description

2022-07-09 08:35 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/en_US.json
>    "DirectKeyboardTooltip": "Enable or disable \"direct keyboard access (HID) support\" (Provides games access to your keyboard as a text entry device)",
same as above

2022-07-09 08:35 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/en_US.json
>    "DirectMouseTooltip": "Enable or disable \"direct mouse access (HID) support\" (Provides games access to your mouse as a pointing device)",
same as above

2022-07-09 08:35 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/en_US.json
>    "CustomThemeCheckTooltip": "Enable or disable custom themes in the GUI",
You removed the `Enable or disable` part from all the other tooltips:
Maybe do the same here for consistency purposes

2022-07-09 08:35 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "VSyncToggleTooltip": "Emulated console's Vertical Sync. Essentially a frame-limiter for the majority of games; disabling it may cause games to run at higher speed or make loading screens take long
With Avalonia `tab` will probably not be the hot key for disabling guest vsync anymore:
(See here: https://discord.com/channels/410208534861447168/412730623405457408/995107048587018260)
I'd honestly remove this part: `Can be toggled in-game with Tab.`

Another reason is that you will be able to switch the hot keys with Avalonia: So this tool tip might be invalid for people who accidently changed it and/or forgot about it: This could confuse them
(Ye I wouldn't be surprised if that actually happens to someone lol)

2022-07-09 08:35 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "GraphicsBackendThreadingTooltip": "Executes graphics backend commands on a second thread.\n\nSpeeds up shader compilation, reduces stuttering, and improves performance on GPU drivers without multi
`\n\n` (a space too much?)
Not sure if this changes any functionality, or was intended (just noticed it while reading through your changes)

2022-07-09 17:51 UTC, MetrosexualGarbodor commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "GraphicsBackendThreadingTooltip": "Executes graphics backend commands on a second thread.\n\nSpeeds up shader compilation, reduces stuttering, and improves performance on GPU drivers without multi
Yep that was a mistake, I'll correct it for a neater result but I don't think it actually changes anything.

2022-07-09 17:58 UTC, MetrosexualGarbodor commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "VSyncToggleTooltip": "Emulated console's Vertical Sync. Essentially a frame-limiter for the majority of games; disabling it may cause games to run at higher speed or make loading screens take long
How about changing that part to "Can be toggled in-game with a hotkey" or even "a hotkey of your preference"?

2022-07-09 18:00 UTC, MetrosexualGarbodor commented on Ryujinx.Ava/Assets/Locales/en_US.json
>    "DirectKeyboardTooltip": "Enable or disable \"direct keyboard access (HID) support\" (Provides games access to your keyboard as a text entry device)",
I simply did it for the settings which needed some explaining or people were confused about. IMO no one is looking for information on what "Enable custom theme" does, for example. But I agree with changing direct keyboard and direct mouse access tooltips, because those aren't as evident.

2022-07-09 18:22 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "VSyncToggleTooltip": "Emulated console's Vertical Sync. Essentially a frame-limiter for the majority of games; disabling it may cause games to run at higher speed or make loading screens take long
Ye sounds good!

2022-07-09 19:18 UTC, gdkchan commented
We will need some way to indicate that the other locale files should be updated too. Removing the modified entries from the other locale files and moving them to the bottom on the English one would work, but would probably be annoying to do without a script to automate it.

2022-07-09 19:32 UTC, MetrosexualGarbodor commented
I was thinking of pinging past localization contributors if they don't respond within some days of merging this.

The lines which have had any significant changes are: 112, 113, 114, 126, 167, 421, 425, 428, 429, 430, 435, 436, 437, 438, 439, 443, 444, 445, 446, 447, 453, 454, 455, 456, 457, 458, 459, 460, 464, 465, 466, 481, 482, 497, 571

2022-07-09 21:35 UTC, Niwu34 commented
I'm waiting for all the Avalonia related stuff to be merged for the German localization.
Will open a PR after that (hoping for some feedback from my German fellows) 😄

2022-07-10 13:23 UTC, Thog approved these changes
lgtm

2022-07-11 22:32 UTC, AcK77 approved these changes

2022-07-11 22:32 UTC, merged