Update de_DE.json
Ryujinx/Ryujinx pull request #3502
Opened 2022-07-29 20:44 UTC by Niwu34

Update for the German Localization.
I mainly changed the part that was changed with the tooltip PR added some missing strings and tried to do some overall clean up/better wording

2022-07-31 07:46 UTC, reloxx13 requested changes
Thank you very much!

I found and added a few suggestions.

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "ToggleDiscordTooltip": "Wähle ob Ryujinx in der Discord Aktivität als \"derzeit spielend\" anzeigezeigt werden soll",
You have removed the activate strings before, remove it here, too for better slang.

Suggestion
`"Ryujinx in der Discord Aktivität als \"derzeit spielend\" anzeigen"`

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "CustomThemeCheckTooltip": "Verwende ein benutzerdefiniertes Avalonia-Thema für die GUI, um das Aussehen der Emulatormenüs zu verändern.",
Users wont know what avalonia is and the codename will also be gone after merge.    

its also called `Theme` or `Skin` in german, even better `Design`. Thema ist auch richtig aber sehr weit hergeholt.

`Verwende ein eigenes Design für die Emulator Benutzeroberfläche`

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "DockModeToggleTooltip": "Im gedockten Modus verhält sich das emulierte System wie eine gedockte Nintendo Switch. Dies verbessert die grafische Qualität der meisten Spiele. Umgekehrt führt die Deak
We also write `Controller` in german

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "VSyncToggleTooltip": "Vertikale Synchronisierung der emulierten Konsole. Im Wesentlichen ist diese Option ein Frame-Limiter für die meisten Spiele; die Deaktivierung kann dazu führen, dass Spiele
2nd `das` should also be `dass`, `dass Spiele mit höherer Geschwindigkeit laufen oder **das** Ladebildschirme länger`   

`deaktiviert/aktiviert` => `ein- und ausgeschaltet` oder `de-/aktiviert`    

Remove cause of sentence is hard to read and i dont see a ryu devs recommending it. `Wir empfehlen, dies zu tun, wenn das Vorhaben besteht, es zu deaktivieren.`, grammatikalisch richtig aber unnötig an dieser Stelle. Bei unsicherheit an reicht.

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "FileAccessLogTooltip": "Druckt FS-Zugriff-Logs in der Konsole.",
Suggestion `Ausgabe von *-Logs in der Konsole...`

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "DebugLogTooltip": "Druckt Debug-Protokollmeldungen in der Konsole.\n\nVerwenden Sie diese Option nur auf ausdrückliche Anweisung eines Mitarbeiters von Ryujinx, da sie das Lesen der Protokolle ers
Standarize like above, `Ausgabe von Debug-Log...`

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "GameListContextMenuOpenSdModsDirectoryToolTip": "Öffnet das alternative SD-Karten-Atmosphere-Verzeichnis, das die Mods der Anwendung enthält. Nützlich für Mods, die für echte Hardware verpackt sin
`verpackt` better `vorbereitet, archiviert, erstellt,...`

2022-07-31 07:46 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "UpdateWindowTitle": "Verwalte Spiel-Updates",
Its more applicable to put the verb to the end in german
`DLC Dateien auswählen`, `Update Dateien auswählen`, `Benutzerprofile verwalten` etc.

2022-07-31 18:24 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "DockModeToggleTooltip": "Im gedockten Modus verhält sich das emulierte System wie eine gedockte Nintendo Switch. Dies verbessert die grafische Qualität der meisten Spiele. Umgekehrt führt die Deak
You marked the word `docked` in this string and I'm not sure where the word `Controller` appears
If you'd prefer a better translation for that part, how about:

English:
> Configure player 1 controls if planning to use docked mode;

German:
`Konfiguriere die Steruerung von Spieler 1 um im Docked Modus zu spielen;`

I'm on purpose not translating the `planning to play` part bc otherwise it would have been said twice in one string which does not sound nice imo.

2022-07-31 18:32 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "VSyncToggleTooltip": "Vertikale Synchronisierung der emulierten Konsole. Im Wesentlichen ist diese Option ein Frame-Limiter für die meisten Spiele; die Deaktivierung kann dazu führen, dass Spiele
So you basically you want the string to be:

"Vertikale Synchronisierung der emulierten Konsole. Im Wesentlichen ist diese Option ein Frame-Limiter für die meisten Spiele; die Deaktivierung kann dazu führen, dass Spiele mit höherer Geschwindigkeit laufen oder dass Ladebildschirme länger benötigen oder hängen bleiben.\n\nKann im Spiel mit einem frei wählbaren Hotkey ein- und ausgeschaltet werden.\n\nAN lassen, wenn unsicherheiten bestehen."

the 2nd does without a comma looks wrong tbh (not required bc of the `oder` afaik) [correct me if I'm wrong]

2022-07-31 18:42 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "DockModeToggleTooltip": "Im gedockten Modus verhält sich das emulierte System wie eine gedockte Nintendo Switch. Dies verbessert die grafische Qualität der meisten Spiele. Umgekehrt führt die Deak
`Kontrollerprofil` is in text, so i suggest Controllerprofil

But this is nice to from you `Konfiguriere die Steuerung von Spieler 1 um im Docked Modus zu spielen;` or `den Controller...`, or as its not the controller which must be configured, its the input `Konfiguriere die(das) Eingabe(gerät) für Spieler 1`.

2022-07-31 18:43 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "VSyncToggleTooltip": "Vertikale Synchronisierung der emulierten Konsole. Im Wesentlichen ist diese Option ein Frame-Limiter für die meisten Spiele; die Deaktivierung kann dazu führen, dass Spiele
u r right, remove the 2nd dass


`
"Vertikale Synchronisierung der emulierten Konsole. Im Wesentlichen ist diese Option ein Frame-Limiter für die meisten Spiele; die Deaktivierung kann dazu führen, dass Spiele mit höherer Geschwindigkeit laufen oder Ladebildschirme länger benötigen oder hängen bleiben.\n\nKann im Spiel mit einem frei wählbaren Hotkey ein- und ausgeschaltet werden.\n\nAN lassen, wenn unsicherheiten bestehen."
`

2022-07-31 18:44 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "VSyncToggleTooltip": "Vertikale Synchronisierung der emulierten Konsole. Im Wesentlichen ist diese Option ein Frame-Limiter für die meisten Spiele; die Deaktivierung kann dazu führen, dass Spiele
Die **U**nsicherheiten

2022-07-31 18:46 UTC, Niwu34 commented
Thank you for your review - Translating German sometimes can be a little annoying so any help is appreciated!

I changed all the wording issues locally and left 2 comments for the stuff that you noted (I'm not super sure if I understood them correctly)
Will push the changes asa you respond @reloxx13

2022-07-31 18:51 UTC, reloxx13 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "DockModeToggleTooltip": "Im gedockten Modus verhält sich das emulierte System wie eine gedockte Nintendo Switch. Dies verbessert die grafische Qualität der meisten Spiele. Umgekehrt führt die Deak
I found a easier and shorter sentence, maybe ull like this one

`"Im gedockten Modus verhält sich das emulierte System wie eine gedockte Nintendo Switch. Dies verbessert die grafische Qualität der meisten Spiele. Umgekehrt führt die Deaktivierung dazu, dass sich das emulierte System wie eine Nintendo Switch im Handheld Modus verhält, was die Grafikqualität beeinträchtigt.\n\nKonfiguriere das Eingabegerät von Spieler 1 um zwischen Docked und Handheld Modus zu wechseln.\n\nAN lassen, wenn unsicherheiten bestehen."`

2022-07-31 18:57 UTC, reloxx13 commented
> Thank you for your review - Translating German sometimes can be a little annoying so any help is appreciated!
> 
> I changed all the wording issues locally and left 2 comments for the stuff that you noted (I'm not super sure if I understood them correctly) Will push the changes asa you respond @reloxx13
> 
> (edit sry forgot to refresh - you are fast haha)

Yeah, german can be hard sometimes and im not perfect, too ;) . Thank you very much again for your work. I hope we can see a translation tool like weblate (free for open source projects) in the future @gdkchan @nijel

2022-07-31 18:58 UTC, Niwu34 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "DockModeToggleTooltip": "Im gedockten Modus verhält sich das emulierte System wie eine gedockte Nintendo Switch. Dies verbessert die grafische Qualität der meisten Spiele. Umgekehrt führt die Deak
Sry but I don't think that combining those two sentences like this makes sense - it sounds like:
player one enabled: docked mode
player one disabled: handheld mode

I think I'll just leave it seperated like this - this makes more sense and is closer to the original english string:
`"Im gedockten Modus verhält sich das emulierte System wie eine gedockte Nintendo Switch. Dies verbessert die grafische Qualität der meisten Spiele. Umgekehrt führt die Deaktivierung dazu, dass sich das emulierte System wie eine Nintendo Switch im Handheld Modus verhält, was die Grafikqualität beeinträchtigt.\n\nKonfiguriere das Eingabegerät für Spieler 1, um im Docked Modus zu spielen; konfiguriere das Controllerprofil via der Handheld Option, wenn geplant wird den Handheld Modus zu nutzen.\n\nAN lassen, wenn unsicherheiten bestehen."`

2022-07-31 19:25 UTC, reloxx13 approved these changes
🥇

2022-07-31 19:27 UTC, reloxx13 approved these changes

2022-08-01 07:11 UTC, Thog approved these changes

2022-08-01 08:51 UTC, reloxx13 approved these changes

2022-08-01 20:43 UTC, Niwu34 commented
Currently still working on more changes with a group of German guys (unsure how to draft this PR tho) - pls don't merge yet

2022-08-02 00:41 UTC, jonker130 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
> +  "PptcToggleTooltip": "Speichert übersetzte JIT-Funktionen, so dass jene nicht jedes Mal übersetzt werden müssen, wenn das Spiel geladen wird.\n\nVerringert Stottern und beschleunigt die Bootzeiten
I think it should be "sodass", not "so dass". Also, maybe change "Bootzeiten" to something else, like"Boot-Dauer"  (still sounds a bit weird).

2022-08-02 00:50 UTC, jonker130 commented on Ryujinx.Ava/Assets/Locales/de_DE.json
>    "DialogUpdaterFlatpakNotSupportedMessage": "Bitte Aktualisiere Ryujinx mit FlatHub",
"aktualisiere" (shouldn't be in capital)

2022-08-02 17:22 UTC, Niwu34 commented
~~Hopefully~~ Done now - I also added the strings from #3483 (prevents having to open another PR for that in the future if it this PR gets merged beforehand)

2022-08-26 04:56 UTC, reloxx13 approved these changes

2022-08-26 04:58 UTC, reloxx13 commented
Those were old comments, i dont know why it re-wrote it. Ignore them.

2022-08-26 17:31 UTC, AcK77 approved these changes

2022-08-26 17:49 UTC, merged