Allow to start Ryujinx in wayland environment
Ryujinx/Ryujinx pull request #3516
Opened 2022-08-01 06:20 UTC by albfan

Allows to start Ryujinx in wayland environment, ignoring code to retrieve monitor dimensions

relates #2714

2022-08-01 06:46 UTC, Thog requested changes

2022-08-01 06:46 UTC, Thog commented on Ryujinx/Ui/MainWindow.cs
> +	    try {
Alignment is off for the whole block

Isn't there a better way to check we are running under Wayland here? that is too hacky for me.

2022-08-01 10:33 UTC, MGThePro commented
One thing to note is that SDL2 still defaults to x11 for now. It was defaulting to wayland for some time but was reversed temporarily a few months ago because there were still a few issues. When setting SDL to wayland however (with the environment variable `SDL_VIDEODRIVER=wayland`) it crashes at startup with this error:

```
Unhandled exception. System.Exception: SDL2 initlaization failed with error "wayland not available"
   at Ryujinx.SDL2.Common.SDL2Driver.Initialize() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.SDL2.Common/SDL2Driver.cs:line 69
   at Ryujinx.Input.SDL2.SDL2GamepadDriver..ctor() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx.Input.SDL2/SDL2GamepadDriver.cs:line 23
   at Ryujinx.Ui.MainWindow..ctor(Builder builder) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 292
   at Ryujinx.Ui.MainWindow..ctor() in /home/runner/work/Ryujinx/Ryujinx/Ryujinx/Ui/MainWindow.cs:line 143
   at Ryujinx.Program.Main(String[] args) in /home/runner/work/Ryujinx/Ryujinx/Ryujinx/Program.cs:line 195
[1]    20990 IOT instruction (core dumped)  ./Ryujinx
```
SDL running with the x11 video driver could maybe also have something to do with Ryujinx crashing when trying to start emulation

2022-08-01 10:37 UTC, Thog commented
> EDIT: Nevermind that last part, that's probably due to the lack of EGL support in SPB

 One major limitation in supporting Wayland is GTK atm
I have pulled some work for EGL in SPB **but gtk 3 doesn't expose any APIs to access any EGL instances**

2022-08-01 10:38 UTC, Thog commented on Ryujinx/Ui/MainWindow.cs
> +	    try {
Still not fully addressed.

the catch block should be inline as following
``catch (NullReferenceException) { }``

And my comment still stand, **isn't there any better way?**

2022-08-01 11:45 UTC, albfan commented
@Thog I know few to nothing about SDL2, just trying to avoid a not significant check (monitor display) To me, Ryujinx should start maximized or redimension depending on preferred size, not try to match a monitor size out of nowhere (1280x760)

I remove all the usages of this size (preferred size for about, settings and manage user profiles) and all these dialogs looks the same for me.

A first window with an icon "select your game directory" or "No games loaded", or a resize if games are already present to match the listrows requested size should work.

I think that could be a better way.

I tried this samples:

https://jan.newmarch.name/Wayland/SDL/

and x11 or wayland works:

```
SDL_VIDEODRIVER=x11 ./window 
SDL_VIDEODRIVER=wayland ./window 
```

to check:

```
SDL_VIDEODRIVER=wrongdriver ./window 
SDL could not initialize! SDL_Error: wrongdriver not available
```

So I think at least to show a window there's something to do at Ryujinx code base

2022-08-01 16:15 UTC, gdkchan commented on Ryujinx/Ui/MainWindow.cs
> +	    try {
I think its better to just check if `Display` (or whatever can be null there) is null directly rather than catching the `NullReferenceException`.

2022-08-01 19:27 UTC, albfan commented on Ryujinx/Ui/MainWindow.cs
> +	    try {
Yes that makes sense. Will rework that

2022-08-02 01:30 UTC, albfan commented
Context for this null on wayland https://gitlab.gnome.org/GNOME/gtk/-/issues/1028

2022-08-02 01:43 UTC, albfan commented
@Thog indeed there was a cleaner and simpler way to fix this

2022-08-02 02:50 UTC, albfan commented
Starting an emulation:

```
00:00:01.816 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1

(Ryujinx:9978): GLib-GObject-WARNING **: 04:30:17.625: invalid cast from 'GdkWaylandDisplay' to 'GdkX11Display'

(Ryujinx:9978): Gdk-WARNING **: 04:30:17.626: ../gdk/x11/gdkwindow-x11.c:5653 drawable is not a native X11 window
00:00:01.846 |E| Application : Unhandled exception caught: System.NotImplementedException: Framebuffer configuration couldn't be selected and fallback not implemented!
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 49
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 36
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

I tried a Q&D replace but fail on GLXWindow:

```
diff --git i/Ryujinx/Ui/GLRenderer.cs w/Ryujinx/Ui/GLRenderer.cs
index 55baaa12..62226935 100644
--- i/Ryujinx/Ui/GLRenderer.cs
+++ w/Ryujinx/Ui/GLRenderer.cs
@@ -67,8 +67,8 @@ namespace Ryujinx.Ui
             }
             else if (OperatingSystem.IsLinux())
             {
-                IntPtr displayHandle = gdk_x11_display_get_xdisplay(Display.Handle);
-                IntPtr windowHandle = gdk_x11_window_get_xid(Window.Handle);
+                IntPtr displayHandle = gdk_wayland_display_get_wl_display(Display.Handle);
+                IntPtr windowHandle = gdk_wayland_window_get_wl_surface(Window.Handle);
 
                 return new GLXWindow(new NativeHandle(displayHandle), new NativeHandle(windowHandle));
             }
@@ -85,6 +85,12 @@ namespace Ryujinx.Ui
         [DllImport("libgdk-3.so.0")]
         private static extern IntPtr gdk_x11_window_get_xid(IntPtr gdkWindow);
 
+        [DllImport("libgdk-3.so.0")]
+        private static extern IntPtr gdk_wayland_display_get_wl_display(IntPtr gdkDisplay);
+
+        [DllImport("libgdk-3.so.0")]
+        private static extern IntPtr gdk_wayland_window_get_wl_surface(IntPtr gdkWindow);
+
         private static FramebufferFormat GetGraphicsMode()
         {
             return Environment.OSVersion.Platform == PlatformID.Unix ? new FramebufferFormat(new ColorFormat(8, 8, 8, 0), 16, 0, ColorFormat.Zero, 0, 2, false) : FramebufferFormat.Default;
```

Errors is:

```
00:00:01.743 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
00:00:01.768 |E| Application : Unhandled exception caught: System.NotImplementedException: Framebuffer configuration couldn't be selected and fallback not implemented!
   at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 49
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 36
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

I have to test Vulkan with nvidia drivers, on intel gpu it fails with a coredump

2022-08-15 08:01 UTC, Thog commented
> Starting an OpenGL emulation:
> 
> ```
> 00:00:01.816 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
> 
> (Ryujinx:9978): GLib-GObject-WARNING **: 04:30:17.625: invalid cast from 'GdkWaylandDisplay' to 'GdkX11Display'
> 
> (Ryujinx:9978): Gdk-WARNING **: 04:30:17.626: ../gdk/x11/gdkwindow-x11.c:5653 drawable is not a native X11 window
> 00:00:01.846 |E| Application : Unhandled exception caught: System.NotImplementedException: Framebuffer configuration couldn't be selected and fallback not implemented!
>    at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
>    at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 49
>    at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 36
>    at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
> ```
> 
> I tried a Q&D replace but fail on GLXWindow:
> 
> ```
> diff --git i/Ryujinx/Ui/GLRenderer.cs w/Ryujinx/Ui/GLRenderer.cs
> index 55baaa12..62226935 100644
> --- i/Ryujinx/Ui/GLRenderer.cs
> +++ w/Ryujinx/Ui/GLRenderer.cs
> @@ -67,8 +67,8 @@ namespace Ryujinx.Ui
>              }
>              else if (OperatingSystem.IsLinux())
>              {
> -                IntPtr displayHandle = gdk_x11_display_get_xdisplay(Display.Handle);
> -                IntPtr windowHandle = gdk_x11_window_get_xid(Window.Handle);
> +                IntPtr displayHandle = gdk_wayland_display_get_wl_display(Display.Handle);
> +                IntPtr windowHandle = gdk_wayland_window_get_wl_surface(Window.Handle);
>  
>                  return new GLXWindow(new NativeHandle(displayHandle), new NativeHandle(windowHandle));
>              }
> @@ -85,6 +85,12 @@ namespace Ryujinx.Ui
>          [DllImport("libgdk-3.so.0")]
>          private static extern IntPtr gdk_x11_window_get_xid(IntPtr gdkWindow);
>  
> +        [DllImport("libgdk-3.so.0")]
> +        private static extern IntPtr gdk_wayland_display_get_wl_display(IntPtr gdkDisplay);
> +
> +        [DllImport("libgdk-3.so.0")]
> +        private static extern IntPtr gdk_wayland_window_get_wl_surface(IntPtr gdkWindow);
> +
>          private static FramebufferFormat GetGraphicsMode()
>          {
>              return Environment.OSVersion.Platform == PlatformID.Unix ? new FramebufferFormat(new ColorFormat(8, 8, 8, 0), 16, 0, ColorFormat.Zero, 0, 2, false) : FramebufferFormat.Default;
> ```
> 
> Errors is:
> 
> ```
> 00:00:01.743 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
> 00:00:01.768 |E| Application : Unhandled exception caught: System.NotImplementedException: Framebuffer configuration couldn't be selected and fallback not implemented!
>    at SPB.Platform.GLX.GLXOpenGLContext.Initialize(NativeWindowBase window)
>    at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 49
>    at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in /home/alberto/projects/csharp/Ryujinx/Ryujinx/Ui/GLRenderer.cs:line 36
>    at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
> ```
> 
> I have to test Vulkan with nvidia drivers, on intel gpu it fails with a coredump

Interesting! ``gdk_wayland_display_get_wl_display`` and ``gdk_wayland_window_get_wl_surface`` are also available with gtk3?

I suppose I will have to take a look into integrating that 👍

2022-08-15 08:03 UTC, Thog approved these changes

2022-08-15 18:47 UTC, albfan commented
There's a lot happening on gtk relates with wayland support.

I can only think on @matthiasclasen to resolve doubts about that

2022-11-17 00:33 UTC, TSRBerry approved these changes
Just tested this and it works fine! Lgtm!

2022-11-17 12:02 UTC, merged

2022-11-17 12:27 UTC, amayra commented
why there no gtk4 csharp yet ?

2022-11-17 12:53 UTC, marysaka commented
> why there no gtk4 csharp yet ?

Even if bindings were present. it would require rewriting all UI code to not use Glade.
We are aiming to migrate to Avalonia in the future.