feat: package main release as appimage on GNU Linux platform
Ryujinx/Ryujinx pull request #3590
Opened 2022-08-15 01:05 UTC by cat-master21

This PR aims to package Ryujinx as an appimage so some dependencies can be lowered on GNU Linux. Currently Yuzu already does this.

Some things that need to be done:

- [X] Create intial things
- [ ] complete AppImageBuilder.yml
- [ ] Make sure it all works (basicly test it all)

2022-08-15 07:43 UTC, Thog requested changes

2022-08-15 07:43 UTC, Thog commented on .github/workflows/release.yml
> +      - uses: actions/setup-dotnet@v2.1.0
This should be done in a separate PR.

Also I don't like precise version pinning here, please prefer v2 here for example.

2022-08-15 07:43 UTC, Thog commented on .github/workflows/release.yml
> +        uses: ncipollo/release-action@v1.10.0
This should be done in a separate PR.

Also I don't like precise version pinning here, please prefer v1 here for example. (so no changes)

2022-08-15 07:43 UTC, Thog commented on .github/workflows/release.yml
> +          cd ./publish
Should be separated from that step.

2022-08-15 07:43 UTC, Thog commented on .github/workflows/release.yml
> +          args: "--skip-test"
We have a reduced amount of allowed actions on the org.

I'm not a fan of 1) docker based actions 2) the fact it refer to the master branch.

Please prefer on host installation.


```suggestion
      - name: Packing AppImage (Linux)
        run: |
         sudo pip3 install appimage-builder==1.0.0
         appimage-builder --recipe AppImageBuilder.yml --skip-test
        shell: bash
```

2022-08-15 07:43 UTC, Thog commented on .github/workflows/release.yml
> +         # Most users won't need this and these are mainly for debug so not packaging as an appimage
This **shouldn't be commented**.

This will remain the main way to install Ryujinx on Linux.

2022-08-15 07:43 UTC, Thog commented on AppImageBuilder.yml
> +        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x871920D1991BC93C'
1) We don't support i386, no need of this arch here
2) You shouldn't pack version as recent as Ubuntu 22.04 **as we support Ubuntu 18.04 as a minimal requirement**

2022-08-15 07:43 UTC, Thog commented on AppImageBuilder.yml
> +    arch: [ x86_64, i386 ]
Same comment as before i386 isn't supported.

2022-08-15 07:43 UTC, Thog commented on AppImageBuilder.yml
> +    version: 1.1
The version should be changed dynamically here.

2022-08-15 07:43 UTC, Thog commented on AppImageBuilder.yml
> +version: 1
This doesn't seems to account for the updater?

If you need to disable it, some changes need to happens on it.

2022-08-15 14:22 UTC, cat-master21 commented on .github/workflows/release.yml
> +          args: "--skip-test"
Yeah I didn't want to use this either. Unfortunately appimages cannot be built in windows or WSL.

2022-08-15 15:08 UTC, cat-master21 commented on AppImageBuilder.yml
> +    version: 1.1
I have sed run in one of the previous steps along with all the other sed commands to change this on [line 49](https://github.com/Ryujinx/Ryujinx/blob/c828def3f0a120aabb55bf1705309ae6eaa7f86b/.github/workflows/release.yml#L49) in release.yml

2022-08-15 23:06 UTC, cat-master21 commented on .github/workflows/release.yml
> +         # Most users won't need this and these are mainly for debug so not packaging as an appimage
Meaning that AppImages will be or just without appimages? Either way I will remove the comment.

2022-08-15 23:19 UTC, cat-master21 commented
@Thog can I change the runner to `ubuntu-latest`? I wish to do this because WSL does not support building AppImages because of libfuse. I just don't know if you would not want to do that.

2022-08-15 23:28 UTC, cat-master21 commented on AppImageBuilder.yml
> +    version: 1.1
Also I don't think it is possible for it to be "dynamic" so it uses `sed` as it does to update other components as explained in previous comment.

2022-08-15 23:32 UTC, cat-master21 commented on AppImageBuilder.yml
> +version: 1
I think this version number is used for what AppImage specification and/or appimage-builder version.

2022-08-15 23:34 UTC, cat-master21 commented on AppImageBuilder.yml
> +version: 1
I think [line 21](https://github.com/cat-master21/Ryujinx/blob/0382356d43b94d73ccd711c5742a423f2da525be/AppImageBuilder.yml#L21) is what your looking for. But `sed` in release.yml updates this just like the rest of the components.

2022-08-16 00:12 UTC, cat-master21 commented
Something cool that I think could be done is packaging a newer version of mesa considering older Linux distrobutions package old ones https://appimage-builder.readthedocs.io/en/latest/advanced/helpers.html#libgl

2022-08-17 07:12 UTC, Thog commented
> @Thog can I change the runner to `ubuntu-latest`? I wish to do this because WSL does not support building AppImages because of libfuse. I just don't know if you would not want to do that.

Impossible at present. building the Windows release require Windows because of broken packaging since .NET Core 3.1 I think (the icon of the executable is missing for example)

I'm not a huge fan of splitting every build in its own workflow because that imply more lost time for release.
Maybe the appimage could be generated in a job depending on the release one?

2022-08-17 07:15 UTC, Thog commented on .github/workflows/release.yml
> +         # Most users won't need this and these are mainly for debug so not packaging as an appimage
The tar compressed version will be the default and official way by default.
That's also to avoid breaking compat for older installation.

2022-08-17 07:16 UTC, Thog commented on AppImageBuilder.yml
> +version: 1
The real issue is that I don't think the updater in the current state will be able to update appimage builds.
We handle tar/zip manually

2022-08-18 16:10 UTC, qurious-pixel commented
@cat-master21 how did you handle the logs folder being created and crashing the appimage?

2022-08-18 17:51 UTC, cat-master21 commented
@qurious-pixel I built the appimage manually and it failed on the header compatibility check no matter what I did. But I will try your suggestion👍.

2022-08-22 00:19 UTC, cat-master21 commented
So @qurious-pixel mkappimage works and removes the issue with building without FUSE. I can't really debug the error because this is an issue with dotnet itself. Output: 
```
bash-5.1$ /home/pumkinking/Downloads/Ryujinx-0d889ad-x86_64.AppImage
Failure processing application bundle.
Bundle header version compatibility check failed. Header version: 18875693.69800449
A fatal error occured while processing application bundle
bash-5.1$
```
I think this may have to do with appimage-builder modifying magic bytes and patching to make it run from a specific PATH and what not I guess. For now all I want to include is `libx11.so` and possibly mesa soon enough.

2022-08-22 00:31 UTC, qurious-pixel commented
> I think this may have to do with appimage-builder modifying magic bytes and patching to make it run from a specific PATH and what not I guess. For now all I want to include is `libx11.so` and possibly mesa soon enough.

Make sure you check the exclude list <https://github.com/appimage-packages/AppImages/blob/master/excludelist>
Sometimes adding a lib will greatly expand the dependencies required for bundling. 

I keep the libs from the publish folder together, and everything else in `./usr/lib`

2022-08-27 18:41 UTC, cat-master21 commented
S a issue with the appimage is 1. it can't boot because Ryujinx requires logs to be created in the Ryujinx folder, and 2. this has issues with Ryujinx's updater.

2022-08-27 23:49 UTC, cat-master21 commented
I think I will close this because 1. Ryujinx doesn't any dependencies 2. can't really happen 3. does not seem to provide any benefits really.

2022-08-27 23:49 UTC, closed without merging