Add Support for Post Processing Effects
Ryujinx/Ryujinx pull request #3616
Opened 2022-08-22 12:03 UTC by emmauss

Adds post processing effects using shaders.
Currently only FXAA and SMAA shaders are supported.
2x No AA
![2-no-fxaa](https://user-images.githubusercontent.com/5307160/185916590-fd88a1e6-7117-413b-a96f-4a91d86204db.png)

2x FXAA
![2-fxaa](https://user-images.githubusercontent.com/5307160/185916582-d8e4f491-ae76-4884-bda4-6338a6f6de85.png)

Fixes #2729 as scaling can be done in post processing

2022-08-22 12:06 UTC, emmauss commented
Effects are run using compute shaders, which may incur a performance cost on high resolution targets depending on the gpu.

2022-08-22 13:06 UTC, GamerzHell9137 commented
Guess this isn't a real time change option? Kirby Buffet goes back screen when the options are being changed to FXAA or any of the SMAA options while the game is running. Also what's the different btw the SMAA options?

2022-08-22 13:16 UTC, GamerzHell9137 commented
Seems like the issue above is related to OpenGL and not Vulkan.
Also seems like on OpenGL its not working properly (or at all?)
And it seems like some 2D UI elements have issues with it

x2 Native, AF x16, SMAA Ultra

![image](https://user-images.githubusercontent.com/2002038/185930013-40d96643-717d-4260-a2ca-b64f68904474.png)

x2 Native, AF x16, None
![image](https://user-images.githubusercontent.com/2002038/185930165-90e58066-1931-4c51-bcdf-93f9363365cf.png)

Another thing i've realized is that when SMAA is chosen and when you leave the settings, going back to them defaults it to FXAA.

2022-08-22 14:44 UTC, emmauss commented
> Seems like the issue above is related to OpenGL and not Vulkan. Also seems like on OpenGL its not working properly (or at all?) And it seems like some 2D UI elements have issues with it
> 
> Vulkan, x2 Native, AF x16, SMAA Ultra
> 
> ![image](https://user-images.githubusercontent.com/2002038/185930013-40d96643-717d-4260-a2ca-b64f68904474.png)
> 
> Vulkan, x2 Native, AF x16, None ![image](https://user-images.githubusercontent.com/2002038/185930165-90e58066-1931-4c51-bcdf-93f9363365cf.png)
> 
> OpenGL, x2 Native, AF x16, SMAA Ultra
> 
> ![image](https://user-images.githubusercontent.com/2002038/185930987-8e3834b3-7c17-4b4d-8cb7-aaf5498630cb.png)
> 
> OpenGL, x2 Native, AFx16, None
> 
> ![image](https://user-images.githubusercontent.com/2002038/185931184-cc57c933-c80d-4aab-8f3a-2dc8164f9fb0.png)
> 
> Another thing i've realized is that when SMAA is chosen and when you leave the settings, going back to them defaults it to FXAA.

Effect should now update when you save settings during game play. Effects don't change when to switch the setting, only when you apply/save.

2022-08-22 21:07 UTC, GamerzHell9137 commented
Bayonetta games are black screened when enabling post processing 
![image](https://user-images.githubusercontent.com/2002038/186019253-4ba31c8e-a233-4592-83e8-be1051b0afa6.png)

2022-08-22 21:15 UTC, GamerzHell9137 commented
Bayonetta 1 on OpenGL is same, RGBA issues and whatever this is
![image](https://user-images.githubusercontent.com/2002038/186020417-478a8d31-0bea-485d-807b-d43fb7f19562.png)
![image](https://user-images.githubusercontent.com/2002038/186020423-558d6601-2deb-402a-9168-182a9daa5350.png)
![image](https://user-images.githubusercontent.com/2002038/186020432-06bda98e-4a07-48c8-b324-9cb81d82f1b8.png)


and on Vulkan its black screen

2022-08-23 18:09 UTC, GamerzHell9137 commented
Bayonetta 2 with FSR on OpenGL crash

```00:00:17.768 |I| Configuration LogValueChange: UpscaleType set to: Fsr
00:00:17.907 |E| GUI.RenderLoop Application : Unhandled exception caught: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\home\nhv3\personal\Ryujinx\Ryujinx.Ava\bin\Debug\shader.glsl'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Ryujinx.Graphics.OpenGL.Effects.FsrUpscaler.Initialize() in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx.Graphics.OpenGL\Effects\FsrUpscaler.cs:line 67
   at Ryujinx.Graphics.OpenGL.Window.UpdateEffect() in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx.Graphics.OpenGL\Window.cs:line 413
   at Ryujinx.Graphics.OpenGL.Window.CopyTextureToFrameBufferRGB(Int32 drawFramebuffer, Int32 readFramebuffer, TextureView view, ImageCrop crop, Action`1 swapBuffersCallback) in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx.Graphics.OpenGL\Window.cs:line 109
   at Ryujinx.Graphics.OpenGL.Window.Present(ITexture texture, ImageCrop crop, Action`1 swapBuffersCallback) in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx.Graphics.OpenGL\Window.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_30(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 120
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 130
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\Users\Gamestation\Desktop\FSR\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 426```

2022-08-23 23:30 UTC, MutantAura commented
Bilinear and Nearest seem to work really well 👍 

BL: 
![image](https://user-images.githubusercontent.com/44103205/186283584-456fb4af-e1eb-42bb-bb81-889e6c617806.png)

Nearest:
![image](https://user-images.githubusercontent.com/44103205/186283641-71223d1a-9396-4eb5-8f56-8e47082d6012.png)

FSR seems to be scaling variably beyond the window size based on the slider. I don't think this is correctly tied to the sharpen value yet.

FSR 0.3:
![image](https://user-images.githubusercontent.com/44103205/186283759-60171ac1-389b-4127-9d40-a42104609355.png)

FSR 1.0:
![image](https://user-images.githubusercontent.com/44103205/186283787-8ba7dae8-1a23-4821-89f1-fc923560eba6.png)

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Ava/AppHost.cs
> +            _renderer?.Window?.ApplyScaler((Graphics.GAL.UpscaleType)ConfigurationState.Instance.Graphics.UpscaleType.Value);
Why all those null checks? Some of those can never be null.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "GraphicsAATooltip" :  "Applies anti-aliasing to the game render",
```suggestion
  "GraphicsAATooltip": "Applies anti-aliasing to the game render",
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "GraphicsAATooltip" :  "Applies anti-aliasing to the game render",
Same for all the ones below.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Ava/AppHost.cs
> +            _renderer?.Window?.ApplyScaler((Graphics.GAL.UpscaleType)ConfigurationState.Instance.Graphics.UpscaleType.Value);
Same for the ones below.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +        public bool IsUpscalingActive => _upscaleType == 2;
Why 2? Can't the enum be used here rather than a raw int so that we can clearly see what the value means?

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
> +                                        <TextBlock Text="SMAA Low" />
Should those be localizable? The quality presets is something that can be translated.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Common/Configuration/AntiAliasing.cs
> +﻿using System;
Those usings can be removed.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.GAL/AntiAliasing.cs
> +﻿using System;
Those usings can be removed.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.GAL/Multithreading/ThreadedWindow.cs
> +        public void ApplyScaler(UpscaleType scalerType) { }
Would be nice to have consistent naming here. This method calls it "Scaler" but the one below calls it "Upscaler". Also some methods are called "Change", others "Apply", others "Set", would be nice to settle with some consistent naming here too.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.GAL/Multithreading/ThreadedWindow.cs
> +        public void ApplyScaler(UpscaleType scalerType) { }
Personally I'd prefer if they were all prefixed with "Set".

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FsrUpscaler.cs
> +            get => _scale; set
```suggestion
            get => _scale;
            set
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FsrUpscaler.cs
> +                var log = GL.GetShaderInfoLog(shader);
It doesn't do anything with `log`.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FsrUpscaler.cs
> +                var log = GL.GetProgramInfoLog(_scalingShaderProgram);
Same for the ones below, I will stop commenting.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FsrUpscaler.cs
> +                var log = GL.GetProgramInfoLog(_scalingShaderProgram);
Also this code pattern is repeated a lot, I think it should be moved to a helper function to avoid all that repetition.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FsrUpscaler.cs
> +	        int threadGroupWorkRegionDim = 16;
Misaligned.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FsrUpscaler.cs
> +            GL.BindImageTexture(0, 0, 0, false, 0, TextureAccess.ReadWrite, SizedInternalFormat.Rgba8);
Should this not restore the previous image? I had to do something like that on #3596 so maybe it will help here.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/IPostProcessingEffect.cs
> +        protected const int LocalGroupSize = 64;
No need for access modifiers in interfaces (so you can remove protected and internal).

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/IScaler.cs
> +        protected void Initialize();
```suggestion
        void Initialize();
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/Smaa/SmaaPostProcessingEffect.cs
> +            _edgeShaderPrograms = new int[0];
You can use `Array.Empty<int>()`, it's a bit more efficient.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/Smaa/SmaaPostProcessingEffect.cs
> +                GL.ShaderSource(shader, 2, shaders, (int*)IntPtr.Zero);
IIRC you can avoid unsafe code by doing `(byte[])null` (or was it `(string)null`?).

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/Smaa/SmaaPostProcessingEffect.cs
> +
Double empty line.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/Smaa/SmaaPostProcessingEffect.cs
> +            GL.BindImageTexture(0, 0, 0, false, 0, TextureAccess.ReadWrite, SizedInternalFormat.Rgba8);
This also does not restore the previous image.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/Smaa/SmaaPostProcessingEffect.cs
> +
Same.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Shaders/fsr_sharpening.glsl
> +    CurrFilter(gxy);
Looks like indentation is off on those shaders. Would be nice to run some auto-formatting on them.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +
Empty line.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                        _antiAliasing = null;
No need to set it to null here.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                    case AntiAliasing.SmaaLow:
I think the logic for SMAA can be simplified if you group the cases for all quality presets, then inside you can add a switch expression to get the quality level integer from the enum, and use that.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FXAAPostProcessingEffect.cs
> +        private int _inputUniform;
Also unused.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FXAAPostProcessingEffect.cs
> +            );
Please move `);` to the line above.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FXAAPostProcessingEffect.cs
> +            _shaderProgram = _renderer.CreateProgramWithMinimalLayout(new[]{
```suggestion
            _shaderProgram = _renderer.CreateProgramWithMinimalLayout(new[]
            {
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            get => _sharpeningLevel; set
```suggestion
            get => _sharpeningLevel;
            set
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            var computeBindings = new ShaderBindings(
Same comments as before.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            _scalingPipeline?.Initialize();
Those can never be null, you just instantiated them right above.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            get => _quality; internal set
No need for the internal set when the class is already internal I guess?

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            _edgeProgram = _renderer.CreateProgramWithMinimalLayout(new[]{
Same for the ones below.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/ImageWindow.cs
> +                view = _antiAliasing?.Run(view, cbs, _width, _height);
You already checks for null above.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Shader.cs
> +            if (_shaderSpecializationInfo != null && this._shaderSpecializationInfo != null)
This is confusing, aren't both checking the same field?

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/ShaderSpecializationInfo.cs
> +        public IReadOnlyCollection<SpecializationEntry> Entries{ get; }
```suggestion
        public IReadOnlyCollection<SpecializationEntry> Entries { get; }
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/ShaderSpecializationInfo.cs
> +        public NativeArray<byte> Data{ get; }
```suggestion
        public NativeArray<byte> Data { get; }
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/ShaderSpecializationInfo.cs
> +            Data?.Dispose();
`Data` can't be null.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/ShaderSpecializationInfo.cs
> +        public uint Size{ get; }
```suggestion
        public uint Size { get; }
```

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/ShaderSpecializationInfo.cs
> +        public uint Size{ get; }
Also properties are usually at the top, not the bottom on this project.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
> +                view = _effect?.Run(view, cbs, _width, _height);
Can't be null.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
> +                _currentEffect = effect;
What's the point of updating it here if they are equal?

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
> +
Empty line.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
> +                _currentScaler = scalerType;
Same comment as before.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
> +                    case AntiAliasing.Fxaa:
I think I have seen this same code at least 2 times already. Would be nice to move it to a common function rather than copy/pasting it in multiple places.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        /// Applies a shader effect to the renderer.
Those descriptions doesn't match the ones on `ConfigurationState`.

2022-09-19 19:00 UTC, gdkchan commented on Ryujinx/Ui/RendererWidgetBase.cs
> +            Renderer.Window.ApplyScaler((Graphics.GAL.UpscaleType)ConfigurationState.Instance.Graphics.UpscaleType.Value);
Can you add `using Ryujinx.Graphics.GAL` to avoid having to fully qualify the type here?

2022-09-19 20:55 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/ImageWindow.cs
> +                view = _antiAliasing?.Run(view, cbs, _width, _height);
Window is removed now.

2022-09-19 21:22 UTC, emmauss commented
Rebased. FSR doesn't currently work on Opengl because the window framebuffer can't be used as an image for compute

2022-09-19 21:34 UTC, gdkchan commented
A `SettingsWindow.axaml.txt` file was added which I believe might have been a mistake.

2022-09-19 21:43 UTC, emmauss commented
> A `SettingsWindow.axaml.txt` file was added which I believe might have been a mistake.

It's removed.

2022-10-03 09:30 UTC, emmauss commented
Rebased

2022-10-28 20:35 UTC, GhostofReachCashGrab commented
can this be updated with master please

2022-10-29 01:37 UTC, AcK77 requested changes
Just a review of the code:
- You use a bunch of `var` maybe it could be nice to use explicit cast sometimes.
- When you compile some shaders, you store the result in `var log` but you don’t use the `log` var.
- You store some shaders in a binary form directly in the code, with a link of a gist as comment, it’s a bit strange.

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +        private float upscaleLevel;
```suggestion
        private float _upscaleLevel;
```

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +            get => upscaleLevel; set
The set shouldn’t be on a new line?

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Ava/Ui/ViewModels/SettingsViewModel.cs
> +            get => _upscaleType; set
The set shouldn’t be on a new line?

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
> +    <Grid HorizontalAlignment="Stretch"
I think all formatting changes in this file could be reverted as they are not useful

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Common/Configuration/AntiAliasing.cs
> +        SmaaUltra,
```suggestion
        SmaaUltra
```

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Common/Configuration/UpscaleType.cs
> +        Fsr,
```suggestion
        Fsr
```

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.GAL/AntiAliasing.cs
> +        SmaaUltra,
```suggestion
        SmaaUltra
```

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.GAL/IWindow.cs
> +        void SetUpscalerLevel(float level);
It’s a bit strange to have `scalerType` in the previous method and just `level` in this one

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.GAL/Multithreading/ThreadedWindow.cs
> +        public void SetUpscalerLevel(float level) { }
It’s a bit strange to have `scalerType` in the previous method and just `level` in this one

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/FXAAPostProcessingEffect.cs
> +            Initialize();
Add a new empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/FXAAPostProcessingEffect.cs
> +                return;
Add a new empty line before

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/FXAAPostProcessingEffect.cs
> +                return;
Add a new empty line before

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/FXAAPostProcessingEffect.cs
> +            }
Add a new empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/FXAAPostProcessingEffect.cs
> +            }
Add a new empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/FsrUpscaler.cs
> +            Initialize();
Add a new empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/IScaler.cs
> +
Remove extra empty line

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +                    return;
Add empty line before

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +                }
Add empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +                    return;
Add empty line before and same for all following conditions

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +                }
Add empty line after, and same for all following conditions

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +
Remove extra empty line

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +
Remove extra empty line

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                return;
Add new line before

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                return;
Add new line before

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.OpenGL/Window.cs
> +
Remove extra empty line

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.Vulkan/Effects/FXAAPostProcessingEffect.cs
> +            _pipeline = new PipelineHelperShader(renderer, device);
Add new empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.Vulkan/Effects/FXAAPostProcessingShader.cs
> +        // https://gist.github.com/emmauss/185fb0b5abf5f61537b0b46060b855ce
What if the gist is removed/deleted one day?

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            _renderer = renderer;
New empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            _quality = quality;
New empty line after

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.Vulkan/Window.cs
> +
Remove extra empty line

2022-10-29 01:37 UTC, AcK77 commented on Ryujinx.Graphics.Vulkan/WindowBase.cs
> +
Remove empty lines between methods

2022-10-29 19:36 UTC, s32303 approved these changes

2022-10-29 20:34 UTC, emmauss commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
> +    <Grid HorizontalAlignment="Stretch"
They help with locating and updating properties. They are not useless.

2022-11-15 17:30 UTC, riperiperi reviewed
Quick testing review.

Just a general thing on the fragment -> compute shader conversions: Fragment shaders generally get gl_FragCoord with an offset to the center of the pixel, so that they sample in the middle. This means you should add 0.5 to your integer pixel coordinate. Of course, the shader can explicitly change this, but I don't think any of your source shaders do. I've only commented on the Vulkan shaders, _but this applies to both._

I think the FXAA shader that's included is awfully blurry. ~~I'm not sure if this is intentional on the shader's part, but I would expect it to be sharper with the caveat of failing to anti-alias more edges. I think it is improved slightly by correcting the frag coord.~~ It is fixed by adding the 0.5 offset to the frag coord.

The SMAA shader was broken on both Vulkan and OpenGL when I tested. One of the main issues is that the area texture contains garbage data due to the file path being wrong - I've commented where the error is in both backends. After this and the frag_coord offset fix, SMAA looks great.

On Vulkan, SMAA has a notable CPU cost. This honestly might be my own fault though - IdList is throwing ArgumentOutOfRange when rebinding the (null) index buffer, which is very much less than optimal. I'll fix this separately.

FSR+SMAA when fixed appears to work great. I'll post a comparison screenshot below.

Just a small note on helper shader compilation if you're using shaderc, make sure you're also using `options.Optimization = OptimizationLevel.Performance;`, as it might be able to optimize the result SPIR-V.

I'll look into the PR further later on. I haven't checked much of the code.

2022-11-15 17:32 UTC, riperiperi commented
Ignore performance, these are in debug build.

4K 1x SMAA only:
![smaaonly](https://user-images.githubusercontent.com/6294155/201987050-b32ffb4d-765e-4f3a-842a-329df479835f.png)

4K 1x SMAA with FSR (mystery option set at 1.0):
![smaafsr](https://user-images.githubusercontent.com/6294155/201987233-63982056-cbb1-47fe-a233-a74f91a400d1.png)

2022-11-15 17:34 UTC, riperiperi commented
Native res SMAA:
![image](https://user-images.githubusercontent.com/6294155/201987693-a800e0e0-4a45-402f-be09-b3ab900b90a7.png)

2022-11-15 17:37 UTC, riperiperi commented
It looks like all of FXAA's issues are the 0.5 pixel offset, too. Making the change locally here makes it a lot sharper:

Native res FXAA:
![image](https://user-images.githubusercontent.com/6294155/201988195-8719a371-0aae-46de-a859-525bc0c47171.png)

2022-11-17 22:23 UTC, SomeoneIsWorking commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
> +    <Grid HorizontalAlignment="Stretch"
I'm not a member but I wanted to chime in and I agree with @AcK77 
When I review a PR, I only expect to see changes that are specifically related to the goal of the PR.
- Code outside of the scope of the PR is modified.
- Formatting changes isn't the goal of the PR or help this PR in any way.

2022-11-19 07:42 UTC, emmauss commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
> +    <Grid HorizontalAlignment="Stretch"
It's updated now.

2022-11-20 20:02 UTC, MutantAura commented
FXAA and SMAA are both much less blurry 👍 

FSR on Vulkan still has major artifacting on some Nvidia cards, possibly Ampere only? (doesn't happen on Pascal at least).

Vulkan: 
![image](https://user-images.githubusercontent.com/44103205/202923468-b80076f5-7e73-471c-bd82-3c5e15dfc729.png)

OpenGL:
![image](https://user-images.githubusercontent.com/44103205/202923512-5b83cd36-b247-4bce-b606-17da42846522.png)

2022-11-25 02:06 UTC, veploxmine123 commented
FSR slider doesn't work.

2022-11-25 02:16 UTC, veploxmine123 commented
![image](https://user-images.githubusercontent.com/85697813/203886874-33335a4d-1be7-406f-86ec-0b27a8555641.png)

2022-11-25 07:40 UTC, emmauss commented
> FSR slider doesn't work.

Do you know what the slider is even for?

2022-11-25 07:58 UTC, veploxmine123 commented
Setting slider to higher it makes it less sharper. But now setting the slider to anything doesn't change anything.

2022-11-25 09:29 UTC, GamerzHell9137 commented
@veploxmine123 what's your GPU?

2022-11-25 12:29 UTC, veploxmine123 commented
The latest commit fixes the slider and now it works

2022-12-06 16:18 UTC, veploxmine123 commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
> +                                        <TextBlock Text="{locale:Locale SettingsTabLoggingOpenglLogLevelNone}" />
![image](https://user-images.githubusercontent.com/85697813/205965475-cc604094-b7a3-4ed6-8894-5c1a7371f0aa.png)

2022-12-06 16:22 UTC, emmauss commented on Ryujinx.Ava/Ui/Windows/SettingsWindow.axaml
> +                                        <TextBlock Text="{locale:Locale SettingsTabLoggingOpenglLogLevelNone}" />
It is, and it isn't. The key for that has been updated in master to a different key, but the branch hasn't been rebased, so it's using the old key.

2022-12-17 12:36 UTC, jojodunet commented
Will the post-processing effect settings (for example for FXAA or MSAA) match with the GFX cheats? #4134

2022-12-17 13:19 UTC, MutantAura commented
> Will the post processing effects settings and values (example for FXAA, MSAA, Bilinear, Nearest, …) match with the GFX cheats? #4134

What do you mean? The changes here are adding support for post-processing filters to the emulator. Cheats or mods will usually do this within the game engine, not the final image output.

2022-12-21 01:27 UTC, jojodunet commented
The arguments for the commande line of the Headless build here of the PR 3616 are missing.
Could you please add them in the next rebased Headless build?

I'm referring at those arguments for example:
--anti-aliasing SmaaUltra
--upscale-type Fsr
--upscale-level 0.3
.
.
etc...

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/DescriptorSetUpdater.cs
> +                return;
We're not doing that anymore, if the image is null it should set the binding to null.

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            var scalingShader = EmbeddedResources.Read("Ryujinx.Graphics.Vulkan/Shaders/fsr_scaling.spirv");
Not saying that this is bad, but we're not using embedded resources for the other SPIR-V shaders right now. Maybe we should, would be nice to make it consistent. But that can be done on a separate PR.

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +                var info = new TextureCreateInfo(width,
```suggestion
                var info = new TextureCreateInfo(
                    width,
```

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            var dimensionsBuffer = new ReadOnlySpan<float>(new float[]
You can use stackalloc here to avoid the heap allocation.

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            var sharpeningBuffer = new ReadOnlySpan<float>(new float[] { Level });
It doesn't look like this was addressed, but I'd just change it to stackalloc.

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +        private PipelineHelperShader _scalingPipeline;
Why does this need 2 separate pipelines?

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs
> +        public void Initialize()
This is called from the constructor. Does it really need to be public?

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs
> +            _pipeline?.Dispose();
Some of those can never be null, so the null check is not necessary.

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs
> +            var resolutionBuffer = new ReadOnlySpan<float>(new float[] { view.Width, view.Height });
stackalloc

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs
> +                (view.Width + IPostProcessingEffect.LocalGroupSize - 1) / IPostProcessingEffect.LocalGroupSize,
DivRoundUp

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +                );
Move to the line above.

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +                );
Move to the line above.

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            var dispatchX = (view.Width + IPostProcessingEffect.LocalGroupSize - 1) / IPostProcessingEffect.LocalGroupSize;
DivRoundUp

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            var resolutionBuffer = new ReadOnlySpan<float>(new float[] { view.Width, view.Height });
stackalloc

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +                PipelineStageFlags.PipelineStageComputeShaderBit,
```suggestion
                PipelineStageFlags.ComputeShaderBit,
```

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +        public unsafe void ComputeBarrier()
Can you use the span overloads to avoid the unsafe context?

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +                PipelineStageFlags.PipelineStageAllCommandsBit,
```suggestion
                PipelineStageFlags.AllCommandsBit,
```

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
> +                _upscaler.Run(view,
```suggestion
                _upscaler.Run(
                    view,
```

2022-12-26 01:23 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
>                  _gd,
Looksl ike this is not indented properly.

2022-12-26 08:03 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Effects/FxaaPostProcessingEffect.cs
> +                _textureStorage.CreateDefaultView();
The texture view returned is disposed after it's blitted. If the default view is returned instead, the storage will be disposed and I would have to create one every frame.

2022-12-26 08:08 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +            var areaTexture = EmbeddedResources.Read("Ryujinx.Graphics.OpenGL/Effects/Textures/smaa_area_texture");
they are raw pixel data. I don't know what format to give them. .bin? .bmp?

2022-12-26 08:22 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Shaders/fxaa.glsl
> +vec3 FxaaPixelShader( vec4 uv, sampler2D tex, vec2 rcpFrame) {
VS doesn't have a formatter for glsl

2022-12-26 09:57 UTC, emmauss commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                    crop.FlipX,
as fsr does not flip the image, as it only cares about the bounds and not if the image is mirrored, I have to translate the coords manually when storing the scaled pixels. The flip can be detected in shader so we can remove these.

2022-12-26 10:03 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            var scalingShader = EmbeddedResources.Read("Ryujinx.Graphics.Vulkan/Shaders/fsr_scaling.spirv");
I found updating the shaders to be much easier with embedded resources.

2022-12-26 10:12 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +        private PipelineHelperShader _scalingPipeline;
Scaling and Sharpening are done in 2 separate passes. I couldn't find any way to have multiple compute shaders in one pipeline, where one shader must run before the other

2022-12-26 10:29 UTC, emmauss commented
Addressed @gdkchan reviews

2022-12-26 17:02 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +        private PipelineHelperShader _scalingPipeline;
You can just call `SetProgram` to set the new program and do the next dispatch.

2022-12-26 17:23 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +            var areaTexture = EmbeddedResources.Read("Ryujinx.Graphics.OpenGL/Effects/Textures/smaa_area_texture");
Raw data should have `.bin` extension.

2022-12-26 17:26 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +            var areaTexture = EmbeddedResources.Read("Ryujinx.Graphics.OpenGL/Effects/Textures/smaa_area_texture");
Also I noticed those files are repeated on both Vulkan and OpenGL backends. Seems a bit wasteful.

2022-12-26 18:05 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                viewConverted = _antiAliasing.Run(viewConverted, _width, _height);
If the previous `viewConverted` is a bgr texture, then it won't be disposed. You should dispose the old value of `viewConverted` if it's not equal to view.

2022-12-26 18:22 UTC, GamerzHell9137 commented
Here's my findings

Issue with Pokemon Arceus (SV did this too) that made FSR broken on 3000 series cards was fixed. The 2D elements were broken once it was enabled and also the UI was shifted couple of pixels, now its not happening.

Before:
![image](https://user-images.githubusercontent.com/2002038/209574593-e87c93fa-6baf-4829-9bbc-6017b93183c0.png)

After:
![image](https://user-images.githubusercontent.com/2002038/209574597-8cce474a-e44d-4d31-8491-2b95d16920fc.png)

Bayonetta games are still broken on Vulkan, once FSR or any filter is enabled the screen goes black.
On OpenGL when FSR is enabled on Bayonetta 2 the game is shifted for 1 pixel from below and adding a black pixel line at the bottom.

FSR :
![image](https://user-images.githubusercontent.com/2002038/209574840-913e6b41-7b47-4bee-adcd-e2e061825785.png)

Bilinear:

![image](https://user-images.githubusercontent.com/2002038/209574866-95194161-8e69-4689-b1fd-46eefffd1e92.png)

(Zoom in to see the black pixel line on the last pixel line of the image on the FSR image)

Another OpenGL issue with Bayonetta 2 is that the VRAM usage starts climbing until the GPU driver crashes when any of the filters are enabled. (Peri commented about it above which i guess is if the fix for it)

Blue Reflections 2 (There's a Demo for it) shifts one pixel from below too like Bayonetta 2 does.

Testing more games to see if anything's wrong but so far so good, no regressions, gonna update it i do see some.

2022-12-28 01:38 UTC, GamerzHell9137 commented
Seems like the pixel shift that's happening in games is only happening on OpenGL right now, Vulkan is fine. Its happening on all games.

2022-12-29 10:07 UTC, emmauss commented
The off by 1 pixel and memory leak should be fixed now

2023-01-09 21:19 UTC, emmauss commented
rebased

2023-01-17 01:16 UTC, Foul-Tarnished commented
Can you add bicubic ?

2023-01-19 15:14 UTC, GamerzHell9137 commented
Persona 5 Royal too blackscreens when PP is enabled on OpenGL. Mayhaps games from older gens trigger the issues so probably any of old ports will show the black screen.

2023-01-19 15:49 UTC, GamerzHell9137 commented
Correction about the blackscreen OpenGL issue, its happening on all games on OpenGL. 
![image](https://user-images.githubusercontent.com/2002038/213488449-d695fc2c-7d12-4cd1-b9f7-02ce614c014f.png)

State about Bayonetta, Bayonetta 2 and Skyward Sword and still valid tho, also why those are not blackscreening on OpenGL is unknown.

2023-01-20 09:38 UTC, GamerzHell9137 commented
OpenGL issues have been fixed and Skyward Sword pixel shift is fixed too.
Only RGB issues in Bayonetta games is what's left.
Another games that do the same are Persona 3 Portable and Persona 4.

Weird enough a combination of FSR with any of the PP filters negates the RBG values mixup but choosing only one of them triggers it.

![image](https://user-images.githubusercontent.com/2002038/213663689-2780ff76-8e23-4904-a037-5e5ff2cbfa3f.png)

![image](https://user-images.githubusercontent.com/2002038/213663595-06f33eb0-c982-48c0-b0f0-ea974fd2a11c.png)

![image](https://user-images.githubusercontent.com/2002038/213663559-d956ae4f-0f04-4977-8667-a267f8e875b9.png)

2023-01-21 10:33 UTC, emmauss commented on Ryujinx.Ava/AppHost.cs
> +            ConfigurationState.Instance.Graphics.UpscaleLevel.Event += UpdateUpscaleLevel;
The aim of that value is to allow some amount of adjustment for the upscaler, not just for FSR, even if only FSR uses it. If more upscalers were added in future, it being call Sharpening level would make less sense,

2023-01-27 18:24 UTC, IsaacMarovitz requested changes

2023-01-27 18:24 UTC, IsaacMarovitz commented on Ryujinx/Ui/Windows/SettingsWindow.glade
> +    <property name="upper">1.5</property>
Upper bound of `GtkAdjustment` restricts to `upper - page-size`, this value should be `1.6`

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Common/Configuration/UpscaleType.cs
> +    public enum UpscaleType
I'd call that `ScalingFilter`.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.GAL/IWindow.cs
> +        void SetAntiAliasing(AntiAliasing antialiasing);
I don't think the empty line between those methods is necessary since they are related.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.GAL/IWindow.cs
> +        void SetUpscaler(UpscaleType type);
If `UpscaleType` is renamed to `ScalingFilter`, I think those methods should be renamed too.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FxaaPostProcessingEffect.cs
> +using OpenTK.Mathematics;
This was never addressed. It can be removed.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/FxaaPostProcessingEffect.cs
> +using System;
Can be removed too.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/IScaler.cs
> +            int srcX0,
Maybe it could take `Extents2D` struct instead of passing all those integer parameters?

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Effects/SmaaPostProcessingEffect.cs
> +            var areaTexture = EmbeddedResources.Read("Ryujinx.Graphics.OpenGL/Effects/Textures/smaa_area_texture");
This was never addressed either. Also maybe it's worth renaming to match the naming we have been using for other files. For example, it could be called `SmaaAreaTexture.bin`. But I think calling it `smaa_area_texture.bin` is fine too.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj
> +    <None Remove="Effects\Textures\smaa_area_texture" />
What is the purpose of specifying those files here in addition to the `EmbeddedResource` ones?

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                viewConverted = _antiAliasing.Run(viewConverted, _width, _height);
Was that addressed?

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +        private PipelineHelperShader _scalingPipeline;
This was not addressed.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            if (_intermediaryTexture == null || _intermediaryTexture.Info.Width != width || _intermediaryTexture.Info.Height != height && !_intermediaryTexture.Info.Equals(view.Info))
Line is too long.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrUpscaler.cs
> +            if (_intermediaryTexture == null || _intermediaryTexture.Info.Width != width || _intermediaryTexture.Info.Height != height && !_intermediaryTexture.Info.Equals(view.Info))
Also mixing `||` and `&&` without parenthesis is rather confusing.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs
> +using System.IO;
Remove using.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs
> +                if(view.Info.Format.IsBgr())
```suggestion
                if (view.Info.Format.IsBgr())
```

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FxaaPostProcessingEffect.cs
> +            scissors[0] = new Rectangle<int>(0, 0, view.Width, view.Height);
Can't this do a inline stackalloc line you did for `SetUniformBuffers` above?

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +using System.IO;
Remove usings.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            _renderer.HelperShader.Clear(_renderer,
Note that this uses a different pipeline for the clear.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            ReadOnlySpan<float> resolutionBuffer =stackalloc float[] { view.Width, view.Height };
```suggestion
            ReadOnlySpan<float> resolutionBuffer = stackalloc float[] { view.Width, view.Height };
```

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            _edgePipeline.ComputeBarrier();
You never call `Finish()` in any of the pipelines.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +        private PipelineHelperShader _edgePipeline;
As I mentioned before, I think this should use just one pipeline. I'm not sure why you need 3. The way how they work is that draws/dispatch etc will use the state up to the point where the call was made. If you change the state after that, it will only affect subsequent operations, not previous one. If it's not behaving like this, then it's a bug.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Shaders/SMAA_neighbour.glsl
> +#version 430 core
SMAA is upper case on the file name, which is inconsistent with the other SMAA shaders.
BTW about those shaders:
- I think they should be on a separate folder since they are not exactly the same as the shaders the emulator uses internally to fill in missing API functionality.
- Maybe they should be renamed to match the naming used on the other shaders.
- SPIR-V binary shaders should use `spv` extension not `spirv`.

2023-02-10 22:32 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/WindowBase.cs
>          public abstract void ChangeVSyncMode(bool vsyncEnabled);
This should probably be renamed to `SetVSyncMode` for consistency with the other methods.

2023-02-13 16:47 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            _edgePipeline.ComputeBarrier();
They are compute pipelines. There's no renderpass to end.

2023-02-13 16:51 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +        private PipelineHelperShader _edgePipeline;
The shaders are compute shaders. Pipelines are limited to only 1 compute shader.

2023-02-13 16:59 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/WindowBase.cs
>          public abstract void ChangeVSyncMode(bool vsyncEnabled);
I don't think that's related. I can still change it if you want.

2023-02-13 17:00 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/WindowBase.cs
>          public abstract void ChangeVSyncMode(bool vsyncEnabled);
Yea it's not directly related to this change, I think it would be nice to change it for consistency, but it doesn't need to be done on this PR.

2023-02-13 17:01 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +        private PipelineHelperShader _edgePipeline;
Where does this limitation comes from? I'm not aware of it.

2023-02-13 17:02 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +            _edgePipeline.ComputeBarrier();
Right, but I think it's still good practice, because if we add more logic to the `Finish` method that needs to run when the pipeline is "done" with, we don't need to update this code to call it (or forget to update the code and introduce bugs).

2023-02-13 17:32 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/Effects/SmaaPostProcessingEffect.cs
> +        private PipelineHelperShader _edgePipeline;
I've replaced them with 1 pipeline, same with fsr.

2023-02-13 18:53 UTC, gdkchan reviewed
nit:
I think it would be better if the scaling options were moved below the resolution scale, like this:
![image](https://user-images.githubusercontent.com/5624669/218548235-225935a0-ee53-43ce-b048-46d8c19dddd2.png)
Since they are related.

Also iirc we had a few users confused with the FSR slider, because lower means more sharpening, when they expect the opposite. Is there some specific reason for it working like this currently? Is that what other software does?

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Ava/AppHost.cs
> +            ConfigurationState.Instance.Graphics.ScalingFilterLevel.Event        += UpdateScalingFilterLevel;
Misaligned.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Ava/AppHost.cs
> +            ConfigurationState.Instance.Graphics.ScalingFilter.Event         -= UpdateScalingFilter;
Misaligned.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Ryujinx.Graphics.OpenGL.csproj
> +    <EmbeddedResource Include="Shaders\fsr_sharpening.glsl" />
IMO it would be better if you moved the shaders folder inside the effects folder.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Graphics.OpenGL/Window.cs
> +                if(viewConverted != oldView && oldView != view)
```suggestion
                if (viewConverted != oldView && oldView != view)
```

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrScalingFIlter.cs
> +    internal partial class FsrScalingFIlter : IScalingFilter
```suggestion
    internal partial class FsrScalingFilter : IScalingFilter
```

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/PipelineBase.cs
> +
```suggestion
```

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Window.cs
> +                    new Extents2D(
`new Extents2D(srcX0, srcY0, srcX1, srcY1),`
Same for the one below.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                ScalingFilter                = Graphics.ScalingFilter,
Misaligned.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            Graphics.ScalingFilter.Value                = ScalingFilter.Bilinear;
Misaligned.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            Graphics.ScalingFilter.Value                = configurationFileFormat.ScalingFilter;
Misaligned.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            _scalingFilterLevel.Value                  = ConfigurationState.Instance.Graphics.ScalingFilterLevel.Value;
Misaligned.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            _scalingFilterSlider.Visible               = _scalingFilter.ActiveId == "2";
Misaligned.

2023-02-13 18:53 UTC, gdkchan commented on Ryujinx/Ui/Windows/SettingsWindow.cs
> +            ConfigurationState.Instance.Graphics.ScalingFilter.Value                = Enum.Parse<ScalingFilter>(_scalingFilter.ActiveId);
Misaligned.

2023-02-13 18:57 UTC, gdkchan commented on Ryujinx.Graphics.Vulkan/Effects/FsrScalingFIlter.cs
> +    internal partial class FsrScalingFIlter : IScalingFilter
The file will also need to be renamed.

2023-02-19 02:16 UTC, gdkchan approved these changes
lgtm, except for this issue which remains:
![image](https://user-images.githubusercontent.com/5624669/219908533-a77c0e30-c094-4687-b871-144f6fbf1497.png)
(Weird gap between the controls when selecting FSR).
Also I'm not sure if the FSR slider is working.

2023-02-19 08:08 UTC, emmauss commented
> lgtm, except for this issue which remains: ![image](https://user-images.githubusercontent.com/5624669/219908533-a77c0e30-c094-4687-b871-144f6fbf1497.png) (Weird gap between the controls when selecting FSR). Also I'm not sure if the FSR slider is working.

fixed

2023-02-26 16:43 UTC, riperiperi approved these changes
Things are looking good now. I can't verify myself if the BGRA issues are fixed, but it looks like they are appropriately handled.

2023-02-26 16:43 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/Effects/Shaders/smaa_blend.glsl
> +            imageStore(imgOutput,  texelCoord, oColor);
```suggestion
            imageStore(imgOutput, texelCoord, oColor);
```

2023-02-26 16:43 UTC, riperiperi commented on Ryujinx.Graphics.OpenGL/Effects/Shaders/smaa_neighbour.glsl
> +            vec4 oColor  = SMAANeighborhoodBlendingPS(coord, offset, inputTexture, samplerBlend);
```suggestion
            vec4 oColor = SMAANeighborhoodBlendingPS(coord, offset, inputTexture, samplerBlend);
```

2023-02-26 16:43 UTC, riperiperi commented on Ryujinx.Graphics.Vulkan/Effects/Shaders/Fxaa.glsl
> +
Double new line?

2023-02-26 18:31 UTC, emmauss commented on Ryujinx.Graphics.Vulkan/Effects/Shaders/Fxaa.glsl
> +
File has now been changed.

2023-02-27 21:11 UTC, merged