Bsd: Fix NullReferenceException in BsdSockAddr.FromIPEndPoint()
Ryujinx/Ryujinx pull request #3652
Opened 2022-08-31 11:43 UTC by TSRBerry

This PR adds another check to prevent games from crashing with guest internet access enabled.

@EmulationFanatic sent me a log of "Victor Vran Overkill Edition" crashing on boot because a NullReferenceException was thrown inside of `BsdSockAddr.FromIPEndPoint()`. 
Following the stack trace I found a missing check for `socket.RemoteEndPoint` to ensure it's not null.

With this change "Victor Vran Overkill Edition" boots with guest internet access enabled, although it will still deadlock shortly after, but that's a different issue.

Thanks to @EmulationFanatic for confirming my fix works so quickly!

2022-08-31 11:47 UTC, Thog requested changes

2022-08-31 11:47 UTC, Thog commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> -            if (socket != null)
I do believe that if ``RemoteEndPoint`` is null we should return ``ENOTCONN`` as per standard [getpeername(2)](https://man7.org/linux/man-pages/man2/getpeername.2.html)

2022-08-31 11:48 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> -            if (socket != null)
That makes sense, will add that shortly!

2022-08-31 11:55 UTC, Thog approved these changes

2022-08-31 19:20 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +
```suggestion

```

2022-09-01 20:59 UTC, riperiperi commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +
Did it remove this empty line entirely? The next line is showing as 570 now.

2022-09-01 21:08 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +
I just clicked on 'commit suggestion' since I'm currently not home, which makes everything involving git a little bit harder :D

2022-09-01 22:03 UTC, AcK77 approved these changes

2022-09-01 22:04 UTC, merged