Avalonia - Fixes updater
Ryujinx/Ryujinx pull request #3670
Opened 2022-09-04 09:09 UTC by emmauss

Fixes updater on the avalonia ui. It was incomplete previously. The window has also been replaced for a task dialog.

2022-09-07 06:54 UTC, Narugakuruga commented
The en_US.json locales changelog is unreadable. Could you make the spacings like original?

2022-09-07 20:11 UTC, gdkchan commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +                    string ryuName = OperatingSystem.IsWindows() ? "Ryujinx.Ava.exe" : "Ryujinx.Ava";
Is there no way to get the currently running executable name? It would be less fragile than the current approach I think. This code will break if we change the executable name as is.

2022-09-07 20:11 UTC, gdkchan commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +                    string ryuArg = string.Join(" ", Environment.GetCommandLineArgs().AsEnumerable().Skip(1).ToArray());
If the first arg that is skipped here is the executable name, it seems like it could be a replacement for the code above.

2022-09-07 20:11 UTC, gdkchan commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +                    string ryuArg = string.Join(" ", Environment.GetCommandLineArgs().AsEnumerable().Skip(1).ToArray());
Also not sure why `AsEnumerable()` is needed since arrays should be enumerable already.

2022-09-07 20:11 UTC, gdkchan commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +        private static void DoUpdateWithSingleThread(TaskDialog taskDIalog, string downloadUrl, string updateFile)
```suggestion
        private static void DoUpdateWithSingleThread(TaskDialog taskDialog, string downloadUrl, string updateFile)
```

2022-09-07 20:11 UTC, gdkchan commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +                            taskDialog.SetProgressBarState((double)byteWritten / totalBytes * 100, TaskDialogProgressState.Normal);
Would be nice to move this logic to calculate the percentage into a small static helper function. It should probably also handle the case where `totalBytes` is zero to avoid a division by zero. Same for the other functions with similar code, but if you use the helper function on all of them, then they should be all handled properly.

2022-09-07 20:11 UTC, gdkchan commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        chmod(ryuExe, 0777);
We had a problem with this before because the value 777 is supposed to be octal. But here it is decimal, I believe it is wrong.

2022-09-08 14:16 UTC, emmauss commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        chmod(ryuExe, 0777);
Doesn't a 0 prefix make a numeric literal octal?

2022-09-08 17:42 UTC, gdkchan approved these changes
lgtm, thanks.

2022-09-26 22:16 UTC, LunaDook commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "RyujinxUpdaterMessage": "Do you want to update Ryujinx to the latest version?"
You forgot a comma here, the current build made by github actions crashes because of it.

2022-09-26 22:18 UTC, LunaDook requested changes
The current GA build is broken, easy fix:

2022-09-26 22:18 UTC, LunaDook commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "RyujinxUpdaterMessage": "Do you want to update Ryujinx to the latest version?"
You forgot a comma here.

2022-09-26 23:21 UTC, emmauss commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "RyujinxUpdaterMessage": "Do you want to update Ryujinx to the latest version?"
Thanks

2022-09-26 23:41 UTC, LunaDook approved these changes

2022-10-02 09:05 UTC, marysaka approved these changes
lgtm

2022-10-03 07:40 UTC, emmauss commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +    <PackageReference Include="Avalonia" Version="0.10.18" />
It's been reverted.

2022-10-03 14:25 UTC, merged