Manage state of NfcManager
Ryujinx/Ryujinx pull request #3678
Opened 2022-09-06 21:48 UTC by Ninban

Very basic state management but works with Hyrule Warriors Definitive Edition. Partially fixes #2122.

An evolution since that issue, on master, that game now asked for `Ryujinx.HLE.HOS.Services.Nfc.NfcManager.INfc: 2` to be implemented. By implementing this basic state management, the game accepts Amiibo scans through the emulator and does not crash anymore.

Should I remove the Stub prints from `Initialize` and `Finalize`? I feel like I didn't really implement anything nor did any kind of reverse engineering to figure out what is supposed to happen here, except blindly setting the state.

2022-10-11 16:00 UTC, AcK77 requested changes
`PrintStub()` should be put just before the `return`

2022-10-11 16:00 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Nfc/NfcManager/Types/State.cs
> +        Initialized    = 1
```suggestion
        NonInitialized,
        Initialized
```

2022-10-11 16:00 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Nfc/NfcManager/INfc.cs
> +        // Initialize()
```suggestion
        // Finalize()
```

2022-10-11 16:00 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Nfc/NfcManager/INfc.cs
>          {
```
// Initialize()
```
-> 
```
// Initialize(u64, u64, pid, buffer<unknown, 5>)
```

2022-10-11 16:00 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Nfc/NfcManager/INfc.cs
> +        private State _state = State.NonInitialized;
```suggestion
        private State _state;
```

and `_state = State.NonInitialized;` should be set in the class constructor.

2022-10-19 00:37 UTC, AcK77 approved these changes

2022-10-19 00:40 UTC, AcK77 commented
Lgtm! Thanks for the contribution!

2022-10-19 00:43 UTC, gdkchan approved these changes
lgtm, thanks.

2022-10-19 01:14 UTC, merged