Local Amiibo.json should be used if connection failed
Ryujinx/Ryujinx pull request #3681
Opened 2022-09-08 00:43 UTC by AxesP

Currently Ryujinx is not loading any Amiibo if connection fails, even if the Amiibo.json exists. This fix will use the local file and show a Dialog if connection fails.

2022-09-10 12:56 UTC, Thog requested changes
Some initial comments

Also the ``JsonSerializer.Deserialize`` should be checked to be valid data, there is always the possibility the json is corrupted.

2022-09-10 12:56 UTC, Thog commented on Ryujinx/Ui/Windows/AmiiboWindow.cs
> +                    return response.Content.Headers.LastModified.Value.TimeOfDay != oldLastModified.AddTicks(-oldLastModified.Ticks % TimeSpan.TicksPerSecond).TimeOfDay;
why was this changed?

2022-09-10 12:56 UTC, Thog commented on Ryujinx.Ava/Ui/ViewModels/AmiiboWindowViewModel.cs
> +                    return response.Content.Headers.LastModified?.TimeOfDay != oldLastModified.AddTicks(-oldLastModified.Ticks % TimeSpan.TicksPerSecond).TimeOfDay;
why was this changed?

2022-09-10 19:43 UTC, AxesP commented on Ryujinx/Ui/Windows/AmiiboWindow.cs
> +                    return response.Content.Headers.LastModified.Value.TimeOfDay != oldLastModified.AddTicks(-oldLastModified.Ticks % TimeSpan.TicksPerSecond).TimeOfDay;
That was changed because the LastModified header has no milliseconds on it, check https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified . And the current JSON in https://amiibo.ryujinx.org/ has milliseconds on it. That will cause an error when comparing the two dates, having the same year, month, day, hour and minutes but different milliseconds, finishing on a returning "false" when the file is the same as the one in the server. This is one possible fix. The other options are:

1. Instead of comparing the date of the header, we can download the file and get the "lastmodified" property in the JSON and comparing that with oldLastModified instead of response.Content.Headers.LastModified. (This will likely never fail).
2. Compare the date in the header with the oldLastModified but without the milliseconds on it (The change I made, it's more like a workaround than a fix).
3. Correct the date on the JSON file uploaded to https://amiibo.ryujinx.org/ and allways put 0 in the milliseconds.
Example: "2022-09-09T22:00:20.776625" is the current value, the correct one should be: "2022-09-09T22:00:20.000000".
4. Or another suggestion...

2022-09-10 19:48 UTC, AxesP commented
Thanks for reviewing the code, Thog.
Okay, I updated the JSON deserialization to be more secure. Now it will use the remote file if the local is oudated or invalid,
and if deserialization fails at one point, it will use the last file that was able to deserialize or no Amiibo if neither the local or remote are valid JSON.
 Also I was thinking if those functionalities are likely to be on another project? Like Ryujinx.Ui.Common?

2022-09-13 05:48 UTC, Thog commented
> Thanks for reviewing the code, Thog. Okay, I updated the JSON deserialization to be more secure. Now it will use the remote file if the local is oudated or invalid, and if deserialization fails at one point, it will use the last file that was able to deserialize or no Amiibo if neither the local or remote are valid JSON. Also I was thinking if those functionalities are likely to be on another project? Like Ryujinx.Ui.Common?

I think it would be nice to have it in [Ryujinx.Ui.Common](https://github.com/Ryujinx/Ryujinx/tree/master/Ryujinx.Ui.Common) to avoid duplication yeah but that can be addressed in another PR if you want

2022-09-13 05:48 UTC, Thog approved these changes

2022-09-13 21:45 UTC, AxesP commented
Sorry @Thog , requested your review again by mistake. Not an expert on GitHub pull requests!

2022-10-02 09:08 UTC, marysaka commented on Ryujinx/Ui/Windows/AmiiboWindow.cs
> +                    return response.Content.Headers.LastModified.Value.TimeOfDay != oldLastModified.AddTicks(-oldLastModified.Ticks % TimeSpan.TicksPerSecond).TimeOfDay;
> That was changed because the LastModified header has no milliseconds on it

We aren't expecting any update with a milliseconds granularity as those data are statically generated daily if any update is present in the database.

2022-10-02 09:09 UTC, marysaka commented on Ryujinx/Ui/Windows/AmiiboWindow.cs
> +                    return response.Content.Headers.LastModified.Value.TimeOfDay != oldLastModified.AddTicks(-oldLastModified.Ticks % TimeSpan.TicksPerSecond).TimeOfDay;
As such I would like that this change and [the other one](https://github.com/Ryujinx/Ryujinx/pull/3681/files/de2723e5cfa7f7962bf4d01bd78fd20e8311a8c3#r967648145) be reverted.

2022-10-02 09:10 UTC, marysaka commented
> Sorry @Thog , requested your review again by mistake. Not an expert on GitHub pull requests!

No worries, I kind of was away for the past weeks 😅

2022-10-09 23:53 UTC, AxesP commented on Ryujinx/Ui/Windows/AmiiboWindow.cs
> +                    return response.Content.Headers.LastModified.Value.TimeOfDay != oldLastModified.AddTicks(-oldLastModified.Ticks % TimeSpan.TicksPerSecond).TimeOfDay;
Okay, changes reverted.
Anyways, this problem needs more explanation by my side and since it goes beyond the goal of this pull request, maybe it should be addressed on another pull request.

2022-10-10 00:00 UTC, AxesP commented
> > Sorry @Thog , requested your review again by mistake. Not an expert on GitHub pull requests!
> 
> No worries, I kind of was away for the past weeks 😅

Me too... I'm having time to review this again after like 4 weeks.
Anyways, after reverting that date comparison thing, I think we are finally done with this pull request and I should only wait for approval to start working on moving that Amiibo code to Ryujinx.Ui.Common.

Thanks!

2022-11-16 22:34 UTC, marysaka approved these changes

2023-12-18 00:56 UTC, AcK77 requested changes

2023-12-18 00:56 UTC, AcK77 commented on Ryujinx.Ava/Ui/ViewModels/AmiiboWindowViewModel.cs
> +                return true;
```suggestion

                return true;
```

2023-12-18 00:56 UTC, AcK77 commented on Ryujinx.Ava/Ui/ViewModels/AmiiboWindowViewModel.cs
> +                return false;
```suggestion

                return false;
```

2023-12-18 00:56 UTC, AcK77 commented on Ryujinx/Ui/Windows/AmiiboWindow.cs
> +                return true;
```suggestion

                return true;
```

2023-12-18 00:56 UTC, AcK77 commented on Ryujinx/Ui/Windows/AmiiboWindow.cs
> +                return false;
```suggestion

                return false;
```

2023-12-18 00:57 UTC, AcK77 approved these changes

2023-12-18 00:57 UTC, AcK77 commented
Needs rebase

2023-12-25 04:37 UTC, AxesP commented
Rebase done.

2023-12-25 05:32 UTC, AcK77 commented
Format have to be fixed (you can look at the CI logs to known the issues)

2023-12-25 13:46 UTC, AxesP commented
@AcK77 Code reformatted.
My bad. I was trying to get Visual Studio Code to use the editorconfig but with no success...

2023-12-25 16:12 UTC, AxesP commented
@AcK77 One reference to the logging was removed in the merge by mistake, I readded the reference and ran dotnet build to double check (My bad again). The project should compile now.

2023-12-28 01:43 UTC, AcK77 approved these changes

2023-12-28 01:43 UTC, merged