Avalonia: update it_IT.json
Ryujinx/Ryujinx pull request #3742
Opened 2022-10-06 12:37 UTC by Mortus06

Updates Italian localization.

2022-10-18 19:03 UTC, AntoSkate requested changes
Era da un po' che volevo rifare la traduzione per renderla più simile al file en_US ma per adesso va bene anche sistemare quella che c'è già 👍

2022-10-18 19:03 UTC, AntoSkate commented on Ryujinx.Ava/Assets/Locales/it_IT.json
> +    "DialogInvalidTitleIdErrorMessage": "Errore UI: Il gioco selezionato non ha un titolo ID valido",
```suggestion
    "DialogInvalidTitleIdErrorMessage": "Errore UI: Il gioco selezionato non ha un ID titolo valido",
```

2022-10-18 19:05 UTC, Mortus06 commented
Sto facendo un mezzo casino da mobile, mi trasferisco su PC e correggo

2022-10-18 19:15 UTC, AntoSkate commented
Domani do un'occhiata al resto del file e vedo se ci sono altre cose da correggere 👀

2022-10-18 19:15 UTC, Mortus06 commented
Ho sistemato tutto, è incredibile GitHub sappia essere controintuitivo e beginner friendly allo stesso tempo

2022-10-18 19:19 UTC, AntoSkate commented
> Ho sistemato tutto, è incredibile quanto GitHub sappia essere controintuitivo e beginner friendly allo stesso tempo

Vero? Quando ho cominciato a usarlo non ci capivo niente lol

2022-10-19 00:07 UTC, AcK77 commented
Is everything done?

2022-10-19 05:18 UTC, Mortus06 commented
Yes, the PR is ready

2022-10-19 09:30 UTC, AcK77 approved these changes

2022-10-19 09:30 UTC, merged