infra: Migrate to .NET 7
Ryujinx/Ryujinx pull request #3795
Opened 2022-10-23 19:39 UTC by marysaka

.NET 7 is still in preview but this prepare for the release coming up next month.

I also added some checks for others platform as some warning were being issued.

2022-10-23 20:57 UTC, sakuka47 commented
Hello,

What are the changes related to the migration to net.7?

Can we now compile in net.7 for builds?

2022-10-23 21:56 UTC, LukeWarnut commented
Crashes Super Smash Bros. Ultimate, Taiko no Tatsujin: Drum 'n' Fun, Brawlhalla, The Legend of Zelda: Breath of the Wild, Bravely Default 2 Demo, and likely others.
[Taiko.log](https://github.com/Ryujinx/Ryujinx/files/9847587/Taiko.log)
[Smash.log](https://github.com/Ryujinx/Ryujinx/files/9847605/Smash.log)
[Brawlhalla.log](https://github.com/Ryujinx/Ryujinx/files/9847608/Brawlhalla.log)
```
00:00:44.559 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason)
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context)
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id)
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id)
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
```

2022-10-23 21:57 UTC, jduncanator requested changes
Just a few minor things.

I'm a little on the fence about introducing new .NET features in the same PR as migrating to .NET 7. Part of me thinks trying to keep the change set as minimal as possible in this PR would be beneficial to identify any issues caused directly by .NET 7, and then having a separate PR that introduces scoped refs and other new features. But that's just my 2c.

2022-10-23 21:57 UTC, jduncanator commented on Ryujinx.HLE/Utilities/UInt128Utils.cs
> +using System;
This entire file can probably live in Ryujinx.Common, given it now extends an intrinsic type in .NET and these helpers may be useful in other projects.

2022-10-23 21:57 UTC, jduncanator commented on Ryujinx.HLE/Utilities/UInt128Utils.cs
> +            Random random = new Random();
It's generally bad practice to use a locally defined Random instance, as multiple callers calling this function in quick succession could generate the same random number (as the Random instance uses time as a seed).

It would be better to move this to a private static instance in the helper class. Then there is only a single instance, and it's only seeded once.

2022-10-23 22:43 UTC, riperiperi commented
The scoped ref changes are not optional, Ryujinx fails to compile without them on .NET 7.

2022-10-23 23:00 UTC, riperiperi commented
FPS peak comparisons (though average is pretty close at around 1fps lower):

.NET 6:
![image](https://user-images.githubusercontent.com/6294155/197422264-efc3291a-463b-4d10-a30b-23475badf139.png)

.NET 7:
![image](https://user-images.githubusercontent.com/6294155/197422294-dc8ea301-d153-499d-82cb-770d458df1fb.png)

Finally, the fun one. .NET 7 with `<TieredPGO>true</TieredPGO>` in `Ryujinx.csproj`:
![image](https://user-images.githubusercontent.com/6294155/197422310-1456898f-1bad-4e29-aed3-b487b48c3cd7.png)

2022-10-23 23:31 UTC, marysaka commented on Ryujinx.HLE/Utilities/UInt128Utils.cs
> +            Random random = new Random();
Technically this is only used for Mii and user id creation but I do agree.

I'm quite surprise we don't have a helper for random number generation atm

2022-10-23 23:32 UTC, turbedi commented on Ryujinx.HLE/Utilities/UInt128Utils.cs
> +            Random random = new Random();
Another alternative: [Random.Shared](https://learn.microsoft.com/en-us/dotnet/api/system.random.shared?view=net-7.0), introduced in .NET 6.
So line 15 would change to 
`return new UInt128((ulong)Random.Shared.NextInt64(), (ulong)Random.Shared.NextInt64());`
and the locally defined instance can be removed.

2022-10-23 23:35 UTC, riperiperi commented
Another healthy .NET 7 + TieredPGO improvement:

.NET 6:
![image](https://user-images.githubusercontent.com/6294155/197423691-7ff081f7-83c7-4485-80d6-97b30f4cf98a.png)

.NET 7 + TieredPGO:
![image](https://user-images.githubusercontent.com/6294155/197423701-75685b1c-107e-4aae-a785-ffd0e77d111c.png)

2022-10-23 23:39 UTC, turbedi commented on Ryujinx.HLE/Utilities/UInt128Utils.cs
> +            return new UInt128((ulong)Convert.ToInt64(hex.Substring(16), 16), (ulong)Convert.ToInt64(hex.Substring(0, 16), 16));
```suggestion
            return new UInt128((ulong)long.Parse(hex.AsSpan(16), 16), (ulong)long.Parse(hex.AsSpan(0, 16), 16));
```
Avoids the Substring allocations

2022-10-24 00:00 UTC, turbedi commented on Ryujinx.HLE/Utilities/UInt128Utils.cs
> +            return new UInt128((ulong)Convert.ToInt64(hex.Substring(16), 16), (ulong)Convert.ToInt64(hex.Substring(0, 16), 16));
Nevermind, didn't see the second parameter.

2022-10-24 13:29 UTC, marysaka commented on Ryujinx.Common/Utilities/UInt128Utils.cs
> +            return new UInt128((ulong)Convert.ToInt64(hex.Substring(16), 16), (ulong)Convert.ToInt64(hex.Substring(0, 16), 16));
MS decided it was a good idea to have upper as first argument, this is inverted.
```suggestion
            return new UInt128((ulong)Convert.ToInt64(hex.Substring(0, 16), 16), (ulong)Convert.ToInt64(hex.Substring(16), 16));
```

2022-10-24 13:29 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserId.cs
> +            return new UInt128((ulong)Low, (ulong)High);
```suggestion
            return new UInt128((ulong)High, (ulong)Low);
```

2022-10-26 08:06 UTC, marysaka commented
> Crashes Super Smash Bros. Ultimate, Taiko no Tatsujin: Drum 'n' Fun, Brawlhalla, The Legend of Zelda: Breath of the Wild, Bravely Default 2 Demo, and likely others. [Taiko.log](https://github.com/Ryujinx/Ryujinx/files/9847587/Taiko.log) [Smash.log](https://github.com/Ryujinx/Ryujinx/files/9847605/Smash.log) [Brawlhalla.log](https://github.com/Ryujinx/Ryujinx/files/9847608/Brawlhalla.log)
> 
> ```
> 00:00:44.559 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
>    at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason)
>    at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context)
>    at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id)
>    at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id)
>    at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm)
>    at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
>    at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address)
>    at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress)
>    at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
> ```

Last commit should fix Smash at least, can you retry on the other games?

2022-10-26 13:41 UTC, ayurai commented
SMO crashes on start with the game update 1.3, but runs normal without it.
[Ryujinx_1.1.0_2022-10-26_10-40-04.log](https://github.com/Ryujinx/Ryujinx/files/9870026/Ryujinx_1.1.0_2022-10-26_10-40-04.log)

2022-10-26 16:16 UTC, LukeWarnut commented
@marysaka Latest changes fix Smash, but the other games I listed now crash with a different error.

[BD2Demo.log](https://github.com/Ryujinx/Ryujinx/files/9871316/BD2Demo.log)
[Taiko.log](https://github.com/Ryujinx/Ryujinx/files/9871330/Taiko.log)
[Brawlhalla.log](https://github.com/Ryujinx/Ryujinx/files/9871332/Brawlhalla.log)
[BOTW.log](https://github.com/Ryujinx/Ryujinx/files/9871338/BOTW.log)

2022-10-26 17:48 UTC, LukeWarnut commented
Latest commit fixes the other time crashes. Great work!

<details>
  <summary>Screenshots</summary>
  
![image](https://user-images.githubusercontent.com/65521430/198094279-3d44f292-5d70-47fa-a788-63c8f98ee29f.png)
![image](https://user-images.githubusercontent.com/65521430/198098426-d55f7803-37f8-43f7-b642-4afb57a8ec46.png)
![image](https://user-images.githubusercontent.com/65521430/198098872-f1b42cc6-ff5b-4818-aa2d-dc89baeab7c1.png)
![image](https://user-images.githubusercontent.com/65521430/198099142-f05bb7cc-3b59-428b-a82a-4e2c23e1e41c.png)
![image](https://user-images.githubusercontent.com/65521430/198099336-040814a8-f63d-4fdc-9b7a-7f7d0d789165.png)
</details>

2022-11-08 17:55 UTC, gdkchan commented on Ryujinx/Ryujinx.csproj
> +    <TieredPGO>true</TieredPGO>
Why is that only enabled here and not on Avalonia and Headless?

2022-11-08 17:55 UTC, gdkchan commented on Ryujinx/Ryujinx.csproj
> +    <TrimMode>partial</TrimMode>
Why is that change required now?

2022-11-08 17:58 UTC, marysaka commented on Ryujinx/Ryujinx.csproj
> +    <TrimMode>partial</TrimMode>
.NET 7 changed the default trimming policy to "full".
WIthout it it would trim all assemblies and we aren't prepared for that as it produce a non functional build.

2022-11-08 17:59 UTC, marysaka commented on Ryujinx/Ryujinx.csproj
> +    <TieredPGO>true</TieredPGO>
It is present on avalonia and headless...?

2022-11-08 18:02 UTC, gdkchan commented on Ryujinx/Ryujinx.csproj
> +    <TrimMode>partial</TrimMode>
Maybe we should have an issue to address that in the future, I imagine we'd want to have the full trim mode working as I assume it produce smaller executables. Maybe it also overlaps with what needs to be done for NativeAOT.

2022-11-08 18:03 UTC, gdkchan approved these changes
Code changes LGTM, but I did not test with .NET 7 yet. Thanks for tackling this.

2022-11-08 18:10 UTC, marysaka commented on Ryujinx/Ryujinx.csproj
> +    <TrimMode>partial</TrimMode>
It totally overlaps with most NativeAOT requirements yeah, I think I will make try to look into that in the near future.

2022-11-08 19:13 UTC, MutantAura commented
Mario Kart 8 Deluxe crashes after the initial splash-screen.
```
00:00:10.342 |I| HLE.GuestThread.36 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x00000000009e4554	main:0x7e0554	


00:00:10.342 |I| HLE.GuestThread.36 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000003e74
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000000
	X[03]:	0x00000000fffffff8
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000e886f4
	X[09]:	0x000000007d8e3488
	X[10]:	0x000000007987ce50
	X[11]:	0x0000000002fcb360 (SP:-0x2fcb360)
	X[12]:	0x0000000079b00330
	X[13]:	0x0000000002fcb350 (SP:-0x2fcb350)
	X[14]:	0x0000000000ab3668 (main:0x8af668)	=> 
	X[15]:	0x0000000000000000
	X[16]:	0x0000000000000000
	X[17]:	0x0000000000000000
	X[18]:	0x0000000000000000
	X[19]:	0x0000000000000000
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000000000000000
	LR:	0x0000000000000000
	SP:	0x0000000000000000
	PC:	0x0000000000aafcac (main:0x8abcac)	=> 


00:00:10.342 |E| HLE.GuestThread.36 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000003000.
00:00:10.415 |E| HLE.GuestThread.36 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 275
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in C:\Users\domw0\Documents\GitHub\Ryujinx\ARMeilleure\Translation\Translator.cs:line 130
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\Users\domw0\Documents\GitHub\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   ```
  
[Ryujinx_1.0.0-dirty_2022-11-08_19-09-10.log](https://github.com/Ryujinx/Ryujinx/files/9964438/Ryujinx_1.0.0-dirty_2022-11-08_19-09-10.log)

2022-11-08 19:14 UTC, TSRBerry commented
Mario Kart 8 Deluxe v2.1.0 crashes with and without a save with this PR.
I compiled my build using .NET 7.0.100 and tried Vulkan and OpenGL, but both result in the same crash.

<details>
  <summary>crash snippet</summary>
  
  ```
  00:00:40.350 |I| HLE.GuestThread.36 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x00000000009e4554	main:0x7e0554	


00:00:40.351 |I| HLE.GuestThread.36 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000003e74
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000000
	X[03]:	0x00000000fffffff8
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000e886f4
	X[09]:	0x000000007d890eb4
	X[10]:	0x000000007987ce50
	X[11]:	0x0000000025a91360 (SP:-0x25a91360)
	X[12]:	0x0000000079b00330
	X[13]:	0x0000000025a91350 (SP:-0x25a91350)
	X[14]:	0x0000000000ab3668 (main:0x8af668)	=> 
	X[15]:	0x0000000000000000
	X[16]:	0x0000000000000000
	X[17]:	0x0000000000000000
	X[18]:	0x0000000000000000
	X[19]:	0x0000000000000000
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x0000000000000000
	LR:	0x0000000000000000
	SP:	0x0000000000000000
	PC:	0x0000000000aafcac (main:0x8abcac)	=> 


00:00:40.351 |E| HLE.GuestThread.36 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000003000.
00:00:40.359 |E| HLE.GuestThread.36 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in /mnt/Dev/git-repos/Nintendo/Ryujinx/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 275

  ```
</details>

2022-11-08 20:49 UTC, marysaka commented
Mario Kart 8 crashes related to this PR should be fixed with last commit, thanks for the report 👍

2022-11-08 21:45 UTC, LukeWarnut commented
Tested around 10 games running on various different engines. No regressions found.

2022-11-08 22:03 UTC, riperiperi approved these changes
LGTM!

2022-11-09 19:22 UTC, merged