hid/irs: Stub StopImageProcessorAsync
Ryujinx/Ryujinx pull request #3799
Opened 2022-10-25 22:46 UTC by LukeWarnut

Fixes a crash in Game Builder Garage when exiting a game using the IR Motion Camera Nodon.

Before:

https://user-images.githubusercontent.com/65521430/197896055-02fe9ea3-9d1e-44c4-88a2-d7a34f037553.mp4

After:

https://user-images.githubusercontent.com/65521430/197896114-d70a8fe9-40a5-4fc5-9229-7d7eb9e74615.mp4

2022-10-25 22:52 UTC, AcK77 requested changes

2022-10-25 22:52 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +        //StopImageProcessorAsync(nn::irsensor::IrCameraHandle, nn::applet::AppletResourceUserId, pid)
```suggestion
        // StopImageProcessorAsync(nn::irsensor::IrCameraHandle, nn::applet::AppletResourceUserId, pid)
```

2022-10-25 22:52 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Hid/Irs/IIrSensorServer.cs
> +            int irCameraHandle        = context.RequestData.ReadInt32();
```suggestion
            int  irCameraHandle        = context.RequestData.ReadInt32();
```

2022-10-27 21:31 UTC, AcK77 approved these changes

2022-10-27 21:36 UTC, marysaka approved these changes

2022-10-27 21:36 UTC, merged