SDL2Driver: Invoke dispatcher on main thread
Ryujinx/Ryujinx pull request #3818
Opened 2022-11-01 15:10 UTC by merryhime

Executes `SDL_PumpEvents` on main thread.

I note the SDL2 frontend already manually calls `SDL_PumpEvents` in its main loop.

macOS enforces the need for events pumped on the main thread.

2022-11-06 00:07 UTC, young40 approved these changes

2022-11-17 13:00 UTC, marysaka approved these changes

2022-11-17 13:12 UTC, marysaka requested changes

2022-11-17 13:12 UTC, marysaka commented on Ryujinx.SDL2.Common/SDL2Driver.cs
> +                waitHandle.Wait(WaitTime.Milliseconds);
I would actually prefer all of this to be in the MainThreadDispatcher callback.
So having the old code in the callback.

2022-11-21 22:52 UTC, merryhime commented
Stuck the poll loop onto the main thread.

2022-11-29 19:18 UTC, riperiperi reviewed
The changes look good to me, for MacOS. Does it make sense to do this on other platforms?

2022-11-30 19:12 UTC, marysaka approved these changes

2022-11-30 21:15 UTC, gdkchan approved these changes
lgtm, just not sure if we want to do that for all platforms (since this only a problem on MacOS). But not having different paths per platform is nice.

2022-12-02 13:37 UTC, EmulationFanatic commented
Tested some controller config/unplugging & replugging during runtime and while the input window was open. Everything works as it should.

2022-12-02 13:37 UTC, merged