Add friend/Cancel.
Ryujinx/Ryujinx pull request #3841
Opened 2022-11-12 03:28 UTC by WilliamWsyHK

Closes #3824

2022-11-12 03:37 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceFriend, "Cancel");
You don't need to pass "Cancel" here since it already prints the caller function name, this is meant for function arguments.

Also it should have an empty line before `return ResultCode.Success;` separating the two.

2022-11-12 03:41 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceFriend, "Cancel");
Updated.

2022-11-17 01:03 UTC, EmulationFanatic commented
With this PR, SnowRunner gets very slightly further and instead crashes with another missing service that isn't implemented: [IFriendService: 10500](https://github.com/Ryujinx/Ryujinx/issues/1575)

2022-11-17 17:26 UTC, AcK77 requested changes

2022-11-17 17:26 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceFriend);
After some RE, this sets an internal field to 1, it could be nice to add a comment in that way. If needed for further implementation.

2022-11-18 13:19 UTC, WilliamWsyHK commented on Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceFriend);
Comment added.

2022-11-19 11:58 UTC, AcK77 requested changes

2022-11-19 11:58 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/IFriendService.cs
> +            // AcK77: After some reverse-engineering, this sets an internal field to 1.
```suggestion
            // TODO: Original service sets an internal field to 1 here. Determine usage.
```

2022-11-23 13:52 UTC, AcK77 approved these changes

2022-11-23 14:26 UTC, marysaka approved these changes

2022-11-23 15:25 UTC, merged