Update to LibHac 0.17.0
Ryujinx/Ryujinx pull request #3878
Opened 2022-11-20 21:57 UTC by Thealexbarney

- Remove some leftover debug code for `CompressedStorage`
- Add key sources for system version 15.0.0
- Update save data service functionality for changes in 14.0.0
- Remove workaround that cleared the saves on the SD card when starting the emulator. Fixes #3800
- General system stability improvements to enhance the user's experience

2022-11-20 22:05 UTC, gdkchan commented
Maybe the ExtraData migration code can be removed as well? Is it still required after all this time?

2022-11-20 22:33 UTC, AcK77 requested changes

2022-11-20 22:33 UTC, AcK77 commented on Ryujinx.HLE/FileSystem/VirtualFileSystem.cs
> +            RandomDataGenerator randomGenerator = buffer => random.NextBytes(buffer);
```suggestion
            RandomDataGenerator randomGenerator = buffer => Random.Shared.NextBytes(buffer);
```

2022-11-20 22:33 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Fs/IFileSystemProxy.cs
> +        [CommandHipc(37)]
```suggestion
        [CommandHipc(37)] // 14.0.0+
```

2022-11-21 00:12 UTC, Thealexbarney commented
@gdkchan If we're thinking about the same thing, the extra data stuff is less of a migration and more trying to fix missing extra data

2022-11-21 04:29 UTC, gdkchan approved these changes
lgtm, thanks. Might be worth to get some testing to ensure this update did not break any games.

2022-11-21 21:38 UTC, AcK77 approved these changes

2022-11-23 17:32 UTC, merged