Update SChinese Transaction of Macro HLE
Ryujinx/Ryujinx pull request #3914
Opened 2022-11-27 10:49 UTC by Soulize

2022-11-27 11:11 UTC, Soulize commented
Transaction→Translation
describe→description
sorry for my poor English😶‍🌫️

2022-11-27 13:11 UTC, Soulize commented
crash(´。＿。｀)

2022-11-27 17:15 UTC, Narugakuruga requested changes
这里55行改成“删除已编译的PPTC文件“，56行补充说明”仅删除PPTC转换后的文件，下次打开游戏时将根据.info文件重新生成PPTC文件。如想彻底清除缓存，请进入目录把.info文件一并删除“

2022-11-27 17:16 UTC, Narugakuruga commented
Nicely done catching up a sorts of the English changes. only missing the pptc related changes.
Otherwise LGTM

2022-11-27 17:29 UTC, Soulize commented
> 这里55行改成“删除已编译的PPTC文件“， 56行补充说明”仅删除PPTC转换后的文件，下次打开游戏时将根据.info文件重新生成PPTC文件。\n如想彻底清除缓存，请进入目录把.info文件一并删除“

感谢大佬_(•̀ω•́ 」∠)_

2022-11-28 00:36 UTC, laincat commented
中文与英文或数字之间建议加上空格。统一一下。

2022-11-28 02:45 UTC, Soulize commented
> 中文与英文或数字之间建议加上空格。统一一下。

描述中应该是没必要加空格，一是加完之后就太长了，二是描述里有空格显得有些突兀。
dlc和更新的个数我觉得是不加空格比较有整体性，加空格的话数字显得有点突出。
我的fork里有自动构建出的版本，大佬可以看一下，如果有什么地方确切的需要改，麻烦提出来_(•̀ω•́ 」∠)_

2022-11-28 08:12 UTC, Soulize commented
@Narugakuruga 手机上点错了，对不起( ´•̥̥̥ω•̥̥̥` )

2022-11-28 12:40 UTC, laincat commented
https://github.com/sparanoid/chinese-copywriting-guidelines
参考一下？

2022-11-29 13:27 UTC, Soulize commented
全角的括号在ryujinx默认中文字体里显示时会有bug，字体间距和大小不一，故改成了空格+半角括号

2022-11-30 21:08 UTC, gdkchan approved these changes

2022-12-02 17:29 UTC, AcK77 commented
As Ryujinx has migrated translation management to Crowdin, please see https://crwd.in/ryujinx if you would like to pursue this contribution. I close this PR.
Thanks.

2022-12-02 17:29 UTC, closed without merging