Optimize string memory usage. Use Spans and StringBuilders where possible
Ryujinx/Ryujinx pull request #3933
Opened 2022-11-28 21:00 UTC by SukharevAndrey

Just a bunch of low-hanging fruits.
This PR replaces substring usages with span slices where possible so it will not allocate in this places. It also introduces StringBuilder in a shader code generator which for some reason uses dumb string concatenations instead. But I think maybe it needs to be benchmarked anyway.

2022-12-01 15:48 UTC, AcK77 requested changes

2022-12-01 15:48 UTC, AcK77 commented on ARMeilleure/Decoders/OpCodeTable.cs
> +            string reversedEncoding = $"{encoding.AsSpan(16)}{encoding.AsSpan(0, 16)}";
Here you use interpolation, in another file you use `string.Concat` it could be nice to keep everything using the same for consistencies.

2022-12-01 15:48 UTC, AcK77 commented on Ryujinx.Ava/Ui/ViewModels/ControllerSettingsViewModel.cs
> +                return string.Concat(str.AsSpan(0, MaxSize - Ellipsis.Length), Ellipsis);
Here you use `string.Concat`, in another file you use string interpolation, it could be nice to keep everything using the same for consistencies.

2022-12-01 15:48 UTC, AcK77 commented on Ryujinx.Common/Utilities/UInt128Utils.cs
> +            return new UInt128(
```suggestion
            return new UInt128(ulong.Parse(hex.AsSpan(0, 16), NumberStyles.HexNumber), ulong.Parse(hex.AsSpan(16), NumberStyles.HexNumber));
```

2022-12-01 15:48 UTC, AcK77 commented on Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
> +                if (texOp.Inst == Instruction.ImageLoad)
```suggestion
                texCallBuilder.Append((texOp.Inst == Instruction.ImageLoad) ? "imageLoad" : "imageStore");
```

2022-12-01 15:48 UTC, AcK77 commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
> -        private RectangleF MeasureString(string text, Font font)
I don't think all those changes are really needed.

2022-12-01 15:48 UTC, AcK77 commented on Ryujinx/Ui/Windows/ControllerWindow.cs
> +                return $"{str.AsSpan(0, MaxSize - ShrinkChars.Length)}{ShrinkChars}";
Same comment about `string.Concat`

2022-12-27 22:36 UTC, TSRBerry requested changes

2022-12-27 22:36 UTC, TSRBerry commented on Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenPacking.cs
> +            return $".{"rgba".AsSpan(index, 1)}";
Why was the string changed here?

2022-12-27 22:36 UTC, TSRBerry commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +        private int _currentIndentCharsCount;
```suggestion
        private int _currentIndentCount;
```
I think the name doesn't need to be this long to understand the purpose of this field.

2022-12-27 22:36 UTC, TSRBerry commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +            _currentIndentCharsCount += SingleIndentLength;
```suggestion
            _currentIndentCharsCount++;
```

2022-12-27 22:36 UTC, TSRBerry commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +            _currentIndentCharsCount = Math.Max(_currentIndentCharsCount - SingleIndentLength, 0);
```suggestion
           if (_currentIndentCharsCount - 1 >= 0)
           {
                _currentIndentCharsCount--;   
           }
```

2022-12-27 22:36 UTC, TSRBerry commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +            _sb.Append(' ', _currentIndentCharsCount);
```suggestion
            _sb.Append(' ', SingleIndentLength * _currentIndentCharsCount);
```

2022-12-27 22:36 UTC, TSRBerry commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +        private const int SingleIndentLength = 4;
```suggestion
        private const int IndentLength = 4;
```
We can simplify the name here.

2023-01-08 12:08 UTC, SukharevAndrey commented on Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenPacking.cs
> +            return $".{"rgba".AsSpan(index, 1)}";
Copypaste error, oops

2023-01-08 12:11 UTC, SukharevAndrey commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +            _currentIndentCharsCount += SingleIndentLength;
But indent is 4 spaces, isn't it? ++ will make this 1 space instead, it will be less readable in generated code.

2023-01-08 22:15 UTC, TSRBerry reviewed
Lgtm, I'd just change the switch statements, but I'm not sure if they are better in general.

2023-01-08 22:15 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
> +            switch (text)
I'm not sure if there are any performance implications, but I'd prefer using an if-statement here, since there are only two cases.

2023-01-08 22:15 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
> +            switch (text)
Same thing as above.

2023-01-08 22:31 UTC, TSRBerry requested changes
A few formatting comments about the latest changes.

2023-01-08 22:31 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
>              if (text == "")
Add a new line before

2023-01-08 22:31 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
> +                return new RectangleF(0, emptyRectangle.Y, 0, emptyRectangle.Height);
```suggestion

                return new RectangleF(0, emptyRectangle.Y, 0, emptyRectangle.Height);
```

2023-01-08 22:31 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
> +            return new RectangleF(rectangle.X, rectangle.Y, rectangle.Width, rectangle.Height);
```suggestion

            return new RectangleF(rectangle.X, rectangle.Y, rectangle.Width, rectangle.Height);
```

2023-01-08 22:31 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
> +            if (text == "")
```suggestion
            
            if (text == "")
```

2023-01-08 22:31 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/SoftwareKeyboardRendererBase.cs
> +            return new RectangleF(rectangle.X, rectangle.Y, rectangle.Width, rectangle.Height);
```suggestion

            return new RectangleF(rectangle.X, rectangle.Y, rectangle.Width, rectangle.Height);
```

2023-01-09 20:48 UTC, TSRBerry approved these changes
Lgtm!

2023-01-15 10:13 UTC, marysaka approved these changes

2023-01-15 10:13 UTC, marysaka commented on Ryujinx.Graphics.Shader/CodeGen/Glsl/Instructions/InstGenMemory.cs
> +                }
line return

```suggestion
                texCallBuilder.Append(')');

                if (texOp.Inst == Instruction.ImageLoad)
                {
                    texCallBuilder.Append(GetMaskMultiDest(texOp.Index));
                }
```

2023-01-18 18:42 UTC, gdkchan approved these changes
lgtm, thanks.

2023-01-18 22:25 UTC, AcK77 approved these changes

2023-01-18 22:25 UTC, merged