Better SDL2 Audio Init Error Logging
Ryujinx/Ryujinx pull request #3967
Opened 2022-11-30 19:23 UTC by IsaacMarovitz

2022-11-30 20:39 UTC, marysaka requested changes

2022-11-30 20:39 UTC, marysaka commented on Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
> +                string errorMessage = $"SDL2 open audio device initialization failed with error \"{SDL_GetError()}\"";
```suggestion
                string errorMessage = $"SDL2 open audio device initialization failed with error \"{SDL_GetError()}\"";

```

2022-11-30 20:39 UTC, marysaka commented on Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
> +                string errorMessage = $"SDL2 open audio device is not valid";
```suggestion
                string errorMessage = $"SDL2 open audio device is not valid";

```

2022-11-30 21:48 UTC, marysaka requested changes

2022-11-30 21:48 UTC, marysaka commented on Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
> +                string errorMessage = $"SDL2 open audio device is not valid";
```suggestion
                string errorMessage = $"SDL2 audio device is invalid!";
```

2022-11-30 21:51 UTC, AcK77 requested changes

2022-11-30 21:51 UTC, AcK77 commented on Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
> +                Logger.Error?.Print(LogClass.Application, errorMessage);
`errorMessage` can be removed (and the string interpolation too).

```suggestion
                Logger.Error?.Print(LogClass.Application, "SDL2 open audio device is not valid");
```

2022-11-30 21:51 UTC, AcK77 commented on Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
> +                Logger.Error?.Print(LogClass.Application, errorMessage);
```suggestion
                Logger.Error?.Print(LogClass.Application, 
                    $"SDL2 open audio device initialization failed with error \"{SDL_GetError()}\"");
```
Add a new extra empty line before the `return` too

2022-12-01 01:24 UTC, AcK77 approved these changes

2022-12-01 16:53 UTC, merged