HLE: Add basic stubs to get Labo VR booting to title screen.
Ryujinx/Ryujinx pull request #4007
Opened 2022-12-04 00:20 UTC by Luminoso-256

A small set of stub additions to `ISelfController`. These let Labo VR boot all the way to the titlescreen, which it previously couldn't manage.

Note: I'm not certain as to the wisdom of actually printing a stub message for GetCurrentIlluminanceEx - Labo seems to check this _every frame_ or something similar, leading to a large amount of log spam.

Screenshots:
![labo1](https://user-images.githubusercontent.com/63971285/205467793-def0fbfa-1f49-496c-b079-a861362980fa.png)
![labo2](https://user-images.githubusercontent.com/63971285/205467794-131a7475-e792-4612-97b8-6e39fff1c6f6.png)

2022-12-04 17:22 UTC, marysaka requested changes

2022-12-04 17:22 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +        // GetCurrentIlluminanceEx() -> u32,float
```suggestion
        // GetCurrentIlluminanceEx() -> (bool, f32)
```

2022-12-04 17:22 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            return ResultCode.Success;
```suggestion

            return ResultCode.Success;
```

2022-12-04 17:22 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceAm);
```suggestion
            Logger.Stub?.PrintStub(LogClass.ServiceAm);

```

2022-12-04 17:22 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            context.ResponseData.Write(1); //OverLimit, as a u32 because who knows why?
As per [switchbrew](https://switchbrew.org/wiki/Applet_Manager_services#GetCurrentIlluminanceEx), this is a bool.

The reason it's a u32 here is because of padding to align to 4 bytes.

2022-12-04 17:34 UTC, Luminoso-256 commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            context.ResponseData.Write(1); //OverLimit, as a u32 because who knows why?
Ah I see. Thanks for that bit of clarification!

2022-12-04 17:41 UTC, Luminoso-256 commented
Formatting suggestions have been applied

2022-12-04 18:42 UTC, gdkchan approved these changes
Code lgtm other than the comment.

2022-12-04 18:42 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +        // GetCurrentIlluminanceEx() -> (bool,f32)
```suggestion
        // GetCurrentIlluminanceEx() -> (bool, f32)
```

2022-12-04 18:47 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +        //IsIlluminanceAvailable() -> bool
```suggestion
        // IsIlluminanceAvailable() -> bool
```

2022-12-04 18:50 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            context.ResponseData.Write(true); // This should call through to Lbl, but there's no situation where we'd want false.
```suggestion
            // NOTE: This should call through to Lbl, but there's no situation where we'd want false.
            context.ResponseData.Write(true);
            
            Logger.Stub?.PrintStub(LogClass.ServiceAm);
```
Small formatting nit.

2022-12-05 13:48 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            return ResultCode.Success;
```suggestion

            return ResultCode.Success;
```
One empty line before a return

2022-12-07 03:46 UTC, AcK77 requested changes

2022-12-07 03:46 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            // NOTE: This should call through to Lbl, but there's no situation where we'd want false.
```suggestion
            // NOTE: This should call IsAmbientLightSensorAvailable through to Lbl, but there's no situation where we'd want false.
```

2022-12-07 03:46 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            context.ResponseData.Write(true);
Have you tested to return `false` here? It shouldn't call `GetCurrentIlluminanceEx` then.

2022-12-07 03:46 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            Logger.Stub?.PrintStub(LogClass.ServiceAm);
We usually put the `PrintStub` right before the `return`, (with the extra empty line before of course)

2022-12-11 17:47 UTC, Luminoso-256 commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            context.ResponseData.Write(true);
The problem with that (to me) is that the idea here is to eventually allow things like LaboVR to actually work, which is only feasible if this is true... I don't really see the harm in a dummy light value at the moment?

2022-12-11 23:58 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +            context.ResponseData.Write(true);
As long as this isn't actually working I'd suggest changing this to false. As soon as work to support LaboVR is being done, changing this to true wouldn't be an issue.

2022-12-29 14:52 UTC, AcK77 approved these changes

2022-12-29 14:57 UTC, merged