Include a start.sh file with correct launch options
Ryujinx/Ryujinx pull request #4013
Opened 2022-12-04 18:53 UTC by RMED24

On quite a few occasions I've seen people launch Ryujinx on linux with different methods. Most people seem to be fine, but I have noticed the occasional issue from users that have occurred at least once in the past.

One of these issues would be people trying to launch Ryujinx in wayland and being annoyed

2022-12-04 19:03 UTC, RMED24 commented
I think it's just best I wait for the build job to complete first. I don't think I'll get it on first try, but hey it is worth trying

2022-12-04 19:28 UTC, RMED24 commented
I got it right first try... Re-basing the PR and opening it up for a merge... Adding checks for dependencies would be nice although not required for a merge...

2022-12-04 19:30 UTC, marysaka requested changes

2022-12-04 19:30 UTC, marysaka commented on distribution/linux/start.sh
> +# We recommend using Pine-jinx if you want the game to be optimised and installed for your system. This is mostly for PR builds and people who want a portable install.
```suggestion
```
No we recommend FlatHub release.

2022-12-04 19:30 UTC, marysaka commented on Ryujinx/Ryujinx.csproj
> +     <ContentWithTargetPath Include="..\distribution\linux\start.sh" Condition="'$(RuntimeIdentifier)' != 'win10-x64' AND '$(RuntimeIdentifier)' != 'osx-x64'">
```suggestion
     <ContentWithTargetPath Include="..\distribution\linux\start.sh" Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
```

2022-12-04 19:30 UTC, marysaka commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +     <ContentWithTargetPath Include="..\distribution\linux\start.sh" Condition="'$(RuntimeIdentifier)' != 'win10-x64' AND '$(RuntimeIdentifier)' != 'osx-x64'">
```suggestion
     <ContentWithTargetPath Include="..\distribution\linux\start.sh" Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
```

2022-12-04 19:30 UTC, marysaka commented on distribution/linux/start.sh
> +DOTNET_EnableAlternateStackCheck=1 GDK_BACKEND=x11 "$SCRIPT_DIR/Ryujinx" "$@"
I would prefer ``GDK_BACKEND`` to be set in Ryujinx's Program.cs for GTK3 frontend.

2022-12-04 19:32 UTC, marysaka commented on distribution/linux/start.sh
> +chmod +x "$SCRIPT_DIR/Ryujinx"
Instead of this, make the CI use [add_tar_exec.py](https://github.com/Ryujinx/Ryujinx/blob/master/distribution/misc/add_tar_exec.py) for the release job.

2022-12-04 19:33 UTC, gdkchan reviewed
For FFmpeg we should probably just include a pre-built library like we do on Windows, to make sure it will use a library that works.

Seems weird that you need to launch the emulator through a script rather than directly. But I don't know a better way to do this so...

2022-12-04 19:33 UTC, gdkchan commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +   <ItemGroup>
Indentation is off on all lines you added since you use 3 spaces, everything else uses 2.

2022-12-04 19:37 UTC, TSRBerry submitted a review, later dismissed
I like this idea! There are already a lot of Linux specific things that need to be done, so we might as well include a script for that.

2022-12-04 19:37 UTC, TSRBerry commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +     <ContentWithTargetPath Include="..\distribution\linux\start.sh" Condition="'$(RuntimeIdentifier)' != 'win10-x64' AND '$(RuntimeIdentifier)' != 'osx-x64'">
```suggestion
     <ContentWithTargetPath Include="..\distribution\linux\Ryujinx.sh" Condition="'$(RuntimeIdentifier)' != 'win10-x64' AND '$(RuntimeIdentifier)' != 'osx-x64'">
```
How about renaming this to `Ryujinx.sh`?

2022-12-04 19:37 UTC, TSRBerry commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +        <TargetPath>start.sh</TargetPath>
```suggestion
        <TargetPath>Ryujinx.sh</TargetPath>
```
Same here

2022-12-04 19:37 UTC, TSRBerry commented on Ryujinx/Ryujinx.csproj
> +        <TargetPath>start.sh</TargetPath>
Here too

2022-12-04 19:37 UTC, TSRBerry commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
Currently the output binary for Avalonia is called `Ryujinx.Ava`. To make this script work you'll need to set the `AssemblyName` in this csproj to `Ryujinx` too.

2022-12-04 19:37 UTC, TSRBerry commented on distribution/linux/start.sh
> +# We recommend using Pine-jinx if you want the game to be optimised and installed for your system. This is mostly for PR builds and people who want a portable install.
```suggestion

# We recommend using Pine-jinx if you want the game to be optimized and installed for your system. This is mostly for PR builds and people who want a portable install.
```
One empty line after the shebang line and a small typo.

If we are shipping a start script we should recommend using that over everything else. But since Pine-jinx already exists, I'm not sure what the best way to handle this is.

2022-12-04 19:37 UTC, TSRBerry commented on distribution/linux/start.sh
> +chmod +x "$SCRIPT_DIR/Ryujinx"
Is this still necessary currently? If so, then we should check if the binary already has execute permissions.

2022-12-04 19:37 UTC, TSRBerry commented on distribution/linux/start.sh
> +# It is also recommended to run start.sh in the terminal, although this isn't required in order for it to operate
```suggestion
```
I think this comment is not needed. The people testing PRs will probably already know to run the script in the terminal.

2022-12-04 19:37 UTC, TSRBerry commented on distribution/linux/start.sh
> +SCRIPT_DIR=$(dirname $0)
```suggestion
SCRIPT_DIR=$(dirname $(realpath $0))

```
Just in case someone starts to mess with symlinks.

2022-12-04 19:43 UTC, RMED24 commented on distribution/linux/start.sh
> +chmod +x "$SCRIPT_DIR/Ryujinx"
> Is this still necessary currently? If so, then we should check if the binary already has execute permissions.

I wanted to be sure, because my worst nightmare is always those who include files that I have to chmod myself. It's also confusing for beginners coming from windows

2022-12-04 19:45 UTC, RMED24 commented
> Seems weird that you need to launch the emulator through a script rather than directly. But I don't know a better way to do this so...

I don't disagree, but I can't think of another way either

2022-12-04 19:46 UTC, RMED24 commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
I forgot about that. I will look into this soon

2022-12-04 19:59 UTC, RMED24 commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +     <ContentWithTargetPath Include="..\distribution\linux\start.sh" Condition="'$(RuntimeIdentifier)' != 'win10-x64' AND '$(RuntimeIdentifier)' != 'osx-x64'">
Done

2022-12-04 20:00 UTC, RMED24 commented on distribution/linux/start.sh
> +# We recommend using Pine-jinx if you want the game to be optimised and installed for your system. This is mostly for PR builds and people who want a portable install.
This line was completely removed, and is no longer relevant now

2022-12-04 20:01 UTC, TSRBerry commented on distribution/linux/start.sh
> +chmod +x "$SCRIPT_DIR/Ryujinx"
Look at this comment, I think it's the better solution:
https://github.com/Ryujinx/Ryujinx/pull/4013#discussion_r1039019263

2022-12-04 20:10 UTC, RMED24 commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
7037c075affbdf3fe0044dc0e9a3ee3cd31a3092 should close this issue

2022-12-04 20:13 UTC, TSRBerry commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +    <RootNamespace>Ryujinx</RootNamespace>
```suggestion
    <RootNamespace>Ryujinx.Ava</RootNamespace>
    <AssemblyName>Ryujinx</AssemblyName>
```

2022-12-04 20:13 UTC, RMED24 commented
I need 7037c075affbdf3fe0044dc0e9a3ee3cd31a3092 to be double checked in order to make sure this is right and doesn't break anything. If it does, _please_ let me know

2022-12-04 20:20 UTC, RMED24 commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +    <RootNamespace>Ryujinx</RootNamespace>
Legend

2022-12-05 07:00 UTC, marysaka requested changes

2022-12-05 07:00 UTC, marysaka commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +    <AssemblyName>Ryujinx</AssemblyName>
You shouldn't do that considering the updater on Avalonia take current executable name and try to rerun itself that way.

This will make it bug at relaunch

2022-12-05 08:06 UTC, RMED24 commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +    <AssemblyName>Ryujinx</AssemblyName>
> You shouldn't do that considering the updater on Avalonia take current executable name and try to rerun itself that way.
> 
> This will make it bug at relaunch

The only other solutions I can see to this is either packing 2 seperate scripts for the avalonia and GTK build, or just flat out renaming Ryujinx.Ava. If there's another solution or we want to go ahead with one of these changes, please let me know

2022-12-05 08:15 UTC, RMED24 commented
This GDK_BACKEND variable is something I will compile and test now on wayland myself. As Mary said it wouldn't work and TSR said it did. I will compile this and confirm it

2022-12-05 08:15 UTC, RMED24 commented
This GDK_BACKEND variable is something I will compile and test now on wayland myself. As Mary said it wouldn't work and TSR said it did. I will compile this and confirm it

2022-12-05 08:29 UTC, RMED24 commented
> This GDK_BACKEND variable is something I will compile and test now on wayland myself. As Mary said it wouldn't work and TSR said it did. I will compile this and confirm it

@TSRBerry looks like this still causes a crash and hasn't fixed the issue at hand. There needs to be more done it seems...

2022-12-05 08:51 UTC, RMED24 commented
From launching the Ryujinx binary directly... We have liftoff! 

![image](https://user-images.githubusercontent.com/81475204/205594217-0178f2ba-30b5-48f0-9627-58507fbb83a1.png)

2022-12-05 13:38 UTC, TSRBerry commented on Ryujinx.Ava/Ryujinx.Ava.csproj
> +    <AssemblyName>Ryujinx</AssemblyName>
> You shouldn't do that considering the updater on Avalonia take current executable name and try to rerun itself that way.

@marysaka what if we push an update (before this PR gets merged) that uses `Ryujinx` as the next executable if `Ryujinx.Ava` is not available?

2022-12-07 22:20 UTC, TSRBerry commented
Needs a rebase

2022-12-09 20:54 UTC, RMED24 commented
I promise I'll get this all finished up in the next few days. I've had to deal with work and college which has given me little time to finish this... I will create a quick to-do list for myself right now so I can keep on top of it.
- Solve the conflict and rebase my PR to the latest version
- Make sure Ryujinx.sh is executable
Once these are solved, I will ping the testers role in order to ask people on Sway, GNOME and KDE plasma-wayland-session to test this works properly when they have xwayland installed... Things are looking good so far however

2022-12-11 09:51 UTC, RMED24 commented
> SDL is switching back to defaulting to wayland soon.
> 
> I'm not sure if that also breaks Ryujinx but probably worth investigating and setting that to x11 too if it causes issues while you're at it.

I'll have a look online and keep an eye out just to be sure. Thanks for letting me know

2022-12-11 11:30 UTC, marysaka commented
Need a rebase

2022-12-12 19:46 UTC, RMED24 commented
> Need a rebase

Resolved

2022-12-13 10:11 UTC, RMED24 commented
Wtf when did I request a review I never did that

2022-12-28 17:15 UTC, TSRBerry commented
I changed a few file paths in distribution and renamed `ReleaseInformation.cs`.
That's why I also opened a PR on the flathub repo, as it would break after merging this PR.

2023-01-07 08:03 UTC, marysaka approved these changes

2023-01-07 08:06 UTC, merged

2024-01-20 19:57 UTC, Melechtna commented
This is bad, and we shouldn't be doing this, instead we should be working on getting Wayland working properly, rather than just throwing it out.

The issue seems to stem from Gdk not being configured to accept wayland windows

00:00:00.027 |E| .NET TP Worker (Ryujinx:3347901): Gdk-CRITICAL **: 13:45:14.007: gdk_x11_window_get_xid: assertion 'GDK_IS_X11_WINDOW (window)' failed

This part here, I've gone in and reverted what this commit does, so I could trouble shoot the actual issue instead of bandaid it.

While I don't have a precise solution to offer, as I typically work with Qt over GDK, likely you'd need to add something to detect when running in a wayland session, or if I'm not mistaken, make its draw calls agnostic to x11 or wayland, and let the DE handle when to use either as with Qt. All that need be done to test things, is to remove or comment out lines 107 and 108 in Ryujinx/program.cs as of the 1117 release. I'm not sure where these "fixes" were shoved into ava, but I'm unable to find them and may be else where, so I can't really confirm if ava might just be fine without forcing everything to run in xWayland.

I am unable to give a more proper log, as of right now this crashes so hard that it starts making other things crash within the system, so besides this error, the logger never has a chance to print anything else out at the moment, assuming it would even if GDK was configured correctly.

2024-01-20 20:49 UTC, TSRBerry commented
I'm sorry but this PR has nothing to do with wayland.

2024-01-20 21:39 UTC, RMED24 commented
> I'm sorry but this PR has nothing to do with wayland.

No Melechtna is right in some regard. This PR was the one where ryujinx always launched in xwayland mode no matter what, as the backend was set to x11 in the ``Program.cs`` file. If you remember, ryujinx got native wayland support before this but it ONLY worked in the menus. It would crash as soon as a game was open. 

This was a bandaid solution as nobody could really suggest better at the time, and I wanted it to be a one click solution for people. I wanted this solution because some ryujinx users were having it crash, and having to set an env environment isn't an ideal solution. Especially to someone who is a beginner.

Maybe a new PR should be opened if it can be fully figured out, and ryujinx can become a native wayland application. After all, GTK and (I believe) avalonia both support wayland.

2024-01-20 21:43 UTC, Melechtna commented
> > I'm sorry but this PR has nothing to do with wayland.
> 
> No Melechtna is right in some regard. This PR was the one where ryujinx always launched in xwayland mode no matter what, as the backend was set to x11 in the `Program.cs` file. If you remember, ryujinx got native wayland support before this but it ONLY worked in the menus. It would crash as soon as a game was open.
> 
> This was a bandaid solution as nobody could really suggest better at the time, and I wanted it to be a one click solution for people. I wanted this solution because some ryujinx users were having it crash, and having to set an env environment isn't an ideal solution. Especially to someone who is a beginner.
> 
> Maybe a new PR should be opened if it can be fully figured out, and ryujinx can become a native wayland application. After all, GTK and (I believe) avalonia both support wayland.

The trouble being, and if you look what keeps getting linked back here, is this bandaid solution is being used as a "we fixed it" answer, when the opposite is true. I'm having trouble locating the code responsible for this xid method, but likely, from what I'm reading, we'd want to swap this out for process or window IDs instead, and it should make the code x11 and wayland agnostic, so it draws to the screen regardless of which environment its in, but I'd need to know what code handles this action to try and implement a proper fix. I'd open a PR, but as I said, it'd likely just get shut down and linked back here anyway.