Bsd: Implement Select
Ryujinx/Ryujinx pull request #4017
Opened 2022-12-05 00:54 UTC by TSRBerry

A while ago @gdkchan already implemented `Select`, but never created a PR for it.
This PR uses this implementation and adapts it to the current Ryujinx version. 

With this implementation @EmulationFanatic was able to start a LAN game in the Saints Row games.

---

Note: The implementation was tested before I cleaned it up. I'm sure I didn't break anything by cleaning it up, but just in case, let's wait for confirmation that everything still works as expected.

2022-12-05 06:52 UTC, marysaka requested changes

2022-12-05 06:52 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +            BuildMask(errorSockets, errorFdsOut.Memory.Span);
Not a huge fan to have the socket logic in here, we have abstraction around for Poll...

Move to ManagedSocketPollManager and extend IPollManager? (might be worth renaming it)

I also think it is possible to Select an eventfd (EventFileDescriptor), might be worth adding for completeness

2022-12-05 14:57 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +            BuildMask(errorSockets, errorFdsOut.Memory.Span);
When I first implemented this method I created a new struct for FileDescriptorSets and tried to use Poll as a reference to implement Select. But I couldn't really understand Poll, so I never finished my implementation.

> Move to ManagedSocketPollManager and extend IPollManager? (might be worth renaming it)

I'm not quite sure how to go about that, since Poll looks very different from Select. I locally added Select to IPollManager with this signature:
```cs
LinuxError Select(List<ISocket> readSockets, List<ISocket> writeSockets, List<ISocket> errorSockets, int timeoutMilliseconds, out int updatedCount)
```
But this won't be compatible with Poll. How should I go about this?

2022-12-05 15:58 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +            BuildMask(errorSockets, errorFdsOut.Memory.Span);
Hmm, I attempt to move Select to IPollManager, but I feel like I just made things a lot worse than before.

https://github.com/Ryujinx/Ryujinx/pull/4017/commits/281eea265939364912bf965b66c06190b39a09bc

2022-12-08 01:39 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +            BuildMask(errorSockets, errorFdsOut.Memory.Span);
Redid this again and this time I feel like I understood what you meant. Hopefully it's better this way!

2022-12-09 01:39 UTC, marysaka approved these changes

2022-12-09 09:52 UTC, EmulationFanatic commented
Also enables [Just Die Already](https://github.com/Ryujinx/Ryujinx-Games-List/issues/4131) to boot and play normally (hangs forever at a black screen otherwise).
![image](https://user-images.githubusercontent.com/62343878/206674745-4011e8df-2e18-4023-9c3b-e4a6340e4c74.png)

2022-12-12 13:59 UTC, AcK77 approved these changes

2022-12-12 13:59 UTC, merged