Filter “._” game files from the Game List
Ryujinx/Ryujinx pull request #4051
Opened 2022-12-07 01:37 UTC by Candygoblen123

`._` files are automatically generated by macOS to store certain metadata about files when you transfer them to an SD card. These files are hidden in finder (even if you enable “show hidden files”) and can only be deleted through terminal. Some users have reported that these files appeared in the game list, so this is a PR that filters them out of the game list.

2022-12-07 03:30 UTC, TSRBerry requested changes

2022-12-07 03:30 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                            (Path.GetFileName(app).Substring(0, 2) != "._"))
Move this into `GetFilesInDirectory()` and use `StartWith()` instead of `Substring()`.

I think it might also be a good idea to filter all files starting with a `.`, so other hidden files won't be listed either.

2022-12-07 03:34 UTC, AcK77 commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                            (Path.GetFileName(app).Substring(0, 2) != "._"))
Or maybe don't list files when this condition `File.GetAttributes(path).HasFlag(FileAttributes.Hidden)` is `true` ?
(I don't know if files starting with `._` or `.` have it or not)

2022-12-07 03:38 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                            (Path.GetFileName(app).Substring(0, 2) != "._"))
Not sure if that works for Linux and/or macOS

2022-12-07 15:39 UTC, gdkchan commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                            (Path.GetFileName(app).Substring(0, 2) != "._"))
I think checking for hidden files is a better solution too (assuming it solves the problem).

2022-12-07 15:56 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                            (Path.GetFileName(app).Substring(0, 2) != "._"))
Yup! We can use that, so no filtering of the filename is needed.

Source: https://learn.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=net-7.0
![image](https://user-images.githubusercontent.com/20988865/206227276-eed0dd0e-9c37-4bb6-a43e-ffcf7a0c3a84.png)

2022-12-07 15:57 UTC, Candygoblen123 commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                            (Path.GetFileName(app).Substring(0, 2) != "._"))
Yeah, I just implemented it and it seems to work just fine.

2022-12-07 15:59 UTC, Candygoblen123 commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                            (extension == ".nso")) &&
Im sorry, but I don't have much experience in C# and im not sure what you mean by that.

2022-12-07 16:08 UTC, gdkchan commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                        if (!File.GetAttributes(file).HasFlag(FileAttributes.Hidden)) {
```suggestion
                        if (!File.GetAttributes(file).HasFlag(FileAttributes.Hidden))
                        {
```

2022-12-07 16:20 UTC, TSRBerry commented
I'd like to ask you for one more thing. Could you also change this?

```diff
- content = Directory.GetFiles(dir, "*");
+ Directory.EnumerateFiles(dir);
```

2022-12-07 21:53 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                IEnumerable<string> content = Array.Empty<string>();
Sorry I didn't see that before, but this method can be completely removed.

Instead you should use `if (!File.GetAttributes(file).HasFlag(FileAttributes.Hidden))` within the foreach-loop in `LoadApplication()`.

2022-12-07 22:43 UTC, TSRBerry approved these changes
Thank you!

2022-12-09 16:23 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                    foreach (string app in Directory.EnumerateFiles(appDir, "*", SearchOption.AllDirectories))
Wrap this into a `try` block, like we discussed on discord

2022-12-18 22:47 UTC, TSRBerry requested changes

2022-12-18 22:47 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +using System.Linq;
```suggestion
```
See other comment below.

2022-12-18 22:47 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                    foreach (string app in content)
```suggestion
                    foreach (string app in Directory.EnumerateFiles(appDir, "*", SearchOption.AllDirectories))
```
Github doesn't let me create a comment further down, so I can put everything into the suggestion block.

You should move the foreach-loop into the try block. This allows you to get rid of the `content` variable and you won't need to import `System.Linq`.

2022-12-27 11:58 UTC, TSRBerry approved these changes
Lgtm, thanks!

2022-12-29 15:04 UTC, marysaka approved these changes

2022-12-29 15:52 UTC, merged