converts the templates into forms
Ryujinx/Ryujinx pull request #4068
Opened 2022-12-08 06:26 UTC by piplup55

closes #4066, just looking for feedback on what to change

2022-12-12 14:03 UTC, AcK77 commented
It could be nice if you could enable issues on your fork, then we could test your template.

2022-12-12 14:12 UTC, piplup55 commented
> It could be nice if you could enable issues on your fork, then we could test your template.

issues have now been enabled, idk why they were disabled in the first place

2022-12-15 17:16 UTC, AcK77 requested changes
I've started to review issues, but I have noticed a lot of things are missing, you didn't use all text descriptions we had. Ryujinx version or Game version are missing too.
Some descriptions have to be improved too (even if that could be done in another PR).

2022-12-15 17:16 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      placeholder: Logs files can be found under ``Logs`` folder in Ryujinx program folder.
The `` don't work there they have to be replaced with "

2022-12-15 17:16 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      description: A log file will help our developers to better diagnose and fix the issue.
Could be nice to say you can drag and drop the file on the textarea

2022-12-15 17:16 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - OS: *(e.g. Windows 10)*
This should be separated textarea

2022-12-15 17:46 UTC, piplup55 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - OS: *(e.g. Windows 10)*
we could do a dropdown for os, the only problem with how would we handle linux distro's

2022-12-23 04:49 UTC, TSRBerry commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - OS: *(e.g. Windows 10)*
Linux distro is not too important imo.
We could also add another textarea when Linux is selected.

2022-12-29 14:19 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +        - OS: *(e.g. Windows 10)*
well if the user want to put the OS version, it's better to use a textarea instead of a dropdown.

2023-01-10 16:44 UTC, EmulationFanatic commented on .github/ISSUE_TEMPLATE/missing_service_call.yml
> +      description: Add our games list database (https://github.com/Ryujinx/Ryujinx-Games-List/issues) links of games who require this instruction
description: Add links to the [compatibility list page(s)](https://github.com/Ryujinx/Ryujinx-Games-List/issues) of the game(s) that require this service.

2023-01-10 16:46 UTC, EmulationFanatic commented on .github/ISSUE_TEMPLATE/missing_service_call.yml
> +      description: Please search for existing missing service call
description: Please search for an [existing missing service call issue](https://github.com/Ryujinx/Ryujinx/issues) first.

2023-01-20 19:58 UTC, piplup55 commented on .github/ISSUE_TEMPLATE/missing_cpu_instruction.yml
> +      description: Add our games list database (https://github.com/Ryujinx/Ryujinx-Games-List/issues) links of games who require this instruction
while i do think the text change is good i don't think descriptions support hyperlinks

2023-01-20 20:28 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/missing_cpu_instruction.yml
> +      description: Add our games list database (https://github.com/Ryujinx/Ryujinx-Games-List/issues) links of games who require this instruction
Markdown like should work in YAML file.

2023-01-20 20:29 UTC, AcK77 commented
> If the user want to put the OS version, it's better to use a textarea instead of a dropdown.
This is not addressed...

2023-01-20 21:24 UTC, AcK77 approved these changes

2023-01-21 00:55 UTC, TSRBerry commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Game version
Is there a input box for the game itself, before we ask about the game version?

2023-01-21 00:57 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Game version
The game version should be optionnal true!

2023-01-21 01:55 UTC, piplup55 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Game version
> Is there a input box for the game itself, before we ask about the game version?

the old template never asked for the game, however it can easily be added if wanted/needed

2023-01-21 01:57 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Game version
I think @TSRBerry tell that because the game version input box is needed to validate the issue.

2023-01-21 02:01 UTC, piplup55 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Game version
what we could do is add the game textbox and make the game version optional

2023-01-22 00:10 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Game version
It's not needed to add a game textbox here. It could be an homebrew too. Users will describe that in the main textbox, that's why game version has to be optional.

2023-01-22 09:50 UTC, piplup55 commented on .github/ISSUE_TEMPLATE/bug_report.yml
> +      label: Game version
> It's not needed to add a game textbox here. It could be an homebrew too. Users will describe that in the main textbox, that's why game version has to be optional.

let me quickly make that change then

2023-01-27 06:27 UTC, piplup55 commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +name: Feature Request
it seems i missed one should be resolved now

2023-01-27 10:40 UTC, TSRBerry approved these changes
Lgtm, thank you!

2023-01-27 18:23 UTC, merged