Replace `DllImport` usage with `LibraryImport`
Ryujinx/Ryujinx pull request #4084
Opened 2022-12-09 17:33 UTC by IsaacMarovitz

Replaces `DllImport` with newer .NET 7 `LibraryImport` attribute.

Unicorn inputs left unchanged due to the upcoming Nguet package https://github.com/unicorn-engine/unicorn/pull/1728

2022-12-11 02:14 UTC, TSRBerry commented
This needs a rebase.

2022-12-11 02:39 UTC, TSRBerry requested changes
Small nits, but otherwise this looks pretty good!
Just needs a rebase for Ryujinx.Audio now.

2022-12-11 02:39 UTC, TSRBerry commented on Ryujinx.Ava/Ui/Controls/Win32NativeInterop.cs
> +           [MarshalAs(UnmanagedType.LPTStr)] string lpWindowName,
```suggestion
           [MarshalAs(UnmanagedType.LPWStr)] string lpClassName,
           [MarshalAs(UnmanagedType.LPWStr)] string lpWindowName,
```

2022-12-11 02:39 UTC, TSRBerry commented on Ryujinx.Common/SystemInfo/WindowsSystemInfo.cs
> +        [LibraryImport("kernel32.dll", SetLastError = true)]
Move the `[return: MarshalAs(UnmanagedType.Bool)]` below the `LibraryImport` line for consistency.

2022-12-11 02:39 UTC, TSRBerry commented on Ryujinx.Graphics.Nvdec.FFmpeg/Native/FFmpegApi.cs
> +        internal static unsafe partial AVFrame* av_frame_alloc();
```suggestion
        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
        internal static unsafe partial AVFrame* av_frame_alloc();
```
This is probably not necessary, since it also seems to work without that. So you could just leave it like that.

2022-12-11 02:39 UTC, TSRBerry commented on Ryujinx.Tests.Unicorn/Native/Interface.cs
> +        [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
Since you added the calling convention back here, could you either remove them completely or add the other ones (see previous comment) back in?

2022-12-12 00:04 UTC, TSRBerry approved these changes
Lgtm, thank you!

2022-12-12 00:04 UTC, TSRBerry commented on Ryujinx.Common/SystemInfo/WindowsSystemInfo.cs
>          [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]
```suggestion
        [StructLayout(LayoutKind.Sequential)]
```

This is not needed, let's remove it while we are at it.

2022-12-12 15:29 UTC, AcK77 commented on Ryujinx.Ui.Common/Ryujinx.Ui.Common.csproj
> +    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
Where `unsafe` is used in `Ryujinx.Ui.Common` ?

2022-12-12 15:31 UTC, TSRBerry commented on Ryujinx.Ui.Common/Ryujinx.Ui.Common.csproj
> +    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
Required by `LibraryImport` for code gen

2022-12-14 18:59 UTC, marysaka approved these changes
two things after rebase

2022-12-14 18:59 UTC, marysaka commented on Ryujinx/Modules/Updater/Updater.cs
> +    public static partial class Updater
```suggestion
    public static class Updater
```

2022-12-14 18:59 UTC, marysaka commented on Ryujinx.Ava/Modules/Updater/Updater.cs
> +    internal static partial class Updater
```suggestion
    internal static class Updater
```

2022-12-15 17:06 UTC, AcK77 approved these changes

2022-12-15 17:07 UTC, merged