Use source generated json serializers in order to improve code trimming
Ryujinx/Ryujinx pull request #4094
Opened 2022-12-10 13:11 UTC by SukharevAndrey

This PR introduces source generated json serializers instead of regular ones. This fixes a lot of trimming warnings in the solution by analyzing types used in serialization in compile time.

Additional changes:
* Fix improper `JsonSerializerOptions` usage as they must be used statically to avoid performance issues. 
* Mark all used enums with converter attribute using generic `TypedStringEnumConverter` . Standard `JsonStringEnumConverter` is not trimming friendly so it can't be used globally.
* Write JSONs indented by default.
* Get rid of two NewtonsoftJson usages in updater. Use typed model instead of parsing fields manually.

2022-12-10 17:44 UTC, gdkchan commented on Ryujinx/Modules/Updater/Updater.cs
> +                        if (asset.Name.StartsWith("test-ava-ryujinx") && asset.Name.EndsWith(_platformExt))
I think this shouldn't have been changed to `test-ava-ryujinx` since it will make GTK update to Avalonia.

2022-12-10 19:37 UTC, SukharevAndrey commented on Ryujinx/Modules/Updater/Updater.cs
> +                        if (asset.Name.StartsWith("test-ava-ryujinx") && asset.Name.EndsWith(_platformExt))
Oops. copypaste error.

2022-12-10 20:31 UTC, gdkchan commented
We will need to test if the updater is still working here since allowing people to update to a version with a broken updater would be a disaster.

2022-12-12 14:19 UTC, AcK77 commented
Needs a rebase

2022-12-12 14:26 UTC, SukharevAndrey commented
> Needs a rebase

Done

2023-01-15 09:54 UTC, marysaka commented
This will requires heavy regression testing to ensure we don't break format compatibility with any JSONs.

2023-01-15 16:17 UTC, TSRBerry commented
Also needs a rebase!

2023-01-22 12:00 UTC, SukharevAndrey commented
> Also needs a rebase!

Done

2023-01-27 20:20 UTC, TSRBerry requested changes
Sorry for the long delay.
This is really cool! I added some questions, but this looks really good!

(I apologize for the large amount of namespace comments in this review, we really should have a bot for styling things. Reviews really shouldn't address styling at all ideally.)

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Utilities/JsonHelper.cs
> +                    if (i == 0 || char.IsUpper(name[i - 1]))
What is `char.IsUpper(name[i - 1]` used for?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserProfileJson.cs
> +    public byte[] Image { get; set; }
Are the `JsonPropertyName` attributes still needed? I understand that these get converted to snake_case automatically.

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Utilities/JsonHelper.cs
> +    }
Can't indented be handled using `JsonSourceGenerationOptions`? Wouldn't this allow us to reuse the same instance of `JsonSerializerOptions` everywhere instead of having this method?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Configuration/DownloadableContentJsonSerializerContext.cs
> +namespace Ryujinx.Common.Configuration;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Configuration/Hid/Controller/Motion/MotionConfigJsonSerializerContext.cs
> +namespace Ryujinx.Common.Configuration.Hid.Controller.Motion;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Configuration/TitleUpdateMetadataJsonSerializerContext.cs
> +namespace Ryujinx.Common.Configuration;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Configuration/Hid/InputConfigJsonSerializerContext.cs
> +namespace Ryujinx.Common.Configuration.Hid;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Logging/Formatters/DynamicObjectFormatter.cs
> +namespace Ryujinx.Common.Logging;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Logging/LogEventArgsJson.cs
> +namespace Ryujinx.Common.Logging;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Logging/LogEventJsonSerializerContext.cs
> +namespace Ryujinx.Common.Logging;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Utilities/CommonJsonContext.cs
> +namespace Ryujinx.Common.Utilities;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Common/Utilities/TypedStringEnumConverter.cs
> +namespace Ryujinx.Common.Utilities;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Account/Acc/ProfilesJsonSerializerContext.cs
> +namespace Ryujinx.HLE.HOS.Services.Account.Acc;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserProfileJson.cs
> +namespace Ryujinx.HLE.HOS.Services.Account.Acc.Types;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Account/Acc/Types/ProfilesJson.cs
> +namespace Ryujinx.HLE.HOS.Services.Account.Acc.Types;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Nfc/Nfp/AmiiboJsonSerializerContext.cs
> +namespace Ryujinx.HLE.HOS.Services.Nfc.Nfp;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationJsonSerializerContext.cs
> +namespace Ryujinx.Ui.App.Common;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormatSettings.cs
> +namespace Ryujinx.Ui.Common.Configuration;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Configuration/ConfigurationJsonSerializerContext.cs
> +namespace Ryujinx.Ui.Common.Configuration;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Amiibo/AmiiboApi.cs
> +namespace Ryujinx.Ui.Common.Models.Amiibo;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Amiibo/AmiiboApiGamesSwitch.cs
> +namespace Ryujinx.Ui.Common.Models.Amiibo;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Amiibo/AmiiboApiUsage.cs
> +namespace Ryujinx.Ui.Common.Models.Amiibo;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Amiibo/AmiiboJson.cs
> +namespace Ryujinx.Ui.Common.Models.Amiibo;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Amiibo/AmiiboJsonSerializerContext.cs
> +namespace Ryujinx.Ui.Common.Models.Amiibo;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Github/GithubReleaseAssetJsonResponse.cs
> +namespace Ryujinx.Ui.Common.Models.Github;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Github/GithubReleasesJsonResponse.cs
> +namespace Ryujinx.Ui.Common.Models.Github;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-01-27 20:20 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Github/GithubReleasesJsonSerializerContext.cs
> +namespace Ryujinx.Ui.Common.Models.Github;
Ryujinx does not use file-scoped namespaces, could you change these to fit the code style?

2023-02-11 20:27 UTC, SukharevAndrey commented on Ryujinx.Common/Utilities/JsonHelper.cs
> +                    if (i == 0 || char.IsUpper(name[i - 1]))
It was like that in the original code, i've changed nothing in it.

2023-02-11 21:01 UTC, SukharevAndrey commented on Ryujinx.Common/Utilities/JsonHelper.cs
> +    }
Reusing the same instance of JsonSerializerOptions in different contexts causes exception:
```
Unhandled exception. System.InvalidOperationException: JsonSerializerOptions instances cannot be modified once encapsulated by a JsonSerializerContext. Such encapsulation can happen either when calling 'JsonSerializerOptions.AddContext' or when passing the options instance to a JsonSerializerContext constructor.
```

2023-03-11 20:08 UTC, gdkchan commented on Ryujinx/Ui/Windows/TitleUpdateWindow.cs
> +using SpanHelpers = LibHac.Common.SpanHelpers;
Indentation is off here.

2023-03-11 20:11 UTC, SukharevAndrey commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +    private static readonly TitleUpdateMetadataJsonSerializerContext SerializerContext = new(JsonHelper.GetDefaultSerializerOptions());
There are not a lot of places like these. Creating base class just to introduce one variable there may be an overkill IMHO.

2023-03-11 20:18 UTC, SukharevAndrey commented on Ryujinx.Common/Utilities/JsonHelper.cs
> +                    if (i == 0 || char.IsUpper(name[i - 1]))
There will be native snake case support in JSON serializer in .NET 8 anyway.

2023-03-11 20:21 UTC, SukharevAndrey commented on Ryujinx.HLE/HOS/Services/Account/Acc/Types/UserProfileJson.cs
> +    public byte[] Image { get; set; }
Yeah, it is not necessary anymore. I've just copied it as it was. Anyway, deleted properties.

2023-03-11 20:22 UTC, SukharevAndrey commented
@TSRBerry Can you please check my answers and fixes?

2023-03-12 00:34 UTC, TSRBerry requested changes
Looks very good! Mostly some stylistic changes again and a few cases where we should be able to automatically get the property names as snake case.

Lgtm otherwise!

(And thank you for adding that rule to `.editorconfig`!)

2023-03-12 00:34 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +        Save();SortUpdates();
```suggestion
        Save();
        SortUpdates();
```

2023-03-12 00:34 UTC, TSRBerry commented on Ryujinx.Common/Logging/Formatters/DynamicObjectFormatter.cs
> +            StringBuilder sb = StringBuilderPool.Allocate();
```suggestion
            StringBuilder sb = StringBuilderPool.Allocate();
            
```

2023-03-12 00:34 UTC, TSRBerry commented on Ryujinx.Common/Logging/Formatters/DynamicObjectFormatter.cs
> +                return sb.ToString();
```suggestion

                return sb.ToString();
```

2023-03-12 00:34 UTC, TSRBerry commented on Ryujinx.Common/Logging/Formatters/DynamicObjectFormatter.cs
> +                    if (array is not null)
```suggestion

                    if (array is not null)
```

2023-03-12 00:34 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Account/Acc/Types/ProfilesJson.cs
> +        [JsonPropertyName("profiles")]
These can also be automatically converted to snake case, right?

2023-03-12 00:34 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Github/GithubReleaseAssetJsonResponse.cs
> +        [JsonPropertyName("name")]
Could probably also be automatically converted to snake case.

2023-03-12 00:34 UTC, TSRBerry commented on Ryujinx.Ui.Common/Models/Github/GithubReleasesJsonResponse.cs
> +        [JsonPropertyName("assets")]
Should also be converted to snake case automatically.

2023-03-19 12:33 UTC, SukharevAndrey commented
@TSRBerry Applied your suggestions. Review one more time please.

2023-03-19 13:42 UTC, TSRBerry commented
Sure! Just as a quick note in case you didn't know, you can re-request reviews by clicking this icon:
![image](https://user-images.githubusercontent.com/20988865/226179052-869a68f9-2602-4b7d-9c75-8a21c912bb75.png)

2023-03-19 13:48 UTC, TSRBerry approved these changes
Lgtm, thank you very much!

2023-03-21 11:37 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +
Please adjust the spacing here. There is a bunch of blank lines now that this code was removed.

2023-03-21 11:37 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +        Save();
This is not properly indented.

2023-03-21 11:37 UTC, gdkchan commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +
Remove white space (not the entire line).

2023-03-21 11:37 UTC, gdkchan commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +
Remove white space (not the entire line).

2023-03-21 19:52 UTC, gdkchan approved these changes
lgtm, thanks. Sorry for the delay.

2023-03-21 22:41 UTC, merged

2023-03-21 23:04 UTC, MetrosexualGarbodor commented
Apparently this change wipes config.json 
![image](https://user-images.githubusercontent.com/79612681/226761177-51cd1acc-ea22-428e-a939-e01ffd3b060f.png)
![image](https://user-images.githubusercontent.com/79612681/226761220-01116858-4926-45b9-9acb-bdc2a9fec6ea.png)

2023-03-21 23:17 UTC, gdkchan commented
Your change has been reverted because it was not able to parse existing configuration files causing existing configuration to be lost. If you still wish to work on this, please be sure to test it thoroughly and then submit a new pull request. Thank you.

2023-03-22 00:13 UTC, TSRBerry commented
@SukharevAndrey open a new PR and apply these two commits, these will fix all the issues we had.
I'd push them to your branch, but without a PR I don't have access to it.
[JsonFixes.patch.zip](https://github.com/Ryujinx/Ryujinx/files/11035064/JsonFixes.patch.zip)

2023-03-22 12:17 UTC, SukharevAndrey commented
@gdkchan @TSRBerry I'm deeply sorry for that. It seems I have not tested the latest version after all edits.
Here is the new PR: #4582

2023-03-22 12:31 UTC, TSRBerry commented
Don't worry about it too much.
I like to think as reviewers we are equally responsible to make sure it works as expected.