bsd::RecvFrom: verify output buffer size before writing socket address
Ryujinx/Ryujinx pull request #4135
Opened 2022-12-16 15:38 UTC by gnisman

bsd::RecvFrom: verify output buffer size (sockAddrOutSize) is non zero before writing socket address
fix for #3458

2022-12-16 19:11 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                        context.Memory.Write(sockAddrOutPosition, BsdSockAddr.FromIPEndPoint(endPoint));
Missing a check if `BsdSockAddr.FromIPEndPoint(endPoint)` fits into the output buffer.

2022-12-16 21:26 UTC, gnisman commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                        context.Memory.Write(sockAddrOutPosition, BsdSockAddr.FromIPEndPoint(endPoint));
Done

2022-12-17 13:01 UTC, marysaka requested changes

2022-12-17 13:01 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                    if (sockAddrOutSize != 0 && sockAddrOutSize >= (ulong) bsdSockAddr.Size())
From my understanding here you are only implementing BsdSockAddr.Size to get the size of a single element size, you can just use [Unsafe.SizeOf API](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.unsafe.sizeof?view=net-7.0).
```suggestion
                    if (sockAddrOutSize != 0 && sockAddrOutSize >= (ulong) Unsafe.SizeOf<BsdSockAddr>())
```

2022-12-17 13:01 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/Types/BsdSockAddr.cs
> +        }
See previous suggestion
```suggestion
```

2022-12-17 16:36 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                    if (sockAddrOutSize != 0 && sockAddrOutSize >= (ulong) Unsafe.SizeOf<BsdSockAddr>())
You should probably return an error if we can't write the address to memory.

2022-12-17 16:48 UTC, gnisman commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                    if (sockAddrOutSize != 0 && sockAddrOutSize >= (ulong) Unsafe.SizeOf<BsdSockAddr>())
Do you suggest to change the errno which is LinuxError enum? if so what should be the error?

2022-12-17 16:59 UTC, TSRBerry commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                    if (sockAddrOutSize != 0 && sockAddrOutSize >= (ulong) Unsafe.SizeOf<BsdSockAddr>())
`LinuxError.ENOMEM` sounds fitting, but I should add that I currently don't know if that's the way HOS deals with it.

2022-12-17 18:55 UTC, TSRBerry approved these changes
Lgtm, but another review should probably check if HOS deals with this at all and if so is this implementation correct?

2022-12-21 18:13 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                        context.Memory.Write(sockAddrOutPosition, bsdSockAddr);
```suggestion
                        context.Memory.Write(sockAddrOutPosition, BsdSockAddr.FromIPEndPoint(endPoint));
```

`bsdSockAddr` is a bit useless here since you don't use it elsewhere.

2022-12-21 19:14 UTC, gnisman commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +                        context.Memory.Write(sockAddrOutPosition, bsdSockAddr);
Agree, its a left over from before when i had bsdSockAddr.Size()

2022-12-26 10:43 UTC, marysaka approved these changes

2022-12-26 12:53 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Sockets/Bsd/IClient.cs
> +
```suggestion
```

2022-12-26 12:54 UTC, AcK77 approved these changes

2022-12-26 13:49 UTC, merged

2023-01-19 17:42 UTC, gdkchan commented
Could it fix #2393 too? It looks like the same problem but on a different function...