Restructure `Ryujinx.Ava`
Ryujinx/Ryujinx pull request #4165
Opened 2022-12-23 00:15 UTC by IsaacMarovitz

Superceeds part of #3997

2022-12-27 22:11 UTC, TSRBerry requested changes

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +        public AvaloniaList<Models.TimeZone> TimeZones { get; set; }
```suggestion
        public AvaloniaList<TimeZone> TimeZones { get; set; }
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            TimeZones = new AvaloniaList<Models.TimeZone>();
```suggestion
            TimeZones = new AvaloniaList<TimeZone>();
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                TimeZones.Add(new Models.TimeZone($"UTC{hours:+0#;-0#;+00}:{minutes:D2}", location, abbr2));
```suggestion
                TimeZones.Add(new TimeZone($"UTC{hours:+0#;-0#;+00}:{minutes:D2}", location, abbr2));
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +        private Models.UserProfile _highlightedProfile;
```suggestion
        private UserProfile _selectedProfile;
        private UserProfile _highlightedProfile;
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +            LostProfiles = new ObservableCollection<Models.UserProfile>();
```suggestion
            Profiles = new ObservableCollection<UserProfile>();
            LostProfiles = new ObservableCollection<UserProfile>();
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +        public ObservableCollection<Models.UserProfile> Profiles { get; set; }
```suggestion
        public ObservableCollection<UserProfile> Profiles { get; set; }
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +        public ObservableCollection<Models.UserProfile> LostProfiles { get; set; }
```suggestion
        public ObservableCollection<UserProfile> LostProfiles { get; set; }
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +        public Models.UserProfile SelectedProfile
```suggestion
        public UserProfile SelectedProfile
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +        public Models.UserProfile HighlightedProfile
```suggestion
        public UserProfile HighlightedProfile
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +                Profiles.Add(new Models.UserProfile(profile, _owner));
```suggestion
                Profiles.Add(new UserProfile(profile, _owner));
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +                LostProfiles.Add(new Models.UserProfile(new HLE.HOS.Services.Account.Acc.UserProfile(account, "", null), _owner));
```suggestion
                LostProfiles.Add(new UserProfile(new HLE.HOS.Services.Account.Acc.UserProfile(account, "", null), _owner));
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +            Models.UserProfile userProfile = null;
```suggestion
            UserProfile userProfile = null;
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +            Models.UserProfile userProfile = _highlightedProfile ?? SelectedProfile;
```suggestion
            UserProfile userProfile = _highlightedProfile ?? SelectedProfile;
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/UserProfileViewModel.cs
> +            Models.UserProfile userProfile = _highlightedProfile ?? SelectedProfile;
```suggestion
            UserProfile userProfile = _highlightedProfile ?? SelectedProfile;
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/SettingsWindow.axaml.cs
> +                if (box.SelectedItem != null && box.SelectedItem is Models.TimeZone timeZone)
```suggestion
                if (box.SelectedItem != null && box.SelectedItem is TimeZone timeZone)
```

2022-12-27 22:11 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/SettingsWindow.axaml.cs
> +                if (box.SelectedItem != null && box.SelectedItem is Models.TimeZone timeZone)
```suggestion
                if (box.SelectedItem != null && box.SelectedItem is TimeZone timeZone)
```

2022-12-27 22:49 UTC, TSRBerry commented on Ryujinx.Ava/UI/Helpers/EmbeddedWindow.cs
> +
I know it's not necessary, but I'd prefer to keep these as `else if`s to be explicit here.

2022-12-27 22:49 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> -        private float _previousVolumeLevel;
Wasn't this used in `SettingsWindow.axaml`?

2022-12-27 22:52 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> -        private float _previousVolumeLevel;
It's used in GTK UI, it is not used in Ava

2022-12-27 22:56 UTC, TSRBerry approved these changes
Lgtm, nicely done!

2022-12-28 15:17 UTC, emmauss approved these changes

2022-12-29 14:15 UTC, AcK77 approved these changes

2022-12-29 14:24 UTC, merged