Ava GUI: Settings Refactor
Ryujinx/Ryujinx pull request #4177
Opened 2022-12-25 15:38 UTC by IsaacMarovitz

**Changes:**
- `SettingsWindow` Refactored

Depends on #4165
Superceeds part of #3997

2022-12-29 18:42 UTC, AcK77 requested changes

2022-12-29 18:42 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                _customThemePath = value;
```suggestion
                _customThemePath = value;

```

2022-12-29 18:42 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/SettingsWindow.axaml.cs
> +                        NavPanel.Content = systemPage;
Same as above comment

2022-12-29 18:42 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/SettingsWindow.axaml.cs
> +                        NavPanel.Content = uiPage;
```suggestion
                        UiPage.ViewModel = ViewModel;
                        NavPanel.Content = UiPage;
```
Isn't doable?

2023-01-03 19:13 UTC, TSRBerry requested changes
Some formatting changes, but looks good otherwise.

Probably also needs a rebase now.

2023-01-03 19:13 UTC, TSRBerry commented on Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                    Dispatcher.UIThread.Post(Action);
Why did you replace this with a function?

2023-01-03 19:13 UTC, TSRBerry commented on Ryujinx.Ava/UI/Views/Settings/SettingsSystemView.axaml.cs
> +        tzMultiBinding.Bindings.Add(new Binding("UtcDifference"));
```suggestion

        tzMultiBinding.Bindings.Add(new Binding("UtcDifference"));
```

2023-01-03 19:13 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/SettingsWindow.axaml.cs
> +                switch(navitem.Tag.ToString())
```suggestion
                switch (navitem.Tag.ToString())
```

2023-01-03 19:17 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/SettingsWindow.axaml.cs
>              if (e.SelectedItem is NavigationViewItem navitem)
```suggestion
            if (e.SelectedItem is NavigationViewItem navItem && navItem.Tag is not null)
```
Change the name to `navItem` and since `navItem.Tag` is nullable add a null check.

2023-01-04 00:12 UTC, TSRBerry approved these changes
Lgtm!

2023-01-06 17:07 UTC, AcK77 approved these changes

2023-01-06 18:58 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/Models/TimeZone.cs
> -    internal class TimeZone
`TimeZone` is used in `SettingsViewModel` so a change in protection is necessary

2023-01-06 23:35 UTC, merged