Ava GUI: `MainWindow` Refactor
Ryujinx/Ryujinx pull request #4178
Opened 2022-12-25 19:02 UTC by IsaacMarovitz

**Changes:**
- `MainWindow` Refactored

**TODO:**
- [ ] Fix bindings

Depends on https://github.com/Ryujinx/Ryujinx/pull/4165
Superceeds part of https://github.com/Ryujinx/Ryujinx/pull/3997

2022-12-29 18:03 UTC, AcK77 requested changes

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +    //       However the new MenuItem does not use the same value for IsVisible as the child.
Is an issue opened somewhere about this issue ?

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Views/Main/MainViewControls.axaml.cs
> +            ViewModel.Sort(sort);
```suggestion
            ViewModel.Sort(Enum.Parse<ApplicationSort>(button.Tag.ToString()));
```

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Views/Main/MainViewControls.axaml.cs
> +            ViewModel.Sort(tag != "Descending");
```suggestion
            ViewModel.Sort(button.Tag.ToString() != "Descending");
```

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +
Extra spaces

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +
Extra spaces

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            if(content == null)
```suggestion
            if (content == null)
```

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            if(MainContent.Content != content)
```suggestion
            if (MainContent.Content != content)
```

2022-12-29 18:03 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +                ViewModel.StatusBarProgressValue           = 0;
```suggestion
                StatusBarView.LoadProgressBar.IsVisible = true;
                ViewModel.StatusBarProgressMaximum      = 0;
                ViewModel.StatusBarProgressValue        = 0;
```

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +        if (!string.IsNullOrWhiteSpace(contentPath))
Maybe you meant using `IsNullOrEmpty` here? Not sure why the path would be just white space.

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +        #region Properties
In other places where we use `#region`, is it not indented.

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                if (IsGridSmall)
Why can't this just do `return ConfigurationState.Instance.Ui.GridSize switch ...`?

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                    LocaleManager.Instance["RyujinxConfirm"]);
Wonder why this key is called `RyujinxConfirm` rather than `InputDialogConfirm`...

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                catch (Exception) { }
Why is that just catching all exceptions here? I guess it makes the `throw new ArgumentException($"Unknown Progress Handler type {typeof(T)}");` above pointless?

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                // otherwise, clear state.
```suggestion
                // Otherwise, clear state.
```

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                        new SolidColorBrush(Color.Parse("#ff2eeac9")) :
Shouldn't those come from the current theme?

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                if (!string.IsNullOrWhiteSpace(folder))
Same comment about `IsNullOrWhiteSpace`.

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +            AppHost = new AppHost(RendererControl, InputManager, path, VirtualFileSystem, ContentManager, AccountManager, UserChannelPersistence, this, TopLevel);
Line is too long, consider putting the arguments on separate lines.

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/Views/Main/MainStatusBarView.axaml.cs
> +        ConfigurationState.Instance.Graphics.AspectRatio.Value = (int)aspectRatio + 1 > Enum.GetNames(typeof(AspectRatio)).Length - 1 ? AspectRatio.Fixed4x3 : aspectRatio + 1;
Why does this default to 4x3 when the value is invalid? Should it not be 16x9 which is the standard  aspect ratio?

2023-01-01 15:47 UTC, gdkchan commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +    {
```suggestion
    {
```
I recommend configuring your IDE to remove trailing whitespace automatically if you can.

2023-01-01 16:22 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/Views/Main/MainStatusBarView.axaml.cs
> +        ConfigurationState.Instance.Graphics.AspectRatio.Value = (int)aspectRatio + 1 > Enum.GetNames(typeof(AspectRatio)).Length - 1 ? AspectRatio.Fixed4x3 : aspectRatio + 1;
`AspectRatio.Fixed4x3` is the first value in the enum. This is mean to cycle through all the values in the enum so it makes sense to return to `Fixed4x3` when the value becomes out of range.

2023-01-01 16:36 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                    LocaleManager.Instance["RyujinxConfirm"]);
It includes `Ryujinx - `in the string all other window title names follow the same convention.

2023-01-04 21:34 UTC, AcK77 approved these changes

2023-01-07 17:49 UTC, marysaka approved these changes

2023-01-07 17:50 UTC, marysaka commented
Need a final rebase

2023-01-08 17:46 UTC, merged