IPC refactor part 3 + 4: New server HIPC message processor
Ryujinx/Ryujinx pull request #4188
Opened 2022-12-28 21:40 UTC by gdkchan

This is resurrecting #1749, this time no reflection is used, instead it uses source generators.

The main problem with the previous PR is that it made a lot of changes on existing services to adapt them to the new IPC system, and it turned into a maintenance nightmare. So this time the plan is manually migrating the services to the new system. The current SM services already allows for proper service registration (using `RegisterService`) and the lookup that is done for HLE services. That was implemented to allow LLE services to work with HLE ones back then. Services that are registered with `RegisterService` always override the HLE ones, so it makes use of that here to register the new service implementation and replace the old one. This also means if there's some regression we don't need to revert all changes, we can simply stop registering the new service to get back the old behaviour.

Naturally, since the existing HLE services don't register themselves on SM, and requires special handling on SM to look them up, we can't replace SM right now. It will only be possible to replace SM after all other services are migrated to the new system, and the reflection based lookup is no longer needed.

Key benefits of this change:
- Cleaner service implementations since we no longer need to manually read and write values to the message buffer.
- More accurate since messages are actually validated and it returns errors if they are invalid.
- More performance since the new code avoids several allocations and copies.
- It should allow multiple IPC processing threads, which should fix some bugs and improve performance in some cases, but that was not tested yet.

Currently only the LM (LogManager) was migrated to the new IPC system. It was chosen because it is very simple and its outputs are easily visible (the only thing it does is writing to the log). The plan is migrating more services after this is merged, and extending/fixing (?)/updating the code as necessary.

I started writing some guidelines which those wiling to help with this task can read:
[https://gist.github.com/gdkchan/84ba88cd50efbe58d1babfaa7cd7c455](https://gist.github.com/gdkchan/84ba88cd50efbe58d1babfaa7cd7c455)

Testing is welcome. We need to make sure it does not cause regressions in any games. Since it only replaces LM right now, I would recommend testing games that prints "guest logs" in the log.

2022-12-29 01:37 UTC, TSRBerry commented on Ryujinx.Horizon.Common/KernelResult.cs
> +        public static Result CmdBufferTooSmall => new Result(ModuleId, 260);
Would it make sense to change these to auto properties, so they are only evaluated once?

2022-12-29 02:24 UTC, gdkchan commented on Ryujinx.Horizon.Common/KernelResult.cs
> +        public static Result CmdBufferTooSmall => new Result(ModuleId, 260);
This is an interesting question. The current code can actually be optimized to a constant by the JIT, while using a auto property forces it to load the value from memory, so the current approach is better for performance.
https://godbolt.org/z/9q1a7ndGY
```cs
    public static Result ResultA => new Result(8, 9);
    public static Result ResultB { get; } = new Result(8, 9);
```
```nasm
C:get_ResultA():Result:
       mov      eax, 0x1208
       ret      

C:get_ResultB():Result:
       push     rax
       call     [CORINFO_HELP_READYTORUN_STATIC_BASE]
       mov      rax, gword ptr [rax]
       mov      eax, dword ptr [rax+08H]
       add      rsp, 8
       ret 
```

2022-12-29 12:30 UTC, TSRBerry commented on Ryujinx.Horizon.Common/KernelResult.cs
> +        public static Result CmdBufferTooSmall => new Result(ModuleId, 260);
That's awesome! Thank you for testing!

2022-12-29 12:42 UTC, TSRBerry commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +            AppendLine("}" + suffix);
Based on #3933, although it's probably not relevant here.
```suggestion
            AppendLine($"}}{suffix}");
```

2022-12-29 15:04 UTC, marysaka reviewed
Overall very clean, but some codepath that aren't implemented should have documentation about what is missing or be removed and added back on a newer iteration.

Various struct have warnings for unused fields too and should be addressed.

I do think the gist in the description of the PR should be added in some docs directory for future reference

2022-12-29 15:04 UTC, marysaka commented on Ryujinx.Horizon/Sdk/Sf/Hipc/BitfieldExtensions.cs
> +}
Could be nice to have in the common project?

2022-12-29 16:04 UTC, AcK77 requested changes

2022-12-29 16:04 UTC, AcK77 commented on Ryujinx.Horizon/Sm/ManagerService.cs
> +    }
```suggestion
    partial class ManagerService : IServiceObject { }
```

2022-12-29 16:04 UTC, AcK77 commented on Ryujinx.Horizon.Common/ResultNames.cs
> +    static class ResultNames
I'm not a huge fan of this, since it could be outdated easily. Maybe we should do something else instead.

2022-12-29 16:07 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Writer.cs
> +}
It will likely need more overloads to be useful in general (like a write method that takes spans and one that takes offsets). But I could move it as-is and it can be extended later.

2022-12-29 16:08 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/DebugUtil.cs
> +        public static void Assert(bool condition)
I think this is supposed to trigger the error applet and error reporting, but I can add a 'Debug.Assert' for now which is better than keeping it empty.

2022-12-29 16:11 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Sf/Hipc/BitfieldExtensions.cs
> +}
I think there's something similar in other projects, maybe I could consolidate it.

2022-12-29 16:12 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            return CreatePort(out serverPortHandle, out clientPortHandle, maxSessions, isLight, null);
The kernel does not actually use this name (pointer) for anything, so I think it's better to keep it as null since the address might be invalid.

2022-12-29 16:13 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            return CreatePort(out serverPortHandle, out clientPortHandle, maxSessions, isLight, null);
Or at least the current implementation does not. But AFAIK it's unused on the official kernel too.

2022-12-29 16:14 UTC, TSRBerry commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +            AppendLine("}" + suffix);
Otherwise $"" wouldn't work

2022-12-29 16:14 UTC, AcK77 commented on Ryujinx.Horizon.Generators/CodeGenerator.cs
> +            AppendLine("}" + suffix);
True! Sorry!

2022-12-29 16:15 UTC, gdkchan commented on Ryujinx.Horizon.Common/InvalidResultException.cs
> +        }
This is not consistent right now, for example see https://github.com/Ryujinx/Ryujinx/blob/master/ARMeilleure/Memory/InvalidAccessException.cs
It would be nice to have a set style to follow.

2022-12-29 16:15 UTC, AcK77 commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            return CreatePort(out serverPortHandle, out clientPortHandle, maxSessions, isLight, null);
Maybe it could be nice to add a comment about that ?

2022-12-29 16:17 UTC, AcK77 commented on Ryujinx.Horizon.Common/InvalidResultException.cs
> +        }
I'd prefer ` { }` is the method is empty, but both are fine to me.

2022-12-29 16:24 UTC, gdkchan commented on Ryujinx.Horizon.Common/ResultNames.cs
> +    static class ResultNames
Like what? I don't think there's a way around this other than depending on another project for those names. But then we depend on that other project being updated. Until someone manages to find all result names it's going to be like that.

Maybe a source generator could be used to collect the names from the result classes we're actually using, and build the dictionary from that, but then we'd need to have all the results defined there. And it feels like it's quite a lot of work for something that is supposed to be simple.

2022-12-29 16:28 UTC, gdkchan commented on Ryujinx.Horizon.Common/InvalidResultException.cs
> +        }
Personally I prefer
```cs
{
}
```
Since it's more consistent with what we do (curly braces on new line rather than on the same line). Empty methods doesn't need to be a exception of that rule. But I don't have a strong preference.

2022-12-29 16:44 UTC, AcK77 commented on Ryujinx.Horizon.Common/ResultNames.cs
> +    static class ResultNames
This can be done later then

2022-12-29 17:10 UTC, AcK77 commented
Fixes https://github.com/Ryujinx/Ryujinx/issues/913 ?

2022-12-29 17:22 UTC, EmulationFanatic commented
> Fixes #913 ?

Only the third checkbox of the to-do list. Modifying the services afterward will then resolve the issue fully.

2023-01-01 03:50 UTC, gdkchan commented on Ryujinx.HLE/HOS/Horizon.cs
> +                // them here.
The line is already very long, if I change this I won't be able to read the full line without scrolling here.
![image](https://user-images.githubusercontent.com/5624669/210160564-533f71e6-2f7d-471b-b810-da42840dedc4.png)

2023-01-01 04:04 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/OsTypes/Event.cs
> +}
I implemented using .NET `Monitor` since using the HLE kernel condition variables would require having memory pointers on the address space, which would require allocations, it would make it a lot more complicated to use for no good reason.

2023-01-01 04:05 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/OsTypes/OsThreadManager.cs
> +            return 0;
It is required to cancel the `MultiWait`, it needs the thread handle to call `CancelSynchronization`. It is implemented now, although I didn't have the chance to test it yet.

2023-01-01 04:06 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Sf/Hipc/BitfieldExtensions.cs
> +}
I moved it to `Ryujinx.Common.Utilities` and also replaced the `BitfieldExtensions` implementation in other projects with the one in common. Also implemented it using generic math so it should be available for all integer types now, rather than just `int`.

2023-01-01 04:11 UTC, gdkchan commented on Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +            KPort port = new KPort(_context, maxSessions, false, null);
The previous code was passing `0` as the pointer. I just changed it to `null` because it stores a string rather than a pointer now. But otherwise the code didn't change. This matches what the official kernel does. It uses the name later on to add to a dictionary.

2023-01-01 04:12 UTC, gdkchan commented on Ryujinx.Horizon/LogManager/LmLogger.cs
> +        private ref struct Reader
I renamed it to `SpanReader`, added a few more useful methods and moved to `Ryujinx.Common.Memory`.

2023-01-01 04:12 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/OsTypes/EventType.cs
> +        public ulong BroadcastCounter;
Should now have warnings anymore since it's actually used now.

2023-01-01 04:13 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Writer.cs
> +}
I renamed it to `SpanWriter`, added a few more useful methods and moved to `Ryujinx.Common.Memory`.

2023-01-01 04:14 UTC, gdkchan commented on Ryujinx.Horizon.Common/InvalidResultException.cs
> +        }
I did not change it for now due to the lack of a consensus on the style of those across the project.

2023-01-01 04:14 UTC, gdkchan commented
I believe all feedback should be addressed, I commented on the ones that I didn't.

2023-01-01 04:51 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Sf/Cmif/InlineContext.cs
> +            // TODO: Implement (will require FS changes???)
Yes. I suppose it's going to be useless until we update the FS implementation to make use of it.

2023-01-02 11:38 UTC, marysaka commented on Ryujinx.HLE/HOS/Horizon.cs
> +                // them here.
I would align the "them here with "Have the ThreadStart" as it's part of that point

2023-01-02 11:39 UTC, marysaka commented on Ryujinx.Horizon.Common/InvalidResultException.cs
> +        }
See https://github.com/Ryujinx/Ryujinx/pull/4188#discussion_r1059703908

2023-01-02 11:39 UTC, marysaka commented on Ryujinx.Horizon.Common/InvalidResultException.cs
> +        }
See https://github.com/Ryujinx/Ryujinx/pull/4188#discussion_r1059703908

2023-01-02 11:39 UTC, marysaka commented on Ryujinx.Horizon/Sdk/Sf/CommandArgAttributes.cs
> +    }
See https://github.com/Ryujinx/Ryujinx/pull/4188#discussion_r1059703908

2023-01-02 11:39 UTC, marysaka commented on Ryujinx.Horizon/Sdk/Sf/CommandArgAttributes.cs
> +    }
See https://github.com/Ryujinx/Ryujinx/pull/4188#discussion_r1059703908

2023-01-02 11:39 UTC, marysaka commented on Ryujinx.Horizon/Sm/ManagerService.cs
> +    }
See https://github.com/Ryujinx/Ryujinx/pull/4188#discussion_r1059703908

2023-01-02 11:39 UTC, marysaka commented on Ryujinx.Horizon/Sdk/Sf/CommandArgAttributes.cs
> +    }
See https://github.com/Ryujinx/Ryujinx/pull/4188#discussion_r1059703908

2023-01-02 11:39 UTC, marysaka commented on Ryujinx.Horizon.Common/InvalidResultException.cs
> +        }
See https://github.com/Ryujinx/Ryujinx/pull/4188#discussion_r1059703908

2023-01-02 11:40 UTC, marysaka commented on Ryujinx.Horizon.Common/ResultNames.cs
> +    static class ResultNames
An issue would be nice to open.

2023-01-02 11:41 UTC, marysaka approved these changes
Apart from the conversations still opened, lgtm

Could you add the gist in a documentation folder?

2023-01-02 13:31 UTC, gdkchan commented on Ryujinx.Horizon.Common/ResultNames.cs
> +    static class ResultNames
What exactly would be on the issue? I'm still not sure what's the plan to replace this.

2023-01-02 13:35 UTC, gdkchan commented
> Could you add the gist in a documentation folder?

I would prefer to do that when it's more complete. The gist is easy to update right now. As a side note it would be nice to move the projects and solution to a `src` sub-folder, it's kind of messy to have the docs in the same folder as the solution and all projects.

2023-01-04 17:12 UTC, lostromb commented
Tested a few games and paid attention to the logger output. Can't notice any regression or difference in the messages being printed.

I know I played a game recently that was dumping a lot of really big guest logs, I'm going to try and find that again to see if there's any buffer overflow issues or whatever

2023-01-04 21:11 UTC, AcK77 approved these changes
Just 2 suggested changes. Instead of them, it's LGTM! Awsome works!!

2023-01-04 21:11 UTC, AcK77 commented on Ryujinx.HLE/HOS/Horizon.cs
> +                //   them here.
```suggestion
                // - Have the ThreadStart function take the syscall, address space and thread context parameters instead of passing them here.
```

2023-01-04 21:11 UTC, AcK77 commented on Ryujinx.Horizon/Sdk/OsTypes/MultiWaitHolderOfEvent.cs
> +                return _event.IsSignaledThreadUnsafe();
```suggestion

                return _event.IsSignaledThreadUnsafe();
```

2023-01-04 22:15 UTC, merged