misc: Uses official names for NVDEC registers
Ryujinx/Ryujinx pull request #4192
Opened 2022-12-29 22:06 UTC by marysaka

As title say.

2022-12-29 22:12 UTC, gdkchan commented on Ryujinx.Graphics.Nvdec/Vp9Decoder.cs
> +            using var mvsRegion = rm.Gmm.GetWritableRegion(ExtendOffset(state.Vp9SetColMvReadBufOffset), miRows * miCols * 16);
Something seems off here since it's going to write to the "Read" buffer, and it's reading form the "Write" buffer.

2022-12-29 22:13 UTC, TSRBerry approved these changes
Lgtm!

2022-12-29 22:30 UTC, gdkchan approved these changes
lgtm, thanks.

2022-12-29 23:56 UTC, AcK77 requested changes

2022-12-29 23:56 UTC, AcK77 commented on Ryujinx.Graphics.Nvdec/FrameDecodedEventArgs.cs
> +        public ApplicationId CodecId { get; }
Maybe rename the var too?

2022-12-29 23:56 UTC, AcK77 commented on Ryujinx.Graphics.Nvdec/FrameDecodedEventArgs.cs
> +        internal FrameDecodedEventArgs(ApplicationId codecId, uint lumaOffset, uint chromaOffset)
Maybe rename the var too?

2022-12-29 23:56 UTC, AcK77 commented on Ryujinx.Graphics.Nvdec/NvdecDevice.cs
> +        private void Decode(ApplicationId codecId)
Maybe rename the var too?

2022-12-31 06:28 UTC, gdkchan commented
I guess that the comment
```cs
// Note: Most of those names are not official.
```
can be removed?

2023-01-01 15:03 UTC, marysaka commented
Ready for review again

2023-01-01 15:11 UTC, gdkchan commented on Ryujinx.Graphics.Nvdec/FrameDecodedEventArgs.cs
>      public readonly struct FrameDecodedEventArgs
That struct is unused, it can be removed.

2023-01-02 14:48 UTC, AcK77 approved these changes

2023-01-02 14:48 UTC, merged