Ava GUI: `AboutWindow` Refactor
Ryujinx/Ryujinx pull request #4196
Opened 2023-01-01 15:46 UTC by IsaacMarovitz

**Changes:**
- Moves `AboutWindow` to a `ContentDialog`
- Update logos and fix light theme
- Redesign layout slightly
- Add a `ViewModel` and switch `AboutWindow` to compiled bindings

<img width="1392" alt="Screenshot 2023-01-01 at 16 46 40" src="https://user-images.githubusercontent.com/42140194/210176718-720ee53d-19ec-485b-94c1-4364335acfa5.png">

2023-01-06 16:07 UTC, AcK77 commented
Quick "design" review (I'll take a look to the code after):

![image](https://user-images.githubusercontent.com/4905390/211049812-8ada1394-d419-48a5-ad62-fbdcb2f6c169.png)

- The Ryujinx's version have to be put on the top of the space behind the logo (see the modified screenshot above).
- The button `See All Contributors` have to be put at the left (see the modified screenshot above).
- There are strange spacing between textblocks (like the `Maintained By:` one).
- The last text line of the patrons list is cutted:
![image](https://user-images.githubusercontent.com/4905390/211050449-a5b168a9-e3c3-4878-ba1b-cded0fa2af50.png)
- Tooltips on link buttons are missing.
- Thog's name is "marysaka" now.

2023-01-06 16:12 UTC, AcK77 requested changes
Some changes here and there.
Maybe we should name white logos > `Logo_Dummy_White` instead of `Light`, same for `Dark` > `Black` ?

2023-01-06 16:12 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/AboutWindowViewModel.cs
> +            get => string.Format(LocaleManager.Instance[LocaleKeys.AboutPageDeveloperListMore], "gdkchan, Ac_K, Thog, rip in peri peri, LDj3SNuD, emmaus, Thealexbarney, Xpl0itR, GoffyDude, »jD«");
```suggestion
            get => string.Format(LocaleManager.Instance[LocaleKeys.AboutPageDeveloperListMore], "gdkchan, Ac_K, marysaka, rip in peri peri, LDj3SNuD, emmaus, Thealexbarney, Xpl0itR, GoffyDude, »jD«");
```

2023-01-06 16:12 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/AboutWindowViewModel.cs
> +            } else
```suggestion
            }
            else
```

2023-01-06 16:12 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/AboutWindow.axaml.cs
>          private void AmiiboLabel_OnPointerPressed(object sender, PointerPressedEventArgs e)
Not related to that part of code, but maybe we should do something to show the amiibo website link is clickable.

2023-01-07 00:00 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/AboutWindowViewModel.cs
> +            get => string.Format(LocaleManager.Instance[LocaleKeys.AboutPageDeveloperListMore], "gdkchan, Ac_K, marysaka, rip in peri peri, LDj3SNuD, emmaus, Thealexbarney, Xpl0itR, GoffyDude, »jD«")
```suggestion
            get => string.Format(LocaleManager.Instance[LocaleKeys.AboutPageDeveloperListMore], "gdkchan, Ac_K, marysaka, rip in peri peri, LDj3SNuD, emmaus, Thealexbarney, GoffyDude, TSRBerry, IsaacMarovitz");
```

2023-01-07 00:09 UTC, AcK77 approved these changes

2023-01-07 00:10 UTC, marysaka approved these changes

2023-01-07 00:29 UTC, merged

2023-02-12 21:18 UTC, Foul-Tarnished commented
why the uppercase for "By" hmmm