Implement `GetTitleId`
Ryujinx/Ryujinx pull request #4210
Opened 2023-01-05 16:39 UTC by IsaacMarovitz

Fixes #2516

2023-01-10 07:21 UTC, marysaka approved these changes
Not technically correct but I think that will do for now.

2023-01-10 14:58 UTC, TSRBerry commented
> Not technically correct but I think that will do for now.

Hm if it's not a stub do we want to have stuff in master that's not correct?

2023-01-12 07:13 UTC, marysaka commented
> > Not technically correct but I think that will do for now.
> 
> Hm if it's not a stub do we want to have stuff in master that's not correct?

It is not correct as it shouldn't be directly using kernel objects here.
Making it an accurate implementation would require implementing the register interface part and ensure we register every processes started with it.

2023-01-13 00:54 UTC, AcK77 requested changes
If you apply my 2 suggestions then you can remove the change in KernelStatic.

2023-01-13 00:54 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pm/IInformationInterface.cs
> +            if (process != null)
```suggestion
            // TODO: Not correct as it shouldn't be directly using kernel objects here
            if (context.Device.System.KernelContext.Processes.TryGetValue(pid, out KProcess process))
```

2023-01-13 00:54 UTC, AcK77 commented on Ryujinx.HLE/HOS/Services/Pm/IDebugMonitorInterface.cs
> +            }
```suggestion
            // TODO: Not correct as it shouldn't be directly using kernel objects here
            foreach (KProcess process in context.Device.System.KernelContext.Processes.Values)
            {
                if (process.IsApplication)
                {
                    context.ResponseData.Write(process.Pid);

                    return ResultCode.Success;
                }
            }
```

2023-01-15 21:16 UTC, AcK77 approved these changes

2023-01-15 21:16 UTC, merged