Ava GUI: Various Fixes
Ryujinx/Ryujinx pull request #4268
Opened 2023-01-11 15:29 UTC by IsaacMarovitz

- Fixed SaveManager bug in #4166 
- Allow save size to be formatted as KB and GB
- Move SearchBox in #4223 fix to `Styles`

2023-01-11 17:08 UTC, AcK77 requested changes

2023-01-11 17:08 UTC, AcK77 commented on Ryujinx.Ava/UI/Models/SaveModel.cs
> +                    return $"{decimal.Divide(Size, max):##.##} {order}";
```suggestion
                if ( Size > max )
                {
                    return $"{decimal.Divide(Size, max):##.##} {order}";
                }
```

2023-01-11 17:08 UTC, AcK77 commented on Ryujinx.Ava/UI/Models/SaveModel.cs
> +            string[] orders = { "GB", "MB", "KB" };
```suggestion
            string[] orders = { "GiB", "MiB", "KiB" };
```
In a way to follow what have been done in https://github.com/Ryujinx/Ryujinx/pull/3716

2023-01-11 17:08 UTC, AcK77 commented on Ryujinx.Ava/UI/Models/SaveModel.cs
> +            return "0 KB";
```suggestion
            return "0 KiB";
```
In a way to follow what have been done in https://github.com/Ryujinx/Ryujinx/pull/3716

2023-01-11 18:54 UTC, AcK77 approved these changes
Lgtm! Thanks!

2023-01-12 07:35 UTC, marysaka approved these changes

2023-01-12 12:23 UTC, merged