Ava UI: `TitleUpdateWindow` Refactor
Ryujinx/Ryujinx pull request #4276
Opened 2023-01-12 14:55 UTC by IsaacMarovitz

- Switches to using compiled bindings
- Moves `TitleUpdateWindow` to a content dialogue
- Updates layout to match rest of Ava UI

Folder opener should be done programmatically on macOS when #4286 is merged

<img width="1392" alt="Screenshot 2023-01-12 at 22 06 30" src="https://user-images.githubusercontent.com/42140194/212227986-325392a6-8ccc-47bb-8d5c-d34c52e9e9fc.png">

2023-01-13 00:08 UTC, AcK77 commented
UI Review:

- "No Update" item have a smaller height than other item:
![image](https://user-images.githubusercontent.com/4905390/212206685-0931cca4-89e2-4459-a917-1d6921a4d834.png)
- The selector of the selected update isn't obvious enough.
- If you remove a selected update, it should select the more recent update or "no update".
- Maybe add a yes/no popup when you remove an update.
- There is no "Remove All" button.
- The height of the update list should fit the items, currently there is a useless space if you scroll at the end:
![image](https://user-images.githubusercontent.com/4905390/212207090-5db9dc2a-942b-466a-b6d1-17f16f7bd78c.png)
- Maybe you can reduce the width of the dialog.

2023-01-13 04:50 UTC, AcK77 requested changes
Thanks for all the UI fixes, that look pretty nice, sadly the "auto-scroll" doesn't seems to work.

2023-01-13 04:50 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
>              if (selection != null)
```suggestion
            if (SelectedApplication != null)
```

2023-01-13 04:50 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                await TitleUpdateWindow.Show(VirtualFileSystem, ulong.Parse(selection.TitleId, NumberStyles.HexNumber), selection.TitleName);
```suggestion
                await TitleUpdateWindow.Show(VirtualFileSystem, ulong.Parse(SelectedApplication.TitleId, NumberStyles.HexNumber), SelectedApplication.TitleName);
```

2023-01-13 04:50 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +    private string              _titleName { get; }
```suggestion
    private VirtualFileSystem  _virtualFileSystem { get; }
    private ulong              _titleId           { get; }
    private string             _titleName         { get; }
```

2023-01-13 04:50 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +        catch
Maybe we should add a Logging and a `CreateErrorDialog` here instead of silent the error, even if populate en empty list is fine.

2023-01-13 04:50 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +                        await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance[LocaleKeys.DialogUpdateAddUpdateErrorMessage]);
Maybe we should add a Logging too.

2023-01-13 04:50 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +                    await ContentDialogHelper.CreateErrorDialog(string.Format(LocaleManager.Instance[LocaleKeys.DialogDlcLoadNcaErrorMessage], ex.Message, path));
Maybe we should add a Logging too.

2023-01-13 18:41 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +                        await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance[LocaleKeys.DialogUpdateAddUpdateErrorMessage]);
`CreateErrorDialog` automatically logs errors

2023-01-13 18:42 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +                    await ContentDialogHelper.CreateErrorDialog(string.Format(LocaleManager.Instance[LocaleKeys.DialogDlcLoadNcaErrorMessage], ex.Message, path));
`CreateErrorDialog` automatically logs errors

2023-01-14 03:26 UTC, AcK77 approved these changes
The "auto-scroll" still doesn't seems to work but I think there is nothing we can do 😕

2023-01-14 03:26 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +            _titleUpdateWindowData = new TitleUpdateMetadata
```suggestion

            _titleUpdateWindowData = new TitleUpdateMetadata
```

2023-01-15 10:30 UTC, marysaka approved these changes

2023-01-15 11:11 UTC, merged