`NativeMacOS` Helper Class
Ryujinx/Ryujinx pull request #4286
Opened 2023-01-14 05:03 UTC by IsaacMarovitz

2023-01-14 13:14 UTC, merryhime commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +        public static partial IntPtr CFStringCreateWithBytes(IntPtr allocator, IntPtr buffer, long bufferLength, CFStringEncoding encoding, [MarshalAs(UnmanagedType.Bool)]bool isExternalRepresentatio
`CFStringCreateWithBytes` and `CFRelease` are not found in Foundation.framework, they're in CoreFoundation.framework.

2023-01-14 13:15 UTC, merryhime commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +        public static partial IntPtr NSSelectorFromString(IntPtr cfstr);
`NSSelectorFromString` and `objc_getClass` do not exist in AppKit.framework

2023-01-14 13:16 UTC, merryhime commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +        [LibraryImport(FoundationFramework)]
`objc_msgSend` is not in `Foundation.framework`, that's part of the base Objective C runtime in the `libobjc.dylib`.

2023-01-14 13:16 UTC, merryhime commented
For future reference, if you're unsure about what symbols are contained in each library, you can dump them with `nm`.

2023-01-14 13:26 UTC, merryhime commented on Ryujinx.Ava/UI/Helpers/MetalHelper.cs
> +            NativeMacOS.objc_msgSend(child, "setWantsLayer:", 1);
1 requires byte cast.

2023-01-14 13:28 UTC, merryhime commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +        public static partial IntPtr objc_getClass(string name);
I am fairly certain that `StringMarshalling.Utf16` is incorrect here.

2023-01-14 17:24 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/Helpers/MetalHelper.cs
> +            NativeMacOS.objc_msgSend(child, "setWantsLayer:", 1);
Cast is redundant

2023-01-14 18:53 UTC, merryhime commented on Ryujinx.Ui.Common/Helper/OpenHelper.cs
> +                NativeMacOS.CFRelease(sharedWorkspace);
This is a shared object that shouldn't be released.

2023-01-14 19:18 UTC, merryhime commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> -                CFRelease(StrPtr);
You're using a CF object here, which has different rules to an NS object. You would likely want to do an `CFBridgingRelease` if you want to use CF objects in an NS context.

2023-01-15 10:35 UTC, marysaka approved these changes

2023-01-15 10:35 UTC, marysaka commented on Ryujinx.Ava/UI/Helpers/MetalHelper.cs
> -
This shouldn't be removed even if it's unused.

2023-01-15 10:35 UTC, marysaka commented on Ryujinx.Ava/UI/Helpers/EmbeddedWindow.cs
> -        }
This call shouldn't be removed even if unused atm.

2023-01-15 11:50 UTC, merryhime commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +            public static implicit operator Selector(string value) => new (value);
```suggestion
            public static implicit operator Selector(string value) => new(value);
```

Searching the codebase, it seems the codestyle is to not have a space here.

2023-01-15 11:52 UTC, merryhime approved these changes
Otherwise lgtm as per comments above.

2023-01-15 19:42 UTC, AcK77 requested changes

2023-01-15 19:42 UTC, AcK77 commented on Ryujinx.Ui.Common/Helper/OpenHelper.cs
> +                    NativeMacOS.objc_msgSend(sharedWorkspace, "activateFileViewerSelectingURLs:", urlArray);
If Metal helper method are stored in `NativeMacOS` maybe you should do one `ActivateFileViewerSelectingURL` with the path as arg and then call `NativeMacOS.ActivateFileViewerSelectingURL(path)` here instead.

2023-01-15 19:42 UTC, AcK77 commented on Ryujinx.Ui.Common/Helper/OpenHelper.cs
> +                NativeMacOS.bool_objc_msgSend(sharedWorkspace, "openURL:", nsUrl);
If Metal helper method are stored in `NativeMacOS` maybe you should do one `OpenURL` with the url as arg and then call `NativeMacOS.OpenURL(url)` here instead.

2023-01-20 20:35 UTC, AcK77 requested changes

2023-01-20 20:35 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/MetalHelper.cs
> +            IntPtr layerClass = NativeMacOS.objc_getClass("CAMetalLayer");
`GetMetalLayer` should be moved to https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs directly and the helper should be removed. We use Win32 call in `EmbeddedWindow` and we don't use an helper for that.

2023-01-20 20:35 UTC, AcK77 commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +        public static void OpenURL(string path)
This should be moved in `Ryujinx.Ui.Common/Helper/OpenHelper.cs`

2023-01-20 20:35 UTC, AcK77 commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +        public static void ActivateFileViewerSelectingURL(string path)
This should be moved in `Ryujinx.Ui.Common/Helper/OpenHelper.cs`. The name is a bit strange even it take the macOS name.

2023-01-27 18:22 UTC, AcK77 approved these changes

2023-01-27 18:37 UTC, gdkchan commented on Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs
> +            // TODO
Why was this removed?

2023-01-27 18:40 UTC, gdkchan commented on Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs
> +            _updateBoundsCallback = rect => {
```suggestion
            _updateBoundsCallback = rect =>
            {
```

2023-01-27 18:40 UTC, gdkchan commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +    public static partial class NativeMacOS
Maybe it should be called `ObjectiveC` or something like thaat? Since it seems to just be ObjectiveC bindings.

2023-01-27 18:40 UTC, gdkchan commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +            public double X;
Maybe t hose can be `readonly`?

2023-01-27 18:40 UTC, gdkchan commented on Ryujinx.Ui.Common/Helper/NativeMacOS.cs
> +            public NSPoint Pos;
Maybe t hose can be `readonly`?

2023-01-27 21:52 UTC, IsaacMarovitz commented on Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs
> +            // TODO
The function was empty, and I was removing the entire helper class. If an implementation is ever created for that, it should be done within `EmbeddedWindow.cs`

2023-02-09 03:08 UTC, merged