Move Ryujinx Folder from ~/.config to ~/Library/Application Support on macOS
Ryujinx/Ryujinx pull request #4296
Opened 2023-01-15 03:29 UTC by Candygoblen123

This change makes Ryujinx more consistent with other apps on macOS. This PR also implements automatic migration of Ryujinx data from the old path to the new one, whenever Ryujinx detects the old data directory exists, but the new one does not.

2023-01-15 03:52 UTC, merryhime commented
It would be helpful to somehow mark the old directory as having been copied from, otherwise intentionally deleted files will be magically recreated from older copies (e.g. by renaming the directory to `Ryujinx.old` or similar).

2023-01-15 03:58 UTC, Candygoblen123 commented
Right now it checks if the path `~/Library/Application Support/Ryujinx` exists, and if it does exist it does nothing. That should be sufficient in preventing intentionally deleted files from being magically recreated. However I can rename the directory as well (or it might be better to create a hidden file, called `.migrated` or something, that marks if the dir has been migrated, to ensure that older versions can still find the directory). Or alternatively, it might be a good idea to just create a symlink from `~/.config/Ryujinx` to `~/Library/Application Support/Ryujinx`.

2023-01-15 04:06 UTC, merryhime commented
I feel a symlink may be the most elegant solution here, given that one may wish to bisect on Ryujinx versions prior to migration.

2023-01-15 04:17 UTC, AcK77 requested changes

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +            string appDataPath = null;
```suggestion
            string appDataPath;
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +            if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.OSX))
```suggestion
            if (OperatingSystem.IsMacOS())
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                appDataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Library/Application Support");
```suggestion
                appDataPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "Library", "Application Support");
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +            if (System.Runtime.InteropServices.RuntimeInformation.IsOSPlatform(System.Runtime.InteropServices.OSPlatform.OSX) && Mode == LaunchMode.UserProfile)
```suggestion
            if (OperatingSystem.IsMacOS() && Mode == LaunchMode.UserProfile)
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +            // Copy .config dir to application support dir
Start your comment with `// NOTE: ` and add a more explicit comment, don't forget to tell it should be removed after some point. There is no need to keep the migration in the future when most of users have already done it.

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                var oldConfigPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), DefaultBaseDir);
```suggestion
                string oldConfigPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), DefaultBaseDir);
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                    CopyDirectory(oldConfigPath, BaseDirPath);
```suggestion
                if (Path.Exists(oldConfigPath) && !Path.Exists(BaseDirPath))
                {
                    CopyDirectory(oldConfigPath, BaseDirPath);
                }
```
You didn't delete or rename `oldConfigPath` which could be nice too.

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                throw new DirectoryNotFoundException($"Source directory not found: {dir.FullName}");
```suggestion
            if (!dir.Exists)
            {
                throw new DirectoryNotFoundException($"Source directory not found: {dir.FullName}");
            }
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                    continue;
```suggestion
                if (file.Name == ".DS_Store")
                {
                    continue;
                }
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                file.CopyTo(destFile);
```suggestion

                file.CopyTo(Path.Combine(destinationDir, file.Name));
```

2023-01-15 04:17 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                CopyDirectory(subDir.FullName, destDir);
```suggestion
                CopyDirectory(subDir.FullName, Path.Combine(destinationDir, subDir.Name));
```

2023-01-18 18:09 UTC, UltraHDR commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +            // NOTE: Copies the Ryujinx folder in `~/.config` to `~/Library/Application Support` if one is found
```suggestion
            // NOTE: Moves the Ryujinx folder in `~/.config` to `~/Library/Application Support` if one is found
```

2023-01-18 18:12 UTC, UltraHDR commented
> I feel a symlink may be the most elegant solution here, given that one may wish to bisect on Ryujinx versions prior to migration.

I'm curious if a bisect would be helpful as macOS support is very basic/not working?

I would prefer if an app didn't create symlinks

but you know best

Just my 2 cents

2023-01-21 23:58 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                    Directory.CreateSymbolicLink(oldConfigPath, BaseDirPath);
I'm not sure if created a symlink is a good thing to do here.

2023-01-21 23:58 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +
Remove extra empty line

2023-01-30 03:34 UTC, Candygoblen123 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                    Directory.CreateSymbolicLink(oldConfigPath, BaseDirPath);
As per the previous comment, the symlink was created to maintain backwards compatibility. If you don't care about it, I can remove it.

2023-02-08 13:31 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                file.CopyTo(Path.Combine(destinationDir, file.Name));
```suggestion

                file.CopyTo(Path.Combine(destinationDir, file.Name));
```

2023-02-08 13:31 UTC, AcK77 approved these changes
LGTM! Thanks!

2023-02-11 20:42 UTC, seivan commented
If I could add one tweak here, is to allow an ENV variable to override it. I like my settings in dotfiles, but preferably not at `~/`. Don't mind adding the change myself, if it's ok.

2023-02-12 01:09 UTC, Candygoblen123 commented
> If I could add one tweak here, is to allow an ENV variable to override it. I like my settings in dotfiles, but preferably not at `~/`. Don't mind adding the change myself, if it's ok.

You can already do this using the `-r` command line argument.

2023-02-15 10:02 UTC, marysaka requested changes
Only one thing otherwise lgtm

2023-02-15 10:02 UTC, marysaka commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +
The symlink creation should be added back tbh (discussed that with @AcK77 as it didn't understood the idea around it initially)

2023-02-15 10:03 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                    Directory.CreateSymbolicLink(oldConfigPath, BaseDirPath);
Sorry I’ve misunderstood how things works here, it should be better to keep the symlink yeah :/

2023-02-15 10:04 UTC, AcK77 commented on Ryujinx.Common/Configuration/AppDataManager.cs
> +                file.CopyTo(Path.Combine(destinationDir, file.Name));
This is still not addressed

2023-02-21 10:53 UTC, marysaka approved these changes

2023-02-21 11:14 UTC, merged

2023-02-21 12:18 UTC, seivan commented
> > If I could add one tweak here, is to allow an ENV variable to override it. I like my settings in dotfiles, but preferably not at `~/`. Don't mind adding the change myself, if it's ok.
> 
> You can already do this using the `-r` command line argument.

That's not the same thing. Reading the ENV is by default and unobtrusive. Asking to pass a command line argument each time means you have to run said binary with the argument.

2023-02-21 14:25 UTC, Candygoblen123 commented
As a reminder, user documentation should be updated to reflect this change before the next macOS update is released.