Ava UI: `DownloadableContentManager` Refactor
Ryujinx/Ryujinx pull request #4300
Opened 2023-01-15 20:34 UTC by IsaacMarovitz

2023-02-14 12:19 UTC, AcK77 requested changes
Lgtm except those following comments.

The search field is a bit strange (smaller than buttons so placeholder text is hidden) too:
![image](https://user-images.githubusercontent.com/4905390/218736421-aa90447b-a2e0-4a33-8a4c-300615341bda.png)

2023-02-14 12:19 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +        private AvaloniaList<DownloadableContentModel>      _selectedDownloadableContents = new();
```suggestion
        private VirtualFileSystem                      _virtualFileSystem;
        private AvaloniaList<DownloadableContentModel> _downloadableContents = new();
        private AvaloniaList<DownloadableContentModel> _views = new();
        private AvaloniaList<DownloadableContentModel> _selectedDownloadableContents = new();
```

2023-02-14 12:19 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +
```suggestion
```

2023-02-14 12:19 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +            catch
A log message (or a dialog message) should be nice to have if the JSON file is corrupted

2023-02-14 12:19 UTC, AcK77 commented on Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +                        fileEntry.FullPath, true);
```suggestion
                    var content = new DownloadableContentModel(nca.Header.TitleId.ToString("X16"), path, fileEntry.FullPath, true);
```

2023-03-04 13:45 UTC, marysaka approved these changes

2023-03-14 13:34 UTC, emmauss approved these changes

2023-03-14 16:03 UTC, TSRBerry approved these changes
Thank you!

2023-03-14 16:04 UTC, merged