UI: Expose games build ID for cheat management
Ryujinx/Ryujinx pull request #4340
Opened 2023-01-24 21:31 UTC by gnisman

Currently Ryujinx is not exposing Build ID to the user in the UI which make it hard to manage cheats

<img width="504" alt="Screenshot 2023-02-03 at 23 32 46" src="https://user-images.githubusercontent.com/11611112/216715008-1c9a6400-85a9-461d-a9a3-139067c6a0ac.png">

<img width="444" alt="Screenshot 2023-02-03 at 23 33 34" src="https://user-images.githubusercontent.com/11611112/216715032-0f5b5696-f642-406e-b7f5-49200b14bbe5.png">

Closes #3397

2023-01-25 15:55 UTC, MetrosexualGarbodor commented
I can't test right now, does this change whenever a game update is added or removed?

2023-01-25 16:35 UTC, gnisman commented
> I can't test right now, does this change whenever a game update is added or removed?



> I can't test right now, does this change whenever a game update is added or removed?

Yes

2023-01-26 21:51 UTC, gdkchan commented
The way how the build ID is currently formatted (inside brackets after the game name) is the as the title ID, which can lead someone to assume this is the title ID rather than build ID. Maybe it would be better to have something explicitly say that this is the build ID.

2023-01-26 22:26 UTC, gnisman commented
> The way how the build ID is currently formatted (inside brackets after the game name) is the as the title ID, which can lead someone to assume this is the title ID rather than build ID. Maybe it would be better to have something explicitly say that this is the build ID.

Wanted to change it to something like "Cheats Available for {0} [Build id: {1}]"
But CheatWindowHeading exists in 14 different languages in AVA, do we really want to change it?
In my opinion title id and build id looks completely different to mistake between them
but on the other hand users got used to see title id in this cheats window.
What do you suggest to do?

2023-01-27 21:04 UTC, OldManKain commented
Don't mind my crappy editiing skills but would it be possible to add the BID's something like this?
![image](https://user-images.githubusercontent.com/47503099/215197950-fa957b86-8f4a-4bd7-9481-19978223236e.png)

2023-01-29 10:28 UTC, gnisman commented
> Don't mind my crappy editiing skills but would it be possible to add the BID's something like this? ![image](https://user-images.githubusercontent.com/47503099/215197950-fa957b86-8f4a-4bd7-9481-19978223236e.png)

It is possible but i dont think there is much use for the Tittle Id here, just adds bloat

2023-01-29 10:30 UTC, gnisman commented
@gdkchan , @OldManKain added BID as a prefix (updated the original screenshots) what do you think?

2023-01-29 10:57 UTC, jojodunet commented
Personally, I think it’s better to see the both, TID and BID, on the same window.
Something like shown by @OldManKain

2023-02-03 15:12 UTC, AcK77 commented
IMO the BuildId should be extracted (and cached in the game json maybe?) when games are loaded in the gamelist, the method should be in `Ryujinx.Ui.Common` instead of `ApplicationLoader` and the BuildId should be shown in a readonly textbox to be able to copy/paste it.

2023-02-03 21:46 UTC, gnisman commented
> IMO the BuildId should be extracted (and cached in the game json maybe?) when games are loaded in the gamelist, the method should be in `Ryujinx.Ui.Common` instead of `ApplicationLoader` and the BuildId should be shown in a readonly textbox to be able to copy/paste it.

Moved the method to `Ryujinx.Ui.Common` and Build id is shown as readonly Text Box now

about extracting build id when games are loaded in the game list, not sure it will be a good to extract build id of all the games ahead of time but rather only when needed in cheat window.
maybe we should address it as part of #3285

2023-02-09 04:03 UTC, gnisman commented
@AcK77 , @OldManKain do you think that the bid as a text box looks visually ok? (screenshots updated at the first comment)

2023-02-09 05:07 UTC, OldManKain commented
> @AcK77 , @OldManKain do you think that the bid as a text box looks visually ok? (screenshots updated at the first comment)

I can live with that, now it's up to the higher ups to make their decision.

2023-03-08 04:53 UTC, OldManKain commented
This still going to happen? 😄

2023-03-08 06:21 UTC, gnisman commented
> This still going to happen? 😄

I am still waiting for code review :)

2023-03-14 00:09 UTC, TSRBerry commented
I'd like to wait for #4480 to be reviewed and merged first, since these changes may also help here to make things easier/better.

2023-03-14 10:57 UTC, gnisman commented
> I'd like to wait for #4480 to be reviewed and merged first, since these changes may also help here to make things easier/better.

Sure no problem, once #4480 is merged it would be nice if you can review my code and point the sections that's needs change in your opinion.
Thanks

2023-03-31 20:00 UTC, TSRBerry commented
Could you rebase this?

2023-04-01 13:12 UTC, gnisman commented
> Could you rebase this?

Yes i will do it tonight

2023-04-02 07:51 UTC, gnisman commented
@TSRBerry rebased and retested, Moved the PR back to review state

2023-04-16 00:33 UTC, TSRBerry requested changes
This review focuses only on the design. I basically commented a suggestion about how I'd move the `BID:` part out of the textbox, but still keep everything centered.
You can do it in a different way if you want.

Is the text in GTK copyable already? (I'll do another review tomorrow.)

2023-04-16 00:33 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/CheatWindow.axaml
>          <TextBlock
```suggestion
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="*" />
        </Grid.ColumnDefinitions>
        <TextBlock
```

2023-04-16 00:33 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/CheatWindow.axaml
>              MaxWidth="500"
```suggestion
            Grid.Row="1"
            Grid.Column="0"
            Grid.ColumnSpan="2"
            MaxWidth="500"
```

2023-04-16 00:33 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/CheatWindow.axaml
> +        <TextBox
```suggestion
        <TextBlock
            Grid.Row="2"
            Grid.Column="0"
            MaxWidth="500"
            Margin="140,15,20,5"
            HorizontalAlignment="Right"
            VerticalAlignment="Center"
            LineHeight="30"
            Text="BID:"
            TextAlignment="Center"
            TextWrapping="Wrap" />
        <TextBox
```
Move the `BID:` out of the TextBox

2023-04-16 00:33 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/CheatWindow.axaml
> +            IsReadOnly="True" />
```suggestion
           Grid.Row="2"
            Grid.Column="1"
            Margin="0,5,110,5"
            MinWidth="160"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            TextAlignment="Center"
            Text="{Binding BuildId}"
            IsReadOnly="True" />
```

2023-04-16 00:33 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/CheatWindow.axaml
> +            Grid.Row="3"
```suggestion
            Grid.Row="3"
            Grid.Column="0"
            Grid.ColumnSpan="2"
```

2023-04-16 00:33 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/CheatWindow.axaml
> +            Grid.Row="4"
```suggestion
            Grid.Row="4"
            Grid.Column="0"
            Grid.ColumnSpan="2"
```

2023-04-16 00:33 UTC, TSRBerry commented on Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
> +            BuildId = $"BID: {gameBuildId}";
```suggestion
            BuildId = gameBuildId;
```

2023-04-19 14:33 UTC, gnisman commented
> This review focuses only on the design. I basically commented a suggestion about how I'd move the `BID:` part out of the textbox, but still keep everything centered. You can do it in a different way if you want.
> 
> Is the text in GTK copyable already? (I'll do another review tomorrow.)

the text in GTK is copyable by right click -> copy

2023-04-20 16:19 UTC, gnisman commented on Ryujinx.Ui.Common/Helper/GameDataExtractor.cs
> +    public static string GetGameBuildId(VirtualFileSystem virtualFileSystem, string titleFilePath)
I can add it as a static method in Ryujinx.Ui.App.Common.ApplicationData will it be ok?
still want to parse it in run time and not store it in ApplicationData instance.

Cheat window can be used during emulation and before the game is started,
and i don't think there is access to ApplicationData instance during that time, even TID is not taken from ApplicationData instance

if adding it as static method to ApplicationData is not a good idea how do you suggest to handle it? 
Thanks

2023-04-20 22:45 UTC, TSRBerry commented on Ryujinx.Ui.Common/Helper/GameDataExtractor.cs
> +    public static string GetGameBuildId(VirtualFileSystem virtualFileSystem, string titleFilePath)
> even TID is not taken from ApplicationData instance

True, although that's really odd and should be changed eventually.

I think it's fine to add it as a static method, as I don't really think we have another option that would be better here.

(Sorry for the late reply!)

2023-04-21 10:53 UTC, gnisman commented on Ryujinx.Ui.Common/Helper/GameDataExtractor.cs
> +    public static string GetGameBuildId(VirtualFileSystem virtualFileSystem, string titleFilePath)
Made the change, Thanks for reviewing

2023-04-21 18:49 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationData.cs
> +        public static string GetApplicationBuildId(VirtualFileSystem virtualFileSystem, string titleFilePath)
```suggestion

        public static string GetApplicationBuildId(VirtualFileSystem virtualFileSystem, string titleFilePath)
```
Since this is a method and not a property, add a empty line to make these easier to distinguish.

2023-04-21 22:46 UTC, TSRBerry approved these changes
Lgtm, thank you for being so patient with me!

2023-04-23 08:09 UTC, gnisman commented
> Lgtm, thank you for being so patient with me!

Thanks for the review and the suggestions, appreciate it

2023-04-29 19:04 UTC, TSRBerry commented
Your latest commit is not correct unfortunately. Could you please drop this one and rebase your PR instead?

2023-05-01 11:05 UTC, gnisman commented
> Your latest commit is not correct unfortunately. Could you please drop this one and rebase your PR instead?

Hey,
can you explain what is wrong with the merge?  or you just prefer rebases instead of merges?

2023-05-01 17:40 UTC, TSRBerry commented
Oh sorry, it seems like it was correct after all and I just didn't read it properly. I thought you added your changes outside of the `src` directory.

2023-05-05 16:25 UTC, marysaka approved these changes

2023-05-05 19:04 UTC, AcK77 requested changes

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
> +        public CheatWindow(VirtualFileSystem virtualFileSystem, string titleId, string titleName, string gameBuildId)
Pass the file path instead and call `ApplicationData.GetApplicationBuildId()` here.

On a side note:
```suggestion
        public CheatWindow(VirtualFileSystem virtualFileSystem, string titleId, string titleName, string buildId)
```

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
> +            BuildId = gameBuildId;
```suggestion
            BuildId = buildId;
            
```
(Just for information, this have to be changed as I suggested above.

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx.Ui.Common/App/ApplicationData.cs
> +                    $"File does not exists. {titleFilePath}");
```suggestion
                Logger.Error?.Print(LogClass.Application, $"File does not exists. {titleFilePath}");
                
```

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx.Ui.Common/App/ApplicationData.cs
> +                    "Extraction failure. The main NCA was not present in the selected file");
```suggestion
                Logger.Error?.Print(LogClass.Application, "Extraction failure. The main NCA was not present in the selected file");
```

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx.Ui.Common/App/ApplicationData.cs
> +                mainNca.Header.TitleId.ToString("x16"), 0, out _);
```suggestion
            (Nca updatePatchNca, _) = ApplicationLibrary.GetGameUpdateData(virtualFileSystem, mainNca.Header.TitleId.ToString("x16"), 0, out _);
```

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx.Ui.Common/App/ApplicationData.cs
> +                        IntegrityCheckLevel.ErrorOnInvalid);
```suggestion
                    codeFs = mainNca.OpenFileSystemWithPatch(patchNca, NcaSectionType.Code, IntegrityCheckLevel.ErrorOnInvalid);
```

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx.Ui.Common/App/ApplicationData.cs
> +                [..buildIdSize];
```suggestion
            return BitConverter.ToString(reader.Header.ModuleId.ItemsRo.ToArray()).Replace("-", "").ToUpper()[..16];
```
You can remove `buildIdSize` it's not really needed.

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                ApplicationData.GetApplicationBuildId(_virtualFileSystem, _currentEmulatedGamePath));
Same as avalonia suggestion

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                ApplicationData.GetApplicationBuildId(_virtualFileSystem, _titleFilePath)).Show();
Same as avalonia suggestion

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/CheatWindow.cs
> +        private CheatWindow(Builder builder, VirtualFileSystem virtualFileSystem, ulong titleId, string titleName, string gameBuildId) : base(builder.GetRawOwnedObject("_cheatWindow"))
Same as avalonia suggestion

2023-05-05 19:04 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/CheatWindow.cs
> +            _buildIdTextView.Buffer.Text = $"BID: {gameBuildId}";
```suggestion
            _buildIdTextView.Buffer.Text = $"BuildId: {gameBuildId}";
```

2023-05-05 20:21 UTC, gnisman commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml
> +            Text="BID:"
Changed to BuildId:
not sure what local file do you mean?

2023-05-05 20:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml
> +            Text="BID:"
You should add an entry here https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.Ava/Assets/Locales/en_US.json and then bind the entry to the `Text` field. Then people will be able to translate the text is needed.

2023-05-06 03:52 UTC, AcK77 requested changes
Some last things and it should be good ;)! Thanks!

2023-05-06 03:52 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml
> +            Text="{Binding BuildIdLabel}"
```suggestion
            Text="{locale:Locale BuildId}"
```

2023-05-06 03:52 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
> +        public string BuildIdLabel { get; }
Can be removed

2023-05-06 03:52 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
> +            BuildIdLabel = LocaleManager.Instance.UpdateAndGetDynamicValue(LocaleKeys.BuildId);
Can be removed

2023-05-06 03:52 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
> +            BuildId = ApplicationData.GetApplicationBuildId(virtualFileSystem, titlePath);
```suggestion
            BuildId = ApplicationData.GetApplicationBuildId(virtualFileSystem, titlePath);
            
```

2023-05-06 07:11 UTC, gnisman commented
> Some last things and it should be good ;)! Thanks!

Done, Thanks for the feedback

2023-05-07 14:13 UTC, AcK77 approved these changes

2023-05-07 14:36 UTC, merged