Check KeyboardMode in GUI
Ryujinx/Ryujinx pull request #4343
Opened 2023-01-26 17:31 UTC by WilliamWsyHK

This PR will allow the GUI to check against the `KeyboardMode` before accepting the text blindly.

This will probably resolve some funny moments such as entering free-text, and then crashed, which suppose to accept only numbers, such as in Pokemon the center asks "month of birth".

Ref. https://discord.com/channels/410208534861447168/410208534861447170/1068159781640093756

2023-01-26 22:54 UTC, Pythonic-Rainbow requested changes
I think the default value of `isTextAgreeWithKeyboardMode` should be true?

2023-01-26 22:54 UTC, Pythonic-Rainbow commented on Ryujinx/Ui/Applet/SwkbdAppletDialog.cs
> +            bool isTextAgreeWithKeyboardMode = false;
I think this should be true? I tested your PR with this line being true and it works as expected in GTK

2023-01-26 22:54 UTC, Pythonic-Rainbow commented on Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
> +                    bool isTextAgreeWithKeyboardMode = false;
I think this should be true?  But for some reason I can't compile ava

2023-01-27 07:08 UTC, WilliamWsyHK commented
Yes, that is the thing I discover just after I shutdown my computer, I will change it once available.

2023-01-27 13:07 UTC, WilliamWsyHK commented on Ryujinx/Ui/Applet/SwkbdAppletDialog.cs
> +            bool isTextAgreeWithKeyboardMode = false;
Updated.

2023-01-27 13:07 UTC, WilliamWsyHK commented on Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
> +                    bool isTextAgreeWithKeyboardMode = false;
Updated.

2023-02-16 06:51 UTC, Pythonic-Rainbow approved these changes

2023-02-16 06:55 UTC, Pythonic-Rainbow commented
The check for number works. I have a few suggestions to further improve this PR:

1. Add checks for other KeyboardModes
2. Maybe we can display more than 1 constraints in the dialog. In the case of registering birthday in Pokemon Scarlet, the dialog will pop up with "Must be 1-2 characters". The line will change to "Must be numbers only" when I input an alphabet. Maybe we can display both constraints at the same time?

2023-04-28 19:58 UTC, TSRBerry requested changes
I restructured your code a little bit, I hope that was okay.

I'm not sure about the current message, they feel a bit weird, but I'm not sure what to write instead.

2023-04-28 19:58 UTC, TSRBerry commented on Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
> +            };
Could you add the validation info messages here as well?

2023-04-29 04:51 UTC, WilliamWsyHK commented on Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
> +            };
Added. Please review.

2023-04-29 15:15 UTC, TSRBerry requested changes
Thank you for the adjustments! I pinged the mods to take a look at the messages here and added a few comments, where I think we could improve the Avalonia part a little.

2023-04-29 15:15 UTC, TSRBerry commented on src/Ryujinx/Ui/Applet/SwkbdAppletDialog.cs
> +                    break;
@Ryujinx/moderators Could you take a look at the text here and check if that's fine? Maybe there is a way to write this better, but I'm not sure.

2023-04-29 15:15 UTC, TSRBerry commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> +  "SoftwareKeyboardModeASCII": "Must be ASCII text only",
Same for the text in Avalonia

2023-04-29 15:15 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
> +        private string _validationInfoText = "";
This is not needed for Avalonia, since `Error.Text` has a getter you can use. For Gtk I only added it because the `Markup` property doesn't have a getter.

2023-04-29 15:15 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
> +                    _validationInfoText = string.IsNullOrEmpty(_validationInfoText) ? LocaleManager.Instance.UpdateAndGetDynamicValue(LocaleKeys.SoftwareKeyboardModeNumbersOnly) : string.Join("\n", _
Here it might be better to get the text from `LocaleManager` first and then do the check if the error text is empty.

2023-05-08 15:14 UTC, WilliamWsyHK commented on src/Ryujinx.Ava/UI/Applet/SwkbdAppletDialog.axaml.cs
> +        private string _validationInfoText = "";
Updated.

2023-05-12 00:18 UTC, TSRBerry approved these changes
Lgtm, thank you!

(Still not sure about the messages, but since I don't know better either I think it's fine to approve.)

2023-05-21 19:18 UTC, riperiperi reviewed
This makes sense, though I'm not sure if IsAsciiLetter is identical to the Alphabet mode. Ascii won't have a bunch of accented characters, for instance.

2023-05-21 23:23 UTC, AcK77 approved these changes

2023-05-22 02:29 UTC, yell0wsuit commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> +  "SoftwareKeyboardModeASCII": "Must be ASCII text only",
```suggestion
  "SoftwareKeyboardModeNumbersOnly": "Must be in numbers (0-9) only",
  "SoftwareKeyboardModeAlphabet": "Must be in English alphabets only",
  "SoftwareKeyboardModeASCII": "Must be in numbers (0-9) and/or English alphabets only",
```

``Must be ASCII text only`` may confuse some users because they may not know about ASCII. While ASCII has the usual punctuation marks such as ``. , ! @ # $ % ^ & * ( )`` and so on (haven't tested which games use these), it also has the control characters (nul, del, etc.) -- see https://en.wikipedia.org/wiki/ASCII#Character_set. So we need to test which games that accepts those characters and change the ``SoftwareKeyboardModeASCII`` message accordingly so that users can understand easily.

2023-05-22 11:41 UTC, TSRBerry commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> +  "SoftwareKeyboardModeASCII": "Must be ASCII text only",
This should also be changed for Gtk

2023-06-01 07:22 UTC, marysaka commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> +  "SoftwareKeyboardModeASCII": "Must be ASCII text only",
This can also be address separately imo.

2023-06-01 07:22 UTC, marysaka approved these changes

2023-06-03 02:55 UTC, WilliamWsyHK commented
Thanks, I will rebase one more time and force-push it.

2023-06-04 03:30 UTC, merged