Ava UI: Mod Manager
Ryujinx/Ryujinx pull request #4390
Opened 2023-02-09 04:16 UTC by IsaacMarovitz

**IN PROGRESS**

Adds a mod manager. Will use #2651 as a reference. This time for Ava not GTK tho (sucks to suck GTK enjoyers).

2023-05-24 10:00 UTC, Foul-Tarnished commented
Will we be able to see exefs mods with this ?
and enable/disable them, without needing to move them manually

2024-01-11 22:07 UTC, IsaacMarovitz commented
Functionality confirmed solid by testers

2024-01-20 13:46 UTC, Mewzapchu commented
how to i install this, i uninstalled the original and unpacked the artifact but it still appears open mod directory

2024-01-25 17:59 UTC, AcK77 requested changes
Could be nice to rename `titleId` to `applicationId` in all modified files, like `ModLoader.cs`

2024-01-25 17:59 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/ModManagerViewModel.cs
> +                AllowMultiple = true
```suggestion
                AllowMultiple = true,
```

2024-01-25 18:16 UTC, AcK77 requested changes

2024-01-25 18:16 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/ModManagerViewModel.cs
> +                        await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance.UpdateAndGetDynamicValue(LocaleKeys.DialogLoadErrorMessage, "Directory", dirToCreate));
`Directory` shouldn't be a locale thing ?

2024-01-25 18:16 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/ModManagerViewModel.cs
> +                var modCache = new ModLoader.ModCache();
Not resolved!

2024-01-25 18:16 UTC, AcK77 commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> +  "DialogLoadErrorMessage": "{0}. Errored File: {1}",
```suggestion
  "DialogLoadFileErrorMessage": "{0}. Errored File: {1}",
```

2024-01-25 18:16 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/ModManagerViewModel.cs
> +                AllowMultiple = true
Not resolved!

2024-01-25 23:45 UTC, AcK77 approved these changes
Lgtm! Thanks!

2024-01-26 00:21 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                Logger.Warning?.Print(LogClass.ModLoader, $"Failed to deserialize mod data for {applicationId} at {modJsonPath}");
```suggestion
                Logger.Warning?.Print(LogClass.ModLoader, $"Failed to deserialize mod data for {applicationId:X16} at {modJsonPath}");
```
It should print the application ID as hex.

2024-01-26 00:21 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                Logger.Warning?.Print(LogClass.ModLoader, $"Failed to deserialize mod data for {applicationId} at {modJsonPath}");
I think it also prints this when the file doesn't exist yet, not sure if that is intentional?

2024-01-26 00:21 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                    var modData = modMetadata.Mods.Find(x => fsFile.FullName.Contains(x.Path));
Do you expect this to throw when no match is found in the list? Per the documentation, it returns the default value for T (null in this case) if not found.

2024-01-26 00:31 UTC, IsaacMarovitz commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                    var modData = modMetadata.Mods.Find(x => fsFile.FullName.Contains(x.Path));
Yes, this is explained in a comment in the catch block.

2024-01-26 00:41 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                    var modData = modMetadata.Mods.Find(x => fsFile.FullName.Contains(x.Path));
Is it wrong then? Because it should *not* throw an exception if the item is not on the list. It should instead return null.

2024-01-26 00:43 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                    var modData = modMetadata.Mods.Find(x => fsFile.FullName.Contains(x.Path));
I guess the exception is supposed to throw here `enabled = modData.Enabled;`.
So I guess my question is, why not remove the try/catch and instead do `enabled = modData == null || modData.Enabled;`?

2024-01-26 00:53 UTC, gdkchan approved these changes
lgtm, thanks, but I did not test extensively.

2024-01-26 01:02 UTC, merged

2024-02-03 17:01 UTC, IsaacMarovitz commented
@semliki This is available in the Avalonia build, which can be downloaded from [here](https://github.com/Ryujinx/release-channel-master/releases)