Update LibHac to 0.18.0
Ryujinx/Ryujinx pull request #4414
Opened 2023-02-13 14:41 UTC by Steveice10

Updates LibHac to the 0.18.0 release. One notable feature is that loading personalized ticket title keys is now supported with the right console keys dumped.

Main changes:
* Changes uses of ```.Ref()``` to ```.Ref```.
* Changes two uses of LibHac SpanHelpers to Ryujinx SpanHelpers due to ref compile errors.
* Updates ticket loading to check for null title key instead of gating to only common keys, as LibHac will now return null when the key cannot be read.

Tested with a few games I have and seems to be working as expected.

2023-02-13 17:00 UTC, Thealexbarney requested changes
Looks mostly okay to me at a glance without actually running the code. The only issue is switching to the Ryujinx copy of the `SpanHelpers` class. The `UnscopedRef` attribute should be used instead of using the Ryujinx copy.

Observation outside the scope of this PR:
I noticed that the `scoped` keyword was added to [SpanHelpers](https://github.com/Ryujinx/Ryujinx/blob/e4f68592c3a6e51414e5f78eef096f21bf735eb1/Ryujinx.Common/Utilities/SpanHelpers.cs) when updating to .NET 7. This isn't correct because the input struct ref *does* escape the scope of the method, so the lifetime of the struct isn't properly tracked. The `scoped` keyword should be removed from these methods, and any callers should be annotated with `scoped` or `UnscopedRef` as necessary.

[Here's](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.memorymarshal.createreadonlyspan?view=net-7.0#remarks) an explanation in the .NET docs under the remarks section.

2023-02-13 17:00 UTC, Thealexbarney commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
These should be annotated with `UnscopedRef` because `this` escapes the scope of the method.
```suggestion
        [UnscopedRef]
```

2023-02-13 17:00 UTC, Thealexbarney commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +            return MemoryMarshal.AsBytes(SpanHelpers.CreateReadOnlySpan(ref this, 1));
Might as well simplify this a bit
```suggestion
            return SpanHelpers.AsReadOnlyByteSpan(in this);
```

2023-02-13 17:00 UTC, Thealexbarney commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
```suggestion
        [UnscopedRef]
```

2023-02-13 17:00 UTC, Thealexbarney commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
Switch back to the other `SpanHelpers` class to get proper lifetime tracking
```suggestion
using LibHac.Common;
```

2023-02-13 17:35 UTC, Steveice10 commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
Ryujinx does the exact same with other struct members elsewhere in the code; this just matches these two cases to the rest of the codebase.

Since these two uses aren’t really specifically related to LibHac at all but just happened to use it’s helper I would argue if there’s an issue there would need to be a larger fix of the Ryujinx SpanHelpers outside of this PR, and aligning these uses onto the same SpanHelpers would suffice for now.

2023-02-13 20:51 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
In general we don't want to add a dependency to Libhac in the code if we don't need to, as if we want to use the code in a separate project or standalone we don't want to depend on Libhac just for minor utility methods.

2023-02-13 21:00 UTC, Thealexbarney commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
The `SpanHelpers` class in Ryujinx is (or was) just a copy of the class in Libhac, so it matter too much which one is used outside of possible naming collisions. I only suggested using the one in Libhac because it doesn't have the incorrect `scoped` parameters, and fixing the one in Ryujinx would probably require properly annotating other functions throughout Ryujinx

2023-02-13 21:14 UTC, gdkchan commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
I think the right thing to do here is fixing the one on Ryujinx, or removing the one on Ryujinx and using the Libhac method everywhere. In both cases it would require all existing uses of those methods. My preference would be of course keeping and fixing the one on Ryujinx due to the reasons I mentioned before. In any case, if this is a existing issue and the code is working as is, I think it would be fine to fix in a separate PR.

2023-02-13 21:50 UTC, Thealexbarney commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
The code in question in the PR is safe as it currently is. It's just bypassing the compiler's lifetime tracking so it's up to the developer to make sure that the code's safe. It should be fine to commit it as-is and do the fix in a separate PR.

2023-02-16 22:54 UTC, Steveice10 commented
Rebased via GitHub tool

2023-02-21 09:45 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
I would really prefer that those helpers be from one dependency.

However, I do not want to bring LibHac dependency on non HLE parts, this part would need to be spitted out of it.

Not to mention it could be beneficial for the .NET ecosystem in general.

In the meantime, @Steveice10 can you revert the changes here and add a TODO comment stating the lifetime issue?

2023-02-21 09:49 UTC, Steveice10 commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
> I would really prefer that those helpers be from one dependency.
> 
> However, I do not want to bring LibHac dependency on non HLE parts, this part would need to be spitted out of it.
> 
> Not to mention it could be beneficial for the .NET ecosystem in general.
> 
> In the meantime, @Steveice10 can you revert the changes here and add a TODO comment stating the lifetime issue?

This change is actually removing the LibHac dependency. Without this change it won't compile because of LibHac changes.

2023-02-21 10:48 UTC, marysaka commented on Ryujinx.HLE/HOS/Services/Mii/Types/StoreData.cs
> +﻿using Ryujinx.Common.Utilities;
urgh right

> > I would really prefer that those helpers be from one dependency.
> > However, I do not want to bring LibHac dependency on non HLE parts, this part would need to be spitted out of it.
> > Not to mention it could be beneficial for the .NET ecosystem in general.
> > In the meantime, @Steveice10 can you revert the changes here and add a TODO comment stating the lifetime issue?
> 
> This change is actually removing the LibHac dependency. Without this change it won't compile because of LibHac changes.

Okay, I guess it's fine then.

It would be nice to open an issue for that @Thealexbarney, I will try to handle it when I get some times (or someone can look into that).

2023-03-02 02:42 UTC, merged