Logging: Redirect StdErr into logging system
Ryujinx/Ryujinx pull request #4427
Opened 2023-02-15 15:58 UTC by merryhime

Redirect stderr output into logging system.

This allows for easier mvk/mesa debugging since stderr will now show up in log files.

Mono.Unix was imported because calling `pipe` would otherwise require a stub library to be implemented.

Extracted from #4227.

2023-02-15 16:09 UTC, marysaka requested changes
I would prefer not importing Mono.Unix again as this force us to have another native dependency again :sweat_smile:

2023-02-16 22:44 UTC, merryhime commented
@marysaka removed dependency on Mono.Unix

2023-02-17 21:37 UTC, marysaka approved these changes

2023-02-21 20:33 UTC, riperiperi commented on Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +        private static partial int dup2 (int fd, int fd2);
```suggestion
        private static partial int dup2(int fd, int fd2);
```

2023-02-21 20:33 UTC, riperiperi commented on Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +                    throw new ();
```suggestion
                    throw new();
```

2023-02-22 15:18 UTC, TSRBerry reviewed
Just have a few suggestions, but lgtm otherwise!

2023-02-22 15:18 UTC, TSRBerry commented on Ryujinx.Common/SystemInterop/UnixStream.cs
> +    public partial class UnixStream : Stream, IDisposable
```suggestion
    [UnsupportedOSPlatform("windows")]
    public partial class UnixStream : Stream, IDisposable
```
Just to make sure we never use it for Windows.

2023-02-22 15:18 UTC, TSRBerry commented on Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +        [SupportedOSPlatform("macos")]
Could you move these to the class?

2023-02-22 16:13 UTC, merryhime commented on Ryujinx.Common/SystemInterop/UnixStream.cs
> +    public partial class UnixStream : Stream, IDisposable
sgtm

2023-02-22 16:15 UTC, merryhime commented on Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +        [SupportedOSPlatform("macos")]
Would rather leave this be, and have this check be encapsulated in this class.

2023-02-22 17:59 UTC, TSRBerry commented on Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +        [SupportedOSPlatform("macos")]
Fine for me as well!

2023-02-25 14:47 UTC, AcK77 approved these changes

2023-02-25 15:03 UTC, TSRBerry approved these changes
Thank you!

2023-02-25 15:07 UTC, merged