IPC - Refactor Bcat service to use new ipc
Ryujinx/Ryujinx pull request #4446
Opened 2023-02-19 08:23 UTC by emmauss

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> +        private const int PointerBufferSize = 0x8000;
You should add a "TODO" comment here as a reminder that the values are wrong.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +        private bool _initialized;
There's a warning about this never being used. Maybe just setting it to false explicitly on the constructor will be enough to silence the warning? Or maybe you should just remove it if it's really never going to be used.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            //       Add an instance of nn::bcat::detail::service::core::TaskManager who load "bcat-sys:/" system save data and open "dc/task.bin".
```suggestion
            //       Add an instance of nn::bcat::detail::service::core::TaskManager who loads "bcat-sys:/" system save data and opens "dc/task.bin". 
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            //       If the file don't exist, create a new one (size of 0x800) and write 2 empty struct with a size of 0x400.
```suggestion
            //       If the file don't exist, create a new one (with a size of 0x800 bytes) and write 2 empty structs with a size of 0x400 bytes.
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            // NOTE: If the IBcatService is null this error is returned, Doesn't occur in our case.
I'm not sure what's the point of this comment. If this can never happen here, the comment can just be removed. Presumably the error would be caused by the service running out of memory and the allocation failing, which would result in a `OutOfMemoryException` here.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            if(rc.IsSuccess())
```suggestion
            if (rc.IsSuccess())
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            return new Result((int)rc.Module, (int)rc.Description);
It might be better to add a extension method somewhere extending `LibHac.Result` with a `ToResult` method that would return the Ryujinx `Result` struct, since that pattern will be common on services that depends on LibHac. Ideally such method should be somewhere on the `Ryujinx.Horizon` project to avoid adding a dependency on LibHac on the `Ryujinx.Horizon.Common` project.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            if(rc.IsSuccess())
```suggestion
            if (rc.IsSuccess())
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            if (Interlocked.CompareExchange(ref _disposalState, 1, 0) == 0)
```suggestion
            if (Interlocked.Exchange(ref _disposalState, 1) == 0)
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheDirectoryService.cs
> +            var rc = _base.Get.Open(ref directoryName);
If the extension method I mentioned before is added, the implementation of those functions could be a single line.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheDirectoryService.cs
> +            if (Interlocked.CompareExchange(ref _disposalState, 1, 0) == 0)
```suggestion
            if (Interlocked.Exchange(ref _disposalState, 1) == 0)
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheFileService.cs
> +            if (Interlocked.CompareExchange(ref _disposalState, 1, 0) == 0)
```suggestion
            if (Interlocked.Exchange(ref _disposalState, 1) == 0)
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> +            Os.CreateSystemEvent(out var systemEventType, EventClearMode.ManualClear, true).AbortOnFailure();
Those events are never destroyed which can cause a handle leak if this function is called over and over again. A better way of doing this is creating the event on the constructor, making the class `IDisposable`, and calling `Os.DestroySystemEvent` in the dispose method. Of course, the correct way of doing this is creating and destroying it on the same place the original service would, but lacking proper RE of the service, I think that's a reasonable way of doing it. You can also create the event lazily (that is, create it only when `GetEvent` is called, if it has not been created it, and then destroy it only if it has been created).

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +            if (Interlocked.CompareExchange(ref _disposalState, 1, 0) == 0)
```suggestion
            if (Interlocked.Exchange(ref _disposalState, 1) == 0)
```

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> +        public Result GetImpl(out Ipc.Types.DeliveryCacheProgressImpl deliveryCacheProgressImpl)
This does not look right, the struct has 0x200 bytes which is way too large to be written on the raw data section of the message (the whole message can only have up to 0x100 bytes). Either this is supposed to use a buffer, or the struct size is wrong.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/HorizonOptions.cs
> +using System;
Not sure why this `using` is necessary.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Bcat/IDeliveryCacheDirectoryService.cs
> +using System;
Several of those are not necessary.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Bcat/IBcatService.cs
> +using System;
Not necessary.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Bcat/IDeliveryCacheFileService.cs
> +using System;
Not necessary.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Bcat/IDeliveryCacheProgressService.cs
> +using System;
Not necessary.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Sdk/Bcat/IServiceCreator.cs
> +using System;
Not necessary.

2023-02-19 15:21 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheFileService.cs
> +        public Result Read(in long offset, out long bytesRead, [Buffer(HipcBufferFlags.Out | HipcBufferFlags.MapAlias)] Span<byte> data)
Any special reason for passing the offset as `in`?

2023-02-19 15:25 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> +        public Result GetImpl(out Ipc.Types.DeliveryCacheProgressImpl deliveryCacheProgressImpl)
I just checked and it is supposed to be a buffer. `[Buffer(HipcBufferFlags.Out | HipcBufferFlags.Pointer, 0x200)] out DeliveryCacheProgressImpl deliveryCacheProgressImpl`

2023-02-25 15:20 UTC, emmauss commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheFileService.cs
> +        public Result Read(in long offset, out long bytesRead, [Buffer(HipcBufferFlags.Out | HipcBufferFlags.MapAlias)] Span<byte> data)
No specific reason.

2023-02-25 15:20 UTC, emmauss commented
Addressed review

2023-02-25 15:25 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> +            if(_handle== 0)
```suggestion
            if (_handle== 0)
```

2023-02-25 18:12 UTC, gdkchan approved these changes
lgtm, minus comments. Note that I did not compare the implementation with that of the original service, this is mostly migrating the existing code which might not be accurate.

2023-02-25 18:12 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> +            if (_handle== 0)
```suggestion
            if (_handle == 0)
```

2023-02-25 18:12 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> +        private SystemEventType _systemEventType;
`_systemEvent` would be a better name imo.

2023-02-25 20:32 UTC, emmauss commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> +        private SystemEventType _systemEventType;
Done

2023-02-25 21:03 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +            using var serv = new SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService>();
Why is that needed? It seems unused.

2023-02-25 21:17 UTC, emmauss commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +            using var serv = new SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService>();
It's unused. Removed

2023-02-26 01:08 UTC, AcK77 reviewed
I haven't reviewed too much for now, I've just REd needed values ;)

2023-02-26 01:08 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> +        // TODO: RE the actual buffer size
Those are the real values found by RE ;)

```csharp
private const int BcatMaxSessionsCount = 8;
private const int BcatTotalMaxSessionsCount = BcatMaxSessionsCount * 4; // 4 is the number of services

private const int PointerBufferSize = 0x400;
private const int MaxDomains = 64;
private const int MaxDomainObjects = 64;
private const int MaxPortsCount = 4; // 4 is the number of services
```

2023-02-26 01:08 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> +            _serverManager.RegisterObjectForServer(new ServiceCreator("bcat:s"), ServiceName.Encode("bcat:s"), BcatMaxSessionsCount);
Found by RE:
```c
sub_7100007C20(port_index, service_name, permission_level);
sub_7100007C20(0, "bcat:u", 1);
sub_7100007C20(1, "bcat:s", 2);
sub_7100007C20(2, "bcat:m", 6);
sub_7100007C20(3, "bcat:a", 0xFFFFFFFF);
```

It could be nice to do the same thing as it done in `prepo` service.
Additionally to that, I don't like get the service string twice on the same line.

2023-02-26 01:08 UTC, AcK77 commented on Ryujinx.Horizon/Prepo/PrepoIpcServer.cs
> +        private static readonly ManagerOptions _prepoManagerOptions = new(PointerBufferSize, MaxDomains, MaxDomainObjects, false);
Nice catch!

2023-02-26 01:08 UTC, AcK77 commented on Ryujinx.Horizon/Prepo/PrepoIpcServer.cs
>          private const int MaxDomainObjects  = 16;
The above const is wrong (Checked by RE):
```csharp
private const int PointerBufferSize = 0x3800;
```
It should be:
```csharp
private const int PointerBufferSize = 0x80;
```
Can you fix it too please ?

2023-03-04 23:08 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> +        private ServerManager _serverManager;
```suggestion
        private BcatServerManager _serverManager;
```

2023-03-04 23:08 UTC, gdkchan commented on Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> +            _serverManager = new ServerManager(allocator, _sm, MaxPortsCount, _bcatManagerOptions, BcatTotalMaxSessionsCount);
```suggestion
            _serverManager = new BcatServerManager(allocator, _sm, MaxPortsCount, _bcatManagerOptions, BcatTotalMaxSessionsCount);
```

2023-05-02 10:42 UTC, AcK77 requested changes
This needs a rebase aswell!

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> +        private const int BcatTotalMaxSessionsCount = BcatMaxSessionsCount * 4; // 4 is the number of services
Comment can be removed

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> +        private const int MaxPortsCount = 4; // 4 is the number of services
Comment can be removed

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/BcatServerManager.cs
> +            return (BcatPortIndex)portIndex switch
Could be nice to handle the PermissionLevel here and in `BcatService` the same way it’s done in prepo since I gave you the values in a previous comment. Even if the permission field is unused.

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +        public Result CreateBcatService(out IBcatService service, [ClientProcessId] ulong pid)
```suggestion
        public Result CreateBcatService(out IBcatService bcatService, [ClientProcessId] ulong pid)
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            var rc = _base.Get.CreateDeliveryCacheStorageService(ref serv.Ref, pid);
```suggestion
            var resultCode = _base.Get.CreateDeliveryCacheStorageService(ref serv.Ref, pid);
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator.cs
> +            var rc = _base.Get.CreateDeliveryCacheStorageServiceWithApplicationId(ref serv.Ref, new LibHac.ApplicationId(applicationId.Id));
```suggestion
            var resultCode = _base.Get.CreateDeliveryCacheStorageServiceWithApplicationId(ref serv.Ref, new LibHac.ApplicationId(applicationId.Id));
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheDirectoryService.cs
> +        private SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService> _base;
```suggestion
        private SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService> _libHacService;
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheFileService.cs
> +        private SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheFileService> _base;
```suggestion
        private SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheFileService> _libHacService;
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +        private SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheStorageService> _base;
```suggestion
        private SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheStorageService> _libHacService;
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +        public DeliveryCacheStorageService(ref SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheStorageService> baseService)
```suggestion
        public DeliveryCacheStorageService(ref SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheStorageService> libHacService)
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +            using var serv = new SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheFileService>();
```suggestion
            using var libHacService = new SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheFileService>();
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +            var rc = _base.Get.CreateFileService(ref serv.Ref);
```suggestion
            var resultCode = _base.Get.CreateFileService(ref serv.Ref);
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheFileService.cs
> +        public DeliveryCacheFileService(ref SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheFileService> baseService)
```suggestion
        public DeliveryCacheFileService(ref SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheFileService> libHacService)
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheDirectoryService.cs
> +        public DeliveryCacheDirectoryService(ref SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService> baseService)
```suggestion
        public DeliveryCacheDirectoryService(ref SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService> libHacService)
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +            using var serv = new SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService>();
```suggestion
            using var libHacService = new SharedRef<LibHac.Bcat.Impl.Ipc.IDeliveryCacheDirectoryService>();
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheStorageService.cs
> +            var rc = _base.Get.CreateDirectoryService(ref serv.Ref);
```suggestion
            var resultCode = _base.Get.CreateDirectoryService(ref serv.Ref);
```

2023-05-02 10:42 UTC, AcK77 commented on Ryujinx.Horizon/Bcat/Types/BcatPortIndex.cs
> +        System,
```suggestion
        System
```

2023-05-04 14:26 UTC, AcK77 approved these changes

2023-05-04 14:26 UTC, merged