support space in path
Ryujinx/Ryujinx pull request #4462
Opened 2023-02-21 21:17 UTC by TimeZlicer

This should add support for space in any path causing build errors mentioned in #4434

2023-02-21 21:26 UTC, lucicam commented
ah, just noticed your PR, I'll close mine since this already fixes it :)

2023-03-04 16:00 UTC, TSRBerry requested changes
Sorry for the late review! Commented some nitpicks and one change request, but otherwise lgtm!

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +APP_BUNDLE_DIRECTORY="$OUTPUT_DIRECTORY"/Ryujinx.app
I'd like to put the complete path in quotes.
```suggestion
APP_BUNDLE_DIRECTORY="$OUTPUT_DIRECTORY/Ryujinx.app"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +mkdir "$APP_BUNDLE_DIRECTORY"/Contents/Resources
```suggestion
mkdir -p "$APP_BUNDLE_DIRECTORY/Contents"
mkdir "$APP_BUNDLE_DIRECTORY/Contents/Frameworks"
mkdir "$APP_BUNDLE_DIRECTORY/Contents/MacOS"
mkdir "$APP_BUNDLE_DIRECTORY/Contents/Resources"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +chmod u+x "$APP_BUNDLE_DIRECTORY"/Contents/MacOS/Ryujinx
```suggestion
cp "$PUBLISH_DIRECTORY/Ryujinx.Ava" "$APP_BUNDLE_DIRECTORY/Contents/MacOS/Ryujinx"
chmod u+x "$APP_BUNDLE_DIRECTORY/Contents/MacOS/Ryujinx"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +cp "$PUBLISH_DIRECTORY"/*.dylib "$APP_BUNDLE_DIRECTORY"/Contents/Frameworks
```suggestion
cp "$PUBLISH_DIRECTORY/*.dylib" "$APP_BUNDLE_DIRECTORY/Contents/Frameworks"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +cp -r "$PUBLISH_DIRECTORY"/THIRDPARTY.md "$APP_BUNDLE_DIRECTORY"/Contents/Resources
```suggestion
cp Info.plist "$APP_BUNDLE_DIRECTORY/Contents"
cp Ryujinx.icns "$APP_BUNDLE_DIRECTORY/Contents/Resources/Ryujinx.icns"
cp updater.sh "$APP_BUNDLE_DIRECTORY/Contents/Resources/updater.sh"
cp -r "$PUBLISH_DIRECTORY/THIRDPARTY.md" "$APP_BUNDLE_DIRECTORY/Contents/Resources"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +echo -n "APPL????" > "$APP_BUNDLE_DIRECTORY"/Contents/PkgInfo
```suggestion
echo -n "APPL????" > "$APP_BUNDLE_DIRECTORY/Contents/PkgInfo"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +python3 bundle_fix_up.py "$APP_BUNDLE_DIRECTORY" MacOS/Ryujinx
```suggestion
python3 bundle_fix_up.py "$APP_BUNDLE_DIRECTORY MacOS/Ryujinx"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +    codesign sign --entitlements-xml-path "$ENTITLEMENTS_FILE_PATH" "$APP_BUNDLE_DIRECTORY"
```suggestion
    rcodesign sign --entitlements-xml-path "$ENTITLEMENTS_FILE_PATH" "$APP_BUNDLE_DIRECTORY"
```
Don't change the executable here.

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +UNIVERSAL_APP_BUNDLE="$OUTPUT_DIRECTORY"/Ryujinx.app
```suggestion
ARM64_APP_BUNDLE="$TEMP_DIRECTORY/output_arm64/Ryujinx.app"
X64_APP_BUNDLE="$TEMP_DIRECTORY/output_x64/Ryujinx.app"
UNIVERSAL_APP_BUNDLE="$OUTPUT_DIRECTORY/Ryujinx.app"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +dotnet publish -c Release -r osx-x64 -o "$TEMP_DIRECTORY"/publish_x64 $DOTNET_COMMON_ARGS Ryujinx.Ava
```suggestion
dotnet publish -c Release -r osx-arm64 -o "$TEMP_DIRECTORY/publish_arm64" $DOTNET_COMMON_ARGS Ryujinx.Ava
dotnet publish -c Release -r osx-x64 -o "$TEMP_DIRECTORY/publish_x64" $DOTNET_COMMON_ARGS Ryujinx.Ava
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +rm -rf "$TEMP_DIRECTORY"/publish_x64/libarmeilleure-jitsupport.dylib
```suggestion
rm -rf "$TEMP_DIRECTORY/publish_x64/libarmeilleure-jitsupport.dylib"
```
You could also fix the typo above if you want. "Get rid" instead of "Get ride".

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +rm -rf "$TEMP_DIRECTORY"/publish_arm64/libsoundio.dylib
```suggestion
rm -rf "$TEMP_DIRECTORY/publish_arm64/libsoundio.dylib"
```
Same typo here.

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +./create_app_bundle.sh "$TEMP_DIRECTORY"/publish_arm64 "$TEMP_DIRECTORY"/output_arm64 "$ENTITLEMENTS_FILE_PATH"
```suggestion
pushd "$BASE_DIR/distribution/macos"
./create_app_bundle.sh "$TEMP_DIRECTORY/publish_x64" "$TEMP_DIRECTORY/output_x64" "$ENTITLEMENTS_FILE_PATH"
./create_app_bundle.sh "$TEMP_DIRECTORY/publish_arm64" "$TEMP_DIRECTORY/output_arm64" "$ENTITLEMENTS_FILE_PATH"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +rm "$UNIVERSAL_APP_BUNDLE"/$EXECUTABLE_SUB_PATH
```suggestion
rm "$UNIVERSAL_APP_BUNDLE/$EXECUTABLE_SUB_PATH"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +python3 "$BASE_DIR"/distribution/macos/construct_universal_dylib.py "$ARM64_APP_BUNDLE" "$X64_APP_BUNDLE" "$UNIVERSAL_APP_BUNDLE" "**/*.dylib"
```suggestion
python3 "$BASE_DIR/distribution/macos/construct_universal_dylib.py" "$ARM64_APP_BUNDLE" "$X64_APP_BUNDLE" "$UNIVERSAL_APP_BUNDLE" "**/*.dylib"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +$LIPO "$ARM64_APP_BUNDLE"/$EXECUTABLE_SUB_PATH "$X64_APP_BUNDLE"/$EXECUTABLE_SUB_PATH -output "$UNIVERSAL_APP_BUNDLE"/$EXECUTABLE_SUB_PATH -create
```suggestion
$LIPO "$ARM64_APP_BUNDLE/$EXECUTABLE_SUB_PATH" "$X64_APP_BUNDLE/$EXECUTABLE_SUB_PATH" -output "$UNIVERSAL_APP_BUNDLE/$EXECUTABLE_SUB_PATH" -create
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +rm "$UNIVERSAL_APP_BUNDLE"/Contents/Info.plist.bck
```suggestion
sed -r -i.bck "s/\%\%RYUJINX_BUILD_VERSION\%\%/$VERSION/g;" "$UNIVERSAL_APP_BUNDLE/Contents/Info.plist"
sed -r -i.bck "s/\%\%RYUJINX_BUILD_GIT_HASH\%\%/$SOURCE_REVISION_ID/g;" "$UNIVERSAL_APP_BUNDLE/Contents/Info.plist"
rm "$UNIVERSAL_APP_BUNDLE/Contents/Info.plist.bck"
```

2023-03-04 16:00 UTC, TSRBerry commented on distribution/macos/create_macos_release.sh
> +python3 "$BASE_DIR"/distribution/misc/add_tar_exec.py $RELEASE_TAR_FILE_NAME "Ryujinx.app/Contents/MacOS/Ryujinx" "Ryujinx.app/Contents/MacOS/Ryujinx"
```suggestion
python3 "$BASE_DIR/distribution/misc/add_tar_exec.py" $RELEASE_TAR_FILE_NAME "Ryujinx.app/Contents/MacOS/Ryujinx" "Ryujinx.app/Contents/MacOS/Ryujinx"
```

2023-03-04 22:27 UTC, TimeZlicer commented on distribution/macos/create_app_bundle.sh
> +python3 bundle_fix_up.py "$APP_BUNDLE_DIRECTORY" MacOS/Ryujinx
thanks @TSRBerry though _"$APP_BUNDLE_DIRECTORY"_ and _MacOS/Ryujinx_ are separate input parameters to _bundle_fix_up.py_ 😉

2023-03-04 22:30 UTC, TSRBerry commented on distribution/macos/create_app_bundle.sh
> +python3 bundle_fix_up.py "$APP_BUNDLE_DIRECTORY" MacOS/Ryujinx
Ah whoops, sorry!

2023-03-04 22:51 UTC, TSRBerry approved these changes
Lgtm, thank you!

2023-03-08 14:41 UTC, TSRBerry approved these changes

2023-03-12 15:48 UTC, gdkchan approved these changes
lgtm, thanks.

2023-03-12 16:21 UTC, merged