Added check for eventual symlink when displaying game files.
Ryujinx/Ryujinx pull request #4526
Opened 2023-03-09 22:14 UTC by Shalito01

2023-03-17 12:44 UTC, TSRBerry commented
Could you please add a description and explain why you made this change?

Also you might want to check that commit, it looks like you are using two Github accounts and probably committed with the wrong identity?

2023-03-20 00:38 UTC, TSRBerry requested changes
I can think we might be able to solve this issue in a better/simpler way.

Let me know what you think about that.

2023-03-20 00:38 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +
I think we could solve this in a better way if we combine this step with the other operations when we add application paths to the list.

```suggestion
```

2023-03-20 00:38 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                foreach (string appPath in applications)
```suggestion
                foreach (string applicationPath in applications)
```

2023-03-20 00:38 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +
```suggestion

                            var fileInfo = new FileInfo(app);
```
If we create an instance of `FileInfo` here, we are able to simplify the steps below and check for symlinks as well.

2023-03-20 00:38 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
>                              string extension = Path.GetExtension(app).ToLower();
```suggestion
                            string extension = fileInfo.Extension.ToLower();
```

2023-03-20 00:38 UTC, TSRBerry commented on Ryujinx.Ui.Common/App/ApplicationLibrary.cs
>                                  applications.Add(app);
```suggestion
                            if (!fileInfo.Attributes.HasFlag(FileAttributes.Hidden) && extension is ".nsp" or ".pfs0" or ".xci" or ".nca" or ".nro" or ".nso")
                            {
                                var fullPath = fileInfo.ResolveLinkTarget(true)?.FullName ?? fileInfo.FullName;

                                applications.Add(fullPath);
```

Now we only need to add a check for symlinks here and resolve the actual path before we add it to the list of applications.

2023-03-20 07:21 UTC, Shalito01 commented
Yeah, I think it's a lot better in this way.

2023-04-15 12:22 UTC, riperiperi approved these changes
I think this makes sense.

2023-04-15 15:47 UTC, TSRBerry approved these changes
I was waiting for a new review request here, but seems like everything is already done.
Make sure to re-request reviewers once you are done adding changes, so we get a notification to review again.

Lgtm!

2023-04-15 16:11 UTC, merged