Add
Ryujinx/Ryujinx pull request #4555
Opened 2023-03-18 02:22 UTC by NitroTears

This is for [[Feature Request] Ability to hide file types in Game List (#4281)](https://github.com/Ryujinx/Ryujinx/issues/4281)

The config file format version has been bumped to 45
 - Also fixed the version 44 check (with antialiasing/scaling filter accidentally being logged as 42)
 - This includes a HiddenFilesTypes struct, HiddenFileTypesSettings class ect.

A dropdown of checkboxes identical to Enable GUI Columns has been added to check which file types should not be shown on the game list.

[Here is a gif of it in action](https://cdn.discordapp.com/attachments/410432399500115968/1086464759727132762/gifnamehere.gif) (as posted on the Ryujinx discord)

 Happy to discuss If you want me to change anything or the like.

2023-03-19 10:49 UTC, NitroTears commented
The Ava version has been added. Just waiting on minor change suggestions / review before finalising.

2023-03-20 08:26 UTC, NitroTears commented
The logic to `hide` is now to `show` as per feedback. That should be it!

2023-03-21 00:06 UTC, TSRBerry requested changes
I think we might be able to simplify this a bit more. Could you take a look at the comments?

2023-03-21 00:06 UTC, TSRBerry commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +        private CheckBox[] GenerateHideFileTypeItems()
```suggestion
        private CheckBox[] GenerateToggleFileTypeItems()
```

2023-03-21 00:06 UTC, TSRBerry commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +            HideFileTypesMenuItem.Items = GenerateHideFileTypeItems();
```suggestion
            ToggleFileTypesMenuItem.Items = GenerateToggleFileTypeItems();
```

2023-03-21 00:06 UTC, TSRBerry commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +                }
Could you add an enum for the file types and change this to a for-loop?

The file type enum can then also be used in a few other cases.

2023-03-21 00:06 UTC, TSRBerry commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml
> +				<MenuItem Name="HideFileTypesMenuItem" Header="{locale:Locale MenuBarShownFileTypes}" />
```suggestion
				<MenuItem Name="ToggleFileTypesMenuItem" Header="{locale:Locale MenuBarShownFileTypes}" />
```

2023-03-21 00:06 UTC, TSRBerry commented on Ryujinx.Ava/Assets/Locales/en_US.json
> +  "MenuBarShownFileTypes": "Show File Types",
```suggestion
  "MenuBarShowFileTypes": "Show File Types",
```

2023-03-21 03:22 UTC, NitroTears commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +                }
I think I *mostly* can at a quick look.

```cs
List<CheckBox> checkBoxes = new List<CheckBox>();

foreach (string type in Enum.GetNames(typeof (FileTypes)))
{
    checkBoxes.Add(new CheckBox()
    {
        Content = $".{type}",
        IsChecked = ConfigurationState.Instance.Ui.ShownFileTypes.NSP.Value,
        Command = MiniCommand.Create(() => ViewModel.ToggleFileType(type))
    });
}
```

With the `IsChecked` property, is there I way I can dynamically change the value that is being looked at based on the `type` string. I know I can't use `Ui.ShownFileTypes[type].Value` like I can in JS. What do you think?

2023-03-21 20:52 UTC, TSRBerry commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +                }
The only way I know to access `ShownFileTypes` like that would be using Reflection.

But I think it might be easier to write an [extension method](https://learn.microsoft.com/en-us/dotnet/api/system.enum?view=net-7.0#adding-enumeration-methods) for this enum, which returns the proper value.
You could then use that to (sort of) dynamically get the value you need here.

2023-03-22 10:16 UTC, NitroTears commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +                }
I've justed added the commits with the review feedback changes and my try at that extension method. 
Here is the code snippet for quick reference.

`MainMenuBarView.axaml.cs`
```cs
checkBoxes.Add(new CheckBox()
{
    Content = $".{fileName}",
    IsChecked = ((FileTypes)item).GetConfigValue(ConfigurationState.Instance.Ui.ShownFileTypes),
    Command = MiniCommand.Create(() => ViewModel.ToggleFileType(fileName))
});
```

`FileTypes.cs`
```cs
public static bool GetConfigValue(this FileTypes type, ShownFileTypeSettings config)
{
    return ((ReactiveObject<bool>) typeof(ShownFileTypeSettings).GetProperty(Enum.GetName(type))
        .GetValue(config, null)).Value;
}
```

It does look a tad messy, in exchange for it being more consice. I have added some documentation to the function as well. Let me know what you think.

2023-03-22 21:25 UTC, TSRBerry commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +                }
This is what I had in mind:

```cs
public static bool GetConfigValue(this FileTypes type, ShownFileTypeSettings config) => type switch
{
    FileTypes.NSP => config.NSP.Value,
    FileTypes.PFS0 => config.PFS0.Value,
    FileTypes.XCI => config.XCI.Value,
    FileTypes.NCA => config.NCA.Value,
    FileTypes.NRO => config.NRO.Value,
    FileTypes.NSO => config.NSO.Value,
    _ => throw new ArgumentOutOfRangeException(nameof(type), type, null)
};
```
This also avoids the use of reflection.

Could you move the extensions into a new file? I think that would be more in line with the rest of the extensions we added in this project.

2023-03-23 06:33 UTC, NitroTears commented on Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +                }
That's all done now 👍🏻

2023-03-23 11:45 UTC, TSRBerry approved these changes
Lgtm, thank you!

2023-03-24 13:23 UTC, marysaka requested changes
Only one thing.

2023-03-24 13:23 UTC, marysaka commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +            _ = fileType switch
Can you fix the warning here?

2023-03-24 13:38 UTC, NitroTears commented on Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +            _ = fileType switch
Added the suggested default case, and an argument out of range exception for it.

2023-03-26 08:49 UTC, NitroTears commented
Just checking if there is anything else? @marysaka

2023-03-26 12:12 UTC, marysaka approved these changes

2023-03-26 17:43 UTC, TSRBerry commented
> Just checking if there is anything else? @/marysaka

Make sure to re-request reviews if you addressed everything, otherwise it will be hard to notice you are done.

2023-04-16 01:03 UTC, merged