ServerBase thread safety
Ryujinx/Ryujinx pull request #4577
Opened 2023-03-22 01:33 UTC by jhorv

@lostromb [commented](https://github.com/Ryujinx/Ryujinx/pull/4537#issuecomment-1477130450) on closed PR #4537 about an intermittent exception when stopping emulation. This PR fixes some issues I found while investigating, and though I was unable to reproduce @lostromb's reported exception, I believe this will fix it.

- ServerBase.Dispose() could be (and often was) called multiple times.
- ServerBase.Dispose() had no checks to ensure the ServerLoop() had stopped first.
- Reworked the port and session storage to use a Dictionary only, instead of a Dictionary and List
- Reworked the locking to use a ReaderWriterLockSlim, and made every access of the port and session stores thread-safe.

2023-03-22 05:19 UTC, lostromb commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +        private int _isDisposed = 0;
Is this used?
In my own code I typically adopt this pattern at the top of every Dispose() function to enforce single-dispose semantics using an integer flag like this:
`if (Interlocked.CompareExchange(ref _isDisposed, 1, 0) != 0) return;`
I assume you were going for a similar design.

2023-03-22 05:25 UTC, lostromb commented
I know in the past when I looked at the shutdown sequence, I found it was not a simple case of just making sure everything was disposed. There were cases such as queuing a FIFO message to the GPU thread to start disposing of textures, handles, etc. but then also we were trying to dispose of the FIFO queue itself at the same time. I imagine there could be similar cases where we're trying to dispose of host resources and IPC channels and such while they are already half-disposed, which might lead to thread contention or deadlocks if you don't carefully control which mutexes get held during disposal routines. Does someone more familiar with the code know if this is a concern?

2023-03-22 19:47 UTC, jhorv commented on Ryujinx.HLE/HOS/Services/ServerBase.cs
> +        private int _isDisposed = 0;
Yes, it's at the top of the Dispose(bool).

2023-05-04 18:07 UTC, riperiperi commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    Logger.Warning?.Print(LogClass.Service, $"the ServerBase thread didn't signal it has stopped within {ThreadStoppedWaitTimeout:g}, resources may be leaked!");
```suggestion
                    Logger.Warning?.Print(LogClass.Service, $"The ServerBase thread didn't signal it has stopped within {ThreadStoppedWaitTimeout:g}, resources may be leaked!");
```

Also, it's not really "may be leaked" if you're skipping the clear and dispose of everything below.

2023-05-04 18:24 UTC, riperiperi commented
I encountered this error when closing BOTW with the latest CI build:
![image](https://user-images.githubusercontent.com/6294155/236294864-a7e29616-be08-42c8-a32a-e1cf1ef27fa9.png)

2023-05-04 18:30 UTC, riperiperi requested changes

2023-05-04 18:30 UTC, riperiperi commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                if (!_threadStopped.Wait(ThreadStoppedWaitTimeout))
This can be used after it's disposed.

2023-05-04 23:21 UTC, riperiperi commented
It still hung on close a bunch of times, but I think there are a few other reasons it can do that (mostly GAL related). I wasn't able to get it to crash.
![image](https://user-images.githubusercontent.com/6294155/236345747-142e7688-f9c2-4ba1-a6e5-f280836483e3.png)

2023-05-04 23:25 UTC, riperiperi approved these changes
Looks good. Honestly I'm not sure why these are being disposed multiple times in the first place...

2023-05-04 23:41 UTC, jhorv commented
> It still hung on close a bunch of times, but I think there are a few other reasons it can do that (mostly GAL related). I wasn't able to get it to crash.

I've noticed master without this PR hanging on close a bunch lately. Haven't looked into it yet.

2023-05-05 14:08 UTC, lostromb commented
I've considered in the past adding some kind of feedback signal to say "send dispose commands to gpu thread, wait for gpu thread to signal finished, then dispose of queue." But I think that's outside the scope of this review

2023-05-07 21:32 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    if (!_threadStopped.Wait(ThreadStoppedWaitTimeout))
Can't this just call `Thread.Join` instead of waiting this event, since it wants to wait for the thread exit? You would need to add something like `_selfThread = KernelStatic.GetCurrentThread();` on the `ServerLoop` method, and then call `_selfThread.HostThread.Join();`.  It is of course, not needed if dispose is called from the same thread if would wait for (and might be even invalid to call `Join` in that case). Also it would be invalid if dispose is called before the thread starts, so it could be worth to add a null check too.

2023-05-08 02:41 UTC, jhorv commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    if (!_threadStopped.Wait(ThreadStoppedWaitTimeout))
Great idea, fixed in #5331f94

2023-05-12 12:00 UTC, marysaka approved these changes
lgtm

2023-05-12 18:59 UTC, IsaacMarovitz approved these changes
Fixed hang when stopping emulation in TOTK for me 👍

2023-05-13 17:41 UTC, noxifoxi commented
> Fixed hang when stopping emulation in TOTK for me +1

I merged this PR to the master branch on my test fork, and it still hangs for me

2023-05-13 18:43 UTC, lostromb commented
> > Fixed hang when stopping emulation in TOTK for me +1
> 
> I merged this PR to the master branch on my test fork, and it still hangs for me

Again, there are other known issues that could cause deadlock on shutdown, this is just addressing one of them

2023-05-16 20:37 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
Why is the time out necessary?

2023-05-16 20:49 UTC, jhorv commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
With the timeout it will log a message instead of possibly hanging on shutdown.

2023-05-19 16:21 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                return _sessions[serverSessionHandle];
```suggestion

                return _sessions[serverSessionHandle];
```

2023-05-19 16:22 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
It doesn't feel right to do this. If it needs that to exit properly, then there's still something wrong with the code.

2023-05-19 16:22 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    return;
```suggestion

                    return;
```

2023-05-19 16:22 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
```suggestion
                if (_selfThread.HostThread.ManagedThreadId != Environment.CurrentManagedThreadId && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
```

2023-05-19 16:27 UTC, jhorv commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
I'm not sure there even is an issue here, but if there is, at least it writes info to the log. The alternative is to hang silently, providing no useful info until someone attaches a debugger.

2023-05-19 16:37 UTC, jhorv commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
What if after logging, I add a call to `_selfThread.HostThread.Join(Timeout.Infinite)`? I'd adjust the log message to say something like "about to try waiting indefinitely for this thread to finish".

2023-05-19 16:41 UTC, jhorv commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
Also, I don't believe this thread is known to hang - this PR doesn't fix hangs on stop, it fixes exceptions on stop due to a race condition. I added a timeout here because I think timeouts are better than infinite waits, if only to log information about what happened.

2023-05-19 17:06 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/ServerBase.cs
> +                    && _selfThread.HostThread.Join(ThreadJoinTimeout) == false)
The sentence has a double negative that makes it more confusing now. You said that you "don't believe" that it "is not known to hang", which means  that it is known to hang I guess? But I assume that you mean the opposite.

Anyway my original comment is because such approaches feel `On Error Resume Next` levels of hacky. If the logic is correct and we don't expect it to ever hang, then there's no need for a time out. I guess it is fair putting it as a fail safe, but we usually don't do that. Also having a time out to ignore the hang would make it harder to debug since you can't just attach a debugger to inspect the invalid state anymore. I guess my main question is, why do we need this? Just to know if a hang is caused by `ServerBase` or something else when it happens, without needing to have a debugger attached?

2023-05-19 23:49 UTC, gdkchan approved these changes
lgtm, thanks.

2023-05-21 19:28 UTC, merged