[GUI] Add network interface dropdown
Ryujinx/Ryujinx pull request #4597
Opened 2023-03-25 01:05 UTC by TSRBerry

I thought this was added to master ages ago and didn't realize it was still missing.
Thank you to @shadowninja108 for making me aware of this.

This is almost 1:1 taken from the LDN build with some minor adjustments and the addition of the lan-interface-id parameter for `Ryujinx.Headless.SDL2`.

2023-04-14 22:16 UTC, riperiperi requested changes
GTK is unable to save the network interface. Make sure you test features on both UIs.

2023-04-14 22:31 UTC, TSRBerry commented
Sorry about that. It's fixed now!

2023-04-14 23:04 UTC, riperiperi approved these changes
LGTM, nice to see this ported over.

2023-04-16 07:12 UTC, AcK77 approved these changes

2023-04-16 15:25 UTC, merged