Add Titlebar Color Support On Windows 11+
Ryujinx/Ryujinx pull request #4619
Opened 2023-03-30 12:20 UTC by SamarthCat

Windows 11 supports custom colors in the titlebar.
The added class will set the titlebar color and respect the selected theme.
The can be extended in the future to support other platforms.

2023-03-30 13:29 UTC, SamarthCat commented
> Could you add this for Avalonia as well? We will _soon_ be moving away from Gtk, so it'd be nice to have this for Avalonia as well.

I'll see what I can do.

2023-03-30 18:56 UTC, SamarthCat commented
Alright, I've added support for Avalonia.

2023-03-31 14:47 UTC, AcK77 commented
Screenshots for a before/after could be nice :)

2023-03-31 17:33 UTC, SamarthCat commented
Before:
![image](https://user-images.githubusercontent.com/79756986/229190079-f626e872-22b1-459e-9831-07bfb4eda4de.png)


After:
![image](https://user-images.githubusercontent.com/79756986/229189826-fe75a22a-f310-4dc8-bdf9-10a80ce7f5f8.png)

2023-03-31 18:05 UTC, OldManKain commented
Doesn't Windows 11 already have this?  My title bar is the same color as as I have it set in windows on Focus then changes to gray when unfocused.

### Focused
![image](https://user-images.githubusercontent.com/47503099/229196432-d5109c06-e85d-4065-8689-5e1df2476db4.png)

### Unfocused
![image](https://user-images.githubusercontent.com/47503099/229196504-5508f657-dca7-441c-b623-ca741ab96650.png)

2023-03-31 18:10 UTC, SamarthCat commented
> Doesn't Windows 11 already have this? My title bar is the same color as as I have it set in windows on Focus then changes to gray when unfocused.

It seems you have "Show accent color on title bars and window borders" turned on in windows settings.
This pr overrides this setting just like vscode, windows mail, task manager, and a ton of other apps.

2023-03-31 19:05 UTC, jojodunet commented
Is this PR set this window « issue #4416 » to the color of the selected theme? (instead of the white color, at least until the issue be solved)

2023-03-31 22:35 UTC, OldManKain commented
Does this PR remove the functionality of ```Show accent color on title bars and window borders```?

2023-04-01 06:28 UTC, SamarthCat commented
> Does this PR remove the functionality of `Show accent color on title bars and window borders`?

It does remove the functionality for any windows owned by Ryujinx.
I don't think it's really an issue though, since even windows built-in apps remove this functionality.

![image](https://user-images.githubusercontent.com/79756986/229269529-7f053ee4-3441-4372-a13f-a69a63cde7df.png)

You see, task manager and notepad don't follow this setting, but 7-zip does.
I think Microsoft is phasing out the feature as most modern first-party or third-party apps don't support it.

2023-04-05 03:24 UTC, AcK77 requested changes
There is a quick overview, this is what I noticed regarding the whole PR:

- It could be nice to store `TitlebarHelper.cs` in `https://github.com/Ryujinx/Ryujinx/tree/master/Ryujinx.Ui.Common/Helper` to avoid duplicate it for both UI.
- `Titlebar` should be renamed `TitleBar`.

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +
Should be removed

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +
Remove extra empty line

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +    public class TitlebarHelper {
```suggestion
    public class TitlebarHelper
    {
```

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +        #region Native Imports
Should be removed

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +        [DllImport("kernel32.dll", CharSet=CharSet.Unicode)] static extern IntPtr GetModuleHandle([MarshalAs(UnmanagedType.LPWStr)] string lpModuleName);
Should use `LibraryImport` instead

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +        public static void Initialize()
This should be done in the same way as https://github.com/Ryujinx/Ryujinx/blob/master/Ryujinx.Ava/Common/Locale/LocaleManager.cs#L20 then you will not have to call `Initialize()` but `TitleBarHelper.Instance.ThemeChanged();`

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +        static IntPtr WindowCreationDetector;
This is unused, you can remove it.

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +                //Listen For Window Created Events
Useless comment

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +                WindowCreationDetector = SetWindowsHookEx(10, OnShellCallback, GetModuleHandle(current.MainModule.ModuleName), (uint)current.Threads[0].Id);
Could be nice to know what the `hookType` 10 is. Maybe you should use a const for it?

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +            if (code == 1) // HSHELL_WINDOWCREATED
Maybe you could use a const named `HSHELL_WINDOWCREATED` instead

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +        static IntPtr OnShellCallback(int code, IntPtr wParam, IntPtr lParam)
```suggestion
        private static IntPtr OnShellCallback(int code, IntPtr wParam, IntPtr lParam)
```

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +        }
```suggestion
        private static void ApplyTitleBarColor(IntPtr hwnd)
        {
            if (OperatingSystem.IsWindows())
            {
                int color = ConfigurationState.Instance.Ui.BaseStyle == "Dark" ? 0x202020 : 0xF3F3F3;

                if (hwnd == IntPtr.Zero)
                {
                    foreach (IntPtr handle in AppWindows)
                    {
                        DwmSetWindowAttribute(handle, 35, new int[] { color }, sizeof(int));
                    }
                }
                else 
                {
                    DwmSetWindowAttribute(hwnd, 35, new int[] { color }, sizeof(int));
                }
            }
        }
```

Could be nice to use a const for the attribute `35`.

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +        //Must Be Called When Theme Is Changed
Could be removed

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs
> +                AppWindows.Add(wParam);
When do you remove the handle from the list? Or what if the handle already exists?

2023-04-05 03:24 UTC, AcK77 commented on Ryujinx/Ui/Helper/TitlebarHelper.cs
> +        public static int GetThemeColor(){
When I rewrote this in `Ryujinx.Ava/UI/Helpers/TitlebarHelper.cs` I have notice this difference, maybe you should add the UI color code in their respective project, like `ThemeChanged(int color)` and then get the color before you call it.

2023-05-05 09:05 UTC, AcK77 commented
Any update about this? Needs a rebase too!

2023-05-16 03:37 UTC, lostromb commented on Ryujinx/Ui/Helper/TitlebarHelper.cs
> +            string ch = $"{(int)(color.Red*255):X2}{(int)(color.Green*255):X2}{(int)(color.Blue*255):X2}";
This could be replaced with bit shifting, right?
`int windowsColor = (((int)(color.Blue * 255) & 0xFF) << 16) | (((int)(color.Green * 255) & 0xFF) << 8) | (((int)(color.Red * 255) & 0xFF) << 0)`

2023-07-20 12:22 UTC, IsaacMarovitz commented
Superceeded somewhat by #4362

2023-10-08 08:47 UTC, closed without merging