Allow window to remember its size, position and state (GTK + Avalonia)
Ryujinx/Ryujinx pull request #4657
Opened 2023-04-08 12:19 UTC by MutantAura

Based on #4439 with support for Avalonia. 

As the two frameworks fight over data types and the like, GTK is given priority for now. It will be a quick job to edit and expand upon once deprecated e.g. WindowState could start in fullscreen instead of just maximised etc.

2023-04-12 01:21 UTC, gdkchan commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            ConfigurationState.Instance.Ui.WindowMaximized.Value = window.WindowState is WindowState.Maximized ? true : false;
This looks very weird, why can't it just do `window.WindowState == WindowState.Maximized` directly?

2023-04-12 01:21 UTC, gdkchan commented on Ryujinx/Ui/MainWindow.cs
> +                int windowWidth;
Should be probably be moved to a separate method instead of repeating this code twice?

2023-04-12 17:22 UTC, MutantAura commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            ConfigurationState.Instance.Ui.WindowMaximized.Value = window.WindowState is WindowState.Maximized ? true : false;
Not sure why I did that... changed.

2023-04-12 17:22 UTC, MutantAura commented on Ryujinx/Ui/MainWindow.cs
> +                int windowWidth;
Moved.

2023-04-16 06:59 UTC, AcK77 requested changes

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        public int WindowSizeWidth { get; set;}
It’s not possible to use `Rectangle` type instead? Since it already have X, Y, Width and Height field. Maybe the JSON serializing will cause issue.

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            SetWindowSizePosition(this);
```suggestion
            SetWindowSizePosition();
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +        private void SetWindowSizePosition(MainWindow window)
```suggestion
        private void SetWindowSizePosition()
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            window.Position = new PixelPoint(ConfigurationState.Instance.Ui.WindowPositionX,
```suggestion
            Position = new PixelPoint(ConfigurationState.Instance.Ui.WindowPositionX, 
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +        private void SaveWindowSizePosition(MainWindow window)
```suggestion
        private void SaveWindowSizePosition()
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            // Avalonia/GTK use different structures. Conversion is required for inter-operation.
```
            // Avalonia/GTK use different structures. Conversion is required for inter-operation.
```
It doesn’t make sense to have a comment about GTK in Avalonia, because when we will drop GTK, it will be pointless

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            ConfigurationState.Instance.Ui.WindowPositionX.Value = window.Position.X;
```suggestion
            ConfigurationState.Instance.Ui.WindowPositionX.Value = Position.X;
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            ConfigurationState.Instance.Ui.WindowMaximized.Value = window.WindowState == WindowState.Maximized;
```suggestion
            ConfigurationState.Instance.Ui.WindowMaximized.Value = WindowState == WindowState.Maximized;
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            ConfigurationState.Instance.Ui.WindowPositionY.Value = window.Position.Y;
```suggestion
            ConfigurationState.Instance.Ui.WindowPositionY.Value = Position.Y;
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            SaveWindowSizePosition(this);
```suggestion
            SaveWindowSizePosition();
```

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            Ui.WindowSizeWidth.Value                  = 1280;
Could be nice to set PositionX and PositionY to 0 for consistency (even if it’s already 0 as default)

2023-04-16 06:59 UTC, AcK77 commented on Ryujinx/Ui/MainWindow.cs
> +            Move(ConfigurationState.Instance.Ui.WindowPositionX, ConfigurationState.Instance.Ui.WindowPositionY);
Add a new empty line before and after

2023-04-16 12:19 UTC, MutantAura commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        public int WindowSizeWidth { get; set;}
This would involve introducing a System.Drawing dep in a few places and I'm not entirely sure how the JSON would parse it. I could give it a try but honestly not sure if the result would be any better.

2023-04-16 17:33 UTC, TSRBerry commented
The network interface dropdown PR also changed the config file version, so you might need to increase it here again

2023-04-16 18:34 UTC, MutantAura commented
Updated config file, added checks on the Avalonia side to ensure the window opens at a valid screen co-ordinate. Previously you could feed it arbitrary values/adjust your monitor config to break it.

2023-04-16 20:44 UTC, TSRBerry reviewed
Lgtm! I Just have 2 styling related comments.

2023-04-16 20:44 UTC, TSRBerry commented on Ryujinx/Ui/MainWindow.cs
> +            GetPosition(out windowXPos, out windowYPos);
```suggestion
            GetSize(out int windowWidth, out int windowHeight);
            GetPosition(out int windowXPos, out int windowYPos);
```
Could you inline these?

2023-04-16 20:44 UTC, TSRBerry commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            public ReactiveObject<bool> WindowMaximized { get; private set; }
Could you group these inside a `Window` subclass like the settings in `ShownFileTypeSettings` are?

2023-04-16 21:00 UTC, gdkchan commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        public int WindowSizeWidth { get; set;}
@TSRBerry Would the formatting check be able to catch this? (I did not check if whitespace formatting is enabled, I think it was disabled).

2023-04-16 21:26 UTC, TSRBerry commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        public int WindowSizeWidth { get; set;}
It's currently disabled, because it would remove all of the vertical alignments we have.

I was thinking a bit about this, but was also hoping for some input on #4670 regarding this.

2023-04-16 22:02 UTC, MutantAura commented on Ryujinx/Ui/MainWindow.cs
> +            GetPosition(out windowXPos, out windowYPos);
Yes!

2023-04-16 22:02 UTC, MutantAura commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            public ReactiveObject<bool> WindowMaximized { get; private set; }
Also yes

2023-04-16 22:03 UTC, MutantAura commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        public int WindowSizeWidth { get; set;}
Should all have correct spacing now.

2023-04-16 22:09 UTC, TSRBerry approved these changes
Awesome, thank you!

2023-04-27 13:20 UTC, marysaka reviewed
Thanks for the PR, I do have some comments

2023-04-27 13:20 UTC, marysaka commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml
> +    Height="{Binding WindowHeight}"
I don't see the default value being set on MainWindowViewModel, is that intended?

I think it's fine but that could maybe mess around with the UI designer. (if it even work)

2023-04-27 13:20 UTC, marysaka commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            Position = CheckScreenBounds(SavedPoint) ? SavedPoint : new PixelPoint(0,0);
Is (0,0) the center of the screen? If not that change the behavior we currently have. (aka centered)

2023-04-27 13:20 UTC, marysaka commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        /// A list of file types to be hidden in the games List
wrong comment copy pasta.
```suggestion
        /// Main window start-up position, size and state
```

2023-04-27 13:20 UTC, marysaka commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> -                configurationFileUpdated = true;
This shouldn't have been removed.

2023-04-27 13:20 UTC, marysaka commented on Ryujinx/Ui/MainWindow.cs
> +            DefaultHeight = monitorHeight < 760  ? monitorHeight : ConfigurationState.Instance.Ui.WindowStartup.WindowSizeHeight;
This logic differ from Avalonia here.
I do think we should have the same monitor size check in Avalonia too.

2023-04-27 13:43 UTC, gdkchan commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            Logger.Warning?.Print(LogClass.Application, $"Failed to find valid start-up coordinates. Defaulting to 0,0.");
```suggestion
            Logger.Warning?.Print(LogClass.Application, $"Failed to find valid start-up coordinates. Defaulting to 0, 0.");
```

2023-04-27 20:05 UTC, MutantAura commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml
> +    Height="{Binding WindowHeight}"
I can set a default but it should fall back to MinWidth/MinHeight in these scenarios, in all other situations it should pull from the config file (via migration or generation).

2023-04-27 20:32 UTC, MutantAura commented on Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            Position = CheckScreenBounds(SavedPoint) ? SavedPoint : new PixelPoint(0,0);
Fixed.

2023-04-27 20:32 UTC, MutantAura commented on Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        /// A list of file types to be hidden in the games List
Fixed.

2023-04-27 20:33 UTC, MutantAura commented on Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> -                configurationFileUpdated = true;
Fixed.

2023-04-28 08:46 UTC, marysaka commented on Ryujinx/Ui/MainWindow.cs
> +            DefaultHeight = monitorHeight < 760  ? monitorHeight : ConfigurationState.Instance.Ui.WindowStartup.WindowSizeHeight;
For this I think it's fine for now but we should probably keep the same logic between the two (aka remove this check or reproduce it if possible)

2023-04-28 08:46 UTC, marysaka approved these changes
Need a rebase but lgtm otherwise :+1:

2023-04-28 16:43 UTC, MutantAura commented on Ryujinx/Ui/MainWindow.cs
> +            DefaultHeight = monitorHeight < 760  ? monitorHeight : ConfigurationState.Instance.Ui.WindowStartup.WindowSizeHeight;
As outlined on discord I think it's best to remove. The theoretical situation this "solves" is virtually impossible and potentially undesirable. I'll try and speed up the work on: https://github.com/Ryujinx/Ryujinx/pull/4681 as I think it's a better solution if this were to ever be a problem.

2023-04-28 16:54 UTC, MutantAura commented
Rebased.

2023-04-28 20:59 UTC, merged