Linux: Automatically increase vm.max_map_count if it's too low
Ryujinx/Ryujinx pull request #4702
Opened 2023-04-20 22:07 UTC by TSRBerry

This PR adds a workaround for #3372 and result checking for memory related pinvoke calls.

If a game adds too many memory map areas Ryujinx will crash with a segmentation fault, which makes these issues difficult to debug.
But since @gdkchan was able to find the cause of this type of crash, we are able to temporarily increase `vm.max_map_count` while Ryujinx is running and reset it to the original value once Ryujinx was closed.

The threshold value in the script is just the default value that the [kernel documentation](https://kernel.org/doc/Documentation/sysctl/vm.txt) for `vm.max_map_count` suggested. This check is just supposed to make sure we aren't messing with the settings if the user has modified them already.

2023-04-22 12:25 UTC, riperiperi approved these changes
Looks sensible, though I'm not an expert on whether `262144` is high enough for all games. It would be nice if this stuff could be set when opening the main Ryujinx executable, too bad it can't.

2023-04-22 12:25 UTC, riperiperi commented on Ryujinx.Memory/MemoryManagementUnix.cs
> +            if (madvise(address, size, MADV_REMOVE) != 0)
I hope nothing else races to change permissions, otherwise these could crash the emulator where otherwise they did not. I suppose Decommit isn't used right now, so it's more a worry for another time...

2023-04-22 12:47 UTC, TSRBerry commented
I mean it could be, but we might not be able to revert to defaults if Ryujinx crashes.

2023-04-24 06:23 UTC, marysaka commented on Ryujinx.Memory/MemoryManagementUnix.cs
> +            if (madvise(address, size, MADV_REMOVE) != 0)
Shouldn't we just return false instead of throwing everywhere here?

that kind of change the behavior of the function entirely... and the return value doesn't meaning anything anymore.

2023-04-24 06:26 UTC, marysaka requested changes

2023-04-24 06:26 UTC, marysaka commented on distribution/linux/Ryujinx.sh
> +  pkexec sh -c 'sysctl -w vm.max_map_count=262144'
This required PolKit, we cannot assume that someone have it installed.

2023-04-24 06:26 UTC, marysaka commented on Ryujinx.Memory/WindowsShared/WindowsApi.cs
> +    [SupportedOSPlatform("windows")]
Cause warnings on build (see CI report)

2023-04-24 07:03 UTC, TSRBerry commented on distribution/linux/Ryujinx.sh
> +  pkexec sh -c 'sysctl -w vm.max_map_count=262144'
Do you have a suggestion on how to deal with that?

2023-04-24 20:59 UTC, TSRBerry commented on Ryujinx.Memory/MemoryManagementUnix.cs
> +            if (madvise(address, size, MADV_REMOVE) != 0)
Afaik Ryujinx would crash either way even if we return false here.

2023-04-25 17:56 UTC, TSRBerry commented
Requesting both reviews, since I essentially changed the whole thing again.

2023-04-25 17:59 UTC, TSRBerry commented on Ryujinx.Ui.Common/Helper/LinuxHelper.cs
> +        public const int RecommendedVmMaxMapCount = 65530;
I'm pretty sure we can go lower here, but I'll need community testing to figure this out.
I don't have any of the game in the referenced issue and can't trigger the issue on my side.

2023-04-25 18:00 UTC, TSRBerry commented on Ryujinx.Ui.Common/Helper/LinuxHelper.cs
> +        public const int RecommendedVmMaxMapCount = 524288;
I'm pretty sure we can go lower here, but I'll need community testing to figure this out.
I don't have any of the game in the referenced issue and can't trigger the issue on my side.

2023-05-06 00:12 UTC, riperiperi reviewed
How will this behave when Ryujinx is installed as a flatpak? I doubt that it'll be able to write sysctl.d config, not sure about the vm map count.

2023-05-06 00:43 UTC, TSRBerry commented
The flatpak probably wouldn't be able to do any of these things. :thinking: 

I'll need to think of something for that. :/

2023-05-06 23:00 UTC, TSRBerry commented
@riperiperi Currently flatpak users would see this warning (even if pkexec is installed, because it doesn't have access to it).
Would this be okay?

![image](https://user-images.githubusercontent.com/20988865/236649549-88fa3637-1cbc-443f-b595-94babe97a435.png)

Ideally we should use dbus to talk to polkitd, but I have no idea how to do that yet and it doesn't seem to be easy.

2023-05-08 11:32 UTC, marysaka approved these changes

2023-05-11 17:24 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            switch (response)
I'm not a huge fan of getting the whole `switch` duplicated between both UI just because of the `response` cast.
Even more because the `LinuxHelper` class is in `Ryujinx.Ui.Common`, everything should goes there.

2023-05-11 17:25 UTC, AcK77 commented on src/Ryujinx/Program.cs
> +                        switch ((int)response)
Sams comment as the Ava project.

2023-05-11 17:59 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            switch (response)
Well that would be the case for the updater as well, but since we use 2 different frameworks to display the dialogs I don't think it makes sense to combine them.

2023-05-11 18:01 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            switch (response)
Dialogs are before this part of the code. Here it's just dialog responses parsing. That's why I said that. But I'm agree for the updater too, There should be only one class...

2023-05-11 23:59 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            switch (response)
The dialog response codes are also different per framework here, unfortunately.

2023-05-12 01:28 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            switch (response)
Maybe you could change them into the same int values.

2023-05-28 23:16 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +            switch (response)
Meh, I kind of prefer to use the enum values here. Would you mind if I leave them as is?

2023-05-29 04:21 UTC, AcK77 approved these changes

2023-05-29 23:48 UTC, merged