Move logging to user base dir & Make config filename changable for releases
Ryujinx/Ryujinx pull request #4707
Opened 2023-04-22 16:58 UTC by TSRBerry

This PR moves logging from the application directory to the Ryujinx directory and moves the config filename to `ReleaseInformation.cs`.

The logging change was attempt a few times before, see #1530 and #2027. However I think we shouldn't assume the application directory is writable, since it's usually not the case. It's better to write log files to locations we expect to be writable anyway.

As a user I also don't need to keep track of two different directories, as everything I need to be aware of is handled in one directory.

As outlined in #2887 the config file change allows users to test PR builds without needing to worry about the config file they use for our release builds.

---

Closes #2887
Closes #1526

2023-05-16 06:11 UTC, marysaka approved these changes

2023-05-16 11:15 UTC, TSRBerry commented
Rebased!

2023-06-18 16:31 UTC, gdkchan commented
> As outlined in https://github.com/Ryujinx/Ryujinx/issues/2887 the config file change allows users to test PR builds without needing to worry about the config file they use for our release builds.

Won't this cause people testing PRs to have a lot of stray config files in the Ryujinx folder?

2023-06-19 00:41 UTC, TSRBerry commented
There will just be one new `PRConfig.json`. The idea is that this config is only used by PR builds and testers won't need to backup and restore their main config file if they switch between PR and release builds.

The `PRConfig.json` could still get reset by different PRs, but that's at least a bit better than resetting the main config file.

2023-06-22 17:47 UTC, AcK77 requested changes

2023-06-22 17:47 UTC, AcK77 commented on src/Ryujinx.Common/Logging/Logger.cs
> +        private static readonly Stopwatch Time;
```suggestion
        private static readonly Stopwatch _time;
```

2023-06-22 17:47 UTC, AcK77 commented on src/Ryujinx.Common/Logging/Logger.cs
> +        private static readonly bool[] EnabledClasses;
```suggestion
        private static readonly bool[] _enabledClasses;
```

2023-06-22 17:47 UTC, AcK77 commented on src/Ryujinx.Common/Logging/Logger.cs
> +        private static readonly List<ILogTarget> LogTargets;
```suggestion
        private static readonly List<ILogTarget> _logTargets;
```

2023-06-22 17:47 UTC, AcK77 commented on src/Ryujinx.Common/Logging/Logger.cs
> +        private static readonly StdErrAdapter StdErrAdapter;
```suggestion
        private static readonly StdErrAdapter _stdErrAdapter;
```

2023-06-22 17:47 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/FileSystemUtils.cs
> +        public static void CopyDirectory(string sourceDir, string destinationDir, bool recursive)
I think we already Copy/Move directories elsewhere in the code, maybe it's could be nice to use this one instead and remove duplicated code (if it's possible) ?

2023-06-22 17:47 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Helper/FileAssociationHelper.cs
> +        private static readonly string[] FileExtensions = { ".nca", ".nro", ".nso", ".nsp", ".xci" };
I'd prefer to keep private field with `_` and camelCase. (Same for other vars)

2023-06-22 17:47 UTC, AcK77 commented on distribution/linux/Ryujinx.desktop
> +Exec=Ryujinx.sh %f
Nice catch!

2023-07-31 22:08 UTC, TSRBerry commented on src/Ryujinx.Common/Utilities/FileSystemUtils.cs
> +        public static void CopyDirectory(string sourceDir, string destinationDir, bool recursive)
Done!

2023-10-12 16:03 UTC, AcK77 commented
> However I think we shouldn't assume the application directory is writable, since it's usually not the case. It's better to write log files to locations we expect to be writable anyway.

Maybe we should check if the Ryujinx folder is writable and if not we can write log files to another folder as your PR suggest ?

2023-10-12 16:28 UTC, TSRBerry commented
Sure, although I'd prefer not writing to the application directory at all even if it's writable.
If you prefer the check I'll implement it in a bit.

2024-01-27 02:23 UTC, TSRBerry commented
The current state of this PR doesn't really hit the target anymore, but I guess these changes still offer slight improvements.

2024-01-27 02:32 UTC, AcK77 approved these changes

2024-01-27 02:32 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/Program.cs
> +                        ;
```suggestion

```

2024-01-29 18:56 UTC, marysaka approved these changes

2024-01-29 18:58 UTC, merged