Add "Create Shortcut" To app context menu
Ryujinx/Ryujinx pull request #4734
Opened 2023-04-27 12:06 UTC by NitroTears

This adds a 'Create Shortcut' button to an app/games right-click context menu. The shortcut is created on the desktop and launches the game directly without needing to use the GUI (in fullscreen or not to be confirmed, windows launches fullscreen while linux does not). closes #3250

![win2](https://user-images.githubusercontent.com/73270647/234856640-0d5191fb-0214-4bb3-9a36-d2f210ad4a08.png)
![linux](https://user-images.githubusercontent.com/73270647/234856202-65e88770-dff9-4df2-95e7-d2d949b7cc1c.png)

[Here is a gif of it in action.](https://cdn.discordapp.com/attachments/410432399500115968/1094833530757972168/bingo-og.gif)

As mentioned on discord `#if OS_Windows` is used instead of `OperatingSystem.IsWindows()` due to the annoying COM reference that is neccessary for this to work on Windows. See the project file: 
https://github.com/NitroTears/Ryujinx/blob/b89637a4b0dc2038ef9926924b5e9679f357d113/Ryujinx.Common/Ryujinx.Common.csproj#L12-L22

This currently does not work on MacOS as there doesn't seem to be a way to do that without mucking around in AppleScript, let alone in .NET (Which to me is a little bit out of scope).

I'd like some feedback with this, regarding the MacOS issue I am considering just hiding the button for that platform if it comes to it.

2023-04-27 13:21 UTC, TSRBerry commented on Ryujinx.Common/Ryujinx.Common.csproj
> +  </ItemGroup>
We can't use `COMReference`, could you try this without relying on the WSH COMReference?

Here are a few links that might help with that:
- [Microsoft Answers: How to create a desktop shortcut](https://answers.microsoft.com/en-us/windows/forum/all/how-to-create-a-desktop-shortcut-in-c-visual/9eb48ee4-d672-4025-8cf0-bddbe19c05ac)
- [StackOverflow: Creating application shortcuts](https://stackoverflow.com/a/234543)
- [vbaccelerator: Creating and Modifying Shortcuts](http://www.vbaccelerator.com/home/NET/Code/Libraries/Shell_Projects/Creating_and_Modifying_Shortcuts/article.html)

If this doesn't work at all, I'd honestly recommend using a helper class and invoking PowerShell to create the shortcut.

2023-05-07 01:01 UTC, NitroTears commented
Rebase was slightly painful but done, I have yet to act on what Berry had said though. Will get on that soon.

2023-05-07 04:12 UTC, NitroTears commented
using System.Runtime.InteropServices and the ComImport tag instead looks to have fixed the build issues. Builds on linux OK for me (and in pipelines which is good) and works good on windows as well. I'd say this isn't a draft anymore!

2023-05-08 12:43 UTC, TSRBerry requested changes
Looks very nice overall!
I left some questions in the comments and a few things for Linux that I think should be changed.

About the P/Invoke stuff I'm not quite sure yet, but will look into it more for the next review.

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                                    controlFs.OpenFile(ref icon.Ref, $"/icon_{desiredTitleLanguage}.dat".ToU8Span(), OpenMode.Read).ThrowIfFailure();
Why was the `_desiredTitleLanguage` added as a parameter?

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            shortcut.SetPath(basePath + ".exe");
`AppDomain.CurrentDomain.FriendlyName` should already include the extension, does it not?

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            shortcut.SetArguments($"""{basePath} "{appFilePath}" --fullscreen""");
```suggestion
            shortcut.SetArguments($"""{basePath} --fullscreen "{appFilePath}"""");
```
Aside from the order of the arguments, could you use a list here instead?

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    """;
Could you move this to a new file in `distribution/linux/` and use that instead?

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            outputFile.Write(desktopFile, cleanedAppName, iconPath + ".png", basePath, "\"appFilePath\"");
Make sure we are opening Ryujinx on Linux using `Ryujinx.sh`.

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            image.SaveAsPng(iconPath + ".png");
Icons are usually saved to `$HOME/.local/share/icons/`, could you create a Ryujinx directory and save the files there?

The icon reference in desktop files can then also be reduced to just the filename (without the extension).

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            fs.WriteByte(0);
Use `fs.Write()` to write an array of bytes at once, instead of having one statement for every single byte.

2023-05-08 12:43 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +        void GetPath([Out, MarshalAs(UnmanagedType.LPWStr)] StringBuilder pszFile, int cchMaxPath, out IntPtr pfd, int fFlags);
It's probably fine to use a StringBuilder for this, but it is generally [discouraged](https://learn.microsoft.com/en-us/dotnet/framework/interop/default-marshalling-for-strings).

I'm not quite sure if using the `Out` attribute is okay here, since it's recommended to avoid using it for P/Invoke.

2023-05-08 22:22 UTC, NitroTears commented on src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                                    controlFs.OpenFile(ref icon.Ref, $"/icon_{desiredTitleLanguage}.dat".ToU8Span(), OpenMode.Read).ThrowIfFailure();
The icon differs depending on the language, I added it as a parameter so that I can use `GetApplicationIcon` with the current language setting as a parameter in another file, I used it here:
https://github.com/NitroTears/Ryujinx/blob/6b316fc679a9a830f0d08a86f62a7cbd77cbdce0/src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs#L612

2023-05-13 05:09 UTC, NitroTears commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            shortcut.SetPath(basePath + ".exe");
No it doesn't, for example it has contained "Ryujinx.Ava" and "Ryujinx"

2023-05-13 06:11 UTC, NitroTears commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            image.SaveAsPng(iconPath + ".png");
I assume using the filename without an extension only applies if the icon is found in the `$HOME/.local/share/icons/` folder. But would this still apply if icons are in the new `.../icons/ryujinx` folder?

2023-05-13 06:19 UTC, NitroTears commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    """;
So I would move the file content into eg. `distribution/linux/shortcut-template.desktop`, and then read the filetext instead of the above hardcoded string? Is there a property that allows me to quickly access the `distribution/linux/` folder? I couldn't see one on a brief search.

2023-05-13 06:33 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            shortcut.SetPath(basePath + ".exe");
I see! That's a little odd since I thought the docs said it would be included, but either way that's fine.

2023-05-13 08:47 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    """;
You need to modify the project file and add a new copy line from `distribution/linux/shortcut-template.desktop` to the publish root (the same as the other files).

2023-05-13 08:48 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            image.SaveAsPng(iconPath + ".png");
This should be the case, but I'll test it to make sure as soon as you added the changes.

2023-05-30 02:52 UTC, patrick-hovsepian commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                "--fullscreen",
should this be passed in from an argument? Can it be resolved from the configuration instance? if neither, should it go in the tooltip so users know on creation?

2023-05-30 02:54 UTC, patrick-hovsepian commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    GenericName=Nintendo Switch Emulator
just say Ryujinx?

2023-06-02 07:48 UTC, NitroTears commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    GenericName=Nintendo Switch Emulator
Is there any short descriptor that already exists that you'd want me to use? Such as some from the website:
`A simple, experimental Nintendo Switch emulator.`
`Ryujinx is an open-source Nintendo Switch emulator created by gdkchan and written in C#.`

2023-06-02 07:55 UTC, NitroTears commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                "--fullscreen",
I can add it to the tooltip for now

2023-06-02 07:58 UTC, marysaka requested changes
COM interface is a no no to me

2023-06-02 07:58 UTC, marysaka commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +    #endregion
I'm highly against usage of COM interface on Ryujinx.

This will break while shrinking release with IRLink.

2023-06-02 08:24 UTC, NitroTears commented
I am going to work on the linux side of side of things for now, and will come back to replacing the COM reference later. Jeez windows shortcuts *suck*.

2023-06-02 09:37 UTC, NitroTears commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            image.SaveAsPng(iconPath + ".png");
I found trouble with using $HOME directly in the code, so I'm going to use `Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` instead, which achieves what I want to.

2023-06-02 12:38 UTC, NitroTears commented
Okay got the linux changes all finished, works okay on my VM. @TSRBerry If you [still wanted to have a look](https://github.com/Ryujinx/Ryujinx/pull/4734#discussion_r1192950894) on linux, it is good to go now.

2023-06-02 13:19 UTC, patrick-hovsepian commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    GenericName=Nintendo Switch Emulator
ah didn't realize this was already defined here https://github.com/Ryujinx/Ryujinx/blob/master/distribution/linux/Ryujinx.desktop would it make more sense to read that in and use it as a template at runtime?

2023-06-02 13:23 UTC, NitroTears commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    GenericName=Nintendo Switch Emulator
I've now added https://github.com/NitroTears/Ryujinx/blob/create-shortcut/distribution/linux/shortcut-template.desktop as a template file to pull from and format when writing a new shortcut

2023-06-10 01:05 UTC, NitroTears commented
This has now moved from the InteropServices to [securifybv.ShellLink](https://github.com/securifybv/ShellLink). Works good on windows and linux now, so it's good for further review!

2023-06-13 19:03 UTC, TSRBerry commented
![image](https://github.com/Ryujinx/Ryujinx/assets/20988865/f0667e6b-e7fd-4cd8-a4c0-eceb62c90090)
Make sure to click this button to request a new review after you made the changes, so we get a notification and have this PR on our list for reviews again.

2023-06-13 19:28 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +                    GenericName=Nintendo Switch Emulator
> Is there any short descriptor that already exists that you'd want me to use?

You could write something like "Plays Nintendo Switch applications" I guess.

2023-06-13 19:33 UTC, TSRBerry commented
> This has now moved from the InteropServices to [securifybv.ShellLink](https://github.com/securifybv/ShellLink).

Make sure to include the license and add a new entry to the README.md if you want to use that.

2023-06-13 21:12 UTC, NitroTears commented
> Make sure to include the license and add a new entry to the README.md if you want to use that.

Ah yep, done that now.

2023-06-22 17:35 UTC, AcK77 requested changes

2023-08-05 13:02 UTC, TSRBerry commented
Hi!
I just rebased your PR, since I feel bad that it has been open for 4 months now. I'll try to review it soon.

2023-08-11 07:24 UTC, NitroTears commented
Hey, no worries, and no rush if you need me to update something let me know

2023-08-11 09:54 UTC, TSRBerry commented
Actually, could you make sure the checks workflow passes? That would help a lot!

2023-08-16 12:35 UTC, NitroTears commented
I have closed a PR by @JoseEstradaC that takes care of the Mac functionality! Big thanks there! I've just run the dotnet format cleanup and had another look over the code. This should hopefully clear it for review @TSRBerry.

2023-09-18 20:03 UTC, TSRBerry approved these changes
Lgtm, thank you!

Sorry for taking such a long time. I added two commits to address a few styling things and to embed the shortcut templates as files into `Ryujinx.Ui.Common`, I hope that's okay for you.

2023-10-20 15:46 UTC, marysaka approved these changes
Seems mostly fine but we need to disable this for flatpak build for now.

2023-10-20 18:49 UTC, NitroTears commented
> Seems mostly fine but we need to disable this for flatpak build for now.

Does flatpak/flathub not allow features like this?

2023-10-20 18:50 UTC, TSRBerry commented
It does, but we need to ask for more permissions first, so it's easier to disable it for now.

2023-10-20 18:51 UTC, merged

2023-10-25 14:03 UTC, NNois commented
Doesn't work on Windows
the generated shortcut is: 
"shortcut" `C:\Ryujinx\emu\Ryujinx.exe C:\Ryujinx\emu\Ryujinx.exe --root-data-dir "..\Data" "C:\Ryujinx\data\games\game.xci"`
"start in" `empty`
but works for me like this:
"shortcut" `C:\Ryujinx\emu\Ryujinx.exe -r "..\Data" "C:\Ryujinx\data\games\game.xci"`
"start in" `C:\Ryujinx`

2023-10-26 18:27 UTC, italoghost commented
Does it work with Linux? I am using the binary found on [release-channel-master](https://github.com/Ryujinx/release-channel-master/releases) and nothing happens. I couldn't even see any logs while launching Ryujinx from the terminal.