UI: Move ApplicationContextMenu in a separated class
Ryujinx/Ryujinx pull request #4755
Opened 2023-05-02 01:09 UTC by AcK77

This PR remove duplicated code related to the context menu on the Application list/grid by creating a control for the menu (which include related handler too).

I've renamed `GameList`/`GameGrid` by `ApplicationList`/`ApplicationGrid` for consistency and I removed all uneeded fields from the project file too.

While I cleaned up things, I've found an issue about purging Ptc/Shader cache, both methods list files even if the user anwser `No`, shader cache is purged even if the user answer `No`. It's fixed.

2023-05-02 19:40 UTC, TSRBerry reviewed
Lgtm! Just added a comment about getting the `ViewModel` within `ApplicationContextMenu`.

2023-05-02 19:40 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +        private static MainWindowViewModel _viewModel => ContentDialogHelper.GetMainWindow().ViewModel;
Could you remove this? You can access the `ViewModel` from the events directly.

Like this for example:

```cs
var viewModel = (sender as MenuItem)?.DataContext as MainWindowViewModel;
```

2023-05-02 19:40 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
> +        public static MainWindow GetMainWindow()
You could leave this as `private` and use `Window` as the return type. If you implement the suggestion above.

2023-05-04 13:46 UTC, IsaacMarovitz requested changes

2023-05-04 13:46 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Controls/ApplicationGridView.axaml
> +                            Classes.small="{Binding $parent[UserControl].DataContext.IsGridSmall}"
It would be great to get some of these properties turned into CompiledBindings, but would probably take some refactoring

2023-05-04 13:46 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Controls/ApplicationListView.axaml
>      xmlns:locale="clr-namespace:Ryujinx.Ava.Common.Locale"
Reference to `locale` unused

2023-05-04 14:20 UTC, TSRBerry approved these changes
Lgtm!

2023-05-04 14:20 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                                await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance.UpdateAndGetDynamicValue(LocaleKeys.DialogPPTCDeletionErrorMessage, file.Name, ex));
I'd always log the exception as well, so when they upload the logs we can see that this happened.

(Of course this applies for all of the exceptions in this file.)

2023-05-04 14:29 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                                await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance.UpdateAndGetDynamicValue(LocaleKeys.DialogPPTCDeletionErrorMessage, file.Name, ex));
Oh I forgot about that! :D

2023-05-04 14:38 UTC, IsaacMarovitz approved these changes
Lgtm

2023-05-04 14:41 UTC, merged