Ryujinx.Ava: _maybe_ fix random hangs on exit
Ryujinx/Ryujinx pull request #4827
Opened 2023-05-06 03:25 UTC by jhorv

I've experienced a lot of instances recently where Ryujinx.Ava would hang on exit, sometimes for so long that I'd open up Task Manager and kill it. It was always with Release builds and attaching the debugger didn't show much. It happened so often, I didn't imagine I should have tried harder because today, try as I might, I've had a real hard time getting it to happen so that I could investigate.

I finally got it to happen though, and with a Debug build too. I found one thread stuck waiting, started by `NotificationHelper.SetNotificationManager()` with `Task.Run()`. The thread itself does a simple foreach over a `BlockingCollection<Notification>` but it doesn't have an exit condition. This PR adds one via a `CancellationTokenSource`.

This uses the `WindowNotificationManager.DetachedFromLogicalTree` event to detect when it's time to shut down. I don't have much Avalonia experience, maybe someone who does can suggest a better way to detect when it's time to shut down.

2023-05-07 17:32 UTC, gdkchan commented on src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs
> +                if (_terminationEvent.WaitOne(terminationWaitTimeout) == false)
I'm not sure why this event is necessary. If it's to ensure this method will not return while there is some command still being processed, just taking the `_lock` lock already serves that purpose, since the `SendCommands` method takes this lock.

2023-05-07 19:23 UTC, jhorv commented on src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs
> +                if (_terminationEvent.WaitOne(terminationWaitTimeout) == false)
I'm going to study how it could go unset, then I'll make another change to remove the event. Meanwhile, I'll make this PR a draft until the set of changes stabilizes.

2023-05-09 01:48 UTC, jhorv commented on src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs
> +                if (_terminationEvent.WaitOne(terminationWaitTimeout) == false)
Removed `_terminationEvent` in commit #[8c44f7d](https://github.com/Ryujinx/Ryujinx/pull/4827/commits/8c44f7dd8f4487d3aa7c4c6c119c6eac2eb1026a)

2023-05-10 00:46 UTC, jhorv commented
Moving this out of Draft. This PR is an attempt at fixing 2 apparent causes of "hang on exit" when closing Ryujinx.Ava. Attaching the debugger when a hang occurred, I found that in many instances these 2 events were being waited on and seemingly nothing else:

- `NotificationHelper.SetNotificationManager()` was using a `ManualResetEvent _templateAppliedEvent` being waited on indefinitely. This was the majority of cases that I personally experienced.
- `AudioRenderSystem` had a `ManualResetEvent _terminationEvent` that could be waited on indefinitely in the `Stop()` method. I experienced this personally but far less frequently.

This PR:
- reworks `NotificationManger` to use the existing `AsyncWorkQueue<T>` to manage the threading/cancellation details.
- removes the `AudioRenderSystem` `_terminationEvent`, it having been determined to be redundant anyway.

Anecdotal evidence suggests these changes do reduce the frequency of "hang on exit" events. When a "hang on exit" has occurred with this PR, the debugger shows it likely to be caused by known issues when disposing of many created resources, many client threads, etc., which this PR will not try to address.

2023-05-10 01:03 UTC, AcK77 requested changes

2023-05-10 01:03 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Helpers/NotificationHelper.cs
> +                , LazyThreadSafetyMode.ExecutionAndPublication);
```suggestion
            var maybeAsyncWorkQueue = new Lazy<AsyncWorkQueue<Notification>>(
                () => new AsyncWorkQueue<Notification>(notification =>
                    {
                        Dispatcher.UIThread.Post(() =>
                        {
                            _notificationManager.Show(notification);
                        });
                    },
                    "UI.NotificationThread",
                    _notifications),
                LazyThreadSafetyMode.ExecutionAndPublication);
```

2023-05-11 16:34 UTC, AcK77 commented on src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs
> +
```suggestion
```

2023-05-11 16:35 UTC, AcK77 approved these changes
LGTM (with my last comment fixed)!

2023-05-19 16:35 UTC, riperiperi approved these changes
Looks fine, though it is weird that the PR has audren changes and does not mention why. I am not able to reproduce a freeze with this PR, though I don't use avalonia casually so not sure if I could get it to happen on master either.

2023-05-19 17:01 UTC, jhorv commented
> Looks fine, though it is weird that the PR has audren changes and does not mention why. I am not able to reproduce a freeze with this PR, though I don't use avalonia casually so not sure if I could get it to happen on master either.

Sorry for that, I added text to the top comment describing how this fixes 2 hang causes, the 2nd one being in `AudioRenderSystem`.

2023-05-26 21:57 UTC, merged