UI: Implement automatic input mapping
Ryujinx/Ryujinx pull request #4865
Opened 2023-05-08 20:37 UTC by nreinartz

This PR intends to implement request #1568, implemented for both GTK and Avalonia.

**GTK:** Several lists with the static button order, depending on the selections.
**Avalonia:** Since the buttons are nicely ordered inside the XAML tree we can simply iterate through all visible toggle buttons

Some explanations on changes:
- One necessary change is that the KeyboardKeyAssigner now only recognizes a key as pressed when KeyDown + KeyUp was fired. Otherwise, due to the nature of the ButtonAssigner (polling of key presses), newly selected buttons would've been immediately set with the value of the current pressed button.
- We do not listen for Checked & Unchecked events due to the trigger source of those being opaque since setting .IsChecked is triggering them as well. Furthermore it simplifies the mapping process.

This PR also contains several fixes & qol updates for both input & hotkey views:
- Properly stop input assignment when view is changed. Previously the button would still be highlighted but would not accept inputs anymore.
- Clicks are now properly recognized inside the input view and the input mapping is stopped
- If the user wants to start a new key mapping while another one is still active, the old one will be canceled and the new one will be started immediately. Previously only the current mapping would be canceled.

2023-05-09 07:20 UTC, NitroTears commented
You legend! Thank you for this!

2023-05-10 00:54 UTC, AcK77 requested changes
Good job on this fix. I've tested UI side and it works quite well.

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/Settings/SettingsHotkeysView.axaml.cs
> +                //It is either a new button, so cancel the old one or it is the same button, so cancel the assignment
```suggestion
                // NOTE: In any case, if a button is clicked we want to cancel the current assignment.
                //       It is either a new button, so cancel the old one or it is the same button, so cancel the assignment.
```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +    <!--Background="Transparent": https://stackoverflow.com/a/70179675 -->
Could be better to add a comment to explain why you set Background as Transparent instead of a link to a website.

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +                //  Same button -> Cancel current assignment
```suggestion
                // NOTE: In any case, if a button is clicked we want to cancel the current assignment.
                //       New button -> Cancel old button assignment
                //       Same button -> Cancel current assignment
```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +                //  Same button -> Cancel current assignment
```suggestion
                // NOTE: In any case, if a button is clicked we want to cancel the current assignment.
                //       New button -> Cancel old button assignment
                //       Same button -> Cancel current assignment
```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +                IKeyboard keyboard = (IKeyboard)ViewModel.AvaloniaKeyboardDriver.GetGamepad("0"); // Open Avalonia keyboard for cancel operations.
```suggestion
                // NOTE: Open Avalonia keyboard for cancel operations.
                IKeyboard keyboard = (IKeyboard)ViewModel.AvaloniaKeyboardDriver.GetGamepad("0");
```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +            //In case the current assignment is canceled by another button click, we don't want to set the new assigner to null
```suggestion
            // NOTE: In case the current assignment is canceled by another button click, we don't want to set the new assigner to null.
```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +                ViewModel.IsModified = true;
```suggestion
                ViewModel.IsModified = true;

```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +            bool shouldUnbind = e.GetCurrentPoint(this).Properties.IsMiddleButtonPressed;
```suggestion
            bool shouldUnbind = e.GetCurrentPoint(this).Properties.IsMiddleButtonPressed;

```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +            bool shouldUnbind = e.GetCurrentPoint(this).Properties.IsMiddleButtonPressed;
```suggestion
            bool shouldUnbind = e.GetCurrentPoint(this).Properties.IsMiddleButtonPressed;

```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Input/Assigner/KeyboardKeyAssigner.cs
```suggestion
```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +            IEnumerable<ToggleButton> buttonOrder = GetCurrentButtonOrder();
```suggestion
            IEnumerable<ToggleButton> buttonOrder = GetCurrentButtonOrder();

```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                throw new Exception("Controller not supported");
```suggestion
                throw new Exception("Input device not supported");
```

2023-05-10 00:54 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +            _ => throw new Exception("Controller not supported")
```suggestion
            _ => throw new Exception("Input device not supported")
```

2023-05-10 09:30 UTC, GamerzHell9137 commented
Is it possible to make it a bit faster?

2023-05-11 07:25 UTC, nreinartz commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +            bool shouldUnbind = e.GetCurrentPoint(this).Properties.IsMiddleButtonPressed;
Duplicate

2023-05-11 07:26 UTC, nreinartz commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml.cs
> +                //  Same button -> Cancel current assignment
Duplicate

2023-05-11 16:59 UTC, AcK77 approved these changes

2023-05-12 17:50 UTC, IsaacMarovitz approved these changes

2023-06-01 00:02 UTC, patrick-hovsepian commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                throw new Exception("Input device not supported");
Can this just return an empty list?

2023-06-01 00:02 UTC, patrick-hovsepian commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                .Skip(1)
Why do you need this?

2023-06-04 13:35 UTC, nreinartz commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                throw new Exception("Input device not supported");
It could, but returning an empty list would hide an error case.

2023-06-04 13:36 UTC, nreinartz commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                .Skip(1)
What exactly do you mean? I want to get the next button in the current order, so I skip all buttons until I get to the current one and then I select the next one (skip the current button, take the next one).

2023-06-05 03:30 UTC, patrick-hovsepian commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                .Skip(1)
Ah, I see now thanks.

2023-06-12 14:35 UTC, TSRBerry approved these changes
Very well done, thank you!

Sorry for the late review, I'm still catching up on review requests :sweat_smile:.

2023-06-19 08:27 UTC, MutantAura commented
Needs a rebase for merge.

2023-10-20 16:27 UTC, marysaka commented
This PR is currently staled and the author seems to not be around anymore.

I will handle the rebase and merge at some point.

2023-10-20 17:41 UTC, IsaacMarovitz commented
This may cause problems with #4998

2024-02-28 18:02 UTC, closed without merging