UI: Adjust input mapping view
Ryujinx/Ryujinx pull request #4866
Opened 2023-05-08 21:07 UTC by nreinartz

In the process of doing #4865 I took the liberty of adjusting the mapping view a little bit. I think most of the issues stem from the boxes not being aligned and the noise created by the amount of borders and small gaps between boxes.

<img src="https://user-images.githubusercontent.com/29705383/236933572-a0b51c00-f15e-4873-987f-2f9a22e2bc8c.png" width="500" />

Changes:
- Top most bar is now a 2x2 grid to create a better overview
- Most boxes are now properly aligned to their neighbours
- The "double borders" have been removed bei either joining borders or putting a margin between boxes
- Right controller buttons are now a list, just like DPad
- Separator between stick mappings and checkboxes
- Deadzone & Range headers are centered
- Move - and + to the bottom of their 

Fixes:
- Slider text blocks now have a fixed width to prevent the slider from changing size when value changes from something like 0.11 to 0.23 (different text widths causing the slider to get bigger/smaller).

Preview:
<img src="https://user-images.githubusercontent.com/29705383/236935030-6076c497-c63e-422f-b9b3-08e1e6bc6972.png" width="400" />
<img src="https://user-images.githubusercontent.com/29705383/236935113-30a74d78-cec6-473c-9a69-398a6d163be6.png" width="400" />

2023-05-08 21:58 UTC, nreinartz commented
> Just FYI I have a pr in works for this already #4251

That's unfortunare, I must have overlooked that one. I'm fine either way, close it or use it as a middle way until yours is finished.

2023-05-10 01:19 UTC, AcK77 requested changes
Just some style comments. I really love it, it's looks way better than before. Thanks for working on it.

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +
```suggestion
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +
```suggestion
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +
```suggestion
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +
```suggestion
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +            <!-- Input device -->
```suggestion

            <!-- Input device -->
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +            <!-- Input device -->
```suggestion

            <!-- Input device -->
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +
```suggestion
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +
```suggestion
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +
```suggestion
```

2023-05-10 01:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +            <!-- Controler type -->
```suggestion

            <!-- Controler type -->
```

2023-05-11 07:34 UTC, nreinartz commented on src/Ryujinx.Ava/UI/Windows/ControllerSettingsWindow.axaml
> +            <!-- Input device -->
I have the impression that github constantly duplicates these suggestions when I try to commit them. Weird.

2023-05-11 16:57 UTC, AcK77 approved these changes

2023-05-11 19:29 UTC, marysaka approved these changes

2023-05-11 21:10 UTC, merged