Fix the restart after an update.
Ryujinx/Ryujinx pull request #4869
Opened 2023-05-09 15:36 UTC by LoneBoco

After running the updater for Ryujinx and clicking Yes to restart, I am greeted with an error message:

> The application was unable to start correctly (0xc0000142).
> Click OK to close the application.

I then have to manually start Ryujinx to finish the update.  This PR changes the way that Ryujinx is launched after an update to fix this error.

2023-05-09 22:15 UTC, LoneBoco commented
> Does that only happen with Gtk?

Do you mean if this only happens with the default UI and not with the new Ava UI?  If so, then no, it happens with both.

2023-05-10 01:44 UTC, AcK77 requested changes

2023-05-10 01:44 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
>                      Process.Start(executablePath, arguments);
This doesn't have to be removed ?

2023-05-10 01:44 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        Process.Start(executablePath, arguments);
`executablePath` don't seems to be used elsewhere now. Maybe you could remove the above condition and related code too and then do:

```suggestion
                        Process.Start("/bin/bash", arguments);
```

2023-05-10 03:36 UTC, LoneBoco commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
>                      Process.Start(executablePath, arguments);
You are right.  I accidentally left a line of code in and didn't notice it.

2023-05-10 03:39 UTC, LoneBoco commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        Process.Start(executablePath, arguments);
I cleaned up the code a bit, removing some variables that aren't really being used anymore.

2023-05-11 17:44 UTC, AcK77 approved these changes
LGTM! I think this has to be tested in all OSs!

2023-05-11 23:10 UTC, LoneBoco commented
> LGTM! I think this has to be tested in all OSs!

@AcK77 I tested on Linux with KDE Neon (Ubuntu 22.04).  The auto-update worked fine for the Gtk version but not for the Ava version.  The issue is that Environment.ProcessPath returns the name of the renamed executable, so we then run the fail condition and just choose "Ryujinx" as the executable name.  With Ava, the actual executable name is Ryujinx.Ava.  This is a problem that existed in the original code.

Should I change the code to look for Ryujinx.Ava instead for the Ava build?  I assume at some point Ava will become the norm.  So the code could be left as-is and work in the future, or I can change it to look for Ryujinx.Ava and the code will need to be changed in the future if the executable name ever changes.

One thing I am going to do is strip the .ryuold off the executable name if it finds it.  That will be the immediate fix for the problem.  My above question is mainly about how to handle the fallback case where the exe name couldn't be found.

2023-05-11 23:13 UTC, LoneBoco commented
I am unable to test on MacOS.  I wonder if MacOS will have the same issue with the Avalonia code (it looks for Ryujinx.app).

2023-05-11 23:51 UTC, TSRBerry requested changes
MacOS is unaffected by these changes, so no need to worry about that.

I added 2 comments about the way the arguments are passed to `processStart`, but other than that, lgtm!

2023-05-11 23:51 UTC, TSRBerry commented on src/Ryujinx/Modules/Updater/UpdateDialog.cs
> +                Process.Start(processStart);
```suggestion
                ProcessStartInfo processStart = new(ryuName)
                {
                    UseShellExecute = true,
                    WorkingDirectory = ReleaseInformation.GetBaseApplicationDirectory()
                };

                foreach (string argument in CommandLineState.Arguments)
                {
                    processStart.ArgumentList.Add(argument);
                }

                Process.Start(processStart);
```

I think doing something like that would be safer.

2023-05-11 23:51 UTC, TSRBerry commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        Process.Start(processStart);
```suggestion
                        ProcessStartInfo processStart = new(ryuName)
                {
                    UseShellExecute = true,
                    WorkingDirectory = executableDirectory
                };

                foreach (string argument in arguments)
                {
                    processStart.ArgumentList.Add(argument);
                }

                Process.Start(processStart);
```
So we don't run into escaping issues.

2023-05-12 00:09 UTC, LoneBoco commented on src/Ryujinx/Modules/Updater/UpdateDialog.cs
> +                Process.Start(processStart);
Done.

2023-05-12 00:09 UTC, LoneBoco commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        Process.Start(processStart);
Done.

2023-05-12 00:11 UTC, TSRBerry approved these changes
Thank you, lgtm!

2023-05-12 00:14 UTC, merged