Overhaul of string formatting/parsing logic for TimeSpans, DateTimes, and file sizes
Ryujinx/Ryujinx pull request #4956
Opened 2023-05-15 05:59 UTC by SamusAranX

This one kinda grew out of #4952 after I found other formatting and parsing issues, including a possible cause for the crash in #4920. I've closed #4952 in favor of this PR.
This is a big PR that touches a bunch of files but I believe it makes every touched part either more robust or simply better.

I'm gonna explain some of the changes in longer form than what commit messages allow:

# Value parsing and formatting

I noticed that the handling of `DateTime`s, `TimeSpan`s, and file sizes was kind of all over the place, so I added a new helper class called `ValueFormatUtils` (naming's not my strong suit) that can handle formatting and parsing.
This class is intended as a centralized place where those operations take place, as discrepancies in how formatting and parsing are done can cause and have caused problems in the past.
(see also: #4861, which solved one of those problems)

## DateTime

Building on #4861, I moved `DateTime` formatting and parsing to the new `ValueFormatUtils` class.
I removed `NullableDateTimeConverter` again because it wasn't actually needed.

## TimeSpan

Similar to what I did in #4861, I replaced the `double`-based `TimePlayed` property with one backed by a `TimeSpan` and added a migration path that upgrades the old "time_played" JSON field to a "timespan_played" field that contains a serialized `TimeSpan`.

I replaced the old `TimePlayed` format ("1d 09h 20m") with another one that's mostly stock `TimeSpan` formatting except for the number of days ("1d, 09:20:00"). The old format was visually very noisy and excluded seconds for no reason.
Additionally, the `SortHelper` code meant to re-parse the string back into a sortable value looked fragile, so I replaced it.

Time Played values of 0 seconds no longer display as "Never", but as 00:00:00.
"Never" makes no sense as an answer to "How long did I play that game for".

## File sizes

`ApplicationLibrary.LoadApplications()` contained this wild line of code:

```cs
double fileSize = new FileInfo(applicationPath).Length * 0.000000000931;
```

I couldn't find out where it came from, let alone what it was supposed to do, but in the name of making the code less fragile, I ripped it out and made `fileSize` a `long`.

The formatting of file sizes in particular was done in various ways in several places in the codebase (SaveModel.cs, SystemInfo.cs, ApplicationLibrary.cs), so I changed all those to use `ValueFormatUtils.FormatFileSize()` instead.
Conversely, `ValueFormatUtils.ParseFileSize()` can turn strings generated by `ValueFormatUtils.FormatFileSize()` back into file size numbers. That function is only used for sorting purposes as of this PR. More on sorting below.

I took some liberties regarding files size formatting here:

`ValueFormatUtils` can parse both base 2 and base 10 file size units (read: KiB/MiB/GiB or KB/MB/GB respectively) but it will format *exclusively* by using base 2 calculations and appending base 10 units.
This matches what Windows and other systems do, as per https://devblogs.microsoft.com/oldnewthing/20090611-00/?p=17933 and this screenshot:
![A screenshot of the Avalonia Ryujinx main window and an explorer.exe properties window side by side, showing that Smash Bros. Ultimate's displayed file sizes match](https://github.com/Ryujinx/Ryujinx/assets/676069/52d197ee-b20f-4e18-b17e-1d0879961251)

Personally, I think it's a little confusing that Ryujinx uses base 2 units for display when, to my knowledge, no other program that's not aimed at nerds (affectionate) does. This change helps legibility. No one knows or cares what a GiB is. 

I also made `SystemInfo` print RAM values in GB instead of MiB.
![A screenshot of Ryujinx's console output showing RAM values in gigabytes instead of mebibytes](https://github.com/Ryujinx/Ryujinx/assets/676069/c558a1a0-2e1c-4e21-86fe-91e7ac62379b)

# Sorting

Prior to this PR, the sorting for `TimePlayed`, `LastPlayed`, and `FileSize` was backwards.
To verify that, open a Ryujinx window and an Explorer window with more than a few files side by side and sort both by size so that the largest files come first.
In this situation, the triangle in the column header is supposed to point downwards.
This PR fixes the order of sort operands in all the places that sorting happens.

Also, as mentioned earlier, I believe the old `SortHelper` code might've been causing the crash mentioned in #4920. I was able to reproduce it and fixed it by making `SortHelper` a thin-ish wrapper around `ValueFormatUtils`.

If there are any changes I didn't mention here that need further explanation, please let me know.

2023-05-21 23:51 UTC, AcK77 requested changes

2023-05-21 23:51 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            "KiB", "MiB", "GiB", "TiB", "PiB", "EiB",
```suggestion
            "KiB", "MiB", "GiB", "TiB", "PiB", "EiB"
```

2023-05-21 23:51 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            Exabytes = 6,
```suggestion
            Exabytes = 6
```

2023-05-21 23:51 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            return $"{timeSpan.Value.Days}d, {onlyTimeString}";
```suggestion

            return $"{timeSpan.Value.Days}d, {onlyTimeString}";
```

2023-05-21 23:51 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            var returnTimeSpan = TimeSpan.Zero;
```suggestion
            TimeSpan returnTimeSpan = TimeSpan.Zero;
```

2023-05-21 23:51 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                return "Never";
You said:
> Time Played values of 0 seconds no longer display as "Never", but as 00:00:00.
> "Never" makes no sense as an answer to "How long did I play that game for".

Then why this is still existing ? `utcDateTime` should always got a value here?

2023-05-21 23:51 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                return Convert.ToInt64(number);
```suggestion

                return Convert.ToInt64(number);
```

2023-05-21 23:51 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +
Extra spaces can be removed

2023-05-22 09:23 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                return "Never";
My comment was about the Time Played column, which uses TimeSpan objects internally.
FormatDateTime is for DateTime objects, which are used by the Last Played column, where a displayed value of "Never" makes sense.

2023-05-22 13:32 UTC, IsaacMarovitz requested changes

2023-05-22 13:32 UTC, IsaacMarovitz commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                return "Never";
Please localise this value in this PR

2023-05-23 10:01 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                return "Never";
`LocaleManager` is in the Ryujinx.Ava namespace, but this class is also used by the old GTK UI. Wouldn't pulling in Avalonia stuff cause problems?

2023-05-23 10:02 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                return "Never";
Fixed the comment mistakes. The comments now correctly state what each method is used for.

2023-05-24 21:25 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                return "Never";
The last commit localizes "Never" in the Avalonia UI.
I found one issue that might be beyond the scope of this PR: Switching languages doesn't reload the game list, which means if you started with English, "Never" will stick around in the UI until you manually hit the reload button.

2023-05-28 17:08 UTC, TSRBerry approved these changes
Thank you so much for this PR! Your description is awesome and the changes look very nice!

I added a few comments where I think we could make a few adjustments, but nothing major.
I won't add any comments about styling issues since my styling PR isn't merged yet and I'll just address these in there as well.

2023-05-28 17:08 UTC, TSRBerry commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            double _base = 1024;
```suggestion
            double base = 1024;
```

Local variables are not prefixed with an underscore.

2023-05-28 17:08 UTC, TSRBerry commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        public static long ParseFileSize(string sizeString)
Should you change the method above to use a `ulong` then you could change the return type here to `ulong` as well.

2023-05-28 17:08 UTC, TSRBerry commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            double _base = 1024;
```suggestion
            double base = 1024;
```

2023-05-28 17:08 UTC, TSRBerry commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                string unit = FILE_SIZE_UNITS[i];
Could you change this to a foreach-loop? Since you already imported `System.Linq` you could use `Reverse()` here to iterate over the array backwards.

2023-05-28 19:19 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            double _base = 1024;
C# doesn't allow you to name a variable `base`, so I put an underscore on it.

2023-05-28 19:34 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                string unit = FILE_SIZE_UNITS[i];
I really rather wouldn't because I need the value of `i` later.

2023-05-28 19:36 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            double _base = 1024;
You could just call it `sizeBase`, `numberBase`, `baseValue` or something like that.

2023-05-28 19:44 UTC, patrick-hovsepian commented on src/Ryujinx.Ui.Common/App/ApplicationMetadata.cs
> +            if (LastPlayed.HasValue)
super nit: test for the negative and immediately return to help readability

2023-05-28 19:44 UTC, patrick-hovsepian commented on src/Ryujinx.Ui.Common/App/ApplicationData.cs
> +        public string FileSizeString => ValueFormatUtils.FormatFileSize(FileSize);
worth caching these with an internal prop?

2023-05-28 19:44 UTC, patrick-hovsepian commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        public static string FormatTimeSpan(TimeSpan? timeSpan)
maybe rename if this only for gameTime played

2023-05-28 19:44 UTC, patrick-hovsepian commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        public static TimeSpan ParseTimeSpan(string timeSpanString)
Would it be better to just define a Formatter and pass that to TimeSpan.Parse?

2023-05-28 19:44 UTC, patrick-hovsepian commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                unitIndex = (int)forceUnit;
just initialize to this so you can remove this else block entirely

2023-05-28 19:44 UTC, patrick-hovsepian commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                if (i > 6)
im not a fan of the magic number and its tied to the order of the FILE_SIZE_UNIT array. maybe consider breaking it up into two separate arrays to better distinguish special cases?

2023-05-28 20:15 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        public static string FormatFileSize(long size, FileSizeUnits forceUnit = FileSizeUnits.Auto)
It's mostly because this function is used from classes that use `long` properties to represent bytes and it'd be a hassle to refactor all of them. There's one instance in `SystemInfo.ToGBString()` where I cast a `ulong` to `long` but that's it.

2023-05-28 20:17 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +using System.Drawing;
Could've sworn I had resharper give this file a once-over. welp

2023-05-28 20:17 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +            double _base = 1024;
Renamed all `_base` variables to `SizeBase`.

2023-05-28 20:19 UTC, SamusAranX commented on src/Ryujinx.Ui.Common/App/ApplicationMetadata.cs
> +            if (LastPlayed.HasValue)
Good point actually.

2023-05-28 20:27 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        public static TimeSpan ParseTimeSpan(string timeSpanString)
Truth be told, I find .NET formatting strings, especially for dates, to be extremely tedious to work with. Personally, I prefer to use the bog standard `.Parse()` overloads and doing everything else myself.

2023-05-28 20:36 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                unitIndex = (int)forceUnit;
Done.

2023-05-28 20:37 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                if (i > 6)
I'm not sure how to do this at this moment. Splitting the array into two separate arrays would make the function you highlighted harder to understand, as I'd have to loop through both arrays in order.
I changed this bit in the last commit to use a properly named variable in place of the magic 6, I hope that makes this part more readable.

2023-05-28 20:40 UTC, TSRBerry commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +                string unit = FILE_SIZE_UNITS[i];
Ah sorry, I didn't see that. Just leave it like that!

2023-05-28 20:40 UTC, SamusAranX commented on src/Ryujinx.Ui.Common/App/ApplicationData.cs
> +        public string FileSizeString => ValueFormatUtils.FormatFileSize(FileSize);
I'd have to keep track of every time the non-string properties these refer to are updated and then update the cached value. It's a good suggestion but since these are called at most once per game list entry, I don't think it's worth the effort atm.

2023-05-28 20:50 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        public static string FormatFileSize(long size, FileSizeUnits forceUnit = FileSizeUnits.Auto)
Oh, I forgot: The main reason is that `FileInfo.Length` is a long. Honestly idk why it's a ulong in some places.

2023-05-28 20:57 UTC, patrick-hovsepian commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        public static TimeSpan ParseTimeSpan(string timeSpanString)
fair enough

2023-05-30 17:21 UTC, SamusAranX commented
I put the methods in `ValueFormatUtils.cs` into formatter and parser `#regions` in the last commit.
IMO this makes the code more readable as the parsers are only ever used by the GTK UI.

2023-05-31 01:05 UTC, SamusAranX commented
The last commit integrates #5056's changes but moves metadata update logic to two methods on `ApplicationMetadata`.
Functionally, `ApplicationMetadata.UpdateTimePlayed()` (from an earlier commit in this PR) is now `UpdatePostGame()`.
`UpdatePreGame()` wraps the changes from #5056.

2023-06-03 23:53 UTC, gdkchan commented on src/Ryujinx/Ui/Helper/SortHelper.cs
> +            if (aSize == bSize)
Can't this just return `aSize.CompareTo(bSize);` directly?

2023-06-03 23:54 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        /// Only used to sort the GTK UI's game list.
I don't think you should be making mentions to the GTK UI Here. If this is something that is only needed by GTK, then it shouldn't be here, it should be in the GTK UI Project.

2023-06-04 00:02 UTC, gdkchan commented on src/Ryujinx.Ui.Common/App/ApplicationMetadata.cs
> +            if(!prevLastPlayed.HasValue)
```suggestion
            if (!prevLastPlayed.HasValue)
```

2023-06-04 02:07 UTC, SamusAranX commented on src/Ryujinx/Ui/Helper/SortHelper.cs
> +            if (aSize == bSize)
You're right, I forgot that method even existed

2023-06-04 02:11 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +    public static class ValueFormatUtils
SystemInfo.cs makes use of ValueFormatUtils and I can't reference the `Ryujinx.Ui.Common` namespace from there. `Ryujinx.Common.Utilities` is usable from more places, so I'd like to keep this file there.

2023-06-04 02:15 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        /// Only used to sort the GTK UI's game list.
I'd like to keep the formatting and parsing functions together in the same file because they're inherently related to each other. Ripping one group of functions out and putting it into another namespace would just result in code duplication and worse maintainability.

2023-06-04 14:41 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +    public static class ValueFormatUtils
I think `SystemInfo` (at least as it exists today) should also be in `Ryujinx.Ui.Common`. It is not really useful for anything other than UI, so it should be in the UI project. `Ryujinx.Common` is for truly common code that can be used by any project. I'd suggest just moving both there.

2023-06-04 14:48 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        /// Only used to sort the GTK UI's game list.
I don't mind keeping them together, but I think it should be moved to `Ryujinx.Ui.Common` (my other suggestion). Also I'm not sure what mentioning that it's only used in GTK here adds if this is supposed to be a generic parsing.

2023-06-04 14:50 UTC, gdkchan commented
> I also made SystemInfo print RAM values in GB instead of MiB.

This will probably mess with the bot. It's worth keeping in mind that the bot will need to be updated after this change (assuming this specific change will go in).

2023-06-04 15:02 UTC, gdkchan commented
> Personally, I think it's a little confusing that Ryujinx uses base 2 units for display when, to my knowledge, no other program that's not aimed at nerds (affectionate) does. This change helps legibility. No one knows or cares what a GiB is.

If we are changing it here, we should probably change it consistently across the UIs too in a follow up PR.

2023-06-04 16:05 UTC, SamusAranX commented
> This will probably mess with the bot.

I didn't consider that. I can try drafting a PR for the bot to help deal with that.

> we should probably change it consistently across the UIs too in a follow up PR

This PR changes display units in all places where file sizes are displayed. I did some surface-level code searches and couldn't find any remaining uses of base 2 units in user-facing contexts. A followup PR might not be needed.

2023-06-04 16:11 UTC, gdkchan commented
> This PR changes display units in all places where file sizes are displayed. I did some surface-level code searches and couldn't find any remaining uses of base 2 units in user-facing contexts. A followup PR might not be needed.

One easy example is some tool tips, for example, this is present in all locales: https://github.com/SamusAranX/Ryujinx/blob/formatting-fixes/src/Ryujinx.Ava/Assets/Locales/en_US.json#L610

There are more (not all of them are user facing, but we should be consistent on code naming too regardless).

2023-06-04 16:44 UTC, SamusAranX commented
Bot PR is up: https://github.com/Ryujinx/ryuko-ng/pull/58

2023-06-04 19:17 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +        /// Only used to sort the GTK UI's game list.
Removed the GTK-specific comments.

2023-06-04 19:17 UTC, SamusAranX commented on src/Ryujinx.Common/Utilities/ValueFormatUtils.cs
> +    public static class ValueFormatUtils
The last commit moves ValueFormatUtils.cs and SystemInfo.cs (along with its subclasses) to `Ryujinx.Ui.Common`.

2023-06-22 22:11 UTC, AcK77 commented on src/Ryujinx.Ui.Common/SystemInfo/SystemInfo.cs
> +namespace Ryujinx.Ui.Common.SystemInfo
I don't think it's needed to move it from `Ryujinx.Common.SystemInfo`  to `Ryujinx.Ui.Common.SystemInfo` since `Ryujinx.Ui.Common` only exist because we currently have 2 UI, one day when we will drop GTK we could not keep it!
(same for the 2 other moved classes)

2023-06-22 22:14 UTC, gdkchan commented on src/Ryujinx.Ui.Common/SystemInfo/SystemInfo.cs
> +namespace Ryujinx.Ui.Common.SystemInfo
If anyone wants to remove `Ryujinx.Ui.Common` after GTK is gone, those classes can just be moved to `Ryujinx.Ava`. The reason why I don't think it should be in `Ryujinx.Common` is because `Ryujinx.Common` is for functionality that is truly useful for any project, not something that is only used by the UI. `SystemInfo` as implemented today is not useful for anything other than UI.

2023-10-30 20:39 UTC, TSRBerry commented
@SamusAranX I resolved the merge conflicts for you, I hope that's okay for you.

@Ryujinx/developers this PR has been waiting for a really long time now and we need it. Could someone of you please review it?

2023-10-30 21:02 UTC, gdkchan commented
If we're changing KiB/MiB/GiB back to KB/MB/GB, we should also replace all UI strings that currently uses MiB/GiB for consistency, and stick with it.

2023-10-30 21:04 UTC, TSRBerry commented
Could be done in a follow-up PR as well. Especially now that we can't be sure anymore that the author wants/intents to work on this any further.

2023-10-30 21:18 UTC, gdkchan commented
Shouldn't be too hard to change it, and it's not very good to leave the emulator in a consistent state. It doesn't need to be done by the author, any maintainer should be able to change the branch.

2023-11-06 18:28 UTC, marysaka approved these changes
lgtm apart from the MiB and GiB changes.

I will merge with that part reverted, if you want to change it back to MB, GB,.. please open an issue/PR to continue that discussion.

2023-11-06 21:47 UTC, merged