Fix crash in SettingsViewModel when Vulkan isn't available
Ryujinx/Ryujinx pull request #4985
Opened 2023-05-16 16:39 UTC by jhorv

Fixes issue #4984 
Doesn't make Ryujinx work on Win11 on ARM, because after this it crashes in ARMeilleure.

2023-05-16 16:45 UTC, IsaacMarovitz commented
Thank you for fixing this very stupid bug lol

2023-05-16 16:55 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                // Do nothing
Maybe you should add a logger message here!

2023-05-16 17:29 UTC, jhorv commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                // Do nothing
Latest commit adds a parameterless overload to VulkanRenderer.GetPhysicalDevices() that catches/logs when Vk.GetApi() throws, and it adjusts the Ava and GTK front-ends to use this overload.

2023-05-16 17:32 UTC, jhorv commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                // Do nothing
Let me know if you think that's overkill. Simpler would be to try/catch around the 4 Vk.GetApi() call sites.

2023-05-16 21:51 UTC, AcK77 requested changes

2023-05-16 21:51 UTC, AcK77 commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +                return VulkanInitialization.GetSuitablePhysicalDevices(api);
```suggestion
                return VulkanInitialization.GetSuitablePhysicalDevices(Vk.GetApi());
```

2023-05-16 21:51 UTC, AcK77 commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +                // If we got an exception here, Vulkan is most likely not supported.
Comment isn't really needed here.

2023-05-16 21:51 UTC, AcK77 commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +                Logger.Warning?.PrintMsg(LogClass.Gpu, $"Error querying Vulkan devices: {ex.Message}");
Idk if we should use `Warning` or `Error` here

2023-05-16 21:51 UTC, AcK77 commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +                return Array.Empty<DeviceInfo>();
```suggestion

                return Array.Empty<DeviceInfo>();
```

2023-05-16 21:56 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                // Do nothing
I prefer how it's done right now, then UIs doesnt have to manage anything ;)

2023-05-16 22:44 UTC, jhorv commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +                // If we got an exception here, Vulkan is most likely not supported.
Removed comment in commit [2b3cdcf](https://github.com/Ryujinx/Ryujinx/pull/4985/commits/2b3cdcf314e39d7c2192d92bb7d29aab5f93f943)

2023-05-16 22:45 UTC, jhorv commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +                Logger.Warning?.PrintMsg(LogClass.Gpu, $"Error querying Vulkan devices: {ex.Message}");
Made it use Error in commit [2b3cdcf](https://github.com/Ryujinx/Ryujinx/pull/4985/commits/2b3cdcf314e39d7c2192d92bb7d29aab5f93f943)

2023-05-16 22:45 UTC, jhorv commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +                return Array.Empty<DeviceInfo>();
Fixed in commit [2b3cdcf](https://github.com/Ryujinx/Ryujinx/pull/4985/commits/2b3cdcf314e39d7c2192d92bb7d29aab5f93f943)

2023-05-16 22:54 UTC, AcK77 approved these changes

2023-05-17 10:12 UTC, marysaka approved these changes

2023-05-17 10:13 UTC, marysaka requested changes

2023-05-17 10:13 UTC, marysaka commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +        public static DeviceInfo[] GetPhysicalDevices()
Actually I would prefer Vk.GetApi to be passed by argument still.

2023-05-17 14:51 UTC, jhorv commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +        public static DeviceInfo[] GetPhysicalDevices()
> Actually I would prefer Vk.GetApi to be passed by argument still. (Required for some stuffs I have been working on)

There is still the overloaded version of `GetPhysicalDevices(Vk api)`. But are you saying you want me to remove the parameterless overload, and try/catch at the UI level?

2023-05-19 15:20 UTC, AcK77 commented on src/Ryujinx.Graphics.Vulkan/VulkanRenderer.cs
> +        public static DeviceInfo[] GetPhysicalDevices()
I don't think the try/catch should be done at the UI side.

2023-05-21 19:37 UTC, marysaka approved these changes

2023-05-21 19:39 UTC, merged