Ava UI: Input Menu Refactor
Ryujinx/Ryujinx pull request #4998
Opened 2023-05-17 14:45 UTC by IsaacMarovitz

**Changes:**
- Refactor Input Menu to use Compiled Bindins
- (welcome to hell)

2023-05-28 21:19 UTC, AcK77 requested changes
Just a quick (code side) review.

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Helpers/KeyValueConverter.cs
> +            throw new NotSupportedException();
It's not supported because it wasn't used before the change ?

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +                ButtonZr      = controllerInput.RightJoycon.ButtonZr;
Remove the alignment here, since other fields aren't aligned.

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +                    ButtonZr = ButtonZr,
```suggestion
                    ButtonZr = ButtonZr
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +                    StickButton = LeftStickButton,
```suggestion
                    StickButton = LeftStickButton
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +                    StickButton = RightStickButton,
```suggestion
                    StickButton = RightStickButton
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +                TriggerThreshold = TriggerThreshold,
```suggestion
                TriggerThreshold = TriggerThreshold
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +
```suggestion
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +
```suggestion
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +
```suggestion
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +
```suggestion
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +
```suggestion
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/KeyboardInputConfig.cs
> +                ButtonZr      = keyboardConfig.RightJoycon.ButtonZr;
Remove alignment

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/KeyboardInputConfig.cs
> +                    ButtonSr = LeftButtonSr,
```suggestion
                    ButtonSr = LeftButtonSr
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/Input/ControllerInputViewModel.cs
> +        }
It's strange to get methods before the constructor

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/Input/ControllerInputViewModel.cs
> +            model.NotifyChangesEvent += UpdateParentModelValues;
The name of the event hander is a bit strange.

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                object pressedButton = assigner.GetPressedButton();
```suggestion
                string pressedButton = assigner.GetPressedButton().ToString();
```

2023-05-28 21:19 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        button.Label = pressedButton.ToString();
```suggestion
                        button.Label = pressedButton;
```
Then the warning doesn't exist anymore.

2023-05-29 00:10 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Helpers/KeyValueConverter.cs
> +            throw new NotSupportedException();
The previous system adjusted the Key value in the config file by reading the string set in the textbox item and converting back (two-way binding). Since I localised these values, converting them back into their original form proved problematic, so this PR changes the values to be updated directly rather than using the two way binding,

2023-06-16 21:02 UTC, IsaacMarovitz commented
@AcK77 Please review

2023-06-21 12:54 UTC, marysaka approved these changes
Only one big thing but otherwise seems fine to me

2023-06-21 12:54 UTC, marysaka commented on src/Ryujinx.Input/Assigner/GamepadButtonAssigner.cs
object usage is ambiguous to me here... I know it's needed to differentiate stick to gamepad button but a new struct that store it would be better imo (and use of nullable in case nothing was pressed).

Something around those lines:
```cs
enum KeyValueType { Key, GamepadInputId, GamepadStickId }

struct KeyValue
{
    public KeyValueType Type;
    public uint RawValue;

    public Key AsKey()
    {
        Debug.Assert(Type == KeyValueType.Key);
        return (Key)RawValue;
    }

    public GamepadInputId AsGamepadInputId()
    {
        Debug.Assert(Type == KeyValueType.GamepadInputId);
        return (GamepadInputId)RawValue;
    }

    public GamepadStickId AsGamepadStickId()
    {
        Debug.Assert(Type == KeyValueType.GamepadStickId);
        return (GamepadStickId)RawValue;
    }

    public string ToString()
    {
        switch (Type)
        {
            case KeyValueType.Key:
                return AsKey().ToString();
            case KeyValueType.GamepadInputId:
                return AsGamepadInputId().ToString();
            case KeyValueType.GamepadStickId:
                return AsGamepadStickId().ToString();
            default:
                return "Unknown";
        }
    }
}
```

2023-06-21 12:54 UTC, marysaka commented on src/Ryujinx.Input/Assigner/KeyboardKeyAssigner.cs
> +            return !ShouldCancel() ? keyPressed : null;
Same comment as before.

Maybe this one could even be simplify to just return a nullable of `Key`.

2023-06-21 12:54 UTC, marysaka commented on src/Ryujinx.Ava/UI/Helpers/KeyValueConverter.cs
> +            throw new NotSupportedException();
Should this really throw tho?

2023-06-21 15:27 UTC, AcK77 submitted a review, later dismissed
After some testing:
- The issue about JoyCon Right can be reproduced here, and have to be fixed before merge. Seems to only break the SL/SR buttons.
- If the `Input Device` is set to `Disabled`, the `Controller Type` control and all `Profile` controls have to be disabled too.
- Doesn't seems to break GTK as far as I have tested.
- Maybe we should introduce a version field in the profile json file, in case we change anything later, then we could be able to migrate things, there is nothing at all right now. (Can be done later I guess).

2023-06-21 15:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +        public float StrongRumble { get; set;  }
```suggestion
        public float StrongRumble { get; set; }
```

2023-06-21 15:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/Input/ControllerInputConfig.cs
> +        public int Sensitivity { get; set;  }
```suggestion
        public int Sensitivity { get; set; }
```

2023-08-12 11:12 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Helpers/KeyValueConverter.cs
> +            throw new NotSupportedException();
We have other such Converters that are only designed to be one way that throw.

2023-08-12 11:13 UTC, IsaacMarovitz commented
> The issue about JoyCon Right can be reproduced here, and have to be fixed before merge. Seems to only break the SL/SR buttons.

Fixed following rebase on Ava 11

2023-09-19 16:54 UTC, IsaacMarovitz commented
Profiles are bugged 😔

2023-10-21 08:40 UTC, emmauss approved these changes

2023-10-21 08:40 UTC, emmauss commented
LGTM. With net 8 coming out next month, we need to get this in early.

2023-10-21 11:26 UTC, merged