Add support for VK_EXT_depth_clip_control.
Ryujinx/Ryujinx pull request #5027
Opened 2023-05-20 02:11 UTC by cstamford

This PR adds support for `VK_EXT_depth_clip_control` on Vulkan. It provides a significant improvement to z-fighting on distant geometry in Tears of the Kingdom, though it doesn't solve the problem entirely. Other games may see an improvement as well.

Before:

https://github.com/Ryujinx/Ryujinx/assets/6191957/fefdcd38-8fb6-49b4-b5b9-54f44c55ae2b

After:

https://github.com/Ryujinx/Ryujinx/assets/6191957/59c1a897-2428-47e7-b0e6-d45623623286

Testing note: I have confirmed via manual testing that the unhappy path works as expected and falls back to the old method when the extension isn't loaded. However, I don't have access to hardware that doesn't support `VK_EXT_depth_clip_control` so I can't try it for 100% realsies.

See also: https://github.com/Ryujinx/Ryujinx/pull/5012

Thanks to [riperiperi](https://github.com/riperiperi) for pointing me towards this.

2023-05-20 02:39 UTC, gdkchan reviewed
Shader specialization will still create 2 versions of the shader if it is used with the 2 different depth modes. It might be worth to disable it when it's not needed. You could do so by not updating the value on cases where the shader doesn't need any special code depending on depth mode here https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.Graphics.Gpu/Engine/Threed/SpecializationStateUpdater.cs#L162

Ultimately it's not a big deal though becaus games usually don't change depth mode. They usually pick one at the start and stick with it. So it's unlikely that it would create 2 versions of the shader anyway.

2023-05-20 02:39 UTC, gdkchan commented on src/Ryujinx.Graphics.Vulkan/PipelineState.cs
> +                        NegativeOneToOne = DepthMode,
```suggestion
                        NegativeOneToOne = DepthMode
```

2023-05-20 09:49 UTC, GamerzHell9137 commented
Mind bumping the shader cache version?

2023-05-20 12:33 UTC, riperiperi commented on src/Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
> +            if (Config.Options.TargetApi == TargetApi.Vulkan && Config.GpuAccessor.QueryTransformDepthMinusOneToOne() && !Config.GpuAccessor.QueryHostSupportsDepthClipControl())
Maybe `Config.Options.TargetApi == TargetApi.Vulkan` is no longer needed here, as OpenGL will return `true` for `Config.GpuAccessor.QueryHostSupportsDepthClipControl()`.

2023-05-20 17:52 UTC, fatjesusonabike commented
Unintended side-effect of the change that I noticed while playing earlier today (this does not happen on the main build) : 

https://github.com/Ryujinx/Ryujinx/assets/134035322/f17a2400-68e5-4f9f-9985-0eaff4aa96ef

2023-05-20 20:02 UTC, IsaacMarovitz commented
Worth noting that I don't think MoltenVK supports `VK_EXT_depth_clip_control`

2023-05-20 20:29 UTC, riperiperi commented
That’s fine, it will just have to use the existing less precise mode.

2023-05-21 07:58 UTC, marysaka requested changes

2023-05-21 07:58 UTC, marysaka commented on src/Ryujinx.Graphics.Vulkan/PipelineState.cs
> +                        NegativeOneToOne = DepthMode
As per spec, [VkPipelineViewportDepthClipControlCreateInfoEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPipelineViewportDepthClipControlCreateInfoEXT.html)::negativeOneToOne is only supported if [VkPhysicalDeviceDepthClipControlFeaturesEXT](https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPhysicalDeviceDepthClipControlFeaturesEXT.html)::depthClipControl is true.

Your VulkanInitialization and VulkanRenderer changes should use that value to determine if `VK_EXT_depth_clip_control` is truly supported for our needs.

2023-05-21 07:58 UTC, marysaka commented on src/Ryujinx.Graphics.Vulkan/VulkanInitialization.cs
> +            "VK_EXT_depth_clip_control"
```suggestion
            "VK_EXT_depth_clip_control",
            "VK_KHR_portability_subset" // As per spec, we should enable this if present.
```

I would prefer to keep VK_KHR_portability_subset as the last in the list if possible.

2023-05-21 11:01 UTC, marysaka commented
> Do you prefer your PRs to be squashed into one commit?

We do squash at merge so don't worry

2023-05-21 11:03 UTC, marysaka approved these changes

2023-05-21 14:20 UTC, riperiperi commented
(note: doesn't have much to do with correctness of this PR, but more observations about depth bias)

Interestingly, there is still a difference between OpenGL and Vulkan with this PR on SMO. Look at the pedestrian crossings at the bottom left.

OpenGL (ignore framerate, debug build):
![image](https://github.com/Ryujinx/Ryujinx/assets/6294155/882400e7-339d-4121-8494-a51fc35c3aef)

Master Vulkan:
![image](https://github.com/Ryujinx/Ryujinx/assets/6294155/954e9039-2c55-4790-b076-f624e7e87450)

PR Vulkan:
![image](https://github.com/Ryujinx/Ryujinx/assets/6294155/4d27e9c2-11b4-4f2d-ab3b-1e6e954efca1)

Bias on pedestrian crossing:
![image](https://github.com/Ryujinx/Ryujinx/assets/6294155/2a9cc225-d7b2-41ca-9ae0-5a7b1c6a8e82)

Bias on manhole covers:
![image](https://github.com/Ryujinx/Ryujinx/assets/6294155/d1c03118-0c21-4b36-939f-f8a7033986a3)

OpenGL is an exact match for the switch, Vulkan has the pedestrian crossing and the area with the manhole covers fighting for attention. This game is using the -1 to 1 depth mode. "depthBias" correlates to "units", and "slopeScaledDepthBias" correlates to factor, where both values are the same on both backends.

The "intended" way this is meant to appear is pretty weird. The square with the manhole covers overlaps the pedestrian crossing when close to the ground, but further up the bias for the pedestrian crossing actually wins out and appears on top (from this height at least). It starts to z fight at a lower altitude and is well past doing that at the example height, is what i'm saying.

2023-05-21 15:03 UTC, riperiperi commented
SMO matches on vulkan when units are multiplied by 2. Maybe this is a werid interaction with MinusOneToOne depth mode and depth bias on Vulkan, which seems to be the same with the depth rescaling workaround and this PR.

2023-05-21 15:11 UTC, riperiperi commented on src/Ryujinx.Graphics.Shader/Translation/EmitterContext.cs
> +            if (Config.Options.TargetApi == TargetApi.Vulkan && Config.GpuAccessor.QueryTransformDepthMinusOneToOne() && !Config.GpuAccessor.QueryHostSupportsDepthClipControl())
If the next platform were Metal, then it wouldn't support depth clip control, and this workaround would have to be activated. Any case where we can't change the depth mode will need the workaround, so I think checking with this capability is enough.

2023-05-22 04:07 UTC, NikkMann commented
Works great to fix the z fighting but oddly seems to break vulkan reshade with ryujinx. It just crashes on game load.

2023-05-23 02:06 UTC, Linear524 commented
Luigis Mansion 3 is also suffering from shadow Z-fighting issues...
Intro - wooden sign right to the road with dynamic shadow on it - flickering...

2023-05-25 19:56 UTC, riperiperi commented
This PR isn't a complaints board for existing issues. LM3 has other issues with shadows that stem from depth aliasing as red.

2023-05-25 19:57 UTC, riperiperi approved these changes
LGTM, nice work!

2023-05-25 20:00 UTC, gdkchan commented
Needs a rebase.
Also might be worth looking at the depth bias issue mentioned earlier? Although if it was already wrong before, then I guess there's no need to fix it on this PR.

2023-05-27 01:35 UTC, MetrosexualGarbodor commented
Needs another rebase.

2023-05-28 08:58 UTC, marysaka commented
> > Needs a rebase. Also might be worth looking at the depth bias issue mentioned earlier? Although if it was already wrong before, then I guess there's no need to fix it on this PR.
> 
> The depth weirdness is on my radar but I have a couple of other things I want to get to first!

Should I under this as being part of the next iteration or this PR?

2023-05-28 21:31 UTC, merged