Add issue template for missing shader instructions
Ryujinx/Ryujinx pull request #5048
Opened 2023-05-22 10:40 UTC by ExE-Boss

For issues like:
- <https://github.com/Ryujinx/Ryujinx/issues/2794>
- <https://github.com/Ryujinx/Ryujinx/issues/5046>
- <https://github.com/Ryujinx/Ryujinx/issues/5047>

2023-05-22 12:16 UTC, TSRBerry commented on .github/ISSUE_TEMPLATE/missing_shader_instruction.yml
> +      required: true
This is the same as the textarea above.

2023-05-22 12:17 UTC, TSRBerry requested changes
Could you remove the duplicated textarea from the form?

Lgtm otherwise!

2023-05-22 13:19 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/missing_shader_instruction.yml
> +      required: true
This is just a copy paste from https://github.com/Ryujinx/Ryujinx/blob/master/.github/ISSUE_TEMPLATE/missing_cpu_instruction.yml?plain=1 so the only missing thing is probably the `tbd` which could be the log file or if our GPU wizards know where to find a list of shaders instructions, it could be that too.

2023-05-23 10:38 UTC, ExE-Boss commented on .github/ISSUE_TEMPLATE/missing_shader_instruction.yml
> +      required: true
I changed it to “Instruction description” to match what `missing_service_call.yml` does: <https://github.com/Ryujinx/Ryujinx/blob/4ca78eded52f21089400cc28351b9353279b8171/.github/ISSUE_TEMPLATE/missing_service_call.yml?plain=1#L12-L18>

2023-05-27 14:26 UTC, TSRBerry requested changes
Pinged the gpu wizards, so let's wait for clarification.

2023-05-27 14:26 UTC, TSRBerry commented on .github/ISSUE_TEMPLATE/missing_shader_instruction.yml
> +      required: true
I still think this field should be removed, unless @riperiperi or @gdkchan think we could use it to add useful information about missing shader instructions, but in that case the description should also be changed.

2023-05-28 22:44 UTC, gdkchan commented on .github/ISSUE_TEMPLATE/missing_shader_instruction.yml
> +      required: true
The emulator already prints the instruction name in the log when there is a missing instruction (unlike the CPU emulator that does not know the name of instructions that are not implemented). So one can just get it from the log. There is no public documentation with instruction descriptions, so there's nowhere to get it from, that part should be just removed.

2023-05-31 08:36 UTC, marysaka commented on .github/ISSUE_TEMPLATE/missing_shader_instruction.yml
> +      required: true
I think it should be removed imo yup

2023-06-01 15:29 UTC, AcK77 commented on .github/ISSUE_TEMPLATE/missing_shader_instruction.yml
> +      required: true
```suggestion
```

2023-06-01 15:32 UTC, marysaka approved these changes

2023-06-01 15:32 UTC, merged