Updater: Ignore files introduced by the user in base directory
Ryujinx/Ryujinx pull request #5092
Opened 2023-05-24 18:49 UTC by Kurochi51

As per #5077 discussion, I added logic to the updater to determine user files and files that need to be updated. The downfall to this is that old / abandoned shipped files will also remain in the base directory.

Fixes #4757

2023-05-25 13:58 UTC, fabiograssiotto commented
Adding to this discussion, even though setting Reshade files as hidden works to keep the files during updates it does not allow Reshade to update shader paramenters on the fly during gameplay.
So in my opinion a solution to skip user files is of general interest for Reshade or other injector users.

2023-05-28 08:53 UTC, marysaka approved these changes
Seems reasonable, but haven't tested.

2023-05-28 20:54 UTC, AcK77 requested changes
It can be simplified.

2023-05-28 20:54 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                List<string> UserFiles = DirFiles.Except(OldFiles).ToList();
```suggestion
                // Compare the loose files in base directory against the loose files from the incoming update, and store foreign ones in a user list.
                var oldFiles = Directory.EnumerateFiles(HomeDir, "*", SearchOption.TopDirectoryOnly).ToList();
                var newFiles = Directory.EnumerateFiles(UpdatePublishDir, "*", SearchOption.TopDirectoryOnly).ToList();
                
                List<string> userFiles = newFiles.Except(oldFiles).ToList();
```

Should do the job ?

2023-05-28 20:54 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                }
```suggestion
                // Remove user files from the paths in files.
                foreach (var userFile in userFiles)
                {
                    files = files.Where(u => !u.Contains(userFile)).ToList();
                }
```

2023-05-28 21:17 UTC, Kurochi51 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                }
I tested all changes at once, and, atleast a first pass, it seems to not work. I'll look a bit deeper into it, but either the .Where isn't filtering properly, or comparing whole paths instead of file names causes some other issue.

2023-05-28 21:23 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                }
Oh yeah there is `Path.GetFileName` it could be done using LINQ

2023-05-28 21:28 UTC, Kurochi51 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                }
Yeah, I was using that before to make the old files and dir files lists. I'm checking right now if there's anything wrong with all 3 lists, and if not maybe I can just go through `userFiles` and remove the paths.

2023-05-28 22:58 UTC, Kurochi51 commented
I thought it would be more obvious if I did the LINQ selection separately from the initial list assignment, but I can change that if preferred otherwise.

2023-05-29 04:47 UTC, AcK77 approved these changes
Just 2 nits. It should do the job for now, this lgtm! Thanks!

2023-05-29 04:47 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                //Compare the loose files in base directory against the loose files from the incoming update, and store foreign ones in a user list.
```suggestion
                // Compare the loose files in base directory against the loose files from the incoming update, and store foreign ones in a user list.
```

2023-05-29 04:47 UTC, AcK77 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                //Compare the loose files in base directory against the loose files from the incoming update, and store foreign ones in a user list.
```suggestion
                // Compare the loose files in base directory against the loose files from the incoming update, and store foreign ones in a user list.
```

2023-06-01 16:21 UTC, TSRBerry requested changes
We should simplify the logic a bit further.

2023-06-01 16:57 UTC, Kurochi51 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
Won't going through all files run into an issue if there's the same file in different directories?

2023-06-01 17:31 UTC, Kurochi51 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
Yeah, that seems to cause issues in the same file being accessed multiple times, and I can't really solve it without iterating through each file, or going further up the food chain and lock each file, but that doesn't solve the issue where identically named files are stored across different folders. And at that point it boils down to whether you realistically expect / want the users to add files in the folders shipped with the emulator.

2023-06-01 17:31 UTC, Kurochi51 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
Yeah, that seems to cause issues in the same file being accessed multiple times, and I can't really solve it without iterating through each file, or going further up the food chain and try to do some file lock, but that doesn't solve the issue where identically named files are stored across different folders. And at that point it boils down to whether you realistically expect / want the users to add files in the folders shipped with the emulator.

2023-06-01 17:45 UTC, Kurochi51 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
I've been trying to think of ways this could work, but I'd more or less have to iterate through all files both in `UpdatePublishDir` and in `HomeDir`, which seems against the point.

2023-06-01 18:52 UTC, TSRBerry commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
Okay, I misunderstood a lot more than that, not even sure if my suggestion really simplifies it.
Tell me what you think about it! :D

2023-06-01 19:04 UTC, TSRBerry commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
Don't forget you are iterating over files multiple times as well.

2023-06-01 19:06 UTC, Kurochi51 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
That's true, in that case I'll make sure it works, and push the update if so.

2023-06-01 19:19 UTC, Kurochi51 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                }
Seems good!

2023-06-01 19:26 UTC, TSRBerry approved these changes
Thank you for being patient with me!
Lgtm! :D

2023-06-05 12:19 UTC, merged