Show/Hide UI Hotkey fix on Avalonia
Ryujinx/Ryujinx pull request #5133
Opened 2023-05-28 20:02 UTC by patrick-hovsepian

Address ` Hide UI use F4 hotkey, but if you enable it, there is no way to get the UI back by pressing F4.` from #3662

2023-05-28 20:03 UTC, gdkchan commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml
> +					Command="{ReflectionBinding SimulateWakeUpMessage}"
This is using Tabs rather than spaces.

2023-05-28 20:07 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml
> +					Command="{ReflectionBinding SimulateWakeUpMessage}"
Ah, just reverted for now until I get my settings figured out.

2023-05-28 20:38 UTC, AcK77 approved these changes

2023-05-28 22:36 UTC, TSRBerry requested changes
Could you add that for Gtk as well?

2023-05-28 23:27 UTC, MutantAura commented
> Could you add that for Gtk as well?

This behavior is fully intentional on GTK. And I'm not entirely sure how to resolve the issue between them here. 
The reason it doesn't simply toggle already, is because we had users who had pressed F4 by mistake, and as such lost access to the UI entirely, with no way to return it outside restarting the program. 

If we just had to deal with Ava, I'd say this change is fine, along with making the hotkey un-assigned by default perhaps, so people can't accidentally trigger it. On GTK, this obviously isn't possible because users wouldn't be able to map it. There is just a straight incompatibility between them.

2023-05-29 00:37 UTC, patrick-hovsepian commented
> along with making the hotkey un-assigned by default perhaps, so people can't accidentally trigger it

Can that be done as a follow up or would you want to require it for this PR?

2023-06-04 21:42 UTC, patrick-hovsepian commented
default to unset

2023-06-04 21:49 UTC, MutantAura commented
> default to unset

Again, this isn't a solution because GTK exists and there is a menu option that can hide the UI. If a user on either clicked this without binding a show hotkey, it would be a one way trip unless the app was restarted.

2023-06-04 21:52 UTC, MutantAura commented
To clarify as I'm not sure why this was closed, I'm fine with this being changed to a toggle (albeit with the inherant downsides this setting intrinsically will always have), but unmapping it by default cannot happen until GTK is gone.

2023-06-04 21:57 UTC, patrick-hovsepian commented
> but unmapping it by default cannot happen until GTK is gone. 

So this PR would just stick around until then? If that's the case, I'll re-open it but I closed it because I thought you wanted changes made there too and I didn't see the point if it was going to be deprecated.

2023-06-04 22:43 UTC, patrick-hovsepian commented
Been some back and forth on discord

2023-06-04 22:51 UTC, MutantAura approved these changes

2023-06-11 13:34 UTC, TSRBerry approved these changes
Sorry for the delay, lgtm!

2023-06-11 13:34 UTC, merged