macOS Headless Fixes
Ryujinx/Ryujinx pull request #5167
Opened 2023-05-30 19:10 UTC by IsaacMarovitz

- Set Hypervisor to disabled by default
   - There is a long-standing bug in CommandLineParser that makes it impossible to disable an bool argument if it is set to true by default
   - Since Headless builds are not currently built with an Info.plist, they do not have the entitlements to access hypervisor and it will always fail to initalise
- Bundled MoltenVK in headless builds when building on macOS

Other Potential Fixes:
- Default to Vulkan on macOS and don't allow OpenGL to be used at all
- Properly give the executable entitlements so it can use the hypervisor

2023-05-30 19:47 UTC, TSRBerry requested changes
A few comments, but lgtm otherwise!

2023-05-30 19:47 UTC, TSRBerry commented on src/Ryujinx.Headless.SDL2/Options.cs
>          public bool UseHypervisor { get; set; }
You can deal with this by using a nullable bool here, instead of setting the default to false.

2023-05-30 19:47 UTC, TSRBerry commented on src/Ryujinx.Headless.SDL2/Program.cs
> +
Only print this warning if the user attempted to launch it with the OpenGL backend.

2023-05-30 20:28 UTC, TSRBerry reviewed
Thank you! Just thought of something, so I added another comment.

2023-05-30 20:28 UTC, TSRBerry commented on src/Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj
> +    <PackageReference Include="Ryujinx.Graphics.Vulkan.Dependencies.MoltenVK" Condition="'$(RuntimeIdentifier)' != 'linux-x64' AND '$(RuntimeIdentifier)' != 'win10-x64'" />
```suggestion
    <PackageReference Include="Ryujinx.Graphics.Vulkan.Dependencies.MoltenVK" Condition="'$(RuntimeIdentifier)' == 'osx-x64' OR '$(RuntimeIdentifier)' == 'osx-arm64' OR $([MSBuild]::IsOSPlatform('OSX'))" />
```
How about something like this? Maybe this could also help with #5049? (cc @marysaka)

2023-05-31 06:17 UTC, marysaka commented on src/Ryujinx.Headless.SDL2/Ryujinx.Headless.SDL2.csproj
> +    <PackageReference Include="Ryujinx.Graphics.Vulkan.Dependencies.MoltenVK" Condition="'$(RuntimeIdentifier)' != 'linux-x64' AND '$(RuntimeIdentifier)' != 'win10-x64'" />
I would prefer to keep the solution the same as we have on other projects for now @TSRBerry.
I think we should unify this kind of checks in some helper file to avoid duplicating it everywhere.

2023-05-31 06:18 UTC, marysaka approved these changes
lgtm

2023-05-31 07:05 UTC, TSRBerry approved these changes
Lgtm, thanks!

2023-05-31 07:08 UTC, merged