Blocks should be synchronized on read-only fields
Ryujinx/Ryujinx pull request #5212
Opened 2023-06-03 20:50 UTC by marco-carvalho

2023-06-03 21:59 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/TimedAction.cs
> +        private readonly object _lock = new object();
This is misaligned now. I'd prefer if you remove alignment from all those fields.

2023-06-03 21:59 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ssl/BuiltInCertificateManager.cs
>          private bool                _initialized;
Might as well fix this that is misaligned while you are at it.

2023-06-03 22:14 UTC, marco-carvalho commented on src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/TimedAction.cs
> +        private readonly object _lock = new object();
committed

2023-06-03 22:14 UTC, marco-carvalho commented on src/Ryujinx.HLE/HOS/Services/Ssl/BuiltInCertificateManager.cs
>          private bool                _initialized;
committed

2023-06-03 22:26 UTC, gdkchan approved these changes
lgtm, thanks.

2023-06-10 14:08 UTC, riperiperi approved these changes
Makes sense.

2023-06-10 14:08 UTC, riperiperi commented on src/Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +        private readonly object _fatalSectionLock = new object();
The alignment of the next line mismatches now.

2023-06-10 14:58 UTC, marco-carvalho commented on src/Ryujinx.HLE/HOS/Services/Am/AppletAE/AllSystemAppletProxiesService/SystemAppletProxy/ISelfController.cs
> +        private readonly object _fatalSectionLock = new object();
could you check again, please?

2023-06-10 15:15 UTC, riperiperi approved these changes

2023-06-14 15:56 UTC, AcK77 requested changes
Could be nice if you could change ` = new object();` with ` = new();`. Thanks.

2023-06-14 18:49 UTC, marco-carvalho commented
> Could be nice if you could change ` = new object();` with ` = new();`. Thanks.

@AcK77 could you check again, please?

2023-06-14 18:50 UTC, TSRBerry commented
![image](https://github.com/Ryujinx/Ryujinx/assets/20988865/7738bc74-754d-4252-ac03-d937afba2b50)
You should be able to re-request a review by clicking this button.

2023-06-15 00:34 UTC, merged