Ava: Fix OpenGL on Linux again
Ryujinx/Ryujinx pull request #5216
Opened 2023-06-04 03:07 UTC by TSRBerry

I have absolutely no clue why this works.

The error produced by X11 looks like that: `XError: X_Error result is BadMatch (invalid parameter attributes) (code: 8)`
(You can get the error by applying https://github.com/marysaka/SPB/pull/4 to SPB.)

As far as I understood, the issue was related to one of the `FramebufferFormat` parameters being incorrect.
I was about to test different values for `depthBits` (as this [answer](https://stackoverflow.com/a/17127200) suggested), but tried the empty constructor once just to see what would happen. To my surprise it just started to work, so here we are.

2023-06-05 12:03 UTC, marysaka requested changes

2023-06-05 12:03 UTC, marysaka commented on src/Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs
> -                X11Window = PlatformHelper.CreateOpenGLWindow(FramebufferFormat.Default, 0, 0, 100, 100) as GLXWindow;
This is wrong, the right fix would be to apply the same logic as in EmbeddedWindowOpenGL [here](https://github.com/Ryujinx/Ryujinx/blob/68848000f77e587ed4cd99e84a234fcf79fd7ea3/src/Ryujinx.Ava/UI/Renderer/EmbeddedWindowOpenGL.cs#L53).

2023-06-05 12:11 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs
> -                X11Window = PlatformHelper.CreateOpenGLWindow(FramebufferFormat.Default, 0, 0, 100, 100) as GLXWindow;
I see, thank you! I had no idea why it worked like that and was confused why this was needed twice as well.

2023-06-05 12:13 UTC, marysaka commented on src/Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs
> -                X11Window = PlatformHelper.CreateOpenGLWindow(FramebufferFormat.Default, 0, 0, 100, 100) as GLXWindow;
I really do not understand too!

all OpenGL related code should be in EmbeddedWindowOpenGL not EmbeddedWindow imo.

2023-06-05 12:21 UTC, TSRBerry commented
Marked as draft, because I just noticed I'm crashing when stopping emulation now.

I think I'm crashing with the same XError, but don't have my SPB fork active right now, so I don't know for sure.

https://github.com/Ryujinx/Ryujinx/blob/1874305040ed4e93cd77f771cdaae99f735f8375/src/Ryujinx.Ava/AppHost.cs#L478

I'll check this later again and hope to fix this completely somehow.

2023-06-05 14:17 UTC, TSRBerry commented
I basically copied the logic from GTK and added logging messages to prevent Ava from crashing when stopping emulation.

2023-06-05 17:06 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +                }
Maybe the `try`/`catch` should be added in `EmbeddedWindowOpenGL.MakeCurrent()` directly, to avoid duplicated code and put everything at the same place ?

2023-06-05 17:28 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> +                }
It has to succeed initially when the window is set up.

2023-06-08 12:55 UTC, riperiperi reviewed
Should probably be tested on AMD. Does this same thing cause issues on GTK? (since it creates the background context this way)

2023-06-08 13:08 UTC, riperiperi commented
It does look like both Ava and GTK create their main context with these parameters, so the change to Ava will probably work on AMD. It's weird that GTK was fine though, as the background context is created in a similar way.

2023-06-09 11:13 UTC, marysaka commented
> It does look like both Ava and GTK create their main context with these parameters, so the change to Ava will probably work on AMD. It's weird that GTK was fine though, as the background context is created in a similar way.

I think the main difference is that the window is provided by GTK (and is setup that way?)

So to me it's a mismatch between the surface requested when creating the window and the one requested for the OpenGL context.

I think asking for default framebuffer format on context creation might work also, but I do not want to have a divergence between GTK and Avalonia here that might cause issues.

2023-06-09 11:15 UTC, marysaka commented on src/Ryujinx.Ava/AppHost.cs
> +                }
> Maybe the `try`/`catch` should be added in `EmbeddedWindowOpenGL.MakeCurrent()` directly, to avoid duplicated code and put everything at the same place ?

Depending of the environment, those might fail here because for example the context is already current or already unbind.

In other cases we want the exception to be throw.

2023-06-09 11:16 UTC, marysaka approved these changes

2023-06-10 01:02 UTC, AcK77 approved these changes

2023-06-10 13:53 UTC, riperiperi approved these changes
Tested on AMD+SteamOS and looks fine. Nice work!

2023-06-11 16:31 UTC, merged