[Ava] Hide Cursor and Window Main Loop Refactor
Ryujinx/Ryujinx pull request #5288
Opened 2023-06-11 22:48 UTC by patrick-hovsepian

This PR addresses the Ava UI not properly hiding the cursor. The check for whether the cursor is within the active window did not take into account the windows position as an offset.

This PR addresses that issues and also slightly refactors some of the logic for readability and modularity. There does appear to be frame updates that are made even when nothing changed. I'd like to go back and address that but will do so separately.

This may address #5136

2023-06-11 22:50 UTC, patrick-hovsepian reviewed
highlights

2023-06-11 22:50 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/AppHost.cs
> +                                        point.Y <= bounds.Height + bounds.Y + window.Position.Y;
account for window position

2023-06-11 22:50 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/AppHost.cs
> +#endif
wrapped this in a pre-processor check

2023-06-11 23:34 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +#endif
DebugPad is something related to the Switch hid service, it shouldn’t be wrapped since it’s not related to a Debug build.

2023-06-12 01:27 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/AppHost.cs
> +#endif
thanks for the context. reverted that bit.

2023-06-13 18:54 UTC, TSRBerry requested changes
Most of the changes lgtm! Just left a few comments where I didn't understand your changes or where I think something could be better named.

2023-06-13 18:54 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> +                // wait for an event to trigger this rather than poll.
Why are these comments here?

2023-06-13 18:54 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> +            // Only call if needed
You changed nothing here, what was that comment added for?

2023-06-13 18:54 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> +            void TriggerKeyboardHotkey()
```suggestion
            void UpdateHotkeyState()
```

2023-06-13 18:54 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> +                if (currentHotkeyState == _prevHotkeyState)
```suggestion
                
                if (currentHotkeyState == _prevHotkeyState)
```

2023-06-13 20:06 UTC, Exhigh commented
This commit seems to aggressively hide the cursor, like whilst moving the cursor it tries to hide the cursor, making the cursor go active and hidden constantly. ( This is on Avalonia btw, also the setting that I am on is to hide the cursor while on idle )

2023-06-13 22:48 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/AppHost.cs
> +                // wait for an event to trigger this rather than poll.
Just thinking out loud - I'll clean this and the other comment up.

2023-06-13 23:04 UTC, patrick-hovsepian commented
@Exhigh this should be the same behavior as the master branch. Would you mind confirming if you see the same behavior there?

2023-06-14 12:26 UTC, TSRBerry commented
I can't reproduce the issue you mentioned @Exhigh. For me direct mouse access behaves as expected, so the mouse is hidden even when moving it and only is shown outside of the emulator window (and for the menu items).
Do you have a video of the behavior you are seeing?

2023-06-14 12:27 UTC, TSRBerry approved these changes
Lgtm, thank you!

2023-06-14 15:25 UTC, AcK77 requested changes

2023-06-14 15:25 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +                return;
```suggestion

                return;
```

2023-06-14 15:25 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +                point.Y <= bounds.Height + bounds.Y + window.Position.Y;
```suggestion
            _isCursorInRenderer = point.X >= bounds.X && point.X <= bounds.Width + bounds.X + window.Position.X
                && point.Y >= bounds.Y && point.Y <= bounds.Height + bounds.Y + window.Position.Y;
```

2023-06-14 15:25 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +            void UpdateCursorState()
I'm not a huge fan of getting the method included in `UpdateActiveFrame`

2023-06-14 15:25 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +            void UpdateHotkeyState()
I'm not a huge fan of getting the method included in `UpdateActiveFrame`

2023-06-14 15:25 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +            // Touchscreen.
```suggestion
```
This can be removed, since we haven't any comment for other input, it make no sense to keep it.

2023-06-14 15:25 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +                _prevHotkeyState = currentHotkeyState;
```suggestion

                _prevHotkeyState = currentHotkeyState;
```

2023-06-14 15:54 UTC, Exhigh commented
> y

I could create a video, would take me some time though.

2023-06-14 16:19 UTC, Exhigh commented
> I can't reproduce the issue you mentioned @Exhigh. For me direct mouse access behaves as expected, so the mouse is hidden even when moving it and only is shown outside of the emulator window (and for the menu items). Do you have a video of the behavior you are seeing?

[Video of the previously stated behavior](https://we.tl/t-5glnurkRxE)

2023-06-14 16:21 UTC, TSRBerry commented
Seems to be a Windows only issue then.

2023-06-14 16:22 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> +            void UpdateCursorState()
It was part of it before as well, what's the issue here?

2023-06-14 16:23 UTC, Exhigh commented
> Seems to be a Windows only issue then.

well

2023-06-14 18:57 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/AppHost.cs
> +            void UpdateCursorState()
I think it's the use of the local function vs a private one in the class? I'll update it if you really want me to but i think there's a small performance boost (although not 100% sure on that) the other thing is it makes it clear that the function is only intended to be used within that calling scope not arbitrarily by other class methods.

2023-06-16 10:09 UTC, Exhigh commented
As of the most recent commit, the cursor hides itself and seems to re-appear after some duration and hides itself again, I am not sure if its an issue just on my end.

2023-06-16 14:38 UTC, TSRBerry commented
Doesn't happen on Linux at least, but that's all I can tell you.

2023-06-16 17:12 UTC, patrick-hovsepian commented
It definitely is a bit wonky on Windows for sure. I tested in Windows 10 and MacOS and didn't see the problem you mentioned but maybe document an issue with settings and someone can dig into it at some point?

2023-06-16 22:00 UTC, jojodunet commented
ava-ryujinx-Release-1.1.0+ca2bc33-win_x64.zip
Windows 10

Ruyjinx.Ava.exe -f --hide-cursor Always Game.nsp

The cursor disappears during the loading screen. It reappears when the game is launched. 
However, if I move the mouse afterwards, it disappears again.

2023-06-16 22:12 UTC, jojodunet commented
> As of the most recent commit, the cursor hides itself and seems to re-appear after some duration and hides itself again, I am not sure if its an issue just on my end.

@Exhigh I have the same issue, but it disappears, reappears, and disappears again at precise moments, as I explained above.

2023-06-18 01:24 UTC, patrick-hovsepian commented
Thanks for checking, are you able to confirm if you see the same thing on master?

2023-06-18 06:33 UTC, jojodunet commented
> Thanks for checking, are you able to confirm if you see the same thing on master?

@patrick-hovsepian It’s not the same on master. 

Here the issue on master actually :
https://github.com/Ryujinx/Ryujinx/pull/4927#issuecomment-1552031910

2023-06-22 16:42 UTC, AcK77 commented
It could be nice to get this issues fixed before considering a merge. Thanks :)

2023-06-22 22:56 UTC, TSRBerry commented
If it's the same as master I don't think it's on them to fix it.

2023-06-26 12:33 UTC, jojodunet commented
Who can handle it and fix the issue on Windows?

2023-06-29 11:58 UTC, closed without merging

2023-06-29 12:34 UTC, TSRBerry commented
Why was this closed?

2023-06-29 22:30 UTC, patrick-hovsepian commented
@TSRBerry Exhigh reached out offline about adding some changes which is #5415