Blocks should be synchronized on read-only fields
Ryujinx/Ryujinx pull request #5318
Opened 2023-06-16 17:37 UTC by marco-carvalho

Continuation of https://github.com/Ryujinx/Ryujinx/pull/5212

2023-06-22 16:35 UTC, AcK77 requested changes

2023-06-22 16:35 UTC, AcK77 commented on src/Ryujinx.Graphics.GAL/Multithreading/BufferMap.cs
> +        private readonly AutoResetEvent _inFlightChanged = new AutoResetEvent(false);
```suggestion
        private readonly Dictionary<BufferHandle, BufferHandle> _bufferMap = new();
        private readonly HashSet<BufferHandle> _inFlight = new();
        private readonly AutoResetEvent _inFlightChanged = new(false);
```

2023-06-22 16:35 UTC, AcK77 commented on src/Ryujinx.Graphics.GAL/Multithreading/SyncMap.cs
> +        private readonly HashSet<ulong> _inFlight = new HashSet<ulong>();
```suggestion
        private readonly HashSet<ulong> _inFlight = new();
```

2023-06-22 16:35 UTC, AcK77 commented on src/Ryujinx.Graphics.Gpu/Image/Texture.cs
> +        private readonly List<TexturePoolOwner> _poolOwners = new List<TexturePoolOwner>();
```suggestion
        private readonly List<TexturePoolOwner> _poolOwners = new();
```

2023-06-22 16:35 UTC, AcK77 commented on src/Ryujinx.Graphics.OpenGL/Sync.cs
> +        private readonly List<SyncHandle> _handles = new List<SyncHandle>();
```suggestion
        private readonly List<SyncHandle> _handles = new();
```

2023-06-22 16:35 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Mm/IRequest.cs
>          private static List<MultiMediaSession> _sessionList     = new List<MultiMediaSession>();
```suggestion
        private static List<MultiMediaSession> _sessionList = new();
```

2023-06-22 21:51 UTC, AcK77 approved these changes

2023-06-24 12:47 UTC, marysaka approved these changes

2023-07-06 09:05 UTC, closed without merging

2023-07-06 13:13 UTC, marco-carvalho commented
@marysaka can I ask why this is now closed, since you and @AcK77 previously approved it?

2023-07-06 13:30 UTC, marysaka commented
> @marysaka can I ask why this is now closed, since you and @AcK77 previously approved it?

Already part of https://github.com/Ryujinx/Ryujinx/pull/5380 planned for merge soon.

Also, I do not believe that flooding PRs from sonar lint or other tools is useful for the project.
We barely have time to review actual changes in the codebase and this just end up slowing us down more than anything.