Null pointers should not be dereferenced
Ryujinx/Ryujinx pull request #5319
Opened 2023-06-16 18:28 UTC by marco-carvalho

2023-06-17 20:25 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/ServerDomainManager.cs
> +                    if (entry != null)
This looks rather weird. Also it accesses `entry.Obj` right below, so if it was null, it would throw there anyway, so not sure what this check adds. Perhaps it should first assert that entry itself is not null, if it's going to use it and there's the possibility of it being null. Or maybe it should just throw `ArgumentNullException` at the start of the method if it is null. Though I think in general, we don't validate method parameters, they are assumed to be correct.

2023-06-18 19:55 UTC, marco-carvalho commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/ServerDomainManager.cs
> +                    if (entry != null)
You were right, I added `entry.Obj` inside the `if` statement.

2023-06-22 16:21 UTC, AcK77 requested changes
There are really some strange changes here. Some null checks could be useful, I'm sorry, but for some others I wonder if you readed the code before you did things.

2023-06-22 16:21 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/ControllerInputViewModel.cs
> +                    if (config != null)
In our current case, if `IsKeyboard` is false then `IsController` is true, or the invert. So `config` can't be null here.
I'd prefer, at least, to change the above `else if (IsController)` into `else // if (IsController)` if we want something cleaner.
But the null check isn't really useful here.

2023-06-22 16:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Gpu/Shader/DiskCache/DiskCacheHostStorage.cs
> +            if (tocFileStream != null)
Above this code there is `if (tocFileStream == null ...` if the condition is reached then `tocFileStream` is assigned. If there is something wrong in the method called to assign it, then I'm pretty sure it will throw something. I don't see why we should add two `if (tocFileStream != null)` here.

2023-06-22 16:21 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +            }
```suggestion

            if (bytes != null)
            {
                writer.Seek((int)maxSize - bytes.Length, SeekOrigin.Current);
            }

```

but this condition do any sense. There is `writer.Write(bytes);` just above, if `bytes` where `null` it will reach a NRE here, so the check will change anything.

2023-06-22 16:21 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs
```suggestion
            else
            {
                channelDeviceFile.Channel.BindMemory(_asContext.Gmm);
            }
```

Or maybe resolve the `TODO` should be enough.

2023-06-22 16:21 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Nv/NvDrvServices/NvHostAsGpu/NvHostAsGpuDeviceFile.cs
> +            }
Not needed, read the above comment.

2023-06-22 16:21 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/ServerDomainManager.cs
> +                    if (entry != null)
I agree with gdkchan, the check here isn't needed, even more because it's a debug assert too (same for all other checks).

2023-06-24 12:06 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Applets/SoftwareKeyboard/InlineResponses.cs
> +            }
> but this condition do any sense. There is writer.Write(bytes); just above, if bytes where null it will reach a NRE here, so the check will change anything.

This is not resolved!

2023-07-01 06:33 UTC, AcK77 commented
Could you please fixes old opened PR like this one before opening new ones?
Thanks.

2023-07-06 09:05 UTC, closed without merging