Ava UI: Make some setting methods async
Ryujinx/Ryujinx pull request #5332
Opened 2023-06-19 11:04 UTC by MutantAura

Creating the settings window was being blocked by a few synchronous methods, the main timesink being the creation of the Vulkan device list which took over a second on my system. By making this check, audio backend checks, timezone creation and network interface population asynchronous, the window is able to open _much_ faster.

https://github.com/Ryujinx/Ryujinx/assets/44103205/bddf51c4-ecb7-401f-ac06-c521c5af2359

The first time the window is opened is still somewhat JIT limited, but subsequent openings will be massively better.

2023-06-19 21:36 UTC, patrick-hovsepian reviewed
nice improvement! some minor thoughts

2023-06-19 21:36 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            });
I'm not familiar with the sound drivers but are these really hotspots in the code? Does this need to happen async? Would it make sense to use a discard and bake in the `OnPropertyChanged` events into the Action?

2023-06-19 21:36 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            AvailableGpus.AddRange(_gpuNames.Select(x => new ComboBoxItem { Content = x }));
Does it make sense to pull the clear up before the if/else. That way you can add the combox as you're iterating the devices anyway and not have to loop through it twice

2023-06-19 21:36 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
>              _timeZoneContentManager.InitializeInstance(_virtualFileSystem, _contentManager, IntegrityCheckLevel.None);
curious if you're aware of why this can't be done in the constructor so it's not repeated on every invocation

2023-06-19 21:36 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                    string abbr2 = abbr.StartsWith('+') || abbr.StartsWith('-') ? string.Empty : abbr;
are you able to reassign to abbr?

2023-06-20 20:08 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            });
The SDL driver can take some time to initialize, I think the GTK UI already defers this.

2023-06-20 20:15 UTC, MutantAura commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            });
Either way as far as UI goes I prefer the opposite mentality of "Does this need to block?" rather than "Does this need to happen async?". Realistically not much outside of the drawing of the windows themselves actually needs to be synchronous on the UI thread. All of the methods here related to settings that are not on the first navpage so I do believe should not be blocking, no matter how small their contribution is.

2023-06-20 20:20 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                        _gpuIds.Add(device.Id);
This list is now accessed from multiple threads, so it there should be some lock around any time it's used, such as in `LoadCurrentConfiguration` and `SaveSettings`.

2023-06-20 20:20 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                    TimeZones.Add(new TimeZone($"UTC{hours:+0#;-0#;+00}:{minutes:D2}", location, abbr2));
`AvaloniaList` doesn't appear to be thread safe. Maybe this should be modified via an invoke on the UI thread. (actually, maybe all the collection modifications should? after we get the expensive parts out of the way)

You can do this with `Dispatcher.UIThread.Post`.

2023-06-20 20:20 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                    _networkInterfaces.Add(networkInterface.Name, networkInterface.Id);
Same here, not thread safe. Modify with `Dispatcher.UIThread.Post` is probably a good shout, but do `NetworkInterface.GetAllNetworkInterfaces()` first outside the invoke.

2023-06-20 20:20 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                        _gpuIds.Add(device.Id);
Changing it to use `Dispatcher.UIThread.Post` as described below may be easier.

2023-06-20 22:39 UTC, patrick-hovsepian commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            });
Again, I wasn't aware of the underlying semantics so figured that played into it some. It looks like a simple boolean assignment which seems like a code smell to wrap in a task. If these were method calls instead, the intent would be much clearer IMO

2023-07-02 19:55 UTC, MutantAura commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +                        _gpuIds.Add(device.Id);
Can you check these again. I believe everything used by multiple methods should now be thread safe?

2023-07-02 19:56 UTC, MutantAura commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            AvailableGpus.AddRange(_gpuNames.Select(x => new ComboBoxItem { Content = x }));
Simplified this logic also allowed me to remove _gpuNames entirely.

2023-07-07 22:47 UTC, IsaacMarovitz approved these changes
lgtm

2023-07-22 19:21 UTC, riperiperi reviewed
Looks good, just one more nit about calls to `OnPropertyChanged`.

I'm not sure what is listening for these property changes, I'm just assuming it is something internal to Avalonia and it might not be thread safe.

2023-07-22 19:21 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            OnPropertyChanged(nameof(IsOpenAlEnabled));
These might need to run in `Dispatcher.UIThread.Post`.

2023-07-22 19:21 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            OnPropertyChanged(nameof(PreferredGpuIndex));
Same here.

2023-07-22 19:21 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            OnPropertyChanged(nameof(TimeZone));
Same here.

2023-07-22 19:21 UTC, riperiperi commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +            OnPropertyChanged(nameof(NetworkInterfaceList));
Same here.

2023-08-03 23:15 UTC, riperiperi approved these changes
This is considerably better. Nice work!

2023-08-12 18:39 UTC, TSRBerry requested changes
```
Unhandled exception caught: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Avalonia.Collections.AvaloniaList`1.get_Item(Int32 index)
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel.set_NetworkInterfaceIndex(Int32 value) in /src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 271
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel.LoadCurrentConfiguration() in /src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 478
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel..ctor() in /src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 299
   at Ryujinx.Ava.UI.ViewModels.SettingsViewModel..ctor(VirtualFileSystem virtualFileSystem, ContentManager contentManager) in /src/Ryujinx/src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs:line 275
   at Ryujinx.Ava.UI.Windows.SettingsWindow..ctor(VirtualFileSystem virtualFileSystem, ContentManager contentManager) in /src/Ryujinx/src/Ryujinx.Ava/UI/Windows/SettingsWindow.axaml.cs:line 19
   at Ryujinx.Ava.UI.Views.Main.MainMenuBarView.OpenSettings(Object sender, RoutedEventArgs e) in /src/Ryujinx/src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs:line 128
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.OnOSTimer()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at Ryujinx.Ava.Program.Main(String[] args) in /src/Ryujinx/src/Ryujinx.Ava/Program.cs:line 51
```

Opening the settings window again after closing it, leads to the crash above. Could you look into that?

2023-08-12 20:41 UTC, TSRBerry approved these changes
Lgtm, thank you! :D

2023-08-12 20:43 UTC, merged