Headless: Add support for fullscreen option
Ryujinx/Ryujinx pull request #5339
Opened 2023-06-21 02:16 UTC by theundebruijn

The headless SDL2 client was missing a way to launch in fullscreen mode.
This PR adds an optional argument similar to the one used in the GUI client's CLI.

In addition to getting headless in line with Ava/GTK, by adding this we support launching games in fullscreen mode from third party launchers (e.g. Steam Big Picture).

---

NOTE: This PR serves as a prerequisite for https://github.com/Ryujinx/Ryujinx/pull/5412

---

#### TODO's

_Implementation_ :
- [x] Implement `borderless fullscreen windowed` logic
- [x] Add `--fullscreen` option to Headless CLI argument list

_Testing_ :
- [x] Windows 11 (22H2) (Intel x64) — Nvidia (Vulkan + OpenGL)
- [x] MacOS 12.x (Intel x64) — AMD (Vulkan)
- [x] MacOS 13.x (ARM64) — Apple Silicon (Vulkan) (tyvm @siegmund-heiss-ich)
- [x] Linux (Fedora Workstation 38) (Intel x64) (Wayland) — AMD (Vulkan + OpenGL)
- [x] Linux (Fedora Workstation 38) (Intel x64) (X11) — AMD (Vulkan + OpenGL)

2023-06-21 02:55 UTC, patrick-hovsepian commented on src/Ryujinx.Headless.SDL2/Program.cs
> +                StartFullscreen = true;
super nit: drop the condition and just assign to option.StartFullScreen

2023-06-21 02:55 UTC, patrick-hovsepian commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +            return (Program.StartFullscreen) ? SDL_WindowFlags.SDL_WINDOW_FULLSCREEN_DESKTOP : 0;
is there a defined flag for 0?

2023-06-21 15:11 UTC, AcK77 requested changes

2023-06-21 15:11 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/Options.cs
> +        public bool StartFullscreen { get; set; }
```suggestion
        public bool IsFullscreen { get; set; }
```

2023-06-21 15:11 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/Program.cs
> +            StartFullscreen = option.StartFullscreen;
Why do not set a field in `WindowBase` instead ?

```suggestion
            _window.IsFullscreen = option.IsFullscreen;
```

2023-06-21 15:11 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +            WindowHandle = SDL_CreateWindow($"Ryujinx {Program.Version}{titleNameSection}{titleVersionSection}{titleIdSection}{titleArchSection}", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, De
```suggestion
            SDL_WindowFlags fullscreenFlag =  IsFullscreen ? SDL_WindowFlags.SDL_WINDOW_FULLSCREEN_DESKTOP : 0;

            WindowHandle = SDL_CreateWindow($"Ryujinx {Program.Version}{titleNameSection}{titleVersionSection}{titleIdSection}{titleArchSection}", SDL_WINDOWPOS_UNDEFINED, SDL_WINDOWPOS_UNDEFINED, DefaultWidth, DefaultHeight, DefaultFlags | fullscreenFlag | GetWindowFlags());
```

2023-06-21 15:11 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +        private SDL_WindowFlags GetFullscreenFlags()
This could be removed since it will not be used elsewhere

2023-06-22 16:05 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/Program.cs
> +        public static bool StartFullscreen { get; private set; } = false;
This is not needed anymore

2023-06-22 16:05 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +            SDL_WindowFlags fullscreenFlag =  IsFullscreen ? SDL_WindowFlags.SDL_WINDOW_FULLSCREEN_DESKTOP : 0;
```suggestion
            SDL_WindowFlags fullscreenFlag =  IsFullscreen ? SDL_WindowFlags.SDL_WINDOW_FULLSCREEN_DESKTOP : 0;

```

2023-06-22 22:45 UTC, AcK77 approved these changes

2023-06-29 15:15 UTC, siegmund-heiss-ich commented
Currently macOS crashes if you try to start headless in fullscreen mode.
This needs to be resolved before merge.

No useful information in ryujinx.log
macOS crash report:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Ryujinx.Headless.SDL2 [2927]
Path:                  /Users/USER/Desktop/*/Ryujinx.Headless.SDL2
Identifier:            Ryujinx.Headless.SDL2
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        zsh [1178]
Responsible:           iTerm2 [1174]
User ID:               501

Date/Time:             2023-06-29 17:09:35.9143 +0200
OS Version:            macOS 13.4.1 (22F82)
Report Version:        12
Anonymous UUID:        6DF772F6-6CCF-2D06-1510-EBE77F2E1FEC


Time Awake Since Boot: 1000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called


Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x183224724 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x18325bc28 pthread_kill + 288
2   libsystem_c.dylib             	       0x183169ae8 abort + 180
3   libcoreclr.dylib              	       0x102942688 PROCAbort + 56
4   libcoreclr.dylib              	       0x1029425a4 PROCEndProcess(void*, unsigned int, int) + 384
5   libcoreclr.dylib              	       0x102b5a0e4 UnwindManagedExceptionPass1(PAL_SEHException&, _CONTEXT*) + 972
6   libcoreclr.dylib              	       0x102b5a12c DispatchManagedException(PAL_SEHException&, bool) + 68
7   libcoreclr.dylib              	       0x102a3e54c VSD_ResolveWorker + 1552
8   libcoreclr.dylib              	       0x102be3a4c ResolveWorkerAsmStub + 88
9   ???                           	       0x283698620 ???
10  ???                           	       0x283698620 ???
```

2023-07-02 14:01 UTC, TSRBerry commented
My test results:

<details>
<summary>Linux x64: OpenGL</summary>

Crash:
```
System.InvalidOperationException: SDL_GL function returned an error: No OpenGL context has been made current
   at Ryujinx.Headless.SDL2.OpenGL.OpenGLWindow.CheckResult(Int32 result) in /src/Ryujinx/src/Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs:line 18
   at Ryujinx.Headless.SDL2.OpenGL.OpenGLWindow.InitializeWindowRenderer() in /src/Ryujinx/src/Ryujinx.Headless.SDL2/OpenGL/OpenGLWindow.cs:line 131
   at Ryujinx.Headless.SDL2.WindowBase.Render() in /src/Ryujinx/src/Ryujinx.Headless.SDL2/WindowBase.cs:line 231
```
</details> 

<details>
<summary>Linux x64: Vulkan</summary>

Works fine!
</details> 

<details>
<summary>macOS arm64: Vulkan</summary>

Works fine!
</details>


#### Notes

- How am I supposed to stop emulation?
- I noticed touchscreen input is currently not recognized properly, but this might not be an issue with your changes, as I think I'm encountering the same issues on master right now.

2023-07-02 17:07 UTC, siegmund-heiss-ich commented
>     * How am I supposed to stop emulation?
> 
>     * I noticed touchscreen input is currently not recognized properly, but this might not be an issue with your changes, as I think I'm encountering the same issues on master right now.

With Control + C. I suppose users who use it in CLI would know that. Tbh I don't know which other use cases there would be. Unless you use some game frontend ui thing to control it. And in this case there is hopefully a way to stop emulation directly from this app. 
The use of a shortcut could be implemented here. But I don't think it's necessary.

Isn't touchscreen implemented with ava?

2023-07-06 09:40 UTC, marysaka approved these changes

2023-07-06 09:42 UTC, marysaka approved these changes

2023-07-06 10:10 UTC, merged