[Ryujinx.Common] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5358
Opened 2023-06-24 14:20 UTC by TSRBerry

Base PR: #4670

2023-06-25 00:33 UTC, AcK77 requested changes

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/Collections/IntrusiveRedBlackTree.cs
>                      parent = element;
Bug in the code ?

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/Memory/PartialUnmaps/NativeReaderWriterLock.cs
> +            }
I prefer how it was before (same for other following changes)

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/Memory/StructArrayHelpers.cs
> +#pragma warning disable CS0169, IDE0051 // Remove unused private member
Maybe this pragma should be added at the begin of the file and all others should be removed.

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/Memory/StructArrayHelpers.cs
> +#pragma warning restore CS0169, IDE0051
Maybe this pragma should be added at the end of the file and all others should be removed.

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/Memory/StructArrayHelpers.cs
> +
Method should have an empty line before and after, which isn't the case for old `ArrayX` ones!

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/SystemInfo/LinuxSystemInfo.cs
> +            using StreamReader file = new(filePath);
```suggestion
            using StreamReader file = new(filePath);

```

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/SystemInfo/MacOSSystemInfo.cs
> +#pragma warning disable IDE1006 // Naming rule violation
Maybe we should fix naming then

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/SystemInfo/MacOSSystemInfo.cs
> +#pragma warning disable IDE1006 // Naming rule violation
Maybe we should fix naming then

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/StreamUtils.cs
> +            using MemoryStream stream = MemoryStreamManager.Shared.GetStream();
```suggestion
            using MemoryStream stream = MemoryStreamManager.Shared.GetStream();

```

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/StreamUtils.cs
> +            using MemoryStream stream = MemoryStreamManager.Shared.GetStream();
```suggestion
            using MemoryStream stream = MemoryStreamManager.Shared.GetStream();

```

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/XXHash128.cs
>                  return h128;
```suggestion

                return h128;
```

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/XXHash128.cs
>              return Mul128Fold64(
```suggestion

            return Mul128Fold64(
```

2023-06-25 00:33 UTC, AcK77 commented on src/Ryujinx.Common/XXHash128.cs
>              return acc;
```suggestion

            return acc;
```

2023-06-25 15:11 UTC, TSRBerry commented on src/Ryujinx.Common/Memory/PartialUnmaps/NativeReaderWriterLock.cs
> +            }
@gdkchan also commented on that and we agreed to leave it like that, would you be fine with that as well?

<details>
<summary>Parts of the chat between gdkchan and me</summary>

gdk — 22/04/2023 02:40:
> ```cs
> #pragma warning disable IDE0055 // Disable formatting
>                 while (Interlocked.CompareExchange(ref _interruptAction, action, null) != null) { }
> #pragma warning restore IDE0055
> ```
> why does it need to be disabled here

TSR Berry — 22/04/2023 02:41
> it just moved the {} to the next line

gdk — 22/04/2023 02:41
> like
> ```cs
> { }
> ```
> or
> ```cs
> {
> }
> ```
> ?

TSR Berry — 22/04/2023 02:41
> first one

gdk — 22/04/2023 02:41
> thats weird
> if it was the second one, I think it would be fine

TSR Berry — 22/04/2023 02:42
> yeah, I think it worked better with ;

gdk — 22/04/2023 02:42
> I'd probably do the second one instead of disabling the formatting just for this line

TSR Berry — 22/04/2023 02:42
> ohh okay!
</details>

2023-06-25 16:25 UTC, AcK77 requested changes
Some tailing `,` are probably still missing.

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Configuration/Hid/PlayerIndex.cs
> +        Auto = 10 // Shouldn't be used directly
```suggestion
        Auto = 10, // Shouldn't be used directly
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Configuration/Hid/Key.cs
>          Count
```suggestion
        Count,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Configuration/Hid/ControllerType.cs
> +        System = 1 << 30
```suggestion
        System = 1 << 30,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Configuration/Hid/Controller/StickInputId.cs
>          Count
```suggestion
        Count,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Configuration/AntiAliasing.cs
>          SmaaUltra
```suggestion
        SmaaUltra,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Configuration/HideCursorMode.cs
>          Always
```suggestion
        Always,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Configuration/ScalingFilter.cs
>          Fsr
```suggestion
        Fsr,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Extensions/BinaryReaderExtensions.cs
>              where T : unmanaged
```suggestion
        public static T ReadStruct<T>(this BinaryReader reader) where T : unmanaged
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Extensions/BinaryWriterExtensions.cs
>              where T : unmanaged
```suggestion
        public static void WriteStruct<T>(this BinaryWriter writer, T value) where T : unmanaged
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/GraphicsDriver/NVThreadedOptimization.cs
> +                    GpuSupport = uint.MaxValue
```suggestion
                    GpuSupport = uint.MaxValue,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Logging/LogClass.cs
>          Vic
```suggestion
        Vic,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Logging/Targets/AsyncLogTargetWrapper.cs
> +                IsBackground = true
```suggestion
                IsBackground = true,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Memory/PartialUnmaps/NativeReaderWriterLock.cs
> +            }
I'm fine then

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/JsonHelper.cs
> +                ReadCommentHandling = JsonCommentHandling.Skip
```suggestion
                ReadCommentHandling = JsonCommentHandling.Skip,
```

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/StreamUtils.cs
> +            using MemoryStream stream = MemoryStreamManager.Shared.GetStream();
Not resolved

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/XXHash128.cs
> -            return (ulong)(uint)x * (ulong)(uint)y;
We have to be sure this casting is useless

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.Common/XXHash128.cs
> +
Remove extra empty line

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Audio/AudioRenderer/AudioRendererServer.cs
> +            using (IMemoryOwner<byte> performanceOutputOwner = ByteMemoryPool.RentCleared(performanceOutputSize))
Those can't be inlined ?

2023-06-25 16:25 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/IHOSBinderDriver.cs
> +            using (IMemoryOwner<byte> outputParcelOwner = ByteMemoryPool.RentCleared(replySize))
Can't be inlined as other `using` ?

2023-06-25 17:51 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Audio/AudioRenderer/AudioRendererServer.cs
> +            using (IMemoryOwner<byte> performanceOutputOwner = ByteMemoryPool.RentCleared(performanceOutputSize))
They can, but I'd like to do that in the HLE PR.

2023-06-25 17:51 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/IHOSBinderDriver.cs
> +            using (IMemoryOwner<byte> outputParcelOwner = ByteMemoryPool.RentCleared(replySize))
I'd prefer to do that in the HLE PR.

2023-06-25 17:54 UTC, TSRBerry commented on src/Ryujinx.Common/XXHash128.cs
> -            return (ulong)(uint)x * (ulong)(uint)y;
The IL stayed the same and it still does the conversion to ulong, so I guess it is not needed!

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/Collections/IntervalTree.cs
> +    /// <typeparam name="TK">Key</typeparam>
Maybe they should be called `TKey` and `TValue`, like .NET `Dictionary` type?

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/Collections/IntrusiveRedBlackTree.cs
>                      parent = element;
IMaybe remove the whole if block since it appears to be useless?

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs
> +        private static readonly MotionConfigJsonSerializerContext _serializerContext = new(JsonHelper.GetDefaultSerializerOptions());
Isn't that the opposite of the changes of have been doing on other PRs?

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/GraphicsDriver/NVThreadedOptimization.cs
> -            IntPtr profileHandle;
I think this has double empty line now that was removed.

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/SystemInfo/SystemInfo.cs
> +            if (OperatingSystem.IsLinux())
I'm not sure what happened here. Why is having multiple `if`s better than the `if`, `else if` chain? In any case it doesn't matter too much for me, just curious.

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +            throw new();
Not related to this change, but this looks weird. Is it not throwing an exception?

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/BitUtils.cs
> +#pragma warning disable IDE0055 // Disable formatting
It's not worth to disable formatting just to keep a space after the number IMO.

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/HexUtils.cs
> +        private static readonly char[] _hexChars = "0123456789ABCDEF".ToCharArray();
Same comment as before.

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/JsonHelper.cs
> +        private static readonly JsonNamingPolicy _snakeCasePolicy = new SnakeCaseNamingPolicy();
Same.

2023-06-25 21:47 UTC, gdkchan commented on src/Ryujinx.Common/XXHash128.cs
> +        private static readonly ulong[] _xxh3InitAcc = {
This also looks like the opposite of what is being done elsewhere?

2023-06-25 22:01 UTC, TSRBerry commented on src/Ryujinx.Common/Configuration/Hid/Controller/Motion/JsonMotionConfigControllerConverter.cs
> +        private static readonly MotionConfigJsonSerializerContext _serializerContext = new(JsonHelper.GetDefaultSerializerOptions());
This change has been made after @AcK77 posted his preference for _lowerCamelCase for private static readonly fields.
All the other formatting PRs applied the rule as well when I added it to #4670.

2023-06-25 22:02 UTC, TSRBerry commented on src/Ryujinx.Common/SystemInfo/SystemInfo.cs
> +            if (OperatingSystem.IsLinux())
I think this doesn't have anything to do with dotnet format, but might be Rider thinking the else is not needed here.

I'll revert this one, since I think it was more readable before.

2023-06-25 22:03 UTC, TSRBerry commented on src/Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +            throw new();
This seems to be throwing a generic exception. :thinking:

2023-06-27 15:00 UTC, marysaka commented on src/Ryujinx.Common/SystemInterop/StdErrAdapter.cs
> +            throw new();
Might be throwing Exception here.

2023-06-27 15:04 UTC, marysaka approved these changes

2023-06-27 18:53 UTC, gdkchan approved these changes
lgtm, thanks.

2023-06-28 15:25 UTC, AcK77 approved these changes
Some spaces issues, instead of that it LGTM!

2023-06-28 15:25 UTC, AcK77 commented on src/Ryujinx.Common/Logging/Logger.cs
>                  case LogLevel.Stub      : Stub      = enabled ? new Log(LogLevel.Stub)     : new Log?(); break;
On the line above this one there is an alignment issue we keep it active:

```
case LogLevel.AccessLog : AccessLog = enabled ? new Log(LogLevel.AccessLog): new Log?(); break;
```
to
```
case LogLevel.AccessLog : AccessLog = enabled ? new Log(LogLevel.AccessLog) : new Log?(); break;
```
and so others lines have to be changed too.

2023-06-28 15:25 UTC, AcK77 commented on src/Ryujinx.Common/SystemInfo/MacOSSystemInfo.cs
> +            if (SysctlByName("hw.memsize", ref totalRAM) != 0)  // Bytes
```suggestion
            if (SysctlByName("hw.memsize", ref totalRAM) != 0) // Bytes
```

2023-06-28 16:41 UTC, merged