[Ryujinx.Audio.Backends.OpenAL] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5359
Opened 2023-06-24 14:20 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:33 UTC, AcK77 requested changes

2023-06-24 18:33 UTC, AcK77 commented on src/Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs
> +                    _ => throw new NotImplementedException($"Unsupported channel config {RequestedChannelCount}"),
```suggestion
                    _ => throw new NotImplementedException($"Unsupported channel config {RequestedChannelCount}")
```

2023-06-24 18:33 UTC, AcK77 commented on src/Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs
> +                _ => throw new NotImplementedException($"Unsupported sample format {RequestedSampleFormat}"),
```suggestion
                _ => throw new NotImplementedException($"Unsupported sample format {RequestedSampleFormat}")
```

2023-06-24 18:56 UTC, marysaka commented on src/Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs
> +                    _ => throw new NotImplementedException($"Unsupported channel config {RequestedChannelCount}"),
That's actually cleaner to have the comma and standard in most language (with some formatter)

2023-06-24 18:56 UTC, marysaka approved these changes

2023-06-24 18:58 UTC, AcK77 commented on src/Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs
> +                    _ => throw new NotImplementedException($"Unsupported channel config {RequestedChannelCount}"),
It’s just a personal preference, I’m fine with both

2023-06-24 19:28 UTC, TSRBerry commented on src/Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs
> +                    _ => throw new NotImplementedException($"Unsupported channel config {RequestedChannelCount}"),
I removed the trailing commas everywhere at first, but the diff of that was very large because we are using them a lot actually. That's why I reverted that again.

2023-06-24 19:36 UTC, TSRBerry commented
Dropped the commit containing the workflow, since that was not supposed to be in here.

2023-06-24 19:58 UTC, AcK77 approved these changes

2023-06-24 20:03 UTC, TSRBerry commented
Just did a final check run for this one and all checks pass, so this is good to merge now!

2023-06-24 23:29 UTC, merged

2023-06-25 11:30 UTC, TSRBerry commented
I have to check these again, since dotnet format doesn't like the include option very much.
Hopefully it still doesn't want any changes.

2023-06-25 11:31 UTC, TSRBerry commented on src/Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs
> +                    _ => throw new NotImplementedException($"Unsupported channel config {RequestedChannelCount}"),
Tailing commas might be enforceable soon: https://github.com/dotnet/roslyn/pull/54859

2023-06-25 11:35 UTC, AcK77 commented on src/Ryujinx.Audio.Backends.OpenAL/OpenALHardwareDeviceSession.cs
> +                    _ => throw new NotImplementedException($"Unsupported channel config {RequestedChannelCount}"),
Then tailing commas should be added everywhere it’s needed!