[Ryujinx.Ava] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5361
Opened 2023-06-24 14:22 UTC by TSRBerry

Base PR: #4670

2023-06-24 20:49 UTC, IsaacMarovitz requested changes

2023-06-24 20:49 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/AppHost.cs
> -            ConfigurationState.Instance.Graphics.AspectRatio.Event         += UpdateAspectRatioState;
Imo alignment should be preserved here.

2023-06-24 20:49 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/AppHost.cs
> +            ConfigurationState.Instance.Graphics.AspectRatio.Event -= UpdateAspectRatioState;
Same thing about preserving alignment

2023-06-24 20:49 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/Common/ApplicationHelper.cs
> +            string saveRootPath = Path.Combine(VirtualFileSystem.GetNandPath(), $"user/save/{saveDataId:x16}");
I would double-check if this is correct is this function static?

2023-06-24 20:49 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/Input/AvaloniaMouseDriver.cs
> -            _widget.PointerMoved        += Parent_PointerMovedEvent;
Alignment should be preserved

2023-06-24 20:49 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/Input/AvaloniaMouseDriver.cs
> -            _widget.PointerMoved        -= Parent_PointerMovedEvent;
Alignment should be preserved

2023-06-24 20:49 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Models/SaveModel.cs
> +                var saveRoot = System.IO.Path.Combine(VirtualFileSystem.GetNandPath(), $"user/save/{info.SaveDataId:x16}");
Same question here, as long as this function is static it's okay

2023-06-24 20:49 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Renderer/EmbeddedWindow.cs
> +        static void DestroyMacOS()
This function shouldn't be static

2023-06-24 20:52 UTC, TSRBerry commented on src/Ryujinx.Ava/Common/ApplicationHelper.cs
> +            string saveRootPath = Path.Combine(VirtualFileSystem.GetNandPath(), $"user/save/{saveDataId:x16}");
It's currently not in this PR, but it was made static in another one.

2023-06-25 00:17 UTC, AcK77 requested changes
There is still strange things about alignment...

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
> +                PrimaryButtonCommand = MiniCommand.Create(() =>
Sometime the alignment is removed, sometimes not. It should be removed everywhere.
The `,` isn't here on the last field, when it is on the last enum value sometime and on the last `switch` sometimes too. We should be consistent and add it in any cases.

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Helpers/Win32NativeInterop.cs
> +        [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
I'd prefer to get this removed.

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/SaveModel.cs
> +                static long GetDirectorySize(string path)
```suggestion

                static long GetDirectorySize(string path)
```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/SaveModel.cs
>                  long total_size = GetDirectorySize(saveRoot);
```suggestion
                long totalSize = GetDirectorySize(saveRoot);
```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AmiiboWindowViewModel.cs
> +                using MemoryStream memoryStream = new(amiiboPreviewBytes);
```suggestion
                using MemoryStream memoryStream = new(amiiboPreviewBytes);

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AmiiboWindowViewModel.cs
> +            using MemoryStream memoryStream = new(_amiiboLogoBytes);
```suggestion
            using MemoryStream memoryStream = new(_amiiboLogoBytes);

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AvatarProfileViewModel.cs
> +            using MemoryStream streamJpg = new();
```suggestion
            using MemoryStream streamJpg = new();

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AvatarProfileViewModel.cs
> +                    using IStorage ncaFileStream = new LocalStorage(avatarPath, FileAccess.Read, FileMode.Open);
```suggestion
                    using IStorage ncaFileStream = new LocalStorage(avatarPath, FileAccess.Read, FileMode.Open);

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AvatarProfileViewModel.cs
> +                            using MemoryStream streamPng = new();
```suggestion
                            using MemoryStream streamPng = new();

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AvatarProfileViewModel.cs
> +            using BinaryReader reader = new(stream);
```suggestion
            using BinaryReader reader = new(stream);

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AvatarProfileViewModel.cs
> +                                .ThrowIfFailure();
Alignment is a bit strange here

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/AvatarProfileViewModel.cs
> +                            item.FullPath.Contains("szs"))
```suggestion
                        if (item.Type == DirectoryEntryType.File && item.FullPath.Contains("chara") && item.FullPath.Contains("szs"))
```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/ControllerInputViewModel.cs
>          public ControllerInputViewModel(UserControl owner) : this()
```suggestion
        public ControllerInputViewModel() : this()
```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/ControllerInputViewModel.cs
> +                _mainWindow.ViewModel.AppHost?.NpadManager.BlockInputUpdates();
```suggestion

                _mainWindow.ViewModel.AppHost?.NpadManager.BlockInputUpdates();
```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +        private readonly VirtualFileSystem                      _virtualFileSystem;
Alignment issue

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
>          public readonly string     _titleUpdateJsonPath;
```suggestion
        public readonly string _titleUpdateJsonPath;
```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +        private ulong TitleId { get; }
```suggestion
        private VirtualFileSystem VirtualFileSystem { get; }
        private ulong TitleId { get; }
```

private > `_camelCase`

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/UserFirmwareAvatarSelectorViewModel.cs
> +                using IStorage ncaFileStream = new LocalStorage(avatarPath, FileAccess.Read, FileMode.Open);
```suggestion
                using IStorage ncaFileStream = new LocalStorage(avatarPath, FileAccess.Read, FileMode.Open);

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/UserFirmwareAvatarSelectorViewModel.cs
> +                        using MemoryStream streamPng = new();
```suggestion
                        using MemoryStream stream = new();
                        using MemoryStream streamPng = new();

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/UserFirmwareAvatarSelectorViewModel.cs
> +            using BinaryReader reader = new(stream);
```suggestion
            using BinaryReader reader = new(stream);

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/UserSaveManagerViewModel.cs
> +                                        : SortExpressionComparer<SaveModel>.Descending(save => save.Size),
Alignment issue

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/User/UserProfileImageSelectorView.axaml.cs
> +            using Image image = Image.Load(buffer);
```suggestion
            using Image image = Image.Load(buffer);

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/User/UserProfileImageSelectorView.axaml.cs
> +            using MemoryStream streamJpg = new();
```suggestion
            using MemoryStream streamJpg = new();

```

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/CheatWindow.axaml.cs
> +            string[] enabled = System.Array.Empty<string>();
`using System;` ?

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ContentDialogOverlayWindow.axaml.cs
> +#if DEBUG
Strange ?

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/IconColorPicker.cs
> -
Why is this removed, even if it's not used maybe it could be nice to keep them ?

2023-06-25 00:17 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> +                WindowStartupLocation = WindowStartupLocation.CenterScreen;
```
            if (CheckScreenBounds(SavedPoint))
            {
                Position = SavedPoint;
            }
            else
            {
                WindowStartupLocation = WindowStartupLocation.CenterScreen;
            }
```

2023-06-25 11:56 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> -            ConfigurationState.Instance.Graphics.AspectRatio.Event         += UpdateAspectRatioState;
@Ryujinx/developers what do you think?

2023-06-25 11:59 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Helpers/Win32NativeInterop.cs
> +        [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
I'm not sure how

2023-06-25 12:01 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +        private ulong TitleId { get; }
Properties are not fields, so currently the default rule PascalCase applies: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules#default-naming-styles

Should this still be changed?

2023-06-25 12:04 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
> +                PrimaryButtonCommand = MiniCommand.Create(() =>
When this gets merged we can enforce that with editorconfig as well: https://github.com/dotnet/roslyn/pull/54859

2023-06-25 13:12 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Windows/ContentDialogOverlayWindow.axaml.cs
> +#if DEBUG
It's because of the constructor, see below.

2023-06-25 13:13 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Applet/ErrorAppletWindow.axaml.cs
> +#if DEBUG
Also because of the constructor below.

2023-06-25 13:16 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
> +            if (parent is { IsActive: true } and MainWindow window && window.ViewModel.IsGameRunning)
@gdkchan is this change fine for you? This doesn't assume parent is of type `MainWindow`, instead the `and MainWindow window` part here checks if `parent` is `MainWindow` and only continues to the next check if that's true.

2023-06-25 21:32 UTC, TSRBerry commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +            using (Stream remoteFileStream = response.Content.ReadAsStreamAsync().Result)
I think I commented the same on #5395: We could use using declarations here, but they aren't needed for the lifetime of the whole method. Do you prefer if I use using declarations here anyway?

2023-06-26 14:38 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Helpers/Win32NativeInterop.cs
> +        [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
I removed them where I think it makes sense to do so, but for this one I don't think we should remove it.

2023-06-26 20:27 UTC, gdkchan commented on src/Ryujinx.Ava/AppHost.cs
> -            ConfigurationState.Instance.Graphics.AspectRatio.Event         += UpdateAspectRatioState;
I don't think it's necessary.

2023-06-26 20:29 UTC, gdkchan commented on src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
> +            if (parent is { IsActive: true } and MainWindow window && window.ViewModel.IsGameRunning)
I think Ac_K tried this change and it didn't work properly. I think if you change it you should make sure it's still working correctly. Also I'm not a fan of `and` expressions, personally I prefer `&&` etc.

2023-06-26 22:45 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Helpers/ContentDialogHelper.cs
> +            if (parent is { IsActive: true } and MainWindow window && window.ViewModel.IsGameRunning)
![image](https://github.com/Ryujinx/Ryujinx/assets/20988865/1f099780-3b27-442d-b549-245d904335e6)
works fine here!

2023-06-27 14:46 UTC, marysaka commented on src/Ryujinx.Ava/AppHost.cs
> -            ConfigurationState.Instance.Graphics.AspectRatio.Event         += UpdateAspectRatioState;
I don't care about alignment too here

2023-07-01 23:18 UTC, AcK77 requested changes

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +        public bool EnableMacroHle { get; set; }
```suggestion
        public bool EnableMacroHle { get; set; }
```
```suggestion
        public bool EnableMacroHLE { get; set; }
```

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/SettingsViewModel.cs
> +        public bool IsSdl2Enabled { get; set; }
```suggestion
        public bool IsSDL2Enabled { get; set; }
```

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/Settings/SettingsAudioView.axaml
> +                        <ComboBoxItem IsEnabled="{Binding IsSdl2Enabled}">
```suggestion
                        <ComboBoxItem IsEnabled="{Binding IsSdl2Enabled}">
```
```suggestion
                        <ComboBoxItem IsEnabled="{Binding IsSDL2Enabled}">
```

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/Settings/SettingsCPUView.axaml.cs
> +        public SettingsCpuView()
```suggestion
        public SettingsCPUView()
```

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/Settings/SettingsCPUView.axaml
> +    x:Class="Ryujinx.Ava.UI.Views.Settings.SettingsCpuView"
```suggestion
    x:Class="Ryujinx.Ava.UI.Views.Settings.SettingsCPUView"
```

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/Settings/SettingsGraphicsView.axaml
> +                        <CheckBox IsChecked="{Binding EnableMacroHle}"
```suggestion
                        <CheckBox IsChecked="{Binding EnableMacroHLE}"
```

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/ContentDialogOverlayWindow.axaml.cs
> +#if DEBUG
I know but it's still strange to get this (in another file aswell), I'd prefer to find another way :/

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/DownloadableContentManagerWindow.axaml
> +                                        Click="RemoveDlc">
```suggestion
                                        Click="RemoveDLC">
```

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/DownloadableContentManagerWindow.axaml.cs
> +        private void RemoveDlc(object sender, RoutedEventArgs e)
```suggestion
        private void RemoveDLC(object sender, RoutedEventArgs e)
```

or `RemoveDownloadableContent`

2023-07-01 23:18 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/SettingsWindow.axaml
> +            ReverseOrder="{Binding IsMacOs}">
https://learn.microsoft.com/en-us/dotnet/api/system.operatingsystem.ismacos?view=net-7.0#system-operatingsystem-ismacos

2023-07-02 00:12 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Windows/ContentDialogOverlayWindow.axaml.cs
> +#if DEBUG
What do you suggest?

2023-07-06 15:20 UTC, AcK77 approved these changes

2023-07-07 20:39 UTC, marysaka approved these changes

2023-07-07 21:03 UTC, merged