[Ryujinx.Audio] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5362
Opened 2023-06-24 14:22 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:55 UTC, marysaka approved these changes
lgtm, apart from build errors :+1:

2023-06-26 05:25 UTC, marysaka approved these changes

2023-07-01 21:13 UTC, AcK77 requested changes
There are a lot of missing tailing `,`

2023-07-01 21:13 UTC, AcK77 commented on src/Ryujinx.Audio/Renderer/Server/CommandGenerator.cs
> +                };
```suggestion
                };

```

2023-07-01 21:13 UTC, AcK77 commented on src/Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion3.cs
> +        protected uint BufferCount;
Changes should be reverted

2023-07-01 21:13 UTC, AcK77 commented on src/Ryujinx.Audio/Renderer/Server/Performance/PerformanceManager.cs
> +                                                                                                                                                              ref parameter),
`parameter` should be on the same line

2023-07-01 21:13 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Audio/AudioInManager.cs
> +            return AudioInManagerImpl.ListAudioIns(filtered);
This should be done per instance and not static. I think the changes were made because `AudioInManagerImpl` don't access to classes fields, which is kind of "normal" since it's not implemented. I think we should revert this change here (and other one related too).

2023-07-01 21:13 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Audio/AudioOutManager.cs
> +            return AudioOutManagerImpl.ListAudioOuts();
This should be done per instance and not static.

2023-07-01 21:13 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Audio/AudioRenderer/AudioDevice.cs
> +                device = VirtualDeviceSessionRegistry.DefaultDevice;
This change is strange too.

2023-07-01 21:13 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Audio/AudioRenderer/AudioDevice.cs
> +                device = VirtualDeviceSessionRegistry.DefaultDevice;
This change is strange too.

2023-07-01 22:07 UTC, TSRBerry commented on src/Ryujinx.Audio/Renderer/Server/AudioRenderSystem.cs
> -                        continue;
It's not exactly needed, but I'll revert this change.

2023-07-01 22:15 UTC, TSRBerry commented on src/Ryujinx.Audio/Renderer/Server/CommandProcessingTimeEstimatorVersion3.cs
> +        protected uint BufferCount;
That would be inconsistent with the rest of the codebase.

2023-07-01 23:27 UTC, AcK77 approved these changes

2023-07-01 23:27 UTC, merged