[Ryujinx.Audio.Backends.SDL2] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5364
Opened 2023-06-24 14:23 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:31 UTC, AcK77 requested changes

2023-06-24 18:31 UTC, AcK77 commented on src/Ryujinx.Audio.Backends.SDL2/SDL2HardwareDeviceDriver.cs
>                      $"SDL2 open audio device initialization failed with error \"{SDL_GetError()}\"");
```suggestion
                Logger.Error?.Print(LogClass.Application, $"SDL2 open audio device initialization failed with error \"{SDL_GetError()}\"");
```

2023-06-24 19:24 UTC, marysaka approved these changes

2023-06-25 19:51 UTC, AcK77 approved these changes

2023-06-25 20:51 UTC, merged