[Ryujinx.Cpu] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5365
Opened 2023-06-24 14:24 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:29 UTC, AcK77 requested changes
Could be nice to get the namespace issue fixed too.

2023-06-24 18:29 UTC, AcK77 commented on src/Ryujinx.Cpu/AddressSpace.cs
>          private const ulong PageSize = 0x1000;
If it's not used, maybe we should remove it

2023-06-24 18:29 UTC, AcK77 commented on src/Ryujinx.Cpu/AddressSpace.cs
>              ulong sizeAligned = endAddressAligned - vaAligned;
Maybe we should do something with it, or remove the assignment.

2023-06-24 18:29 UTC, AcK77 commented on src/Ryujinx.Cpu/AddressSpace.cs
>              ulong alignedSize = endAddressAligned - vaAligned;
Maybe we should do something with it, or remove the assignment.

2023-06-24 18:29 UTC, AcK77 commented on src/Ryujinx.Cpu/AppleHv/HvApi.cs
> +#pragma warning disable IDE1006 // Naming rule violation
Maybe we should rename the structs then

2023-06-24 18:29 UTC, AcK77 commented on src/Ryujinx.Cpu/MemoryEhMeilleure.cs
> +            _trackingEvent = tracking.VirtualMemoryEvent;
Strange change, is `VirtualMemoryEvent` already a delegate ?

2023-06-24 18:29 UTC, AcK77 commented on src/Ryujinx.Cpu/MemoryHelper.cs
> +            using RecyclableMemoryStream ms = MemoryStreamManager.Shared.GetStream();
```suggestion
            using RecyclableMemoryStream ms = MemoryStreamManager.Shared.GetStream();

```

2023-06-24 20:37 UTC, TSRBerry commented
I probably need to address namespaces with #4670 anyway

2023-06-24 21:46 UTC, TSRBerry commented on src/Ryujinx.Cpu/MemoryEhMeilleure.cs
> +            _trackingEvent = tracking.VirtualMemoryEvent;
Yes!

2023-06-25 00:06 UTC, TSRBerry commented
Checks are passing here as well, marking as ready!

2023-06-25 20:36 UTC, marysaka approved these changes

2023-06-28 16:41 UTC, AcK77 commented on src/Ryujinx.Cpu/AddressSpace.cs
>              ulong sizeAligned = endAddressAligned - vaAligned;
Still unresolved

2023-06-28 16:41 UTC, AcK77 commented on src/Ryujinx.Cpu/AddressSpace.cs
>              ulong alignedSize = endAddressAligned - vaAligned;
Still unresolved

2023-06-28 16:41 UTC, AcK77 commented on src/Ryujinx.Cpu/AppleHv/HvApi.cs
>          [LibraryImport(LibraryName, SetLastError = true)]
Maybe we could use `EntryPoint` args to map the real name `EntryPoint = "hv_vm_get_max_vcpu_count"` and then use a consistent name like `GetMaxVCPUCount`.
Same comment is available for other `LibraryImport`.

2023-06-28 17:39 UTC, TSRBerry commented on src/Ryujinx.Cpu/AddressSpace.cs
> +            GC.SuppressFinalize(this);
Do we do that in a separate PR later like with the other PR?

2023-06-28 17:41 UTC, gdkchan commented on src/Ryujinx.Cpu/AddressSpace.cs
> +            GC.SuppressFinalize(this);
Yea.

2023-06-28 17:46 UTC, gdkchan approved these changes
lgtm, thanks.

2023-07-01 02:17 UTC, AcK77 approved these changes

2023-07-01 02:18 UTC, merged