[Ryujinx.Graphics.Nvdec.Vp9] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5371
Opened 2023-06-24 14:26 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:21 UTC, AcK77 requested changes

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +            if (Surface.HighBd)
?

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +            if (Surface.HighBd)
?

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +            if (Surface.HighBd)
?

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +            if (Surface.HighBd)
?

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
>              }
```suggestion
            }

```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
> +#pragma warning disable IDE1006 // Naming rule violation
Then we should rename the method and remove pragma

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/InvTxfm.cs
>                  return;
```suggestion

                return;
```

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
> +#pragma warning disable IDE1006 // Naming rule violation
Then we should rename the method and remove pragma

2023-06-24 18:21 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/ReconIntra.cs
> +            if (Surface.HighBd)
?

2023-06-25 19:18 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +            if (Surface.HighBd)
That happened because `HighBd` was marked static. But that shouldn't be correct, so I'll change that!

2023-06-25 19:49 UTC, AcK77 requested changes

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Idct.cs
> +            new(HighbdIadst16, HighbdIadst16), // ADST_ADST = 3
```suggestion
            new(HighbdIdct16, HighbdIdct16),   // DCT_DCT  = 0
            new(HighbdIadst16, HighbdIdct16),  // ADST_DCT = 1
            new(HighbdIdct16, HighbdIadst16),  // DCT_ADST = 2
            new(HighbdIadst16, HighbdIadst16), // ADST_ADST = 3
```

Sometime comments are align, sometime not.

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0xffffffffffffffffUL,  // TX_4X4
```suggestion
            0xffffffffffffffffUL, // TX_4X4
```

Same for other comments

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0xffffffffffffffffUL,  // TX_4X4
```suggestion
            0xffffffffffffffffUL, // TX_4X4
```
Same for other comments

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0x0000000000000001UL,  // BLOCK_4X4,
```suggestion
            0x0000000000000001UL, // BLOCK_4X4,
```
Same for other comments

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0x0000000000000001UL,  // BLOCK_4X4
```suggestion
            0x0000000000000001UL, // BLOCK_4X4
```
Same for other comments

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0x0000000000000001UL,  // BLOCK_4X4
```suggestion
            0x0000000000000001UL, // BLOCK_4X4
```
Same for other comments

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0xffff,  // TX_4X4
```suggestion
            0xffff, // TX_4X4
```
Same for other comments

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0xffff,  // TX_4X4
```suggestion
            0xffff, // TX_4X4
```
Same for other comments

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/LoopFilter.cs
>              0x0001,  // BLOCK_4X4,
```suggestion
            0x0001, // BLOCK_4X4,
```
Same for other comments (in the whole file)

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
>              TxSize.Tx4x4,    // ONLY_4X4
Comment issue here too (and in other places in the file)

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
>          /* Array indices are identical to previously-existing INTRAMODECONTEXTNODES. */
```suggestion
        // Array indices are identical to previously-existing INTRAMODECONTEXTNODES.
```

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/ReconInter.cs
>              return res;
Why not `return new Mv() ...` ?

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/ReconInter.cs
>              return res;
Why not `return new Mv() ...` ?

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/ReconIntra.cs
>              TxType.DctDct,    // DC
Same comment issue

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/ScaleFactors.cs
>          public int YScaleFP;  // Vertical fixed point scale factor
```suggestion
        public int XScaleFP; // Horizontal fixed point scale factor
        public int YScaleFP; // Vertical fixed point scale factor
```

2023-06-25 19:49 UTC, AcK77 commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/SegLvlFeatures.cs
> +        SegLvlMax = 4, // Number of features supported
Comment issue

2023-06-25 20:05 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/ReconInter.cs
>              return res;
No idea, I'll change that!

2023-06-27 05:09 UTC, angelohelloworld commented
i can fix that

2023-06-27 17:11 UTC, TSRBerry commented
What exactly do you want to fix here? There is nothing that needs to be fixed here anymore.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Constants.cs
> +        public const int ZeroToken = 0;  // 0     Extra Bits 0+0
Maybe it's worth to remove the weird spacing on the comment too?

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +
nit: No need for the empty line separating the return from the assert. It looks a bit odd when the other cases with break don't have htat.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +
Same comments as before applies here.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +                            Debug.Assert(false, "Invalid transform size");
This could use `Debug.Fail` rather than `Debug.Assert` with constant condition.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/Prob.cs
> +        private static readonly uint[] _countToUpdateFactor = {
I think I already commented this elsewhere, but is the change where the `{` is moved to the same line expected? Usually the `{` is on a separate line, so it looks a bit odd for me.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/Prob.cs
> +            uint count = Math.Min(den, ModeMvCountSat);
This kind of change is a little bit odd. Why is moving the code out of the else block better?

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
> +            {  // PARTITION_NONE
Why does it have two whitespaces before the `//` now rather than one?

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
>              -(sbyte)PredictionMode.D45Pred,  14,                                /* 6 = D45_NODE */
It seems the comments here are misaligned, maybe it's worth addressing that while you're at it.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
> +            new Position[] { new( -1, 0 ),
maybe worth removing the weird spacing on the `new()`, not sure which purpose it has.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/MacroBlockD.cs
> -            else if (leftType == Constants.SwitchableFilters)
This change is also a bit odd, preferring separate `if` blocks over a `if`/`else if`` chain. Not sure which benefit it brings.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/PredictionMode.cs
> +        DcPred = 0,  // Average of above and left pixels
The alignment was removed, but there's still double spacing here. Not sure if that is intentional.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/SegLvlFeatures.cs
> +        SegLvlAltQ = 0,  // Use alternate Quantizer ....
This one also has double spacing.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
> +        public readonly bool HighBd => false;
Maybe making this an auto-property and assigning it to false on the constructor is better than silencing the warning here. I added this to make easier to implement the high bit-depth modes, but the Switch does not support it so it hard-coded to false right now.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/PredictionMode.cs
> +        DcPred = 0,  // Average of above and left pixels
After looking at more code, I noticed that it is apparently using the double spacing everywhere, From what I recall we use a single space for comments at the end of a line of code in the project.

2023-06-27 18:49 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/DecodeFrame.cs
> +                            Debug.Assert(false, "Invalid transform size");
There are multiple places that does this, so probably better to address it on a separate change.

2023-06-27 19:13 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/Prob.cs
> +        private static readonly uint[] _countToUpdateFactor = {
It only moves it to the same line if an array initializer is used.
I suppose this is preferred because there is nothing else before the newline, so it might be confusing as people could think there is something missing there. But that's just my guess.

2023-06-27 19:13 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
> +            {  // PARTITION_NONE
It should have been one, will fix that.

2023-06-27 19:36 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Luts.cs
> +            new Position[] { new( -1, 0 ),
Should be better now!

2023-06-27 19:40 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/MacroBlockD.cs
> -            else if (leftType == Constants.SwitchableFilters)
It doesn't bring any, these changes were made by Rider when I fixed something else. I thought I reverted all of them, but I forgot some.

2023-06-27 19:44 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Dsp/Prob.cs
> +            uint count = Math.Min(den, ModeMvCountSat);
It's not, this was not done on purpose.

2023-06-27 19:46 UTC, gdkchan approved these changes
lgtm, thanks.

2023-06-27 19:46 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
I think method local constant names start with upper case character. Not 100% sure.

2023-06-27 19:49 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
Have we used them somewhere else before? :o
I'm not sure about any convention for that, I'll try to figure that out.

2023-06-27 19:50 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
Yes, it's used in a few other places.

2023-06-27 19:51 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
But TBH I usually move them out of the method and make them class scoped just because I don't know how to name them.

2023-06-27 19:57 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
Doing a case sensitive regex search with the pattern `^\s*const` reveals several instances. It is not consistent across the code base, some start with lower case character like local variables, others start with upper case ones.
Upper case example: https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.Graphics.Gpu/Engine/Threed/StateUpdater.cs#L583
Lower case example: https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.Audio/Renderer/Dsp/Command/DelayCommand.cs#L82

2023-06-27 20:05 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
dotnet runtime uses PascalCase for these and the [regular naming conventions](https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions#naming-conventions) don't mention them.

Let's create a rule for that. Do you prefer them to be camelCase or PascalCase?

2023-06-27 20:06 UTC, gdkchan commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
I would prefer to just follow what the .NET runtime does and use PascalCase.

2023-06-27 20:09 UTC, TSRBerry commented on src/Ryujinx.Graphics.Nvdec.Vp9/Types/Surface.cs
>              const int border = 32;
I'll open a new PR to apply this to all the projects that we already merged the formatting PRs for and apply them here as well!

2023-06-28 07:04 UTC, marysaka approved these changes

2023-06-28 07:26 UTC, merged