[Ryujinx.Graphics.OpenGL] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5372
Opened 2023-06-24 14:26 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:15 UTC, AcK77 requested changes

2023-06-24 18:15 UTC, AcK77 commented on src/Ryujinx.Graphics.OpenGL/BackgroundContextWorker.cs
> +        private readonly ObjectPool<ManualResetEventSlim> _invokePool;
Should be a namespace issue

2023-06-24 18:15 UTC, AcK77 commented on src/Ryujinx.Graphics.OpenGL/HwCapabilities.cs
> +#pragma warning disable IDE0051, IDE0055 // Disable formatting
Useless

2023-06-24 18:15 UTC, AcK77 commented on src/Ryujinx.Graphics.OpenGL/Pipeline.cs
Remove extra empty line

2023-06-24 18:15 UTC, AcK77 commented on src/Ryujinx.Graphics.OpenGL/Queries/CounterQueue.cs
> +                _ => QueryTarget.SamplesPassed,
```suggestion
                _ => QueryTarget.SamplesPassed
```

2023-06-25 14:09 UTC, TSRBerry commented on src/Ryujinx.Graphics.OpenGL/BackgroundContextWorker.cs
> +        private readonly ObjectPool<ManualResetEventSlim> _invokePool;
What do you mean?

2023-06-25 16:07 UTC, AcK77 commented on src/Ryujinx.Graphics.OpenGL/BackgroundContextWorker.cs
> +        private readonly ObjectPool<ManualResetEventSlim> _invokePool;
There was an error about `ObjectPool` which isn't here anymore

2023-06-25 16:07 UTC, AcK77 commented on src/Ryujinx.Graphics.OpenGL/Sync.cs
> +        private static ClientWaitSyncFlags SyncFlags => HwCapabilities.RequiresSyncFlush ? ClientWaitSyncFlags.None : ClientWaitSyncFlags.SyncFlushCommandsBit;
```suggestion
        private static ClientWaitSyncFlags _syncFlags => HwCapabilities.RequiresSyncFlush ? ClientWaitSyncFlags.None : ClientWaitSyncFlags.SyncFlushCommandsBit;
```

2023-06-25 17:57 UTC, TSRBerry commented on src/Ryujinx.Graphics.OpenGL/Sync.cs
> +        private static ClientWaitSyncFlags SyncFlags => HwCapabilities.RequiresSyncFlush ? ClientWaitSyncFlags.None : ClientWaitSyncFlags.SyncFlushCommandsBit;
This is now a property so the default naming style applies again (https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules#default-naming-styles). Should we still change it?

2023-06-27 14:57 UTC, marysaka approved these changes

2023-06-27 20:16 UTC, gdkchan approved these changes
lgtm, thanks.

2023-06-27 20:16 UTC, gdkchan commented on src/Ryujinx.Graphics.OpenGL/Sync.cs
> +        private static ClientWaitSyncFlags SyncFlags => HwCapabilities.RequiresSyncFlush ? ClientWaitSyncFlags.None : ClientWaitSyncFlags.SyncFlushCommandsBit;
Is an answer for that question still pending? It seems it was already changed on other PRs.

2023-06-27 20:18 UTC, TSRBerry commented on src/Ryujinx.Graphics.OpenGL/Sync.cs
> +        private static ClientWaitSyncFlags SyncFlags => HwCapabilities.RequiresSyncFlush ? ClientWaitSyncFlags.None : ClientWaitSyncFlags.SyncFlushCommandsBit;
Some final confirmation would be nice! :sweat_smile:

2023-06-27 20:39 UTC, gdkchan commented on src/Ryujinx.Graphics.OpenGL/Sync.cs
> +        private static ClientWaitSyncFlags SyncFlags => HwCapabilities.RequiresSyncFlush ? ClientWaitSyncFlags.None : ClientWaitSyncFlags.SyncFlushCommandsBit;
I would prefer to follow the default naming guidelines. If it says it's PascalCase, then I think we should use PascalCase. The link you mentioned doesn't mention instance vs static members, so I assume it applies to both.

2023-06-28 15:44 UTC, AcK77 approved these changes

2023-06-28 16:10 UTC, merged