[Ryujinx.Graphics.Vic] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5374
Opened 2023-06-24 14:27 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:10 UTC, AcK77 requested changes

2023-06-24 18:10 UTC, AcK77 commented on src/Ryujinx.Graphics.Vic/Image/SurfaceCommon.cs
> +﻿using Ryujinx.Common.Utilities;
Same issue as https://github.com/Ryujinx/Ryujinx/pull/5375

2023-06-24 18:10 UTC, AcK77 commented on src/Ryujinx.Graphics.Vic/Types/FrameFormat.cs
> +    [SuppressMessage("Style", "IDE0066: Use switch expression")]
Where ?

2023-06-25 00:29 UTC, TSRBerry commented on src/Ryujinx.Graphics.Vic/Types/FrameFormat.cs
> +    [SuppressMessage("Style", "IDE0066: Use switch expression")]
Ah this rule was already disabled. I must have missed this one.

2023-06-25 16:03 UTC, AcK77 approved these changes

2023-06-25 16:05 UTC, marysaka approved these changes

2023-06-25 16:37 UTC, merged