[Ryujinx.Graphics.Texture] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5375
Opened 2023-06-24 14:28 UTC by TSRBerry

Base PR: #4670

2023-06-24 18:08 UTC, AcK77 requested changes

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +                    }
```suggestion
                    }

```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +                    if (!(c[i]))
```suggestion

                    if (!(c[i]))
```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +            unsafe
```suggestion

            unsafe
```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +            unsafe
```suggestion

            unsafe
```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +            }
```suggestion
            }

```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +            unsafe
```suggestion

            unsafe
```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +            }
```suggestion
            }

```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +            unsafe
```suggestion

            unsafe
```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +            { _ = &integerEncodedSequence; } // Skip struct initialization
```suggestion

            unsafe
            {
                // Skip struct initialization
                _ = &integerEncodedSequence; 
            }

```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
>                  int a = 0, b = 0, c = 0, d = 0;
We should remove the assignments then

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/BitStream128.cs
> +#pragma warning disable IDE0044 // Make field readonly
The field can't be marked as readonly ?

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/Bits.cs
> +            }
```suggestion
            }

```

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/BCnDecoder.cs
> +using Ryujinx.Common.Utilities;
The error above are because `BinUtils` have a wrong namespace `Ryujinx.Common` instead of `Ryujinx.Common.Utilities`

2023-06-24 18:08 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/BCnEncoder.cs
>                  int rgba8Size = width * height * depth * layers * 4;
Can be removed I guess

2023-06-25 13:54 UTC, TSRBerry commented on src/Ryujinx.Graphics.Texture/Astc/BitStream128.cs
> +#pragma warning disable IDE0044 // Make field readonly
Yes it will break ASTC if we mark it as readonly.

2023-06-25 16:12 UTC, AcK77 requested changes

2023-06-25 16:12 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/AstcDecoder.cs
> +                int a = Bits.Replicate(bitValue & 1, 1, 9);
```suggestion
                int a = Bits.Replicate(bitValue & 1, 1, 9);

```

2023-06-25 16:12 UTC, AcK77 commented on src/Ryujinx.Graphics.Texture/Astc/BitStream128.cs
> +#pragma warning disable IDE0044 // Make field readonly
Fine then

2023-06-27 19:28 UTC, gdkchan approved these changes
lgtm, thanks.

2023-06-28 16:46 UTC, merged