[Ryujinx.Horizon.Kernel.Generators] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5376
Opened 2023-06-24 14:28 UTC by TSRBerry

Base PR: #4670

2023-06-24 17:59 UTC, AcK77 commented
I think there is something wrong in this PR

2023-06-24 19:26 UTC, TSRBerry commented
Fixed!

2023-06-24 20:51 UTC, IsaacMarovitz commented
Labels need to fixed on this pr

2023-06-25 17:58 UTC, TSRBerry commented
They will be in a few minutes.

2023-06-25 18:36 UTC, AcK77 requested changes

2023-06-25 18:36 UTC, AcK77 commented on src/Ryujinx.Horizon.Kernel.Generators/SyscallGenerator.cs
>                          into numericLiteral
Wrong alignment

2023-06-25 18:50 UTC, TSRBerry commented on src/Ryujinx.Horizon.Kernel.Generators/SyscallGenerator.cs
>                          into numericLiteral
![image](https://github.com/Ryujinx/Ryujinx/assets/20988865/f3077f9b-521b-4c34-84de-2bcc9e497ab3)
It looks right to me, what's wrong?

2023-06-26 01:58 UTC, AcK77 commented on src/Ryujinx.Horizon.Kernel.Generators/SyscallGenerator.cs
>                          into numericLiteral
`into` shouldn’t be aligned with from/where/select?
Maybe `in` should be in a new line too.

2023-06-26 10:03 UTC, TSRBerry commented on src/Ryujinx.Horizon.Kernel.Generators/SyscallGenerator.cs
>                          into numericLiteral
Ohh yeah that makes sense! I aligned into with the rest of them, but left the `in` in the first line, since I think it's easier to read this way.

2023-06-27 14:51 UTC, marysaka approved these changes

2023-06-27 23:27 UTC, AcK77 approved these changes

2023-06-27 23:27 UTC, merged