[Ryujinx.Headless.SDL2 Address dotnet-format issues
Ryujinx/Ryujinx pull request #5379
Opened 2023-06-24 14:29 UTC by TSRBerry

Base PR: #4670

2023-06-24 17:36 UTC, AcK77 requested changes
Some errors have to be fixed too.

2023-06-24 17:36 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/Program.cs
> +#pragma warning disable IDE0055 // Disable formatting
Should be removed, and code have to be formatted for consistencies

2023-06-24 17:36 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/Program.cs
> +                _ => throw new ArgumentException($"Unknown Progress Handler type {typeof(T)}"),
```suggestion
                _ => throw new ArgumentException($"Unknown Progress Handler type {typeof(T)}")
```

2023-06-24 17:36 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/Program.cs
>                                                                    _accountManager,
Formatting is wrong

2023-06-24 17:36 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/SDL2MouseDriver.cs
> +            _ = SDL_GetMouseState(out int posX, out int posY);
There are check on all other `SDL_` method, this one should get one too.

2023-06-24 17:36 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
>          private const SDL_WindowFlags DefaultFlags = SDL_WindowFlags.SDL_WINDOW_ALLOW_HIGHDPI | SDL_WindowFlags.SDL_WINDOW_RESIZABLE | SDL_WindowFlags.SDL_WINDOW_INPUT_FOCUS | SDL_WindowFlags.SDL_WIN
`protected const` vars alignment is off

2023-06-25 13:26 UTC, TSRBerry commented on src/Ryujinx.Headless.SDL2/SDL2MouseDriver.cs
> +            _ = SDL_GetMouseState(out int posX, out int posY);
It returns a bitmask of the current button state, not sure if that's useful in any way here.

2023-06-25 13:27 UTC, TSRBerry commented
Since all checks are passing, I'll mark it as ready!

2023-06-25 14:55 UTC, marysaka approved these changes

2023-06-25 16:01 UTC, AcK77 requested changes

2023-06-25 16:01 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/SDL2MouseDriver.cs
> +            _ = SDL_GetMouseState(out int posX, out int posY);
True! Sorry I haven't checked :D

2023-06-25 16:01 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +        private void NvStutterWorkaround()
```suggestion
        private void NVStutterWorkaround()
```

Same with NV

2023-06-28 16:54 UTC, AcK77 approved these changes

2023-06-28 17:03 UTC, merged