[Ryujinx.HLE] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5380
Opened 2023-06-24 14:30 UTC by TSRBerry

Base PR: #4670

2023-07-02 02:41 UTC, AcK77 requested changes
Reviewed around 60% for the PR for now.
A lot of IPC method are now changed into `static` which lead to some other change in services. I don't think it's safe to assume everything could works using `static` since we use a bunch of reflection in services. Additionally to that is doesn't looks good for consistency and do the services code less readable.

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/MemoryConfiguration.cs
> +#pragma warning disable IDE0055 // Disable formatting
Isn't better to put that around the whole class instead ?

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Executables/NroExecutable.cs
> +#pragma warning disable IDE0055 // Disable formatting
Formatting isn't needed here

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Executables/NroExecutable.cs
> +#pragma warning disable IDE0055 // Disable formatting
Formatting isn't needed here

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Elf/ElfDynamicTag.cs
> +        DT_PREINIT_ARRAY = 32,
```suggestion
        DT_PREINIT_ARRAY = DT_ENCODING,
```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Elf/ElfDynamicTag.cs
> +    [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
Can be removed, aswell as the ReSharper attribute too.

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Tamper/CodeEmitters/LoadRegisterWithMemory.cs
> -
Shouldn't be removed

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Tamper/CodeEmitters/LegacyArithmetic.cs
> +#pragma warning disable IDE0055 // Disable formatting
This is useless

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Tamper/CodeEmitters/Arithmetic.cs
> +#pragma warning disable IDE0055 // Disable formatting
This is useless, formatting isn't needed

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Tamper/AtmosphereCompiler.cs
> +            catch (TamperCompilationException exception)
```suggestion
            catch (TamperCompilationException ex)
```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +#pragma warning disable IDE0055 // Disable formatting
Formatting isn't needed here

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +#pragma warning restore IDE0059
Can be removed

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +#pragma warning disable IDE0059 // Remove unnecessary value assignment
Can be removed

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +            _ = context.RequestData.ReadInt64();
Have to be reverted

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs
> +                using IStorage ncaFileStream = new LocalStorage(VirtualFileSystem.SwitchPathToSystemPath(GetTimeZoneBinaryTitleContentPath()), FileAccess.Read, FileMode.Open);
```suggestion
                using IStorage ncaFileStream = new LocalStorage(VirtualFileSystem.SwitchPathToSystemPath(GetTimeZoneBinaryTitleContentPath()), FileAccess.Read, FileMode.Open);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
> +#pragma warning disable IDE0059 // Remove unnecessary value assignment
Remove the assignment then.

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
> +#pragma warning disable IDE0059 // Remove unnecessary value assignment
Remove the assignment

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
> +#pragma warning disable IDE0059 // Remove unnecessary value assignment
Code issue ?

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZone.cs
> +#pragma warning disable IDE0059 // Remove unnecessary value assignment
Code issue ?

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/StaticService/ITimeZoneServiceForPsc.cs
> +            using MemoryStream timeZoneBinaryStream = new(temp);
```suggestion
            using MemoryStream timeZoneBinaryStream = new(temp);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/StaticService/ITimeZoneServiceForPsc.cs
> +            using WritableRegion region = context.Memory.GetWritableRegion(timeZoneRuleBufferPosition, Unsafe.SizeOf<TimeZoneRule>());
```suggestion
            using WritableRegion region = context.Memory.GetWritableRegion(timeZoneRuleBufferPosition, Unsafe.SizeOf<TimeZoneRule>());

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/StaticService/ITimeZoneServiceForGlue.cs
> +            using WritableRegion region = context.Memory.GetWritableRegion(bufferPosition, Unsafe.SizeOf<TimeZoneRule>());
```suggestion
            using WritableRegion region = context.Memory.GetWritableRegion(bufferPosition, Unsafe.SizeOf<TimeZoneRule>());

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/ITimeServiceManager.cs
> +            using MemoryStream timeZoneBinaryStream = new(temp);
```suggestion
            using MemoryStream timeZoneBinaryStream = new(temp);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/IStaticServiceForPsc.cs
> +            using BinaryReader bufferReader = new(new MemoryStream(temp));
```suggestion
            using BinaryReader bufferReader = new(new MemoryStream(temp));

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/Clock/SystemClockContextUpdateCallback.cs
> +        protected SystemClockContext Context;
This is the perfect example of naming issue here.
Protected or Private property should be PascalCase so it's called `Context`, but in HLE service `context` is usually used for `ServiceCtx` args, so called it `_context` do the property name a bit obvious. To avoid that we should named it `_systemClockContext` but since it should be PascalCase it have to be named `SystemClockContext` which conflict with the type itself.

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/Clock/NetworkSystemClockContextWriter.cs
> +            _sharedMemory.UpdateNetworkSystemClockContext(Context);
See my comment in `SystemClockContextUpdateCallback`

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Time/Clock/LocalSystemClockContextWriter.cs
> +            _sharedMemory.UpdateLocalSystemClockContext(Context);
See my comment in `SystemClockContextUpdateCallback`

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/Types/Color/ColorFormat.cs
> -        NonColor8                       = ColorSpace.NonColor      | ColorSwizzle.X000  | ColorComponent.X8           | ColorDataType.Integer,
Could be nice to keep the formatting here

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/Types/Color/ColorComponent.cs
> -        X1           = (0x01 << ColorShift.Component) | ColorBytePerPixel.Bpp1,
Could be nice to keep the formatting here

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs
> -    using ResultCode = Ryujinx.HLE.HOS.Services.Vi.ResultCode;
Shouldn't be removed

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/SurfaceFlinger.cs
> +        public Vi.ResultCode OpenLayer(ulong pid, long layerId, out IBinder producer)
`SurfaceFlinger` return `Vi` result code, that why it was done like that.

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/SurfaceFlinger/IHOSBinderDriver.cs
> +            using IMemoryOwner<byte> outputParcelOwner = ByteMemoryPool.RentCleared(replySize);
```suggestion
            using IMemoryOwner<byte> outputParcelOwner = ByteMemoryPool.RentCleared(replySize);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs
> +                    using WritableRegion region = context.Memory.GetWritableRegion(context.Request.ReceiveBuff[0].Position, (int)context.Request.ReceiveBuff[0].Size);
```suggestion
                    using WritableRegion region = context.Memory.GetWritableRegion(context.Request.ReceiveBuff[0].Position, (int)context.Request.ReceiveBuff[0].Size);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs
> +            using WritableRegion region = context.Memory.GetWritableRegion(context.Request.ReceiveBuff[0].Position, (int)context.Request.ReceiveBuff[0].Size);
```suggestion
            using WritableRegion region = context.Memory.GetWritableRegion(context.Request.ReceiveBuff[0].Position, (int)context.Request.ReceiveBuff[0].Size);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ssl/SslService/ISslConnection.cs
> +            using WritableRegion region = context.Memory.GetWritableRegion(context.Request.ReceiveBuff[0].Position, (int)context.Request.ReceiveBuff[0].Size);
```suggestion
            using WritableRegion region = context.Memory.GetWritableRegion(context.Request.ReceiveBuff[0].Position, (int)context.Request.ReceiveBuff[0].Size);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Spl/IRandomInterface.cs
>          private readonly object _lock = new();
Should be removed if it's unused

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +            using WritableRegion region = context.Memory.GetWritableRegion(responseBufferPosition, (int)responseBufferSize);
```suggestion
            using WritableRegion region = context.Memory.GetWritableRegion(responseBufferPosition, (int)responseBufferSize);

```

2023-07-02 02:41 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +#pragma warning disable IDE0059 // Remove unnecessary value assignment
There are too much of this pragma

2023-07-02 02:42 UTC, AcK77 requested changes
Reviewed around 60% for the PR for now.
A lot of IPC method are now changed into `static` which lead to some other change in services. I don't think it's safe to assume everything could works using `static` since we use a bunch of reflection in services. Additionally to that is doesn't looks good for consistency and do the services code less readable.

2023-07-02 14:42 UTC, TSRBerry commented on src/Ryujinx.HLE/FileSystem/ContentManager.cs
> +            using FileStream file = File.OpenRead(firmwareSource);
I don't quite understand what's the issue here. The alignment is currently correct the way it is.

2023-07-02 14:44 UTC, TSRBerry commented on src/Ryujinx.HLE/FileSystem/ContentManager.cs
> +                                extraNcas += path + Environment.NewLine;
Could you explain that?

2023-07-02 15:09 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Kernel/Process/KContextIdManager.cs
> +            return (_idMasks[bit / 32] & (1 << (bit & 31))) != 0;
Yep, I asked gdkchan about that in DMs, because I was curious why `bit` was unused here.

2023-07-02 15:12 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +    [SuppressMessage("Performance", "CA1822: Mark members as static")]
Almost all SVCs, I'll add the pragmas in a separate commit to make it easier to revert, since it will be a lot.

2023-07-02 15:39 UTC, TSRBerry commented on src/Ryujinx.HLE/Loaders/Elf/ElfDynamicTag.cs
> +        DT_PREINIT_ARRAY = 32,
I was thinking about doing that at first, but these mean different things, so I'm not sure if we really should change that here.

2023-07-02 15:40 UTC, TSRBerry commented on src/Ryujinx.HLE/Ui/Input/NpadReader.cs
> +                 firstEntryNum--)
That's way too long. It's unreadable without scrolling.

2023-07-02 15:43 UTC, TSRBerry commented on src/Ryujinx.HLE/Ui/RenderingSurfaceInfo.cs
> +                   Size == other.Size;
That would make it harder to read.

2023-07-02 16:11 UTC, TSRBerry commented on src/Ryujinx.HLE/Ui/RenderingSurfaceInfo.cs
> +#pragma warning disable CS0659 // Class overrides Object.Equals(object o) but does not override Object.GetHashCode()
I added an implementation for that now, but I have never done that and really don't know if that's a good way of doing it.

2023-07-02 16:30 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs
> +    [SuppressMessage("Performance", "CA1822: Mark members as static")]
Take a look at this commit: b62f985ad47031530b62744ecc1aea1943f03678

2023-07-02 16:51 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Vi/RootService/IApplicationDisplayService.cs
> +#pragma warning restore IDE0059
Why remove this one when you commented to revert the other one?

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/Exceptions/ServiceNotImplementedException.cs
> +#pragma warning disable IDE0055 // Disable formatting
No need to disable formatting here IMO.

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/FileSystem/ContentManager.cs
> +                                extraNcas += path + Environment.NewLine;
I prefer how it is now.

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Applets/Browser/BrowserApplet.cs
> +#pragma warning disable IDE0052 // Remove unread private member
Remove it?

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Kernel/Process/KHandleTable.cs
> +#pragma warning disable IDE0052 // Remove unread private member
Remove it?

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
> +#pragma warning disable IDE0052 // Remove unread private member
I'd just remove the unused fields.

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Kernel/Process/KProcess.cs
> +        private static void GenerateRandomEntropy()
Those should not be static. The only reason they *can* be static r ight now is because it is not actually implemented. Once it is implemented, it will need to access instance members and be made not static.

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Kernel/Process/ProcessExecutionContext.cs
> +        public static ulong CntpctEl0 => 0UL;
I think this implements an interface, so it can't be static?

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Kernel/Process/ProcessExecutionContext.cs
> +        public static ulong CntpctEl0 => 0UL;
Looks like it's not the case, so I think it can be removed, along with `CntfrqEl0`.

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Kernel/Threading/KReadableEvent.cs
> +#pragma warning disable IDE0052 // Remove unread private member
Remove it?

2023-07-02 18:47 UTC, gdkchan commented on src/Ryujinx.HLE/Ui/RenderingSurfaceInfo.cs
> +                   Size == other.Size;
Yea, I think splitting long lines into multiple lines like that is preferable.

2023-07-02 18:51 UTC, gdkchan commented
> A lot of IPC method are now changed into static which lead to some other change in services. I don't think it's safe to assume everything could works using static since we use a bunch of reflection in services. Additionally to that is doesn't looks good for consistency and do the services code less readable.

I think methods that can be made static just because they are not fully implemented yet (and so doesn't need to access any instance member) shouldn't be made static. Other cases should be fine to make static. Also any method with attributes might not be safe to make static as it might be accessed with reflection. As for the services implementation, I generally prefer making them not static in general.

2023-07-06 09:36 UTC, marysaka approved these changes

2023-07-16 17:31 UTC, merged

2023-07-17 00:04 UTC, demize commented on src/Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +                }
This change causes a regression in network functionality in certain games, causing a 2306-0520 network error when trying to resolve the server IP. Reverting just this part of this commit fixes the issue.

2023-07-17 11:34 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Sockets/Sfdnsres/IResolver.cs
> +                }
Thank you! I fixed this with #5459.