[Ryujinx.Horizon] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5381
Opened 2023-06-24 14:30 UTC by TSRBerry

Base PR: #4670

2023-06-25 20:00 UTC, AcK77 requested changes

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/DeliveryCacheProgressService.cs
> -using Ryujinx.Horizon.Bcat.Ipc.Types;
I prefer to keep that and remove the `Types.` in the rest of the code

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Bcat/Types/BcatServicePermissionLevel.cs
>          Manager = 6
```suggestion
        Manager = 6,
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Bcat/BcatIpcServer.cs
> -            _serverManager.RegisterServer((int)BcatPortIndex.Admin,   ServiceName.Encode("bcat:a"), BcatMaxSessionsCount);
Use `#pragma warning disable IDE0055 // Disable formatting` here

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Prepo/PrepoServerManager.cs
> +                _                      => throw new ArgumentOutOfRangeException(nameof(portIndex))
```suggestion
                _                      => throw new ArgumentOutOfRangeException(nameof(portIndex)),
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Prepo/Types/PrepoPortIndex.cs
>          Debug
```suggestion
        Debug,
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Prepo/Types/PrepoServicePermissionLevel.cs
>          Debug   = unchecked((int)0x80000006)
```suggestion
        Debug   = unchecked((int)0x80000006),
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Diag/LogSeverity.cs
>          Fatal = 4
```suggestion
        Fatal = 4,
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Lm/LogDataChunkKey.cs
>          Count
```suggestion
        Count,
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/OsTypes/InitializationState.cs
>          Initialized
```suggestion
        Initialized,
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/CmifMessage.cs
> +                    Token = format.Context
```suggestion
                    Token = format.Context,
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/CmifMessage.cs
> +                Token = format.ObjectId != 0 ? 0u : format.Context
```suggestion
                Token = format.ObjectId != 0 ? 0u : format.Context,
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/CmifOutHeader.cs
>          public uint   Magic;
Alignment issue

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/CmifRequestFormat.cs
>          public int  ObjectId;
Alignment issue

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/ServiceDispatchContext.cs
>          public HipcMessage            Request;
Alignment issue

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/CommandHandler.cs
>          private readonly MethodInvoke         _invoke;
Alignment issue

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/CommandSerialization.cs
> -        }
Even if we don't use it, we should keep it just in case

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Hipc/HipcMessage.cs
>                  };
There are alignment issues after that

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/Hipc/ServerManagerBase.cs
> +                _ => throw new NotImplementedException(((UserDataTag)holder.UserData).ToString())
```suggestion
                _ => throw new NotImplementedException(((UserDataTag)holder.UserData).ToString()),
```

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
> +#pragma warning disable CA1822 // Mark member as static
Can't be static ?

2023-06-25 20:00 UTC, AcK77 commented on src/Ryujinx.Horizon/Sm/Types/SmPortIndex.cs
>          Manager
```suggestion
        Manager,
```

2023-06-25 20:49 UTC, TSRBerry commented on src/Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
> +#pragma warning disable CA1822 // Mark member as static
I wasn't sure if this could cause problems, so I wanted to wait for @gdkchan's opinion on that.

2023-06-26 20:21 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
> +#pragma warning disable CA1822 // Mark member as static
I believe it can be static, but you will need to change `HipcGenerator` too if you make it static (as it currently generates code that will call it on the context instance).

2023-06-26 22:52 UTC, TSRBerry commented on src/Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
> +#pragma warning disable CA1822 // Mark member as static
In that case I think we should leave it as is for now, since this PR only focuses on formatting.

2023-06-27 14:47 UTC, marysaka commented on src/Ryujinx.Horizon/Sdk/Sf/HipcCommandProcessor.cs
> +#pragma warning disable CA1822 // Mark member as static
Yeah that can be left to address later.

2023-06-27 14:55 UTC, marysaka approved these changes

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Bcat/Ipc/ServiceCreator/BcatService.cs
> +#pragma warning disable IDE0052 // Remove unread private member
Just remove if it's unused? It's easy to add it back if we need it.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/OsTypes/Impl/InterProcessEventImpl.cs
> +                if (result == KernelResult.TimedOut)
Same comment as the other PRs about else-if chains.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/OsTypes/Impl/MultiWaitImpl.cs
> +            if (result == KernelResult.Cancelled)
Same as above.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/OsTypes/Impl/MultiWaitImpl.cs
> +            foreach (MultiWaitHolder holder in _multiWaits.Cast<MultiWaitHolder>())
Why was `.Cast<MultiWaitHolder>()` added?

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/DomainServiceObjectProcessor.cs
> +#pragma warning disable IDE0051 // Remove unused private member
If it's unused, just remove.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sf/Cmif/ServiceDispatchTableBase.cs
> +                if (HorizonStatic.Options.ThrowOnInvalidCommandIds)
else-if chain.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sf/Hipc/Api.cs
> +            if (result == KernelResult.ReceiveListBroken)
else-if chain.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sf/Hipc/ServerManagerBase.cs
> +                    if (selected == _notifyEventHolder)
else-if chain.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sf/Hipc/ServerSessionManager.cs
> +            if (SfResult.RequestContextChanged(result))
else-if chain.

2023-06-27 21:22 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Sm/ServiceName.cs
> +        public static int Length => sizeof(ulong);
I wonder if that can be `const`?

2023-06-27 22:55 UTC, TSRBerry commented on src/Ryujinx.Horizon/Sdk/OsTypes/Impl/MultiWaitImpl.cs
> +            foreach (MultiWaitHolder holder in _multiWaits.Cast<MultiWaitHolder>())
I added it to avoid this warning:
> Possible 'System.InvalidCastException' when casting from Ryujinx.Horizon.Sdk.OsTypes.MultiWaitHolderBase to Ryujinx.Horizon.Sdk.OsTypes.MultiWaitHolder

But it's not really needed, so I could remove it if you want.

2023-06-27 22:57 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/OsTypes/Impl/MultiWaitImpl.cs
> +            foreach (MultiWaitHolder holder in _multiWaits.Cast<MultiWaitHolder>())
Yea, seems better to remove it. I think I saw it used elsewhere too.

2023-06-27 23:06 UTC, gdkchan approved these changes
lgtm, thanks.

2023-07-01 10:42 UTC, merged