[Ryujinx.Input] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5384
Opened 2023-06-24 14:31 UTC by TSRBerry

Base PR: #4670

2023-06-24 17:29 UTC, AcK77 requested changes

2023-06-24 17:29 UTC, AcK77 commented on src/Ryujinx.Input/HLE/NpadManager.cs
> +                        inputState.Buttons |= Hid.UpdateStickButtons(inputState.LStick, inputState.RStick);
This change is strange or maybe I misunderstood something. (Or maybe there is something wrong in our code)

2023-06-24 17:29 UTC, AcK77 commented on src/Ryujinx.Input/Motion/CemuHook/Client.cs
> +            using BinaryWriter writer = new(stream);
```suggestion
            using BinaryWriter writer = new(stream);

```

2023-06-24 17:29 UTC, AcK77 commented on src/Ryujinx.Input/Motion/CemuHook/Client.cs
> +            using BinaryWriter writer = new(stream);
```suggestion
            using BinaryWriter writer = new(stream);

```

2023-06-24 19:16 UTC, marysaka approved these changes
same comment as Ack, otherwise lgtm.

2023-06-26 05:31 UTC, marysaka approved these changes

2023-06-28 16:22 UTC, AcK77 approved these changes

2023-06-28 16:23 UTC, merged