[Ryujinx.Input.SDL2] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5385
Opened 2023-06-24 14:31 UTC by TSRBerry

Base PR: #4670

2023-06-24 17:24 UTC, AcK77 requested changes

2023-06-24 17:24 UTC, AcK77 commented on src/Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                    throw new InvalidOperationException($"Could not enable data reporting for SensorType {SDL_SensorType.SDL_SENSOR_ACCEL}.");
Maybe we should use `Logger` instead of throwing here.

2023-06-24 17:24 UTC, AcK77 commented on src/Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                    throw new InvalidOperationException($"Could not enable data reporting for SensorType {SDL_SensorType.SDL_SENSOR_GYRO}.");
Maybe we should use `Logger` instead of throwing here.

2023-06-24 17:24 UTC, AcK77 commented on src/Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                        throw new NotSupportedException("Rumble is not supported on this game controller.");
Maybe we should use `Logger` instead of throwing here.

2023-06-24 17:24 UTC, AcK77 commented on src/Ryujinx.Input.SDL2/SDL2Gamepad.cs
> +                        throw new NotSupportedException("Rumble is not supported on this game controller.");
Maybe we should use `Logger` instead of throwing here.

2023-06-24 17:24 UTC, AcK77 commented on src/Ryujinx.Input.SDL2/SDL2Keyboard.cs
> +                _ => SDL_Keymod.KMOD_NONE,
```suggestion
                _ => SDL_Keymod.KMOD_NONE
```

2023-06-24 19:25 UTC, marysaka approved these changes
I agree with Ack, those throw should be logged as error.

2023-06-26 01:52 UTC, AcK77 approved these changes

2023-06-26 01:55 UTC, merged