[Ryujinx.Memory] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5386
Opened 2023-06-24 14:32 UTC by TSRBerry

Base PR: #4670

2023-06-24 17:22 UTC, AcK77 requested changes

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/MemoryBlock.cs
>              return (IntPtr)(pointer.ToInt64() + (long)offset);
```suggestion
            return new IntPtr(pointer.ToInt64() + (long)offset);
```

And remove the pragma ?

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/MemoryManagementUnix.cs
>              close((int)handle);
```suggestion
            close(handle.ToInt32());
```
And remove the pragma

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/MemoryManagementUnix.cs
>              return mmap(IntPtr.Zero, size, MmapProts.PROT_READ | MmapProts.PROT_WRITE, MmapFlags.MAP_SHARED, (int)handle, 0);
```suggestion
            return mmap(IntPtr.Zero, size, MmapProts.PROT_READ | MmapProts.PROT_WRITE, MmapFlags.MAP_SHARED, handle.ToInt32(), 0);
```
And remove the pragma

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/MemoryManagementUnix.cs
>              mmap(location, size, MmapProts.PROT_READ | MmapProts.PROT_WRITE, MmapFlags.MAP_FIXED | MmapFlags.MAP_SHARED, (int)sharedMemory, (long)srcOffset);
```suggestion
            mmap(location, size, MmapProts.PROT_READ | MmapProts.PROT_WRITE, MmapFlags.MAP_FIXED | MmapFlags.MAP_SHARED, sharedMemory.ToInt32(), (long)srcOffset);
```
And remove the pragma

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/MemoryManagerUnixHelper.cs
> +#pragma warning disable IDE1006 // Naming rule violation
Maybe we should rename the method instead of using a pragma

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/Tracking/MultiRegionHandle.cs
> +            GC.SuppressFinalize(this);
```suggestion
            GC.SuppressFinalize(this);

```

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
I'd prefer to keep private fields prefixed by `_` in cameCase

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/Tracking/SmartMultiRegionHandle.cs
> +            GC.SuppressFinalize(this);
```suggestion
            GC.SuppressFinalize(this);

```

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/WindowsShared/PlaceholderManager.cs
>              ulong startAddress = address;
If it's not needed, maybe we should remove it.

2023-06-24 17:22 UTC, AcK77 commented on src/Ryujinx.Memory/WindowsShared/WindowsFlags.cs
> +    [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
As I said in another project, this should be removed.

2023-06-24 22:58 UTC, TSRBerry commented on src/Ryujinx.Memory/WindowsShared/WindowsFlags.cs
> +    [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
If I remove that CI will fail. I either need to disable it in `.editorconfig` or replace this with a pragma.

2023-06-24 23:45 UTC, TSRBerry commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
Events don't qualify as fields. C# defaults to PascalCase for these, see: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/naming-rules#default-naming-styles

Should I still change it?

2023-06-24 23:54 UTC, AcK77 commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
It's a bit strange >< ... Let's other devs input on this.
I prefer `_camelCase` for `private` in any case when it's not a `const`.

2023-06-24 23:56 UTC, AcK77 commented on src/Ryujinx.Memory/WindowsShared/WindowsFlags.cs
> +    [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
Maybe we could fix the enum that way:

```
...
Decommit = 0x4000,
ReplacePlaceholder = Decommit,
...
```

2023-06-25 00:07 UTC, TSRBerry commented on src/Ryujinx.Memory/WindowsShared/WindowsFlags.cs
> +    [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
I can try that, but I think it leads to the same issue.

2023-06-25 00:10 UTC, TSRBerry commented on src/Ryujinx.Memory/WindowsShared/WindowsFlags.cs
> +    [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
Nvm, your suggestion seems to work just fine!

2023-06-25 21:15 UTC, TSRBerry commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
@Ryujinx/developers need some input here.

2023-06-26 05:37 UTC, marysaka commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
it follows property pattern right? so that kind of makes sense to me...

2023-06-26 05:37 UTC, marysaka approved these changes

2023-06-26 09:54 UTC, TSRBerry commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
I'd also like to keep them as PascalCase tbh

2023-06-26 20:18 UTC, gdkchan commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
I'd just follow standard naming rules for those which is PascalCase apparently?

2023-06-27 14:49 UTC, marysaka commented on src/Ryujinx.Memory/Tracking/RegionHandle.cs
> +        private event Action OnDirty;
That makes sense as you can see `event`s as properties in a sense (and properties use PascalCase too)

2023-06-27 21:29 UTC, gdkchan commented on src/Ryujinx.Memory/MemoryManagementUnix.cs
> +
I might be imagining things, but I think some of your other PRs removes the separation between `using` and `using static`.

2023-06-27 21:29 UTC, gdkchan commented on src/Ryujinx.Memory/Tracking/MultiRegionHandle.cs
> +            GC.SuppressFinalize(this);
Might be wroth properly implementing the dispose pattern.

2023-06-27 23:04 UTC, TSRBerry commented on src/Ryujinx.Memory/MemoryManagementUnix.cs
> +
I thought so too, I'll check that.

2023-06-27 23:06 UTC, TSRBerry commented on src/Ryujinx.Memory/Tracking/MultiRegionHandle.cs
> +            GC.SuppressFinalize(this);
What's missing for that? `IMultiRegionHandle` implements `IDisposable`

2023-06-27 23:10 UTC, gdkchan commented on src/Ryujinx.Memory/Tracking/MultiRegionHandle.cs
> +            GC.SuppressFinalize(this);
You can check https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose#dispose-and-disposebool

2023-06-27 23:13 UTC, gdkchan commented on src/Ryujinx.Memory/Tracking/MultiRegionHandle.cs
> +            GC.SuppressFinalize(this);
I was thinking about the missing `Dispose(bool)` method, but since the `GC.SuppressFinalize(this);` goes into the main `Dispose` method it should be fine like that. We can change it to follow the recommended pattern on a separate PR.

2023-06-27 23:13 UTC, gdkchan approved these changes
lgtm, thanks.

2023-06-28 15:35 UTC, AcK77 approved these changes
Little missing things, but I approve it with requested changes fixed!

2023-06-28 15:35 UTC, AcK77 commented on src/Ryujinx.Memory/Tracking/SmartMultiRegionHandle.cs
> +            GC.SuppressFinalize(this);
```suggestion
            GC.SuppressFinalize(this);

```

2023-06-28 15:35 UTC, AcK77 commented on src/Ryujinx.Memory/WindowsShared/WindowsFlags.cs
> +        ReplacePlaceholder = Decommit,
I comment here since I can't at any other place, but it seems some enums here missing the tailing `,`

2023-06-28 16:34 UTC, merged