[Ryujinx.Tests] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5389
Opened 2023-06-24 14:32 UTC by TSRBerry

Base PR: #4670

2023-06-24 17:11 UTC, AcK77 requested changes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestMul32.cs
> +#pragma warning disable IDE0051, IDE1006 // Remove unused private member, Naming rule violation
Maybe we should rename methods instead of use a pragma

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimd.cs
> +            }
```suggestion
            }

```

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimd.cs
> +            }
```suggestion
            }

```

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimd.cs
> +            }
```suggestion
            }

```

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimd.cs
> +#pragma warning disable IDE1006 // Naming rule violation
Maybe we should rename methods instead of use a pragma (Same for all other "Naming rule violation" pragmas)

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimd.cs
> +        [Explicit] // Unicorn seems to default all rounding modes to RMode.Rn.
Maybe we should put the comment before attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimd.cs
> +        [Explicit] // Unicorn seems to default all rounding modes to RMode.Rn.
Maybe we should put the comment before attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdMov32.cs
>              }
```suggestion
            }

```

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdMov32.cs
>              }
```suggestion
            }

```

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdMov32.cs
>              }
```suggestion
            }

```

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
> +                            [Values(0b0u, 0b1u)] uint q)    // Q1: <16B, 2D> => <8H, 1Q>
```suggestion
                            [Values(0b0u, 0b1u)] uint q) // Q1: <16B, 2D> => <8H, 1Q>
```

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg32.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdRegElemF.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdRegElemF.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdRegElemF.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdRegElemF.cs
> +        [Explicit] // Fused.
Comment should be above attributes

2023-06-24 17:11 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestT32Mem.cs
> +                MemoryDelta = System.Array.Empty<(ulong Address, ushort Value)>(),
Add `using System;` instead ? (same for other changes)

2023-06-24 19:12 UTC, marysaka commented on src/Ryujinx.Tests/Cpu/CpuTest32.cs
> +#pragma warning restore CA2211
Those are used by tests derivated from CpuTest32.

2023-06-24 19:12 UTC, marysaka approved these changes

2023-06-26 05:26 UTC, marysaka approved these changes

2023-06-28 16:03 UTC, AcK77 reviewed
Some things are still missing, maybe some tailing `,` too.

2023-06-28 16:15 UTC, AcK77 reviewed
There are still missing `,` at many places :P

2023-06-28 16:15 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdLogical32.cs
>                             0x8000000080000000ul, 0xFFFFFFFFFFFFFFFFul };
```suggestion
                           0x8000000080000000ul, 0xFFFFFFFFFFFFFFFFul, };
```

2023-06-28 16:15 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdRegElem.cs
>                             0x8000800080008000ul, 0xFFFFFFFFFFFFFFFFul };
```suggestion
                           0x8000800080008000ul, 0xFFFFFFFFFFFFFFFFul, };
```

2023-06-28 16:15 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdShImm32.cs
>              return new[] { 0x0000000000000000ul, 0x7FFFFFFFFFFFFFFFul,
Missing `,` on next lines

2023-06-28 16:15 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdShImm32.cs
>              return new[] { 0x0000000000000000ul, 0x7F7F7F7F7F7F7F7Ful, 0x8080808080808080ul, 0xFFFFFFFFFFFFFFFFul };
```suggestion
            return new[] { 0x0000000000000000ul, 0x7F7F7F7F7F7F7F7Ful, 0x8080808080808080ul, 0xFFFFFFFFFFFFFFFFul, };
```
Same for above lines

2023-06-28 16:15 UTC, AcK77 commented on src/Ryujinx.Tests/Cpu/CpuTestSimdReg.cs
>              return new[] { 0x0000000000000000ul, 0x000000000000007Ful,
Same here

2023-07-01 02:14 UTC, AcK77 approved these changes

2023-07-01 02:14 UTC, merged