[Ryujinx.Ui.Common] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5392
Opened 2023-06-24 14:33 UTC by TSRBerry

Base PR: #4670

2023-06-24 16:44 UTC, AcK77 commented on src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +using TimeSpan = System.TimeSpan;
I wonder what currently conflict with TimeSpan here.

2023-06-24 16:44 UTC, AcK77 commented on src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                appMetadata = JsonHelper.DeserializeFromFile<ApplicationMetadata>(metadataFile, SerializerContext.ApplicationMetadata);
This is really needed? Since `appMetadata` is already casted to `ApplicationMetadata`

2023-06-24 16:44 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
>                  Version                    = ConfigurationFileFormat.CurrentVersion,
Alignment isn't removed here ?

2023-06-24 16:44 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/LoggerModule.cs
> +#pragma warning disable IDE0055 // Disable formatting
I think we should remove the pragma and remove the alignment aswell

2023-06-24 20:39 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +                appMetadata = JsonHelper.DeserializeFromFile<ApplicationMetadata>(metadataFile, SerializerContext.ApplicationMetadata);
Odd, it shouldn't be. Let me check again.

2023-06-24 20:59 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/App/ApplicationLibrary.cs
> +using TimeSpan = System.TimeSpan;
Conflict with `LibHac.TimeSpan`

2023-06-24 21:02 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
>                  Version                    = ConfigurationFileFormat.CurrentVersion,
For some reason `dotnet format whitespace` doesn't remove it even though the rule is gone :thinking:

2023-06-24 23:24 UTC, TSRBerry commented
All checks are passing, so marking this as ready to review!

2023-06-25 11:44 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
>                  Version                    = ConfigurationFileFormat.CurrentVersion,
Figured that one out, it should be good now.

2023-06-25 11:47 UTC, marysaka approved these changes

2023-06-25 15:52 UTC, AcK77 requested changes

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                        ButtonSr = Key.Unbound
```suggestion
                        ButtonSr = Key.Unbound,
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                    }
```suggestion
                    },
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                MultiplayerLanInterfaceId = Multiplayer.LanInterfaceId
```suggestion
                MultiplayerLanInterfaceId = Multiplayer.LanInterfaceId,
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                    PathColumn = Ui.GuiColumns.PathColumn
```suggestion
                    PathColumn = Ui.GuiColumns.PathColumn,
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                            ButtonSr = Key.Unbound
```suggestion
                            ButtonSr = Key.Unbound,
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                            ButtonSr = Key.Unbound
```suggestion
                            ButtonSr = Key.Unbound,
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                        }
```suggestion
                        },
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +                configurationFileFormat.Hotkeys = new KeyboardHotkeys { ToggleVsync = Key.F1, Screenshot = Key.F8 };
This doesn't have to be on one line

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/DiscordIntegrationModule.cs
>                          Url   = "https://ryujinx.org/"
```suggestion
                        Url   = "https://ryujinx.org/",
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/DiscordIntegrationModule.cs
>                  }
```suggestion
                },
```

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/DiscordIntegrationModule.cs
>                          Url   = "https://ryujinx.org/"
```suggestion
                        Url = "https://ryujinx.org/",
```

tailing `,` is missing after next `}`

2023-06-25 15:52 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Helper/OpenHelper.cs
> +                    Verb = "open"
```suggestion
                    Verb = "open",
```

2023-06-26 17:20 UTC, IsaacMarovitz approved these changes

2023-06-28 17:00 UTC, AcK77 reviewed
Maybe some tailing `,` are still missing, I haven't checked the whole project.

2023-06-28 17:00 UTC, AcK77 commented on src/Ryujinx.Ui.Common/UserError.cs
>          Unknown = 0xDEAD
```suggestion
        Unknown = 0xDEAD,
```

2023-06-29 00:39 UTC, AcK77 approved these changes

2023-06-29 00:39 UTC, merged