[Spv.Generator] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5394
Opened 2023-06-24 14:34 UTC by TSRBerry

Base PR: #4670

2023-06-24 16:35 UTC, AcK77 reviewed
Some cleaned code is autogenerated one, maybe we should clean the generator aswell.

2023-06-24 16:35 UTC, AcK77 commented on src/Spv.Generator/ConstantKey.cs
> +            return obj is ConstantKey key && Equals(key);
Mixing `is` and `&&` could cause this strange issue: https://github.com/Ryujinx/Ryujinx/pull/5207#discussion_r1214943768

2023-06-24 16:35 UTC, AcK77 commented on src/Spv.Generator/DeterministicStringKey.cs
> +            return obj is DeterministicStringKey key && Equals(key);
Mixing `is` and `&&` could cause this strange issue: https://github.com/Ryujinx/Ryujinx/pull/5207#discussion_r1214943768

2023-06-24 16:35 UTC, AcK77 commented on src/Spv.Generator/Module.cs
> +            using MemoryStream stream = new(sizeEstimate);
```suggestion
            using MemoryStream stream = new(sizeEstimate);

```

2023-06-24 16:35 UTC, AcK77 commented on src/Spv.Generator/TypeDeclarationKey.cs
> +            return obj is TypeDeclarationKey key && Equals(key);
Mixing `is` and `&&` could cause this strange issue: https://github.com/Ryujinx/Ryujinx/pull/5207#discussion_r1214943768

2023-06-24 16:35 UTC, AcK77 commented on src/Spv.Generator/spirv.cs
> +        [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
I think we should remove that, in many places we could duplicate some enum values, so it just add extra useless code here. (Same for all other `SuppressMessage`

2023-06-24 19:21 UTC, marysaka requested changes

2023-06-24 19:21 UTC, marysaka commented on src/Spv.Generator/Operand.cs
> +    public interface IOperand : IEquatable<IOperand>
Rename the file too.

2023-06-25 15:24 UTC, TSRBerry commented on src/Spv.Generator/ConstantKey.cs
> +            return obj is ConstantKey key && Equals(key);
Let's wait for gdkchans comment on the other PR

2023-06-26 05:28 UTC, marysaka approved these changes

2023-06-26 10:07 UTC, TSRBerry commented on src/Spv.Generator/DeterministicStringKey.cs
> +            return obj is DeterministicStringKey key && Equals(key);
The attribute for the parameter should just be `NotNull` instead of `NotNullWhen(true)`.

2023-06-26 10:10 UTC, TSRBerry commented on src/Spv.Generator/DeterministicStringKey.cs
> +            return obj is DeterministicStringKey key && Equals(key);
Although Equals can be used with null as well, so the `NotNull` doesn't really make sense here anyway.

2023-06-26 10:20 UTC, TSRBerry commented on src/Spv.Generator/spirv.cs
> +        [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
Instead of disabling the warning I'll solve them instead.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1069#how-to-fix-violations

2023-06-26 10:58 UTC, TSRBerry commented on src/Spv.Generator/spirv.cs
> +        [SuppressMessage("Design", "CA1069: Enums values should not be duplicated")]
List of other affected projects:

- Ryujinx.HLE
- Ryujinx.Graphics.Gpu
- Ryujinx.Graphics.GAL
- Ryujinx.Graphics.Shader
- Ryujinx.Memory
- Ryujinx.Ava

You can generate this list by executing this: `dotnet format analyzers --severity info -v d --report analyzers.json ; jq '.[] | select(.FileChanges[].DiagnosticId == "CA1069") | .FilePath' ./analyzers.json | uniq` and by adding `awk -F'/' '{print $<position of the project in the path>}'` in front of `uniq` you can get the list without any duplicates.

2023-06-27 21:33 UTC, gdkchan commented on src/Spv.Generator/ConstantKey.cs
> +            return obj is ConstantKey key && Equals(key);
I have done this exact pattern in several other places and it has always been fine. I don't think it should be an issue here.

2023-06-27 21:33 UTC, gdkchan commented on src/Spv.Generator/DeterministicStringKey.cs
> +            return obj is DeterministicStringKey key && Equals(key);
Same as above.

2023-06-27 21:33 UTC, gdkchan commented on src/Spv.Generator/GeneratorPool.cs
> +#pragma warning disable IDE0052 // Remove unread private member
If it's unused, just remove it.

2023-06-28 16:49 UTC, AcK77 approved these changes

2023-06-28 16:54 UTC, merged