[Ryujinx] Address dotnet-format issues
Ryujinx/Ryujinx pull request #5395
Opened 2023-06-24 15:06 UTC by TSRBerry

Base PR: #4670

2023-06-24 17:56 UTC, AcK77 requested changes
There are a lot of formatting/alignment/spacing issues. I haven't commented all of them.

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                using Stream updateFileStream = File.Open(updateFile, FileMode.Create);
```suggestion
                using Stream updateFileStream = File.Open(updateFile, FileMode.Create);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Modules/Updater/Updater.cs
> +                using ZipFile zipFile  = new(inStream);
Alignment isn't removed here.

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Modules/Updater/Updater.cs
>                          using (FileStream outStream = File.OpenWrite(outPath))
`using` can't be inlined here ?

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Program.cs
> +                    throw new NotSupportedException("Failed to initialize multi-threading support.");
I don't think we should throw here, maybe we should log instead?

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Applet/GtkHostUiHandler.cs
> +        private static void SynchronousGtkInvoke(Action action)
If it's really unused, maybe we should remove it.

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
>                                                                            _accountManager,
Aligment is off here

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                Name         = "GUI.ApplicationLibraryThread",
```suggestion
                Name = "GUI.ApplicationLibraryThread",
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +            using FileChooserNative fileChooser = new("Choose the file to open", this, FileChooserAction.Open, "Open", "Cancel");
```suggestion
            using FileChooserNative fileChooser = new("Choose the file to open", this, FileChooserAction.Open, "Open", "Cancel");

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +            using FileChooserNative fileChooser = new("Choose the folder to open", this, FileChooserAction.SelectFolder, "Open", "Cancel");
```suggestion
            using FileChooserNative fileChooser = new("Choose the folder to open", this, FileChooserAction.SelectFolder, "Open", "Cancel");

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                            _currentEmulatedGamePath);
Alignment is strange here

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                    using FileStream file = new(_titleFilePath, FileMode.Open, FileAccess.Read);
```suggestion
                    using FileStream file = new(_titleFilePath, FileMode.Open, FileAccess.Read);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                    Nca mainNca  = null;
```suggestion
                    Nca mainNca = null;
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GtkInputDialog.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/UserErrorDialog.cs
> +                _ => "Undefined error",
```suggestion
                _ => "Undefined error"
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/UserErrorDialog.cs
> +                _ => "An undefined error occured! This shouldn't happen, please contact a dev!",
```suggestion
                _ => "An undefined error occured! This shouldn't happen, please contact a dev!"
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/UserErrorDialog.cs
> +                _ => false,
```suggestion
                _ => false
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/UserErrorDialog.cs
> +                _ => SetupGuideUrl,
```suggestion
                _ => SetupGuideUrl
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AvatarWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AvatarWindow.cs
> +                using IStorage ncaFileStream = new LocalStorage(avatarPath, FileAccess.Read, FileMode.Open);
```suggestion
                using IStorage ncaFileStream = new LocalStorage(avatarPath, FileAccess.Read, FileMode.Open);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AvatarWindow.cs
> +            using MemoryStream streamJpg = MemoryStreamManager.Shared.GetStream();
```suggestion
            using MemoryStream streamJpg = MemoryStreamManager.Shared.GetStream();

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AvatarWindow.cs
> +            using ColorChooserDialog colorChooserDialog = new("Set Background Color", this);
```suggestion
            using ColorChooserDialog colorChooserDialog = new("Set Background Color", this);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AvatarWindow.cs
> +            using BinaryReader reader = new(stream);
```suggestion
            using BinaryReader reader = new(stream);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
>                      _               => new Gdk.Pixbuf(Assembly.GetAssembly(typeof(ConfigurationState)), "Ryujinx.Ui.Common.Resources.Controller_JoyConPair.svg", 400, 500),
```suggestion
                    _ => new Gdk.Pixbuf(Assembly.GetAssembly(typeof(ConfigurationState)), "Ryujinx.Ui.Common.Resources.Controller_JoyConPair.svg", 400, 500)
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +#pragma warning disable CA1806, IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        StickButton = lStickButton,
```suggestion
                        StickButton = lStickButton
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        StickButton = rStickButton,
```suggestion
                        StickButton = rStickButton
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
>                      },
```suggestion
                    }
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +#pragma warning disable CA1806, IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        GyroDeadzone = _gyroDeadzone.Value,
```suggestion
                        GyroDeadzone = _gyroDeadzone.Value
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        Rotate90CW = _rotateL90CW.Active,
```suggestion
                        Rotate90CW = _rotateL90CW.Active
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                        Rotate90CW = _rotateR90CW.Active,
```suggestion
                        Rotate90CW = _rotateR90CW.Active
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                            StickButton = Key.F,
```suggestion
                            StickButton = Key.F
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                            StickButton = Key.H,
```suggestion
                            StickButton = Key.H
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                            ButtonSr = ConfigGamepadInputId.Unbound,
```suggestion
                            ButtonSr = ConfigGamepadInputId.Unbound
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                            Rotate90CW = false,
```suggestion
                            Rotate90CW = false
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                            ButtonSr = ConfigGamepadInputId.Unbound,
```suggestion
                            ButtonSr = ConfigGamepadInputId.Unbound
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
> +                            Rotate90CW = false,
```suggestion
                            Rotate90CW = false
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/ControllerWindow.cs
>                              GyroDeadzone = 1,
```suggestion
                            GyroDeadzone = 1
```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/DlcWindow.cs
>                      using FileStream containerFile = File.OpenRead(dlcContainer.ContainerPath);
```suggestion

                    using FileStream containerFile = File.OpenRead(dlcContainer.ContainerPath);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/DlcWindow.cs
> +                    PartitionFileSystem pfs = new(containerFile.AsStorage());
```suggestion
                    PartitionFileSystem pfs = new(containerFile.AsStorage());

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/DlcWindow.cs
> +                    using FileStream containerFile = File.OpenRead(containerPath);
```suggestion
                    using FileStream containerFile = File.OpenRead(containerPath);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/SettingsWindow.cs
> +#pragma warning disable IDE0055 // Disable formatting
Can be removed for consistencies

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/TitleUpdateWindow.cs
> +                using FileStream file = new(path, FileMode.Open, FileAccess.Read);
```suggestion
                using FileStream file = new(path, FileMode.Open, FileAccess.Read);

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/TitleUpdateWindow.cs
> +            using FileChooserNative fileChooser = new("Select update files", this, FileChooserAction.Open, "Add", "Cancel");
```suggestion
            using FileChooserNative fileChooser = new("Select update files", this, FileChooserAction.Open, "Add", "Cancel");

```

2023-06-24 17:56 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/UserProfilesManagerWindow.cs
> +            using MemoryStream streamJpg = MemoryStreamManager.Shared.GetStream();
```suggestion
            using MemoryStream streamJpg = MemoryStreamManager.Shared.GetStream();

```

2023-06-25 13:50 UTC, TSRBerry commented
All checks are passing here as well, marking as ready!

2023-06-25 16:44 UTC, AcK77 requested changes
More reviewing.
We should probably choose between `GTK` / `Gtk`, `SDL` / `Sdl`, `SPB` / `Spb`, ... There are a lot of acronym like that in the code.

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Input/GTK3/GTK3Keyboard.cs
> +    public class Gtk3Keyboard : IKeyboard
```suggestion
    public class GTK3Keyboard : IKeyboard
```

I'd prefer to keep `GTK`

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Input/GTK3/GTK3KeyboardDriver.cs
> +    public class Gtk3KeyboardDriver : IGamepadDriver
```suggestion
    public class GTK3KeyboardDriver : IGamepadDriver
```
Same as other comment

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Input/GTK3/GTK3MappingHelper.cs
> +    public static class Gtk3MappingHelper
```suggestion
    public static class GTK3MappingHelper
```
Same as other comment

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Input/GTK3/GTK3Mouse.cs
> +    public class Gtk3Mouse : IMouse
```suggestion
    public class GTK3Mouse : IMouse
```

Same as other comment

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Input/GTK3/GTK3MouseDriver.cs
> +    public class Gtk3MouseDriver : IGamepadDriver
```suggestion
    public class GTK3MouseDriver : IGamepadDriver
```
Same as other comment

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Program.cs
> +        private const uint MbIconwarning = 0x30;
```suggestion
        private const uint MbIconWarning = 0x30;
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                _pathToggle.Active = true;
```
            if (ConfigurationState.Instance.Ui.GuiColumns.FavColumn)
            {
                _favToggle.Active = true;
            }
            
            ...
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                _gameTable.AppendColumn("Path", new CellRendererText(), "text", 9);
```
            if (ConfigurationState.Instance.Ui.GuiColumns.FavColumn)
            {
                _gameTable.AppendColumn("Fav", favToggle, "active", 0);
            }

            ...
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +            bool threadedGal = threadingMode == BackendThreading.On || (threadingMode == BackendThreading.Auto && renderer.PreferThreading);
```suggestion
            bool threadedGAL = threadingMode == BackendThreading.On || (threadingMode == BackendThreading.Auto && renderer.PreferThreading);
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
>                                                                            _accountManager,
This is not resolved

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +            return new SurfaceKHR((ulong)((VkRenderer)RendererWidget).CreateWindowSurface(instance.Handle));
```suggestion
            return new SurfaceKHR((ulong)((VKRenderer)RendererWidget).CreateWindowSurface(instance.Handle));
```

Or maybe rename the original class `VulkanRenderer` ?

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                IsBackground = true
```suggestion
                IsBackground = true,
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
>                      SecondaryText = "For optimal performance, it's recommended to disable trace logging. Would you like to disable trace logging now?"
```suggestion
                    SecondaryText = "For optimal performance, it's recommended to disable trace logging. Would you like to disable trace logging now?",
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
>                      SecondaryText = "For optimal performance, it's recommended to disable shader dumping. Would you like to disable shader dumping now?"
```suggestion
                    SecondaryText = "For optimal performance, it's recommended to disable shader dumping. Would you like to disable shader dumping now?",
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                Name = "Switch Executables"
```suggestion
                Name = "Switch Executables",
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                            Name = "GUI.FirmwareInstallerThread"
```suggestion
                            Name = "GUI.FirmwareInstallerThread",
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                            _currentEmulatedGamePath);
Still unresolved

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/RendererWidgetBase.cs
>                  Name = "GUI.RenderLoop"
```suggestion
                Name = "GUI.RenderLoop",
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/RendererWidgetBase.cs
>                      Name = "GUI.NVStutterWorkaround"
```suggestion
                    Name = "GUI.NVStutterWorkaround",
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/RendererWidgetBase.cs
> +        private void NvStutterWorkaround()
```suggestion
        private void NvidiaStutterWorkaround()
```

in `Ryujinx.Headless.SDL2` I suggested `NV` but maybe `Nvidia` do more sense

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/SPBOpenGLContext.cs
> +    class SpbOpenGLContext : IOpenGLContext
```suggestion
    class SPBOpenGLContext : IOpenGLContext
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/VKRenderer.cs
> +    public partial class VkRenderer : RendererWidgetBase
```suggestion
    public partial class VulkanRenderer : RendererWidgetBase
```

As suggested above

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
>                              WindowPosition = WindowPosition.Center
```suggestion
                            WindowPosition = WindowPosition.Center,
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GameTableContextMenu.cs
> +                    IsBackground = true
```suggestion
                    IsBackground = true,
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Widgets/GtkInputDialog.cs
>                  Text = mainText
```suggestion
                Text = mainText,
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs
> +                MarginEnd = 0
```suggestion
                MarginEnd = 0,
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs
> +                MarginStart = 15
```suggestion
                MarginStart = 15,
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs
> +                MarginEnd     = 30
```suggestion
                MarginEnd     = 30,
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs
>                  Editable      = false,
Aligmnent isn't removed here

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs
>                  Attributes  = new AttrList()
```suggestion
                Attributes  = new AttrList(),
```

2023-06-25 16:44 UTC, AcK77 commented on src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs
>                  Halign      = Align.End,
Alignment isn't removed

2023-06-25 17:15 UTC, TSRBerry commented on src/Ryujinx/Modules/Updater/Updater.cs
>                          using (FileStream outStream = File.OpenWrite(outPath))
This would extend the lifetime of these, but we only need them for the copy. Should I still switch to using declarations for them?

2023-06-25 17:17 UTC, AcK77 commented on src/Ryujinx/Modules/Updater/Updater.cs
>                          using (FileStream outStream = File.OpenWrite(outPath))
I don't think it will extend the lifetime too much.

2023-06-25 17:18 UTC, TSRBerry commented on src/Ryujinx/Program.cs
> +                    throw new NotSupportedException("Failed to initialize multi-threading support.");
If this fails we can't access any Xlib related methods from other threads. I'm not sure if we do this but if we don't then I can change it to a logging statement.

2023-06-25 17:21 UTC, AcK77 commented on src/Ryujinx/Program.cs
> +                    throw new NotSupportedException("Failed to initialize multi-threading support.");
Maybe @marysaka could help here!

2023-06-25 17:25 UTC, TSRBerry commented on src/Ryujinx/Ui/MainWindow.cs
>                                                                            _accountManager,
Should be resolved now!

2023-06-25 17:25 UTC, TSRBerry commented on src/Ryujinx/Ui/MainWindow.cs
> +                            _currentEmulatedGamePath);
This as well!

2023-06-25 17:39 UTC, TSRBerry commented on src/Ryujinx/Ui/Windows/AboutWindow.Designer.cs
>                  Halign      = Align.End,
dotnet format seems to exclude generated files like `.Designer.cs` files.

It might be added automatically again with new UI changes. Want me to manually remove it for now?

2023-06-27 15:13 UTC, marysaka approved these changes
some notes

2023-06-27 15:13 UTC, marysaka commented on src/Ryujinx/Ui/Windows/UserProfilesManagerWindow.Designer.cs
> +                MarginStart = 30
Need someone to test this PR on Windows as I think that could possibly not be present on the version we use of GTK3.

2023-06-27 15:13 UTC, marysaka commented on src/Ryujinx/Program.cs
> +                    throw new NotSupportedException("Failed to initialize multi-threading support.");
If this fail, when starting a game it will crash, I think we would prefer this to crash at startup?

2023-06-27 18:35 UTC, TSRBerry commented on src/Ryujinx/Ui/Windows/UserProfilesManagerWindow.Designer.cs
> +                MarginStart = 30
There were issues unrelated to that, but they are fixed now! 2 community testers also said it works fine, so I think this is good now!

2023-07-01 21:32 UTC, AcK77 approved these changes
Should be good instead of my 2 comments!

2023-07-01 21:32 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                Name = "Switch Executables"
This isn't resolved.

2023-07-01 21:32 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +                            Name = "GUI.FirmwareInstallerThread"
Still not resolved

2023-07-01 22:25 UTC, merged