Headless: Add support for Scaling Filters, Anti-aliasing and Exclusive Fullscreen
Ryujinx/Ryujinx pull request #5412
Opened 2023-06-29 05:18 UTC by theundebruijn

This PR adds several features to the Headless SDL2 client:

_Missing feature(s) added:_
`Scaling Filters (Bilinear, Nearest, FSR)`, `Anti-aliasing (None, FXAA, SMAA (all levels))`

_New feature(s) added:_
`Support for an Exclusive Fullscreen mode`

All features mentioned come with CLI options. These, with their descriptions, are added to the Headless' `Options.cs`.
Here's an example of how to launch a game using them:
```
Ryujinx.Headless.SDL2(.exe) --display-id 0 --exclusive-fullscreen --exclusive-fullscreen-width 3840 --exclusive-fullscreen-height 2160 --anti-aliasing "SmaaUltra" --scaling-filter "Fsr" --scaling-filter-level 10 "<path to>.xci"
```
**_NOTE: to exit the app on macOS when using Exclusive Fullscreen use `cmd + option + shift + escape`_.**
**_NOTE: we really do need some global keyboard shortcuts for headless. Would be a good next PR._**

---

This PR builds on top of https://github.com/Ryujinx/Ryujinx/pull/5339
Closes: https://github.com/Ryujinx/Ryujinx/issues/4508

---

#### TODO's

_Implementation_ :
- [x] Implement `Scaling Filter` logic
- [x] Add `Scaling Filter` options to the Headless CLI
- [x] Implement `Anti-Aliasing` logic
- [x] Add `Anti-aliasing` options to the Headless CLI
- [x] Implement `Exclusive Fullscreen` logic (OpenGL + Vulkan)
- [x] Add `Exclusive Fullscreen` options to the Headless CLI

_Testing_ :
- [x] Windows 11 (22H2) (Intel x64) — Nvidia (Vulkan + OpenGL)
- [x] MacOS 12.x (Intel x64) — AMD (Vulkan)
- [x] MacOS 13.x (ARM64) — Apple Silicon (Vulkan) (tyvm @siegmund-heiss-ich)
- [x] Linux (Fedora Workstation 38) (Intel x64) (Wayland) — AMD (Vulkan + OpenGL)
- [x] Linux (Fedora Workstation 38) (Intel x64) (X11) — AMD (Vulkan + OpenGL)

---

### About Exclusive Fullscreen

Exclusive Fullscreen mode has been a feature of many games and applications as it can help to significantly reduce the overhead of the display stack. Resulting in (ideally) much lower application latency.

The second reason is to add 'native' support for VRR technology such as Nvidia's G-SYNC. Using VRR on supported systems results in, once again, lower latency, as it overrides the VSync functionality to draw frames as soon as they're ready.

To use VRR with the current Ryujinx we need to use the nvcp to set the present method to 'Prefer layered on DXGI Swapchain'. Which - while it impressively works - likely has performance implications, is rather unintuitive and doesn't give us control over what's happening.

### How

This (rather small) PR updates the Headless SDL2 implementation to use the `SDL_WINDOW_FULLSCREEN` flag to set the correct window mode. It also uses `Ryujinx.Common.SystemInterop` to force DPI awareness as that screws up the scaling in this mode.

It adds a couple extra options to the Headless CLI: `--exclusive-fullscreen, --exclusive-fullscreen-width` and `--exclusive-fullscreen-height` which are needed as we no longer inherit the desktop properties. An additional `--display-id` option has been added that allows the user to choose which display to use.

### Does it work?

Well, yes. It successfully sets an exclusive fullscreen mode and Ryujinx renders things as expected.
VRR (G-SYNC in my case) gets triggered automatically, without any nvcp overrides, and overall application latency seems to be _much_ reduced.

#### Windows latency reduction

To make sure I'm not experiencing massive placebo effects here's some quick test results using [PresentMon](https://github.com/GameTechDev/PresentMon):

Measured latency using Headless in `Hardware: Legacy Flip` mode (Exclusive Fullscreen):
<img width="674" alt="Screenshot 2023-06-29 010730" src="https://github.com/Ryujinx/Ryujinx/assets/504559/49c51d39-ca02-464a-b9c7-f3fd19ecac8d">

Measured latency using the existing GTK client:
<img width="674" alt="Screenshot 2023-06-29 010907" src="https://github.com/Ryujinx/Ryujinx/assets/504559/2ea252ec-eb2e-45b2-a710-9c74f7e683fb">

Measured latency using the existing Avalonia client:
<img width="674" alt="Screenshot 2023-06-29 011851_" src="https://github.com/Ryujinx/Ryujinx/assets/504559/195c91c5-f550-4056-9d63-73d76ec994fa">

The Ava client is particularly slow (both in windowed and fullscreen mode). Indicative of why it can feel sluggish at times.

#### macOS (Apple Silicon) output

Metal Performance HUD - Headless (Exclusive Fullscreen) (macOS 13.4.1):
<img width="810" alt="ryujinx_arm_headless-exclusivefullscreen" src="https://github.com/Ryujinx/Ryujinx/assets/504559/241320ef-2026-44e0-a961-4fe740353fee">

Metal Performance HUD - Avalonia (Fullscreen) (macOS 13.4.1):

**_NOTE: Please don't look at the FPS, that just happened to be fluctuating._**
<img width="810" alt="ryujinx_arm_ava-fullscreen" src="https://github.com/Ryujinx/Ryujinx/assets/504559/a7788a2f-a01b-44bb-9a5d-c2d06c24fda7">

@siegmund-heiss-ich was particularly inventive and tried measuring latency on macOS - in the absence of tools like PresentMon - by comparing the audio latency between physical button press and the sound output in Super Mario Odyssey. He found a noticeable reduction by switching to exclusive fullscreen.

Please keep in mind testing was limited to a couple manual scenarios ran between the two of us.

<img width="631" alt="Bildschirmfoto_2023-07-06_um_18 32 02" src="https://github.com/Ryujinx/Ryujinx/assets/504559/ddc7c0f3-8426-45f1-80ed-36b7a150d551">

#### VRR (G-SYNC) support

Finally, besides the potential latency improvements, here's a photo of the Nvidia driver indicating that G-SYNC is actually active:
![IMG_5581](https://github.com/Ryujinx/Ryujinx/assets/504559/0ce3f5d5-2663-4366-b493-23f8c6b2f580)

2023-06-29 07:24 UTC, Foul-Tarnished commented
Why does Avalonia do Composed : Copy with GPU GDI instead of hardware composed : independant flip ? 💀 
As far as I'm aware, and as a SpecialK user, this seems to be just way worse

2023-07-06 13:40 UTC, siegmund-heiss-ich commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +                        if (!IsFullscreen || !IsExclusiveFullscreen)
Logic error (use &&)
With this changes fullscreen and also exclusive fullscreen works on macOS.

2023-07-06 15:05 UTC, siegmund-heiss-ich commented
Everything in this PR addressed works fine now on Apple Silicon.

2023-07-08 07:51 UTC, marysaka requested changes

2023-07-08 07:51 UTC, marysaka commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +
Why is not using variants of the enum directly?

2023-07-08 10:54 UTC, marysaka approved these changes
One comment otherwise seems fine :+1:

2023-07-08 10:54 UTC, marysaka commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +        public Ryujinx.Common.Configuration.ScalingFilter ScalingFilter { get; set; }
Can't use do a ``using Ryujinx.Common.Configuration;``  to import that namespace?

If you do then you can change this to:

```suggestion
        public AntiAliasing AntiAliasing { get; set; }
        public ScalingFilter ScalingFilter { get; set; }
```

2023-08-16 21:27 UTC, AcK77 commented on src/Ryujinx.Headless.SDL2/WindowBase.cs
> +        public Ryujinx.Common.Configuration.ScalingFilter ScalingFilter { get; set; }
You can do:

`using AntiAliasing = Ryujinx.Common.Configuration.AntiAliasing;`

And same for `ScalingFilter`

2023-09-24 02:17 UTC, AcK77 approved these changes
I haven’t tested it but code-wise it LGTM!

2023-09-24 11:56 UTC, TSRBerry reviewed
Sorry for the late review! Everything lgtm, I just have one change request.

2023-09-24 11:56 UTC, TSRBerry commented on src/Ryujinx.Headless.SDL2/Options.cs
> +        [Option("exclusive-fullscreen-width", Required = false, Default = 1280, HelpText = "Set horizontal resolution for exclusive fullscreen mode.")]
```suggestion
        [Option("exclusive-fullscreen-width", Required = false, Default = 1920, HelpText = "Set horizontal resolution for exclusive fullscreen mode.")]
```
Lets default to the resolution in docked mode

2023-09-24 11:56 UTC, TSRBerry commented on src/Ryujinx.Headless.SDL2/Options.cs
> +        [Option("exclusive-fullscreen-height", Required = false, Default = 720, HelpText = "Set vertical resolution for exclusive fullscreen mode.")]
```suggestion
        [Option("exclusive-fullscreen-height", Required = false, Default = 1080, HelpText = "Set vertical resolution for exclusive fullscreen mode.")]
```

2023-09-25 21:13 UTC, TSRBerry approved these changes
Lgtm, thank you! :D

(And sorry again for the late review :sweat_smile:)

2023-09-25 21:40 UTC, merged

2024-07-02 15:55 UTC, SixelAlexiS90 commented
@theundebruijn Hi! I want to thank you for adding this features on Headless, especially for the Exclusive Fullscreen, it's a game changer.
I'm using this version now since Avalonia completely got rid of Exclusive Fullscreen support, which is a big shame, especially considering that Exclusive Fullscreen WAS supported on the old "GTK" UI.
Exclusive Fullscreen was enabled by default on OpenGL once you got into the fullscreen mode while with Vulkan it could be forced via a "trick", I talked about it back then:
https://github.com/Ryujinx/Ryujinx/issues/4505

With Avalonia the Exclusive Fullscreen isn't a thing at all, which is a downgrade.
I don't know why they are relying on _Prefer layered on DXGI Swapchain_ only since, as you said, it can introduce a performance hit and it isn't as reliable, for example in my case DXGI swapchian doesn't work on Ryujinx, talked about this issue here:
https://github.com/Ryujinx/Ryujinx/pull/6645#issuecomment-2186746292

At least now I can use Ryujinx with a proper Gsync support thanks to your implementation so thank you very much!
I still hope they will re-integrate Exclusive Fullscreen to Avalonia since it's the only emulator I've seen that doesn't use it, especially when we talk about Vulkan.