[Ava]: Fix Cursor States On Windows
Ryujinx/Ryujinx pull request #5415
Opened 2023-06-29 13:04 UTC by Exhigh

With this PR, cursor states on windows should be finally fixed for good. The main reason for the issue persisting across commits was the fact that the cursor's position updates while the game was being rendered wasn't being updated with regards to the scaling factor of the system, which led to an empty area, where the cursor's position wasn't considered within the rendering area. Also, previously the cursor, was rendered on every draw of the frame, which when we hide the cursor leads to the cursor flickering. Which has been fixed as of this PR.

Testing needs to be done to ensure that this PR, fixes the issue on systems with different configurations ( Resolutions and Scaling Factor ) and on ( MacOS & Linux ) to ensure their functionality hasn't been broken.

2023-06-29 13:08 UTC, TSRBerry commented
@patrick-hovsepian are you okay with this? Since you opened a similar PR and closed it a few minutes ago, I'm wondering if that was done for this PR or if there were other reasons.

2023-07-06 13:33 UTC, marysaka requested changes
Apologies I forgot to send my review yesterday :sweat: 

Seems mostly fine to me but quite complicated... we need people to test this to ensure nothing breaks :+1:

2023-07-06 13:33 UTC, marysaka commented on src/Ryujinx.Ava/AppHost.cs
> +        private bool _changeCursorState = false;
I was thinking maybe to simplify that logic, you could create a private enum with two flags instead?

2023-07-06 20:33 UTC, Exhigh commented on src/Ryujinx.Ava/AppHost.cs
> +        private bool _changeCursorState = false;
Have a look at commit [#Feedback](https://github.com/Ryujinx/Ryujinx/pull/5415/commits/58344e6d8d642805186bb6e80497559d465ced92) and let me know if this is what was intended.

2023-07-06 20:33 UTC, Exhigh commented on src/Ryujinx.Ava/AppHost.cs
> +                _changeCursorState = false;
addressed in the latest commit

2023-07-06 20:33 UTC, Exhigh commented on src/Ryujinx.Ava/AppHost.cs
> +                _changeCursorState = false;
addressed in the latest commit

2023-07-08 16:00 UTC, Exhigh commented on src/Ryujinx.Ava/AppHost.cs
> +        private bool _changeCursorState = false;
@marysaka

2023-07-16 13:42 UTC, jojodunet commented
@Exhigh Have the requested changes been addressed? (I still see the requested changes status)

2023-07-16 13:49 UTC, Exhigh commented
That's just Github being Github, i have made the changes, tho it needs to be reviewed / looked at.

2023-07-16 14:03 UTC, jojodunet commented
> That's just Github being Github, i have made the changes, tho it needs to be reviewed / looked at.

Tried Experimental GUI (Avalonia) [241c96a](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/806134244.zip)
Windows 10
NVidia GTX 1070M
Ryujinx.Ava.exe -f --hide-cursor Always game.nsp

The mouse cursor is still visible upon launching the game and on the game window.
I need to move the mouse (just a little) for it to disappear from the window.

2023-07-16 14:12 UTC, Exhigh commented
hmmm, i don't remember having that said issue, will look into it, but prior to this patch the cursor wouldn't hide itself right ?

2023-07-16 14:16 UTC, jojodunet commented
> hmmm, i don't remember having that said issue, will look into it, but prior to this patch the cursor wouldn't hide itself right ?

Yes exactly

2023-07-16 14:18 UTC, Exhigh commented
can you test where rather than moving your mouse on the screen after launching from the commandline, try pressing a mousebutton and see if it causes the cursor to hide itself.

2023-07-16 19:02 UTC, jojodunet commented
> can you test where rather than moving your mouse on the screen after launching from the commandline, try pressing a mousebutton and see if it causes the cursor to hide itself.

The mouse cursor still persists when I try to press both the right or left mouse buttons.

2023-07-16 19:40 UTC, Exhigh commented
okie, will look into the issue.

2023-07-19 08:36 UTC, Exhigh commented
> > can you test where rather than moving your mouse on the screen after launching from the commandline, try pressing a mousebutton and see if it causes the cursor to hide itself.
> 
> The mouse cursor still persists when I try to press either the right or left mouse button.

@jojodunet Could you test with the latest commit and let me know if it fixes the issue. Hopefully it should

2023-07-19 12:24 UTC, jojodunet commented
@Exhigh Could you please rebase ?

2023-07-19 13:41 UTC, Exhigh commented
Its already rebased, its waiting on the PR workflow approval.

2023-07-19 15:03 UTC, Exhigh commented
> @Exhigh Could you please rebase? I still see the old PR build from 4 days ago.

For testing as of now, you could download the win artifact from [Build Artifact](https://github.com/Ryujinx/Ryujinx/actions/runs/5596885945), linux debug build test seems to be bugging out, for now this should do.

2023-07-19 17:24 UTC, jojodunet commented
Tried Experimental GUI (Avalonia) [aec4e5a](https://github.com/Ryujinx/Ryujinx/suites/14404392925/artifacts/813004046)
Windows 10
NVidia GTX 1070M
Ryujinx.Ava.exe -f --hide-cursor Always game.nsp

I have tested it, and here's my observation:

> The mouse cursor is present during the game loading.
> The mouse cursor disappears on its own at the first frame of the game.

Maybe I'm asking for too much, but would it be possible not to see the cursor at all?

In my use case, it's not really an issue as I won't have a mouse, but I have also noticed the following. 
(Could this be an issue for those who don't want to see the cursor regardless of the use case?)"

> The mouse cursor reappears on the game image if you move the mouse (whether in fullscreen or windowed mode).
> In windowed mode, I had thought that the cursor should only be visible at the emulator's menu level.
> From time to time, when moving the mouse actively, the cursor disappears again.

2023-07-19 17:38 UTC, Exhigh commented
> The mouse cursor is present during the game loading.
> The mouse cursor disappears on its own at the first frame of the game.

This is by design, I feel like the cursor should be visible while the game is loading, inferring that the game hasn't started yet. I could change this behavior but would need feedback from the devs.

> The mouse cursor reappears on the game image if you move the mouse (whether in fullscreen or windowed mode).
> In windowed mode, I had thought that the cursor should only be visible at the emulator's menu level.
> From time to time, when moving the mouse actively, the cursor disappears again.

Could you explain this statement, what was the cursor hide state (i.e whether the cursor hide state was Always, OnIdle or Never) and also whether direct mouse input was enabled or disabled. Also if possible attach a video showing the incident.
If you don't mind sharing which game are you seeing this issue, i know that the game doesn't matter but just to make sure nothing weird is happening.

2023-07-19 18:54 UTC, jojodunet commented
All observations are done on my side with the same command line " Ryujinx.Ava.exe -f --hide-cursor Always game.nsp "

I'm not sure how to share a video, but I would be interested in receiving more feedback from other users' experiences.

I tested with different games. 
I tested with both Direct mouse input enabled and disabled.

> In my use case, it's not really an issue as I won't have a mouse, but I have also noticed the following. (Could this be an issue for those who don't want to see the cursor regardless of the use case?)"
> 
> > The mouse cursor reappears on the game image if you move the mouse (whether in fullscreen or windowed mode).
> > In windowed mode, I had thought that the cursor should only be visible at the emulator's menu level.
> > From time to time, when moving the mouse actively, the cursor disappears again.

The observation above only appears when I move the mouse. 

> > In windowed mode, I had thought that the cursor should only be visible at the emulator's menu level.
> 
> It does and it also does for the status bar so that the users can interact with the menu. what's the question for this behavior ?

Once the cursor has reappeared on the game's rendering image because (and only if) you move the mouse, that is no longer the case and the cursor is visible everywhere.

> > From time to time, when moving the mouse actively, the cursor disappears again.
> 
> Within the render region or how exactly and if possible explain the reproduction steps.

On the game's rendering image (render region).
Reproduction steps: 
Just move the mouse, and then you could see the cursor reappears and disappears randomly.

2023-07-19 19:22 UTC, Exhigh commented
If possible could you post a log file for the run and provide a screencapture of the events happening. As I am not able to reproduce the said issues. Also which win10 version are you running ?

2023-07-23 19:47 UTC, jojodunet commented
Tried Experimental GUI (Avalonia) [aec4e5a](https://github.com/Ryujinx/Ryujinx/suites/14404392925/artifacts/813004046)
Windows 11 Home 22H2
With a different mouse than the one used in the previous tests
Ryujinx.Ava.exe -f --hide-cursor Always game.nsp

The cursor is still present during game loading. It seems to work fine in fullscreen, but switching to windowed mode breaks the feature. Returning to fullscreen makes it work fine.

It is fully broken under Windows, as shared above.

2023-08-29 08:51 UTC, marysaka approved these changes

2024-04-26 15:10 UTC, Exhigh commented
Re-Opening A New PR Instead of Updating This PR, since its been stale for some time now.

2024-04-26 15:10 UTC, closed without merging