Log when `IFileSystem.Commit()` fails due to `PathAlreadyInUse`
Ryujinx/Ryujinx pull request #5418
Opened 2023-06-30 08:10 UTC by jamestiotio

When the filesystem resource is already in use by another process, the call to `IFileSystem.Commit()` might fail with a result code of `PathAlreadyInUse`. This commit adds a warning log when this occurs to inform the user. This is because the resource might not have been released by other processes on the user's machine. The actual issue resolution will be left to the user since the root cause might wildly vary depending on what processes are running.

Related Issue: #5024

Note that this commit technically does not actually resolve the issue above. It simply helps the user with debugging purposes.

Signed-off-by: James Raphael Tiovalen <jamestiotio@gmail.com>

2023-06-30 12:11 UTC, jamestiotio commented
Note that I did consider implementing a more "permanent" solution to this issue. However, after thinking about it, the only way to truly free up filesystem resources locked by other processes on the system from Ryujinx's side is by killing those processes, which seems a little overkill and destructive. Killing random processes just because we want to access the files might also result in unwanted side effects such as file corruption. We also cannot and should not assume the user's intention of prioritizing Ryujinx's actions of committing filesystem changes since those other processes might be important. Thus, I ended up with this PR which just logs a simple warning. That way, the user can ultimately decide what to do to resolve the issue.

2023-07-07 15:31 UTC, jamestiotio commented
Oh also, while I have solved the original issue (#5024) via Thealexbarney/LibHac#276, I still recommend adding this logging since I found it significantly helpful during debugging.

2023-07-07 21:40 UTC, marysaka requested changes
apart from comment nothing much to say.

I'm not sure if we want this in the emulator tbh, any thoughts @gdkchan?

2023-07-07 21:40 UTC, marysaka commented on src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs
> +            return resCode;
This should be spaced correctly.

Also use resultCode instead of resCode

2023-07-07 22:17 UTC, Thealexbarney commented
I should note that the proposed solution for fixing the issue won't really work

2023-08-16 20:24 UTC, AcK77 requested changes

2023-08-16 20:24 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs
> +            if ((result.IsFailure()) && (resultCode == ResultCode.PathAlreadyInUse))
```suggestion
            if (result.IsFailure() && resultCode == ResultCode.PathAlreadyInUse)
```

2023-08-16 20:24 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Fs/FileSystemProxy/IFileSystem.cs
> +
Remove extra empty line

2024-01-26 00:47 UTC, AcK77 commented
Superseeded by #5672

2024-01-26 00:47 UTC, closed without merging