Refactor `async` usage
Ryujinx/Ryujinx pull request #5516
Opened 2023-08-01 19:46 UTC by IsaacMarovitz

Depends on #4362

Changes:
- Removes `async void` usage
- Makes `LoadApplications()` async

2023-08-12 23:26 UTC, TSRBerry requested changes
This defintitely improves the responsiveness of the Avalonia GUI even further!

However some things seem a little off to me in this PR and I also think you forgot to edit a few lines.

I'll add a commit with some changes to `Updater.cs` shortly.

2023-08-12 23:26 UTC, TSRBerry commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +        private static async Task InstallUpdate(TaskDialog taskDialog, string updateFile)
I don't think this method should be async.

2023-08-12 23:26 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                    userId: new UserId((ulong)viewModel.AccountManager.LastOpenedUser.UserId.High, (ulong)viewModel.AccountManager.LastOpenedUser.UserId.Low));
```suggestion
                    new UserId((ulong)viewModel.AccountManager.LastOpenedUser.UserId.High, (ulong)viewModel.AccountManager.LastOpenedUser.UserId.Low));
```

2023-08-12 23:26 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                    await Dispatcher.UIThread.InvokeAsync(Action);
```suggestion
                    await Dispatcher.UIThread.InvokeAsync(asymc () => await UserErrorDialog.ShowUserErrorDialog(UserError.NoKeys));
```

Everywhere else we inline these, so lets be consistent and do that here as well.

The UIThread isn't used a few lines below, this should probably be changed as well.

A few more lines below `Post()` is used instead of `InvokeAsync()`, did you do that on purpose?

2023-08-12 23:26 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +            Task.Run(() =>
Why is this done on another thread?

2023-08-12 23:26 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +            Task.Run(() =>
Same here. I'm pretty sure we can run this on the same thread.

2023-08-12 23:26 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +            Dispatcher.UIThread.InvokeAsync(() => Window.ViewModel.AppHost?.ShowExitPrompt());
This should already be the UIThread. I don't think it is necessary to do this here.

2023-08-12 23:26 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Views/Main/MainStatusBarView.axaml.cs
> +            Task.Run(Window.LoadApplications);
This doesn't seem right. You are running this on another thread from the UIThread and the function then runs another delegate on the UIThread.

2023-08-12 23:54 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +            Dispatcher.UIThread.InvokeAsync(() => Window.ViewModel.AppHost?.ShowExitPrompt());
Avalonia can't see async Task methods only async Void so I dispatched to get around it

2023-08-13 00:49 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +            Dispatcher.UIThread.InvokeAsync(() => Window.ViewModel.AppHost?.ShowExitPrompt());
> You use the void return type in asynchronous event handlers, which require a void return type.

https://learn.microsoft.com/en-us/dotnet/csharp/asynchronous-programming/async-return-types#void-return-type

These are event handlers and should be `async void`.

2023-08-13 00:51 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +            Task.Run(() =>
Please don't resolve conversations without a comment if you don't change the code.

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        ContentDialogHelper.CreateWarningDialog(
Fix the warning

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> +                        ContentDialogHelper.CreateWarningDialog(
Fix the warning

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                    new UserId((ulong)viewModel.AccountManager.LastOpenedUser.UserId.High, (ulong)viewModel.AccountManager.LastOpenedUser.UserId.Low));
I don't think splitted args are needed, at least you can remove `userId:`

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                            LocaleManager.Instance[LocaleKeys.DialogInvalidTitleIdErrorMessage]);
It's fine on one line

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                    viewModel.SelectedApplication.TitleName);
It's fine on one line

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                    viewModel.SelectedApplication.TitleName);
It's fine on one line

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
>                  UserResult result = await ContentDialogHelper.CreateConfirmationDialog(LocaleManager.Instance[LocaleKeys.DialogWarning],
above you put the first arg on a new line, here you don't.

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +                    await Dispatcher.UIThread.InvokeAsync(async () => await UserErrorDialog.ShowUserErrorDialog(UserError.NoKeys));
```suggestion
                    await Dispatcher.UIThread.InvokeAsync(async () => 
                        await UserErrorDialog.ShowUserErrorDialog(UserError.NoKeys)
                    );
```

2023-08-16 20:23 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> -            if (_isLoading)
I don't remember for what `_isLoading` is used, but double check it, I'm pretty it's to avoid something.

2023-08-16 22:11 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
> -            if (_isLoading)
I checked, it's unused

2023-08-29 19:38 UTC, riperiperi commented
Looks pretty good, game list definitely loads a lot faster (even from network drive) and I tested a bunch of other functions that changed and still seem to work properly. I haven't tested the updater though, which is probably the most important thing to ensure is working properly before merge...

2023-08-30 18:18 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/MainWindow.axaml.cs
>              _isLoading = false;
Good spot, fixed it

2023-09-02 14:13 UTC, TSRBerry approved these changes
Lgtm!

I just have one question left:
You replaced a lot of `Dispatcher.UIThread.Post` calls with `Dispatcher.UIThread.InvokeAsync`. Should we replace all of them or is there a reason only a few of them were changed?

2023-09-18 20:37 UTC, IsaacMarovitz commented
@TSRBerry I'm sure there was a perfectly logical reason when I wrote it, but it's been quite a while and I don't remember the specifics anymore.

2023-09-24 02:31 UTC, AcK77 reviewed
Do the updater been tested? Because some changes are a bit strange!
Maybe we should find something more consistent for the usage of `Dispatcher.UIThread.InvokeAsync()/Post()`

2023-09-24 02:31 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> -                Dispatcher.UIThread.Post(async () =>
Remove this don’t make `CreateWarningDialog()` block the UI?
(Same comment for all other same changes)

2023-09-24 02:31 UTC, AcK77 commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> -            await Task.Run(() =>
Making this part not async anymore should block the UI until the update is extracted, which is bad UX.

2023-09-25 19:12 UTC, TSRBerry commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> -            await Task.Run(() =>
That doesn't happen because the entire thing is already run async.
I tested the updater before pushing my commits.

2023-09-25 19:14 UTC, TSRBerry commented on src/Ryujinx.Ava/Modules/Updater/Updater.cs
> -                Dispatcher.UIThread.Post(async () =>
This is already called from the UI thread, so using another call to `Dispatcher.UIThread.Post()` is not necessary.

2023-09-25 22:03 UTC, AcK77 approved these changes

2023-09-25 22:04 UTC, merged