[INFRA] Addition of basic contributor guides and docs framework.
Ryujinx/Ryujinx pull request #5581
Opened 2023-08-16 19:30 UTC by MutantAura

All files and structure heavily inspired by the dotnet/runtime docs: https://github.com/dotnet/runtime/tree/main/docs

- Main contributor guide landing page.
- C# codestyle doc.
- Pull request guide doc.

Let me know if any references to the `dotnet/runtime` project remain in the files as these were used as a template due to their excellent quality. Draft for now to open a discussion.

2023-08-16 19:36 UTC, MutantAura commented on CONTRIBUTING.md
> +Ryujinx uses some implementations and frameworks from other projects. The following rules must be followed for PRs that include changes from another project:
Feedback on how this should be handled needed.

2023-08-16 19:36 UTC, MutantAura commented on docs/README.md
> +    ANY MORE? SVC GIST PERHAPS?
This section is used for code guidelines for specific projects in the `dotnet/runtime` repo. For instance it could be used on our end for gdkchan's IPC refactor guide in future. Feedback appreciated. Remove before merge if nothing noteworthy at the moment.

2023-08-16 19:36 UTC, MutantAura commented on docs/coding-guidelines/coding-style.md
> +C# Coding Style
General feedback here would be nice.

2023-08-16 19:36 UTC, MutantAura commented on docs/coding-guidelines/coding-style.md
> +20. XML docs should be used for [TODO].
Feedback required.

2023-08-16 19:36 UTC, MutantAura commented on docs/coding-guidelines/coding-style.md
> +``ShaderCache.cs:``
File used as the first example I had open. If anyone can suggest a better example as a case study that would be appreciated.

2023-08-16 19:36 UTC, MutantAura commented on docs/workflow/pr-guide.md
> +* Avoid rebasing your changes unless required or directly requested. If you are asked to make changes during the review process do them as a new commit.
Feedback required. Not sure what our general view on rebase vs merge is.

2023-08-16 20:11 UTC, AcK77 commented on CONTRIBUTING.md
> +Before filing a new issue, please search our [open issues](https://github.com/Ryujinx/Ryujinx/issues) to check if it already exists.
```suggestion
Before filing a new issue, please search our [opened issues](https://github.com/Ryujinx/Ryujinx/issues) to check if it already exists.
```

2023-08-16 20:11 UTC, AcK77 commented on CONTRIBUTING.md
> +Good bug reports make it easier for maintainers to verify and root cause the underlying problem. The better a bug report, the faster the problem will be resolved. Ideally, a bug report should contain
```suggestion
Good bug reports make it easier for maintainers to verify and root cause the underlying problem. The better a bug report, the faster the problem will be resolved.
Ideally, a bug report should contain the following information:
```

2023-08-16 20:16 UTC, MetrosexualGarbodor commented on CONTRIBUTING.md
> +Before filing a new issue, please search our [open issues](https://github.com/Ryujinx/Ryujinx/issues) to check if it already exists.
'open' is correct here

2023-08-16 20:56 UTC, MetrosexualGarbodor requested changes

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on CONTRIBUTING.md
> +Please read the entire document before continuing as it can potentially save everyone involved a signficiant amount of time.
signficiant > significant

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on CONTRIBUTING.md
> +* A Ryujinx log file of the run instance where the issue occured. Log files can be found in `[Executable Folder]/Logs` and are named chronologically.
occured > occurred

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on CONTRIBUTING.md
> +Please review any feature requests already opened to both check it has not already been suggested, and to familiarise yourself with the format. When ready to submit a proposal, please use the [Featur
familiarise > familiarize, since the majority of other words in the rest of the doc use the US spelling

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on CONTRIBUTING.md
> +* Random failure of the workflow can ocassionally result in a CI failure. In this scenario a maintainer will manually restart the job.
ocassionally > occasionally

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on docs/workflow/pr-guide.md
> +When submitting a PR to the `Ryujinx/Ryujinx` repository, various builds will run validating many areas to ensure we keep developer productivity and product quality high. These various workflows can
completition > completion, (yes the comma too)

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on docs/workflow/pr-guide.md
> +* We're human. We miss things. We forget things. If there has been radio silence on your changes for a substatial period of time then do not hesitate to reach out directly either with something simpl
substatial > substantial

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on docs/workflow/pr-guide.md
> +Typically, PRs are merged as one commit (squash merges). It creates a simpler history than a Merge Commit. "Special circumstances" are rare, and typically mean that there are a series of cleanly sepa
disect > dissect

2023-08-16 20:56 UTC, MetrosexualGarbodor commented on docs/workflow/pr-guide.md
> +From time to time we will review older PR's and check them for relevance. If we find the PR is inactive or no longer applies, we will close it. As the PR owner, you can simply reopen it if you feel y
PR's > PRs

2023-08-17 20:36 UTC, TSRBerry approved these changes
Lgtm, thank you very much for doing this! I wanted to have something like this for a long time now!

2023-08-17 20:36 UTC, TSRBerry commented on CONTRIBUTING.md
> +You can contribute to Ryujinx with issues and PRs. Contributing code and other implementations is greatly appreciated alongside simply filing issues for problems you encounter.
You can also contribute by testing PRs! :D

2023-08-17 20:36 UTC, TSRBerry commented on CONTRIBUTING.md
> +* [Ryujinx/Ryujinx-Website](https://github.com/Ryujinx/Ryujinx-Website) Ryujinx website source code.
```suggestion
* [Ryujinx/Ryujinx-Website](https://github.com/Ryujinx/Ryujinx-Website) Ryujinx website source code.
* [Ryujinx/Ryujinx-Ldn-Website](https://github.com/Ryujinx/Ryujinx-Ldn-Website)
```

2023-08-17 20:36 UTC, TSRBerry commented on CONTRIBUTING.md
> +9. When area owners have signed off, and all checks are green, your PR will be merged.
We don't really have code/area owners for Ryujinx, should this be worded differently?

2023-08-17 20:36 UTC, TSRBerry commented on CONTRIBUTING.md
> +Ryujinx uses some implementations and frameworks from other projects. The following rules must be followed for PRs that include changes from another project:
Current state lgtm! :D

2023-08-17 20:36 UTC, TSRBerry commented on docs/README.md
> +===============
```suggestion
# Documents Index
```

Lets be consistent and switch to `#` headings for this one.

2023-08-17 20:36 UTC, TSRBerry commented on docs/coding-guidelines/coding-style.md
> +===============
```suggestion
# C# Coding Style
```

Same as the last nitpick, just for consistency.

2023-08-17 20:36 UTC, TSRBerry commented on docs/coding-guidelines/coding-style.md
> +The general rule we follow is "use Visual Studio defaults".
Can we somehow add that any IDE/editor that supports `.editorconfig` will make following these a lot easier?

2023-08-17 20:36 UTC, TSRBerry commented on docs/workflow/pr-guide.md
> +All contributions to Ryujinx/Ryujinx repo are made via pull requests (PRs) rather than through direct commits. The pull requests are reviewed and merged by the repository maintainers after a review a
Since we don't have code/area owners, this might need to be reworded a bit.

```suggestion

All contributions to Ryujinx/Ryujinx repository are made via pull requests (PRs) rather than through direct commits. The pull requests are reviewed and merged by the maintainers after a review and at least two approvals from the core development team.
```
How does this sound?

2023-08-17 20:36 UTC, TSRBerry commented on docs/workflow/pr-guide.md
> +* Avoid rebasing your changes unless required or directly requested. If you are asked to make changes during the review process do them as a new commit.
I'd like people to rebase if required, ideally new changes shouldn't be merged and always integrated with a rebase of their branch.

2023-08-17 20:36 UTC, TSRBerry commented on docs/workflow/pr-guide.md
> +* To resolve merge conflicts, use "merge" instead of "rebase". CHECK THIS?!
For me both is fine, but I can see why merge would be preferred here.
It saves time and only requires you to address the actual merge conflict.
Although if you regularly rebase you often won't even see merge conflicts (depends on the nature of your PR of course).

2023-09-12 13:07 UTC, TSRBerry commented
@MutantAura could we add another sentence/section for PRs which says that we prefer people to resolve conversations as soon as they addressed them?

2023-09-19 17:20 UTC, marysaka commented on CONTRIBUTING.md
> +Ryujinx uses some implementations and frameworks from other projects. The following rules must be followed for PRs that include changes from another project:
lgtm but as a note I think it would be nice to have SPDX headers around someday.

2023-09-19 17:21 UTC, marysaka commented on docs/coding-guidelines/coding-style.md
> +20. XML docs should be used for [TODO].
I never use XML for TODOs tbh, only regular comments

```cs
// TODO: Something should be redone here, but I was too tired for this...
```

2023-09-19 17:24 UTC, marysaka commented on docs/coding-guidelines/coding-style.md
> +``ShaderCache.cs:``
Might need to craft a custom example that show all rules maybe....? not sure if that matter much tho.

2023-09-19 17:25 UTC, marysaka approved these changes
Sorry for the long delay here.

To me this seems fine :+1: 

Some random thought I had here: It would probably be good at one point to have a security report policy too (that I would probably be the one to handle?)

Anyway, great work here :+1:

2023-09-19 19:18 UTC, TSRBerry commented on docs/coding-guidelines/coding-style.md
> +20. XML docs should be used for [TODO].
We use XML docs mainly in interfaces right?

2023-09-19 19:36 UTC, marysaka commented on docs/coding-guidelines/coding-style.md
> +20. XML docs should be used for [TODO].
yup

2023-09-22 08:55 UTC, MutantAura commented on docs/coding-guidelines/coding-style.md
> +``ShaderCache.cs:``
I think this is fine for now. Tbh the whole repo is a living example so I dont think it matters too much.

2023-09-22 08:55 UTC, MutantAura commented on docs/workflow/pr-guide.md
> +* Avoid rebasing your changes unless required or directly requested. If you are asked to make changes during the review process do them as a new commit.
Adjusted.

2023-09-22 08:59 UTC, MutantAura commented
> @MutantAura could we add another sentence/section for PRs which says that we prefer people to resolve conversations as soon as they addressed them?

`* Only resolve GitHub conversations with reviewers once they have been addressed with a commit, or via a mutual agreement.` added to pr-guide.

> Some random thought I had here: It would probably be good at one point to have a security report policy too (that I would probably be the one to handle?)

As far as this goes I do agree, but I personally don't have the required knowledge to really write one. Guess it can be a follow up for anyone interested now that we have some structure to this.

2023-09-22 14:16 UTC, MetrosexualGarbodor approved these changes

2023-09-22 14:21 UTC, merged