pctl: Migrate service to Horizon
Ryujinx/Ryujinx pull request #5631
Opened 2023-08-31 10:54 UTC by IsaacMarovitz

2023-08-31 11:44 UTC, gdkchan reviewed
It would be nice  to change the parameter names to something more meaningful in the class and interfaces, for the functions that are implemented at least.

2023-08-31 11:44 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                    // TODO: Service store TitleId and FreeCommunicationEnabled in another static object.
Comment needs some proofreading.

2023-08-31 11:44 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                // TODO: It seems to checks if an entry exists in the FreeCommunicationApplicationList using the TitleId.
Comment needs some proofreading.

2023-08-31 11:44 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                // TODO: It seems to checks if an entry exists in the FreeCommunicationApplicationList using the TitleId.
Comment needs some proofreading.

2023-08-31 11:44 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +            stereoVisionRestriction = false;
Why not just
```cs
stereoVisionRestriction = _stereoVisionRestrictionConfigurable && _stereoVisionRestriction;
```

2023-08-31 11:44 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                    // TODO: It signals an internal event of service. We have to determine where this event is used.
```suggestion
                    // TODO: It signals an internal event of the service. We have to determine where this event is used.
```

2023-08-31 11:44 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                isStereoVisionPermitted = true;
Why not just
```cs
isStereoVisionPermitted = result == Result.Success;
```

2023-08-31 11:44 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                if (appExemption)
I don't think the commented code is necessary (or makes sense, the `appExemption` variable doesn't exist so one would need to guess what it is supposed to be).

2023-08-31 12:52 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                    _parentalControlFlag = PctlFlagValue.FreeCommunication;
It seems that the previous implementation at least gets the correct value from the nacp. Would be nice to do the same here.

2023-08-31 12:54 UTC, IsaacMarovitz commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                    _parentalControlFlag = PctlFlagValue.FreeCommunication;
I'm not sure how to get the Application context in the new services implementation

2023-09-13 23:55 UTC, AcK77 requested changes

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                    _parentalControlFlag = PctlFlagValue.FreeCommunication;
It have to be passed from HLE to `HorizonStatic.Options`. But yeah the original NACP value is needed here.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                    // TODO: Services store TitleId and FreeCommunicationEnabled in a static object.
```suggestion
                    // TODO: Service store ApplicationId and FreeCommunicationEnabled in a static object.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                    // When initialisation is complete, signal an event on that static object.
```suggestion
                    //       When initialisation is complete, signal an event on that static object.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                // TODO: Checks if an entry exists in the FreeCommunicationApplicationList using the TitleId.
```suggestion
                // TODO: Checks if an entry exists in the FreeCommunicationApplicationList using the ApplicationId.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                // Returns FreeCommunicationDisabled if entry doesn't exist.
```suggestion
                //       Returns FreeCommunicationDisabled if entry doesn't exist.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +using Result = Ryujinx.Horizon.Common.Result;
Since LibHac isn't used here, I wonder why is it needed here.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +using TimeSpan = Ryujinx.Horizon.Pctl.Types.TimeSpan;
I don't think `TimeSpan` type is part of `Pctl` in original service.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +            throw new NotImplementedException();
This make no sense. Ignore missing services option is already handled elsewhere so that should be removed.

(Same for similar IPCs)

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +        [CmifCommand(1013)] // 4.0.0+
```suggestion
        [CmifCommand(1013)]
```

We do not put firmware version as comment anymore.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                // TODO: Checks if an entry exists in the FreeCommunicationApplicationList using the TitleId.
```suggestion
                // TODO: Checks if an entry exists in the FreeCommunicationApplicationList using the ApplicationId.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                // Returns FreeCommunicationDisabled if entry doesn't exist.
```suggestion
                //       Returns FreeCommunicationDisabled if entry doesn't exist.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                return PctlResult.PermissionDenied;
```suggestion

                return PctlResult.PermissionDenied;
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +                stereoVisionRestriction = default;
```suggestion
                stereoVisionRestriction = default;

```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlService.cs
> +            // Since we don't support the pctl savedata for now, this can be implemented later.
```suggestion
            //       Since we don't support the pctl savedata for now, this can be implemented later.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlServiceFactory.cs
> +        public Result CreateService(out IPctlService pctlService, ulong arg1, [ClientProcessId] ulong pid)
`arg1` is the pid placedholder, I don't think this is needed anymore.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Ipc/PctlServiceFactory.cs
> +        public Result CreateServiceWithoutInitialize(out IPctlService pctlService, ulong arg1, [ClientProcessId] ulong pid)
`arg1` is the pid placedholder, I don't think this is needed anymore.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/PctlIpcServer.cs
> +            _serverManager.RegisterObjectForServer(new PctlServiceFactory(0x8040), ServiceName.Encode("pctl:r"), RMaxSessionsCount);
Could be nice to get them sorted by service name.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/PctlIpcServer.cs
> +            _serverManager.RegisterObjectForServer(new PctlServiceFactory(0x303), ServiceName.Encode("pctl"), MaxSessionsCount);
0x303 is the permission flag.
Maybe we should store them in an enum

```
enum PermissionFlag
{
    Normal = 0x303,
    Admin = 0x83BE,
    System = Admin,
    Recovery = 0x8040,
}

(Names are guessed)

Then the cast of `_permissionFlag` have to be changed in `ParentalControlServiceFactory` and `ParentalControlService`. Even when the Flag is checked.
```

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Types/AsyncData.cs
> +}
This is useless and do any sense at all since it's empty...
Same for a lot of other `Types`, it have to reflect what the original service do.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Pctl/IPctlService.cs
> +    internal interface IPctlService : IServiceObject
args have to be renamed to reflect the implementation when needed.

2023-09-13 23:55 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Pctl/IPctlServiceFactory.cs
> +        Result CreateServiceWithoutInitialize(out IPctlService pctlService, ulong arg1, ulong pid);
`arg1` is already a pid placeholder.

2023-09-14 00:16 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Types/AsyncData.cs
> +}
It is necessary since the function receives those structs as argument. The `Size` field above on the `StructLayout` attribute will force the struct to have the correct size, even if it's empty. Fields can be added once someones reverse the service and figure out what the struct looks like. The structs without `StructLayout` attribute and a explicit size are probably wrong though.

2023-09-14 00:17 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Types/AsyncData.cs
> +}
I mean, all those structs are used in unimplemented call, it's cleaner to remove the unimplemented call and the related types instead of fill everything with placeholders.

2023-09-14 00:20 UTC, gdkchan commented on src/Ryujinx.Horizon/Pctl/Types/AsyncData.cs
> +}
> I mean, all those structs are used in unimplemented IPCs, it's cleaner to remove the unimplemented IPCs and the related types instead of fill everything with placeholders.

IMO it's better to keep the empty implementation here. Then when the service is implemented, we just need to full it in, instead of adding the functions all over again, creating all the structs/enums again, etc which is more work.

2023-09-14 00:25 UTC, AcK77 commented on src/Ryujinx.Horizon/Pctl/Types/AsyncData.cs
> +}
That will be a mess to maintain in case a new firmware which add new IPCs is released.
And the structs/enums aren't in the good namespaces for most of them.
In `HLE` we currently just have needed IPCs and Types, which is more cleaner.

2023-10-17 17:49 UTC, IsaacMarovitz commented
To be overridden by @AcK77 in the future.

2023-10-17 17:49 UTC, closed without merging