Add support for multi game XCIs
Ryujinx/Ryujinx pull request #5638
Opened 2023-09-01 16:35 UTC by TSRBerry

Huge thank you to @piplup55 for his patience and the large amount of testing he did for me while I was trying to make this work!

This PR refactors a lot of the code used for application loading to use `.cnmt.nca` files.

Before we needed a lot more logic for checks that can now be reduced to simple reads of values in the `cnmt` files.

I wrapped `Cnmt` in a `ContentCollection` class which can also get the referenced `NCAs`, so that should be pretty simple now as well.

---

Eventually we should also replace all `ProgramIndex` logic with reads from `NACP`, but that's for another PR.

2023-09-01 17:08 UTC, piplup55 commented
this is all i could find i will update this as things are fixed or if i find more issues

### Known issues
- gta trilogy crashing with a (2002-4604)/(2002-4644) when no update is applied
- dlc not working

### Notes
- nsp's will show as having the title update if you enabled the bundled update
- selecting a older game version than on the cart may crash the game

2023-09-14 00:27 UTC, AcK77 requested changes
Some feedback after a quick review:

- `TitleId` should be `ApplicationId`.
- I haven't check GTK UI.

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> +                var saveDataFilter = SaveDataFilter.Make(viewModel.SelectedApplication.TitleId, saveDataType, userId, saveDataId: default, index: default);
```suggestion
                var saveDataFilter = SaveDataFilter.Make(viewModel.SelectedApplication.ApplicationId, saveDataType, userId, saveDataId: default, index: default);
```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/TitleUpdateModel.cs
> +        private bool IsXCI => System.IO.Path.GetExtension(Path)?.ToLower() == ".xci";
```suggestion
        private bool IsXci => Path.GetExtension(Path)?.ToLower() == ".xci";
```
And a using to `System.IO` ?

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +        private readonly ApplicationData _title;
```suggestion
        private readonly ApplicationData _applicationData;
```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +                _downloadableContentContainerList = new List<DownloadableContentContainer>();
```suggestion
                _downloadableContentContainerList = new List<DownloadableContentContainer>();

```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/DownloadableContentManagerViewModel.cs
> +            // Try to load DLCs from PFS first
```suggestion
            // NOTE: Try to load downloadable contents from PFS0 first.
```

(or `Partition File System`)

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> +        private ApplicationData _currentEmulatedApplication;
```suggestion
        private ApplicationData _currentApplicationData;
```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/MainWindowViewModel.cs
> -
I'd prefer to keep this extra empty line.

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/ViewModels/TitleUpdateViewModel.cs
> +        private ApplicationData Title { get; }
```suggestion
        private ApplicationData ApplicationData { get; }
```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Views/Main/MainMenuBarView.axaml.cs
> +                    TitleId = 0x0100000000001009ul,
is the `ul` really needed here ?

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.HLE/FileSystem/ContentCollection.cs
> +                    return _pfs.GetNca(keySet, $"/{ncaId}.nca");
```suggestion

                    return _pfs.GetNca(keySet, $"/{ncaId}.nca");
```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Processes/Extensions/NcaExtensions.cs
> +                        if ((updateTitleId & ~0x1FFFUL) != titleIdBase)
There is a bunch of duplicated ` & ~0x1FFFUL` in different classes, maybe we should use and helper somewhere to avoid duplicated code.

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Processes/Extensions/NcaExtensions.cs
> +            catch (HorizonResultException e)
```suggestion
            catch (HorizonResultException ex)
```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Processes/Extensions/PartitionFileSystemExtensions.cs
> +            var programs = new Dictionary<ulong, ContentCollection>();
I'm not sure about `programs` name here, but I can't find a better one :(

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx.HLE/Loaders/Processes/Extensions/PartitionFileSystemExtensions.cs
> +            errorMessage = $"Unable to load: Could not find Main NCA for title '{titleId:x16}'";
```suggestion
            errorMessage = $"Unable to load: Could not find Main NCA for title \"{titleId:x16}\"";
```

2023-09-14 00:27 UTC, AcK77 commented on src/Ryujinx/Ui/MainWindow.cs
> +        private ApplicationData _currentEmulatedApplication = null;
```suggestion
        private ApplicationData _currentApplicationData = null;
```

2023-09-14 14:53 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Models/TitleUpdateModel.cs
> +        private bool IsXCI => System.IO.Path.GetExtension(Path)?.ToLower() == ".xci";
It would use the Path defined above.

2023-09-14 15:45 UTC, TSRBerry commented on src/Ryujinx.HLE/Loaders/Processes/Extensions/NcaExtensions.cs
> +                        if ((updateTitleId & ~0x1FFFUL) != titleIdBase)
Yeah, we have one in NcaExtensions.cs iirc, but that doesn't work for ulongs and we shouldn't be doing that anyway.

2023-09-14 17:33 UTC, marysaka approved these changes

2023-10-09 13:12 UTC, gdkchan approved these changes
lgtm, but I'm not familiarized with this code, and I don't have any of those multi-game XCIs to test.

2023-10-28 19:02 UTC, gdkchan commented
This apparently has a regression on games that needs relaunch like Super Mario 3D All-Stars, so it can't be merged right now.

2023-10-29 00:28 UTC, TSRBerry commented
Any details on that? That should be a bug and I should be able to fix that.

2023-10-31 17:48 UTC, AcK77 approved these changes
I haven't tested the PR build. But code-wise this LGTM! Nice job!

2023-10-31 17:48 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> -                        await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance[LocaleKeys.DialogRyujinxErrorMessage], LocaleManager.Instance[LocaleKeys.DialogInvalidTitleIdErrorMessage]);
Why was the error dialog removed ?

2023-10-31 17:48 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/DownloadableContentModel.cs
> +        private bool IsXci => Path.GetExtension(FileName)?.ToLower() == ".xci";
Is that really needed and can't be directly in the `Label` property above ?

2023-10-31 17:48 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Models/TitleUpdateModel.cs
> +        private bool IsXci => System.IO.Path.GetExtension(Path)?.ToLower() == ".xci";
Is that really needed and can't be directly in the `Label` property above ?

2023-10-31 18:12 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> -                        await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance[LocaleKeys.DialogRyujinxErrorMessage], LocaleManager.Instance[LocaleKeys.DialogInvalidTitleIdErrorMessage]);
Uhhh this night have been a mistake. I'll check that when I get home.

2023-11-11 15:43 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Controls/ApplicationContextMenu.axaml.cs
> -                        await ContentDialogHelper.CreateErrorDialog(LocaleManager.Instance[LocaleKeys.DialogRyujinxErrorMessage], LocaleManager.Instance[LocaleKeys.DialogInvalidTitleIdErrorMessage]);
Okay nvm, this wasn't a mistake. The error can't occur since we don't need to parse the string anymore. We can directly pass the ulong now.

2023-11-11 20:56 UTC, marysaka approved these changes

2023-11-11 20:56 UTC, merged

2023-11-12 02:37 UTC, gdkchan commented
This was reverted because it is no longer possible to add DLCs on games with the XCI format on GTK UI. Apparently it is also not possible to launch said games if they have a DLC enabled, but I did not test that part.