Add ldn:u implementation, INetworkClient interface and DisabledLdnClient
Ryujinx/Ryujinx pull request #5652
Opened 2023-09-04 22:10 UTC by TSRBerry

This PR is part of our ongoing effort to upstream our LDN implementation (#4716).

I tried my best to preserve as many commits as possible, but since the initial `ldn:u` implementation was closely connected to `RyuLDN` I had to filter and modify a few of them. But if you take a look at the commit history you should be able to see the timeline following the author dates (the first commit was made on 21.07.2020 at 16:13).

This also contains some of the UI changes, a few fixes and the interface `INetworkClient` which can be used for different multiplayer modes / network protocols. It is also used by the dummy `DisabledNetworkClient` implementation, which Ryujinx will use as a default for now.

2023-09-04 23:10 UTC, gdkchan reviewed
Not a full review, I just took a quick look.

2023-09-04 23:10 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +        private const int NIFM_REQUEST_ID = 90;
I think those names violate our naming conventions?

2023-09-04 23:10 UTC, gdkchan commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationFileFormat.cs
> +        /// Multiplayer Mode
Missing `/// <summary>`.

2023-09-04 23:10 UTC, gdkchan commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            // configurationFileFormat.Version == 13 -> LDN1
Do we really need those comments?

2023-09-04 23:12 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +        private const int NIFM_REQUEST_ID = 90;
Oh true, they do! Will fix that.

2023-09-05 03:26 UTC, sakuka47 commented
Does this Pr signal the end of the ldn version?

2023-09-05 03:41 UTC, GamerzHell9137 commented
> Does this Pr signal the end of the ldn version?

No

2023-09-05 16:08 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            // configurationFileFormat.Version == 13 -> LDN1
I guess not, but can't hurt to keep them, right?

2023-09-11 18:52 UTC, gdkchan reviewed
Looking at the code makes me wish it used the new IPC, it would be so much cleaner.

2023-09-11 18:52 UTC, gdkchan commented on Directory.Packages.props
> +    <PackageVersion Include="NetCoreServer" Version="3.0.12" />
Why do we need this dependency?

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.Common/Memory/StructArrayHelpers.cs
> +
Double empty line.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.Common/Utilities/NetworkHelpers.cs
> +            byte[] addressBytes = ipAddress.GetAddressBytes();
I think it would be simpler, more efficient and more correct to do `return BinaryPrimitives.ReadUInt32BigEndian(ipAddress.GetAddressBytes());`

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                 || controlProperty.LocalCommunicationId[6] == localCommunicationIdChecked) | (controlProperty.LocalCommunicationId[7] == localCommunicationIdChecked);
the ` | (controlProperty.LocalCommunicationId[7] == localCommunicationIdChecked)` here is a bit odd, why is it not using a short-circuiting operator like the others?

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            // NOTE: Return ResultCode.InvalidArgument if _state is null, doesn't occur in our case.
```suggestion
            // NOTE: Returns ResultCode.InvalidArgument if _state is null, doesn't occur in our case.
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            // NOTE: Return ResultCode.InvalidArgument if _disconnectReason is null, doesn't occur in our case.
```suggestion
            // NOTE: Returns ResultCode.InvalidArgument if _disconnectReason is null, doesn't occur in our case.
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            // NOTE: Return ResultCode.InvalidArgument if _disconnectReason is null, doesn't occur in our case.
This comment doesn't make sense since `_disconnectReason` is not a pointer/reference type, so it can't be null.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            // Return ResultCode.InvalidArgument if handle is null, doesn't occur in our case since we already throw an Exception.
```suggestion
            // Returns ResultCode.InvalidArgument if handle is null, doesn't occur in our case since we already throw an Exception.
```
And what is "handle"? There is no variable called `handle` here.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +
```suggestion
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            _ = context.RequestData.ReadUInt32(); // Alignment?
```suggestion
            context.RequestData.ReadUInt32(); // Alignment?
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            _ = context.RequestData.ReadUInt32(); // Alignment?
Could also use seek.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            // NOTE: Calls nifm service and return related result codes.
```suggestion
            // NOTE: Calls nifm service and returns related result codes.
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +
```suggestion
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            _station?.Dispose();
Why not call `CloseStation()` instead?

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            _accessPoint?.Dispose();
Why not call `CloseAccessPoint()` instead?

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            //       This call twice InitializeImpl(): A first time with NIFM_REQUEST_ID, if its failed a second time with nifm_request_id = 1.
```suggestion
            //       This calls InitializeImpl() twice: The first time with NIFM_REQUEST_ID, and if it fails, a second time with nifm_request_id = 1.
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            //       This call twice InitializeImpl(): A first time with NIFM_REQUEST_ID, if its failed a second time with nifm_request_id = 1.
Maybe the first part is supposed to say "with nifm_request_id = 0"? It seems a bit confusing.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            //       Since we proxy connections, we don't needs to get the ip_address, subnet_mask and nifm_request_id.
```suggestion
            //       Since we proxy connections, we don't need to get the ip_address, subnet_mask and nifm_request_id.
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                    // NOTE: Service calls nn::ldn::detail::NetworkInterfaceManager::NetworkInterfaceMonitor::Initialize() with nifmRequestId as argument.
```suggestion
                    // NOTE: Service calls nn::ldn::detail::NetworkInterfaceManager::NetworkInterfaceMonitor::Initialize() with nifmRequestId as argument,
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                    //       Then it stores the result code of it in a global field. Since we use our own implementation, we can just check the connection
```suggestion
                    //       then it stores the result code of it in a global field. Since we use our own implementation, we can just check the connection
```
Maybe it should say "global variable" rather than "global field"?

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                    if (System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable())
Add `using System.Net.NetworkInformation;`?

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                        NetworkClient.SetGameVersion(context.Device.Processes.ActiveApplication.ApplicationControlProperties.DisplayVersion.Items.ToArray());
I guess this one is missing a comment about calling `arp` service once it is implemented?

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            NetworkClient?.DisconnectAndStop();
Move those inside the `if` above? Then you can remove the `?`.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/Network/Types/CreateAccessPointRequest.cs
> +        // Advertise data is appended separately. (remaining data in the buffer)
```suggestion
        // Advertise data is appended separately (remaining data in the buffer).
```

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/RyuLdn/INetworkClient.cs
> +    interface INetworkClient : IDisposable
There's no need for an empty line separating each function on the interface IMO. I usually add a separation to group related functions, but separating everything like this is not necessary.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/RyuLdn/Types/CreateAccessPointPrivateRequest.cs
> +        // Advertise data is appended separately. (remaining data in the buffer)
Same comment as before.

2023-09-11 18:52 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/Station.cs
> +        public ResultCode ConnectPrivate(SecurityConfig securityConfig, SecurityParameter securityParameter, UserConfig userConfig, uint localCommunicationVersion, uint optionUnknown, NetworkConfig n
Can you break the parameters into multiple line? This is too long as is.

2023-09-11 19:12 UTC, TSRBerry commented on Directory.Packages.props
> +    <PackageVersion Include="NetCoreServer" Version="3.0.12" />
Ah whoops, we don't need it for this one just yet I just forgot to remove that.

2023-09-11 19:27 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                 || controlProperty.LocalCommunicationId[6] == localCommunicationIdChecked) | (controlProperty.LocalCommunicationId[7] == localCommunicationIdChecked);
I have no clue, but I'm pretty sure it's supposed to be like the others.

2023-09-11 19:33 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                            throw new NotSupportedException();
@AcK77 I have no clue about this, do you remember why you did it this way?

2023-09-11 19:40 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            _station?.Dispose();
@AcK77 could you check what the real sysmodule does here? (Same for `AccessPoint` below)

2023-09-11 19:42 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            _station?.Dispose();
The function does the same thing that is done here, so I don't think it makes any difference in this case. Calling the function just saves one line of code and reduces code duplication.

2023-09-11 19:46 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                    if (System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable())
We have a class `NetworkInterface` in the `Ryujinx.HLE.HOS.Services.Ldn` namespace, so we need to be explicit here.

2023-09-11 20:05 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +            _station?.Dispose();
Ah yeah, I looked at the CmifCommand `CloseStation` instead of the private method.

2023-09-11 20:13 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/RyuLdn/Types/CreateAccessPointPrivateRequest.cs
> +    /// </remarks>>
```suggestion
    /// </remarks>
```

2023-09-12 12:59 UTC, gdkchan approved these changes
lgtm minus pending comments, thanks. Worth noting that I didn't test the implementation.

2023-09-12 13:00 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                    if (System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable())
Should we look for another solution or do we leave this as is?

2023-09-12 13:04 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                    if (System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable())
Leave it as is, unless there is a good reason to change the name of LDN `NetworkInterface` class.

2023-09-14 00:54 UTC, AcK77 requested changes

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/LdnNetworkInfo.cs
> +        public byte Unknown1;
```suggestion
        public byte Reserved1;
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/LdnNetworkInfo.cs
> +        public ushort Reserved1;
```suggestion
        public ushort Reserved2;
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/LdnNetworkInfo.cs
> +        public ushort Reserved2;
```suggestion
        public ushort Reserved3;
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/LdnNetworkInfo.cs
> +        public Array140<byte> Unknown2;
```suggestion
        public Array140<byte> Reserved4;
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/NodeLatestUpdateFlags.cs
> +        Disconnect = 1 << 1
```suggestion
        Disconnect = 1 << 1,
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/ScanFilterFlag.cs
> +        All = NetworkType | IntentId | SessionId | MacAddress | Ssid
```suggestion
        All = NetworkType | IntentId | SessionId | MacAddress | Ssid,
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/ScanFilterFlag.cs
> +    enum ScanFilterFlag : byte
```suggestion
    [Flags]
    enum ScanFilterFlag : byte
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/SecurityMode.cs
> +        Debug
```suggestion
        Debug,
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/UserConfig.cs
> +        public Array15<byte> Unknown1;
```suggestion
        public Array15<byte> Reserved;
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/AccessPoint.cs
> +                NetworkConfig = networkConfig
```suggestion
                NetworkConfig = networkConfig,
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                Reserved2 = new Array10<byte>()
```suggestion
                Reserved2 = new Array10<byte>(),
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                            throw new NotSupportedException();
It's something which isn't supported in the original service. There is currently only 2 `ScanFilterFlag` available `MacAddress` and `Ssid`.

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
> +                        _nifmResultCode = resultCode;
```suggestion
                        _nifmResultCode = resultCode;
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/RyuLdn/Types/NetworkError.cs
> +        Unknown = -1
```suggestion
        Unknown = -1,
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/Station.cs
> +                NetworkInfo = networkInfo
```suggestion
                NetworkInfo = networkInfo,
```

2023-09-14 00:54 UTC, AcK77 commented on src/Ryujinx.Ui.Common/Configuration/ConfigurationState.cs
> +            // configurationFileFormat.Version == 13 -> LDN1
Maybe we could add a comment which say `configurationFileFormat.Version == 13/19 were used for old LDN builds` to keep the information somewhere.

2023-09-24 02:14 UTC, AcK77 approved these changes
Just one last comment.
(It’s a bit strange to get some format change in the LDN PR)

2023-09-24 02:14 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/RyuLdn/Types/NetworkError.cs
> +    struct NetworkErrorMessage
Could be nice to get that in a separated file

2023-09-25 21:19 UTC, marysaka approved these changes

2023-09-25 21:50 UTC, merged