Add ldn_mitm as a network client for LDN
Ryujinx/Ryujinx pull request #5656
Opened 2023-09-05 19:33 UTC by TSRBerry

This PR is part of our ongoing effort to upstream our LDN implementation (#4716).

As with my last LDN PR I tried to preserve the commit history as well as I could! But for this one there are a few more things that happened outside of git, which I want to preserve as well in some way!

With that out of the way, you can read the original PR description (which was written when I first contributed this to a private Ryujinx repo) below!

---

Depends on #5652

---

This PR contains LDN settings for Avalonia and the port of [ldn_mitm](https://github.com/spacemeowx2/ldn_mitm) to Ryujinx.

Thanks to @spacemeowx2 for encouraging me to finish this project and giving me permission to port ldn_mitm to Ryujinx (before the public license exemption for Ryujinx and yuzu was in place).

I tried to port the code from ldn_mitm as closely as possible, so it should be pretty easy to compare as well.

By supporting ldn_mitm the following local multiplayer scenarios are now possible:
- AMS switch using ldn_mitm <-> Ryujinx (on the same network)
- Ryujinx <-> Ryujinx (on the same network)
- ldn_mitm <-> proxy/lan-play server <-> Ryujinx
- Ryujinx <-> proxy/lan-play server <-> Ryujinx

My development repo (which is kept up-to-date with master) can be found here: [TSRBerry/Ryujinx-Spacemeowx2-Ldn](https://github.com/TSRBerry/Ryujinx-Spacemeowx2-Ldn)

---

I started developing this for LDN 2.3 originally, but after 2.4 came out I merged my changes into the new version and finished my implementation there. So my changes have been sitting around for quite a while and might need some more cleanup.

Although I tested the following scenarios before and confirmed these all work I'll test them again this weekend just to be sure:
- Ryujinx as the host:
  - 4 player Mario Kart 8: Deluxe (same network)
  - 2 player Animal Crossing: New Horizons (same network)
- Switch as the host:
  - 2 player Mario Kart 8: Deluxe (same network)
  - 2 player Animal Crossing: New Horizons (same network)

---

Some fun things I want to add:

- I initially [asked](https://discord.com/channels/410208534861447168/747613951709151233/806549817459081287) if RyuLdn would work with ldn_mitm, without understanding anything about it just yet.
- [This comment](https://discord.com/channels/410208534861447168/747613951709151233/806550465146781726) by riperiperi would later motivate me to actually work on this project.
- I finally got ldn_mitm for Ryujinx working just before I posted this [message](https://discord.com/channels/410208534861447168/410432399500115968/926832006204100618).

2023-09-05 22:16 UTC, Niwu34 commented
Tested The following games:
- Mario Kart 8 Deluxe
- Pokemon Violet/scarlet (Playing together & trading)
- Mario Party Superstars
- Super Mario 3D world

A stable and good wlan connection is required but everything works as expected!
Great job :)

Here are some screenshots:
![IMG_8863](https://github.com/Ryujinx/Ryujinx/assets/67392333/b1a9f0d3-88ab-4484-b066-4248fd2b7b7f)
![IMG_8865](https://github.com/Ryujinx/Ryujinx/assets/67392333/4d707f33-b920-4bb6-8524-09d248b43fb0)
![IMG_8873](https://github.com/Ryujinx/Ryujinx/assets/67392333/1ca3751f-4912-4f6d-b2df-02aa8e0f0a16)
![IMG_8874](https://github.com/Ryujinx/Ryujinx/assets/67392333/478c706a-9fe4-470c-a5ad-bcaeb061ef40)

2023-09-25 23:03 UTC, AcK77 requested changes
Awesome to see that finally released!
The works done here is amazing!
Really nice job!

2023-09-25 23:03 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/LdnMitm/Proxy/ILdnTcpSocket.cs
> +
```suggestion
```

2023-09-25 23:07 UTC, TSRBerry commented on distribution/legal/THIRDPARTY.md
> +</details>
> They are permitted, each at their individual discretion, to instead license any source code authored for the ldn_mitm project as either GPLv2 or later or the [MIT license](https://github.com/Atmosphere-NX/Atmosphere/blob/master/docs/licensing_exemptions/MIT_LICENSE).

We don't really need to do this I know, but I thought it would be a nice gesture.
I'm fine with removing it from `THIRDPARTY.md` as long as we keep the credits in the `README.md`.

2023-09-25 23:12 UTC, AcK77 commented on distribution/legal/THIRDPARTY.md
> +</details>
The quoted text means we can relicense the code under our own GPLv2 or MIT license, not change the license of the original project in our license file (`THIRDPARTY.md`).
But sure, I agree to the fact we have to keep the credit in the `README.md` ;)

2023-09-27 16:31 UTC, TSRBerry commented on distribution/legal/THIRDPARTY.md
> +</details>
I misunderstood that sentence whoops. I'll push the change!

2023-09-27 16:38 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/Types/LdnNetworkInfo.cs
> +using Ryujinx.Common.Memory;
All these files were encoded using `UTF-8-BOM` instead of `UTF-8` and I fixed that somewhere in here.

2023-09-27 16:42 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/LdnMitm/LanProtocol.cs
> +        public const int RxBufferSizeMax = 0x2000;
What do you mean? The public ones are used for the proxy clients/servers and the private one only needs to be used in here.

2023-09-27 16:44 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
>  using System;
These are only valid for ldn_mitm they are not actually constant for the real LDN sysmodule.

2023-09-27 16:54 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/LdnMitm/LanProtocol.cs
> +        public const int RxBufferSizeMax = 0x2000;
It could be nice to sort them by `public` and `private` then

2023-09-27 16:56 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Ldn/UserServiceCreator/IUserLocalCommunicationService.cs
>  using System;
I speak about the LDN sysmodule, the class still contains some hardcoded values.
But that could be done later as I don't want to block the PR.

2023-09-27 16:58 UTC, AcK77 approved these changes

2023-10-24 22:50 UTC, marysaka approved these changes

2023-10-25 22:22 UTC, TSRBerry commented
This is ready to merge now. I'm still investigating the issues with Taiko, but I'm in the middle of moving currently and since I only make progress very slowly I guess it's better to fix it afterwards.

That also means I won't need to keep this branch up to date anymore and should probably finish the proxy sockets next.

2023-10-25 22:32 UTC, merged