Fix: Improve loose file mod time
Ryujinx/Ryujinx pull request #5672
Opened 2023-09-11 08:43 UTC by hYdos

This PR updates the Loose file mod logic to handle mods in a more similar way to hardware by grabbing file "Metadata" at startup and then opening files as needed later on.

Closes #5661 

https://github.com/Ryujinx/Ryujinx/assets/25501603/bc3f3d3d-7835-4acf-b033-18ed7b41e2d7

![image](https://github.com/Ryujinx/Ryujinx/assets/25501603/42d01dbe-3efa-444a-83cd-a2657c36fb81)

Here is the original (its still counting but it works out to around 10 minutes I'm just not patient as you should be able to tell by this PR)
![image](https://github.com/Ryujinx/Ryujinx/assets/25501603/4040efe1-3230-48c3-8b6f-95c32e6649f9)

2023-09-11 13:23 UTC, TSRBerry commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +            private readonly UniqueRef<IFile> _fileReference;
Could you fix the warnings here?

2023-09-11 14:01 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                         .AsParallel()
Indentation is a bit off here.

2023-09-12 05:13 UTC, hYdos commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +            private string FilePath { get; }
ah my bad i should of looked closer into this

2023-09-12 06:59 UTC, hYdos commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +            private readonly UniqueRef<IFile> _fileReference;
should be all good just waiting for the action's to run to verify

2023-09-12 13:01 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +
Double empty line.

2023-09-13 11:22 UTC, hYdos commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +
fixing this broke the whitespace check

2023-09-13 14:02 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +
The line is probably not empty I guess? You can fix it automatically by running `dotnet format whitespace`. I think you can also use the Format Document option within VS if you use that.

2023-09-13 21:17 UTC, hYdos commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +
Ah yea you were right Rider indented it for some reason

2023-09-14 17:43 UTC, marysaka approved these changes

2023-09-26 00:10 UTC, AcK77 requested changes
Just a suggestion but why don't modify `AddFiles` method to add a bool argument `isLooseFile` and then do the right things in the `foreach` ? `AsParallel()` doesn't work in both cases ?
Maybe that could reduce the duplicated code and do everything cleaner.
I'm not a huge fan of getting `LazyFsFile` included in `ModLoader` class too. (But idk where we could store it...)

2023-09-26 00:10 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                return _fileReference.Get!.Read(out bytesRead, offset, destination);
```suggestion

                return _fileReference.Get!.Read(out bytesRead, offset, destination);
```

2023-09-26 00:10 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                return new Result(0);
```suggestion

                return new Result(0);
```

2023-09-26 00:10 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +
```suggestion
```

2023-09-26 00:10 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                    builder.AddFile(entry.FullPath, file);
```suggestion
                    builder.AddFile(entry.FullPath, new LazyFsFile(entry.FullPath, rootPath, fs));
```

2023-09-26 00:10 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/ModLoader.cs
> +                throw new NotImplementedException();
Maybe this could be replaced by `NotSupportedException` ?
(Same for other class methods)

2024-01-26 02:27 UTC, AcK77 commented
Superseeded by #6180

2024-01-26 02:27 UTC, closed without merging