Stub NGC service
Ryujinx/Ryujinx pull request #5681
Opened 2023-09-14 06:42 UTC by gdkchan

As the title says. Baten Kaitos Remaster requires this, the game only connects to the service, but doesn't actually call any of its functions (at least as far as I have tested).

With this change, it can go in-game without enabling ignore missing services.
![image](https://github.com/Ryujinx/Ryujinx/assets/5624669/20c022aa-656b-4515-b07f-4cfd763769f6)

Closes #5678.

2023-09-15 11:31 UTC, Illynir commented
**STAR OCEAN THE SECOND STORY R** Demo Seems to need this too. The game boots but when you start a new game the game makes an "exception error stopping point".

The demo works flawlessly with Ignore missing service or this PR.

2023-09-25 21:45 UTC, AcK77 requested changes
Some nits here and there, but otherwise it's an awesome work as usual!

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/HorizonFsClient.cs
> +    class HorizonFsClient : IFsClient
Maybe add a TODO comment since content manager have to be done through `Horizon` project, then the property `_system` will not needed anymore, so `_system.LibHacHorizonManager.FsClient.Fs` could be passed in the constructor argument, and then the whole class could be moved in `Horizon` project ?

(I hope I don't have wrong here)

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/HorizonFsClient.cs
> +            return result.ToHorizonResult();
```suggestion

            return result.ToHorizonResult();
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/HorizonFsClient.cs
> +            return Result.Success;
```suggestion

            return Result.Success;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Ngc/NgcMain.cs
> +            // TODO: Notification thread, requires implementing OpenSystemDataUpdateEventNotifier on FS.
Maybe you could explain a bit what's the notification thread does, because if it will be implemented later, we could forgot :)

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/AhoCorasick.cs
> +                            Debug.Assert(storageOffset + 1 == wordLength);
```suggestion

                            Debug.Assert(storageOffset + 1 == wordLength);
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/AhoCorasick.cs
> +                                sb.AppendLine(multiWord);
```suggestion

                                sb.AppendLine(multiWord);
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/BinaryReader.cs
> +            return false;
```suggestion

            return false;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/BinaryReader.cs
> +                return true;
```suggestion

                return true;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/BinaryReader.cs
> +            return ReadArray(array);
```suggestion

            return ReadArray(array);
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/BinaryReader.cs
> +                return byteLength / Unsafe.SizeOf<T>();
```suggestion

                return byteLength / Unsafe.SizeOf<T>();
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/BinaryReader.cs
> +                _offset += byteLength;
```suggestion

                _offset += byteLength;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/CompressedArray.cs
> +                reader.AllocateAndReadArray(ref _bitfieldRanges, bitfieldRangesCount) != bitfieldRangesCount)
I'd put that on one line.

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/CompressedArray.cs
> +                reader.AllocateAndReadArray(ref _bitfields, bitfieldsCount) != bitfieldsCount)
I'd put that on one line.

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ContentsReader.cs
> +                        return result;
```suggestion
                        return NgcResult.InvalidSize;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ContentsReader.cs
> +            return Result.Success;
```suggestion

            return Result.Success;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ContentsReader.cs
> +            return Result.Success;
```suggestion

            return Result.Success;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ContentsReader.cs
> +            gZipStream.CopyTo(output);
```suggestion

            gZipStream.CopyTo(output);

```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/MatchRangeList.cs
> +                Array.Resize(ref _ranges, newCapacity);
```suggestion
                Array.Resize(ref _ranges, newCapacity);

```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/MatchRangeList.cs
> +                        output.Add(prevStartOffset, prevEndOffset);
```suggestion
                        output.Add(prevStartOffset, prevEndOffset);

```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/MatchRangeList.cs
> +                    (currRange.StartOffset == startOffset && currRange.EndOffset < endOffset))
```suggestion
                if (currRange.StartOffset < startOffset || (currRange.StartOffset == startOffset && currRange.EndOffset < endOffset))
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/MatchRangeListState.cs
> +            return true;
```suggestion

            return true;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilter.cs
> +            return Result.Success;
```suggestion

            return Result.Success;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilter.cs
> +                return Result.Success;
```suggestion

                return Result.Success;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilter.cs
> +            return true;
```suggestion

            return true;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilter.cs
> +            return true;
```suggestion

            return true;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilter.cs
> +            return true;
```suggestion

            return true;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilter.cs
> +            text.Slice(matchStartOffset, matchLength).CopyTo(delimitedText.Slice(delimitedTextOffset, matchLength));
```suggestion
            text.Slice(matchStartOffset, matchLength).CopyTo(delimitedText.Slice(delimitedTextOffset, matchLength));

```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilter.cs
> +            text.Slice(matchStartOffset, matchLength).CopyTo(delimitedText.Slice(delimitedTextOffset, matchLength));
```suggestion
            text.Slice(matchStartOffset, matchLength).CopyTo(delimitedText.Slice(delimitedTextOffset, matchLength));

```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilterBase.cs
> +                character == '_';
```suggestion
            return char.IsAsciiLetterOrDigit((char)character) || character == '-' || character == '.' || character == '_';
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilterBase.cs
> +                            input.Slice(index, separator.Length).SequenceEqual(separator))
```suggestion
                        if (index + separator.Length < input.Length && input.Slice(index, separator.Length).SequenceEqual(separator))
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilterBase.cs
> +                            map.Set.TurnOn(index, separator.Length);
```suggestion
                            map.Set.TurnOn(index, separator.Length);

```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilterBase.cs
> +                    text.Slice(offset - separator.Length, separator.Length).SequenceEqual(separator))
```suggestion
                if (offset >= separator.Length && text.Slice(offset - separator.Length, separator.Length).SequenceEqual(separator))
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilterBase.cs
> +            return false;
```suggestion

            return false;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/SparseSet.cs
> +            return plainIndex != 0 && Select1Ex(plainIndex - 1) == index;
```suggestion

            return plainIndex != 0 && Select1Ex(plainIndex - 1) == index;
```

2023-09-25 21:45 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/Utf8Text.cs
> +                return Utf8ParseResult.InvalidCharacter;
```suggestion

                return Utf8ParseResult.InvalidCharacter;
```

2023-09-25 22:19 UTC, gdkchan commented on src/Ryujinx.HLE/HOS/HorizonFsClient.cs
> +    class HorizonFsClient : IFsClient
I'm not sure if I get this. The reason this class needs to exist is because Libhac does not implement `MountSystemData`. I'm not sure if it will be implemented on Libhac in the future, or if we will need to implement it ourselves. It seems that Libhac also does not implement `OpenDataStorageByDataId` (which we would end up calling on `MountSystemData`). I'm not sure if that is something that will be implemented on Libhac in the future either, or we will need to implement it ourselves. Also I guess that this function will need to call NCM, but it is something to be concerned about when FS is implemented on Horizon project.

2023-09-25 22:22 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/HorizonFsClient.cs
> +    class HorizonFsClient : IFsClient
Then it's fine to leave things as-is and discuss about everything when FS will be implemented on Horizon project.

2023-09-25 22:24 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/CompressedArray.cs
> +                reader.AllocateAndReadArray(ref _bitfieldRanges, bitfieldRangesCount) != bitfieldRangesCount)
This line is already 145 characters long. If I put in a single line it will be almost 200 characters long, and impossible to read without scrolling horizontally.

2023-09-25 22:25 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/CompressedArray.cs
> +                reader.AllocateAndReadArray(ref _bitfields, bitfieldsCount) != bitfieldsCount)
More or less the same comment as above.

2023-09-25 22:26 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/CompressedArray.cs
> +                reader.AllocateAndReadArray(ref _bitfieldRanges, bitfieldRangesCount) != bitfieldRangesCount)
I have no issue to read it with a single line on a 1920x1080 screen... But for what it cost, you can leave things like that.

2023-09-25 22:27 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/MatchRangeList.cs
> +                    (currRange.StartOffset == startOffset && currRange.EndOffset < endOffset))
If I put it on a single line, it will be too long. As a general rule, I don't like letting any line be longer than 120 characters, because then it requires scrolling horizontally to be fully readable.

2023-09-25 22:30 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Ngc/Detail/ProfanityFilterBase.cs
> +                            input.Slice(index, separator.Length).SequenceEqual(separator))
Line will be too long if I change that.

2023-09-27 16:55 UTC, marysaka approved these changes

2023-09-27 17:21 UTC, merged

2023-09-27 19:29 UTC, GamerzHell9137 commented
> **STAR OCEAN THE SECOND STORY R** Demo Seems to need this too. The game boots but when you start a new game the game makes an "exception error stopping point".
> 
> The demo works flawlessly with Ignore missing service or this PR.

Where does it trigger the ```ngc:u is not implemented``` ?