Ava UI: Better Controller Applet
Ryujinx/Ryujinx pull request #5756
Opened 2023-10-02 13:46 UTC by IsaacMarovitz

2023-10-24 22:45 UTC, AcK77 approved these changes
I’m not a huge fan of the popup design as discussed on discord, but I can live with it like that…
Other than my comments, that lgtm!

2023-10-24 22:45 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Applet/AvaHostUiHandler.cs
> +
```suggestion
```

2023-10-24 22:45 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +            InitializeComponent();
```suggestion

            InitializeComponent();
```

2023-10-24 22:45 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +            InitializeComponent();
```suggestion

            InitializeComponent();
```

2023-10-24 22:45 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +
```suggestion
```

2023-10-24 22:45 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +
```suggestion
```

2023-10-24 22:45 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +        private static SvgImage GetResource(string path)
Maybe that should be moved somewhere else to avoid duplicated code in future.

2023-12-12 01:13 UTC, AcK77 commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +        private static SvgImage GetResource(string path)
Only this comment left, is it possible to do something about my suggestion?

2023-12-18 16:09 UTC, TSRBerry requested changes
Looks quite nice!
However the window issues should be fixed before I approve this.
I'd also like the embedded resources be moved to Ava, but if other developers are fine with it this way, that's also okay for me.

2023-12-29 22:04 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +            }
We use this same design pattern in other places in Ava see `SwkbdAppletDialog.axaml.cs`

2023-12-29 22:12 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Applet/AvaHostUiHandler.cs
> +                var response = await ControllerAppletDialog.ShowControllerAppletDialog(args, _parent);
This doesn't happen to me on macOS. I've pushed a commit to try and remedy it.

2023-12-30 01:48 UTC, TSRBerry commented
Unfortunately I can only review this in about 2 weeks again, since I'm currently not home. Sorry!

2024-01-12 20:46 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Applet/AvaHostUiHandler.cs
> +                var response = await ControllerAppletDialog.ShowControllerAppletDialog(args, _parent);
It sadly still does that, I'll look into that.

2024-01-12 23:34 UTC, TSRBerry requested changes
Lgtm mostly!
During my last test I found one bug though: If you try to close Ryujinx while the controller applet is open Ryujinx will just hang until you close the dialog separately. After that it continues closing normally.

Could you fix that so Ryujinx closes without having to manually close the dialog as well?

2024-01-12 23:34 UTC, TSRBerry commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> -  "DialogControllerAppletDockModeSet": "Docked mode set. Handheld is also invalid.\n\n",
Since you are changing these, could you remove the strings for other languages? The translations need to be adjusted again before we can show them to users. Iirc we fall back to English for strings that don't exist for other languages?

2024-01-12 23:34 UTC, TSRBerry commented on src/Ryujinx.Ava/UI/Applet/ControllerAppletDialog.axaml.cs
> +            ((ContentDialog)Parent).Hide();
Could you change this to a conditional access or if this will always be a `ContentDialog` suppress the NRE warning by adding a `!` here?

2024-01-13 00:04 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> -  "DialogControllerAppletDockModeSet": "Docked mode set. Handheld is also invalid.\n\n",
Crowdin will purge removed strings from other language files automatically.

2024-01-13 00:06 UTC, TSRBerry commented on src/Ryujinx.Ava/Assets/Locales/en_US.json
> -  "DialogControllerAppletDockModeSet": "Docked mode set. Handheld is also invalid.\n\n",
Oh awesome, thanks for checking!

2024-01-13 00:18 UTC, TSRBerry approved these changes
Lgtm, thank you!

I'll create an issue about the closing bug affecting `AvaHostUiHandler` as discussed on Discord.

2024-01-13 00:41 UTC, merged