Ava UI: Input Menu Refactor
Ryujinx/Ryujinx pull request #5826
Opened 2023-10-21 13:32 UTC by IsaacMarovitz

**Changes:**
- Removes all remaining ReflectionBindings from Avalonia 🎉 
- Localised Keys (finally!)
- Added platform-specific keys (Win key will show as Cmd on Mac etc...)
- Destroyed and simultaneously created some crimes against humanity 

![image](https://github.com/Ryujinx/Ryujinx/assets/42140194/8de41f60-4215-4ad4-98ab-3447d9f94fe0)
![image](https://github.com/Ryujinx/Ryujinx/assets/42140194/6bc937a5-1d90-4113-ab06-66d7ebc2d3f8)

2023-10-21 14:41 UTC, gdkchan commented
This issue is likely caused by this change too: https://github.com/Ryujinx/Ryujinx/issues/5828
Should be checked before merging.

2023-10-21 14:50 UTC, MarcosLH1504 commented
Sorry, when I make a diagonal it doesn't do it until 1 second later. Can you tell me what I have to do? thank you

2023-10-21 14:50 UTC, MarcosLH1504 commented
https://github.com/Ryujinx/Ryujinx/issues/5828

2024-01-25 18:13 UTC, Littl3Guy commented
Launching a game with motion controls enabled causes ryujinx to crash.
[Ryujinx_1.1.0+6d386ff_2024-01-25_13-09-58.log](https://github.com/Ryujinx/Ryujinx/files/14056436/Ryujinx_1.1.0%2B6d386ff_2024-01-25_13-09-58.log)

2024-02-23 22:57 UTC, IsaacMarovitz commented
> Launching a game with motion controls enabled causes ryujinx to crash. 

Fixed

2024-02-24 01:05 UTC, TSRBerry reviewed
This looks fine to me, but I want to test this as well before I approve.
Too tired to do that properly now, so I'll try that tomorrow.

2024-03-17 02:05 UTC, AcK77 requested changes

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                    ButtonZl = ButtonZl
```suggestion
                    ButtonZl = ButtonZl,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                    ButtonZr = ButtonZr
```suggestion
                    ButtonZr = ButtonZr,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                    StickButton = LeftStickButton
```suggestion
                    StickButton = LeftStickButton,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                    StickButton = RightStickButton
```suggestion
                    StickButton = RightStickButton,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                    StrongRumble = StrongRumble
```suggestion
                    StrongRumble = StrongRumble,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                TriggerThreshold = TriggerThreshold
```suggestion
                TriggerThreshold = TriggerThreshold,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                    MirrorInput = MirrorInput
```suggestion
                    MirrorInput = MirrorInput,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/ControllerInputConfig.cs
> +                    Sensitivity = Sensitivity
```suggestion
                    Sensitivity = Sensitivity,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/HotkeysConfig.cs
> +                VolumeDown = VolumeDown
```suggestion
                VolumeDown = VolumeDown,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/KeyboardInputConfig.cs
> +                    ButtonSr = LeftButtonSr
```suggestion
                    ButtonSr = LeftButtonSr,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/KeyboardInputConfig.cs
> +                    ButtonZr = ButtonZr
```suggestion
                    ButtonZr = ButtonZr,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/KeyboardInputConfig.cs
> +                    StickButton = LeftStickButton
```suggestion
                    StickButton = LeftStickButton,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/KeyboardInputConfig.cs
> +                    StickButton = RightStickButton
```suggestion
                    StickButton = RightStickButton,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Models/Input/KeyboardInputConfig.cs
> +                Version = InputConfig.CurrentVersion
```suggestion
                Version = InputConfig.CurrentVersion,
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/ViewModels/Input/InputViewModel.cs
> -
Do not remove the extra empty line

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Views/Input/KeyboardInputView.axaml.cs
> +                        this.Focus(NavigationMethod.Pointer);
```suggestion
                        Focus(NavigationMethod.Pointer);
```

2024-03-17 02:05 UTC, AcK77 commented on src/Ryujinx/UI/Views/Settings/SettingsHotkeysView.axaml.cs
> +            }
```suggestion
            }

```

2024-03-23 23:00 UTC, TSRBerry requested changes
Mostly commented on some naming issues.

I also tested it a bit and found some issues:
- The save dialog binds to the wrong window
  ![image](https://github.com/Ryujinx/Ryujinx/assets/20988865/9a17e04c-bba2-406a-b965-3b399e782a73)
- Switching between players is now painfully slow
- Connecting a controller while the input settings are open, switches the selected controller to `Disabled`. If you want to switch it automatically switch to the new  controller.
- You can't configure controllers for multiple players. It only saves the configuration for the currently selected one.

2024-03-25 17:11 UTC, IsaacMarovitz commented on src/Ryujinx/Assets/Styles/Styles.xaml
> +                                    <CheckBox Margin="0" />
The controls in the style XAMLs are purely for testing purposes. This checkbox doesn't actually need to be hooked up to anything, i.e. an unnecessary ReflectionBinding

2024-03-25 18:16 UTC, IsaacMarovitz commented
> - Switching between players is now painfully slow

I was not able to recreate that on my machine.

> - Connecting a controller while the input settings are open, switches the selected controller to Disabled. If you want to switch it automatically switch to the new controller.
> - You can't configure controllers for multiple players. It only saves the configuration for the currently selected one.

I believe these are issues on master and not from this PR.

2024-03-26 08:31 UTC, pincetgore commented
I tested this PR vs Master and didn't notice any difference speedwise

2024-04-05 16:25 UTC, gdkchan commented on src/Ryujinx/UI/Helpers/KeyValueConverter.cs
> +                            symbol = OperatingSystem.IsMacOS() ? "⌃ " : "Ctrl ";
Why are those not part of the locale as well? You could add a "MacOS" suffix to the key for the macOS variants.

2024-04-05 16:25 UTC, gdkchan commented on src/Ryujinx/UI/ViewModels/Input/ControllerInputViewModel.cs
> +        public InputViewModel parentModel;
Is that supposed to be `private`? If so, it should be renamed to `_parentModel`, otherwise it should be `ParentModel`. If it does need to be public, I'd at least recommend changing it to a get-only property to prevent the instance from being changed by accident externally. If it's private, I think it could be `readonly`.

2024-04-05 16:25 UTC, gdkchan commented on src/Ryujinx/UI/ViewModels/Input/KeyboardInputViewModel.cs
> +        public InputViewModel parentModel;
Same comment as above.

2024-04-05 16:25 UTC, gdkchan commented on src/Ryujinx/UI/Views/Input/ControllerInputView.axaml.cs
> +            assigner = new GamepadButtonAssigner((DataContext as ControllerInputViewModel).parentModel.SelectedGamepad, ((DataContext as ControllerInputViewModel).parentModel.Config as StandardContro
Line is too long.

2024-04-05 16:25 UTC, gdkchan commented on src/Ryujinx/UI/Views/Input/KeyboardInputView.axaml.cs
> +                                switch (button.Name)
I assume we can't use an enum here instead of a string? Using strings for this is fragile since if the string is changed, the code breaks.

2024-04-05 16:25 UTC, gdkchan commented on src/Ryujinx/UI/Views/Settings/SettingsHotkeysView.axaml.cs
> +
Double line break.

2024-04-05 16:25 UTC, gdkchan commented on src/Ryujinx/UI/Views/Settings/SettingsHotkeysView.axaml.cs
> +            if (_currentAssigner != null && _currentAssigner.ToggledButton != null && !_currentAssigner.ToggledButton.IsPointerOver)
```suggestion
            if (!_currentAssigner?.ToggledButton?.IsPointerOver ?? false)
```
I do wonder if all those can really be null.

2024-04-05 17:17 UTC, IsaacMarovitz commented on src/Ryujinx/UI/Views/Input/KeyboardInputView.axaml.cs
> +                                switch (button.Name)
Afaik there's no easier and safer way to do this, maybe emmaus can come up with something

2024-04-05 21:55 UTC, gdkchan approved these changes
lgtm, thanks.

2024-04-09 08:19 UTC, TSRBerry requested changes
Lgtm, I have a few small questions and committed some naming changes that might even be unrelated to your PR.

2024-04-15 21:12 UTC, gdkchan commented
Needs a rebase now.

2024-04-15 21:13 UTC, gdkchan commented on src/Ryujinx/Assets/Locales/en_US.json
> +  "KeyMacWinRight": "⌘ Right",
I think it's better this way, translator have the freedom to move the symbol somewhere else if needed.

2024-04-16 21:31 UTC, TSRBerry approved these changes
Lgtm!

2024-04-17 21:52 UTC, merged