Improve indication of emulation being paused by the User
Ryujinx/Ryujinx pull request #5836
Opened 2023-10-22 18:05 UTC by gnisman

Improve indication of emulation being paused by adding Paused to application title bar and log to console and log file.

Closes #5334

2023-10-22 18:09 UTC, MutantAura commented on src/Ryujinx.Ava/AppHost.cs
> +            _viewModel.Title = _viewModel.Title.Replace("(Paused)", string.Empty);
`Paused` should be localised and called through the Locale Manager.

2023-11-05 11:39 UTC, marysaka requested changes
Only that comment, but otherwise seems fine to me :+1:

2023-11-05 11:39 UTC, marysaka commented on src/Ryujinx.Ava/AppHost.cs
> +            _viewModel.Title = _viewModel.Title.Replace($"({LocaleManager.Instance[LocaleKeys.Paused]})", string.Empty);
I would prefer that you backup the old title somewhere and restore it instead of replacing (as that could just replace a word on the actual game title with bad luck)

2023-11-05 11:39 UTC, marysaka commented on src/Ryujinx/Ui/MainWindow.cs
> +            Title = Title.Replace("(Paused)", string.Empty);
Same comment as for Avalonia

2023-11-11 14:59 UTC, marysaka approved these changes

2023-11-11 15:12 UTC, gdkchan reviewed
I think having a helper method that can assemble the full window title (including or not the "(Paused)" indicator) would be better than appending it at the end of the title (and would eliminate the need for the `_titleBackup`.

2023-11-11 15:12 UTC, gdkchan commented on src/Ryujinx.Ava/AppHost.cs
> +            _viewModel.Title += $"({LocaleManager.Instance[LocaleKeys.Paused]})";
```suggestion
            _viewModel.Title += $" ({LocaleManager.Instance[LocaleKeys.Paused]})";
```

2023-11-11 15:12 UTC, gdkchan commented on src/Ryujinx/Ui/MainWindow.cs
> +            Title += "(Paused)";
```suggestion
            Title += " (Paused)";
```

2023-11-11 21:22 UTC, gdkchan approved these changes
lgtm, thanks.

2023-11-28 10:57 UTC, gnisman commented
@marysaka can you please review again? Thanks

2023-12-04 16:52 UTC, marysaka approved these changes

2023-12-04 16:52 UTC, merged