Desktop shortcut fixes
Ryujinx/Ryujinx pull request #5852
Opened 2023-10-27 10:16 UTC by NitroTears

This pull request aims to fix current issues with the Create Shortcut functionality, specifically this will close #5839 #5827.
This will also add the `--fullscreen` arg to the shortcuts so by default launching games with shortcuts automatically open Ryujinx in fullscreen mode.

I will need some testing with the MacOS issue (#5827), as I do not currently have a Mac to test with myself. Perhaps @nickoanastassiu could help with this?

2023-10-27 10:57 UTC, TSRBerry requested changes
Sorry we missed this before. Lgtm except for the comments!

2023-10-27 10:57 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            argsList.Add($"--fullscreen");
```suggestion
```

I prefer using Ryujinx settings instead of overriding them for shortcuts

2023-10-27 10:57 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
> +            var argsList = new List<string>();
How do you want to launch Ryujinx without adding the path to the binary?
```suggestion
            var argsList = new List<string>
            {
                basePath,
            };
```

2023-10-27 11:03 UTC, TSRBerry commented
Fixes #5827

2023-10-27 12:17 UTC, nickoanastassiu commented
Does not fix #5827. Here's a before and after of the runner.sh file:

#### Before
`/Applications/Ryujinx.app/Contents/MacOS/Ryujinx.Ava "{Path to game file}"`
#### After
`"{Path to game file}" --fullscreen`

Removing the executable path does not fix it (the shell cannot simply open the file, it needs the executable to open it with and then the game path as an argument, just like on other platforms). The problem is that the name of the executable isn't `Ryujinx.Ava` but just `Ryujinx` (see attachment):
<img width="377" alt="Screenshot 2023-10-27 at 15 10 37" src="https://github.com/Ryujinx/Ryujinx/assets/134955950/e9035252-560b-4f30-9dcc-da41e031a16a">

This issue can be resolved by removing the `.Ava` part of the executable's name from the script. As a last resort although it's probably not recommended I guess the executable's name could just be hardcoded.

2023-10-27 12:49 UTC, TSRBerry commented
See my review comments.

2023-10-27 13:59 UTC, nickoanastassiu commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
>              string contentFolderPath = Path.Combine(desktopPath, cleanedAppName + ".app", "Contents");
The changes proposed by TSRBerry close #5827.

I would also suggest putting the shortcut in the Applications folder on macOS.
```suggestion
            string contentFolderPath = Path.Combine("/Applications", cleanedAppName + ".app", "Contents");
```

2023-10-27 15:34 UTC, TSRBerry commented on src/Ryujinx.Ui.Common/Helper/ShortcutHelper.cs
>              string contentFolderPath = Path.Combine(desktopPath, cleanedAppName + ".app", "Contents");
@marysaka is this desired?

2023-10-27 20:13 UTC, NitroTears commented
From what I can see here, I think we might need to move the logic in `GetArgsString` into the individual platform functions since it seems we might need different logic per platform. 

> Removing the executable path does not fix it (the shell cannot simply open the file, it needs the executable to open it with and then the game path as an argument, just like on other platforms).

To me this seems to conflict with the suggested fix at the top of the description in #5839. That is what I implemented, and while it seems it might OK for windows, not so much for mac. Let me know what you think.

2023-10-28 11:50 UTC, TSRBerry commented
@NitroTears how does this look for you?

2023-10-28 19:07 UTC, gdkchan commented
I didn't review the original PR so commenting now, there should be a separation on the context menu since the "Create Desktop Shortcut" option is not related to the cache management options before it.
![image](https://github.com/Ryujinx/Ryujinx/assets/5624669/983d6860-93d8-4e09-9c8c-9f2100083891)

2023-10-28 19:12 UTC, nickoanastassiu commented
Perhaps it would be smarter to bundle it in the first section?

<img width="268" alt="Screenshot 2023-10-28 at 22 11 28" src="https://github.com/Ryujinx/Ryujinx/assets/134955950/19172904-387d-4e68-98b7-05208c994596">

2023-10-28 19:14 UTC, gdkchan commented
Yea that would be better, although I guess it doesn't exist on GTK.

2023-10-29 08:23 UTC, NitroTears commented
I'll combine what @gdkchan and @nickoanastassiu said and move the create shortcut button to the top section (and create a seperator for it to be at the top in GTK, if that is alright). I'll also:

- Make the application folder the default shortcut location on Mac
- Add the changes by @TSRBerry 
- remove `--fullscreen` arg again until I know a definitive yay or nah for having in by default.

2023-10-29 09:45 UTC, NitroTears commented
I realise @TSRBerry did most of that already in a commit lol. So it's good to review / have a look at again now. Testing on Mac would be much appreciated.

2023-10-29 09:46 UTC, nickoanastassiu commented
I already tried this exact change on my machine locally yesterday, it should work.

2023-11-05 11:30 UTC, marysaka approved these changes

2023-11-06 20:29 UTC, NitroTears commented
Excellent, Thank you!

2023-11-11 15:08 UTC, marysaka commented
Forcing merge as all comments were addressed appropriately.

2023-11-11 15:08 UTC, merged