Use driver name instead of vendor name in the status bar for Vulkan.
Ryujinx/Ryujinx pull request #6146
Opened 2024-01-18 01:55 UTC by etkramer

This PR handles #3682 by displaying the more specific driver name in the status bar rather than only the device vendor. OpenGL has no such API, so there we just continue to display the vendor name.

In many cases such as Windows/NV the name displayed for the vendor and the driver are the same. Seeking testers on Linux to confirm.

2024-01-20 12:36 UTC, marysaka requested changes

2024-01-20 12:36 UTC, marysaka commented on src/Ryujinx.Graphics.Vulkan/VulkanPhysicalDevice.cs
> +            PhysicalDeviceVulkan12Properties physicalDeviceVulkan12Properties = new() // We need this to retrive driver-related details.
I would prefer this be queried with ``VK_KHR_driver_properties`` extension instead and follow back to the old behavior otherwise.

I have plans to make Ryujinx compatible with Vulkan 1.1 + extensions

2024-01-20 19:02 UTC, etkramer commented on src/Ryujinx.Graphics.Vulkan/VulkanPhysicalDevice.cs
> +            PhysicalDeviceVulkan12Properties physicalDeviceVulkan12Properties = new() // We need this to retrive driver-related details.
Should be resolved now

2024-01-22 21:17 UTC, marysaka approved these changes

2024-01-25 19:22 UTC, MutantAura commented
I'd agree it's worth preferring vendor name on macOS as the driver name won't give the information that this change gives on other platforms, in fact it does the exact opposite.

2024-01-25 23:19 UTC, AcK77 requested changes

2024-01-25 23:19 UTC, AcK77 commented on src/Ryujinx.Graphics.Vulkan/VulkanPhysicalDevice.cs
> +            return true;
```suggestion

            return true;
```

2024-01-25 23:19 UTC, AcK77 commented on src/Ryujinx.Graphics.Vulkan/VulkanPhysicalDevice.cs
> +                return false;
```suggestion

                return false;
```

2024-01-25 23:33 UTC, gdkchan approved these changes
lgtm, thanks.

2024-01-25 23:46 UTC, AcK77 approved these changes

2024-01-26 00:07 UTC, merged

2024-01-26 17:07 UTC, IsaacMarovitz commented
macOS issue was not addressed prior to merging...