Migrate friends service to new IPC
Ryujinx/Ryujinx pull request #6174
Opened 2024-01-25 19:01 UTC by gdkchan

This migrates the friends service to the new IPC system. The implementation should be the same (assuming I did not forget anything). Most functions are stubbed, we can't emulate it (at least not right now) since it requires information from the Nintendo Account (which might need a connection to their servers). In any case, unlike the previous implementation, now all commands that the service expose are either stubbed or implemented (the previous one was missing a bunch of them).

Closes #1575, closes #3769.
Allow the games linked on the above issues to run with ignore missing services disabled.

Testing is welcome.

2024-01-25 22:51 UTC, AcK77 requested changes
Some structs have no size, which maybe could lead to a crash?
Some structs are named "...Impl" as example: `BlockedUserImpl` which are used in `GetBlockedUserList` IPC, so appropriate name could be `BlockedUserItem`.

Other than that and my comments, rest looks good to me!

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/FriendsServicePermissionLevel.cs
>          SystemMask = 8,
```suggestion
        ViewerMask = 3,
        ManagerMask = 7,
        SystemMask = 9,
```

![image](https://github.com/Ryujinx/Ryujinx/assets/4905390/5cde6697-cb92-4188-b886-7145bba5d5fd)

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Friends/FriendsIpcServer.cs
> +        private const int MaxDomainObjects = 16; // TODO: Figure out the correct values.
```suggestion
        private const int MaxDomainObjects = 16;
```

Checked by RE

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Friends/FriendsIpcServer.cs
> +        private const int PointerBufferSize = 0x800; // TODO: Figure out the correct values.
```suggestion
        private const int PointerBufferSize = 0xA00;
```
Checked by RE

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Friends/FriendsIpcServer.cs
> +        private const int MaxDomains = 64; // TODO: Figure out the correct values.
```suggestion
        private const int MaxDomains = 64;
```
Checked by RE

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Friends/FriendsIpcServer.cs
> +        private const int MaxSessionsCount = 32;
```suggestion
        private const int MaxSessionsCount = 8;
```
Checked by RE

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/ApplicationInfo.cs
> +    }
It's 2 ulong, first one is `ApplicationId` and second one seems to be `PresenceGroupId`

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/IDaemonSuspendSessionService.cs
> +    }
```suggestion
    {
        // NOTE: This service has no commands.
    }
```

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/DaemonSuspendSessionService.cs
> +    }
```suggestion
    {
        // NOTE: This service has no commands.
    }
```

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/INotificationService.cs
> +        Result Pop(out SizedNotificationInfo info);
```suggestion
        Result Pop(out SizedNotificationInfo sizedNotificationInfo);
```

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/NotificationService.cs
> +        public Result Pop(out SizedNotificationInfo info)
```suggestion
        public Result Pop(out SizedNotificationInfo sizedNotificationInfo)
```

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/ServiceCreator.cs
> +        [CmifCommand(1)] // 2.0.0+
```suggestion
        [CmifCommand(1)]
```

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/ServiceCreator.cs
> +        [CmifCommand(2)] // 4.0.0+
```suggestion
        [CmifCommand(2)]
```

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/SizedFriendFilter.cs
> +                $"PresenceGroupId: {PresenceGroupId} }}";
Are the `{{ ... }}` really needed?

2024-01-25 22:51 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/UserPresenceImpl.cs
> +            return $"{{ UserId: {UserId}, LastTimeOnlineTimestamp: {LastTimeOnlineTimestamp}, Status: {Status} }}";
Are the `{{ ... }}` really needed?

2024-01-25 23:00 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/FriendsServicePermissionLevel.cs
>          SystemMask = 8,
The actual values are below:
```cs
        Admin = -1,
        User = UserMask,
        Viewer = UserMask | ViewerMask,
        Manager = UserMask | ViewerMask | ManagerMask,
        System = UserMask | SystemMask,
```
so User = 1, Viewer = 1 | 2 = 3, Manager = 1 | 2 | 4 = 7 and System is 1 | 8 = 9. So it should be already correct.

2024-01-25 23:01 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/FriendsServicePermissionLevel.cs
>          SystemMask = 8,
Oh yeah my bad I didn't see them sorry ^^'

2024-01-25 23:06 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/ServiceCreator.cs
> +        [CmifCommand(1)] // 2.0.0+
We are not documenting the fw version where functions were added anymore? Doesn't matter too much for me but I assumed it was still being done.

2024-01-25 23:08 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/SizedFriendFilter.cs
> +                $"PresenceGroupId: {PresenceGroupId} }}";
I just copied what is done on `UserPresenceImpl` which was existing code. It can be useful to indicate those are values inside of a struct on the log.

2024-01-25 23:09 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/ServiceCreator.cs
> +        [CmifCommand(1)] // 2.0.0+
I thought we removed it, but they are still present in Prepo so it's fine to keep them then. But maybe all services needs to be checked on that.

2024-01-25 23:10 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/UserPresenceImpl.cs
> +            return $"{{ UserId: {UserId}, LastTimeOnlineTimestamp: {LastTimeOnlineTimestamp}, Status: {Status} }}";
I copied from https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.HLE/HOS/Services/Friend/ServiceCreator/FriendService/Types/UserPresence.cs#L31 and removed the `UserPresence` part, that is redundant. I can remove the { } but I think it will look a bit weird on the log when its mixed with the other function parameters.

2024-01-25 23:11 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Friends/Detail/Ipc/ServiceCreator.cs
> +        [CmifCommand(1)] // 2.0.0+
The comments above the function with the signature were removed (since they become redundant with new IPC), but fw version was kept IIRC.

2024-01-26 01:42 UTC, AcK77 requested changes
Some settings struct like `LanguageCode` are supposed to be a enum casted ulong instead of a struct, but that should be fine for now.

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/Factory/AccelerometerOffset.cs
> +    }
```suggestion
    struct AccelerometerOffset
    {
        public ushort X;
        public ushort Y;
        public ushort Z;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/Factory/AccelerometerScale.cs
> +    }
```suggestion
    struct AccelerometerScale
    {
        public ushort X;
        public ushort Y;
        public ushort Z;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/Factory/ConsoleSixAxisSensorHorizontalOffset.cs
> +    }
```suggestion
    {
        public ushort X;
        public ushort Y;
        public ushort Z;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/Factory/GyroscopeOffset.cs
> +    }
```suggestion
    {
        public ushort X;
        public ushort Y;
        public ushort Z;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/Factory/GyroscopeScale.cs
> +    }
```suggestion
    {
        public ushort X;
        public ushort Y;
        public ushort Z;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/Factory/SpeakerParameter.cs
> +    }
```suggestion
    {
        public ushort Version;
        public Array34<byte> Reserved;
        public ushort SpeakerHpf2A1;
        public ushort SpeakerHpf2A2;
        public ushort SpeakerHpf2H0;
        public ushort SpeakerEqInputVolume;
        public ushort SpeakerEqOutputVolume;
        public ushort SpeakerEqCtrl1;
        public ushort SpeakerEqCtrl2;
        public ushort SpeakerDrcAgcCtrl2;
        public ushort SpeakerDrcAgcCtrl3;
        public ushort SpeakerDrcAgcCtrl1;
        public ushort SpeakerAnalogVolume;
        public ushort HeadphoneAnalogVolume;
        public ushort SpeakerDigitalVolumeMin;
        public ushort SpeakerDigitalVolumeMax;
        public ushort HeadphoneDigitalVolumeMin;
        public ushort HeadphoneDigitalVolumeMax;
        public ushort MicFixedGain;
        public ushort MicVariableVolumeMin;
        public ushort MicVariableVolumeMax;
        public Array16<byte> Reserved;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/AccountNotificationSettings.cs
> +    }
```suggestion
    {
        public Uid UserId;
        public uint Flags;
        public byte FriendPresenceOverlayPermission;
        public byte FriendInvitationOverlayPermission;
        public ushort Reserved;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/AllowedSslHost.cs
> +    struct AllowedSslHost
Size is 0x100

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/AppletLaunchFlag.cs
> +    struct AppletLaunchFlag
It's a u32 bitmask

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/BluetoothDevicesSettings.cs
> +    }
```suggestion
    {
        public Array6<byte> BdAddr;
        public Array32<byte> DeviceName;
        public Array3<byte> ClassOfDevice;
        public Array16<byte> LinkKey;
        public bool LinkKeyPresent;
        public ushort Version;
        public uint TrustedServices;
        public ushort Vid;
        public ushort Pid;
        public byte SubClass;
        public byte AttributeMask;
        public ushort DescriptorLength;
        public Array128<byte> Descriptor;
        public byte KeyType;
        public byte DeviceType;
        public ushort BrrSize;
        public Array9<byte> Brr;
        public Array299<byte> Reserved;
    }
```
Size is 0x200

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/ButtonConfigRegisteredSettings.cs
> +    struct ButtonConfigRegisteredSettings
This is a 0x5C8-byte struct

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/ButtonConfigSettings.cs
> +    struct ButtonConfigSettings
This is a 0x5A8-byte struct

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/DataDeletionSettings.cs
> +    }
```suggestion
    {
        public uint Flags;
        public uint UseCount;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/HomeMenuScheme.cs
> +    }
```suggestion
    {
        public uint Main;
        public uint Back;
        public uint Sub;
        public uint Bezel;
        public uint Extra;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/InitialLaunchSettings.cs
> +    }
```suggestion
    {
        public uint Flags;
        public uint Reserved;
        public ulong TimeStamp1;
        public ulong TimeStamp2;
        public ulong TimeStamp3;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NotificationSettings.cs
> +    }
```suggestion
    {
        public uint Flag;
        public float Volume;
        public ulong HeadTime;
        public ulong TailTime;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NxControllerLegacySettings.cs
> +    struct NxControllerLegacySettings
This is a 0x29-byte struct

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NxControllerSettings.cs
> +    struct NxControllerSettings
This is a 0x42C-byte struct

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/PtmFuelGaugeParameter.cs
> +    }
```suggestion
    {
        public ushort Rcomp0;
        public ushort TempCo;
        public ushort FullCap;
        public ushort FullCapNom;
        public ushort IavgEmpty;
        public ushort QrTable00;
        public ushort QrTable10;
        public ushort QrTable20;
        public ushort QrTable30;
        public ushort Reserved;
        public uint Cycles;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/ServiceDiscoveryControlSettings.cs
> +    struct ServiceDiscoveryControlSettings
u32 bitflag here where 0 = `IsChangeEnvironmentIdentifierDisabled`

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/SleepSettings.cs
> +    }
```suggestion
    {
        public uint Flags;
        public uint HandheldSleepPlan;
        public uint ConsoleSleepPlan;
    }
```

2024-01-26 01:42 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/TvSettings.cs
> +    }
```suggestion
    {
        public uint Flags;
        public uint TvResolution;
        public uint HdmiContentType;
        public uint RgbRange;
        public uint CmuMode;
        public uint TvUnderscan;
        public uint TvGamma;
        public uint ContrastRatio;
    }
```

2024-01-26 19:28 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Settings/System/BluetoothDevicesSettings.cs
> +    }
I had to split `public Array299<byte> Reserved;` in two since there is no `Array299` type. I could also just remove it and set a explicit size.

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/LanguageCode.cs
> +    }
```suggestion
    [StructLayout(LayoutKind.Sequential, Size = 0x8, Pack = 0x1)]
    public struct LanguageCode
    {
        public Array8<byte> Value;

        private string[] GetList()
        {
            return new string[]
            {
                "ja",
                "en-US",
                "fr",
                "de",
                "it",
                "es",
                "zh-CN",
                "ko",
                "nl",
                "pt",
                "ru",
                "zh-TW",
                "en-GB",
                "fr-CA",
                "es-419",
                "zh-Hans",
                "zh-Hant",
                "pt-BR"
            };
        }

        public bool IsValid()
        {
            return GetList().Contains(Value.AsSpan().ToStringNullTerminated());
        }

        public LanguageCode(string strCode)
        {
            long code = 0;
            int shift = 0;

            foreach (char chr in strCode)
            {
                code |= (long)(byte)chr << shift++ * 8;
            }

            BitConverter.GetBytes(code).AsSpan().CopyTo(Value.AsSpan());
        }

        public LanguageCode(Language index)
        {
            if ((uint)index >= GetList().Length)
            {
                throw new ArgumentOutOfRangeException(nameof(index));
            }

            this = new LanguageCode(GetList()[(int)index]);
        }
    }
```

Part of some old WIP code

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/DeviceNickName.cs
> +    }
```suggestion
    [StructLayout(LayoutKind.Sequential, Size = 0x80)]
    public struct DeviceNickName
    {
        public ByteArray128 Value;

        public DeviceNickName(string value)
        {
            byte[] buffer = Encoding.ASCII.GetBytes(value);

            Array.Resize(ref buffer, 0x80);

            if (buffer.Length > 0x80)
            {
                buffer[0x80] = 0;
            }
            else
            {
                buffer[value.Length] = 0;
            }

            buffer.AsSpan().CopyTo(Value.AsSpan());
        }
    }
```

Part of some old WIP code

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/BacklightSettings.cs
> +    }
```suggestion
    [StructLayout(LayoutKind.Sequential, Size = 0x28, Pack = 0x4)]
    struct BacklightSettings
    {
        // TODO: Determine field names.
        public uint Unknown0x00;
        public float Unknown0x04;

        // 1st group
        public float Unknown0x08;
        public float Unknown0x0C;
        public float Unknown0x10;

        // 2nd group
        public float Unknown0x14;
        public float Unknown0x18;
        public float Unknown0x1C;

        public float Unknown0x20;
        public float Unknown0x24;
    }
```

Part of some old WIP code

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/DataDeletionSettings.cs
> +        public uint Flags;
```
    enum DataDeletionFlag : uint
    {
        AutomaticDeletionFlag = 1 << 0,
    }
```

Part of some old WIP code

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NotificationSettings.cs
> +        public uint Flag;
```
    enum NotificationFlag : uint
    {
        RingtoneFlag           = 1 << 0,
        DownloadCompletionFlag = 1 << 1,
        EnablesNews            = 1 << 8,
        IncomingLampFlag       = 1 << 9,
    }
```

Part of some old WIP code

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NotificationSettings.cs
> +        public float Volume;
```suggestion
        public uint Volume;
```

```
    enum NotificationVolume : uint
    {
        Mute,
        Low,
        High,
    }
```

Part of some old WIP code

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NotificationSettings.cs
> +        public ulong TailTime;
```suggestion
        public ulong HeadTime; // uint Hour - uint Minute
        public ulong TailTime; // uint Hour - uint Minute
```

Idk if it's useful

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/SleepSettings.cs
> +        public uint Flags;
```
    enum SleepFlag : uint
    {
        SleepsWhilePlayingMedia = 1 << 0,
        WakesAtPowerStateChange = 1 << 1,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/SleepSettings.cs
> +        public uint HandheldSleepPlan;
```
    enum HandheldSleepPlan : uint
    {
        At1Min,
        At3Min,
        At5Min,
        At10Min,
        At30Min,
        Never,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/SleepSettings.cs
> +        public uint ConsoleSleepPlan;
```
    enum ConsoleSleepPlan : uint
    {
        At1Hour,
        At2Hour,
        At3Hour,
        At6Hour,
        At12Hour,
        Never,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/TvSettings.cs
> +        public uint Flags;
```
    enum TvFlag : uint
    {
        Allows4k             = 1 << 0,
        Allows3d             = 1 << 1,
        AllowsCec            = 1 << 2,
        PreventsScreenBurnIn = 1 << 3,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/TvSettings.cs
> +        public uint TvResolution;
```
    enum TvResolution : uint
    {
        Auto,
        At1080p,
        At720p,
        At480p,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/TvSettings.cs
> +        public uint HdmiContentType;
```
    enum HdmiContentType : uint
    {
        None,
        Graphics,
        Cinema,
        Photo,
        Game,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/TvSettings.cs
> +        public uint RgbRange;
```
    enum RgbRange : uint
    {
        Auto,
        Full,
        Limited,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/TvSettings.cs
> +        public uint CmuMode;
```
    enum CmuMode : uint
    {
        None,
        ColorInvert,
        HighContrast,
        GrayScale,
    }
```

2024-01-27 00:59 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/TvSettings.cs
> +        public uint ContrastRatio;
```suggestion
        public float TvUnderscan;
        public float TvGamma;
        public float ContrastRatio;
```

2024-01-27 01:41 UTC, AcK77 approved these changes
Lgtm!

2024-01-27 01:41 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Settings/LanguageCode.cs
> +    }
Did not add the `public LanguageCode(Language index)` constructor since the `Language` type does not exist on `Ryujinx.Horizon` yet. The other functionality was added.

2024-01-27 01:57 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/LanguageCode.cs
> +    }
```
    public enum Language : uint
    {
        Japanese,
        AmericanEnglish,
        French,
        German,
        Italian,
        Spanish,
        Chinese,
        Korean,
        Dutch,
        Portuguese,
        Russian,
        Taiwanese,
        BritishEnglish,
        CanadianFrench,
        LatinAmericanSpanish,
        SimplifiedChinese,
        TraditionalChinese,
        BrazilianPortuguese,

        Min = Japanese,
        Max = BrazilianPortuguese,
    }
    
```

2024-01-27 01:58 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NotificationSettings.cs
> +        public ulong TailTime;
Or maybe
```
public uint HeadTimeHour;
public uint HeadTimeMinute;
public uint TailTimeHour;
public uint TailTimeMinute;
```
That should do it for now ;)

2024-01-27 04:38 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Settings/System/NotificationSettings.cs
> +        public ulong TailTime;
Added a `NotificationTime` struct.

2024-01-27 04:43 UTC, benderscruffy commented
Pinball FX3 table "Medieval Madness" still crashes out

2024-01-27 04:44 UTC, gdkchan commented
Post the log.

2024-01-27 04:45 UTC, benderscruffy commented
[Ryujinx_1.1.0+a3e64f9_2024-01-27_12-40-10.log](https://github.com/Ryujinx/Ryujinx/files/14071081/Ryujinx_1.1.0%2Ba3e64f9_2024-01-27_12-40-10.log)

2024-01-27 04:54 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Settings/System/NotificationSettings.cs
> +        public ulong TailTime;
You should fix the warning

2024-01-29 19:07 UTC, marysaka approved these changes

2024-01-29 21:45 UTC, merged

2024-01-30 08:30 UTC, benderscruffy commented
Pinball FX3 table "Medieval Madness" still crashes out
so there is another problem with this game

2024-02-07 12:06 UTC, masaki-sti commented
@gdkchan 

It seems that userId and offset are byte-mismatched in the GetFriendList function of FriendService.cs.
I solved it by changing the Uid.cs as follows.

```diff
diff --git a/src/Ryujinx.Horizon/Sdk/Account/Uid.cs b/src/Ryujinx.Horizon/Sdk/Account/Uid.cs
index e2d20cbf..360f248b 100644
--- a/src/Ryujinx.Horizon/Sdk/Account/Uid.cs
+++ b/src/Ryujinx.Horizon/Sdk/Account/Uid.cs
@@ -5,7 +5,7 @@ using System.Runtime.InteropServices;

 namespace Ryujinx.Horizon.Sdk.Account
 {
-    [StructLayout(LayoutKind.Sequential)]
+    [StructLayout(LayoutKind.Sequential, Size = 0x8, Pack = 0x8)]
     public readonly record struct Uid
     {
         public readonly ulong High;

```

2024-02-07 12:31 UTC, gdkchan commented
`Uid` is a 16 bytes struct, so a 8 bytes size is not correct. As for the `Pack`, it might be wrong right now, maybe it is 16 bytes too.

2024-02-07 13:30 UTC, masaki-sti commented
I noticed this byte-mismatched in the following log.
My profile id is "022a5d7234e849e0a19405387687689b"

The following is a log of the original source code.
```
00:01:55.980 |S| HLE.OsThread.18 ServiceFriend GetFriendList: Stubbed. {userId: 0000000000000000022a5d7234e849e0 ; offset: 1988585627 ; filter: { PresenceStatus: None, IsFavoriteOnly: False, IsSameAppPresenceOnly: False, IsSameAppPlayedOnly: False, IsArbitraryAppPlayedOnly: False, PresenceGroupId: 0 } ; pidPlaceholder: 0 ; pid: 123}
00:01:55.981 |W| HLE.OsThread.18 KernelIpc ProcessMessageImpl: GetBlockedUserListIds returned error InsufficientPointerTransferBuffer
00:01:55.981 |W| HLE.OsThread.18 KernelIpc ProcessRequest: Request processing returned error InsufficientPointerTransferBuffer
```

If the Size and Pack is 0x8, the log is as follows.
It looks corrent.
```
00:02:39.093 |S| HLE.OsThread.18 ServiceFriend GetFriendList: Stubbed. {userId: 022a5d7234e849e0a19405387687689b ; offset: 0 ; filter: { PresenceStatus: None, IsFavoriteOnly: False, IsSameAppPresenceOnly: False, IsSameAppPlayedOnly: False, IsArbitraryAppPlayedOnly: False, PresenceGroupId: 0 } ; pidPlaceholder: 0 ; pid: 123}
00:02:45.739 |S| HLE.OsThread.18 ServiceFriend GetBlockedUserListIds: Stubbed. {userId: 022a5d7234e849e0a19405387687689b ; offset: 0}
```

If the Size and Pack is 0x10, the log is as follows.
It looks wrong.
```
00:04:35.789 |S| HLE.OsThread.18 ServiceFriend GetFriendList: Stubbed. {userId: 00000000000000000000000000000000 ; offset: 0 ; filter: { PresenceStatus: 887638496, IsFavoriteOnly: True, IsSameAppPresenceOnly: True, IsSameAppPlayedOnly: True, IsArbitraryAppPlayedOnly: True, PresenceGroupId: 11642936676724467867 } ; pidPlaceholder: 0 ; pid: 123}
00:04:35.801 |W| HLE.OsThread.18 KernelIpc ProcessMessageImpl: GetBlockedUserListIds returned error InvalidCmifRequest
00:04:35.801 |W| HLE.OsThread.18 KernelIpc ProcessRequest: Request processing returned error InvalidCmifRequest
```

I don't know how to fix correctly.

2024-02-07 13:35 UTC, gdkchan commented
I think Size is 16 bytes and Pack is 8 bytes.

2024-02-07 13:47 UTC, masaki-sti commented
I have tried above.
It is correct behavior.

```
00:02:56.927 |S| HLE.OsThread.18 ServiceFriend GetFriendList: Stubbed. {userId: 022a5d7234e849e0a19405387687689b ; offset: 0 ; filter: { PresenceStatus: None, IsFavoriteOnly: False, IsSameAppPresenceOnly: False, IsSameAppPlayedOnly: False, IsArbitraryAppPlayedOnly: False, PresenceGroupId: 0 } ; pidPlaceholder: 0 ; pid: 123}
00:03:00.645 |S| HLE.OsThread.18 ServiceFriend GetBlockedUserListIds: Stubbed. {userId: 022a5d7234e849e0a19405387687689b ; offset: 0}
```

Thank you for your support.