macOS: Stop storing user data in Documents for some users; fix symlinks
Ryujinx/Ryujinx pull request #6241
Opened 2024-02-02 01:01 UTC by jcm93

### Context

When .NET 8 was merged, there were some breaking changes to `Environment.SpecialFolder` values on macOS. One was immediately noticed, the change of `SpecialFolder.Personal` from `~/` to `~/Documents/`. This was addressed by https://github.com/Ryujinx/Ryujinx/pull/5941. Another important change was that of `SpecialFolder.ApplicationData` from `~/.config/` to `~/Library/Application Support`, correcting a longstanding discrepancy between macOS and Linux.

Now let's briefly go back in time to a commit dating from 2020 in `AppDataManager`, which got ahead of .NET, moving Mac configuration files from `~/.config/Ryujinx/` to `~/Library/Application Support/Ryujinx` to fix this discrepancy. The code block that does this is partially excerpted below:

```c#
if (OperatingSystem.IsMacOS() && Mode == LaunchMode.UserProfile)
{
    if (Path.Exists(oldConfigPath) && !IsPathSymlink(oldConfigPath) && !Path.Exists(BaseDirPath))
    {
        FileSystemUtils.MoveDirectory(oldConfigPath, BaseDirPath);
        Directory.CreateSymbolicLink(oldConfigPath, BaseDirPath);
    }
}
```

Here, on every startup, the existence of configuration files at the old config path, `~/.config/Ryujinx/`, is checked, and, if detected, they are moved to the new area, creating a symlink that links `~/.config/Ryujinx` to `~/Library/Application Support/Ryujinx` in the process.

Unfortunately, the key it used to describe the folder when checking for the existence of old configuration files was `SpecialFolder.ApplicationData`. Perhaps you can see where this is going.

When .NET 8 landed, `oldConfigPath` started evaluating to what should be *correct* directory, and the new, "correct" directory was an entirely incorrect one in `~/Documents`. The above code block, however, was still happily running, and moving all user files to the nonsensical folder `~/Documents/Library/Application Support/Ryujinx`, with a symlink being created at` ~/Library/Application Support/Ryujinx`.

Once https://github.com/Ryujinx/Ryujinx/pull/5941 was committed, Ryujinx began looking in the correct location for user data once more, and found it, but only because this directory was a symlink leading to ~/Documents.

This was actively noticed by both users and developers of Ryujinx, but was for some reason unaddressed. This is an editorial aside, but this represents a fairly large testing and process failure in my opinion. Not noticing this issue ahead of time is, of course, excusable, but noticing it and failing to fix it is less so. Because:

> [!IMPORTANT]
> Any person that updated and ran Ryujinx in the two days between 1084 and 1088 has had their saves and application data stored in this nonsensical folder ever since, vulnerable to wipes, iCloud or Dropbox shenanigans, or simply being cleaned out by a reasonable person wondering why `~/Documents/Library` exists.

### Now

This PR addresses all of the above.

* Config version is incremented, though no file format changes are made.
* The original code designed to migrate from `~/.config` to `~/Library/Application Support/` has been changed to run exactly once, on config update, and now uses a more explicit path to target the long-deprecated config path.
* On config update we will also run, exactly once, a check to see if the correct configuration directory, `~/Library/Application Support/Ryujinx`, is a symlink, and if so, we will remove it, and copy the files from the resolved path to the original path. 

### Testing

This has been tested locally on my Mac machine and verified to fix the symlink issue. It should be tested by other Mac users, especially those with the symlink resident in their Application Support folders.

There is some chance for this process to fail, if for some strange reason the Application Support directory isn't writable. However, I do not see a particularly good way around this externality. I would prefer not to run this code every time Ryujinx starts up. If this fails on a user's machine that has the symlink in their Application Support folder, they may just be stuck with it unless they manually resolve the situation. I added a log statement to `AppDataManager` to report if the user's data directory is a symlink, so that this circumstance will at least be apparent via support channels.

Please leave any feedback if anyone sees a better way to handle any aspect of this.

2024-02-05 14:47 UTC, TSRBerry commented
> this represents a fairly large testing and process failure

I completely agree with this. :/

2024-02-05 14:58 UTC, TSRBerry requested changes
Just minor changes, otherwise lgtm!

(I didn't comment on style issues, but will fix them once, you addressed my review comments if you don't mind.)

2024-02-05 14:58 UTC, TSRBerry commented on src/Ryujinx.Common/Configuration/AppDataManager.cs
> +            {
```suggestion
        [SupportedOSPlatform("macos")]
        public static void FixMacOSConfigurationFolders()
        {
```
(Make sure to remove the if statement manually and not using the suggestion here.)

2024-02-05 14:58 UTC, TSRBerry commented on src/Ryujinx.Common/Configuration/AppDataManager.cs
> +                            $"Critical error copying Ryujinx application data into the temp folder. Please manually move your application data to the correct folder.");
Could you make sure to log the exception (at least the message) for these as well?

2024-02-05 15:08 UTC, TSRBerry commented on src/Ryujinx.Common/Configuration/AppDataManager.cs
> +                Logger.Error?.Print(LogClass.Application, $"Application data directory is a symlink. This may be unintended.");
```suggestion
                Logger.Warn?.Print(LogClass.Application, $"Application data directory is a symlink. This may be unintended.");
```
Feels more like a warning than an error.

2024-02-05 16:04 UTC, jcm93 commented
Thanks, all addressed.

2024-02-05 16:13 UTC, jcm93 commented
I mentioned it over in #6238, but #6238 should be merged before this. I think the probability of the delete/copy operation failing is higher if the bundle's code signature is invalid, which it is until we stop logging inside the bundle. I am not actually sure why more Mac users are not currently having issues launching Ryujinx; so maybe it's not as big a deal as the documentation implies, but better to be cautious and fix that first.

2024-02-05 17:41 UTC, TSRBerry approved these changes
Lgtm! Just one minor thing i just noticed.

2024-02-05 17:41 UTC, TSRBerry commented on src/Ryujinx.Common/Configuration/AppDataManager.cs
> +                        $"Critical error copying Ryujinx application data into the temp folder. Please manually move your application data to the correct folder. {exception}");
Could you log which directory needs to be copied where?

2024-02-05 17:41 UTC, TSRBerry commented on src/Ryujinx.Common/Configuration/AppDataManager.cs
> +                        $"Critical error copying Ryujinx application data into the correct location. Please manually move your application data to the correct folder. {exception}");
Could you log the temp and the correct directory as well?

2024-02-05 22:28 UTC, jcm93 commented on src/Ryujinx.Common/Configuration/AppDataManager.cs
> +                        $"Critical error copying Ryujinx application data into the temp folder. Please manually move your application data to the correct folder. {exception}");
Resolving the symlink takes another try/catch, but added in new commit.

2024-02-05 22:28 UTC, jcm93 commented on src/Ryujinx.Common/Configuration/AppDataManager.cs
> +                        $"Critical error copying Ryujinx application data into the correct location. Please manually move your application data to the correct folder. {exception}");
Done.

2024-02-05 22:30 UTC, jcm93 commented
In addition to above, I also noticed that I hadn't set `configurationFileUpdated = true;` previously, whoops. Fixed.

2024-02-11 09:21 UTC, marysaka approved these changes
lgtm, just need a rebase :+1:

2024-02-11 18:04 UTC, merged