Add title of game to screenshot text
Ryujinx/Ryujinx pull request #6266
Opened 2024-02-07 20:46 UTC by Kfollen93

Regarding Issue #5553, I have implemented the title of the running application to the screenshot text.
This change has been applied to the base Ryujinx project and Ryujinx Ava project.

2024-02-07 21:39 UTC, AcK77 approved these changes

2024-02-08 00:54 UTC, TSRBerry commented
Closes #5553

2024-02-08 00:55 UTC, TSRBerry approved these changes
LGTM, thank you!

2024-02-08 00:57 UTC, TSRBerry requested changes
Ah sorry, Windows won't play nice with this. Could you make sure the application name doesn't contain any forbidden characters?

See: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

2024-02-08 01:04 UTC, gdkchan commented
This is a minor nitpick, but I find a bit weird to mix underscores and spaces in the file name. Maybe we should just replace the underscores with spaces if we are going to allow an arbitrary game name (which will most likely contain spaces). Ensuring that the file name is valid in all OS will probably be a bit tricky as well. I wonder if using the title ID would be considered good enough? It avoids those issues.

2024-02-08 01:05 UTC, TSRBerry commented
> I wonder if using the title ID would be considered good enough? It avoids those issues.

That wouldn't really be useful to anyone. People usually don't recognize games by their IDs.

2024-02-08 01:09 UTC, Kfollen93 commented
I'm working through the update right now with a reserved characters char array from what @TSRBerry linked.

2024-02-08 02:01 UTC, Kfollen93 commented
> Ah sorry, Windows won't play nice with this. Could you make sure the application name doesn't contain any forbidden characters?
> 
> See: https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions

Hey there, thanks for the info. I have added a sanitize method, which I believe follows all the checks. The reserved names section (ie. 'CON', 'PRN', etc) as well as ending a file with a space or period would (should) never occur since we always append the date. 

Please let me know if I'm overlooking anything. This is my first contribution to the project and I plan to become a frequent contributor. Thank you!

2024-02-11 00:01 UTC, marysaka approved these changes

2024-02-11 00:11 UTC, AcK77 requested changes

2024-02-11 00:11 UTC, AcK77 commented on src/Ryujinx.Ava/AppHost.cs
> +            }
```suggestion
            StringBuilder sbAppName = new(applicationName);
            HashSet<char> reservedChars = ['<', '>', ':', '"', '/', '\\', '|', '?', '*'];

            for (char c = (char)0; c <= 31; c++)
            {
                reservedChars.Add(c);
            }
```

2024-02-11 00:11 UTC, AcK77 commented on src/Ryujinx/Ui/RendererWidgetBase.cs
> +            }
```suggestion
            StringBuilder sbAppName = new(applicationName);
            HashSet<char> reservedChars = ['<', '>', ':', '"', '/', '\\', '|', '?', '*'];

            for (char c = (char)0; c <= 31; c++)
            {
                reservedChars.Add(c);
            }
```
```

2024-02-11 02:36 UTC, LDj3SNuD commented on src/Ryujinx.Ava/AppHost.cs
> +            }
maybe:
```csharp
private string SanitizeApplicationName(string applicationName)
{
    var reservedChars = new HashSet<char>(Path.GetInvalidFileNameChars());

    return String.Concat(applicationName.Select(c => reservedChars.Contains(c) ? '_' : c));
}

2024-02-11 04:29 UTC, Kfollen93 commented on src/Ryujinx/Ui/RendererWidgetBase.cs
> +            }
Updated. Thank you.

2024-02-11 04:30 UTC, Kfollen93 commented on src/Ryujinx.Ava/AppHost.cs
> +            }
Updated with suggested change from Ack.  Thank you!

2024-02-11 17:06 UTC, TSRBerry commented on src/Ryujinx.Ava/AppHost.cs
> +            }
I'd prefer the method suggested by @LDj3SNuD, it could be added to `src/Ryujinx.Common/Utilities/FileSystemUtils.cs` and be used for more than just application names in the future.

Would you mind adding it (and maybe rename it to something like `SanitizeFileName`)?

2024-02-11 18:02 UTC, Kfollen93 commented on src/Ryujinx.Ava/AppHost.cs
> +            }
Awesome, I definitely agree. Thanks @LDj3SNuD for the input. I didn't know there was a `.GetInvalidFileNameChars()`.
Changes have been made @TSRBerry.

2024-02-11 18:03 UTC, TSRBerry approved these changes
Awesome, thank you very much!

2024-02-18 00:50 UTC, Kfollen93 commented
Hi @AcK77 anything needed before PR is merged? Thank you.

2024-02-18 00:58 UTC, AcK77 reviewed
Sorry for the late answer!

2024-02-18 00:58 UTC, AcK77 commented on src/Ryujinx.Common/Utilities/FileSystemUtils.cs
> +            return string.Concat(fileName.Select(c => reservedChars.Contains(c) ? '_' : c));
```suggestion

            return string.Concat(fileName.Select(c => reservedChars.Contains(c) ? '_' : c));
```

2024-02-18 00:58 UTC, AcK77 commented on src/Ryujinx/Ui/RendererWidgetBase.cs
> +
```suggestion
```

2024-02-18 01:34 UTC, Kfollen93 commented on src/Ryujinx/Ui/RendererWidgetBase.cs
> +
Removed space.

2024-02-18 01:34 UTC, Kfollen93 commented on src/Ryujinx.Common/Utilities/FileSystemUtils.cs
> +            return string.Concat(fileName.Select(c => reservedChars.Contains(c) ? '_' : c));
Added space.

2024-02-18 01:36 UTC, Kfollen93 commented
> Sorry for the late answer!

All good! Just added your requested changes. Thank you.

2024-02-24 00:18 UTC, AcK77 approved these changes

2024-02-24 00:18 UTC, AcK77 commented
Needs a rebase

2024-02-24 16:53 UTC, Kfollen93 commented
> Needs a rebase

Rebased!  Thanks.

2024-03-06 20:40 UTC, Kfollen93 commented
@AcK77 Hey, just following up.  Thanks.

2024-03-06 20:53 UTC, jcm93 commented
Looks like you merged instead of rebased here.

2024-03-06 21:26 UTC, Kfollen93 commented
> Looks like you merged instead of rebased here.

Hey @jcm93 thanks for the input. Can you help me understand how to perform the rebase? I ran `git rebase` but I must have merged it afterwards.

2024-03-06 21:57 UTC, jcm93 commented
It looks like you have your commits mixed in with merge commits, and then somehow your commits are also added again at the end. I am not sure if you ever rebased. If the branch is properly rebased on the master branch, the only commits in this branch should be your own, as they differ from master (and those of maintainers if they committed to it).

I am not a Git brain surgeon, so I can't really tell you how to resolve this in-place.

There are many different ways to perform a rebase. Generally from a feature branch my own workflow is to just `git fetch upstream` after adding the master branch as an upstream repository, and then `git rebase upstream/master` from my branch, resolving conflicts if needed.

If I were in your position now, I would just stash my actual changes manually, completely reset this branch so it's identical to master, add them as a single commit, and force push. That is probably the simplest way to clean this up.

2024-03-06 22:36 UTC, Kfollen93 commented
@jcm93 Thanks for the details... I think I got it.

2024-03-07 05:02 UTC, Kfollen93 commented
Alright, my apologies. Had some rebasing issues. @AcK77 I think we're finally good to go. Thank you for your patience.

2024-03-07 22:49 UTC, merged