Use SkiaSharp for Avalonia in place of ImageSharp
Ryujinx/Ryujinx pull request #6269
Opened 2024-02-08 06:38 UTC by sunshineinabox

This pull request updates the Avalonia UI project to use SkiaSharp for image processing, replacing the previously used SixLabors ImageSharp library. There might be minor benefits, but the goal is no change, but reduced dependency. 

-----------------------------------------------------------------

**Testing:**
Requires testing on different platforms for screenshot capture, profile image selection.

I will open this PR as a Draft. Don't plan on adding any more functionality here feel free to use as you would like. Unsure if it's worth it to even merge SkiaSharp is technically more performant than ImageSharp, but I don't think it will make any difference at all, perceptible or measurable.

2024-02-08 13:41 UTC, IsaacMarovitz approved these changes

2024-02-08 17:58 UTC, IsaacMarovitz requested changes

2024-02-08 17:58 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/AppHost.cs
> +                            : new SKBitmap(new SKImageInfo(e.Width, e.Height, SKColorType.Rgba8888, SKAlphaType.Premul));
It might be better to move this ternary to just the format parameter since everything else in this constructor is the same.

2024-02-08 17:58 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/AppHost.cs
> +                            SaveBitmapAsPng(bitmap, path);
SaveBitmapAsPng happens on both paths, IMO it would be better here to override bitmap with flippedBitmap if necessary, and then save outside of the if statement.

2024-02-08 17:58 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/AppHost.cs
> +            using var data = image.Encode(SKEncodedImageFormat.Png, 100);
Specifying quality `100` is not necessary for this constructor

2024-02-08 17:58 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/ViewModels/UserFirmwareAvatarSelectorViewModel.cs
> +                        using (SKData data = avatarImage.Encode(SKEncodedImageFormat.Png, 100))
Redundant quality specifier

2024-02-08 17:58 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Views/User/UserFirmwareAvatarSelectorView.axaml.cs
> +                    dataJpeg.SaveTo(streamJpg);
I am not sure why we're saving it as a JPEG here; better to just stick with PNG to avoid artifacting.

2024-02-08 17:58 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Views/User/UserProfileImageSelectorView.axaml.cs
> +                using var dataJpeg = image.Encode(SKEncodedImageFormat.Jpeg, 100);
Again, it's probably better to use PNG and redundant quality.

2024-02-08 17:59 UTC, gdkchan commented on src/Ryujinx.Ava/UI/Views/User/UserProfileImageSelectorView.axaml.cs
> +                using var dataJpeg = image.Encode(SKEncodedImageFormat.Jpeg, 100);
IIRC the account service expects jpeg.

2024-02-08 18:00 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Views/User/UserProfileImageSelectorView.axaml.cs
> +                using var dataJpeg = image.Encode(SKEncodedImageFormat.Jpeg, 100);
Alr in that case Nintendo faux pas but JPEG it is 😆

2024-02-09 14:03 UTC, IsaacMarovitz approved these changes

2024-03-17 01:54 UTC, AcK77 commented
Needs a rebase

2024-03-18 06:33 UTC, amayra commented
is SkiaSharp is faster than ImageSharp ?

2024-04-10 22:10 UTC, AcK77 requested changes

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/AppHost.cs
> +                            using var canvas = new SKCanvas(bitmapToSave);
```suggestion
                            using var canvas = new SKCanvas(bitmapToSave);

```

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/AppHost.cs
> +                            canvas.DrawBitmap(bitmap, drawPosition);
```suggestion
                            canvas.DrawBitmap(bitmap, new SKPoint(e.FlipX ? -bitmap.Width : 0, e.FlipY ? -bitmap.Height : 0));
```

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/AppHost.cs
> +            data.SaveTo(stream);
```suggestion

            data.SaveTo(stream);
```

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/UI/Views/User/UserFirmwareAvatarSelectorView.axaml.cs
> +
```suggestion
```

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/UI/Views/User/UserFirmwareAvatarSelectorView.axaml.cs
> +                using (var canvas = new SKCanvas(newBitmap))
```suggestion

                using (var canvas = new SKCanvas(newBitmap))
```

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/UI/Views/User/UserProfileImageSelectorView.axaml.cs
> +                dataJpeg.SaveTo(streamJpg);
```suggestion

                dataJpeg.SaveTo(streamJpg);
```

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/UI/Windows/IconColorPicker.cs
> +            // Luminosity calculation
```
            // We don't want colors that are too dark.
            // If the color is too dark, make it brighter by reducing the range
```

Why is that removed ?

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/UI/Windows/IconColorPicker.cs
> +            return pixels;
```suggestion

            return pixels;
```

2024-04-10 22:10 UTC, AcK77 commented on src/Ryujinx/UI/Windows/IconColorPicker.cs
> +            var pixels = new SKColor[image.Width * image.Height];
```suggestion
            var pixels = new SKColor[image.Width * image.Height];

```

2024-05-14 15:00 UTC, AcK77 approved these changes

2024-05-15 13:38 UTC, AcK77 commented
Needs a rebase

2024-07-14 07:32 UTC, emmauss approved these changes

2024-07-14 08:16 UTC, merged