Update Avalonia About Window like requested in PR #6267
Ryujinx/Ryujinx pull request #6278
Opened 2024-02-08 19:21 UTC by sunshineinabox

Update about window to have Logo and "Ryujinx" in center and adjacent as requested in PR #6267.

---

Before:
<img width="601" alt="image" src="https://github.com/Ryujinx/Ryujinx/assets/11906669/1fd90580-582b-400b-b5f7-f0ab1bd79107">

After:
<img width="603" alt="image" src="https://github.com/Ryujinx/Ryujinx/assets/11906669/deeb94d0-02aa-47bb-bd27-b6d59363a383">

2024-02-08 19:58 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
> +                            TextAlignment="Left"
`TextAlignment=Start` should be used instead of Left to avoid issues in RTL

2024-02-10 11:03 UTC, marysaka approved these changes

2024-02-10 17:26 UTC, IsaacMarovitz requested changes

2024-02-10 17:26 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
> +                        Spacing="10">
Children of this StackPanel should be indented

2024-02-10 17:26 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
> +                        IsHitTestVisible="True"/>
```suggestion
                        IsHitTestVisible="True" />
```

2024-02-10 17:26 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
> +                            VerticalAlignment="Center"/>
```suggestion
                            VerticalAlignment="Center" />
```

2024-02-10 17:26 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
> +                            VerticalAlignment="Center"/>
```suggestion
                            VerticalAlignment="Center" />
```

2024-02-10 17:26 UTC, IsaacMarovitz commented on src/Ryujinx.Ava/UI/Windows/AboutWindow.axaml
> +                    </WrapPanel></StackPanel>
Indentation

2024-02-10 19:36 UTC, IsaacMarovitz approved these changes

2024-02-10 23:45 UTC, AcK77 approved these changes

2024-02-10 23:45 UTC, merged