Migrate Audio service to new IPC
Ryujinx/Ryujinx pull request #6285
Opened 2024-02-09 22:29 UTC by gdkchan

This is similar to the other IPC migrations, this time for the Audio service. It is not really expected to have any user visible improvement, except for one UI related issue.

Before this change, the volume that is set on the UI is set to the audio session. This means that any game that creates more than one session will effectively reset the volume. Another issue is that it uses the same methods to set the volume that the game uses, that means if the game sets a custom volume, it will override the one set on the UI (and vice-versa, if the user changes the volume again, it will override the one set by the game).

To fix this issue, I added a new `float Volume { get; set; }` property to the `IHardwareDeviceDriver` interface, in addition to the per-session interface. Now the backend volume is set to the driver volume multiplied by the session volume.

See below to have an idea of what this change does.

Before:

https://github.com/Ryujinx/Ryujinx/assets/5624669/a5d8f62e-877c-48d6-8022-cd4b25a72a97

After:

https://github.com/Ryujinx/Ryujinx/assets/5624669/5369ac6e-8e35-4849-a51d-311fbe9a27cb

Pay attention to the volume on the status bar at the bottom. Notice how it would keep changing back to 100% every time the game closes and creates a new session. With the fix, it keeps the volume set by the user.

It's worth noting that the volume can still reset in multi-game collections such as Super Mario 3D All-Stars, that is because it re-creates the emulation context, and with it the volume is also reset.

Testing is welcome (and important).

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Audio/Renderer/Dsp/AudioProcessor.cs
> +                _mailbox?.Dispose();
I assume that it was an oversight this was not disposed before, so added the dispose call here. It has two blocking collections which does implement `IDisposable`.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.HLE/Switch.cs
> +            AudioDeviceDriver.Volume = Math.Clamp(volume, 0f, 1f);
We could just access `AudioDeviceDriver` from the UI directly and remove those methods too. I didn't to reduce the amount of diffs.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon.Common/IExternalEvent.cs
> +    public interface IExternalEvent
This is currently required for events that are signalled from other threads. I might be able to remove it if I remove the thread static stuff from Horizon and Kernel, but it's quite a bit of work.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon.Common/Result.cs
> +        public Result(int errorCode)
Required to create a `Result` from Audio project `ResultCode` enum.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon.Generators/Hipc/HipcGenerator.cs
> +                        outParameters.Add(new OutParameter(argName, canonicalTypeName, outArgIndex++, argType));
This was wrong, but was not an issue before because out arguments usually come before everything. But it's not the case in one of the audio methods that I added, so I had to fix this. It is possible that the signature of said method is "wrong", but with this fixed the order shouldn't matter anymore.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon/Arp/ArpIpcServer.cs
> +            _sm.Dispose();
This is not really necessary since the HLE process will exit after that anyway (and close all handles etc), but I added it just because its the "right thing".

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Account/Uid.cs
> +    [StructLayout(LayoutKind.Sequential, Size = 0x10, Pack = 0x8)]
See https://github.com/Ryujinx/Ryujinx/pull/6174#issuecomment-1931910329 for the reason. Didn't want to create a separate PR just to fix that.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioIn.cs
> +            _impl.SetVolume(gain);
I think this name is wrong and should be `SetDeviceGain`. It also has methods that doesn't make sense for audio input like `GetPlayedSamplesCount`. I assume it was copied from audio output interface. Not sure if I should fix that here, it can be fixed when microphone support is implemented.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioRendererManager.cs
> +            renderer = default;
This needs to  be implemented, or the method should be removed. I don't know what this function is supposed to do though. The previous implementation did not have it, so it should be fine to remove.

2024-02-09 22:42 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioDevice.cs
> +            if (name.Length > 0)
I would guess it should return an error if the buffer size is incorrect, but the previous implementation did not care.

2024-02-11 04:01 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioRendererManager.cs
> +            renderer = default;
Implemented now, but I don't know anything that uses it (and it was not implemented before, so I don't htink any game uses it), so I couldn't test.

2024-02-16 02:15 UTC, riperiperi commented on src/Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs
> +            _outputStream.SetVolume(_driver.Volume * newVolume);
I'm not quite sure I understand, the driver calls `UpdateVolume` with the driver's new volume, so this effectively does `_outputStream.SetVolume(_driver.Volume * _driver.Volume);`?

2024-02-16 02:22 UTC, gdkchan commented on src/Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs
> +            _outputStream.SetVolume(_driver.Volume * newVolume);
It is wrong, it was supposed to multiple `_driver.Volume` with `_volume`.

2024-02-16 02:29 UTC, gdkchan commented on src/Ryujinx.Audio.Backends.SoundIo/SoundIoHardwareDeviceSession.cs
> +            _outputStream.SetVolume(_driver.Volume * newVolume);
Should be fixed now.

2024-02-17 02:25 UTC, riperiperi reviewed
New IPC is definitely a lot cleaner to look at. 😌 I've tested a few games and they seem to work fine.

2024-02-17 03:06 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Codec/Detail/IHardwareOpusDecoderManager.cs
> +        Result OpenHardwareOpusDecoder(out IHardwareOpusDecoder arg0, HardwareOpusDecoderParameterInternal arg1, int arg2, int arg3);
No, I forgot to update it.

2024-02-17 23:48 UTC, AcK77 requested changes

2024-02-17 23:48 UTC, AcK77 commented on src/Ryujinx.HLE/Switch.cs
> +            AudioDeviceDriver.Volume = Math.Clamp(volume, 0f, 1f);
It could be nice to open an issue about that once this PR will be merged!

2024-02-17 23:48 UTC, AcK77 commented on src/Ryujinx.Horizon/Audio/AudioUserIpcServer.cs
> +        private const int MaxPortsCount = 1;
`audren:u`
`audout:u`
`audin:u`
`audrec:u`
MaxSessionsCount: 30
MaxDomains: 0
MaxDomainObjects: 0
PointerBufferSize: 0xB40

`hwopus`
MaxSessionsCount: 24
MaxDomains: 8
MaxDomainObjects: 256
PointerBufferSize: 0x1000

As a side note, maybe `hwopus` should be in another IpcServer as the original service doing it!

2024-02-17 23:48 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Applet/AppletId.cs
> +    struct AppletId
Isn't an `uint` enum? (https://switchbrew.org/wiki/Applet_Manager_services#AppletId)

2024-02-17 23:48 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioIn.cs
> +            _impl.SetVolume(gain);
Maybe we should open an issue about that once this PR will be merged.

2024-02-17 23:48 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioInProtocol.cs
> +            Value[0] = value ? (byte)1 : (byte)0;
IDA RE:
```c
    strcpy(v49, "DeviceIn");
    strcpy(v48, "UacIn");
    if ( v42 )
    {
      v43 = v48;
    }
    else
    {
      v43 = v49;
    }
```

So value 0 for protocol is `UacIn` and 1 is `DeviceIn`, maybe we should use an enum here ?

2024-02-17 23:48 UTC, AcK77 commented on src/Ryujinx.Horizon/Sdk/Codec/Detail/HardwareOpusDecoder.cs
> +                    FinalRange = BinaryPrimitives.ReadUInt32BigEndian(data[sizeof(uint)..])
```suggestion
                    FinalRange = BinaryPrimitives.ReadUInt32BigEndian(data[sizeof(uint)..]),
```

2024-02-18 02:14 UTC, gdkchan commented on src/Ryujinx.Horizon/Audio/AudioUserIpcServer.cs
> +        private const int MaxPortsCount = 1;
> As a side note, maybe hwopus should be in another IpcServer as the original service doing it!

That would require support for creating separate HLE threads on services. This is not supported right now and I didn't want to add the support on this PR.

2024-02-18 15:24 UTC, gdkchan commented on src/Ryujinx.Horizon/Sdk/Audio/Detail/AudioInProtocol.cs
> +            Value[0] = value ? (byte)1 : (byte)0;
From my tests, it has to be a struct, otherwise we can't specify the size and alignment. I could put a enum inside the struct though.

2024-02-19 03:01 UTC, gdkchan commented on src/Ryujinx.Horizon/Audio/AudioUserIpcServer.cs
> +        private const int MaxPortsCount = 1;
I added a separate `Main` method for Hwopus for now. It means that Hwopus runs in a separate HLE process. When the support for creating HLE threads from a process is implemented, I will remove it.

2024-02-19 03:05 UTC, gdkchan commented
Feedback addressed, I also added stubs for `audrec` (it did exist in the old implementation, but the implementations was completely empty).
There are other services that existed in the old implementation, but are not implemented here:
- `audctl`, `auddev`: Implementation was fully empty as well, and I believe it can only be used by other services, not by applications directly. I will implement once we have support for creating threads.
- Applet/Debug variants of `audren`, `audin`, `audout`, `audout`: It can also only be accessed by other services, and was removed on firmware 11.0.0, I'm not sure if anything ever used it. Doesn't seems to be very important, but I can add back in the future if desired.

2024-02-22 02:16 UTC, AcK77 approved these changes

2024-02-22 18:48 UTC, marysaka approved these changes
Didn't saw anything obviously wrong and gave it some simple testing, thank for the work :+1:

2024-02-22 19:58 UTC, merged