Ava UI: Fix locale crash
Ryujinx/Ryujinx pull request #6385
Opened 2024-03-02 21:39 UTC by IsaacMarovitz

Fixes a crash on Ava when an invalid locale value is taken from system, or present in config.

Fixes #6382.

2024-03-02 23:37 UTC, marysaka commented on src/Ryujinx/Common/Locale/LocaleManager.cs
> +        public bool IsRTL()
Can you noot reorder function? that make the diff quite annoying to read

2024-03-02 23:39 UTC, marysaka approved these changes
otherwise lgtm

2024-03-03 16:22 UTC, riperiperi approved these changes

2024-03-08 00:00 UTC, gdkchan commented on src/Ryujinx/Common/Locale/LocaleManager.cs
> +            try
Why does it need this `try`/`catch`?

2024-03-08 00:28 UTC, IsaacMarovitz commented on src/Ryujinx/Common/Locale/LocaleManager.cs
> +            try
If the locale returned by `CultureInfo.CurrentCulture.Name` does not have a corresponding file, the function to load the JSON will error. try/catch is here to stop that from crashing us.

2024-03-08 19:26 UTC, TSRBerry commented on src/Ryujinx/Common/Locale/LocaleManager.cs
> +            try
Why aren't you checking if the file exists instead of using `try`/`catch`?

2024-03-16 19:09 UTC, AcK77 requested changes

2024-03-16 19:09 UTC, AcK77 commented on src/Ryujinx/Common/Locale/LocaleManager.cs
> +            // Save whatever we ended up with
```suggestion
            // Save whatever we ended up with.
```

2024-03-16 19:09 UTC, AcK77 commented on src/Ryujinx/Common/Locale/LocaleManager.cs
> +                ConfigurationState.Instance.ToFileFormat().SaveConfig(Program.ConfigurationPath);
```suggestion

                ConfigurationState.Instance.ToFileFormat().SaveConfig(Program.ConfigurationPath);
```

2024-03-16 19:09 UTC, AcK77 commented on src/Ryujinx/Common/Locale/LocaleManager.cs
> +                // We were unable to find file for that language code
```suggestion
                // We were unable to find file for that language code.
```

2024-03-17 01:12 UTC, AcK77 approved these changes

2024-03-17 01:27 UTC, merged