Improves some log messages and fixes a typo
Ryujinx/Ryujinx pull request #6773
Opened 2024-05-04 13:18 UTC by SamusAranX

The main goal of this commit is to improve the somewhat cryptic wording of the log message that shows up when previously specified game directories no longer exist. I removed the config file's name from the message since the **vast** majority of users do not and should never interact with that file directly.

As for the change in `ConfigurationState.cs`: I noticed floats (like the one for `AudioVolume`) got formatted with the local culture for some reason, so I made it use the invariant culture.

2024-05-14 14:00 UTC, AcK77 requested changes

2024-05-14 14:00 UTC, AcK77 commented on src/Ryujinx.UI.Common/Configuration/ConfigurationState.cs
> +            string message = string.Create(CultureInfo.InvariantCulture, $"{valueName} set to: {eventArgs.NewValue}");
```suggestion
            string message = string.Create(CultureInfo.InvariantCulture, $"{valueName} set to: {eventArgs.NewValue}");

```

2024-05-14 14:00 UTC, AcK77 commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
I think we should keep `ReleaseInformation.ConfigName` here

2024-05-14 14:58 UTC, SamusAranX commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
Any reason why it should be mentioned in this log message specifically? If the goal is to have the config file's name pop up in the log somewhere I'd suggest making that its own log message during startup.

2024-05-14 15:05 UTC, AcK77 commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
For some reason, we could use a different config file, so it's always nice to log it and know which file it is.

2024-05-14 21:41 UTC, SamusAranX commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
I had a hunch that was why the file got mentioned here, but I still believe it should be split out into a separate `Using config file "example.json"` log message. The name of the log file isn't relevant to user-specified game directories being invalid.

2024-05-15 10:09 UTC, AcK77 commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
I think there is already a log message somewhere with this information, but for what it cost, duplicate the information here could help to fix the related config file

2024-05-15 13:38 UTC, SamusAranX commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
The solution to a misconfigured game directory is deleting it from the main UI, not messing with the file directly. Giving the file name here is entirely unnecessary.

2024-05-15 13:43 UTC, TSRBerry commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
> I had a hunch that was why the file got mentioned here, but I still believe it should be split out into a separate `Using config file "example.json"` log message. The name of the log file isn't relevant to user-specified game directories being invalid.

I think using a separate message would be the best way to deal with that. You're right to say that it doesn't really belong in the message here.

Do you mind if I take care of that in this PR? I'd add a commit to add the new message.

2024-05-15 14:22 UTC, SamusAranX commented on src/Ryujinx.UI.Common/App/ApplicationLibrary.cs
> +                        Logger.Warning?.Print(LogClass.Application, $"The specified game directory \"{appDir}\" does not exist.");
Sure, go for it.

2024-05-15 15:35 UTC, TSRBerry approved these changes
Lgtm, thank you!

2024-05-15 16:10 UTC, AcK77 approved these changes

2024-05-15 16:10 UTC, merged