Replace ImageSharp with SkiaSharp everywhere
Ryujinx/Ryujinx pull request #7030
Opened 2024-07-15 10:03 UTC by emmauss

Use Skiasharp for image processing. ImageSharp is replaced because;
1. Their tendencies to change license on a whim
2. ImageSharp isn't fully AOT compatible
3. Why have 2 image processing libraries when 1 is enough.

There isn't any real performance gain of using Skiasharp. This is mainly to add Native AOT support to the Avalonia UI project.

2024-07-15 11:32 UTC, IsaacMarovitz requested changes
I'm not sure of the overall utility of doing this. GTK3 will be retired in the not-too-distant future. At that point, the only remaining dependency on SkiaSharp outside of Avalonia and helper projects would be in HLE, which could be eliminated with applet improvements.

SkiaSharp adds a native library dep, which I think we should seek to avoid unnecessarily, especially when it's used in only one place.

2024-07-15 11:32 UTC, IsaacMarovitz commented on src/Ryujinx/UI/Applet/AvaloniaDynamicTextInputHandler.cs
> +            TextChangedEvent?.Invoke(text ?? string.Empty, _hiddenTextBox.SelectionStart, _hiddenTextBox.SelectionEnd, false);
These unrelated changes should be explained in the PR description or moved to a different PR.

2024-07-15 13:29 UTC, riperiperi commented
> I'm not sure of the overall utility of doing this.
NativeAOT support.

> which could be eliminated with applet improvements.
When exactly will this happen?

2024-07-15 13:38 UTC, emmauss commented on src/Ryujinx/UI/Applet/AvaloniaDynamicTextInputHandler.cs
> +            TextChangedEvent?.Invoke(text ?? string.Empty, _hiddenTextBox.SelectionStart, _hiddenTextBox.SelectionEnd, false);
Avalonia doesn't have overwrite mode for their text boxes. So it's incorrect to always have it in overwrite mode on the applet, when we are mirroring the contents of the hidden textbox.

2024-07-15 13:58 UTC, IsaacMarovitz commented
> When exactly will this happen?

Gdk has had the code floating about for this for years.

2024-07-25 22:47 UTC, charlesroddie commented
It's premature to say that ImageSharp is not AOT-compatible without reporting or linking to an issue in the ImageSharp repo.

2024-07-26 20:01 UTC, emmauss commented
> It's premature to say that ImageSharp is not AOT-compatible without reporting or linking to an issue in the ImageSharp repo.

This class specifically is the AOT incompatible code that we hit;
https://github.com/SixLabors/ImageSharp/blob/main/src/ImageSharp/Metadata/Profiles/Exif/ExifTagDescriptionAttribute.cs
 and it's a code path you'll hit often, because loading images will load their exif info. and Native Aot will complain with a crash because the class isn't found.

2024-07-26 23:38 UTC, charlesroddie commented
So... post that in the ImageSharp repo.

2024-07-27 07:16 UTC, emmauss commented
> So... post that in the ImageSharp repo.

It still wouldn't affect anything. We are sticking to the 2.1.x versions, and unless it's a critical bug (NativeAot support isn't critical), they won't be backporting new changes to the 2.1 branch. At this point, they as devs should have had enough time to test their library with trimming and aot enabled.

2024-08-24 00:34 UTC, riperiperi commented
Something's wrong with the shortcut creation feature - the icons it generates seem to be half black.

Master:
![image](https://github.com/user-attachments/assets/45d03ced-756c-4a58-966f-ed1057222ca8)

PR:
![image](https://github.com/user-attachments/assets/46d53f59-0aba-4fe9-a22c-3144fcb4dda1)

2024-08-24 10:51 UTC, emmauss commented
> Something's wrong with the shortcut creation feature - the icons it generates seem to be half black.
> 
> Master: ![image](https://private-user-images.githubusercontent.com/6294155/361089244-c3e15f67-ce96-4017-a3aa-8c82b268ba6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTY5OTAsIm5iZiI6MTcyNDQ5NjY5MCwicGF0aCI6Ii82Mjk0MTU1LzM2MTA4OTI0NC1jM2UxNWY2Ny1jZTk2LTQwMTctYTNhYS04YzgyYjI2OGJhNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjRUMTA1MTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDIxNjE0NWQzOTU1NDhlOGQ5MGMzNDUyYWQzM2Q2Mjk0MTg2OTliNDcwYzM4MDAzZjZiZGFhNDFhNDZjZjlmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pXT32eaQpR3CO6d6bmKjuKO74Di7U1L4nDfLobk5S4Q)
> 
> PR: ![image](https://private-user-images.githubusercontent.com/6294155/361089189-46d53f59-0aba-4fe9-a22c-3144fcb4dda1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0OTY5OTAsIm5iZiI6MTcyNDQ5NjY5MCwicGF0aCI6Ii82Mjk0MTU1LzM2MTA4OTE4OS00NmQ1M2Y1OS0wYWJhLTRmZTktYTIyYy0zMTQ0ZmNiNGRkYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjRUMTA1MTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODA2MmQ4NDM0ODMxMmZkMTJlZDAxOTUwM2RkZDI1MDIwODY2NDQ1MjUyMzk2NDY5ODU3ZTU4NjUzNGMzZDdjYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aDgMyluq7kZ53GstM-AzgNpxYwkKQfxaonqUedYilME)

Should be fixed now

2024-08-24 12:30 UTC, riperiperi approved these changes
Looks fine on Windows and MacOS. I don't have any games with the inline keyboard, so I can't check if it's still working.

2024-08-24 12:30 UTC, riperiperi commented on src/Ryujinx.HLE/HOS/Services/Caps/CaptureManager.cs
> +                data.SaveTo(file);
There's a bit of a change here since this is no longer async. I'm not sure if the jpeg should be fully written before this service returns success - if it should then it was actually wrong before.

2024-08-24 12:30 UTC, riperiperi commented on src/Ryujinx.UI.Common/Helper/ShortcutHelper.cs
> +            fs.WriteByte((byte)(dataLength >> 16));
Odd how this wasn't causing an issue before, I imagine the icons were larger than 65kb.

2024-08-24 15:01 UTC, IsaacMarovitz approved these changes

2024-08-24 16:44 UTC, emmauss commented on src/Ryujinx.UI.Common/Helper/ShortcutHelper.cs
> +            fs.WriteByte((byte)(dataLength >> 16));
It may be from the quality or difference in compression between imagesharp and skia.

2024-08-31 14:32 UTC, gdkchan approved these changes
lgtm, thanks.

2024-08-31 14:32 UTC, merged