Ava UI: Extend ContentDialogHelper to work on multiple windows
Ryujinx/Ryujinx pull request #7033
Opened 2024-07-16 11:04 UTC by IsaacMarovitz

Allows `ContentDialogHelper` to work on windows other than the main window. Previously, any dialogues triggered by settings would awkwardly springboard the user back to the main window, leaving the settings window open in the background. Now, these dialogues will appear on the settings window itself.

2024-07-19 17:11 UTC, TSRBerry reviewed
I only have one comment, otherwise lgtm, thank you!

2024-07-19 17:11 UTC, TSRBerry commented on src/Ryujinx/UI/Helpers/ContentDialogHelper.cs
> +            parent.Activate();
As far as I know we only need the overlay window when the main window is the parent of the dialog, since the game renderer hides it on Linux otherwise.

Could you make sure it's only used when we need to?

2024-07-19 17:19 UTC, IsaacMarovitz commented on src/Ryujinx/UI/Helpers/ContentDialogHelper.cs
> +            parent.Activate();
Since I don't have an affected Linux machine to test this behaviour on, I'd rather not poke the bear for now.

2024-07-19 17:55 UTC, TSRBerry commented on src/Ryujinx/UI/Helpers/ContentDialogHelper.cs
> +            parent.Activate();
The previous code already had this check, so you just need to take it from there I believe.

2024-07-20 11:33 UTC, IsaacMarovitz commented on src/Ryujinx/UI/Helpers/ContentDialogHelper.cs
> +            parent.Activate();
Done

2024-07-22 08:06 UTC, emmauss approved these changes

2024-07-24 17:41 UTC, TSRBerry requested changes
While testing I noticed some issues, so I described a few situations which you can hopefully use to investigate and fix them.

2024-07-24 17:41 UTC, TSRBerry commented on src/Ryujinx/UI/Helpers/ContentDialogHelper.cs
>              }
I didn't realize this before, but there are some problems with this.

Situation 1:
- Assume you open a dialog in the settings window (`_contentDialogOverlayWindow` will be created)
- Now open another dialog in the main window (it creates a new `_contentDialogOverlayWindow` but `isTopDialog`  will be false)
- After closing the dialog in the main window, the dialog overlay window will remain
- The dialog in the settings window can't close the dialog overlay window either
- -> So there are two floating dialog overlay windows now.

Situation 2:
- Open a game and trigger an applet dialog (easiest was the controller applet for me)
- Then click on the close window button in the title bar, which opens the exit confirmation dialog behind the controller applet.
- One of them isn't interactable and you'll need to close them using ESC.
- One dialog overlay window will remain and the GUI can't be interacted with because of that. (You might be able to close it using the close window button or by pressing ESC again)

Situation 3:
- Open a game and trigger an applet dialog (easiest was the controller applet for me)
- Close the applet without changing anything and try to open the close confirmation dialog before the controller applet reappears.
- You'll notice that you might not be able to interact with one (or both) of the dialogs.
- In that case you can only close them by pressing ESC again and one of the dialog overlay windows will remain (but it might not be in the foreground)

If we want to address this we probably need to have a a dictionary which contains the parents and a stack with the dialogs for each of them?
That sounds pretty bad to me, but I couldn't come up with another solution to this problem.

Could you take another look at it and test using the three situations above?

2024-10-02 06:23 UTC, closed without merging