Ava UI: Handle updates containing non numeric characters
Ryujinx/Ryujinx pull request #7043
Opened 2024-07-17 18:12 UTC by IsaacMarovitz

Fixes #7021. I don't have Sonic Superstars, so I will need the users from this issue to double-check.

2024-07-17 19:49 UTC, lostromb commented on src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs
> +                var firstVersion = Version.Parse(firstVersionString.Where(x => char.IsDigit(x) || x != '.').ToArray());
I think a regex with capture groups would be more effective than this weird LINQ construct. `(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:\.(\d+))?` would match version strings with up to 4 numerical groups.

2024-07-17 20:14 UTC, IsaacMarovitz commented on src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs
> +                var firstVersion = Version.Parse(firstVersionString.Where(x => char.IsDigit(x) || x != '.').ToArray());
A regex would be way too expensive

2024-07-17 20:43 UTC, RupeeClock commented
Tested Win_x64 artifact build Ryujinx 1.1.0+f5b28e3 from above and fix looks correct.
Am able to add all three updates to the title without issue, including the update with the alphanumeric version number 1.0.5a
![image](https://github.com/user-attachments/assets/68dfa0b8-8bbc-4460-8bd4-01cf863b3577)

Other XCI titles with bundled updates also worked correctly, when adding other updates.

2024-07-17 22:06 UTC, lostromb commented on src/Ryujinx/UI/ViewModels/TitleUpdateViewModel.cs
> +                var firstVersion = Version.Parse(firstVersionString.Where(x => char.IsDigit(x) || x != '.').ToArray());
maybe that would a separate code fix. it also bugs me that the parsing code is duplicated twice instead of just being its own function

2024-07-18 20:24 UTC, riperiperi approved these changes
Makes sense, though I imagine the case where there is `1.1.0a` and `1.1.0b` could break this comparison.

2024-07-18 21:56 UTC, TSRBerry requested changes
This solution seems like a band-aid to me. Ignoring all characters except digits is the wrong approach for this.

Is there a reason we aren't just using string comparison for this?
It seems to work pretty well: https://dotnetfiddle.net/08WM86

2024-07-19 16:17 UTC, IsaacMarovitz commented
> This solution seems like a band-aid to me. Ignoring all characters except digits is the wrong approach for this.
> 
> Is there a reason we aren't just using string comparison for this? It seems to work pretty well: https://dotnetfiddle.net/08WM86

Your approach seems to work so I'll switch to it.

2024-07-19 16:51 UTC, TSRBerry commented
Without verifying it, I think GTK probably also did string comparison that's why I asked about it.

2024-07-19 16:53 UTC, TSRBerry submitted a review, later dismissed
Lgtm, thank you for using my suggestion!

2024-07-19 16:59 UTC, RupeeClock commented
Quickly tested artefact [ryujinx-Release-1.1.0+c36dd97-win_x64](https://nightly.link/Ryujinx/Ryujinx/actions/artifacts/1719924876.zip) and worked correctly for me.

2024-07-19 22:28 UTC, lostromb commented
Wait, if we switch to string comparison, won't that mess up sorting of versions that are longer than 1 digit long? I thought that's why we were doing `Version.Parse` so it does a proper piecewise comparison of major, minor, sub components.

Naive string comparison would result in weird orderings like this:
`1.0.0` < `1.10.0` < `1.5.1`

2024-07-20 00:03 UTC, TSRBerry commented
Yeah, it definitely doesn't work for everything (see: https://dotnetfiddle.net/5cuTTz). Thanks for noticing that!

I guess our best bet is regex then.

2024-07-20 00:04 UTC, TSRBerry requested changes
Since the string comparison doesn't work for everything, we can't use it.

We should probably switch to regex.

2024-07-20 01:36 UTC, lostromb commented
There's the new AOT way of doing regexes that I haven't learned yet but this would probably do the job, plus it'd be unit testable.
```csharp
private static readonly Regex VersionParseRegex = new Regex("(\\d+)(?:\\.(\\d+))?(?:\\.(\\d+))?(?:\\.(\\d+))?");

internal static Version ParseVersionString(string str)
{
    int major = 0;
    int minor = 0;
    int build = 0;
    int revision = 0;
    Match match = VersionParseRegex.Match(str);
    if (!match.Success)
    {
        return new Version();
    }

    major = int.Parse(match.Groups[0].Value);
    if (match.Groups[1].Success)
    {
        minor = int.Parse(match.Groups[1].Value);
        if (match.Groups[2].Success)
        {
            build = int.Parse(match.Groups[2].Value);
            if (match.Groups[3].Success)
            {
                revision = int.Parse(match.Groups[3].Value);
            }
        }
    }

    return new Version(major, minor, build, revision);
}
```

2024-07-20 01:42 UTC, gdkchan commented
Is there any constraint on the version strings? Like, can we assume they will be formatted in a specific way? If not, we should probably just some sort of string based sort with some best effort to parse the numbers there.

2024-07-20 02:15 UTC, gdkchan commented
There's a integer version number here already: https://github.com/Ryujinx/Ryujinx/blob/master/src/Ryujinx.HLE/FileSystem/ContentMetaData.cs#L20
It should probably be using that for parsing purposes. In fact, doing so is even simpler than the current change, one just needs to modify `TitleUpdateViewModel.AddUpdate` and `TitleUpdateModel` to include that version. Then the compare is as simple as comparing two integers values.

I did not test this myself though. I don't have many updates, and it seems that a regression is preventing me from adding my complete games folder since a invalid file among them is now causing the emulator to crash.

2024-07-20 11:23 UTC, IsaacMarovitz commented
> There's an integer version number here already

Nice catch, seems to work

2024-07-20 12:11 UTC, TSRBerry commented
> I did not test this myself though. I don't have many updates, and it seems that a regression is preventing me from adding my complete games folder since a invalid file among them is now causing the emulator to crash.

Just review #7046 :p

2024-07-20 19:41 UTC, gdkchan commented
Needs a rebase.

2024-07-20 19:47 UTC, gdkchan approved these changes
lgtm, thanks, but I don't have any game with non-numeric characters in the version. I did test in a game where I have many different versions here, and it appears to be working properly. It shows the latest version in the top (after "No updates"), and older versions in the bottom, but I guess that's intentional.

2024-07-20 19:50 UTC, gdkchan commented on src/Ryujinx/UI/Models/TitleUpdateModel.cs
> +                System.IO.Path.GetExtension(path)?.ToLower() == ".xci" ? LocaleKeys.TitleBundledUpdateVersionLabel : LocaleKeys.TitleUpdateVersionLabel,
Add `using System.IO;`?

2024-07-24 17:08 UTC, TSRBerry approved these changes
Lgtm!

2024-07-24 17:08 UTC, TSRBerry commented on src/Ryujinx/UI/Models/TitleUpdateModel.cs
> +                System.IO.Path.GetExtension(path)?.ToLower() == ".xci" ? LocaleKeys.TitleBundledUpdateVersionLabel : LocaleKeys.TitleUpdateVersionLabel,
If you omit the `System.IO` part it'll try to access the `Path` property.

2024-07-25 19:44 UTC, merged