hid: Stub CreateServerInterface2
Ryujinx/Ryujinx pull request #7128
Opened 2024-07-29 14:57 UTC by Tsubasa0504

Fixes #7127 

Should make games like THE NEW DENPA MEN bootable without Ignore Missing Services.

2024-08-03 10:20 UTC, AcK77 requested changes

2024-08-03 10:20 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServerInterface.cs
> +        public ResultCode CreateServerInterface2(ServiceCtx context)
I’d create a `CreatrServerInterfaceImpl` method with the IPC 0 code inside and then call this method in both IPC, it will avoid duplicated code and since we will never support that it’s fine to use the same code here.
Or at least you can `return CreateServerInterface(context);` directly in this method  too if you prefer.

2024-08-04 13:59 UTC, Tsubasa0504 commented on src/Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServerInterface.cs
> +        public ResultCode CreateServerInterface2(ServiceCtx context)
Did it with `return`, thanks

2024-08-04 17:57 UTC, AcK77 approved these changes

2024-08-04 19:18 UTC, TSRBerry approved these changes

2024-08-16 23:05 UTC, AcK77 commented on src/Ryujinx.HLE/HOS/Services/Nim/IShopServiceAccessServerInterface.cs
> +        [CommandCmif(5)] //17.0.0+
```suggestion
        [CommandCmif(5)] // 17.0.0+
```

2024-08-17 08:57 UTC, merged