Migrate to .NET 8 Collection Expressions
Ryujinx/Ryujinx pull request #7203
Opened 2024-08-14 14:04 UTC by IsaacMarovitz

This is a re-tool of part of #5928

2024-08-20 23:48 UTC, AcK77 requested changes

2024-08-20 23:48 UTC, AcK77 commented on src/ARMeilleure/Instructions/InstEmitSimdHelper.cs
> +            Intrinsic.X86Paddq
Ident is off and `,` is missing

(Same for other changes in this file)

2024-08-20 23:48 UTC, AcK77 commented on src/ARMeilleure/Translation/PTC/PtcProfiler.cs
> +            1866
`,` is missing

2024-08-20 23:48 UTC, AcK77 commented on src/ARMeilleure/Translation/Translator.cs
> +            new(2, 5)
`,` is missing

2024-08-20 23:48 UTC, AcK77 commented on src/ARMeilleure/Translation/Translator.cs
> +            new(1, 6)
`,` is missing

2024-08-20 23:48 UTC, AcK77 commented on src/Ryujinx.Audio/Backends/CompatLayer/Downmixing.cs
> +            Minus3dBInQ15
`,` is missing

2024-08-20 23:48 UTC, AcK77 commented on src/Ryujinx.Audio/Backends/CompatLayer/Downmixing.cs
> +            Minus6dBInQ15
`,` is missing

2024-08-20 23:48 UTC, AcK77 commented on src/Ryujinx.Audio/Constants.cs
> +            0.707f
`,` is missing

2024-08-20 23:48 UTC, AcK77 commented on src/Ryujinx.Audio/Renderer/Device/VirtualDevice.cs
> +            new("AudioExternalOutput", 6, true)
`,` is missing

2024-08-21 11:22 UTC, IsaacMarovitz commented on src/ARMeilleure/Instructions/InstEmitSimdHelper.cs
> +            Intrinsic.X86Paddq
I didn't bother keeping the last `,` if it didn't affect the indentation of comments. If you really want me to keep them I can add them back in.

2024-08-21 18:16 UTC, AcK77 commented on src/ARMeilleure/Instructions/InstEmitSimdHelper.cs
> +            Intrinsic.X86Paddq
That’s something we usually do in our codebase since we added auto-formatting

2024-10-02 06:23 UTC, closed without merging